### ISSUE TITLE
MFA failure with HTTP 504 (Gateway timeout 504) in Trino CLI

### ISSUE THREAD

**Issue by sajjoseph** [trinodb/trino#10018]
Trino CLI receives HTTP 504 if the user doesn't perform authentication immediately and the connection goes through a proxy. Note that the issue doesn't occur if the CLI is connecting directly to the coordinator.

Exception in CLI:
```
trino> show catalogs;
External authentication required. Please go to:
https://proxy_endpoint:port/oauth2/token/initiate/65e03b5807b324cdfb898c4a15d3bf6812dd18a5083aba0e0e890f46bd4cb556
Error running command: Request to https://proxy_endpoint:port/oauth2/token/95b728f0-9699-4dbb-8efc-5f4d79c161f9 failed: JsonResponse{statusCode=504, statusMessage=Gateway Time-out, headers={cache-control=[no-cache], content-length=[92], content-type=[text/html]}, hasValue=false} [Error: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
]
io.trino.client.ClientException: Request to https://proxy_endpoint:port/oauth2/token/95b728f0-9699-4dbb-8efc-5f4d79c161f9 failed: JsonResponse{statusCode=504, statusMessage=Gateway Time-out, headers={cache-control=[no-cache], content-length=[92], content-type=[text/html]}, hasValue=false} [Error: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
]
	at io.trino.client.auth.external.ExternalAuthentication.obtainToken(ExternalAuthentication.java:54)
	at io.trino.client.auth.external.ExternalAuthenticator.lambda$authenticate$0(ExternalAuthenticator.java:67)
	at io.trino.client.auth.external.LocalKnownToken.setupToken(LocalKnownToken.java:44)
	at io.trino.client.auth.external.ExternalAuthenticator.authenticate(ExternalAuthenticator.java:61)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.kt:223)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:108)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at io.trino.client.auth.external.ExternalAuthenticator.intercept(ExternalAuthenticator.java:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at io.trino.client.JsonResponse.execute(JsonResponse.java:130)
	at io.trino.client.StatementClientV1.<init>(StatementClientV1.java:109)
	at io.trino.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24)
	at io.trino.cli.QueryRunner.startInternalQuery(QueryRunner.java:153)
	at io.trino.cli.QueryRunner.startQuery(QueryRunner.java:139)
	at io.trino.cli.Console.process(Console.java:358)
	at io.trino.cli.Console.runConsole(Console.java:289)
	at io.trino.cli.Console.run(Console.java:191)
	at io.trino.cli.Console.call(Console.java:102)
	at io.trino.cli.Console.call(Console.java:75)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.trino.cli.Trino.main(Trino.java:42)
```
The issue can be fixed at the location mentioned below (will send the PR shortly). 

https://github.com/trinodb/trino/blob/a89d7c18af214c9f2fcbde1700266ca9e854fa10/client/trino-client/src/main/java/io/trino/client/auth/external/HttpTokenPoller.java#L138

**Comment by hashhar** [comment]
Feel free to reopen if you can still reproduce this or if you plan to resubmit the PR - https://github.com/trinodb/trino/pull/10168
