### ISSUE TITLE
Fix Phoenix tests failing on JDK 17

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#10010]
Some of the Phoenix 4 and 5 tests are failing on JDK 17

**Comment by lhofhansl** [comment]
@vincentpoon FYI.

**Comment by wendigo** [comment]
@vincentpoon if there is other solution - please let me know. I'm interested in fixing those tests, as they are the only one failing on JDK 17 right now.

**Comment by vincentpoon** [comment]
@wendigo Do you know what the problem is when starting the Testing HBase?  Do you have steps I can use to repro?

The other stacktrace you pasted is just a Warning - that is something intrinsic to HBase, which is still on older versions of the JDK, so not something we can change easily externally, but may be ignorable.

**Comment by wendigo** [comment]
@vincentpoon just switch project JDK to 17 in IntelliJ and try to run any Phoenix test.

**Comment by vincentpoon** [comment]
@wendigo The tests run fine for me with JDK 17.  There are some test failures, but might be unrelated.  But at least the TestingPhoenixServer appears to work.  I ran `TestPhoenixConnectorTest`

**Comment by wendigo** [comment]
@vincentpoon you can see failures here: https://github.com/trinodb/trino/pull/10004

**Comment by wendigo** [comment]
```
Error:  io.trino.plugin.phoenix5.TestPhoenixConnectorTest.init  Time elapsed: 20.265 s  <<< FAILURE!
java.lang.RuntimeException: Can't start phoenix server.
	at io.trino.plugin.phoenix5.TestingPhoenixServer.<init>(TestingPhoenixServer.java:106)
	at io.trino.plugin.phoenix5.TestingPhoenixServer.getInstance(TestingPhoenixServer.java:50)
	at io.trino.plugin.phoenix5.TestPhoenixConnectorTest.createQueryRunner(TestPhoenixConnectorTest.java:72)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Shutting down
	at org.apache.hadoop.hbase.MiniHBaseCluster.init(MiniHBaseCluster.java:266)
	at org.apache.hadoop.hbase.MiniHBaseCluster.<init>(MiniHBaseCluster.java:116)
	at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniHBaseCluster(HBaseTestingUtility.java:1169)
	at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniHBaseCluster(HBaseTestingUtility.java:1213)
	at io.trino.plugin.phoenix5.TestingPhoenixServer.<init>(TestingPhoenixServer.java:101)
	... 16 more
Caused by: java.lang.RuntimeException: Failed construction of Master: class org.apache.hadoop.hbase.master.HMasterKeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.hadoop.hbase.util.JVMClusterUtil.createMasterThread(JVMClusterUtil.java:137)
	at org.apache.hadoop.hbase.LocalHBaseCluster.addMaster(LocalHBaseCluster.java:227)
	at org.apache.hadoop.hbase.LocalHBaseCluster.<init>(LocalHBaseCluster.java:174)
	at org.apache.hadoop.hbase.MiniHBaseCluster.init(MiniHBaseCluster.java:245)
	... 20 more
Caused by: org.apache.hadoop.hbase.ZooKeeperConnectionException: master:376530x0, quorum=localhost:62689, baseZNode=/hbase Unexpected KeeperException creating base node
	at org.apache.hadoop.hbase.zookeeper.ZKWatcher.createBaseZNodes(ZKWatcher.java:210)
	at org.apache.hadoop.hbase.zookeeper.ZKWatcher.<init>(ZKWatcher.java:183)
	at org.apache.hadoop.hbase.zookeeper.ZKWatcher.<init>(ZKWatcher.java:135)
	at org.apache.hadoop.hbase.regionserver.HRegionServer.<init>(HRegionServer.java:652)
	at org.apache.hadoop.hbase.master.HMaster.<init>(HMaster.java:493)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.apache.hadoop.hbase.util.JVMClusterUtil.createMasterThread(JVMClusterUtil.java:132)
	... 23 more
Caused by: org.apache.phoenix.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
	at org.apache.phoenix.shaded.org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.phoenix.shaded.org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:792)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.createNonSequential(RecoverableZooKeeper.java:547)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.create(RecoverableZooKeeper.java:526)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.createWithParents(ZKUtil.java:1197)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.createWithParents(ZKUtil.java:1175)
	at org.apache.hadoop.hbase.zookeeper.ZKWatcher.createBaseZNodes(ZKWatcher.java:201)
	... 33 more

```

**Comment by wendigo** [comment]
There is also a failure in product test:

```
2021-11-23T13:15:49.6263039Z presto-master       | 2021-11-23T19:00:49.625+0545	WARN	ReadOnlyZKClient-phoenix:2181@0x79ce1b3b-SendThread(phoenix:2181)	org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn	Session 0x0 for server phoenix/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
2021-11-23T13:15:49.6266762Z presto-master       | java.lang.IllegalArgumentException: Unable to canonicalize address phoenix/<unresolved>:2181 because it's not resolvable
2021-11-23T13:15:49.6270221Z presto-master       | 	at org.apache.phoenix.shaded.org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65)
2021-11-23T13:15:49.6274969Z presto-master       | 	at org.apache.phoenix.shaded.org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41)
2021-11-23T13:15:49.6280753Z presto-master       | 	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001)
2021-11-23T13:15:49.6284663Z presto-master       | 	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
```

**Comment by wendigo** [comment]
@vincentpoon you are right. I guess that I've messed with my environment too much. There are still some weird failures in tests. Can you take a look?

**Comment by wendigo** [comment]
Product tests are failing only for phoenix5

**Comment by martint** [comment]
Any updates on this?

**Comment by wendigo** [comment]
This is related to https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8225499. More reference: https://github.com/quarkusio/quarkus/issues/8212

**Comment by wendigo** [comment]
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8232369

**Comment by electrum** [comment]
Can we fix this by converting `TestingPhoenixServer` to use Testcontainers? Then it can continue running with Java 11.

**Comment by wendigo** [comment]
@vincentpoon I've filled https://github.com/apache/phoenix/pull/1434

**Comment by findepi** [comment]
@wendigo can this be closed?

**Comment by wendigo** [comment]
@findepi No

**Comment by findepi** [comment]
Then please explain what's to be done here. "Phoenix tests failing on JDK 17" implies that CI would be red if we were running on Java 17. We are running on Java 17. What am i missing?

**Comment by vincentpoon** [comment]
The Phoenix patch above was merged, so is this just a matter of updating to that Phoenix version?

**Comment by wendigo** [comment]
@vincentpoon I've tried that but zookeeper is still failing on 17 :(

**Comment by ebyhr** [comment]
Is this issue still effective?
