### ISSUE TITLE
Flaky test TestJdbcConnection.testConcurrentCancellationOnConnectionClose

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#10020]
```
Error:  io.trino.jdbc.TestJdbcConnection.testConcurrentCancellationOnConnectionClose[false](4)  Time elapsed: 0.837 s  <<< FAILURE!
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.sql.SQLException: Query failed (#20211121_033139_00052_rersc): Nested transactions not supported
	at io.trino.jdbc.TestJdbcConnection.assertThatFutureIsBlocked(TestJdbcConnection.java:698)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at io.trino.jdbc.TestJdbcConnection.lambda$testConcurrentCancellationOnConnectionClose$8(TestJdbcConnection.java:526)
	at io.trino.testing.assertions.Assert.assertEventually(Assert.java:71)
	at io.trino.testing.assertions.Assert.assertEventually(Assert.java:63)
	at io.trino.testing.assertions.Assert.assertEventually(Assert.java:58)
	at io.trino.jdbc.TestJdbcConnection.testConcurrentCancellationOnConnectionClose(TestJdbcConnection.java:525)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.sql.SQLException: Query failed (#20211121_033139_00052_rersc): Nested transactions not supported
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.trino.jdbc.TestJdbcConnection.assertThatFutureIsBlocked(TestJdbcConnection.java:695)
	... 18 more
Caused by: java.sql.SQLException: Query failed (#20211121_033139_00052_rersc): Nested transactions not supported
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1912)
	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:243)
	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:53)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:238)
	at io.trino.jdbc.TrinoStatement.executeQuery(TrinoStatement.java:78)
	at io.trino.jdbc.TestJdbcConnection.lambda$testConcurrentCancellationOnConnectionClose$6(TestJdbcConnection.java:514)
	... 4 more
Caused by: io.trino.spi.TrinoException: Nested transactions not supported
	at io.trino.execution.StartTransactionTask.execute(StartTransactionTask.java:62)
	at io.trino.execution.StartTransactionTask.execute(StartTransactionTask.java:38)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:170)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:146)
	at io.trino.$gen.Trino_testversion____20211121_033133_15.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by electrum** [comment]
@kokosing there might be a race condition in the cancellation code, but I'm not sure how, since we never start a transaction

**Comment by findepi** [comment]
already reported as https://github.com/trinodb/trino/issues/8611
