### ISSUE TITLE
Kafka connector - java.nio.BufferUnderflowException when doing WHERE filter

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#10026]
query:
```
SELECT * FROM kafka.default."my-topicoracle-abc.abc.redact_redact_redact" 
WHERE contract_number = 'xyz'
```

error:
```
2021-11-22T09:52:46.171Z        INFO    20211122_095240_00009_bxnpm.1.0-11-676  org.apache.kafka.clients.Metadata       [Consumer clientId=consumer-53, groupId=null] Cluster ID: Hkredact
2021-11-22T09:52:50.966Z        ERROR   SplitRunner-12-676      io.trino.execution.executor.TaskExecutor        Error processing Split 20211122_095240_00009_bxnpm.1.0-11 KafkaSplit{topicName=my-topicoracle-abc.ABC.REDACT_REDACT_REDACT, keyDataFormat=avro, messageDataFormat=avro, keyDataSchemaContents=Optional[{"type":"record","name":"Key","namespace":"my_topicoracle_abc.ABC.REDACT_REDACT_REDACT","fields":[{"name":"id","type":"string"},{"name":"contract_number","type":"string"},{"name":"authoring_org_id","type":"string"},{"name":"contract_number_modifier","type":["null","string"],"default":null},{"name":"chr_id_response","type":["null","string"],"default":null},{"name":"chr_id_award","type":["null","string"],"default":null},{"name":"chr_id_renewed","type":["null","string"],"default":null},{"name":"inv_organization_id","type":"string"},{"name":"sts_code","type":"string"},{"name":"qcl_id","type":["null","string"],"default":null},{"name":"scs_code","type":"string"},{"name":"trn_code","type":["null","string"],"default":null},{"name":"currency_code","type":["null","string"],"default":null},{"name":"archived_yn","type":"string"},{"name":"deleted_yn","type":"string"},{"name":"template_yn","type":"string"},{"name":"chr_type","type":"string"},{"name":"object_version_number","type":"int"},{"name":"created_by","type":"long"},{"name":"creation_date","type":{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}},{"name":"last_updated_by","type":"long"},{"name":"cust_po_number_req_yn","type":["null","string"],"default":null},{"name":"pre_pay_req_yn","type":["null","string"],"default":null},{"name":"cust_po_number","type":["null","string"],"default":null},{"name":"dpas_rating","type":["null","string"],"default":null},{"name":"template_used","type":["null","string"],"default":null},{"name":"date_approved","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"datetime_cancelled","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"auto_renew_days","type":["null",{"type":"int","connect.type":"int16"}],"default":null},{"name":"date_issued","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"datetime_responded","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"rfp_type","type":["null","string"],"default":null},{"name":"keep_on_mail_list","type":["null","string"],"default":null},{"name":"set_aside_percent","type":["null","string"],"default":null},{"name":"response_copies_req","type":["null",{"type":"int","connect.type":"int8"}],"default":null},{"name":"date_close_projected","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"datetime_proposed","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"date_signed","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"date_terminated","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"date_renewed","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"start_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"end_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"buy_or_sell","type":["null","string"],"default":null},{"name":"issue_or_receive","type":["null","string"],"default":null},{"name":"last_update_login","type":["null","long"],"default":null},{"name":"estimated_amount","type":["null","string"],"default":null},{"name":"attribute_category","type":["null","string"],"default":null},{"name":"last_update_date","type":{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}},{"name":"attribute1","type":["null","string"],"default":null},{"name":"attribute2","type":["null","string"],"default":null},{"name":"attribute3","type":["null","string"],"default":null},{"name":"attribute4","type":["null","string"],"default":null},{"name":"attribute5","type":["null","string"],"default":null},{"name":"attribute6","type":["null","string"],"default":null},{"name":"attribute7","type":["null","string"],"default":null},{"name":"attribute8","type":["null","string"],"default":null},{"name":"attribute9","type":["null","string"],"default":null},{"name":"attribute10","type":["null","string"],"default":null},{"name":"attribute11","type":["null","string"],"default":null},{"name":"attribute12","type":["null","string"],"default":null},{"name":"attribute13","type":["null","string"],"default":null},{"name":"attribute14","type":["null","string"],"default":null},{"name":"attribute15","type":["null","string"],"default":null},{"name":"security_group_id","type":["null","string"],"default":null},{"name":"chr_id_renewed_to","type":["null","string"],"default":null},{"name":"estimated_amount_renewed","type":["null","string"],"default":null},{"name":"currency_code_renewed","type":["null","string"],"default":null},{"name":"upg_orig_system_ref","type":["null","string"],"default":null},{"name":"upg_orig_system_ref_id","type":["null","string"],"default":null},{"name":"application_id","type":["null","string"],"default":null},{"name":"resolved_until","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"orig_system_source_code","type":["null","string"],"default":null},{"name":"orig_system_id1","type":["null","string"],"default":null},{"name":"orig_system_reference1","type":["null","string"],"default":null},{"name":"program_application_id","type":["null","string"],"default":null},{"name":"program_id","type":["null","string"],"default":null},{"name":"program_update_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"request_id","type":["null","string"],"default":null},{"name":"price_list_id","type":["null","string"],"default":null},{"name":"pricing_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"total_line_list_price","type":["null","string"],"default":null},{"name":"sign_by_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"user_estimated_amount","type":["null","string"],"default":null},{"name":"governing_contract_yn","type":["null","string"],"default":null},{"name":"conversion_type","type":["null","string"],"default":null},{"name":"conversion_rate","type":["null","string"],"default":null},{"name":"conversion_rate_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"conversion_euro_rate","type":["null","string"],"default":null},{"name":"cust_acct_id","type":["null","long"],"default":null},{"name":"bill_to_site_use_id","type":["null","long"],"default":null},{"name":"inv_rule_id","type":["null","long"],"default":null},{"name":"renewal_type_code","type":["null","string"],"default":null},{"name":"renewal_notify_to","type":["null","string"],"default":null},{"name":"renewal_end_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"ship_to_site_use_id","type":["null","long"],"default":null},{"name":"payment_term_id","type":["null","long"],"default":null},{"name":"document_id","type":["null","string"],"default":null},{"name":"approval_type","type":["null","string"],"default":null},{"name":"term_cancel_source","type":["null","string"],"default":null},{"name":"payment_instruction_type","type":["null","string"],"default":null},{"name":"org_id","type":"string"},{"name":"cancelled_amount","type":["null","string"],"default":null},{"name":"billed_at_source","type":["null","string"],"default":null},{"name":"attribute16","type":["null","string"],"default":null},{"name":"attribute17","type":["null","string"],"default":null},{"name":"attribute18","type":["null","string"],"default":null},{"name":"attribute19","type":["null","string"],"default":null},{"name":"attribute20","type":["null","string"],"default":null},{"name":"attribute21","type":["null","string"],"default":null},{"name":"attribute22","type":["null","string"],"default":null},{"name":"attribute23","type":["null","string"],"default":null},{"name":"attribute24","type":["null","string"],"default":null},{"name":"attribute25","type":["null","string"],"default":null},{"name":"attribute26","type":["null","string"],"default":null},{"name":"attribute27","type":["null","string"],"default":null},{"name":"attribute28","type":["null","string"],"default":null},{"name":"attribute29","type":["null","string"],"default":null},{"name":"attribute30","type":["null","string"],"default":null},{"name":"attribute31","type":["null","string"],"default":null},{"name":"attribute32","type":["null","string"],"default":null},{"name":"attribute33","type":["null","string"],"default":null},{"name":"attribute34","type":["null","string"],"default":null},{"name":"attribute35","type":["null","string"],"default":null},{"name":"attribute36","type":["null","string"],"default":null},{"name":"attribute37","type":["null","string"],"default":null},{"name":"attribute38","type":["null","string"],"default":null},{"name":"attribute39","type":["null","string"],"default":null},{"name":"attribute40","type":["null","string"],"default":null},{"name":"attribute41","type":["null","string"],"default":null},{"name":"attribute42","type":["null","string"],"default":null},{"name":"attribute43","type":["null","string"],"default":null},{"name":"attribute44","type":["null","string"],"default":null},{"name":"attribute45","type":["null","string"],"default":null}],"connect.name":"my_topicoracle_abc.ABC.REDACT_REDACT_REDACT.Key"}], messageDataSchemaContents=Optional[{"type":"record","name":"Value","namespace":"my_topicoracle_abc.ABC.REDACT_REDACT_REDACT","fields":[{"name":"id","type":"string"},{"name":"contract_number","type":"string"},{"name":"authoring_org_id","type":"string"},{"name":"contract_number_modifier","type":["null","string"],"default":null},{"name":"chr_id_response","type":["null","string"],"default":null},{"name":"chr_id_award","type":["null","string"],"default":null},{"name":"chr_id_renewed","type":["null","string"],"default":null},{"name":"inv_organization_id","type":"string"},{"name":"sts_code","type":"string"},{"name":"qcl_id","type":["null","string"],"default":null},{"name":"scs_code","type":"string"},{"name":"trn_code","type":["null","string"],"default":null},{"name":"currency_code","type":["null","string"],"default":null},{"name":"archived_yn","type":"string"},{"name":"deleted_yn","type":"string"},{"name":"template_yn","type":"string"},{"name":"chr_type","type":"string"},{"name":"object_version_number","type":"int"},{"name":"created_by","type":"long"},{"name":"creation_date","type":{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}},{"name":"last_updated_by","type":"long"},{"name":"cust_po_number_req_yn","type":["null","string"],"default":null},{"name":"pre_pay_req_yn","type":["null","string"],"default":null},{"name":"cust_po_number","type":["null","string"],"default":null},{"name":"dpas_rating","type":["null","string"],"default":null},{"name":"template_used","type":["null","string"],"default":null},{"name":"date_approved","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"datetime_cancelled","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"auto_renew_days","type":["null",{"type":"int","connect.type":"int16"}],"default":null},{"name":"date_issued","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"datetime_responded","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"rfp_type","type":["null","string"],"default":null},{"name":"keep_on_mail_list","type":["null","string"],"default":null},{"name":"set_aside_percent","type":["null","string"],"default":null},{"name":"response_copies_req","type":["null",{"type":"int","connect.type":"int8"}],"default":null},{"name":"date_close_projected","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"datetime_proposed","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"date_signed","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"date_terminated","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"date_renewed","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"start_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"end_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"buy_or_sell","type":["null","string"],"default":null},{"name":"issue_or_receive","type":["null","string"],"default":null},{"name":"last_update_login","type":["null","long"],"default":null},{"name":"estimated_amount","type":["null","string"],"default":null},{"name":"attribute_category","type":["null","string"],"default":null},{"name":"last_update_date","type":{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}},{"name":"attribute1","type":["null","string"],"default":null},{"name":"attribute2","type":["null","string"],"default":null},{"name":"attribute3","type":["null","string"],"default":null},{"name":"attribute4","type":["null","string"],"default":null},{"name":"attribute5","type":["null","string"],"default":null},{"name":"attribute6","type":["null","string"],"default":null},{"name":"attribute7","type":["null","string"],"default":null},{"name":"attribute8","type":["null","string"],"default":null},{"name":"attribute9","type":["null","string"],"default":null},{"name":"attribute10","type":["null","string"],"default":null},{"name":"attribute11","type":["null","string"],"default":null},{"name":"attribute12","type":["null","string"],"default":null},{"name":"attribute13","type":["null","string"],"default":null},{"name":"attribute14","type":["null","string"],"default":null},{"name":"attribute15","type":["null","string"],"default":null},{"name":"security_group_id","type":["null","string"],"default":null},{"name":"chr_id_renewed_to","type":["null","string"],"default":null},{"name":"estimated_amount_renewed","type":["null","string"],"default":null},{"name":"currency_code_renewed","type":["null","string"],"default":null},{"name":"upg_orig_system_ref","type":["null","string"],"default":null},{"name":"upg_orig_system_ref_id","type":["null","string"],"default":null},{"name":"application_id","type":["null","string"],"default":null},{"name":"resolved_until","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"orig_system_source_code","type":["null","string"],"default":null},{"name":"orig_system_id1","type":["null","string"],"default":null},{"name":"orig_system_reference1","type":["null","string"],"default":null},{"name":"program_application_id","type":["null","string"],"default":null},{"name":"program_id","type":["null","string"],"default":null},{"name":"program_update_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"request_id","type":["null","string"],"default":null},{"name":"price_list_id","type":["null","string"],"default":null},{"name":"pricing_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"total_line_list_price","type":["null","string"],"default":null},{"name":"sign_by_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"user_estimated_amount","type":["null","string"],"default":null},{"name":"governing_contract_yn","type":["null","string"],"default":null},{"name":"conversion_type","type":["null","string"],"default":null},{"name":"conversion_rate","type":["null","string"],"default":null},{"name":"conversion_rate_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"conversion_euro_rate","type":["null","string"],"default":null},{"name":"cust_acct_id","type":["null","long"],"default":null},{"name":"bill_to_site_use_id","type":["null","long"],"default":null},{"name":"inv_rule_id","type":["null","long"],"default":null},{"name":"renewal_type_code","type":["null","string"],"default":null},{"name":"renewal_notify_to","type":["null","string"],"default":null},{"name":"renewal_end_date","type":["null",{"type":"long","connect.version":1,"connect.name":"io.debezium.time.Timestamp"}],"default":null},{"name":"ship_to_site_use_id","type":["null","long"],"default":null},{"name":"payment_term_id","type":["null","long"],"default":null},{"name":"document_id","type":["null","string"],"default":null},{"name":"approval_type","type":["null","string"],"default":null},{"name":"term_cancel_source","type":["null","string"],"default":null},{"name":"payment_instruction_type","type":["null","string"],"default":null},{"name":"org_id","type":"string"},{"name":"cancelled_amount","type":["null","string"],"default":null},{"name":"billed_at_source","type":["null","string"],"default":null},{"name":"attribute16","type":["null","string"],"default":null},{"name":"attribute17","type":["null","string"],"default":null},{"name":"attribute18","type":["null","string"],"default":null},{"name":"attribute19","type":["null","string"],"default":null},{"name":"attribute20","type":["null","string"],"default":null},{"name":"attribute21","type":["null","string"],"default":null},{"name":"attribute22","type":["null","string"],"default":null},{"name":"attribute23","type":["null","string"],"default":null},{"name":"attribute24","type":["null","string"],"default":null},{"name":"attribute25","type":["null","string"],"default":null},{"name":"attribute26","type":["null","string"],"default":null},{"name":"attribute27","type":["null","string"],"default":null},{"name":"attribute28","type":["null","string"],"default":null},{"name":"attribute29","type":["null","string"],"default":null},{"name":"attribute30","type":["null","string"],"default":null},{"name":"attribute31","type":["null","string"],"default":null},{"name":"attribute32","type":["null","string"],"default":null},{"name":"attribute33","type":["null","string"],"default":null},{"name":"attribute34","type":["null","string"],"default":null},{"name":"attribute35","type":["null","string"],"default":null},{"name":"attribute36","type":["null","string"],"default":null},{"name":"attribute37","type":["null","string"],"default":null},{"name":"attribute38","type":["null","string"],"default":null},{"name":"attribute39","type":["null","string"],"default":null},{"name":"attribute40","type":["null","string"],"default":null},{"name":"attribute41","type":["null","string"],"default":null},{"name":"attribute42","type":["null","string"],"default":null},{"name":"attribute43","type":["null","string"],"default":null},{"name":"attribute44","type":["null","string"],"default":null},{"name":"attribute45","type":["null","string"],"default":null},{"name":"__scn","type":["null","string"],"default":null},{"name":"__op","type":["null","string"],"default":null},{"name":"__source_ts_ms","type":["null","long"],"default":null},{"name":"__ts_ms","type":["null","long"],"default":null},{"name":"__deleted","type":["null","string"],"default":null}],"connect.name":"my_topicoracle_abc.ABC.REDACT_REDACT_REDACT.Value"}], partitionId=7, messagesRange=Range{begin=20464, end=40884}, leader=redact:9098} (start = 3.311952306458E7, wall = 4895 ms, cpu = 1506 ms, wait = 3012 ms, calls = 3)
java.nio.BufferUnderflowException
        at java.base/java.nio.Buffer.nextGetIndex(Unknown Source)
        at java.base/java.nio.HeapByteBuffer.get(Unknown Source)
        at io.trino.plugin.kafka.schema.confluent.ConfluentAvroReaderSupplier.get(ConfluentAvroReaderSupplier.java:67)
        at io.trino.decoder.avro.AvroBytesDeserializer.deserialize(AvroBytesDeserializer.java:45)
        at io.trino.decoder.avro.GenericRecordRowDecoder.decodeRow(GenericRecordRowDecoder.java:49)
        at io.trino.decoder.RowDecoder.decodeRow(RowDecoder.java:34)
        at io.trino.plugin.kafka.KafkaRecordSet$KafkaRecordCursor.nextRow(KafkaRecordSet.java:190)
        at io.trino.plugin.kafka.KafkaRecordSet$KafkaRecordCursor.advanceNextPosition(KafkaRecordSet.java:163)
        at io.trino.$gen.CursorProcessor_20211122_095240_5.process(Unknown Source)
        at io.trino.operator.ScanFilterAndProjectOperator$RecordCursorToPages.process(ScanFilterAndProjectOperator.java:338)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:151)
        at io.trino.operator.Driver.processInternal(Driver.java:388)
        at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
        at io.trino.operator.Driver.tryWithLock(Driver.java:685)
        at io.trino.operator.Driver.processFor(Driver.java:285)
        at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1078)
        at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.trino.$gen.Trino_364____20211122_022231_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)


2021-11-22T09:52:50.968Z        ERROR   remote-task-callback-10 io.trino.execution.StageStateMachine    Stage 20211122_095240_00009_bxnpm.1 failed
java.nio.BufferUnderflowException
        at java.base/java.nio.Buffer.nextGetIndex(Unknown Source)
        at java.base/java.nio.HeapByteBuffer.get(Unknown Source)
        at io.trino.plugin.kafka.schema.confluent.ConfluentAvroReaderSupplier.get(ConfluentAvroReaderSupplier.java:67)
        at io.trino.decoder.avro.AvroBytesDeserializer.deserialize(AvroBytesDeserializer.java:45)
        at io.trino.decoder.avro.GenericRecordRowDecoder.decodeRow(GenericRecordRowDecoder.java:49)
        at io.trino.decoder.RowDecoder.decodeRow(RowDecoder.java:34)
        at io.trino.plugin.kafka.KafkaRecordSet$KafkaRecordCursor.nextRow(KafkaRecordSet.java:190)
        at io.trino.plugin.kafka.KafkaRecordSet$KafkaRecordCursor.advanceNextPosition(KafkaRecordSet.java:163)
        at io.trino.$gen.CursorProcessor_20211122_095240_5.process(Unknown Source)
        at io.trino.operator.ScanFilterAndProjectOperator$RecordCursorToPages.process(ScanFilterAndProjectOperator.java:338)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:151)
        at io.trino.operator.Driver.processInternal(Driver.java:388)
        at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
        at io.trino.operator.Driver.tryWithLock(Driver.java:685)
        at io.trino.operator.Driver.processFor(Driver.java:285)
        at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1078)
        at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.trino.$gen.Trino_364____20211122_022231_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

query without WHERE filter works ok

**Comment by tooptoop4** [comment]
I think this is happening for topics with tombstone messages (https://debezium.io/documentation/reference/transformations/applying-transformations-selectively.html). ie have a key but null value

**Comment by ubyyj** [comment]
got the same issue, is there any way to skip those null value records?

**Comment by hashhar** [comment]
https://github.com/trinodb/trino/pull/17479 needs to be applied for all decoders.

We fixed it for Avro only it seems.
