### ISSUE TITLE
Flaky test TestParquetReader.testStructOfTwoNestedArrays: Dictionary is missing for Page

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#10038]
https://github.com/trinodb/trino/runs/4287754066?check_suite_focus=true

```
2021-11-22T19:36:49.8938068Z [ERROR] Tests run: 3018, Failures: 1, Errors: 0, Skipped: 91, Time elapsed: 2,479.186 s <<< FAILURE! - in TestSuite
2021-11-22T19:36:49.8943379Z [ERROR] io.trino.plugin.hive.parquet.TestParquetReader.testStructOfTwoNestedArrays  Time elapsed: 1.347 s  <<< FAILURE!
2021-11-22T19:36:49.8946749Z org.apache.parquet.io.ParquetDecodingException: Dictionary is missing for Page
2021-11-22T19:36:49.8949043Z 	at io.trino.parquet.reader.PrimitiveColumnReader.initDataReader(PrimitiveColumnReader.java:406)
2021-11-22T19:36:49.8951654Z 	at io.trino.parquet.reader.PrimitiveColumnReader.readPageV1(PrimitiveColumnReader.java:379)
2021-11-22T19:36:49.8954626Z 	at io.trino.parquet.reader.PrimitiveColumnReader.readNextPage(PrimitiveColumnReader.java:350)
2021-11-22T19:36:49.8958078Z 	at io.trino.parquet.reader.PrimitiveColumnReader.readPrimitive(PrimitiveColumnReader.java:217)
2021-11-22T19:36:49.8961952Z 	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:370)
2021-11-22T19:36:49.8975069Z 	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:444)
2021-11-22T19:36:49.8976992Z 	at io.trino.parquet.reader.ParquetReader.readArray(ParquetReader.java:289)
2021-11-22T19:36:49.8978867Z 	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:441)
2021-11-22T19:36:49.8980739Z 	at io.trino.parquet.reader.ParquetReader.readArray(ParquetReader.java:289)
2021-11-22T19:36:49.8982596Z 	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:441)
2021-11-22T19:36:49.8984493Z 	at io.trino.parquet.reader.ParquetReader.readStruct(ParquetReader.java:325)
2021-11-22T19:36:49.8986390Z 	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:435)
2021-11-22T19:36:49.8988465Z 	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:427)
2021-11-22T19:36:49.8990475Z 	at io.trino.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:224)
2021-11-22T19:36:49.8992239Z 	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:396)
2021-11-22T19:36:49.8993589Z 	at io.trino.spi.block.LazyBlock$LazyData.getTopLevelBlock(LazyBlock.java:365)
2021-11-22T19:36:49.8994807Z 	at io.trino.spi.block.LazyBlock.getBlock(LazyBlock.java:270)
2021-11-22T19:36:49.8995905Z 	at io.trino.spi.block.LazyBlock.isNull(LazyBlock.java:253)
2021-11-22T19:36:49.8997697Z 	at io.trino.plugin.hive.parquet.ParquetTester.decodeObject(ParquetTester.java:712)
2021-11-22T19:36:49.9000090Z 	at io.trino.plugin.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:492)
2021-11-22T19:36:49.9002643Z 	at io.trino.plugin.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:473)
2021-11-22T19:36:49.9004917Z 	at io.trino.plugin.hive.parquet.ParquetTester.assertFileContents(ParquetTester.java:465)
2021-11-22T19:36:49.9007135Z 	at io.trino.plugin.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:367)
2021-11-22T19:36:49.9009345Z 	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:298)
2021-11-22T19:36:49.9011501Z 	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:220)
2021-11-22T19:36:49.9015863Z 	at io.trino.plugin.hive.parquet.AbstractTestParquetReader.testStructOfTwoNestedArrays(AbstractTestParquetReader.java:756)
2021-11-22T19:36:49.9019090Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-11-22T19:36:49.9021359Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-11-22T19:36:49.9024415Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-11-22T19:36:49.9026627Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-11-22T19:36:49.9028216Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-11-22T19:36:49.9030406Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-11-22T19:36:49.9031925Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-11-22T19:36:49.9033319Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-11-22T19:36:49.9035231Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-11-22T19:36:49.9038993Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-11-22T19:36:49.9040839Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-11-22T19:36:49.9043116Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-11-22T19:36:49.9044580Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-11-22T19:36:49.9045017Z 
```

**Comment by findepi** [comment]
cc @skrzypo987 @raunaqmorarka @sopel39

**Comment by raunaqmorarka** [comment]
Haven't seen report of this in a while, closing
