### ISSUE TITLE
TrinoException: Malformed ORC file. Seek past end of stream 

### ISSUE THREAD

**Issue by ByPatrick** [trinodb/trino#10113]
Presto server version: `364`

I do compaction frequently for incremental data, but sometime this error will occur after compaction. 
Once this error occur, the record in that file cannot read anymore. (the broken data uncertain is the newest)

```
io.trino.spi.TrinoException: Malformed ORC file. Seek past end of stream [hdfs://hdfs:8020/user/hive/warehouse/debug.db/debug_table/000001_0_20211130_003002_00034_dfz2x]
	at io.trino.plugin.hive.orc.OrcPageSource.handleException(OrcPageSource.java:166)
	at io.trino.plugin.hive.orc.OrcPageSourceFactory.lambda$createOrcPageSource$8(OrcPageSourceFactory.java:382)
	at io.trino.orc.OrcBlockFactory$OrcBlockLoader.load(OrcBlockFactory.java:83)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:396)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:375)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:282)
	at io.trino.plugin.hive.orc.OrcPageSource$SourceColumn$MaskingBlockLoader.load(OrcPageSource.java:325)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:396)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:375)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:282)
	at io.trino.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.setupDictionaryBlockProjection(DictionaryAwarePageProjection.java:211)
	at io.trino.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.lambda$getResult$0(DictionaryAwarePageProjection.java:197)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:396)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:375)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:282)
	at io.trino.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:346)
	at io.trino.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:209)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:151)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1078)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_364____20211116_092039_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.trino.orc.OrcCorruptionException: Malformed ORC file. Seek past end of stream [hdfs://hdfs:8020/user/hive/warehouse/debug.db/debug_table/000001_0_20211130_003002_00034_dfz2x]
	at io.trino.orc.stream.CompressedOrcChunkLoader.seekToCheckpoint(CompressedOrcChunkLoader.java:94)
	at io.trino.orc.stream.OrcInputStream.seekToCheckpoint(OrcInputStream.java:174)
	at io.trino.orc.stream.ByteArrayInputStream.seekToCheckpoint(ByteArrayInputStream.java:50)
	at io.trino.orc.stream.ByteArrayInputStream.seekToCheckpoint(ByteArrayInputStream.java:22)
	at io.trino.orc.stream.CheckpointInputStreamSource.openStream(CheckpointInputStreamSource.java:57)
	at io.trino.orc.reader.SliceDirectColumnReader.openRowGroup(SliceDirectColumnReader.java:243)
	at io.trino.orc.reader.SliceDirectColumnReader.readBlock(SliceDirectColumnReader.java:104)
	at io.trino.orc.reader.SliceColumnReader.readBlock(SliceColumnReader.java:74)
	at io.trino.orc.OrcBlockFactory$OrcBlockLoader.load(OrcBlockFactory.java:76)
	... 46 more
```

**Comment by Praveen2112** [comment]
Are we able to read the same ORC file from other system like Hive or using Apache ORC tools ?

**Comment by ByPatrick** [comment]
Yes, It can be read using ORC Java tool.
![image](https://user-images.githubusercontent.com/5445771/144166941-438753b6-9f96-4538-85d1-05a3c9b5e2fd.png)

**Comment by ByPatrick** [comment]
I had pointed to a "cell" that will occur this exception when query.

Also I try to read this one record in Hive, and hive return the error below:

Failed with exception java.io.IOException:java.lang.RuntimeException: ORC split generation failed with exception: java.io.IOException: Problem reading file footer hdfs://hive-hdfs:8020/user/hive/warehouse/debug.db/debug_table/000009_0_20211213_153001_01739_vxz83

**Comment by ByPatrick** [comment]
BTW, only read the cell will fire exception.
Query others are fine.

**Comment by findepi** [comment]
@dain is most knowledgable about ORC

**Comment by ByPatrick** [comment]
Just FYR:

I create the table without the orc_bloom_filter_columns property, this issue didn't show up so far.
