### ISSUE TITLE
Server keeps trying to use TLS1.3

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#10119]
trino server 364 running on java13 (```openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)```)

local jdbc client (364 driver) running on java8 (```java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
```) with ```jdbc:trino://mydns:8085?SSL=true&SSLVerification=NONE```

gets below

```
java.sql.SQLException: Error executing query
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:287)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
	at io.trino.jdbc.TrinoStatement.executeQuery(TrinoStatement.java:78)
	at io.trino.jdbc.TrinoDatabaseMetaData.select(TrinoDatabaseMetaData.java:1491)
	at io.trino.jdbc.TrinoDatabaseMetaData.getSchemas(TrinoDatabaseMetaData.java:962)
	at workbench.db.DbMetadata.getSchemas(DbMetadata.java:2629)
	at workbench.gui.dbobjects.objecttree.TreeLoader.loadSchemas(TreeLoader.java:433)
	at workbench.gui.dbobjects.objecttree.TreeLoader.load(TreeLoader.java:356)
	at workbench.gui.dbobjects.objecttree.DbObjectsTree.load(DbObjectsTree.java:455)
	at workbench.gui.dbobjects.objecttree.DbTreePanel$5.run(DbTreePanel.java:325)
Caused by: java.io.UncheckedIOException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:148)
	at io.trino.jdbc.$internal.client.StatementClientV1.<init>(StatementClientV1.java:109)
	at io.trino.jdbc.$internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24)
	at io.trino.jdbc.TrinoConnection.startQuery(TrinoConnection.java:750)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:252)
	... 9 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alert.createSSLException(Unknown Source)
	at sun.security.ssl.Alert.createSSLException(Unknown Source)
	at sun.security.ssl.TransportContext.fatal(Unknown Source)
	at sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
	at sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at sun.security.ssl.SSLTransport.decode(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at io.trino.jdbc.$internal.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.trino.jdbc.$internal.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.trino.jdbc.$internal.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.trino.jdbc.$internal.client.OkHttpUtil.lambda$basicAuth$1(OkHttpUtil.java:83)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.trino.jdbc.$internal.client.OkHttpUtil.lambda$userAgent$0(OkHttpUtil.java:69)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.trino.jdbc.$internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at io.trino.jdbc.$internal.okhttp3.RealCall.execute(RealCall.java:81)
	at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:130)
	... 13 more
```

from looking at the logs the server is only accepting TLS1.3 even if i modify java.security file, is java8 client not supported?

**Comment by tooptoop4** [comment]
ignore, the file pointed to by http-server.https.keystore.path was dodgy
