### ISSUE TITLE
Deprecation of `docker-machine`

### ISSUE THREAD

**Issue by jerryleooo** [trinodb/trino#10132]
https://github.com/docker/machine discontinued since 2019, and its latest version seems not to support M1 chip, maybe we should consider deprecating it?

docker-machine depends on VirtualBox, while VirtualBox doesn't support M1 chip.

```
➜  trino-357 git:(fix_8404_1) ✗ docker-machine  -D ip
Docker Machine Version:  0.16.2, build bd45ab13
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:57757
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
command=ip machine=default
(default) Calling .GetIP
(default) DBG | COMMAND: /usr/local/bin/VBoxManage showvminfo default --machinereadable
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | /usr/local/bin/VBoxManage: line 2: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage: No such file or directory
(default) DBG | /usr/local/bin/VBoxManage: line 2: exec: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage: cannot execute: No such file or directory
(default) DBG | }
Error getting IP address: exit status 126

```

**Comment by jerryleooo** [comment]
FYI: https://forums.virtualbox.org/viewtopic.php?f=8&t=100875

**Comment by hashhar** [comment]
I believe you are referring to https://github.com/trinodb/trino/blob/c9955373e4faa79a37a612b0094f7017eb342450/plugin/trino-hive-hadoop2/bin/common.sh#L114-L119?

We don't use docker-machine, that code just tries to find correct IP to be used for proxying requests to the Hive containers in the product tests. It always ends up choosing localhost since tests don't use docker-machine.

Maybe we can remove that since it looks like dead code? @sopel39 (git tells me you might know about that)?

**Comment by jerryleooo** [comment]
Yes @hashhar that is what I am referring to

**Comment by jerryleooo** [comment]
And since we are using https://github.com/testcontainers/testcontainers-java 
I also encountered https://github.com/testcontainers/testcontainers-java/issues/3834

**Comment by findepi** [comment]
Tests don't rely on virtualbox, nor docker-machine

**Comment by jerryleooo** [comment]
@findepi 

when running tests on https://github.com/trinodb/trino/blob/master/plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestDruidConnectorTest.java#L27 I got following errors:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.testng.xml.XMLParser (file:/Users/leo/.m2/repository/org/testng/testng/6.10/testng-6.10.jar) to constructor com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl()
WARNING: Please consider reporting this to the maintainers of org.testng.xml.XMLParser
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-12-01T03:13:45.176-0600 INFO LogTestDurationListener enabled: false
2021-12-01T03:13:45.228-0600 INFO ProgressLoggingListener is disabled!
[TestNG] Running:
  /Users/leo/Library/Caches/JetBrains/IdeaIC2021.2/temp-testng-customsuite.xml

2021-12-01T03:13:47.031-0600 INFO Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2021-12-01T03:13:47.911-0600 INFO docker-machine executable was not found on PATH ([/usr/local/opt/binutils/bin, /Users/leo/go/bin, /usr/local/go/bin, /Users/leo/bin/, /Applications/Postgres.app/Contents/Versions/latest/bin, /usr/local/heroku/bin, /Users/leo/kubernetes/kubernetes/cluster, /usr/local/heroku/bin, /Users/leo/kubernetes/kubernetes/cluster, /usr/bin, /bin, /usr/sbin, /sbin, /usr/local/bin, /opt/X11/bin, /usr/local/aria2/bin, /usr/local/sbin, /Users/leo/nodejs/npm_global/bin])
2021-12-01T03:13:47.921-0600 SEVERE Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
2021-12-01T03:13:47.922-0600 SEVERE     UnixSocketClientProviderStrategy: failed with exception RuntimeException (java.lang.UnsatisfiedLinkError: /Users/leo/Library/Caches/JNA/temp/jna5706398095917706561.tmp: dlopen(/Users/leo/Library/Caches/JNA/temp/jna5706398095917706561.tmp, 0x0001): tried: '/Users/leo/Library/Caches/JNA/temp/jna5706398095917706561.tmp' (code signature in <7B2B9DAD-A613-3D6C-8F29-CECF5295831F> '/Users/leo/Library/Caches/JNA/temp/jna5706398095917706561.tmp' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/lib/jna5706398095917706561.tmp' (no such file)). Root cause UnsatisfiedLinkError (/Users/leo/Library/Caches/JNA/temp/jna5706398095917706561.tmp: dlopen(/Users/leo/Library/Caches/JNA/temp/jna5706398095917706561.tmp, 0x0001): tried: '/Users/leo/Library/Caches/JNA/temp/jna5706398095917706561.tmp' (code signature in <7B2B9DAD-A613-3D6C-8F29-CECF5295831F> '/Users/leo/Library/Caches/JNA/temp/jna5706398095917706561.tmp' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/lib/jna5706398095917706561.tmp' (no such file))
2021-12-01T03:13:47.922-0600 SEVERE As no valid configuration was found, execution cannot continue

java.lang.RuntimeException: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration

	at io.trino.plugin.druid.TestingDruidServer.<init>(TestingDruidServer.java:177)
	at io.trino.plugin.druid.TestDruidLatestConnectorTest.createQueryRunner(TestDruidLatestConnectorTest.java:36)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:107)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$4(DockerClientProviderStrategy.java:156)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:148)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:146)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:188)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:101)
	at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:107)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:316)
	at io.trino.plugin.druid.TestingDruidServer.<init>(TestingDruidServer.java:94)
	... 26 more
```

It should be caused the use of testcontainers
