### ISSUE TITLE
Can't create materialized views when using Ranger plugin

### ISSUE THREAD

**Issue by nfoerster** [trinodb/trino#10136]
Trino Version: 364
Apache Ranger Version: 2.1.0

Hi all,

I finally can't create any materialized views, also not with superuser. Creating tables/views works as designed.
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [4]: Query failed (#20211201_121952_00065_ez3hh): Access Denied: Cannot create materialized view hive.test.mat_vw_dim_time
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:509)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:440)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:427)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:812)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3181)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:119)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4514)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Query failed (#20211201_121952_00065_ez3hh): Access Denied: Cannot create materialized view hive.fme_cpm_prod.vw_dim_time2
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1912)
	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:243)
	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:53)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:327)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	... 12 more
Caused by: io.trino.spi.security.AccessDeniedException: Access Denied: Cannot create materialized view hive.fme_cpm_prod.vw_dim_time2
	at io.trino.spi.security.AccessDeniedException.denyCreateMaterializedView(AccessDeniedException.java:408)
	at io.trino.spi.security.AccessDeniedException.denyCreateMaterializedView(AccessDeniedException.java:403)
	at io.trino.spi.security.SystemAccessControl.checkCanCreateMaterializedView(SystemAccessControl.java:538)
	at io.trino.security.AccessControlManager.lambda$checkCanCreateMaterializedView$64(AccessControlManager.java:751)
	at io.trino.security.AccessControlManager.systemAuthorizationCheck(AccessControlManager.java:1186)
	at io.trino.security.AccessControlManager.checkCanCreateMaterializedView(AccessControlManager.java:751)
	at io.trino.security.ForwardingAccessControl.checkCanCreateMaterializedView(ForwardingAccessControl.java:297)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitCreateMaterializedView(StatementAnalyzer.java:1213)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitCreateMaterializedView(StatementAnalyzer.java:367)
	at io.trino.sql.tree.CreateMaterializedView.accept(CreateMaterializedView.java:85)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:384)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:347)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:92)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:84)
	at io.trino.execution.CreateMaterializedViewTask.execute(CreateMaterializedViewTask.java:94)
	at io.trino.execution.CreateMaterializedViewTask.execute(CreateMaterializedViewTask.java:50)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:170)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_364____20211201_075803_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I deployed Trino to Kubernetes together with Ranger, also as a deployment. As Apache has until now still no usable plugin for Trino, I used the plugin from: 
https://github.com/aakashnand/trino-ranger-demo
following guide from https://towardsdatascience.com/integrating-trino-and-apache-ranger-b808f6b96ad8

Well, everything works fine so far, however creating materialized views does not, so I'm wondering if it is caused by my rarely used setup or if there are missing Trino options I need to set. 

Any guidance would be helpful, thanks

**Comment by aakashnand** [comment]
@nfoerster this bug is not on Trino but it is a bug on https://github.com/aakashnand/trino-ranger-demo side. I have a solution for this. I will soon update the code meanwhile if you want to get immediate help. Please reach out to me on Trino Slack https://trino.io/community.html
