### ISSUE TITLE
Support subquery in VALUES 

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#10161]
This works:
```
trino:tpch> SELECT 1, 2, 3, (SELECT max(nationkey) FROM tpch.tiny.nation);
 _col0 | _col1 | _col2 | _col3
-------+-------+-------+-------
     1 |     2 |     3 |    24
```

but this doesn't:
```
trino:tpch> VALUES (1, 2, 3, (SELECT max(nationkey) FROM tpch.tiny.nation));
Query 20211202_141247_00038_3urjr failed: Unexpected subquery expression in logical plan: (SELECT max(nationkey)
FROM
  tpch.tiny.nation
)
```
```
java.lang.IllegalStateException: Unexpected subquery expression in logical plan: (SELECT max(nationkey)
FROM
  tpch.tiny.nation
)
	at io.trino.sql.planner.sanity.NoSubqueryExpressionLeftChecker$1.visitSubqueryExpression(NoSubqueryExpressionLeftChecker.java:49)
	at io.trino.sql.planner.sanity.NoSubqueryExpressionLeftChecker$1.visitSubqueryExpression(NoSubqueryExpressionLeftChecker.java:45)
	at io.trino.sql.tree.SubqueryExpression.accept(SubqueryExpression.java:51)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.tree.DefaultTraversalVisitor.visitRow(DefaultTraversalVisitor.java:540)
	at io.trino.sql.tree.DefaultTraversalVisitor.visitRow(DefaultTraversalVisitor.java:16)
	at io.trino.sql.tree.Row.accept(Row.java:54)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.sanity.NoSubqueryExpressionLeftChecker.validate(NoSubqueryExpressionLeftChecker.java:51)
	at io.trino.sql.planner.sanity.PlanSanityChecker.lambda$validateIntermediatePlan$1(PlanSanityChecker.java:88)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at io.trino.sql.planner.sanity.PlanSanityChecker.validateIntermediatePlan(PlanSanityChecker.java:88)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:228)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:217)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:212)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:480)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:460)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:401)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20211202_135354_3.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lukaseder** [comment]
Just ran into this. It also affects `VALUES` usage in `INSERT`, e.g. this doesn't work:

```sql
INSERT INTO t (i) VALUES ((SELECT 1))
```

This does:

```sql
INSERT INTO t (i) SELECT (SELECT 1)
```
