### ISSUE TITLE
supports Apache Iceberg table spec version 2

### ISSUE THREAD

**Issue by haoweijia** [trinodb/trino#10290]
I create a Apache Iceberg table spec version 2 , like this:
```
CREATE TABLE person_cdc_addr (
    id int,
    event_time timestamp,
    name string,
    address string
    )
USING iceberg
OPTIONS ('format-version'=2, format = 'PARQUET', write.upsert.enable = true)
PARTITIONED BY (address);
```
I want to use iceberg V2 table cdc character update data, but  I can't use trino select the table.

sql: 
```
select * from person_cdc_addr.
```

```
java.lang.NullPointerException: undefined
	at io.trino.plugin.iceberg.HiveTableOperations.refreshFromMetadataLocation(HiveTableOperations.java:299)
	at io.trino.plugin.iceberg.HiveTableOperations.refresh(HiveTableOperations.java:145)
	at io.trino.plugin.iceberg.HiveTableOperations.current(HiveTableOperations.java:121)
	at io.trino.plugin.iceberg.IcebergMetadata.lambda$getIcebergTable$26(IcebergMetadata.java:852)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.trino.plugin.iceberg.IcebergMetadata.getIcebergTable(IcebergMetadata.java:850)
	at io.trino.plugin.iceberg.IcebergMetadata.getRawSystemTable(IcebergMetadata.java:278)
	at io.trino.plugin.iceberg.IcebergMetadata.getSystemTable(IcebergMetadata.java:265)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getSystemTable(ClassLoaderSafeConnectorMetadata.java:223)
	at io.trino.metadata.MetadataManager.getSystemTable(MetadataManager.java:439)
	at io.trino.connector.system.CoordinatorSystemTablesProvider.getSystemTable(CoordinatorSystemTablesProvider.java:72)
	at io.trino.connector.system.SystemTablesMetadata.getTableHandle(SystemTablesMetadata.java:68)
	at io.trino.metadata.CatalogMetadata.getConnectorId(CatalogMetadata.java:115)
	at io.trino.metadata.MetadataManager.getMaterializedView(MetadataManager.java:1376)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1297)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:362)
	at io.trino.sql.tree.Table.accept(Table.java:53)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:379)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3174)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1946)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:362)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:379)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:389)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1165)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:362)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:379)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:342)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:190)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:806)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
	at io.trino.$gen.Trino_359____20211214_023941_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by findepi** [comment]
let's talk under https://github.com/trinodb/trino/issues/8873. Seems this is the same.
Can you please retest with version 361 or newer?
