### ISSUE TITLE
Strange behavior of all columns expression .* 

### ISSUE THREAD

**Issue by jaehc** [trinodb/trino#10298]
Hi, 
I came across a strange behavior regarding all columns expression, that is `.*`. 

As per [this document](https://trino.io/docs/current/sql/select.html), I am able to run the following query with no problem.
```
trino> SELECT (CAST(ROW(1, true) AS ROW(field1 bigint, field2 boolean))).* AS (alias1, alias2);
--
 ALIAS1 | ALIAS2 
--------+--------
      1 | true   
(1 row)

```

However, when I put another constant column in the SELECT caluse, it fails with the following error as below.

```
trino> SELECT 1 as num, (CAST(ROW(1, true) AS ROW(field1 bigint, field2 boolean))).* AS (alias1, alias2);

Query 20211214_142835_00005_c83qd failed: Subscript expression on ROW requires a constant index
---
```

Even though this behavior dosen't hinder Trino's usability, I want to let you know about this behavior. 

I appreciate all your help. Thank you.

**Comment by findepi** [comment]
Minimal repro

```
trino> SELECT 1, ROW(1, true).*;
Query 20211215_203535_00006_qiu47 failed: Subscript expression on ROW requires a constant index
io.trino.spi.TrinoException: Subscript expression on ROW requires a constant index
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitSubscriptExpression(ExpressionAnalyzer.java:927)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitSubscriptExpression(ExpressionAnalyzer.java:495)
	at io.trino.sql.tree.SubscriptExpression.accept(SubscriptExpression.java:50)
	at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:518)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:403)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:2711)
	at io.trino.sql.planner.TypeAnalyzer.getTypes(TypeAnalyzer.java:54)
	at io.trino.sql.planner.TypeAnalyzer.getTypes(TypeAnalyzer.java:69)
	at io.trino.sql.planner.TypeAnalyzer.getType(TypeAnalyzer.java:74)
	at io.trino.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:128)
	at io.trino.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:63)
	at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.trino.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at io.trino.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:119)
	at io.trino.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:63)
	at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.trino.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at io.trino.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:119)
	at io.trino.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:63)
	at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.trino.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at io.trino.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:119)
	at io.trino.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:63)
	at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.trino.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at io.trino.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.sanity.TypeValidator.validate(TypeValidator.java:60)
	at io.trino.sql.planner.sanity.PlanSanityChecker.lambda$validateIntermediatePlan$1(PlanSanityChecker.java:88)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at io.trino.sql.planner.sanity.PlanSanityChecker.validateIntermediatePlan(PlanSanityChecker.java:88)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:228)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:217)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:212)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:480)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:460)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:401)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_365____20211215_203446_2.run(Unknown Source)
```
