### ISSUE TITLE
trino-hadoop-apache: `FileSystem#getLocal` fails since ClassCastException

### ISSUE THREAD

**Issue by yittg** [trinodb/trino#10306]
If `fs.file.impl.disable.cache` is not set as `true`, the method `FileSystem#getLocal` will fail since it tries to cast a `TrinoFileSystemCache$FileSystemWrapper` to `LocalFileSystem`.

**Comment by yittg** [comment]
Hi, @lzeiming , @Praveen2112 , @findepi , is this PR #8333 continue?

I encountered this issue while trying to integrate [aliyun oss](https://github.com/apache/hadoop/tree/trunk/hadoop-tools/hadoop-aliyun) for `iceberg` connector with hive catalog.

I have to disable cache for `LocalFileSystem` to walk around it. 

Here is a full stack of this issue, hope it can help:
```
java.lang.ClassCastException: class io.trino.plugin.hive.fs.TrinoFileSystemCache$FileSystemWrapper cannot be cast to class org.apache.hadoop.fs.LocalFileSystem (io.trino.plugin.hive.fs.TrinoFileSystemCache$FileSystemWrapper and org.apache.hadoop.fs.LocalFileSystem are in unnamed module of loader io.trino.server.PluginClassLoader @5ce1b67b)
	at org.apache.hadoop.fs.FileSystem.getLocal(FileSystem.java:435)
	at org.apache.hadoop.fs.LocalDirAllocator$AllocatorPerContext.confChanged(LocalDirAllocator.java:317)
	at org.apache.hadoop.fs.LocalDirAllocator$AllocatorPerContext.getLocalPathForWrite(LocalDirAllocator.java:394)
	at org.apache.hadoop.fs.LocalDirAllocator$AllocatorPerContext.createTmpFileForWrite(LocalDirAllocator.java:477)
	at org.apache.hadoop.fs.LocalDirAllocator.createTmpFileForWrite(LocalDirAllocator.java:213)
	at org.apache.hadoop.fs.aliyun.oss.AliyunOSSUtils.createTmpFileForWrite(AliyunOSSUtils.java:186)
	at org.apache.hadoop.fs.aliyun.oss.AliyunOSSBlockOutputStream.newBlockFile(AliyunOSSBlockOutputStream.java:82)
	at org.apache.hadoop.fs.aliyun.oss.AliyunOSSBlockOutputStream.<init>(AliyunOSSBlockOutputStream.java:74)
	at org.apache.hadoop.fs.aliyun.oss.AliyunOSSFileSystem.create(AliyunOSSFileSystem.java:137)
	at io.trino.plugin.hive.fs.TrinoFileSystemCache$FileSystemWrapper.create(TrinoFileSystemCache.java:321)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1118)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1098)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:987)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:975)
	at io.trino.plugin.iceberg.IcebergFileWriterFactory.lambda$createOrcWriter$3(IcebergFileWriterFactory.java:180)
	at io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:97)
	at io.trino.plugin.iceberg.IcebergFileWriterFactory.createOrcWriter(IcebergFileWriterFactory.java:180)
	at io.trino.plugin.iceberg.IcebergFileWriterFactory.createFileWriter(IcebergFileWriterFactory.java:119)
	at io.trino.plugin.iceberg.IcebergPageSink.createWriter(IcebergPageSink.java:309)
	at io.trino.plugin.iceberg.IcebergPageSink.getWriterIndexes(IcebergPageSink.java:293)
	at io.trino.plugin.iceberg.IcebergPageSink.writePage(IcebergPageSink.java:223)
	at io.trino.plugin.iceberg.IcebergPageSink.doAppend(IcebergPageSink.java:218)
	at io.trino.plugin.iceberg.IcebergPageSink.lambda$appendPage$0(IcebergPageSink.java:156)
	at io.trino.plugin.hive.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:26)
	at io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.plugin.hive.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:25)
	at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:102)
	at io.trino.plugin.iceberg.IcebergPageSink.appendPage(IcebergPageSink.java:156)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:69)
	at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:270)
	at io.trino.operator.Driver.processInternal(Driver.java:393)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_365____20211215_101646_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by yittg** [comment]
@findepi @Praveen2112 , Given that the PR #8333 has not progressed for a long time, and trinodb/trino-hadoop-apache#36 may be a simpler solution, would you have a look?
