### ISSUE TITLE
Query failure: Cannot invoke "io.trino.operator.aggregation.state.GenericLongState.isNull()" because "state" is null

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#10314]
When running `TestJoinQueries#testSemiJoinWithGroupBy` locally I'm hitting (sometimes):
```
java.lang.NullPointerException: Cannot invoke "io.trino.operator.aggregation.state.GenericLongState.isNull()" because "state" is null
	at io.trino.operator.aggregation.AbstractMinMaxAggregationFunction.compareAndUpdateState(AbstractMinMaxAggregationFunction.java:246)
	at io.trino.operator.aggregation.AbstractMinMaxAggregationFunction.input(AbstractMinMaxAggregationFunction.java:205)
	at io.trino.$gen.minGroupedAccumulator_20211215_213907_1530.addInput(Unknown Source)
	at io.trino.operator.aggregation.builder.InMemoryHashAggregationBuilder$Aggregator.processPage(InMemoryHashAggregationBuilder.java:385)
	at io.trino.operator.aggregation.builder.InMemoryHashAggregationBuilder.lambda$processPage$1(InMemoryHashAggregationBuilder.java:148)
	at io.trino.operator.TransformWork.process(TransformWork.java:44)
	at io.trino.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:436)
	at io.trino.operator.Driver.processInternal(Driver.java:393)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_testversion____20211215_213734_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Exact line:
```
	at io.trino.testing.AbstractTestJoinQueries.testSemiJoinWithGroupBy(AbstractTestJoinQueries.java:1927)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
I think this might be related to https://github.com/trinodb/trino/pull/10183
This is most likely a bug

cc @dain

**Comment by sopel39** [comment]
I think this is release blocker as it suggest bug within engine

**Comment by dain** [comment]
Do you have a reproduction for this?  I can't reproduce it

**Comment by dain** [comment]
Looking at the stack, the only way I see we can get this problem is if the state instance passed to the input method is null.  Looking at the state compiler, the only way this is possible is if the state factory is returning null.  I put up this [PR](https://github.com/trinodb/trino/pull/10335) that verifies that none of the fields are null in the constructor, and I also replace the unsafe copy method with a copy constructor.  I don't think the state compiler or the copy constructor are causing this problem, but this change makes everything safer.

**Comment by sopel39** [comment]
@dain It occurs for me by running full TestJoinQueries test (it also fails for TestHiveDisttibutedJoinQueries). Running test individually doesn't fail

**Comment by sopel39** [comment]
I run tests again and I don't see failures anymore.

**Comment by sopel39** [comment]
Fixed by https://github.com/trinodb/trino/pull/10335

**Comment by sopel39** [comment]
I still see this:
```
java.lang.RuntimeException: Cannot invoke "io.trino.operator.aggregation.state.LongState.getValue()" because "state" is null

	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:505)
	at io.trino.memory.TestMemoryManager.testQueryMemoryPerNodeLimit(TestMemoryManager.java:377)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
	Suppressed: java.lang.Exception: SQL: SELECT COUNT(*), repeat(orderstatus, 1000) FROM orders GROUP BY 2
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:508)
		... 14 more
Caused by: java.lang.NullPointerException: Cannot invoke "io.trino.operator.aggregation.state.LongState.getValue()" because "state" is null
	at io.trino.operator.aggregation.CountAggregation.input(CountAggregation.java:36)
	at io.trino.$gen.countGroupedAccumulator_20220111_103949_49.addInput(Unknown Source)
	at io.trino.operator.aggregation.GroupedAggregator.processPage(GroupedAggregator.java:70)
	at io.trino.operator.aggregation.builder.InMemoryHashAggregationBuilder.lambda$processPage$1(InMemoryHashAggregationBuilder.java:146)
	at io.trino.operator.TransformWork.process(TransformWork.java:44)
	at io.trino.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:434)
	at io.trino.operator.Driver.processInternal(Driver.java:393)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_testversion____20220111_103948_27.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
`testQueryMemoryPerNodeLimit`
`testQueryUserMemoryLimit`

in tight memory situation

cc @dain

**Comment by sopel39** [comment]
This fails with java 15, works with 11

**Comment by martint** [comment]
I can't repro it with either 11 or 17

**Comment by sopel39** [comment]
It works for me with 17 too. I guess it's bug in Java 15.
