### ISSUE TITLE
Invalid date causes NullPointerException during SELECT in MemSQL

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#10320]
Steps to reproduce.
```
trino> CREATE TABLE memsql.tpch.test (c1 date);
trino> INSERT INTO memsql.tpch.test VALUES (date '-1234-01-01');
trino> SELECT * FROM memsql.tpch.test;

io.trino.spi.TrinoException: JDBC_ERROR
	at io.trino.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:299)
	at io.trino.plugin.jdbc.JdbcRecordCursor.getLong(JdbcRecordCursor.java:199)
	at io.trino.spi.connector.RecordPageSource.getNextPage(RecordPageSource.java:106)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_testversion____20211216_095406_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at io.trino.plugin.jdbc.StandardColumnMappings$1.readLong(StandardColumnMappings.java:408)
	at io.trino.plugin.jdbc.JdbcRecordCursor.getLong(JdbcRecordCursor.java:196)
	... 13 more
```

ResultSet.getString() returns 0000-00-00 and ResultSet.getObject(columnIndex, LocalDate.class) returns null, but ResultSet.wasNull() return false. It returned null when we were using `java.sql.Date`. MySQL seems fine.

**Comment by ebyhr** [comment]
Closing as #12235
