### ISSUE TITLE
Improve error message when verifyPredicate failed in SqlDataTypeTest

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#10338]
We should report the column position.
```sh
java.lang.AssertionError: [Rows] 
Expecting:
  <>
to contain exactly in any order:
  <[(found)]>
but could not find the following elements:
  <(found)>


	at io.trino.sql.query.QueryAssertions$QueryAssert.lambda$matches$2(QueryAssertions.java:346)
	at io.trino.sql.query.QueryAssertions$QueryAssert.matches(QueryAssertions.java:333)
	at io.trino.sql.query.QueryAssertions$QueryAssert.matches(QueryAssertions.java:328)
	at io.trino.testing.datatype.SqlDataTypeTest.verifyPredicate(SqlDataTypeTest.java:127)
	at io.trino.testing.datatype.SqlDataTypeTest.execute(SqlDataTypeTest.java:80)
	at io.trino.testing.datatype.SqlDataTypeTest.execute(SqlDataTypeTest.java:72)
```

**Comment by findepi** [comment]
Would
```diff
--- core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
+++ core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
@@ -336,7 +336,7 @@ public class QueryAssertions
                 }

                 ListAssert<MaterializedRow> assertion = assertThat(actual.getMaterializedRows())
-                        .as("Rows")
+                        .as("Rows for query [%s]", query)
                         .withRepresentation(ROWS_REPRESENTATION);
```

help?

**Comment by ebyhr** [comment]
@findepi Yes, reporting the query is also helpful.

**Comment by findepi** [comment]
@ebyhr see https://github.com/trinodb/trino/pull/10349
