### ISSUE TITLE
java.lang.UnsupportedOperationException: io.trino.spi.block.ByteArrayBlockBuilder

### ISSUE THREAD

**Issue by pangyifish** [trinodb/trino#10347]
Hi there, I'm stuck on the following exception after migrating from 350->366
```
java.lang.UnsupportedOperationException: io.trino.spi.block.ByteArrayBlockBuilder
	at io.trino.spi.block.BlockBuilder.writeLong(BlockBuilder.java:50)
	at io.trino.spi.block.SingleRowBlockWriter.writeLong(SingleRowBlockWriter.java:134)
	at io.trino.spi.block.LongArrayBlock.writePositionTo(LongArrayBlock.java:201)
	at io.trino.spi.block.RowBlockBuilder.appendStructureInternal(RowBlockBuilder.java:274)
	at io.trino.spi.block.AbstractRowBlock.writePositionTo(AbstractRowBlock.java:212)
	at io.trino.spi.type.RowType.appendTo(RowType.java:238)
	at io.trino.operator.project.MergePages$MergePagesTransformation.appendBlock(MergePages.java:218)
	at io.trino.operator.project.MergePages$MergePagesTransformation.appendPage(MergePages.java:208)
	at io.trino.operator.project.MergePages$MergePagesTransformation.process(MergePages.java:194)
	at io.trino.operator.project.MergePages$MergePagesTransformation.process(MergePages.java:135)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorOperatorAdapter.getOutput(WorkProcessorOperatorAdapter.java:188)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_366____20211219_085010_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The query:
```
In [18]: sql="""SELECT
    ...:                 id0,
    ...:                 MIN_BY(id1, time)
    ...:             FROM default.xxx
    ...:             GROUP BY 1
    ...:             """
```

but if I change it to 
```
In [18]: sql="""SELECT
    ...:                 id0,
    ...:                 MIN_BY(id1, time, 1)
    ...:             FROM default.xxx
    ...:             GROUP BY 1
    ...:             """
```
works fine.

create table statement: 
CREATE TABLE hive.default.xxx (
   nid bigint,
   id0 bigint,
   type varchar,
   id1 bigint,
   time bigint,
   source varchar,
   is_p boolean,
   is_t boolean,
   is_c boolean
)
WITH (
   external_location = 's3a://yyy',
   format = 'PARQUET'
)

**Comment by findepi** [comment]
> after migrating from 350->366

can you please narrow down the range, eg by testing with 360 or 364?

**Comment by findepi** [comment]
cc @raunaqmorarka @sopel39 @skrzypo987

**Comment by sopel39** [comment]
cc @dain

**Comment by findepi** [comment]
This is easily reproducible
```
$ docker rm -f trino; docker run --rm -it --name trino -p 8080:8080 trinodb/trino:366
```

```
$ bin/trino-cli
trino> SELECT custkey, min_by(totalprice, orderkey) FROM tpch.sf1.orders GROUP BY 1;

Query 20211220_111303_00003_m5n2t, FAILED, 1 node
http://localhost:8080/ui/query.html?20211220_111303_00003_m5n2t
Splits: 16 total, 0 done (0.00%)
CPU Time: 1.7s total,  768K rows/s,     0B/s, 55% active
Per Node: 1.4 parallelism, 1.07M rows/s,     0B/s
Parallelism: 1.4
Peak Memory: 0B
1.22 [1.31M rows, 0B] [1.07M rows/s, 0B/s]

Query 20211220_111303_00003_m5n2t failed: io.trino.spi.block.ByteArrayBlockBuilder
java.lang.UnsupportedOperationException: io.trino.spi.block.ByteArrayBlockBuilder
	at io.trino.spi.block.BlockBuilder.writeLong(BlockBuilder.java:50)
	at io.trino.spi.block.SingleRowBlockWriter.writeLong(SingleRowBlockWriter.java:134)
	at io.trino.spi.block.LongArrayBlock.writePositionTo(LongArrayBlock.java:201)
	at io.trino.spi.block.RowBlockBuilder.appendStructureInternal(RowBlockBuilder.java:274)
	at io.trino.spi.block.AbstractRowBlock.writePositionTo(AbstractRowBlock.java:212)
	at io.trino.spi.type.RowType.appendTo(RowType.java:238)
	at io.trino.operator.project.MergePages$MergePagesTransformation.appendBlock(MergePages.java:218)
	at io.trino.operator.project.MergePages$MergePagesTransformation.appendPage(MergePages.java:208)
	at io.trino.operator.project.MergePages$MergePagesTransformation.process(MergePages.java:194)
	at io.trino.operator.project.MergePages$MergePagesTransformation.process(MergePages.java:135)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorOperatorAdapter.getOutput(WorkProcessorOperatorAdapter.java:188)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_366____20211220_111204_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sopel39** [comment]
I think this is related to aggregation changes as `RowBlockBuilder` is involved as well as aggregation

**Comment by sopel39** [comment]
Cc @martint

**Comment by martint** [comment]
@dain is looking into this.

**Comment by pangyifish** [comment]
I still see this error when I do SQL like below in 367

```
select dt, MIN_BY(IF(uid IS NOT NULL, 1, 0),"time"
 ) AS is_employee from xxx group by 1
limit 1`
```

if I remove the group by, it works fine.

**Comment by findepi** [comment]
Continued at #10572
