### ISSUE TITLE
A NPE when starting product tests

### ISSUE THREAD

**Issue by ksobolew** [trinodb/trino#10366]
```
2021-12-21T10:59:08.839+0100	INFO	environment-listener-0	io.trino.tests.product.launcher.env.StatisticsFetcher	Started listening for container hadoop-master statistics stream...
2021-12-21T10:59:08.859+0100	WARN	docker-java-stream--385536058	io.trino.tests.product.launcher.env.StatisticsFetcher	Caught exception while processing statistics
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "com.github.dockerjava.api.model.MemoryStatsConfig.getMaxUsage()" is null
	at io.trino.tests.product.launcher.env.StatisticsFetcher.toStats(StatisticsFetcher.java:109)
	at io.trino.tests.product.launcher.env.StatisticsFetcher$StatisticsCallback.lambda$onNext$0(StatisticsFetcher.java:130)
	at java.base/java.util.concurrent.atomic.AtomicReference.getAndUpdate(AtomicReference.java:188)
	at io.trino.tests.product.launcher.env.StatisticsFetcher$StatisticsCallback.onNext(StatisticsFetcher.java:130)
	at io.trino.tests.product.launcher.env.StatisticsFetcher$StatisticsCallback.onNext(StatisticsFetcher.java:121)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onNext(AbstrAsyncDockerCmdExec.java:41)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder$JsonSink.accept(DefaultInvocationBuilder.java:315)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder$JsonSink.accept(DefaultInvocationBuilder.java:298)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:275)
	at java.base/java.lang.Thread.run(Thread.java:833)


2021-12-21T10:59:08.860+0100	INFO	docker-java-stream--385536058	io.trino.tests.product.launcher.env.StatisticsFetcher	Stopped listening for container hadoop-master stats
```

The PTs seem to work fine, so it's not fatal, but *something* is clearly broken.

**Comment by nineinchnick** [comment]
Can you add more details about your environment, like Docker version, OS, etc?

**Comment by ksobolew** [comment]
Sure, it's plain Docker Desktop on Mac (4.3.1 (72247), Engine: 20.10.11), Zulu Java 17

**Comment by findepi** [comment]
`memoryStats` fields are nullable. and my IDE indicates a warning here

 cc @wendigo

**Comment by findepi** [comment]
```
2022-01-10T11:09:09.796+0100	WARN	docker-java-stream--986236188	io.trino.tests.product.launcher.env.StatisticsFetcher	Caught exception while processing statistics
java.lang.NullPointerException
	at io.trino.tests.product.launcher.env.StatisticsFetcher.toStats(StatisticsFetcher.java:109)
	at io.trino.tests.product.launcher.env.StatisticsFetcher$StatisticsCallback.lambda$onNext$0(StatisticsFetcher.java:130)
	at java.base/java.util.concurrent.atomic.AtomicReference.getAndUpdate(AtomicReference.java:187)
	at io.trino.tests.product.launcher.env.StatisticsFetcher$StatisticsCallback.onNext(StatisticsFetcher.java:130)
	at io.trino.tests.product.launcher.env.StatisticsFetcher$StatisticsCallback.onNext(StatisticsFetcher.java:121)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onNext(AbstrAsyncDockerCmdExec.java:41)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder$JsonSink.accept(DefaultInvocationBuilder.java:315)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder$JsonSink.accept(DefaultInvocationBuilder.java:298)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:275)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

cc @wendigo
