### ISSUE TITLE
Flaky TestHiveFailureRecoveryMinIO.testExplainAnalyze

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#10363]
* https://github.com/trinodb/trino/runs/4586900892
* https://github.com/trinodb/trino/runs/4588858574

```
2021-12-21T00:15:56.7628764Z [ERROR] Tests run: 44, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2,429.722 s <<< FAILURE! - in TestSuite
2021-12-21T00:15:56.7631052Z [ERROR] io.trino.plugin.hive.TestHiveFailureRecoveryMinIO.testExplainAnalyze  Time elapsed: 67.267 s  <<< FAILURE!
2021-12-21T00:15:56.7633083Z java.lang.AssertionError: 
2021-12-21T00:15:56.7633520Z 
2021-12-21T00:15:56.7634096Z Expecting throwable message:
2021-12-21T00:15:56.7635740Z   <"Error closing remote buffer (http://127.0.0.1:41155/v1/task/20211220_234551_00323_w4uu6.1.0.0/results/0 - 3 failures, failure duration 10.05s, total failed request time 15.06s)">
2021-12-21T00:15:56.7636829Z to contain:
2021-12-21T00:15:56.7637445Z   <"Encountered too many errors talking to a worker node">
2021-12-21T00:15:56.7638022Z but did not.
2021-12-21T00:15:56.7638292Z 
2021-12-21T00:15:56.7638739Z Throwable that failed the check:
2021-12-21T00:15:56.7639098Z 
2021-12-21T00:15:56.7640705Z java.lang.RuntimeException: Error closing remote buffer (http://127.0.0.1:41155/v1/task/20211220_234551_00323_w4uu6.1.0.0/results/0 - 3 failures, failure duration 10.05s, total failed request time 15.06s)
2021-12-21T00:15:56.7642871Z 	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
2021-12-21T00:15:56.7645706Z 	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:520)
2021-12-21T00:15:56.7648492Z 	at io.trino.testing.AbstractTestFailureRecovery$FailureRecoveryAssert.execute(AbstractTestFailureRecovery.java:542)
2021-12-21T00:15:56.7651423Z 	at io.trino.testing.AbstractTestFailureRecovery$FailureRecoveryAssert.executeActual(AbstractTestFailureRecovery.java:528)
2021-12-21T00:15:56.7654779Z 	at io.trino.testing.AbstractTestFailureRecovery$FailureRecoveryAssert.executeActualNoRetries(AbstractTestFailureRecovery.java:513)
2021-12-21T00:15:56.7658082Z 	at io.trino.testing.AbstractTestFailureRecovery$FailureRecoveryAssert.lambda$failsWithoutRetries$8(AbstractTestFailureRecovery.java:644)
2021-12-21T00:15:56.7664482Z 	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
2021-12-21T00:15:56.7666723Z 	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:877)
2021-12-21T00:15:56.7668770Z 	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1306)
2021-12-21T00:15:56.7671010Z 	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1178)
2021-12-21T00:15:56.7674115Z 	at io.trino.testing.AbstractTestFailureRecovery$FailureRecoveryAssert.failsWithoutRetries(AbstractTestFailureRecovery.java:644)
2021-12-21T00:15:56.7676918Z 	at io.trino.testing.AbstractTestFailureRecovery.testSelect(AbstractTestFailureRecovery.java:209)
2021-12-21T00:15:56.7679502Z 	at io.trino.testing.AbstractTestFailureRecovery.testSelect(AbstractTestFailureRecovery.java:166)
2021-12-21T00:15:56.7683201Z 	at io.trino.testing.AbstractTestFailureRecovery.testSelect(AbstractTestFailureRecovery.java:161)
2021-12-21T00:15:56.7686391Z 	at io.trino.testing.AbstractTestFailureRecovery.testExplainAnalyze(AbstractTestFailureRecovery.java:302)
2021-12-21T00:15:56.7688925Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-12-21T00:15:56.7691529Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-12-21T00:15:56.7694630Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-21T00:15:56.7696623Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-21T00:15:56.7698625Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-12-21T00:15:56.7707833Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-12-21T00:15:56.7712486Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-12-21T00:15:56.7714328Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-12-21T00:15:56.7716934Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-12-21T00:15:56.7719521Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-12-21T00:15:56.7721746Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-12-21T00:15:56.7723653Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-12-21T00:15:56.7746022Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-12-21T00:15:56.7748265Z Caused by: io.trino.spi.TrinoTransportException: Error closing remote buffer (http://127.0.0.1:41155/v1/task/20211220_234551_00323_w4uu6.1.0.0/results/0 - 3 failures, failure duration 10.05s, total failed request time 15.06s)
2021-12-21T00:15:56.7750285Z 	at io.trino.operator.HttpPageBufferClient$2.onFailure(HttpPageBufferClient.java:523)
2021-12-21T00:15:56.7785280Z 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1074)
2021-12-21T00:15:56.7787788Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-12-21T00:15:56.7790765Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-12-21T00:15:56.7792396Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-12-21T00:15:56.7794392Z Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Idle timeout 5000 ms
2021-12-21T00:15:56.7796426Z 	at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:25)
2021-12-21T00:15:56.7810408Z 	at io.airlift.http.client.StatusResponseHandler.handleException(StatusResponseHandler.java:45)
2021-12-21T00:15:56.7813228Z 	at io.airlift.http.client.StatusResponseHandler.handleException(StatusResponseHandler.java:28)
2021-12-21T00:15:56.7815781Z 	at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:120)
2021-12-21T00:15:56.7818782Z 	at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:85)
2021-12-21T00:15:56.7829536Z 	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
2021-12-21T00:15:56.7832668Z 	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
2021-12-21T00:15:56.7835298Z 	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481)
2021-12-21T00:15:56.7838299Z 	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461)
2021-12-21T00:15:56.7840405Z 	at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:557)
2021-12-21T00:15:56.7842189Z 	at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:152)
2021-12-21T00:15:56.7843936Z 	at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:145)
2021-12-21T00:15:56.7845511Z 	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:264)
2021-12-21T00:15:56.7848089Z 	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:164)
2021-12-21T00:15:56.7849844Z 	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:819)
2021-12-21T00:15:56.7851970Z 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.abort(HttpConnectionOverHTTP.java:214)
2021-12-21T00:15:56.7858719Z 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:200)
2021-12-21T00:15:56.7864943Z 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onIdleExpired(HttpConnectionOverHTTP.java:160)
2021-12-21T00:15:56.7867869Z 	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:402)
2021-12-21T00:15:56.7869871Z 	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
2021-12-21T00:15:56.7871585Z 	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
2021-12-21T00:15:56.7873235Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-12-21T00:15:56.7874597Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-12-21T00:15:56.7876607Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
2021-12-21T00:15:56.7878389Z 	... 3 more
2021-12-21T00:15:56.7879247Z Caused by: java.util.concurrent.TimeoutException: Idle timeout 5000 ms
2021-12-21T00:15:56.7880058Z 	... 10 more
2021-12-21T00:15:56.7880367Z 
2021-12-21T00:15:56.7882542Z 	at io.trino.testing.AbstractTestFailureRecovery.lambda$testSelect$7(AbstractTestFailureRecovery.java:209)
2021-12-21T00:15:56.7885474Z 	at io.trino.testing.AbstractTestFailureRecovery$FailureRecoveryAssert.failsWithoutRetries(AbstractTestFailureRecovery.java:644)
2021-12-21T00:15:56.7888446Z 	at io.trino.testing.AbstractTestFailureRecovery.testSelect(AbstractTestFailureRecovery.java:209)
2021-12-21T00:15:56.7891199Z 	at io.trino.testing.AbstractTestFailureRecovery.testSelect(AbstractTestFailureRecovery.java:166)
2021-12-21T00:15:56.7894244Z 	at io.trino.testing.AbstractTestFailureRecovery.testSelect(AbstractTestFailureRecovery.java:161)
2021-12-21T00:15:56.7897450Z 	at io.trino.testing.AbstractTestFailureRecovery.testExplainAnalyze(AbstractTestFailureRecovery.java:302)
2021-12-21T00:15:56.7900130Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-12-21T00:15:56.7902549Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-12-21T00:15:56.7905538Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-21T00:15:56.7907714Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-12-21T00:15:56.7909486Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-12-21T00:15:56.7911369Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-12-21T00:15:56.7912789Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-12-21T00:15:56.7914333Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-12-21T00:15:56.7917005Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-12-21T00:15:56.7918973Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-12-21T00:15:56.7921680Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-12-21T00:15:56.7923800Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-12-21T00:15:56.7925124Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-12-21T00:15:56.7925610Z 
2021-12-21T00:15:57.4192352Z [INFO] 
2021-12-21T00:15:57.4193783Z [INFO] Results:
2021-12-21T00:15:57.4194569Z [INFO] 
2021-12-21T00:15:57.4195457Z [ERROR] Failures: 
2021-12-21T00:15:57.4234872Z [ERROR]   TestHiveFailureRecoveryMinIO>AbstractTestFailureRecovery.testExplainAnalyze:302->AbstractTestFailureRecovery.testSelect:161->AbstractTestFailureRecovery.testSelect:166->AbstractTestFailureRecovery.testSelect:209->AbstractTestFailureRecovery.lambda$testSelect$7:209 
2021-12-21T00:15:57.4239890Z Expecting throwable message:
2021-12-21T00:15:57.4241809Z   <"Error closing remote buffer (http://127.0.0.1:41155/v1/task/20211220_234551_00323_w4uu6.1.0.0/results/0 - 3 failures, failure duration 10.05s, total failed request time 15.06s)">
2021-12-21T00:15:57.4242888Z to contain:
2021-12-21T00:15:57.4243637Z   <"Encountered too many errors talking to a worker node">
2021-12-21T00:15:57.4244573Z but did not.
```

**Comment by sopel39** [comment]
Similar https://github.com/trinodb/trino/runs/4588991771?check_suite_focus=true,
```
2021-12-21T00:27:52.6001076Z [ERROR]   TestHiveFailureRecoveryMinIO>BaseTestHiveFailureRecovery.testInsertIntoNewPartitionBucketed:117->AbstractTestFailureRecovery.testTableModification:340->AbstractTestFailureRecovery.testTableModification:345->AbstractTestFailureRecovery.testNonSelect:366 » Runtime
2021-12-21T00:27:52.6010176Z [ERROR]   TestHiveFailureRecoveryMinIO>BaseTestHiveFailureRecovery.testReplaceExistingPartition:135->AbstractTestFailureRecovery.testTableModification:345->AbstractTestFailureRecovery.testNonSelect:366 » Runtime
```

**Comment by sopel39** [comment]
cc @arhimondr @losipiuk

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/4593209042?check_suite_focus=true

**Comment by losipiuk** [comment]
Excercise PR: https://github.com/trinodb/trino/pull/10372

**Comment by losipiuk** [comment]
Partial fix: https://github.com/trinodb/trino/pull/10383

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/4811814411

**Comment by losipiuk** [comment]
I will close this one as the remaining issue is the same as reported in https://github.com/trinodb/trino/issues/10631.
Actually the https://github.com/trinodb/trino/issues/10631 reports two issues. 
* One with timeout in `SqlQueryScheduler.scheduleRetry`. This one is fixed already
* The other with "Unable to add partitions because database or table" which matches https://github.com/trinodb/trino/runs/4811814411 linked by @ebyhr above.

The other issues reported here were fixed by @arhimondr in https://github.com/trinodb/trino/pull/10481
