### ISSUE TITLE
Add DataStax as Cassandra test environment

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#10444]
As far as I confirmed, `5.1.5` works without any changes, but `6.8.18` fails to start a query runner due to below messages:
```bash
2022-01-01T14:37:44.296+0900	ERROR	main	Bootstrap	Uncaught exception in thread main
java.lang.RuntimeException: Schema tpch not found
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:505)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:339)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:331)
	at io.trino.testing.QueryAssertions.copyTpchTables(QueryAssertions.java:323)
	at io.trino.plugin.cassandra.DataStaxQueryRunner.createScyllaQueryRunner(DataStaxQueryRunner.java:61)
	at io.trino.plugin.cassandra.DataStaxQueryRunner.main(DataStaxQueryRunner.java:86)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE IF NOT EXISTS customer AS SELECT * FROM tpch.tiny.customer
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:508)
		... 5 more
Caused by: io.trino.spi.connector.SchemaNotFoundException: Schema tpch not found
	at io.trino.plugin.cassandra.CassandraSession.getKeyspaceByCaseInsensitiveName(CassandraSession.java:274)
	at io.trino.plugin.cassandra.CassandraSession.getCaseSensitiveSchemaName(CassandraSession.java:154)
	at io.trino.plugin.cassandra.CassandraMetadata.createTable(CassandraMetadata.java:294)
	at io.trino.plugin.cassandra.CassandraMetadata.beginCreateTable(CassandraMetadata.java:278)
	at io.trino.spi.connector.ConnectorMetadata.beginCreateTable(ConnectorMetadata.java:528)
	at io.trino.metadata.MetadataManager.beginCreateTable(MetadataManager.java:955)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:253)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:197)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:100)
	at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:85)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:230)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:215)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:210)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:466)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:447)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:388)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20220101_053741_3.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: Current plan:
                Output[rows]
                │   Layout: [rows:bigint]
                └─ TableCommit[cassandra.tpch.customer]
                   │   Layout: [rows:bigint]
                   └─ LocalExchange[SINGLE] ()
                      │   Layout: [partialrows:bigint, fragment:varbinary]
                      └─ RemoteExchange[GATHER]
                         │   Layout: [partialrows:bigint, fragment:varbinary]
                         └─ TableWriter
                            │   Layout: [partialrows:bigint, fragment:varbinary]
                            │   custkey := custkey
                            │   name := name
                            │   address := address
                            │   nationkey := nationkey
                            │   phone := phone
                            │   acctbal := acctbal
                            │   mktsegment := mktsegment
                            │   comment := comment
                            └─ LocalExchange[SINGLE] ()
                               │   Layout: [custkey:bigint, name:varchar(25), address:varchar(40), nationkey:bigint, phone:varchar(15), acctbal:double, mktsegment:varchar(10), comment:varchar(117)]
                               └─ RemoteExchange[REPARTITION]
                                  │   Layout: [custkey:bigint, name:varchar(25), address:varchar(40), nationkey:bigint, phone:varchar(15), acctbal:double, mktsegment:varchar(10), comment:varchar(117)]
                                  └─ TableScan[tpch:tiny:customer]
                                         Layout: [custkey:bigint, name:varchar(25), address:varchar(40), nationkey:bigint, phone:varchar(15), acctbal:double, mktsegment:varchar(10), comment:varchar(117)]
                                         nationkey := tpch:nationkey
                                         mktsegment := tpch:mktsegment
                                         address := tpch:address
                                         phone := tpch:phone
                                         custkey := tpch:custkey
                                         name := tpch:name
                                         comment := tpch:comment
                                         acctbal := tpch:acctbal

		at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:91)
		... 12 more
```

https://hub.docker.com/r/datastax/dse-server

**Comment by kamil-rafalko** [comment]
@ebyhr Let me rewrite it in my own words. Do you want to add a new test runner in particular dse-server which will be run next to existing ones - latest Cassandra, Cassandra V3 and Scylla and in the same time adjust the connector to the latest version of dse-server because it doesn't work out of the box, is that right understanding?

**Comment by ebyhr** [comment]
@kamil-rafalko Depends on how DSE implementation is different from Apache Cassandra. If it's close to Cassandra, just adding a new version to  `CassandraServer` is enough. If it's much different and we can't reuse existing `CassandraServer` & `CassandraQueryRunner`, we will need to add such new lasses.

**Comment by kamil-rafalko** [comment]
@ebyhr Sounds, good. I think I can try closing this issue
