### ISSUE TITLE
Iceberg  Table is missing [metadata_location] property:tablename

### ISSUE THREAD

**Issue by yunfeng79** [trinodb/trino#10489]
trino 367 (trino 360 same error)

catalog:iceberg 
```
2022-01-06T19:15:56.004+0800    ERROR   SplitRunner-7-103       io.trino.execution.executor.TaskExecutor        Error processing Split 20220106_111555_00014_y9vix.2.0.0-0 SystemSplit{addresses=[192.168.0.128:40080]} (start = 2.434395212560186E9, wall = 90 ms, cpu = 0 ms, wait = 0 ms, calls = 1): ICEBERG_INVALID_METADATA: Table is missing [metadata_location] property: ods_received_data
io.trino.spi.TrinoException: Table is missing [metadata_location] property: ods_received_data
        at io.trino.plugin.iceberg.catalog.AbstractMetastoreTableOperations.refresh(AbstractMetastoreTableOperations.java:157)
        at io.trino.plugin.iceberg.catalog.AbstractMetastoreTableOperations.current(AbstractMetastoreTableOperations.java:132)
        at io.trino.plugin.iceberg.TrinoHiveCatalog.lambda$loadTable$9(TrinoHiveCatalog.java:319)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at io.trino.plugin.iceberg.TrinoHiveCatalog.loadTable(TrinoHiveCatalog.java:317)
        at io.trino.plugin.iceberg.IcebergMetadata.getTableMetadata(IcebergMetadata.java:595)
        at io.trino.plugin.iceberg.IcebergMetadata.listTableColumns(IcebergMetadata.java:368)
        at io.trino.spi.connector.ConnectorMetadata.streamTableColumns(ConnectorMetadata.java:311)
        at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.streamTableColumns(ClassLoaderSafeConnectorMetadata.java:341)
        at io.trino.metadata.MetadataManager.listTableColumns(MetadataManager.java:677)
        at io.trino.metadata.MetadataListing.listTableColumns(MetadataListing.java:178)
        at io.trino.connector.system.jdbc.ColumnJdbcTable.cursor(ColumnJdbcTable.java:263)
        at io.trino.connector.system.SystemPageSourceProvider$1.cursor(SystemPageSourceProvider.java:129)
        at io.trino.split.MappedRecordSet.cursor(MappedRecordSet.java:53)
        at io.trino.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
        at io.trino.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:108)
        at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:68)
        at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:268)
        at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:196)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:151)
        at io.trino.operator.Driver.processInternal(Driver.java:388)
        at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
        at io.trino.operator.Driver.tryWithLock(Driver.java:685)
        at io.trino.operator.Driver.processFor(Driver.java:285)
        at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
        at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
        at io.trino.$gen.Trino_367____20220106_111515_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findinpath** [comment]
Do you have a reproduction scenario for this issue?

Here is the related code used to throw the exception

https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractMetastoreTableOperations.java#L155-L158

A few questions to narrow down the issue:
How was the table created?
What table properties are currently available in the metastore?

**Comment by yunfeng79** [comment]
@findinpath 
create table
SET iceberg.catalog.hadoop_catalog.type=hadoop;
SET iceberg.catalog.hadoop_catalog.warehouse=hdfs://datacenter/iceberg/warehouse;

use dongxin;
CREATE external TABLE ods_received_data
STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
LOCATION 'hdfs://datacenter/iceberg/warehouse/dongxin/ods_received_data'
TBLPROPERTIES (
'iceberg.catalog'='hadoop_catalog'
);
