### ISSUE TITLE
kafka.timestamp-upper-bound-force-push-down-enabled not working

### ISSUE THREAD

**Issue by mapshen** [trinodb/trino#10494]
We use the trino kafka connector with `kafka.timestamp-upper-bound-force-push-down-enabled` set to true, but got the following error when running this query:
```
trino:default> select _timestamp from "<kafka-topic>" where _timestamp > timestamp '2022-01-06 16:00' limit 10;
Query 20220106_160320_00125_3ysgz failed: Cannot list splits for table '<kafka-topic>' reading topic '<kafka-topic>'
```

And the stack trace shows:
```
io.trino.spi.TrinoException: Cannot list splits for table '<kafka-topic>' reading topic '<kafka-topic>'
	at io.trino.plugin.kafka.KafkaSplitManager.getSplits(KafkaSplitManager.java:109)
	at io.trino.spi.connector.ConnectorSplitManager.getSplits(ConnectorSplitManager.java:47)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorSplitManager.getSplits(ClassLoaderSafeConnectorSplitManager.java:69)
	at io.trino.split.SplitManager.getSplits(SplitManager.java:95)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitScanAndFilter(DistributedExecutionPlanner.java:222)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:292)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:167)
	at io.trino.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitLimit(DistributedExecutionPlanner.java:399)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitLimit(DistributedExecutionPlanner.java:167)
	at io.trino.sql.planner.plan.LimitNode.accept(LimitNode.java:124)
	at io.trino.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:135)
	at io.trino.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:142)
	at io.trino.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:112)
	at io.trino.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:500)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:405)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_364_344_ga639a35_dirty____20220105_171958_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: The target time for partition <kafka-topic>-0 is -1. The target time cannot be negative.
	at org.apache.kafka.clients.consumer.KafkaConsumer.offsetsForTimes(KafkaConsumer.java:2091)
	at org.apache.kafka.clients.consumer.KafkaConsumer.offsetsForTimes(KafkaConsumer.java:2057)
	at io.trino.plugin.kafka.KafkaFilterManager.findOffsetsForTimestampGreaterOrEqual(KafkaFilterManager.java:176)
	at io.trino.plugin.kafka.KafkaFilterManager.lambda$getKafkaFilterResult$4(KafkaFilterManager.java:136)
	at io.trino.plugin.kafka.KafkaFilterManager.lambda$overridePartitionEndOffsets$9(KafkaFilterManager.java:196)
	at java.base/java.util.HashMap.forEach(HashMap.java:1337)
	at io.trino.plugin.kafka.KafkaFilterManager.overridePartitionEndOffsets(KafkaFilterManager.java:195)
	at io.trino.plugin.kafka.KafkaFilterManager.getKafkaFilterResult(KafkaFilterManager.java:135)
	at io.trino.plugin.kafka.KafkaSplitManager.getSplits(KafkaSplitManager.java:77)
	... 21 more
```

**Comment by hashhar** [comment]
Today timestamp pushdown for Kafka only works if the condition is an equality or a sorted-range (i.e. `=`, `IN` or `> AND <`). Open-ranges don't seem to work (`>` or `<`).

Can you check whether a query like `select _timestamp from "<kafka-topic>" where _timestamp > timestamp '2022-01-06 16:00' and _timestamp < current_timestamp limit 10;` works?

The offending code is https://github.com/trinodb/trino/blob/master/plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java#L203-L236

It leaves `low` set to `-1` in case of only an upper bound being present. This should be fixed by defaulting `low` and `high` to `0` (the minimum possible timestamp in Kafka unless somehow https://cwiki.apache.org/confluence/display/KAFKA/KIP-228+Negative+record+timestamp+support lands).

Would you be willing to submit a PR @mapshen? If not, I'll try to get to this over the next week.

**Comment by mapshen** [comment]
@hashhar apologies for the late response. It seems @murong00 beat me to it :)

That said, we have found out an edge case: say current time is  '2022-01-06 16:10' and messages came in the past 10 minutes, then query `select _timestamp from "<kafka-topic>" where _timestamp > timestamp '2022-01-06 16:00'` would trigger a full table scan instead of returning right away. Any idea on how we can fix this?

**Comment by mapshen** [comment]
Took a look at the code base. So when an offset is not be able to be located for a given timestamp, the default partition offset is returned as per https://github.com/trinodb/trino/blob/master/plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java#L173. In the case above, the `partitionBeginOffsets` is set to the beginning of each partition and the `partitionEndOffsets` is to the end of each partition, so that a full scan is triggered.

This behavior might make sense when the query is like `select _timestamp from "<kafka-topic>" where _timestamp > timestamp '1970-01-01 16:00'` but in reality, no such query should be written in the first place. A full scan is an extremely expensive operation against large partitions. @hashhar any thoughts on better handling this?

**Comment by hashhar** [comment]
That's a limitation of the API Kafka provides and the history of the timestamp field in Kafka messages. `offsetsForTimes` should return the earliest offset with timestamp <= requested timestamp. However not all messages need to have timestamps or topic version could be old without timestamps.

In those cases assuming `null` to mean that no matching messages are found would lead to correctness issues.
