### ISSUE TITLE
No factory for connector 'postgresql'

### ISSUE THREAD

**Issue by AVSuni** [trinodb/trino#10491]
Hi, I am trying to deploy trino on k8s with Trino's official charts. I have added the following to values.yaml

```
additionalCatalogs: {
          "postgresql": 
          connector.name=postgresql
          connection-url=jdbc:postgresql://mypostgres:5432/mydb
          connection-user=postgres
          connection-password=postgresSuperUserPsw
        }
```

I get 

```
ERROR   main    io.trino.server.Server  No factory for connector 'postgresql connection-url=jdbc:postgresql://mypostgres:5432/mydb connection-user=postgres connection-password=postgresSuperUserPsw'.  Available factories: [hive, memory, kudu, blackhole, kinesis, redis, accumulo, gsheets, raptor-legacy, elasticsearch, jmx, postgresql, redshift, sqlserver, localfile, tpch, iceberg, mysql, bigquery, memsql, prometheus, mongodb, example-http, pinot, tpcds, oracle, trino-thrift, phoenix, system, druid, cassandra, clickhouse, kafka, atop, hive-hadoop2, phoenix5]
java.lang.IllegalArgumentException: No factory for connector 'postgresql connection-url=jdbc:postgresql://mypostgres:5432/mydb connection-user=postgres connection-password=postgresSuperUserPsw'.  Available factories: [hive, memory, kudu, blackhole, kinesis, redis, accumulo, gsheets, raptor-legacy, elasticsearch, jmx, postgresql, redshift, sqlserver, localfile, tpch, iceberg, mysql, bigquery, memsql, prometheus, mongodb, example-http, pinot, tpcds, oracle, trino-thrift, phoenix, system, druid, cassandra, clickhouse, kafka, atop, hive-hadoop2, phoenix5]
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435)
        at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:231)
        at io.trino.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
        at io.trino.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
        at io.trino.server.Server.doStart(Server.java:125)
        at io.trino.server.Server.lambda$start$0(Server.java:78)
        at io.trino.$gen.Trino_367____20220106_141512_1.run(Unknown Source)
        at io.trino.server.Server.start(Server.java:78)
        at io.trino.server.TrinoServer.main(TrinoServer.java:38)
```

Any ideas as to where to go from here? There isn't much documentation on Trino/K8s. Many thanks

**Comment by hashhar** [comment]
Your values.yml is getting rendered as a single line. Notice the error message:

> `No factory for connector 'postgresql connection-url=jdbc:postgresql://mypostgres:5432/mydb connection-user=postgres connection-password=postgresSuperUserPsw'`

Can you try the below:

```yaml
additionalCatalogs:
  postgresql: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://mypostgres:5432/mydb
    connection-user=postgres
    connection-password=postgresSuperUserPsw
```

Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there on #troubleshooting. We try to keep GitHub issues limited to bugs. However feel free to re-open this and continue here.
