### ISSUE TITLE
Trino fails to read double in Parquet  - java.lang.IllegalArgumentException: valuePosition 230100 must be equal to readOffset 231423 

### ISSUE THREAD

**Issue by cozos** [trinodb/trino#10517]
When running the following query on Trino 364:
```
SELECT
  sum(my_parquet_data.price)
FROM
  my_parquet_data
WHERE
  my_parquet_data.name = 'abc'
```

```
java.lang.IllegalArgumentException: valuePosition 230100 must be equal to readOffset 231423
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:303)
	at io.trino.parquet.reader.PrimitiveColumnReader.seek(PrimitiveColumnReader.java:337)
	at io.trino.parquet.reader.PrimitiveColumnReader.readPrimitive(PrimitiveColumnReader.java:212)
	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:370)
	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:444)
	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:427)
	at io.trino.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:224)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:396)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:375)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:282)
	at io.trino.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.setupDictionaryBlockProjection(DictionaryAwarePageProjection.java:211)
	at io.trino.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.lambda$getResult$0(DictionaryAwarePageProjection.java:197)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:396)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:375)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:282)
	at io.trino.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:346)
	at io.trino.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:209)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:151)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1078)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_364____20220110_090017_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The table in Trino:

```
 CREATE TABLE hive.default.my_parquet_data (                                       
    name varchar COMMENT '',                                                              
    price double COMMENT ''                                                     
)                                                                                       
 WITH (                                                                                  
    external_location = 'gs://arwintio-dev/my_parquet_data', 
    format = 'PARQUET'                                                                   
 )
```

The parquet file:
```
parquet-tools meta my-parquet-data.snappy.parquet
file:          file:/Users/arwin.tio/scratchpad/my-parquet-data.snappy.parquet 
creator:       parquet-mr version 1.12.0 (build db75a6815f2ba1d1ee89d1a90aeb296f1f3a8f20) 
extra:         org.apache.spark.version = 3.2.0 

file schema:   spark_schema 
--------------------------------------------------------------------------------
name:           OPTIONAL BINARY L:STRING R:0 D:1
price:           OPTIONAL DOUBLE R:0 D:1
```

Some observations:

- I changed the table name and column names and removed some columns (didn't want to expose company data)
- The query works if the `WHERE` clause is removed
- Pruning the other columns (not shown here) away also fixes the problem

Any idea what's happening here and how to debug?

**Comment by cozos** [comment]
Hello @raunaqmorarka it looks like upgrading to 367 fixed the problem. Thanks for the help!
