### ISSUE TITLE
planning infinite in some cases

### ISSUE THREAD

**Issue by ImTangYun** [trinodb/trino#10532]
bad case:
create table tmp.plan_debug as select 1 as uid;
select uid from tmp.plan_debug where uid > 0 and (uid not between 1 and 3)
![plan-bug](https://user-images.githubusercontent.com/5945486/148871170-39c11b95-fbcb-48bd-b6a4-fa45bf9144f0.png)

When I ran sqls as above, i found that the second sql will stay on planning stage until planning timeout.
Here is my pr of fixing it:
https://github.com/trinodb/trino/pull/10531

**Comment by findepi** [comment]
Reproducible in 367

```
docker rm -f trino; docker run --rm -it --name trino -p 8080:8080 trinodb/trino:367
```

```
$ bin/trino-cli
trino> USE memory.default;
    -> create table plan_debug as select 1 as uid;
    -> select uid from plan_debug
    -> where uid > 0 and (uid not between 1 and 3);
USE
CREATE TABLE: 1 row

Query 20220111_104601_00008_dqw5g, FINISHED, 1 node
http://localhost:8080/ui/query.html?20220111_104601_00008_dqw5g
Splits: 11 total, 11 done (100.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 100% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
Peak Memory: 0B
0.23 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20220111_104602_00010_dqw5g failed: The optimizer exhausted the time limit of 180000 ms
io.trino.spi.TrinoException: The optimizer exhausted the time limit of 180000 ms
	at io.trino.sql.planner.iterative.IterativeOptimizer$Context.checkTimeoutNotExhausted(IterativeOptimizer.java:318)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:148)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:124)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:109)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:230)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:215)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:210)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:466)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:447)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:388)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_367____20220111_104259_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

With https://github.com/trinodb/trino/pull/10543 on current master, using shorter timeout i get:

```
$ bin/trino-cli
trino> USE memory.default;
    -> SET SESSION iterative_optimizer_timeout = '5s';
    -> DROP TABLE IF EXISTS plan_debug;
    -> create table plan_debug as select 1 as uid;
    -> select uid from plan_debug
    -> where uid > 0 and (uid not between 1 and 3);

[...]

Query 20220111_114348_00055_sdtzh failed: The optimizer exhausted the time limit of 5000 ms: Top rules: {
		io.trino.sql.planner.iterative.rule.RemoveRedundantTableScanPredicate@2047adea: 3021 ms, 12778 invocations, 12778 applications,
		io.trino.sql.planner.iterative.rule.ExpressionRewriteRuleSet$FilterExpressionRewrite@29699283: 1191 ms, 12778 invocations, 12777 applications,
		io.trino.sql.planner.iterative.rule.ExpressionRewriteRuleSet$FilterExpressionRewrite@4272d8cf: 329 ms, 12778 invocations, 0 applications }
```

**Comment by findepi** [comment]
Relates to #9267 cc @martint

**Comment by findepi** [comment]
per stacktrace pasted above, it's a loop between `SimplifyExpressions` and `RemoveRedundantTableScanPredicate`.

**Comment by ImTangYun** [comment]
> Can you please specify the version of Trino ? Is it seen in master or ?

I just ran on 363

**Comment by findepi** [comment]
@ImTangYun it's reproducible in 367 and current master too.

**Comment by martint** [comment]
The problem happens because:

1. In RemoveRedundantTableScanPredicate, the line `new DomainTranslator(plannerContext).toPredicate(session, unenforcedDomain.transformKeys(assignments::get))`  produces an expression of the form `((("uid" > 0) AND ("uid" < 1)) OR ("uid" > 3))`. When passed through SimplifyExpressions, the last term gets distributed into the first term by `extractCommonPredicates` to produce `((("uid" > 0) OR ("uid" > 3)) AND (("uid" < 1) OR ("uid" > 3)))`

2. The SimplifyExpression rule gets invoked with `((("uid" > 0) OR ("uid" > 3)) AND (("uid" < 1) OR ("uid" > 3)))`. In `extractCommonPredicates`, it extracts `("uid" > 3)` as the common predicate, combines it to form `(("uid" > 3) OR (("uid" > 0) AND ("uid" < 1)))` and then distributes the first term into the second term for produce `((("uid" > 3) OR ("uid" > 0)) AND (("uid" > 3) OR ("uid" < 1)))`

**Comment by martint** [comment]
Fundamentally, the problem happens because `RemoveRedundantTableScanPredicate` is firing when it shouldn't. In the example above, there are no pushed-down predicates, and the rule is simply changing the filter expression from `((("uid" > 3) OR ("uid" > 0)) AND (("uid" > 3) OR ("uid" < 1)))` to `((("uid" > 0) OR ("uid" > 3)) AND (("uid" < 1) OR ("uid" > 3)))`, even though there's no reason to do so.

**Comment by martint** [comment]
We need a more robust way to determine whether a predicate is redundant with respect to another predicate. Currently, RemoveRedundantTableScanPredicate works by extracting a summary structure from the predicate (TupleDomain), combining it with the TupleDomain from the TableScan, converting it back to an IR expression and hoping that it will produce the same structure if the table scan predicate was a no-op.

One possible approach would be to walk the predicate expression tree bottom up and check whether each subexpression is "covered" by the TableScan predicate. If so, replace it with "true", otherwise, continue up the stack.

**Comment by sopel39** [comment]
I've made PR that fixes this holistically: https://github.com/trinodb/trino/pull/10985
