### ISSUE TITLE
Not able to authenticate with LDAP

### ISSUE THREAD

**Issue by rdagur** [trinodb/trino#10533]
I am trying to integrate trino with LDAP. Configurations are given below 

  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    http-server.https.enabled=true
    http-server.https.port=8443
    http-server.authentication.type=PASSWORD
    http-server.https.keystore.path=/etc/trinonew.pem
    query.max-memory=8GB
    query.max-memory-per-node=4GB
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080
    jmx.rmiregistry.port=9080
    jmx.rmiserver.port=9081

  password-authenticator.properties: |
    password-authenticator.name=ldap
    ldap.url=ldap://url-of-ldap-server:389
    ldap.allow-insecure=true
    ldap.bind-dn=CN=svc-account,OU=Users,OU=JP,OU=APAC,OU=Earth,DC=test,DC=abc-test,DC=jp
    ldap.bind-password=somepassword
    ldap.user-base-dn=OU=JP,OU=APAC,OU=Earth,DC=test,DC=abc-test,DC=jp
    ldap.group-auth-pattern=(&(objectClass=person)(sAMAccountName=${USER})(memberof=CN=hello-sadmin-os,OU=Groups,OU=JP,OU=APAC,OU=Earth,DC=test,DC=abc-test,DC=jp))
    ldap.user-bind-pattern=CN=${USER},OU=Users,OU=JP,OU=APAC,OU=earth,DC=test,DC=abc-test,DC=jp

**Getting below authentication error while connecting to ldap :** 

$trino --server https://localhost:8443 --keystore-path /etc/trinonew.pem --user rohit.dagur-a --password
Password:

  trino> show catalogs;
Error running command: Error starting query at https://localhost:8443/v1/statement returned an invalid response: JsonResponse{statusCode=500, statusMessage=Internal Server Error, headers={content-length=[6283], content-type=[text/plain], date=[Mon, 10 Jan 2022 15:17:44 GMT]}, hasValue=false} [Error: java.lang.RuntimeException: Authentication error
  at io.trino.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:64)
  at io.trino.server.security.AuthenticationFilter.filter(AuthenticationFilter.java:86)
  at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)
  at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)
  at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
  at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:269)
  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
  at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
  at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
  at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
  at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
  at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
  at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
  at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:717)
  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
  at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
  at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  at org.eclipse.jetty.server.Server.handle(Server.java:501)
  at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
  at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272)
  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
  at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:543)
  at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:398)
  at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
  at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
  at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
  at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Authentication error
  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
  at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
  at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
  at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
  at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4941)
  at io.trino.plugin.password.ldap.LdapAuthenticator.createAuthenticatedPrincipal(LdapAuthenticator.java:102)
  at io.trino.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:51)
  ... 59 more
Caused by: java.lang.RuntimeException: Authentication error
  at io.trino.plugin.password.ldap.LdapAuthenticator.authenticateWithBindDistinguishedName(LdapAuthenticator.java:157)
  at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
  at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
  at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
  ... 65 more
]

**Comment by rdagur** [comment]
It was due to connection issue. By putting IP of ldap server instead of hostname in ldap.url property, it is working.
ldap.url=ldap://IP of ldap server:389
