### ISSUE TITLE
keyBlock and valueBlock has different size: 14906 14864

### ISSUE THREAD

**Issue by ImTangYun** [trinodb/trino#10569]
Table schama:
```
CREATE TABLE hive.tmp.tangyun_test_parquet (
   client_version varchar,
   event ROW(time bigint, lng bigint, lat bigint, net varchar, log_extra map(varchar, varchar), event_id varchar, event_info map(varchar, varchar))
)
WITH (
   external_location = 'hdfs://cluster/user/tangyun/test/test_parquet',
   format = 'PARQUET'
)
```

In path hdfs://cluster/user/test/test/test_parquet there is a parquet file, you can get it by my wechat imcandycloud

when I ran sql below:
```
SELECT event.event_info['watch_time'] AS watchTime 
FROM tmp.tangyun_test_parquet2 
WHERE client_version = '4856'
```

I get exception:
```
java.lang.IllegalArgumentException: keyBlock and valueBlock has different size: 14906 14864
    at io.trino.spi.block.MapBlock.validateConstructorArguments(MapBlock.java:122)
    at io.trino.spi.block.MapBlock.fromKeyValueBlock(MapBlock.java:59)
    at io.trino.spi.type.MapType.createBlockFromKeyValue(MapType.java:271)
    at io.trino.parquet.reader.ParquetReader.readMap(ParquetReader.java:311)
    at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:438)
    at io.trino.parquet.reader.ParquetReader.readStruct(ParquetReader.java:325)
    at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:435)
    at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:427)
    at io.trino.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:224)
    at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:396)
    at io.trino.spi.block.LazyBlock$LazyData.getTopLevelBlock(LazyBlock.java:365)
    at io.trino.spi.block.LazyBlock.getBlock(LazyBlock.java:270)
    at io.trino.spi.block.LazyBlock.isNull(LazyBlock.java:253)
    at io.trino.$gen.PageFilter_20220111_033759_1522.filter(Unknown Source)
    at io.trino.$gen.PageFilter_20220111_033759_1522.filter(Unknown Source)
    at io.trino.operator.project.PageProcessor.createWorkProcessor(PageProcessor.java:121)
    at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.lambda$processPageSource$1(ScanFilterAndProjectOperator.java:293)
    at io.trino.operator.WorkProcessorUtils.lambda$flatMap$4(WorkProcessorUtils.java:245)
    at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
    at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
    at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
    at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
    at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
    at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
    at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
    at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
    at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
    at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
    at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
    at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
    at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
    at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
    at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
    at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
    at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
    at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
    at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
    at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
    at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:151)
    at io.trino.operator.Driver.processInternal(Driver.java:388)
    at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
    at io.trino.operator.Driver.tryWithLock(Driver.java:685)
    at io.trino.operator.Driver.processFor(Driver.java:285)
    at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
    at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
    at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
    at io.trino.$gen.Trino_363_35_g8e888af____20220111_031016_2.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

this exception does not exists in version of prestosql 324

**Comment by findepi** [comment]
Is the problem reproducible on vanilla Trino 368, without your custom modifications?

**Comment by ImTangYun** [comment]
> Is the problem reproducible on vanilla Trino 368, without your custom modifications?

I don't have 368, i'll try when i have time

**Comment by ImTangYun** [comment]
368 works well in this case

**Comment by findepi** [comment]
Thanks for checking.
