### ISSUE TITLE
Aggregations min_by/max_by failing with java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by sshkvar** [trinodb/trino#10572]
Hi we are upgrading from Trino 363 to 367 (the same issue in 368),

during version upgrade we have faced issue which is blocking us, after upgrade  a lot of scheduled jobs failed with 

```
java.lang.UnsupportedOperationException: io.trino.spi.block.IntArrayBlockBuilder
	at io.trino.spi.block.BlockBuilder.writeBytes(BlockBuilder.java:58)
	at io.trino.spi.block.SingleRowBlockWriter.writeBytes(SingleRowBlockWriter.java:142)
	at io.trino.spi.block.AbstractVariableWidthBlock.writeBytesTo(AbstractVariableWidthBlock.java:120)
	at io.trino.spi.block.AbstractVariableWidthBlock.writePositionTo(AbstractVariableWidthBlock.java:126)
	at io.trino.spi.block.RowBlockBuilder.appendStructureInternal(RowBlockBuilder.java:274)
	at io.trino.spi.block.AbstractRowBlock.writePositionTo(AbstractRowBlock.java:212)
	at io.trino.spi.type.RowType.appendTo(RowType.java:238)
	at io.trino.operator.output.DefaultPagePartitioner.appendRow(DefaultPagePartitioner.java:237)
	at io.trino.operator.output.DefaultPagePartitioner.partitionPage(DefaultPagePartitioner.java:204)
	at io.trino.operator.output.PartitionedOutputOperator.addInput(PartitionedOutputOperator.java:304)
	at io.trino.operator.Driver.processInternal(Driver.java:393)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_testversion____20220112_131929_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

issue can be reproduced with really simple test

```java
    @Test
    public void testMaxBy()
    {
        assertUpdate("create table max_by_test as select 'a' as user_name, 'b' as status, 1 as order_value", 1);
        assertQuery("select user_name, max_by(status,order_value) as results from max_by_test group by 1");
    }
```

Appreciate for help

**Comment by findepi** [comment]
Confirmed 368 is affected with:

```
docker rm -f trino; docker run --rm -it --name trino -p 8080:8080 trinodb/trino:368
```

```
$ bin/trino-cli
USE memory.default;
drop table if exists max_by_test;
create table max_by_test as select 'a' as user_name, 'b' as status, 1 as order_value;
select user_name, max_by(status,order_value) as results from max_by_test group by 1;

Query 20220112_142627_00005_yxgug failed: io.trino.spi.block.IntArrayBlockBuilder
java.lang.UnsupportedOperationException: io.trino.spi.block.IntArrayBlockBuilder
	at io.trino.spi.block.BlockBuilder.writeLong(BlockBuilder.java:50)
	at io.trino.spi.block.SingleRowBlockWriter.writeLong(SingleRowBlockWriter.java:134)
	at io.trino.spi.block.LongArrayBlock.writePositionTo(LongArrayBlock.java:201)
	at io.trino.spi.block.RowBlockBuilder.appendStructureInternal(RowBlockBuilder.java:274)
	at io.trino.spi.block.AbstractRowBlock.writePositionTo(AbstractRowBlock.java:212)
	at io.trino.spi.type.RowType.appendTo(RowType.java:238)
	at io.trino.operator.output.DefaultPagePartitioner.appendRow(DefaultPagePartitioner.java:237)
	at io.trino.operator.output.DefaultPagePartitioner.partitionPage(DefaultPagePartitioner.java:204)
	at io.trino.operator.output.PartitionedOutputOperator.addInput(PartitionedOutputOperator.java:304)
	at io.trino.operator.Driver.processInternal(Driver.java:393)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_368____20220112_142617_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

cc @dain
