### ISSUE TITLE
Flaky TestMemoryManager.testClusterPools

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#10573]
`ci / test (:trino-tests)` job fails in flaky manner.

```
Error:  io.trino.memory.TestMemoryManager.testClusterPools  Time elapsed: 6.353 s  <<< FAILURE!
java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.assertNotEquals(Assert.java:832)
	at org.testng.Assert.assertNotEquals(Assert.java:837)
	at io.trino.memory.TestMemoryManager.testClusterPools(TestMemoryManager.java:288)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Observed in https://github.com/trinodb/trino/actions/runs/1686942253

**Comment by findepi** [comment]
cc @sopel39  per https://github.com/trinodb/trino/commit/9da468a13699a816a3e7ff9d41b8f77f5e118a15

**Comment by findepi** [comment]
The flakiness can be reproduced locally, semi-reliably, with `invocationCount = 100`.

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/4795599935?check_suite_focus=true

**Comment by sopel39** [comment]
I cannot repro locally, but https://github.com/trinodb/trino/pull/10589 should fix it
