### ISSUE TITLE
java.lang.UnsupportedOperationException: io.trino.spi.block.IntArrayBlockBuilder

### ISSUE THREAD

**Issue by pangyifish** [trinodb/trino#10582]
similar error to https://github.com/trinodb/trino/issues/10347

I still see this error when I do SQL like below in 367

```
select dt, MIN_BY(IF(uid IS NOT NULL, 1, 0),"time"
 ) AS is_employee from xxx group by 1
limit 1
```
if I remove the group by, it works fine.

stack trace:

```
2022-01-13T01:42:07.393Z        ERROR   stage-scheduler io.trino.execution.StageStateMachine    Stage 20220113_014206_06989_9hgb5.2 failed
java.lang.UnsupportedOperationException: io.trino.spi.block.IntArrayBlockBuilder
        at io.trino.spi.block.BlockBuilder.writeLong(BlockBuilder.java:50)
        at io.trino.spi.block.SingleRowBlockWriter.writeLong(SingleRowBlockWriter.java:134)
        at io.trino.spi.block.LongArrayBlock.writePositionTo(LongArrayBlock.java:201)
        at io.trino.spi.block.RowBlockBuilder.appendStructureInternal(RowBlockBuilder.java:274)
        at io.trino.spi.block.AbstractRowBlock.writePositionTo(AbstractRowBlock.java:212)
        at io.trino.spi.type.RowType.appendTo(RowType.java:238)
        at io.trino.operator.output.DefaultPagePartitioner.appendRow(DefaultPagePartitioner.java:237)
        at io.trino.operator.output.DefaultPagePartitioner.partitionPage(DefaultPagePartitioner.java:204)
        at io.trino.operator.output.PartitionedOutputOperator.addInput(PartitionedOutputOperator.java:304)
        at io.trino.operator.Driver.processInternal(Driver.java:393)
        at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
        at io.trino.operator.Driver.tryWithLock(Driver.java:685)
        at io.trino.operator.Driver.processFor(Driver.java:285)
        at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
        at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
        at io.trino.$gen.Trino_367____20220112_232656_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by martint** [comment]
Are you able to reproduce the error in 368?

**Comment by pangyifish** [comment]
> Are you able to reproduce the error in 368?

Yes, just tried.

**Comment by pangyifish** [comment]
might be the same issue as https://github.com/trinodb/trino/issues/10572

**Comment by findepi** [comment]
Closing in favor of #10572
