### ISSUE TITLE
Cannot create a table (as select) with array type in PostgreSQL

### ISSUE THREAD

**Issue by egor-ryashin** [trinodb/trino#10637]
I try this:
```
create table "postgresql"."public"."test__dbt_tmp"

  as (


with
lmt as (
	select * from postgresql.public.temp_out limit 10
)
select account_id, array_agg(c_id) as ag from lmt group by account_id
  )
```
produces
```
io.trino.spi.TrinoException: Unsupported column type: array(bigint)
	at io.trino.plugin.postgresql.PostgreSqlClient.toWriteMapping(PostgreSqlClient.java:706)
	at io.trino.plugin.jdbc.BaseJdbcClient.getColumnDefinitionSql(BaseJdbcClient.java:526)
	at io.trino.plugin.jdbc.BaseJdbcClient.createTable(BaseJdbcClient.java:497)
	at io.trino.plugin.jdbc.BaseJdbcClient.beginCreateTable(BaseJdbcClient.java:467)
	at io.trino.plugin.jdbc.ForwardingJdbcClient.beginCreateTable(ForwardingJdbcClient.java:177)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$beginCreateTable$22(StatisticsAwareJdbcClient.java:238)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.beginCreateTable(StatisticsAwareJdbcClient.java:238)
	at io.trino.plugin.jdbc.CachingJdbcClient.beginCreateTable(CachingJdbcClient.java:421)
	at io.trino.plugin.jdbc.CachingJdbcClient.beginCreateTable(CachingJdbcClient.java:421)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.beginCreateTable(DefaultJdbcMetadata.java:628)
	at io.trino.spi.connector.ConnectorMetadata.beginCreateTable(ConnectorMetadata.java:528)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.beginCreateTable(ClassLoaderSafeConnectorMetadata.java:485)
	at io.trino.metadata.MetadataManager.beginCreateTable(MetadataManager.java:955)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:253)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:197)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:100)
	at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:85)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:230)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:215)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:210)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:466)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:447)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:388)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_367____20220116_101859_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: Current plan:
                Output[rows]
                │   Layout: [rows:bigint]
                └─ TableCommit[postgresql.public.test__dbt_tmp]
                   │   Layout: [rows:bigint]
                   └─ LocalExchange[SINGLE] ()
                      │   Layout: [partialrows:bigint, fragment:varbinary]
                      └─ RemoteExchange[GATHER]
                         │   Layout: [partialrows:bigint, fragment:varbinary]
                         └─ TableWriter
                            │   Layout: [partialrows:bigint, fragment:varbinary]
                            │   account_id := account_id
                            │   ag := array_agg
                            └─ LocalExchange[SINGLE] ()
                               │   Layout: [account_id:bigint, array_agg:array(bigint)]
                               └─ RemoteExchange[REPARTITION]
                                  │   Layout: [account_id:bigint, array_agg:array(bigint)]
                                  └─ Aggregate(FINAL)[account_id]
                                     │   Layout: [account_id:bigint, array_agg:array(bigint)]
                                     │   array_agg := array_agg("array_agg_0")
                                     └─ LocalExchange[SINGLE] ()
                                        │   Layout: [account_id:bigint, array_agg_0:array(bigint)]
                                        └─ Project[]
                                           │   Layout: [account_id:bigint, array_agg_0:array(bigint)]
                                           └─ RemoteExchange[REPARTITION][$hashvalue]
                                              │   Layout: [account_id:bigint, array_agg_0:array(bigint), $hashvalue:bigint]
                                              └─ Project[]
                                                 │   Layout: [account_id:bigint, array_agg_0:array(bigint), $hashvalue_1:bigint]
                                                 │   $hashvalue_1 := combine_hash(bigint '0', COALESCE("$operator$hash_code"("account_id"), 0))
                                                 └─ Aggregate(PARTIAL)[account_id]
                                                    │   Layout: [account_id:bigint, array_agg_0:array(bigint)]
                                                    │   array_agg_0 := array_agg("c_id")
                                                    └─ TableScan[postgresql:public.temp_out public.temp_out limit=10 columns=[account_id:bigint:int8, c_id:bigint:int8]]
                                                           Layout: [account_id:bigint, c_id:bigint]
                                                           account_id := account_id:bigint:int8
                                                           c_id := c_id:bigint:int8

		at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:91)
		... 12 more
```

I can run without errors in psql client:
```
  create table test_a as select account_id, array_agg(c_id) from (select * from temp_out limit 10) a group by account_id;
```

**Comment by hashhar** [comment]
By default arrays are not mapped. See https://trino.io/docs/current/connector/postgresql.html#array-type-handling to learn how to enable ARRAY support in PostgreSQL connector.

**Comment by hashhar** [comment]
Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there in case you still run into issues.
