### ISSUE TITLE
[BUG] IllegalArgumentException: Too large (1510752245 expected elements with load factor 0.75)

### ISSUE THREAD

**Issue by zhengxingmao** [trinodb/trino#10649]
Trino version is 365 . When running big dataset (10TB) TPC-DS Query test met this error . 
`java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.trino.sql.gen.JoinCompiler$LookupSourceSupplierFactory.createLookupSourceSupplier(JoinCompiler.java:1043)
	at io.trino.operator.PagesIndex.createLookupSourceSupplier(PagesIndex.java:508)
	at io.trino.operator.join.HashBuilderOperator.buildLookupSource(HashBuilderOperator.java:603)
	at io.trino.operator.join.HashBuilderOperator.finishLookupSourceUnspilling(HashBuilderOperator.java:578)
	at io.trino.operator.join.HashBuilderOperator.finish(HashBuilderOperator.java:477)
	at io.trino.operator.Driver.processInternal(Driver.java:370)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_360_39_g65c37f9_dirty____20211008_024247_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException: undefined
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.trino.sql.gen.JoinCompiler$LookupSourceSupplierFactory.createLookupSourceSupplier(JoinCompiler.java:1040)
	... 15 more
Caused by: java.lang.IllegalArgumentException: Too large (1510752245 expected elements with load factor 0.75)
	at it.unimi.dsi.fastutil.HashCommon.arraySize(HashCommon.java:222)
	at io.trino.operator.join.PagesHash.<init>(PagesHash.java:64)
	at io.trino.operator.join.JoinHashSupplier.<init>(JoinHashSupplier.java:72)
	... 20 more`

**Comment by zhengxingmao** [comment]
And here is SQL
select  a.ca_state state, count(*) cnt
 from customer_address a
     ,customer c
     ,store_sales s
     ,date_dim d
     ,item i
 where       a.ca_address_sk = c.c_current_addr_sk
 	and c.c_customer_sk = s.ss_customer_sk
 	and s.ss_sold_date_sk = d.d_date_sk
 	and s.ss_item_sk = i.i_item_sk
 	and d.d_month_seq = 
 	     (select distinct (d_month_seq)
 	      from date_dim
               where d_year = 2000
 	        and d_moy = 2 )
 	and i.i_current_price > 1.2 * 
             (select avg(j.i_current_price) 
 	     from item j 
 	     where j.i_category = i.i_category)
 group by a.ca_state
 having count(*) >= 10
 order by cnt, a.ca_state 
 limit 100;

**Comment by jerryleooo** [comment]
I guess it is related to https://github.com/trinodb/trino/pull/5440/

**Comment by jotarada** [comment]
Hi, I'm facing the same issue. is there any advices?

**Comment by zhengxingmao** [comment]
what's version?

**Comment by hashhar** [comment]
Generally this means that you have enough data that Trino needed to build a hashtable with more than 2 billion entries. The solution is to add more worker nodes or change query shape to avoid large aggregation (for example moving the filter before the aggregation).

**Comment by jotarada** [comment]
Version 400

**Comment by zhengxingmao** [comment]
We end up optimizing SQL to avoid this problem. There are several reasons for this problem: 1. The SQL execution plan is not optimal; 2. There is skew in the data.What SQL statement are you running?

**Comment by futureltl** [comment]
> We end up optimizing SQL to avoid this problem. There are several reasons for this problem: 1. The SQL execution plan is not optimal; 2. There is skew in the data.What SQL statement are you running?

I am wondering how to optimze the mentioned SQL, can you show it.
