### ISSUE TITLE
Fix flaky TestClickHouseConnectorSmokeTest.testRenameSchema

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#10653]
```
Error:  io.trino.plugin.clickhouse.TestClickHouseConnectorSmokeTest.testRenameSchema  Time elapsed: 0.05 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting code to raise a throwable.
	at io.trino.plugin.clickhouse.TestClickHouseConnectorSmokeTest.testRenameSchema(TestClickHouseConnectorSmokeTest.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

https://github.com/trinodb/trino/runs/4849619566

**Comment by ebyhr** [comment]
We should specify minor version here. 
>     public static final String DEFAULT_VERSION = "20.8";

**Comment by ebyhr** [comment]
#10672 https://github.com/trinodb/trino/runs/4862267419
