### ISSUE TITLE
Flaky TestMemoryManager.testClusterPools

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#10684]
```
 java.lang.AssertionError: expected [966350171] but found [966367642]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:284)
	at org.testng.Assert.assertEquals(Assert.java:294)
	at io.trino.memory.TestMemoryManager.testClusterPools(TestMem
```

**Comment by sopel39** [comment]
I cannot repro it locally

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/runs/4863393673?check_suite_focus=true

**Comment by sopel39** [comment]
This should be fixed by https://github.com/trinodb/trino/issues/6677

**Comment by sopel39** [comment]
Closed by https://github.com/trinodb/trino/issues/6677
