### ISSUE TITLE
io.trino.util.TestTimeZoneUtils.testNamedZones seems to be flaky

### ISSUE THREAD

**Issue by homar** [trinodb/trino#10693]
I saw it failing with:
`java.lang.IllegalArgumentException: The datetime zone id 'Pacific/Kanton' is not recognised
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:247)
	at io.trino.util.TestTimeZoneUtils.testNamedZones(TestTimeZoneUtils.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

I tried to reproduce it but without success

**Comment by ebyhr** [comment]
It's already fixed in #10679. (1 hour ago in master)

**Comment by homar** [comment]
Oh I didn't see it,thanks
