### ISSUE TITLE
Inserting in Iceberg $properties table doesn't work

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#10701]
`$properties` Iceberg metadata table has been recently added in https://github.com/trinodb/trino/pull/10480

```
create table iceberg.default.test1
(
    c_int integer
);


insert into iceberg.default."test1$properties" values ('my-prop', 'my-value');
```

```
 Query failed (#20220120_060956_00008_xi99v): class io.trino.connector.system.SystemTableHandle cannot be cast to class io.trino.plugin.iceberg.IcebergTableHandle (io.trino.connector.system.SystemTableHandle is in unnamed module of loader 'app'; io.trino.plugin.iceberg.IcebergTableHandle is in unnamed module of loader io.trino.server.PluginClassLoader @66075347)
```

**Comment by findepi** [comment]
The system tables are supposed to be read-only

> Query failed (#20220120_061815_00010_xi99v): This connector does not support updates

Who threw that? SystemTablesMetadata? 

>  Query failed (#20220120_060956_00008_xi99v): class io.trino.connector.system.SystemTableHandle cannot be cast to class io.trino.plugin.iceberg.IcebergTableHandle (io.trino.connector.system.SystemTableHandle is in unnamed module of loader 'app'; io.trino.plugin.iceberg.IcebergTableHandle is in unnamed module of loader io.trino.server.PluginClassLoader @66075347)

That looks like a bug in the engine.

**Comment by findinpath** [comment]
For the update statement I see the following stacktrace:

```
2022-01-20T20:21:03.493+0100	ERROR	pool-69-thread-1	io.trino.plugin.httpquery.HttpEventListener	QueryId = "20220120_192053_00018_qwmuz", attempt = 1/1, URL = http://localhost:8090 | Error sending HTTP request
java.io.UncheckedIOException: Server refused connection: http://localhost:8090
	at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:19)
	at io.airlift.http.client.StatusResponseHandler.handleException(StatusResponseHandler.java:45)
	at io.airlift.http.client.StatusResponseHandler.handleException(StatusResponseHandler.java:28)
	at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:120)
	at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:85)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:276)
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:247)
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:164)
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:819)
	at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:502)
	at org.eclipse.jetty.client.HttpDestination.failed(HttpDestination.java:252)
	at org.eclipse.jetty.client.AbstractConnectionPool$FutureConnection.failed(AbstractConnectionPool.java:557)
	at org.eclipse.jetty.util.Promise$Wrapper.failed(Promise.java:136)
	at org.eclipse.jetty.client.HttpClient$1$1.failed(HttpClient.java:633)
	at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.connectFailed(AbstractConnectorHttpClientTransport.java:138)
	at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport$ClientSelectorManager.connectionFailed(AbstractConnectorHttpClientTransport.java:188)
	at org.eclipse.jetty.io.ManagedSelector$Connect.failed(ManagedSelector.java:966)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:369)
	at org.eclipse.jetty.io.ManagedSelector.access$1700(ManagedSelector.java:65)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:676)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:535)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:362)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:186)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
	at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:355)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:347)
	... 10 more
```

Here is the stacktrace of the TrinoException thrown from the analyzer for the UPDATE statement

```
022-01-20T20:24:18.650+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr	io.trino.spi.TrinoException: 
2022-01-20T20:24:18.651+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.spi.connector.ConnectorMetadata.getUpdateRowIdColumnHandle(ConnectorMetadata.java:612)
2022-01-20T20:24:18.651+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.metadata.MetadataManager.getUpdateRowIdColumnHandle(MetadataManager.java:1013)
2022-01-20T20:24:18.652+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1552)
2022-01-20T20:24:18.652+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:405)
2022-01-20T20:24:18.653+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.tree.Table.accept(Table.java:60)
2022-01-20T20:24:18.653+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
2022-01-20T20:24:18.653+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:422)
2022-01-20T20:24:18.654+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.analyzer.StatementAnalyzer.analyzeForUpdate(StatementAnalyzer.java:391)
2022-01-20T20:24:18.654+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitUpdate(StatementAnalyzer.java:2464)
2022-01-20T20:24:18.655+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitUpdate(StatementAnalyzer.java:405)
2022-01-20T20:24:18.655+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.tree.Update.accept(Update.java:77)
2022-01-20T20:24:18.655+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
2022-01-20T20:24:18.656+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:422)
2022-01-20T20:24:18.656+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:385)
2022-01-20T20:24:18.657+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
2022-01-20T20:24:18.657+0100	INFO	Query-20220120_192306_00019_qwmuz-447	stderr		at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
```
