### ISSUE TITLE
Uncaught overflow in decimal multiplication

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#10732]
Query completes successfully even though the multiplication overflows:

```
trino> SELECT DECIMAL '12345678901234567890123456789012345678' * DECIMAL '9'  > 5;
 _col0
-------
 true
```

indeed, this doesn't fail with "Decimal overflow".
```
io.trino.type.DecimalOperators.multiplyLongShortLong(Int128.valueOf("12345678901234567890123456789012345678"), 9)
```

**Comment by findepi** [comment]
This is a regression since 367, the query used to be failing

```
trino> SELECT DECIMAL '12345678901234567890123456789012345678' * DECIMAL '9'  > 5;
Query 20220121_150142_00000_dipkg failed: Decimal overflow
io.trino.spi.TrinoException: Decimal overflow
	at io.trino.type.DecimalOperators.multiplyLongShortLong(DecimalOperators.java:323)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:735)
	at io.trino.sql.InterpretedFunctionInvoker.invoke(InterpretedFunctionInvoker.java:101)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.invokeOperator(ExpressionInterpreter.java:1413)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitArithmeticBinary(ExpressionInterpreter.java:766)
	at io.trino.sql.tree.ArithmeticBinaryExpression.accept(ArithmeticBinaryExpression.java:85)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processWithExceptionHandling(ExpressionInterpreter.java:301)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processComparisonExpression(ExpressionInterpreter.java:830)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitComparisonExpression(ExpressionInterpreter.java:800)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitComparisonExpression(ExpressionInterpreter.java:793)
	at io.trino.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:71)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processWithExceptionHandling(ExpressionInterpreter.java:301)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitRow(ExpressionInterpreter.java:1315)
	at io.trino.sql.tree.Row.accept(Row.java:54)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processWithExceptionHandling(ExpressionInterpreter.java:301)
	at io.trino.sql.planner.ExpressionInterpreter.evaluate(ExpressionInterpreter.java:267)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitValues(LocalExecutionPlanner.java:2027)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitValues(LocalExecutionPlanner.java:843)
	at io.trino.sql.planner.plan.ValuesNode.accept(ValuesNode.java:131)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:931)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:843)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:539)
	at io.trino.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:460)
	at io.trino.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:79)
	at io.trino.execution.SqlTask.updateTask(SqlTask.java:448)
	at io.trino.execution.SqlTaskManager.doUpdateTask(SqlTaskManager.java:417)
	at io.trino.execution.SqlTaskManager.lambda$updateTask$6(SqlTaskManager.java:381)
	at io.trino.$gen.Trino_367____20220121_150134_2.call(Unknown Source)
```
