### ISSUE TITLE
Inconsistent handling of invalid literals within in `try(...)`

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#10755]
### observed

This catches the error

```
trino> SELECT try(JSON 'x');
 _col0
-------
 NULL
```

The behavior is even test-covered at https://github.com/trinodb/trino/blob/c0276cea688da155f7f5bf0cb0b53169ece43e6e/testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java#L5443

however, it's not consistently applied to other literals:

```
trino> SELECT try(DECIMAL '1.2.3');
Query 20220124_091251_00002_v4784 failed: Invalid decimal value '1.2.3'
java.lang.IllegalArgumentException: Invalid decimal value '1.2.3'
	at io.trino.spi.type.Decimals.parse(Decimals.java:91)
	at io.trino.spi.type.Decimals.parse(Decimals.java:78)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitDecimalLiteral(ExpressionAnalyzer.java:1019)
```

```
trino> SELECT try(TIMESTAMP 'right now');
Query 20220124_091326_00004_v4784 failed: line 1:12: 'right now' is not a valid timestamp literal
io.trino.spi.TrinoException: line 1:12: 'right now' is not a valid timestamp literal
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitTimestampLiteral(ExpressionAnalyzer.java:1098)
```

**Comment by findepi** [comment]
### expected

All literal forms are validated, regardless of `try`.
`try` remains to catch "runtime" errors.
