### ISSUE TITLE
SQL Server metadata listing may fail with "Transaction was deadlocked on lock resources with another process" in case of concurrent table creation/deletion

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#10846]

**Comment by findepi** [comment]
This causes `TestSqlServerConnectorTest>BaseConnectorTest.testSelectInformationSchemaColumns` to be flaky
https://github.com/trinodb/trino/runs/5345450918?check_suite_focus=true

cc @ebyhr

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8265006163/job/22609848003?pr=21050

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/10608699623/job/29403442313
```
Error:  io.trino.plugin.sqlserver.TestSqlServerConnectorTest.testBulkColumnListingOptions -- Time elapsed: 1.899 s <<< FAILURE!
java.lang.AssertionError: Failure for bulkListColumns false
	at io.trino.plugin.jdbc.BaseJdbcConnectorTest.testBulkColumnListingOptions(BaseJdbcConnectorTest.java:1582)
	at io.trino.plugin.jdbc.BaseJdbcConnectorTest.testBulkColumnListingOptions(BaseJdbcConnectorTest.java:1563)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1489)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2071)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2033)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: org.opentest4j.AssertionFailedError: 
Expecting message to be:
  "Error listing table columns for catalog sqlserver: The requested column listing mode is not supported"
but was:
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: io.trino.spi.TrinoException: An error occurred during the current command (Done status 0). Transaction (Process ID 53) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at io.trino.plugin.jdbc.BaseJdbcClient.getAllTableComments(BaseJdbcClient.java:221)
	at io.trino.plugin.jdbc.BaseJdbcClient.getTableNames(BaseJdbcClient.java:192)
	at io.trino.plugin.jdbc.ForwardingJdbcClient.getTableNames(ForwardingJdbcClient.java:84)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getTableNames$2(StatisticsAwareJdbcClient.java:105)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:34)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getTableNames(StatisticsAwareJdbcClient.java:105)
	at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getTableNames$2(CachingJdbcClient.java:172)
	at io.trino.cache.EmptyCache.get(EmptyCache.java:94)
	at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:793)
	at io.trino.plugin.jdbc.CachingJdbcClient.getTableNames(CachingJdbcClient.java:172)
	at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getTableNames$2(CachingJdbcClient.java:172)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4903)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3574)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2316)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4017)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4898)
	at io.trino.cache.EvictableCache.get(EvictableCache.java:118)
	at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:793)
	at io.trino.plugin.jdbc.CachingJdbcClient.getTableNames(CachingJdbcClient.java:172)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.listTables(DefaultJdbcMetadata.java:1056)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.lambda$listTableColumns$21(DefaultJdbcMetadata.java:1077)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.listTableColumns(DefaultJdbcMetadata.java:1077)
	at io.trino.spi.connector.ConnectorMetadata.streamTableColumns(ConnectorMetadata.java:323)
	at io.trino.spi.connector.ConnectorMetadata.streamRelationColumns(ConnectorMetadata.java:344)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.streamRelationColumns(DefaultJdbcMetadata.java:1095)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.streamRelationColumns(ClassLoaderSafeConnectorMetadata.java:338)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.streamRelationColumns(ClassLoaderSafeConnectorMetadata.java:102)
	at io.trino.tracing.TracingConnectorMetadata.streamRelationColumns(TracingConnectorMetadata.java:313)
	at io.trino.metadata.MetadataManager.listTableColumns(MetadataManager.java:667)
	at io.trino.tracing.TracingMetadata.listTableColumns(TracingMetadata.java:356)
	at io.trino.metadata.MetadataListing.doListTableColumns(MetadataListing.java:261)
	at io.trino.metadata.MetadataListing.listTableColumns(MetadataListing.java:251)
	... 48 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: An error occurred during the current command (Done status 0). Transaction (Process ID 53) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:270)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer$FetchBufferTokenHandler.onDone(SQLServerResultSet.java:5455)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:103)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:42)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5558)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1821)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1079)
	at io.trino.plugin.jdbc.BaseJdbcClient.getAllTableComments(BaseJdbcClient.java:209)
	... 82 more

	at io.trino.plugin.jdbc.BaseJdbcConnectorTest.testBulkColumnListingOptions(BaseJdbcConnectorTest.java:1600)
	at io.trino.plugin.jdbc.BaseJdbcConnectorTest.testBulkColumnListingOptions(BaseJdbcConnectorTest.java:1579)
	... 8 more
```

Note: The error comes from `ResultSet.next()` in `BaseJdbcClient#getAllTableComments`:

https://github.com/trinodb/trino/blob/4e07ebfb38d5c96d00303e9e6c22673bdd60e857/plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java#L202-L228
