### ISSUE TITLE
Query failure when IS NOT NULL predicate used on information_schema

### ISSUE THREAD

**Issue by takezoe** [trinodb/trino#10861]
The following query fails on the latest master.
```sql
select * from information_schema.columns where table_schema is not null;
```
Full stacktrace:
```
java.lang.IllegalStateException: undefined
	at com.google.common.base.Preconditions.checkState(Preconditions.java:486)
	at io.trino.connector.informationschema.InformationSchemaMetadata.filterString(InformationSchemaMetadata.java:429)
	at io.trino.connector.informationschema.InformationSchemaMetadata.calculatePrefixesWithSchemaName(InformationSchemaMetadata.java:315)
	at io.trino.connector.informationschema.InformationSchemaMetadata.getPrefixes(InformationSchemaMetadata.java:231)
	at io.trino.connector.informationschema.InformationSchemaMetadata.applyFilter(InformationSchemaMetadata.java:203)
	at io.trino.metadata.MetadataManager.applyFilter(MetadataManager.java:1726)
	at io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan.pushFilterIntoTableScan(PushPredicateIntoTableScan.java:222)
	at io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan.apply(PushPredicateIntoTableScan.java:102)
	at io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan.apply(PushPredicateIntoTableScan.java:68)
	at io.trino.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:202)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:169)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:132)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:235)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:134)
	at io.trino.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:117)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:230)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:215)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:210)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:474)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:455)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:396)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_dev____20220131_083155_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
For sure, this predicate is meaningless because table_name will never be NULL but this query worked on at least 317. The root cause is https://github.com/trinodb/trino/commit/625712ba24fd547180326ea754394dd9a660ebb4 introduced in 319.

**Comment by findepi** [comment]
@takezoe are you planning on making a PR with a fix?

**Comment by takezoe** [comment]
Actually, I don't know what is the right way to fix this issue.

**Comment by takezoe** [comment]
Oh, just removing a status check was fine. Thank you!
