### ISSUE TITLE
TestOrcPageSourceMemoryTracking.testScanFilterAndProjectOperator   seems to be very flaky

### ISSUE THREAD

**Issue by homar** [trinodb/trino#10883]
Recently it fails quite often with:

`2022-01-31T16:18:08.6072441Z [ERROR] io.trino.plugin.hive.TestOrcPageSourceMemoryTracking.testScanFilterAndProjectOperator  Time elapsed: 0.098 s  <<< FAILURE!
2022-01-31T16:18:08.6073156Z java.lang.AssertionError: expected [true] but found [false]
2022-01-31T16:18:08.6073556Z 	at org.testng.Assert.fail(Assert.java:94)
2022-01-31T16:18:08.6073965Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2022-01-31T16:18:08.6074375Z 	at org.testng.Assert.assertTrue(Assert.java:42)
2022-01-31T16:18:08.6074764Z 	at org.testng.Assert.assertTrue(Assert.java:52)
2022-01-31T16:18:08.6075524Z 	at io.trino.plugin.hive.TestOrcPageSourceMemoryTracking.testScanFilterAndProjectOperator(TestOrcPageSourceMemoryTracking.java:470)
2022-01-31T16:18:08.6076380Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-01-31T16:18:08.6077061Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-01-31T16:18:08.6077819Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-01-31T16:18:08.6078418Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-01-31T16:18:08.6079002Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-01-31T16:18:08.6079597Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-01-31T16:18:08.6080093Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-01-31T16:18:08.6080688Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-01-31T16:18:08.6081239Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-01-31T16:18:08.6081793Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-01-31T16:18:08.6082353Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-01-31T16:18:08.6082939Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-01-31T16:18:08.6083396Z 	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by homar** [comment]
Already addressed.
