### ISSUE TITLE
Flaky TestIcebergParquetConnectorTest.testLocalDynamicFilteringWithSelectiveBuildSizeJoin

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#10932]
This looks like a general issue instead of test only.

```
Error:  io.trino.plugin.iceberg.TestIcebergParquetConnectorTest.testLocalDynamicFilteringWithSelectiveBuildSizeJoin  Time elapsed: 0.791 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting:
 <2L>
to be equal to:
 <3L>
but was not.
	at io.trino.plugin.iceberg.BaseIcebergConnectorTest.testLocalDynamicFilteringWithSelectiveBuildSizeJoin(BaseIcebergConnectorTest.java:2743)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Observed in https://github.com/trinodb/trino/runs/5048547902?check_suite_focus=true

cc: @raunaqmorarka

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/5104560238

**Comment by findepi** [comment]
It's very flaky. Apparently 8 of 30 runs failed in  ​https://github.com/trinodb/trino/actions/runs/1807712651

cc @alexjo2144 @sopel39 @raunaqmorarka

**Comment by sopel39** [comment]
I see comment:
```
        // Assert no split level pruning occurs. If this starts failing a new totalprice
```
do we need to adjust totalproce (cc @alexjo2144 )?

**Comment by alexjo2144** [comment]
We could remove the test and add a more targeted IcebergPageSource test. Testing this scenario through a query consistently is probably going to be hard.

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/5107360728?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/5116347006?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/5124513060?check_suite_focus=true

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/5195864837?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/5212722692?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/5833064777?check_suite_focus=true

```
Error:  Tests run: 854, Failures: 1, Errors: 0, Skipped: 9, Time elapsed: 1,111.916 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.iceberg.TestIcebergOrcConnectorTest.testLocalDynamicFilteringWithSelectiveBuildSizeJoin  Time elapsed: 0.954 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting:
 <60175L>
to be less than:
 <60175L> 
	at io.trino.plugin.iceberg.BaseIcebergConnectorTest.testLocalDynamicFilteringWithSelectiveBuildSizeJoin(BaseIcebergConnectorTest.java:2715)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/6379609139

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/runs/6496491229?check_suite_focus=true

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/runs/6660809653

**Comment by hashhar** [comment]
https://github.com/trinodb/trino/actions/runs/2432989983

**Comment by alexjo2144** [comment]
I didn't realize it had been reopened, I'll take another look

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/6827578303?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/10614 may be related, see https://github.com/trinodb/trino/pull/10614/files#r894610627

cc @radek-starburst @alexjo2144 @arhimondr

**Comment by radek-starburst** [comment]
It may be related. However, it occurred before scale-writes was merged.

**Comment by ebyhr** [comment]
The test was renamed in https://github.com/trinodb/trino/pull/12829 and removed in https://github.com/trinodb/trino/pull/13233

**Comment by kokosing** [comment]
Thank you!
