### ISSUE TITLE
Error when reading JSON table with TIMESTAMP:java.lang.ClassCastException: class java.sql.Timestamp cannot be cast to class java.lang.Number

### ISSUE THREAD

**Issue by zigbang-yeezy** [trinodb/trino#10961]
Hi, I'm getting the below error when SELECT query in hive(AWS glue) json table
```
java.lang.ClassCastException: class java.sql.Timestamp cannot be cast to class java.lang.Number (java.sql.Timestamp is in module java.sql of loader 'platform'; java.lang.Number is in module java.base of loader 'bootstrap')
	at io.trino.plugin.hive.GenericHiveRecordCursor.getLongExpressedValue(GenericHiveRecordCursor.java:306)
	at io.trino.plugin.hive.GenericHiveRecordCursor.parseLongColumn(GenericHiveRecordCursor.java:290)
	at io.trino.plugin.hive.GenericHiveRecordCursor.parseColumn(GenericHiveRecordCursor.java:548)
	at io.trino.plugin.hive.GenericHiveRecordCursor.isNull(GenericHiveRecordCursor.java:505)
	at io.trino.plugin.hive.HiveRecordCursor.isNull(HiveRecordCursor.java:211)
	at io.trino.spi.connector.RecordPageSource.getNextPage(RecordPageSource.java:96)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:682)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_369____20220126_101517_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
Through the above error, I found the following issue.
https://github.com/trinodb/trino/issues/5602
Referring to this article, I changed the json serde of the table to org.apache.hive.hcatalog.data.jsonSerDe.(https://github.com/trinodb/trino/issues/5602#issuecomment-714297025)

After that, I looked up the table again and faced another error.
`Cannot create timestamp, parsing error`
Is there any way to change the existing row so that it can be viewed without modifying it?

This is a problem only in trino versions above 360. In the existing 339 version, rows are shown without problems.

**Comment by zigbang-yeezy** [comment]
#10961

**Comment by zigbang-yeezy** [comment]
#5638
