### ISSUE TITLE
Flaky test TestMemoryManager.testOutOfMemoryKiller

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#11016]
```
Error:  io.trino.memory.TestMemoryManager.testOutOfMemoryKiller  Time elapsed: 6.675 s  <<< FAILURE!
java.lang.AssertionError: expected object to not be null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.assertNotNull(Assert.java:423)
	at org.testng.Assert.assertNotNull(Assert.java:408)
	at io.trino.memory.TestMemoryManager.waitForQueryToBeKilled(TestMemoryManager.java:156)
	at io.trino.memory.TestMemoryManager.testOutOfMemoryKiller(TestMemoryManager.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Unrelated. Wasn't able to reproduce with 100 runs.

_Originally posted by @hashhar in https://github.com/trinodb/trino/issues/10996#issuecomment-1035931902_

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/5838149587?check_suite_focus=true
