### ISSUE TITLE
How can i extract data from json {'G/B':"G"}

### ISSUE THREAD

**Issue by sjx782392329** [trinodb/trino#11058]
I use Prestosql v344
There is my error information
```java
presto> select json_extract('{"G/B":"B", "GB":"G"}', '$.G/B');
Query 20220216_073544_18044_zfcct failed: Invalid JSON path: '$.G/B'
io.prestosql.spi.PrestoException: Invalid JSON path: '$.G/B'
	at io.prestosql.operator.scalar.JsonPathTokenizer.invalidJsonPath(JsonPathTokenizer.java:196)
	at io.prestosql.operator.scalar.JsonPathTokenizer.computeNext(JsonPathTokenizer.java:69)
	at io.prestosql.operator.scalar.JsonPathTokenizer.computeNext(JsonPathTokenizer.java:26)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:272)
	at io.prestosql.operator.scalar.JsonExtract.generateExtractor(JsonExtract.java:154)
	at io.prestosql.operator.scalar.JsonExtract.generateExtractor(JsonExtract.java:149)
	at io.prestosql.operator.scalar.JsonPath.<init>(JsonPath.java:30)
	at io.prestosql.operator.scalar.JsonFunctions.castVarcharToJsonPath(JsonFunctions.java:69)
	at io.prestosql.$gen.PageProjectionWork_20220216_073544_12984698.evaluate(Unknown Source)
	at io.prestosql.$gen.PageProjectionWork_20220216_073544_12984698.process(Unknown Source)
	at io.prestosql.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:333)
	at io.prestosql.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:205)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorOperatorAdapter.getOutput(WorkProcessorOperatorAdapter.java:188)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_344____20211014_111936_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
I want to know how extract this data
Please help me~

**Comment by sjx782392329** [comment]
I don't know why slack archived the #general channel, I can't submit this problem in that

**Comment by ebyhr** [comment]
Try `$["G/B"]` 

```
trino> SELECT json_extract('{"G/B":"B", "GB":"G"}', '$["G/B"]');
 _col0
-------
 "B"
```

`#general` channel was renamed to `#begineer`
