### ISSUE TITLE
Flaky test TestIcebergParquetConnectorTest.testTargetMaxFileSize

### ISSUE THREAD

**Issue by puchengy** [trinodb/trino#11127]
I sometimes saw flaky test results for this test case in trino-iceberg module
```
[ERROR] Tests run: 806, Failures: 1, Errors: 0, Skipped: 7, Time elapsed: 1,402.258 s <<< FAILURE! - in TestSuite
[ERROR] io.trino.plugin.iceberg.TestIcebergParquetConnectorTest.testTargetMaxFileSize  Time elapsed: 0.215 s  <<< FAILURE!
java.lang.AssertionError:

Expecting:
 <125520L>
to be between:
 [1L, 122880L]

        at io.trino.plugin.iceberg.BaseIcebergConnectorTest.lambda$testTargetMaxFileSize$39(BaseIcebergConnectorTest.java:3370)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
        at io.trino.plugin.iceberg.BaseIcebergConnectorTest.testTargetMaxFileSize(BaseIcebergConnectorTest.java:3370)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

2022-02-21T13:06:56.604-0600 INFO JVM is shutting down, cleaning up
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestIcebergParquetConnectorTest>BaseIcebergConnectorTest.testTargetMaxFileSize:3370->BaseIcebergConnectorTest.lambda$testTargetMaxFileSize$39:3370
Expecting:
 <125520L>
to be between:
 [1L, 122880L]

[INFO]
[ERROR] Tests run: 806, Failures: 1, Errors: 0, Skipped: 7
```
This is based on Trino 371, with command `./mvn clean install -T 4`.

@homar could you take a look? Also I wonder how `isBetween(1L, maxSize.toBytes() * 3)` is decided? Thanks.

**Comment by hashhar** [comment]
Not seen for a very long time. Closing.
