### ISSUE TITLE
Flaky maven-checks is cancelled after 45 minutes

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#11131]
```
2022-02-21T02:33:37.9491812Z Feb 21, 2022 2:33:37 AM org.testcontainers.containers.GenericContainer tryStart
2022-02-21T02:33:37.9492728Z INFO: Container ghcr.io/trinodb/testing/centos7-oj11:latest started in PT42.47305S
2022-02-21T02:40:56.8310722Z Feb 21, 2022 2:40:56 AM io.airlift.log.Logger warn
2022-02-21T02:40:56.8311222Z WARNING: No test started or completed in 8.00m. Running tests:
2022-02-21T02:40:56.8313701Z 	io.trino.server.rpm.ServerIT running for 8.08m
2022-02-21T02:40:56.8314923Z 	io.trino.server.rpm.ServerIT::testUninstall running for 8.08m.
2022-02-21T02:40:56.8315440Z 
2022-02-21T02:40:56.8315816Z Full Thread Dump:
2022-02-21T02:40:56.8316687Z "main" prio=5 Id=1 WAITING on java.util.concurrent.CountDownLatch$Sync@8b97b27
2022-02-21T02:40:56.8317175Z 	at java.base@11.0.14/jdk.internal.misc.Unsafe.park(Native Method)
2022-02-21T02:40:56.8317970Z 	-  waiting on java.util.concurrent.CountDownLatch$Sync@8b97b27
2022-02-21T02:40:56.8318942Z 	at java.base@11.0.14/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
2022-02-21T02:40:56.8319678Z 	at java.base@11.0.14/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
2022-02-21T02:40:56.8320613Z 	at java.base@11.0.14/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
2022-02-21T02:40:56.8321570Z 	at java.base@11.0.14/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
2022-02-21T02:40:56.8322289Z 	at java.base@11.0.14/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
2022-02-21T02:40:56.8322958Z 	at app//com.github.dockerjava.api.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:91)
2022-02-21T02:40:56.8323744Z 	at app//org.testcontainers.containers.ExecInContainerPattern.execInContainer(ExecInContainerPattern.java:80)
2022-02-21T02:40:56.8324446Z 	at app//org.testcontainers.containers.ContainerState.execInContainer(ContainerState.java:235)
2022-02-21T02:40:56.8325105Z 	at app//org.testcontainers.containers.ContainerState.execInContainer(ContainerState.java:226)
2022-02-21T02:40:56.8325676Z 	at app//io.trino.server.rpm.ServerIT.testUninstall(ServerIT.java:73)
2022-02-21T02:40:56.8326196Z 	at java.base@11.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-02-21T02:40:56.8326826Z 	at java.base@11.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-02-21T02:40:56.8353127Z 	at java.base@11.0.14/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-02-21T02:40:56.8353721Z 	at java.base@11.0.14/java.lang.reflect.Method.invoke(Method.java:566)
2022-02-21T02:40:56.8354286Z 	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-02-21T02:40:56.8354946Z 	at app//org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-02-21T02:40:56.8355434Z 	at app//org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-02-21T02:40:56.8355924Z 	at app//org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-02-21T02:40:56.8356489Z 	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-02-21T02:40:56.8357058Z 	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-02-21T02:40:56.8357532Z 	at app//org.testng.TestRunner.privateRun(TestRunner.java:756)
2022-02-21T02:40:56.8357951Z 	at app//org.testng.TestRunner.run(TestRunner.java:610)
2022-02-21T02:40:56.8358347Z 	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
2022-02-21T02:40:56.8358797Z 	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
2022-02-21T02:40:56.8359257Z 	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
2022-02-21T02:40:56.8359663Z 	at app//org.testng.SuiteRunner.run(SuiteRunner.java:289)
2022-02-21T02:40:56.8360117Z 	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
2022-02-21T02:40:56.8360588Z 	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
2022-02-21T02:40:56.8361054Z 	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
2022-02-21T02:40:56.8361498Z 	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
2022-02-21T02:40:56.8361888Z 	at app//org.testng.TestNG.runSuites(TestNG.java:1133)
2022-02-21T02:40:56.8362254Z 	at app//org.testng.TestNG.run(TestNG.java:1104)
2022-02-21T02:40:56.8362950Z 	at app//org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
2022-02-21T02:40:56.8363721Z 	at app//org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
2022-02-21T02:40:56.8364519Z 	at app//org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
2022-02-21T02:40:56.8365174Z 	at app//org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
2022-02-21T02:40:56.8365881Z 	at app//org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2022-02-21T02:40:56.8366598Z 	at app//org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2022-02-21T02:40:56.8367228Z 	at app//org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2022-02-21T02:40:56.8367797Z 	at app//org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
2022-02-21T02:40:56.8368103Z 
2022-02-21T02:40:56.8368112Z 
2022-02-21T02:40:56.8368260Z "Reference Handler" daemon prio=10 Id=2 RUNNABLE
2022-02-21T02:40:56.8368718Z 	at java.base@11.0.14/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
2022-02-21T02:40:56.8369285Z 	at java.base@11.0.14/java.lang.ref.Reference.processPendingReferences(Reference.java:241)
2022-02-21T02:40:56.8369794Z 	at java.base@11.0.14/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)
2022-02-21T02:40:56.8370047Z 
2022-02-21T02:40:56.8370055Z 
2022-02-21T02:40:56.8370289Z "Finalizer" daemon prio=8 Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@52953f76
2022-02-21T02:40:56.8370700Z 	at java.base@11.0.14/java.lang.Object.wait(Native Method)
2022-02-21T02:40:56.8371256Z 	-  waiting on java.lang.ref.ReferenceQueue$Lock@52953f76
2022-02-21T02:40:56.8371713Z 	at java.base@11.0.14/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
2022-02-21T02:40:56.8372191Z 	at java.base@11.0.14/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
2022-02-21T02:40:56.8372833Z 	at java.base@11.0.14/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)
2022-02-21T02:40:56.8373086Z 
2022-02-21T02:40:56.8373094Z 
2022-02-21T02:40:56.8373255Z "Signal Dispatcher" daemon prio=9 Id=4 RUNNABLE
2022-02-21T02:40:56.8373444Z 
2022-02-21T02:40:56.8373451Z 
2022-02-21T02:40:56.8373904Z "Common-Cleaner" daemon prio=8 Id=9 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@5599bc26
2022-02-21T02:40:56.8374347Z 	at java.base@11.0.14/java.lang.Object.wait(Native Method)
2022-02-21T02:40:56.8374818Z 	-  waiting on java.lang.ref.ReferenceQueue$Lock@5599bc26
2022-02-21T02:40:56.8375246Z 	at java.base@11.0.14/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
2022-02-21T02:40:56.8375727Z 	at java.base@11.0.14/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
2022-02-21T02:40:56.8376133Z 	at java.base@11.0.14/java.lang.Thread.run(Thread.java:829)
2022-02-21T02:40:56.8376589Z 	at java.base@11.0.14/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:161)
2022-02-21T02:40:56.8376862Z 
2022-02-21T02:40:56.8376870Z 
2022-02-21T02:40:56.8377224Z "surefire-forkedjvm-command-thread" daemon prio=5 Id=10 RUNNABLE (in native)
2022-02-21T02:40:56.8377676Z 	at java.base@11.0.14/java.io.FileInputStream.readBytes(Native Method)
2022-02-21T02:40:56.8378131Z 	at java.base@11.0.14/java.io.FileInputStream.read(FileInputStream.java:279)
2022-02-21T02:40:56.8378625Z 	at java.base@11.0.14/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
2022-02-21T02:40:56.8379114Z 	at java.base@11.0.14/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
2022-02-21T02:40:56.8379611Z 	at java.base@11.0.14/java.io.DataInputStream.readInt(DataInputStream.java:392)
2022-02-21T02:40:56.8380185Z 	at app//org.apache.maven.surefire.booter.MasterProcessCommand.decode(MasterProcessCommand.java:115)
2022-02-21T02:40:56.8380838Z 	at app//org.apache.maven.surefire.booter.CommandReader$CommandRunnable.run(CommandReader.java:391)
2022-02-21T02:40:56.8381442Z 	at java.base@11.0.14/java.lang.Thread.run(Thread.java:829)
2022-02-21T02:40:56.8381665Z 
2022-02-21T02:40:56.8381674Z 
2022-02-21T02:40:56.8382248Z "surefire-forkedjvm-ping-30s" daemon prio=5 Id=11 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6fe90c9f
2022-02-21T02:40:56.8382843Z 	at java.base@11.0.14/jdk.internal.misc.Unsafe.park(Native Method)
2022-02-21T02:40:56.8383481Z 	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6fe90c9f
2022-02-21T02:40:56.8384439Z 	at java.base@11.0.14/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
2022-02-21T02:40:56.8385153Z 	at java.base@11.0.14/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
2022-02-21T02:40:56.8385935Z 	at java.base@11.0.14/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
2022-02-21T02:40:56.8386677Z 	at java.base@11.0.14/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
2022-02-21T02:40:56.8387351Z 	at java.base@11.0.14/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
2022-02-21T02:40:56.8387949Z 	at java.base@11.0.14/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
2022-02-21T02:40:56.8388539Z 	at java.base@11.0.14/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-02-21T02:40:56.8389012Z 	at java.base@11.0.14/java.lang.Thread.run(Thread.java:829)
2022-02-21T02:40:56.8389217Z 
2022-02-21T02:40:56.8389225Z 
2022-02-21T02:40:56.8389514Z "process reaper" daemon prio=10 Id=12 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@7789f5c8
2022-02-21T02:40:56.8390017Z 	at java.base@11.0.14/jdk.internal.misc.Unsafe.park(Native Method)
2022-02-21T02:40:56.8390606Z 	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@7789f5c8
2022-02-21T02:40:56.8391292Z 	at java.base@11.0.14/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
2022-02-21T02:40:56.8391902Z 	at java.base@11.0.14/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
2022-02-21T02:40:56.8392520Z 	at java.base@11.0.14/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
2022-02-21T02:40:56.8393080Z 	at java.base@11.0.14/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
2022-02-21T02:40:56.8393664Z 	at java.base@11.0.14/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
2022-02-21T02:40:56.8394258Z 	at java.base@11.0.14/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
2022-02-21T02:40:56.8394850Z 	at java.base@11.0.14/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-02-21T02:40:56.8395314Z 	at java.base@11.0.14/java.lang.Thread.run(Thread.java:829)
2022-02-21T02:40:56.8395501Z 
2022-02-21T02:40:56.8395532Z 
2022-02-21T02:40:56.8395679Z "TestHangMonitor" daemon prio=5 Id=14 RUNNABLE
2022-02-21T02:40:56.8396102Z 	at java.management@11.0.14/sun.management.ThreadImpl.dumpThreads0(Native Method)
2022-02-21T02:40:56.8396621Z 	at java.management@11.0.14/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
2022-02-21T02:40:56.8397142Z 	at java.management@11.0.14/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
2022-02-21T02:40:56.8397781Z 	at app//io.trino.testng.services.LogTestDurationListener.dumpAllThreads(LogTestDurationListener.java:160)
2022-02-21T02:40:56.8398503Z 	at app//io.trino.testng.services.LogTestDurationListener.checkForTestHang(LogTestDurationListener.java:147)
2022-02-21T02:40:56.8399161Z 	at app//io.trino.testng.services.LogTestDurationListener$$Lambda$70/0x0000000100130c40.run(Unknown Source)
2022-02-21T02:40:56.8399711Z 	at java.base@11.0.14/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-02-21T02:40:56.8400317Z 	at java.base@11.0.14/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
2022-02-21T02:40:56.8400997Z 	at java.base@11.0.14/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
2022-02-21T02:40:56.8401686Z 	at java.base@11.0.14/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-02-21T02:40:56.8402266Z 	at java.base@11.0.14/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-02-21T02:40:56.8402734Z 	at java.base@11.0.14/java.lang.Thread.run(Thread.java:829)
2022-02-21T02:40:56.8402938Z 
2022-02-21T02:40:56.8403039Z 	locked synchronizers:
2022-02-21T02:40:56.8403517Z 	- java.util.concurrent.ThreadPoolExecutor$Worker@131774fe
2022-02-21T02:40:56.8403759Z 
2022-02-21T02:40:56.8403766Z 
2022-02-21T02:40:56.8404357Z "testcontainers-pull-watchdog-1" daemon prio=5 Id=17 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@5e4cf129
2022-02-21T02:40:56.8404951Z 	at java.base@11.0.14/jdk.internal.misc.Unsafe.park(Native Method)
2022-02-21T02:40:56.8405591Z 	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@5e4cf129
2022-02-21T02:40:56.8406186Z 	at java.base@11.0.14/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
2022-02-21T02:40:56.8406867Z 	at java.base@11.0.14/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
2022-02-21T02:40:56.8407640Z 	at java.base@11.0.14/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.poll(ScheduledThreadPoolExecutor.java:1218)
2022-02-21T02:40:56.8408387Z 	at java.base@11.0.14/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.poll(ScheduledThreadPoolExecutor.java:899)
2022-02-21T02:40:56.8409042Z 	at java.base@11.0.14/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
2022-02-21T02:40:56.8409656Z 	at java.base@11.0.14/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
2022-02-21T02:40:56.8410347Z 	at java.base@11.0.14/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-02-21T02:40:56.8410811Z 	at java.base@11.0.14/java.lang.Thread.run(Thread.java:829)
2022-02-21T02:40:56.8411018Z 
2022-02-21T02:40:56.8411027Z 
2022-02-21T02:40:56.8411366Z "docker-java-stream--1791483794" daemon prio=5 Id=18 RUNNABLE (in native)
2022-02-21T02:40:56.8411837Z 	at app//com.github.dockerjava.transport.DomainSocket.read(Native Method)
2022-02-21T02:40:56.8412383Z 	at app//com.github.dockerjava.transport.DomainSocket.read(DomainSocket.java:79)
2022-02-21T02:40:56.8413607Z 	at app//com.github.dockerjava.transport.DomainSocket.access$200(DomainSocket.java:35)
2022-02-21T02:40:56.8414262Z 	at app//com.github.dockerjava.transport.DomainSocket$DomainSocketInputStream.read(DomainSocket.java:164)
2022-02-21T02:40:56.8415160Z 	at app//com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149)
2022-02-21T02:40:56.8416260Z 	at app//com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
2022-02-21T02:40:56.8417319Z 	at app//com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:261)
2022-02-21T02:40:56.8418355Z 	at app//com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
2022-02-21T02:40:56.8419334Z 	at app//com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:147)
2022-02-21T02:40:56.8420293Z 	at app//com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.io.EofSensorInputStream.read(EofSensorInputStream.java:118)
2022-02-21T02:40:56.8421236Z 	at app//org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:30)
2022-02-21T02:40:56.8422343Z 	at app//org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:12)
2022-02-21T02:40:56.8423344Z 	at app//org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:275)
2022-02-21T02:40:56.8424486Z 	at app//org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder$$Lambda$171/0x0000000100295c40.run(Unknown Source)
2022-02-21T02:40:56.8425078Z 	at java.base@11.0.14/java.lang.Thread.run(Thread.java:829)
2022-02-21T02:40:56.8425284Z 
2022-02-21T02:40:56.8425293Z 
2022-02-21T02:40:56.8425712Z "testcontainers-ryuk" daemon prio=5 Id=19 TIMED_WAITING on java.util.ArrayList@2dbcdebe
2022-02-21T02:40:56.8426141Z 	at java.base@11.0.14/java.lang.Object.wait(Native Method)
2022-02-21T02:40:56.8426551Z 	-  waiting on java.util.ArrayList@2dbcdebe
2022-02-21T02:40:56.8427021Z 	at app//org.testcontainers.utility.ResourceReaper.lambda$null$3(ResourceReaper.java:201)
2022-02-21T02:40:56.8427577Z 	at app//org.testcontainers.utility.ResourceReaper$$Lambda$211/0x00000001002c1440.run(Unknown Source)
2022-02-21T02:40:56.8428145Z 	at app//org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
2022-02-21T02:40:56.8428929Z 	at app//org.testcontainers.utility.ResourceReaper.lambda$start$4(ResourceReaper.java:190)
2022-02-21T02:40:56.8429484Z 	at app//org.testcontainers.utility.ResourceReaper$$Lambda$210/0x00000001002c1040.run(Unknown Source)
2022-02-21T02:40:56.8429916Z 	at java.base@11.0.14/java.lang.Thread.run(Thread.java:829)
2022-02-21T02:40:56.8430125Z 
2022-02-21T02:40:56.8430133Z 
2022-02-21T02:40:56.8430474Z "docker-java-stream--401752197" daemon prio=5 Id=24 RUNNABLE (in native)
2022-02-21T02:40:56.8430944Z 	at app//com.github.dockerjava.transport.DomainSocket.read(Native Method)
2022-02-21T02:40:56.8431488Z 	at app//com.github.dockerjava.transport.DomainSocket.read(DomainSocket.java:79)
2022-02-21T02:40:56.8432197Z 	at app//com.github.dockerjava.transport.DomainSocket.access$200(DomainSocket.java:35)
2022-02-21T02:40:56.8432994Z 	at app//com.github.dockerjava.transport.DomainSocket$DomainSocketInputStream.read(DomainSocket.java:164)
2022-02-21T02:40:56.8433887Z 	at app//com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149)
2022-02-21T02:40:56.8434941Z 	at app//com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:172)
2022-02-21T02:40:56.8436093Z 	at app//com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.IdentityInputStream.read(IdentityInputStream.java:87)
2022-02-21T02:40:56.8437077Z 	at app//com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.io.EofSensorInputStream.read(EofSensorInputStream.java:118)
2022-02-21T02:40:56.8438009Z 	at app//org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:30)
2022-02-21T02:40:56.8439106Z 	at app//org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:12)
2022-02-21T02:40:56.8440081Z 	at app//org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:275)
2022-02-21T02:40:56.8440969Z 	at app//org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder$$Lambda$171/0x0000000100295c40.run(Unknown Source)
2022-02-21T02:40:56.8441557Z 	at java.base@11.0.14/java.lang.Thread.run(Thread.java:829)
```

**Comment by findepi** [comment]
cc @nineinchnick @MiguelWeezardo

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/6416489582

**Comment by ebyhr** [comment]
I guess it's already fixed. Going to close.

**Comment by pajaks** [comment]
https://github.com/trinodb/trino/actions/runs/4193228276

**Comment by nineinchnick** [comment]
Looks like it fails when pulling `ghcr.io/trinodb/testing/centos7-oj17:latest`. We can pull this explicitly before starting tests, and maybe add a timeout and retries in case it gets stuck like this.

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/4584653136/jobs/8096275081?pr=16842

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/4716511095/jobs/8364306093?pr=16183

**Comment by nineinchnick** [comment]
I think we can close this after #17112 split up maven checks job..
