### ISSUE TITLE
Flaky Could not start environment 'singlenode-oauth2-http-proxy'

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#11130]
```
2022-02-21T07:46:23.5742384Z 2022-02-21T07:46:23.573Z	ERROR	testcontainers-lifecycle-0	🐳 [ghcr.io/trinodb/testing/centos7-oj11:53]	There are no stdout/stderr logs available for the failed container
2022-02-21T07:46:23.5786616Z 2022-02-21T07:46:23.577Z	WARN	main	io.trino.tests.product.launcher.env.Environment	Could not start environment 'singlenode-oauth2-http-proxy'
2022-02-21T07:46:23.5787559Z java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.testcontainers.containers.ContainerLaunchException: Container startup failed
2022-02-21T07:46:23.5788330Z 	at io.trino.tests.product.launcher.env.Environment.tryStart(Environment.java:161)
2022-02-21T07:46:23.5788868Z 	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
2022-02-21T07:46:23.5789392Z 	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:62)
2022-02-21T07:46:23.5789914Z 	at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
2022-02-21T07:46:23.5790408Z 	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
2022-02-21T07:46:23.5790916Z 	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:67)
2022-02-21T07:46:23.5791456Z 	at io.trino.tests.product.launcher.env.Environment.start(Environment.java:114)
2022-02-21T07:46:23.5792037Z 	at io.trino.tests.product.launcher.cli.TestRun$Execution.startEnvironment(TestRun.java:246)
2022-02-21T07:46:23.5792635Z 	at io.trino.tests.product.launcher.cli.TestRun$Execution.tryExecuteTests(TestRun.java:222)
2022-02-21T07:46:23.5793152Z 	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
2022-02-21T07:46:23.5793634Z 	at net.jodah.failsafe.TimeoutExecutor.lambda$supply$2(TimeoutExecutor.java:91)
2022-02-21T07:46:23.5794135Z 	at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
2022-02-21T07:46:23.5794623Z 	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
2022-02-21T07:46:23.5795226Z 	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:67)
2022-02-21T07:46:23.5795690Z 	at io.trino.tests.product.launcher.cli.TestRun$Execution.call(TestRun.java:205)
2022-02-21T07:46:23.5796205Z 	at io.trino.tests.product.launcher.cli.SuiteRun$Execution.runTest(SuiteRun.java:291)
2022-02-21T07:46:23.5796808Z 	at io.trino.tests.product.launcher.cli.SuiteRun$Execution.executeSuiteTestRun(SuiteRun.java:276)
2022-02-21T07:46:23.5797302Z 	at io.trino.tests.product.launcher.cli.SuiteRun$Execution.lambda$runSuites$2(SuiteRun.java:209)
2022-02-21T07:46:23.5797748Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
2022-02-21T07:46:23.5798458Z 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
2022-02-21T07:46:23.5798924Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2022-02-21T07:46:23.5799403Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2022-02-21T07:46:23.5799859Z 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
2022-02-21T07:46:23.5800317Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2022-02-21T07:46:23.5800769Z 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
2022-02-21T07:46:23.5801358Z 	at io.trino.tests.product.launcher.cli.SuiteRun$Execution.lambda$runSuites$3(SuiteRun.java:210)
2022-02-21T07:46:23.5801932Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2022-02-21T07:46:23.5802423Z 	at io.trino.tests.product.launcher.cli.SuiteRun$Execution.runSuites(SuiteRun.java:196)
2022-02-21T07:46:23.5802981Z 	at io.trino.tests.product.launcher.cli.SuiteRun$Execution.call(SuiteRun.java:182)
2022-02-21T07:46:23.5803510Z 	at io.trino.tests.product.launcher.cli.SuiteRun$Execution.call(SuiteRun.java:139)
2022-02-21T07:46:23.5804067Z 	at io.trino.tests.product.launcher.cli.Commands.runCommand(Commands.java:41)
2022-02-21T07:46:23.5804624Z 	at io.trino.tests.product.launcher.cli.SuiteRun.call(SuiteRun.java:104)
2022-02-21T07:46:23.5805153Z 	at io.trino.tests.product.launcher.cli.SuiteRun.call(SuiteRun.java:72)
2022-02-21T07:46:23.5805642Z 	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
2022-02-21T07:46:23.5806087Z 	at picocli.CommandLine.access$1300(CommandLine.java:145)
2022-02-21T07:46:23.5806656Z 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
2022-02-21T07:46:23.5807217Z 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
2022-02-21T07:46:23.5807614Z 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
2022-02-21T07:46:23.5808092Z 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
2022-02-21T07:46:23.5808561Z 	at picocli.CommandLine.execute(CommandLine.java:2078)
2022-02-21T07:46:23.5809012Z 	at io.trino.tests.product.launcher.cli.Launcher.run(Launcher.java:71)
2022-02-21T07:46:23.5809538Z 	at io.trino.tests.product.launcher.cli.Launcher.main(Launcher.java:61)
2022-02-21T07:46:23.5810219Z Caused by: java.util.concurrent.ExecutionException: org.testcontainers.containers.ContainerLaunchException: Container startup failed
2022-02-21T07:46:23.5810944Z 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
2022-02-21T07:46:23.5811519Z 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
2022-02-21T07:46:23.5812107Z 	at io.trino.tests.product.launcher.env.Environment.tryStart(Environment.java:134)
2022-02-21T07:46:23.5812512Z 	... 41 more
2022-02-21T07:46:23.5812945Z Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
2022-02-21T07:46:23.5813563Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)
2022-02-21T07:46:23.5814284Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
2022-02-21T07:46:23.5814841Z 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
2022-02-21T07:46:23.5815382Z 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
2022-02-21T07:46:23.5817066Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-02-21T07:46:23.5817636Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-02-21T07:46:23.5818076Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-02-21T07:46:23.5818616Z Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
2022-02-21T07:46:23.5819249Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
2022-02-21T07:46:23.5819771Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)
2022-02-21T07:46:23.5820113Z 	... 6 more
2022-02-21T07:46:23.5820460Z Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
2022-02-21T07:46:23.5821156Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:525)
2022-02-21T07:46:23.5821795Z 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)
2022-02-21T07:46:23.5822406Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
2022-02-21T07:46:23.5822860Z 	... 7 more
2022-02-21T07:46:23.5823351Z Caused by: java.lang.IllegalStateException: Container is removed
2022-02-21T07:46:23.5823892Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:479)
```

**Comment by nineinchnick** [comment]
I also hit that in https://github.com/trinodb/trino/runs/5389981295?check_suite_focus=true
