### ISSUE TITLE
approx_percentile is not accepting infinite values

### ISSUE THREAD

**Issue by saharghya** [trinodb/trino#11156]
The below query works on Presto 334 but not on Trino 370
```
select
approx_percentile((((1 / (1 / cast('38.851238250732400000000000' as double) - 1 / 1560) - 18) / (1 / (1 / cast('18.0000' as DOUBLE) - 1 / 1560) - 18)) * 540 + 2), 0.5)
;
```

Below is the error
```
java.lang.IllegalArgumentException: value must be finite
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at io.airlift.stats.TDigest.add(TDigest.java:194)
	at io.airlift.stats.TDigest.add(TDigest.java:187)
	at io.trino.operator.aggregation.ApproximateDoublePercentileAggregations.input(ApproximateDoublePercentileAggregations.java:50)
	at io.trino.$gen.approx_percentileGroupedAccumulator_20220222_161600_1980104.addInput(Unknown Source)
	at io.trino.operator.aggregation.GroupedAggregator.processPage(GroupedAggregator.java:70)
	at io.trino.operator.aggregation.builder.InMemoryHashAggregationBuilder.lambda$processPage$1(InMemoryHashAggregationBuilder.java:146)
	at io.trino.operator.TransformWork.process(TransformWork.java:44)
	at io.trino.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:417)
	at io.trino.operator.Driver.processInternal(Driver.java:393)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:682)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_370____20220219_054148_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
Discussion: https://trinodb.slack.com/archives/CGB0QHWSW/p1645546926267429

**Comment by findepi** [comment]
Marking as bug, as it's believed to be a regression since introduction of TDigest.

**Comment by findepi** [comment]
@martint indicated this may be intentional

**Comment by losipiuk** [comment]
@martint It may intentional but it should not fail GENERIC_INTERNAL_ERROR. It does so also for `NaN`.
My intuition is it should fail with USER_ERROR. Do you agree?

**Comment by losipiuk** [comment]
Improved input validation: https://github.com/trinodb/trino/issues/11156

**Comment by findepi** [comment]
> Improved input validation: #11156

did you mean to link to https://github.com/trinodb/trino/pull/23546?

**Comment by losipiuk** [comment]
> > Improved input validation: #11156
> 
> did you mean to link to #23546?

Yeah - thanks

**Comment by kasiafi** [comment]
@losipiuk should we close this issue?
