### ISSUE TITLE
testAssignUniqueId fails with task-level retries

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#11223]
when running with `retry-policy` set to `TASK`

```
    @Test
    public void testAssignUniqueId()
    {
        String unionLineitem25Times = range(0, 25)
                .mapToObj(i -> "SELECT * FROM lineitem")
                .collect(joining(" UNION ALL "));

        assertQuery(
                "SELECT count(*) FROM (" +
                        "SELECT * FROM (" +
                        "   SELECT (SELECT count(*) WHERE c = 1) " +
                        "   FROM (SELECT CASE orderkey WHEN 1 THEN orderkey ELSE 1 END " +
                        "       FROM (" + unionLineitem25Times + ")) o(c)) result(a) " +
                        "WHERE a = 1)",
                "VALUES 1504375");
    }
```

fails with 
```
java.lang.IllegalArgumentException: replicated exchanges are not expected in source distributed stage, got: [io.trino.sql.planner.plan.RemoteSourceNode@16582757, io.trino.sql.planner.plan.RemoteSourceNode@314ca0e5]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
	at io.trino.execution.scheduler.StageTaskSourceFactory$ArbitraryDistributionTaskSource.create(StageTaskSourceFactory.java:226)
	at io.trino.execution.scheduler.StageTaskSourceFactory.create(StageTaskSourceFactory.java:132)
	at io.trino.execution.scheduler.FaultTolerantStageScheduler.schedule(FaultTolerantStageScheduler.java:218)
	at io.trino.execution.scheduler.SqlQueryScheduler$FaultTolerantDistributedStagesScheduler.schedule(SqlQueryScheduler.java:1944)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by losipiuk** [comment]
cc: @arhimondr

**Comment by arhimondr** [comment]
Fixed by https://github.com/trinodb/trino/pull/11224/commits/c4670d5882d82162c74dfcc1d963143182cc1dc9
