### ISSUE TITLE
Query against $manifests Iceberg table fails with NullPointerException

### ISSUE THREAD

**Issue by vincentpoon** [trinodb/trino#11237]
After upgrading to 371, seeing:
```
java.lang.NullPointerException: undefined
	at io.trino.plugin.iceberg.ManifestsTable.writePartitionSummaries(ManifestsTable.java:140)
	at io.trino.plugin.iceberg.ManifestsTable.lambda$buildPages$0(ManifestsTable.java:123)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.trino.plugin.iceberg.ManifestsTable.buildPages(ManifestsTable.java:114)
	at io.trino.plugin.iceberg.ManifestsTable.pageSource(ManifestsTable.java:100)
	at io.trino.plugin.base.classloader.ClassLoaderSafeSystemTable.pageSource(ClassLoaderSafeSystemTable.java:70)
	at io.trino.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:105)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:68)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:308)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:693)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_371_sfdc_6_dbee13f____20220228_195331_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Relevant code was changed here:
https://github.com/trinodb/trino/pull/10702

**Comment by hashhar** [comment]
cc: @findinpath
