### ISSUE TITLE
Flaky KuduSmokeTests

### ISSUE THREAD

**Issue by phd3** [trinodb/trino#11245]
https://github.com/trinodb/trino/runs/5362620480?check_suite_focus=true

```
Error:  io.trino.plugin.kudu.KuduSmokeTests$TestKuduWithEmptyInferSchemaConnectorTest.init  Time elapsed: 49.421 s  <<< FAILURE!
java.lang.RuntimeException: Schema tpch not found
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:505)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:339)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:331)
	at io.trino.testing.QueryAssertions.copyTpchTables(QueryAssertions.java:323)
	at io.trino.plugin.kudu.KuduQueryRunnerFactory.createKuduQueryRunnerTpch(KuduQueryRunnerFactory.java:107)
	at io.trino.plugin.kudu.KuduQueryRunnerFactory.createKuduQueryRunnerTpch(KuduQueryRunnerFactory.java:83)
	at io.trino.plugin.kudu.AbstractKuduConnectorTest.createQueryRunner(AbstractKuduConnectorTest.java:54)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE IF NOT EXISTS customer AS SELECT * FROM tpch.tiny.customer
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:508)
		... 20 more
Caused by: io.trino.spi.connector.SchemaNotFoundException: Schema tpch not found
	at io.trino.plugin.kudu.KuduClientSession.openTable(KuduClientSession.java:237)
	at io.trino.plugin.kudu.KuduOutputTableHandle.getTable(KuduOutputTableHandle.java:91)
	at io.trino.plugin.kudu.KuduPageSink.<init>(KuduPageSink.java:89)
	at io.trino.plugin.kudu.KuduPageSinkProvider.createPageSink(KuduPageSinkProvider.java:46)
	at io.trino.split.PageSinkManager.createPageSink(PageSinkManager.java:54)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:126)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:120)
	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:114)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:958)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1086)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_testversion____20220228_195319_147.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Error:  io.trino.plugin.kudu.KuduSmokeTests$TestKuduWithDisabledInferSchemaConnectorTest.init  Time elapsed: 1.381 s  <<< FAILURE!
java.lang.RuntimeException: Table 'default.customer' not found
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:505)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:339)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:331)
	at io.trino.testing.QueryAssertions.copyTpchTables(QueryAssertions.java:323)
	at io.trino.plugin.kudu.KuduQueryRunnerFactory.createKuduQueryRunnerTpch(KuduQueryRunnerFactory.java:107)
	at io.trino.plugin.kudu.KuduQueryRunnerFactory.createKuduQueryRunnerTpch(KuduQueryRunnerFactory.java:83)
	at io.trino.plugin.kudu.AbstractKuduConnectorTest.createQueryRunner(AbstractKuduConnectorTest.java:54)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE IF NOT EXISTS customer AS SELECT * FROM tpch.tiny.customer
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:508)
		... 20 more
Caused by: io.trino.spi.connector.TableNotFoundException: Table 'default.customer' not found
	at io.trino.plugin.kudu.KuduClientSession.openTable(KuduClientSession.java:239)
	at io.trino.plugin.kudu.KuduOutputTableHandle.getTable(KuduOutputTableHandle.java:91)
	at io.trino.plugin.kudu.KuduPageSink.<init>(KuduPageSink.java:89)
	at io.trino.plugin.kudu.KuduPageSinkProvider.createPageSink(KuduPageSinkProvider.java:46)
	at io.trino.split.PageSinkManager.createPageSink(PageSinkManager.java:54)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:126)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:120)
	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:114)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:958)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1086)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_testversion____20220228_195317_144.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ebyhr** [comment]
The flaky test is handled in #11203. 

@grantatspothero I would recommend including test name in the issue title and description so that other people can find it easily.
