### ISSUE TITLE
trino fails to connect to kerberized Hive and HDFS on CentOS

### ISSUE THREAD

**Issue by suryanshagnihotri** [trinodb/trino#11251]
I am unable to query hive table via trino when hive/hadoop is kerberized. 

I was able to run the above query if i edit the /etc/krb5.conf & remove "renew_lifetime = 7d". But this is not feasible to do.
I have followed doc and added configs correctly https://trino.io/docs/current/connector/hive-security.html.
Let me know if this is a known issue.

hive.properties contains:
```
connector.name=hive
hive.metastore.uri=thrift://IP:9083
hive.metastore.authentication.type=KERBEROS
hive.metastore.service.principal=hive/IP@XYZ.COM
hive.metastore.client.principal=trino/IP@XYZ.COM
hive.metastore.client.keytab=/etc/security/keytabs/trino.service.keytab
hive.hdfs.authentication.type=KERBEROS
hive.hdfs.trino.principal=trino/IP@XYZ.COM
hive.hdfs.trino.keytab=/etc/security/keytabs/trino.service.keytab
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
hive.metastore.thrift.impersonation.enabled=true
```

I get below error
```
trino> show tables in hive.default;
Query 20220301_110357_00000_i7qjh failed: java.lang.RuntimeException: javax.security.auth.login.LoginException: Message stream modified (41)
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: javax.security.auth.login.LoginException: Message stream modified (41)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4952)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:259)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getAllDatabases(CachingHiveMetastore.java:293)
	at io.trino.plugin.hive.HiveMetastoreClosure.getAllDatabases(HiveMetastoreClosure.java:65)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.getAllDatabases(SemiTransactionalHiveMetastore.java:183)
	at io.trino.plugin.hive.HiveMetadata.listSchemaNames(HiveMetadata.java:375)
	at io.trino.spi.connector.ConnectorMetadata.schemaExists(ConnectorMetadata.java:58)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.schemaExists(ClassLoaderSafeConnectorMetadata.java:191)
	at io.trino.metadata.MetadataManager.lambda$schemaExists$2(MetadataManager.java:355)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at io.trino.metadata.MetadataManager.schemaExists(MetadataManager.java:355)
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowTables(ShowQueriesRewrite.java:213)
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowTables(ShowQueriesRewrite.java:172)
	at io.trino.sql.tree.ShowTables.accept(ShowTables.java:72)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:169)
	at io.trino.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:61)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:88)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:190)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:806)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
	at io.trino.$gen.Trino_360_1_g6402c1f_dirty____20220301_110331_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: javax.security.auth.login.LoginException: Message stream modified (41)
	at io.trino.plugin.base.authentication.KerberosAuthentication.getSubject(KerberosAuthentication.java:72)
	at io.trino.plugin.hive.authentication.KerberosHadoopAuthentication.getUserGroupInformation(KerberosHadoopAuthentication.java:59)
	at io.trino.plugin.hive.authentication.CachingKerberosHadoopAuthentication.getUserGroupInformation(CachingKerberosHadoopAuthentication.java:47)
	at io.trino.plugin.hive.metastore.thrift.KerberosHiveMetastoreAuthentication.authenticate(KerberosHiveMetastoreAuthentication.java:103)
	at io.trino.plugin.hive.metastore.thrift.Transport.create(Transport.java:48)
	at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.createTransport(DefaultThriftMetastoreClientFactory.java:110)
	at io.trino.plugin.hive.metastore.thrift.DefaultThriftMetastoreClientFactory.create(DefaultThriftMetastoreClientFactory.java:97)
	at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.getClient(StaticMetastoreLocator.java:123)
	at io.trino.plugin.hive.metastore.thrift.StaticMetastoreLocator.createMetastoreClient(StaticMetastoreLocator.java:109)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createMetastoreClient(ThriftHiveMetastore.java:1978)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$getAllDatabases$0(ThriftHiveMetastore.java:259)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
	at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getAllDatabases(ThriftHiveMetastore.java:258)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.getAllDatabases(BridgingHiveMetastore.java:89)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadAllDatabases(CachingHiveMetastore.java:298)
	at com.google.common.cache.CacheLoader$SupplierToCacheLoader.load(CacheLoader.java:227)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 43 more
	Suppressed: java.lang.RuntimeException: javax.security.auth.login.LoginException: Message stream modified (41)
		... 65 more
	Caused by: javax.security.auth.login.LoginException: Message stream modified (41)
		at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:784)
		at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:592)
		at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:747)
		at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:672)
		at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:670)
		at java.base/java.security.AccessController.doPrivileged(Native Method)
		at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:670)
		at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:581)
		at io.trino.plugin.base.authentication.KerberosAuthentication.getSubject(KerberosAuthentication.java:68)
		... 64 more
	Caused by: sun.security.krb5.internal.KrbApErrException: Message stream modified (41)
		at java.security.jgss/sun.security.krb5.KrbKdcRep.check(KrbKdcRep.java:103)
		at java.security.jgss/sun.security.krb5.KrbAsRep.decrypt(KrbAsRep.java:159)
		at java.security.jgss/sun.security.krb5.KrbAsRep.decryptUsingKeyTab(KrbAsRep.java:121)
		at java.security.jgss/sun.security.krb5.KrbAsReqBuilder.resolve(KrbAsReqBuilder.java:310)
		at java.security.jgss/sun.security.krb5.KrbAsReqBuilder.action(KrbAsReqBuilder.java:498)
		at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:756)
		... 72 more
	Suppressed: java.lang.RuntimeException: javax.security.auth.login.LoginException: Message stream modified (41)
		... 65 more
	Caused by: javax.security.auth.login.LoginException: Message stream modified (41)
		at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:784)
		at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:592)
		at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:747)
		at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:672)
		at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:670)
		at java.base/java.security.AccessController.doPrivileged(Native Method)
		at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:670)
		at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:581)
		at io.trino.plugin.base.authentication.KerberosAuthentication.getSubject(KerberosAuthentication.java:68)
		... 64 more
	Caused by: sun.security.krb5.internal.KrbApErrException: Message stream modified (41)
		at java.security.jgss/sun.security.krb5.KrbKdcRep.check(KrbKdcRep.java:103)
		at java.security.jgss/sun.security.krb5.KrbAsRep.decrypt(KrbAsRep.java:159)
		at java.security.jgss/sun.security.krb5.KrbAsRep.decryptUsingKeyTab(KrbAsRep.java:121)
		at java.security.jgss/sun.security.krb5.KrbAsReqBuilder.resolve(KrbAsReqBuilder.java:310)
		at java.security.jgss/sun.security.krb5.KrbAsReqBuilder.action(KrbAsReqBuilder.java:498)
		at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:756)
		... 72 more
	Suppressed: java.lang.RuntimeException: javax.security.auth.login.LoginException: Message stream modified (41)
		... 65 more
	Caused by: javax.security.auth.login.LoginException: Message stream modified (41)
		at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:784)
		at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:592)
		at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:747)
		at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:672)
		at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:670)
		at java.base/java.security.AccessController.doPrivileged(Native Method)
		at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:670)
		at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:581)
		at io.trino.plugin.base.authentication.KerberosAuthentication.getSubject(KerberosAuthentication.java:68)
		... 64 more

**Comment by suryanshagnihotri** [comment]
cc @agrawalreetika  @imjalpreet

**Comment by Praveen2112** [comment]
I'll try to reproduce it by adding this config `renew_lifetime = 7d` to the Product tests environment.

**Comment by suryanshagnihotri** [comment]
The issue came after java9 release and it is present from there onwards https://bugs.openjdk.java.net/browse/JDK-8131051
In order to fix it user can either remove `renew_lifetime` from /etc/krb5.conf or create a principal of user with `renew_lifetime` in it (something like ```kadmin.local:  modprinc -maxrenewlife 9day +allow_renewable krbtgt/BDACLOUDSERVICE.ORACLE.COM```)

**Comment by sujith71955** [comment]
@suryanshagnihotri @Praveen2112  can we document somewhere in hive Kerberos section. It may help the kerberos based users.
