### ISSUE TITLE
Raptor's TestShardOrganizer.testShardOrganizerInProgress test is flaky

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#11252]
```
2022-03-01T01:54:19.559-0600 INFO [TEST START] io.trino.plugin.raptor.legacy.storage.organization.TestShardOrganizer.testShardOrganizerInProgress
2022-03-01T01:54:19.749-0600 INFO not retrying; @Flaky annotation not present
2022-03-01T01:54:19.754-0600 SEVERE [TEST FAILURE] io.trino.plugin.raptor.legacy.storage.organization.TestShardOrganizer.testShardOrganizerInProgress; (took: 0.2 seconds)
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at io.trino.plugin.raptor.legacy.storage.organization.TestShardOrganizer.testShardOrganizerInProgress(TestShardOrganizer.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/6892864058/job/18751316816?pr=19777

```
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.052 s <<< FAILURE! -- in io.trino.plugin.raptor.legacy.storage.organization.TestShardOrganizer
Error:  io.trino.plugin.raptor.legacy.storage.organization.TestShardOrganizer.testShardOrganizerInProgress -- Time elapsed: 0.050 s <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at io.trino.plugin.raptor.legacy.storage.organization.TestShardOrganizer.testShardOrganizerInProgress(TestShardOrganizer.java:45)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/6940970228/job/18881371466?pr=19841 

```
Error:  io.trino.plugin.raptor.legacy.storage.organization.TestShardOrganizer.testShardOrganizerInProgress -- Time elapsed: 0.116 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: 1
 but was: 0
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.trino.plugin.raptor.legacy.storage.organization.TestShardOrganizer.testShardOrganizerInProgress(TestShardOrganizer.java:44)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:[114](https://github.com/trinodb/trino/actions/runs/6940970228/job/18881371466?pr=19841#step:5:115)4)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
