### ISSUE TITLE
io.trino.spi.TrinoException: Could not serialize column 'role_grade' of type 'integer'

### ISSUE THREAD

**Issue by ruanliang-hualun** [trinodb/trino#11339]
**I use Trino(368) query es data，Occasionally the following errors occur
'role_grade'  filed data can be NULL or an Integer Array**

io.trino.spi.TrinoException: Could not serialize column 'role_grade' of type 'integer' at position 3:11
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.lambda$propagateException$2(QueryResultRows.java:418)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.propagateException(QueryResultRows.java:418)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.getRowValues(QueryResultRows.java:340)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.computeNext(QueryResultRows.java:311)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.computeNext(QueryResultRows.java:273)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serializeContents(IterableSerializer.java:111)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:74)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:12)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1518)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1007)
	at io.airlift.jaxrs.JsonMapper.write(JsonMapper.java:108)
	at io.airlift.jaxrs.AbstractJacksonMapper.writeTo(AbstractJacksonMapper.java:157)
	at io.airlift.jaxrs.JsonMapper.writeTo(JsonMapper.java:44)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:662)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:884)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:916)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872)
	at io.airlift.jaxrs.AsyncResponseHandler$1.onSuccess(AsyncResponseHandler.java:100)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1139)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsupportedOperationException: io.trino.spi.block.ArrayBlock
	at io.trino.spi.block.Block.getInt(Block.java:57)
	at io.trino.spi.type.IntegerType.getObjectValue(IntegerType.java:38)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.getRowValues(QueryResultRows.java:333)
	... 44 more

**Comment by ruanliang-hualun** [comment]
I Run multiple experiments. when the error occurs ,  all NULL data is returned

 role_id
---------
 NULL
 NULL
 NULL
 NULL
 NULL
 NULL
 NULL
 NULL
 NULL
 NULL
 NULL
 NULL
 NULL
 NULL
 NULL
 NULL
 NULL
 NULL
(18 rows)

Query 20220304_095029_00118_rv7t3, **FAILED**, 1 node
Splits: 35 total, 34 done (97.14%)
0.21 [100 rows, 1.79KB] [471 rows/s, 8.46KB/s]

**Comment by findepi** [comment]
That seems like a bug in a connector. What connector is it?

**Comment by ruanliang-hualun** [comment]
1：Connector   **trino-elasticsearch**
    <properties>
        <air.main.basedir>${project.parent.basedir}</air.main.basedir>
        <dep.elasticsearch.version>6.0.0</dep.elasticsearch.version>
    </properties>

2：The back-end es cluster version is  6.4.0

**Comment by findepi** [comment]
cc @ebyhr @hashhar @aalbu

**Comment by ebyhr** [comment]
@ruanliang-hualun Could you share the steps to reproduce?

**Comment by ruanliang-hualun** [comment]
@ebyhr  
1：I have an es index "test"  which have a filed "role_grade"(Examples of data are below)
    "role_grade": [
      109,
      109
    ]
   role_grade can be NULL, or a single numerical

2：define the catalog file es-dev.properties

3：define the index meta,  identify the role_grade is array type
curl --request PUT \
    --url http://ip:port/test/doc/_mapping \
    --header 'content-type: application/json' \
    --data '{"_meta": {"trino":{"role_grade":{"isArray":true}}}}'

4：use cli tool to query table data, Sometimes serialization errors occur
trino> select role_grade from "es-dev"."default"."test";

**Comment by ruanliang-hualun** [comment]
@ebyhr   I found the cause of the bug

**ElasticsearchClient.getIndexMetadata(String index)  get the wrong mapping element,** 
[https://github.com/trinodb/trino/blob/master/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java](url)
```
    public IndexMetadata getIndexMetadata(String index)
    {
        String path = format("/%s/_mappings", index);

        return doRequest(path, body -> {
            try {
                //1： this mappings  get two elements ,  ( _default_ and doc  )
                JsonNode mappings = OBJECT_MAPPER.readTree(body)
                        .elements().next()
                        .get("mappings");
                
                //2：clearly satisfy the condition
                if (!mappings.has("properties")) {

                    //3：get the first wrong element _default_ , which does not contain the _meta  filed
                    mappings = mappings.elements().next();
                }

                JsonNode metaNode = nullSafeNode(mappings, "_meta");
                ........
            }
        });
    }
```

**verification**
1：my index mapping contains two parts "doc" and "\_default\_" 
     "\_default\_" is not enable 
```
{"qn_2022-01-18":{"mappings":{"_default_":{"_all":{"enabled":false},"dynamic_templates":[{"string_template":{"match":"*","match_mapping_type":"string","mapping":{"type":"keyword"}}}],"properties":{"role_grade":{"type":"integer"},"role_id":{"type":"keyword"}}},"doc":{"_meta":{"trino":{"role_grade":{"isArray":true},"role_id":{"isArray":true}}},"_all":{"enabled":false},"dynamic_templates":[{"string_template":{"match":"*","match_mapping_type":"string","mapping":{"type":"keyword"}}}],"properties":{"role_grade":{"type":"integer"},"role_id":{"type":"keyword"}}}}}}
```

2：run the test case
```
    public static void main(String[] args) {

        String body = "{\"qn_2022-01-18\":{\"mappings\":{\"_default_\":{\"_all\":{\"enabled\":false},\"dynamic_templates\":[{\"string_template\":{\"match\":\"*\",\"match_mapping_type\":\"string\",\"mapping\":{\"type\":\"keyword\"}}}],\"properties\":{\"role_grade\":{\"type\":\"integer\"},\"role_id\":{\"type\":\"keyword\"}}},\"doc\":{\"_meta\":{\"trino\":{\"role_grade\":{\"isArray\":true},\"role_id\":{\"isArray\":true}}},\"_all\":{\"enabled\":false},\"dynamic_templates\":[{\"string_template\":{\"match\":\"*\",\"match_mapping_type\":\"string\",\"mapping\":{\"type\":\"keyword\"}}}],\"properties\":{\"role_grade\":{\"type\":\"integer\"},\"role_id\":{\"type\":\"keyword\"}}}}}}";

        try {
            JsonNode mappings = OBJECT_MAPPER.readTree(body)
                    .elements().next()
                    .get("mappings");

            // obvious not true
            if (!mappings.has("properties")) {
                // get  the wrong element
                mappings = mappings.elements().next();
            }
            
            // the first element does not contain the _meta filed, this will case the serialize problem
            // {"_all":{"enabled":false},"dynamic_templates":[{"string_template":{"match":"*","match_mapping_type":"string","mapping":{"type":"keyword"}}}],"properties":{"role_grade":{"type":"integer"},"role_id":{"type":"keyword"}}}
            System.out.println(mappings.toString());
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }

    }
```

3：some doubt
- why use the below code to  compatible with earlier versions of ES , in my case this does not work , my es version is 6.4.0
```
                if (!mappings.has("properties")) {
                    // Older versions of ElasticSearch supported multiple "type" mappings
                    // for a given index. Newer versions support only one and don't
                    // expose it in the document. Here we skip it if it's present.
                    mappings = mappings.elements().next();

                    if (!mappings.has("properties")) {
                        return new IndexMetadata(new IndexMetadata.ObjectType(ImmutableList.of()));
                    }
                }
```
- why not use filed {"enabled":false}  to filter out the wrong element
```
{"_all":{"enabled":false},"dynamic_templates":[{"string_template":{"match":"*","match_mapping_type":"string","mapping":{"type":"keyword"}}}],"properties":{"role_grade":{"type":"integer"},"role_id":{"type":"keyword"}}}
```

**Comment by ebyhr** [comment]
@martint @phd3 Can you take look at the above comment?

**Comment by martint** [comment]
The connector doesn't support indexes with multiple mappings -- it wouldn't know how to pick between them.

We should update it to fail if there are more than one mapping. In your case, you would need to delete one of those mappings to be able to query it.

**Comment by ruanliang-hualun** [comment]
@martint  
I do delete the incorrect mapping,to solve the problem . 
I wonder if I can fix this connector bug ?

**Comment by ruanliang-hualun** [comment]
@phd3  in es6.x a index can have multiple mapping element
