### ISSUE TITLE
Flaky Phoenix tests: "ERROR 722 (43M05): Schema does not exist schemaName=TPCH"

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#11344]
```
2022-03-05T05:14:57.2453486Z [ERROR] Tests run: 265, Failures: 1, Errors: 0, Skipped: 36, Time elapsed: 737.928 s <<< FAILURE! - in TestSuite
2022-03-05T05:14:57.2458152Z [ERROR] io.trino.plugin.phoenix.TestPhoenixConnectorTest.testDataMappingSmokeTest[boolean](1)  Time elapsed: 0.089 s  <<< FAILURE!
2022-03-05T05:14:57.2458873Z java.lang.RuntimeException: ERROR 722 (43M05): Schema does not exist schemaName=TPCH
2022-03-05T05:14:57.2459472Z 	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
2022-03-05T05:14:57.2460150Z 	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:506)
2022-03-05T05:14:57.2460744Z 	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
2022-03-05T05:14:57.2604286Z 	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:281)
2022-03-05T05:14:57.2605271Z 	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:276)
2022-03-05T05:14:57.2606226Z 	at io.trino.testing.BaseConnectorTest.lambda$testDataMapping$20(BaseConnectorTest.java:2857)
2022-03-05T05:14:57.2607399Z 	at io.trino.testing.BaseConnectorTest.testDataMapping(BaseConnectorTest.java:2867)
2022-03-05T05:14:57.2608125Z 	at io.trino.testing.BaseConnectorTest.testDataMappingSmokeTest(BaseConnectorTest.java:2834)
2022-03-05T05:14:57.2608798Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-03-05T05:14:57.2609461Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-03-05T05:14:57.2610232Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-03-05T05:14:57.2610846Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-03-05T05:14:57.2611426Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-03-05T05:14:57.2612004Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-03-05T05:14:57.2612500Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-03-05T05:14:57.2613029Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-03-05T05:14:57.2613616Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-03-05T05:14:57.2614335Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-03-05T05:14:57.2614939Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-03-05T05:14:57.2615851Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-03-05T05:14:57.2616338Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-03-05T05:14:57.2617612Z 	Suppressed: java.lang.Exception: SQL: CREATE TABLE test_data_mapping_smoke_boolean_1kqrpc5bqo AS SELECT CAST(row_id AS varchar(50)) row_id, CAST(value AS boolean) value FROM (VALUES   ('null value', NULL),   ('sample value', false),   ('high value', true))  t(row_id, value)
2022-03-05T05:14:57.2618423Z 		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:509)
2022-03-05T05:14:57.2618837Z 		... 19 more
2022-03-05T05:14:57.2619239Z Caused by: io.trino.spi.TrinoException: ERROR 722 (43M05): Schema does not exist schemaName=TPCH
2022-03-05T05:14:57.2619758Z 	at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:890)
2022-03-05T05:14:57.2620346Z 	at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:876)
2022-03-05T05:14:57.2620898Z 	at io.trino.plugin.phoenix.PhoenixClient.execute(PhoenixClient.java:237)
2022-03-05T05:14:57.2621501Z 	at io.trino.plugin.phoenix.PhoenixClient.beginCreateTable(PhoenixClient.java:581)
2022-03-05T05:14:57.2622154Z 	at io.trino.plugin.phoenix.PhoenixMetadata.beginCreateTable(PhoenixMetadata.java:154)
2022-03-05T05:14:57.2622813Z 	at io.trino.spi.connector.ConnectorMetadata.beginCreateTable(ConnectorMetadata.java:472)
2022-03-05T05:14:57.2623685Z 	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.beginCreateTable(ClassLoaderSafeConnectorMetadata.java:446)
2022-03-05T05:14:57.2624616Z 	at io.trino.metadata.MetadataManager.beginCreateTable(MetadataManager.java:886)
2022-03-05T05:14:57.2625302Z 	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:253)
2022-03-05T05:14:57.2626005Z 	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:197)
2022-03-05T05:14:57.2626713Z 	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:100)
2022-03-05T05:14:57.2627352Z 	at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
2022-03-05T05:14:57.2627984Z 	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
2022-03-05T05:14:57.2628669Z 	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
2022-03-05T05:14:57.2629313Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
2022-03-05T05:14:57.2629826Z 	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
2022-03-05T05:14:57.2630307Z 	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
2022-03-05T05:14:57.2630838Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2022-03-05T05:14:57.2631458Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2022-03-05T05:14:57.2632075Z 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
2022-03-05T05:14:57.2632653Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2022-03-05T05:14:57.2633232Z 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
2022-03-05T05:14:57.2633896Z 	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
2022-03-05T05:14:57.2634582Z 	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
2022-03-05T05:14:57.2635232Z 	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
2022-03-05T05:14:57.2635831Z 	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
2022-03-05T05:14:57.2636383Z 	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
2022-03-05T05:14:57.2636994Z 	at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
2022-03-05T05:14:57.2637749Z 	at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:85)
2022-03-05T05:14:57.2638338Z 	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:230)
2022-03-05T05:14:57.2638874Z 	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:215)
2022-03-05T05:14:57.2639395Z 	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:210)
2022-03-05T05:14:57.2639945Z 	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:465)
2022-03-05T05:14:57.2640547Z 	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:446)
2022-03-05T05:14:57.2641123Z 	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:387)
2022-03-05T05:14:57.2641686Z 	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
2022-03-05T05:14:57.2642292Z 	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
2022-03-05T05:14:57.2642829Z 	at io.trino.$gen.Trino_testversion____20220305_050254_3.run(Unknown Source)
2022-03-05T05:14:57.2643363Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-03-05T05:14:57.2644001Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-03-05T05:14:57.2644476Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-03-05T05:14:57.2645003Z 	Suppressed: java.lang.RuntimeException: Query: CREATE SEQUENCE "TPCH"."TEST_DATA_MAPPING_SMOKE_BOOLEAN_1KQRPC5BQO_sequence"
2022-03-05T05:14:57.2645591Z 		at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:891)
2022-03-05T05:14:57.2646019Z 		... 40 more
2022-03-05T05:14:57.2646324Z 	Suppressed: java.lang.Exception: Current plan:
2022-03-05T05:14:57.2646641Z                 Output[rows]
2022-03-05T05:14:57.2647079Z                 │   Layout: [rows:bigint]
2022-03-05T05:14:57.2647592Z                 └─ TableCommit[phoenix.tpch.test_data_mapping_smoke_boolean_1kqrpc5bqo]
2022-03-05T05:14:57.2648076Z                    │   Layout: [rows:bigint]
2022-03-05T05:14:57.2648474Z                    └─ LocalExchange[SINGLE] ()
2022-03-05T05:14:57.2648954Z                       │   Layout: [partialrows:bigint, fragment:varbinary]
2022-03-05T05:14:57.2649375Z                       └─ RemoteExchange[GATHER]
2022-03-05T05:14:57.2649849Z                          │   Layout: [partialrows:bigint, fragment:varbinary]
2022-03-05T05:14:57.2698913Z                          └─ TableWriter
2022-03-05T05:14:57.2699683Z                             │   Layout: [partialrows:bigint, fragment:varbinary]
2022-03-05T05:14:57.2700128Z                             │   row_id := expr
2022-03-05T05:14:57.2700544Z                             │   value := field_0
2022-03-05T05:14:57.2700963Z                             └─ LocalExchange[SINGLE] ()
2022-03-05T05:14:57.2701427Z                                │   Layout: [expr:varchar(50), field_0:boolean]
2022-03-05T05:14:57.2701902Z                                └─ RemoteExchange[REPARTITION]
2022-03-05T05:14:57.2702405Z                                   │   Layout: [expr:varchar(50), field_0:boolean]
2022-03-05T05:14:57.2702805Z                                   └─ Values
2022-03-05T05:14:57.2703129Z                                          Layout: [expr:varchar(50), field_0:boolean]
2022-03-05T05:14:57.2703763Z                                          (CAST('null value' AS varchar(50)), CAST(null AS boolean))
2022-03-05T05:14:57.2704240Z                                          (CAST('sample value' AS varchar(50)), false)
2022-03-05T05:14:57.2704689Z                                          (CAST('high value' AS varchar(50)), true)
2022-03-05T05:14:57.2704887Z 
2022-03-05T05:14:57.2705211Z 		at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:91)
2022-03-05T05:14:57.2705616Z 		... 12 more
2022-03-05T05:14:57.2706074Z Caused by: org.apache.phoenix.schema.SchemaNotFoundException: ERROR 722 (43M05): Schema does not exist schemaName=TPCH
2022-03-05T05:14:57.2706922Z 	at org.apache.phoenix.compile.FromCompiler$BaseColumnResolver.createSchemaRef(FromCompiler.java:538)
2022-03-05T05:14:57.2707512Z 	at org.apache.phoenix.compile.FromCompiler$SchemaResolver.<init>(FromCompiler.java:315)
2022-03-05T05:14:57.2708107Z 	at org.apache.phoenix.compile.FromCompiler.getResolverForSchema(FromCompiler.java:241)
2022-03-05T05:14:57.2708728Z 	at org.apache.phoenix.schema.MetaDataClient.createSequence(MetaDataClient.java:1733)
2022-03-05T05:14:57.2709335Z 	at org.apache.phoenix.compile.CreateSequenceCompiler$1.execute(CreateSequenceCompiler.java:239)
2022-03-05T05:14:57.2709912Z 	at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:408)
2022-03-05T05:14:57.2710430Z 	at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:391)
2022-03-05T05:14:57.2710916Z 	at org.apache.phoenix.call.CallRunner.run(CallRunner.java:53)
2022-03-05T05:14:57.2711442Z 	at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:390)
2022-03-05T05:14:57.2712074Z 	at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:378)
2022-03-05T05:14:57.2712662Z 	at org.apache.phoenix.jdbc.PhoenixStatement.execute(PhoenixStatement.java:1825)
2022-03-05T05:14:57.2713191Z 	at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:887)
2022-03-05T05:14:57.2713520Z 	... 40 more
```

https://github.com/trinodb/trino/runs/5430335432

**Comment by sabirali2560** [comment]
Hi I want to work on this issue. Could someone please assign it to me.

**Comment by ebyhr** [comment]
Different error, but I guess the root cause is same. https://github.com/trinodb/trino/runs/7015686192

**Comment by findepi** [comment]
Different test class, but problem seems the same
https://github.com/trinodb/trino/actions/runs/4022709157/jobs/6913239950

```
Error:  io.trino.plugin.phoenix5.TestPhoenixTypeMapping.testChar  Time elapsed: 5.19 s  <<< FAILURE!
java.lang.RuntimeException: 
Error executing sql:
CREATE TABLE tpch.test_chark0f86547ol (
col_0 char(10),
col_1 char(255),
col_2 char(65536),
col_3 char(10),
col_4 integer primary key)
	at io.trino.plugin.phoenix5.PhoenixSqlExecutor.execute(PhoenixSqlExecutor.java:54)
	at io.trino.testing.sql.TestTable.createAndInsert(TestTable.java:56)
	at io.trino.testing.sql.TestTable.<init>(TestTable.java:44)
	at io.trino.testing.sql.TestTable.<init>(TestTable.java:36)
	at io.trino.testing.datatype.CreateAndInsertDataSetup.createTestTable(CreateAndInsertDataSetup.java:64)
	at io.trino.testing.datatype.CreateAndInsertDataSetup.setupTemporaryRelation(CreateAndInsertDataSetup.java:43)
	at io.trino.testing.datatype.CreateAndInsertDataSetup.setupTemporaryRelation(CreateAndInsertDataSetup.java:28)
	at io.trino.testing.datatype.SqlDataTypeTest.execute(SqlDataTypeTest.java:90)
	at io.trino.testing.datatype.SqlDataTypeTest.execute(SqlDataTypeTest.java:84)
	at io.trino.plugin.phoenix5.TestPhoenixTypeMapping.testChar(TestPhoenixTypeMapping.java:388)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.phoenix.schema.SchemaNotFoundException: ERROR 722 (43M05): Schema does not exist schemaName=TPCH
	at org.apache.phoenix.compile.FromCompiler$BaseColumnResolver.createSchemaRef(FromCompiler.java:737)
	at org.apache.phoenix.compile.FromCompiler$SchemaResolver.<init>(FromCompiler.java:346)
	at org.apache.phoenix.compile.FromCompiler.getResolverForCreation(FromCompiler.java:166)
	at org.apache.phoenix.compile.CreateTableCompiler.compile(CreateTableCompiler.java:88)
	at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableCreateTableStatement.compilePlan(PhoenixStatement.java:880)
	at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableCreateTableStatement.compilePlan(PhoenixStatement.java:869)
	at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:433)
	at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:423)
	at org.apache.phoenix.call.CallRunner.run(CallRunner.java:53)
	at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:422)
	at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:410)
	at org.apache.phoenix.jdbc.PhoenixStatement.execute(PhoenixStatement.java:1986)
	at io.trino.plugin.phoenix5.PhoenixSqlExecutor.execute(PhoenixSqlExecutor.java:50)
	... 22 more

[INFO] 
[INFO] Results:
```

**Comment by nineinchnick** [comment]
I hit that in https://github.com/trinodb/trino/actions/runs/4042500349/jobs/6950833968

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/4572435133/jobs/8075033039?pr=16817

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/5608327470/jobs/10260605325?pr=18343
