### ISSUE TITLE
Trino client unable to connect to Trino server [Caused by: java.io.UncheckedIOException: javax.net.ssl.SSLPeerUnverifiedException: Hostname trino-dev.mydomain.net not verified ]

### ISSUE THREAD

**Issue by DwijadasDey** [trinodb/trino#11349]
Hi
I have configured Trino server(v371) with SSL and user authentication. The server is up and i can access the web UI.
However, if i try to connect trino server using following command from a remote trino client, i am getting following error.

`#  ./trino --server https://trino-dev.mydomain.net:8443 --catalog druid --schema default --user trino --password
`
```
java.util.concurrent.ExecutionException: java.io.UncheckedIOException: javax.net.ssl.SSLPeerUnverifiedException: Hostname trino-dev.mydomain.net not verified:
    certificate: sha256/1dSVIYFkotrcUf2AwvQEhPSEQyoEeiOZ14Dsg3h2TdY=
    DN: CN=trino-dev, OU=BDP, O=Company, L=San Jose, ST=CA, C=US
    subjectAltNames: []
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:527)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:104)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:240)
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2313)
        at com.google.common.cache.LocalCache$Segment$1.run(LocalCache.java:2293)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
        at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:724)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:126)
        at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2288)
        at com.google.common.cache.LocalCache$Segment.refresh(LocalCache.java:2360)
        at com.google.common.cache.LocalCache.refresh(LocalCache.java:4134)
        at com.google.common.cache.LocalCache$LocalLoadingCache.refresh(LocalCache.java:4965)
        at io.trino.cli.TableNameCompleter.lambda$populateCache$0(TableNameCompleter.java:95)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.UncheckedIOException: javax.net.ssl.SSLPeerUnverifiedException: Hostname trino-dev.mydomain.net not verified:
    certificate: sha256/1dSVIYFkotrcUf2AwvQEhPSEQyoEeiOZ14Dsg3h2TdY=
    DN: CN=trino-dev, OU=BDP, O=Company, L=San Jose, ST=CA, C=US
    subjectAltNames: []
        at io.trino.client.JsonResponse.execute(JsonResponse.java:148)
        at io.trino.client.StatementClientV1.<init>(StatementClientV1.java:109)
        at io.trino.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24)
        at io.trino.cli.QueryRunner.startInternalQuery(QueryRunner.java:153)
        at io.trino.cli.QueryRunner.startInternalQuery(QueryRunner.java:144)
        at io.trino.cli.TableNameCompleter.queryMetadata(TableNameCompleter.java:76)
        at io.trino.cli.TableNameCompleter.listFunctions(TableNameCompleter.java:70)
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168)
        at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadAsync(LocalCache.java:2287)
        ... 7 more
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname trino-dev.mydomain.net not verified:
    certificate: sha256/1dSVIYFkotrcUf2AwvQEhPSEQyoEeiOZ14Dsg3h2TdY=
    DN: CN=trino-dev, OU=BDP, O=Company, L=San Jose, ST=CA, C=US
    subjectAltNames: []
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:350)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at io.trino.client.OkHttpUtil.lambda$basicAuth$1(OkHttpUtil.java:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at io.trino.client.JsonResponse.execute(JsonResponse.java:130)
        ... 17 more
```
The error is due to trino client is unable to verify the host name in the SSL certificate sent by the trino  server during the connect process.

However, i have created the trino server SSL certificate using SAN that includes both IP and DNS

`#  keytool -genkeypair -alias trino_keystore -validity 3650 -keyalg RSA -dname "CN=trino-dev,OU=BDP,O=Company,L=San Jose,S=CA,C=US" -ext SAN=DNS:trino-dev.mydomain.net,IP:172.16.10.85 -keypass password123 -keystore /u01/olap/trino/server_ssl_cert/trino_keystore.jks -storepass password123 -storetype pkcs12`

The hostname verification error is discussed here #6172

What is the solution for the issue ? 

Thanks

**Comment by DwijadasDey** [comment]
I need to import Trino servers trust certificate in the client system using `keytool` command and the trino client able to connect Trino  server.
