### ISSUE TITLE
Flaky test TestHiveTaskFailureRecoveryTest.testJoinDynamicFilteringDisabled

### ISSUE THREAD

**Issue by raunaqmorarka** [trinodb/trino#11368]
```
2022-03-08T05:47:59.6709044Z 2022-03-07T23:47:59.442-0600	INFO	pool-3-thread-1	io.trino.testng.services.LogTestDurationListener	Test io.trino.plugin.hive.TestHiveTaskFailureRecoveryTest.testJoinDynamicFilteringDisabled took 39.62s
2022-03-08T05:47:59.6710734Z 2022-03-07T23:47:59.510-0600	ERROR	pool-3-thread-1	io.trino.testng.services.ProgressLoggingListener	[TEST FAILURE] io.trino.plugin.hive.TestHiveTaskFailureRecoveryTest.testJoinDynamicFilteringDisabled; (took: 39.6 seconds)
2022-03-08T05:47:59.6711801Z java.lang.AssertionError: expected [1] but found [0]
2022-03-08T05:47:59.6712187Z 	at org.testng.Assert.fail(Assert.java:94)
2022-03-08T05:47:59.6712586Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2022-03-08T05:47:59.6713032Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2022-03-08T05:47:59.6713456Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2022-03-08T05:47:59.6713872Z 	at org.testng.Assert.assertEquals(Assert.java:389)
2022-03-08T05:47:59.6714281Z 	at org.testng.Assert.assertEquals(Assert.java:399)
2022-03-08T05:47:59.6714893Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.finishesSuccessfully(BaseFailureRecoveryTest.java:619)
2022-03-08T05:47:59.6715708Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.finishesSuccessfully(BaseFailureRecoveryTest.java:609)
2022-03-08T05:47:59.6716442Z 	at io.trino.testing.BaseFailureRecoveryTest.testSelect(BaseFailureRecoveryTest.java:209)
2022-03-08T05:47:59.6717109Z 	at io.trino.testing.BaseFailureRecoveryTest.testSelect(BaseFailureRecoveryTest.java:185)
2022-03-08T05:47:59.6717870Z 	at io.trino.testing.BaseFailureRecoveryTest.testJoinDynamicFilteringDisabled(BaseFailureRecoveryTest.java:154)
2022-03-08T05:47:59.6718622Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-03-08T05:47:59.6719304Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-03-08T05:47:59.6720062Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-03-08T05:47:59.6720661Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-03-08T05:47:59.6721242Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-03-08T05:47:59.6722089Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-03-08T05:47:59.6722592Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-03-08T05:47:59.6723105Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-03-08T05:47:59.6723701Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-03-08T05:47:59.6724299Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-03-08T05:47:59.6725079Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-03-08T05:47:59.6725707Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-03-08T05:47:59.6726200Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```
https://github.com/trinodb/trino/runs/5459930338?check_suite_focus=true

**Comment by findepi** [comment]
cc @arhimondr @losipiuk @linzebing

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/5492136290

**Comment by linzebing** [comment]
I will look into this.

**Comment by linzebing** [comment]
Another stack trace
```
io.trino.plugin.hive.TestHiveTaskFailureRecoveryTest.testJoinDynamicFilteringDisabled; (took: 39.8 seconds)
2022-03-10T07:47:08.9707364Z java.lang.AssertionError: For query: 
2022-03-10T07:47:08.9708363Z  SELECT * FROM partitioned_lineitem JOIN supplier ON partitioned_lineitem.suppkey = supplier.suppkey AND supplier.name = 'Supplier#000000001'
2022-03-10T07:47:08.9708723Z not equal
2022-03-10T07:47:08.9708989Z Actual rows (up to 100 of 0 extra rows shown, 0 rows in total):
2022-03-10T07:47:08.9709223Z     
2022-03-10T07:47:08.9709492Z Expected rows (up to 100 of 615 missing rows shown, 615 rows in total):
2022-03-10T07:47:08.9710077Z     [50084, 1386, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9710703Z     [50179, 1520, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9711624Z     [50208, 800, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9712238Z     [50210, 1600, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9713248Z     [50245, 1618, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9714036Z     [50439, 200, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9714656Z     [50758, 669, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9715758Z     [50791, 1030, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9716477Z     [50853, 1912, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9717087Z     [51009, 1871, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9718324Z     [51011, 413, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9718938Z     [51077, 1912, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9720759Z     [51200, 1871, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9721410Z     [51462, 1030, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9722025Z     [51685, 669, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9722632Z     [51814, 1600, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9723225Z     [51872, 570, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9725335Z     [51906, 1857, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9725961Z     [51910, 834, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9726565Z     [52071, 998, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9731143Z     [52192, 1200, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9731755Z     [52391, 1386, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9732369Z     [52736, 834, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9732981Z     [52900, 1500, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9750125Z     [52965, 1600, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9750757Z     [53030, 25, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9830567Z     [53091, 1700, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9831457Z     [53125, 801, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9832087Z     [53344, 1814, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9832887Z     [53413, 273, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9833500Z     [53447, 540, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9861828Z     [53703, 442, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9863001Z     [53825, 1164, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9863638Z     [54021, 100, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9864244Z     [54054, 100, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:08.9864858Z     [54336, 1100, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0155231Z     [54368, 607, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0155899Z     [54498, 300, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0156534Z     [54502, 1226, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0157131Z     [54626, 219, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0157745Z     [54657, 1857, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0158368Z     [54721, 1758, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0158976Z     [55011, 300, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0159576Z     [55079, 1520, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0160183Z     [55079, 1263, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0160794Z     [55104, 1716, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0161395Z     [55143, 1677, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0161996Z     [55205, 1900, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0162578Z     [55330, 638, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0163194Z     [55360, 1362, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0163804Z     [55365, 1263, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0164408Z     [55365, 607, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0165010Z     [55398, 1095, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0165853Z     [55425, 1500, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0166474Z     [55586, 768, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0167081Z     [55713, 1618, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0167800Z     [55713, 669, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0168392Z     [55783, 1800, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0169038Z     [55813, 1700, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0169652Z     [55972, 100, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0170256Z     [55974, 1386, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0170857Z     [56037, 834, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0171447Z     [56067, 932, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0172055Z     [56262, 1263, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0172657Z     [56290, 1677, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0173405Z     [56357, 1300, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0173991Z     [56453, 1956, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0174586Z     [56544, 834, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0175191Z     [56772, 1900, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0175798Z     [56929, 246, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0274226Z     [57185, 1520, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0275055Z     [57284, 998, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0275680Z     [57447, 1095, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0276302Z     [57574, 736, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0287586Z     [57633, 100, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0288244Z     [57698, 1560, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0288861Z     [57698, 1128, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0301461Z     [57699, 471, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0302276Z     [57732, 273, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0303599Z     [57732, 148, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0304242Z     [57733, 1814, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0305721Z     [57763, 442, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0311822Z     [58052, 607, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0312528Z     [58178, 1461, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0316165Z     [58214, 801, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0316815Z     [58310, 25, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0317443Z     [58465, 1871, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0320979Z     [58564, 1030, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0321604Z     [58757, 932, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0338749Z     [58785, 1580, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0348155Z     [58884, 413, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0348806Z     [58913, 1677, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0349423Z     [58916, 2000, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0350047Z     [59011, 998, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0350645Z     [59329, 1956, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0351262Z     [59334, 1659, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0369726Z     [59558, 768, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0373010Z     [59586, 570, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0373750Z     [59623, 50, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0374383Z     [59809, 1857, 1, 1, Supplier#000000001,  N kD4on9OM Ipw3,gf0JBoQDd7tgrzrddZ, 17, 27-918-335-1736, 5755.94, each slyly above the careful]
2022-03-10T07:47:09.0374617Z 
2022-03-10T07:47:09.0374757Z 	at org.testng.Assert.fail(Assert.java:94)
2022-03-10T07:47:09.0375193Z 	at io.trino.testing.QueryAssertions.assertEqualsIgnoreOrder(QueryAssertions.java:237)
2022-03-10T07:47:09.0376032Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.finishesSuccessfully(BaseFailureRecoveryTest.java:646)
2022-03-10T07:47:09.0376719Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.finishesSuccessfully(BaseFailureRecoveryTest.java:609)
2022-03-10T07:47:09.0450056Z 	at io.trino.testing.BaseFailureRecoveryTest.testSelect(BaseFailureRecoveryTest.java:216)
2022-03-10T07:47:09.0450705Z 	at io.trino.testing.BaseFailureRecoveryTest.testSelect(BaseFailureRecoveryTest.java:185)
2022-03-10T07:47:09.0451603Z 	at io.trino.testing.BaseFailureRecoveryTest.testJoinDynamicFilteringDisabled(BaseFailureRecoveryTest.java:154)
2022-03-10T07:47:09.0452227Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-03-10T07:47:09.0452802Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-03-10T07:47:09.0453632Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-03-10T07:47:09.0454151Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-03-10T07:47:09.0454629Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-03-10T07:47:09.0455127Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-03-10T07:47:09.0455544Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-03-10T07:47:09.0478515Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-03-10T07:47:09.0479046Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-03-10T07:47:09.0479546Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-03-10T07:47:09.0480058Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-03-10T07:47:09.0480784Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-03-10T07:47:09.0481852Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/runs/5790074728?check_suite_focus=true

**Comment by arhimondr** [comment]
Looking

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/5878088000

**Comment by arhimondr** [comment]
https://github.com/trinodb/trino/pull/11870
