### ISSUE TITLE
PostgreSQL BIT should be mapped to a VARBINARY in Trino

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#11384]
PostgreSQL BIT is a bitstring and can be > 1 bit.

Today we map all single-bit values to a boolean but don't properly handle other values.

This can be demonstrated by following test:

```java
@Test
public void testBit()
{
    SqlDataTypeTest.create()
            .addRoundTrip("bit", "NULL", VARBINARY, "CAST(NULL AS BOOLEAN)")
            .addRoundTrip("bit(2)", "B'10'", VARBINARY, "CAST(NULL AS BOOLEAN)")
            .execute(getQueryRunner(), postgresCreateAndInsert("tpch.test_bit"));
}
```

This fails with:

```
2022-03-09T01:12:11.906-0600 SEVERE Error processing Split 20220309_071211_00000_6bnz8.1.0.0-0 io.trino.plugin.jdbc.JdbcSplit@26f014ef (start = 5.61837068556718E8, wall = 51 ms, cpu = 0 ms, wait = 0 ms, calls = 1): JDBC_ERROR: Cannot cast to boolean: "10"
io.trino.spi.TrinoException: Cannot cast to boolean: "10"
	at io.trino.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:299)
	at io.trino.plugin.jdbc.JdbcRecordCursor.getBoolean(JdbcRecordCursor.java:186)
	at io.trino.spi.connector.RecordPageSource.getNextPage(RecordPageSource.java:103)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:693)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_testversion____20220309_071205_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.postgresql.util.PSQLException: Cannot cast to boolean: "10"
	at org.postgresql.jdbc.BooleanTypeUtil.cannotCoerceException(BooleanTypeUtil.java:99)
	at org.postgresql.jdbc.BooleanTypeUtil.fromString(BooleanTypeUtil.java:67)
	at org.postgresql.jdbc.BooleanTypeUtil.castToBoolean(BooleanTypeUtil.java:43)
	at org.postgresql.jdbc.PgResultSet.getBoolean(PgResultSet.java:2215)
	at io.trino.plugin.jdbc.JdbcRecordCursor.getBoolean(JdbcRecordCursor.java:183)
	... 13 more
```

**Comment by hashhar** [comment]
Also existing type mapping to boolean also causes issues when predicates are pushed down:

```java
@Test
public void testBoolean()
{
    SqlDataTypeTest.create()
            .addRoundTrip("bit", "B'1'", BOOLEAN, "TRUE")
            .addRoundTrip("bit", "B'0'", BOOLEAN, "FALSE")
            .addRoundTrip("bit", "NULL", BOOLEAN, "CAST(NULL AS BOOLEAN)")
            .execute(getQueryRunner(), postgresCreateAndInsert("tpch.test_bit"))
            .execute(getQueryRunner(), postgresCreateTrinoInsert("tpch.test_bit"));
}
```

**Comment by ebyhr** [comment]
I believe other JDBC connectors also have the same issue. e.g. MemSQL connector
