### ISSUE TITLE
PostgreSQL predicates on ARRAY containing NULLs fails

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#11386]
Trino doesn't allow comparing arrays with null elements so if we pushdown such operations queries fail.

For example:

```java
@Test
public void testArrayEmptyOrNulls()
{
    SqlDataTypeTest.create()
           .addRoundTrip("ARRAY(bigint)", "ARRAY[]", new ArrayType(BIGINT), "CAST(ARRAY[] AS ARRAY(BIGINT))")
            .addRoundTrip("ARRAY(boolean)", "NULL", new ArrayType(BOOLEAN), "CAST(NULL AS ARRAY(BOOLEAN))")
            .addRoundTrip("ARRAY(real)", "NULL", new ArrayType(REAL), "CAST(NULL AS ARRAY(REAL))")
            .addRoundTrip("ARRAY(integer)", "ARRAY[1, NULL, 3, NULL]", new ArrayType(INTEGER), "ARRAY[1, NULL, 3, NULL]")
            .execute(getQueryRunner(), sessionWithArrayAsArray(), trinoCreateAsSelect(sessionWithArrayAsArray(), "test_array_empty_or_nulls"))
            .execute(getQueryRunner(), sessionWithArrayAsArray(), trinoCreateAndInsert(sessionWithArrayAsArray(), "test_array_empty_or_nulls"));
}
```

```
java.lang.RuntimeException: ARRAY comparison not supported for arrays with null elements

	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:507)
	at io.trino.testing.datatype.SqlDataTypeTest.verifyPredicate(SqlDataTypeTest.java:117)
	at io.trino.testing.datatype.SqlDataTypeTest.execute(SqlDataTypeTest.java:80)
	at io.trino.plugin.postgresql.TestPostgreSqlTypeMapping.testArrayEmptyOrNulls(TestPostgreSqlTypeMapping.java:876)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
	Suppressed: java.lang.Exception: SQL: SELECT 'all found' FROM test_array_empty_or_nullsfnm9d2ss8e WHERE col_0 IS NOT DISTINCT FROM CAST(ARRAY[] AS ARRAY(BIGINT)) AND col_1 IS NOT DISTINCT FROM CAST(NULL AS ARRAY(BOOLEAN)) AND col_2 IS NOT DISTINCT FROM CAST(NULL AS ARRAY(REAL)) AND col_3 IS NOT DISTINCT FROM ARRAY[1, NULL, 3, NULL]
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:510)
		... 27 more
Caused by: io.trino.spi.TrinoException: ARRAY comparison not supported for arrays with null elements
	at io.trino.spi.type.TypeUtils.checkElementNotNull(TypeUtils.java:116)
	at io.trino.spi.type.ArrayType.comparisonOperator(ArrayType.java:371)
	at io.trino.spi.predicate.Range.compareValues(Range.java:372)
	at io.trino.spi.predicate.Range.tryMergeWithNext(Range.java:275)
	at io.trino.spi.predicate.SortedRangeSet.buildFromUnsortedRanges(SortedRangeSet.java:1013)
	at io.trino.spi.predicate.SortedRangeSet.copyOf(SortedRangeSet.java:267)
	at io.trino.spi.predicate.SortedRangeSet.copyOf(SortedRangeSet.java:275)
	at io.trino.spi.predicate.SortedRangeSet.of(SortedRangeSet.java:244)
	at io.trino.spi.predicate.ValueSet.ofRanges(ValueSet.java:80)
	at io.trino.sql.planner.DomainTranslator$Visitor.extractOrderableDomain(DomainTranslator.java:641)
	at io.trino.sql.planner.DomainTranslator$Visitor.createComparisonExtractionResult(DomainTranslator.java:608)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitComparisonExpression(DomainTranslator.java:494)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitComparisonExpression(DomainTranslator.java:322)
	at io.trino.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:71)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitNotExpression(DomainTranslator.java:466)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitNotExpression(DomainTranslator.java:322)
	at io.trino.sql.tree.NotExpression.accept(NotExpression.java:54)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.DomainTranslator$Visitor.lambda$visitLogicalExpression$0(DomainTranslator.java:377)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitLogicalExpression(DomainTranslator.java:378)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitLogicalExpression(DomainTranslator.java:322)
	at io.trino.sql.tree.LogicalExpression.accept(LogicalExpression.java:80)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.DomainTranslator.getExtractionResult(DomainTranslator.java:319)
	at io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan.pushFilterIntoTableScan(PushPredicateIntoTableScan.java:171)
	at io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan.apply(PushPredicateIntoTableScan.java:111)
	at io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan.apply(PushPredicateIntoTableScan.java:77)
	at io.trino.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:202)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:169)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:132)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:235)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:134)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:235)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:134)
	at io.trino.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:117)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:230)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:215)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:210)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:465)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:446)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:387)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20220309_075157_3.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by findepi** [comment]
> Trino doesn't allow comparing arrays with null elements so if we pushdown such operations queries fail.

Would query not fail if pushdown did not happen?

(i guess yes, if the source table is empty, or contains only NULL entries in the array column)

**Comment by hashhar** [comment]
Thank you for checking. the error comes from engine, not connector so pushdown doesn't matter anyway.

The reason why I thought of pushdown first was because I noticed this while using SqlDataTypeTest.

I close this and create a more general purpose issue for the engine if needed.
