### ISSUE TITLE
Flaky `TestHiveDynamicPartitionPruningTest.testJoinWithEmptyBuildSide`

### ISSUE THREAD

**Issue by ssheikin** [trinodb/trino#11408]
```
2022-03-09T09:46:20.1563106Z [ERROR] Tests run: 3124, Failures: 1, Errors: 0, Skipped: 92, Time elapsed: 2,348.463 s <<< FAILURE! - in TestSuite
2022-03-09T09:46:20.1564177Z [ERROR] io.trino.plugin.hive.TestHiveDynamicPartitionPruningTest.testJoinWithEmptyBuildSide  Time elapsed: 3.617 s  <<< FAILURE!
2022-03-09T09:46:20.1565293Z java.lang.AssertionError: expected [true] but found [false]
2022-03-09T09:46:20.1565839Z 	at org.testng.Assert.fail(Assert.java:94)
2022-03-09T09:46:20.1566457Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2022-03-09T09:46:20.1567249Z 	at org.testng.Assert.assertTrue(Assert.java:42)
2022-03-09T09:46:20.1567663Z 	at org.testng.Assert.assertTrue(Assert.java:52)
2022-03-09T09:46:20.1568270Z 	at io.trino.testing.BaseDynamicPartitionPruningTest.testJoinWithEmptyBuildSide(BaseDynamicPartitionPruningTest.java:119)
2022-03-09T09:46:20.1568947Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-03-09T09:46:20.1569504Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-03-09T09:46:20.1570139Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-03-09T09:46:20.1570672Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-03-09T09:46:20.1571169Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-03-09T09:46:20.1571709Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2022-03-09T09:46:20.1572214Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2022-03-09T09:46:20.1572839Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-03-09T09:46:20.1573281Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-03-09T09:46:20.1573760Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-03-09T09:46:20.1574475Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-03-09T09:46:20.1574888Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-03-09T09:46:20.1575327Z 
2022-03-09T09:46:20.8780123Z [INFO] 
2022-03-09T09:46:20.8782385Z [INFO] Results:
2022-03-09T09:46:20.8782834Z [INFO] 
2022-03-09T09:46:20.8783168Z [ERROR] Failures: 
2022-03-09T09:46:20.8805769Z [ERROR]   TestHiveDynamicPartitionPruningTest>BaseDynamicPartitionPruningTest.testJoinWithEmptyBuildSide:119 expected [true] but found [false]
2022-03-09T09:46:20.8806376Z [INFO] 
2022-03-09T09:46:20.8832222Z [ERROR] Tests run: 3124, Failures: 1, Errors: 0, Skipped: 92
```
https://github.com/trinodb/trino/runs/5477229326?check_suite_focus=true

**Comment by ssheikin** [comment]
@kokosing I'm not sure that we have to annotate test with `@Flaky` if it's already annotated with `@Test(timeOut = ...)`.
Either we have not to do this at all or annotate all such tests (or process all tests already annotated with `@Test(timeOut = ...)` as flaky)

**Comment by kokosing** [comment]
CC: @sopel39 @raunaqmorarka 

I would prefer to fix the test instead. `@Flaky` annotation is last resort and not always works.
