### ISSUE TITLE
Flaky `TestDeltaLakeCreateTableStatisticsOptimizedWriter.testMultiFileTableWithNaNValue`

### ISSUE THREAD

**Issue by ssheikin** [trinodb/trino#11407]
```
Error:  Tests run: 792, Failures: 1, Errors: 0, Skipped: 54, Time elapsed: 2,025.537 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.deltalake.TestDeltaLakeCreateTableStatisticsOptimizedWriter.testMultiFileTableWithNaNValue  Time elapsed: 1.363 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting:
 <1>
to be greater than:
 <1> 
	at io.trino.plugin.deltalake.AbstractTestDeltaLakeCreateTableStatistics.testMultiFileTableWithNaNValue(AbstractTestDeltaLakeCreateTableStatistics.java:473)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
https://github.com/trinodb/trino/runs/5482452933?check_suite_focus=true

**Comment by findepi** [comment]
cc @jirassimok @alexjo2144

**Comment by findepi** [comment]
This reproduces for my locally with `@Test(invocationCount = 1000)`.
cc @homar
