### ISSUE TITLE
Flaky test io.trino.plugin.iceberg.TestIcebergParquetConnectorTest.testReadMetadataWithRelationsConcurrentModifications

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#11435]
```
Error:  io.trino.plugin.iceberg.TestIcebergParquetConnectorTest.testReadMetadataWithRelationsConcurrentModifications  Time elapsed: 0.478 s  <<< FAILURE!
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to open input stream for file: /tmp/TrinoTest14022721672366748770/iceberg_data/tpch/concur_table_mydics6qx7/metadata/00000-be2ebe87-aa3e-465d-8181-f2ac8662a625.metadata.json
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.trino.testing.BaseConnectorTest.testReadMetadataWithRelationsConcurrentModifications(BaseConnectorTest.java:1290)
	at io.trino.testing.BaseConnectorTest.testReadMetadataWithRelationsConcurrentModifications(BaseConnectorTest.java:1229)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Failed to open input stream for file: /tmp/TrinoTest14022721672366748770/iceberg_data/tpch/concur_table_mydics6qx7/metadata/00000-be2ebe87-aa3e-465d-8181-f2ac8662a625.metadata.json
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:507)
	at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:215)
	at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:210)
	at io.trino.testing.BaseConnectorTest$1.call(BaseConnectorTest.java:1312)
	at io.trino.testing.BaseConnectorTest$1.call(BaseConnectorTest.java:1306)
	at io.trino.testing.BaseConnectorTest$3.call(BaseConnectorTest.java:1380)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 5 more
	Suppressed: java.lang.Exception: SQL: SELECT * FROM information_schema.columns WHERE table_schema = CURRENT_SCHEMA
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:510)
		... 11 more
	Suppressed: java.lang.Exception: Task: Query(SELECT * FROM information_schema.columns WHERE table_schema = CURRENT_SCHEMA)
		at io.trino.testing.BaseConnectorTest$3.call(BaseConnectorTest.java:1383)
		... 6 more
Caused by: org.apache.iceberg.exceptions.NotFoundException: Failed to open input stream for file: /tmp/TrinoTest14022721672366748770/iceberg_data/tpch/concur_table_mydics6qx7/metadata/00000-be2ebe87-aa3e-465d-8181-f2ac8662a625.metadata.json
	at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:177)
	at io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:97)
	at io.trino.plugin.iceberg.HdfsInputFile.newStream(HdfsInputFile.java:62)
	at org.apache.iceberg.TableMetadataParser.read(TableMetadataParser.java:250)
	at io.trino.plugin.iceberg.catalog.AbstractMetastoreTableOperations.lambda$refreshFromMetadataLocation$4(AbstractMetastoreTableOperations.java:284)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190)
	at io.trino.plugin.iceberg.catalog.AbstractMetastoreTableOperations.refreshFromMetadataLocation(AbstractMetastoreTableOperations.java:283)
	at io.trino.plugin.iceberg.catalog.AbstractMetastoreTableOperations.refresh(AbstractMetastoreTableOperations.java:158)
	at io.trino.plugin.iceberg.catalog.AbstractMetastoreTableOperations.current(AbstractMetastoreTableOperations.java:130)
	at io.trino.plugin.iceberg.TrinoHiveCatalog.lambda$loadTable$10(TrinoHiveCatalog.java:363)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.trino.plugin.iceberg.TrinoHiveCatalog.loadTable(TrinoHiveCatalog.java:361)
	at io.trino.plugin.iceberg.IcebergMetadata.getTableMetadata(IcebergMetadata.java:879)
	at io.trino.plugin.iceberg.IcebergMetadata.lambda$streamTableColumns$42(IcebergMetadata.java:1417)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.lambda$forEachRemaining$1(CollectSpliterators.java:71)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:71)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.trino.metadata.MetadataManager.listTableColumns(MetadataManager.java:611)
	at io.trino.metadata.MetadataListing.listTableColumns(MetadataListing.java:177)
	at io.trino.connector.informationschema.InformationSchemaPageSource.addColumnsRecords(InformationSchemaPageSource.java:251)
	at io.trino.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:216)
	at io.trino.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:183)
	at io.trino.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:392)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:182)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$7(WorkProcessorUtils.java:296)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$3(WorkProcessorUtils.java:219)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$4(WorkProcessorUtils.java:234)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:150)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:693)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_testversion____20220310_125451_5.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.FileNotFoundException: File /tmp/TrinoTest14022721672366748770/iceberg_data/tpch/concur_table_mydics6qx7/metadata/00000-be2ebe87-aa3e-465d-8181-f2ac8662a625.metadata.json does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:666)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:987)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:656)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:454)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:146)
	at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:347)
	at io.trino.plugin.hive.fs.TrinoFileSystemCache$FileSystemWrapper.open(TrinoFileSystemCache.java:307)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:899)
	at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175)
	... 68 more
```

**Comment by findinpath** [comment]
Closing the issue, after gathering more experience on the matter I think the failure of the test is correct and has to do with my implementation which was not taking into account the fact that tables may disappear  between the time we retrieve their schema table name and the time we want to get their metadata
