### ISSUE TITLE
Flaky TestDeltaLakeCreateTableStatisticsOptimizedWriter.testMultiFileTableWithNaNValue

### ISSUE THREAD

**Issue by homar** [trinodb/trino#11471]
> Expecting:
<1>
to be greater than:
<1>
at io.trino.plugin.deltalake.AbstractTestDeltaLakeCreateTableStatistics.testMultiFileTableWithNaNValue(AbstractTestDeltaLakeCreateTableStatistics.java:473)
       	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
       	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
       	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
       	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
       	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
       	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
       	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
       	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
       	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by findepi** [comment]
duplicates https://github.com/trinodb/trino/issues/11407
