### ISSUE TITLE
Flaky test TestParquetPageSkipping.testAndPredicates

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#11505]
https://github.com/trinodb/trino/runs/5554739990?check_suite_focus=true

```
2022-03-15T20:15:12.8369005Z [ERROR] Tests run: 3124, Failures: 1, Errors: 0, Skipped: 92, Time elapsed: 2,386.423 s <<< FAILURE! - in TestSuite
2022-03-15T20:15:12.8370866Z [ERROR] io.trino.plugin.hive.TestParquetPageSkipping.testAndPredicates  Time elapsed: 1.51 s  <<< FAILURE!
2022-03-15T20:15:12.8371688Z org.junit.ComparisonFailure: expected:<[0]L> but was:<[1207]L>
2022-03-15T20:15:12.8372706Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2022-03-15T20:15:12.8373537Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2022-03-15T20:15:12.8374423Z 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2022-03-15T20:15:12.8375279Z 	at io.trino.plugin.hive.TestParquetPageSkipping.lambda$assertRowGroupPruning$2(TestParquetPageSkipping.java:185)
2022-03-15T20:15:12.8376043Z 	at io.trino.testing.AbstractTestQueryFramework.assertQueryStats(AbstractTestQueryFramework.java:471)
2022-03-15T20:15:12.8377733Z 	at io.trino.plugin.hive.TestParquetPageSkipping.assertRowGroupPruning(TestParquetPageSkipping.java:181)
2022-03-15T20:15:12.8378541Z 	at io.trino.plugin.hive.TestParquetPageSkipping.testAndPredicates(TestParquetPageSkipping.java:93)
2022-03-15T20:15:12.8379359Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-03-15T20:15:12.8380026Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-03-15T20:15:12.8380788Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-03-15T20:15:12.8381397Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-03-15T20:15:12.8381987Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-03-15T20:15:12.8382569Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-03-15T20:15:12.8383074Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-03-15T20:15:12.8383598Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-03-15T20:15:12.8384178Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-03-15T20:15:12.8384773Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-03-15T20:15:12.8385379Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-03-15T20:15:12.8386261Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-03-15T20:15:12.8387150Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findepi** [comment]
cc @raunaqmorarka @JamesRTaylor

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/runs/6222742010?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/7745768940?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/8121407727?check_suite_focus=true 

cc @JamesRTaylor @raunaqmorarka
