### ISSUE TITLE
Error running query: Please specify advertisable(s) with '=' or 'IN' syntax

### ISSUE THREAD

**Issue by victordiasadroll** [trinodb/trino#11513]
Hi! I'm running a query similar to this:
```
SELECT
     adv as advertisable,
     ...,
     multiple,
     columns,
     here
FROM
    few,
    joins,
    here
WHERE
    advertisable IN (multiple_22_char_length_strings),
    AND some,
    AND other,
    AND criteria
```
That first condition in the WHERE clause is a list of IDs we want to retrieve data using our pipeline and currently our query needs to fetch data for ~1200 of them. However, upon running the query we get the error message:
`Error running query: Please specify advertisable(s) with '=' or 'IN' syntax`
which doesn't make sense because:
* I'm clearing using the IN predicate;
* if I reduce that list to about 100 of them (without changing anything else in the query), it runs without issues. 
What's going on?

Find the stack trace below:

```
io.trino.spi.TrinoException: Please specify advertisable(s) with '=' or 'IN' syntax
	at io.trino.plugin.hive.nextroll.DomainInterface.enforcePartitions(DomainInterface.java:126)
	at io.trino.plugin.hive.nextroll.S3Metastore.getPartitionNamesByFilter(S3Metastore.java:77)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$getPartitionNamesByFilter$56(ThriftHiveMetastore.java:1216)
	at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getPartitionNamesByFilter(ThriftHiveMetastore.java:1215)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.getPartitionNamesByFilter(BridgingHiveMetastore.java:354)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadPartitionNamesByFilter(CachingHiveMetastore.java:700)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4952)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:259)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getPartitionNamesByFilter(CachingHiveMetastore.java:695)
	at io.trino.plugin.hive.HiveMetastoreClosure.getPartitionNamesByFilter(HiveMetastoreClosure.java:211)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.doGetPartitionNames(SemiTransactionalHiveMetastore.java:787)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.getPartitionNamesByFilter(SemiTransactionalHiveMetastore.java:757)
	at io.trino.plugin.hive.HivePartitionManager.getFilteredPartitionNames(HivePartitionManager.java:251)
	at io.trino.plugin.hive.HivePartitionManager.getPartitions(HivePartitionManager.java:121)
	at io.trino.plugin.hive.HiveMetadata.applyFilter(HiveMetadata.java:2506)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.applyFilter(ClassLoaderSafeConnectorMetadata.java:847)
	at io.trino.metadata.MetadataManager.applyFilter(MetadataManager.java:1782)
	at io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan.pushFilterIntoTableScan(PushPredicateIntoTableScan.java:241)
	at io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan.apply(PushPredicateIntoTableScan.java:112)
	at io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan.apply(PushPredicateIntoTableScan.java:76)
	at io.trino.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:184)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:159)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:124)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:109)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:224)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:209)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:204)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:495)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:475)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:416)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_7e4332b____20220316_120704_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by hashhar** [comment]
Are you using custom connector or a forked version of Trino? The stack trace doesn't match up with Trino code and the exception is thrown from some extension class `io.trino.plugin.hive.nextroll.DomainInterface.enforcePartitions(DomainInterface.java:126)` which doesn't exist in Trino.
