### ISSUE TITLE
Query failure when pushing down row dereference within expression into Iceberg connector: Unbound variable

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#11560]
Reproducible on current master with `IcebergQueryRunner`, so affects 374 too

```
trino:tpch> CREATE TABLE t(r row(a varchar, b int));
CREATE TABLE
trino:tpch> SET SESSION iterative_optimizer_timeout = '10s';
SET SESSION
trino:tpch> SELECT r, r.a LIKE 'a%' FROM t;
Query 20220318_093129_00029_9n28n failed: Unbound variable: r_0
java.lang.IllegalStateException: Unbound variable: r_0
	at io.trino.metadata.MetadataManager.lambda$verifyProjection$38(MetadataManager.java:1663)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.trino.metadata.MetadataManager.verifyProjection(MetadataManager.java:1663)
	at io.trino.metadata.MetadataManager.lambda$applyProjection$41(MetadataManager.java:1694)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.trino.metadata.MetadataManager.applyProjection(MetadataManager.java:1693)
	at io.trino.sql.planner.iterative.rule.PushProjectionIntoTableScan.apply(PushProjectionIntoTableScan.java:122)
	at io.trino.sql.planner.iterative.rule.PushProjectionIntoTableScan.apply(PushProjectionIntoTableScan.java:66)
	at io.trino.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:202)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:169)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:132)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:251)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:134)
	at io.trino.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:117)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:238)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:215)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:210)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:473)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:454)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:395)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20220318_093010_3.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Rel: https://github.com/trinodb/trino/issues/11559

**Comment by findepi** [comment]
Note that disabling `complex_expression_pushdown` is **not** a workaround:

```
trino:tpch> SET SESSION complex_expression_pushdown = false;
SET SESSION
trino:tpch> SELECT r, r.a LIKE 'a%' FROM t;
Query 20220318_093241_00033_9n28n failed: Unbound variable: r_0
```

**Comment by findepi** [comment]
cc @phd3 @alexjo2144 @martint @wendigo @hashhar @losipiuk

**Comment by findepi** [comment]
Repro: https://github.com/trinodb/trino/pull/11561
