### ISSUE TITLE
Flaky TestPinotWithoutAuthenticationIntegrationSmokeTest.testBrokerQueryWithTooManyRowsForSegmentQuery

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#11685]
```
Error:  io.trino.plugin.pinot.TestPinotWithoutAuthenticationIntegrationSmokeTest.testBrokerQueryWithTooManyRowsForSegmentQuery  Time elapsed: 0.065 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT string_col, updated_at_seconds  FROM  "SELECT updated_at_seconds, string_col FROM too_many_rows  LIMIT 13"
	at org.testng.Assert.fail(Assert.java:83)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:253)
	at io.trino.plugin.pinot.AbstractPinotIntegrationSmokeTest.testBrokerQueryWithTooManyRowsForSegmentQuery(AbstractPinotIntegrationSmokeTest.java:831)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Only 0 out of 0 servers responded for query select "updated_at_seconds", "string_col" from too_many_rows limit 13 with query "select "updated_at_seconds", "string_col" from too_many_rows limit 13"
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:514)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 16 more
	Suppressed: java.lang.Exception: SQL: SELECT string_col, updated_at_seconds  FROM  "SELECT updated_at_seconds, string_col FROM too_many_rows  LIMIT 13"
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:517)
		... 17 more
Caused by: io.trino.plugin.pinot.PinotInsufficientServerResponseException: Only 0 out of 0 servers responded for query select "updated_at_seconds", "string_col" from too_many_rows limit 13 with query "select "updated_at_seconds", "string_col" from too_many_rows limit 13"
	at io.trino.plugin.pinot.client.PinotClient.lambda$submitBrokerQueryJson$6(PinotClient.java:489)
	at io.trino.plugin.pinot.client.PinotClient.doWithRetries(PinotClient.java:554)
	at io.trino.plugin.pinot.client.PinotClient.submitBrokerQueryJson(PinotClient.java:470)
	at io.trino.plugin.pinot.client.PinotClient.createResultIterator(PinotClient.java:511)
	at io.trino.plugin.pinot.PinotBrokerPageSource.getNextPage(PinotBrokerPageSource.java:112)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:693)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_testversion____20220328_003510_3.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Error:  io.trino.plugin.pinot.TestPinotWithoutAuthenticationIntegrationSmokeTest.testLimitForSegmentQueries  Time elapsed: 0.129 s  <<< FAILURE!
java.lang.AssertionError: Expected query to fail: SELECT string_col, updated_at_seconds FROM too_many_rows
	at org.testng.Assert.fail(Assert.java:94)
	at io.trino.testing.QueryAssertions.assertQueryFails(QueryAssertions.java:291)
	at io.trino.testing.AbstractTestQueryFramework.assertQueryFails(AbstractTestQueryFramework.java:349)
	at io.trino.plugin.pinot.AbstractPinotIntegrationSmokeTest.testLimitForSegmentQueries(AbstractPinotIntegrationSmokeTest.java:810)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

https://github.com/trinodb/trino/runs/5712955691

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/runs/6401407533?check_suite_focus=true
