### ISSUE TITLE
Wrong number of rows inserted into Hive with fault-tolerant execution

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#11825]
`TestHiveFaultTolerantExecutionConnectorTest.testPartitionPerScanLimitWithMultiplePartitionColumns` is flaky

```
Error:  io.trino.plugin.hive.TestHiveFaultTolerantExecutionConnectorTest.testPartitionPerScanLimitWithMultiplePartitionColumns  Time elapsed: 16.795 s  <<< FAILURE!
java.lang.AssertionError: 
[Rows for query [SELECT count(*) FROM test_multi_partition_per_scan_limit WHERE part1 IS NULL AND part2 < 1001]] 
Expecting:
  <(992)>
to contain exactly in any order:
  <[(1000)]>
elements not found:
  <(1000)>
and elements not expected:
  <(992)>

	at io.trino.sql.query.QueryAssertions$QueryAssert.lambda$matches$2(QueryAssertions.java:346)
	at io.trino.sql.query.QueryAssertions$QueryAssert.matches(QueryAssertions.java:333)
	at io.trino.sql.query.QueryAssertions$QueryAssert.matches(QueryAssertions.java:328)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testPartitionPerScanLimitWithMultiplePartitionColumns(BaseHiveConnectorTest.java:3191)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

-- looks like a wrong number of rows got inserted 

cc @arhimondr @losipiuk @linzebing

**Comment by arhimondr** [comment]
Looking

**Comment by arhimondr** [comment]
https://github.com/trinodb/trino/pull/11870

**Comment by sopel39** [comment]
Still saw it: https://github.com/trinodb/trino/runs/5975365288?check_suite_focus=true

**Comment by arhimondr** [comment]
Thanks @sopel39 . Seems like there's a one more problem. Will take a look

**Comment by ebyhr** [comment]
`testPartitionPerScanLimit` also failed in https://github.com/trinodb/trino/runs/6016481992
