### ISSUE TITLE
Dropping a previously renamed *partitioned* table fails in Hive consistently with request timed out on HMS

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#11826]
*hive.properties*
```
connector.name=hive
hive.metastore.uri=${ENV:HIVE_METASTORE_URI}
# We need to give access to bucket owner (the AWS account integrated with Databricks), otherwise files won't be readable from Databricks
hive.s3.upload-acl-type=BUCKET_OWNER_FULL_CONTROL
hive.allow-drop-table=true
hive.non-managed-table-writes-enabled=true
# Required by some product tests
hive.translate-hive-views=true
hive.allow-comment-table=true
hive.allow-rename-table=true
```

*trino cli*
```

trino> create table hive.default.mg_test10(id, flag, rate) with (external_location='s3://test-data/mg_test10', partitioned_by = ARRAY['rate']) as values (1, boolean 'false', tinyint '-128'), (2, boolean 'true', tinyint '127');
CREATE TABLE: 2 rows

Query 20220406_100232_00000_hqwzy, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
8.80 [0 rows, 0B] [0 rows/s, 0B/s]

trino> alter table hive.default.mg_test10 rename to hive.default.mg_test10_new;
RENAME TABLE
trino> drop table hive.default.mg_test10_new;
Query 20220406_100317_00002_hqwzy failed: The following metastore delete operations failed: drop table default.mg_test10_new

```

*stacktrace*

```
io.trino.spi.TrinoException: The following metastore delete operations failed: drop table default.mg_test10_new
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeIrreversibleMetastoreOperations(SemiTransactionalHiveMetastore.java:2294)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:1532)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1225)
	at io.trino.plugin.hive.HiveMetadata.commit(HiveMetadata.java:3446)
	at io.trino.plugin.hive.HiveTransactionManager.lambda$commit$0(HiveTransactionManager.java:59)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.trino.plugin.hive.HiveTransactionManager.commit(HiveTransactionManager.java:57)
	at io.trino.plugin.hive.HiveConnector.commit(HiveConnector.java:207)
	at io.trino.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:623)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at io.trino.$gen.Trino_dev____20220406_100131_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: io.trino.spi.TrinoException: ec2-xx-xx-xxx-xxx.compute-1.amazonaws.com:9083: java.net.SocketTimeoutException: Read timed out
		at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.dropTable(ThriftHiveMetastore.java:1114)
		at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.dropTable(BridgingHiveMetastore.java:211)
		at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.dropTable(CachingHiveMetastore.java:485)
		at io.trino.plugin.hive.HiveMetastoreClosure.dropTable(HiveMetastoreClosure.java:171)
		at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.lambda$prepareDropTable$0(SemiTransactionalHiveMetastore.java:1595)
		at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$IrreversibleMetastoreOperation.run(SemiTransactionalHiveMetastore.java:3221)
		at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.lambda$executeIrreversibleMetastoreOperations$21(SemiTransactionalHiveMetastore.java:2269)
		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1736)
		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
		at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
		... 3 more
```

When working with a non-partitioned Hive table the `DROP` operation completes successfully.

**Comment by findepi** [comment]
Does this look like a HMS bug?

**Comment by findinpath** [comment]
> Does this look like a HMS bug?

Yes indeed. The issue is related to an older HMS version and not to Trino itself.
