### ISSUE TITLE
io.trino.orc.TestSliceDictionaryColumnWriter.testDirectConversion: Invalid code point 0x1CEAAE

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#11847]
```
Error:  io.trino.orc.TestSliceDictionaryColumnWriter.testDirectConversion  Time elapsed: 1.301 s  <<< FAILURE!
io.airlift.slice.InvalidCodePointException: Invalid code point 0x1CEAAE
	at io.airlift.slice.SliceUtf8.lengthOfCodePoint(SliceUtf8.java:926)
	at io.airlift.slice.SliceUtf8.codePointToUtf8(SliceUtf8.java:1053)
	at io.trino.orc.metadata.statistics.StringStatisticsBuilder$StringCompactor.truncateMax(StringStatisticsBuilder.java:240)
	at io.trino.orc.metadata.statistics.StringStatisticsBuilder.computeStringMinMax(StringStatisticsBuilder.java:191)
	at io.trino.orc.metadata.statistics.StringStatisticsBuilder.buildStringStatistics(StringStatisticsBuilder.java:135)
	at io.trino.orc.metadata.statistics.StringStatisticsBuilder.buildColumnStatistics(StringStatisticsBuilder.java:147)
	at io.trino.orc.writer.SliceDictionaryColumnWriter.finishRowGroup(SliceDictionaryColumnWriter.java:312)
	at io.trino.orc.TestSliceDictionaryColumnWriter.testDirectConversion(TestSliceDictionaryColumnWriter.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findepi** [comment]
This is easily reproducible (`@Test(invocationCount = 10_000, threadPoolSize = 11)`)

**Comment by findepi** [comment]
@homar can you take a look?

**Comment by homar** [comment]
Will do

**Comment by homar** [comment]
So I'd say the problem comes from the fact that bytes are randomly generated thus there are bytes which can't be properly transformed to UT8

**Comment by homar** [comment]
I will try to change the way bytes are generated

**Comment by findepi** [comment]
Maybe we can randomly gen codepoints and produces bytes from that?

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/5954730758
