### ISSUE TITLE
testUpdateFullAcidWithOriginalFilesTrinoInsertingAndDeleting flaky

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#11893]
```
tests               | 2022-04-09 14:44:59 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveTransactionalTable.testUpdateFullAcidWithOriginalFilesTrinoInsertingAndDeleting [false, NONE] (Groups: storage_formats, hive_transactional) took 19.7 seconds
tests               | 2022-04-09 14:44:59 SEVERE: Failure cause:
tests               | java.lang.AssertionError: Expected row count to be <8>, but was <10>; rows=[[10, 100], [13, 130], [15, 150], [19, 190], [31, 2], [33, 2], [41, 2], [43, 2], [41, 2], [43, 2]]
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.lambda$testUpdateFullAcidWithOriginalFilesTrinoInsertingAndDeleting$1(TestHiveTransactionalTable.java:411)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.withTemporaryTable(TestHiveTransactionalTable.java:1785)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.testUpdateFullAcidWithOriginalFilesTrinoInsertingAndDeleting(TestHiveTransactionalTable.java:378)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
tests               | 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findepi** [comment]
Merging this issue into https://github.com/trinodb/trino/issues/14519
