### ISSUE TITLE
[BUG] Function inside TABLESAMPLE is not resolved

### ISSUE THREAD

**Issue by puchengy** [trinodb/trino#12107]
```
WITH tbl AS (
  SELECT
    *
  FROM
    (
      VALUES
        (1, 'a'),
        (2, 'b'),
        (3, 'c')
    ) AS t (id, name)
)
SELECT
  *
FROM
  tbl TABLESAMPLE SYSTEM (
    CASE
      WHEN DATE_DIFF('Day', date '2022-03-02', date '2022-04-01') >= 7 THEN 5
      ELSE 5
    END
  )
```

**Comment by martint** [comment]
It fails with:

```
Query 20220422_221604_00000_4dv7b failed: Function is not resolved: date_diff
java.lang.IllegalArgumentException: Function is not resolved: date_diff
	at io.trino.metadata.MetadataManager.lambda$decodeFunction$44(MetadataManager.java:2030)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.trino.metadata.MetadataManager.decodeFunction(MetadataManager.java:2030)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:1034)
	at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processWithExceptionHandling(ExpressionInterpreter.java:302)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processComparisonExpression(ExpressionInterpreter.java:834)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitComparisonExpression(ExpressionInterpreter.java:804)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitComparisonExpression(ExpressionInterpreter.java:797)
	at io.trino.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:71)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processWithExceptionHandling(ExpressionInterpreter.java:302)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitSearchedCaseExpression(ExpressionInterpreter.java:424)
	at io.trino.sql.tree.SearchedCaseExpression.accept(SearchedCaseExpression.java:62)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processWithExceptionHandling(ExpressionInterpreter.java:302)
	at io.trino.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:282)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitSampledRelation(StatementAnalyzer.java:2099)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitSampledRelation(StatementAnalyzer.java:404)
	at io.trino.sql.tree.SampledRelation.accept(SampledRelation.java:74)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:421)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3403)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2142)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:404)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:421)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:429)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1345)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:404)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:421)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:384)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:265)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:189)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:800)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:135)
	at io.trino.$gen.Trino_376____20220422_221555_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by albericgenius** [comment]
hi @martint, i can work on this, i have created a PR to fix this issue, it can work well on my local environment.
Thanks for help
Alberic
