### ISSUE TITLE
Flaky test Test*FailureRecoveryTest: reported query failure does not match injected one

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#12151]
Observed for various tests from:
*  TestDeltaTaskFailureRecoveryTest
* TestIcebergQueryFailureRecoveryTest

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/6175492069?check_suite_focus=true

```
2022-04-26T13:13:36.2331493Z [ERROR] Tests run: 38, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 771.54 s <<< FAILURE! - in TestSuite
2022-04-26T13:13:36.2335353Z [ERROR] io.trino.plugin.iceberg.TestIcebergQueryFailureRecoveryTest.testDeleteWithSubquery  Time elapsed: 30.649 s  <<< FAILURE!
2022-04-26T13:13:36.2336002Z java.lang.AssertionError: 
2022-04-26T13:13:36.2336262Z 
2022-04-26T13:13:36.2336422Z Expecting throwable message:
2022-04-26T13:13:36.2337233Z   <"Error closing remote buffer (http://127.0.0.1:44827/v1/task/20220426_130451_00401_h7fn8.1.0.0/results/0 - 3 failures, failure duration 10.06s, total failed request time 15.06s)">
2022-04-26T13:13:36.2337672Z to contain:
2022-04-26T13:13:36.2338009Z   <"Encountered too many errors talking to a worker node">
2022-04-26T13:13:36.2338319Z but did not.
2022-04-26T13:13:36.2338707Z 
2022-04-26T13:13:36.2338848Z Throwable that failed the check:
2022-04-26T13:13:36.2339031Z 
2022-04-26T13:13:36.2339670Z java.lang.RuntimeException: Error closing remote buffer (http://127.0.0.1:44827/v1/task/20220426_130451_00401_h7fn8.1.0.0/results/0 - 3 failures, failure duration 10.06s, total failed request time 15.06s)
2022-04-26T13:13:36.2340395Z 	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
2022-04-26T13:13:36.2341084Z 	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:541)
2022-04-26T13:13:36.2341811Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.execute(BaseFailureRecoveryTest.java:565)
2022-04-26T13:13:36.2342515Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.executeActual(BaseFailureRecoveryTest.java:551)
2022-04-26T13:13:36.2343272Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.executeActualNoRetries(BaseFailureRecoveryTest.java:536)
2022-04-26T13:13:36.2344068Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.lambda$failsWithoutRetries$8(BaseFailureRecoveryTest.java:667)
2022-04-26T13:13:36.2344738Z 	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
2022-04-26T13:13:36.2345413Z 	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:877)
2022-04-26T13:13:36.2346131Z 	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1306)
2022-04-26T13:13:36.2346717Z 	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1178)
2022-04-26T13:13:36.2347389Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.failsWithoutRetries(BaseFailureRecoveryTest.java:667)
2022-04-26T13:13:36.2348112Z 	at io.trino.testing.BaseFailureRecoveryTest.testNonSelect(BaseFailureRecoveryTest.java:457)
2022-04-26T13:13:36.2348810Z 	at io.trino.testing.BaseFailureRecoveryTest.testTableModification(BaseFailureRecoveryTest.java:368)
2022-04-26T13:13:36.2349528Z 	at io.trino.testing.BaseFailureRecoveryTest.testTableModification(BaseFailureRecoveryTest.java:363)
2022-04-26T13:13:36.2350270Z 	at io.trino.testing.BaseFailureRecoveryTest.testDeleteWithSubquery(BaseFailureRecoveryTest.java:278)
2022-04-26T13:13:36.2350935Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-04-26T13:13:36.2351826Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-04-26T13:13:36.2352560Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-04-26T13:13:36.2353171Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-04-26T13:13:36.2353732Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-04-26T13:13:36.2354296Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-04-26T13:13:36.2354791Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-04-26T13:13:36.2355297Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-04-26T13:13:36.2355879Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-04-26T13:13:36.2356448Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-04-26T13:13:36.2357036Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-04-26T13:13:36.2357654Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-04-26T13:13:36.2358137Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-04-26T13:13:36.2359071Z Caused by: io.trino.spi.TrinoTransportException: Error closing remote buffer (http://127.0.0.1:44827/v1/task/20220426_130451_00401_h7fn8.1.0.0/results/0 - 3 failures, failure duration 10.06s, total failed request time 15.06s)
2022-04-26T13:13:36.2359798Z 	at io.trino.operator.HttpPageBufferClient$2.onFailure(HttpPageBufferClient.java:531)
2022-04-26T13:13:36.2360487Z 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
2022-04-26T13:13:36.2361093Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-04-26T13:13:36.2361715Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-04-26T13:13:36.2362194Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-04-26T13:13:36.2362719Z Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Idle timeout 5000 ms
2022-04-26T13:13:36.2363347Z 	at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:25)
2022-04-26T13:13:36.2364013Z 	at io.airlift.http.client.StatusResponseHandler.handleException(StatusResponseHandler.java:45)
2022-04-26T13:13:36.2364711Z 	at io.airlift.http.client.StatusResponseHandler.handleException(StatusResponseHandler.java:28)
2022-04-26T13:13:36.2365378Z 	at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:120)
2022-04-26T13:13:36.2366094Z 	at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:85)
2022-04-26T13:13:36.2366787Z 	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
2022-04-26T13:13:36.2367445Z 	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
2022-04-26T13:13:36.2368137Z 	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481)
2022-04-26T13:13:36.2368765Z 	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461)
2022-04-26T13:13:36.2369347Z 	at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:557)
2022-04-26T13:13:36.2369894Z 	at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:152)
2022-04-26T13:13:36.2370459Z 	at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:145)
2022-04-26T13:13:36.2370977Z 	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:264)
2022-04-26T13:13:36.2371540Z 	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:164)
2022-04-26T13:13:36.2372072Z 	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:819)
2022-04-26T13:13:36.2372722Z 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.abort(HttpConnectionOverHTTP.java:214)
2022-04-26T13:13:36.2373423Z 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:200)
2022-04-26T13:13:36.2374157Z 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onIdleExpired(HttpConnectionOverHTTP.java:160)
2022-04-26T13:13:36.2374862Z 	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:402)
2022-04-26T13:13:36.2375440Z 	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
2022-04-26T13:13:36.2375987Z 	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
2022-04-26T13:13:36.2376516Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-04-26T13:13:36.2377032Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-04-26T13:13:36.2377695Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
2022-04-26T13:13:36.2378188Z 	... 3 more
2022-04-26T13:13:36.2378637Z Caused by: java.util.concurrent.TimeoutException: Idle timeout 5000 ms
2022-04-26T13:13:36.2378987Z 	... 10 more
2022-04-26T13:13:36.2379138Z 
2022-04-26T13:13:36.2379493Z 	at io.trino.testing.BaseFailureRecoveryTest.lambda$testNonSelect$22(BaseFailureRecoveryTest.java:457)
2022-04-26T13:13:36.2380202Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.failsWithoutRetries(BaseFailureRecoveryTest.java:667)
2022-04-26T13:13:36.2380918Z 	at io.trino.testing.BaseFailureRecoveryTest.testNonSelect(BaseFailureRecoveryTest.java:457)
2022-04-26T13:13:36.2381634Z 	at io.trino.testing.BaseFailureRecoveryTest.testTableModification(BaseFailureRecoveryTest.java:368)
2022-04-26T13:13:36.2382351Z 	at io.trino.testing.BaseFailureRecoveryTest.testTableModification(BaseFailureRecoveryTest.java:363)
2022-04-26T13:13:36.2383190Z 	at io.trino.testing.BaseFailureRecoveryTest.testDeleteWithSubquery(BaseFailureRecoveryTest.java:278)
2022-04-26T13:13:36.2383854Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-04-26T13:13:36.2384518Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-04-26T13:13:36.2385245Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-04-26T13:13:36.2385854Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-04-26T13:13:36.2386418Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-04-26T13:13:36.2386982Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-04-26T13:13:36.2387478Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-04-26T13:13:36.2387977Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-04-26T13:13:36.2388556Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-04-26T13:13:36.2389122Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-04-26T13:13:36.2389700Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-04-26T13:13:36.2390388Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-04-26T13:13:36.2390874Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

cc @arhimondr @losipiuk

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/6195137822?check_suite_focus=true 

```
2022-04-27T15:38:26.2624194Z [ERROR] io.trino.plugin.iceberg.TestIcebergQueryFailureRecoveryTest.testDeleteWithSubquery  Time elapsed: 25.595 s  <<< FAILURE!
2022-04-27T15:38:26.2624809Z java.lang.AssertionError: 
2022-04-27T15:38:26.2625047Z 
2022-04-27T15:38:26.2625348Z Expecting throwable message:
2022-04-27T15:38:26.2626029Z   <"Error closing remote buffer (http://127.0.0.1:41235/v1/task/20220427_152944_00401_hz3jt.1.0.0/results/0 - 3 failures, failure duration 10.05s, total failed request time 15.05s)">
2022-04-27T15:38:26.2626406Z to contain:
2022-04-27T15:38:26.2626688Z   <"Encountered too many errors talking to a worker node">
2022-04-27T15:38:26.2627037Z but did not.
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/6250830094?check_suite_focus=true

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/6250928227?check_suite_focus=true

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/6252434621?check_suite_focus=true

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/runs/6317452330?check_suite_focus=true

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/6331254682?check_suite_focus=true

**Comment by arhimondr** [comment]
This should fix it: https://github.com/trinodb/trino/pull/12274
