### ISSUE TITLE
EKS pod identity webhook (IRSA) - Unable to load AWS credentials from any provider in the chain

### ISSUE THREAD

**Issue by fabioaraujopt** [trinodb/trino#12189]
We are running trino in a kubernetes platform, and we are moving the current IAM authentication from using KIAM to be using AWS IRSA (pod-identity-webhook).
This injects two variables in the each pod AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE which should be assumed by the running aws client or aws SDK. 
All our services are working correctly, only trino is not. 

We are receiving the following errors:

```
io.trino.spi.TrinoException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region., com.amazonaws.auth.profile.ProfileCredentialsProvider@25a4e1e4: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@8409f7c: The requested metadata is not found at http:/XXXX/latest/meta-data/iam/security-credentials/]
	at io.trino.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:284)
	at io.trino.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
	at io.trino.$gen.Trino_378____20220429_103118_2.run(Unknown Source)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region., com.amazonaws.auth.profile.ProfileCredentialsProvider@25a4e1e4: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@8409f7c: The requested metadata is not found at http://XXXX/latest/meta-data/iam/security-credentials/]
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:136)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1266)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:842)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:792)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
```

We are running trino version 378, and this error can be seen in the trino coordinator pod. 

Is there any change we should make to this to work?

**Comment by fabioaraujopt** [comment]
It worked after setting the "region" env var.
Unlike aws cli, aws-java-sdk requires a region env var.

**Comment by jeremyakers** [comment]
> It worked after setting the "region" env var. Unlike aws cli, aws-java-sdk requires a region env var.

Hi @fabioaraujopt : I'm running into this same issue and I was curious where exactly you set the region env variable?

Thanks
