### ISSUE TITLE
SingleStore Connector: Inserts Not Working

### ISSUE THREAD

**Issue by metalshanked** [trinodb/trino#12220]
Hi, 
I am not able to insert into a single store table using Trino (378)

STEPS to REPRODUCE
```
TABLE CREATION WORKS --> CREATE TABLE singlestore.mydb.mytbl2(a int not null)

INSERT FAILS WITH ERROR BELOW --> INSERT INTO singlestore.mydb.mytbl2 VALUES(7)
```

```
io.trino.spi.TrinoException: This connector does not support query retries
	at io.trino.spi.connector.ConnectorMetadata.beginInsert(ConnectorMetadata.java:552)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.beginInsert(ClassLoaderSafeConnectorMetadata.java:518)
	at io.trino.metadata.MetadataManager.beginInsert(MetadataManager.java:874)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:261)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:201)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:104)
	at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:81)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:72)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:72)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:37)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:21)
	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:31)
	at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:89)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:239)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:216)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:211)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:473)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:454)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:395)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_378____20220503_041819_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: Current plan:
                Output[rows]
                │   Layout: [rows:bigint]
                └─ TableCommit[singlestore:mydb.mytbl2 mydb.mytbl2]
                   │   Layout: [rows:bigint]
                   └─ LocalExchange[SINGLE] ()
                      │   Layout: [partialrows:bigint, fragment:varbinary]
                      └─ RemoteExchange[GATHER]
                         │   Layout: [partialrows:bigint, fragment:varbinary]
                         └─ TableWriter
                            │   Layout: [partialrows:bigint, fragment:varbinary]
                            │   a := field
                            └─ LocalExchange[SINGLE] ()
                               │   Layout: [field:integer]
                               └─ RemoteExchange[REPARTITION]
                                  │   Layout: [field:integer]
                                  └─ Values
                                         Layout: [field:integer]
                                         (6)

		at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:95)
		... 12 more
		```

**Comment by ebyhr** [comment]
The connector doesn't yet support retry mode. Please try ` SET SESSION retry_policy='NONE'`.
