### ISSUE TITLE
Support Delta DML operations on Google Cloud Storage

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#12264]
```
trino> create schema delta.tiny with (location = 'gs://tiny-tpch/tpch');
CREATE SCHEMA
trino> create table delta.tiny.nation as select * from tpch.sf1.nation;
CREATE TABLE: 25 rows


trino> insert into delta.tiny.nation (nationkey, name) values (42, 'AUSTRIA');
Query 20220505_191547_00010_t5ys6 failed: Cannot write to table in gs://tiny-tpch/tpch/nation; gs not supported
java.lang.IllegalArgumentException: Cannot write to table in gs://tiny-tpch/tpch/nation; gs not supported
	at io.trino.plugin.deltalake.transactionlog.writer.TransactionLogSynchronizerManager.getSynchronizer(TransactionLogSynchronizerManager.java:48)
	at io.trino.plugin.deltalake.transactionlog.writer.TransactionLogWriterFactory.newWriter(TransactionLogWriterFactory.java:36)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.allowWrite(DeltaLakeMetadata.java:1370)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.beginInsert(DeltaLakeMetadata.java:966)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.beginInsert(ClassLoaderSafeConnectorMetadata.java:518)
	at io.trino.metadata.MetadataManager.beginInsert(MetadataManager.java:875)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:262)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:201)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:104)
	at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:81)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:72)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:72)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:37)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:21)
	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:31)
	at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:89)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:239)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:216)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:211)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:477)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:458)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:399)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_dev____20220505_190911_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: Current plan:
                Output[rows]
                │   Layout: [rows:bigint]
                └─ TableCommit[delta:tiny.nation]
                   │   Layout: [rows:bigint]
                   └─ LocalExchange[SINGLE] ()
                      │   Layout: [partialrows:bigint, fragment:varbinary]
                      └─ RemoteExchange[GATHER]
                         │   Layout: [partialrows:bigint, fragment:varbinary]
                         └─ TableWriter
                            │   Layout: [partialrows:bigint, fragment:varbinary]
                            │   nationkey := nationkey
                            │   name := field_0
                            │   regionkey := regionkey
                            │   comment := comment
                            └─ LocalExchange[SINGLE] ()
                               │   Layout: [nationkey:bigint, field_0:varchar(7), regionkey:bigint, comment:varchar]
                               └─ RemoteExchange[REPARTITION]
                                  │   Layout: [nationkey:bigint, field_0:varchar(7), regionkey:bigint, comment:varchar]
                                  └─ Values
                                         Layout: [nationkey:bigint, field_0:varchar(7), regionkey:bigint, comment:varchar]
                                         (BIGINT '42', 'AUSTRIA', CAST(null AS bigint), CAST(null AS varchar))

		at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:95)
		... 12 more
```

https://github.com/trinodb/trino/blob/9956543e429419a268cfe20a47af7f7c47fa2398/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogSynchronizerManager.java#L46-L49

GCS needs  something similar to `AzureTransactionLogSynchronizer`.

**Comment by findinpath** [comment]
https://cloud.google.com/storage/docs/key-terms#immutability

> _Object immutability_
> Objects are immutable, which means that an uploaded object cannot change throughout its storage lifetime. An object's storage lifetime is the time between successful object creation, such as uploading, and successful object deletion. In practice, this means that you cannot make incremental changes to objects, such as append operations or truncate operations. However, it is possible to replace objects that are stored in Cloud Storage, and doing so happens atomically: until the new upload completes, the old version of the object is served to readers, and after the upload completes the new version of the object is served to readers. So a single replacement operation simply marks the end of one immutable object's lifetime and the beginning of a new immutable object's lifetime.
