### ISSUE TITLE
approx_percentile weight parameter documentation incorrect

### ISSUE THREAD

**Issue by puchengy** [trinodb/trino#12276]
query
```
SELECT APPROX_PERCENTILE(budget, budget, 0.5)
FROM (
    VALUES
        (0.10),
        (0.20),
        (0.30),
        (0.40),
        (0.50),
        (0.60),
        (0.70)
) AS t(budget)
```

error
```
io.trino.spi.TrinoException: weight must be >= 1, was 0.1
	at io.trino.util.Failures.checkCondition(Failures.java:64)
	at io.trino.operator.scalar.TDigestFunctions.verifyWeight(TDigestFunctions.java:67)
	at io.trino.operator.aggregation.ApproximateDoublePercentileAggregations.weightedInput(ApproximateDoublePercentileAggregations.java:60)
	at io.trino.operator.aggregation.ApproximateRealPercentileAggregations.weightedInput(ApproximateRealPercentileAggregations.java:48)
	at io.trino.$gen.approx_percentileAccumulator_20220506_223150_142521.addInput(Unknown Source)
	at io.trino.operator.aggregation.Aggregator.processPage(Aggregator.java:63)
	at io.trino.operator.AggregationOperator.addInput(AggregationOperator.java:137)
	at io.trino.operator.Driver.processInternal(Driver.java:393)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:693)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_c1096aa____20220506_090721_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

According to the doc, https://trino.io/docs/current/functions/aggregate.html The requirement is `Weights must be strictly positive.`

**Comment by martint** [comment]
The documentation is incorrect. The value must be >= 1 due to prerequisites of the underlying t-digest data structure.

**Comment by martint** [comment]
Sorry, let me reopen it so we can track the fix to the documentation.
