### ISSUE TITLE
Trino use coral to parse hive view with the following exception

### ISSUE THREAD

**Issue by gjhkael** [trinodb/trino#12288]
We using coral to parse hive view with open the following property in hive catalog.
```shell
hive.translate-hive-views=true
```
When the view have "regexp_extract" function, then query will failed with following exception.

```shell
io.trino.spi.TrinoException: line 1:15: Failed analyzing stored view 'hive.tmp_xxx.tmp_view': line 1:38: Function 'hive_pattern_to_trino' not registered
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeView(StatementAnalyzer.java:3493)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.createScopeForView(StatementAnalyzer.java:1731)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.createScopeForView(StatementAnalyzer.java:1696)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1513)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:405)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:422)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3412)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2151)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:405)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:422)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:430)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1354)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:405)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:422)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:385)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:246)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:173)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:760)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
	at io.trino.$gen.Trino_364_904_g3ff7bfb_dirty____20220509_054839_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.trino.spi.TrinoException: line 1:38: Function 'hive_pattern_to_trino' not registered
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:1206)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:519)
	at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
	at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:542)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.getCallArgumentTypes(ExpressionAnalyzer.java:1581)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:1173)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:519)
	at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
	at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:542)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:433)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:2764)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:3563)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelectSingleColumn(StatementAnalyzer.java:3375)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:3159)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2158)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:405)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:422)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:430)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1354)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:405)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:422)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:385)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:379)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeView(StatementAnalyzer.java:3489)
	... 33 more
Caused by: io.trino.spi.TrinoException: Function 'hive_pattern_to_trino' not registered
	at io.trino.metadata.FunctionResolver.resolveFunction(FunctionResolver.java:119)
	at io.trino.metadata.MetadataManager.lambda$resolvedFunctionInternal$44(MetadataManager.java:2108)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at io.trino.metadata.MetadataManager.resolvedFunctionInternal(MetadataManager.java:2108)
	at io.trino.metadata.MetadataManager.resolveFunction(MetadataManager.java:2076)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:1194)
	... 62 more
```

Reproduce the problem:
```shell
#step1 use hive cli create a view as the following
create view tmp_xxx.tmp_view as select regexp_extract('1a 2b 14m', '\d+', 1) from xxx
#step2 
trino> select * from tmp_bdp.tmp_view;
Query 20220509_064225_00001_nbzvj failed: line 1:15: Failed analyzing stored view 'hive.tmp_bdp.tmp_view': line 1:38: Function 'hive_pattern_to_trino' not registered 
```

**Comment by findepi** [comment]
@gjhkael 
The only code reference to `hive_pattern_to_trino` that i can find is inside Coral.
The reference got renamed from `hive_pattern_to_presto` in https://github.com/linkedin/coral/pull/69 
We need to update the function declaration accordingly.
However, neither the previous name was provided by Trino (nor Coral), so I don't know how to fix this.

@wmoustafa does the handling of Hive `regexp_extract` defined in Coral:
(https://github.com/linkedin/coral/blob/d39a41a6cd7d8c2acc21eeb1d4975ecb2c44c906/coral-trino/src/main/java/com/linkedin/coral/trino/rel2trino/CalciteTrinoUDFMap.java#L65-L66)

```java
createUDFMapEntry(UDF_MAP, hiveToCalciteOp("regexp_extract"), 3, "regexp_extract",
        "[{\"input\": 1}, {\"op\": \"hive_pattern_to_trino\", \"operands\":[{\"input\": 2}]}, {\"input\": 3}]", null);
```

work with vanilla Trino or does it require some additional plugins to work?


cc  @alexjo2144 @losipiuk @findinpath

**Comment by gjhkael** [comment]
Thanks for you reply, I also find the problem is caused by coral, seems the function "hive_pattern_to_trino" is implemented in linkined internal, so I open new issue in coral.
https://github.com/linkedin/coral/issues/266

**Comment by findepi** [comment]
> seems the function "hive_pattern_to_trino" is implemented in linkined internal,

That's another example why Coral integration needs to be tested end-to-end within Trino.
See `AbstractTestHiveViews` and derived classes. 
cc @wmoustafa

(That's also why Trino Hive view translation issues should be tracked in Trino, thanks @gjhkael for your report!)

**Comment by findinpath** [comment]
I've added a PR to coral project for addressing this issue.
https://github.com/linkedin/coral/pull/267
