### ISSUE TITLE
Possible NPE in BinPackingNodeAllocatorService

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#12299]
```
2022-05-09T21:35:59.550Z        WARN    bin-packing-node-allocator      io.trino.execution.scheduler.BinPackingNodeAllocatorService     Error updating nodes
java.lang.NullPointerException: Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because "realtimeNodeMemory" is null
        at io.trino.execution.scheduler.BinPackingNodeAllocatorService$BinPackingSimulation.<init>(BinPackingNodeAllocatorService.java:469)
        at io.trino.execution.scheduler.BinPackingNodeAllocatorService.processPendingAcquires(BinPackingNodeAllocatorService.java:194)
        at io.trino.execution.scheduler.BinPackingNodeAllocatorService.lambda$start$0(BinPackingNodeAllocatorService.java:143)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by losipiuk** [comment]
cc: @arhimondr
