### ISSUE TITLE
Error reading ORC file with short zone id in the footer

### ISSUE THREAD

**Issue by metalshanked** [trinodb/trino#12303]
I seem to be getting the below error when reading from a Hive Table from HDFS.
This table and query work perfectly fine from Hiveserver2/Tez
Also, trino works fine on some other ORC tables

```
Failed to read ORC file: hdfs://xxxxx.snappy.orc
```
The error logs suggest a timestamp issue `Unknown time-zone ID: EST`
```
	at io.trino.$gen.Trino_378____20220509_231427_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.time.zone.ZoneRulesException: Unknown time-zone ID: EST
```

Could it be related to the known limitation?  If so are there any workarounds to fetch the rest of the columns or some data from the table? [https://trino.io/docs/current/connector/hive.html#hive-3-related-limitations]

_Hive’s timestamp with local zone data type is not supported. It is possible to read from a table with a column of this type, but the column data is not accessible. Writing to such a table is not supported._

**Comment by findepi** [comment]
Would you mind attaching full failure stacktrace?

**Comment by metalshanked** [comment]
Sure @findepi  here is the full traceback for the trino query
```
Caused by: java.sql.SQLException: Query failed (#20220510_184817_00139_8g78m): Failed to read ORC file: hdfs://hive444/wir/tablespace/external/hive/big.db/my_hive_table/filedate=2021-05-02/partitionkey=mykey/part-00017-27ceafd2-8f3f-41aa-aa56-a15ee2b5a624.c000.snappy.orc
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1932)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:261)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:221)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Unknown Source)
	at io.trino.jdbc.TrinoResultSet$AsyncIterator.lambda$new$0(TrinoResultSet.java:167)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.trino.spi.TrinoException: Failed to read ORC file: hdfs://hive444/wir/tablespace/external/hive/big.db/my_hive_table/filedate=2021-05-02/partitionkey=mykey/part-00017-27ceafd2-8f3f-41aa-aa56-a15ee2b5a624.c000.snappy.orc
	at io.trino.plugin.hive.orc.OrcPageSource.handleException(OrcPageSource.java:200)
	at io.trino.plugin.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:155)
	at io.trino.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:195)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:693)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_378____20220509_231427_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.time.zone.ZoneRulesException: Unknown time-zone ID: EST
	at java.base/java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:279)
	at java.base/java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:234)
	at java.base/java.time.ZoneRegion.ofId(ZoneRegion.java:120)
	at java.base/java.time.ZoneId.of(ZoneId.java:408)
	at java.base/java.time.ZoneId.of(ZoneId.java:356)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.trino.orc.metadata.OrcMetadataReader.readStripeFooter(OrcMetadataReader.java:175)
	at io.trino.orc.metadata.ExceptionWrappingMetadataReader.readStripeFooter(ExceptionWrappingMetadataReader.java:85)
	at io.trino.orc.StripeReader.readStripeFooter(StripeReader.java:395)
	at io.trino.orc.StripeReader.readStripe(StripeReader.java:120)
	at io.trino.orc.OrcRecordReader.advanceToNextStripe(OrcRecordReader.java:524)
	at io.trino.orc.OrcRecordReader.advanceToNextRowGroup(OrcRecordReader.java:466)
	at io.trino.orc.OrcRecordReader.nextPage(OrcRecordReader.java:387)
	at io.trino.plugin.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:150)
	... 13 more
```

**Comment by findepi** [comment]
Thanks. As you probably now, 3-letter zone abbreviated names are not supported by Java Time, due to their ambiguity.
Do you know what application wrote this ORC file? Why did it use `EST` and not proper IANA time zone name?

**Comment by dain** [comment]
The problem is the metadata inside these files bad.  The only way to work around this would be to modify the code for `OrcMetadataReader.readStripeFooter` to have a manual handle this case.

This could be handled like with this:
```
                Optional.ofNullable(emptyToNull(stripeFooter.getWriterTimezone()))
                        .map(zoneId -> ZoneId.of(zoneId, ZoneId.SHORT_IDS)) // <-- this line changed
                        .orElse(legacyFileTimeZone));
```
But I'm not sure it is proper... seems kind of sketchy.  @findepi what do you think?

**Comment by metalshanked** [comment]
Thanks @dain . Yes, past ORC files already have this deprecated timezone in the stripe footer, so any option from Trino would be great.  Something like the current `hive.orc.time-zone` overriding the read value from the ORC footer?

**Comment by metalshanked** [comment]
btw @dain's code snippet worked great. I created a test jar with it and ORC reads are working fine (no timezone errors)
