### ISSUE TITLE
Flaky TestIcebergTaskFailureRecoveryTest>BaseFailureRecoveryTest.testDeleteWithSubquery

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#12328]
```
2022-05-10T15:35:18.3168232Z [ERROR]   TestIcebergTaskFailureRecoveryTest>BaseFailureRecoveryTest.testDeleteWithSubquery:278->BaseFailureRecoveryTest.testTableModification:363->BaseFailureRecoveryTest.testTableModification:368->BaseFailureRecoveryTest.testNonSelect:457->BaseFailureRecoveryTest.lambda$testNonSelect$22:457 
2022-05-10T15:35:18.3169563Z Expecting throwable message:
2022-05-10T15:35:18.3170447Z   <"Error closing remote buffer (http://127.0.0.1:38511/v1/task/20220510_152620_00390_bikgs.1.0.0/results/0 - 3 failures, failure duration 10.05s, total failed request time 15.05s)">
2022-05-10T15:35:18.3171383Z to contain:
2022-05-10T15:35:18.3172623Z   <"Encountered too many errors talking to a worker node">
2022-05-10T15:35:18.3173871Z but did not.
2022-05-10T15:35:18.3174064Z 
2022-05-10T15:35:18.3174230Z Throwable that failed the check:
2022-05-10T15:35:18.3174430Z 
2022-05-10T15:35:18.3175296Z java.lang.RuntimeException: Error closing remote buffer (http://127.0.0.1:38511/v1/task/20220510_152620_00390_bikgs.1.0.0/results/0 - 3 failures, failure duration 10.05s, total failed request time 15.05s)
2022-05-10T15:35:18.3176318Z 	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
2022-05-10T15:35:18.3176988Z 	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:541)
2022-05-10T15:35:18.3177660Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.execute(BaseFailureRecoveryTest.java:565)
2022-05-10T15:35:18.3178369Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.executeActual(BaseFailureRecoveryTest.java:551)
2022-05-10T15:35:18.3179094Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.executeActualNoRetries(BaseFailureRecoveryTest.java:536)
2022-05-10T15:35:18.3179855Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.lambda$failsWithoutRetries$8(BaseFailureRecoveryTest.java:667)
2022-05-10T15:35:18.3180496Z 	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
2022-05-10T15:35:18.3181143Z 	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:877)
2022-05-10T15:35:18.3181742Z 	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1306)
2022-05-10T15:35:18.3182298Z 	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1178)
2022-05-10T15:35:18.3183153Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.failsWithoutRetries(BaseFailureRecoveryTest.java:667)
2022-05-10T15:35:18.3183880Z 	at io.trino.testing.BaseFailureRecoveryTest.testNonSelect(BaseFailureRecoveryTest.java:457)
2022-05-10T15:35:18.3184552Z 	at io.trino.testing.BaseFailureRecoveryTest.testTableModification(BaseFailureRecoveryTest.java:368)
2022-05-10T15:35:18.3185259Z 	at io.trino.testing.BaseFailureRecoveryTest.testTableModification(BaseFailureRecoveryTest.java:363)
2022-05-10T15:35:18.3185952Z 	at io.trino.testing.BaseFailureRecoveryTest.testDeleteWithSubquery(BaseFailureRecoveryTest.java:278)
2022-05-10T15:35:18.3186603Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-05-10T15:35:18.3187225Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-05-10T15:35:18.3187914Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-05-10T15:35:18.3188501Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-05-10T15:35:18.3189049Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-05-10T15:35:18.3189616Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-05-10T15:35:18.3190100Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-05-10T15:35:18.3190618Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-05-10T15:35:18.3191178Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-05-10T15:35:18.3191750Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-05-10T15:35:18.3192317Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-05-10T15:35:18.3192929Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-05-10T15:35:18.3193407Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-05-10T15:35:18.3194424Z Caused by: io.trino.spi.TrinoTransportException: Error closing remote buffer (http://127.0.0.1:38511/v1/task/20220510_152620_00390_bikgs.1.0.0/results/0 - 3 failures, failure duration 10.05s, total failed request time 15.05s)
2022-05-10T15:35:18.3195275Z 	at io.trino.operator.HttpPageBufferClient$2.onFailure(HttpPageBufferClient.java:531)
2022-05-10T15:35:18.3195850Z 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
2022-05-10T15:35:18.3196430Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-05-10T15:35:18.3197093Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-05-10T15:35:18.3197575Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-05-10T15:35:18.3198086Z Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Idle timeout 5000 ms
2022-05-10T15:35:18.3198685Z 	at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:25)
2022-05-10T15:35:18.3199348Z 	at io.airlift.http.client.StatusResponseHandler.handleException(StatusResponseHandler.java:45)
2022-05-10T15:35:18.3200005Z 	at io.airlift.http.client.StatusResponseHandler.handleException(StatusResponseHandler.java:28)
2022-05-10T15:35:18.3200664Z 	at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:120)
2022-05-10T15:35:18.3201700Z 	at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:85)
2022-05-10T15:35:18.3202533Z 	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
2022-05-10T15:35:18.3203133Z 	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
2022-05-10T15:35:18.3203735Z 	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481)
2022-05-10T15:35:18.3204324Z 	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461)
2022-05-10T15:35:18.3205105Z 	at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:557)
2022-05-10T15:35:18.3206634Z 	at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:152)
2022-05-10T15:35:18.3207203Z 	at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:145)
2022-05-10T15:35:18.3207911Z 	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:264)
2022-05-10T15:35:18.3208461Z 	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:164)
2022-05-10T15:35:18.3211959Z 	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:819)
2022-05-10T15:35:18.3212611Z 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.abort(HttpConnectionOverHTTP.java:214)
2022-05-10T15:35:18.3213264Z 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:200)
2022-05-10T15:35:18.3213940Z 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onIdleExpired(HttpConnectionOverHTTP.java:160)
2022-05-10T15:35:18.3214598Z 	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:402)
2022-05-10T15:35:18.3215147Z 	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
2022-05-10T15:35:18.3215859Z 	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
2022-05-10T15:35:18.3216753Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-05-10T15:35:18.3217261Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-05-10T15:35:18.3218052Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
2022-05-10T15:35:18.3218894Z 	... 3 more
2022-05-10T15:35:18.3219283Z Caused by: java.util.concurrent.TimeoutException: Idle timeout 5000 ms
2022-05-10T15:35:18.3219830Z 	... 10 more
2022-05-10T15:35:18.3220168Z 
```

**Comment by kokosing** [comment]
Oh... this is already solved with https://github.com/trinodb/trino/commit/69ad6ac485b325fa3b0d65fbf7012e50b7e2300c
