### ISSUE TITLE
Flaky raptor tests: `.FileSystemException: /tmp/.... failed to delete one or more files; see suppressed exceptions for details`

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#12385]
```
java.io.UncheckedIOException: java.nio.file.FileSystemException: /tmp/TrinoTest3453139378186970036: failed to delete one or more files; see suppressed exceptions for details
	at io.trino.testing.DistributedQueryRunner.close(DistributedQueryRunner.java:611)
	at io.trino.util.AutoCloseableCloser.close(AutoCloseableCloser.java:52)
	at io.trino.testing.AbstractTestQueryFramework.close(AbstractTestQueryFramework.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.file.FileSystemException: /tmp/TrinoTest3453139378186970036: failed to delete one or more files; see suppressed exceptions for details
	at com.google.common.io.MoreFiles.throwDeleteFailed(MoreFiles.java:810)
	at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:561)
	at io.trino.server.testing.TestingTrinoServer.lambda$close$2(TestingTrinoServer.java:374)
	at com.google.common.io.Closer.close(Closer.java:218)
	at io.trino.server.testing.TestingTrinoServer.close(TestingTrinoServer.java:383)
	at com.google.common.io.Closer.close(Closer.java:218)
	at io.trino.testing.DistributedQueryRunner.close(DistributedQueryRunner.java:608)
	... 15 more
	Suppressed: java.nio.file.DirectoryNotEmptyException
		at java.base/sun.nio.fs.UnixSecureDirectoryStream.implDelete(UnixSecureDirectoryStream.java:204)
		at java.base/sun.nio.fs.UnixSecureDirectoryStream.deleteDirectory(UnixSecureDirectoryStream.java:221)
		at java.base/sun.nio.fs.UnixSecureDirectoryStream.deleteDirectory(UnixSecureDirectoryStream.java:42)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:637)
		at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:538)
		... 20 more
```

**Comment by tangjiangling** [comment]
https://github.com/trinodb/trino/runs/7946669571?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/8093999153?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/8228887039?check_suite_focus=true

**Comment by wendigo** [comment]
I believe that this is solved by: https://github.com/trinodb/trino/pull/21161/commits/66e6f4d3ceb880448bde55c7093e11bf710175f2

**Comment by wendigo** [comment]
Happens more frequently on JDK 22 but reason is unknown. It is stable with the aforementioned change.

**Comment by findepi** [comment]
Thanks @wendigo . would be possible to move the fix to a separate PR?

**Comment by wendigo** [comment]
@findepi sure.

**Comment by wendigo** [comment]
@findepi here you go: https://github.com/trinodb/trino/pull/21213

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8820173346/job/24214101965?pr=21691
```
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    TestRaptorStorageManager.tearDown:167 » FileSystem /tmp/5458528045541130757: failed to delete one or more files; see suppressed exceptions for details
[INFO] 
Error:  Tests run: 1041, Failures: 0, Errors: 1, Skipped: 168
[INFO] 
```
