### ISSUE TITLE
ERROR   main    io.trino.server.Server  Unable to create injector, see the following errors:

### ISSUE THREAD

**Issue by StalkerOne** [trinodb/trino#12397]
hi，everybody，i hava a problem for config the password to run trino. The following is the details of the error report：

2022-05-15T10:34:56.411+0800    ERROR   main    io.trino.server.Server  Unable to create injector, see the following errors:

1) [Guice/ErrorInjectingConstructor]: IllegalArgumentException: Shared secret (internal-communication.shared-secret) is required when authentication is enabled
  at InternalAuthenticationManager.<init>(InternalAuthenticationManager.java:60)
  while locating InternalAuthenticationManager
  at HttpClientBinder.bindGlobalFilter(HttpClientBinder.java:59)
      \_ installed by: ServerMainModule -> InternalCommunicationModule
  while locating HttpRequestFilter annotated with @Element(setName=@GlobalFilter,uniqueId=707, type=MULTIBINDER, keyType=)
  while locating Set<HttpRequestFilter> annotated with interface GlobalFilter
  at HttpClientModule.configure(HttpClientModule.java:74)
      \_ installed by: DiscoveryModule -> HttpClientModule
  at ServiceInventory.<init>(ServiceInventory.java:72)
      \_ for 4th parameter httpClient
  at DiscoveryModule.configure(DiscoveryModule.java:48)
  at DiscoveryServiceSelector.<init>(DiscoveryServiceSelector.java:38)
      \_ for 2nd parameter inventory
  while locating DiscoveryServiceSelector
  at ReplicatedStoreModule$ReplicatorProvider.setServiceSelector(ReplicatedStoreModule.java:172)
      \_ for 1st parameter serviceSelector
  at ReplicatedStoreModule.configure(ReplicatedStoreModule.java:86)
      \_ installed by: CoordinatorDiscoveryModule -> EmbeddedDiscoveryModule -> ReplicatedStoreModule

**Comment by Praveen2112** [comment]
Starting from version 370 - we need to set the `internal-communication.shared-secret` when authentication is enabled. 
This [docs](https://trino.io/docs/current/security/internal-communication.html#shared-secret-for-internal-authentication) provides information on configuring those secret. 


You could also post these questions in our slack channel. Feel free to join [here](https://trino.io/slack.html).

**Comment by Praveen2112** [comment]
I'll be closing this issue. Feel free to open if the issue still persists after configuring the shared-secret.
