### ISSUE TITLE
Flaky test TestBinPackingNodeAllocator.testAllocateDifferentSizesOpportunisticAcquisition: didn't finish within the time-out 2500

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#12415]
```
2022-05-13T17:26:21.4382571Z [ERROR] Tests run: 7923, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,090.994 s <<< FAILURE! - in TestSuite
2022-05-13T17:26:21.4388950Z [ERROR] io.trino.execution.scheduler.TestBinPackingNodeAllocator.testAllocateDifferentSizesOpportunisticAcquisition  Time elapsed: 0.032 s  <<< FAILURE!
2022-05-13T17:26:21.4391002Z org.testng.internal.thread.ThreadTimeoutException: Method io.trino.execution.scheduler.TestBinPackingNodeAllocator.testAllocateDifferentSizesOpportunisticAcquisition() didn't finish within the time-out 2500
2022-05-13T17:26:21.4392901Z 	at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:69)
2022-05-13T17:26:21.4393714Z 	at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2022-05-13T17:26:21.4394737Z 	at java.base@11.0.15/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-05-13T17:26:21.4395675Z 	at java.base@11.0.15/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-05-13T17:26:21.4396728Z 	at java.base@11.0.15/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-05-13T17:26:21.4397575Z 	at java.base@11.0.15/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-05-13T17:26:21.4398495Z 	at java.base@11.0.15/java.lang.Thread.run(Thread.java:829)
```

**Comment by sopel39** [comment]
cc @losipiuk
