### ISSUE TITLE
Error while trying to retrieve certain data via Druid connector

### ISSUE THREAD

**Issue by jmaxx37** [trinodb/trino#12426]
We are on Trino version 373.
We have a Druid connector all set up and working fine. We are able to query tables as well.

druid.properties config file:

connector.name=druid
connection-url=jdbc:avatica:remote:url=http://druid_broker_host:8082/druid/v2/sql/avatica/;authentication=BASIC
connection-user=admin
connection-password=admin

We're using Basic auth.

There's one particular table in Druid...it's returning rows fine when we run the same query in Druid. Running the same query in Trino is failing with this error:

SQL Error [67108864]: Query failed (#20220516_200548_24420_iuhsh): Remote driver error: QueryInterruptedException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
 at [Source: (SequenceInputStream); line: -1, column: 326427590] -> JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
 at [Source: (SequenceInputStream); line: -1, column: 326427590]
 
 
I do see that the table in Druid has a few of these timestamp values under the __time column as a timestamp value, which I get it, doesn't make sense for a year value...but it is not erroring out on Druid or Presto. Same query on Trino is erroring out:
 
 171976-04-06 11:55:57
 
 If I do a select * on the table, it's showing me data. Filtering on other columns also seems to be working.
 Only when I filter on the __time column, it's giving the above error.
 
 Please advice.
 
 Here is the full error stack trace:
 
 io.trino.spi.TrinoException: Remote driver error: QueryInterruptedException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
 at [Source: (SequenceInputStream); line: -1, column: 326427590] -> JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
 at [Source: (SequenceInputStream); line: -1, column: 326427590]
	at io.trino.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:299)
	at io.trino.plugin.jdbc.JdbcRecordCursor.advanceNextPosition(JdbcRecordCursor.java:173)
	at io.trino.$gen.CursorProcessor_20220516_200548_22069.process(Unknown Source)
	at io.trino.operator.ScanFilterAndProjectOperator$RecordCursorToPages.process(ScanFilterAndProjectOperator.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:182)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$7(WorkProcessorUtils.java:296)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$3(WorkProcessorUtils.java:219)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$4(WorkProcessorUtils.java:234)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:150)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:693)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_373____20220513_120101_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.calcite.avatica.AvaticaClientRuntimeException: Remote driver error: QueryInterruptedException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
 at [Source: (SequenceInputStream); line: -1, column: 326427590] -> JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
 at [Source: (SequenceInputStream); line: -1, column: 326427590]
	at org.apache.calcite.avatica.remote.Service$ErrorResponse.toException(Service.java:2475)
	at org.apache.calcite.avatica.remote.JsonService.decode(JsonService.java:55)
	at org.apache.calcite.avatica.remote.JsonService.apply(JsonService.java:140)
	at org.apache.calcite.avatica.remote.RemoteMeta$14.call(RemoteMeta.java:310)
	at org.apache.calcite.avatica.remote.RemoteMeta$14.call(RemoteMeta.java:307)
	at org.apache.calcite.avatica.AvaticaConnection.invokeWithRetries(AvaticaConnection.java:793)
	at org.apache.calcite.avatica.remote.RemoteMeta.fetch(RemoteMeta.java:306)
	at org.apache.calcite.avatica.MetaImpl$FetchIterator.moveNext(MetaImpl.java:1606)
	at org.apache.calcite.avatica.MetaImpl$FetchIterator.next(MetaImpl.java:1591)
	at org.apache.calcite.avatica.util.IteratorCursor.next(IteratorCursor.java:46)
	at org.apache.calcite.avatica.AvaticaResultSet.next(AvaticaResultSet.java:217)
	at io.trino.plugin.jdbc.JdbcRecordCursor.advanceNextPosition(JdbcRecordCursor.java:170)
	... 31 more

**Comment by hashhar** [comment]
The error seems to be coming from the JDBC driver. The query that gets sent to the driver looked correct to me, I'll check if this is a known bug in the driver and whether a newer version has a fix.

```
Caused by: org.apache.calcite.avatica.AvaticaClientRuntimeException: Remote driver error: QueryInterruptedException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
```

**Comment by jmaxx37** [comment]
@hashhar @findepi @ebyhr 

I'm attaching the logs from the Druid Broker node as well when I run the SQL:

2022-05-17T22:05:32,222 ERROR [qtp288756266-174] org.apache.druid.server.QueryLifecycle - Exception while processing queryId [091f7d0f-81c0-44e4-9ca7-cf64689e0fd7] (QueryInterruptedException{msg=Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
 at [Source: (SequenceInputStream); line: -1, column: 305347710], code=Unknown exception, class=com.fasterxml.jackson.core.io.JsonEOFException, host=hostname52.domain.com:8083})
2022-05-17T22:05:32,222 WARN [JDBCYielderOpenCloseExecutor-connection-494333f8-0069-42c6-bf5e-29e07bc2f170-statement-1] org.apache.druid.server.QueryLifecycle - Tried to emit logs and metrics twice for query[091f7d0f-81c0-44e4-9ca7-cf64689e0fd7]!
2022-05-17T22:12:59,484 WARN [qtp288756266-166] org.apache.druid.client.JsonParserIterator - Query [ba7a685f-8fa1-4991-8c70-fac86ef67482] to host [hostname53.domain.com:8083] interrupted
com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
 at [Source: (SequenceInputStream); line: -1, column: 300098059]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:664) ~[jackson-core-2.10.5.jar:2.10.5]
        at com.fasterxml.jackson.dataformat.smile.SmileParserBase._handleEOF(SmileParserBase.java:746) ~[jackson-dataformat-smile-2.10.5.jar:2.10.5]
        at com.fasterxml.jackson.dataformat.smile.SmileParser._eofAsNextToken(SmileParser.java:2691) ~[jackson-dataformat-smile-2.10.5.jar:2.10.5]
        at com.fasterxml.jackson.dataformat.smile.SmileParser.nextToken(SmileParser.java:378) ~[jackson-dataformat-smile-2.10.5.jar:2.10.5]
        at org.apache.druid.client.JsonParserIterator.next(JsonParserIterator.java:113) ~[druid-server-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.BaseSequence.makeYielder(BaseSequence.java:90) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.BaseSequence.access$000(BaseSequence.java:27) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.BaseSequence$1.next(BaseSequence.java:114) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.MergeSequence.makeYielder(MergeSequence.java:131) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.MergeSequence.access$000(MergeSequence.java:32) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.MergeSequence$2.next(MergeSequence.java:173) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.WrappingYielder$1.get(WrappingYielder.java:53) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.WrappingYielder$1.get(WrappingYielder.java:49) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.WrappingYielder.next(WrappingYielder.java:48) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.MergeSequence.makeYielder(MergeSequence.java:131) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.MergeSequence.access$000(MergeSequence.java:32) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.MergeSequence$2.next(MergeSequence.java:173) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.WrappingYielder$1.get(WrappingYielder.java:53) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.WrappingYielder$1.get(WrappingYielder.java:49) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.query.CPUTimeMetricQueryRunner$1.wrap(CPUTimeMetricQueryRunner.java:78) ~[druid-processing-0.22.1.jar:0.22.1]
at org.apache.druid.query.CPUTimeMetricQueryRunner$1.wrap(CPUTimeMetricQueryRunner.java:78) ~[druid-processing-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.WrappingYielder.next(WrappingYielder.java:48) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.WrappingYielder$1.get(WrappingYielder.java:53) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.WrappingYielder$1.get(WrappingYielder.java:49) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.WrappingYielder.next(WrappingYielder.java:48) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.ConcatSequence.wrapYielder(ConcatSequence.java:118) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.ConcatSequence.access$000(ConcatSequence.java:27) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.java.util.common.guava.ConcatSequence$2.next(ConcatSequence.java:132) ~[druid-core-0.22.1.jar:0.22.1]
        at org.apache.druid.sql.avatica.DruidStatement.nextFrame(DruidStatement.java:297) ~[druid-sql-0.22.1.jar:0.22.1]
        at org.apache.druid.sql.avatica.DruidMeta.fetch(DruidMeta.java:243) ~[druid-sql-0.22.1.jar:0.22.1]
        at org.apache.calcite.avatica.remote.LocalService.apply(LocalService.java:239) ~[avatica-core-1.17.0.jar:1.17.0]
        at org.apache.calcite.avatica.remote.Service$FetchRequest.accept(Service.java:1370) ~[avatica-core-1.17.0.jar:1.17.0]
        at org.apache.calcite.avatica.remote.Service$FetchRequest.accept(Service.java:1337) ~[avatica-core-1.17.0.jar:1.17.0]
        at org.apache.calcite.avatica.remote.AbstractHandler.apply(AbstractHandler.java:94) ~[avatica-core-1.17.0.jar:1.17.0]
        at org.apache.calcite.avatica.remote.JsonHandler.apply(JsonHandler.java:52) ~[avatica-core-1.17.0.jar:1.17.0]
        at org.apache.calcite.avatica.server.AvaticaJsonHandler.handle(AvaticaJsonHandler.java:133) ~[avatica-server-1.17.0.jar:1.17.0]
        at org.apache.druid.sql.avatica.DruidAvaticaJsonHandler.handle(DruidAvaticaJsonHandler.java:59) ~[druid-sql-0.22.1.jar:0.22.1]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) [jetty-util-9.4.40.v20210413.jar:9.4.40.v20210413]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
2022-05-17T22:13:18,621 ERROR [qtp288756266-166] org.apache.druid.server.QueryLifecycle - Exception while processing queryId [ba7a685f-8fa1-4991-8c70-fac86ef67482] (QueryInterruptedException{msg=Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
 at [Source: (SequenceInputStream); line: -1, column: 300098059], code=Unknown exception, class=com.fasterxml.jackson.core.io.JsonEOFException, host=hostname53.domain.com:8083})

**Comment by jmaxx37** [comment]
```io.trino.spi.TrinoException: Remote driver error: QueryInterruptedException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
at [Source: (SequenceInputStream); line: -1, column: 326427590] -> JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
at [Source: (SequenceInputStream); line: -1, column: 326427590]```

**Comment by jmaxx37** [comment]
Got it @ebyhr! I updated my log posts.
Definitely looks a lot better now. Thanks!

**Comment by vamsi4uonly** [comment]
We too encountered the similar issue, can you please guide us on this please.

QL Error [67108864]: Query failed (#20221013_153527_13418_tmmkj): Remote driver error: QueryInterruptedException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
at [Source: (SequenceInputStream); line: -1, column: 96228016] -> JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (SequenceInputStream); line: -1, column: -1])
at [Source: (SequenceInputStream); line: -1, column: 96228016]
Query:
select cast(__time as date), col1,col2,col3
   from druid.tables
   WHERE "g.d32" in ('checkout',
                     'myredvest:checkout')
                     and cast(__time as date) between current_date - interval '30' day and current_date - interval '1' day
                     group by cast(__time as date), col1,col2,col3
