### ISSUE TITLE
`UPDATE` does not support `WHERE false`

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#12422]
```
trino:default> create table t1(a_varchar varchar);
CREATE TABLE
trino:default> update t1 set a_varchar = 'Trino' where false;
Query 20220516_111829_00001_7ng9n failed: Invalid descendant for DeleteNode or UpdateNode: io.trino.sql.planner.plan.ExchangeNode

trino:default> insert into t1 select * from t1 where false;
INSERT: 0 rows

Query 20220516_111855_00002_7ng9n, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
1.83 [0 rows, 0B] [0 rows/s, 0B/s]

trino:default> delete from t1 where false;
DELETE: 0 rows

Query 20220516_112029_00003_7ng9n, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.26 [0 rows, 0B] [0 rows/s, 0B/s]
```

`UPDATE` does not support `WHERE FALSE` while `SELECT` and `DELETE` do.

Stacktrace:

```
trino:default> update t1 set a_varchar = 'Trino' where false;
Query 20220818_085157_00009_st42k failed: Invalid descendant for DeleteNode or UpdateNode: io.trino.sql.planner.plan.ExchangeNode
java.lang.IllegalArgumentException: Invalid descendant for DeleteNode or UpdateNode: io.trino.sql.planner.plan.ExchangeNode
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.findTableScanHandleForDeleteOrUpdate(BeginTableWrite.java:353)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.getWriterTarget(BeginTableWrite.java:247)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.getWriterTarget(BeginTableWrite.java:268)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.getWriterTarget(BeginTableWrite.java:268)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:217)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:109)
	at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:81)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:72)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:72)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:37)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:21)
	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:31)
	at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:94)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:247)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:222)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:217)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:462)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:443)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:384)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_393_5_g41d9749____20220818_085025_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: Current plan:
                Output[columnNames = [rows]]
                │   Layout: [rows:bigint]
                │   Estimates: 
                └─ TableCommit[]
                   │   Layout: [rows:bigint]
                   │   Estimates: 
                   └─ LocalExchange[partitioning = SINGLE]
                      │   Layout: [partialrows:bigint, fragment:varbinary]
                      │   Estimates: 
                      └─ RemoteExchange[type = GATHER]
                         │   Layout: [partialrows:bigint, fragment:varbinary]
                         │   Estimates: 
                         └─ Update[[]][]
                            │   Layout: [partialrows:bigint, fragment:varbinary]
                            │   Estimates: 
                            │   a_varchar := expr_0
                            └─ LocalExchange[partitioning = ROUND_ROBIN]
                               │   Layout: [field:row(_pos bigint), expr_0:varchar]
                               │   Estimates: 
                               └─ Values[]
                                      Layout: [field:row(_pos bigint), expr_0:varchar]
                                      Estimates: 

		at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:100)
		... 12 more
```

Found in Trino 381

Tested with Trino 393

Input from @findepi 

> This is because the TableScan was fully replaced with Values.

**Comment by ebyhr** [comment]
@findinpath The stacktrace looks incorrect. Could you update it? 

#8855 is existing issue.

**Comment by findinpath** [comment]
Can I take this one ? I find this could be a good learning experience?

**Comment by aletc1** [comment]
Hi @findinpath,

This does not seem to be resolved in 394. 

```
java.lang.IllegalArgumentException: Invalid descendant for DeleteNode or UpdateNode: io.trino.sql.planner.plan.ExchangeNode
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.findTableScanHandleForDeleteOrUpdate(BeginTableWrite.java:353)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.findTableScanHandleForDeleteOrUpdate(BeginTableWrite.java:338)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.findTableScanHandleForDeleteOrUpdate(BeginTableWrite.java:335)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.findTableScanHandleForDeleteOrUpdate(BeginTableWrite.java:332)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.findTableScanHandleForDeleteOrUpdate(BeginTableWrite.java:335)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.findTableScanHandleForDeleteOrUpdate(BeginTableWrite.java:335)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.getWriterTarget(BeginTableWrite.java:247)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.getWriterTarget(BeginTableWrite.java:268)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.getWriterTarget(BeginTableWrite.java:268)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:217)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:109)
	at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:81)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:72)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:72)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:37)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:21)
	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:31)
	at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:94)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:247)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:222)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:217)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:469)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:450)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:391)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_394____20220906_131144_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: Current plan:
                Output[columnNames = [rows]]
                │   Layout: [rows:bigint]
                │   Estimates: 
                └─ TableCommit[]
                   │   Layout: [rows:bigint]
                   │   Estimates: 
                   └─ LocalExchange[partitioning = SINGLE]
                      │   Layout: [partialrows:bigint, fragment:varbinary]
                      │   Estimates: 
                      └─ RemoteExchange[type = GATHER]
                         │   Layout: [partialrows:bigint, fragment:varbinary]
                         │   Estimates: 
                         └─ Update[[]][]
                            │   Layout: [partialrows:bigint, fragment:varbinary]
                            │   Estimates: 
                            │   _expired := _expired_12
                            └─ Project[]
                               │   Layout: [field:row(_pos bigint, name varchar, active boolean, fecha date, modifiedon timestamp(6), _timestamp timestamp(6), _position bigint), _expired_12:timestamp(6)]
                               │   Estimates: 
                               │   _expired_12 := TIMESTAMP '2022-09-06 15:15:05.128731'
                               └─ FilterProject[filterPredicate = "expr"]
                                  │   Layout: [field:row(_pos bigint, name varchar, active boolean, fecha date, modifiedon timestamp(6), _timestamp timestamp(6), _position bigint)]
                                  │   Estimates: 
                                  └─ Project[]
                                     │   Layout: [field:row(_pos bigint, name varchar, active boolean, fecha date, modifiedon timestamp(6), _timestamp timestamp(6), _position bigint), expr:boolean]
                                     │   Estimates: 
                                     └─ SemiJoin[criteria = name = name_0, hash = [$hashvalue, $hashvalue_15]]
                                        │   Layout: [name:varchar, field:row(_pos bigint, name varchar, active boolean, fecha date, modifiedon timestamp(6), _timestamp timestamp(6), _position bigint), $hashvalue:bigint, expr:boolean]
                                        │   Estimates: 
                                        │   Distribution: PARTITIONED
                                        │   dynamicFilterId: df_813
                                        ├─ RemoteExchange[type = REPARTITION, hashColumn = [$hashvalue]]
                                        │  │   Layout: [name:varchar, field:row(_pos bigint, name varchar, active boolean, fecha date, modifiedon timestamp(6), _timestamp timestamp(6), _position bigint), $hashvalue:bigint]
                                        │  │   Estimates: 
                                        │  └─ ScanFilterProject[table = weather:lorem.colors2__history$data@4429725747316070875, dynamicFilters = {"name" = #df_813}]
                                        │         Layout: [name:varchar, field:row(_pos bigint, name varchar, active boolean, fecha date, modifiedon timestamp(6), _timestamp timestamp(6), _position bigint), $hashvalue_14:bigint]
                                        │         Estimates: 
                                        │         $hashvalue_14 := combine_hash(bigint '0', COALESCE("$operator$hash_code"("name"), 0))
                                        │         field := -2147483648:$row_id:row(_pos bigint, name varchar, active boolean, fecha date, modifiedon timestamp(6), _timestamp timestamp(6), _position bigint)
                                        │         name := 1:name:varchar
                                        │         7:_expired:timestamp(6)
                                        │             :: [NULL]
                                        └─ LocalExchange[partitioning = SINGLE]
                                           │   Layout: [name_0:varchar, $hashvalue_15:bigint]
                                           │   Estimates: 
                                           └─ RemoteExchange[type = REPARTITION, isReplicateNullsAndAny = true, hashColumn = [$hashvalue_16]]
                                              │   Layout: [name_0:varchar, $hashvalue_16:bigint]
                                              │   Estimates: 
                                              └─ ScanFilterProject[table = weather_streams:lorem:colors2__stream, filterPredicate = ((((CAST("$file_modified_time_7" AS timestamp(6)) = TIMESTAMP '2022-08-27 13:28:31.000000') AND ("_position_5" > 2)) OR (CAST("$file_modified_time_7" AS timestamp(6)) > TIMESTAMP '2022-08-27 13:28:31.000000')) AND (((CAST("$file_modified_time_7" AS timestamp(6)) = TIMESTAMP '2022-09-06 13:09:11.000000') AND ("_position_5" <= 2)) OR (CAST("$file_modified_time_7" AS timestamp(6)) < TIMESTAMP '2022-09-06 13:09:11.000000')))]
                                                     Layout: [name_0:varchar, $hashvalue_17:bigint]
                                                     Estimates: 
                                                     $hashvalue_17 := combine_hash(bigint '0', COALESCE("$operator$hash_code"("name_0"), 0))
                                                     _position_5 := _position:int:REGULAR
                                                     name_0 := name:string:REGULAR
                                                     $file_modified_time_7 := $file_modified_time:timestamp:SYNTHESIZED

		at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:100)
		... 12 more
```

Steps to reproduce:

```
CREATE TABLE axprod.main.test2 (
    order_date TIMESTAMP(6),
    customer VARCHAR
)
WITH (partitioning = ARRAY['month(order_date)'])

update axprod.main.test2 set order_date = cast('2022-01-01 23:50' as timestamp(6)) where customer in (select customer from axprod.main.test2 where 1=2)
```
