### ISSUE TITLE
Mismatch between the table and partition schemas. Cannot be coerced .Decimal and Bigint

### ISSUE THREAD

**Issue by anirbanch** [trinodb/trino#1245]
Find 3 similar error message, Hive is able to handle these situations without any error.  

1.) [There is a mismatch between the table and partition schemas. The types are incompatible and cannot be coerced. The column 'aaaaa' in table 'tttt' is declared as type 'decimal(11,6)', but partition 'ppp=a/b/c=06' declared column 'aaaaa' as type 'decimal(11,2)'.]

 

2.)[There is a mismatch between the table and partition schemas. The types are incompatible and cannot be coerced. The column 'aaaaa' in table 'opddpe.tddpef_cs_agg_m' is declared as type 'decimal(8,0)', but partition 'ppp=a/b/c=Y' declared column 'aaaaa' as type 'decimal(6,0)'.]

 

3.) [There is a mismatch between the table and partition schemas. The types are incompatible and cannot be coerced. The column 'aaaaa' in table 'tttt' is declared as type 'bigint', but partition 'dt=20191212' declared column 'aaaaa' as type 'decimal(10,0)'.]

 
Stack trace for the 3rd issue:
 
. io.prestosql.spi.PrestoException: There is a mismatch between the table and partition schemas. The types are incompatible and cannot be coerced. The column 'aaaaa' in table 'tttt' is declared as type 'bigint', but partition 'dt=20191212' declared column 'aaaaa' as type 'decimal(10,0)'.].

       at io.prestosql.plugin.hive.HiveSplitManager.lambda$getPartitionMetadata$1(HiveSplitManager.java:329)

       at com.google.common.collect.Iterators$6.transform(Iterators.java:785)

       at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)

       at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)

       at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1332)

       at io.prestosql.plugin.hive.ConcurrentLazyQueue.poll(ConcurrentLazyQueue.java:37)

       at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:267)

       at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:100)

       at io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:200)

       at io.prestosql.plugin.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)

       at io.prestosql.plugin.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)

       at io.prestosql.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)

       at io.prestosql.$gen.Presto_316_dirty____20190729_193037_1.run(Unknown Source)

       at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)

       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

       at java.lang.Thread.run(Thread.java:748)

 
Here are the steps to reproduce the issue above (3rd issue). The same steps can be used to reproduce the other errors (decimal(11,62) - decimal(11,26) or decimal(6,0) to decimal(8,0))

 
Create partitioned table -

CREATE external TABLE `presto_test`(

  `sbnum` decimal(10,0)',

)

partitioned by (

month int

)

STORED AS PARQUET

LOCATION

  '/hive/presto_test';

2.Insert data into this table, create few partitions -

insert overwrite table presto_test partition (month=201801)

select sbnum from <tabname> limit 10;

insert overwrite table presto_test partition (month=201802)

select sbnum from <tabname> limit 10;

3.Access the table from Presto to ensure it works -

select count(1) from presto_test ;

4.alter the table, change the data type - 

alter table presto_test change sbnum bigint;

5.Access the table again from presto -

select count(1) from presto_test ; (should throw the error)

Slack Discussion on this thread: https://prestosql.slack.com/archives/CGB0QHWSW/p1564446267158300

**Comment by NeerajUnnikrishnan** [comment]
Has this issue already been handled somewhere else? When I am trying to reproduce, I am not getting the expected errors? @anirbanch

**Comment by hashhar** [comment]
Coercions have been added over time and indeed this is now fixed.

The most recent change being https://github.com/trinodb/trino/commit/182d40bb449e9a90c0505cdf46d44bca9cc9fa0f
