### ISSUE TITLE
Password file authentication crashes Trino ver 381

### ISSUE THREAD

**Issue by erikcw** [trinodb/trino#12500]
I have Trino deployed on Kubernetes using the latest version of the Helm chart with Password authentication configured (through the helm chart).  It works fine on Trino 380, but causes Trino 381 to crash with the following error:

```
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.s3-file-system-type                                         TRINO                TRINO
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.s3.security-mapping.colon-replacement                       ----                 ----                 Value used in place of colon for IAM role name in extra credentials
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.s3.security-mapping.config-file                             ----                 ----                 JSON configuration file containing security mappings
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.s3.security-mapping.json-pointer                                                                      JSON pointer (RFC 6901) to mappings inside JSON config
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.s3.security-mapping.kms-key-id-credential-name              ----                 ----                 Name of the extra credential used to provide KMS Key ID
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.s3.security-mapping.refresh-period                          ----                 ----                 How often to refresh the security mapping configuration
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.s3.security-mapping.iam-role-credential-name                ----                 ----                 Name of the extra credential used to provide IAM role
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.allow-add-column                                            false                false                Allow Hive connector to add column
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.allow-comment-column                                        false                false                Allow Hive connector to set comment for a column
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.allow-comment-table                                         false                false                Allow Hive connector to set comment for a table
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.allow-drop-column                                           false                false                Allow Hive connector to drop column
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.allow-drop-table                                            false                false                Allow Hive connector to drop table
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.allow-rename-column                                         false                false                Allow Hive connector to rename column
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.allow-rename-table                                          false                false                Allow Hive connector to rename table
2022-05-21T00:30:08.466Z    INFO    main    Bootstrap    hive.security                                                    legacy               legacy
2022-05-21T00:30:09.991Z    INFO    main    com.qubole.rubix.bookkeeper.BookKeeper    Cache disabled on master node; skipping initialization
2022-05-21T00:30:10.051Z    INFO    main    io.airlift.bootstrap.LifeCycleManager    Life cycle starting...
2022-05-21T00:30:10.051Z    INFO    main    io.airlift.bootstrap.LifeCycleManager    Life cycle started
2022-05-21T00:30:10.061Z    INFO    main    io.trino.metadata.StaticCatalogStore    -- Added catalog hive using connector hive-hadoop2 --
2022-05-21T00:30:10.061Z    INFO    main    io.trino.metadata.StaticCatalogStore    -- Loading catalog etc/catalog/jmx.properties --
2022-05-21T00:30:10.386Z    INFO    main    Bootstrap    PROPERTY         DEFAULT  RUNTIME  DESCRIPTION
2022-05-21T00:30:10.386Z    INFO    main    Bootstrap    jmx.dump-period  10.00s   10.00s
2022-05-21T00:30:10.386Z    INFO    main    Bootstrap    jmx.dump-tables  []       []
2022-05-21T00:30:10.386Z    INFO    main    Bootstrap    jmx.max-entries  86400    86400
2022-05-21T00:30:10.502Z    INFO    main    io.airlift.bootstrap.LifeCycleManager    Life cycle starting...
2022-05-21T00:30:10.502Z    INFO    main    io.airlift.bootstrap.LifeCycleManager    Life cycle started
2022-05-21T00:30:10.503Z    INFO    main    io.trino.metadata.StaticCatalogStore    -- Added catalog jmx using connector jmx --
2022-05-21T00:30:10.503Z    INFO    main    io.trino.metadata.StaticCatalogStore    -- Loading catalog etc/catalog/scylla.properties --
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    PROPERTY                                                  DEFAULT     RUNTIME                                                                                                             DESCRIPTION
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.allow-drop-table                                false       false                                                                                                               Allow Cassandra connector to drop table
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.load-policy.allowed-addresses                   []          []
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.batch-size                                      100         100
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.client.connect-timeout                          5000.00ms   5000.00ms
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.client.read-timeout                             12000.00ms  12000.00ms
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.client.so-linger                                ----        ----
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.consistency-level                               ONE         ONE
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.contact-points                                  []          [scylla-us-east-1-us-east-1b-0.scylla, scylla-us-east-1-us-east-1b-1.scylla, scylla-us-east-1-us-east-1b-2.scylla]
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.load-policy.dc-aware.allow-remote-dc-for-local  false       false
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.load-policy.dc-aware.local-dc                   ----        us-east-1
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.load-policy.dc-aware.used-hosts-per-remote-dc   0           0
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.fetch-size                                      5000        5000
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.tls.keystore-password                           [REDACTED]  [REDACTED]
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.tls.keystore-path                               ----        ----
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.native-protocol-port                            9042        9042
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.no-host-available-retry-timeout                 1.00m       1.00m
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.partition-size-for-batch-select                 100         100
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.password                                        [REDACTED]  [REDACTED]
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.protocol-version                                ----        ----
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.retry-policy                                    DEFAULT     DEFAULT
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.speculative-execution.delay                     500.00ms    500.00ms
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.speculative-execution.limit                     ----        ----
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.split-size                                      1024        1024
2022-05-21T00:30:10.975Z    INFO    main    Bootstrap    cassandra.splits-per-node                                 ----        ----
2022-05-21T00:30:10.976Z    INFO    main    Bootstrap    cassandra.tls.enabled                                     false       false
2022-05-21T00:30:10.976Z    INFO    main    Bootstrap    cassandra.load-policy.token-aware.shuffle-replicas        false       false
2022-05-21T00:30:10.976Z    INFO    main    Bootstrap    cassandra.tls.truststore-password                         [REDACTED]  [REDACTED]
2022-05-21T00:30:10.976Z    INFO    main    Bootstrap    cassandra.tls.truststore-path                             ----        ----
2022-05-21T00:30:10.976Z    INFO    main    Bootstrap    cassandra.load-policy.use-dc-aware                        false       false
2022-05-21T00:30:10.976Z    INFO    main    Bootstrap    cassandra.load-policy.use-token-aware                     false       false
2022-05-21T00:30:10.976Z    INFO    main    Bootstrap    cassandra.username                                        ----        ----
2022-05-21T00:30:11.406Z    INFO    main    io.airlift.bootstrap.LifeCycleManager    Life cycle starting...
2022-05-21T00:30:11.406Z    INFO    main    io.airlift.bootstrap.LifeCycleManager    Life cycle started
2022-05-21T00:30:11.407Z    INFO    main    io.trino.metadata.StaticCatalogStore    -- Added catalog scylla using connector cassandra --
2022-05-21T00:30:11.407Z    INFO    main    io.trino.metadata.StaticCatalogStore    -- Loading catalog etc/catalog/tpcds.properties --
2022-05-21T00:30:11.409Z    INFO    main    io.trino.metadata.StaticCatalogStore    -- Added catalog tpcds using connector tpcds --
2022-05-21T00:30:11.410Z    INFO    main    io.trino.metadata.StaticCatalogStore    -- Loading catalog etc/catalog/tpch.properties --
2022-05-21T00:30:11.416Z    INFO    main    io.trino.metadata.StaticCatalogStore    -- Added catalog tpch using connector tpch --
2022-05-21T00:30:11.417Z    INFO    main    io.trino.execution.resourcegroups.InternalResourceGroupManager    -- Loading resource group configuration manager --
2022-05-21T00:30:11.773Z    INFO    main    Bootstrap    PROPERTY                     DEFAULT  RUNTIME                   DESCRIPTION
2022-05-21T00:30:11.773Z    INFO    main    Bootstrap    resource-groups.config-file  ----     etc/resource-groups.json
2022-05-21T00:30:12.199Z    INFO    main    io.airlift.bootstrap.LifeCycleManager    Life cycle starting...
2022-05-21T00:30:12.200Z    INFO    main    io.airlift.bootstrap.LifeCycleManager    Life cycle started
2022-05-21T00:30:12.200Z    INFO    main    io.trino.execution.resourcegroups.InternalResourceGroupManager    -- Loaded resource group configuration manager file --
2022-05-21T00:30:12.202Z    INFO    main    io.trino.security.AccessControlManager    Using system access control: default
2022-05-21T00:30:12.202Z    INFO    main    io.trino.server.security.PasswordAuthenticatorManager    -- Loading password authenticator --
2022-05-21T00:30:12.517Z    INFO    main    Bootstrap    PROPERTY                        DEFAULT  RUNTIME                      DESCRIPTION
2022-05-21T00:30:12.517Z    INFO    main    Bootstrap    file.auth-token-cache.max-size  1000     1000                         Max number of cached authenticated passwords
2022-05-21T00:30:12.517Z    INFO    main    Bootstrap    file.password-file              ----     /etc/trino/auth/password.db  Location of the file that provides user names and passwords
2022-05-21T00:30:12.517Z    INFO    main    Bootstrap    file.refresh-period             5.00s    5.00s                        How often to reload the password file
2022-05-21T00:30:12.611Z    INFO    main    io.airlift.bootstrap.LifeCycleManager    Life cycle starting...
2022-05-21T00:30:12.612Z    INFO    main    io.airlift.bootstrap.LifeCycleManager    Life cycle started
2022-05-21T00:30:12.612Z    INFO    main    io.trino.server.security.PasswordAuthenticatorManager    -- Loaded password authenticator file --
2022-05-21T00:30:12.612Z    INFO    main    io.trino.exchange.ExchangeManagerRegistry    -- Loading exchange manager filesystem --
2022-05-21T00:30:12.612Z    ERROR    main    io.trino.server.Server    Exchange manager factory 'filesystem' is not registered. Available factories: []
java.lang.IllegalArgumentException: Exchange manager factory 'filesystem' is not registered. Available factories: []
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435)
    at io.trino.exchange.ExchangeManagerRegistry.loadExchangeManager(ExchangeManagerRegistry.java:88)
    at io.trino.exchange.ExchangeManagerRegistry.loadExchangeManager(ExchangeManagerRegistry.java:78)
    at io.trino.server.Server.doStart(Server.java:140)
    at io.trino.server.Server.lambda$start$0(Server.java:80)
    at io.trino.$gen.Trino_370____20220521_002957_1.run(Unknown Source)
    at io.trino.server.Server.start(Server.java:80)
    at io.trino.server.TrinoServer.main(TrinoServer.java:38)


2022-05-21T00:30:12.613Z    INFO    Thread-101    io.airlift.bootstrap.LifeCycleManager    JVM is shutting down, cleaning up
2022-05-21T00:30:12.613Z    INFO    Thread-98    io.airlift.bootstrap.LifeCycleManager    JVM is shutting down, cleaning up
2022-05-21T00:30:12.613Z    INFO    Thread-99    io.airlift.bootstrap.LifeCycleManager    JVM is shutting down, cleaning up
2022-05-21T00:30:12.613Z    INFO    Thread-100    io.airlift.bootstrap.LifeCycleManager    JVM is shutting down, cleaning up
2022-05-21T00:30:12.613Z    INFO    Thread-101    io.airlift.bootstrap.LifeCycleManager    Life cycle stopping...
Stream closed EOF for trino/trino-test-coordinator-cdb697c67-hsqb4 (trino-coordinator)

```

If I remove Password auth, the trino coordinator boots just fine.  I've revered back to ver 380 in the mean time.

**Comment by findepi** [comment]
> `java.lang.IllegalArgumentException: Exchange manager factory 'filesystem' is not registered. Available factories: []`

cc @arhimondr

**Comment by findepi** [comment]
> It works fine on Trino 380, but causes Trino 381 to crash with the following error:

@erikcw the stacktrace indicates you're deploying 370, not 381.
Please check your configuration.

**Comment by Eniloracm** [comment]
My mistake!  Machine had cached `trino:latest` on 370.  That's what I get for not pinning my release.  Sorry guys.

**Comment by erikcw** [comment]
My mistake! Machine had cached `trino:latest` on 370. That's what I get for not pinning my release. Sorry guys.
