### ISSUE TITLE
Flaky TestIcebergGlueCatalogConnectorSmokeTest.testDeleteRowsConcurrently

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#12521]
https://github.com/trinodb/trino/runs/6558840919

```
Error:  io.trino.plugin.iceberg.catalog.glue.TestIcebergGlueCatalogConnectorSmokeTest.testDeleteRowsConcurrently  Time elapsed: 10.358 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently() didn't finish within the time-out 60000
	at java.base@11.0.15/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base@11.0.15/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base@11.0.15/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base@11.0.15/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at app//okio.Okio$2.read(Okio.java:140)
	at app//okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at app//okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
	at app//okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
	at app//okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
	at app//okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
	at app//okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
	at app//okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at app//okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at app//okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at app//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at app//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at app//okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at app//okhttp3.RealCall.execute(RealCall.java:81)
	at app//io.trino.client.JsonResponse.execute(JsonResponse.java:124)
	at app//io.trino.client.StatementClientV1.advance(StatementClientV1.java:378)
	at app//io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:98)
	at app//io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:86)
	at app//io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:514)
	at app//io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest$$Lambda$5189/0x000000080163e440.execute(Unknown Source)
	at app//io.trino.testing.sql.TestTable.close(TestTable.java:129)
	at app//io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently(BaseIcebergConnectorSmokeTest.java:136)
	at java.base@11.0.15/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.15/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.15/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.15/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base@11.0.15/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base@11.0.15/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.15/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.15/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@11.0.15/java.lang.Thread.run(Thread.java:829)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:  io.trino.plugin.iceberg.catalog.glue.TestIcebergGlueCatalogConnectorSmokeTest.testDeleteRowsConcurrently
[INFO]   Run 1: PASS
Error:    Run 2: TestIcebergGlueCatalogConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:136 » ThreadTimeout
[INFO]   Run 3: PASS
[INFO]   Run 4: PASS
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/3432919368/jobs/5722806540
