### ISSUE TITLE
Metadata file missing after writing to Iceberg table on GCS

### ISSUE THREAD

**Issue by mlaforet** [trinodb/trino#12581]
We are running Trino 381 to write iceberg datasets on GCS.

We are seeing the following error quite frequently 

```
org.apache.iceberg.exceptions.NotFoundException: Failed to open input stream for file: gs://our_table_path/snap-6889287511386293514-2-6a576bd9-67ee-4f7a-9aa6-a26435740c45.avro
	at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:177)
	at io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:97)
	at io.trino.plugin.iceberg.HdfsInputFile.newStream(HdfsInputFile.java:62)
	at org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:101)
	at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77)
	at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:37)
	at org.apache.iceberg.relocated.com.google.common.collect.Iterables.addAll(Iterables.java:320)
	at org.apache.iceberg.relocated.com.google.common.collect.Lists.newLinkedList(Lists.java:237)
	at org.apache.iceberg.ManifestLists.read(ManifestLists.java:46)
	at org.apache.iceberg.BaseSnapshot.cacheManifests(BaseSnapshot.java:141)
	at org.apache.iceberg.BaseSnapshot.dataManifests(BaseSnapshot.java:163)
	at org.apache.iceberg.MergingSnapshotProducer.apply(MergingSnapshotProducer.java:518)
	at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:164)
	at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:283)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190)
	at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:282)
	at io.trino.plugin.iceberg.IcebergMetadata.finishInsert(IcebergMetadata.java:665)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishInsert(ClassLoaderSafeConnectorMetadata.java:504)
	at io.trino.metadata.MetadataManager.finishInsert(MetadataManager.java:893)
	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$3(LocalExecutionPlanner.java:3963)
	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
	at io.trino.operator.Driver.processInternal(Driver.java:410)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_381_001____20220526_203611_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.FileNotFoundException: Item not found: 'gs://our_table_path/metadata/snap-6889287511386293514-2-6a576bd9-67ee-4f7a-9aa6-a26435740c45.avro'. If you enabled STRICT generation consistency, it is possible that the live version is still available but the intended generation is deleted.
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageExceptions.createFileNotFoundException(GoogleCloudStorageExceptions.java:45)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.open(GoogleCloudStorageImpl.java:603)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.open(GoogleCloudStorageFileSystem.java:305)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFSInputStream.<init>(GoogleHadoopFSInputStream.java:78)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.open(GoogleHadoopFileSystemBase.java:628)
	at io.trino.plugin.hive.fs.TrinoFileSystemCache$FileSystemWrapper.open(TrinoFileSystemCache.java:307)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:899)
	at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175)
	... 36 more
```

We have object versioning setup on the buckets and can see that the file did exist but was deleted.

At this point we're thinking that trino tried to write data, committed to the iceberg ledger but then thinks it failed and tries to clean up after itself, corrupting the ledger in the process.

Any help or guidance would be appreciated!

**Comment by findepi** [comment]
> We are seeing the following error quite frequently [...]

@mlaforet It's bad when a problem is frequent, but that's also an opportunity.
Please enable DEBUG logs in Iceberg connector on the coordinator node, and reproduce the problem.
Let's identity 
- what metastore are you using?
- what was the status of the query which created the file?
- what queries has been run around the time when metadata file was deleted?

Can it be related to commit retries, see https://github.com/trinodb/trino/pull/11886/commits/af51789ffb4bf04abfc66a3521683659135dbbed ?
cc @alexjo2144

**Comment by electrum** [comment]
Can you explain your workflow? What queries are you running?

**Comment by mlaforet** [comment]
We are rewriting historical datasets from json into parquet. Reading using a hive connector and writting using an iceberg connector (still backed by a hive metastore).

Both our input and output data is partitioned in the same way. We have a multi-threaded application that retrieves a partition to rebuild and submits an insert query to read the data and then write it in the new format. This is done using an `INSERT INTO SELECT` statement. B/c this is multi-threaded we are rewriting multiple partitions concurrently and do see contention to commit to the table. We have retries enabled however.

My hunch is that trino fails to commit, retries and succeeds but for some reason thinks it still failed and will try to 'be a good citizen' by cleaning up after itself and deleting the metadata file it thought it failed to commit.

Let me know if I can provide more information.
