### ISSUE TITLE
redshift  is valid for the driver com.amazon.redshift.Driver

### ISSUE THREAD

**Issue by duhanmin** [trinodb/trino#12630]
Caused by: java.sql.SQLException: Query failed (#20220601_112020_01618_xm6aj): com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Driver returned null connection, make sure the connection URL 'jdbc:postgresql://**********redshift.amazonaws.com:5439/*****' is valid for the driver com.amazon.redshift.Driver@b296f57
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1912)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:219)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:179)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)

**Comment by ebyhr** [comment]
Please use `jdbc:redshift...` instead of `jdbc:postgresql...`.
