### ISSUE TITLE
The problem of SingleRowBlockWriter

### ISSUE THREAD

**Issue by wuguangkuo** [trinodb/trino#12659]
I had write a window function like this:
```java
@WindowFunctionSignature(name = "row_test", returnType = "row(int,int,int)", argumentTypes = {})
public class RowTest extends ValueWindowFunction {
    @Override
    public void processRow(BlockBuilder output, int frameStart, int frameEnd, int currentPosition) {
        SingleRowBlockWriter rowOutput = (SingleRowBlockWriter) output.beginBlockEntry();
        BlockBuilder fieldOutput = rowOutput.getFieldBlockBuilder(0);
        fieldOutput.writeInt(1);
        fieldOutput = rowOutput.getFieldBlockBuilder(1);
        fieldOutput.writeInt(2);
        fieldOutput = rowOutput.getFieldBlockBuilder(2);
        fieldOutput.writeInt(3);
        output.closeEntry();
    }
}
```
I write a sql to test it:
```sql
SELECT row_test() over (partition by orderstatus order by orderdate) as num
FROM (
select * from (values
( 3, 'F', '1993-10-14'),
( 5, 'F', '1994-07-30'),
( 6, 'F', '1992-02-21')
) AS orders (orderkey, orderstatus, orderdate)
) x;
```
It works as expected. But when I modify the code to this:

```java
@WindowFunctionSignature(name = "row_test", returnType = "row(int,int,int)", argumentTypes = {})
public class RowTest extends ValueWindowFunction {
    @Override
    public void processRow(BlockBuilder output, int frameStart, int frameEnd, int currentPosition) {
        SingleRowBlockWriter rowOutput = (SingleRowBlockWriter) output.beginBlockEntry();

        BlockBuilder fieldOutput = rowOutput.beginBlockEntry();
        fieldOutput.writeInt(1);
        rowOutput.closeEntry();

        fieldOutput = rowOutput.beginBlockEntry();
        fieldOutput.writeInt(2);
        rowOutput.closeEntry();

        fieldOutput = rowOutput.beginBlockEntry();
        fieldOutput.writeInt(3);
        rowOutput.closeEntry();

        output.closeEntry();
    }
}
```

And execute the same sql, it throws exception:

```java
java.lang.UnsupportedOperationException: io.trino.spi.block.IntArrayBlockBuilder
	at io.trino.spi.block.BlockBuilder.beginBlockEntry(BlockBuilder.java:67)
	at io.trino.spi.block.SingleRowBlockWriter.beginBlockEntry(SingleRowBlockWriter.java:160)
```

Seems the **SingleRowBlockWriter** didn't support this case? Or the **IntArrayBlockBuilder** should add an empty method: **beginBlockEntry**

**Comment by wuguangkuo** [comment]
I made mistakes when testing
