### ISSUE TITLE
Trino 383 Regression: Declared positions (3062) does not match block 1's number of entries

### ISSUE THREAD

**Issue by erikcw** [trinodb/trino#12667]
After upgrading from `v382` to `v383`, my queries have started to fail with the following exception:

```
java.lang.IllegalStateException: Declared positions (3062) does not match block 1's number of entries (6105)
	at com.google.common.base.Preconditions.checkState(Preconditions.java:840)
	at io.trino.operator.output.PositionsAppenderPageBuilder.build(PositionsAppenderPageBuilder.java:108)
	at io.trino.operator.output.PagePartitioner.flushPositionsAppenders(PagePartitioner.java:500)
	at io.trino.operator.output.PagePartitioner.partitionPageByColumn(PagePartitioner.java:265)
	at io.trino.operator.output.PagePartitioner.partitionPage(PagePartitioner.java:193)
	at io.trino.operator.output.PartitionedOutputOperator.addInput(PartitionedOutputOperator.java:286)
	at io.trino.operator.Driver.processInternal(Driver.java:415)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_383____20220602_160301_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

EXPLAIN:
```sql
Fragment 0 [SINGLE]
    Output layout: [audience_slug, cc_uid, sha256_lower_case, sha1_lower_case, md5_lower_case, maid, partner_id, max_by, max_by_0, max_by_1, max_by_2, min, max, max_by_3, sum, array_join]
    Output partitioning: SINGLE []
    Stage Execution Strategy: UNGROUPED_EXECUTION
    Output[audience_slug, cc_uid, sha256_lower_case, sha1_lower_case, md5_lower_case, maid, partner_id, ip, ua, referer, source, first_instance, timestamp, dt, instances, all_segments]
    │   Layout: [audience_slug:varchar, cc_uid:varchar, sha256_lower_case:varchar, sha1_lower_case:varchar, md5_lower_case:varchar, maid:varchar, partner_id:varchar, max_by:varchar, max_by_0:varchar, max_by_1:varchar, max_by_2:varchar(18), min:timestamp(3), max:timestamp(3), max_by_3:date, sum:bigint, array_join:varchar]
    │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
    │   ip := max_by
    │   ua := max_by_0
    │   referer := max_by_1
    │   source := max_by_2
    │   first_instance := min
    │   timestamp := max
    │   dt := max_by_3
    │   instances := sum
    │   all_segments := array_join
    └─ RemoteSource[1]
           Layout: [md5_lower_case:varchar, max:timestamp(3), array_join:varchar, max_by_0:varchar, sum:bigint, max_by_3:date, max_by_2:varchar(18), max_by_1:varchar, maid:varchar, sha256_lower_case:varchar, audience_slug:varchar, min:timestamp(3), cc_uid:varchar, sha1_lower_case:varchar, max_by:varchar, partner_id:varchar]

Fragment 1 [HASH]
    Output layout: [md5_lower_case, max, array_join, max_by_0, sum, max_by_3, max_by_2, max_by_1, maid, sha256_lower_case, audience_slug, min, cc_uid, sha1_lower_case, max_by, partner_id]
    Output partitioning: SINGLE []
    Stage Execution Strategy: UNGROUPED_EXECUTION
    Project[]
    │   Layout: [md5_lower_case:varchar, max:timestamp(3), array_join:varchar, max_by_0:varchar, sum:bigint, max_by_3:date, max_by_2:varchar(18), max_by_1:varchar, maid:varchar, sha256_lower_case:varchar, audience_slug:varchar, min:timestamp(3), cc_uid:varchar, sha1_lower_case:varchar, max_by:varchar, partner_id:varchar]
    │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
    │   array_join := array_join(array_sort("array_agg"), VARCHAR ',')
    └─ Aggregate(FINAL)[cc_uid, sha256_lower_case, sha1_lower_case, md5_lower_case, maid, partner_id, audience_slug][$hashvalue]
       │   Layout: [cc_uid:varchar, sha256_lower_case:varchar, sha1_lower_case:varchar, md5_lower_case:varchar, maid:varchar, partner_id:varchar, audience_slug:varchar, $hashvalue:bigint, min:timestamp(3), max:timestamp(3), max_by_0:varchar, sum:bigint, max_by:varchar, max_by_3:date, array_agg:array(varchar), max_by_2:varchar(18), max_by_1:varchar]
       │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
       │   min := min("min_4")
       │   max := max("max_5")
       │   max_by_0 := max_by("max_by_6")
       │   sum := sum("sum_7")
       │   max_by := max_by("max_by_8")
       │   max_by_3 := max_by("max_by_9")
       │   array_agg := array_agg("array_agg_10")
       │   max_by_2 := max_by("max_by_11")
       │   max_by_1 := max_by("max_by_12")
       └─ LocalExchange[HASH][$hashvalue] ("cc_uid", "sha256_lower_case", "sha1_lower_case", "md5_lower_case", "maid", "partner_id", "audience_slug")
          │   Layout: [cc_uid:varchar, sha256_lower_case:varchar, sha1_lower_case:varchar, md5_lower_case:varchar, maid:varchar, partner_id:varchar, audience_slug:varchar, max_by_8:row(timestamp(3), varchar), max_by_6:row(timestamp(3), varchar), max_by_12:row(timestamp(3), varchar), min_4:timestamp(3), max_5:timestamp(3), max_by_9:row(timestamp(3), date), max_by_11:row(timestamp(3), varchar(18)), sum_7:row(bigint, boolean, bigint, boolean), array_agg_10:array(varchar), $hashvalue:bigint]
          │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
          └─ RemoteSource[2]
                 Layout: [cc_uid:varchar, sha256_lower_case:varchar, sha1_lower_case:varchar, md5_lower_case:varchar, maid:varchar, partner_id:varchar, audience_slug:varchar, max_by_8:row(timestamp(3), varchar), max_by_6:row(timestamp(3), varchar), max_by_12:row(timestamp(3), varchar), min_4:timestamp(3), max_5:timestamp(3), max_by_9:row(timestamp(3), date), max_by_11:row(timestamp(3), varchar(18)), sum_7:row(bigint, boolean, bigint, boolean), array_agg_10:array(varchar), $hashvalue_13:bigint]

Fragment 2 [HASH]
    Output layout: [cc_uid, sha256_lower_case, sha1_lower_case, md5_lower_case, maid, partner_id, audience_slug, max_by_8, max_by_6, max_by_12, min_4, max_5, max_by_9, max_by_11, sum_7, array_agg_10, $hashvalue_14]
    Output partitioning: HASH [cc_uid, sha256_lower_case, sha1_lower_case, md5_lower_case, maid, partner_id, audience_slug][$hashvalue_14]
    Stage Execution Strategy: UNGROUPED_EXECUTION
    Aggregate(PARTIAL)[cc_uid, sha256_lower_case, sha1_lower_case, md5_lower_case, maid, partner_id, audience_slug][$hashvalue_14]
    │   Layout: [cc_uid:varchar, sha256_lower_case:varchar, sha1_lower_case:varchar, md5_lower_case:varchar, maid:varchar, partner_id:varchar, audience_slug:varchar, $hashvalue_14:bigint, max_by_8:row(timestamp(3), varchar), max_by_6:row(timestamp(3), varchar), max_by_12:row(timestamp(3), varchar), min_4:timestamp(3), max_5:timestamp(3), max_by_9:row(timestamp(3), date), max_by_11:row(timestamp(3), varchar(18)), sum_7:row(bigint, boolean, bigint, boolean), array_agg_10:array(varchar)]
    │   max_by_8 := max_by("ip", "timestamp")
    │   max_by_6 := max_by("ua", "timestamp")
    │   max_by_12 := max_by("referer", "timestamp")
    │   min_4 := min("timestamp")
    │   max_5 := max("timestamp")
    │   max_by_9 := max_by("dt", "timestamp")
    │   max_by_11 := max_by("source", "timestamp")
    │   sum_7 := sum("expr")
    │   array_agg_10 := array_agg("segment") (mask = segment$distinct)
    └─ MarkDistinct[distinct=cc_uid:varchar, sha256_lower_case:varchar, sha1_lower_case:varchar, md5_lower_case:varchar, maid:varchar, partner_id:varchar, segment:varchar marker=segment$distinct][$hashvalue_15]
       │   Layout: [referer:varchar, md5_lower_case:varchar, ip:varchar, source:varchar(18), ua:varchar, dt:date, maid:varchar, sha256_lower_case:varchar, audience_slug:varchar, cc_uid:varchar, segment:varchar, expr:bigint, sha1_lower_case:varchar, partner_id:varchar, timestamp:timestamp(3), $hashvalue_14:bigint, $hashvalue_15:bigint, $hashvalue_16:bigint, segment$distinct:boolean]
       └─ LocalExchange[HASH][$hashvalue_16] ("cc_uid", "sha256_lower_case", "sha1_lower_case", "md5_lower_case", "maid", "partner_id", "audience_slug", "segment")
          │   Layout: [referer:varchar, md5_lower_case:varchar, ip:varchar, source:varchar(18), ua:varchar, dt:date, maid:varchar, sha256_lower_case:varchar, audience_slug:varchar, cc_uid:varchar, segment:varchar, expr:bigint, sha1_lower_case:varchar, partner_id:varchar, timestamp:timestamp(3), $hashvalue_14:bigint, $hashvalue_15:bigint, $hashvalue_16:bigint]
          │   Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: ?}
          └─ RemoteSource[3]
                 Layout: [referer:varchar, md5_lower_case:varchar, ip:varchar, source:varchar(18), ua:varchar, dt:date, maid:varchar, sha256_lower_case:varchar, audience_slug:varchar, cc_uid:varchar, segment:varchar, expr:bigint, sha1_lower_case:varchar, partner_id:varchar, timestamp:timestamp(3), $hashvalue_17:bigint, $hashvalue_18:bigint, $hashvalue_19:bigint]

Fragment 3 [SOURCE]
    Output layout: [referer, md5_lower_case, ip, source, ua, dt, maid, sha256_lower_case, audience_slug, cc_uid, segment, expr, sha1_lower_case, partner_id, timestamp, $hashvalue_20, $hashvalue_21, $hashvalue_22]
    Output partitioning: HASH [cc_uid, sha256_lower_case, sha1_lower_case, md5_lower_case, maid, partner_id, audience_slug, segment][$hashvalue_22]
    Stage Execution Strategy: UNGROUPED_EXECUTION
    ScanProject[table = hive:ddt:site_visitor_match, grouped = false]
        Layout: [referer:varchar, md5_lower_case:varchar, ip:varchar, source:varchar(18), ua:varchar, dt:date, maid:varchar, sha256_lower_case:varchar, audience_slug:varchar, cc_uid:varchar, segment:varchar, expr:bigint, sha1_lower_case:varchar, partner_id:varchar, timestamp:timestamp(3), $hashvalue_20:bigint, $hashvalue_21:bigint, $hashvalue_22:bigint]
        Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: 0B}/{rows: ? (?), cpu: ?, memory: 0B, network: 0B}
        expr := CAST("instances" AS bigint)
        $hashvalue_20 := combine_hash(combine_hash(combine_hash(combine_hash(combine_hash(combine_hash(combine_hash(bigint '0', COALESCE("$operator$hash_code"("cc_uid"), 0)), COALESCE("$operator$hash_code"("sha256_lower_case"), 0)), COALESCE("$operator$hash_code"("sha1_lower_case"), 0)), COALESCE("$operator$hash_code"("md5_lower_case"), 0)), COALESCE("$operator$hash_code"("maid"), 0)), COALESCE("$operator$hash_code"("partner_id"), 0)), COALESCE("$operator$hash_code"("audience_slug"), 0))
        $hashvalue_21 := combine_hash(combine_hash(combine_hash(combine_hash(combine_hash(combine_hash(combine_hash(bigint '0', COALESCE("$operator$hash_code"("cc_uid"), 0)), COALESCE("$operator$hash_code"("sha256_lower_case"), 0)), COALESCE("$operator$hash_code"("sha1_lower_case"), 0)), COALESCE("$operator$hash_code"("md5_lower_case"), 0)), COALESCE("$operator$hash_code"("maid"), 0)), COALESCE("$operator$hash_code"("partner_id"), 0)), COALESCE("$operator$hash_code"("segment"), 0))
        $hashvalue_22 := combine_hash(combine_hash(combine_hash(combine_hash(combine_hash(combine_hash(combine_hash(combine_hash(bigint '0', COALESCE("$operator$hash_code"("cc_uid"), 0)), COALESCE("$operator$hash_code"("sha256_lower_case"), 0)), COALESCE("$operator$hash_code"("sha1_lower_case"), 0)), COALESCE("$operator$hash_code"("md5_lower_case"), 0)), COALESCE("$operator$hash_code"("maid"), 0)), COALESCE("$operator$hash_code"("partner_id"), 0)), COALESCE("$operator$hash_code"("audience_slug"), 0)), COALESCE("$operator$hash_code"("segment"), 0))
        sha1_lower_case := sha1_lower_case:string:REGULAR
        referer := referer:string:REGULAR
        instances := instances:int:REGULAR
        cc_uid := cc_uid:string:REGULAR
        ip := ip:string:REGULAR
        source := source:varchar(18):REGULAR
        ua := ua:string:REGULAR
        dt := dt:date:REGULAR
        sha256_lower_case := sha256_lower_case:string:REGULAR
        md5_lower_case := md5_lower_case:string:REGULAR
        partner_id := partner_id:string:REGULAR
        segment := segment:string:REGULAR
        audience_slug := audience_slug:string:PARTITION_KEY
            :: [[24a6bc8c41bebcd]]
        maid := maid:string:REGULAR
        timestamp := timestamp:timestamp:REGULAR
        date:date:PARTITION_KEY
            :: [[2022-06-02]]


```

Initial discussion: https://trinodb.slack.com/archives/CGB0QHWSW/p1654174991704059

**Comment by martint** [comment]
Probably related to https://github.com/trinodb/trino/pull/11289

**Comment by lukasz-stec** [comment]
The bug is caused by an unusual `Block` with all positions null that is not RLE.
Fix https://github.com/trinodb/trino/pull/12670

**Comment by sopel39** [comment]
It's not that unusual as it might come from appending null only positions from block with both nulls and non nulls
