### ISSUE TITLE
Iceberg fails with java.lang.NoClassDefFoundError: io/grpc/Context when using GCS

### ISSUE THREAD

**Issue by jotarada** [trinodb/trino#12674]
upgrading a system from trino 380 to 383 running on k8s using the official docker image using iceberg tables in GCS storage got this error:

 ```TrinoQueryError(type=INTERNAL_ERROR, name=GENERIC_INTERNAL_ERROR, message="java.lang.NoClassDefFoundError: io/grpc/Context", query_id=20220603_081657_00029_pds2t)``` 

Full stack error 
```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: io/grpc/Context
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:147)
	at io.trino.$gen.Trino_383____20220603_080549_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: io/grpc/Context
	at io.opencensus.trace.unsafe.ContextManagerImpl.currentContext(ContextManagerImpl.java:30)
	at io.opencensus.trace.unsafe.ContextHandleUtils.currentContext(ContextHandleUtils.java:56)
	at io.opencensus.trace.CurrentSpanUtils.getCurrentSpan(CurrentSpanUtils.java:37)
	at io.opencensus.trace.Tracer.spanBuilder(Tracer.java:308)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:847)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:549)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:482)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:599)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getObject(GoogleCloudStorageImpl.java:1905)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfo(GoogleCloudStorageImpl.java:1813)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.open(GoogleCloudStorageImpl.java:601)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.open(GoogleCloudStorageFileSystem.java:305)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFSInputStream.<init>(GoogleHadoopFSInputStream.java:78)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.open(GoogleHadoopFileSystemBase.java:628)
	at io.trino.plugin.hive.fs.TrinoFileSystemCache$FileSystemWrapper.open(TrinoFileSystemCache.java:307)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:899)
	at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175)
	at io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:97)
	at io.trino.plugin.iceberg.HdfsInputFile.newStream(HdfsInputFile.java:62)
	at org.apache.iceberg.TableMetadataParser.read(TableMetadataParser.java:250)
	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.lambda$refreshFromMetadataLocation$1(AbstractIcebergTableOperations.java:223)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190)
	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.refreshFromMetadataLocation(AbstractIcebergTableOperations.java:222)
	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.refresh(AbstractIcebergTableOperations.java:127)
	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.current(AbstractIcebergTableOperations.java:110)
	at io.trino.plugin.iceberg.catalog.hms.TrinoHiveCatalog.lambda$loadTable$8(TrinoHiveCatalog.java:287)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.trino.plugin.iceberg.catalog.hms.TrinoHiveCatalog.loadTable(TrinoHiveCatalog.java:285)
	at io.trino.plugin.iceberg.IcebergMetadata.getTableHandle(IcebergMetadata.java:276)
	at io.trino.plugin.iceberg.IcebergMetadata.getTableHandle(IcebergMetadata.java:213)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableHandle(ClassLoaderSafeConnectorMetadata.java:184)
	at io.trino.metadata.MetadataManager.lambda$getTableHandle$5(MetadataManager.java:281)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at io.trino.metadata.MetadataManager.getTableHandle(MetadataManager.java:261)
	at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1486)
	at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1478)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitInsert(StatementAnalyzer.java:493)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitInsert(StatementAnalyzer.java:436)
	at io.trino.sql.tree.Insert.accept(Insert.java:68)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:453)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:416)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:193)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:808)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:135)
```

**Comment by findepi** [comment]
cc @alexjo2144

**Comment by findepi** [comment]
The class should come in Iceberg from `io.grpc:grpc-context:jar:1.44.1` dep, but it's on `test` classpath of the Iceberg module.

i bisected this to ab25d52b4f54cd9be3973fc8a2fadd99bacc73f4 (released in 382)

```
git bisect start master 370

git bisect run sh -c '
rm -rf ~/.m2/repository/io/trino && 
mvnd -pl :trino-iceberg -am clean install -nsu -DskipTests -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -Dair.check.skip-all=true >/dev/null &&
mvnd dependency:tree -nsu -pl :trino-iceberg | grep grpc-context:jar | grep compile
'

ab25d52b4f54cd9be3973fc8a2fadd99bacc73f4 is the first bad commit
commit ab25d52b4f54cd9be3973fc8a2fadd99bacc73f4
Author: Zebing Lin <linzebing1995@gmail.com>
Date:   Thu May 12 14:34:24 2022 -0700

    Support exchange spooling on GCS
```


cc @linzebing @arhimondr @losipiuk

**Comment by losipiuk** [comment]
I send out a workaround PR https://github.com/trinodb/trino/pull/12742.
Not tested yet - do we have a repro @findepi ?

But I think this is not a proper way to fix it long term.
The fix specifically addresses GCS problem but IDK if similar situation is not happening with some other jars, we just did not hit the problem yet.

If we cannot safely add `trino-exchange-filesystem` as `test` dependency of other modules we may need to create specific test modules for hive, iceberg, delta. Any other ideas?

We could also maybe split `trino-exchange-filesystem` into multiple modules - one per supported cloud. We then would use only one of those as test dependency of `trino-hive`, `trino-delta` and `trino-iceberg`. 
But it just makes the problem surface smaller.  The used one would depend on AWS SDK - which may have similar issue with what we observe with GCP.

**Comment by findepi** [comment]
> I send out a workaround PR #12742.

thanks

> Not tested yet - do we have a repro @findepi ?

nope. i was doing the mvnd dependency listing only

> But I think this is not a proper way to fix it long term.
The fix specifically addresses GCS problem but IDK if similar situation is not happening with some other jars, we just did not hit the problem yet.

agreed

> We could also maybe split trino-exchange-filesystem into multiple modules - one per supported cloud. We then would use only one of those as test dependency of trino-hive, trino-delta and trino-iceberg.
But it just makes the problem surface smaller.

agree it sounds like a workaround, not a full solution

maybe we can remove GCS-related exclusions from the `trino-exchange-filesystem`?
or, maybe splitting `trino-exchange-filesystem` into 2+ modules allows us to remove maven exclusions, which seem to be the source of evil here? (no exclusions => no problem)

or, maybe, we can remove `trino-exchange-filesystem` from being test dependency of other plugins?
the fact that a plugin needs some other plugin for its tests is not a good sign.
it means that something is not properly stubbed out.

**Comment by alexjo2144** [comment]
I just put together a GCS product test env, I'll try that patch out for ya.

**Comment by losipiuk** [comment]
> I was able to do a CTAS and select against GCS with those POM changes. I'm not sure exactly how to test the exchange-filesystem features though

thanks - the exchange-filesystem should not be impacted at all.

You tested with https://github.com/trinodb/trino/pull/12746, right?

**Comment by alexjo2144** [comment]
Whoops, no I missed that. I tested https://github.com/trinodb/trino/pull/12742 I'll try that one too

**Comment by alexjo2144** [comment]
Alright for total clarity, I tested a GCS ctas + select with commit `b3dd2607b120bb1c25ea8e9949b16e1e04e2c05b Move fault tolerant tests to trino-tests module`

Works fine
