### ISSUE TITLE
Cannot create tables when specified database name in MariaDB connection url

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#12712]
If we specify a database name in connection url likes `jdbc:mariadb://localhost:3306/tpch`, the connector fails to create a new table. 
```
java.lang.RuntimeException: (conn=12) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`tmp_trino_2f490ed693c2484599d588d044c8b1ce` (`custkey` bigint, `name` tinyt...' at line 1
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:526)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:339)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:331)
	at io.trino.testing.QueryAssertions.copyTpchTables(QueryAssertions.java:323)
	at io.trino.plugin.mariadb.MariaDbQueryRunner.createMariaDbQueryRunner(MariaDbQueryRunner.java:59)
	at io.trino.plugin.mariadb.MariaDbQueryRunner.main(MariaDbQueryRunner.java:80)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE IF NOT EXISTS customer AS SELECT * FROM tpch.tiny.customer
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:529)
		... 5 more
Caused by: io.trino.spi.TrinoException: (conn=12) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`tmp_trino_2f490ed693c2484599d588d044c8b1ce` (`custkey` bigint, `name` tinyt...' at line 1
	at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:949)
	at io.trino.plugin.jdbc.BaseJdbcClient.createTable(BaseJdbcClient.java:572)
	at io.trino.plugin.jdbc.BaseJdbcClient.beginCreateTable(BaseJdbcClient.java:535)
	at io.trino.plugin.jdbc.ForwardingJdbcClient.beginCreateTable(ForwardingJdbcClient.java:190)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$beginCreateTable$26(StatisticsAwareJdbcClient.java:264)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.beginCreateTable(StatisticsAwareJdbcClient.java:264)
	at io.trino.plugin.jdbc.CachingJdbcClient.beginCreateTable(CachingJdbcClient.java:457)
	at io.trino.plugin.jdbc.CachingJdbcClient.beginCreateTable(CachingJdbcClient.java:457)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.beginCreateTable(DefaultJdbcMetadata.java:702)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.beginCreateTable(ClassLoaderSafeConnectorMetadata.java:456)
	at io.trino.metadata.MetadataManager.beginCreateTable(MetadataManager.java:852)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:258)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:201)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:104)
	at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:81)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:72)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:72)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:37)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:21)
	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:31)
	at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:89)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:239)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:216)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:211)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:477)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:458)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:399)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20220607_003919_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.RuntimeException: Query: CREATE TABLE `tpch`.`tpch`.`tmp_trino_2f490ed693c2484599d588d044c8b1ce` (`custkey` bigint, `name` tinytext, `address` tinytext, `nationkey` bigint, `phone` tinytext, `acctbal` double precision, `mktsegment` tinytext, `comment` tinytext) COMMENT ''
```

**Comment by zhaoyim** [comment]
In Mysql I saw the fix is as following, I think we should do the same fix. Any ideas? @ebyhr 
```
2022-06-07T12:23:46.278+0800	ERROR	main	io.trino.server.Server	Configuration errors:

1) Error: Invalid configuration property with prefix '': Database (catalog) must not be specified in JDBC URL for MySQL connector (for class MySqlJdbcConfig.urlWithoutDatabase)

1 error

======================
Full classname legend:
======================
MySqlJdbcConfig: "io.trino.plugin.mysql.MySqlJdbcConfig"
========================
End of classname legend:
========================

io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Invalid configuration property with prefix '': Database (catalog) must not be specified in JDBC URL for MySQL connector (for class MySqlJdbcConfig.urlWithoutDatabase)

1 error

======================
Full classname legend:
======================
MySqlJdbcConfig: "io.trino.plugin.mysql.MySqlJdbcConfig"
========================
End of classname legend:
========================


```

**Comment by zhaoyim** [comment]
Same results as Mysql

### MariaDB :
Login with root user:

```
MariaDB [(none)]> CREATE USER 'zhaoyim'@'%' IDENTIFIED BY 'test';
Query OK, 0 rows affected (0.00 sec)

MariaDB [(none)]> create database data1;
Query OK, 1 row affected (0.00 sec)

MariaDB [(none)]> GRANT ALL PRIVILEGES ON data1.* TO 'zhaoyim'@'%';
Query OK, 0 rows affected (0.01 sec)

MariaDB [(none)]> flush privileges;
Query OK, 0 rows affected (0.00 sec)
```

Login with user:zhaoyim
```
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| data1              |
| information_schema |
+--------------------+
2 rows in set (0.00 sec)
```

### Trino
catalog properties using user zhaoyim
```
trino:tpch> show schemas  from mariadb;
       Schema
--------------------
 data1
 information_schema
(2 rows)
```

**Comment by zhaoyim** [comment]
@[martint](https://github.com/martint) Could you help confirm, will we do the same fix as Mysql? Thanks a lot!

**Comment by ebyhr** [comment]
@zhaoyim I guess we can avoid the above failure by adjusting the logic around quoting the identifier. On the other hand, I think it doesn't bring any (or less) benefits. Let's add the same restriction as MySQL.

**Comment by zhaoyim** [comment]
@ebyhr  Thanks for confirm!
