### ISSUE TITLE
Support time travel on Iceberg system tables

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#12736]
The following versioned query works OK:

```
select * from "icebergtable$files@7046541185529900854";
```

However the query:

```
select * from "icebergtable$files" for version as of 7046541185529900854;
```

fails with the exception:

```
io.trino.spi.TrinoException: This connector does not support versioned tables
	at io.trino.spi.connector.ConnectorMetadata.isSupportedVersionType(ConnectorMetadata.java:1319)
	at io.trino.metadata.MetadataManager.isValidTableVersion(MetadataManager.java:2415)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.extractTableVersion(StatementAnalyzer.java:4579)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.getTableHandle(StatementAnalyzer.java:4543)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1771)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:436)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:453)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3666)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2405)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:436)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:453)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:461)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1377)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:436)
```

The problem is lied to the fact that "icebergtable$files" translates to  `SystemTablesMetadata` which has no implementation for the method `io.trino.spi.connector.ConnectorMetadata#isSupportedVersionType`

In any case extracting the start version and end version shouldn't be done in `StatementAnalyzer` but in `IcebergMetadata`

https://github.com/trinodb/trino/blob/84162568f31493137e88e0359c14cfcba50c783b/core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java#L4541-L4544

Also `SystemTablesMetadata` should have an implementation for the interface method `getTableHandle(io.trino.spi.connector.ConnectorSession, io.trino.spi.connector.SchemaTableName, java.util.Optional<io.trino.spi.connector.ConnectorTableVersion>, java.util.Optional<io.trino.spi.connector.ConnectorTableVersion>)`

**Comment by electrum** [comment]
I don't think we want to extend `SystemTable` any further. Now that we allow multiple table handles, that seems like a more straightforward approach.
