### ISSUE TITLE
Query some google sheets found error

### ISSUE THREAD

**Issue by zengbotang** [trinodb/trino#12811]
Query some google sheets throw the following exception :

`Query 20220518_025840_00003_vkndz failed: CacheLoader returned null for key my_google_sheet_keyxxxxxxxxx#s1.
com.google.common.cache.CacheLoader.InvalidCacheLoadException: CacheLoader returned null for key my_google_sheet_keyxxxxxxxxx#s1.
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2319)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2283)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4956)
        at com.google.common.cache.ForwardingLoadingCache.getUnchecked(ForwardingLoadingCache.java:51)
        at io.trino.plugin.google.sheets.SheetsClient.readAllValues(SheetsClient.java:165)
        at io.trino.plugin.google.sheets.SheetsClient.getTable(SheetsClient.java:118)
        at io.trino.plugin.google.sheets.SheetsMetadata.getTableHandle(SheetsMetadata.java:72)
        at io.trino.plugin.google.sheets.SheetsMetadata.getTableHandle(SheetsMetadata.java:41)
        at io.trino.metadata.MetadataManager.lambda$getTableHandle$5(MetadataManager.java:280)
        at java.base/java.util.Optional.flatMap(Optional.java:287)
        at io.trino.metadata.MetadataManager.getTableHandle(MetadataManager.java:260)
        at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1485)
        at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1477)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.getTableHandle(StatementAnalyzer.java:4283)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1508)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:404)
        at io.trino.sql.tree.Table.accept(Table.java:60)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:421)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3403)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2142)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:404)
        at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:421)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:429)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1345)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:404)
        at io.trino.sql.tree.Query.accept(Query.java:107)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:421)
        at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:384)
        at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
        at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
        at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)
        at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:193)
        at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:808)
        at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:135)
        at io.trino.$gen.Trino_380____20220507_140727_2.call(Unknown Source)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)`

trino version : 380

some info: 
This error only appear in some special Google sheet,  I am sorry that I can not provide my google sheet to reproduce this error.
but if I remove #s1 in sheet key : my_google_sheet_keyxxxxxxxxx#s1, then the sheet can be query normally.

I have do some test , an found that may be the following code in io.trino.plugin.google.sheets.SheetsClient.readAllValuesFromSheetExpression return null lead to this error:
return sheetsService.spreadsheets().values().get(sheetId, defaultRange).execute().getValues();

**Comment by ebyhr** [comment]
Could you try to prepare the steps to reproduce with sample data?

**Comment by zengbotang** [comment]
@ebyhr It can be reproduce by the following step 
1. create a google sheet with some data
2. rename Sheet1 to s1, you will get a key like "you_google_sheet_key#s1"
3. do some trino config , like auth , add to metasheet 
4. query the sheet table
