### ISSUE TITLE
Flaky `Query timed out after PT2S` in Cassandra product tests

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#12818]
We may want to increase the timeout or add retry logic to `onCassandra` method. 
```
tests               | 2022-06-13 14:03:00 INFO: FAILURE     /    io.trino.tests.product.cassandra.TestSelect.testSelectAllTypePartitioningMaterializedView (Groups: profile_specific_tests, cassandra) took 12.8 seconds
tests               | 2022-06-13 14:03:00 SEVERE: Failure cause:
tests               | com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
tests               | 	at com.datastax.oss.driver.api.core.DriverTimeoutException.copy(DriverTimeoutException.java:34)
tests               | 	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
tests               | 	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
tests               | 	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
tests               | 	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
tests               | 	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54)
tests               | 	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:78)
tests               | 	at io.trino.tempto.internal.query.CassandraQueryExecutor.executeQuery(CassandraQueryExecutor.java:87)
tests               | 	at io.trino.tests.product.cassandra.TestSelect.onCassandra(TestSelect.java:569)
tests               | 	at io.trino.tests.product.cassandra.TestSelect.testSelectAllTypePartitioningMaterializedView(TestSelect.java:329)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:829)
```
https://github.com/trinodb/trino/runs/6857005393

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/8223696569

**Comment by ebyhr** [comment]
```
tests               | 2022-12-06 07:28:34 INFO: FAILURE     /    io.trino.tests.product.cassandra.TestInsertIntoCassandraTable.testInsertIntoTupleType (Groups: profile_specific_tests, cassandra) took 10.6 seconds
tests               | 2022-12-06 07:28:34 SEVERE: Failure cause:
tests               | com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
tests               | 	at com.datastax.oss.driver.api.core.DriverTimeoutException.copy(DriverTimeoutException.java:34)
tests               | 	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
tests               | 	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
tests               | 	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
tests               | 	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
tests               | 	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54)
tests               | 	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:78)
tests               | 	at io.trino.tempto.internal.query.CassandraQueryExecutor.executeQuery(CassandraQueryExecutor.java:87)
tests               | 	at io.trino.tests.product.cassandra.TestInsertIntoCassandraTable.onCasssandra(TestInsertIntoCassandraTable.java:191)
tests               | 	at io.trino.tests.product.cassandra.TestInsertIntoCassandraTable.testInsertIntoTupleType(TestInsertIntoCassandraTable.java:185)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
```
https://github.com/trinodb/trino/actions/runs/3624162092/jobs/6111905985

**Comment by ebyhr** [comment]
```
tests               | 2022-12-20 10:32:47 INFO: FAILURE     /    io.trino.tests.product.cassandra.TestSelect.testSelectClusteringMaterializedView (Groups: profile_specific_tests, cassandra) took 6.3 seconds
tests               | 2022-12-20 10:32:47 SEVERE: Failure cause:
tests               | com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
```
https://github.com/trinodb/trino/actions/runs/3737494447/jobs/6342870321

**Comment by raunaqmorarka** [comment]
https://github.com/trinodb/trino/actions/runs/4413797584/jobs/7736262572
```
tests               | 2023-03-14 16:47:07 INFO: FAILURE     /    io.trino.tests.product.cassandra.TestInsertIntoCassandraTable.testInsertIntoTupleType (Groups: profile_specific_tests, cassandra) took 17.8 seconds
[2320](https://github.com/trinodb/trino/actions/runs/4413797584/jobs/7736262572#step:7:2321)
tests               | 2023-03-14 16:47:07 SEVERE: Failure cause:
[2321](https://github.com/trinodb/trino/actions/runs/4413797584/jobs/7736262572#step:7:2322)
tests               | com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
[2322](https://github.com/trinodb/trino/actions/runs/4413797584/jobs/7736262572#step:7:2323)
tests               | 	at com.datastax.oss.driver.api.core.DriverTimeoutException.copy(DriverTimeoutException.java:34)
```
Encountered in https://github.com/trinodb/trino/pull/16203

**Comment by Praveen2112** [comment]
https://github.com/trinodb/trino/actions/runs/4424015003/jobs/7759726674

Encountered in https://github.com/trinodb/trino/pull/16402

**Comment by homar** [comment]
https://github.com/trinodb/trino/actions/runs/4562761241/jobs/8057065016?pr=16794

Hit again https://github.com/trinodb/trino/pull/16794

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/actions/runs/4576945110/jobs/8085873870?pr=16796

**Comment by krvikash** [comment]
https://github.com/trinodb/trino/actions/runs/4665929809/jobs/8260256116?pr=16786

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4699807665/jobs/8338142207?pr=16825

```
tests               | 2023-04-15 01:42:13 INFO: FAILURE     /    io.trino.tests.product.cassandra.TestSelect.testSelectAllTypePartitioningMaterializedView (Groups: profile_specific_tests, cassandra) took 15.2 seconds
tests               | 2023-04-15 01:42:13 SEVERE: Failure cause:
tests               | com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
tests               | 	at com.datastax.oss.driver.api.core.DriverTimeoutException.copy(DriverTimeoutException.java:34)
tests               | 	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
tests               | 	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
tests               | 	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
tests               | 	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
tests               | 	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54)
tests               | 	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:78)
tests               | 	at io.trino.tempto.internal.query.CassandraQueryExecutor.executeQuery(CassandraQueryExecutor.java:87)
tests               | 	at io.trino.tests.product.cassandra.TestSelect.onCassandra(TestSelect.java:568)
tests               | 	at io.trino.tests.product.cassandra.TestSelect.testSelectAllTypePartitioningMaterializedView(TestSelect.java:328)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by krvikash** [comment]
https://github.com/trinodb/trino/actions/runs/4729576698/jobs/8392840710
