### ISSUE TITLE
Iceberg fails to read certain timestamp with time zone values before the epoch from a Parquet file

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#12852]
```sql
DROP TABLE IF EXISTS t;
CREATE TABLE t (d timestamp(6) with time zone, b integer) WITH (format = 'PARQUET');

-- this works
INSERT INTO t VALUES (TIMESTAMP '1969-12-01 00:00:00.000000 UTC', 10);
INSERT: 1 row

SELECT * FROM t;
               d                | b
--------------------------------+----
 1969-12-01 00:00:00.000000 UTC | 10

-- but this similar value does not
INSERT INTO t VALUES (TIMESTAMP '1969-12-01 05:06:07.234567 UTC', 11);
INSERT: 1 row

SELECT * FROM t;
Query 20220615_080027_00072_ej99z failed: picosOfMilli must be >= 0
java.lang.IllegalArgumentException: picosOfMilli must be >= 0
	at io.trino.spi.type.LongTimestampWithTimeZone.<init>(LongTimestampWithTimeZone.java:52)
	at io.trino.spi.type.LongTimestampWithTimeZone.fromEpochMillisAndFraction(LongTimestampWithTimeZone.java:41)
	at io.trino.parquet.reader.TimestampMicrosColumnReader.readValue(TimestampMicrosColumnReader.java:69)
	at io.trino.parquet.reader.PrimitiveColumnReader.lambda$readValues$2(PrimitiveColumnReader.java:244)
	at io.trino.parquet.reader.PrimitiveColumnReader.processValues(PrimitiveColumnReader.java:300)
	at io.trino.parquet.reader.PrimitiveColumnReader.readValues(PrimitiveColumnReader.java:242)
	at io.trino.parquet.reader.PrimitiveColumnReader.readPrimitive(PrimitiveColumnReader.java:231)
	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:381)
	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:460)
	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:443)
	at io.trino.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:212)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:400)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:379)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:286)
	at io.trino.spi.Page.getLoadedPage(Page.java:287)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:314)
	at io.trino.operator.Driver.processInternal(Driver.java:410)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_testversion____20220615_075608_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

reproduced on current master

```
$ git describe
385-96-g7aa4a0ec6c
```

**Comment by findepi** [comment]
Repro: https://github.com/trinodb/trino/pull/12855
