### ISSUE TITLE
Flaky test TestHiveFaultTolerantExecutionConnectorTest

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#12858]

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/6894880810?check_suite_focus=true

```
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionConnectorTest.testTableAuthorizationForRole  Time elapsed: 0.031 s  <<< FAILURE!
java.lang.RuntimeException: line 1:1: Schema 'hive.test_table_authorization' already exists
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:526)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:313)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testTableAuthorizationForRole(BaseHiveConnectorTest.java:813)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: SQL: CREATE SCHEMA test_table_authorization
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:529)
		... 16 more
Caused by: io.trino.spi.TrinoException: line 1:1: Schema 'hive.test_table_authorization' already exists
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.execution.CreateSchemaTask.internalExecute(CreateSchemaTask.java:97)
	at io.trino.execution.CreateSchemaTask.execute(CreateSchemaTask.java:77)
	at io.trino.execution.CreateSchemaTask.execute(CreateSchemaTask.java:49)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20220615_073047_4802.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

cc @arhimondr @losipiuk @linzebing
