### ISSUE TITLE
JsonParseException when writing from Hive JSON table using writer scaling

### ISSUE THREAD

**Issue by radek-starburst** [trinodb/trino#12866]
When Trino decides to use `ScaledWritersScheduler` it causes unexpected errors, especially errors during reading and parsing input data. The bug occurrs as `JsonParseException` (for table with `JSON` format) or some `IOException` for `Avro` format. 

The problem was observed by other user, I did not manage to reproduce that. 
 
The stacktrace for query like `insert into ... (select * from )` is:

```
io.trino.spi.TrinoException: io.trino.hive.$internal.org.codehaus.jackson.JsonParseException: Unexpected character ('b' (code 98)): was expecting a colon to separate field name and value
 at [Source: [B@7abe6191; line: 1, column: 1316]
	at io.trino.plugin.hive.GenericHiveRecordCursor.advanceNextPosition(GenericHiveRecordCursor.java:233)
	at io.trino.plugin.hive.util.ForwardingRecordCursor.advanceNextPosition(ForwardingRecordCursor.java:46)
	at io.trino.plugin.hive.util.ForwardingRecordCursor.advanceNextPosition(ForwardingRecordCursor.java:46)
	at io.trino.$gen.CursorProcessor_20220527_184104_3.process(Unknown Source)
	at io.trino.operator.ScanFilterAndProjectOperator$RecordCursorToPages.process(ScanFilterAndProjectOperator.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:182)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$7(WorkProcessorUtils.java:296)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$3(WorkProcessorUtils.java:219)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$4(WorkProcessorUtils.java:234)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:150)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:693)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_380_e_0____20220527_183838_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.hadoop.hive.serde2.SerDeException: io.trino.hive.$internal.org.codehaus.jackson.JsonParseException: Unexpected character ('b' (code 98)): was expecting a colon to separate field name and value
 at [Source: [B@7abe6191; line: 1, column: 1316]
	at org.apache.hive.hcatalog.data.JsonSerDe.deserialize(JsonSerDe.java:184)
	at io.trino.plugin.hive.GenericHiveRecordCursor.advanceNextPosition(GenericHiveRecordCursor.java:224)
	... 33 more
Caused by: io.trino.hive.$internal.org.codehaus.jackson.JsonParseException: Unexpected character ('b' (code 98)): was expecting a colon to separate field name and value
 at [Source: [B@7abe6191; line: 1, column: 1316]
	at io.trino.hive.$internal.org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
	at io.trino.hive.$internal.org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
	at io.trino.hive.$internal.org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
	at io.trino.hive.$internal.org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:500)
	at org.apache.hive.hcatalog.data.JsonSerDe.extractCurrentField(JsonSerDe.java:385)
	at org.apache.hive.hcatalog.data.JsonSerDe.populateRecord(JsonSerDe.java:222)
	at org.apache.hive.hcatalog.data.JsonSerDe.deserialize(JsonSerDe.java:177)
	... 34 more

```

It is not observed when `scaleWriters` is off

The suggestion is to:

1. Disable `scaleWriters`  by default
2. Repair `ScaledWriterScheduler` and its effects.
3. Enable by default.

@arhimondr , @raunaqmorarka , @sopel39

**Comment by findepi** [comment]
Can it be a concurrency problem in `org.apache.hive.hcatalog.data.JsonSerDe`?

cc @MiguelWeezardo 

(not sure how it could be related to writer scaling though)

**Comment by radek-starburst** [comment]
> Can it be a concurrency problem in `org.apache.hive.hcatalog.data.JsonSerDe`?

This problem looks like a concurrency problem. However, the current analysis points that `JsonSerde` is not threadsafe by design. It could mean that there is a concurrency problem in an execution stuff. But, it is only hypothesis for now.

**Comment by MiguelWeezardo** [comment]
`JsonSerDe` has a `HCatSchema` field which explicitly states it's not thread-safe, yet it's being passed to `populateRecord()` which handles blocks of consecutive JSON lines. If multiple splits can access the same file it could be accessed from multiple threads.

**Comment by MiguelWeezardo** [comment]
I've noticed the description also mentions an exception when using with `Avro` format. I see several possibilities:
* we have two separate formatters which are expected to be thread-safe but aren't
* `avro` and `json` share some code which has a problem with thread-safety
* there's some synchronization problem in the `scaleWriters` code outside of the actual formatter code, but the formatter is the first to notice.

**Comment by radek-starburst** [comment]
> there's some synchronization problem in the scaleWriters code outside of the actual formatter code, but the formatter is the first to notice.

There is no something like synchronization code in `scaleWriters`. `scaleWriters` just adds tasks dynamically to the writing stage. This dynamic adding tasks is just using the scheduling inteface. However, adding task in the upper stage causes some updated (`outputBuffers` and `splitAssigment`) to the source tasks and this thing could be a root cause as a side-effect of adding task dynamically. 

> we have two separate formatters which are expected to be thread-safe but aren't
I've read the code a bit and how `cursors` / `fomatters` / `recordreaders` are used. They are not thread-safe, they are not expected to be thread-safe, at lest intentionally. Obviously, they could be used concurrently / used after close because of bug in assigning split to the drivers. 

> avro and json share some code (JSON parser for avro schemas?) which has a problem with thread-safety

Yes, it looks like the problem is same for `avro` and `json`. Howver, it is not strictly coupled to the `JSON` or `AVRO`, on my eye.  It is connected to the `HiveRecordReader`. Parsing error of `avro`/`json` is just a manifestation.  

Looks like concurrency bug. It happens *every* time for user. Concurrency bugs are used to be more fussy ;), though.

**Comment by findepi** [comment]
FWIW i tried to repro this with https://github.com/trinodb/trino/pull/12958
at least locally i didn't get any failure. @radek-starburst can you help me reproduce the problem?

**Comment by radek-starburst** [comment]
@findepi , I was also unable to reproduce that. Anyway, I can try to do it again.

**Comment by findepi** [comment]
> `JsonSerDe` has a `HCatSchema` field which explicitly states it's not thread-safe, yet it's being passed to `populateRecord()` which handles blocks of consecutive JSON lines. If multiple splits can access the same file it could be accessed from multiple threads.

@MiguelWeezardo 
If there are two concurrent splits for same file, will they have same instance of `JsonSerDe` or separate?

BTW i realized @electrum already fixed some thread-safety issue in `org.apache.hive.hcatalog.data.JsonSerDe`:
https://github.com/trinodb/trino-hive-apache/commit/26cd4c26a7458b3dcf3fc82c42e86275f76f7469
as a workaround to https://issues.apache.org/jira/browse/HIVE-15773 not being fixed.

@electrum can you help reproducing this issue?

**Comment by findinpath** [comment]
@findepi the fix you are referring to is already included in Trino `380` with dependency `io.trino.hive:hive-apache:3.1.2-19`.

> If there are two concurrent splits for same file, will they have same instance of JsonSerDe or separate?

Each cursor instance creates its own deserializer instance:

https://github.com/trinodb/trino/blob/fe608f2723842037ff620d612a706900e79c52c8/plugin/trino-hive/src/main/java/io/trino/plugin/hive/GenericHiveRecordCursor.java#L141

**Comment by electrum** [comment]
This happens on the read path, so it’s not directly related to writer scaling. My guess is that writer scaling triggers a thread safety issue somehow this due to readers becoming blocked since the output buffer is full. Without writer scaling, readers might not block or will block less often.

You could try to reproduce this by doing a high concurrency read, or writing a concurrency test that utilizers many readers in parallel.

**Comment by findinpath** [comment]
Further test (which still doesn't reproduce) the issue:

https://github.com/trinodb/trino/commit/9f0289ec760b3ac08c42234a4a9aa96e62802a7f

One aspect on which I'm hanging now is in `io.trino.hive.$internal.org.codehaus.jackson.JsonFactory` :

```
    /**
     * This <code>ThreadLocal</code> contains a {@link java.lang.ref.SoftReference}
     * to a {@link BufferRecycler} used to provide a low-cost
     * buffer recycling between reader and writer instances.
     */
    final protected static ThreadLocal<SoftReference<BufferRecycler>> _recyclerRef
        = new ThreadLocal<SoftReference<BufferRecycler>>();
```

Maybe this thread local buffer recycler is getting to some inconsistent state.
