### ISSUE TITLE
Issue reading Iceberg `$partitions` table when updating the partition scheme

### ISSUE THREAD

**Issue by bitsondatadev** [trinodb/trino#12874]
Getting this in version 384 specifically when we use level column partition schemes (day(ts), string) > (hour(ts), string). When I remove the string column, there is no issue.

Stacktrace
```
java.lang.IllegalArgumentException: Wrong class, java.lang.Integer, for object: WARN
	at org.apache.iceberg.PartitionData.get(PartitionData.java:120)
	at org.apache.iceberg.types.Comparators$StructLikeComparator.compare(Comparators.java:126)
	at org.apache.iceberg.types.Comparators$StructLikeComparator.compare(Comparators.java:102)
	at org.apache.iceberg.util.StructLikeWrapper.equals(StructLikeWrapper.java:76)
	at java.base/java.util.Objects.equals(Objects.java:77)
	at io.trino.plugin.iceberg.PartitionTable$StructLikeWrapperWithFieldIdToIndex.equals(PartitionTable.java:363)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:239)
	at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:132)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:94)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:573)
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:601)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:588)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:582)
	at io.trino.plugin.iceberg.PartitionTable.getStatisticsByPartition(PartitionTable.java:236)
	at io.trino.plugin.iceberg.PartitionTable.cursor(PartitionTable.java:215)
	at io.trino.plugin.base.classloader.ClassLoaderSafeSystemTable.cursor(ClassLoaderSafeSystemTable.java:62)
	at io.trino.connector.system.SystemPageSourceProvider$1.cursor(SystemPageSourceProvider.java:129)
	at io.trino.split.MappedRecordSet.cursor(MappedRecordSet.java:53)
	at io.trino.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
	at io.trino.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:108)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:68)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:308)
	at io.trino.operator.Driver.processInternal(Driver.java:410)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_384____20220609_204327_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Steps to reproduce:
```
CREATE SCHEMA iceberg.logging
WITH (location = 's3a://logging/');

CREATE TABLE iceberg.logging.logs (
   level varchar NOT NULL,
   event_time timestamp(6) with time zone NOT NULL,
   message varchar NOT NULL,
   call_stack array(varchar)
)
WITH (
   format = 'ORC',
   partitioning = ARRAY['day(event_time)', 'level']
);

INSERT INTO iceberg.logging.logs VALUES 
(
  'ERROR', 
  timestamp '2021-04-01 12:23:53.383345' AT TIME ZONE 'America/Los_Angeles', 
  '1 message',
  ARRAY ['Exception in thread "main" java.lang.NullPointerException']
),
(
  'ERROR', 
  timestamp '2021-04-01 13:36:23' AT TIME ZONE 'America/Los_Angeles', 
  '2 message', 
  ARRAY ['Exception in thread "main" java.lang.NullPointerException']
);


SELECT * FROM iceberg.logging."logs$partitions"; # no issues on the first one

ALTER TABLE iceberg.logging.logs 
SET PROPERTIES partitioning = ARRAY['hour(event_time)', 'level'];

INSERT INTO iceberg.logging.logs VALUES 
(
  'ERROR', 
  timestamp '2021-04-01 15:55:23' AT TIME ZONE 'America/Los_Angeles', 
  '3 message', 
  ARRAY ['Exception in thread "main" java.lang.NullPointerException']
), 
(
  'WARN', 
  timestamp '2021-04-01 15:55:23' AT TIME ZONE 'America/Los_Angeles', 
  '4 message', 
  ARRAY ['bad things could be happening']
), 
(
  'WARN', 
  timestamp '2021-04-01 16:55:23' AT TIME ZONE 'America/Los_Angeles', 
  '5 message', 
  ARRAY ['bad things could be happening']
);

SELECT * FROM iceberg.logging."logs$partitions"; #error here
```

**Comment by osscm** [comment]
`SELECT * FROM iceberg.logging."logs$partitions"; #error here`

@bitsondatadev whats the error you see at this step?

**Comment by homar** [comment]
This was the stacktrace:
```
java.lang.IllegalArgumentException: Wrong class, java.lang.Integer, for object: WARN
    at org.apache.iceberg.PartitionData.get(PartitionData.java:120)
    at org.apache.iceberg.types.Comparators$StructLikeComparator.compare(Comparators.java:126)
    at org.apache.iceberg.types.Comparators$StructLikeComparator.compare(Comparators.java:102)
    at org.apache.iceberg.util.StructLikeWrapper.equals(StructLikeWrapper.java:76)
    at java.base/java.util.Objects.equals(Objects.java:77)
    at io.trino.plugin.iceberg.PartitionTable$StructLikeWrapperWithFieldIdToIndex.equals(PartitionTable.java:363)
    at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:239)
    at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:132)
    at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:94)
    at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:573)
    at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:601)
    at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:588)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:582)
    at io.trino.plugin.iceberg.PartitionTable.getStatisticsByPartition(PartitionTable.java:236)
    at io.trino.plugin.iceberg.PartitionTable.cursor(PartitionTable.java:215)
    at io.trino.plugin.base.classloader.ClassLoaderSafeSystemTable.cursor(ClassLoaderSafeSystemTable.java:62)
    at io.trino.connector.system.SystemPageSourceProvider$1.cursor(SystemPageSourceProvider.java:129)
    at io.trino.split.MappedRecordSet.cursor(MappedRecordSet.java:53)
    at io.trino.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
    at io.trino.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:108)
    at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:68)
    at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:308)
    at io.trino.operator.Driver.processInternal(Driver.java:410)
    at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
    at io.trino.operator.Driver.tryWithLock(Driver.java:698)
    at io.trino.operator.Driver.process(Driver.java:305)
    at io.trino.operator.Driver.processForDuration(Driver.java:276)
    at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
    at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
    at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
    at io.trino.$gen.Trino_384____20220609_204327_2.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by bitsondatadev** [comment]
Hey just realized I was actually using 384 (not 385) updated above.

Also, for the demo I removed the `level` field from the partition as the error was seemed to be related to that field and just just used the timestamp for the partition (or maybe the issue occurs for more than one field in the partition?) and that resolved the issue for my purposes.

**Comment by bitsondatadev** [comment]
Thanks @homar
