### ISSUE TITLE
Flaky TestPositionsAppender.testConsecutiveBuilds

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#12875]
We can reproduce by increasing `invocationCount`, 10 is enough in my environment. 

```sh
com.google.common.base.VerifyException: position count 1 too small to have at least one null with rate 0.5

	at com.google.common.base.Verify.verify(Verify.java:417)
	at io.trino.block.BlockAssertions.chooseNullPositions(BlockAssertions.java:362)
	at io.trino.block.BlockAssertions.generateListWithNulls(BlockAssertions.java:351)
	at io.trino.block.BlockAssertions.createRandomLongsBlock(BlockAssertions.java:301)
	at io.trino.block.BlockAssertions.createRandomBlockForType(BlockAssertions.java:151)
	at io.trino.block.BlockAssertions.createRandomBlockForNestedType(BlockAssertions.java:223)
	at io.trino.block.BlockAssertions.createRandomBlockForType(BlockAssertions.java:195)
	at io.trino.operator.output.TestPositionsAppender.testConsecutiveBuilds(TestPositionsAppender.java:188)
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```
https://github.com/trinodb/trino/runs/6903695040

cc: @sopel39 @lukasz-stec

**Comment by lukasz-stec** [comment]
@ebyhr I prepared a fix https://github.com/trinodb/trino/pull/12888

**Comment by phd3** [comment]
https://github.com/trinodb/trino/runs/7080500814?check_suite_focus=true
