### ISSUE TITLE
Iceberg rollback_to_snapshot procedure fails due to classloader issues

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#12887]
```
trino:default> create table t2 (a integer);
CREATE TABLE
trino:default> insert into t2 values 1;
INSERT: 1 row

Query 20220617_054905_00010_qdyhx, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
1.39 [0 rows, 0B] [0 rows/s, 0B/s]

trino:default> insert into t2 values 2;
INSERT: 1 row

Query 20220617_055212_00011_qdyhx, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
1.60 [0 rows, 0B] [0 rows/s, 0B/s]

trino:default> select * from "t2$snapshots";
             committed_at              |     snapshot_id     |      parent_id      | operation |                              >
---------------------------------------+---------------------+---------------------+-----------+------------------------------>
 2022-06-17 07:48:57.359 Europe/Vienna | 8877014715680553605 |                NULL | append    | hdfs://hadoop-master:9000/use>
 2022-06-17 07:49:06.499 Europe/Vienna |  546732699615194599 | 8877014715680553605 | append    | hdfs://hadoop-master:9000/use>
 2022-06-17 07:52:12.865 Europe/Vienna | 5328766858763350946 |  546732699615194599 | append    | hdfs://hadoop-master:9000/use>
(3 rows)

Query 20220617_055221_00012_qdyhx, FINISHED, 1 node
Splits: 9 total, 9 done (100.00%)
0.30 [3 rows, 1.49KB] [10 rows/s, 4.99KB/s]

trino:default> call system.rollback_to_snapshot('default', 't2', 546732699615194599);
Query 20220617_055250_00013_qdyhx failed: During instantiation, the Configuration object captures the TCCL and uses it to resolve classes by name. For this reason, the current TCCL jdk.internal.loader.ClassLoaders$AppClassLoader@77556fd should be same as this class's classloader io.trino.server.PluginClassLoader@5e8e40e8. Otherwise the constructed Configuration will use *some* classloader to resolve classes
```

Full stacktrace:

```
2022-06-17T07:54:16.859+0200	WARN	dispatcher-query-9	org.apache.iceberg.util.Tasks	Retrying task after failure: During instantiation, the Configuration object captures the TCCL and uses it to resolve classes by name. For this reason, the current TCCL jdk.internal.loader.ClassLoaders$AppClassLoader@77556fd should be same as this class's classloader io.trino.server.PluginClassLoader@5e8e40e8. Otherwise the constructed Configuration will use *some* classloader to resolve classes
java.lang.IllegalStateException: During instantiation, the Configuration object captures the TCCL and uses it to resolve classes by name. For this reason, the current TCCL jdk.internal.loader.ClassLoaders$AppClassLoader@77556fd should be same as this class's classloader io.trino.server.PluginClassLoader@5e8e40e8. Otherwise the constructed Configuration will use *some* classloader to resolve classes
	at com.google.common.base.Preconditions.checkState(Preconditions.java:821)
	at io.trino.hadoop.ConfigurationInstantiator.newConfiguration(ConfigurationInstantiator.java:43)
	at io.trino.hadoop.ConfigurationInstantiator.newEmptyConfiguration(ConfigurationInstantiator.java:27)
	at io.trino.plugin.hive.HiveHdfsConfiguration$1.initialValue(HiveHdfsConfiguration.java:41)
	at io.trino.plugin.hive.HiveHdfsConfiguration$1.initialValue(HiveHdfsConfiguration.java:37)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at io.trino.plugin.hive.HiveHdfsConfiguration.getConfiguration(HiveHdfsConfiguration.java:63)
	at io.trino.plugin.hive.HdfsEnvironment.getConfiguration(HdfsEnvironment.java:65)
	at io.trino.plugin.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:71)
	at io.trino.plugin.iceberg.HdfsInputFile.<init>(HdfsInputFile.java:44)
	at io.trino.plugin.iceberg.HdfsFileIo.newInputFile(HdfsFileIo.java:44)
	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.lambda$refreshFromMetadataLocation$1(AbstractIcebergTableOperations.java:223)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190)
	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.refreshFromMetadataLocation(AbstractIcebergTableOperations.java:222)
	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.refresh(AbstractIcebergTableOperations.java:127)
	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.current(AbstractIcebergTableOperations.java:110)
	at io.trino.plugin.iceberg.catalog.hms.TrinoHiveCatalog.lambda$loadTable$8(TrinoHiveCatalog.java:287)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.trino.plugin.iceberg.catalog.hms.TrinoHiveCatalog.loadTable(TrinoHiveCatalog.java:285)
	at io.trino.plugin.iceberg.RollbackToSnapshotProcedure.rollbackToSnapshot(RollbackToSnapshotProcedure.java:68)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:735)
	at io.trino.execution.CallTask.execute(CallTask.java:209)
	at io.trino.execution.CallTask.execute(CallTask.java:71)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_dev____20220617_054617_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Related issue: https://github.com/trinodb/trino/pull/12687

**Comment by findinpath** [comment]
cc: @findepi @losipiuk

**Comment by jotarada** [comment]
Hi we are hitting a similar issue during a Create as Select 
Full stacktrace:
```io.trino.spi.TrinoException: During instantiation, the Configuration object captures the TCCL and uses it to resolve classes by name. For this reason, the current TCCL jdk.internal.loader.ClassLoaders$AppClassLoader@21588809 should be same as this class's classloader io.trino.server.PluginClassLoader@d424f08. Otherwise the constructed Configuration will use *some* classloader to resolve classes
	at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:198)
	at io.trino.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:392)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:182)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$7(WorkProcessorUtils.java:296)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$3(WorkProcessorUtils.java:219)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$4(WorkProcessorUtils.java:234)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:150)
	at io.trino.operator.Driver.processInternal(Driver.java:410)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_386____20220620_155807_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: During instantiation, the Configuration object captures the TCCL and uses it to resolve classes by name. For this reason, the current TCCL jdk.internal.loader.ClassLoaders$AppClassLoader@21588809 should be same as this class's classloader io.trino.server.PluginClassLoader@d424f08. Otherwise the constructed Configuration will use *some* classloader to resolve classes
	at com.google.common.base.Preconditions.checkState(Preconditions.java:821)
	at io.trino.hadoop.ConfigurationInstantiator.newConfiguration(ConfigurationInstantiator.java:43)
	at io.trino.hadoop.ConfigurationInstantiator.newEmptyConfiguration(ConfigurationInstantiator.java:27)
	at io.trino.plugin.hive.HiveHdfsConfiguration$1.initialValue(HiveHdfsConfiguration.java:41)
	at io.trino.plugin.hive.HiveHdfsConfiguration$1.initialValue(HiveHdfsConfiguration.java:37)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at io.trino.plugin.hive.HiveHdfsConfiguration.getConfiguration(HiveHdfsConfiguration.java:63)
	at io.trino.plugin.hive.HdfsEnvironment.getConfiguration(HdfsEnvironment.java:65)
	at io.trino.plugin.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:71)
	at io.trino.plugin.iceberg.HdfsInputFile.<init>(HdfsInputFile.java:44)
	at io.trino.plugin.iceberg.HdfsFileIo.newInputFile(HdfsFileIo.java:44)
	at io.trino.plugin.iceberg.delete.TrinoDeleteFilter.getInputFile(TrinoDeleteFilter.java:55)
	at org.apache.iceberg.data.DeleteFilter.openDeletes(DeleteFilter.java:242)
	at org.apache.iceberg.data.DeleteFilter.openPosDeletes(DeleteFilter.java:238)
	at org.apache.iceberg.relocated.com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:599)
	at org.apache.iceberg.relocated.com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:599)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.get(AbstractList.java:735)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.apache.iceberg.util.SortedMerge.iterator(SortedMerge.java:56)
	at org.apache.iceberg.deletes.Deletes$PositionStreamDeleteFilter.iterator(Deletes.java:169)
	at org.apache.iceberg.deletes.Deletes$PositionStreamDeleteFilter.iterator(Deletes.java:155)
	at org.apache.iceberg.util.Filter.lambda$filter$0(Filter.java:35)
	at org.apache.iceberg.io.CloseableIterable$2.iterator(CloseableIterable.java:73)
	at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:175)
	... 37 more```

**Comment by jotarada** [comment]
@homar 
The table is created based on select from a union between CTE's.
The source table does not contains any delete files.

```
CREATE TABLE sandbox.table AS SELECT * FROM (

WITH 
    template_7d AS (
        select
            'TEMPLATE' as aggregation_type,
            et.template_id as aggregation_id,
            '7 DAYS' as date_range,
            COUNT(DISTINCT et.user_id) as num_users,
            COUNT(DISTINCT et.message_id) as num_messages,
            COUNT(DISTINCT CASE WHEN et.delivered is not null THEN et.message_id END) as NUM_EVENT_1_MESSAGES
        from
        source.table et
        WHERE 1=1
            AND et.created_date BETWEEN timestamp '2022-05-23' - interval '7' day and timestamp '2022-05-23' 
        GROUP BY 1, 2, 3
      ),

      template_30d AS (
          select
            'TEMPLATE' as aggregation_type,
            et.template_id as aggregation_id,
            '30 DAYS' as date_range,
            COUNT(DISTINCT et.user_id) as num_users,
            COUNT(DISTINCT et.message_id) as num_messages,
            COUNT(DISTINCT CASE WHEN et.delivered is not null THEN et.message_id END) as NUM_EVENT_1_MESSAGES
        from
        source.table et
        WHERE 1=1
            AND et.created_date BETWEEN timestamp '2022-05-23' - interval '90' day and timestamp '2022-05-23' 
        GROUP BY 1, 2, 3
      )

      (SELECT current_date as last_update, a.* FROM template_7d a)
      UNION ALL
      (SELECT current_date as last_update, a.*  FROM template_30d a)
     )
```

**Comment by homar** [comment]
@jotarada  
you must have delete files as `at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:175)` wouldn't be called otherwise.
What version of trino do you use? Do you have any custom modifications? 
I did not manage to reproduce this using your query.

**Comment by jotarada** [comment]
I can't see delete files in $manifests details
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/35892383/176460344-6646dc0d-f99c-4485-a5ca-e2b429125fd5.png">

**Comment by homar** [comment]
ok did it here https://github.com/trinodb/trino/issues/13035

**Comment by jotarada** [comment]
Thanks for taking a look.

**Comment by lhofhansl** [comment]
I'm seeing the same with `alter table ... execute optimize`.

`Caused by:` is the same. Build from current master.

**Comment by findinpath** [comment]
@lhofhansl not that your scenario involves dealing with `optimize` and not `rollback_to_snapshot`.
I'm looking into the issue and creating a PR if it is reproducible.
