### ISSUE TITLE
Max requests queued per destination 1024 exceeded for HttpDestination

### ISSUE THREAD

**Issue by duhanmin** [trinodb/trino#12902]
2022-06-20 02:01:10.001 ERROR java.sql.SQLException: Query failed (#20220620_020054_00165_g7n7n): Max requests queued per destination 1024 exceeded for HttpDestination[http://*****:8889]@22b60219,queue=1024,pool=DuplexConnectionPool@f3a2566[c=3/250/250,a=247,i=0,q=1023]
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1912)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:219)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:179)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136)

**Comment by duhanmin** [comment]
Is the following scheme feasible?

https://github.com/prestodb/presto/issues/8005

**Comment by robinsinghstudios** [comment]
Facing the same issue. The document says you might experience this issue if you set the max stage count to a high value but I am using the default value of 100. The thread shared by @duhanmin seems to be the best possible solution but I don't see these properties on Trino. Any help on this will be appreciated.

**Comment by hashhar** [comment]
You can set those properties on Trino too, they aren't documented since in ideal situations a user never needs to change them.

**Comment by robinsinghstudios** [comment]
@hashhar I used all of these properties and it solved the issue. But I am not sure which one actually affects this issue. Can you help?

discovery.http-client.max-requests-queued-per-destination=2048
dynamic.http-client.max-requests-queued-per-destination=2048
failure-detector.http-client.max-requests-queued-per-destination=2048
memoryManager.http-client.max-requests-queued-per-destination=2048
node-manager.http-client.max-requests-queued-per-destination=2048
exchange.http-client.max-requests-queued-per-destination=2048
scheduler.http-client.max-requests-queued-per-destination=2048
workerInfo.http-client.max-requests-queued-per-destination=2048

**Comment by houhashv** [comment]
just to make sure, you've wrote this in the etc/config.properties of the coordinator?

**Comment by robinsinghstudios** [comment]
> just to make sure, you've wrote this in the etc/config.properties of the coordinator?

Yup

**Comment by hashhar** [comment]
Only `exchange` and `scheduler` are the relevant HTTP clients which might need these values increased. Others generally would not need changing.

**Comment by duhanmin** [comment]
> 只有`exchange`和`scheduler`是可能需要增加这些值的相关 HTTP 客户端。其他的一般不需要改变。

@houhashv 
catalog有4000个,修改到10240依然不够用

```
io.trino.spi.TrinoException: Max requests queued per destination 10240 exceeded for HttpDestination[Origin@756c45b3[http://10.160.40.179:9090,tag=null,protocol=Protocol@7f4624a[proto=[http/1.1],nego=false]]]@7e2f0d64,state=STARTED,queue=10240,pool=DuplexConnectionPool@3b2d8cc5[s=STARTED,c=0/250/250,a=250,i=0,q=10240,p=Pool@deff834[inUse=250,size=250,max=250,closed=false]],stale=false,idle=-1
	at io.trino.server.remotetask.RequestErrorTracker.requestFailed(RequestErrorTracker.java:105)
	at io.trino.server.remotetask.HttpRemoteTask$UpdateResponseHandler.failed(HttpRemoteTask.java:1178)
	at io.trino.server.remotetask.SimpleHttpResponseHandler.onFailure(SimpleHttpResponseHandler.java:85)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1127)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:79)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by airvine-r7** [comment]
@duhanmin Hey what properties have you set?
