### ISSUE TITLE
Iceberg product tests flaky with: Cannot create a table on a non-empty location

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#12908]

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/6962436517?check_suite_focus=true 
```
tests               | 2022-06-20 14:33:34 INFO: FAILURE     /    io.trino.tests.product.iceberg.TestIcebergHiveTablesCompatibility.testHiveSelectTableColumns (Groups: hms_only, storage_formats, iceberg) took 1.8 seconds
tests               | 2022-06-20 14:33:34 SEVERE: Failure cause:
tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20220620_084834_01176_pr9dv): Cannot create a table on a non-empty location: hdfs://hadoop-master:9000/user/hive/warehouse/test_iceberg_table_columns_table_ejb0qy7eyta8, set 'iceberg.unique-table-location=true' in your Iceberg catalog properties to use unique table locations for every table.
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:60)
tests               | 	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
tests               | 	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:62)
tests               | 	at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
tests               | 	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:67)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:60)
tests               | 	at io.trino.tests.product.iceberg.TestIcebergHiveTablesCompatibility.testHiveSelectTableColumns(TestIcebergHiveTablesCompatibility.java:105)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:829)
tests               | Caused by: java.sql.SQLException: Query failed (#20220620_084834_01176_pr9dv): Cannot create a table on a non-empty location: hdfs://hadoop-master:9000/user/hive/warehouse/test_iceberg_table_columns_table_ejb0qy7eyta8, set 'iceberg.unique-table-location=true' in your Iceberg catalog properties to use unique table locations for every table.
tests               | 	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
tests               | 	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:285)
tests               | 	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:61)
tests               | 	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
tests               | 	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 	... 22 more
tests               | 	Suppressed: java.lang.Exception: Query: CREATE TABLE iceberg.default.test_iceberg_table_columns_table_ejb0qy7eyta8(a bigint)
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
tests               | 		... 23 more
tests               | Caused by: io.trino.spi.TrinoException: Cannot create a table on a non-empty location: hdfs://hadoop-master:9000/user/hive/warehouse/test_iceberg_table_columns_table_ejb0qy7eyta8, set 'iceberg.unique-table-location=true' in your Iceberg catalog properties to use unique table locations for every table.
tests               | 	at io.trino.plugin.iceberg.IcebergMetadata.beginCreateTable(IcebergMetadata.java:632)
tests               | 	at io.trino.plugin.iceberg.IcebergMetadata.createTable(IcebergMetadata.java:604)
tests               | 	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.createTable(ClassLoaderSafeConnectorMetadata.java:382)
tests               | 	at io.trino.metadata.MetadataManager.createTable(MetadataManager.java:640)
tests               | 	at io.trino.execution.CreateTableTask.internalExecute(CreateTableTask.java:270)
tests               | 	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:119)
tests               | 	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:85)
tests               | 	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
tests               | 	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
tests               | 	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
tests               | 	at io.trino.$gen.Trino_386_26_gb4c70eb____20220620_083251_2.run(Unknown Source)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:829)
```
