### ISSUE TITLE
Flaky BaseIcebergConnectorTest.testLocalDynamicFilteringWithSelectiveBuildSideJoin

### ISSUE THREAD

**Issue by lukasz-stec** [trinodb/trino#12931]
https://github.com/trinodb/trino/runs/7000875572?check_suite_focus=true

```
Error:  Tests run: 1069, Failures: 1, Errors: 0, Skipped: 9, Time elapsed: 2,164.382 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.iceberg.TestIcebergOrcConnectorTest.testLocalDynamicFilteringWithSelectiveBuildSideJoin  Time elapsed: 4.275 s  <<< FAILURE!
java.lang.AssertionError: 
Expecting:
 <60175L>
to be less than:
 <60175L> 
	at io.trino.plugin.iceberg.BaseIcebergConnectorTest.testLocalDynamicFilteringWithSelectiveBuildSideJoin(BaseIcebergConnectorTest.java:3121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by hashhar** [comment]
See also https://github.com/trinodb/trino/issues/10932

**Comment by alexjo2144** [comment]
Was that a recent run against master? That's very sad, thought I had fixed it. Maybe we should remove this test and try a different approach

**Comment by hashhar** [comment]
@alexjo2144 I noticed that this failure was with ORC reader and earlier it used to fail with Parquet reader most often.

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/7293652341

**Comment by sopel39** [comment]
Another one https://github.com/trinodb/trino/runs/7250659239. @raunaqmorarka did DF code change recently in such a way that it could impact Iceberg?
