### ISSUE TITLE
Flaky testRepartitionDataOnCtas

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#12950]
```
Error:  Failures: 
Error:    TestIcebergOrcConnectorTest>BaseIcebergConnectorTest.testRepartitionDataOnCtas:3127->BaseIcebergConnectorTest.testRepartitionData:3213->AbstractTestQueryFramework.assertUpdate:323 » Runtime
Error:    TestIcebergParquetConnectorTest>BaseIcebergConnectorTest.testRepartitionDataOnCtas:3127->BaseIcebergConnectorTest.testRepartitionData:3213->AbstractTestQueryFramework.assertUpdate:323 » Runtime
```

```
Error:  io.trino.plugin.iceberg.TestIcebergParquetConnectorTest.testRepartitionDataOnCtas[Session{queryId=20220622_151323_00003_t9xzv, transactionId=Optional.empty, user=user, source=test, catalog=iceberg, schema=tpch, path=, timeZoneKey=Pacific/Apia, locale=en, remoteUserAddress=address, userAgent=agent, clientTags=[], clientCapabilities=[], resourceEstimates=ResourceEstimates{executionTime=Optional.empty, cpuTime=Optional.empty, peakMemoryBytes=Optional.empty}, start=2022-06-22T15:13:23.078154Z}, 'truncate(comment, 1)', 'orderstatus', 'bucket(comment, 2)', 180](5)  Time elapsed: 168.126 s  <<< FAILURE!
java.lang.RuntimeException: Error fetching next (attempts: 2, duration: 2.55m)
	at io.trino.client.StatementClientV1.advance(StatementClientV1.java:357)
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:98)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:526)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:323)
	at io.trino.plugin.iceberg.BaseIcebergConnectorTest.testRepartitionData(BaseIcebergConnectorTest.java:3213)
	at io.trino.plugin.iceberg.BaseIcebergConnectorTest.testRepartitionDataOnCtas(BaseIcebergConnectorTest.java:3127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE repartition_tpchtinyordersctas_truncatecomment1orderstatusbucketcomment2_x63qaw4i5z WITH (partitioning = ARRAY['truncate(comment, 1)', 'orderstatus', 'bucket(comment, 2)']) AS SELECT * FROM tpch.tiny.orders
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:529)
		... 17 more
Caused by: java.io.UncheckedIOException: java.net.SocketTimeoutException: timeout
	at io.trino.client.JsonResponse.execute(JsonResponse.java:166)
	at io.trino.client.StatementClientV1.advance(StatementClientV1.java:378)
	... 19 more
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:232)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at io.trino.client.JsonResponse.execute(JsonResponse.java:124)
	... 20 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 41 more
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/7047111799?check_suite_focus=true

**Comment by ebyhr** [comment]
Probably, there're two issues, "timeout" & "Exceeded limit of 100 open writers for partitions". Either way, Major GC seems happened around the failure.
