### ISSUE TITLE
Reading Iceberg table with delete files sometimes fail due to invalid class loader

### ISSUE THREAD

**Issue by homar** [trinodb/trino#13035]
```
        at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:198)
	at io.trino.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:392)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:182)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$7(WorkProcessorUtils.java:296)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$3(WorkProcessorUtils.java:219)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$4(WorkProcessorUtils.java:234)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:150)
	at io.trino.operator.Driver.processInternal(Driver.java:410)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_386____20220620_155807_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: During instantiation, the Configuration object captures the TCCL and uses it to resolve classes by name. For this reason, the current TCCL jdk.internal.loader.ClassLoaders$AppClassLoader@21588809 should be same as this class's classloader io.trino.server.PluginClassLoader@d424f08. Otherwise the constructed Configuration will use *some* classloader to resolve classes
	at com.google.common.base.Preconditions.checkState(Preconditions.java:821)
	at io.trino.hadoop.ConfigurationInstantiator.newConfiguration(ConfigurationInstantiator.java:43)
	at io.trino.hadoop.ConfigurationInstantiator.newEmptyConfiguration(ConfigurationInstantiator.java:27)
	at io.trino.plugin.hive.HiveHdfsConfiguration$1.initialValue(HiveHdfsConfiguration.java:41)
	at io.trino.plugin.hive.HiveHdfsConfiguration$1.initialValue(HiveHdfsConfiguration.java:37)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at io.trino.plugin.hive.HiveHdfsConfiguration.getConfiguration(HiveHdfsConfiguration.java:63)
	at io.trino.plugin.hive.HdfsEnvironment.getConfiguration(HdfsEnvironment.java:65)
	at io.trino.plugin.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:71)
	at io.trino.plugin.iceberg.HdfsInputFile.<init>(HdfsInputFile.java:44)
	at io.trino.plugin.iceberg.HdfsFileIo.newInputFile(HdfsFileIo.java:44)
	at io.trino.plugin.iceberg.delete.TrinoDeleteFilter.getInputFile(TrinoDeleteFilter.java:55)
	at org.apache.iceberg.data.DeleteFilter.openDeletes(DeleteFilter.java:242)
	at org.apache.iceberg.data.DeleteFilter.openPosDeletes(DeleteFilter.java:238)
	at org.apache.iceberg.relocated.com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:599)
	at org.apache.iceberg.relocated.com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:599)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.get(AbstractList.java:735)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.apache.iceberg.util.SortedMerge.iterator(SortedMerge.java:56)
	at org.apache.iceberg.deletes.Deletes$PositionStreamDeleteFilter.iterator(Deletes.java:169)
	at org.apache.iceberg.deletes.Deletes$PositionStreamDeleteFilter.iterator(Deletes.java:155)
	at org.apache.iceberg.util.Filter.lambda$filter$0(Filter.java:35)
	at org.apache.iceberg.io.CloseableIterable$2.iterator(CloseableIterable.java:73)
	at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:175)
	... 37 more```
```

**Comment by findinpath** [comment]
I've tried to test the code on this branch and ran into the following problem:

```
trino:default> create table iceberg.default.lineitem as select * from tpch.sf1.lineitem;
CREATE TABLE: 6001215 rows

Query 20220704_104259_00001_p7usw, FINISHED, 1 node
Splits: 22 total, 22 done (100.00%)
31.61 [6M rows, 0B] [190K rows/s, 0B/s]

trino:default> delete from iceberg.default.lineitem where extendedprice = 1000;

Query 20220704_104337_00002_p7usw, FAILED, 1 node
Splits: 11 total, 0 done (0.00%)
1.55 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20220704_104337_00002_p7usw failed: UpdatablePageSource not set
```
