### ISSUE TITLE
ALTER TABLE iceberg.table EXECUTE OPTIMIZE fails on HDFS

### ISSUE THREAD

**Issue by lhofhansl** [trinodb/trino#13071]
```
> create table iceberg.default.lineitem as select * from tpch.sf1.lineitem;
...
> delete from iceberg.default.lineitem where extendedprice = 1000;
...
> alter table iceberg.default.lineitem execute optimize;
...

Query 20220703_170119_00012_tzunu failed: During instantiation, the Configuration object captures the TCCL and uses it to resolve classes by name. For this reason, the current TCCL jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc should be same as this class's classloader PluginClassLoader{pluginName=iceberg, catalogName=iceberg, identityHash=@5f96ea5}. Otherwise the constructed Configuration will use *some* classloader to resolve classes
io.trino.spi.TrinoException: During instantiation, the Configuration object captures the TCCL and uses it to resolve classes by name. For this reason, the current TCCL jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc should be same as this class's classloader PluginClassLoader{pluginName=iceberg, catalogName=iceberg, identityHash=@5f96ea5}. Otherwise the constructed Configuration will use *some* classloader to resolve classes
at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:198)
at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
at io.trino.operator.Driver.processInternal(Driver.java:410)
at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
at io.trino.operator.Driver.tryWithLock(Driver.java:698)
at io.trino.operator.Driver.process(Driver.java:305)
at io.trino.operator.Driver.processForDuration(Driver.java:276)
at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:740)
at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
at io.trino.$gen.Trino_351_6050_g89a9247____20220703_162025_2.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: During instantiation, the Configuration object captures the TCCL and uses it to resolve classes by name. For this reason, the current TCCL jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc should be same as this class's classloader PluginClassLoader{pluginName=iceberg, catalogName=iceberg, identityHash=@5f96ea5}. Otherwise the constructed Configuration will use *some* classloader to resolve classes
at com.google.common.base.Preconditions.checkState(Preconditions.java:821)
at io.trino.hadoop.ConfigurationInstantiator.newConfiguration(ConfigurationInstantiator.java:43)
at io.trino.hadoop.ConfigurationInstantiator.newEmptyConfiguration(ConfigurationInstantiator.java:27)
at io.trino.plugin.hive.HiveHdfsConfiguration$1.initialValue(HiveHdfsConfiguration.java:41)
at io.trino.plugin.hive.HiveHdfsConfiguration$1.initialValue(HiveHdfsConfiguration.java:37)
at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
at io.trino.plugin.hive.HiveHdfsConfiguration.getConfiguration(HiveHdfsConfiguration.java:63)
at io.trino.plugin.hive.HdfsEnvironment.getConfiguration(HdfsEnvironment.java:65)
at io.trino.plugin.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:71)
at io.trino.plugin.iceberg.HdfsInputFile.<init>(HdfsInputFile.java:44)
at io.trino.plugin.iceberg.HdfsFileIo.newInputFile(HdfsFileIo.java:44)
at io.trino.plugin.iceberg.delete.TrinoDeleteFilter.getInputFile(TrinoDeleteFilter.java:55)
at org.apache.iceberg.data.DeleteFilter.openDeletes(DeleteFilter.java:242)
at org.apache.iceberg.data.DeleteFilter.openPosDeletes(DeleteFilter.java:238)
at org.apache.iceberg.relocated.com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:612)
at org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
at org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
at org.apache.iceberg.io.CloseableIterable$ConcatCloseableIterable$ConcatCloseableIterator.<init>(CloseableIterable.java:151)
at org.apache.iceberg.io.CloseableIterable$ConcatCloseableIterable$ConcatCloseableIterator.<init>(CloseableIterable.java:143)
at org.apache.iceberg.io.CloseableIterable$ConcatCloseableIterable.iterator(CloseableIterable.java:138)
at org.apache.iceberg.io.CloseableIterable$ConcatCloseableIterable.iterator(CloseableIterable.java:129)
at java.base/java.lang.Iterable.forEach(Iterable.java:74)
at org.apache.iceberg.deletes.Deletes.toPositionIndex(Deletes.java:97)
at org.apache.iceberg.deletes.Deletes.toPositionIndex(Deletes.java:91)
at org.apache.iceberg.data.DeleteFilter.applyPosDeletes(DeleteFilter.java:231)
at org.apache.iceberg.data.DeleteFilter.filter(DeleteFilter.java:126)
at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:173)
... 13 more
```

**Comment by lhofhansl** [comment]
See also #12887

**Comment by findepi** [comment]
Duplicates https://github.com/trinodb/trino/issues/13035
