### ISSUE TITLE
Support writing time and timestamp columns in JDBC connectors

### ISSUE THREAD

**Issue by pgagnon** [trinodb/trino#1307]
`CTAS` and `INSERT` queries involving `timestamp` and `time` typed columns currently fail in JDBC-based connectors. It looks like these types are missing in the write type mapping.

```
io.prestosql.spi.PrestoException: Unsupported column type: timestamp
	at io.prestosql.plugin.jdbc.BaseJdbcClient.toWriteMapping(BaseJdbcClient.java:725)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.getColumnSql(BaseJdbcClient.java:392)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.createTable(BaseJdbcClient.java:368)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.beginWriteTable(BaseJdbcClient.java:331)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.beginCreateTable(BaseJdbcClient.java:319)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$beginCreateTable$16(StatisticsAwareJdbcClient.java:174)
	at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.beginCreateTable(StatisticsAwareJdbcClient.java:174)
	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.beginCreateTable(ForwardingJdbcClient.java:110)
	at io.prestosql.plugin.jdbc.JdbcMetadata.beginCreateTable(JdbcMetadata.java:211)
	at io.prestosql.metadata.MetadataManager.beginCreateTable(MetadataManager.java:750)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:179)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:142)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:76)
	at io.prestosql.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4745)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4753)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at io.prestosql.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.prestosql.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:73)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:173)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:162)
	at io.prestosql.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:381)
	at io.prestosql.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:366)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:316)
	at io.prestosql.$gen.Presto_317____20190815_141438_1.run(Unknown Source)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:239)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$4(LocalDispatchQuery.java:105)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ebyhr** [comment]
Closing as #1313

**Comment by hashhar** [comment]
Closed since timestamp/time mappings now exist in `StandardColumnMappings` and most JDBC based connectors now support them (with exception of a few like Druid).
