### ISSUE TITLE
Cannot insert into Iceberg Parquet table having column identifier with quotes

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#13074]
```
trino:default> create table test21 ("an identifier with ""quotes"" " integer, a row ("another identier" int));
CREATE TABLE
trino:default> insert into test21 values (1, row(11));

Query 20220704_060511_00036_58g78, FAILED, 1 node
Splits: 19 total, 1 done (5.26%)
0.30 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20220704_060511_00036_58g78 failed: Trino type is null
```

```
presto-master       | java.lang.NullPointerException: Trino type is null
presto-master       | 	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
presto-master       | 	at io.trino.parquet.writer.ParquetWriters$WriteBuilder.primitive(ParquetWriters.java:168)
presto-master       | 	at io.trino.parquet.writer.ParquetWriters$WriteBuilder.primitive(ParquetWriters.java:99)
presto-master       | 	at io.trino.parquet.writer.ParquetTypeVisitor.visit(ParquetTypeVisitor.java:42)
presto-master       | 	at io.trino.parquet.writer.ParquetTypeVisitor.visitField(ParquetTypeVisitor.java:118)
presto-master       | 	at io.trino.parquet.writer.ParquetTypeVisitor.visitFields(ParquetTypeVisitor.java:129)
presto-master       | 	at io.trino.parquet.writer.ParquetTypeVisitor.visit(ParquetTypeVisitor.java:110)
presto-master       | 	at io.trino.parquet.writer.ParquetTypeVisitor.visitField(ParquetTypeVisitor.java:118)
presto-master       | 	at io.trino.parquet.writer.ParquetTypeVisitor.visitFields(ParquetTypeVisitor.java:129)
presto-master       | 	at io.trino.parquet.writer.ParquetTypeVisitor.visit(ParquetTypeVisitor.java:39)
presto-master       | 	at io.trino.parquet.writer.ParquetWriters.getColumnWriters(ParquetWriters.java:95)
presto-master       | 	at io.trino.parquet.writer.ParquetWriter.initColumnWriters(ParquetWriter.java:308)
presto-master       | 	at io.trino.parquet.writer.ParquetWriter.<init>(ParquetWriter.java:100)
presto-master       | 	at io.trino.plugin.hive.parquet.ParquetFileWriter.<init>(ParquetFileWriter.java:69)
presto-master       | 	at io.trino.plugin.iceberg.IcebergParquetFileWriter.<init>(IcebergParquetFileWriter.java:60)
presto-master       | 	at io.trino.plugin.iceberg.IcebergFileWriterFactory.createParquetWriter(IcebergFileWriterFactory.java:201)
presto-master       | 	at io.trino.plugin.iceberg.IcebergFileWriterFactory.createDataFileWriter(IcebergFileWriterFactory.java:136)
presto-master       | 	at io.trino.plugin.iceberg.IcebergPageSink.createWriter(IcebergPageSink.java:342)
presto-master       | 	at io.trino.plugin.iceberg.IcebergPageSink.getWriterIndexes(IcebergPageSink.java:299)
presto-master       | 	at io.trino.plugin.iceberg.IcebergPageSink.writePage(IcebergPageSink.java:225)
presto-master       | 	at io.trino.plugin.iceberg.IcebergPageSink.doAppend(IcebergPageSink.java:220)
presto-master       | 	at io.trino.plugin.iceberg.IcebergPageSink.lambda$appendPage$0(IcebergPageSink.java:168)
presto-master       | 	at io.trino.plugin.hive.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:26)
presto-master       | 	at io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
presto-master       | 	at io.trino.plugin.hive.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:25)
presto-master       | 	at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:102)
presto-master       | 	at io.trino.plugin.iceberg.IcebergPageSink.appendPage(IcebergPageSink.java:168)
presto-master       | 	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:69)
presto-master       | 	at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:270)
presto-master       | 	at io.trino.operator.Driver.processInternal(Driver.java:415)
presto-master       | 	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
presto-master       | 	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
presto-master       | 	at io.trino.operator.Driver.process(Driver.java:305)
presto-master       | 	at io.trino.operator.Driver.processForDuration(Driver.java:276)
presto-master       | 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:740)
presto-master       | 	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
presto-master       | 	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
presto-master       | 	at io.trino.$gen.Trino_387_105_g90f1fb7____20220704_050437_2.run(Unknown Source)
presto-master       | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
presto-master       | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
presto-master       | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

Trino version:

```
trino:default> select node_version from system.runtime.nodes;
   node_version   
------------------
 387-105-g90f1fb7 
(1 row)

```

**Comment by homar** [comment]
Cannot reproduce, seems to work now.
