### ISSUE TITLE
not able to query presto after adding performance tuning parameters

### ISSUE THREAD

**Issue by rajathc93** [trinodb/trino#13144]
Hi Team, 

I'm getting below errors after enabling the performance tuning parameters, 
Performance tuning parameters used, 
optimizer.join-reordering-strategy=AUTOMATIC
optimizer.join_distribution_type=AUTOMATIC
experimental.enable-dynamic-filtering=TRUE

I'm using amazon emr,
presto version: Presto CLI 0.267-amzn-1

I'm adding these parameters,
/etc/presto/conf/config.properties

`2022-07-11T11:02:36.728Z	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Configuration property 'optimizer.join_distribution_type' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'optimizer.join_distribution_type' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:251)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:143)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:85)

2022-07-11T11:02:42.674Z	INFO	main	com.facebook.airlift.log.Logging	Disabling stderr output`

Any idea how to fix this issue?

**Comment by raunaqmorarka** [comment]
You probably need to use dashes instead of underscores in `optimizer.join_distribution_type`.
Please note that you are using https://github.com/prestodb/presto and this board is for issues related to https://github.com/trinodb/trino
EMR versions 6.4.0 and later should have the option to use Trino instead of Presto as well.
