### ISSUE TITLE
OAUTH2 issues

### ISSUE THREAD

**Issue by eadapa29** [trinodb/trino#13148]
Hello,
   I am trying to enable OAUTH2 login for trino container using the following updates to config.properties

#single node install config
coordinator=true
node-scheduler.include-coordinator=true
http-server.https.port=8443
http-server.https.enabled=true
#discovery-server.enabled=true
discovery.uri=http://localhost:8080
http-server.https.keystore.path=/etc/trino/certs/xx.pem
internal-communication.https.required=false
http-server.authentication.type=oauth2
http-server.authentication.allow-insecure-over-http=true
http-server.authentication.oauth2.issuer=https://<OKTA HOST>/oauth2/ausce7f2wukjHDlvu297
http-server.authentication.oauth2.auth-url=https://<OKTA HOST>/oauth2/ausce7f2wukjHDlvu297/v1/authorize
http-server.authentication.oauth2.token-url=https://<OKTA HOST>/oauth2/ausce7f2wukjHDlvu297/v1/token
http-server.authentication.oauth2.jwks-url=https://<OKTA HOST>/oauth2/ausce7f2wukjHDlvu297/.well-known/oauth-authorization-server
http-server.authentication.oauth2.client-id=xxxxx
http-server.authentication.oauth2.client-secret=xxxxx
web-ui.authentication.type=oauth2

During the launch i get the following Warnings

2022-07-12T07:40:20.469Z        WARN    query-management-2      io.trino.memory.RemoteNodeMemory        Memory info update request to http://100.85.60.121:8080/v1/memory has not returned in 2919769.08s
2022-07-12T07:40:22.470Z        WARN    query-management-4      io.trino.memory.RemoteNodeMemory        Memory info update request to http://100.85.60.121:8080/v1/memory has not returned in 2919771.08s
2022-07-12T07:40:23.305Z        WARN    node-state-poller-0     io.trino.metadata.RemoteNodeState       Node state update request to http://100.85.60.121:8080/v1/info/state has not returned in 2919771.92s
2022-07-12T07:40:24.471Z        WARN    query-management-0      io.trino.memory.RemoteNodeMemory        Memory info update request to http://100.85.60.121:8080/v1/memory has not returned in 2919773.08s
2022-07-12T07:40:26.472Z        WARN    query-management-3      io.trino.memory.RemoteNodeMemory        Memory info update request to http://100.85.60.121:8080/v1/memory has not returned in 2919775.08s
2022-07-12T07:40:28.306Z        WARN    node-state-poller-0     io.trino.metadata.RemoteNodeState       Node state update request to http://100.85.60.121:8080/v1/info/state has not returned in 2919776.92s
2022-07-12T07:40:28.315Z        WARN    http-client-node-manager-scheduler-1    io.trino.metadata.RemoteNodeState       Error fetching node state from http://100.85.60.121:8080/v1/info/state: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
2022-07-12T07:40:28.500Z        WARN    query-management-4      io.trino.memory.RemoteNodeMemory        Memory info update request to http://100.85.60.121:8080/v1/memory has not returned in 2919777.11s

**And also  a communication error that it cannot connect to the <OKTA HOST>** 
Caused by: UncheckedIOException: Failed communicating with server: https://<OKTA HOST>/oauth2/ausce7f2wukjHDlvu297/.well-known/oauth-authorization-server
        at ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:22)
        at StringResponseHandler.handleException(StringResponseHandler.java:51)
        at StringResponseHandler.handleException(StringResponseHandler.java:34)
        at JettyHttpClient.execute(JettyHttpClient.java:599)
        at JwkService.fetchKeys(JwkService.java:137)
        ... 182 more
Caused by: SocketTimeoutException: Connect Timeout

From wherever i am launching the trino I am able to connect to the OKTA host without any issues via proxy.
For trino launch is there a way to connect to external URLs via proxy  ?  because the trino launch command  is not recognizing the HTTP_PROXY parameters that i have set

**Comment by eadapa29** [comment]
Thank you very much... Let me try that option and will let you know

**Comment by eadapa29** [comment]
Attached is the stack trace
[Uploading trino_oauth2_error_log.txt…]()
