### ISSUE TITLE
Slow EXPLAIN with Iceberg connector

### ISSUE THREAD

**Issue by vincentpoon** [trinodb/trino#13158]
On a fairly large table with many partitions/manifests/files, seeing very slow EXPLAIN execution of >30m versus actual query execution of ~15s.

It seems this is due to the [code](https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsMaker.java#L109) in `TableStatisticsMaker` which needs to loop over all physical manifests to collect stats for each data file.
Here is a snippet of stack trace where we're seeing a lot of time spent:

```
  at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:454)
  at org.apache.iceberg.hadoop.HadoopInputFile.lazyStat(HadoopInputFile.java:156)
  at org.apache.iceberg.hadoop.HadoopInputFile.getLength(HadoopInputFile.java:167)
  at io.trino.plugin.iceberg.HdfsInputFile$$Lambda$13102/0x00007eee441dccb0.run(:-1)
  at io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
  at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:97)
  at io.trino.plugin.iceberg.HdfsInputFile.getLength(HdfsInputFile.java:55)
  at org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:101)
  at org.apache.iceberg.avro.AvroIterable.getMetadata(AvroIterable.java:66)
  at org.apache.iceberg.ManifestReader.<init>(ManifestReader.java:104)
  at org.apache.iceberg.ManifestFiles.read(ManifestFiles.java:87)
  at org.apache.iceberg.ManifestGroup.lambda$entries$15(ManifestGroup.java:245)
  at org.apache.iceberg.ManifestGroup$$Lambda$13131/0x00007eee443d0120.apply(:-1)
  at org.apache.iceberg.relocated.com.google.common.collect.Iterators$6.transform(Iterators.java:783)
  at org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
  at org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
  at org.apache.iceberg.util.ParallelIterable$ParallelIterator.submitNextTask(ParallelIterable.java:131)
  at org.apache.iceberg.util.ParallelIterable$ParallelIterator.checkTasks(ParallelIterable.java:118)
  at org.apache.iceberg.util.ParallelIterable$ParallelIterator.hasNext(ParallelIterable.java:155)
  at java.lang.Iterable.forEach(Iterable.java:74)
  at io.trino.plugin.iceberg.TableStatisticsMaker.makeTableStatistics(TableStatisticsMaker.java:109)
  at io.trino.plugin.iceberg.TableStatisticsMaker.getTableStatistics(TableStatisticsMaker.java:60)
  at io.trino.plugin.iceberg.IcebergMetadata.getTableStatistics(IcebergMetadata.java:1846)
```

**Comment by raunaqmorarka** [comment]
cc: @alexjo2144

**Comment by vincentpoon** [comment]
It looks like perhaps the issue is related to the Iceberg Worker Threadpool not getting fully utilized.
I can see that most threads are generally sitting idle while the query is hanging.
Meanwhile the main query thread is apparently itself reading manifest files, as seen in the stack trace above.
Hard to tell from the `ParallelIterable` used what is actually parallelized and what is not.

**Comment by vincentpoon** [comment]
Looks like this is fixed by https://github.com/apache/iceberg/pull/5206 (yet to be released)
