### ISSUE TITLE
Flaky TestHiveTransactionalTable.testAcidUpdateWithSubqueryPredicate

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#13162]
https://github.com/trinodb/trino/runs/7317409065
```
tests               | 2022-07-13 14:54:12 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveTransactionalTable.testAcidUpdateWithSubqueryPredicate (Groups: hive_transactional) took 3.4 seconds
tests               | 2022-07-13 14:54:12 SEVERE: Failure cause:
tests               | java.lang.AssertionError: [onTrino] Expected row count to be <2>, but was <3>; rows=[[2, y], [1, row updated], [2, y]]
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.verifySelect(TestHiveTransactionalTable.java:2225)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.verifySelectForTrinoAndHive(TestHiveTransactionalTable.java:2215)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.lambda$testAcidUpdateWithSubqueryPredicate$70(TestHiveTransactionalTable.java:1496)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.withTemporaryTable(TestHiveTransactionalTable.java:1808)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.testAcidUpdateWithSubqueryPredicate(TestHiveTransactionalTable.java:1489)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
tests               | 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

This might be related to #11893

**Comment by findepi** [comment]
Merging this issue into https://github.com/trinodb/trino/issues/14519
