### ISSUE TITLE
Flaky TestDeltaLakeDatabricksConnectorTest.testAddColumnConcurrently

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#13166]
```
Error:  io.trino.plugin.deltalake.TestDeltaLakeDatabricksConnectorTest.testAddColumnConcurrently
Error:    Run 1: TestDeltaLakeDatabricksConnectorTest>BaseConnectorTest.lambda$testAddColumnConcurrently$31:3189->BaseDeltaLakeMinioConnectorTest.verifyConcurrentAddColumnFailurePermissible:156 
Expecting message:
  <"Internal error while writing s3://databricks-test-queries/test_schema/test_add_column4lt6oobzdz/_delta_log/00000000000000000002.json">
to match regex:
  <"Transaction log locked.*|.*/_delta_log/\d+.json already exists|Conflicting concurrent writes found..*|Multiple live locks found for:.*|Target file .* was created during locking">
but did not.
Throwable that failed the check:
java.io.UncheckedIOException: Internal error while writing s3://databricks-test-queries/test_schema/test_add_column4lt6oobzdz/_delta_log/00000000000000000002.json
	at io.trino.plugin.deltalake.transactionlog.writer.S3TransactionLogSynchronizer.write(S3TransactionLogSynchronizer.java:144)
	at io.trino.plugin.deltalake.transactionlog.writer.TransactionLogWriter.flush(TransactionLogWriter.java:104)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.addColumn(DeltaLakeMetadata.java:1092)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.addColumn(ClassLoaderSafeConnectorMetadata.java:334)
	at io.trino.metadata.MetadataManager.addColumn(MetadataManager.java:707)
	at io.trino.execution.AddColumnTask.execute(AddColumnTask.java:136)
	at io.trino.execution.AddColumnTask.execute(AddColumnTask.java:55)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20220713_125253_4610.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 170164C0347881FA; S3 Extended Request ID: f4ae1f01-dda5-463a-8cfa-0719ac713113; Proxy: null), S3 Extended Request ID: f4ae1f01-dda5-463a-8cfa-0719ac713113
	at io.trino.plugin.hive.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.flushBuffer(TrinoS3FileSystem.java:1659)
	at io.trino.plugin.hive.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.close(TrinoS3FileSystem.java:1622)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:101)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:101)
	at io.trino.plugin.deltalake.transactionlog.writer.S3TransactionLogSynchronizer.writeNewLockInfo(S3TransactionLogSynchronizer.java:179)
	at io.trino.plugin.deltalake.transactionlog.writer.S3TransactionLogSynchronizer.write(S3TransactionLogSynchronizer.java:117)
	... 13 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 170164C0347881FA; S3 Extended Request ID: f4ae1f01-dda5-463a-8cfa-0719ac713113; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1862)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1415)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1384)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5453)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5400)
	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:421)
	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6528)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1861)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1821)
	at io.trino.plugin.hive.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.flushBuffer(TrinoS3FileSystem.java:1654)
	... 20 more
```
https://github.com/trinodb/trino/runs/7320969889

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/7776189140?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/3218319569/jobs/5262761388

```
Error:  io.trino.plugin.deltalake.TestDeltaLakeOssDeltaLakeConnectorTest.testInsertRowConcurrently  Time elapsed: 1.434 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting message:
  <"Internal error while writing s3://ossdeltalake-test-queries/test_schema/test_insert143rxoa8g3-ac3841dfa8304d14999306ce079730d8/_delta_log/00000000000000000001.json">
to match regex:
  <"Transaction log locked.*|.*/_delta_log/\d+.json already exists|Conflicting concurrent writes found..*|Multiple live locks found for:.*|Target file .* was created during locking">
but did not.

Throwable that failed the check:

java.io.UncheckedIOException: Internal error while writing s3://ossdeltalake-test-queries/test_schema/test_insert143rxoa8g3-ac3841dfa8304d14999306ce079730d8/_delta_log/00000000000000000001.json
	at io.trino.plugin.deltalake.transactionlog.writer.S3TransactionLogSynchronizer.write(S3TransactionLogSynchronizer.java:144)
	at io.trino.plugin.deltalake.transactionlog.writer.TransactionLogWriter.flush(TransactionLogWriter.java:104)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.finishInsert(DeltaLakeMetadata.java:1362)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishInsert(ClassLoaderSafeConnectorMetadata.java:502)
	at io.trino.metadata.MetadataManager.finishInsert(MetadataManager.java:888)
	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$4(LocalExecutionPlanner.java:4031)
	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:736)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:515)
	at io.trino.$gen.Trino_testversion____20221010_113657_142.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 171CB29DB8DC5343; S3 Extended Request ID: 615d891e-beaf-4c09-90eb-a3fb802e7cda; Proxy: null), S3 Extended Request ID: 615d891e-beaf-4c09-90eb-a3fb802e7cda
	at io.trino.plugin.hive.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.flushBuffer(TrinoS3FileSystem.java:1709)
	at io.trino.plugin.hive.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.close(TrinoS3FileSystem.java:1656)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:101)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:101)
	at io.trino.plugin.deltalake.transactionlog.writer.S3TransactionLogSynchronizer.writeNewLockInfo(S3TransactionLogSynchronizer.java:170)
	at io.trino.plugin.deltalake.transactionlog.writer.S3TransactionLogSynchronizer.write(S3TransactionLogSynchronizer.java:117)
	... 18 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 171CB29DB8DC5343; S3 Extended Request ID: 615d891e-beaf-4c09-90eb-a3fb802e7cda; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1862)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1415)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1384)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5453)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5400)
	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:421)
	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6528)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1861)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1821)
	at io.trino.plugin.hive.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.flushBuffer(TrinoS3FileSystem.java:1704)
	... 25 more

	at io.trino.plugin.deltalake.BaseDeltaLakeMinioConnectorTest.verifyConcurrentInsertFailurePermissible(BaseDeltaLakeMinioConnectorTest.java:155)
	at io.trino.testing.BaseConnectorTest.lambda$testInsertRowConcurrently$43(BaseConnectorTest.java:3486)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: io.trino.testing.QueryFailedException: Failed to write Delta Lake transaction log entry
		at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:123)
		at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:86)
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:468)
		at io.trino.testing.BaseConnectorTest.lambda$testInsertRowConcurrently$43(BaseConnectorTest.java:3480)
		... 4 more
	Caused by: io.trino.spi.TrinoException: Failed to write Delta Lake transaction log entry
		at io.trino.plugin.deltalake.DeltaLakeMetadata.finishInsert(DeltaLakeMetadata.java:1371)
		at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishInsert(ClassLoaderSafeConnectorMetadata.java:502)
		at io.trino.metadata.MetadataManager.finishInsert(MetadataManager.java:888)
		at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$4(LocalExecutionPlanner.java:4031)
		at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
		at io.trino.operator.Driver.processInternal(Driver.java:411)
		at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
		at io.trino.operator.Driver.tryWithLock(Driver.java:706)
		at io.trino.operator.Driver.process(Driver.java:306)
		at io.trino.operator.Driver.processForDuration(Driver.java:277)
		at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:736)
		at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
		at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:515)
		at io.trino.$gen.Trino_testversion____20221010_113657_142.run(Unknown Source)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)
	Caused by: java.io.UncheckedIOException: Internal error while writing s3://ossdeltalake-test-queries/test_schema/test_insert143rxoa8g3-ac3841dfa8304d14999306ce079730d8/_delta_log/00000000000000000001.json
		at io.trino.plugin.deltalake.transactionlog.writer.S3TransactionLogSynchronizer.write(S3TransactionLogSynchronizer.java:144)
		at io.trino.plugin.deltalake.transactionlog.writer.TransactionLogWriter.flush(TransactionLogWriter.java:104)
		at io.trino.plugin.deltalake.DeltaLakeMetadata.finishInsert(DeltaLakeMetadata.java:1362)
		... 16 more
	Caused by: java.io.IOException: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 171CB29DB8DC5343; S3 Extended Request ID: 615d891e-beaf-4c09-90eb-a3fb802e7cda; Proxy: null), S3 Extended Request ID: 615d891e-beaf-4c09-90eb-a3fb802e7cda
		at io.trino.plugin.hive.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.flushBuffer(TrinoS3FileSystem.java:1709)
		at io.trino.plugin.hive.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.close(TrinoS3FileSystem.java:1656)
		at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
		at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:101)
		at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
		at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:101)
		at io.trino.plugin.deltalake.transactionlog.writer.S3TransactionLogSynchronizer.writeNewLockInfo(S3TransactionLogSynchronizer.java:170)
		at io.trino.plugin.deltalake.transactionlog.writer.S3TransactionLogSynchronizer.write(S3TransactionLogSynchronizer.java:117)
		... 18 more
	Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 171CB29DB8DC5343; S3 Extended Request ID: 615d891e-beaf-4c09-90eb-a3fb802e7cda; Proxy: null)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1862)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1415)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1384)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
		at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
		at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
		at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5453)
		at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5400)
		at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:421)
		at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6528)
		at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1861)
		at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1821)
		at io.trino.plugin.hive.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.flushBuffer(TrinoS3FileSystem.java:1704)
		... 25 more
```

**Comment by findepi** [comment]
@linzebing @arhimondr 
do you happen to know under what conditions the S3 / MinIO would throw "The specified key does not exist" when writing to a file?

in the last stacktrace above the failure occurred here
https://github.com/trinodb/trino/blob/14f61898fa50411af7943578b2651fc2d1d6a7ff/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3TransactionLogSynchronizer.java#L162-L169
i.e. when writing to `new Path(lockDirectory, logEntryFilename + "." + LOCK_INFIX + queryId)`, so this should be unique and not pre-existing.

cc @findinpath @homar

**Comment by linzebing** [comment]
I have never encountered this error with S3 or MinIO

**Comment by ebyhr** [comment]
```
Error:  io.trino.plugin.deltalake.TestDeltaLakeOssDeltaLakeConnectorTest.testInsertRowConcurrently
[INFO]   Run 1: PASS
[INFO]   Run 2: PASS
Error:    Run 3: TestDeltaLakeOssDeltaLakeConnectorTest>BaseConnectorTest.lambda$testInsertRowConcurrently$50:3924->BaseDeltaLakeMinioConnectorTest.verifyConcurrentInsertFailurePermissible:156 
Expecting message:
  <"Internal error while writing s3://ossdeltalake-test-queries/test_schema/test_insert1k5lfv6k62-f77712cece7e4b288656faab37e9fe2c/_delta_log/00000000000000000001.json">
to match regex:
  <"Transaction log locked.*|.*/_delta_log/\d+.json already exists|Conflicting concurrent writes found..*|Multiple live locks found for:.*|Target file .* was created during locking">
but did not.
```

https://github.com/trinodb/trino/actions/runs/4161013002/jobs/7199037446

**Comment by vscfreire** [comment]
I'm also encountering this problem, when performing DELETE tasks (two or more) at the same time or very close to one another.

If I perform the two DELETEs exactly at the same time, both fail with `Query XXX failed: Failed to write Delta Lake transaction log entry`. If I perform both in quick succession, only the second one fails. Immediately afterwards, I can perform the second one successfully.

This also happens with several DELETE operations in quick succession, only the first one completes, the remaining fail.

The error type is `EXTERNAL` and the error code `DELTA_LAKE_BAD_WRITE (84279299)`.

The stack trace, obtained from the web console, is: 
```
io.trino.spi.TrinoException: Failed to write Delta Lake transaction log entry
	at io.trino.plugin.deltalake.DeltaLakeMetadata.finishWrite(DeltaLakeMetadata.java:1967)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.finishDelete(DeltaLakeMetadata.java:1424)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishDelete(ClassLoaderSafeConnectorMetadata.java:652)
	at io.trino.metadata.MetadataManager.finishDelete(MetadataManager.java:1042)
	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$4(LocalExecutionPlanner.java:4062)
	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:739)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:519)
	at io.trino.$gen.Trino_403____20230210_115917_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.trino.plugin.deltalake.transactionlog.writer.TransactionConflictException: Transaction log locked(2); lockingCluster=trino-403-1039ffbb-daf8-48b0-b9a4-326c125f1706; lockingQuery=20230213_153942_00052_5yrxi; expires=2023-02-13T15:44:42.742Z
	at io.trino.plugin.deltalake.transactionlog.writer.S3TransactionLogSynchronizer.write(S3TransactionLogSynchronizer.java:128)
	at io.trino.plugin.deltalake.transactionlog.writer.TransactionLogWriter.flush(TransactionLogWriter.java:104)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.finishWrite(DeltaLakeMetadata.java:1958)
	... 17 more
```

I can provide more extensive data related to the error, if needed.

Using delta tables stored on MinIO, accessed using `s3a`. Apart from this problem, it's working correctly and with good performance.

Is this related to the above situation? Is there anything we should do to allow concurrent writes on delta tables?

Thanks.

**Comment by vscfreire** [comment]
> I'm also encountering this problem, when performing DELETE tasks (two or more) at the same time or very close to one another.

Created #16413 since it appears to be a different problem from what's described here (this issue refers to tests, and the error message is slightly different).

Please ignore previous comment.

**Comment by findepi** [comment]
hopefully obsolete. we use a new S3 transaction synchronizer now
