### ISSUE TITLE
Flaky test TestPinotWithoutAuthenticationIntegrationSmokeTestLatestVersion.testAggregatePassthroughQueriesWithExpressions and TestPinotWithoutAuthenticationIntegrationSmokeTestLatestVersionNoGrpc.testAggregatePassthroughQueriesWithExpressions

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#13165]
https://github.com/trinodb/trino/runs/7319645851
```
Error:  io.trino.plugin.pinot.TestPinotWithoutAuthenticationIntegrationSmokeTestLatestVersionNoGrpc.testAggregatePassthroughQueriesWithExpressions  Time elapsed: 0.999 s  <<< FAILURE!
java.lang.RuntimeException: Query select "string_col", sum("metric_col1") AS "sum_metric_col1", distinctcount("another_string_col") AS "count_dup_string_col", divide(sum("metric_col1") - sum("metric_col2"), sum("metric_col1")) AS "ratio_metric_col" from duplicate_values_in_columns where ("dim_col") = ("another_dim_col") group by "string_col" order by "string_col" limit 10 encountered exception org.apache.pinot.common.response.broker.QueryProcessingException@17d147ca with query "select "string_col", sum("metric_col1") AS "sum_metric_col1", distinctcount("another_string_col") AS "count_dup_string_col", divide(sum("metric_col1") - sum("metric_col2"), sum("metric_col1")) AS "ratio_metric_col" from duplicate_values_in_columns where ("dim_col") = ("another_dim_col") group by "string_col" order by "string_col" limit 10"
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:528)
	at io.trino.sql.query.QueryAssertions$QueryAssert.newQueryAssert(QueryAssertions.java:266)
	at io.trino.sql.query.QueryAssertions.query(QueryAssertions.java:114)
	at io.trino.testing.AbstractTestQueryFramework.query(AbstractTestQueryFramework.java:237)
	at io.trino.testing.AbstractTestQueryFramework.query(AbstractTestQueryFramework.java:232)
	at io.trino.plugin.pinot.AbstractPinotIntegrationSmokeTest.testAggregatePassthroughQueriesWithExpressions(AbstractPinotIntegrationSmokeTest.java:2105)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: SQL: SELECT string_col, sum_metric_col1, count_dup_string_col, ratio_metric_col  FROM "SELECT string_col, SUM(metric_col1) AS sum_metric_col1, COUNT(DISTINCT another_string_col) AS count_dup_string_col,  (SUM(metric_col1) - SUM(metric_col2)) / SUM(metric_col1) AS ratio_metric_col  FROM duplicate_values_in_columns WHERE dim_col = another_dim_col  GROUP BY string_col  ORDER BY string_col"
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:531)
		... 18 more
Caused by: io.trino.plugin.pinot.PinotException: Query select "string_col", sum("metric_col1") AS "sum_metric_col1", distinctcount("another_string_col") AS "count_dup_string_col", divide(sum("metric_col1") - sum("metric_col2"), sum("metric_col1")) AS "ratio_metric_col" from duplicate_values_in_columns where ("dim_col") = ("another_dim_col") group by "string_col" order by "string_col" limit 10 encountered exception org.apache.pinot.common.response.broker.QueryProcessingException@17d147ca with query "select "string_col", sum("metric_col1") AS "sum_metric_col1", distinctcount("another_string_col") AS "count_dup_string_col", divide(sum("metric_col1") - sum("metric_col2"), sum("metric_col1")) AS "ratio_metric_col" from duplicate_values_in_columns where ("dim_col") = ("another_dim_col") group by "string_col" order by "string_col" limit 10"
	at io.trino.plugin.pinot.client.PinotClient.lambda$submitBrokerQueryJson$6(PinotClient.java:548)
	at io.trino.plugin.pinot.client.PinotClient.doWithRetries(PinotClient.java:616)
	at io.trino.plugin.pinot.client.PinotClient.submitBrokerQueryJson(PinotClient.java:532)
	at io.trino.plugin.pinot.client.PinotClient.createResultIterator(PinotClient.java:573)
	at io.trino.plugin.pinot.PinotBrokerPageSource.getNextPage(PinotBrokerPageSource.java:112)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
	at io.trino.operator.Driver.processInternal(Driver.java:410)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:740)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_testversion____20220713_113459_1387.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ksobolew** [comment]
CI hit: https://github.com/trinodb/trino/runs/7341133651?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/7745769680?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/7971229321?check_suite_focus=true

**Comment by kokosing** [comment]
It happened to me too.
