### ISSUE TITLE
INTERNAL_ERROR when running OPTIMIZE targeting Iceberg v2 table

### ISSUE THREAD

**Issue by aletc1** [trinodb/trino#13234]
When running ```ALTER TABLE <catalog>.<schema>.<table> EXECUTE optimize``` targeting Iceberg v2 table, Trino throws [GENERIC_INTERNAL_ERROR]: Internal error.

Env:
- Trino 390
- Iceberg v2 table
- Some deletions have been made.
- unique names enabled in iceberg catalog

Stack trace:
```
java.lang.IllegalArgumentException: undefined
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:131)
	at io.trino.operator.output.Int128PositionsAppender.append(Int128PositionsAppender.java:66)
	at io.trino.operator.output.RleAwarePositionsAppender.append(RleAwarePositionsAppender.java:59)
	at io.trino.operator.output.UnnestingPositionsAppender.append(UnnestingPositionsAppender.java:56)
	at io.trino.operator.output.PositionsAppenderPageBuilder.appendToOutputPartition(PositionsAppenderPageBuilder.java:60)
	at io.trino.operator.output.PagePartitioner.partitionPageByColumn(PagePartitioner.java:260)
	at io.trino.operator.output.PagePartitioner.partitionPage(PagePartitioner.java:193)
	at io.trino.operator.output.PartitionedOutputOperator.addInput(PartitionedOutputOperator.java:286)
	at io.trino.operator.Driver.processInternal(Driver.java:415)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:740)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_390____20220719_135459_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Steps to reproduce:
```sql
CREATE TABLE IF NOT EXISTS "basetable" ("Id" uuid,"SeqId" integer,"Title" VarChar,"Amount" decimal(28,12), "CreatedOn" timestamp(6),"_expired" timestamp(6)) WITH (format = 'ORC', format_version = 2, partitioning = ARRAY['day(_expired)'])

insert into "basetable" values
 (uuid'7dcd3fbc-31a8-4442-a724-7914023f1e1d', 6928, 'XXX', 1549.81, timestamp'2022-07-19 12:23:04.295', null),
 (uuid'7aa35563-5282-40c7-865b-d45f88908b8d', 6929, 'YYY', 11552.40, timestamp'2022-07-19 12:23:05.115', null),
 (uuid'b7b561e2-1bc7-4752-8dfd-d735035e1918', 6930, 'ZZZ', 20000, timestamp'2022-07-19 12:23:05.896', null)

CREATE TABLE IF NOT EXISTS "finaltable" ("Id" uuid,"SeqId" integer,"Title" VarChar,"Amount" decimal(28,12), "CreatedOn" timestamp(6),"_expired" timestamp(6)) WITH (format = 'ORC', format_version = 2, partitioning = ARRAY['day(_expired)'])

insert into "finaltable" (select "Id","SeqId","Title","Amount", "CreatedOn","_expired" from basetable)

alter table finaltable execute optimize
```

Expected result: The previous sequence of statements must succeed

**Comment by aletc1** [comment]
> Thanks for the report. Are you able to create a reproduction for this?

Right now I have some tables that produce this (and others are ok), but I cannot thell the steps that leaves them in this state.

I could try to reproduce it, but, in the meantime, is there anything I can share to help? Like a log or something besides the stack trace?

Thanks

**Comment by aletc1** [comment]
Hi @electrum, I managed to reproduce the issue, see the steps in the description. It fails in the INSERT/SELECT clause (insert into "finaltable" select...).
I suppose that the OPTIMIZE was doing the same operation internally (like the INSERT/SELECT) and that's why I was getting this in the optimize, but the problem as you can see is more generic and might impact other scenarios. 
**The problem is with the UUID**. The previous code works if you remove the UUID field.

**Comment by findepi** [comment]
I think this is the same bug as in https://github.com/trinodb/trino/issues/13265 cc @sopel39 @martint 
@aletc1 can you verify latest master is working for you?

closing as fixed by https://github.com/trinodb/trino/pull/13268
