### ISSUE TITLE
UUID type in Iceberg returns invalid block type

### ISSUE THREAD

**Issue by martint** [trinodb/trino#13235]
UUID type is based on `Int128ArrayBlock`, but the Iceberg connector returns a `VariableWidthBlock`. This causes a failure in PartitionedOutputOperator:

```
java.lang.IllegalArgumentException: undefined
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:131)
	at io.trino.operator.output.Int128PositionsAppender.append(Int128PositionsAppender.java:66)
	at io.trino.operator.output.RleAwarePositionsAppender.append(RleAwarePositionsAppender.java:59)
	at io.trino.operator.output.UnnestingPositionsAppender.append(UnnestingPositionsAppender.java:56)
	at io.trino.operator.output.PositionsAppenderPageBuilder.appendToOutputPartition(PositionsAppenderPageBuilder.java:60)
	at io.trino.operator.output.PagePartitioner.partitionPageByColumn(PagePartitioner.java:260)
	at io.trino.operator.output.PagePartitioner.partitionPage(PagePartitioner.java:193)
	at io.trino.operator.output.PartitionedOutputOperator.addInput(PartitionedOutputOperator.java:286)
	at io.trino.operator.Driver.processInternal(Driver.java:415)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:740)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_389____20220714_180032_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

This issue was uncovered as a result of changes introduced in https://github.com/trinodb/trino/pull/11289

Related discussion: https://trinodb.slack.com/archives/CGB0QHWSW/p1657822779648409

**Comment by findepi** [comment]
> UUID type in Iceberg returns invalid block type


So far i thought the valid block type is anything given `io.trino.spi.type.Type` instance can work with.
What's the definition of a valid block type for a given Trino type?

**Comment by electrum** [comment]
That was my understanding as well. The `UuidType.createBlockBuilder()` returns `Int128ArrayBlockBuilder`, but the Javadoc for `Type.createBlockBuilder()` says

> Creates the *preferred* block builder for this type

I don't think we've ever required a specific block type for a given type. cc @dain

**Comment by martint** [comment]
Yes. That's correct. For a given type it's generally either RunLengthEncodedBlock, DictionaryBlock and one of the concrete fixed/variable width blocks.

The UUID type needs to be able to call `getLong()` on the block, which isn't supported by VariableWidthBlock. Therefore, it can't work with that type of block.

**Comment by electrum** [comment]
`VariableWidthBlock` does support `getLong()` via the implementation in its parent class `AbstractVariableWidthBlock`.

**Comment by martint** [comment]
I'm going to close this issue. While it's better to always return the same type of block (for performance reasons), it's not a requirement right now as long as the blocks support the methods the Type class needs. It's something we've discussed cleaning up in the future, especially now that we support arbitrary container types (via `getObject()`), but that's a larger change.

In the meantime, the engine should not be making assumptions about the concrete type of block returned by connectors.
