### ISSUE TITLE
Failure in PartitionedOutputOperator due to incorrect expectation

### ISSUE THREAD

**Issue by martint** [trinodb/trino#13265]
PartitionedOutputOperator incorrectly expects types to support only specific block types. As a result, queries fail with:

```
java.lang.IllegalArgumentException: undefined
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:131)
	at io.trino.operator.output.Int128PositionsAppender.append(Int128PositionsAppender.java:66)
	at io.trino.operator.output.RleAwarePositionsAppender.append(RleAwarePositionsAppender.java:59)
	at io.trino.operator.output.UnnestingPositionsAppender.append(UnnestingPositionsAppender.java:56)
	at io.trino.operator.output.PositionsAppenderPageBuilder.appendToOutputPartition(PositionsAppenderPageBuilder.java:60)
	at io.trino.operator.output.PagePartitioner.partitionPageByColumn(PagePartitioner.java:260)
	at io.trino.operator.output.PagePartitioner.partitionPage(PagePartitioner.java:193)
	at io.trino.operator.output.PartitionedOutputOperator.addInput(PartitionedOutputOperator.java:286)
	at io.trino.operator.Driver.processInternal(Driver.java:415)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:740)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_389____20220714_180032_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

This was introduced in https://github.com/trinodb/trino/pull/11289

Related discussions
* https://trinodb.slack.com/archives/CGB0QHWSW/p1657822779648409
* https://github.com/trinodb/trino/issues/13235

**Comment by martint** [comment]
These assumptions are incorrect:

https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/operator/output/PositionsAppenderFactory.java#L59

https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/operator/output/Int96PositionsAppender.java#L67

https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/operator/output/Int128PositionsAppender.java#L66

The fact that a type has a fixed size of 96 or 128 bytes does not imply that the data for those types will be encoded in one of those two block types.

**Comment by martint** [comment]
cc @lukasz-stec
