### ISSUE TITLE
Query sometimes fails when spill enabled: Failed to read spilled pages

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#13288]
First reported on March 31, 2021 in https://github.com/trinodb/trino/issues/7466.

TestSpilledJoinQueries.testSemiJoinWithGroupBy failed in https://github.com/trinodb/trino/runs/7434661444?check_suite_focus=true

```
Error:  io.trino.tests.TestSpilledJoinQueries.testSemiJoinWithGroupBy  Time elapsed: 2.702 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT linenumber, min(orderkey), 6 IN (SELECT max(orderkey) FROM orders WHERE orderkey < 7)FROM lineitem GROUP BY linenumber, 6 IN (SELECT sum(orderkey) FROM orders WHERE orderkey < 5)
	at org.testng.Assert.fail(Assert.java:83)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:247)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:242)
	at io.trino.testing.AbstractTestJoinQueries.testSemiJoinWithGroupBy(AbstractTestJoinQueries.java:1923)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Failed to read spilled pages
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:528)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 17 more
	Suppressed: java.lang.Exception: SQL: SELECT linenumber, min(orderkey), 6 IN (SELECT max(orderkey) FROM orders WHERE orderkey < 7)FROM lineitem GROUP BY linenumber, 6 IN (SELECT sum(orderkey) FROM orders WHERE orderkey < 5)
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:531)
		... 18 more
Caused by: io.trino.spi.TrinoException: Failed to read spilled pages
	at io.trino.spiller.FileSingleStreamSpiller.readPages(FileSingleStreamSpiller.java:175)
	at io.trino.spiller.FileSingleStreamSpiller.getSpilledPages(FileSingleStreamSpiller.java:133)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.spiller.GenericSpiller.getSpills(GenericSpiller.java:76)
	at io.trino.operator.aggregation.builder.SpillableHashAggregationBuilder.mergeFromDiskAndMemory(SpillableHashAggregationBuilder.java:279)
	at io.trino.operator.aggregation.builder.SpillableHashAggregationBuilder.buildResult(SpillableHashAggregationBuilder.java:209)
	at io.trino.operator.HashAggregationOperator.getOutput(HashAggregationOperator.java:506)
	at io.trino.operator.Driver.processInternal(Driver.java:410)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:740)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:490)
	at io.trino.$gen.Trino_testversion____20220720_212519_26189.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill11047950622644845756.bin
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at io.trino.spiller.FileHolder.newInputStream(FileHolder.java:56)
	at io.trino.spiller.FileSingleStreamSpiller.readPages(FileSingleStreamSpiller.java:169)
	... 24 more
```

**Comment by findepi** [comment]
@skrzypo987 @sopel39 can this anyhow be related to https://github.com/trinodb/trino/pull/12618?

**Comment by skrzypo987** [comment]
> @skrzypo987 @sopel39 can this anyhow be related to #12618?

My answer is somewhere between "definitely not", "shouldn't", "no way", "doesn't look like it" and "who knows"

**Comment by sopel39** [comment]
@findepi How many times you observed that? Maybe some test concurrency issue (e.g. cleaning up of spill dir)?

**Comment by findepi** [comment]
> How many times you observed that?

the linked CI run attempted the test once and it failed once during that test run

> e.g. cleaning up of spill dir

this shouldn't happen concurrently with a test method execution

**Comment by findepi** [comment]
> > @skrzypo987 @sopel39 can this anyhow be related to #12618?
> 
> My answer is somewhere between "definitely not", "shouldn't", "no way", "doesn't look like it" and "who knows"

Asking because I haven't seen this test flaky until recently and so it failing already twice this week.
(don't remember where i saw it first time, don't have the link anymore)

**Comment by sopel39** [comment]
Probably it is related. @skrzypo987 could you take a look and try to repro?

**Comment by sopel39** [comment]
> I've looked through the changes and see no reason for this to happen due to https://github.com/trinodb/trino/pull/12618. There were no changes whatsoever in the spilling operator

Could you run the test in a loop?

**Comment by skrzypo987** [comment]
I ran it 1000x times locally

**Comment by findepi** [comment]
`TestSpilledWindowQueries.testWindowsPrefixPartitionin`  in https://github.com/trinodb/trino/runs/8205427230?check_suite_focus=true

```
io.trino.spi.TrinoException: Failed to read spilled pages
	at io.trino.spiller.FileSingleStreamSpiller.readPages(FileSingleStreamSpiller.java:175)
	at io.trino.spiller.FileSingleStreamSpiller.getSpilledPages(FileSingleStreamSpiller.java:133)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.spiller.GenericSpiller.getSpills(GenericSpiller.java:76)
	at io.trino.operator.WindowOperator$SpillablePagesToPagesIndexes.unspill(WindowOperator.java:833)
	at io.trino.operator.WindowOperator$SpillablePagesToPagesIndexes.fullGroupBuffered(WindowOperator.java:773)
	at io.trino.operator.WindowOperator$SpillablePagesToPagesIndexes.process(WindowOperator.java:736)
	at io.trino.operator.WindowOperator$SpillablePagesToPagesIndexes.process(WindowOperator.java:658)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WindowOperator.getOutput(WindowOperator.java:404)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:737)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:514)
	at io.trino.$gen.Trino_testversion____20220906_115330_16059.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill2138212386742840784.bin
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at io.trino.spiller.FileHolder.newInputStream(FileHolder.java:56)
	at io.trino.spiller.FileSingleStreamSpiller.readPages(FileSingleStreamSpiller.java:169)
	... 36 more
```

**Comment by findepi** [comment]
I merged https://github.com/trinodb/trino/issues/13887 as a duplicate of this one.
It was reported for `TestSpilledWindowQueries.testWindowsDifferentPartitions` failure in https://github.com/trinodb/trino/runs/8049156767 .

**Comment by findepi** [comment]
I closed https://github.com/trinodb/trino/issues/7466 as a duplicate of this one.

**Comment by hashhar** [comment]
`NoSuchFileException` can also be thrown in case of open files limit being exceeded - at-least that's what I saw in the past.

**Comment by findepi** [comment]
I closed https://github.com/trinodb/trino/issues/13778 as a dup of this.

cc @arhimondr @MiguelWeezardo

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/3046124099/jobs/4908791825

```
Error:  io.trino.tests.TestSpilledAggregations.testGroupingCombinationsDistinct  Time elapsed: 1.35 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT orderkey, partkey, suppkey, linenumber, SUM(CAST(quantity AS BIGINT)) FROM lineitem GROUP BY DISTINCT orderkey, partkey, ROLLUP (suppkey, linenumber), CUBE (linenumber)
	at org.testng.Assert.fail(Assert.java:83)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:252)
	at io.trino.testing.AbstractTestAggregations.testGroupingCombinationsDistinct(AbstractTestAggregations.java:1314)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.trino.testing.QueryFailedException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill1665944624812581390.bin
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:123)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:480)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 16 more
	Suppressed: java.lang.Exception: SQL: SELECT orderkey, partkey, suppkey, linenumber, SUM(CAST(quantity AS BIGINT)) FROM lineitem GROUP BY DISTINCT orderkey, partkey, ROLLUP (suppkey, linenumber), CUBE (linenumber)
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:483)
		... 17 more
Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill1665944624812581390.bin
	at io.trino.spiller.FileHolder.close(FileHolder.java:71)
	at com.google.common.io.Closer.close(Closer.java:218)
	at io.trino.spiller.FileSingleStreamSpiller.close(FileSingleStreamSpiller.java:183)
	at com.google.common.io.Closer.close(Closer.java:218)
	at io.trino.spiller.GenericSpiller.close(GenericSpiller.java:83)
	at com.google.common.io.Closer.close(Closer.java:218)
	at io.trino.operator.aggregation.builder.SpillableHashAggregationBuilder.close(SpillableHashAggregationBuilder.java:237)
	at io.trino.operator.HashAggregationOperator.closeAggregationBuilder(HashAggregationOperator.java:538)
	at io.trino.operator.HashAggregationOperator.getOutput(HashAggregationOperator.java:512)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:736)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:515)
	at io.trino.$gen.Trino_testversion____20220913_154415_11472.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill15176837042355282283.bin
		... 21 more
	Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill15176837042355282283.bin
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at io.trino.spiller.FileHolder.close(FileHolder.java:68)
		... 20 more
	Suppressed: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill15739788277233959778.bin
		... 21 more
	Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill15739788277233959778.bin
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at io.trino.spiller.FileHolder.close(FileHolder.java:68)
		... 20 more
	Suppressed: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill107674181220822[25771](https://github.com/trinodb/trino/actions/runs/3046124099/jobs/4908791825#step:8:25772).bin
		... 21 more
	Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill10767418122082225771.bin
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at io.trino.spiller.FileHolder.close(FileHolder.java:68)
		... 20 more
	Suppressed: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill8379830453237678910.bin
		... 21 more
	Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill8379830453237678910.bin
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at io.trino.spiller.FileHolder.close(FileHolder.java:68)
		... 20 more
	Suppressed: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill3229416976065748830.bin
		... 21 more
	Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill3229416976065748830.bin
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at io.trino.spiller.FileHolder.close(FileHolder.java:68)
		... 20 more
Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill166594462481[25813](https://github.com/trinodb/trino/actions/runs/3046124099/jobs/4908791825#step:8:25814)90.bin
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1152)
	at io.trino.spiller.FileHolder.close(FileHolder.java:68)
	... 20 more
```

**Comment by findepi** [comment]
@MiguelWeezardo @nineinchnick how can we verify the hypothesis that there is some background cleanup going on inside `/tmp`?

**Comment by nineinchnick** [comment]
@findepi we could set up `inotifywait` to find who's deleting files from `/tmp` or just prevent this by setting `chattr +a /tmp/<subdir>` (make it append-only)

**Comment by nineinchnick** [comment]
I'm not aware of anything like that, that would be running in the background and not explicitly.

**Comment by findepi** [comment]
I am sure our code wouldn't do that. But maybe there is something that comes with github runners?

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/14173

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/3135264357/jobs/5091986323

**Comment by nevillelyh** [comment]
https://github.com/trinodb/trino/actions/runs/3242724734/jobs/5317567698

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/3460294216/jobs/5777172091

**Comment by homar** [comment]
https://github.com/trinodb/trino/actions/runs/3901915892/jobs/6664902595

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/3935843549/jobs/6732428630

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/3966879583/jobs/6799356558

```
2023-01-20T07:03:54.358-0600	INFO	pool-5-thread-2	io.trino.spiller.FileSingleStreamSpillerFactory	Deleting old spill file: /tmp/trino/spills/spill9717569101033421874.bin
2023-01-20T07:03:54.358-0600	INFO	pool-5-thread-2	io.trino.spiller.FileSingleStreamSpillerFactory	Deleting old spill file: /tmp/trino/spills/spill12204723447457484879.bin
2023-01-20T07:03:54.408-0600	ERROR	SplitRunner-13-230	io.trino.execution.executor.TaskExecutor	Error processing Split 20230120_130353_00171_hn7mk.0.1.0-1 TpchSplit{partNumber=3, totalParts=4} (start = 428058.784767, wall = 780 ms, cpu = 166 ms, wait = 11 ms, calls = 10): GENERIC_INTERNAL_ERROR: Failed to read spilled pages
io.trino.spi.TrinoException: Failed to read spilled pages
	at io.trino.spiller.FileSingleStreamSpiller.readPages(FileSingleStreamSpiller.java:178)
	at io.trino.spiller.FileSingleStreamSpiller.getSpilledPages(FileSingleStreamSpiller.java:135)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.spiller.GenericSpiller.getSpills(GenericSpiller.java:76)
	at io.trino.operator.aggregation.builder.SpillableHashAggregationBuilder.mergeFromDisk(SpillableHashAggregationBuilder.java:283)
	at io.trino.operator.aggregation.builder.SpillableHashAggregationBuilder.buildResult(SpillableHashAggregationBuilder.java:199)
	at io.trino.operator.HashAggregationOperator.getOutput(HashAggregationOperator.java:501)
	at io.trino.operator.Driver.processInternal(Driver.java:394)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:297)
	at io.trino.operator.Driver.tryWithLock(Driver.java:689)
	at io.trino.operator.Driver.process(Driver.java:289)
	at io.trino.operator.Driver.processForDuration(Driver.java:260)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:755)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
	at io.trino.$gen.Trino_testversion____20230120_130256_72.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill4883327794454224878.bin
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at io.trino.spiller.FileHolder.newInputStream(FileHolder.java:56)
	at io.trino.spiller.FileSingleStreamSpiller.readPages(FileSingleStreamSpiller.java:172)
	... 24 more

```

**Comment by nineinchnick** [comment]
This is present in logs on line 780:
```
2023-01-20T07:03:54.356-0600	INFO	pool-5-thread-2	io.trino.spiller.FileSingleStreamSpillerFactory	Deleting old spill file: /tmp/trino/spills/spill4883327794454224878.bin
```
can it be a race in Trino?
