### ISSUE TITLE
Flaky `TestHiveDynamicPartitionPruningTest.testJoinDynamicFilteringMultiJoinOnBucketedTables`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#13322]
```
Error:  io.trino.plugin.hive.TestHiveDynamicPartitionPruningTest.testJoinDynamicFilteringMultiJoinOnBucketedTables[BROADCAST](2)  Time elapsed: 1.408 s  <<< FAILURE!
java.lang.AssertionError: 
[filtered input positions] 
Expecting:
 <4L>
to be less than:
 <4L> 
	at io.trino.testing.BaseDynamicPartitionPruningTest.assertDynamicFilters(BaseDynamicPartitionPruningTest.java:491)
	at io.trino.testing.BaseDynamicPartitionPruningTest.testJoinDynamicFilteringMultiJoin(BaseDynamicPartitionPruningTest.java:465)
	at io.trino.testing.BaseDynamicPartitionPruningTest.testJoinDynamicFilteringMultiJoinOnBucketedTables(BaseDynamicPartitionPruningTest.java:457)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

https://github.com/trinodb/trino/runs/7479762692

**Comment by sopel39** [comment]
This wasn't flaky before. Could  it be actual product test due to recent DF changes, cc @raunaqmorarka @arhimondr ?

**Comment by sopel39** [comment]
@nineinchnick Could you confirm that it's a new flakyness rather than being there always from time to time?

**Comment by nineinchnick** [comment]
@sopel39 last occurrence was on 2022-06-14

**Comment by nineinchnick** [comment]
Is this happening in the CI? Shouldn't we see more recent occurrences?

**Comment by ebyhr** [comment]
@nineinchnick It failed 2 days ago in https://github.com/trinodb/trino/runs/7479762692

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/runs/7520376089?check_suite_focus=true

**Comment by Praveen2112** [comment]
https://github.com/trinodb/trino/runs/7560632851?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/7776189226?check_suite_focus=true

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/7802208619
