### ISSUE TITLE
Flaky TestDistributedFaultTolerantEngineOnlyQueries.close

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#13362]
```
2022-07-23T11:53:37.5100187Z [ERROR] io.trino.tests.TestDistributedFaultTolerantEngineOnlyQueries.close  Time elapsed: 1.43 s  <<< FAILURE!
2022-07-23T11:53:37.5101051Z java.lang.AssertionError: 
2022-07-23T11:53:37.5101986Z Expected memory reservation on server_2(coordinator)to be 0 but was 120; detailed memory usage:
2022-07-23T11:53:37.5102357Z  20220723_114511_00071_rkct5:
2022-07-23T11:53:37.5102704Z    SQL: SELECT count(*) c_tfa8rercpm FROM lineitem CROSS JOIN lineitem CROSS JOIN lineitem
2022-07-23T11:53:37.5103017Z    state: FAILED
2022-07-23T11:53:37.5103261Z    memoryReservation: 120
2022-07-23T11:53:37.5103986Z    taggedMemoryReservaton: {FORCE_FREE_OPERATION=-816, TableScanOperator=816, LazyOutputBuffer=120}
2022-07-23T11:53:37.5104252Z 
2022-07-23T11:53:37.5104418Z 	at org.testng.Assert.fail(Assert.java:94)
2022-07-23T11:53:37.5104967Z 	at io.trino.testing.AbstractTestQueryFramework.assertMemoryPoolReleased(AbstractTestQueryFramework.java:148)
2022-07-23T11:53:37.5105673Z 	at io.trino.testing.AbstractTestQueryFramework.lambda$checkQueryMemoryReleased$0(AbstractTestQueryFramework.java:133)
2022-07-23T11:53:37.5106309Z 	at io.trino.testing.assertions.Assert.assertEventually(Assert.java:77)
2022-07-23T11:53:37.5106940Z 	at io.trino.testing.AbstractTestQueryFramework.checkQueryMemoryReleased(AbstractTestQueryFramework.java:126)
2022-07-23T11:53:37.5107599Z 	at io.trino.testing.AbstractTestQueryFramework.close(AbstractTestQueryFramework.java:108)
2022-07-23T11:53:37.5108156Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-07-23T11:53:37.5108743Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-07-23T11:53:37.5109670Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-07-23T11:53:37.5110187Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-07-23T11:53:37.5110701Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-07-23T11:53:37.5111263Z 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
2022-07-23T11:53:37.5111770Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
2022-07-23T11:53:37.5112252Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
2022-07-23T11:53:37.5112808Z 	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
2022-07-23T11:53:37.5113337Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
2022-07-23T11:53:37.5113865Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-07-23T11:53:37.5114426Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-07-23T11:53:37.5114857Z 	at java.base/java.lang.Thread.run(Thread.java:833)
```
cc @arhimondr @losipiuk

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/runs/7480214992?check_suite_focus=true

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/runs/7624187595

**Comment by nineinchnick** [comment]
https://github.com/trinodb/trino/runs/7765863878?check_suite_focus=true

**Comment by arhimondr** [comment]
Fix: https://github.com/trinodb/trino/pull/13717

**Comment by tangjiangling** [comment]
https://github.com/trinodb/trino/runs/7901491814?check_suite_focus=true

**Comment by arhimondr** [comment]
Closed through https://github.com/trinodb/trino/pull/13717
