### ISSUE TITLE
NULL value may be inserted into non-nullable column if it is a result of an expression

### ISSUE THREAD

**Issue by homar** [trinodb/trino#13434]
on Iceberg:
`
CREATE TABLE  tableName  (col1 INTEGER NOT NULL, col2 INTEGER);
INSERT INTO tableName VALUES(1, 10);
`
This doesn't work which is good:
`INSERT INTO tableName VALUES(null, 1)`

but this works which is not good:

`INSERT INTO  tableName  VALUES(TRY(5/0), 1)`

**Comment by homar** [comment]
failure: https://starburstdata.atlassian.net/browse/SEP-9412

**Comment by findepi** [comment]
This depends on the column type and/or coercions.

with `bigint` column (and integer producing expression) the validation happens in `TableWriterOperator`

```
trino:tpch> DROP TABLE IF EXISTS t;
         -> CREATE TABLE t( c bigint not null ); -- bigint
         -> INSERT INTO t VALUES try(5/0);
         ->
DROP TABLE
CREATE TABLE

Query 20220803_082158_00029_24rf9, FAILED, 2 nodes

Query 20220803_082158_00029_24rf9 failed: NULL value not allowed for NOT NULL column: c
io.trino.spi.TrinoException: NULL value not allowed for NOT NULL column: c
	at io.trino.operator.TableWriterOperator.verifyBlockHasNoNulls(TableWriterOperator.java:285)
	at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:260)
	at io.trino.operator.Driver.processInternal(Driver.java:415)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:740)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:490)
	at io.trino.$gen.Trino_testversion____20220803_082101_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

with `integer` column (and integer producing expression) the INSERT passes
```
trino:tpch> DROP TABLE IF EXISTS t;
         -> CREATE TABLE t( c integer not null ); -- integer
         -> INSERT INTO t VALUES try(5/0);
         ->
DROP TABLE
CREATE TABLE
INSERT: 1 row
```
