### ISSUE TITLE
Flaky io.trino.execution.TestSqlTaskManager.testFailStuckSplitTasks

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#13437]
```
2022-07-29T21:50:26.1127048Z [ERROR] io.trino.execution.TestSqlTaskManager.testFailStuckSplitTasks  Time elapsed: 0.021 s  <<< FAILURE!
2022-07-29T21:50:26.1127727Z java.lang.AssertionError: expected [1] but found [0]
2022-07-29T21:50:26.1128224Z 	at org.testng.Assert.fail(Assert.java:94)
2022-07-29T21:50:26.1128887Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2022-07-29T21:50:26.1129744Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2022-07-29T21:50:26.1130429Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2022-07-29T21:50:26.1130919Z 	at org.testng.Assert.assertEquals(Assert.java:389)
2022-07-29T21:50:26.1131426Z 	at org.testng.Assert.assertEquals(Assert.java:399)
2022-07-29T21:50:26.1132103Z 	at io.trino.execution.TestSqlTaskManager.testFailStuckSplitTasks(TestSqlTaskManager.java:278)
2022-07-29T21:50:26.1132865Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-07-29T21:50:26.1133749Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-07-29T21:50:26.1134553Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-07-29T21:50:26.1135221Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-07-29T21:50:26.1136082Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-07-29T21:50:26.1136770Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-07-29T21:50:26.1137376Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-07-29T21:50:26.1137987Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-07-29T21:50:26.1138997Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-07-29T21:50:26.1139653Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-07-29T21:50:26.1140319Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-07-29T21:50:26.1141369Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-07-29T21:50:26.1142084Z 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by sopel39** [comment]
cc @arhimondr @losipiuk

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/runs/7585678894?check_suite_focus=true

**Comment by arhimondr** [comment]
@leetcode-1533 Could you please take a look?

**Comment by leetcode-1533** [comment]
taking a look

**Comment by leetcode-1533** [comment]
https://github.com/trinodb/trino/pull/13441

**Comment by arhimondr** [comment]
Resolved by https://github.com/trinodb/trino/pull/13441
