### ISSUE TITLE
Fix failure when reading a table having partition columns renamed by Spark

### ISSUE THREAD

**Issue by Dearkano** [trinodb/trino#13521]
Hi, Trino community,

I found this issue when I tried the renaming feature of Delta Lake. It appeared that Trino did not support this feature weeks ago, and it started to support this in the recent update. However, I found when I tried to rename the partition columns, the query would still fail while the query on SparkSQL is correct. (It works fine for non-partition columns).

This test is to rename the partition "department" to "dep"
![Screen Shot 2022-08-05 at 11 22 08 AM](https://user-images.githubusercontent.com/24840232/183138206-a069a771-6baf-44ff-9c1a-bc33885cbf77.png)

**Comment by findepi** [comment]
Hi @Dearkano 

thanks for your report.
Can you please attach exact steps (SQL statements) to reproduce the problem?

cc @alexjo2144 @findinpath @ebyhr

**Comment by ebyhr** [comment]
I could reproduce the issue using the below steps. Let us know if it's different from your intention. 

```sql
-- Databricks
CREATE TABLE test_rename (c1 int, c2 int) PARTITIONED BY (c2) TBLPROPERTIES ('delta.columnMapping.mode' = 'name', 'delta.minReaderVersion' = '2', 'delta.minWriterVersion' = '5');
INSERT INTO test_rename VALUES (1, 1);
ALTER TABLE test_rename RENAME COLUMN c2 TO new_c2;

-- Trino
SELECT * FROM test_rename;
io.trino.spi.TrinoException: Index 1 out of bounds for length 1
	at io.trino.plugin.deltalake.DeltaLakePageSource.getNextPage(DeltaLakePageSource.java:176)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
	at io.trino.operator.Driver.processInternal(Driver.java:410)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:740)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:490)
	at io.trino.$gen.Trino_dev____20220808_024050_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at io.trino.spi.Page.getBlock(Page.java:131)
	at io.trino.plugin.deltalake.DeltaLakePageSource.getNextPage(DeltaLakePageSource.java:168)
	... 13 more
```

**Comment by ebyhr** [comment]
Supporting reading columns renamed by Databricks and implementing `RENAME COLUMN` syntax in the connector can be separated issues. It would be better to fix the former first.
