### ISSUE TITLE
Predicates on JSON column fails in MongoDB connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#13536]
We can just disable the pushdown on json column in MongoDB connector. `TestMongoTypeMapping` needs a new test method for json type when fixing this issue. 

```sql
CREATE TABLE test (c1 json);
INSERT INTO test VALUES (json '{"id":0,"name":"user_0"}');

SELECT * FROM test WHERE c1 = json '{"id":0,"name":"user_0"}';
java.lang.UnsupportedOperationException
	at io.trino.spi.predicate.ValueSet.getRanges(ValueSet.java:122)
	at io.trino.plugin.mongodb.MongoSession.buildPredicate(MongoSession.java:438)
	at io.trino.plugin.mongodb.MongoSession.buildQuery(MongoSession.java:417)
	at io.trino.plugin.mongodb.MongoSession.execute(MongoSession.java:398)
	at io.trino.plugin.mongodb.MongoPageSource.<init>(MongoPageSource.java:108)
	at io.trino.plugin.mongodb.MongoPageSourceProvider.createPageSource(MongoPageSourceProvider.java:59)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:62)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:268)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:196)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$3(WorkProcessorUtils.java:219)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$4(WorkProcessorUtils.java:234)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:150)
	at io.trino.operator.Driver.processInternal(Driver.java:410)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:740)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:490)
	at io.trino.$gen.Trino_testversion____20220808_001654_36.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by silly-carbon** [comment]
Can I work on this issue? I'm very glad to help 😁

**Comment by martint** [comment]
Go for it!

**Comment by silly-carbon** [comment]
> Go for it!

Thanks, I'll start doing now
