### ISSUE TITLE
TestIcebergSparkCompatibility test methods became flaky recently

### ISSUE THREAD

**Issue by homar** [trinodb/trino#13601]
Some tests in `TestIcebergSparkCompatibility`  are failing with 
`could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and no node(s) are excluded in this operation`

There are retries for that in Hive product tests. Maybe similar mechanism can be added here?

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/7763335328?check_suite_focus=true


```
2022-08-10T10:41:59.6039792Z tests               | Caused by: org.apache.spark.SparkException: Writing job aborted
2022-08-10T10:41:59.6040272Z tests               | 	at org.apache.spark.sql.errors.QueryExecutionErrors$.writingJobAbortedError(QueryExecutionErrors.scala:613)
2022-08-10T10:41:59.6040934Z tests               | 	at org.apache.spark.sql.execution.datasources.v2.ExtendedV2ExistingTableWriteExec.writeWithV2(WriteDeltaExec.scala:129)
2022-08-10T10:41:59.6041666Z tests               | 	at org.apache.spark.sql.execution.datasources.v2.ExtendedV2ExistingTableWriteExec.writeWithV2$(WriteDeltaExec.scala:72)
2022-08-10T10:41:59.6042326Z tests               | 	at org.apache.spark.sql.execution.datasources.v2.WriteDeltaExec.writeWithV2(WriteDeltaExec.scala:50)
2022-08-10T10:41:59.6042952Z tests               | 	at org.apache.spark.sql.execution.datasources.v2.V2ExistingTableWriteExec.run(WriteToDataSourceV2Exec.scala:309)
2022-08-10T10:41:59.6043603Z tests               | 	at org.apache.spark.sql.execution.datasources.v2.V2ExistingTableWriteExec.run$(WriteToDataSourceV2Exec.scala:308)
2022-08-10T10:41:59.6044240Z tests               | 	at org.apache.spark.sql.execution.datasources.v2.WriteDeltaExec.run(WriteDeltaExec.scala:50)
2022-08-10T10:41:59.6044801Z tests               | 	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
2022-08-10T10:41:59.6045364Z tests               | 	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
2022-08-10T10:41:59.6045934Z tests               | 	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
2022-08-10T10:41:59.6046536Z tests               | 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:110)
2022-08-10T10:41:59.6047068Z tests               | 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
2022-08-10T10:41:59.6047567Z tests               | 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
2022-08-10T10:41:59.6048058Z tests               | 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
2022-08-10T10:41:59.6048520Z tests               | 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
2022-08-10T10:41:59.6048967Z tests               | 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
2022-08-10T10:41:59.6049487Z tests               | 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:110)
2022-08-10T10:41:59.6050095Z tests               | 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
2022-08-10T10:41:59.6050626Z tests               | 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
2022-08-10T10:41:59.6051113Z tests               | 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
2022-08-10T10:41:59.6051640Z tests               | 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
2022-08-10T10:41:59.6052296Z tests               | 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
2022-08-10T10:41:59.6053005Z tests               | 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
2022-08-10T10:41:59.6053687Z tests               | 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
2022-08-10T10:41:59.6054360Z tests               | 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
2022-08-10T10:41:59.6055008Z tests               | 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
2022-08-10T10:41:59.6056733Z tests               | 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
2022-08-10T10:41:59.6057274Z tests               | 	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
2022-08-10T10:41:59.6057848Z tests               | 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
2022-08-10T10:41:59.6058397Z tests               | 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
2022-08-10T10:41:59.6058838Z tests               | 	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:219)
2022-08-10T10:41:59.6059205Z tests               | 	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
2022-08-10T10:41:59.6059617Z tests               | 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
2022-08-10T10:41:59.6060095Z tests               | 	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
2022-08-10T10:41:59.6060488Z tests               | 	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
2022-08-10T10:41:59.6060901Z tests               | 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
2022-08-10T10:41:59.6061309Z tests               | 	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
2022-08-10T10:41:59.6061700Z tests               | 	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:651)
2022-08-10T10:41:59.6062354Z tests               | 	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:291)
2022-08-10T10:41:59.6062886Z tests               | 	... 16 more
2022-08-10T10:41:59.6063249Z tests               | Caused by: org.apache.iceberg.exceptions.RuntimeIOException: Failed to close manifest writer
2022-08-10T10:41:59.6063892Z tests               | 	at org.apache.iceberg.MergingSnapshotProducer.lambda$newDeleteFilesAsManifests$17(MergingSnapshotProducer.java:861)
2022-08-10T10:41:59.6064359Z tests               | 	at java.base/java.util.HashMap.forEach(HashMap.java:1337)
2022-08-10T10:41:59.6064864Z tests               | 	at org.apache.iceberg.MergingSnapshotProducer.newDeleteFilesAsManifests(MergingSnapshotProducer.java:850)
2022-08-10T10:41:59.6065489Z tests               | 	at org.apache.iceberg.MergingSnapshotProducer.prepareDeleteManifests(MergingSnapshotProducer.java:836)
2022-08-10T10:41:59.6066145Z tests               | 	at org.apache.iceberg.MergingSnapshotProducer.apply(MergingSnapshotProducer.java:705)
2022-08-10T10:41:59.6066608Z tests               | 	at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:177)
2022-08-10T10:41:59.6067060Z tests               | 	at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:296)
2022-08-10T10:41:59.6067501Z tests               | 	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404)
2022-08-10T10:41:59.6067916Z tests               | 	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214)
2022-08-10T10:41:59.6068297Z tests               | 	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198)
2022-08-10T10:41:59.6068660Z tests               | 	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190)
2022-08-10T10:41:59.6069058Z tests               | 	at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:295)
2022-08-10T10:41:59.6069631Z tests               | 	at org.apache.iceberg.spark.source.SparkPositionDeltaWrite$PositionDeltaBatchWrite.commitOperation(SparkPositionDeltaWrite.java:265)
2022-08-10T10:41:59.6070288Z tests               | 	at org.apache.iceberg.spark.source.SparkPositionDeltaWrite$PositionDeltaBatchWrite.commit(SparkPositionDeltaWrite.java:209)
2022-08-10T10:41:59.6070977Z tests               | 	at org.apache.spark.sql.execution.datasources.v2.ExtendedV2ExistingTableWriteExec.writeWithV2(WriteDeltaExec.scala:112)
2022-08-10T10:41:59.6071441Z tests               | 	... 53 more
2022-08-10T10:41:59.6072509Z tests               | Caused by: org.apache.hadoop.ipc.RemoteException(java.io.IOException): File /user/hive/warehouse/test_trino_reads_spark_row_level_deletes_row_types_ORC_AVRO_qh0ssvfrk57h/metadata/091f46ab-b93b-4ce2-b1e5-4cced866e35a-m0.avro could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and no node(s) are excluded in this operation.
```
