### ISSUE TITLE
Flaky io.trino.plugin.redis.TestMinimalFunctionality & TestMinimalFunctionalityWithoutKeyPrefix

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#13779]
https://github.com/trinodb/trino/runs/7955766570?check_suite_focus=true

**Comment by findepi** [comment]
@arhimondr would you mind pasting the faling method name and a stacktrace here? the workflow run link will be defunct at some point

**Comment by arhimondr** [comment]
```
Error:  io.trino.plugin.redis.TestMinimalFunctionality.testHashValueWhereClauseHasData  Time elapsed: 0.174 s  <<< FAILURE!
java.lang.AssertionError: Iterators differ at element [0]: [1] != [0] expected [[1]] but found [[0]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:611)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at io.trino.testing.assertions.Assert.assertEquals(Assert.java:53)
	at io.trino.testing.assertions.Assert.assertEquals(Assert.java:41)
	at io.trino.plugin.redis.TestMinimalFunctionality.testHashValueWhereClauseHasData(TestMinimalFunctionality.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Error:  io.trino.plugin.redis.TestMinimalFunctionality.testStringValueWhereClauseHasData  Time elapsed: 0.055 s  <<< FAILURE!
java.lang.AssertionError: Iterators differ at element [0]: [1] != [0] expected [[1]] but found [[0]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:611)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at io.trino.testing.assertions.Assert.assertEquals(Assert.java:53)
	at io.trino.testing.assertions.Assert.assertEquals(Assert.java:41)
	at io.trino.plugin.redis.TestMinimalFunctionality.testStringValueWhereClauseHasData(TestMinimalFunctionality.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Error:  io.trino.plugin.redis.TestMinimalFunctionality.testTableHasData  Time elapsed: 0.562 s  <<< FAILURE!
java.lang.AssertionError: Iterators differ at element [0]: [1000] != [0] expected [[1000]] but found [[0]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:611)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at io.trino.testing.assertions.Assert.assertEquals(Assert.java:53)
	at io.trino.testing.assertions.Assert.assertEquals(Assert.java:41)
	at io.trino.plugin.redis.TestMinimalFunctionality.testTableHasData(TestMinimalFunctionality.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/actions/runs/3172607329/jobs/5167373948

**Comment by findepi** [comment]
`TestMinimalFunctionalityWithoutKeyPrefix` test class is similarly affected 
https://github.com/trinodb/trino/actions/runs/3704502522/jobs/6277996892

```
Error:  io.trino.plugin.redis.TestMinimalFunctionalityWithoutKeyPrefix.testStringValueWhereClauseHasData  Time elapsed: 0.048 s  <<< FAILURE!
java.lang.AssertionError: Iterators differ at element [0]: [2] != [0] expected [[2]] but found [[0]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:611)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at io.trino.testing.assertions.Assert.assertEquals(Assert.java:53)
	at io.trino.testing.assertions.Assert.assertEquals(Assert.java:41)
	at io.trino.plugin.redis.TestMinimalFunctionalityWithoutKeyPrefix.testStringValueWhereClauseHasData(TestMinimalFunctionalityWithoutKeyPrefix.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/3947125426/jobs/6755886822

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/3953934302/jobs/6771691167

**Comment by ebyhr** [comment]
Closing as we haven't seen this failure recently.
