### ISSUE TITLE
Flaky TestSpilledAggregations#testGroupingCombinationsAll

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#13778]
https://github.com/trinodb/trino/runs/7955764266?check_suite_focus=true

**Comment by findepi** [comment]
@arhimondr would you mind pasting the faling method name and a stacktrace here? the workflow run link will be defunct at some point

**Comment by arhimondr** [comment]
It felt like a failure might not be specific to a certain test method. But I could be wrong. Updated the title.

**Comment by findepi** [comment]
Thanks. Can you also paste a stacktrace here as well?

**Comment by arhimondr** [comment]
```
Error:  io.trino.tests.TestSpilledAggregations.testGroupingCombinationsAll  Time elapsed: 2.406 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT orderkey, partkey, suppkey, linenumber, SUM(CAST(quantity AS BIGINT)) FROM lineitem GROUP BY orderkey, partkey, ROLLUP (suppkey, linenumber), CUBE (linenumber)
	at org.testng.Assert.fail(Assert.java:83)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:252)
	at io.trino.testing.AbstractTestAggregations.testGroupingCombinationsAll(AbstractTestAggregations.java:1302)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.trino.testing.QueryFailedException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill5464940820281833041.bin
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:123)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:480)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 16 more
	Suppressed: java.lang.Exception: SQL: SELECT orderkey, partkey, suppkey, linenumber, SUM(CAST(quantity AS BIGINT)) FROM lineitem GROUP BY orderkey, partkey, ROLLUP (suppkey, linenumber), CUBE (linenumber)
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:483)
		... 17 more
Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill5464940820281833041.bin
	at io.trino.spiller.FileHolder.close(FileHolder.java:71)
	at com.google.common.io.Closer.close(Closer.java:218)
	at io.trino.spiller.FileSingleStreamSpiller.close(FileSingleStreamSpiller.java:185)
	at com.google.common.io.Closer.close(Closer.java:218)
	at io.trino.spiller.GenericSpiller.close(GenericSpiller.java:83)
	at com.google.common.io.Closer.close(Closer.java:218)
	at io.trino.operator.aggregation.builder.SpillableHashAggregationBuilder.close(SpillableHashAggregationBuilder.java:241)
	at io.trino.operator.HashAggregationOperator.closeAggregationBuilder(HashAggregationOperator.java:540)
	at io.trino.operator.HashAggregationOperator.getOutput(HashAggregationOperator.java:514)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:737)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:490)
	at io.trino.$gen.Trino_testversion____20220822_170718_13580.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill18354738113694553069.bin
		... 21 more
	Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill18354738113694553069.bin
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at io.trino.spiller.FileHolder.close(FileHolder.java:68)
		... 20 more
	Suppressed: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill11046946133006548061.bin
		... 21 more
	Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill11046946133006548061.bin
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at io.trino.spiller.FileHolder.close(FileHolder.java:68)
		... 20 more
	Suppressed: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill13174353726523252681.bin
		... 21 more
	Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill13174353726523252681.bin
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at io.trino.spiller.FileHolder.close(FileHolder.java:68)
		... 20 more
	Suppressed: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill14716774122335957192.bin
		... 21 more
	Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill14716774122335957192.bin
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at io.trino.spiller.FileHolder.close(FileHolder.java:68)
		... 20 more
	Suppressed: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill17484035528309676989.bin
		... 21 more
	Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill17484035528309676989.bin
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at io.trino.spiller.FileHolder.close(FileHolder.java:68)
		... 20 more
	Suppressed: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill12479036550163316623.bin
		... 21 more
	Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill12479036550163316623.bin
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at io.trino.spiller.FileHolder.close(FileHolder.java:68)
		... 20 more
	Suppressed: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill10415163473297746799.bin
		... 21 more
	Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill10415163473297746799.bin
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at io.trino.spiller.FileHolder.close(FileHolder.java:68)
		... 20 more
	Suppressed: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill6063968503833217352.bin
		... 21 more
	Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill6063968503833217352.bin
		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at io.trino.spiller.FileHolder.close(FileHolder.java:68)
		... 20 more
Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill5464940820281833041.bin
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1152)
	at io.trino.spiller.FileHolder.close(FileHolder.java:68)
	... 20 more
```

**Comment by findepi** [comment]
Looks like something is deleting those tmp spill files before the code is done using them.
Can it be that something is deleting those tmp spill files before _the application_ is done using them?
i.e. can there be some background service which deletes files in /tmp to prevent out of disk space?

cc @nineinchnick @MiguelWeezardo

**Comment by findepi** [comment]
other tests methods eg `TestSpilledAggregations.testSingleDistinctOptimizer` are also affected (https://github.com/trinodb/trino/issues/13849)

**Comment by MiguelWeezardo** [comment]
I haven't heard of any automatic /tmp cleanup process on GitHub runners, but I'll take a closer look in the docs.

**Comment by findepi** [comment]
probably same as https://github.com/trinodb/trino/issues/13288

@MiguelWeezardo see especially https://github.com/trinodb/trino/issues/13288#issuecomment-1240279537

**Comment by findepi** [comment]
Closing as dup of https://github.com/trinodb/trino/issues/13288
