### ISSUE TITLE
CTAS fails on non-lowercase schemas with case-insensitive name matching enabled

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#13826]
In Postgres and SQL Server connectors the follow test added to `TestPostgreSqlCaseInsensitiveMapping`/`TestSqlServerCaseInsensitiveMapping` fails:

```java
@Test
public void testNonLowerCaseSchemaNameCreateTableAsSelect()
        throws Exception
{
    try (AutoCloseable ignore1 = withSchema("NonLowerCaseSchema")) {
        assertUpdate("CREATE TABLE nonlowercaseschema.ctas_table AS SELECT 'a' c", 1);
    }
}
```

with an error: 

```
io.trino.testing.QueryFailedException: This connector does not support renaming tables across schemas

	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:123)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:480)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:323)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:318)
	at io.trino.plugin.jdbc.BaseCaseInsensitiveMappingTest.testNonLowerCaseSchemaNameCreateTableAsSelect(BaseCaseInsensitiveMappingTest.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE nonlowercaseschema.ctas_table AS SELECT 'a' c
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:483)
		... 28 more
Caused by: io.trino.spi.TrinoException: This connector does not support renaming tables across schemas
	at io.trino.plugin.postgresql.PostgreSqlClient.renameTable(PostgreSqlClient.java:367)
	at io.trino.plugin.jdbc.BaseJdbcClient.commitCreateTable(BaseJdbcClient.java:680)
	at io.trino.plugin.jdbc.ForwardingJdbcClient.commitCreateTable(ForwardingJdbcClient.java:196)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$commitCreateTable$27(StatisticsAwareJdbcClient.java:270)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:47)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.commitCreateTable(StatisticsAwareJdbcClient.java:270)
	at io.trino.plugin.jdbc.CachingJdbcClient.commitCreateTable(CachingJdbcClient.java:305)
	at io.trino.plugin.jdbc.CachingJdbcClient.commitCreateTable(CachingJdbcClient.java:305)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.finishCreateTable(DefaultJdbcMetadata.java:719)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishCreateTable(ClassLoaderSafeConnectorMetadata.java:472)
	at io.trino.metadata.MetadataManager.finishCreateTable(MetadataManager.java:847)
	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$4(LocalExecutionPlanner.java:4073)
	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:737)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:490)
	at io.trino.$gen.Trino_testversion____20220824_120645_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

This seems to happen because the output table handle created in `beginCreateTable` and the temporary table handle both have different case for the schema name when `commitCreateTable` executes which ends up calling `renameTable`.

Both Postgres and SQL Server connectors don't support renaming tables across schemas which is why this fails.
We probably need to make sure that both the temporary table handle and the output table handle have the same correct remote schema name.

**Comment by hashhar** [comment]
I personally think time would be better spent by working on #17 instead of "fixing" case-insensitive name matching in the longer run.

**Comment by findepi** [comment]
#17 is the right long term fix, but the existing case-insensitive matching logic will remain with us for some time even after #17 is completed. It shouldn't be too hard to fix this bug.
