### ISSUE TITLE
TestSpilledAggregations.testSingleDistinctOptimizer is flaky

### ISSUE THREAD

**Issue by homar** [trinodb/trino#13849]
Stack trace:

```

2022-08-25T11:57:31.9289797Z [ERROR] io.trino.tests.TestSpilledAggregations.testSingleDistinctOptimizer  Time elapsed: 0.667 s  <<< FAILURE!
2022-08-25T11:57:31.9291177Z java.lang.AssertionError: Execution of 'actual' query failed: SELECT custkey, COUNT(DISTINCT orderstatus) FROM (   SELECT orders.custkey AS custkey, orders.orderstatus AS orderstatus    FROM lineitem JOIN orders ON lineitem.orderkey = orders.orderkey AND orders.orderkey = lineitem.partkey    GROUP BY orders.custkey, orders.orderstatus) GROUP BY custkey
2022-08-25T11:57:31.9291903Z 	at org.testng.Assert.fail(Assert.java:83)
2022-08-25T11:57:31.9292312Z 	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:150)
2022-08-25T11:57:31.9292798Z 	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:106)
2022-08-25T11:57:31.9293358Z 	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:247)
2022-08-25T11:57:31.9293977Z 	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:242)
2022-08-25T11:57:31.9294651Z 	at io.trino.testing.AbstractTestAggregations.testSingleDistinctOptimizer(AbstractTestAggregations.java:256)
2022-08-25T11:57:31.9295400Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-08-25T11:57:31.9295964Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-08-25T11:57:31.9296606Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-08-25T11:57:31.9297132Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-08-25T11:57:31.9297637Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-08-25T11:57:31.9298140Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-08-25T11:57:31.9298565Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-08-25T11:57:31.9298998Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-08-25T11:57:31.9299503Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-08-25T11:57:31.9300011Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-08-25T11:57:31.9300730Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-08-25T11:57:31.9301287Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-08-25T11:57:31.9301708Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-08-25T11:57:31.9302216Z Caused by: io.trino.testing.QueryFailedException: Failed to spill pages
2022-08-25T11:57:31.9302717Z 	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:123)
2022-08-25T11:57:31.9303274Z 	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:480)
2022-08-25T11:57:31.9303791Z 	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:147)
2022-08-25T11:57:31.9304114Z 	... 17 more
2022-08-25T11:57:31.9304827Z 	Suppressed: java.lang.Exception: SQL: SELECT custkey, COUNT(DISTINCT orderstatus) FROM (   SELECT orders.custkey AS custkey, orders.orderstatus AS orderstatus    FROM lineitem JOIN orders ON lineitem.orderkey = orders.orderkey AND orders.orderkey = lineitem.partkey    GROUP BY orders.custkey, orders.orderstatus) GROUP BY custkey
2022-08-25T11:57:31.9305626Z 		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:483)
2022-08-25T11:57:31.9305979Z 		... 18 more
2022-08-25T11:57:31.9306263Z Caused by: io.trino.spi.TrinoException: Failed to spill pages
2022-08-25T11:57:31.9306743Z 	at io.trino.spiller.FileSingleStreamSpiller.writePages(FileSingleStreamSpiller.java:159)
2022-08-25T11:57:31.9307318Z 	at io.trino.spiller.FileSingleStreamSpiller.lambda$spill$0(FileSingleStreamSpiller.java:119)
2022-08-25T11:57:31.9307829Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2022-08-25T11:57:31.9308528Z 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
2022-08-25T11:57:31.9309245Z 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
2022-08-25T11:57:31.9309883Z 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
2022-08-25T11:57:31.9310497Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-08-25T11:57:31.9311037Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-08-25T11:57:31.9311465Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-08-25T11:57:31.9311872Z Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill3118120787555776882.bin
2022-08-25T11:57:31.9312360Z 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
2022-08-25T11:57:31.9312867Z 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
2022-08-25T11:57:31.9313366Z 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
2022-08-25T11:57:31.9313886Z 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
2022-08-25T11:57:31.9314455Z 	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
2022-08-25T11:57:31.9314940Z 	at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
2022-08-25T11:57:31.9315368Z 	at io.trino.spiller.FileHolder.newOutputStream(FileHolder.java:49)
2022-08-25T11:57:31.9315879Z 	at io.trino.spiller.FileSingleStreamSpiller.writePages(FileSingleStreamSpiller.java:145)
2022-08-25T11:57:31.9316246Z 	... 8 more
```

failed here https://github.com/trinodb/trino/pull/13824

**Comment by findepi** [comment]
Can it be the same as https://github.com/trinodb/trino/issues/13778 ?

**Comment by homar** [comment]
Yes i think it is possible

**Comment by findepi** [comment]
Closing in favor of https://github.com/trinodb/trino/issues/13778
