### ISSUE TITLE
Flaky `TestHiveAnalyzeCorruptStatistics.testAnalyzeCorruptColumnStatisticsOnEmptyTable`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#13889]
```
2022-08-26T19:22:50.292-0500	ERROR	pool-3-thread-2	io.trino.testng.services.ProgressLoggingListener	[TEST FAILURE] io.trino.plugin.hive.TestHiveAnalyzeCorruptStatistics.testAnalyzeCorruptColumnStatisticsOnEmptyTable; (took: 2 minutes and 14 seconds)
java.lang.AssertionError: 
Expecting code to raise a throwable.
	at io.trino.plugin.hive.TestHiveAnalyzeCorruptStatistics.testAnalyzeCorruptColumnStatisticsOnEmptyTable(TestHiveAnalyzeCorruptStatistics.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/runs/8111049903?check_suite_focus=true

**Comment by raunaqmorarka** [comment]
https://github.com/trinodb/trino/runs/8214669429?check_suite_focus=true

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/runs/8263699613?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/8265920214?check_suite_focus=true

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/runs/8298217310?check_suite_focus=true

**Comment by vlad-lyutenko** [comment]
https://github.com/trinodb/trino/runs/8302497949?check_suite_focus=true
