### ISSUE TITLE
Flaky `TestSpilledWindowQueries.testWindowsDifferentPartitions`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#13887]
```
2022-08-27T04:05:14.737-0500	ERROR	pool-5-thread-1	io.trino.testng.services.ProgressLoggingListener	[TEST FAILURE] io.trino.tests.TestSpilledWindowQueries.testWindowsDifferentPartitions; (took: 0.3 seconds)
io.trino.testing.QueryFailedException: Failed to read spilled pages
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:123)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:480)
	at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:217)
	at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:212)
	at io.trino.testing.AbstractTestWindowQueries.testWindowsDifferentPartitions(AbstractTestWindowQueries.java:221)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: SQL: SELECT sum(quantity) OVER(PARTITION BY suppkey ORDER BY orderkey),count(discount) OVER(PARTITION BY partkey ORDER BY receiptdate),min(tax) OVER(PARTITION BY suppkey, tax ORDER BY receiptdate)FROM lineitem ORDER BY 1, 2 LIMIT 10
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:483)
		... 16 more
Caused by: io.trino.spi.TrinoException: Failed to read spilled pages
	at io.trino.spiller.FileSingleStreamSpiller.readPages(FileSingleStreamSpiller.java:175)
	at io.trino.spiller.FileSingleStreamSpiller.getSpilledPages(FileSingleStreamSpiller.java:133)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.spiller.GenericSpiller.getSpills(GenericSpiller.java:76)
	at io.trino.operator.WindowOperator$SpillablePagesToPagesIndexes.unspill(WindowOperator.java:833)
	at io.trino.operator.WindowOperator$SpillablePagesToPagesIndexes.fullGroupBuffered(WindowOperator.java:773)
	at io.trino.operator.WindowOperator$SpillablePagesToPagesIndexes.process(WindowOperator.java:736)
	at io.trino.operator.WindowOperator$SpillablePagesToPagesIndexes.process(WindowOperator.java:658)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WindowOperator.getOutput(WindowOperator.java:404)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:737)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:514)
	at io.trino.$gen.Trino_testversion____20220827_090509_37836.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.file.NoSuchFileException: /tmp/trino/spills/spill10109761102785735303.bin
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at io.trino.spiller.FileHolder.newInputStream(FileHolder.java:56)
	at io.trino.spiller.FileSingleStreamSpiller.readPages(FileSingleStreamSpiller.java:169)
	... 36 more
```

https://github.com/trinodb/trino/runs/8049156767

**Comment by findepi** [comment]
Duplicates https://github.com/trinodb/trino/issues/13288
