### ISSUE TITLE
Unable to authenticate Web-UI with JWT 

### ISSUE THREAD

**Issue by jaseemjaskp** [trinodb/trino#13915]
Hi, I am setting up trino-v393 with web UI jwt authentication.
after adding ```web-ui.authentication.type=JWT``` in config.properties
I am unable to run the trinodb server. kindly help to resolve this error.

```

1) [Guice/JitDisabled]: Explicit bindings are required and WebUiAuthenticationFilter is not explicitly bound.
at ResourceSecurityDynamicFeature.<init>(ResourceSecurityDynamicFeature.java:70)
\_ for 3rd parameter webUiAuthenticationFilter
at ServerSecurityModule.setup(ServerSecurityModule.java:57)

1 error

======================
Full classname legend:
======================
ResourceSecurityDynamicFeature: "io.trino.server.security.ResourceSecurityDynamicFeature"
ServerSecurityModule: "io.trino.server.security.ServerSecurityModule"
WebUiAuthenticationFilter: "io.trino.server.ui.WebUiAuthenticationFilter"
========================
End of classname legend:
========================

at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:576)
at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163)
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
at com.google.inject.Guice.createInjector(Guice.java:87)
at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:270)
at io.trino.server.Server.doStart(Server.java:121)
at io.trino.server.Server.lambda$start$0(Server.java:81)
at io.trino.$gen.Trino_381_65_g632b424_dirty____20220830_082937_1.run(Unknown Source)
at io.trino.server.Server.start(Server.java:81)
at io.trino.server.TrinoServer.main(TrinoServer.java:38)
```

**Comment by jaseemjaskp** [comment]
the value of web-ui.authentication.type is case sensitive and it is working with lowercase value 'jwt'
