### ISSUE TITLE
Flaky `TestIcebergGcsConnectorSmokeTest.testDeleteRowsConcurrently`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#13995]
```
Error:  Tests run: 112, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,204.025 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.iceberg.TestIcebergGcsConnectorSmokeTest.testDeleteRowsConcurrently  Time elapsed: 120.014 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently() didn't finish within the time-out 120000
	at java.base@17.0.4/sun.nio.ch.Net.poll(Native Method)
	at java.base@17.0.4/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
	at java.base@17.0.4/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:285)
	at java.base@17.0.4/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
	at java.base@17.0.4/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base@17.0.4/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base@17.0.4/java.net.Socket$SocketInputStream.read(Socket.java:976)
	at app//okio.Okio$2.read(Okio.java:140)
	at app//okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at app//okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
	at app//okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
	at app//okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
	at app//okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
	at app//okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
	at app//okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at app//okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at app//okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at app//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at app//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at app//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at app//okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at app//okhttp3.RealCall.execute(RealCall.java:81)
	at app//io.trino.client.JsonResponse.execute(JsonResponse.java:124)
	at app//io.trino.client.StatementClientV1.advance(StatementClientV1.java:378)
	at app//io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:99)
	at app//io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:86)
	at app//io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:468)
	at app//io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest$$Lambda$5410/0x0000000802493000.execute(Unknown Source)
	at app//io.trino.testing.sql.TestTable.close(TestTable.java:130)
	at app//io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently(BaseIcebergConnectorSmokeTest.java:137)
	at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.4/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.4/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base@17.0.4/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base@17.0.4/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.4/java.lang.Thread.run(Thread.java:833)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:  io.trino.plugin.iceberg.TestIcebergGcsConnectorSmokeTest.testDeleteRowsConcurrently
Error:    Run 1: TestIcebergGcsConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:137 » ThreadTimeout
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
[INFO]   Run 4: PASS
```

https://github.com/trinodb/trino/runs/8197101407

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/4160134251/jobs/7196879430

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/actions/runs/4352631358/jobs/7606779942

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4469322142/jobs/7851886796
```
[INFO] 
Error:  Failures: 
Error:  io.trino.plugin.iceberg.TestIcebergGcsConnectorSmokeTest.testDeleteRowsConcurrently
[INFO]   Run 1: PASS
Error:    Run 2: TestIcebergGcsConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:144 » ThreadTimeout
Error:    Run 3: TestIcebergGcsConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:144 » ThreadTimeout
Error:    Run 4: TestIcebergGcsConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:144 » ThreadTimeout
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4482014417/jobs/7879616846?pr=16650

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/4551140249/jobs/8025266680?pr=16771

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/4606870125/jobs/8143814680

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4753718303/jobs/8447054079?pr=16825

```
[INFO] 
Error:  Failures: 
Error:  io.trino.plugin.iceberg.TestIcebergGcsConnectorSmokeTest.testDeleteRowsConcurrently
Error:    Run 1: TestIcebergGcsConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:131->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:131 » ThreadTimeout Method io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently() didn't finish within the time-out 120000
Error:    Run 2: TestIcebergGcsConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:106 » ThreadTimeout Method io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently() didn't finish within the time-out 120000
Error:    Run 3: TestIcebergGcsConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:131->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:131 » ThreadTimeout Method io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently() didn't finish within the time-out 120000
Error:    Run 4: TestIcebergGcsConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:133 » ThreadTimeout Method io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently() didn't finish within the time-out 120000
[INFO] 
Error:    TestIcebergGlueCatalogAccessOperations.testCreateTableAsSelect:177->assertGlueMetastoreApiInvocations:494 Expected: 
		1 more occurrences of GET_TABLE
[INFO] 
Error:  Tests run: 244, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4766640955/jobs/8475850958?pr=17175

**Comment by findepi** [comment]
`TestIcebergAbfsConnectorSmokeTest` looks affected as well
```
Error:  Tests run: 364, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,197.211 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.iceberg.TestIcebergAbfsConnectorSmokeTest.testDeleteRowsConcurrently  Time elapsed: 6.841 s  <<< FAILURE!
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2(BaseIcebergConnectorSmokeTest.java:157)
	at com.google.common.collect.Streams$1Splitr.tryAdvance(Streams.java:469)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently(BaseIcebergConnectorSmokeTest.java:160)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```
