### ISSUE TITLE
Pinot connector throws `Segment query returned 'xxx' rows per split` for `ORDER BY ... LIMIT`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#14045]
```
SELECT regionkey FROM nation ORDER BY name LIMIT 3

io.trino.plugin.pinot.PinotException: Segment query returned '12' rows per split, maximum allowed is '11' rows. with query "SELECT "regionkey", "name" FROM nation_REALTIME  LIMIT 12"
	at io.trino.plugin.pinot.client.PinotDataFetcher$RowCountChecker.checkTooManyRows(PinotDataFetcher.java:72)
	at io.trino.plugin.pinot.client.PinotGrpcDataFetcher.getNextDataTable(PinotGrpcDataFetcher.java:109)
	at io.trino.plugin.pinot.PinotSegmentPageSource.getNextPage(PinotSegmentPageSource.java:127)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:737)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:490)
	at io.trino.$gen.Trino_testversion____20220907_225235_36.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ebyhr** [comment]
cc:  @elonazoulay @xiangfu0
