### ISSUE TITLE
`MERGE` on Hive transactional table on hdp2.6 fails

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#14054]
While trying to enable table redirection awareness for `MERGE` (see https://github.com/trinodb/trino/pull/14055) I tested on `io.trino.tests.product.iceberg.TestIcebergRedirectionToHive` the `MERGE` operation 

```
testing/bin/ptl test  run --environment singlenode-hive-iceberg-redirections --config 'config-default'  -- -t io.trino.tests.product.iceberg.TestIcebergRedirectionToHive.testMerge
```

```
@Test(groups = {HIVE_ICEBERG_REDIRECTIONS, PROFILE_SPECIFIC_TESTS})
    public void testMerge()
    {
        String sourceTableName = "hive_merge_source_" + randomTableSuffix();
        String targetTableName = "hive_merge_target_" + randomTableSuffix();
        String hiveSourceTableName = "hive.default." + sourceTableName;
        String hiveTargetTableName = "hive.default." + targetTableName;
        String icebergSourceTableName = "iceberg.default." + sourceTableName;
        String icebergTargetTableName = "iceberg.default." + targetTableName;

        createHiveTable(hiveSourceTableName, true);
        // MERGE on Hive is supported only for transactional tables
        onTrino().executeQuery(
                "CREATE TABLE " + hiveTargetTableName + " WITH (transactional = true, format = 'ORC', bucketed_by = ARRAY['regionkey'], bucket_count = 5) " +
                        " AS " +
                        "SELECT nationkey, name, comment, regionkey FROM tpch.tiny.nation " +
                        "WITH NO DATA");

        assertThat(onTrino().executeQuery("""
                    MERGE INTO %s t USING %s s
                    ON t.nationkey = s.nationkey
                    WHEN NOT MATCHED
                        THEN INSERT (nationkey, name, regionkey, comment)
                                VALUES (s.nationkey, s.name, s.regionkey, s.comment)
                """.formatted(icebergTargetTableName, icebergSourceTableName)
        )).updatedRowsCountIsEqualTo(25);
        assertResultsEqual(
                onTrino().executeQuery("TABLE " + hiveSourceTableName),
                onTrino().executeQuery("TABLE " + hiveTargetTableName));

        onTrino().executeQuery("DROP TABLE " + hiveSourceTableName);
        onTrino().executeQuery("DROP TABLE " + hiveTargetTableName);
    }

```

Exception stacktrace 

```
tests               | 2022-09-08 16:31:23 SEVERE: Failure cause:
tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20220908_104602_00003_tjign): Internal error processing lock
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:60)
tests               | 	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
tests               | 	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:62)
tests               | 	at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
tests               | 	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:67)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:60)
tests               | 	at io.trino.tests.product.iceberg.TestIcebergRedirectionToHive.testMerge(TestIcebergRedirectionToHive.java:246)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
tests               | Caused by: java.sql.SQLException: Query failed (#20220908_104602_00003_tjign): Internal error processing lock
tests               | 	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
tests               | 	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:285)
tests               | 	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:61)
tests               | 	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
tests               | 	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 	... 22 more
tests               | 	Suppressed: java.lang.Exception: Query: MERGE INTO iceberg.default.hive_merge_target_dnn2rhf7e8qh t USING iceberg.default.hive_merge_source_r1g127x1uqd3 s
tests               |     ON t.nationkey = s.nationkey
tests               |     WHEN NOT MATCHED
tests               |         THEN INSERT (nationkey, name, regionkey, comment)
tests               |                 VALUES (s.nationkey, s.name, s.regionkey, s.comment)
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
tests               | 		... 23 more
tests               | Caused by: io.trino.spi.TrinoException: Internal error processing lock
tests               | 	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.acquireLock(ThriftHiveMetastore.java:1623)
tests               | 	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.acquireSharedLock(ThriftHiveMetastore.java:1566)
tests               | 	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.acquireTableWriteLock(ThriftHiveMetastore.java:1534)
tests               | 	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.acquireTableWriteLock(BridgingHiveMetastore.java:512)
tests               | 	at io.trino.plugin.hive.metastore.ForwardingHiveMetastore.acquireTableWriteLock(ForwardingHiveMetastore.java:405)
tests               | 	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.acquireTableWriteLock(CachingHiveMetastore.java:982)
tests               | 	at io.trino.plugin.hive.HiveMetastoreClosure.acquireTableWriteLock(HiveMetastoreClosure.java:363)
tests               | 	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.acquireTableWriteLock(SemiTransactionalHiveMetastore.java:3793)
tests               | 	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.lambda$beginOperation$43(SemiTransactionalHiveMetastore.java:1409)
tests               | 	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.makeHiveTransaction(SemiTransactionalHiveMetastore.java:1443)
tests               | 	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.beginOperation(SemiTransactionalHiveMetastore.java:1408)
tests               | 	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.beginMerge(SemiTransactionalHiveMetastore.java:1396)
tests               | 	at io.trino.plugin.hive.HiveMetadata.beginInsertOrMerge(HiveMetadata.java:1920)
tests               | 	at io.trino.plugin.hive.HiveMetadata.beginMerge(HiveMetadata.java:1831)
tests               | 	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.beginMerge(ClassLoaderSafeConnectorMetadata.java:1046)
tests               | 	at io.trino.metadata.MetadataManager.beginMerge(MetadataManager.java:1063)
tests               | 	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:301)
tests               | 	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:218)
tests               | 	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:109)
tests               | 	at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
tests               | 	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:81)
tests               | 	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:72)
tests               | 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
tests               | 	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:72)
tests               | 	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:37)
tests               | 	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:21)
tests               | 	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
tests               | 	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
tests               | 	at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:31)
tests               | 	at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:94)
tests               | 	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:247)
tests               | 	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:222)
tests               | 	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:217)
tests               | 	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:469)
tests               | 	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:450)
tests               | 	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:391)
tests               | 	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
tests               | 	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
tests               | 	at io.trino.$gen.Trino_394_128_g44178f7_dirty____20220908_104525_2.run(Unknown Source)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
tests               | 	Suppressed: java.lang.Exception: Current plan:
tests               |                 Output[columnNames = [rows]]
tests               |                 │   Layout: [rows:bigint]
tests               |                 │   Estimates: 
tests               |                 └─ TableCommit[target = hive:default:hive_merge_target_dnn2rhf7e8qh buckets=5]
tests               |                    │   Layout: [rows:bigint]
tests               |                    │   Estimates: 
tests               |                    └─ LocalExchange[partitioning = SINGLE]
tests               |                       │   Layout: [partialrows:bigint, fragment:varbinary]
tests               |                       │   Estimates: 
tests               |                       └─ RemoteExchange[type = GATHER]
tests               |                          │   Layout: [partialrows:bigint, fragment:varbinary]
tests               |                          │   Estimates: 
tests               |                          └─ MergeWriter[table = hive:default:hive_merge_target_dnn2rhf7e8qh buckets=5]
tests               |                             │   Layout: [partialrows:bigint, fragment:varbinary]
tests               |                             │   Estimates: 
tests               |                             └─ LocalExchange[partitioning = SINGLE]
tests               |                                │   Layout: [nationkey:bigint, name:varchar(25), comment:varchar(152), regionkey:bigint, operation:tinyint, field:row(originalTransaction bigint, bucket integer, rowId bigint), insert_from_update:tinyint]
tests               |                                │   Estimates: 
tests               |                                └─ RemoteExchange[type = REPARTITION]
tests               |                                   │   Layout: [nationkey:bigint, name:varchar(25), comment:varchar(152), regionkey:bigint, operation:tinyint, field:row(originalTransaction bigint, bucket integer, rowId bigint), insert_from_update:tinyint]
tests               |                                   │   Estimates: 
tests               |                                   └─ MergeProcessor[]
tests               |                                      │   Layout: [nationkey:bigint, name:varchar(25), comment:varchar(152), regionkey:bigint, operation:tinyint, field:row(originalTransaction bigint, bucket integer, rowId bigint), insert_from_update:tinyint]
tests               |                                      │   Estimates: 
tests               |                                      │   target: hive:default:hive_merge_target_dnn2rhf7e8qh buckets=5
tests               |                                      │   merge row column: merge_row
tests               |                                      │   row id column: field
tests               |                                      │   redistribution columns: [regionkey]
tests               |                                      │   data columns: [nationkey, name, comment, regionkey]
tests               |                                      └─ Filter[filterPredicate = (CASE WHEN ((NOT "is_distinct") AND (NOT ("unique_id" IS NULL))) THEN CAST(fail(119, VARCHAR 'One MERGE target table row matched more than one source row') AS boolean) ELSE true END)]
tests               |                                         │   Layout: [regionkey:bigint, unique_id:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint), merge_row:row(nationkey bigint, name varchar(25), comment varchar(152), regionkey bigint, boolean, tinyint, integer), case_number:integer, is_distinct:boolean]
tests               |                                         │   Estimates: 
tests               |                                         └─ Project[]
tests               |                                            │   Layout: [regionkey:bigint, unique_id:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint), merge_row:row(nationkey bigint, name varchar(25), comment varchar(152), regionkey bigint, boolean, tinyint, integer), case_number:integer, is_distinct:boolean]
tests               |                                            │   Estimates: 
tests               |                                            └─ MarkDistinct[distinct = [unique_id:bigint, case_number:integer], marker = is_distinct, hash = [$hashvalue]]
tests               |                                               │   Layout: [regionkey:bigint, unique_id:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint), merge_row:row(nationkey bigint, name varchar(25), comment varchar(152), regionkey bigint, boolean, tinyint, integer), case_number:integer, $hashvalue:bigint, is_distinct:boolean]
tests               |                                               │   Estimates: 
tests               |                                               └─ LocalExchange[partitioning = HASH, hashColumn = [$hashvalue], arguments = ["unique_id", "case_number"]]
tests               |                                                  │   Layout: [regionkey:bigint, unique_id:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint), merge_row:row(nationkey bigint, name varchar(25), comment varchar(152), regionkey bigint, boolean, tinyint, integer), case_number:integer, $hashvalue:bigint]
tests               |                                                  │   Estimates: 
tests               |                                                  └─ RemoteExchange[type = REPARTITION, hashColumn = [$hashvalue_7]]
tests               |                                                     │   Layout: [regionkey:bigint, unique_id:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint), merge_row:row(nationkey bigint, name varchar(25), comment varchar(152), regionkey bigint, boolean, tinyint, integer), case_number:integer, $hashvalue_7:bigint]
tests               |                                                     │   Estimates: 
tests               |                                                     └─ Project[]
tests               |                                                        │   Layout: [regionkey:bigint, unique_id:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint), merge_row:row(nationkey bigint, name varchar(25), comment varchar(152), regionkey bigint, boolean, tinyint, integer), case_number:integer, $hashvalue_12:bigint]
tests               |                                                        │   Estimates: 
tests               |                                                        │   $hashvalue_12 := combine_hash(combine_hash(bigint '0', COALESCE("$operator$hash_code"("unique_id"), 0)), COALESCE("$operator$hash_code"("case_number"), 0))
tests               |                                                        └─ Project[]
tests               |                                                           │   Layout: [regionkey:bigint, unique_id:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint), merge_row:row(nationkey bigint, name varchar(25), comment varchar(152), regionkey bigint, boolean, tinyint, integer), case_number:integer]
tests               |                                                           │   Estimates: 
tests               |                                                           │   case_number := "merge_row"[7]
tests               |                                                           └─ Project[]
tests               |                                                              │   Layout: [regionkey:bigint, unique_id:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint), merge_row:row(nationkey bigint, name varchar(25), comment varchar(152), regionkey bigint, boolean, tinyint, integer)]
tests               |                                                              │   Estimates: 
tests               |                                                              │   merge_row := (CASE WHEN ("present" IS NULL) THEN ROW ("nationkey_0", "name_1", "comment_2", "regionkey_3", (NOT ("present" IS NULL)), TINYINT '1', 0) ELSE ROW (CAST(null AS bigint), CAST(null AS varchar(25)), CAST(null AS varchar(152)), CAST(null AS bigint), (NOT ("present" IS NULL)), TINYINT '-1', -1) END)
tests               |                                                              └─ LeftJoin[criteria = ("nationkey_0" = "nationkey"), hash = [$hashvalue_8, $hashvalue_9], distribution = REPLICATED]
tests               |                                                                 │   Layout: [nationkey_0:bigint, name_1:varchar(25), comment_2:varchar(152), regionkey_3:bigint, unique_id:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint), regionkey:bigint, present:boolean]
tests               |                                                                 │   Estimates: 
tests               |                                                                 │   Distribution: REPLICATED
tests               |                                                                 ├─ ScanProject[table = hive:default:hive_merge_source_r1g127x1uqd3]
tests               |                                                                 │      Layout: [nationkey_0:bigint, name_1:varchar(25), comment_2:varchar(152), regionkey_3:bigint, $hashvalue_8:bigint]
tests               |                                                                 │      Estimates: 
tests               |                                                                 │      $hashvalue_8 := combine_hash(bigint '0', COALESCE("$operator$hash_code"("nationkey_0"), 0))
tests               |                                                                 │      comment_2 := comment:varchar(152):REGULAR
tests               |                                                                 │      name_1 := name:varchar(25):REGULAR
tests               |                                                                 │      nationkey_0 := nationkey:bigint:REGULAR
tests               |                                                                 │      regionkey_3 := regionkey:bigint:PARTITION_KEY
tests               |                                                                 │          :: [[0], [1], [2], [3], [4]]
tests               |                                                                 └─ LocalExchange[partitioning = SINGLE]
tests               |                                                                    │   Layout: [nationkey:bigint, unique_id:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint), regionkey:bigint, present:boolean, $hashvalue_9:bigint]
tests               |                                                                    │   Estimates: 
tests               |                                                                    └─ RemoteExchange[type = REPLICATE]
tests               |                                                                       │   Layout: [nationkey:bigint, unique_id:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint), regionkey:bigint, present:boolean, $hashvalue_10:bigint]
tests               |                                                                       │   Estimates: 
tests               |                                                                       └─ Project[]
tests               |                                                                          │   Layout: [nationkey:bigint, unique_id:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint), regionkey:bigint, present:boolean, $hashvalue_11:bigint]
tests               |                                                                          │   Estimates: 
tests               |                                                                          │   present := true
tests               |                                                                          │   $hashvalue_11 := combine_hash(bigint '0', COALESCE("$operator$hash_code"("nationkey"), 0))
tests               |                                                                          └─ AssignUniqueId[]
tests               |                                                                             │   Layout: [nationkey:bigint, regionkey:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint), unique_id:bigint]
tests               |                                                                             │   Estimates: 
tests               |                                                                             └─ TableScan[table = hive:default:hive_merge_target_dnn2rhf7e8qh buckets=5]
tests               |                                                                                    Layout: [nationkey:bigint, regionkey:bigint, field:row(originalTransaction bigint, bucket integer, rowId bigint)]
tests               |                                                                                    Estimates: 
tests               |                                                                                    nationkey := nationkey:bigint:REGULAR
tests               |                                                                                    field := $row_id:struct<originalTransaction:bigint,bucket:int,rowId:bigint>:SYNTHESIZED
tests               |                                                                                    regionkey := regionkey:bigint:REGULAR
tests               | 
tests               | 		at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:100)
tests               | 		... 12 more
tests               | Caused by: org.apache.thrift.TApplicationException: Internal error processing lock
tests               | 	at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
tests               | 	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
tests               | 	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_lock(ThriftHiveMetastore.java:5443)
tests               | 	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.lock(ThriftHiveMetastore.java:5430)
tests               | 	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.acquireLock(ThriftHiveMetastoreClient.java:628)
tests               | 	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.lambda$acquireLock$39(FailureAwareThriftMetastoreClient.java:363)
tests               | 	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.runWithHandle(FailureAwareThriftMetastoreClient.java:447)
tests               | 	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.acquireLock(FailureAwareThriftMetastoreClient.java:363)
tests               | 	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$acquireLock$58(ThriftHiveMetastore.java:1593)
tests               | 	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
tests               | 	at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
tests               | 	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.acquireLock(ThriftHiveMetastore.java:1591)
tests               | 	... 41 more
tests               | 	Suppressed: org.apache.thrift.TApplicationException: Internal error processing lock
tests               | 		... 53 more
```

**Comment by findinpath** [comment]
Please analyze whether a fix or simply disallowing the operation for hive 2.x is appropriate in this case.

cc : @djsstarburst

**Comment by Praveen2112** [comment]
Does HDP 2.6 supports transaction tables ? I think transaction tables are supported from 3.0+ version.

**Comment by findepi** [comment]
Trino doesn't support Hive ACID tables with HMS version < 3
(This is what HDP 2.6 provides.)

I think MERGE is tested with hive ACID on Hive 3. @djsstarburst please correct me if I am wrong.

**Comment by djsstarburst** [comment]
> I think MERGE is tested with hive ACID on Hive 3

Correct.

**Comment by findepi** [comment]
> Does HDP 2.6 supports transaction tables ? I think transaction tables are supported from 3.0+ version.

@Praveen2112  Hive ACID was added around Hive 1.2

but we support Hive ACID after Hive 3 changes to it

> Please analyze whether a fix or simply disallowing the operation for hive 2.x is appropriate in this case.

Disallowing.
But we don't know the HMS version, so we don't disallow explicitly.
(Same for INSERT, etc.)
