### ISSUE TITLE
Postgresql connector - convert timetz to time(6), unsupported_type_handling cause errors

### ISSUE THREAD

**Issue by xsgao-github** [trinodb/trino#14156]
Slacks: https://trinodb.slack.com/archives/CP1MUNEUX/p1663284984896799

I have a Postgresql table, which has a “time with timezone” column. It shows up in Trino as time(6) column. But when I execute select against it, I got error:

`Cannot convert the column of type TIMETZ to requested type java.time.LocalTime.`

I put unsupported_type_handling=IGNORE in my properties file, as suggested by https://trino.io/docs/current/connector/postgresql.html#postgresql-array-type-handling, but I got error when restarting Trino/SEP:

```
2022-09-15T20:07:45.696-0400	ERROR	main	io.trino.server.Server	Configuration errors:

1) Error: Configuration property 'postgresql.unsupported_type_handling' was not used

1 error
io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Configuration property 'postgresql.unsupported_type_handling' was not used

1 error
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:234)
	at io.trino.plugin.jdbc.JdbcConnectorFactory.create(JdbcConnectorFactory.java:78)
	at io.trino.connector.DefaultCatalogFactory.createConnector(DefaultCatalogFactory.java:201)
	at io.trino.connector.DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:123)
	at io.trino.connector.LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:44)
	at io.trino.connector.StaticCatalogManager.loadInitialCatalogs(StaticCatalogManager.java:139)
	at io.trino.server.Server.doStart(Server.java:139)
	at io.trino.server.Server.lambda$start$0(Server.java:88)
	at io.trino.$gen.Trino_dev____20220916_000736_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:88)
	at com.starburstdata.trino.StarburstDevelopmentServer.main(StarburstDevelopmentServer.java:32)
```

**Comment by xsgao-github** [comment]
It may be worth spinning another issue for unsupported-type-handling. SEP
server failed to start if I put this property in catalog.properties file.

**Comment by hashhar** [comment]
@xsgao-github please add stack trace for the failure when doing the SELECT on that column as well. That's the more relevant part.

**Comment by mosabua** [comment]
Also .. please verify but from what i know the property is just `unsupported_type_handling` ...

**Comment by hashhar** [comment]
Yup, I was able to get it to work - don't run into the issue mentioned.

The other issue (@xsgao-github Please try to keep issues focused on a single issue - in this case ideally it could've been two separate issues) of being unable to read a value seems data-dependent. I can't reproduce it yet.

@xsgao-github Would be useful if you can point out some small self-contained dataset which lead to this error.

**Comment by xsgao-github** [comment]
@hashhar Here is the script to create a table and insert one row in postgresql.

```
CREATE TABLE public.category_ext (
	c_timetz timetz -- Trino (as of 394) does not support timetz -- '00:11:00.123456 GMT'::timetz, '24:00:00.000000 );
)

insert into public.category_ext (c_timetz) values ('12:34:56.123456'::timetz)
```

My Postgresql is version 12.

**Comment by findepi** [comment]
@xsgao-github just curious, what's your use-case for using TIMETZ data type in PostgreSQL?

**Comment by findepi** [comment]
@xsgao-github thanks for sharing.
I think the rarity of the "time with time zone" is what caused us not to add proper support for it.

**Comment by xsgao-github** [comment]
> Also .. please verify but from what i know the property is just `unsupported_type_handling` ..

Adding this property did not break Trino. Must be something else caused this error yesterday.

**Comment by maratbakiev2** [comment]
Hi guys! I've faced with the same error.
I have a table in postgres named cities, where there is a column named time_zone, which just resembled the time zone of the city. When I ran select * from cities I got 
`SQL Error [67108864]: Query failed (#20230210_131417_00015_nkymb): Cannot convert the column of type TIMETZ to requested type java.time.LocalTime.`
The full error trace that DBeaver shows is
`
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [67108864]: Query failed (#20230210_131417_00015_nkymb): Cannot convert the column of type TIMETZ to requested type java.time.LocalTime.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.nextRow(JDBCResultSetImpl.java:183)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:823)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:920)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3805)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5067)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Query failed (#20230210_131417_00015_nkymb): Cannot convert the column of type TIMETZ to requested type java.time.LocalTime.
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:295)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:255)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Unknown Source)
	at io.trino.jdbc.TrinoResultSet$AsyncIterator.lambda$new$1(TrinoResultSet.java:180)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.trino.spi.TrinoException: Cannot convert the column of type TIMETZ to requested type java.time.LocalTime.
	at io.trino.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:305)
	at io.trino.plugin.jdbc.JdbcRecordCursor.getLong(JdbcRecordCursor.java:205)
	at io.trino.spi.connector.RecordPageSource.getNextPage(RecordPageSource.java:106)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:752)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:519)
	at io.trino.$gen.Trino_405____20230210_130831_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.postgresql.util.PSQLException: Cannot convert the column of type TIMETZ to requested type java.time.LocalTime.
	at org.postgresql.jdbc.PgResultSet.getLocalTime(PgResultSet.java:778)
	at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:3758)
	at io.trino.plugin.postgresql.PostgreSqlClient.lambda$timeColumnMapping$15(PostgreSqlClient.java:1076)
	at io.trino.plugin.jdbc.JdbcRecordCursor.getLong(JdbcRecordCursor.java:202)
	... 14 more
`
then I've added a line
`unsupported-type-handling=CONVERT_TO_VARCHAR` into source.properties file but the error was the same.
May you add a logic that if any error in type conversion occurs Trino just shows the column in varchar type?
My use case for using timetz column is just to keep the info on local timezone of the city itself.

**Comment by maratbakiev2** [comment]
@hashhar @findepi what do you think about adding the type mapping of postgres `timetz` column to trino `time with time zone`
