### ISSUE TITLE
Flaky test TestSystemConnector.testQueryDuringAnalysisIsCaptured

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#14170]
https://github.com/trinodb/trino/actions/runs/3068889672/jobs/4956920919

```
Error:  Tests run: 3099, Failures: 1, Errors: 0, Skipped: 246, Time elapsed: 1,473.717 s <<< FAILURE! - in TestSuite
Error:  io.trino.connector.system.runtime.TestSystemConnector.testQueryDuringAnalysisIsCaptured  Time elapsed: 0.571 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at io.trino.connector.system.runtime.TestSystemConnector.testQueryDuringAnalysisIsCaptured(TestSystemConnector.java:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by findepi** [comment]
This looks like a potential test error

the query state is FINISHED, but the future from

```java
Future<?> queryFuture = executor.submit(() -> {
    getQueryRunner().execute(format("EXPLAIN SELECT 1 AS %s FROM test_table", testQueryId));
});
```

isn't done yet.
in fact, it doesn't have to be.

**Comment by findepi** [comment]
Hopefully fixed by https://github.com/trinodb/trino/pull/14171. Let's reopen if not.
