### ISSUE TITLE
[trino-394]connect to phoenix5 error : InaccessibleObjectException: Unable to make static boolean java.nio.Bits.unaligned

### ISSUE THREAD

**Issue by wc99** [trinodb/trino#14226]
i use trino-394 try to connect to phoenix5(hbase:2.0  phoenix:5.0)
but when trino server server.log show error:
2022-09-20T17:57:20.846+0800    INFO    main    Bootstrap       phoenix.connection-url                                     ----         jdbc:phoenix:172.29.15.246:2181:/hbase
2022-09-20T17:57:20.847+0800    INFO    main    Bootstrap       phoenix.max-scans-per-split                                20           20                                      Maximum number of HBase scans that will be performed in a single split.
2022-09-20T17:57:20.847+0800    INFO    main    Bootstrap       phoenix.config.resources                                   []           [//opt/pi/trino/etc/hbase-site.xml]
2022-09-20T17:57:21.104+0800    WARN    main    org.apache.hadoop.util.NativeCodeLoader Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2022-09-20T17:57:21.313+0800    WARN    main    org.apache.hadoop.hbase.util.UnsafeAvailChecker java.nio.Bits#unaligned() check failed.Unsafe based read/write of primitive types won't be used
java.lang.reflect.InaccessibleObjectException: Unable to make static boolean java.nio.Bits.unaligned() accessible: module java.base does not "opens java.nio" to unnamed module @2e0f3405
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at org.apache.hadoop.hbase.util.UnsafeAvailChecker.<clinit>(UnsafeAvailChecker.java:161)
        at org.apache.hadoop.hbase.util.Bytes.<clinit>(Bytes.java:134)
        at org.apache.hadoop.hbase.io.encoding.DataBlockEncoding.<init>(DataBlockEncoding.java:72)
        at org.apache.hadoop.hbase.io.encoding.DataBlockEncoding.<clinit>(DataBlockEncoding.java:35)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.lang.Class.getEnumConstantsShared(Class.java:3837)
        at java.base/java.lang.System$2.getEnumConstantsShared(System.java:2284)
        at java.base/java.util.EnumSet.getUniverse(EnumSet.java:408)
        at java.base/java.util.EnumSet.noneOf(EnumSet.java:111)
        at java.base/java.util.EnumSet.allOf(EnumSet.java:132)
        at io.trino.spi.session.PropertyMetadata.enumProperty(PropertyMetadata.java:265)
        at io.trino.spi.session.PropertyMetadata.enumProperty(PropertyMetadata.java:260)
        at io.trino.plugin.phoenix5.PhoenixTableProperties.<init>(PhoenixTableProperties.java:122)
        at io.trino.plugin.phoenix5.PhoenixTableProperties$$FastClassByGuice$$29787327.GUICE$TRAMPOLINE(<generated>)
        at io.trino.plugin.phoenix5.PhoenixTableProperties$$FastClassByGuice$$29787327.apply(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:270)
        at io.trino.plugin.phoenix5.PhoenixConnectorFactory.create(PhoenixConnectorFactory.java:66)
        at io.trino.connector.DefaultCatalogFactory.createConnector(DefaultCatalogFactory.java:201)
        at io.trino.connector.DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:123)
        at io.trino.connector.LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:44)
        at io.trino.connector.StaticCatalogManager.loadInitialCatalogs(StaticCatalogManager.java:139)
        at io.trino.server.Server.doStart(Server.java:139)
        at io.trino.server.Server.lambda$start$0(Server.java:88)
        at io.trino.$gen.Trino_394____20220920_095703_1.run(Unknown Source)
        at io.trino.server.Server.start(Server.java:88)
        at io.trino.server.TrinoServer.main(TrinoServer.java:38)

2022-09-20T17:57:21.625+0800    INFO    main    io.airlift.bootstrap.LifeCycleManager   Life cycle starting...
2022-09-20T17:57:21.626+0800    INFO    main    io.airlift.bootstrap.LifeCycleManager   Life cycle started
2022-09-20T17:57:21.627+0800    INFO    main    io.trino.connector.StaticCatalogManager -- Added catalog phonix using connector phoenix5 --
2022-09-20T17:57:21.633+0800    INFO    main    io.trino.security.AccessControlManager  Using system access control: default
2022-09-20T17:57:21.653+0800    INFO    main    io.trino.server.Server  ======== SERVER STARTED ========

trino server has java 14 installed
[trino_pi@ha-node2 bin]$ java -version
```
openjdk version "17.0.4.1" 2022-08-12 LTS
OpenJDK Runtime Environment Zulu17.36+17-CA (build 17.0.4.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu17.36+17-CA (build 17.0.4.1+1-LTS, mixed mode, sharing)
```

phoenix.properties
```
connector.name=phoenix5
phoenix.connection-url=jdbc:phoenix:172.29.15.246:2181:/hbase
phoenix.config.resources=//opt/pi/trino/etc/hbase-site.xml
```
help me please!

**Comment by findepi** [comment]
cc @wendigo

**Comment by wendigo** [comment]
@wc99 It's only a warning. Does it actually fail for any of the queries?

**Comment by wc99** [comment]
> @wc99 It's only a warning. Does it actually fail for any of the queries?
most connectors to the trino server are normal ,but then phoenix connector are abnormal.
when i try to connect phoenix ,the server return error info !
```
2022-09-23T09:54:54.840+0800    ERROR   stage-scheduler io.trino.execution.StageStateMachine    Stage 20220923_015454_00002_4mhzy.2 failed
io.trino.spi.TrinoException: ERROR 2007 (INT09): Outdated jars. Newer Phoenix clients can't communicate with older Phoenix servers. Client version: 5.1.0; Server version: 5.0.0 The following servers require an updated phoenix-[version]-server.jar to be put in the classpath of HBase
        at io.trino.plugin.jdbc.BaseJdbcClient.getTableNames(BaseJdbcClient.java:198)
        at io.trino.plugin.jdbc.DefaultJdbcMetadata.listTables(DefaultJdbcMetadata.java:654)
        at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.listTables(ClassLoaderSafeConnectorMetadata.java:288)
        at io.trino.metadata.MetadataManager.listTables(MetadataManager.java:500)
        at io.trino.metadata.MetadataListing.listTables(MetadataListing.java:99)
        at io.trino.connector.system.jdbc.TableJdbcTable.cursor(TableJdbcTable.java:106)
        at io.trino.connector.system.SystemPageSourceProvider$1.cursor(SystemPageSourceProvider.java:129)
        at io.trino.split.MappedRecordSet.cursor(MappedRecordSet.java:53)
        at io.trino.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
        at io.trino.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:108)
        at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:62)
        at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:268)
        at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:196)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
        at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$3(WorkProcessorUtils.java:219)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
        at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$4(WorkProcessorUtils.java:234)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
        at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:150)
        at io.trino.operator.Driver.processInternal(Driver.java:411)
        at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
        at io.trino.operator.Driver.tryWithLock(Driver.java:706)
        at io.trino.operator.Driver.process(Driver.java:306)
        at io.trino.operator.Driver.processForDuration(Driver.java:277)
        at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:737)
        at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
        at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:514)
        at io.trino.$gen.Trino_394____20220923_015414_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLException: ERROR 2007 (INT09): Outdated jars. Newer Phoenix clients can't communicate with older Phoenix servers. Client version: 5.1.0; Server version: 5.0.0 The following servers require an updated phoenix-[version]-server.jar to be put in the classpath of HBase
        at org.apache.phoenix.exception.SQLExceptionCode$Factory$1.newException(SQLExceptionCode.java:606)
        at org.apache.phoenix.exception.SQLExceptionInfo.buildException(SQLExceptionInfo.java:217)
        at org.apache.phoenix.query.ConnectionQueryServicesImpl.checkClientServerCompatibility(ConnectionQueryServicesImpl.java:1693)
        at org.apache.phoenix.query.ConnectionQueryServicesImpl.ensureTableCreated(ConnectionQueryServicesImpl.java:1462)
        at org.apache.phoenix.query.ConnectionQueryServicesImpl.createTable(ConnectionQueryServicesImpl.java:1913)
        at org.apache.phoenix.schema.MetaDataClient.createTableInternal(MetaDataClient.java:3074)
        at org.apache.phoenix.schema.MetaDataClient.createTable(MetaDataClient.java:1105)
        at org.apache.phoenix.compile.CreateTableCompiler$CreateTableMutationPlan.execute(CreateTableCompiler.java:420)
        at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:441)
        at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:423)
        at org.apache.phoenix.call.CallRunner.run(CallRunner.java:53)
        at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:422)
        at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:410)
        at org.apache.phoenix.jdbc.PhoenixStatement.executeUpdate(PhoenixStatement.java:1967)
        at org.apache.phoenix.query.ConnectionQueryServicesImpl$12.call(ConnectionQueryServicesImpl.java:3267)
        at org.apache.phoenix.query.ConnectionQueryServicesImpl$12.call(ConnectionQueryServicesImpl.java:3230)
        at org.apache.phoenix.util.PhoenixContextExecutor.call(PhoenixContextExecutor.java:76)
        at org.apache.phoenix.query.ConnectionQueryServicesImpl.init(ConnectionQueryServicesImpl.java:3230)
        at org.apache.phoenix.jdbc.PhoenixDriver.getConnectionQueryServices(PhoenixDriver.java:255)
        at org.apache.phoenix.jdbc.PhoenixEmbeddedDriver.createConnection(PhoenixEmbeddedDriver.java:144)
        at org.apache.phoenix.jdbc.PhoenixDriver.connect(PhoenixDriver.java:221)
        at io.trino.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:65)
        at io.trino.plugin.jdbc.ConfiguringConnectionFactory.openConnection(ConfiguringConnectionFactory.java:39)
        at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:42)
        at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
        at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:42)
        at io.trino.plugin.jdbc.LazyConnectionFactory.lambda$openConnection$0(LazyConnectionFactory.java:45)
        at io.trino.plugin.jdbc.LazyConnectionFactory$LazyConnection.getDelegate(LazyConnectionFactory.java:76)
        at io.trino.plugin.jdbc.ForwardingConnection.getMetaData(ForwardingConnection.java:117)
        at io.trino.plugin.jdbc.BaseJdbcClient.getTables(BaseJdbcClient.java:869)
        at io.trino.plugin.phoenix5.PhoenixClient.getTables(PhoenixClient.java:362)
        at io.trino.plugin.jdbc.BaseJdbcClient.getTableNames(BaseJdbcClient.java:184)
        ... 37 more
```

**Comment by wc99** [comment]
Hbase version：2.0
Phoenix version ： 5.0
i noticed that document says trino only support 5.1.0 ……

**Comment by ebyhr** [comment]
Closing as the Phoenix version is unsupported as https://github.com/trinodb/trino/pull/6865#issuecomment-779493200
Please feel free to reopen or file a new issue if you face the issue in supported version.
