### ISSUE TITLE
Roles with special characters are created but can't be granted

### ISSUE THREAD

**Issue by mdesmet** [trinodb/trino#14252]
Expected behavior:

When using a role surrounded by quotes, I expect quoted identifier rules to respected and input be accepted as is. It seems the role can be created but not granted.

```
SET ROLE
trino> create role "test;test=test" in hive
    -> ;
CREATE ROLE
trino> show roles;
 Role 
------
(0 rows)

Query 20220922_105716_00007_q3nf4, FINISHED, 1 node
Splits: 1 total, 1 done (100,00%)
0,38 [0 rows, 0B] [0 rows/s, 0B/s]

trino> show roles in hive;
      Role      
----------------
 admin          
 public         
 test;test=test 
(3 rows)

Query 20220922_105736_00008_q3nf4, FINISHED, 1 node
Splits: 7 total, 7 done (100,00%)
0,50 [0 rows, 0B] [0 rows/s, 0B/s]

trino> set role admin in hive
    -> ;
SET ROLE
trino> grant role "test;test=test" to user admin
    -> ;
Query 20220922_105957_00012_q3nf4 failed: line 1:12: mismatched input '"test;test=test"'. Expecting: ',', 'TO'
grant role "test;test=test" to user admin
```

**Comment by hashhar** [comment]
cc: @dain

**Comment by findepi** [comment]
> trino> grant role "test;test=test" to user admin
>     -> ;
> Query 20220922_105957_00012_q3nf4 failed: line 1:12: mismatched input '"test;test=test"'. Expecting: ',', 'TO'
> grant role "test;test=test" to user admin


@mdesmet can you try without "role", `GRANT "test;test=test" TO USER admn`?

also, can you please paste the full stacktrace?

**Comment by mdesmet** [comment]
The statement `grant role "test;test=test" to user admin` results in following exception

```
io.trino.sql.parser.ParsingException: line 1:12: mismatched input '"test;test=test"'. Expecting: ',', 'TO'
	at io.trino.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:109)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
	at io.trino.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:5048)
	at io.trino.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:320)
	at io.trino.sql.parser.SqlParser.invokeParser(SqlParser.java:145)
	at io.trino.sql.parser.SqlParser.createStatement(SqlParser.java:85)
	at io.trino.execution.QueryPreparer.prepareQuery(QueryPreparer.java:55)
	at io.trino.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:180)
	at io.trino.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:149)
	at io.trino.$gen.Trino_393____20220923_115331_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.antlr.v4.runtime.InputMismatchException: undefined
	at io.trino.sql.parser.SqlParser$2.recoverInline(SqlParser.java:128)
	at org.antlr.v4.runtime.Parser.match(Parser.java:206)
	at io.trino.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:3755)
	... 10 more
```

The statement `grant "test;test=test" to user admin` in this exception:

```
io.trino.spi.TrinoException: line 1:1: Role 'test;test=test' does not exist
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.metadata.MetadataUtil.checkRoleExists(MetadataUtil.java:216)
	at io.trino.execution.GrantRolesTask.execute(GrantRolesTask.java:90)
	at io.trino.execution.GrantRolesTask.execute(GrantRolesTask.java:43)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_393____20220923_115331_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by hashhar** [comment]
Shouldn't it be `grant "test;test=test" to user admin in hive`?

**Comment by mdesmet** [comment]
You are right. So the issue is only with `GRANT role` statement as that one supports multiple roles but doesn't respect quoted identifier rules.

**Comment by hashhar** [comment]
I don't see a `GRANT ROLE` statement though - there's just `GRANT privilege` (https://trino.io/docs/current/sql/grant.html) and `GRANT <role>` (https://trino.io/docs/current/sql/grant-roles.html).

I do think however that the `GRANT ROLES` heading is misleading/confusing.

**Comment by mdesmet** [comment]
Right. I think this can be closed. It works as expected.

**Comment by hashhar** [comment]
cc: @mosabua for ideas to improve the documentation (heading on the `GRANT ROLES` page since there is no `GRANT ROLES` statements - there's just `GRANT` but with different syntax/purpose.
