### ISSUE TITLE
The GC stall makes it unusable and can only be restarted

### ISSUE THREAD

**Issue by duhanmin** [trinodb/trino#14337]
```
2022-09-28T03:30:39.207Z	WARN	20220928_033028_03802_xb7p8.31.1-1-12431	com.amazon.ws.emr.hadoop.fs.identity.HadoopFileSystemOwner	found no group information for ******* (auth:PROXY) via trino (auth:SIMPLE), using **@** as primary group
2022-09-28T03:30:39.207Z	INFO	20220928_033028_03802_xb7p8.31.1-1-12431	com.amazon.ws.emr.hadoop.fs.s3n.S3NativeFileSystem	Opening 's3://lb-bi-data-warehouse/ods/lb_order/lb_order_histories/5a8df65d306d4ee9b5ee98154354c5e7.parquet' for reading
2022-09-28T03:31:00.999Z	ERROR	Announcer-4	io.airlift.discovery.client.Announcer	Expected service announcement after 8000.00ms, but announcement was delayed 13.83s
2022-09-28T03:31:01.024Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 2572194ms, stopped 6969ms: 49.75GB -> 36.41GB
2022-09-28T03:31:16.323Z	ERROR	Announcer-0	io.airlift.discovery.client.Announcer	Expected service announcement after 8000.00ms, but announcement was delayed 15.32s
2022-09-28T03:31:16.327Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 6346ms, stopped 8917ms: 49.50GB -> 46.02GB
2022-09-28T03:31:26.171Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.74:8889/v1/info/state has not returned in 20.15s
2022-09-28T03:31:26.195Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 1091ms, stopped 8818ms: 49.51GB -> 47.23GB
2022-09-28T03:31:35.829Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 606ms, stopped 8949ms: 49.49GB -> 47.77GB
2022-09-28T03:31:45.349Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.74:8889/v1/info/state has not returned in 19.18s
2022-09-28T03:31:45.354Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 535ms, stopped 9087ms: 49.55GB -> 48.17GB
2022-09-28T03:31:54.845Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 371ms, stopped 9120ms: 49.57GB -> 48.46GB
2022-09-28T03:32:04.452Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.74:8889/v1/info/state has not returned in 19.10s
2022-09-28T03:32:04.452Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.220:8889/v1/info/state has not returned in 19.09s
2022-09-28T03:32:04.455Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 303ms, stopped 9309ms: 49.52GB -> 47.00GB
2022-09-28T03:32:04.520Z	WARN	20220928_033028_03802_xb7p8.31.1-2-12542	com.amazon.ws.emr.hadoop.fs.identity.HadoopFileSystemOwner	found no group information for ******(auth:PROXY) via trino (auth:SIMPLE), using  *** as primary group
2022-09-28T03:32:04.520Z	INFO	20220928_033028_03802_xb7p8.31.1-2-12542	com.amazon.ws.emr.hadoop.fs.s3n.S3NativeFileSystem	Opening 's3://lb-bi-data-warehouse/ods/lb_order/lb_order_histories/5a8df65d306d4ee9b5ee98154354c5e7.parquet' for reading
2022-09-28T03:32:14.303Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 880ms, stopped 8969ms: 49.44GB -> 47.85GB
2022-09-28T03:32:23.659Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.74:8889/v1/info/state has not returned in 19.21s
2022-09-28T03:32:23.664Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 451ms, stopped 8908ms: 49.51GB -> 48.21GB
2022-09-28T03:32:33.039Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 383ms, stopped 8993ms: 49.59GB -> 48.52GB
2022-09-28T03:32:42.203Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.74:8889/v1/info/state has not returned in 18.54s
2022-09-28T03:32:42.214Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 286ms, stopped 8881ms: 49.59GB -> 48.73GB
2022-09-28T03:32:51.254Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.74:8889/v1/info/state has not returned in 27.59s
2022-09-28T03:32:51.256Z	WARN	http-client-node-manager-scheduler-1	io.trino.metadata.RemoteNodeState	Error fetching node state from http://*******.74:8889/v1/info/state: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
2022-09-28T03:32:51.257Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 245ms, stopped 8807ms: 49.55GB -> 48.92GB
2022-09-28T03:33:09.647Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 194ms, stopped 9018ms: 49.54GB -> 49.05GB
2022-09-28T03:33:09.647Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 146ms, stopped 9033ms: 49.52GB -> 49.16GB
2022-09-28T03:33:27.868Z	WARN	HikariPool-1 housekeeper	com.zaxxer.hikari.pool.HikariPool	HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=45s665ms663µs262ns).
2022-09-28T03:33:27.870Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 109ms, stopped 8997ms: 49.50GB -> 49.24GB
2022-09-28T03:33:27.871Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 111ms, stopped 9006ms: 49.55GB -> 49.31GB
2022-09-28T03:33:37.020Z	WARN	http-client-node-manager-scheduler-1	io.trino.metadata.RemoteNodeState	Error fetching node state from http://*******.74:8889/v1/info/state: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
2022-09-28T03:33:37.027Z	ERROR	Announcer-0	io.airlift.discovery.client.Announcer	Expected service announcement after 8000.00ms, but announcement was delayed 36.55s
2022-09-28T03:33:46.287Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.220:8889/v1/info/state has not returned in 45.82s
2022-09-28T03:33:55.349Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 51ms, stopped 9101ms: 49.47GB -> 49.35GB
2022-09-28T03:33:55.349Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 90ms, stopped 9176ms: 49.56GB -> 49.39GB
2022-09-28T03:33:55.349Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 46ms, stopped 9016ms: 49.48GB -> 49.41GB
2022-09-28T03:33:55.350Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.74:8889/v1/info/state has not returned in 18.33s
2022-09-28T03:33:55.350Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.220:8889/v1/info/state has not returned in 54.88s
2022-09-28T03:33:55.361Z	WARN	http-client-node-manager-scheduler-1	io.trino.metadata.RemoteNodeState	Error fetching node state from http://*******.220:8889/v1/info/state: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
2022-09-28T03:34:04.529Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.74:8889/v1/info/state has not returned in 27.51s
2022-09-28T03:34:04.530Z	WARN	http-client-node-manager-scheduler-1	io.trino.metadata.RemoteNodeState	Error fetching node state from http://*******.74:8889/v1/info/state: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
2022-09-28T03:34:04.531Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 82ms, stopped 9099ms: 49.57GB -> 49.45GB
2022-09-28T03:34:22.774Z	ERROR	Announcer-1	io.airlift.discovery.client.Announcer	Expected service announcement after 8000.00ms, but announcement was delayed 18.24s
2022-09-28T03:35:07.569Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 48ms, stopped 9028ms: 49.54GB -> 49.47GB
2022-09-28T03:35:07.569Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 60ms, stopped 9109ms: 49.59GB -> 49.50GB
2022-09-28T03:35:07.569Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 36ms, stopped 8930ms: 49.59GB -> 49.52GB
2022-09-28T03:35:07.569Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 45ms, stopped 8932ms: 49.58GB -> 49.53GB
2022-09-28T03:35:07.570Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 24ms, stopped 8872ms: 49.56GB -> 49.54GB
2022-09-28T03:35:07.570Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 36ms, stopped 8739ms: 49.57GB -> 49.54GB
2022-09-28T03:35:07.570Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 33ms, stopped 9147ms: 49.60GB -> 49.55GB
2022-09-28T03:35:16.688Z	WARN	http-client-node-manager-scheduler-1	io.trino.metadata.RemoteNodeState	Error fetching node state from http://*******.220:8889/v1/info/state: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
2022-09-28T03:35:52.841Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 34ms, stopped 9086ms: 49.58GB -> 49.56GB
2022-09-28T03:35:52.842Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 22ms, stopped 9014ms: 49.59GB -> 49.56GB
2022-09-28T03:35:52.842Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 64ms, stopped 9131ms: 49.66GB -> 49.58GB
2022-09-28T03:35:52.842Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 25ms, stopped 8967ms: 49.61GB -> 49.58GB
2022-09-28T03:36:01.834Z	ERROR	Announcer-1	io.airlift.discovery.client.Announcer	Expected service announcement after 8000.00ms, but announcement was delayed 54.26s
2022-09-28T03:36:01.834Z	WARN	HikariPool-1 housekeeper	com.zaxxer.hikari.pool.HikariPool	HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=45s18ms142µs806ns).
2022-09-28T03:36:11.039Z	WARN	http-client-node-manager-scheduler-1	io.trino.metadata.RemoteNodeState	Error fetching node state from http://*******.74:8889/v1/info/state: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
2022-09-28T03:36:28.868Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.44:8889/v1/info/state has not returned in 144.34s
2022-09-28T03:36:28.868Z	WARN	http-client-node-manager-scheduler-1	io.trino.metadata.RemoteNodeState	Error fetching node state from http://*******.44:8889/v1/info/state: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
2022-09-28T03:35:52.842Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 24ms, stopped 8904ms: 49.62GB -> 49.59GB
2022-09-28T03:36:46.850Z	WARN	HikariPool-1 housekeeper	com.zaxxer.hikari.pool.HikariPool	HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m21s113ms754µs630ns).
2022-09-28T03:36:46.850Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 20ms, stopped 8974ms: 49.62GB -> 49.59GB
2022-09-28T03:36:46.850Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 67ms, stopped 9138ms: 49.72GB -> 49.61GB
2022-09-28T03:36:46.851Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 30ms, stopped 8863ms: 49.71GB -> 49.63GB
2022-09-28T03:36:46.851Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 33ms, stopped 8903ms: 49.66GB -> 49.63GB
2022-09-28T03:36:46.851Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 11ms, stopped 9045ms: 49.66GB -> 49.63GB
2022-09-28T03:36:46.851Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 31ms, stopped 8896ms: 49.66GB -> 49.63GB
2022-09-28T03:37:05.050Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.74:8889/v1/info/state has not returned in 54.01s
2022-09-28T03:37:05.050Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.220:8889/v1/info/state has not returned in 108.36s
2022-09-28T03:37:05.050Z	WARN	http-client-node-manager-scheduler-1	io.trino.metadata.RemoteNodeState	Error fetching node state from http://*******.220:8889/v1/info/state: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
2022-09-28T03:37:14.035Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 14ms, stopped 9026ms: 49.67GB -> 49.64GB
2022-09-28T03:37:14.035Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 53ms, stopped 9103ms: 49.73GB -> 49.66GB
2022-09-28T03:37:14.036Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 32ms, stopped 8956ms: 49.72GB -> 49.67GB
2022-09-28T03:37:23.114Z	WARN	http-client-node-manager-40	io.trino.metadata.RemoteNodeState	Error fetching node state from http://*******.74:8889/v1/info/state: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
2022-09-28T03:37:41.239Z	WARN	http-client-node-manager-35	io.trino.metadata.RemoteNodeState	Error fetching node state from http://*******.44:8889/v1/info/state: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
2022-09-28T03:37:59.131Z	WARN	HikariPool-1 housekeeper	com.zaxxer.hikari.pool.HikariPool	HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=45s300ms787µs217ns).
2022-09-28T03:37:59.131Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 48ms, stopped 9032ms: 49.73GB -> 49.68GB
2022-09-28T03:37:59.131Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 20ms, stopped 9009ms: 49.71GB -> 49.68GB
2022-09-28T03:37:59.132Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 35ms, stopped 9061ms: 49.72GB -> 49.69GB
2022-09-28T03:37:59.132Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 20ms, stopped 8942ms: 49.72GB -> 49.69GB
2022-09-28T03:37:59.132Z	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 34ms, stopped 8895ms: 49.72GB -> 49.70GB
2022-09-28T03:38:25.997Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.74:8889/v1/info/state has not returned in 62.88s
2022-09-28T03:38:25.998Z	WARN	node-state-poller-0	io.trino.metadata.RemoteNodeState	Node state update request to http://*******.220:8889/v1/info/state has not returned in 80.95s
2022-09-28T03:38:25.998Z	ERROR	http-worker-13730	io.trino.server.InternalAuthenticationManager	Internal authentication failed
io.jsonwebtoken.ExpiredJwtException: JWT expired at 2022-09-28T03:38:24Z. Current time: 2022-09-28T03:38:25Z, a difference of 1998 milliseconds.  Allowed clock skew: 0 milliseconds.
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:385)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:481)
	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:541)
	at io.trino.server.InternalAuthenticationManager.parseJwt(InternalAuthenticationManager.java:128)
	at io.trino.server.InternalAuthenticationManager.handleInternalRequest(InternalAuthenticationManager.java:88)
	at io.trino.server.security.ResourceSecurityDynamicFeature$InternalOnlyRequestFilter.filter(ResourceSecurityDynamicFeature.java:206)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:269)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.base/java.lang.Thread.run(Thread.java:829)


```

**Comment by duhanmin** [comment]
jvm.config 
```
-verbose:class
-server
-Xmx53369263620
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:OnOutOfMemoryError=kill -9 %p
-XX:ReservedCodeCacheSize=150M
-Djava.library.path=/usr/lib/hadoop/lib/native/:/usr/lib/hadoop-lzo/lib/native/:/usr/lib/
-Djdk.attach.allowAttachSelf=true
--add-exports=java.base/jdk.internal.util=ALL-UNNAMED 
--add-opens=java.base/jdk.internal.util=ALL-UNNAMED
--add-exports=java.base/jdk.internal.loader=ALL-UNNAMED
--add-opens=java.base/jdk.internal.loader=ALL-UNNAMED
--add-exports=java.base/jdk.internal.module=ALL-UNNAMED
--add-opens=java.base/jdk.internal.module=ALL-UNNAMED
--add-exports=java.base/java.lang.module=ALL-UNNAMED
--add-opens=java.base/java.lang.module=ALL-UNNAMED
--add-exports=java.base/jdk.internal.util.jar=ALL-UNNAMED
--add-opens=java.base/jdk.internal.util.jar=ALL-UNNAMED
--add-exports=java.base/jdk.internal.reflect=ALL-UNNAMED
--add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED
--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED
-Dcom.sun.management.jmxremote=true
-Dcom.sun.management.jmxremote.port=9080
-Dcom.sun.management.jmxremote.rmi.port=9081
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.host=localhost
```

config.properties 
```
coordinator=false
node-scheduler.include-coordinator=false
discovery.uri=http://ip-**********.ap-east-1.compute.internal:8889
http-server.threads.max=500
sink.max-buffer-size=1GB
query.max-memory=45875MB
query.max-memory-per-node=26684631810B
query.max-total-memory-per-node=32021558172B
query.max-history=40
query.min-expire-age=30m
query.client.timeout=30m
query.stage-count-warning-threshold=100
query.max-stage-count=150
http-server.http.port=8889
http-server.log.path=/var/log/trino/http-request.log
http-server.log.max-size=67108864B
http-server.log.max-history=5
log.max-size=268435456B
log.max-history=5
jmx.rmiregistry.port = 9080
jmx.rmiserver.port = 9081
exchange.http-client.max-requests-queued-per-destination=5120
exchange.http-client.max-connections-per-server=5120
iterative-optimizer-timeout=10m
```

**Comment by ubyyj** [comment]
hit the same issue on trino 377, with 200GB heap size.

**Comment by duhanmin** [comment]
@ubyyj Problem solved. OOM caused by oversized Parquet file

**Comment by charlessong-lyft** [comment]
hey @duhanmin can you share more details about "oversized parquet file" and how you resolved it?

**Comment by siminyou** [comment]
> hey @duhanmin can you share more details about "oversized parquet file" and how you resolved it?

I have similar memory issue, @duhanmin would you mind providing more details on how it got resolved? TIA!
