### ISSUE TITLE
Selecting hidden columns fails to open split in Hudi

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#14341]
We should throw column not found exception if we don't support them. 

```
SELECT "$path" FROM hudi.tests.hudi_cow_pt_tbl;

Query 20220928_074646_00017_n54ug failed: Error opening Hudi split file:/var/folders/8s/dkvf18z55lj_9yxhy1n54sph0000gn/T/TrinoTest15358788863231304430/data/hudi_cow_pt_tbl/dt=2021-12-09/hh=10/719c3273-2805-4124-b1ac-e980dada85bf-0_0-27-1215_20220906063435640.parquet (offset=0, length=435204): column type must be REGULAR: $path:string:SYNTHESIZED
io.trino.spi.TrinoException: Error opening Hudi split file:/var/folders/8s/dkvf18z55lj_9yxhy1n54sph0000gn/T/TrinoTest15358788863231304430/data/hudi_cow_pt_tbl/dt=2021-12-09/hh=10/719c3273-2805-4124-b1ac-e980dada85bf-0_0-27-1215_20220906063435640.parquet (offset=0, length=435204): column type must be REGULAR: $path:string:SYNTHESIZED
	at io.trino.plugin.hudi.HudiPageSourceProvider.createPageSource(HudiPageSourceProvider.java:268)
	at io.trino.plugin.hudi.HudiPageSourceProvider.createPageSource(HudiPageSourceProvider.java:165)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:49)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:62)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:308)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:736)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:515)
	at io.trino.$gen.Trino_testversion____20220928_074154_36.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: column type must be REGULAR: $path:string:SYNTHESIZED
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
	at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createParquetReaderColumns(ParquetPageSourceFactory.java:440)
	at io.trino.plugin.hudi.HudiPageSourceProvider.createPageSource(HudiPageSourceProvider.java:227)
	... 16 more
```

Below columns cause this issue
* `$path`
* `$file_size`
* `$file_modified_time`
* `$partition`

**Comment by codope** [comment]
I see. Let me fix this.
