### ISSUE TITLE
Fix broken main method in Hudi query runners

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#14340]
Both `HudiQueryRunner` and `S3HudiQueryRunner` fail:
```
java.nio.file.NoSuchFileException: src/test/resources/hudi-testing-data
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3918)
	at java.base/java.nio.file.Files.walk(Files.java:3973)
	at io.trino.plugin.hudi.testing.ResourceHudiTablesInitializer.copyDir(ResourceHudiTablesInitializer.java:137)
	at io.trino.plugin.hudi.testing.ResourceHudiTablesInitializer.initializeTables(ResourceHudiTablesInitializer.java:72)
	at io.trino.plugin.hudi.HudiQueryRunner.createHudiQueryRunner(HudiQueryRunner.java:83)
	at io.trino.plugin.hudi.HudiQueryRunner.main(HudiQueryRunner.java:94)
```

**Comment by findepi** [comment]
cc @codope @7c00

**Comment by codope** [comment]
Checking.
