### ISSUE TITLE
io.trino.tests.product.hive.TestRoles is flaky

### ISSUE THREAD

**Issue by arhimondr** [trinodb/trino#14358]
Example stack trace:

```
io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20220928_165020_00245_9au7n): line 1:1: Table 'hive.default.test_table' of unsupported type already exists
2022-09-28T16:50:21.0382363Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
2022-09-28T16:50:21.0382928Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2022-09-28T16:50:21.0383519Z tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:60)
2022-09-28T16:50:21.0384035Z tests               | 	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
2022-09-28T16:50:21.0384569Z tests               | 	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:62)
2022-09-28T16:50:21.0385085Z tests               | 	at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
2022-09-28T16:50:21.0385577Z tests               | 	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
2022-09-28T16:50:21.0386084Z tests               | 	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:67)
2022-09-28T16:50:21.0386619Z tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:60)
2022-09-28T16:50:21.0387229Z tests               | 	at io.trino.tests.product.hive.TestRoles.testAdminCanAddColumnToAnyTable(TestRoles.java:652)
2022-09-28T16:50:21.0387865Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-09-28T16:50:21.0388487Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-09-28T16:50:21.0389186Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-09-28T16:50:21.0389748Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-09-28T16:50:21.0390299Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-09-28T16:50:21.0391105Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-09-28T16:50:21.0391601Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-09-28T16:50:21.0392098Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-09-28T16:50:21.0392659Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-09-28T16:50:21.0393215Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-09-28T16:50:21.0393773Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-09-28T16:50:21.0394370Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-09-28T16:50:21.0394898Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-09-28T16:50:21.0395648Z tests               | Caused by: java.sql.SQLException: Query failed (#20220928_165020_00245_9au7n): line 1:1: Table 'hive.default.test_table' of unsupported type already exists
2022-09-28T16:50:21.0396254Z tests               | 	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
2022-09-28T16:50:21.0396814Z tests               | 	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:319)
2022-09-28T16:50:21.0397284Z tests               | 	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:62)
2022-09-28T16:50:21.0397928Z tests               | 	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
2022-09-28T16:50:21.0398408Z tests               | 	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
2022-09-28T16:50:21.0398975Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
2022-09-28T16:50:21.0399587Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
2022-09-28T16:50:21.0399964Z tests               | 	... 22 more
2022-09-28T16:50:21.0400348Z tests               | 	Suppressed: java.lang.Exception: Query: CREATE TABLE hive.default.test_table (foo BIGINT)
2022-09-28T16:50:21.0400931Z tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
2022-09-28T16:50:21.0401369Z tests               | 		... 23 more
2022-09-28T16:50:21.0401953Z tests               | Caused by: io.trino.spi.TrinoException: line 1:1: Table 'hive.default.test_table' of unsupported type already exists
2022-09-28T16:50:21.0402564Z tests               | 	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
2022-09-28T16:50:21.0403203Z tests               | 	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
2022-09-28T16:50:21.0403807Z tests               | 	at io.trino.execution.CreateTableTask.internalExecute(CreateTableTask.java:135)
2022-09-28T16:50:21.0404335Z tests               | 	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:119)
2022-09-28T16:50:21.0404846Z tests               | 	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:85)
2022-09-28T16:50:21.0405397Z tests               | 	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
2022-09-28T16:50:21.0405962Z tests               | 	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
2022-09-28T16:50:21.0406529Z tests               | 	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
2022-09-28T16:50:21.0407026Z tests               | 	at io.trino.$gen.Trino_397_82_g7e4134d____20220928_164355_2.run(Unknown Source)
2022-09-28T16:50:21.0407530Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-09-28T16:50:21.0408207Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-09-28T16:50:21.0408700Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by arhimondr** [comment]
Should be fixed by https://github.com/trinodb/trino/pull/14323
