### ISSUE TITLE
TestIcebergParquetConnectorTest.testStatsBasedRepartitionDataOnCtas flaky

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#14368]
```
2022-09-28T22:57:30.2515805Z [ERROR] io.trino.plugin.iceberg.TestIcebergParquetConnectorTest.testStatsBasedRepartitionDataOnCtas  Time elapsed: 7.062 s  <<< FAILURE!
2022-09-28T22:57:30.2516388Z java.lang.AssertionError: 
2022-09-28T22:57:30.2516952Z [Rows for query [SELECT count(*) FROM "repartition_SELECTDISTINCTorderkeycustkeyorderstatusFROMtpchtinyordersctas_orderstatus_5cjf604goo$files"]] 
2022-09-28T22:57:30.2517416Z Expecting:
2022-09-28T22:57:30.2517597Z   <(3)>
2022-09-28T22:57:30.2517929Z to contain exactly in any order:
2022-09-28T22:57:30.2518150Z   <[(9)]>
2022-09-28T22:57:30.2518355Z elements not found:
2022-09-28T22:57:30.2518554Z   <(9)>
2022-09-28T22:57:30.2518754Z and elements not expected:
2022-09-28T22:57:30.2518964Z   <(3)>
2022-09-28T22:57:30.2519077Z 
2022-09-28T22:57:30.2519332Z 	at io.trino.sql.query.QueryAssertions$QueryAssert.lambda$matches$2(QueryAssertions.java:383)
2022-09-28T22:57:30.2519827Z 	at io.trino.sql.query.QueryAssertions$QueryAssert.matches(QueryAssertions.java:370)
2022-09-28T22:57:30.2520530Z 	at io.trino.sql.query.QueryAssertions$QueryAssert.matches(QueryAssertions.java:365)
2022-09-28T22:57:30.2521140Z 	at io.trino.plugin.iceberg.BaseIcebergConnectorTest.testRepartitionData(BaseIcebergConnectorTest.java:4182)
2022-09-28T22:57:30.2521971Z 	at io.trino.plugin.iceberg.BaseIcebergConnectorTest.lambda$testStatsBasedRepartitionData$16(BaseIcebergConnectorTest.java:4139)
2022-09-28T22:57:30.2522587Z 	at io.trino.testing.assertions.Assert.assertEventually(Assert.java:77)
2022-09-28T22:57:30.2523199Z 	at io.trino.testing.assertions.Assert.assertEventually(Assert.java:68)
2022-09-28T22:57:30.2523680Z 	at io.trino.testing.assertions.Assert.assertEventually(Assert.java:62)
2022-09-28T22:57:30.2524338Z 	at io.trino.plugin.iceberg.BaseIcebergConnectorTest.testStatsBasedRepartitionData(BaseIcebergConnectorTest.java:4138)
2022-09-28T22:57:30.2525178Z 	at io.trino.plugin.iceberg.BaseIcebergConnectorTest.testStatsBasedRepartitionDataOnCtas(BaseIcebergConnectorTest.java:4110)
2022-09-28T22:57:30.2525873Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-09-28T22:57:30.2526437Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-09-28T22:57:30.2527089Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-09-28T22:57:30.2527613Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-09-28T22:57:30.2528116Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-09-28T22:57:30.2528617Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-09-28T22:57:30.2529044Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-09-28T22:57:30.2529491Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-09-28T22:57:30.2529990Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-09-28T22:57:30.2530496Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-09-28T22:57:30.2531326Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-09-28T22:57:30.2531970Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-09-28T22:57:30.2532478Z 	at java.base/java.lang.Thread.run(Thread.java:833)
```

Observed https://github.com/trinodb/trino/actions/runs/3146868604/jobs/5116286188

cc: @findepi

**Comment by findepi** [comment]
Might be same as https://github.com/trinodb/trino/issues/11140

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/3152488100/jobs/5128906441
