### ISSUE TITLE
ClassLoader issue using plugin aggregate function in window accumulator: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by georgewfisher** [trinodb/trino#14486]
I'm seeing exceptions caused by ClassLoaders when using a plugin aggregator function plugin inside a window function. The issue is similar to the issue mentioned on [this Slack thread](https://trinodb.slack.com/archives/CP1MUNEUX/p1640390600083200?thread_ts=1640349840.080000&cid=CP1MUNEUX).

Specifically, during this call in AccumulatorCompiler it is using the ClassLoader for the AccumulatorCompiler class, not the ClassLoader for the aggregation function state. This works for aggregation functions within Trino, but those that are plugins do not work.
`Class<? extends WindowAccumulator> windowAccumulatorClass = defineClass(definition, WindowAccumulator.class, callSiteBinder.getBindings(), classLoader);`

The exception I am getting is this:
```
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: io/gefisher/trino/operator/aggregation/state/TestAggregatorState
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2053)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
        at com.google.common.cache.ForwardingCache.get(ForwardingCache.java:55)
        at io.trino.collect.cache.CacheUtils.uncheckedCacheGet(CacheUtils.java:28)
...
Caused by: java.lang.NoClassDefFoundError: io/gefisher/trino/operator/aggregation/state/TestAggregatorState
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at com.google.common.reflect.Reflection.initialize(Reflection.java:64)
        at io.airlift.bytecode.ClassGenerator.defineClasses(ClassGenerator.java:177)
        at io.airlift.bytecode.ClassGenerator.defineClass(ClassGenerator.java:117)
        at io.trino.util.CompilerUtils.defineClass(CompilerUtils.java:63)
        at io.trino.util.CompilerUtils.defineClass(CompilerUtils.java:57)
        at io.trino.operator.aggregation.AccumulatorCompiler.generateWindowAccumulatorClass(AccumulatorCompiler.java:287)
        at io.trino.operator.window.AggregationWindowFunctionSupplier.<init>(AggregationWindowFunctionSupplier.java:40)
        at io.trino.sql.planner.LocalExecutionPlanner$Visitor.lambda$getWindowFunctionImplementation$5(LocalExecutionPlanner.java:1194)
```

Do we need a similar fix to this? https://github.com/trinodb/trino/pull/10408

I propose we do something like this in `AccumulatorCompiler.generateWindowAccumulatorClass(...)`. This works:
```java
List<ClassLoader> classLoaders = metadata.getAccumulatorStateDescriptors().stream()
                .map(stateDescriptor-> stateDescriptor.getStateInterface().getClassLoader())
                .distinct()
                .collect(Collectors.toList());
if (classLoaders.size() != 1) {
    throw new TrinoException(StandardErrorCode.FUNCTION_IMPLEMENTATION_ERROR, "Window accumulator function state interface does not have a single class loader.");
}

DynamicClassLoader classLoader = new DynamicClassLoader(classLoaders.stream().findFirst().get(), AccumulatorCompiler.class.getClassLoader());
```

* Is this an issue? Or is there a workaround?
* Can I send out a PR to fix this?
* Is there a preference for how to fix this more cleanly than my suggestion above?

**Comment by georgewfisher** [comment]
The fix works to address this issue, thank you! Tested with my aggregation function plugin.

This issue can be closed once the PR lands.

**Comment by findepi** [comment]
Relates to https://github.com/trinodb/trino/pull/10346 (https://github.com/trinodb/trino/issues/10341), https://github.com/trinodb/trino/pull/10408.
