### ISSUE TITLE
java.io.EOFException Trino -> Pinot 

### ISSUE THREAD

**Issue by Airliquide76** [trinodb/trino#14501]
Hi I'm facing an issue on trino <-> pinot connections. 

Trino V393 -> Java 17
Pinot  0.11.0 -> Java 11

Got a java.io.EOFException in trino errors logs. 
```
ERROR	nioEventLoopGroup-2-1	org.apache.pinot.core.transport.DataTableHandler	Caught exception while deserializing data table of size: 1813585 from server: IPOFSERVER_R
java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:398)
	at org.apache.pinot.core.common.datatable.DataTableImplV3.deserializeMetadata(DataTableImplV3.java:360)
	at org.apache.pinot.core.common.datatable.DataTableImplV3.<init>(DataTableImplV3.java:173)
	at org.apache.pinot.core.common.datatable.DataTableFactory.getDataTable(DataTableFactory.java:37)
	at org.apache.pinot.core.transport.DataTableHandler.channelRead0(DataTableHandler.java:67)
	at org.apache.pinot.core.transport.DataTableHandler.channelRead0(DataTableHandler.java:36)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

When issuing a simple select count(id) from pinot.default.myTable

Same select works fine in pinot

So rollback to previous pinot version working as it should be. 

Feel free to ask more infos if needed

**Comment by findepi** [comment]
cc @elonazoulay
