### ISSUE TITLE
Update Hive ACID table seems sometime to corrupt the data

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#14519]
for example `TestHiveTransactionalTable.testAcidUpdateSelectedValues` is flaky https://github.com/trinodb/trino/actions/runs/3203025750/jobs/5233758071

```
2022-10-07T11:11:00.0565869Z tests               | 2022-10-07 16:56:00 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveTransactionalTable.testAcidUpdateSelectedValues (Groups: hive_transactional) took 2.8 seconds
2022-10-07T11:11:00.0566612Z tests               | 2022-10-07 16:56:00 SEVERE: Failure cause:
2022-10-07T11:11:00.0567331Z tests               | java.lang.AssertionError: [onTrino] Expected row count to be <2>, but was <4>; rows=[[7, ONE, 1000, true, 101], [13, DEUX, 2235, false, 202], [13, DEUX, 2235, false, 202], [7, ONE, 1000, true, 101]]
2022-10-07T11:11:00.0568062Z tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.verifySelect(TestHiveTransactionalTable.java:2230)
2022-10-07T11:11:00.0568883Z tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.verifySelectForTrinoAndHive(TestHiveTransactionalTable.java:2220)
2022-10-07T11:11:00.0569731Z tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.lambda$testAcidUpdateSelectedValues$57(TestHiveTransactionalTable.java:1309)
2022-10-07T11:11:00.0570515Z tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.withTemporaryTable(TestHiveTransactionalTable.java:1810)
2022-10-07T11:11:00.0571360Z tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.testAcidUpdateSelectedValues(TestHiveTransactionalTable.java:1302)
2022-10-07T11:11:00.0572092Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-10-07T11:11:00.0572734Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-10-07T11:11:00.0573420Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-10-07T11:11:00.0573909Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-10-07T11:11:00.0574488Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-10-07T11:11:00.0575111Z tests               | 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2022-10-07T11:11:00.0575570Z tests               | 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2022-10-07T11:11:00.0576136Z tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2022-10-07T11:11:00.0576680Z tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-10-07T11:11:00.0577245Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-10-07T11:11:00.0577736Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-10-07T11:11:00.0578358Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

cc @djsstarburst

**Comment by findepi** [comment]
`TestHiveTransactionalTable.testAcidUpdateWithSubqueryPredicate` is also affected https://github.com/trinodb/trino/issues/13162

and `testUpdateFullAcidWithOriginalFilesTrinoInsertingAndDeleting` https://github.com/trinodb/trino/issues/11893

and `testPartitionedInsertAndRowLevelDelete` https://github.com/trinodb/trino/issues/9083

and `testFilesForAbortedTransactionsIgnored` https://github.com/trinodb/trino/issues/5463

**Comment by findepi** [comment]
`testOrcColumnTypeChange` https://github.com/trinodb/trino/issues/12063 seems to be about the same problem too

**Comment by djsstarburst** [comment]
Hmm, I had not looked into this before.  Summarizing:

Here is the exception:

```
2022-10-07T11:11:00.0567331Z tests               | java.lang.AssertionError: [onTrino] Expected row count to be <2>, but was <4>; rows=[[7, ONE, 1000, true, 101], [13, DEUX, 2235, false, 202], [13, DEUX, 2235, false, 202], [7, ONE, 1000, true, 101]
```

Here is what the test is doing:

```
CREATE TABLE tablename (col1 TINYINT, col2 VARCHAR, col3 BIGINT, col4 BOOLEAN, col5 INT);
INSERT INTO tablename (col1, col2, col3, col4, col5) VALUES (7, 'ONE', 1000, true, 101), (13, 'TWO', 2000, false, 202);

UPDATE tablename SET col2 = 'DEUX', col3 = col3 + 20 + col1 + col5 WHERE col1 = 13;

SELECT * FROM tablename;

Result should be:
VALUES (7, 'ONE', 1000, true, 101),
       (13, 'DEUX', 2235, false, 202)

Result was:       
VALUES (7, 'ONE', 1000, true, 101),
       (7, 'ONE', 1000, true, 101),
       (13, 'DEUX', 2235, false, 202),
       (13, 'DEUX', 2235, false, 202);
```

The UPDATE operation should change a single row.  However, in the following SELECT operation, both rows in the result set are duplicated.

**Comment by djsstarburst** [comment]
This is yet another test table name collision, and is not a product problem.  Both `testAcidUpdateSelectedValues` and `testAcidUpdateSimple` use the root test name `test_update_simple` and `withTemporaryTable` is not add a random suffix.

PR #14883 eliminates the collision by changing the name of the former test, and adding a random suffix in `withTemporaryTable`.

**Comment by findepi** [comment]
> This is yet another test table name collision

why didn't the tests fail due to the collision?

**Comment by djsstarburst** [comment]
> why didn't the tests fail due to the collision?

I'm not sure I understand the question, @findepi.  There are 87 tests in `TestHiveTransactionalTable`.  In order to see the failure, two specific tests had to be running at the same time.  When I tried to reproduce the problem, I was only running one of the two name-colliding tests, so the that test always passed.

**Comment by sopel39** [comment]
@djsstarburst @findepi can we consider this done?

**Comment by djsstarburst** [comment]
> @djsstarburst @findepi can we consider this done?

Yes.
