### ISSUE TITLE
Flaky `TestHiveMerge.testMergeSimpleSelectPartitioned`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#14516]
https://github.com/trinodb/trino/actions/runs/3202027731/jobs/5231426378

```
tests               | 2022-10-07 13:00:16 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveMerge.testMergeSimpleSelectPartitioned (Groups: hive_transactional) took 3.6 seconds
tests               | 2022-10-07 13:00:16 SEVERE: Failure cause:
tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20221007_071516_01026_ffvnx): One MERGE target table row matched more than one source row
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:60)
tests               | 	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
tests               | 	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:62)
tests               | 	at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
tests               | 	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:67)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:60)
tests               | 	at io.trino.tests.product.hive.TestHiveMerge.lambda$testMergeSimpleSelectPartitioned$2(TestHiveMerge.java:89)
tests               | 	at io.trino.tests.product.hive.TestHiveMerge.withTemporaryTable(TestHiveMerge.java:730)
tests               | 	at io.trino.tests.product.hive.TestHiveMerge.lambda$testMergeSimpleSelectPartitioned$3(TestHiveMerge.java:79)
tests               | 	at io.trino.tests.product.hive.TestHiveMerge.withTemporaryTable(TestHiveMerge.java:730)
tests               | 	at io.trino.tests.product.hive.TestHiveMerge.testMergeSimpleSelectPartitioned(TestHiveMerge.java:74)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
tests               | 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
tests               | Caused by: java.sql.SQLException: Query failed (#20221007_071516_01026_ffvnx): One MERGE target table row matched more than one source row
tests               | 	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
tests               | 	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:295)
tests               | 	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:255)
tests               | 	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
tests               | 	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
tests               | 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1855)
tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292)
tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298)
tests               | 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
tests               | 	at io.trino.jdbc.TrinoResultSet$AsyncIterator.lambda$new$1(TrinoResultSet.java:180)
tests               | 	... 5 more
tests               | 	Suppressed: java.lang.Exception: Query: MERGE INTO test_merge_simple_target_true_NONE_1y0keckrqgcs t USING test_merge_simple_source_false_NONE_i9jlvrhmz0bx s ON (t.customer = s.customer)    WHEN MATCHED AND s.address = 'Centreville' THEN DELETE    WHEN MATCHED THEN UPDATE SET purchases = s.purchases + t.purchases, address = s.address    WHEN NOT MATCHED THEN INSERT (customer, purchases, address) VALUES(s.customer, s.purchases, s.address)
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 		at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:60)
tests               | 		at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
tests               | 		at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:62)
tests               | 		at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
tests               | 		at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 		at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:67)
tests               | 		at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:60)
tests               | 		at io.trino.tests.product.hive.TestHiveMerge.lambda$testMergeSimpleSelectPartitioned$2(TestHiveMerge.java:89)
tests               | 		at io.trino.tests.product.hive.TestHiveMerge.withTemporaryTable(TestHiveMerge.java:730)
tests               | 		at io.trino.tests.product.hive.TestHiveMerge.lambda$testMergeSimpleSelectPartitioned$3(TestHiveMerge.java:79)
tests               | 		at io.trino.tests.product.hive.TestHiveMerge.withTemporaryTable(TestHiveMerge.java:730)
tests               | 		at io.trino.tests.product.hive.TestHiveMerge.testMergeSimpleSelectPartitioned(TestHiveMerge.java:74)
tests               | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 		at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 		at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
tests               | 		at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
tests               | 		... 5 more
tests               | Caused by: io.trino.spi.TrinoException: One MERGE target table row matched more than one source row
tests               | 	at io.trino.operator.scalar.FailureFunction.fail(FailureFunction.java:60)
tests               | 	at io.trino.$gen.PageFilter_20221007_071350_450.filter(Unknown Source)
tests               | 	at io.trino.$gen.PageFilter_20221007_071350_450.filter(Unknown Source)
tests               | 	at io.trino.operator.project.PageProcessor.createWorkProcessor(PageProcessor.java:129)
tests               | 	at io.trino.operator.FilterAndProjectOperator.lambda$new$0(FilterAndProjectOperator.java:62)
tests               | 	at io.trino.operator.WorkProcessorUtils.lambda$flatMap$5(WorkProcessorUtils.java:264)
tests               | 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
tests               | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
tests               | 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
tests               | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.ja
tests               | va:391)
tests               | 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
tests               | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
tests               | 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
tests               | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
tests               | 	at io.trino.operator.WorkProcessorOperatorAdapter.getOutput(WorkProcessorOperatorAdapter.java:173)
tests               | 	at io.trino.operator.Driver.processInternal(Driver.java:411)
tests               | 	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
tests               | 	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
tests               | 	at io.trino.operator.Driver.process(Driver.java:306)
tests               | 	at io.trino.operator.Driver.processForDuration(Driver.java:277)
tests               | 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:736)
tests               | 	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
tests               | 	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:515)
tests               | 	at io.trino.$gen.Trino_399_3_gb[7693](https://github.com/trinodb/trino/actions/runs/3202027731/jobs/5231426378#step:8:7694)4a____20221007_065945_2.run(Unknown Source)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by findepi** [comment]
cc @djsstarburst

**Comment by gaurav8297** [comment]
Test failing TestHiveMerge > testMergeMultipleOperationsUnbucketedPartitioned [groups: hive_transactional]

CI: https://github.com/trinodb/trino/pull/14553/checks?check_run_id=8882217060

```
java.lang.AssertionError: Could not find rows:
[joe_32, 5000, 85000, jen_32, 32 Poe Ct]
[joe_33, 5000, 85000, jen_33, 33 Poe Ct]
[joe_34, 5000, 85000, jen_34, 34 Poe Ct]
[joe_35, 5000, 85000, jen_35, 35 Poe Ct]
[joe_36, 5000, 85000, jen_36, 36 Poe Ct]
[joe_37, 5000, 85000, jen_37, 37 Poe Ct]
[joe_38, 5000, 85000, jen_38, 38 Poe Ct]
[joe_39, 5000, 85000, jen_39, 39 Poe Ct]
[joe_40, 5000, 85000, jen_40, 40 Poe Ct]
[joe_41, 5000, 85000, jen_41, 41 Poe Ct]
[joe_42, 5000, 85000, jen_42, 42 Poe Ct]
[joe_43, 5000, 85000, jen_43, 43 Poe Ct]
[joe_44, 5000, 85000, jen_44, 44 Poe Ct]
[joe_45, 5000, 85000, jen_45, 45 Poe Ct]
[joe_46, 5000, 85000, jen_46, 46 Poe Ct]
[joe_47, 5000, 85000, jen_47, 47 Poe Ct]

actual rows:
[joe_5, 5000, 85000, jen_5, 5 Poe Ct]
[joe_4, 5000, 85000, jen_4, 4 Poe Ct]
[joe_43, 5000, 60000, jen_43, 43 Poe Ct]
[joe_39, 5000, 60000, jen_39, 39 Poe Ct]
[joe_42, 5000, 60000, jen_42, 42 Poe Ct]
[joe_26, 3000, 60000, jill_26, 26 Eop Ct]
[joe_32, 5000, 60000, jen_32, 32 Poe Ct]
[joe_9, 5000, 85000, jen_9, 9 Poe Ct]
[joe_3, 5000, 85000, jen_3, 3 Poe Ct]
[joe_19, 3000, 60000, jill_19, 19 Eop Ct]
[jack_32, 4000, 74000, jan_32, 32 Poe Ct]
[jack_41, 4000, 74000, jan_41, 41 Poe Ct]
[joe_21, 3000, 60000, jill_21, 21 Eop Ct]
[joe_44, 5000, 60000, jen_44, 44 Poe Ct]
[joe_31, 3000, 60000, jill_31, 31 Eop Ct]
[jack_37, 4000, 74000, jan_37, 37 Poe Ct]
[joe_27, 3000, 60000, jill_27, 27 Eop Ct]
[joe_47, 5000, 60000, jen_47, 47 Poe Ct]
[jack_40, 4000, 74000, jan_40, 40 Poe Ct]
[joe_37, 5000, 60000, jen_37, 37 Poe Ct]
[joe_12, 5000, 85000, jen_12, 12 Poe Ct]
[joe_13, 5000, 85000, jen_13, 13 Poe Ct]
[joe_29, 3000, 60000, jill_29, 29 Eop Ct]
[joe_22, 3000, 60000, jill_22, 22 Eop Ct]
[jack_35, 4000, 74000, jan_35, 35 Poe Ct]
[jack_33, 4000, 74000, jan_33, 33 Poe Ct]
[joe_15, 5000, 85000, jen_15, 15 Poe Ct]
[joe_8, 5000, 85000, jen_8, 8 Poe Ct]
[joe_38, 5000, 60000, jen_38, 38 Poe Ct]
[joe_14, 5000, 85000, jen_14, 14 Poe Ct]
[joe_17, 3000, 60000, jill_17, 17 Eop Ct]
[jack_36, 4000, 74000, jan_36, 36 Poe Ct]
[joe_35, 5000, 60000, jen_35, 35 Poe Ct]
[jack_43, 4000, 74000, jan_43, 43 Poe Ct]
[joe_2, 5000, 85000, jen_2, 2 Poe Ct]
[joe_36, 5000, 60000, jen_36, 36 Poe Ct]
[jack_39, 4000, 74000, jan_39, 39 Poe Ct]
[joe_18, 3000, 60000, jill_18, 18 Eop Ct]
[joe_46, 5000, 60000, jen_46, 46 Poe Ct]
[joe_25, 3000, 60000, jill_25, 25 Eop Ct]
[joe_20, 3000, 60000, jill_20, 20 Eop Ct]
[jack_38, 4000, 74000, jan_38, 38 Poe Ct]
[joe_24, 3000, 60000, jill_24, 24 Eop Ct]
[jack_42, 4000, 74000, jan_42, 42 Poe Ct]
[joe_16, 3000, 60000, jill_16, 16 Eop Ct]
[jack_44, 4000, 74000, jan_44, 44 Poe Ct]
[joe_1, 5000, 85000, jen_1, 1 Poe Ct]
[joe_6, 5000, 85000, jen_6, 6 Poe Ct]
[jack_45, 4000, 74000, jan_45, 45 Poe Ct]
[joe_45, 5000, 60000, jen_45, 45 Poe Ct]
[jack_46, 4000, 74000, jan_46, 46 Poe Ct]
[joe_11, 5000, 85000, jen_11, 11 Poe Ct]
[jack_47, 4000, 74000, jan_47, 47 Poe Ct]
[joe_34, 5000, 60000, jen_34, 34 Poe Ct]
[joe_40, 5000, 60000, jen_40, 40 Poe Ct]
[joe_7, 5000, 85000, jen_7, 7 Poe Ct]
[joe_23, 3000, 60000, jill_23, 23 Eop Ct]
[joe_30, 3000, 60000, jill_30, 30 Eop Ct]
[jack_34, 4000, 74000, jan_34, 34 Poe Ct]
[joe_10, 5000, 85000, jen_10, 10 Poe Ct]
[joe_33, 5000, 60000, jen_33, 33 Poe Ct]
[joe_41, 5000, 60000, jen_41, 41 Poe Ct]
[joe_28, 3000, 60000, jill_28, 28 Eop Ct]
	at io.trino.tests.product.hive.TestHiveMerge.verifyOnTrinoAndHiveFromQueryResults(TestHiveMerge.java:253)
	at io.trino.tests.product.hive.TestHiveMerge.testMergeMultipleOperationsInternal(TestHiveMerge.java:247)
	at io.trino.tests.product.hive.TestHiveMerge.lambda$testMergeMultipleOperationsUnbucketedPartitioned$9(TestHiveMerge.java:184)
	at io.trino.tests.product.hive.TestHiveMerge.withTemporaryTable(TestHiveMerge.java:730)
	at io.trino.tests.product.hive.TestHiveMerge.testMergeMultipleOperationsUnbucketedPartitioned(TestHiveMerge.java:182)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by djsstarburst** [comment]
I checked out branch `gaurav8297/prefer_partitioning_fix`, and ran these tests, but I haven't been able to reproduce the failures.  I'm not sure exactly how to set the writer count to be more than 1, and maybe that's the problem.  @gaurav8297 - - Are you able to reproduce any of the failures on your laptop?  If so, please provide instructions.

@electrum and I added a couple of commits to [my PR implementing delete and update](https://github.com/trinodb/trino/pull/13926) that fixed a similar-looking problem.  The first commit implements `HiveMetadata.getUpdateLayout()`, and @electrum thought there was a good chance that it would fix these problems as well.  [This is the SHA of the first commit](https://github.com/trinodb/trino/pull/13926/commits/f40ee43be5d99b45447d968a47093c801803b419) of the commit, which is titled `Add HiveMetadata.getUpdateLayout`.  [This is the SHA of the second commit](https://github.com/trinodb/trino/pull/13926/commits/32d741d22fba4bccb32fbbd43eb82e968d376168), which is titled `Fix bogus compare of bucketToPartitionMaps`.

I had planned to see the tests fail, and then cherry-pick those two commits and hope that they passed.  But I have to see the tests fail first :)

BTW, I've extracted _ALL_ the fixes/improvements to infrastructure applicable to SQL MERGE from [my PR implementing delete and update](https://github.com/trinodb/trino/pull/13926) into [this separate PR](https://github.com/trinodb/trino/pull/14650).  I hope it is eligible to be merged quickly.  @sopel39 and @homar as well as @electrum are listed as reviewers.  The last two commits in the series are the ones that we guess fix the failing tests mentioned in this issue.

**Comment by sopel39** [comment]
@djsstarburst is it same as https://github.com/trinodb/trino/issues/14637 or https://github.com/trinodb/trino/issues/14636?

**Comment by gaurav8297** [comment]
>  @gaurav8297 - - Are you able to reproduce any of the failures on your laptop? If so, please provide instructions.

I've fixed this branch (`gaurav8297/prefer_partitioning_fix`) that's why you might not be able to reproduce it locally. However, I've pushed the changes to `gaurav8297/prefer_partitioning_bug` in which the last commit introduces the bug.

To reproduce run this suite:
```
./testing/bin/ptl suite run --suite suite-8-non-generic --config config-default --logs-dir logs/ --output PRINT_WRITE --timeout 105m
```

Also, note that I was able to reproduce this bug: https://github.com/trinodb/trino/issues/14636

cc @djsstarburst

**Comment by djsstarburst** [comment]
I just verified that the commit titled `Add HiveMetadata.getUpdateLayout` fixes the two failures in `suite-8-non-generic`.  I checked out branch `gaurav8297/prefer_partitioning_bug` and ran `suite-8-non-generic`.  As expected, I saw these failures:

```
suite-8-non-generic.before:4246:tests               | 2022-10-17 19:08:21 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveMerge.testMergeMultipleOperationsBucketedUnpartitioned (Groups: hive_transactional) took 2.0 seconds
suite-8-non-generic.before:5926:tests               | 2022-10-17 19:10:20 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveMerge.testMergeWithDifferentPartitioning [target_bucketed_by_customer_source_flat, CREATE TABLE %s (customer STRING, purchases INT, address STRING) CLUSTERED BY (customer) INTO 3 BUCKETS STORED AS ORC TBLPROPERTIES ('transactional'='true'), CREATE TABLE %s (customer STRING, purchases INT, address STRING) STORED AS ORC TBLPROPERTIES ('transactional'='true')] (Groups: hive_transactional) took 2.3 seconds
```

I then cherry-picked the `Add HiveMetadata.getUpdateLayout` commit, and ran the suite again, and all tests passed.  The grep matched no lines, and here is the suite summary:

```
2022-10-17T07:24:29.698-0700	INFO	main	io.trino.tests.product.launcher.cli.SuiteRun	Test run 41fc9f4ea7a64eeba44f57fca29cf339 finished
2022-10-17T07:24:29.699-0700	INFO	main	io.trino.tests.product.launcher.cli.SuiteRun	Suite tests results:
+----------------------------------+---------------------+-----------------+----------------+---------+---------+---------+-------+
|                               id |               suite |     environment |         config | options |  status | elapsed | error |
+----------------------------------+---------------------+-----------------+----------------+---------+---------+---------+-------+
| 41fc9f4ea7a64eeba44f57fca29cf339 | suite-8-non-generic | singlenode-hdp3 | config-default |      {} | SUCCESS |  33.23m |     - |
+----------------------------------+---------------------+-----------------+----------------+---------+---------+---------+-------+
```

**Comment by djsstarburst** [comment]
> @djsstarburst is it same as https://github.com/trinodb/trino/issues/14637 or https://github.com/trinodb/trino/issues/14636?

I think so @sopel39.  Without the `Add HiveMetadata.getUpdateLayout` commit both tests failed in `suite-8-non-generic` and with the fix both tests passed.

**Comment by djsstarburst** [comment]
The [SQL MERGE fixes PR](https://github.com/trinodb/trino/pull/14650) has been merged, and that series contained the `HiveMetadata.getUpdateLayout()` support.  So the two Hive tests whose failure I could reproduce, `testMergeMultipleOperationsBucketedUnpartitioned` and `testMergeWithDifferentPartitioning `, should now be fixed in tip master.
