### ISSUE TITLE
Flaky test TestHttpRemoteTask.testRejectedExecution 

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#14526]
https://github.com/trinodb/trino/actions/runs/3205780736/jobs/5240103859

```
Error:  io.trino.server.remotetask.TestHttpRemoteTask.testRejectedExecution  Time elapsed: 4.194 s  <<< FAILURE!
java.lang.AssertionError: expected [REMOTE_TASK_ERROR:65542] but found [GENERIC_INTERNAL_ERROR:65536]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at io.trino.server.remotetask.TestHttpRemoteTask.runTest(TestHttpRemoteTask.java:398)
	at io.trino.server.remotetask.TestHttpRemoteTask.testRejectedExecution(TestHttpRemoteTask.java:167)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by piotrrzysko** [comment]
Reopening because it failed again in https://github.com/trinodb/trino/actions/runs/19766469580/job/56640519324 with:

```
 [ERROR] Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.02 s <<< FAILURE! -- in io.trino.server.remotetask.TestHttpRemoteTask
 [ERROR] io.trino.server.remotetask.TestHttpRemoteTask.testRejectedExecution -- Time elapsed: 3.877 s <<< FAILURE!
 org.opentest4j.AssertionFailedError:

 expected: REMOTE_TASK_ERROR:65542
  but was: GENERIC_INTERNAL_ERROR:65536
 	at io.trino.server.remotetask.TestHttpRemoteTask.runTest(TestHttpRemoteTask.java:604)
 	at io.trino.server.remotetask.TestHttpRemoteTask.testRejectedExecution(TestHttpRemoteTask.java:191)
```
