### ISSUE TITLE
TestFileBasedSystemAccess control fails in IDE

### ISSUE THREAD

**Issue by martint** [trinodb/trino#14530]
```
2022-10-08T15:17:14.285-0500	INFO	main	io.trino.testng.services.FlakyTestRetryAnalyzer	FlakyTestRetryAnalyzer not enabled: CONTINUOUS_INTEGRATION environment is not detected or system property 'io.trino.testng.services.FlakyTestRetryAnalyzer.enabled' is not set to 'true' (actual: <not set>)

java.lang.AssertionError: 
Expecting throwable message:
  <"Configuration errors:

1) Error: Invalid configuration property security.config-file: file does not exist: src/test/resources/security-config-file-with-unknown-rules.json (for class FileBasedAccessControlConfig.configFile)

1 error

======================
Full classname legend:
======================
FileBasedAccessControlConfig: "io.trino.plugin.base.security.FileBasedAccessControlConfig"
========================
End of classname legend:
========================
">
to contain:
  <"Invalid JSON">
but did not.

Throwable that failed the check:

io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Invalid configuration property security.config-file: file does not exist: src/test/resources/security-config-file-with-unknown-rules.json (for class FileBasedAccessControlConfig.configFile)

1 error

======================
Full classname legend:
======================
FileBasedAccessControlConfig: "io.trino.plugin.base.security.FileBasedAccessControlConfig"
========================
End of classname legend:
========================

	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:234)
	at io.trino.plugin.base.security.FileBasedSystemAccessControl$Factory.create(FileBasedSystemAccessControl.java:212)
	at io.trino.security.TestFileBasedSystemAccessControl.parse(TestFileBasedSystemAccessControl.java:869)
	at io.trino.security.TestFileBasedSystemAccessControl.lambda$parseUnknownRules$140(TestFileBasedSystemAccessControl.java:863)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:877)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1306)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1178)
	at io.trino.security.TestFileBasedSystemAccessControl.parseUnknownRules(TestFileBasedSystemAccessControl.java:863)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)


	at io.trino.security.TestFileBasedSystemAccessControl.parseUnknownRules(TestFileBasedSystemAccessControl.java:864)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

2022-10-08T15:17:14.286-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                                                  DESCRIPTION
2022-10-08T15:17:14.286-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog_invalid_allow_value.json
2022-10-08T15:17:14.286-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.287-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.287-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.300-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                                          DESCRIPTION
2022-10-08T15:17:14.300-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog_allow_unset.json
2022-10-08T15:17:14.300-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.301-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.301-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.302-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                                            DESCRIPTION
2022-10-08T15:17:14.302-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog_impersonation.json
2022-10-08T15:17:14.302-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.303-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.303-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.308-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                                        DESCRIPTION
2022-10-08T15:17:14.308-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog_principal.json
2022-10-08T15:17:14.308-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.308-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.308-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.310-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                                        DESCRIPTION
2022-10-08T15:17:14.310-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog_principal.json
2022-10-08T15:17:14.310-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.311-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.311-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.313-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                              DESCRIPTION
2022-10-08T15:17:14.313-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog.json
2022-10-08T15:17:14.313-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.313-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.313-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.315-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                              DESCRIPTION
2022-10-08T15:17:14.315-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog.json
2022-10-08T15:17:14.315-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.315-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.316-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.319-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                                        DESCRIPTION
2022-10-08T15:17:14.319-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog_read_only.json
2022-10-08T15:17:14.319-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.320-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.320-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.322-0500	INFO	main	io.trino.testng.services.FlakyTestRetryAnalyzer	FlakyTestRetryAnalyzer not enabled: CONTINUOUS_INTEGRATION environment is not detected or system property 'io.trino.testng.services.FlakyTestRetryAnalyzer.enabled' is not set to 'true' (actual: <not set>)

io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Invalid configuration property security.config-file: file does not exist: /Users/martin/projects/trino/trino/../../docs/src/main/sphinx/security/user-impersonation.json (for class FileBasedAccessControlConfig.configFile)

1 error

======================
Full classname legend:
======================
FileBasedAccessControlConfig: "io.trino.plugin.base.security.FileBasedAccessControlConfig"
========================
End of classname legend:
========================


	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:234)
	at io.trino.plugin.base.security.FileBasedSystemAccessControl$Factory.create(FileBasedSystemAccessControl.java:212)
	at io.trino.security.AccessControlManager.loadSystemAccessControl(AccessControlManager.java:199)
	at io.trino.security.TestFileBasedSystemAccessControl.testDocsExample(TestFileBasedSystemAccessControl.java:126)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

2022-10-08T15:17:14.324-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                              DESCRIPTION
2022-10-08T15:17:14.324-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog.json
2022-10-08T15:17:14.324-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.324-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.325-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.328-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                                        DESCRIPTION
2022-10-08T15:17:14.328-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog_read_only.json
2022-10-08T15:17:14.328-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.328-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.328-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.333-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                                    DESCRIPTION
2022-10-08T15:17:14.333-0500	INFO	main	Bootstrap	security.config-file     ----     /var/folders/_v/2kb9fsms6zl47z4m635n3scc0000gn/T/9832b066-eb78-4ece-9e5e-77feb13ec8a0.txt
2022-10-08T15:17:14.333-0500	INFO	main	Bootstrap	security.refresh-period  ----     1.00ms
2022-10-08T15:17:14.334-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.334-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.339-0500	INFO	main	io.trino.plugin.base.security.FileBasedSystemAccessControl	Refreshing system access control from /var/folders/_v/2kb9fsms6zl47z4m635n3scc0000gn/T/9832b066-eb78-4ece-9e5e-77feb13ec8a0.txt
2022-10-08T15:17:14.343-0500	INFO	main	io.trino.plugin.base.security.FileBasedSystemAccessControl	Refreshing system access control from /var/folders/_v/2kb9fsms6zl47z4m635n3scc0000gn/T/9832b066-eb78-4ece-9e5e-77feb13ec8a0.txt
2022-10-08T15:17:14.344-0500	INFO	main	io.trino.plugin.base.security.FileBasedSystemAccessControl	Refreshing system access control from /var/folders/_v/2kb9fsms6zl47z4m635n3scc0000gn/T/9832b066-eb78-4ece-9e5e-77feb13ec8a0.txt
2022-10-08T15:17:14.347-0500	INFO	main	io.trino.plugin.base.security.FileBasedSystemAccessControl	Refreshing system access control from /var/folders/_v/2kb9fsms6zl47z4m635n3scc0000gn/T/9832b066-eb78-4ece-9e5e-77feb13ec8a0.txt
2022-10-08T15:17:14.349-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                              DESCRIPTION
2022-10-08T15:17:14.349-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog.json
2022-10-08T15:17:14.349-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.349-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.349-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.352-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                                        DESCRIPTION
2022-10-08T15:17:14.352-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog_read_only.json
2022-10-08T15:17:14.352-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.353-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.353-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.354-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                                         DESCRIPTION
2022-10-08T15:17:14.354-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/system_information.json
2022-10-08T15:17:14.354-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.355-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.355-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.357-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                              DESCRIPTION
2022-10-08T15:17:14.357-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog.json
2022-10-08T15:17:14.357-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.358-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.358-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.362-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                                        DESCRIPTION
2022-10-08T15:17:14.362-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog_read_only.json
2022-10-08T15:17:14.362-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.363-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.363-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.366-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                              DESCRIPTION
2022-10-08T15:17:14.366-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog.json
2022-10-08T15:17:14.366-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.367-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.367-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2022-10-08T15:17:14.372-0500	INFO	main	Bootstrap	PROPERTY                 DEFAULT  RUNTIME                                                                                        DESCRIPTION
2022-10-08T15:17:14.372-0500	INFO	main	Bootstrap	security.config-file     ----     /Users/martin/projects/trino/trino/core/trino-main/target/test-classes/catalog_read_only.json
2022-10-08T15:17:14.372-0500	INFO	main	Bootstrap	security.refresh-period  ----     ----
2022-10-08T15:17:14.373-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2022-10-08T15:17:14.373-0500	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
```

**Comment by findepi** [comment]
How do you run it?
It seems to work for me

<img width="359" alt="image" src="https://user-images.githubusercontent.com/144328/194826657-5633d643-e475-41e4-a1c4-964c19ebe085.png">
