### ISSUE TITLE
Flaky TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest.init: Container startup failed: Timed out waiting for container port to open

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#14546]
```
Error:  io.trino.plugin.pinot.TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest.init  Time elapsed: 157.654 s  <<< FAILURE!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at io.trino.plugin.pinot.TestingPinotCluster.start(TestingPinotCluster.java:138)
	at io.trino.plugin.pinot.BasePinotIntegrationConnectorSmokeTest.createQueryRunner(BasePinotIntegrationConnectorSmokeTest.java:155)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	... 17 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 18 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [49187, 49188, 49189] should be listening)
	at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:102)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:953)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:485)
	... 20 more

```

**Comment by findepi** [comment]
cc @elonazoulay @xiangfu0

**Comment by xiangfu0** [comment]
I'm also observing this under my test in https://github.com/trinodb/trino/issues/14277

**Comment by findepi** [comment]
> I'm also observing this under my test in https://github.com/trinodb/trino/issues/14277

@xiangfu0 did you mean to link to a PR?

the linked issue doesn't mention `init` failures, so may be a different problem

**Comment by xiangfu0** [comment]
Right, could be a different issue. I'm testing if extend the startup timeout check will help

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/3247297137/jobs/5327104955
