### ISSUE TITLE
Flaky `TestTrinoCli.shouldRunMultipleBatchQueriesWithStdinRedirect`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#14587]
https://github.com/trinodb/trino/actions/runs/3224211999/jobs/5275210287

```
2022-10-11T05:27:01.4718071Z tests               | 2022-10-11 11:12:01 INFO: FAILURE     /    io.trino.tests.product.cli.TestTrinoCli.shouldRunMultipleBatchQueriesWithStdinRedirect (Groups: cli) took 5 minutes and 0 seconds
2022-10-11T05:27:01.4742414Z tests               | 2022-10-11 11:12:01 SEVERE: Failure cause:
2022-10-11T05:27:01.4743474Z tests               | org.testng.internal.thread.ThreadTimeoutException: Method io.trino.tests.product.cli.TestTrinoCli.shouldRunMultipleBatchQueriesWithStdinRedirect() didn't finish within the time-out 300000
2022-10-11T05:27:01.4744266Z tests               | 	at java.base@17.0.3/java.io.FileInputStream.readBytes(Native Method)
2022-10-11T05:27:01.4744766Z tests               | 	at java.base@17.0.3/java.io.FileInputStream.read(FileInputStream.java:276)
2022-10-11T05:27:01.4745358Z tests               | 	at java.base@17.0.3/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
2022-10-11T05:27:01.4745879Z tests               | 	at java.base@17.0.3/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
2022-10-11T05:27:01.4746385Z tests               | 	at java.base@17.0.3/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
2022-10-11T05:27:01.4746898Z tests               | 	at java.base@17.0.3/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
2022-10-11T05:27:01.4747386Z tests               | 	at java.base@17.0.3/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
2022-10-11T05:27:01.4747838Z tests               | 	at java.base@17.0.3/java.io.Reader.read(Reader.java:197)
2022-10-11T05:27:01.4748294Z tests               | 	at java.base@17.0.3/java.io.InputStreamReader.read(InputStreamReader.java:157)
2022-10-11T05:27:01.4748993Z tests               | 	at java.base@17.0.3/java.util.Scanner.readInput(Scanner.java:882)
2022-10-11T05:27:01.4749461Z tests               | 	at java.base@17.0.3/java.util.Scanner.findWithinHorizon(Scanner.java:1796)
2022-10-11T05:27:01.4749942Z tests               | 	at java.base@17.0.3/java.util.Scanner.hasNextLine(Scanner.java:1610)
2022-10-11T05:27:01.4750523Z tests               | 	at app//io.trino.tempto.internal.process.CliProcessBase.hasNextOutputLine(CliProcessBase.java:79)
2022-10-11T05:27:01.4751303Z tests               | 	at app//io.trino.tempto.internal.process.CliProcessBase.readRemainingOutputLines(CliProcessBase.java:54)
2022-10-11T05:27:01.4752103Z tests               | 	at app//io.trino.tests.product.cli.TestTrinoCli.shouldRunMultipleBatchQueriesWithStdinRedirect(TestTrinoCli.java:178)
2022-10-11T05:27:01.4752808Z tests               | 	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-10-11T05:27:01.4753444Z tests               | 	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-10-11T05:27:01.4754117Z tests               | 	at java.base@17.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-10-11T05:27:01.4754779Z tests               | 	at java.base@17.0.3/java.lang.reflect.Method.invoke(Method.java:568)
2022-10-11T05:27:01.4755333Z tests               | 	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-10-11T05:27:01.4755952Z tests               | 	at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2022-10-11T05:27:01.4756521Z tests               | 	at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2022-10-11T05:27:01.4757076Z tests               | 	at java.base@17.0.3/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2022-10-11T05:27:01.4757593Z tests               | 	at java.base@17.0.3/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-10-11T05:27:01.4758161Z tests               | 	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-10-11T05:27:01.4758745Z tests               | 	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-10-11T05:27:01.4759242Z tests               | 	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)
```

**Comment by ebyhr** [comment]
Closing as I haven't seen this failure for a long time.
