### ISSUE TITLE
query iceberg orc table throw exception: Class org.apache.hadoop.net.StandardSocketFactory not found

### ISSUE THREAD

**Issue by user-GitHub-user** [trinodb/trino#14634]
trino:381
iceberg:0.13.1

 CREATE TABLE test (                                                  
    int_1 integer NOT NULL,                                                                                                                                                     
    bigint_1 bigint,                                                                                                                                                          
    decimal_1 decimal(10, 2),                                                                                                                                     
    timestamp_1 timestamp(6) with time zone,                                                                                                   
    date_1 date,                                                                                                                                                                  
    char_1 varchar,                                                                                                                                                            
    varchar_1 varchar,                                                                                                                                                     
    text_1 varchar                                                            
 )                                                                                                 
 WITH (                                                                                            
    format = 'ORC',                                                                                
    format_version = 2
 )

excetion:
io.trino.spi.TrinoException: Socket Factory class not found: java.lang.ClassNotFoundException: Class org.apache.hadoop.net.StandardSocketFactory not found
	at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:202)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
	at io.trino.operator.Driver.processInternal(Driver.java:410)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_381_1_gec7226d____20221008_090218_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Socket Factory class not found: java.lang.ClassNotFoundException: Class org.apache.hadoop.net.StandardSocketFactory not found
	at org.apache.hadoop.net.NetUtils.getSocketFactoryFromProperty(NetUtils.java:143)
	at org.apache.hadoop.net.NetUtils.getDefaultSocketFactory(NetUtils.java:123)
	at org.apache.hadoop.net.NetUtils.getSocketFactory(NetUtils.java:101)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:308)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:289)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:176)
	at io.trino.plugin.hive.fs.TrinoFileSystemCache.createFileSystem(TrinoFileSystemCache.java:132)
	at io.trino.plugin.hive.fs.TrinoFileSystemCache.getInternal(TrinoFileSystemCache.java:116)
	at io.trino.plugin.hive.fs.TrinoFileSystemCache.get(TrinoFileSystemCache.java:76)
	at org.apache.hadoop.fs.ForwardingFileSystemCache.get(ForwardingFileSystemCache.java:38)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
	at org.apache.orc.impl.ReaderImpl.getFileSystem(ReaderImpl.java:597)
	at org.apache.orc.impl.ReaderImpl.<init>(ReaderImpl.java:565)
	at org.apache.orc.OrcFile.createReader(OrcFile.java:385)
	at org.apache.iceberg.orc.ORC.newFileReader(ORC.java:501)
	at org.apache.iceberg.orc.ORC.newFileReader(ORC.java:512)
	at org.apache.iceberg.orc.OrcIterable.iterator(OrcIterable.java:78)
	at org.apache.iceberg.orc.OrcIterable.iterator(OrcIterable.java:45)
	at org.apache.iceberg.util.Filter.lambda$filter$0(Filter.java:35)
	at org.apache.iceberg.io.CloseableIterable$2.iterator(CloseableIterable.java:73)
	at org.apache.iceberg.io.CloseableIterable$4$1.<init>(CloseableIterable.java:99)
	at org.apache.iceberg.io.CloseableIterable$4.iterator(CloseableIterable.java:98)
	at org.apache.iceberg.io.CloseableIterable$ConcatCloseableIterable$ConcatCloseableIterator.<init>(CloseableIterable.java:152)
	at org.apache.iceberg.io.CloseableIterable$ConcatCloseableIterable$ConcatCloseableIterator.<init>(CloseableIterable.java:143)
	at org.apache.iceberg.io.CloseableIterable$ConcatCloseableIterable.iterator(CloseableIterable.java:138)
	at org.apache.iceberg.io.CloseableIterable$ConcatCloseableIterable.iterator(CloseableIterable.java:129)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at org.apache.iceberg.deletes.Deletes.toPositionIndex(Deletes.java:97)
	at org.apache.iceberg.deletes.Deletes.toPositionIndex(Deletes.java:91)
	at org.apache.iceberg.data.DeleteFilter.applyPosDeletes(DeleteFilter.java:231)
	at org.apache.iceberg.data.DeleteFilter.filter(DeleteFilter.java:126)
	at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:177)
	... 13 more

**Comment by findepi** [comment]
This is probably fixed by https://github.com/trinodb/trino/pull/13078
