### ISSUE TITLE
VerifyException: cannot unset noMoreSplits which introduced from v396

### ISSUE THREAD

**Issue by zhengxingmao** [trinodb/trino#14656]
I use v396 version met this error.

Test SQl is select count(1) from tab which contains nearly 100 millions rows and execute concurrently.

Some small files may exist in the table.

May introduced by #13978 .

```
com.google.common.base.VerifyException: cannot unset noMoreSplits
  at com.google.common.base.Verify.verify(Verify.java:126)
  at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.enqueueSplits(SqlTaskExecution.java:592)
  at io.trino.execution.SqlTaskExecution.updateSplitAssignments(SqlTaskExecution.java:257)
  at io.trino.execution.SqlTaskExecution.addSplitAssignments(SqlTaskExecution.java:223)
  at io.trino.execution.SqlTask.updateTask(SqlTask.java:451)
  at io.trino.execution.SqlTaskManager.doUpdateTask(SqlTaskManager.java:498)
  at io.trino.execution.SqlTaskManager.lambda$updateTask$9(SqlTaskManager.java:453)
  at io.trino.$gen.Trino_396____20221014_015911_2.call(Unknown Source)
  at io.trino.execution.SqlTaskManager.updateTask(SqlTaskManager.java:453)
  at io.trino.server.TaskResource.createOrUpdateTask(TaskResource.java:151)
  at jdk.internal.reflect.GeneratedMethodAccessor452.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
  at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:183)
  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
  at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
  at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277) 
```

**Comment by arhimondr** [comment]
https://github.com/trinodb/trino/pull/14668

**Comment by arhimondr** [comment]
Fixed by https://github.com/trinodb/trino/pull/14668
