### ISSUE TITLE
Access denied when drop hive tables use system access-control

### ISSUE THREAD

**Issue by user-GitHub-user** [trinodb/trino#14748]
trino version: 400

access-control.properties :
      access-control.name=file
      security.config-file=etc/rules.json
      security.refresh-period=1s

catalog/hive.properties:
    connector.name=hive
    hive.metastore.uri=thrift://host:9083
    hive.config.resources=/xxx/core-site.xml,/xxx/hdfs-site.xml 
    hive.metastore.authentication.type=KERBEROS
    hive.metastore.service.principal=hive/_HOST@xxxx
    hive.metastore.client.principal=hive/ip@xxxx
    hive.metastore.client.keytab=/xxxx/hive.keytab
    hive.hdfs.authentication.type=KERBEROS
    hive.hdfs.trino.principal=trino/_HOST@xxxx
    hive.hdfs.trino.keytab=/xxx/trino.keytab

hive.properties not have any role control config

rules.json is ：
`{
  "catalogs" : [ {
    "user" : "admin",
    "catalog" : ".*",
    "allow" : "all"
  }],
 "schemas" : [ {
    "user" : "admin",
    "schema" : ".*",
    "owner" : true
  }],
"tables" : [ {
    "user" : "admin",
    "privileges" : [ "SELECT", "INSERT", "DELETE", "OWNERSHIP" ]
  }]
}`

admin have all tables OWNERSHIP

exception:

io.trino.spi.security.AccessDeniedException: Access Denied: Cannot drop table prodhouse_stg.a
	at io.trino.spi.security.AccessDeniedException.denyDropTable(AccessDeniedException.java:208)
	at io.trino.spi.security.AccessDeniedException.denyDropTable(AccessDeniedException.java:203)
	at io.trino.plugin.hive.security.LegacyAccessControl.checkCanDropTable(LegacyAccessControl.java:123)
	at io.trino.plugin.base.security.ForwardingConnectorAccessControl.checkCanDropTable(ForwardingConnectorAccessControl.java:109)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorAccessControl.checkCanDropTable(ClassLoaderSafeConnectorAccessControl.java:125)
	at io.trino.security.AccessControlManager.lambda$checkCanDropTable$25(AccessControlManager.java:441)
	at io.trino.security.AccessControlManager.catalogAuthorizationCheck(AccessControlManager.java:1322)
	at io.trino.security.AccessControlManager.checkCanDropTable(AccessControlManager.java:441)
	at io.trino.security.ForwardingAccessControl.checkCanDropTable(ForwardingAccessControl.java:167)
	at io.trino.execution.DropTableTask.execute(DropTableTask.java:87)
	at io.trino.execution.DropTableTask.execute(DropTableTask.java:37)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_d4ca50a____20221024_073532_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by user-GitHub-user** [comment]
solved by config 
hive.allow-drop-table, hive.allow-rename-table, hive.allow-add-column, hive.allow-drop-column and hive.allow-rename-column
in hive catalog
