### ISSUE TITLE
Write data to iceberg on gcs failed

### ISSUE THREAD

**Issue by myfjdthink** [trinodb/trino#14758]
It doesn't always failed

SQL Query:
```sql
insert into "iceberg"."prod_bronze"."table"
select * from "bigquey".table
where time >= timestamp '2022-10-25 09:00:00'
and time < timestamp '2022-10-25 12:00:00'
```
Error Type	EXTERNAL
Error Code	HIVE_WRITER_DATA_ERROR (16777243)
Stack Trace
```
io.trino.spi.TrinoException: java.io.IOException: Upload failed for 'gs://xxx-prod/hive-warehouse/prod_bronze.db/xxxtablexxx-51787185160b4ee59fcfe375a8ef06cf/data/time_hour=2022-10-25-09/20221026_030438_02993_r7kh6-8de2a152-d4bf-43c0-a09f-01d9c4ce8534.orc'
   at io.trino.plugin.hive.orc.OrcFileWriter.appendRows(OrcFileWriter.java:178)
   at io.trino.plugin.iceberg.IcebergPageSink.writePage(IcebergPageSink.java:257)
   at io.trino.plugin.iceberg.IcebergPageSink.doAppend(IcebergPageSink.java:210)
   at io.trino.plugin.iceberg.IcebergPageSink.appendPage(IcebergPageSink.java:159)
   at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:69)
   at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:257)
   at io.trino.operator.Driver.processInternal(Driver.java:416)
   at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
   at io.trino.operator.Driver.tryWithLock(Driver.java:706)
   at io.trino.operator.Driver.process(Driver.java:306)
   at io.trino.operator.Driver.processForDuration(Driver.java:277)
   at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:736)
   at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
   at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:515)
   at io.trino.$gen.Trino_400____20221025_105153_2.run(Unknown Source)
   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.UncheckedIOException: java.io.IOException: Upload failed for 'gs://xxx-prod/hive-warehouse/prod_bronze.db/xxxtablexxx-51787185160b4ee59fcfe375a8ef06cf/data/time_hour=2022-10-25-09/20221026_030438_02993_r7kh6-8de2a152-d4bf-43c0-a09f-01d9c4ce8534.orc'
   at io.airlift.slice.OutputStreamSliceOutput.writeToOutputStream(OutputStreamSliceOutput.java:363)
   at io.airlift.slice.OutputStreamSliceOutput.writeBytes(OutputStreamSliceOutput.java:186)
   at io.airlift.slice.OutputStreamSliceOutput.writeBytes(OutputStreamSliceOutput.java:177)
   at io.trino.orc.OrcOutputBuffer.writeDataTo(OrcOutputBuffer.java:123)
   at io.trino.orc.stream.StreamDataOutput.writeData(StreamDataOutput.java:67)
   at io.trino.orc.OutputStreamOrcDataSink.lambda$write$0(OutputStreamOrcDataSink.java:54)
   at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
   at io.trino.orc.OutputStreamOrcDataSink.write(OutputStreamOrcDataSink.java:54)
   at io.trino.orc.OrcWriter.flushStripe(OrcWriter.java:358)
   at io.trino.orc.OrcWriter.writeChunk(OrcWriter.java:323)
   at io.trino.orc.OrcWriter.write(OrcWriter.java:280)
   at io.trino.plugin.hive.orc.OrcFileWriter.appendRows(OrcFileWriter.java:175)
   ... 17 more
Caused by: java.io.IOException: Upload failed for 'gs://xxx-prod/hive-warehouse/prod_bronze.db/xxxtablexxx-51787185160b4ee59fcfe375a8ef06cf/data/time_hour=2022-10-25-09/20221026_030438_02993_r7kh6-8de2a152-d4bf-43c0-a09f-01d9c4ce8534.orc'
   at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.BaseAbstractGoogleAsyncWriteChannel.waitForCompletionAndThrowIfUploadFailed(BaseAbstractGoogleAsyncWriteChannel.java:260)
   at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.BaseAbstractGoogleAsyncWriteChannel.write(BaseAbstractGoogleAsyncWriteChannel.java:121)
   at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
   at java.base/java.nio.channels.Channels.writeFully(Channels.java:96)
   at java.base/java.nio.channels.Channels$1.write(Channels.java:171)
   at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
   at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
   at com.google.cloud.hadoop.fs.gcs.GoogleHadoopOutputStream.write(GoogleHadoopOutputStream.java:108)
   at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.write(FSDataOutputStream.java:57)
   at java.base/java.io.DataOutputStream.write(DataOutputStream.java:112)
   at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.write(FSDataOutputStream.java:57)
   at java.base/java.io.DataOutputStream.write(DataOutputStream.java:112)
   at io.airlift.slice.Slice.getBytes(Slice.java:648)
   at io.airlift.slice.OutputStreamSliceOutput.writeToOutputStream(OutputStreamSliceOutput.java:360)
   ... 28 more
Caused by: java.io.IOException: Pipe broken
   at java.base/java.io.PipedInputStream.read(PipedInputStream.java:321)
   at java.base/java.io.PipedInputStream.read(PipedInputStream.java:377)
   at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.util.ByteStreams.read(ByteStreams.java:172)
   at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.media.MediaHttpUploader.buildContentChunk(MediaHttpUploader.java:610)
   at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.media.MediaHttpUploader.resumableUpload(MediaHttpUploader.java:380)
   at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:308)
   at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:528)
   at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
   at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
   at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel$UploadOperation.call(AbstractGoogleAsyncWriteChannel.java:85)
   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
   ... 3 more
```
What caused the error？
hive metastore or gcs ?

**Comment by findepi** [comment]
cc @elonazoulay

**Comment by ricardopereira33** [comment]
Hi! 
Any updates regarding this issue? 

I saw some [comments](https://trinodb.slack.com/archives/CGB0QHWSW/p1666757447381109) about this issue on Slack, and the solution of changing the property `fs.gs.outputstream.pipe.type` to `NIO_CHANNEL_PIPE` actually solved it. **However, it degraded the performance 2x (in some cases 3x).** 

Would a retry mechanism when writing to GCS solve this? Without relaying on the FTE...
