### ISSUE TITLE
Cleanup metadata file when commit fails to create Iceberg table

### ISSUE THREAD

**Issue by krvikash** [trinodb/trino#14798]
CREATE TABLE statement failure in iceberg still creates metadata file on s3 location

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/11939923/198279305-df4f05e7-7961-4c02-8044-9bebf7b4f880.png">

SQL statement:

`create table iceberg.default.test2(a int) with(location='s3://krvikash-test/test2-table/');`

Failure Message:

```
Query 20221027_112152_00001_5x34f failed: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified by setting the fs.s3.awsAccessKeyId and fs.s3.awsSecretAccessKey properties (respectively).
io.trino.spi.TrinoException: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified by setting the fs.s3.awsAccessKeyId and fs.s3.awsSecretAccessKey properties (respectively).
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createTable(ThriftHiveMetastore.java:936)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.createTable(BridgingHiveMetastore.java:201)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.createTable(CachingHiveMetastore.java:501)
	at io.trino.plugin.iceberg.catalog.hms.AbstractMetastoreTableOperations.commitNewTable(AbstractMetastoreTableOperations.java:114)
	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.commit(AbstractIcebergTableOperations.java:149)
	at org.apache.iceberg.BaseTransaction.commitCreateTransaction(BaseTransaction.java:278)
	at org.apache.iceberg.BaseTransaction.commitTransaction(BaseTransaction.java:257)
	at io.trino.plugin.iceberg.IcebergMetadata.finishCreateTable(IcebergMetadata.java:702)
	at io.trino.plugin.iceberg.IcebergMetadata.createTable(IcebergMetadata.java:653)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.createTable(ClassLoaderSafeConnectorMetadata.java:374)
	at io.trino.metadata.MetadataManager.createTable(MetadataManager.java:654)
	at io.trino.execution.CreateTableTask.internalExecute(CreateTableTask.java:273)
	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:119)
	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:85)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_dev____20221027_112055_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified by setting the fs.s3.awsAccessKeyId and fs.s3.awsSecretAccessKey properties (respectively).
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:54418)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:54386)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_result.read(ThriftHiveMetastore.java:54312)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_table(ThriftHiveMetastore.java:1539)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_table(ThriftHiveMetastore.java:1526)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.createTable(ThriftHiveMetastoreClient.java:237)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.lambda$createTable$7(FailureAwareThriftMetastoreClient.java:132)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.runWithHandle(FailureAwareThriftMetastoreClient.java:467)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.createTable(FailureAwareThriftMetastoreClient.java:132)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$createTable$36(ThriftHiveMetastore.java:924)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
	at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createTable(ThriftHiveMetastore.java:922)
	... 20 more
```

Note: I have started the standalone environment using `testing/bin/ptl env up --environment 'singlenode'  --config 'config-default' --without-trino`

Expected: Metadata file should not be created or should be deleted in case of failure event.

**Comment by osscm** [comment]
@krvikash it looks like it failed because S3 secrets are not present. and if that case, it can not access S3.
I was wondering if this file/folder is created in some other flow?

**Comment by krvikash** [comment]
Thanks, @osscm for the pointer. Yes, the metadata file gets created in the `commit()` phase. But does not get deleted when there is failure while calling `metastore#createTable`.

**Comment by osscm** [comment]
> Thanks, @osscm for the pointer. Yes, the metadata file gets created in the `commit()` phase. But does not get deleted when there is failure while calling `metastore#createTable`.

IMO there are 2 things
1. Create table failed when S3 credentials are not present, in that case as S3 creds itself are missing, then even if there is a bug in handling some exception it cannot create a folder/file in S3.
2. The metadata folder/file is been created in previous operations or flow.

Can you please try fresh and this time check/share the timestamp in the logs and the folder/file?

**Comment by krvikash** [comment]
https://github.com/trinodb/trino/blob/1ee0cf7fcdb0f6a363acb1a224a53478e434571d/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergTableOperations.java#L105-L119

Here L108 basically creates the new metadata file. But L117 fails the `createTable` call. There is no handling over the failure to cleanup the metadata in any case.

**Comment by findinpath** [comment]
```
Query 20221027_112152_00001_5x34f failed: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified by setting the fs.s3.awsAccessKeyId and fs.s3.awsSecretAccessKey properties (respectively).
...
at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createTable(ThriftHiveMetastore.java:936)
```

Note that the issue of writing S3 content, but not being able to write Glue content was caused by the fact that Trino was trying to connect via HMS

```
hive.metastore.uri=thrift://localhost:9083
```

Changing the catalog type to Glue should solve the issue:

```
iceberg.catalog.type=glue
```


Nevertheless, if writing to S3 succeeds, and writing to Glue fails (e.g. : `InternalServiceException`, `AlreadyExistsException`), then the metadata file created on S3 should be deleted.
