### ISSUE TITLE
Read iceberg v2 table throw multiple entries with same key

### ISSUE THREAD

**Issue by Heltman** [trinodb/trino#14836]
When read a iceberg v2 table with nested fields which contain child type, trino will not deal with right column id through the actural column id, just config id like 1 and 2, this will cause exception:

```log
io.trino.spi.TrinoException: Multiple entries with same key: 1=abnormal_nodes.element and 1=date
	at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:183)
	at io.trino.plugin.base.classloader.ClassLoaderSafeUpdatablePageSource.getNextPage(ClassLoaderSafeUpdatablePageSource.java:79)
...
```

This will happen when table with equality delete file, because `EqualityDeleteFilter$createPredicate` will create iceberg schema from some `IcebergColumnHandle`. It run `IcebergUtil$schemaFromHandles` to create schema. 

When we run `TypeConveter$toIcebergType`, we only pass trino column type to convert to iceberg type and bind id to this column, but we don't bind child type with child id, we just bind a fake id, this will make it's same with other column(like column `date` with id=1, but column `abnormal_nodes` is array type , `abnormal_nodes.element` with id=1 too, it will conflict).

```java
// TypeConveter.java
public static org.apache.iceberg.types.Type toIcebergType(Type type)
{
        ...
        if (type instanceof RowType) {
            return fromRow((RowType) type);
        }
        if (type instanceof ArrayType) {
            return fromArray((ArrayType) type);
        }
        if (type instanceof MapType) {
            return fromMap((MapType) type);
        }
        ...
}

private static org.apache.iceberg.types.Type fromRow(RowType type)
{
        List<Types.NestedField> fields = new ArrayList<>();
        for (RowType.Field field : type.getFields()) {
            String name = field.getName().orElseThrow(() ->
                    new TrinoException(NOT_SUPPORTED, "Row type field does not have a name: " + type.getDisplayName()));
            fields.add(Types.NestedField.optional(fields.size() + 1, name, toIcebergType(field.getType())));
        }
        return Types.StructType.of(fields);
    }

private static org.apache.iceberg.types.Type fromArray(ArrayType type)
    {
        return Types.ListType.ofOptional(1, toIcebergType(type.getElementType()));
    }

    private static org.apache.iceberg.types.Type fromMap(MapType type)
    {
        return Types.MapType.ofOptional(1, 2, toIcebergType(type.getKeyType()), toIcebergType(type.getValueType()));
    }
```

**Comment by 0xffmeta** [comment]
JFY - we have met the same proble with trino 402, but it was working with trion 377. Not sure if there is anything specific changed for the filed ids.

**Comment by Heltman** [comment]
@0xffmeta Maybe 377 don't support pushdown predicate in delete file filter

**Comment by findepi** [comment]
@fritzb do you have a full stacktrace?

**Comment by fritzb** [comment]
@findepi How do I get the stacktrace? Please send instruction, or a pointer.

**Comment by fritzb** [comment]
Once I removed tags array<string>, the problem no longer occur. It is #14837

**Comment by findepi** [comment]
> How do I get the stacktrace?

run trino CLI with `--debug` flag, or click the query to see its details in the Trino UI (https://trino.io/docs/current/admin/web-interface.html)

> Once I removed tags array

This part i don't understand. please explain

> It is https://github.com/trinodb/trino/pull/14837

thank you for your PR!

**Comment by fritzb** [comment]
In my example schema, there is a column called tags (type array<string>). Once I drop this column, upsert continue to work as expected. This conclude #14837

**Comment by congd123** [comment]
Are you working on this issue? @Heltman

**Comment by Heltman** [comment]
> Are you working on this issue? @Heltman

I had fix it, only need review. See #14837 .

**Comment by fritzb** [comment]
I don't have complex type column, and similar error message: `Multiple entries with same key: 3=$row_id.file_record_count and 3=metric_process_timestamp . metric_process_timestamp`. All my columns are string and int, and `metric_process_timestamp` is not part of the key. I have equality columns set in Flink writer shown below.
Could this be the same root cause @Heltman ? When are you planning to merge the fix ?

```
FlinkSink.forRowData(stream.map(x -> RowHelper.convertProtoToRowData(x,
                    MapMakingMetricUtils.NON_NULL_COLUMNS,
                    Collections.EMPTY_LIST, true)))
            .tableLoader(tableLoader)
            .equalityFieldColumns(Arrays
                    .asList("meta_data_center", "meta_namespace", "metric_timestamp", "name", "sequence_id"))
            .upsert(true)
            .append()
            .name(sinkNameExtension + "-iceberg");
```




```
trino> update metrics.map_making_metrics set meta_row_state = 0;

Query 20230202_164316_00015_687bi, FAILED, 3 nodes
http://trino.dev.deepmap.ai/ui/query.html?20230202_164316_00015_687bi
Splits: 195 total, 22 done (11.28%)
CPU Time: 0.3s total, 14.8K rows/s, 4.89MB/s, 25% active
Per Node: 0.1 parallelism, 2.06K rows/s,  698KB/s
Parallelism: 0.4
Peak Memory: 3.18MB
0.78 [4.83K rows, 1.59MB] [6.19K rows/s, 2.04MB/s]

Query 20230202_164316_00015_687bi failed: Multiple entries with same key: 3=$row_id.file_record_count and 3=metric_process_timestamp
io.trino.spi.TrinoException: Multiple entries with same key: 3=$row_id.file_record_count and 3=metric_process_timestamp
	at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:179)
	at io.trino.plugin.base.classloader.ClassLoaderSafeUpdatablePageSource.getNextPage(ClassLoaderSafeUpdatablePageSource.java:79)
	at io.trino.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:400)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:182)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$7(WorkProcessorUtils.java:296)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$3(WorkProcessorUtils.java:219)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$4(WorkProcessorUtils.java:234)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:150)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:752)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:519)
	at io.trino.$gen.Trino_405____20230130_193035_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: 3=$row_id.file_record_count and 3=metric_process_timestamp
	at org.apache.iceberg.relocated.com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:377)
	at org.apache.iceberg.relocated.com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:371)
	at org.apache.iceberg.relocated.com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:241)
	at org.apache.iceberg.relocated.com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:132)
	at org.apache.iceberg.relocated.com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:94)
	at org.apache.iceberg.relocated.com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:573)
	at org.apache.iceberg.relocated.com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:601)
	at org.apache.iceberg.relocated.com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:588)
	at org.apache.iceberg.types.IndexByName.byId(IndexByName.java:81)
	at org.apache.iceberg.types.TypeUtil.indexNameById(TypeUtil.java:160)
	at org.apache.iceberg.Schema.lazyIdToName(Schema.java:183)
	at org.apache.iceberg.Schema.<init>(Schema.java:112)
	at org.apache.iceberg.Schema.<init>(Schema.java:91)
	at org.apache.iceberg.Schema.<init>(Schema.java:83)
	at org.apache.iceberg.Schema.<init>(Schema.java:79)
	at io.trino.plugin.iceberg.IcebergUtil.schemaFromHandles(IcebergUtil.java:248)
	at io.trino.plugin.iceberg.delete.EqualityDeleteFilter.createPredicate(EqualityDeleteFilter.java:49)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.lambda$createPageSource$7(IcebergPageSourceProvider.java:350)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.lambda$createPageSource$8(IcebergPageSourceProvider.java:351)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:162)
	... 38 more

trino>
```

**Comment by Heltman** [comment]
@fritzb I will check and try fix it.
