### ISSUE TITLE
Flaky TestHttpEventListener.testNoServerCertificateShouldNotSendRequest

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#14895]
```
Error:  io.trino.plugin.httpquery.TestHttpEventListener.testNoServerCertificateShouldNotSendRequest  Time elapsed: 0.098 s  <<< FAILURE!
java.lang.AssertionError: Handshake should have failed expected [null] but found [��i�w��3D'�bn~g9I�s�t
���S�<9 	8��P<t��S�a���!���Ծ%�'� >�,�+̩�0̨�/�̪����$�(�#�'kjg@�.�2�-�1�&�*�%�)�.	localhost]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:509)
	at org.testng.Assert.assertNull(Assert.java:445)
	at io.trino.plugin.httpquery.TestHttpEventListener.testNoServerCertificateShouldNotSendRequest(TestHttpEventListener.java:372)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

https://github.com/trinodb/trino/actions/runs/3390819543/jobs/5635363274

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/16117372295/job/45488949210

**Comment by wendigo** [comment]
Fixed @ebyhr

**Comment by ebyhr** [comment]
@wendigo Thank you!
