### ISSUE TITLE
One worker's CPU is always high 

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#14996]
I am running one trino(394) cluster with 10 workers. But after a couple of days there is one work node's cpu is keeping 100% and other work is less then 20%. All the servers are VM and only trino is running on these servers. This work node cause the whole cluster is slow and most of the queries are running timeout(more than 5 minutes).

![image](https://user-images.githubusercontent.com/8622340/201301779-7dac6865-d2bf-4100-b99c-fe7f796dc1b0.png)

top -H -p 4517
top - 16:28:25 up 50 days,  5:46,  2 users,  load average: 40.23, 40.06, 37.83
Threads: 591 total,  56 running, 535 sleeping,   0 stopped,   0 zombie
%Cpu(s): 91.8 us,  6.7 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  1.5 si,  0.0 st
KiB Mem : 13186292+total,  4129648 free, 12272278+used,  5010496 buff/cache
KiB Swap:  3145724 total,  3076084 free,    69640 used.  8249072 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
13443 root      20   0  126.9g 115.0g  23364 R 55.6 91.4  98:49.06 20221111_082812
20279 root      20   0  126.9g 115.0g  23364 R 48.2 91.4 278:10.63 20221111_082820
 1350 root      20   0  126.9g 115.0g  23364 R 47.9 91.4 108:11.18 20221111_082646
15281 root      20   0  126.9g 115.0g  23364 R 42.8 91.4 215:58.09 20221111_082822
 4132 root      20   0  126.9g 115.0g  23364 R 39.0 91.4 194:09.15 20221111_082655
28726 root      20   0  126.9g 115.0g  23364 R 39.0 91.4 109:14.25 20221111_082823
18923 root      20   0  126.9g 115.0g  23364 R 38.7 91.4 658:06.94 20221111_082822
13760 root      20   0  126.9g 115.0g  23364 R 37.1 91.4 238:14.91 20221111_082731
 1419 root      20   0  126.9g 115.0g  23364 R 37.1 91.4 108:10.93 20221111_082709
13449 root      20   0  126.9g 115.0g  23364 R 36.4 91.4  98:47.20 20221111_082812
 8233 root      20   0  126.9g 115.0g  23364 R 33.9 91.4 224:11.37 20221111_082822
14387 root      20   0  126.9g 115.0g  23364 R 31.6 91.4 218:27.73 20221111_082822
 4150 root      20   0  126.9g 115.0g  23364 R 31.6 91.4 195:37.79 20221111_082820
24704 root      20   0  126.9g 115.0g  23364 R 31.3 91.4 118:58.37 20221111_082822
 9278 root      20   0  126.9g 115.0g  23364 R 30.7 91.4 108:26.28 20221111_082721
15280 root      20   0  126.9g 115.0g  23364 R 30.0 91.4 218:36.35 20221111_082823
15291 root      20   0  126.9g 115.0g  23364 R 28.8 91.4 218:12.50 20221111_082822
10713 root      20   0  126.9g 115.0g  23364 R 27.8 91.4 219:00.52 20221111_082748
 9347 root      20   0  126.9g 115.0g  23364 R 27.5 91.4 221:35.15 20221111_082812
20129 root      20   0  126.9g 115.0g  23364 R 27.5 91.4 118:44.53 20221111_082723
 4600 root      20   0  126.9g 115.0g  23364 R 26.8 91.4 696:17.12 20221111_082822
25138 root      20   0  126.9g 115.0g  23364 R 26.8 91.4 118:47.29 20221111_082823
28688 root      20   0  126.9g 115.0g  23364 R 26.2 91.4 106:46.94 20221111_082707
10346 root      20   0  126.9g 115.0g  23364 R 24.9 91.4 220:12.03 20221111_082823
13288 root      20   0  126.9g 115.0g  23364 R 23.6 91.4 218:16.71 20221111_082823
13295 root      20   0  126.9g 115.0g  23364 R 23.6 91.4 218:38.99 20221111_082822
27891 root      20   0  126.9g 115.0g  23364 S 23.6 91.4   1:22.88 C2 CompilerThre
11142 root      20   0  126.9g 115.0g  23364 R 19.8 91.4  98:36.68 20221111_082818
 4626 root      20   0  126.9g 115.0g  23364 S 18.8 91.4 420:18.39 task-management
13301 root      20   0  126.9g 115.0g  23364 R 17.9 91.4 219:05.70 20221111_082818
  519 root      20   0  126.9g 115.0g  23364 R 16.6 91.4 195:10.36 20221111_082808
23952 root      20   0  126.9g 115.0g  23364 R 16.0 91.4   0:17.39 http-worker-694
27881 root      20   0  126.9g 115.0g  23364 R 14.7 91.4   1:18.90 C2 CompilerThre
27923 root      20   0  126.9g 115.0g  23364 R 14.7 91.4   1:14.88 C2 CompilerThre
 4532 root      20   0  126.9g 115.0g  23364 R 14.4 91.4 117:25.27 Sweeper thread
10882 root      20   0  126.9g 115.0g  23364 S 14.4 91.4   0:51.05 http-worker-688
 9496 root      20   0  126.9g 115.0g  23364 R 13.7 91.4 223:05.04 20221111_082822
27921 root      20   0  126.9g 115.0g  23364 R 13.4 91.4   1:17.59 C2 CompilerThre
24033 root      20   0  126.9g 115.0g  23364 S 12.8 91.4   0:11.63 http-worker-694
 4530 root      20   0  126.9g 115.0g  23364 R 12.1 91.4   1001:01 C2 CompilerThre
10755 root      20   0  126.9g 115.0g  23364 S 12.1 91.4   0:54.13 http-worker-687
10805 root      20   0  126.9g 115.0g  23364 S 12.1 91.4   0:51.51 http-worker-687

Below are some top process from jstack:

jstack -l  4517 | grep 2fad -A 10

"C2 CompilerThread1" #8 daemon prio=9 os_prio=0 cpu=322748.73ms elapsed=2601.11s tid=0x00007f2c185d5460 nid=0x2fad runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   Compiling: 5957489       4       io.trino.$gen.PageFilter_20221111_075226_1575863::filter (81 bytes)

   Locked ownable synchronizers:
	- None

"http-worker-68888" #68888 prio=5 os_prio=0 cpu=30640.25ms elapsed=2589.85s tid=0x00007f2bf06a7c90 nid=0x2ffc waiting on condition  [0x00007f2a430ae000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4/Native Method)
	- parking to wait for  <0x00007f2d6332f630> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)

 jstack -l 4517 | grep 3b85 -A 10

"C2 CompilerThread6" #13 daemon prio=9 os_prio=0 cpu=207197.03ms elapsed=1814.13s tid=0x00007f2a586b8200 nid=0x3b85 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   Compiling: 5957566       4       io.trino.$gen.PageFilter_20221111_075309_1575900::filter (485 bytes)

   Locked ownable synchronizers:
	- None

"C2 CompilerThread7" #14 daemon prio=9 os_prio=0 cpu=210672.66ms elapsed=1814.05s tid=0x00007f2a58523d90 nid=0x3b86 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   Compiling: 5957332       4       io.trino.$gen.PageFilter_20221111_075147_1575837::filter (553 bytes)

jstack -l 4517 | grep 7036  -A 10
"20221111_075854_66105_uztrp.3.2.0-1-62029" #62029 prio=5 os_prio=0 cpu=6141695.45ms elapsed=111445.25s tid=0x00007f2c34924bd0 nid=0x7036 runnable  [0x00007f2a47cfa000]
   java.lang.Thread.State: RUNNABLE
	at io.trino.$gen.PageFilter_20221111_075856_1576038.filter(Unknown Source)
	at io.trino.operator.project.PageProcessor.createWorkProcessor(PageProcessor.java:120)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.lambda$processPageSource$1(ScanFilterAndProjectOperator.java:295)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages$$Lambda$5119/0x0000000802015250.apply(Unknown Source)
	at io.trino.operator.WorkProcessorUtils.lambda$flatMap$5(WorkProcessorUtils.java:264)
	at io.trino.operator.WorkProcessorUtils$$Lambda$5123/0x0000000802015de0.process(Unknown Source)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)

jstack -l 4517 | grep 0x207 -A 10
"20221111_080826_66897_uztrp.2.1.0-1-52909" #52909 prio=5 os_prio=0 cpu=11408466.13ms elapsed=362168.15s tid=0x00007f2b8c223ff0 nid=0x207 runnable  [0x00007f2a471ef000]
   java.lang.Thread.State: RUNNABLE
	at io.trino.parquet.reader.PrimitiveColumnReader.lambda$readValues$2(PrimitiveColumnReader.java:248)
	at io.trino.parquet.reader.PrimitiveColumnReader$$Lambda$5271/0x000000080207a128.run(Unknown Source)
	at io.trino.parquet.reader.PrimitiveColumnReader.processValues(PrimitiveColumnReader.java:304)
	at io.trino.parquet.reader.PrimitiveColumnReader.readValues(PrimitiveColumnReader.java:246)
	at io.trino.parquet.reader.PrimitiveColumnReader.readPrimitive(PrimitiveColumnReader.java:235)
	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:378)
	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:480)
	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:463)
	at io.trino.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:212

**Comment by njalan** [comment]
it takes too mush time at stage 0:
![image](https://user-images.githubusercontent.com/8622340/201304180-6c31247c-97fd-43d7-8a1f-f1b0f9def7e2.png)

**Comment by njalan** [comment]
Attached Cpu profile
[20221114-211036.html.zip](https://github.com/trinodb/trino/files/10003523/20221114-211036.html.zip)

**Comment by njalan** [comment]
Can anyone take a look at this ?

**Comment by findepi** [comment]
cc @raunaqmorarka or @sopel39

**Comment by sopel39** [comment]
Does it go away when server is restarted? Is there a single query that causes that (could you share query json?)

**Comment by njalan** [comment]
@sopel39 I am running same 10 queries by jemeter for a couple of days. Initially there is no issues but after like 10 days most of the queries are running timeout. After restart the server then query is running fine. But after a couple of days most of queries running timeout again.

**Comment by sopel39** [comment]
cc @dain

**Comment by sopel39** [comment]
@njalan What is your jvm.config and config.properties?

**Comment by njalan** [comment]
@sopel39 Below is config:
 cat config.properties
coordinator=false
http-server.http.port=8084
internal-communication.shared-secret=trino
discovery.uri=http://xxxxx:8084


Below is the  jvm.config and all the worker node is 125G
-server
-Xmx110G
-XX:InitialRAMPercentage=80
-XX:MaxRAMPercentage=80
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+ExitOnOutOfMemoryError
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-XX:ReservedCodeCacheSize=2G
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-Djdk.attach.allowAttachSelf=true
-Djdk.nio.maxCachedBufferSize=2000000
-XX:+UnlockDiagnosticVMOptions
-XX:+UseAESCTRIntrinsics
-Djava.io.tmpdir=/data/trinossl/jvm
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.local.only=false
-Dcom.sun.management.jmxremote.port=38084
-javaagent:/opt/bigdata/monitor/jmx_prometheus_javaagent.jar=xxxxx:28084:/xxxx/trino-server-394/etc/presto_prometheus_jmx_exporter.yml


All the nodes have the same config  file but only one node's cpu is always high.

**Comment by sopel39** [comment]
@njalan what JVM vendor do you use?

**Comment by njalan** [comment]
@sopel39 I am using zulu17.36.13-ca-jdk17.0.4-linux_x64

**Comment by njalan** [comment]
@sopel39 May I know any updates on it?

**Comment by sopel39** [comment]
> @sopel39 May I know any updates on it?

@dain suggestion was to contact JVM vendor (Azul).
Could you also try Jvm 19?

**Comment by njalan** [comment]
@sopel39 you mean let me try with Jvm 19? Do you have any specific version advised?  Do I need to upgrade to the latest trino version to test? It is currently in testing environment with trino.

**Comment by njalan** [comment]
@sopel39 https://trino.io/docs/current/installation/deployment.html 
it says **Newer major versions such as Java 18 or 19, are not supported – they may work, but are not tested.**

**Comment by sopel39** [comment]
Yes. I mean testing since this is testing env AFAIU

**Comment by akenO8** [comment]
![Image](https://github.com/user-attachments/assets/26d91d76-0ab4-4607-8cd5-92e8acb0ef9c)
I had a similar problem, in the same cluster, there were queries all the time, and the average query duration was less than 5 minutes. In my opinion, the tasks are distributed randomly, and the load of all workers should be balanced, but the load performance of workers is different. In peak times, this difference will amplify the problem, resulting in too long task execution time and poor cluster stability. version: 452.

**Comment by akenO8** [comment]
> [@akenO8](https://github.com/akenO8) you can check if tasks are skewed by running `EXPLAIN ANALYZE VERBOSE`. There should be distribution stats there

I don't think it's a question of one query, because there are so many different queries all the time.
The following is the result of executing EXPLAIN ANALYZE VERBOSE on a relatively large query, and I don't see any problems.

[EXPLAIN_ANALYZE_VERBOSE.log](https://github.com/user-attachments/files/19629093/EXPLAIN_ANALYZE_VERBOSE.log)
