### ISSUE TITLE
Flaky Delta Lake Databricks product tests

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#15069]
https://github.com/trinodb/trino/actions/runs/3483769315/jobs/5827818378

```
2022-11-17T00:39:36.1273014Z tests               | 2022-11-17 06:24:36 INFO: FAILURE     /    io.trino.tests.product.deltalake.TestDeltaLakeWriteDatabricksCompatibility.testCaseDeleteEntirePartition [downpart] (Groups: profile_specific_tests, delta-lake-databricks) took 1 minutes and 39 seconds
2022-11-17T00:39:36.1273988Z tests               | 2022-11-17 06:24:36 SEVERE: Failure cause:
2022-11-17T00:39:36.1275647Z tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: [Databricks][DatabricksJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: Error running query: com.databricks.s3commit.S3CommitFailedException: Unable to execute HTTP request: Connect to trino-ci-test.s3.us-east-2.amazonaws.com:443 [trino-ci-test.s3.us-east-2.amazonaws.com/3.5.129.110] failed: connect timed out, Query: CREATE TABLE default.delete_case_compat_hf08z7atw7 (lower int, UPPER int, downpart int)
2022-11-17T00:39:36.1276653Z tests               | USING DELTA
2022-11-17T00:39:36.1276965Z tests               | PARTITIONED BY (downpart)
2022-11-17T00:39:36.1277542Z tests               | LOCATION 's3://trino-ci-test/databricks-compatibility-test-delete_case_compat_hf08z7atw7'.
2022-11-17T00:39:36.1278117Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
2022-11-17T00:39:36.1278692Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2022-11-17T00:39:36.1279287Z tests               | 	at io.trino.tests.product.utils.QueryExecutors$3.lambda$executeQuery$0(QueryExecutors.java:141)
2022-11-17T00:39:36.1279807Z tests               | 	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
2022-11-17T00:39:36.1280320Z tests               | 	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:62)
2022-11-17T00:39:36.1280853Z tests               | 	at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
2022-11-17T00:39:36.1281342Z tests               | 	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
2022-11-17T00:39:36.1281842Z tests               | 	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:67)
2022-11-17T00:39:36.1282455Z tests               | 	at io.trino.tests.product.utils.QueryExecutors$3.executeQuery(QueryExecutors.java:141)
2022-11-17T00:39:36.1283201Z tests               | 	at io.trino.tests.product.deltalake.TestDeltaLakeWriteDatabricksCompatibility$CaseTestTable.<init>(TestDeltaLakeWriteDatabricksCompatibility.java:438)
2022-11-17T00:39:36.1284212Z tests               | 	at io.trino.tests.product.deltalake.TestDeltaLakeWriteDatabricksCompatibility.testCaseDeleteEntirePartition(TestDeltaLakeWriteDatabricksCompatibility.java:229)
2022-11-17T00:39:36.1285052Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-11-17T00:39:36.1285657Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-11-17T00:39:36.1286313Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-11-17T00:39:36.1286874Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-11-17T00:39:36.1300058Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-11-17T00:39:36.1300747Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-11-17T00:39:36.1301261Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-11-17T00:39:36.1301760Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-11-17T00:39:36.1302327Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-11-17T00:39:36.1302884Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-11-17T00:39:36.1303451Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-11-17T00:39:36.1304062Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-11-17T00:39:36.1304551Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ebyhr** [comment]
We may need to change `DATABRICKS_COMMUNICATION_FAILURE_MATCH` pattern:
```
tests               | 2022-11-18 09:09:28 WARNING: not retrying; stacktrace 'java.lang.RuntimeException: java.sql.SQLException: [Databricks][DatabricksJDBCDriver](500593) Communication link failure. Failed to connect to server. Reason: com.databricks.client.jdbc42.internal.apache.http.conn.ConnectTimeoutException: Connect to dbc-88a53597-967a.cloud.databricks.com:443 [dbc-88a53597-967a.cloud.databricks.com/3.128.237.223] failed: Connection timed out.
```

https://github.com/trinodb/trino/actions/runs/3493626172/jobs/5848793293

**Comment by ebyhr** [comment]
It was very flaky on Nov 17, but somehow it's stable now. I will reopen or file a new issue if necessary.
