### ISSUE TITLE
io.prestosql.cost.CachingStatsProvider	Error cause query queue very high

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#15074]
Below is the error message and some times got this message and this error tables within 5 minutes:

	ERROR	Query-20221114_113501_24969_8bgqq-67499	io.prestosql.cost.CachingStatsProvider	Error occurred when computing stats for query 20221114_113501_24969_8bgqq
io.prestosql.NotInTransactionException: Unknown transaction ID: bb335171-a577-4bc4-8730-dba0d5fc108d. Possibly expired? Commands ignored until end of transaction block
	at io.prestosql.transaction.InMemoryTransactionManager.getTransactionMetadata(InMemoryTransactionManager.java:257)
	at io.prestosql.transaction.InMemoryTransactionManager.getCatalogMetadata(InMemoryTransactionManager.java:199)
	at io.prestosql.metadata.MetadataManager.getCatalogMetadata(MetadataManager.java:1812)
	at io.prestosql.metadata.MetadataManager.getTableProperties(MetadataManager.java:434)
	at io.prestosql.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:62)
	at io.prestosql.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:39)

**Comment by njalan** [comment]
@findepi  Can you please take a look at below ticket raised by me also and it is on trino 394.
https://github.com/trinodb/trino/issues/14996
