### ISSUE TITLE
Support multiple authentication types for web-ui.authentication.type

### ISSUE THREAD

**Issue by vishalya** [trinodb/trino#15137]
The api server supports mulitple authentication types  e.g. The config for the api could be 
```
http-server.authentication.type=oauth2,PASSWORD
```
But the config for the web-ui can support only one type of the authentication. It should follow the same pattern as api
```
web-ui.authentication.type=oauth2,form
```
With the above web-ui config coordinator fails to start with the following error - 
```
1) [Guice/JitDisabled]: Explicit bindings are required and WebUiAuthenticationFilter is not explicitly bound.
  at ResourceSecurityDynamicFeature.<init>(ResourceSecurityDynamicFeature.java:70)
      \_ for 3rd parameter webUiAuthenticationFilter
  at ServerSecurityModule.setup(ServerSecurityModule.java:57)

```

**Comment by hashhar** [comment]
cc: @dain

**Comment by dain** [comment]
The UI only supports a single authentication method. It is possible to support multiple authentication systems, but it would require some changes... it isn't hard but likely a few days worth of work.

**Comment by Chaho12** [comment]
Would be great if this multiple web ui authentication is supported!

**Comment by Chaho12** [comment]
i notice this simply installs single module in [code](https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/server/ui/WebUiAuthenticationModule.java#L101-L106) 

would changing it to code below work as simple?
https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/server/security/ServerSecurityModule.java#L56-L95
