### ISSUE TITLE
Iceberg `register_table` procedure can't register partitioned tables

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#15191]
```sh
io.trino.spi.TrinoException: No versioned metadata file exists at location: /var/folders/8s/dkvf18z55lj_9yxhy1n54sph0000gn/T/test_iceberg_register_table11465907991788873203/tpch/test_register_partitioned_table_orc_7en0y52cwf-10defc47876346ce9c1ff8c7c1c7ff13/data/metadata
	at io.trino.plugin.iceberg.procedure.RegisterTableProcedure.getLatestMetadataLocation(RegisterTableProcedure.java:203)
	at io.trino.plugin.iceberg.procedure.RegisterTableProcedure.lambda$getMetadataLocation$1(RegisterTableProcedure.java:175)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.trino.plugin.iceberg.procedure.RegisterTableProcedure.getMetadataLocation(RegisterTableProcedure.java:175)
	at io.trino.plugin.iceberg.procedure.RegisterTableProcedure.doRegisterTable(RegisterTableProcedure.java:147)
	at io.trino.plugin.iceberg.procedure.RegisterTableProcedure.registerTable(RegisterTableProcedure.java:116)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:757)
	at io.trino.execution.CallTask.execute(CallTask.java:211)
	at io.trino.execution.CallTask.execute(CallTask.java:71)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20221125_091918_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ebyhr** [comment]
It was test specific issue. I sent #15207 for tests, but closing this issue.
