### ISSUE TITLE
Flaky OutOfMemoryError trino-faulttolerant-tests

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#15293]
splitting out from https://github.com/trinodb/trino/issues/14248

@ebyhr  https://github.com/trinodb/trino/issues/14248#issuecomment-1336748420

> `testing/trino-faulttolerant-tests, test-fault-tolerant-hive-2` failed with OutOfMemoryError.
https://github.com/trinodb/trino/actions/runs/3616948145/jobs/6095378984

**Comment by findepi** [comment]
For the above run (https://github.com/trinodb/trino/actions/runs/3616948145/jobs/6095378984), the Summary (https://github.com/trinodb/trino/actions/runs/3616948145) has this

<img width="774" alt="image" src="https://user-images.githubusercontent.com/144328/205633527-05cd91cb-823d-46c7-953c-b5c24f330811.png">


thank you @nineinchnick!

cc @arhimondr @losipiuk and @linzebing since it happened in faulttolerant tests.

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/3620072161/jobs/6102455167

```
Error:  java.lang.OutOfMemoryError: Java heap space
Error:  Terminating due to java.lang.OutOfMemoryError: Java heap space
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
Warning:  Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/runner/work/trino/trino/testing/trino-faulttolerant-tests/target/surefire-reports/2022-12-05T13-55-03_056-jvmRun1.dumpstream
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:09 min
[INFO] Finished at: 2022-12-05T13:59:05Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project trino-faulttolerant-tests: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/trino/trino/testing/trino-faulttolerant-tests/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd /home/runner/work/trino/trino/testing/trino-faulttolerant-tests && /opt/hostedtoolcache/Java_Zulu_jdk/17.0.5-8/x64/bin/java -Duser.timezone=America/Bahia_Banderas -Duser.language=en -Duser.region=US -Dfile.encoding=UTF-8 -Xmx3g -Xms3g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -jar /home/runner/work/trino/trino/testing/trino-faulttolerant-tests/target/surefire/surefirebooter6470061530236542225.jar /home/runner/work/trino/trino/testing/trino-faulttolerant-tests/target/surefire 2022-12-05T13-55-03_056-jvmRun1 surefire9046702879014656174tmp surefire_014162616108651171144tmp
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 3
Error:  Crashed tests:
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionAggregations
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionConnectorTest
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionJoinQueries
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionTest
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd /home/runner/work/trino/trino/testing/trino-faulttolerant-tests && /opt/hostedtoolcache/Java_Zulu_jdk/17.0.5-8/x64/bin/java -Duser.timezone=America/Bahia_Banderas -Duser.language=en -Duser.region=US -Dfile.encoding=UTF-8 -Xmx3g -Xms3g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -jar /home/runner/work/trino/trino/testing/trino-faulttolerant-tests/target/surefire/surefirebooter6470061530236542225.jar /home/runner/work/trino/trino/testing/trino-faulttolerant-tests/target/surefire 2022-12-05T13-55-03_056-jvmRun1 surefire9046702879014656174tmp surefire_014162616108651171144tmp
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 3
Error:  Crashed tests:
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionAggregations
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionConnectorTest
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionJoinQueries
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionTest
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
Error:  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
Error:  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
Error:  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
Error:  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
Error:  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Error:  	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:47)
Error:  	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:156)
Error:  	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
Error:  -> [Help 1]
```

**Comment by findepi** [comment]
guys, did you find anything interesting in the attached heap dump?

**Comment by arhimondr** [comment]
Haven't had a chance to look into it. Going to take a look soon.

**Comment by huberty89** [comment]
https://github.com/trinodb/trino/actions/runs/3656718173/jobs/6179497723

```
Error:  Please refer to /home/runner/work/trino/trino/testing/trino-faulttolerant-tests/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd /home/runner/work/trino/trino/testing/trino-faulttolerant-tests && /opt/hostedtoolcache/Java_Zulu_jdk/17.0.5-8/x64/bin/java -Duser.timezone=America/Bahia_Banderas -Duser.language=en -Duser.region=US -Dfile.encoding=UTF-8 -Xmx3g -Xms3g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -jar /home/runner/work/trino/trino/testing/trino-faulttolerant-tests/target/surefire/surefirebooter12198436092246495648.jar /home/runner/work/trino/trino/testing/trino-faulttolerant-tests/target/surefire 2022-12-09T11-00-26_881-jvmRun1 surefire14832856115746630504tmp surefire_011656816868573313923tmp
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 3
Error:  Crashed tests:
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionAggregations
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionConnectorTest
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionJoinQueries
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionTest
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

**Comment by linzebing** [comment]
![image](https://user-images.githubusercontent.com/9404831/207440980-dcdde3d5-889d-444c-83af-36f7dcde612e.png)
Can't parse the heap dump

**Comment by linzebing** [comment]
I didn't see any outstanding issues from the heap dump:
![image](https://user-images.githubusercontent.com/9404831/207711299-7e37c864-8c62-45de-906f-cfbe27c7040f.png)

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/3764021682/jobs/6398062123

**Comment by losipiuk** [comment]
`-XX:G1HeapRegionSize=32M` introduced by https://github.com/trinodb/trino/pull/15471 does not help here @findepi  :/

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/3840312420/jobs/6539306781 

```
Error:  java.lang.OutOfMemoryError: Java heap space
Error:  Terminating due to java.lang.OutOfMemoryError: Java heap space
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
Warning:  Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/runner/work/trino/trino/testing/trino-faulttolerant-tests/target/surefire-reports/2023-01-04T18-09-16_465-jvmRun1.dumpstream
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:32 min
[INFO] Finished at: 2023-01-04T18:14:43Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project trino-faulttolerant-tests: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/trino/trino/testing/trino-faulttolerant-tests/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd /home/runner/work/trino/trino/testing/trino-faulttolerant-tests && /opt/hostedtoolcache/Java_Zulu_jdk/17.0.5-8/x64/bin/java -Duser.timezone=America/Bahia_Banderas -Duser.language=en -Duser.region=US -Dfile.encoding=UTF-8 -Xmx3g -Xms3g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -XX:G1HeapRegionSize=32M -jar /home/runner/work/trino/trino/testing/trino-faulttolerant-tests/target/surefire/surefirebooter9610229286998227292.jar /home/runner/work/trino/trino/testing/trino-faulttolerant-tests/target/surefire 2023-01-04T18-09-16_465-jvmRun1 surefire13308688913671040296tmp surefire_09609415452462336212tmp
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 3
Error:  Crashed tests:
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionAggregations
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionJoinQueries
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionTest
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

**Comment by arhimondr** [comment]
I analyzed two different heap dumps. Both of them report only 1.1GB of live objects:

![image](https://user-images.githubusercontent.com/5570988/211052191-ac7f25c6-e454-4bc3-9dcc-324498fd93e1.png)
![image](https://user-images.githubusercontent.com/5570988/211052216-3b06c00e-477e-4938-a48e-d9ed5b9cdced.png)

I don't see anything that would be outstanding or suspicious:

![image](https://user-images.githubusercontent.com/5570988/211052321-582c021c-9f98-4aa1-86b1-77f0fb40c47a.png)
![image](https://user-images.githubusercontent.com/5570988/211052350-46a38781-5fa3-41c6-a866-80458a4c538b.png)

From what I see we allocate 3GB for tests:

![image](https://user-images.githubusercontent.com/5570988/211052562-601a5478-a3b6-4126-b3e8-bba7852a49ab.png)

Hard to say why does the JVM decide to throw an OOM when there are only 1.1GB of live objects.

I'm thinking about setting `-XX:-G1UsePreventiveGC` (https://github.com/trinodb/trino/pull/15380) to make sure this behavior is not caused by the bug described in the PR and also increasing number of GCLocker attempts by adjusting `-XX:GCLockerRetryAllocationCount=10` to make sure that's a not JNI related fluke.

**Comment by findepi** [comment]
hopefully obsolete
