### ISSUE TITLE
Flaky test TestHiveStorageFormats.testTimestampCreatedFromHive

### ISSUE THREAD

**Issue by homar** [trinodb/trino#15313]
Stacktrace:
```
2022-12-02T11:09:06.3068263Z tests               | 2022-12-02 16:54:06 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveStorageFormats.testTimestampCreatedFromHive [StorageFormat{name=RCTEXT, properties={}, sessionProperties={hive.rcfile_optimized_writer_validate=true}}] (Groups: storage_formats_detailed) took 49.8 seconds
2022-12-02T11:09:06.3077412Z tests               | 2022-12-02 16:54:06 SEVERE: Failure cause:
2022-12-02T11:09:06.3078362Z tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. Error caching map.xml: java.nio.channels.ClosedByInterruptException
2022-12-02T11:09:06.3079232Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
2022-12-02T11:09:06.3080461Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2022-12-02T11:09:06.3081100Z tests               | 	at io.trino.tests.product.hive.TestHiveStorageFormats.testTimestampCreatedFromHive(TestHiveStorageFormats.java:687)
2022-12-02T11:09:06.3081730Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-12-02T11:09:06.3082283Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-12-02T11:09:06.3082897Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-12-02T11:09:06.3083408Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-12-02T11:09:06.3083896Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-12-02T11:09:06.3084384Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-12-02T11:09:06.3084812Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-12-02T11:09:06.3085251Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-12-02T11:09:06.3085745Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-12-02T11:09:06.3086234Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-12-02T11:09:06.3086731Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-12-02T11:09:06.3087245Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-12-02T11:09:06.3087842Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-12-02T11:09:06.3088509Z tests               | Caused by: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. Error caching map.xml: java.nio.channels.ClosedByInterruptException
2022-12-02T11:09:06.3089169Z tests               | 	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:275)
2022-12-02T11:09:06.3089689Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
2022-12-02T11:09:06.3090330Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
2022-12-02T11:09:06.3090677Z tests               | 	... 15 more
2022-12-02T11:09:06.3091342Z tests               | 	Suppressed: java.lang.Exception: Query: INSERT INTO timestamps_from_hive_rctext_mcv1pysrlq VALUES (4, '1967-01-02 12:01:00.1113334')
2022-12-02T11:09:06.3091894Z tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
2022-12-02T11:09:06.3092278Z tests               | 		... 16 more

```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/3947125426/jobs/6756087759

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/3984597033/jobs/6831311620
```
tests               | 2023-01-23 15:11:48 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveStorageFormats.testStructTimestampsFromHive [StorageFormat{name=SEQUENCEFILE, properties={}, sessionProperties={}}] (Groups: storage_formats_detailed) took 1 minutes and 18 seconds
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4766640955/jobs/8476063008?pr=17175

```
tests               | 2023-04-22 04:07:46 INFO: FAILURE     /    io.trino.tests.product.hive.TestCsv.testReadCsvTableWithMultiCharProperties (Groups: storage_formats) took 1.2 seconds
tests               | 2023-04-22 04:07:46 SEVERE: Failure cause:
tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. Error caching map.xml: java.nio.channels.ClosedByInterruptException
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.hive.TestCsv.testReadCsvTableWithMultiCharProperties(TestCsv.java:194)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
tests               | Caused by: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. Error caching map.xml: java.nio.channels.ClosedByInterruptException
tests               | 	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:275)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 	... 15 more
tests               | 	Suppressed: java.lang.Exception: Query: INSERT INTO storage_formats_test_read_csv_table_with_multi_char_properties(a, b, c) VALUES ('1', 'a', 'A'), ('2', 'b', 'B'), ('3', 'c', 'C')
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
tests               | 		... 16 more
tests               | 
```
