### ISSUE TITLE
trino cannot query doris 1.1.5

### ISSUE THREAD

**Issue by Yifan122** [trinodb/trino#15331]
version:
trino: 360 (aws emr)
doris: 1.1.5

we previously install doris 1.1.0 and 1.1.1 which trino can query successfully. But after we upgrade doris to 1.1.5, trino cannot query the table.

when we run  the show schemas, it works well
```
show schemas in doris
```

But when we run show tables, it returns nothing.
```
show tables in doris.db;
```

When we query the table, it returns the error. However, if we use mysql client to connect doris, it works well
```
query:
select * from doris.rt_cdm.dwd_usr_deposit_detail_rt limit 10;

error stack:
io.prestosql.spi.PrestoException: line 1:15: Table 'doris.rt_cdm.dwd_usr_deposit_detail_rt' does not exist
	at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1041)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:306)
	at io.prestosql.sql.tree.Table.accept(Table.java:53)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:323)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2329)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1284)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:306)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:323)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:333)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:918)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:306)
	at io.prestosql.sql.tree.Query.accept(Query.java:107)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:323)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:292)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:246)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:180)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:746)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
	at io.prestosql.$gen.Presto_338____20221020_135206_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ebyhr** [comment]
What happens if you enable `case-insensitive-name-matching`?

**Comment by Yifan122** [comment]
enable case-insensitive-name-matching still cannot query the table, same issue above

**Comment by Yifan122** [comment]
> 
enable case-insensitive-name-matching still cannot query the table, same issue above

**Comment by Yifan122** [comment]
> What happens if you enable `case-insensitive-name-matching`?

enable case-insensitive-name-matching still cannot query the table, same issue above

**Comment by guiyanakuang** [comment]
@Yifan122 Try setting this configuration item `mysql.jdbc.use-information-schema=false` .
If it's working, then it should be the issue ：https://github.com/apache/doris/issues/14790

**Comment by ebyhr** [comment]
@Yifan122 By the way, I would recommend asking questions in [GitHub discussions](https://github.com/trinodb/trino/discussions) or [Slack](https://trino.io/slack.html).

**Comment by ArmstrongGou** [comment]
I have the same issue please solt it as soon as possible
