### ISSUE TITLE
Iceberg: optimize fails on table partitioned by uuid

### ISSUE THREAD

**Issue by joshuarobinson** [trinodb/trino#15349]
I have an iceberg table partitioned by a UUID field and I'm not able to call "alter table optimize". 

Environment: Trino 403 running on Iceberg with Hive Metastore catalog and data on S3.

```
trino:alpha_sherpa> ALTER TABLE locations EXECUTE optimize WHERE dataset_id=uuid '246fd026-18e0-4559-9871-d7f6cf04f513';
Query 20221208_165234_03934_6hk6h failed: Unexpected FilterNode found in plan; probably connector was not able to handle provided WHERE expression
```

Note that this table has 10k+ partitions, so I need to specify filters so that the operation can succeed.

my table definition:
```
trino:alpha_sherpa> show create table locations;
                                       Create Table                                       
------------------------------------------------------------------------------------------
 CREATE TABLE iceberg.alpha.locations (                                            
    datum_id uuid,                                                                        
    dataset_id uuid,                                                                      
    device varchar,                                                                       
    device_type varchar,                                                                  
    path varchar,                                                                         
    is_external boolean                                                                   
 )                                                                                        
 WITH (                                                                                   
    format = 'PARQUET',                                                                   
    format_version = 2,                                                                   
    location = 's3a://warehouse/alpha/locations-d393029e8c0e43f4bebb8758d605fa1d', 
    partitioning = ARRAY['dataset_id']                                                    
 )   
```

I don't see any error/warn messages in the coordinator logs.

Stack trace:
```
java.lang.IllegalStateException: Unexpected FilterNode found in plan; probably connector was not able to handle provided WHERE expression
	at io.trino.sql.planner.sanity.TableExecuteStructureValidator.lambda$validate$1(TableExecuteStructureValidator.java:57)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at io.trino.sql.planner.sanity.TableExecuteStructureValidator.validate(TableExecuteStructureValidator.java:55)
	at io.trino.sql.planner.sanity.PlanSanityChecker.lambda$validateFinalPlan$0(PlanSanityChecker.java:75)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at io.trino.sql.planner.sanity.PlanSanityChecker.validateFinalPlan(PlanSanityChecker.java:75)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:266)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:222)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:217)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:475)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:456)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:397)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_403____20221208_151418_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ebyhr** [comment]
That's intentionally disabled. See #12834 for more details.

**Comment by joshuarobinson** [comment]
any workarounds for optimizing tables with 10k+ partitions on UUID field?

**Comment by alexjo2144** [comment]
You could select your data using the `$path` or `$file_modified_time` hidden columns, rather than your partition key

**Comment by joshuarobinson** [comment]
hmmm, that doesn't work either....
```
trino:alpha_sherpa> ALTER TABLE locations
                 -> EXECUTE optimize
                 -> WHERE "$path" LIKE 's3a://warehouse/alpha/locations-d393029e8c0e43f4bebb8758d605fa1d/data/dataset_id=a26c9a3e-3db9-4%';
Query 20221214_102109_00152_6hk6h failed: Unexpected FilterNode found in plan; probably connector was not able to handle provided WHERE expression
```

**Comment by ebyhr** [comment]
@joshuarobinson Please avoid using `LIKE`.

**Comment by joshuarobinson** [comment]
I don't think it's the LIKE that's the problem, starts_with() doesn't work either.

```
> ALTER TABLE locations EXECUTE optimize WHERE starts_with("$path", 's3a://warehouse/alpha/locations-d393029e8c0e43f4bebb8758d605fa1d/data/dataset_id=a26c9a3e-3db9-4');
Query 20221214_121708_00173_6hk6h failed: Unexpected FilterNode found in plan; probably connector was not able to handle provided WHERE expression
```

Any suggestions on a way to use the "$path" special column that won't trip this bug?

**Comment by joshuarobinson** [comment]
Aha, got it. If I manually specify paths in the IN clause, it works. BUT if I try to use a select for the IN clause, it also doesn't work. Which means I'm not sure how I can create a query to build up the path list, but it's maybe a workaround.

And importantly, is the fixed needed in the Iceberg library or in Trino?  (Just want to make sure there's a bug against the right place)

**Comment by ebyhr** [comment]
> is the fixed needed in the Iceberg library or in Trino

This should be fixed in Trino. This is a limitation rather than a bug in my opinion.

**Comment by joshuarobinson** [comment]
Any update on this?  It appears to still be in issue in 418
