### ISSUE TITLE
Pinot smoke tests failed due to empty result

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#15367]
https://github.com/trinodb/trino/actions/runs/3672195779/jobs/6208163039

```
Error:  io.trino.plugin.pinot.TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest.testJoin  Time elapsed: 0.642 s  <<< FAILURE!
java.lang.AssertionError: Expected query to fail: SELECT n.name, r.name FROM nation n JOIN region r on n.regionkey = r.regionkey
	at org.testng.Assert.fail(Assert.java:94)
	at io.trino.testing.QueryAssertions.assertQueryFails(QueryAssertions.java:291)
	at io.trino.testing.AbstractTestQueryFramework.assertQueryFails(AbstractTestQueryFramework.java:400)
	at io.trino.plugin.pinot.BasePinotIntegrationConnectorSmokeTest.testJoin(BasePinotIntegrationConnectorSmokeTest.java:1034)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
to contain exactly in any order:
  <[(3.5, vendor1)]>
but could not find the following elements:
  <(3.5, vendor1)>

Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testFilterWithRealLiteral:1526 [Rows for query [SELECT price, vendor FROM my_table WHERE price = 3.5]] 
Expecting:
  <>
to contain exactly in any order:
  <[(3.5, vendor1)]>
but could not find the following elements:
  <(3.5, vendor1)>

Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testHavingClause:2510 [Rows for query [SELECT city, SUM(long_number)  FROM my_table  GROUP BY city  HAVING SUM(long_number) > 10000]] 
Expecting:
  <(New York, 20000), (Los Angeles, 50000)>
to contain exactly in any order:
  <[]>
but the following elements were unexpected:
  <(New York, 20000), (Los Angeles, 50000)>

Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testIntegerType:1050 [Rows for query [SELECT lucky_number FROM my_table WHERE vendor = 'vendor1']] 
Expecting:
  <>
to contain exactly in any order:
  <[(5)]>
but could not find the following elements:
  <(5)>

Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testJoin:1034->AbstractTestQueryFramework.assertQueryFails:400 Expected query to fail: SELECT n.name, r.name FROM nation n JOIN region r on n.regionkey = r.regionkey
Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testJson:2471 [Rows for query [SELECT json_col FROM json_table]] 
Expecting:
  <>
to contain exactly in any order:
  <[({"id":0,"name":"user_0"}),
    ({"id":1,"name":"user_1"}),
    ({"id":2,"name":"user_2"})]>
but could not find the following elements:
  <({"id":0,"name":"user_0"}), ({"id":1,"name":"user_1"}), ({"id":2,"name":"user_2"})>

Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testNonLowerTable:1186->AbstractTestQueryFramework.assertQuery:304 For query: 
 SELECT stringcol, longcol, updatedatseconds  FROM mixedCase
not equal
Actual rows (up to 100 of 0 extra rows shown, 0 rows in total):
    
Expected rows (up to 100 of 4 missing rows shown, 4 rows in total):
    [string_0, 0, 1670727416]
    [string_1, 1, 1670727417]
    [string_2, 2, 1670727418]
    [string_3, 3, 1670727419]

Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BaseConnectorSmokeTest.testPredicate:97->AbstractTestQueryFramework.assertQuery:294->AbstractTestQueryFramework.assertQuery:299 For query: 
 SELECT name, regionkey FROM nation WHERE nationkey = 10
not equal
Actual rows (up to 100 of 0 extra rows shown, 0 rows in total):
    
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
    [IRAN, 4]

Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testRealType:1043 » IllegalState
Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testTopN:1026->AbstractTestQueryFramework.assertQueryFails:400 Expected query to fail: SELECT regionkey FROM nation ORDER BY name LIMIT 3
[INFO] 
Error:  Tests run: 315, Failures: 11, Errors: 0, Skipped: 20
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/3755634329/jobs/6380932688

**Comment by ebyhr** [comment]
Some tests in `TestPinotWithoutAuthenticationIntegrationLatestVersionNoGrpcConnectorSmokeTest ` hit the same issue. 
https://github.com/trinodb/trino/actions/runs/3898826537/jobs/6657947142

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4407246706/jobs/7722034936?pr=16527


```
Error:  Tests run: 319, Failures: 15, Errors: 0, Skipped: 20, Time elapsed: 1,097.438 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.pinot.TestPinotWithoutAuthenticationIntegrationLatestVersionNoGrpcConnectorSmokeTest.testAggregation  Time elapsed: 13.514 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT sum(regionkey) FROM nation
	at org.testng.Assert.fail(Assert.java:83)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:335)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:330)
	at io.trino.testing.BaseConnectorSmokeTest.testAggregation(BaseConnectorSmokeTest.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.trino.testing.QueryFailedException: Query select sum("regionkey") from nation encountered exception code: '427' message: '1 servers [f864294ee336_R] not responded' with query "select sum("regionkey") from nation"
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:489)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 17 more
	Suppressed: java.lang.Exception: SQL: SELECT sum(regionkey) FROM nation
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:492)
		... 18 more
Caused by: io.trino.plugin.pinot.PinotException: Query select sum("regionkey") from nation encountered exception code: '427' message: '1 servers [f864294ee336_R] not responded' with query "select sum("regionkey") from nation"
	at io.trino.plugin.pinot.client.PinotClient.lambda$submitBrokerQueryJson$7(PinotClient.java:563)
	at io.trino.plugin.pinot.client.PinotClient.doWithRetries(PinotClient.java:631)
    [AFRICA]
    [AMERICA]
    [ASIA]
    [EUROPE]
    [MIDDLE EAST]

Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionNoGrpcConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testTimestamp:2451 
The following assertion failed:
1) [Rows for query [SELECT ts FROM alltypes ORDER BY ts LIMIT 1]] 
Expecting actual:
  
to contain exactly in any order:
  [(1970-01-01T00:00)]
but could not find the following elements:
  (1970-01-01T00:00)


Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionNoGrpcConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testVarbinary:2443 
The following assertion failed:
1) [Rows for query [SELECT bytes_col FROM alltypes WHERE string_col != 'array_null']] 
Expecting actual:
  
to contain exactly in any order:
  [([]),
    ([115, 116, 114, 105, 110, 103, 95, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 49, 50, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 50, 52, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 51, 54, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 52, 56, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 54, 48, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 55, 50, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 56, 52, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 57, 54, 48, 48])]
but could not find the following elements:
  ([]), ([115, 116, 114, 105, 110, 103, 95, 48]), ([115, 116, 114, 105, 110, 103, 95, 49, 50, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 50, 52, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 51, 54, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 52, 56, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 54, 48, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 55, 50, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 56, 52, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 57, 54, 48, 48])


Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionNoGrpcConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testVarbinaryFilters:1933 
The following assertion failed:
1) [Rows for query [SELECT string_col  FROM alltypes  WHERE bytes_col = X'']] 
Expecting actual:
  
to contain exactly in any order:
  [(null), (array_null)]
but could not find the following elements:
  (null), (array_null)


[INFO] 
Error:  Tests run: 319, Failures: 15, Errors: 0, Skipped: 20
[INFO] 
Warning:  Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/runner/work/trino/trino/plugin/trino-pinot/target/surefire-reports/2023-03-13T18-28-08_628-jvmRun1.dumpstream
[INFO] ------------------------------------------------------------------------
```

cc @elonazoulay

**Comment by findepi** [comment]
cc @elonazoulay

**Comment by elonazoulay** [comment]
This test (TestPinotWithoutAuthenticationIntegrationLatestVersionNoGrpcConnectorSmokeTest.testAggregation) works locally when run in isolation repeatedly. I will attempt to run this with less resources for docker and run all 4 integration tests in parallel and attempt to reproduce.
