### ISSUE TITLE
NPE when invoking Iceberg system.rollback_to_snapshot with NULL

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#15399]
```
trino:tpch> CREATE TABLE t(x int);
CREATE TABLE
trino:tpch> CALL system.rollback_to_snapshot(CURRENT_SCHEMA, 't', NULL);
Query 20221214_123006_00029_8azn7 failed: Cannot invoke "java.lang.Long.longValue()" because "snapshotId" is null
io.trino.spi.TrinoException: Cannot invoke "java.lang.Long.longValue()" because "snapshotId" is null
	at io.trino.execution.CallTask.execute(CallTask.java:218)
	at io.trino.execution.CallTask.execute(CallTask.java:71)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20221214_122932_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "snapshotId" is null
	at io.trino.plugin.iceberg.RollbackToSnapshotProcedure.rollbackToSnapshot(RollbackToSnapshotProcedure.java:74)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:757)
	at io.trino.execution.CallTask.execute(CallTask.java:211)
	... 8 more
```

cc @djsstarburst

**Comment by findepi** [comment]
Note that NPE is wrapped with meaningless `TrinoException`. It should not be IMO.
