### ISSUE TITLE
Flaky TestSqlServerConnectorTest.checkQueryInfosFinal test check: query is expected to be in a done state

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#15430]
https://github.com/trinodb/trino/actions/runs/3704502522/jobs/6277997232

```
Error:  Tests run: 673, Failures: 1, Errors: 0, Skipped: 116, Time elapsed: 976.35 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.sqlserver.TestSqlServerConnectorTest.close  Time elapsed: 31.395 s  <<< FAILURE!
java.lang.AssertionError: query is expected to be in done state: CREATE TABLE concur_table_p8ti5cvfge(a integer)
	at org.testng.Assert.fail(Assert.java:94)
	at io.trino.testing.AbstractTestQueryFramework.lambda$checkQueryInfosFinal$4(AbstractTestQueryFramework.java:195)
	at io.trino.testing.assertions.Assert.assertEventually(Assert.java:77)
	at io.trino.testing.AbstractTestQueryFramework.lambda$checkQueryInfosFinal$5(AbstractTestQueryFramework.java:186)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.testing.AbstractTestQueryFramework.checkQueryInfosFinal(AbstractTestQueryFramework.java:186)
	at io.trino.testing.AbstractTestQueryFramework.close(AbstractTestQueryFramework.java:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by findepi** [comment]
cc @arhimondr  per https://github.com/trinodb/trino/pull/14328

**Comment by gaurav8297** [comment]
Kind of similar error occurred in https://github.com/trinodb/trino/actions/runs/4306496034/jobs/7516553974

```
Error:  io.trino.plugin.sqlserver.TestSqlServerConnectorTest.close  Time elapsed: 32.302 s  <<< FAILURE!
java.lang.AssertionError: 
query is expected to be in a done state

Query 20230302_025032_05488_exuhj [RUNNING]: DROP TABLE concur_table_8qzkqf3sw7 -- <no output stage present>
	at org.testng.Assert.fail(Assert.java:94)
	at io.trino.testing.AbstractTestQueryFramework.lambda$checkQueryInfosFinal$4(AbstractTestQueryFramework.java:198)
	at io.trino.testing.assertions.Assert.assertEventually(Assert.java:77)
	at io.trino.testing.AbstractTestQueryFramework.lambda$checkQueryInfosFinal$5(AbstractTestQueryFramework.java:189)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.testing.AbstractTestQueryFramework.checkQueryInfosFinal(AbstractTestQueryFramework.java:189)
	at io.trino.testing.AbstractTestQueryFramework.close(AbstractTestQueryFramework.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4479729229/jobs/7874126054?pr=16644

```
Error:  Tests run: 748, Failures: 1, Errors: 0, Skipped: 182, Time elapsed: 1,030.759 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.sqlserver.TestSqlServerConnectorTest.close  Time elapsed: 32.668 s  <<< FAILURE!
java.lang.AssertionError: 
query is expected to be in a done state

Query 20230321_140543_05604_w5q9i [RUNNING]: CREATE TABLE concur_table_h708heo3g9(a integer) -- <no output stage present>
	at org.testng.Assert.fail(Assert.java:94)
	at io.trino.testing.AbstractTestQueryFramework.lambda$checkQueryInfosFinal$4(AbstractTestQueryFramework.java:198)
	at io.trino.testing.assertions.Assert.assertEventually(Assert.java:43)
	at io.trino.testing.AbstractTestQueryFramework.lambda$checkQueryInfosFinal$5(AbstractTestQueryFramework.java:189)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.testing.AbstractTestQueryFramework.checkQueryInfosFinal(AbstractTestQueryFramework.java:189)
	at io.trino.testing.AbstractTestQueryFramework.close(AbstractTestQueryFramework.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestSqlServerConnectorTest>AbstractTestQueryFramework.close:119->AbstractTestQueryFramework.checkQueryInfosFinal:189->AbstractTestQueryFramework.lambda$checkQueryInfosFinal$5:189->AbstractTestQueryFramework.lambda$checkQueryInfosFinal$4:198 query is expected to be in a done state

Query 20230321_140543_05604_w5q9i [RUNNING]: CREATE TABLE concur_table_h708heo3g9(a integer) -- <no output stage present>
[INFO] 
```

cc @arhimondr @pettyjamesm @linzebing

**Comment by arhimondr** [comment]
@mwd410 Could you please take a look?

**Comment by homar** [comment]
happened again here: https://github.com/trinodb/trino/actions/runs/4621016431/jobs/8173886603?pr=16205

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4675615638/jobs/8281421815?pr=16961

```
Error:  io.trino.plugin.sqlserver.TestSqlServerConnectorTest.close  Time elapsed: 31.631 s  <<< FAILURE!
java.lang.AssertionError: 
query is expected to be in a done state

Query 20230412_083209_07241_au8mz [FINISHING]: DROP TABLE concur_table_37eclfdgtw -- <no output stage present>
	at org.testng.Assert.fail(Assert.java:94)
	at io.trino.testing.AbstractTestQueryFramework.lambda$checkQueryInfosFinal$4(AbstractTestQueryFramework.java:199)
	at io.trino.testing.assertions.Assert.assertEventually(Assert.java:43)
	at io.trino.testing.AbstractTestQueryFramework.lambda$checkQueryInfosFinal$5(AbstractTestQueryFramework.java:190)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.testing.AbstractTestQueryFramework.checkQueryInfosFinal(AbstractTestQueryFramework.java:190)
	at io.trino.testing.AbstractTestQueryFramework.close(AbstractTestQueryFramework.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestSqlServerConnectorTest>AbstractTestQueryFramework.close:120->AbstractTestQueryFramework.checkQueryInfosFinal:190->AbstractTestQueryFramework.lambda$checkQueryInfosFinal$5:190->AbstractTestQueryFramework.lambda$checkQueryInfosFinal$4:199 query is expected to be in a done state
```

@arhimondr @losipiuk @joshthoward

**Comment by findepi** [comment]
> https://github.com/trinodb/trino/actions/runs/4675615638/jobs/8281421815?pr=16961

the problematic query `DROP TABLE concur_table_37eclfdgtw` comes from `testReadMetadataWithRelationsConcurrentModifications`
that test schedules queries in threads, but also waits for completion of all these threads.
this test didn't fail, so should wait for all threads to complete

however, the test method is overridden for SQL Server, calling super and expectin a failure. 
therefore the `testReadMetadataWithRelationsConcurrentModifications` doesn't fail, but threads can be left behind running
