### ISSUE TITLE
Failed to load Hadoop native library when running a test case against all derived classes in IntelliJ

### ISSUE THREAD

**Issue by krvikash** [trinodb/trino#15506]
Running a test case in IntelliJ against all derived classes at once fails with the below error. I tried running `io.trino.plugin.hive.BaseHiveConnectorTest#testDelete`.

However, a test case against one derived class works fine.

```

java.lang.ExceptionInInitializerError
	at io.trino.plugin.hive.metastore.file.FileHiveMetastore.createTestingFileHiveMetastore(FileHiveMetastore.java:176)
	at io.trino.plugin.hive.HiveQueryRunner$Builder.lambda$new$0(HiveQueryRunner.java:105)
	at io.trino.plugin.hive.HiveQueryRunner$Builder.build(HiveQueryRunner.java:231)
	at io.trino.plugin.hive.BaseHiveConnectorTest.createHiveQueryRunner(BaseHiveConnectorTest.java:215)
	at io.trino.plugin.hive.TestHiveConnectorTest.createQueryRunner(TestHiveConnectorTest.java:26)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.RuntimeException: failed to load Hadoop native library
	at io.trino.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:59)
	at io.trino.hdfs.HdfsEnvironment.<clinit>(HdfsEnvironment.java:36)
	... 30 more
Caused by: java.lang.NoSuchMethodError: 'boolean org.apache.hadoop.util.NativeCodeLoader.buildSupportsZstd()'
	at org.apache.hadoop.io.compress.ZStandardCodec.checkNativeCodeLoaded(ZStandardCodec.java:64)
	at org.apache.hadoop.io.compress.ZStandardCodec.getDecompressorType(ZStandardCodec.java:211)
	at io.trino.hadoop.HadoopNative.loadAllCodecs(HadoopNative.java:72)
	at io.trino.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:53)
	... 31 more


Test ignored.

```

**Comment by findinpath** [comment]
Notice that there are two libraries containing the class `org.apache.hadoop.util.NativeCodeLoader` : 
- io.prestosql.hadoop:hadoop-apache:2.7.7-1 (this library does NOT contain the method `buildSupportsZstd`)
- io.trino.hadoop:hadoop-apache:3.2.0-18 (this library does contain the method `buildSupportsZstd`)

**Comment by findepi** [comment]
> when running a test case against all derived classes in IntelliJ

This works (more or less) only if subclasses are all in one module, which isn't the case for `BaseHiveConnectorTest` subclasses.

IntelliJ offers "run all" a bit over-optimistically, and is sometimes not always to provide a reasonable, working classpath for such execution.
