### ISSUE TITLE
Aggregation on non-table or non-view fail in BigQuery

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#15546]
```sql
bigquery> CREATE MATERIALIZED VIEW test.test_mv AS SELECT * FROM test.test; 
trino> SELECT count(*) FROM bigquery.test.test_mv;
Query 20221228_231242_00030_q2wq2 failed: Unsupported table type: MATERIALIZED_VIEW
io.trino.spi.TrinoException: Unsupported table type: MATERIALIZED_VIEW
	at io.trino.plugin.bigquery.BigQuerySplitManager.createEmptyProjection(BigQuerySplitManager.java:177)
	at io.trino.plugin.bigquery.BigQuerySplitManager.getSplits(BigQuerySplitManager.java:115)
	at io.trino.split.SplitManager.getSplits(SplitManager.java:58)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitScanAndFilter(SplitSourceFactory.java:181)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:155)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:129)
	at io.trino.sql.planner.plan.TableScanNode.accept(TableScanNode.java:222)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitAggregation(SplitSourceFactory.java:284)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitAggregation(SplitSourceFactory.java:129)
	at io.trino.sql.planner.plan.AggregationNode.accept(AggregationNode.java:222)
	at io.trino.sql.planner.SplitSourceFactory.createSplitSources(SplitSourceFactory.java:109)
	at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.createStageScheduler(PipelinedQueryScheduler.java:1025)
	at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.create(PipelinedQueryScheduler.java:909)
	at io.trino.execution.scheduler.PipelinedQueryScheduler.createDistributedStagesScheduler(PipelinedQueryScheduler.java:312)
	at io.trino.execution.scheduler.PipelinedQueryScheduler.start(PipelinedQueryScheduler.java:293)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:423)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20221228_230942_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Below queries works fine:
```sql
SELECT count(value) FROM bigquery.test.test_mv;
SELECT count(*) FROM bigquery.test.test_mv WHERE value = 1;
```

**Comment by ebyhr** [comment]
cc: @wendigo @hashhar @vlad-lyutenko

**Comment by hashhar** [comment]
Easy to fix, today we throw when creating empty projections for unknown table types, we should instead use the `COUNT(*)` trick on all table types. I'll submit a PR since I touched that code already in https://github.com/trinodb/trino/pull/15542

**Comment by ebyhr** [comment]
Reopened. It's not yet fixed in my understanding.

**Comment by ebyhr** [comment]
@hashhar Gentler reminder.
