### ISSUE TITLE
Query fails when masking function uses a column

### ISSUE THREAD

**Issue by guyco33** [trinodb/trino#15583]
Regression bug found on `405`

Access control file:
```
{
    "tables": [
        {
          "catalog": "tpch",
          "schema": "tiny",
          "table": "orders",
          "columns": [
            {
              "name": "comment",
              "mask": "substr(comment,1,3)"
            }
          ],
          "privileges": ["SELECT"],
          "group": ".*"
        }
    ]
}
```

```
SELECT comment FROM tpch.tiny.orders LIMIT 2
```

`405` fails
`trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=PERMISSION_DENIED, message="Access Denied: Cannot select from table tpch.tiny.orders"`

`403`  succeed
```
+-----+
|_col0|
+-----+
|le.  |
|nst  |
+-----+
```

Query succeed on both versions when `"group"` is omitted or when masking function doesn't use a column

**Comment by guyco33** [comment]
Probably relates to https://github.com/trinodb/trino/pull/14008
@Praveen2112 @arkadiuszbalcerek

**Comment by kokosing** [comment]
cc @atanasenko

**Comment by findepi** [comment]
> masking function doesn't use a column

Looks like referencing a column is something every reasonable mask would do, right?
@guyco33 are you saying that file-based masking is completely unusable in 405?

**Comment by guyco33** [comment]
@findepi Yes, especially for implementations that are based on groups

**Comment by guyco33** [comment]
Attaching a stack trace for the error:
```
io.trino.spi.security.AccessDeniedException: Access Denied: Cannot select from table tpch.tiny.orders
	at io.trino.spi.security.AccessDeniedException.denySelectTable(AccessDeniedException.java:333)
	at io.trino.spi.security.AccessDeniedException.denySelectTable(AccessDeniedException.java:328)
	at io.trino.plugin.base.security.FileBasedSystemAccessControl.checkCanSelectFromColumns(FileBasedSystemAccessControl.java:636)
	at io.trino.plugin.base.security.ForwardingSystemAccessControl.checkCanSelectFromColumns(ForwardingSystemAccessControl.java:295)
	at io.trino.security.AccessControlManager.lambda$checkCanSelectFromColumns$96(AccessControlManager.java:1009)
	at io.trino.security.AccessControlManager.systemAuthorizationCheck(AccessControlManager.java:1317)
	at io.trino.security.AccessControlManager.checkCanSelectFromColumns(AccessControlManager.java:1009)
	at io.trino.security.ForwardingAccessControl.checkCanSelectFromColumns(ForwardingAccessControl.java:401)
	at io.trino.sql.analyzer.Analyzer.lambda$analyze$0(Analyzer.java:84)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at io.trino.sql.analyzer.Analyzer.lambda$analyze$1(Analyzer.java:83)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:82)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:267)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:204)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:856)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:143)
	at io.trino.$gen.Trino_405____20230103_172033_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Praveen2112** [comment]
I think the issue is due to user groups skipped when we execute a query with a column masking.

**Comment by Praveen2112** [comment]
When we analyze a `RowFilter` or a `ColumnMask` I guess we need to pass the `Identity` instead of userName. Since `Identity` equality check is now considering all the parameters (groups, roles, etc) - when analyzing it returns two different `Identity` one with groups and one without groups, the latter fails the access checks. Will raise a PR for this
