### ISSUE TITLE
Hudi query fails when timestamp values have precision higher than milliseconds

### ISSUE THREAD

**Issue by elonazoulay** [trinodb/trino#15593]
When hive.timestamp_precision is set to millis and a value with precision > 3 is encountered an error is thrown. Would there be any issue with changing the behavior to round (and have a config for rounding type)?

Or is the behavior that way because if data is written in a precision it should be read in that precision and rounding should be done in queries?

Stack trace:
Caused by: java.lang.IllegalArgumentException: Expected 0s for digits beyond precision 3: epochMicros = 1668741027571747
	at io.trino.spi.type.SqlTimestamp.newInstance(SqlTimestamp.java:54)
	at io.trino.spi.type.ShortTimestampType.getObjectValue(ShortTimestampType.java:125)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.getRowValues(QueryResultRows.java:332)
	... 44 more

Workaround was to set the session to use timestamp micros but we cannot do this globally w config until all tables and views are updated.

**Comment by findepi** [comment]
> When hive.timestamp_precision is set to millis and a value with precision > 3 is encountered an error is thrown. Would there be any issue with changing the behavior to round (and have a config for rounding type)?

That's the design behavior. See `io.trino.tests.product.hive.TestHiveStorageFormats#testTimestampCreatedFromHive`
cc @aalbu @findinpath @jirassimok 


@elonazoulay what are the steps to reproduce?

**Comment by findepi** [comment]
@elonazoulay do you have a full stacktrace?

**Comment by elonazoulay** [comment]
Hey, happy new year! 
Thanks for confirming, makes sense: if data is written with > millis precision then it should throw an error instead of silently rounding. lmk if it would be desirable to have a config so users can choose.

Steps to reproduce: write data with micro precision and select with either the `hive.timestamp-precision` config or `timestamp_precision` session  property set to `MILLISECONDS`.

The full stack trace:
```Query SUPER_SECRET_QUERY_ID failed: Could not serialize column 'SUPER_SECRET_COLUMN_NAME' of type 'timestamp(3)' at position 1:2
io.trino.spi.TrinoException: Could not serialize column 'last_updated_at' of type 'timestamp(3)' at position 1:2
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.lambda$propagateException$1(QueryResultRows.java:419)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.propagateException(QueryResultRows.java:419)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.getRowValues(QueryResultRows.java:339)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.computeNext(QueryResultRows.java:311)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.computeNext(QueryResultRows.java:273)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serializeContents(IterableSerializer.java:83)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:74)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:12)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1518)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1007)
	at io.airlift.jaxrs.JsonMapper.write(JsonMapper.java:108)
	at io.airlift.jaxrs.AbstractJacksonMapper.writeTo(AbstractJacksonMapper.java:157)
	at io.airlift.jaxrs.JsonMapper.writeTo(JsonMapper.java:44)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:662)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:884)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:916)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872)
	at io.airlift.jaxrs.AsyncResponseHandler$1.onSuccess(AsyncResponseHandler.java:100)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Expected 0s for digits beyond precision 3: epochMicros = 1668741027571747
	at io.trino.spi.type.SqlTimestamp.newInstance(SqlTimestamp.java:54)
	at io.trino.spi.type.ShortTimestampType.getObjectValue(ShortTimestampType.java:125)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.getRowValues(QueryResultRows.java:332)
	... 44 more
```

**Comment by findepi** [comment]
> : if data is written with > millis precision then it should throw an error instead of silently rounding

that's not how we designed it

among `io.trino.tests.product.hive.TestHiveStorageFormats#TIMESTAMPS_FROM_HIVE` we have test cases with values having higher micro/nano precision and being rounded on read.

> Steps to reproduce: write data with micro precision and select with either the hive.timestamp-precision config or timestamp_precision session property set to MILLISECONDS.

that's exactly what `io.trino.tests.product.hive.TestHiveStorageFormats#testTimestampCreatedFromTrino` does.

can you provide exact steps (SQL queriss) I should run on current master?

**Comment by kmanamcheri** [comment]
@findepi Is my understanding correct that the design behavior is

When `hive.timestamp_precision` is set to MILLIS AND
- If a value is read `1668741027571000` it silently converts and works (since the last digits are 000s)
- If a value is read `1668741027571747` it throws an exception

Is that the intended behavior? If so, then that doesn't sound like its rounding. Rounding would mean that it actually rounds the value to the desired precision (losing any precision if needed).

For example, IMO
`Round(1.2345) to two decimals = 1.23`

Trino says `Round(1.2345) to two decimals` is an error! and it says `Round(1.2300) to two decimals` is the only correct input. That seems wrong.

**Comment by findinpath** [comment]
Related commit & code to this context:

https://github.com/trinodb/trino/commit/16da7770#diff-fe67f7949a720cafcdb39bf6de91e34935aeb43dad4f6ba53e057a6401f20fceR51-R53

**Comment by findepi** [comment]
> hat the design behavior is
> 
> When `hive.timestamp_precision` is set to MILLIS AND
> 
> * If a value is read `1668741027571000` it silently converts and works (since the last digits are 000s)
> * If a value is read `1668741027571747` it throws an exception
> 
> Is that the intended behavior?

no, it's not

**Comment by elonazoulay** [comment]
Update:
This is likely a bug with the hudi reader. 
I tried creating a raw parquet table via the hive connector and and an iceberg table with this data and everything works as expected.

We still use the hudi jar in the classpath as we are still testing out the new native hudi connector.


The paste is pretty large. I can share the paste for the queries on the hudi (via hive connector) table:
```
trino:XXX> set session XXX.timestamp_precision = 'MICROSECONDS';
SET SESSION

 SELECT
                    ->   XXX,
                    ->   last_updated_at,
                    ->   typeof(last_updated_at)
                    ->   --, cast(last_updated_at as varchar)
                    -> FROM
                    ->   XXX
                    -> WHERE
                    ->   day_partition = '2022-11-18'
                    ->   AND feature_name = 'XXX'
                    ->   AND entity_id = 'XXX
                    ->
                    ->   and cast(last_updated_at as timestamp(3)) >= cast('2022-11-18 03:10:27.571' as timestamp(3))
                    ->   and cast(last_updated_at as timestamp(3)) <= cast('2022-11-18 03:10:27.572' as timestamp(3));
              entity_id               |      last_updated_at       |    _col2
--------------------------------------+----------------------------+--------------
 XXX | 2022-11-18 03:10:27.571747 | timestamp(6)
(1 row)

Query XXX, FINISHED, 6 nodes
http://XXX
Splits: 293 total, 293 done (100.00%)
CPU Time: 10.2s total, 8.68M rows/s, 30.7MB/s, 37% active
Per Node: 0.6 parallelism, 4.81M rows/s,   17MB/s
Parallelism: 3.3
Peak Memory: 0B
3.07 [88.7M rows, 313MB] [28.9M rows/s, 102MB/s]

trino:XXX> set session XXX.timestamp_precision = 'MILLISECONDS';
SET SESSION
trino:XXX> SELECT
                    ->   entity_id,
                    ->   last_updated_at,
                    ->   typeof(last_updated_at)
                    ->   --, cast(last_updated_at as varchar)
                    -> FROM
                    ->   XXX
                    -> WHERE
                    ->   day_partition = '2022-11-18'
                    ->   AND feature_name = 'XXX'
                    ->   AND entity_id = 'XXX'
                    ->
                    ->   and cast(last_updated_at as timestamp(3)) >= cast('2022-11-18 03:10:27.571' as timestamp(3))
                    ->   and cast(last_updated_at as timestamp(3)) <= cast('2022-11-18 03:10:27.572' as timestamp(3));

Query XXX, FAILED, 6 nodes
http://XXX
Splits: 293 total, 292 done (99.66%)
CPU Time: 13.9s total, 6.35M rows/s, 21.9MB/s, 35% active
Per Node: 0.6 parallelism, 3.64M rows/s, 12.6MB/s
Parallelism: 3.4
Peak Memory: 226B
4.04 [88.2M rows, 304MB] [21.9M rows/s, 75.4MB/s]

Query XXX failed: Could not serialize column 'last_updated_at' of type 'timestamp(3)' at position 1:2
io.trino.spi.TrinoException: Could not serialize column 'last_updated_at' of type 'timestamp(3)' at position 1:2
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.lambda$propagateException$1(QueryResultRows.java:419)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.propagateException(QueryResultRows.java:419)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.getRowValues(QueryResultRows.java:339)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.computeNext(QueryResultRows.java:311)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.computeNext(QueryResultRows.java:273)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serializeContents(IterableSerializer.java:83)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:74)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:12)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1518)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1007)
	at io.airlift.jaxrs.JsonMapper.write(JsonMapper.java:108)
	at io.airlift.jaxrs.AbstractJacksonMapper.writeTo(AbstractJacksonMapper.java:157)
	at io.airlift.jaxrs.JsonMapper.writeTo(JsonMapper.java:44)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:662)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:884)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:916)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872)
	at io.airlift.jaxrs.AsyncResponseHandler$1.onSuccess(AsyncResponseHandler.java:100)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Expected 0s for digits beyond precision 3: epochMicros = 1668741027571747
	at io.trino.spi.type.SqlTimestamp.newInstance(SqlTimestamp.java:54)
	at io.trino.spi.type.ShortTimestampType.getObjectValue(ShortTimestampType.java:125)
	at io.trino.server.protocol.QueryResultRows$ResultsIterator.getRowValues(QueryResultRows.java:332)
	... 44 more
```

**Comment by kmanamcheri** [comment]
> > hat the design behavior is
> > When `hive.timestamp_precision` is set to MILLIS AND
> > 
> > * If a value is read `1668741027571000` it silently converts and works (since the last digits are 000s)
> > * If a value is read `1668741027571747` it throws an exception
> > 
> > Is that the intended behavior?
> 
> no, it's not

That's what I am seeing at my end. If I understand this code snippet correctly (in [`trino/SqlTimestamp.java`](https://github.com/trinodb/trino/blob/master/core/trino-spi/src/main/java/io/trino/spi/type/SqlTimestamp.java#L49))
```
if (precision <= 3) {
    if (picosOfMilli != 0) {
        throw new IllegalArgumentException(format("Expected picosOfMilli to be 0 for precision %s: %s", precision, picosOfMilli));
    }
    if (round(epochMillis, 3 - precision) != epochMillis) {
        throw new IllegalArgumentException(format("Expected 0s for digits beyond precision %s: epochMicros = %s", precision, epochMillis));
    }
}
```
says that if the last digits are NOT 0, it throws an `IllegalArgumentException`. So if its not the intended behavior, this is a bug, no? @findepi

**Comment by kmanamcheri** [comment]
> This is likely a bug with the hudi reader.

Possibly, or in the way that Hudi reader interacts with the Trino type system.

**Comment by findepi** [comment]
> We still use the hudi jar in the classpath as we are still testing out the new native hudi connector.

Please reopen if you see the problem with the Hudi connector.
(or better: file a new clean issue)
