### ISSUE TITLE
JOIN queries using LIKE fail during analysis since Trino 405

### ISSUE THREAD

**Issue by WangJ1an** [trinodb/trino#15629]
Can't use 'like' syntax on join condition
sql：
```
select * from A join B on  A.a like B.b
```
It is correct in the 384 version, and the following exception occurs in the 405 version
```
java.lang.IllegalArgumentException: no type found for symbol 'b'
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
	at io.trino.sql.planner.TypeProvider.get(TypeProvider.java:54)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitSymbolReference(ExpressionAnalyzer.java:657)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitSymbolReference(ExpressionAnalyzer.java:581)
	at io.trino.sql.tree.SymbolReference.accept(SymbolReference.java:41)
	at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:604)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.getCallArgumentTypes(ExpressionAnalyzer.java:1643)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:1237)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:581)
	at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
	at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:604)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:479)
	at io.trino.sql.planner.ExpressionInterpreter.evaluateConstantExpression(ExpressionInterpreter.java:213)
	at io.trino.sql.planner.DomainTranslator$Visitor.tryVisitLikeFunction(DomainTranslator.java:1068)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitFunctionCall(DomainTranslator.java:1117)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitFunctionCall(DomainTranslator.java:335)
	at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.DomainTranslator.getExtractionResult(DomainTranslator.java:332)
	at io.trino.sql.planner.optimizations.PropertyDerivations$Visitor.visitFilter(PropertyDerivations.java:722)
	at io.trino.sql.planner.optimizations.PropertyDerivations$Visitor.visitFilter(PropertyDerivations.java:171)
	at io.trino.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
	at io.trino.sql.planner.optimizations.PropertyDerivations.deriveProperties(PropertyDerivations.java:145)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.deriveProperties(AddExchanges.java:1366)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.deriveProperties(AddExchanges.java:1360)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.withDerivedProperties(AddExchanges.java:1355)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.rebaseAndDeriveProperties(AddExchanges.java:1331)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.visitFilter(AddExchanges.java:590)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.visitFilter(AddExchanges.java:150)
	at io.trino.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1326)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:190)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:150)
	at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1326)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:237)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:150)
	at io.trino.sql.planner.plan.AggregationNode.accept(AggregationNode.java:222)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1326)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:196)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:150)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.optimizations.AddExchanges.optimize(AddExchanges.java:146)
	at io.trino.sql.planner.optimizations.StatsRecordingPlanOptimizer.optimize(StatsRecordingPlanOptimizer.java:54)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:247)
	at io.trino.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:175)
	at io.trino.sql.analyzer.QueryExplainer.getDistributedPlan(QueryExplainer.java:186)
	at io.trino.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:106)
	at io.trino.sql.rewrite.ExplainRewrite$Visitor.getQueryPlan(ExplainRewrite.java:147)
	at io.trino.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:125)
	at io.trino.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:73)
	at io.trino.sql.tree.Explain.accept(Explain.java:61)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.rewrite.ExplainRewrite.rewrite(ExplainRewrite.java:70)
	at io.trino.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:53)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:76)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:267)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:204)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:856)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:143)
	at io.trino.$gen.Trino_405____20230106_043730_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by hashhar** [comment]
@martint this is from trinodb/trino@6238bdc63065c486e1edeb7e73c552bb3a652773

```
dafe30b6d3c0ac5a9d12103946661bcd3b6b12e6 is the first bad commit
commit dafe30b6d3c0ac5a9d12103946661bcd3b6b12e6
Author: Martin Traverso <mtraverso@gmail.com>
Date:   Thu Sep 1 09:26:00 2022 -0700

    Move desugaring of LIKE to planner

    This is to support the AST/IR split
```

**Comment by hashhar** [comment]
i.e. 405 is the only affected version.
