### ISSUE TITLE
`ALTER TABLE ... EXECUTE OPTIMIZE WHERE ...` fails when partitioning field added after insert statement in iceberg

### ISSUE THREAD

**Issue by krvikash** [trinodb/trino#15697]
Below `ALTER TABLE ... EXECUTE OPTIMIZE WHERE ...` query fails with error `Query 20230112_174453_00008_98hpu failed: Unexpected FilterNode found in plan; probably connector was not able to handle provided WHERE expression`

```sql
create table test_table_1 (a int, b varchar);
insert into test_table_1 values(1, 'A');
alter table test_table_1 SET PROPERTIES partitioning = ARRAY['a'];
insert into test_table_1 values(2, 'B');
alter table test_table_1 EXECUTE OPTIMIZE WHERE a = 2;
```

Stacktrace:
```
java.lang.IllegalStateException: Unexpected FilterNode found in plan; probably connector was not able to handle provided WHERE expression
	at io.trino.sql.planner.sanity.TableExecuteStructureValidator.lambda$validate$1(TableExecuteStructureValidator.java:57)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at io.trino.sql.planner.sanity.TableExecuteStructureValidator.validate(TableExecuteStructureValidator.java:55)
	at io.trino.sql.planner.sanity.PlanSanityChecker.lambda$validateFinalPlan$0(PlanSanityChecker.java:80)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at io.trino.sql.planner.sanity.PlanSanityChecker.validateFinalPlan(PlanSanityChecker.java:80)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:266)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:222)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:217)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:475)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:456)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:397)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_403_601_g1482e02____20230112_174040_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: Current plan:
                Output[columnNames = [rows]]
                │   Layout: [rows:bigint]
                └─ TableCommit[target = iceberg:schemaTableName:default.test_table_1, procedureId:OPTIMIZE, procedureHandle:{IcebergOptimizeHandle{snapshotId=Optional[3569631741906518423], schemaAsJson={"type":"struct","schema-id":0,"fields":[{"id":1,"name":"a","required":false,"type":"int"},{"id":2,"name":"b","required":false,"type":"string"}]}, partitionSpecAsJson={"spec-id":1,"fields":[{"name":"a","transform":"identity","source-id":1,"field-id":1000}]}, tableColumns=[1:a:integer, 2:b:varchar], fileFormat=PARQUET, tableStorageProperties={write.format.default=PARQUET}, maxScannedFileSize=100MB, retriesEnabled=false}}]
                   │   Layout: [rows:bigint]
                   └─ LocalExchange[partitioning = SINGLE]
                      │   Layout: [partialrows:bigint, fragment:varbinary]
                      └─ RemoteExchange[type = GATHER]
                         │   Layout: [partialrows:bigint, fragment:varbinary]
                         └─ TableExecute[]
                            │   Layout: [partialrows:bigint, fragment:varbinary]
                            │   a := a
                            │   b := b
                            └─ LocalExchange[partitioning = iceberg:IcebergPartitioningHandle{partitioning=[a]} (scale writers), arguments = ["a"]]
                               │   Layout: [a:integer, b:varchar]
                               └─ RemoteExchange[type = REPARTITION]
                                  │   Layout: [a:integer, b:varchar]
                                  └─ ScanFilter[table = iceberg:default.test_table_1$data@3569631741906518423, filterPredicate = ("a" = 2)]
                                         Layout: [a:integer, b:varchar]
                                         a := 1:a:integer
                                         b := 2:b:varchar

		at io.trino.sql.planner.sanity.PlanSanityChecker.validateFinalPlan(PlanSanityChecker.java:94)
		... 12 more
```

Whereas below passes
```sql
create table test_table_2 (a int, b varchar);
alter table test_table_2 SET PROPERTIES partitioning = ARRAY['a'];
insert into test_table_2 values(1, 'A');
alter table test_table_2 EXECUTE OPTIMIZE WHERE a = 1;
```

**Comment by tbaeg** [comment]
Apologies for the duplicate issue. 

Any plans for a solution here? I think the easiest one is to add `FilterNode` as part of `TableExecuteStructureValidator`. Happy to work on this as well.

**Comment by tbaeg** [comment]
@krvikash Would #31104 assist with your problem?
