### ISSUE TITLE
Fails to insert into iceberg table after dropping a `void` transform partition column

### ISSUE THREAD

**Issue by krvikash** [trinodb/trino#15738]
Repro SQL:
```sql
CREATE TABLE test (id int, col int) WITH (partitioning = ARRAY['void(col)']);
ALTER TABLE test DROP COLUMN col;
INSERT INTO test values(1);
-- Query 20230116_203114_00002_rt5sw failed: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
```
Stack trace:
```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
	at io.trino.plugin.iceberg.PartitionFields.quotedName(PartitionFields.java:162)
	at io.trino.plugin.iceberg.PartitionFields.fromColumnToIdentifier(PartitionFields.java:157)
	at io.trino.plugin.iceberg.PartitionFields.toPartitionField(PartitionFields.java:128)
	at io.trino.plugin.iceberg.PartitionFields.lambda$toPartitionFields$8(PartitionFields.java:122)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.plugin.iceberg.PartitionFields.toPartitionFields(PartitionFields.java:123)
	at io.trino.plugin.iceberg.IcebergUtil.getIcebergTableProperties(IcebergUtil.java:202)
	at io.trino.plugin.iceberg.IcebergMetadata.getTableMetadata(IcebergMetadata.java:562)
	at io.trino.spi.connector.ConnectorMetadata.getTableSchema(ConnectorMetadata.java:238)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableSchema(ClassLoaderSafeConnectorMetadata.java:247)
	at io.trino.metadata.MetadataManager.getTableSchema(MetadataManager.java:439)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitInsert(StatementAnalyzer.java:540)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitInsert(StatementAnalyzer.java:475)
	at io.trino.sql.tree.Insert.accept(Insert.java:68)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:492)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:454)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:267)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:204)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:856)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:143)
	at io.trino.$gen.Trino_403_638_gdda6432____20230116_202911_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by krvikash** [comment]
The issue is happening even with SELECT and UPDATE

```sql
select * from test;
-- java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
update test set id = 2;
-- java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
```
