### ISSUE TITLE
DROP TABLE IF EXISTS fails with hive metastore on 405 if table doesn't exist

### ISSUE THREAD

**Issue by brokenjacobs** [trinodb/trino#15789]
I'm guessing this might be related to: https://github.com/trinodb/trino/pull/13974

But in the most recent trino release we run queries like:
DROP TABLE IF EXISTS hive.pipeline_prod6.tablename

And if the table does not exist in the metastore we get a query failure:
Error Type | EXTERNAL
Error Code | HIVE_METASTORE_ERROR (16777216)
```
io.trino.spi.TrinoException: The following metastore delete operations failed: drop table pipeline_prod6.tablename
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeIrreversibleMetastoreOperations(SemiTransactionalHiveMetastore.java:2464)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:1679)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1355)
	at io.trino.plugin.hive.HiveMetadata.commit(HiveMetadata.java:3739)
	at io.trino.plugin.hive.HiveTransactionManager.lambda$commit$0(HiveTransactionManager.java:59)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.plugin.hive.HiveTransactionManager.commit(HiveTransactionManager.java:57)
	at io.trino.plugin.hive.HiveConnector.commit(HiveConnector.java:216)
	at io.trino.metadata.CatalogTransaction.commit(CatalogTransaction.java:78)
	at io.trino.metadata.CatalogMetadata.commit(CatalogMetadata.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at io.trino.$gen.Trino_405____20230117_163801_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: io.trino.spi.connector.TableNotFoundException: Table 'pipeline_prod6.irga_dsny_2022_12_09' not found
		at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.dropTable(ThriftHiveMetastore.java:985)
		at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.dropTable(BridgingHiveMetastore.java:207)
		at io.trino.plugin.hive.metastore.ForwardingHiveMetastore.dropTable(ForwardingHiveMetastore.java:162)
		at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.dropTable(CachingHiveMetastore.java:490)
		at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.dropTable(CachingHiveMetastore.java:490)
		at io.trino.plugin.hive.HiveMetastoreClosure.dropTable(HiveMetastoreClosure.java:170)
		at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.lambda$prepareDropTable$0(SemiTransactionalHiveMetastore.java:1742)
		at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$IrreversibleMetastoreOperation.run(SemiTransactionalHiveMetastore.java:3428)
		at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.lambda$executeIrreversibleMetastoreOperations$25(SemiTransactionalHiveMetastore.java:2439)
		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
		at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
		... 3 more
```

**Comment by ebyhr** [comment]
@brokenjacobs When the statement contains `IF EXISTS` and the table doesn't exist, `ThriftHiveMetastore.dropTable` shouldn't be called. Did you really specify `IF EXISTS` option? Can you share your Hive config properties?

**Comment by brokenjacobs** [comment]
Yes if exists is specified on the query. I’ll get the hive config properties.

**Comment by brokenjacobs** [comment]
```connector.name=hive
hive.metastore.uri=thrift://metastore.hive.svc:9083
hive.security=file
hive.orc.time-zone=Etc/UTC
hive.parquet.time-zone=Etc/UTC
# hive.file-status-cache-tables=l0files.*
hive.temporary-staging-directory-enabled=false
# hive.metastore-timeout=30s
# These are the values amazon EMR uses
hive.metastore-cache-ttl=20m
hive.metastore-refresh-interval=1m
security.config-file=/etc/trino/catalog/hive-rules.json
hive.metastore.thrift.delete-files-on-drop=true
# Sets the default table property for auto-purge, is overrideable
hive.auto-purge=true
```

**Comment by ebyhr** [comment]
Could you make sure if the table really didn't exist? My assumption is:
1. `ThriftHiveMetastore.dropTable` was called because the table exists
2. Exception happened in `deleteDirRecursive` method and retry happened
3. `TableNotFoundException` was thrown because the table was already dropped from the metastore in step 2

**Comment by brokenjacobs** [comment]
Looks like this may be an issue with DROP statements not completing properly when the cluster is busy. Investigating more today.

**Comment by findinpath** [comment]
Another user from the community stumbled on this one:

https://trinodb.slack.com/archives/CJ6UC075E/p1676485146907409

As @ebyhr  suggested, while performing the deletion on the s3 filesystem, there was a permission denied issue which caused the operation to fail in the following retry because the table didn't exist anymore.

**Comment by findepi** [comment]
this was due to configuration issue, but drop and retries may fail in other cases (legitimate retries).
i filed https://github.com/trinodb/trino/issues/18848 for that case. closing this issue
