### ISSUE TITLE
Flaky TestBigQueryCaseInsensitiveMapping.testNonLowerCaseTableName

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#15801]
```
2023-01-20T11:25:43.418-0600	INFO	main	io.trino.testng.services.ManageTestResources	ManageTestResources.onFinish: running checks
Error:  Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 137.406 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.bigquery.TestBigQueryCaseInsensitiveMapping.testNonLowerCaseTableName  Time elapsed: 18.613 s  <<< FAILURE!
io.trino.testing.QueryFailedException: Expected schema name from internal metadata to be lowercase: SomeSchema_6mgcsu6rky
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:490)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:375)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:370)
	at io.trino.plugin.bigquery.TestBigQueryCaseInsensitiveMapping.testNonLowerCaseTableName(TestBigQueryCaseInsensitiveMapping.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: SQL: INSERT INTO someschema_6mgcsu6rky.nonlowercasetable (lower_case_name) VALUES ('l')
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:493)
		... 17 more
Caused by: com.google.common.base.VerifyException: Expected schema name from internal metadata to be lowercase: SomeSchema_6mgcsu6rky
	at com.google.common.base.Verify.verify(Verify.java:183)
	at io.trino.plugin.bigquery.BigQueryClient.toRemoteDataset(BigQueryClient.java:105)
	at io.trino.plugin.bigquery.BigQueryMetadata.schemaExists(BigQueryMetadata.java:170)
	at io.trino.plugin.bigquery.BigQueryMetadata.beginInsert(BigQueryMetadata.java:541)
	at io.trino.metadata.MetadataManager.beginInsert(MetadataManager.java:894)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:300)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:218)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:109)
	at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:81)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:72)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:72)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:37)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:21)
	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:31)
	at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:94)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:247)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:222)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:217)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:475)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:456)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:397)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20230120_172335_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: Current plan:
                Output[columnNames = [rows]]
                │   Layout: [rows:bigint]
                └─ TableCommit[target = bigquery:BigQueryTableHandle{relationHandle=BigQueryNamedRelationHandle{remoteTableName=sep-bq-cicd-case-insensitive.SomeSchema_6mgcsu6rky.NonLowerCaseTable, schemaTableName=someschema_6mgcsu6rky.nonlowercasetable, type=TABLE, comment=Optional.empty}, constraint=ALL, projectedColumns=Optional[[BigQueryColumnHandle{name=lower_case_name, trinoType=varchar, bigqueryType=STRING, mode=NULLABLE, precision=null, scale=null, subColumns=[], description=null}, BigQueryColumnHandle{name=Mixed_Case_Name, trinoType=varchar, bigqueryType=STRING, mode=NULLABLE, precision=null, scale=null, subColumns=[], description=null}, BigQueryColumnHandle{name=UPPER_CASE_NAME, trinoType=varchar, bigqueryType=STRING, mode=NULLABLE, precision=null, scale=null, subColumns=[], description=null}]]}]
                   │   Layout: [rows:bigint]
                   └─ LocalExchange[partitioning = SINGLE]
                      │   Layout: [partialrows:bigint, fragment:varbinary]
                      └─ RemoteExchange[type = GATHER]
                         │   Layout: [partialrows:bigint, fragment:varbinary]
                         └─ TableWriter[]
                            │   Layout: [partialrows:bigint, fragment:varbinary]
                            │   lower_case_name := field
                            │   mixed_case_name := mixed_case_name
                            │   upper_case_name := mixed_case_name
                            └─ RemoteExchange[type = REPARTITION]
                               │   Layout: [field:varchar(1), mixed_case_name:varchar]
                               └─ Values[]
                                      Layout: [field:varchar(1), mixed_case_name:varchar]
                                      ('l', CAST(null AS varchar))

		at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:100)
		... 12 more

```

**Comment by ebyhr** [comment]
I suppose the cause is the schema having uppercase characters was created in #15761 unintentionally. I deleted the problematic schema manually though `TestBigQueryInstanceCleaner` will eventually delete it.
