### ISSUE TITLE
Flaky failure recovery tests TestMySqlTaskFailureRecoveryTest TestIcebergTaskFailureRecoveryTest testParallel

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#15809]
https://github.com/trinodb/trino/actions/runs/3948992707/jobs/6760527498

```
Error:  Tests run: 24, Failures: 2, Errors: 0, Skipped: 11, Time elapsed: 458.073 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.mysql.TestMySqlTaskFailureRecoveryTest.testParallel[testUpdateWithSubquery](2)  Time elapsed: 4.162 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting throwable message:
  <"Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://127.0.0.1:44923/v1/task/20230118_145705_00017_q5n4n.2.0.0/results/0/0 - 3 failures, failure duration 10.06s, total failed request time 15.06s)">
to contain:
  <"This connector does not support modifying table rows">
but did not.

Throwable that failed the check:

	at io.trino.testing.BaseFailureRecoveryTest.testUpdateWithSubquery(BaseFailureRecoveryTest.java:246)
	at io.trino.plugin.jdbc.BaseJdbcFailureRecoveryTest.lambda$testUpdateWithSubquery$4(BaseJdbcFailureRecoveryTest.java:80)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:877)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1306)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1178)
	at io.trino.plugin.jdbc.BaseJdbcFailureRecoveryTest.testUpdateWithSubquery(BaseJdbcFailureRecoveryTest.java:80)
	at io.trino.testing.BaseFailureRecoveryTest$ParallelTestRunnable.run(BaseFailureRecoveryTest.java:807)
	at io.trino.testing.BaseFailureRecoveryTest.testParallel(BaseFailureRecoveryTest.java:201)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE table_eb5byqjw59 AS SELECT * FROM orders
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:493)
		... 35 more
Caused by: io.trino.operator.PageTransportTimeoutException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://127.0.0.1:44923/v1/task/20230118_145705_00017_q5n4n.2.0.0/results/0/0 - 3 failures, failure duration 10.06s, total failed request time 15.06s)
	at io.trino.operator.HttpPageBufferClient$1.onFailure(HttpPageBufferClient.java:494)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Idle timeout 5000 ms
	at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:25)
	at io.trino.operator.HttpPageBufferClient$PageResponseHandler.handleException(HttpPageBufferClient.java:653)
	at io.trino.operator.HttpPageBufferClient$PageResponseHandler.handleException(HttpPageBufferClient.java:640)
	at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:120)
	at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:85)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461)
	at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:557)
	at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:152)
	at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:145)
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:264)
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:164)
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:821)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.abort(HttpConnectionOverHTTP.java:214)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:200)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onIdleExpired(HttpConnectionOverHTTP.java:160)
	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:402)
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	... 3 more
Caused by: java.util.concurrent.TimeoutException: Idle timeout 5000 ms
	... 10 more

[INFO] 
Error:  Tests run: 24, Failures: 2, Errors: 0, Skipped: 11
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:45 min
[INFO] Finished at: 2023-01-18T15:03:30Z
```

cc @mwd410 @arhimondr @losipiuk @linzebing

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/4051473831/jobs/6970310150

**Comment by findepi** [comment]
Similar for `TestIcebergTaskFailureRecoveryTest` https://github.com/trinodb/trino/actions/runs/4055689915/jobs/6985044303

```
2023-02-01T00:35:17.1653991Z [ERROR]   TestIcebergTaskFailureRecoveryTest>BaseFailureRecoveryTest.testParallel:200->BaseFailureRecoveryTest.testExplainAnalyze:287->BaseFailureRecoveryTest.testSelect:125->BaseFailureRecoveryTest.testSelect:130->BaseFailureRecoveryTest.testSelect:139->BaseFailureRecoveryTest.lambda$testSelect$1:139 
2023-02-01T00:35:17.1655378Z Expecting message:
2023-02-01T00:35:17.1656403Z   <"Could not communicate with the remote task. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (127.0.0.1:45039)">
2023-02-01T00:35:17.1656923Z to be found for regex:
2023-02-01T00:35:17.1657311Z   <"Error 500 Internal Server Error|Error closing remote buffer, expected 204 got 500">
2023-02-01T00:35:17.1657658Z but did not.
2023-02-01T00:35:17.1657804Z 
2023-02-01T00:35:17.1657941Z Throwable that failed the check:
2023-02-01T00:35:17.1658114Z 
2023-02-01T00:35:17.1658604Z io.trino.testing.QueryFailedException: Could not communicate with the remote task. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (127.0.0.1:45039)
2023-02-01T00:35:17.1659389Z 	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
2023-02-01T00:35:17.1660058Z 	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:505)
2023-02-01T00:35:17.1660748Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.execute(BaseFailureRecoveryTest.java:488)
2023-02-01T00:35:17.1661442Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.executeActual(BaseFailureRecoveryTest.java:474)
2023-02-01T00:35:17.1662204Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.executeActualNoRetries(BaseFailureRecoveryTest.java:459)
2023-02-01T00:35:17.1662972Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.lambda$failsWithoutRetries$11(BaseFailureRecoveryTest.java:633)
2023-02-01T00:35:17.1663632Z 	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
2023-02-01T00:35:17.1664278Z 	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:877)
2023-02-01T00:35:17.1664887Z 	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1306)
2023-02-01T00:35:17.1665738Z 	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1178)
2023-02-01T00:35:17.1666462Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.failsWithoutRetries(BaseFailureRecoveryTest.java:633)
2023-02-01T00:35:17.1667157Z 	at io.trino.testing.BaseFailureRecoveryTest.testSelect(BaseFailureRecoveryTest.java:139)
2023-02-01T00:35:17.1668187Z 	at io.trino.testing.BaseFailureRecoveryTest.testSelect(BaseFailureRecoveryTest.java:130)
2023-02-01T00:35:17.1668807Z 	at io.trino.testing.BaseFailureRecoveryTest.testSelect(BaseFailureRecoveryTest.java:125)
2023-02-01T00:35:17.1669476Z 	at io.trino.testing.BaseFailureRecoveryTest.testExplainAnalyze(BaseFailureRecoveryTest.java:287)
2023-02-01T00:35:17.1670158Z 	at io.trino.testing.BaseFailureRecoveryTest$ParallelTestRunnable.run(BaseFailureRecoveryTest.java:806)
2023-02-01T00:35:17.1670815Z 	at io.trino.testing.BaseFailureRecoveryTest.testParallel(BaseFailureRecoveryTest.java:200)
2023-02-01T00:35:17.1671416Z 	at jdk.internal.reflect.GeneratedMethodAccessor905.invoke(Unknown Source)
2023-02-01T00:35:17.1672079Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-02-01T00:35:17.1672647Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-02-01T00:35:17.1673352Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2023-02-01T00:35:17.1673934Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2023-02-01T00:35:17.1674412Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2023-02-01T00:35:17.1675097Z 	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
2023-02-01T00:35:17.1675942Z 	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
2023-02-01T00:35:17.1676577Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-01T00:35:17.1677088Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2023-02-01T00:35:17.1677590Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-01T00:35:17.1678147Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-02-01T00:35:17.1678759Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-02-01T00:35:17.1679232Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-02-01T00:35:17.1679893Z Caused by: io.trino.spi.TrinoException: Could not communicate with the remote task. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (127.0.0.1:45039)
2023-02-01T00:35:17.1680740Z 	at io.trino.server.remotetask.ContinuousTaskStatusFetcher.updateTaskStatus(ContinuousTaskStatusFetcher.java:242)
2023-02-01T00:35:17.1681405Z 	at io.trino.server.remotetask.HttpRemoteTask.fail(HttpRemoteTask.java:932)
2023-02-01T00:35:17.1682004Z 	at io.trino.server.remotetask.HttpRemoteTask$UpdateResponseHandler.fatal(HttpRemoteTask.java:1065)
2023-02-01T00:35:17.1682692Z 	at io.trino.server.remotetask.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:72)
2023-02-01T00:35:17.1683429Z 	at io.trino.server.remotetask.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:27)
2023-02-01T00:35:17.1684064Z 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
2023-02-01T00:35:17.1684623Z 	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
2023-02-01T00:35:17.1685218Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-02-01T00:35:17.1685815Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-02-01T00:35:17.1686284Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-02-01T00:35:17.1686491Z 
2023-02-01T00:35:17.1686579Z [INFO] 
2023-02-01T00:35:17.1686943Z [ERROR] Tests run: 32, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by findepi** [comment]
cc @arhimondr @losipiuk @linzebing @mwd410

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4054199820/jobs/6978789414 

```
Error:    TestMySqlTaskFailureRecoveryTest>BaseFailureRecoveryTest.testParallel:200->BaseFailureRecoveryTest.testExplainAnalyze:287->BaseFailureRecoveryTest.testSelect:125->BaseFailureRecoveryTest.testSelect:130->BaseFailureRecoveryTest.testSelect:139->BaseFailureRecoveryTest.lambda$testSelect$1:139 
Expecting message:
  <"Could not communicate with the remote task. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (127.0.0.1:46257)">
to be found for regex:
  <"Error 500 Internal Server Error|Error closing remote buffer, expected 204 got 500">
but did not.

Throwable that failed the check:

io.trino.testing.QueryFailedException: Could not communicate with the remote task. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (127.0.0.1:46257)
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:505)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.execute(BaseFailureRecoveryTest.java:488)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.executeActual(BaseFailureRecoveryTest.java:474)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.executeActualNoRetries(BaseFailureRecoveryTest.java:459)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.lambda$failsWithoutRetries$11(BaseFailureRecoveryTest.java:633)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:877)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1306)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1178)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.failsWithoutRetries(BaseFailureRecoveryTest.java:633)
	at io.trino.testing.BaseFailureRecoveryTest.testSelect(BaseFailureRecoveryTest.java:139)
	at io.trino.testing.BaseFailureRecoveryTest.testSelect(BaseFailureRecoveryTest.java:130)
	at io.trino.testing.BaseFailureRecoveryTest.testSelect(BaseFailureRecoveryTest.java:125)
	at io.trino.testing.BaseFailureRecoveryTest.testExplainAnalyze(BaseFailureRecoveryTest.java:287)
	at io.trino.testing.BaseFailureRecoveryTest$ParallelTestRunnable.run(BaseFailureRecoveryTest.java:806)
	at io.trino.testing.BaseFailureRecoveryTest.testParallel(BaseFailureRecoveryTest.java:200)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.trino.spi.TrinoException: Could not communicate with the remote task. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (127.0.0.1:46257)
	at io.trino.server.remotetask.ContinuousTaskStatusFetcher.updateTaskStatus(ContinuousTaskStatusFetcher.java:242)
	at io.trino.server.remotetask.HttpRemoteTask.fail(HttpRemoteTask.java:932)
	at io.trino.server.remotetask.HttpRemoteTask$UpdateResponseHandler.fatal(HttpRemoteTask.java:1065)
	at io.trino.server.remotetask.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:72)
	at io.trino.server.remotetask.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:27)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 
Error:  Tests run: 24, Failures: 1, Errors: 0, Skipped: 12
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4068806771/jobs/7009769847 

```
Error:    TestMySqlTaskFailureRecoveryTest>BaseFailureRecoveryTest.testParallel:200->BaseJdbcFailureRecoveryTest.testUpdate:73 
Expecting throwable message:
  <"Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (getting task status http://127.0.0.1:41425/v1/task/20230202_013253_00016_rba4k.1.0.0 - 3 failures, failure duration 11.28s, total failed request time 15.51s)">
to contain:
  <"This connector does not support modifying table rows">
but did not.

Throwable that failed the check:

io.trino.testing.QueryFailedException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (getting task status http://127.0.0.1:41425/v1/task/20230202_013253_00016_rba4k.1.0.0 - 3 failures, failure duration 11.28s, total failed request time 15.51s)
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:490)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.lambda$execute$2(BaseFailureRecoveryTest.java:483)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.execute(BaseFailureRecoveryTest.java:483)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.executeExpected(BaseFailureRecoveryTest.java:449)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.lambda$failsWithoutRetries$10(BaseFailureRecoveryTest.java:632)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.getFailureStageId(BaseFailureRecoveryTest.java:656)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.failsWithoutRetries(BaseFailureRecoveryTest.java:632)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.failsAlways(BaseFailureRecoveryTest.java:624)
	at io.trino.testing.BaseFailureRecoveryTest.testNonSelect(BaseFailureRecoveryTest.java:337)
	at io.trino.testing.BaseFailureRecoveryTest.testTableModification(BaseFailureRecoveryTest.java:316)
	at io.trino.testing.BaseFailureRecoveryTest.testTableModification(BaseFailureRecoveryTest.java:311)
	at io.trino.testing.BaseFailureRecoveryTest.testUpdate(BaseFailureRecoveryTest.java:237)
	at io.trino.plugin.jdbc.BaseJdbcFailureRecoveryTest.lambda$testUpdate$3(BaseJdbcFailureRecoveryTest.java:73)
		at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:553)
		at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:149)
		at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:142)
		at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:273)
		at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:159)
		at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:865)
		at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.abort(HttpConnectionOverHTTP.java:251)
		at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:237)
		at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onIdleExpired(HttpConnectionOverHTTP.java:181)
		at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:407)
		at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:170)
		at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:112)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		... 3 more
	Caused by: java.util.concurrent.TimeoutException: Idle timeout 5000 ms
		... 10 more

[INFO] 
Error:  Tests run: 24, Failures: 15, Errors: 0, Skipped: 3
```

**Comment by findepi** [comment]
thank you @losipiuk !

**Comment by losipiuk** [comment]
> thank you @losipiuk !

Please don't. I hope it will help. But I do not know really.

**Comment by findepi** [comment]
Thank you for spending time to work on this, analyze and put up a PR that (hopefully) helps.
