### ISSUE TITLE
Allow dropping a specific field in nested field in iceberg connector

### ISSUE THREAD

**Issue by krvikash** [trinodb/trino#15975]
Currently, we don’t allow dropping a specific field in the nested field. However, Dropping the parent field is allowed.

```
trino> create table iceberg.vikash_test_3.test (id INTEGER, parent ROW(child1 INTEGER, child2 INTEGER));
CREATE TABLE

trino> ALTER TABLE iceberg.vikash_test_3.test DROP COLUMN parent.child1;
Query 20230204_054125_00019_wsixk failed: not yet implemented

trino> ALTER TABLE iceberg.vikash_test_3.test DROP COLUMN parent;
DROP COLUMN
```

Stack trace:

```
java.lang.UnsupportedOperationException: not yet implemented
	at io.trino.sql.parser.AstBuilder.aggregateResult(AstBuilder.java:3345)
	at io.trino.sql.parser.AstBuilder.aggregateResult(AstBuilder.java:312)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:47)
	at io.trino.sql.parser.SqlBaseBaseVisitor.visitQualifiedName(SqlBaseBaseVisitor.java:1918)
	at io.trino.sql.parser.SqlBaseParser$QualifiedNameContext.accept(SqlBaseParser.java:19284)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.trino.sql.parser.AstBuilder.visitDropColumn(AstBuilder.java:734)
	at io.trino.sql.parser.AstBuilder.visitDropColumn(AstBuilder.java:312)
	at io.trino.sql.parser.SqlBaseParser$DropColumnContext.accept(SqlBaseParser.java:810)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.trino.sql.parser.AstBuilder.visitSingleStatement(AstBuilder.java:326)
	at io.trino.sql.parser.AstBuilder.visitSingleStatement(AstBuilder.java:312)
	at io.trino.sql.parser.SqlBaseParser$SingleStatementContext.accept(SqlBaseParser.java:309)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.trino.sql.parser.SqlParser.invokeParser(SqlParser.java:153)
	at io.trino.sql.parser.SqlParser.createStatement(SqlParser.java:84)
	at io.trino.execution.QueryPreparer.prepareQuery(QueryPreparer.java:55)
	at io.trino.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:179)
	at io.trino.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:148)
	at io.trino.$gen.Trino_testversion____20230204_053116_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by krvikash** [comment]
Spark allows the same https://iceberg.apache.org/docs/latest/spark-ddl/#alter-table--drop-column
