### ISSUE TITLE
trino-server-rpm-406.rpm failed to restart

### ISSUE THREAD

**Issue by wffger** [trinodb/trino#15980]
I install trino-server-rpm-406.rpm.
When I restart service, /var/log/trino/server.log shows as below
```
2023-02-06T10:52:45.951+0800	ERROR	main	io.trino.server.Server	Configuration errors:

1) Error: Invalid configuration property trino-logs.http-request-log.location: file does not exist: var/log/http-request.log (for class LocalFileConfig.httpRequestLogLocation)

1 error

======================
Full classname legend:
======================
LocalFileConfig: "io.trino.plugin.localfile.LocalFileConfig"
========================
End of classname legend:
========================

io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Invalid configuration property trino-logs.http-request-log.location: file does not exist: var/log/http-request.log (for class LocalFileConfig.httpRequestLogLocation)

1 error

======================
Full classname legend:
======================
LocalFileConfig: "io.trino.plugin.localfile.LocalFileConfig"
========================
End of classname legend:
========================

	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:234)
	at io.trino.plugin.localfile.LocalFileConnectorFactory.create(LocalFileConnectorFactory.java:50)
	at io.trino.connector.DefaultCatalogFactory.createConnector(DefaultCatalogFactory.java:203)
	at io.trino.connector.DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:124)
	at io.trino.connector.LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:45)
	at io.trino.connector.StaticCatalogManager.lambda$loadInitialCatalogs$1(StaticCatalogManager.java:150)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at java.base/java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:184)
	at io.trino.util.Executors.executeUntilFailure(Executors.java:41)
	at io.trino.connector.StaticCatalogManager.loadInitialCatalogs(StaticCatalogManager.java:144)
	at io.trino.server.Server.doStart(Server.java:139)
	at io.trino.server.Server.lambda$start$0(Server.java:88)
	at io.trino.$gen.Trino_406____20230206_025236_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:88)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)


2023-02-06T10:52:45.952+0800	INFO	Thread-33	io.airlift.bootstrap.LifeCycleManager	JVM is shutting down, cleaning up
```

It seems that the program does not read configuration from /etc/trino/*properties.

**Comment by wffger** [comment]
I find the root cause. Connector properties were wrong.
I add `trino-logs.http-request-log.location=/var/log/trino/http-request.log` to /etc/trino/catalog/localfile.properties.
Then it fixed.
