### ISSUE TITLE
TestHivePartitionSchemaEvolution.testParquet fails during REPLACE COLUMNS

### ISSUE THREAD

**Issue by MiguelWeezardo** [trinodb/trino#16042]
A test failure reported in https://github.com/trinodb/trino/pull/15797#issuecomment-1424015121:
```
tests               | 2023-02-08 22:30:08 WARNING: Unable to execute: ALTER TABLE schema_evolution_rhiw4er6vu REPLACE COLUMNS (float_column float, varchar_column varchar(20)), due: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Replacing columns cannot drop columns for table default.schema_evolution_rhiw4er6vu. SerDe may be incompatible
tests               | 2023-02-08 22:30:08 WARNING: Unable to execute: ALTER TABLE schema_evolution_rhiw4er6vu REPLACE COLUMNS (int_column int, varchar_column varchar(20)), due: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Replacing columns cannot drop columns for table default.schema_evolution_rhiw4er6vu. SerDe may be incompatible
tests               | 2023-02-08 22:30:08 WARNING: Unable to execute: ALTER TABLE schema_evolution_rhiw4er6vu REPLACE COLUMNS (int_column int, float_column float), due: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Replacing columns cannot drop columns for table default.schema_evolution_rhiw4er6vu. SerDe may be incompatible
tests               | 2023-02-08 22:30:08 WARNING: Unable to execute: ALTER TABLE schema_evolution_rhiw4er6vu REPLACE COLUMNS (tiny_column tinyint, int_column int, float_column float, varchar_column varchar(20)), due: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Unable to alter table. The following columns have types incompatible with the existing columns in their respective positions :
tests               | tiny_column,int_column,float_column
tests               | 2023-02-08 22:30:08 WARNING: Unable to execute: ALTER TABLE schema_evolution_rhiw4er6vu REPLACE COLUMNS (int_column int, tiny_column tinyint, float_column float, varchar_column varchar(20)), due: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Unable to alter table. The following columns have types incompatible with the existing columns in their respective positions :
tests               | tiny_column,float_column
presto-master       | 2023-02-08T22:30:08.957+0545	INFO	dispatcher-query-25	io.trino.event.QueryMonitor	TIMELINE: Query 20230208_164508_02152_j74bh :: FINISHED :: elapsed 87ms :: planning 47ms :: waiting 10ms :: scheduling 20ms :: running 17ms :: finishing 3ms :: begin 2023-02-08T22:30:08.869+05:45 :: end 2023-02-08T22:30:08.956+05:45
tests               | 2023-02-08 22:30:11 INFO: not retrying; @Flaky annotation not present
tests               | 2023-02-08 22:30:11 INFO: FAILURE     /    io.trino.tests.product.hive.TestHivePartitionSchemaEvolution.testParquet (Groups: ) took 4.0 seconds
tests               | 2023-02-08 22:30:11 SEVERE: Failure cause:
tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.hive.TestHivePartitionSchemaEvolution.tryExecuteOnHive(TestHivePartitionSchemaEvolution.java:119)
tests               | 	at io.trino.tests.product.hive.TestHivePartitionSchemaEvolution.testEvolution(TestHivePartitionSchemaEvolution.java:110)
tests               | 	at io.trino.tests.product.hive.TestHivePartitionSchemaEvolution.test(TestHivePartitionSchemaEvolution.java:92)
tests               | 	at io.trino.tests.product.hive.TestHivePartitionSchemaEvolution.testParquet(TestHivePartitionSchemaEvolution.java:58)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
tests               | Caused by: java.sql.SQLException
tests               | 	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:275)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 	... 18 more
tests               | 	Suppressed: java.lang.Exception: Query: ALTER TABLE schema_evolution_rhiw4er6vu REPLACE COLUMNS (int_column int, tiny_column tinyint, varchar_column varchar(20))
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
tests               | 		... 19 more
```

**Comment by MiguelWeezardo** [comment]
cc: @kokosing
