### ISSUE TITLE
Prepared statement fails when using PARTITION and DATE_TRUNC

### ISSUE THREAD

**Issue by lpoulain** [trinodb/trino#16156]
Running the following query issues an error: `PARTITION BY expression 'DATE_TRUNC(?, orderdate)' must be an aggregate expression or appear in GROUP BY clause`:

```
PREPARE statement1 FROM
SELECT DATE_TRUNC(?, orderdate), SUM(COUNT(DISTINCT custkey)) OVER (PARTITION BY DATE_TRUNC(?, orderdate)) FROM "tpch"."sf1"."orders"
GROUP BY 1;

EXECUTE statement1 USING 'week', 'week';
```

The same query without a prepared statement works fine:

```
SELECT SUM(COUNT(DISTINCT id)) OVER (PARTITION BY DATE_TRUNC('week', "date")) FROM "sample"."demo"."missions"
GROUP BY DATE_TRUNC('week', "date");
```

Here is the stack trace:

```
io.trino.spi.TrinoException: line 3:51: PARTITION BY expression 'DATE_TRUNC(?, orderdate)' must be an aggregate expression or appear in GROUP BY clause
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.sql.analyzer.AggregationAnalyzer$Visitor.visitWindowSpecification(AggregationAnalyzer.java:487)
	at io.trino.sql.analyzer.AggregationAnalyzer$Visitor.visitWindowSpecification(AggregationAnalyzer.java:205)
	at io.trino.sql.tree.WindowSpecification.accept(WindowSpecification.java:76)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.AggregationAnalyzer$Visitor.process(AggregationAnalyzer.java:781)
	at io.trino.sql.analyzer.AggregationAnalyzer$Visitor.visitFunctionCall(AggregationAnalyzer.java:451)
	at io.trino.sql.analyzer.AggregationAnalyzer$Visitor.visitFunctionCall(AggregationAnalyzer.java:205)
	at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.AggregationAnalyzer$Visitor.process(AggregationAnalyzer.java:781)
	at io.trino.sql.analyzer.AggregationAnalyzer.analyze(AggregationAnalyzer.java:197)
	at io.trino.sql.analyzer.AggregationAnalyzer.verifySourceAggregations(AggregationAnalyzer.java:137)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeAggregations(StatementAnalyzer.java:4461)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2946)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:476)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:493)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:501)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1449)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:476)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:493)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:455)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:267)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:204)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:856)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:143)
	at io.trino.$gen.Trino_406_65_g0a3ccd0____20230217_061202_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by martint** [comment]
That's because the `DATE_TRUNC(?, date)` in the `SELECT` and `PARTITION` clauses are considered as different expressions with different argument bindings.

You need to rewrite the query as follows:

```sql
PREPARE statement1 FROM
SELECT
    dt,
    SUM(COUNT(DISTINCT custkey)) OVER (PARTITION BY dt)
FROM (
    SELECT *, DATE_TRUNC(?, orderdate) dt
    FROM "tpch"."sf1"."orders"
) t
GROUP BY 1;
```

and then execute it as:

```sql
EXECUTE statement1 USING 'week';
