### ISSUE TITLE
container dies when trying to write iceberg table

### ISSUE THREAD

**Issue by YuriyGavrilov** [trinodb/trino#16189]
1. Just set up fresh environment with 1 coordinator 1 worker and 1 metastore
2. add csv.bz2 file to hive text table ( 1 gigabyte size - 112 millions rows ) 
3. select * from hive text table - works good
4. try to make insert into iceberg select * from hive text table.  container dies on 137 second.
5. one million rows limit works good. 

Help please with writing a full table to iceberg from csv.bz2

```
ateMachine{stageId=20230220_180517_00015_krhag.2, state=RUNNING}, PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.3, state=RUNNING}]
2023-02-20 21:05:29 2023-02-20T18:05:29.110Z    DEBUG   Query-20230220_180517_00015_krhag-546   io.trino.execution.scheduler.policy.PhasedExecutionSchedule     blockedFragments: [2, 3]
2023-02-20 21:05:29 2023-02-20T18:05:29.110Z    DEBUG   Query-20230220_180517_00015_krhag-546   io.trino.execution.scheduler.policy.PhasedExecutionSchedule     selectedForExecution: [PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.2, state=RUNNING}, PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.1, state=SCHEDULING}]
2023-02-20 21:05:29 2023-02-20T18:05:29.185Z    DEBUG   Query-20230220_180517_00015_krhag-546   io.trino.execution.scheduler.policy.PhasedExecutionSchedule     scheduledStages: [PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.2, state=RUNNING}, PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.3, state=RUNNING}]
2023-02-20 21:05:29 2023-02-20T18:05:29.185Z    DEBUG   Query-20230220_180517_00015_krhag-546   io.trino.execution.scheduler.policy.PhasedExecutionSchedule     blockedFragments: [2, 3]
2023-02-20 21:05:29 2023-02-20T18:05:29.185Z    DEBUG   Query-20230220_180517_00015_krhag-546   io.trino.execution.scheduler.policy.PhasedExecutionSchedule     selectedForExecution: [PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.2, state=RUNNING}, PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.1, state=SCHEDULING}]
2023-02-20 21:05:29 2023-02-20T18:05:29.310Z    DEBUG   Query-20230220_180517_00015_krhag-546   io.trino.execution.scheduler.policy.PhasedExecutionSchedule     scheduledStages: [PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.2, state=RUNNING}, PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.3, state=RUNNING}]
2023-02-20 21:05:29 2023-02-20T18:05:29.310Z    DEBUG   Query-20230220_180517_00015_krhag-546   io.trino.execution.scheduler.policy.PhasedExecutionSchedule     blockedFragments: [2, 3]
2023-02-20 21:05:29 2023-02-20T18:05:29.310Z    DEBUG   Query-20230220_180517_00015_krhag-546   io.trino.execution.scheduler.policy.PhasedExecutionSchedule     selectedForExecution: [PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.2, state=RUNNING}, PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.1, state=SCHEDULING}]
2023-02-20 21:05:29 2023-02-20T18:05:29.385Z    DEBUG   Query-20230220_180517_00015_krhag-546   io.trino.execution.scheduler.policy.PhasedExecutionSchedule     scheduledStages: [PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.2, state=RUNNING}, PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.3, state=RUNNING}]
2023-02-20 21:05:29 2023-02-20T18:05:29.385Z    DEBUG   Query-20230220_180517_00015_krhag-546   io.trino.execution.scheduler.policy.PhasedExecutionSchedule     blockedFragments: [2, 3]
2023-02-20 21:05:29 2023-02-20T18:05:29.385Z    DEBUG   Query-20230220_180517_00015_krhag-546   io.trino.execution.scheduler.policy.PhasedExecutionSchedule     selectedForExecution: [PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.2, state=RUNNING}, PipelinedStageStateMachine{stageId=20230220_180517_00015_krhag.1, state=SCHEDULING}]
2023-02-20 21:05:31 Killed
```

**Comment by ebyhr** [comment]
Which container is killed? e.g. Trino coordinator, worker, Iceberg, metatore

Could you share the container's log and Icebeg config propeties?

**Comment by YuriyGavrilov** [comment]
connector.name=iceberg

hive.metastore.uri=thrift://metastore:9083
hive.metastore.username=trino
hive.metastore-timeout=1m

hive.s3.endpoint=https://gateway.storjshare.io
hive.s3.path-style-access=true
hive.s3.aws-access-key=jvli3k
hive.s3.aws-secret-key=jy7vkaw52wlva
hive.s3.ssl.enabled=true
hive.s3.socket-timeout=1m

iceberg.file-format=PARQUET
iceberg.compression-codec=SNAPPY

**Comment by YuriyGavrilov** [comment]
Trino coordinator and worker sometimes killed

**Comment by YuriyGavrilov** [comment]
fresh logs and configs 
-----

`-server
-Xmx8G
-XX:InitialRAMPercentage=80
-XX:MaxRAMPercentage=80
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+ExitOnOutOfMemoryError
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-XX:ReservedCodeCacheSize=512M
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-Djdk.attach.allowAttachSelf=true
-Djdk.nio.maxCachedBufferSize=2000000
-XX:+UnlockDiagnosticVMOptions
-XX:+UseAESCTRIntrinsics
# Disable Preventive GC for performance reasons (JDK-8293861)
-XX:-G1UsePreventiveGC

coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
query.max-memory=2GB
query.max-memory-per-node=1GB
discovery.uri=http://trino:8080

connector.name=iceberg

hive.metastore.uri=thrift://metastore:9083
hive.metastore.username=trino
hive.metastore-timeout=1m

hive.s3.endpoint=https://gateway.storjshare.io
hive.s3.path-style-access=true
hive.s3.aws-access-key=jvli3kmmq6vhyhive.s3.aws-secret-key=jy7vkaw52wlva4ofg5treegtdhfvywcrb2arx45
hive.s3.ssl.enabled=true
hive.s3.socket-timeout=1m

iceberg.file-format=PARQUET
iceberg.compression-codec=SNAPPY

запрос простой

insert into iceberg.my_schema_i.taxi_i select * from hive.my_schema_h.taxi_p limit 1000000`

**Comment by YuriyGavrilov** [comment]
if I reduce limits to one million room it completes normally

**Comment by YuriyGavrilov** [comment]
io.trino.operator.PageTransportTimeoutException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://172.18.0.5:8080/v1/task/20230221_182148_00024_ywyq2.1.0.0/results/0/0 - 97 failures, failure duration 302.09s, total failed request time 304.20s)
	at io.trino.operator.HttpPageBufferClient$1.onFailure(HttpPageBufferClient.java:505)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.UncheckedIOException: Failed communicating with server: http://172.18.0.5:8080/v1/task/20230221_182148_00024_ywyq2.1.0.0/results/0/0
	at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:22)
	at io.trino.operator.HttpPageBufferClient$PageResponseHandler.handleException(HttpPageBufferClient.java:664)
	at io.trino.operator.HttpPageBufferClient$PageResponseHandler.handleException(HttpPageBufferClient.java:651)
	at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:120)
	at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:85)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:213)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:205)
	at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:285)
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:256)
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:159)
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:865)
	at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:530)
	at org.eclipse.jetty.client.HttpDestination.failed(HttpDestination.java:294)
	at org.eclipse.jetty.client.AbstractConnectionPool$FutureConnection.failed(AbstractConnectionPool.java:574)
	at org.eclipse.jetty.util.Promise$Wrapper.failed(Promise.java:169)
	at org.eclipse.jetty.client.HttpClient$1$1.failed(HttpClient.java:628)
	at org.eclipse.jetty.util.Promise$1.failed(Promise.java:94)
	at org.eclipse.jetty.io.ClientConnector.connectFailed(ClientConnector.java:539)
	at org.eclipse.jetty.io.ClientConnector$ClientSelectorManager.connectionFailed(ClientConnector.java:584)
	at org.eclipse.jetty.io.ManagedSelector$Connect.failed(ManagedSelector.java:964)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:366)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:675)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:533)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:450)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:243)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:934)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1078)
	... 1 more
Caused by: java.net.NoRouteToHostException: No route to host
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
	at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:341)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:344)
	... 9 more

**Comment by YuriyGavrilov** [comment]
problem was in memory allocation
