### ISSUE TITLE
Dependencies not found happens when using Iceberg REST catalog

### ISSUE THREAD

**Issue by cgpoh** [trinodb/trino#16213]
I'm trying to get Trino to use Iceberg REST catalog but having issues. I can show schemas and tables from the REST catalog but if I do a "select * from rest.raw" statement, amazon dependencies not found exception will show up. I read from [Trino 407](https://trino.io/docs/current/connector/iceberg.html) that Iceberg REST catalog is supported and how do I resolve this issue?

**Comment by ebyhr** [comment]
Could you share the stacktrace?

**Comment by cgpoh** [comment]
Sure, stacktrace below:

2023-02-22 17:13:15 2023-02-22T09:13:15.967Z    WARN    Query-20230222_091313_00000_65694-162   org.apache.iceberg.io.ResolvingFileIO   Failed to load FileIO implementation: org.apache.iceberg.aws.s3.S3FileIO, falling back to org.apache.iceberg.hadoop.HadoopFileIO
2023-02-22 17:13:15 java.lang.IllegalArgumentException: Cannot initialize FileIO, missing no-arg constructor: org.apache.iceberg.aws.s3.S3FileIO
2023-02-22 17:13:15     at org.apache.iceberg.CatalogUtil.loadFileIO(CatalogUtil.java:310)
2023-02-22 17:13:15     at org.apache.iceberg.io.ResolvingFileIO.io(ResolvingFileIO.java:136)
2023-02-22 17:13:15     at org.apache.iceberg.io.ResolvingFileIO.newInputFile(ResolvingFileIO.java:60)
2023-02-22 17:13:15     at org.apache.iceberg.BaseSnapshot.cacheManifests(BaseSnapshot.java:148)
2023-02-22 17:13:15     at org.apache.iceberg.BaseSnapshot.dataManifests(BaseSnapshot.java:174)
2023-02-22 17:13:15     at org.apache.iceberg.DataTableScan.doPlanFiles(DataTableScan.java:82)
2023-02-22 17:13:15     at org.apache.iceberg.BaseTableScan.planFiles(BaseTableScan.java:152)
2023-02-22 17:13:15     at org.apache.iceberg.DataTableScan.planFiles(DataTableScan.java:27)
2023-02-22 17:13:15     at io.trino.plugin.iceberg.TableStatisticsReader.makeTableStatistics(TableStatisticsReader.java:138)
2023-02-22 17:13:15     at io.trino.plugin.iceberg.TableStatisticsReader.getTableStatistics(TableStatisticsReader.java:101)
2023-02-22 17:13:15     at io.trino.plugin.iceberg.IcebergMetadata.lambda$getTableStatistics$65(IcebergMetadata.java:2354)
2023-02-22 17:13:15     at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
2023-02-22 17:13:15     at io.trino.plugin.iceberg.IcebergMetadata.getTableStatistics(IcebergMetadata.java:2333)
2023-02-22 17:13:15     at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableStatistics(ClassLoaderSafeConnectorMetadata.java:319)
2023-02-22 17:13:15     at io.trino.metadata.MetadataManager.getTableStatistics(MetadataManager.java:460)
2023-02-22 17:13:15     at io.trino.cost.CachingTableStatsProvider.getTableStatistics(CachingTableStatsProvider.java:45)
2023-02-22 17:13:15     at io.trino.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:62)
2023-02-22 17:13:15     at io.trino.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:38)
2023-02-22 17:13:15     at io.trino.cost.SimpleStatsRule.calculate(SimpleStatsRule.java:39)
2023-02-22 17:13:15     at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:85)
2023-02-22 17:13:15     at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:73)
2023-02-22 17:13:15     at io.trino.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:82)
2023-02-22 17:13:15     at io.trino.sql.planner.optimizations.DeterminePartitionCount.lambda$getPartitionCountBasedOnOutputSize$1(DeterminePartitionCount.java:182)
2023-02-22 17:13:15     at java.base/java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:248)
2023-02-22 17:13:15     at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
2023-02-22 17:13:15     at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
2023-02-22 17:13:15     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2023-02-22 17:13:15     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2023-02-22 17:13:15     at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
2023-02-22 17:13:15     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2023-02-22 17:13:15     at java.base/java.util.stream.DoublePipeline.collect(DoublePipeline.java:541)
2023-02-22 17:13:15     at java.base/java.util.stream.DoublePipeline.sum(DoublePipeline.java:450)
2023-02-22 17:13:15     at io.trino.sql.planner.optimizations.DeterminePartitionCount.getSourceNodesOutputStats(DeterminePartitionCount.java:273)
2023-02-22 17:13:15     at io.trino.sql.planner.optimizations.DeterminePartitionCount.getPartitionCountBasedOnOutputSize(DeterminePartitionCount.java:180)
2023-02-22 17:13:15     at io.trino.sql.planner.optimizations.DeterminePartitionCount.determinePartitionCount(DeterminePartitionCount.java:146)
2023-02-22 17:13:15     at io.trino.sql.planner.optimizations.DeterminePartitionCount.optimize(DeterminePartitionCount.java:118)
2023-02-22 17:13:15     at io.trino.sql.planner.optimizations.StatsRecordingPlanOptimizer.optimize(StatsRecordingPlanOptimizer.java:54)
2023-02-22 17:13:15     at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:245)
2023-02-22 17:13:15     at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:220)
2023-02-22 17:13:15     at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:215)
2023-02-22 17:13:15     at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:466)
2023-02-22 17:13:15     at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:447)
2023-02-22 17:13:15     at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:388)
2023-02-22 17:13:15     at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
2023-02-22 17:13:15     at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
2023-02-22 17:13:15     at io.trino.$gen.Trino_407____20230222_091254_2.run(Unknown Source)
2023-02-22 17:13:15     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-02-22 17:13:15     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-02-22 17:13:15     at java.base/java.lang.Thread.run(Thread.java:833)
2023-02-22 17:13:15 Caused by: java.lang.NoSuchMethodException: Cannot find constructor for interface org.apache.iceberg.io.FileIO
2023-02-22 17:13:15     Missing org.apache.iceberg.aws.s3.S3FileIO [java.lang.ClassNotFoundException: org.apache.iceberg.aws.s3.S3FileIO]
2023-02-22 17:13:15     at org.apache.iceberg.common.DynConstructors.buildCheckedException(DynConstructors.java:250)
2023-02-22 17:13:15     at org.apache.iceberg.common.DynConstructors.access$200(DynConstructors.java:32)
2023-02-22 17:13:15     at org.apache.iceberg.common.DynConstructors$Builder.buildChecked(DynConstructors.java:220)
2023-02-22 17:13:15     at org.apache.iceberg.CatalogUtil.loadFileIO(CatalogUtil.java:307)
2023-02-22 17:13:15     ... 48 more
2023-02-22 17:13:15     Suppressed: java.lang.ClassNotFoundException: org.apache.iceberg.aws.s3.S3FileIO
2023-02-22 17:13:15             at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
2023-02-22 17:13:15             at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
2023-02-22 17:13:15             at io.trino.server.PluginClassLoader.loadClass(PluginClassLoader.java:126)
2023-02-22 17:13:15             at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
2023-02-22 17:13:15             at java.base/java.lang.Class.forName0(Native Method)
2023-02-22 17:13:15             at java.base/java.lang.Class.forName(Class.java:467)
2023-02-22 17:13:15             at org.apache.iceberg.common.DynConstructors$Builder.impl(DynConstructors.java:149)
2023-02-22 17:13:15             at org.apache.iceberg.CatalogUtil.loadFileIO(CatalogUtil.java:306)
2023-02-22 17:13:15             ... 48 more
2023-02-22 17:13:15 
2023-02-22 17:13:15 
2023-02-22 17:13:15 2023-02-22T09:13:15.969Z    INFO    Query-20230222_091313_00000_65694-162   org.apache.iceberg.CatalogUtil  Loading custom FileIO implementation: org.apache.iceberg.hadoop.HadoopFileIO
2023-02-22 17:13:16 2023-02-22T09:13:16.315Z    ERROR   Query-20230222_091313_00000_65694-162   io.trino.cost.CachingStatsProvider      Error occurred when computing stats for query 20230222_091313_00000_65694
2023-02-22 17:13:16 java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
2023-02-22 17:13:16     at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2595)
2023-02-22 17:13:16     at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3276)
2023-02-22 17:13:16     at io.trino.hdfs.TrinoFileSystemCache.createFileSystem(TrinoFileSystemCache.java:154)
2023-02-22 17:13:16     at io.trino.hdfs.TrinoFileSystemCache$FileSystemHolder.createFileSystemOnce(TrinoFileSystemCache.java:345)
2023-02-22 17:13:16     at io.trino.hdfs.TrinoFileSystemCache.getInternal(TrinoFileSystemCache.java:139)
2023-02-22 17:13:16     at io.trino.hdfs.TrinoFileSystemCache.get(TrinoFileSystemCache.java:92)
2023-02-22 17:13:16     at org.apache.hadoop.fs.ForwardingFileSystemCache.get(ForwardingFileSystemCache.java:38)
2023-02-22 17:13:16     at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
2023-02-22 17:13:16     at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
2023-02-22 17:13:16     at org.apache.iceberg.hadoop.Util.getFs(Util.java:52)
2023-02-22 17:13:16     at org.apache.iceberg.hadoop.HadoopInputFile.fromLocation(HadoopInputFile.java:56)
2023-02-22 17:13:16     at org.apache.iceberg.hadoop.HadoopFileIO.newInputFile(HadoopFileIO.java:73)
2023-02-22 17:13:16     at org.apache.iceberg.io.ResolvingFileIO.newInputFile(ResolvingFileIO.java:60)
2023-02-22 17:13:16     at org.apache.iceberg.BaseSnapshot.cacheManifests(BaseSnapshot.java:148)
2023-02-22 17:13:16     at org.apache.iceberg.BaseSnapshot.dataManifests(BaseSnapshot.java:174)
2023-02-22 17:13:16     at org.apache.iceberg.DataTableScan.doPlanFiles(DataTableScan.java:82)
2023-02-22 17:13:16     at org.apache.iceberg.BaseTableScan.planFiles(BaseTableScan.java:152)
2023-02-22 17:13:16     at org.apache.iceberg.DataTableScan.planFiles(DataTableScan.java:27)
2023-02-22 17:13:16     at io.trino.plugin.iceberg.TableStatisticsReader.makeTableStatistics(TableStatisticsReader.java:138)
2023-02-22 17:13:16     at io.trino.plugin.iceberg.TableStatisticsReader.getTableStatistics(TableStatisticsReader.java:101)
2023-02-22 17:13:16     at io.trino.plugin.iceberg.IcebergMetadata.lambda$getTableStatistics$65(IcebergMetadata.java:2354)
2023-02-22 17:13:16     at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
2023-02-22 17:13:16     at io.trino.plugin.iceberg.IcebergMetadata.getTableStatistics(IcebergMetadata.java:2333)
2023-02-22 17:13:16     at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableStatistics(ClassLoaderSafeConnectorMetadata.java:319)
2023-02-22 17:13:16     at io.trino.metadata.MetadataManager.getTableStatistics(MetadataManager.java:460)
2023-02-22 17:13:16     at io.trino.cost.CachingTableStatsProvider.getTableStatistics(CachingTableStatsProvider.java:45)
2023-02-22 17:13:16     at io.trino.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:62)
2023-02-22 17:13:16     at io.trino.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:38)
2023-02-22 17:13:16     at io.trino.cost.SimpleStatsRule.calculate(SimpleStatsRule.java:39)
2023-02-22 17:13:16     at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:85)
2023-02-22 17:13:16     at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:73)
2023-02-22 17:13:16     at io.trino.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:82)
2023-02-22 17:13:16     at io.trino.sql.planner.optimizations.DeterminePartitionCount.lambda$getPartitionCountBasedOnOutputSize$1(DeterminePartitionCount.java:182)
2023-02-22 17:13:16     at java.base/java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:248)
2023-02-22 17:13:16     at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
2023-02-22 17:13:16     at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
2023-02-22 17:13:16     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2023-02-22 17:13:16     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2023-02-22 17:13:16     at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
2023-02-22 17:13:16     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2023-02-22 17:13:16     at java.base/java.util.stream.DoublePipeline.collect(DoublePipeline.java:541)
2023-02-22 17:13:16     at java.base/java.util.stream.DoublePipeline.sum(DoublePipeline.java:450)
2023-02-22 17:13:16     at io.trino.sql.planner.optimizations.DeterminePartitionCount.getSourceNodesOutputStats(DeterminePartitionCount.java:273)
2023-02-22 17:13:16     at io.trino.sql.planner.optimizations.DeterminePartitionCount.getPartitionCountBasedOnOutputSize(DeterminePartitionCount.java:180)
2023-02-22 17:13:16     at io.trino.sql.planner.optimizations.DeterminePartitionCount.determinePartitionCount(DeterminePartitionCount.java:146)
2023-02-22 17:13:16     at io.trino.sql.planner.optimizations.DeterminePartitionCount.optimize(DeterminePartitionCount.java:118)
2023-02-22 17:13:16     at io.trino.sql.planner.optimizations.StatsRecordingPlanOptimizer.optimize(StatsRecordingPlanOptimizer.java:54)
2023-02-22 17:13:16     at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:245)
2023-02-22 17:13:16     at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:220)
2023-02-22 17:13:16     at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:215)
2023-02-22 17:13:16     at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:466)
2023-02-22 17:13:16     at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:447)
2023-02-22 17:13:16     at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:388)
2023-02-22 17:13:16     at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
2023-02-22 17:13:16     at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
2023-02-22 17:13:16     at io.trino.$gen.Trino_407____20230222_091254_2.run(Unknown Source)
2023-02-22 17:13:16     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-02-22 17:13:16     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-02-22 17:13:16     at java.base/java.lang.Thread.run(Thread.java:833)
2023-02-22 17:13:16 Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
2023-02-22 17:13:16     at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2499)
2023-02-22 17:13:16     at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2593)
2023-02-22 17:13:16     ... 58 more

**Comment by cgpoh** [comment]
as I'm using Docker compose, I tried adding the dependencies:

  trino-coordinator:
    image: 'trinodb/trino:407'
    hostname: trino-coordinator
    ports:
      - '8088:8088'
    volumes:
      - ./etc:/etc/trino
      - ./usr/lib/iceberg-aws-1.1.0.jar:/usr/lib/trino/plugin/iceberg/iceberg-aws-1.1.0.jar
      - ./usr/lib/s3-2.17.257.jar:/usr/lib/trino/plugin/iceberg/s3-2.17.257.jar
      - ./usr/lib/aws-core-2.17.257.jar:/usr/lib/trino/plugin/iceberg/aws-core-2.17.257.jar
      - ./usr/lib/sdk-core-2.17.257.jar:/usr/lib/trino/plugin/iceberg/sdk-core-2.17.257.jar
      - ./usr/lib/auth-2.17.257.jar:/usr/lib/trino/plugin/iceberg/auth-2.17.257.jar
      - ./usr/lib/sts-2.17.257.jar:/usr/lib/trino/plugin/iceberg/sts-2.17.257.jar
      - ./usr/lib/utils-2.17.257.jar:/usr/lib/trino/plugin/iceberg/utils-2.17.257.jar
      - ./usr/lib/http-client-spi-2.17.257.jar:/usr/lib/trino/plugin/iceberg/http-client-spi-2.17.257.jar
      - ./usr/lib/regions-2.17.257.jar:/usr/lib/trino/plugin/iceberg/regions-2.17.257.jar
      - ./usr/lib/url-connection-client-2.17.257.jar:/usr/lib/trino/plugin/iceberg/url-connection-client-2.17.257.jar
      - ./usr/lib/profiles-2.17.257.jar:/usr/lib/trino/plugin/iceberg/profiles-2.17.257.jar
      - ./usr/lib/metrics-spi-2.17.257.jar:/usr/lib/trino/plugin/iceberg/metrics-spi-2.17.257.jar
      - ./usr/lib/aws-xml-protocol-2.17.257.jar:/usr/lib/trino/plugin/iceberg/aws-xml-protocol-2.17.257.jar
      - ./usr/lib/reactive-streams-1.0.3.jar:/usr/lib/trino/plugin/iceberg/reactive-streams-1.0.3.jar
      - ./usr/lib/aws-json-protocol-2.17.257.jar:/usr/lib/trino/plugin/iceberg/aws-json-protocol-2.17.257.jar
      - ./usr/lib/protocol-core-2.17.257.jar:/usr/lib/trino/plugin/iceberg/protocol-core-2.17.257.jar
      - ./usr/lib/third-party-jackson-core-2.17.257.jar:/usr/lib/trino/plugin/iceberg/third-party-jackson-core-2.17.257.jar
      - ./usr/lib/json-utils-2.17.257.jar:/usr/lib/trino/plugin/iceberg/json-utils-2.17.257.jar
      - ./usr/lib/aws-query-protocol-2.17.257.jar:/usr/lib/trino/plugin/iceberg/aws-query-protocol-2.17.257.jar
      - ./usr/lib/endpoints-spi-2.19.18.jar:/usr/lib/trino/plugin/iceberg/endpoints-spi-2.19.18.jar
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: key
      AWS_SECRET_ACCESS_KEY: secret
    networks:
      - trino-network

but I got another error and the stacktrace is below:

2023-02-22 17:22:59 2023-02-22T09:22:59.023Z    INFO    Query-20230222_092254_00000_3xbhb-173   org.apache.iceberg.BaseTableScan        Scanning table "test/raw".rawtable snapshot 4351736378486598618 created at 2023-02-21T08:48:51.468+00:00 with filter true
2023-02-22 17:22:59 2023-02-22T09:22:59.737Z    ERROR   query-execution-3       io.trino.execution.scheduler.PipelinedQueryScheduler    Failure in distributed stage for query 20230222_092254_00000_3xbhb
2023-02-22 17:22:59 software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 400, Request ID: XVXAEJCKTX7R55SR, Extended Request ID: 7UsDXD5V3qPkZjuTw/DAnxZczhDr3AV0gH4h3aECxrh6kT42LeqDQQxzWqq1d7P+oJ9FkmkVsjY=)
2023-02-22 17:22:59     at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
2023-02-22 17:22:59     at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
2023-02-22 17:22:59     at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
2023-02-22 17:22:59     at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)
2023-02-22 17:22:59     at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:95)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:245)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:167)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175)
2023-02-22 17:22:59     at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
2023-02-22 17:22:59     at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
2023-02-22 17:22:59     at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
2023-02-22 17:22:59     at software.amazon.awssdk.services.s3.DefaultS3Client.headObject(DefaultS3Client.java:5438)
2023-02-22 17:22:59     at org.apache.iceberg.aws.s3.BaseS3File.getObjectMetadata(BaseS3File.java:85)
2023-02-22 17:22:59     at org.apache.iceberg.aws.s3.S3InputFile.getLength(S3InputFile.java:75)
2023-02-22 17:22:59     at org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:100)
2023-02-22 17:22:59     at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:76)
2023-02-22 17:22:59     at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:36)
2023-02-22 17:22:59     at org.apache.iceberg.relocated.com.google.common.collect.Iterables.addAll(Iterables.java:337)
2023-02-22 17:22:59     at org.apache.iceberg.relocated.com.google.common.collect.Lists.newLinkedList(Lists.java:241)
2023-02-22 17:22:59     at org.apache.iceberg.ManifestLists.read(ManifestLists.java:45)
2023-02-22 17:22:59     at org.apache.iceberg.BaseSnapshot.cacheManifests(BaseSnapshot.java:148)
2023-02-22 17:22:59     at org.apache.iceberg.BaseSnapshot.dataManifests(BaseSnapshot.java:174)
2023-02-22 17:22:59     at org.apache.iceberg.DataTableScan.doPlanFiles(DataTableScan.java:82)
2023-02-22 17:22:59     at org.apache.iceberg.BaseTableScan.planFiles(BaseTableScan.java:152)
2023-02-22 17:22:59     at org.apache.iceberg.DataTableScan.planFiles(DataTableScan.java:27)
2023-02-22 17:22:59     at io.trino.plugin.iceberg.IcebergSplitSource.getNextBatch(IcebergSplitSource.java:192)
2023-02-22 17:22:59     at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorSplitSource.getNextBatch(ClassLoaderSafeConnectorSplitSource.java:44)
2023-02-22 17:22:59     at io.trino.split.ConnectorAwareSplitSource.getNextBatch(ConnectorAwareSplitSource.java:53)
2023-02-22 17:22:59     at io.trino.split.BufferingSplitSource$GetNextBatch.fetchSplits(BufferingSplitSource.java:105)
2023-02-22 17:22:59     at io.trino.split.BufferingSplitSource$GetNextBatch.fetchNextBatchAsync(BufferingSplitSource.java:88)
2023-02-22 17:22:59     at io.trino.split.BufferingSplitSource.getNextBatch(BufferingSplitSource.java:52)
2023-02-22 17:22:59     at io.trino.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:247)
2023-02-22 17:22:59     at io.trino.execution.scheduler.SourcePartitionedScheduler$1.schedule(SourcePartitionedScheduler.java:172)
2023-02-22 17:22:59     at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.schedule(PipelinedQueryScheduler.java:1239)
2023-02-22 17:22:59     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2023-02-22 17:22:59     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-22 17:22:59     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-02-22 17:22:59     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-02-22 17:22:59     at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by cgpoh** [comment]
Hi @ebyhr , I got confused. I'm actually using JDBC catalog instead of REST catalog. Thanks for looking at my issue. Closing this issue now.
