### ISSUE TITLE
Table in accessible with error - failed accessing transaction log

### ISSUE THREAD

**Issue by slice-viditp** [trinodb/trino#16257]
`Failed accessing transaction log for table: schema.table`
There is a delta table stored at a S3 location and I am using the following query to create a table using the delta location.
```
CREATE TABLE  glue.default.table(dummy bigint)
WITH (
location = 's3://*****',
partitioned_by = ARRAY['year','month','day']);
```
I am using glue for storing the metadata and in the above query I am giving a dummy schema and partition because this information is picked up automatically from _delta_log . I was able to verify the schema and partition inference from a trino client UI (DBeaver) and using show create table. But when I try to query the table I get the above error.
I was able to narrow the source of error to the *****checkpoint*****.parquet files present in _delta_log .By deleting these checkpoints file and without any change in the table or table properties I was able to query the table successfully.But new writes to this location will generate new checkpoint files in _delta_log and the table becomes inaccessible again.
A workaround for this is changing the location of checkpoints files to a separate location than the table

**Comment by slice-viditp** [comment]
Detailed Error Log 

```
io.trino.spi.TrinoException: Failed accessing transaction log for table: schema.table
	at io.trino.plugin.deltalake.transactionlog.TransactionLogAccess.getActiveFiles(TransactionLogAccess.java:234)
	at io.trino.plugin.deltalake.metastore.HiveMetastoreBackedDeltaLakeMetastore.getValidDataFiles(HiveMetastoreBackedDeltaLakeMetastore.java:235)
	at io.trino.plugin.deltalake.DeltaLakeSplitManager.getSplits(DeltaLakeSplitManager.java:132)
	at io.trino.plugin.deltalake.DeltaLakeSplitManager.getSplits(DeltaLakeSplitManager.java:111)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorSplitManager.getSplits(ClassLoaderSafeConnectorSplitManager.java:51)
	at io.trino.split.SplitManager.getSplits(SplitManager.java:58)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitScanAndFilter(SplitSourceFactory.java:180)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:154)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:128)
	at io.trino.sql.planner.plan.TableScanNode.accept(TableScanNode.java:222)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitOutput(SplitSourceFactory.java:343)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitOutput(SplitSourceFactory.java:128)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.SplitSourceFactory.createSplitSources(SplitSourceFactory.java:108)
	at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.createStageScheduler(PipelinedQueryScheduler.java:1020)
	at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.create(PipelinedQueryScheduler.java:904)
	at io.trino.execution.scheduler.PipelinedQueryScheduler.createDistributedStagesScheduler(PipelinedQueryScheduler.java:310)
	at io.trino.execution.scheduler.PipelinedQueryScheduler.start(PipelinedQueryScheduler.java:291)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:417)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_398_amzn_0____20230224_104537_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Millis overflow: 3094598902496000
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
	at io.trino.collect.cache.EvictableCache.get(EvictableCache.java:108)
	at io.trino.plugin.deltalake.transactionlog.TransactionLogAccess.getActiveFiles(TransactionLogAccess.java:203)
	... 24 more
Caused by: java.lang.IllegalArgumentException: Millis overflow: 3094598902496000
	at io.trino.spi.type.DateTimeEncoding.pack(DateTimeEncoding.java:30)
	at io.trino.spi.type.DateTimeEncoding.packDateTimeWithZone(DateTimeEncoding.java:52)
	at io.trino.plugin.deltalake.transactionlog.checkpoint.CheckpointEntryIterator.readMinMax(CheckpointEntryIterator.java:460)
	at io.trino.plugin.deltalake.transactionlog.checkpoint.CheckpointEntryIterator.parseStatisticsFromParquet(CheckpointEntryIterator.java:417)
	at io.trino.plugin.deltalake.transactionlog.checkpoint.CheckpointEntryIterator.buildAddEntry(CheckpointEntryIterator.java:373)
	at io.trino.plugin.deltalake.transactionlog.checkpoint.CheckpointEntryIterator.fillNextEntries(CheckpointEntryIterator.java:613)
	at io.trino.plugin.deltalake.transactionlog.checkpoint.CheckpointEntryIterator.hasNext(CheckpointEntryIterator.java:562)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.plugin.deltalake.transactionlog.TransactionLogAccess.loadActiveFiles(TransactionLogAccess.java:247)
	at io.trino.plugin.deltalake.transactionlog.TransactionLogAccess.lambda$getActiveFiles$4(TransactionLogAccess.java:204)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	... 28 more
```

**Comment by findinpath** [comment]
Relevant part of the stacktrace:

```
...
Trino_398_amzn_0
...
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Millis overflow: 3094598902496000
```


Can be reproduced via:

```
packDateTimeWithZone(3094598902496000L, TimeZoneKey.UTC_KEY);
```

This issue does not appear in Databricks.

**Comment by theesen** [comment]
I am able to reproducer the error in our environment using Trino release 408.

**Comment by krvikash** [comment]
> this information is picked up automatically from _delta_log

Hi @theesen, I assume the location which you are providing has transaction log already. Could you please try `register_table` procedure https://trino.io/docs/current/connector/delta-lake.html#register-table to register table into the metastore with existing transaction logs and data files?

Using `CREATE TABLE` with an existing table content is deprecated.

**Comment by krvikash** [comment]
> Relevant part of the stacktrace:
> 
> ```
> ...
> Trino_398_amzn_0
> ...
> Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Millis overflow: 3094598902496000
> ```
> 
> Can be reproduced via:
> 
> ```
> packDateTimeWithZone(3094598902496000L, TimeZoneKey.UTC_KEY);
> ```
> 
> This issue does not appear in Databricks.

As mentioned by @findinpath, I will take a look `Millis overflow: 3094598902496000` error.

**Comment by theesen** [comment]
> > this information is picked up automatically from _delta_log
> 
> Hi @theesen, I assume the location which you are providing has transaction log already. Could you please try `register_table` procedure https://trino.io/docs/current/connector/delta-lake.html#register-table to register table into the metastore with existing transaction logs and data files?
> 
> Using `CREATE TABLE` with an existing table content is deprecated.

I am facing the exact same error, when I follow your suggestion.
`CALL delta_lake.system.register_table(schema_name => 'test', table_name => 'foo', table_location => 's3a://my_bucket/warehouse/default.db/another_delta_lake_table');`

**Comment by krvikash** [comment]
Thanks, @theesen for verifying. Is it possible to share the content of the table location? So that I will be easy to debug.

**Comment by theesen** [comment]
Of course, the screenshot shows the direct content of the folder shown in my previous comment
```s3a://my_bucket/warehouse/default.db/another_delta_lake_table```

<img width="577" alt="image" src="https://user-images.githubusercontent.com/1630170/222657532-69a83819-2986-4766-a4d0-8a0a0dd97960.png">

And the delta_log content is the following

<img width="275" alt="image" src="https://user-images.githubusercontent.com/1630170/222657800-51a8f000-445e-41e1-91a7-89884bf0f993.png">

**Comment by krvikash** [comment]
Hi @theesen, I was more of asking for the contents of the table location. So that I could create a table and repro the issue. Currently, I don't know why overflowed value `3094598902496000` is getting read from the checkpoint file.

**Comment by slice-viditp** [comment]
@krvikash I cannot share the contents of the table, but will try to recreate this issue and share that.

**Comment by krvikash** [comment]
Sure @slice-viditp, That would be enough.
