### ISSUE TITLE
mongodb connector: throws io.trino.sql.parser.ParsingException: line 1:13: mismatched input '-'. Expecting: ')', ','

### ISSUE THREAD

**Issue by lwjhn** [trinodb/trino#16253]
I'm using a jdbc connection to look up the number of table files, or to look at the table fields, and some table queries are throwing exceptions.

### sql:
```
select count(1) from mongodb.test.approval
```

### exception:
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error[1]: Query failed (#20230224_081605_00013_3ubj8): io.trino.sql.parser.ParsingException: line 1:13: mismatched input '-'. Expecting: ')', ',', <type>
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:575)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:484)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:878)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3519)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4855)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Query failed (#20230224_081605_00013_3ubj8): io.trino.sql.parser.ParsingException: line 1:13: mismatched input '-'. Expecting: ')', ',', <type>
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:319)
	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:62)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: io.trino.sql.parser.ParsingException: line 1:13: mismatched input '-'. Expecting: ')', ',', <type>
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4952)
	at io.trino.plugin.mongodb.MongoSession.getTable(MongoSession.java:167)
	at io.trino.plugin.mongodb.MongoMetadata.getTableHandle(MongoMetadata.java:83)
	at io.trino.plugin.mongodb.MongoMetadata.getTableHandle(MongoMetadata.java:58)
	at io.trino.metadata.MetadataManager.lambda$getTableHandle$5(MetadataManager.java:393)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at io.trino.metadata.MetadataManager.getTableHandle(MetadataManager.java:387)
	at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1457)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1328)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:362)
	at io.trino.sql.tree.Table.accept(Table.java:53)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:379)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3174)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1946)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:362)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:379)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:389)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1165)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:362)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:379)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:342)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:190)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:806)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
	at io.trino.$gen.Trino_359____20230224_081432_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.trino.sql.parser.ParsingException: line 1:13: mismatched input '-'. Expecting: ')', ',', <type>
	at io.trino.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:109)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at io.trino.sql.parser.SqlBaseParser.type(SqlBaseParser.java:12611)
	at io.trino.sql.parser.SqlBaseParser.standaloneType(SqlBaseParser.java:425)
	at io.trino.sql.parser.SqlParser.invokeParser(SqlParser.java:145)
	at io.trino.sql.parser.SqlParser.createType(SqlParser.java:95)
	at io.trino.metadata.TypeRegistry.fromSqlType(TypeRegistry.java:166)
	at io.trino.metadata.MetadataManager.fromSqlType(MetadataManager.java:1908)
	at io.trino.type.InternalTypeManager.fromSqlType(InternalTypeManager.java:49)
	at io.trino.plugin.mongodb.MongoSession.buildColumnHandle(MongoSession.java:258)
	at io.trino.plugin.mongodb.MongoSession.loadTableSchema(MongoSession.java:244)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 42 more
Caused by: org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2026)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at io.trino.sql.parser.SqlBaseParser.type(SqlBaseParser.java:12297)
	... 55 more
```

**Comment by ebyhr** [comment]
I believe the issue query is different from `select count(1) from mongodb.test.approval`. Could you share the actual query without modification? You may want to get it from webui.

**Comment by lwjhn** [comment]
Thanks for your response, my query did use  `select cout(1) from [mongo collection]` .
I found a field in the mongodb database that was a hashmap, and the key had the `-` character.
I can use presto 0.196 version normally, other versions will have problems. Because the library name is capitalized, the trino test, installing the latest version, and 351 all have the problems described above.

```json
{
  "customFormId": "158aa054948a5000",
  "formValue": {
    "b68c0731-2a94-11ed-b37b-0dbc71e2f5b8": "",
    "LeavePerson": "test111",
    "FromDate": "2022-09-06",
    "LeaveReason": "hh",
    "DraftDate": "2022-09-23 10:18",
    "csyj": null
  },
  "subject": "test-approval-2022-09",
  "draftDate": {
    "$date": {
      "$numberLong": "1663899529063"
    }
  },
  "reader": [
    {
      "readName": "admin",
      "readerNo": "U000001",
      "readOrgNo": "D00004",
      "type": "user",
      "stateLabel": "state20",
      "stateName": "Day-off",
      "createTime": {
        "$date": {
          "$numberLong": "1663899530000"
        }
      }
    }
  ]
}
```

**Comment by ebyhr** [comment]
You need to modify `_schema` collection directly. I confirmed the connector can read the data correctly on latest Trino version.

**Comment by lwjhn** [comment]
Thanks, I delete the corresponding document in the schema, and it really works.
Strangely, a uniform query of `0.196` is normal, so I didn't think of the reason for `_schema`
