### ISSUE TITLE
Iceberg Rest Catalog and s3 security-mapping do not work together

### ISSUE THREAD

**Issue by retrry** [trinodb/trino#16289]
I've been trying to configure rest catalog (https://github.com/tabular-io/iceberg-rest-image/) and Trino to work together. And it works unless I enable `hive.s3.security-mapping.config-file`. When I enable that option Trino starts throwing query error:
```
org.apache.iceberg.exceptions.RuntimeIOException: Failed to get file system for path: s3://testing/bleh/table_name-53c7897c337e4fc1991b77021d543150/metadata/fd2a879c-0c11-4387-986d-4d57cc31f2c7-m0.avro
	at org.apache.iceberg.hadoop.Util.getFs(Util.java:54)
	at org.apache.iceberg.hadoop.HadoopOutputFile.fromPath(HadoopOutputFile.java:53)
	at org.apache.iceberg.hadoop.HadoopFileIO.newOutputFile(HadoopFileIO.java:83)
	at org.apache.iceberg.io.ResolvingFileIO.newOutputFile(ResolvingFileIO.java:70)
	at org.apache.iceberg.SnapshotProducer.newManifestOutput(SnapshotProducer.java:468)
	at org.apache.iceberg.SnapshotProducer.newManifestWriter(SnapshotProducer.java:475)
	at org.apache.iceberg.MergingSnapshotProducer.newFilesAsManifest(MergingSnapshotProducer.java:907)
	at org.apache.iceberg.MergingSnapshotProducer.prepareNewManifests(MergingSnapshotProducer.java:886)
	at org.apache.iceberg.MergingSnapshotProducer.apply(MergingSnapshotProducer.java:802)
	at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:223)
	at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:369)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:402)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:212)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:189)
	at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:367)
	at io.trino.plugin.iceberg.IcebergUtil.commit(IcebergUtil.java:678)
	at io.trino.plugin.iceberg.IcebergMetadata.finishInsert(IcebergMetadata.java:848)
	at io.trino.plugin.iceberg.IcebergMetadata.finishCreateTable(IcebergMetadata.java:736)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishCreateTable(ClassLoaderSafeConnectorMetadata.java:479)
	at io.trino.metadata.MetadataManager.finishCreateTable(MetadataManager.java:880)
	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$4(LocalExecutionPlanner.java:4036)
	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
	at io.trino.operator.Driver.processInternal(Driver.java:394)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:297)
	at io.trino.operator.Driver.tryWithLock(Driver.java:689)
	at io.trino.operator.Driver.process(Driver.java:289)
	at io.trino.operator.Driver.processForDuration(Driver.java:260)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:773)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
	at io.trino.$gen.Trino_408____20230227_230614_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "s3"
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3288)
	at io.trino.hdfs.TrinoFileSystemCache.createFileSystem(TrinoFileSystemCache.java:154)
	at io.trino.hdfs.TrinoFileSystemCache$FileSystemHolder.createFileSystemOnce(TrinoFileSystemCache.java:345)
	at io.trino.hdfs.TrinoFileSystemCache.getInternal(TrinoFileSystemCache.java:139)
	at io.trino.hdfs.TrinoFileSystemCache.get(TrinoFileSystemCache.java:92)
	at org.apache.hadoop.fs.ForwardingFileSystemCache.get(ForwardingFileSystemCache.java:38)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
	at org.apache.iceberg.hadoop.Util.getFs(Util.java:52)
	... 34 more
```

My mapping.json:
```
{
  "mappings": [
    {
      "prefix": "s3://data-warehouse",
      "accessKey": "access_key",
      "secretKey": "secret_key"
    },
    {
      "prefix": "s3://testing",
      "accessKey": "access_key",
      "secretKey": "secret_key"
    }
  ]
}
```

**Comment by retrry** [comment]
Actual problem is my configuration issue with differences between s3 and s3a protocol, not s3 mappings.
