### ISSUE TITLE
TrinoException: number of successes must not be larger than number of trials

### ISSUE THREAD

**Issue by ubyyj** [trinodb/trino#16316]
we hit the following error on version 407:

io.trino.spi.TrinoException: number of successes must not be larger than number of trials
	at io.trino.util.Failures.checkCondition(Failures.java:64)
	at io.trino.operator.scalar.WilsonInterval.wilsonInterval(WilsonInterval.java:48)
	at io.trino.operator.scalar.WilsonInterval.wilsonIntervalLower(WilsonInterval.java:33)
	at io.trino.$gen.PageProjectionWork_20230301_003336_6825.lambda_3(Unknown Source)
	at io.trino.operator.scalar.MapZipWithFunction.mapZipWith(MapZipWithFunction.java:127)
	at io.trino.$gen.PageProjectionWork_20230301_003336_6825.evaluate(Unknown Source)
	at io.trino.$gen.PageProjectionWork_20230301_003336_6825.process(Unknown Source)
	at io.trino.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:348)
	at io.trino.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:220)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:318)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:360)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils$BlockingProcess.process(WorkProcessorUtils.java:208)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorOperatorAdapter.getOutput(WorkProcessorOperatorAdapter.java:173)
	at io.trino.operator.Driver.processInternal(Driver.java:394)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:297)
	at io.trino.operator.Driver.tryWithLock(Driver.java:689)
	at io.trino.operator.Driver.process(Driver.java:289)
	at io.trino.operator.Driver.processForDuration(Driver.java:260)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:773)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
	at io.trino.$gen.Trino_407_dirty____20230228_220857_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ubyyj** [comment]
by looking into the sql, should be a user error
