### ISSUE TITLE
An error is reported when the trino cli executes sql statements.

### ISSUE THREAD

**Issue by youzhiliu** [trinodb/trino#16377]
After a large number of SQL statements are executed, the size of the .trino_history file reaches a certain value. The java.lang.StringIndexOutOfBoundsException: String index out of range: -1 error is reported when any SQL statement is executed on the trino-cli client. After the ./trino_history file is deleted, the fault is rectified.

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at org.jline.reader.impl.history.DefaultHistory.lambda$trimHistory$2(DefaultHistory.java:254)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at org.jline.reader.impl.history.DefaultHistory.trimHistory(DefaultHistory.java:252)
	at org.jline.reader.impl.history.DefaultHistory.internalWrite(DefaultHistory.java:241)
	at org.jline.reader.impl.history.DefaultHistory.save(DefaultHistory.java:219)
	at org.jline.reader.impl.history.DefaultHistory.add(DefaultHistory.java:384)
	at org.jline.reader.impl.LineReaderImpl.finish(LineReaderImpl.java:1140)
	at org.jline.reader.impl.LineReaderImpl.finishBuffer(LineReaderImpl.java:1109)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:689)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:507)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:493)
	at io.trino.cli.InputReader.readLine(InputReader.java:69)
	at io.trino.cli.Console.runConsole(Console.java:242)
	at io.trino.cli.Console.run(Console.java:194)
	at io.trino.cli.Console.call(Console.java:102)
	at io.trino.cli.Console.call(Console.java:75)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.trino.cli.Trino.main(Trino.java:42)
	Suppressed: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
		at java.lang.String.substring(String.java:1967)
		at org.jline.reader.impl.history.DefaultHistory.lambda$trimHistory$2(DefaultHistory.java:254)
		at java.util.Iterator.forEachRemaining(Iterator.java:116)
		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
		at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
		at org.jline.reader.impl.history.DefaultHistory.trimHistory(DefaultHistory.java:252)
		at org.jline.reader.impl.history.DefaultHistory.internalWrite(DefaultHistory.java:241)
		at org.jline.reader.impl.history.DefaultHistory.save(DefaultHistory.java:219)
		at com.google.common.io.Closer.close(Closer.java:218)
		at io.trino.cli.InputReader.close(InputReader.java:79)
		at io.trino.cli.Console.runConsole(Console.java:226)
		... 11 more
```

**Comment by nineinchnick** [comment]
Can you describe steps to reproduce the issue? How many entries need to be in the history file for this to happen?

**Comment by youzhiliu** [comment]
> Can you describe steps to reproduce the issue? How many entries need to be in the history file for this to happen?

Steps to reproduce

Run the SQL statement until the size of the .trino_history file is about 1 MB.

![image](https://user-images.githubusercontent.com/40929212/223047983-d9cb6d63-fa2f-4921-b0d7-2ac4815755b3.png)

**Comment by nineinchnick** [comment]
My local history file is over 2 MB and I don't have this issue. What kind of queries do I need to run?

**Comment by youzhiliu** [comment]
> StringIndexOutOfBoundsException

Yes, it looks like a bug on the jline side
