### ISSUE TITLE
Flaky accumulo test: TestAccumuloConnectorTest.testInsertDuplicateRows: Table does not exist

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#16437]
https://github.com/trinodb/trino/actions/runs/4364381826/jobs/7633010303

```
2023-03-08T14:29:03.7960139Z [ERROR] Tests run: 477, Failures: 1, Errors: 0, Skipped: 186, Time elapsed: 364.697 s <<< FAILURE! - in TestSuite
2023-03-08T14:29:03.7961341Z [ERROR] io.trino.plugin.accumulo.TestAccumuloConnectorTest.testInsertDuplicateRows  Time elapsed: 0.261 s  <<< FAILURE!
2023-03-08T14:29:03.7962488Z io.trino.testing.QueryFailedException: line 1:1: Table 'accumulo.tpch.test_insert_duplicate' does not exist
2023-03-08T14:29:03.7963187Z 	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
2023-03-08T14:29:03.7964058Z 	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:489)
2023-03-08T14:29:03.7964686Z 	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
2023-03-08T14:29:03.7965550Z 	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:401)
2023-03-08T14:29:03.7966267Z 	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:396)
2023-03-08T14:29:03.7967247Z 	at io.trino.plugin.accumulo.TestAccumuloConnectorTest.testInsertDuplicateRows(TestAccumuloConnectorTest.java:195)
2023-03-08T14:29:03.7967989Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-03-08T14:29:03.7968845Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-03-08T14:29:03.7969579Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-03-08T14:29:03.7970411Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-03-08T14:29:03.7971021Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2023-03-08T14:29:03.7971950Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2023-03-08T14:29:03.7972513Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2023-03-08T14:29:03.7973275Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2023-03-08T14:29:03.7973893Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2023-03-08T14:29:03.7974693Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2023-03-08T14:29:03.7975307Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-03-08T14:29:03.7976244Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-03-08T14:29:03.7976775Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-08T14:29:03.7977478Z 	Suppressed: java.lang.Exception: SQL: DROP TABLE test_insert_duplicate
2023-03-08T14:29:03.7978063Z 		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:492)
2023-03-08T14:29:03.7978730Z 		... 17 more
2023-03-08T14:29:03.7979340Z Caused by: io.trino.spi.TrinoException: line 1:1: Table 'accumulo.tpch.test_insert_duplicate' does not exist
2023-03-08T14:29:03.7980197Z 	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
2023-03-08T14:29:03.7980868Z 	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
2023-03-08T14:29:03.7981674Z 	at io.trino.execution.DropTableTask.execute(DropTableTask.java:82)
2023-03-08T14:29:03.7982228Z 	at io.trino.execution.DropTableTask.execute(DropTableTask.java:37)
2023-03-08T14:29:03.7983017Z 	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
2023-03-08T14:29:03.7983633Z 	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
2023-03-08T14:29:03.7984904Z 	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
2023-03-08T14:29:03.7985527Z 	at io.trino.$gen.Trino_testversion____20230308_142306_71.run(Unknown Source)
2023-03-08T14:29:03.7986322Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-03-08T14:29:03.7986961Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-03-08T14:29:03.7987676Z 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ebyhr** [comment]
The actual failed point seems `assertUpdate("CREATE TABLE test_insert_duplicate AS SELECT 1 a, 2 b, '3' c", 1);`. `DROP TABLE test_insert_duplicate` in finally block failed because of the missing table. 
```sh
2023-03-08T14:28:55.3482033Z 2023-03-08T08:28:55.303-0600	ERROR	SplitRunner-4-105	io.trino.execution.executor.TaskExecutor	Error processing Split 20230308_142855_01939_64nhe.1.1.0-0  (start = 695330.484599, wall = 5 ms, cpu = 0 ms, wait = 0 ms, calls = 1): ACCUMULO_TABLE_DNE: Accumulo error when creating BatchWriter and/or Indexer, table does not exist
2023-03-08T14:28:55.3483008Z io.trino.spi.TrinoException: Accumulo error when creating BatchWriter and/or Indexer, table does not exist
2023-03-08T14:28:55.3483873Z 	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:124)
2023-03-08T14:28:55.3485907Z 	at io.trino.plugin.accumulo.io.AccumuloPageSinkProvider.createPageSink(AccumuloPageSinkProvider.java:59)
2023-03-08T14:28:55.3486705Z 	at io.trino.split.PageSinkManager.createPageSink(PageSinkManager.java:49)
2023-03-08T14:28:55.3487485Z 	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:122)
2023-03-08T14:28:55.3488589Z 	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:116)
2023-03-08T14:28:55.3489386Z 	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:103)
2023-03-08T14:28:55.3490753Z 	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:592)
2023-03-08T14:28:55.3491426Z 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:767)
2023-03-08T14:28:55.3492106Z 	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
2023-03-08T14:28:55.3492722Z 	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
2023-03-08T14:28:55.3493342Z 	at io.trino.$gen.Trino_testversion____20230308_142305_36.run(Unknown Source)
2023-03-08T14:28:55.3493875Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-03-08T14:28:55.3494484Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-03-08T14:28:55.3494975Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-08T14:28:55.3495919Z Caused by: org.apache.accumulo.core.client.TableNotFoundException: Table tpch.test_insert_duplicate does not exist
2023-03-08T14:28:55.3496503Z 	at org.apache.accumulo.core.client.impl.Tables._getTableId(Tables.java:88)
2023-03-08T14:28:55.3496967Z 	at org.apache.accumulo.core.client.impl.Tables.getTableId(Tables.java:71)
2023-03-08T14:28:55.3497477Z 	at org.apache.accumulo.core.client.impl.ConnectorImpl.getTableId(ConnectorImpl.java:88)
2023-03-08T14:28:55.3498053Z 	at org.apache.accumulo.core.client.impl.ConnectorImpl.createBatchWriter(ConnectorImpl.java:143)
2023-03-08T14:28:55.3498591Z 	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:105)
2023-03-08T14:28:55.3498905Z 	... 13 more
2023-03-08T14:28:55.3499027Z 
2023-03-08T14:28:55.3499036Z 
2023-03-08T14:28:55.3499686Z 2023-03-08T08:28:55.307-0600	ERROR	remote-task-callback-27	io.trino.execution.scheduler.PipelinedStageExecution	Pipelined stage execution for stage 20230308_142855_01939_64nhe.1 failed
2023-03-08T14:28:55.3500271Z io.trino.spi.TrinoException: Accumulo error when creating BatchWriter and/or Indexer, table does not exist
2023-03-08T14:28:55.3500735Z 	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:124)
2023-03-08T14:28:55.3501286Z 	at io.trino.plugin.accumulo.io.AccumuloPageSinkProvider.createPageSink(AccumuloPageSinkProvider.java:59)
2023-03-08T14:28:55.3505621Z 	at io.trino.split.PageSinkManager.createPageSink(PageSinkManager.java:49)
2023-03-08T14:28:55.3508506Z 	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:122)
2023-03-08T14:28:55.3509127Z 	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:116)
2023-03-08T14:28:55.3509644Z 	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:103)
2023-03-08T14:28:55.3520712Z 	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:592)
2023-03-08T14:28:55.3530389Z 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:767)
2023-03-08T14:28:55.3532951Z 	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
2023-03-08T14:28:55.3542436Z 	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
2023-03-08T14:28:55.3546480Z 	at io.trino.$gen.Trino_testversion____20230308_142305_36.run(Unknown Source)
2023-03-08T14:28:55.3557463Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-03-08T14:28:55.3558043Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-03-08T14:28:55.3558518Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-08T14:28:55.3559044Z Caused by: org.apache.accumulo.core.client.TableNotFoundException: Table tpch.test_insert_duplicate does not exist
2023-03-08T14:28:55.3559735Z 	at org.apache.accumulo.core.client.impl.Tables._getTableId(Tables.java:88)
2023-03-08T14:28:55.3560288Z 	at org.apache.accumulo.core.client.impl.Tables.getTableId(Tables.java:71)
2023-03-08T14:28:55.3608897Z 	at org.apache.accumulo.core.client.impl.ConnectorImpl.getTableId(ConnectorImpl.java:88)
2023-03-08T14:28:55.3609583Z 	at org.apache.accumulo.core.client.impl.ConnectorImpl.createBatchWriter(ConnectorImpl.java:143)
2023-03-08T14:28:55.3610568Z 	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:105)
2023-03-08T14:28:55.3632304Z 	... 13 more
2023-03-08T14:28:55.3632439Z 
2023-03-08T14:28:55.3633069Z 
2023-03-08T14:28:55.3637278Z 2023-03-08T08:28:55.308-0600	ERROR	stage-scheduler	io.trino.execution.scheduler.PipelinedQueryScheduler	Failure in distributed stage for query 20230308_142855_01939_64nhe
2023-03-08T14:28:55.3637886Z io.trino.spi.TrinoException: Accumulo error when creating BatchWriter and/or Indexer, table does not exist
2023-03-08T14:28:55.3638593Z 	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:124)
2023-03-08T14:28:55.3717555Z 	at io.trino.plugin.accumulo.io.AccumuloPageSinkProvider.createPageSink(AccumuloPageSinkProvider.java:59)
2023-03-08T14:28:55.3729191Z 	at io.trino.split.PageSinkManager.createPageSink(PageSinkManager.java:49)
2023-03-08T14:28:55.3731119Z 	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:122)
2023-03-08T14:28:55.3731870Z 	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:116)
2023-03-08T14:28:55.3732416Z 	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:103)
2023-03-08T14:28:55.3732914Z 	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:592)
2023-03-08T14:28:55.3733446Z 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:767)
2023-03-08T14:28:55.3733984Z 	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
2023-03-08T14:28:55.3734487Z 	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
2023-03-08T14:28:55.3734884Z 	at io.trino.$gen.Trino_testversion____20230308_142305_36.run(Unknown Source)
2023-03-08T14:28:55.3735316Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-03-08T14:28:55.3735812Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-03-08T14:28:55.3736207Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-08T14:28:55.3736671Z Caused by: org.apache.accumulo.core.client.TableNotFoundException: Table tpch.test_insert_duplicate does not exist
2023-03-08T14:28:55.3737176Z 	at org.apache.accumulo.core.client.impl.Tables._getTableId(Tables.java:88)
2023-03-08T14:28:55.3737628Z 	at org.apache.accumulo.core.client.impl.Tables.getTableId(Tables.java:71)
2023-03-08T14:28:55.3738130Z 	at org.apache.accumulo.core.client.impl.ConnectorImpl.getTableId(ConnectorImpl.java:88)
2023-03-08T14:28:55.3738686Z 	at org.apache.accumulo.core.client.impl.ConnectorImpl.createBatchWriter(ConnectorImpl.java:143)
2023-03-08T14:28:55.3739209Z 	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:105)
2023-03-08T14:28:55.3739521Z 	... 13 more
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4884417707/jobs/8718083909?pr=12734

```
2023-05-04T11:22:38.092-0600	INFO	pool-3-thread-2	io.trino.testng.services.ProgressLoggingListener	[TEST START] io.trino.plugin.accumulo.TestAccumuloConnectorTest.testCaseSensitiveDataMapping [varchar(1):B]
2023-05-04T11:22:38.180-0600	INFO	dispatcher-query-9	io.trino.event.QueryMonitor	TIMELINE: Query 20230504_172237_00278_ggmf8 :: FAILED (NOT_SUPPORTED) :: elapsed 261ms :: planning 161ms :: waiting 24ms :: scheduling 83ms :: running 34ms :: finishing 0ms :: begin 2023-05-04T11:22:37.809-06:00 :: end 2023-05-04T11:22:38.070-06:00
2023-05-04T11:22:38.785-0600	ERROR	SplitRunner-1-69	io.trino.execution.executor.TaskExecutor	Error processing Split 20230504_172238_00279_ggmf8.1.2.0-0  (start = 647273.306984, wall = 54 ms, cpu = 0 ms, wait = 0 ms, calls = 1): ACCUMULO_TABLE_DNE: Accumulo error when creating BatchWriter and/or Indexer, table does not exist
io.trino.spi.TrinoException: Accumulo error when creating BatchWriter and/or Indexer, table does not exist
	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:124)
	at io.trino.plugin.accumulo.io.AccumuloPageSinkProvider.createPageSink(AccumuloPageSinkProvider.java:59)
	at io.trino.split.PageSinkManager.createPageSink(PageSinkManager.java:49)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:123)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:117)
	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:106)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:666)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:877)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:561)
	at io.trino.$gen.Trino_testversion____20230504_171856_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.accumulo.core.client.TableNotFoundException: Table tpch.test_data_mapping_smoke_varchar_1_5bx2zfydps does not exist
	at org.apache.accumulo.core.client.impl.Tables._getTableId(Tables.java:88)
	at org.apache.accumulo.core.client.impl.Tables.getTableId(Tables.java:71)
	at org.apache.accumulo.core.client.impl.ConnectorImpl.getTableId(ConnectorImpl.java:88)
	at org.apache.accumulo.core.client.impl.ConnectorImpl.createBatchWriter(ConnectorImpl.java:143)
	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:105)
	... 13 more


2023-05-04T11:22:38.793-0600	ERROR	remote-task-callback-6	io.trino.execution.scheduler.PipelinedStageExecution	Pipelined stage execution for stage 20230504_172238_00279_ggmf8.1 failed
io.trino.spi.TrinoException: Accumulo error when creating BatchWriter and/or Indexer, table does not exist
	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:124)
	at io.trino.plugin.accumulo.io.AccumuloPageSinkProvider.createPageSink(AccumuloPageSinkProvider.java:59)
	at io.trino.split.PageSinkManager.createPageSink(PageSinkManager.java:49)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:123)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:117)
	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:106)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:666)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:877)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:561)
	at io.trino.$gen.Trino_testversion____20230504_171856_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.accumulo.core.client.TableNotFoundException: Table tpch.test_data_mapping_smoke_varchar_1_5bx2zfydps does not exist
	at org.apache.accumulo.core.client.impl.Tables._getTableId(Tables.java:88)
	at org.apache.accumulo.core.client.impl.Tables.getTableId(Tables.java:71)
	at org.apache.accumulo.core.client.impl.ConnectorImpl.getTableId(ConnectorImpl.java:88)
	at org.apache.accumulo.core.client.impl.ConnectorImpl.createBatchWriter(ConnectorImpl.java:143)
	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:105)
	... 13 more


2023-05-04T11:22:38.794-0600	ERROR	stage-scheduler	io.trino.execution.scheduler.PipelinedQueryScheduler	Failure in distributed stage for query 20230504_172238_00279_ggmf8
io.trino.spi.TrinoException: Accumulo error when creating BatchWriter and/or Indexer, table does not exist
	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:124)
	at io.trino.plugin.accumulo.io.AccumuloPageSinkProvider.createPageSink(AccumuloPageSinkProvider.java:59)
	at io.trino.split.PageSinkManager.createPageSink(PageSinkManager.java:49)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:123)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:117)
	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:106)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:666)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:877)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:561)
	at io.trino.$gen.Trino_testversion____20230504_171856_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.accumulo.core.client.TableNotFoundException: Table tpch.test_data_mapping_smoke_varchar_1_5bx2zfydps does not exist
	at org.apache.accumulo.core.client.impl.Tables._getTableId(Tables.java:88)
	at org.apache.accumulo.core.client.impl.Tables.getTableId(Tables.java:71)
	at org.apache.accumulo.core.client.impl.ConnectorImpl.getTableId(ConnectorImpl.java:88)
	at org.apache.accumulo.core.client.impl.ConnectorImpl.createBatchWriter(ConnectorImpl.java:143)
	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:105)
	... 13 more


2023-05-04T11:22:38.794-0600	ERROR	stage-scheduler	io.trino.execution.StageStateMachine	Stage 20230504_172238_00279_ggmf8.1 failed
io.trino.spi.TrinoException: Accumulo error when creating BatchWriter and/or Indexer, table does not exist
	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:124)
	at io.trino.plugin.accumulo.io.AccumuloPageSinkProvider.createPageSink(AccumuloPageSinkProvider.java:59)
	at io.trino.split.PageSinkManager.createPageSink(PageSinkManager.java:49)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:123)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:117)
	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:106)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:666)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:877)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:561)
	at io.trino.$gen.Trino_testversion____20230504_171856_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.accumulo.core.client.TableNotFoundException: Table tpch.test_data_mapping_smoke_varchar_1_5bx2zfydps does not exist
	at org.apache.accumulo.core.client.impl.Tables._getTableId(Tables.java:88)
	at org.apache.accumulo.core.client.impl.Tables.getTableId(Tables.java:71)
	at org.apache.accumulo.core.client.impl.ConnectorImpl.getTableId(ConnectorImpl.java:88)
	at org.apache.accumulo.core.client.impl.ConnectorImpl.createBatchWriter(ConnectorImpl.java:143)
	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:105)
	... 13 more


2023-05-04T11:22:38.820-0600	INFO	pool-3-thread-2	io.trino.testng.services.FlakyTestRetryAnalyzer	not retrying; @Flaky annotation not present
2023-05-04T11:22:38.851-0600	ERROR	pool-3-thread-2	io.trino.testng.services.ProgressLoggingListener	[TEST FAILURE] io.trino.plugin.accumulo.TestAccumuloConnectorTest.testCaseSensitiveDataMapping [varchar(1):B]; (took: 0.7 seconds)
```

cc @kokosing

**Comment by ksobolew** [comment]
https://github.com/trinodb/trino/actions/runs/6094933858/job/16538675122?pr=18933

```
io.trino.testing.QueryFailedException: Accumulo error when creating BatchWriter and/or Indexer, table does not exist
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:516)
	at io.trino.testing.QueryAssertions.assertDistributedUpdate(QueryAssertions.java:107)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:63)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:410)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:405)
	at io.trino.testing.BaseConnectorTest.lambda$testDataMapping$71(BaseConnectorTest.java:5424)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:892)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1366)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1210)
	at io.trino.testing.BaseConnectorTest.testDataMapping(BaseConnectorTest.java:5427)
	at io.trino.testing.BaseConnectorTest.testDataMappingSmokeTest(BaseConnectorTest.java:5401)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE test_data_mapping_smoke_decimal_15_3_nj9gqj3c43 AS SELECT CAST(row_id AS varchar(50)) row_id, CAST(value AS decimal(15,3)) value, CAST(value AS decimal(15,3)) another_column FROM (VALUES   ('null value', NULL),   ('sample value', 123456789012.345),   ('high value', 999999999999.99))  t(row_id, value)
		at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:520)
		... 24 more
Caused by: io.trino.spi.TrinoException: Accumulo error when creating BatchWriter and/or Indexer, table does not exist
	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:124)
	at io.trino.plugin.accumulo.io.AccumuloPageSinkProvider.createPageSink(AccumuloPageSinkProvider.java:58)
	at io.trino.split.PageSinkManager.createPageSink(PageSinkManager.java:48)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:123)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:117)
	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:105)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:665)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:876)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_testversion____20230906_113321_75.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.accumulo.core.client.TableNotFoundException: Table tpch.test_data_mapping_smoke_decimal_15_3_nj9gqj3c43 does not exist
	at org.apache.accumulo.core.client.impl.Tables._getTableId(Tables.java:88)
	at org.apache.accumulo.core.client.impl.Tables.getTableId(Tables.java:71)
	at org.apache.accumulo.core.client.impl.ConnectorImpl.getTableId(ConnectorImpl.java:88)
	at org.apache.accumulo.core.client.impl.ConnectorImpl.createBatchWriter(ConnectorImpl.java:143)
	at io.trino.plugin.accumulo.io.AccumuloPageSink.<init>(AccumuloPageSink.java:105)
	... 13 more
at BaseConnectorTest.verifyUnsupportedTypeException(BaseConnectorTest.java:6191)
```
