### ISSUE TITLE
Metadata $files table on iceberg connector throws an error

### ISSUE THREAD

**Issue by ricardopereira33** [trinodb/trino#16473]
On the last version 409, we start getting the following error when we try to query the `$files` metadata table from an Iceberg table:

```
Error: TrinoQueryError(type=INTERNAL_ERROR, name=GENERIC_INTERNAL_ERROR, message="Unknown type: class java.util.ArrayList", query_id=20230309_140747_03630_wb3r2)
```

Query:
```
SELECT * FROM <schema>."<table>$files"
```

Strack Trace:
```
java.lang.IllegalArgumentException: Unknown type: class java.util.ArrayList
	at io.trino.spi.connector.InMemoryRecordSet.sizeOf(InMemoryRecordSet.java:328)
	at io.trino.spi.connector.InMemoryRecordSet$InMemoryRecordCursor.advanceNextPosition(InMemoryRecordSet.java:111)
	at io.trino.split.MappedRecordSet$MappedRecordCursor.advanceNextPosition(MappedRecordSet.java:89)
	at io.trino.spi.connector.RecordPageSource.getNextPage(RecordPageSource.java:88)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:301)
	at io.trino.operator.Driver.processInternal(Driver.java:394)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:297)
	at io.trino.operator.Driver.tryWithLock(Driver.java:689)
	at io.trino.operator.Driver.process(Driver.java:289)
	at io.trino.operator.Driver.processForDuration(Driver.java:260)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:773)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
	at io.trino.$gen.Trino_409____20230308_140820_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by alexjo2144** [comment]
@krvikash would you be able to take a look tomorrow? I think this relates to your changes

**Comment by findinpath** [comment]
See the fix here https://github.com/trinodb/trino/pull/16232/commits/009753c8c2dca51d8603fb0dd4d2d0c08bef001c

**Comment by electrum** [comment]
We should change `FilesTable` (and the other system tables) to use `pageSource()` instead of `cursor()`. `RecordCursor` is inefficient and ends up being more complicated to use for complex types.

**Comment by findepi** [comment]
We shouldn't prevent doing a bug fix because we would want a refactor, unless bugfix and refactor are comparable in complexity.
