### ISSUE TITLE
JDBC bind variables aren't supported in JSON_OBJECT

### ISSUE THREAD

**Issue by lukaseder** [trinodb/trino#16489]
I'm running this on Trino 409:

```java
try (PreparedStatement s = connection.prepareStatement("select json_object(key 'a' value ?)")) {
    s.setInt(1, 1);

    try (ResultSet rs = s.executeQuery()) {
        while (rs.next())
            System.out.println(rs.getString(1));
    }
}
```

It produces this exception:

```
Exception in thread "main" java.sql.SQLException: Query failed (#20230310_111239_40025_8hyv9): line 1:1: Incorrect number of parameters: expected 0 but found 1
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1943)
	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:319)
	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:62)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
	at io.trino.jdbc.TrinoPreparedStatement.executeQuery(TrinoPreparedStatement.java:135)
	at org.jooq.testscripts.JDBC.main(JDBC.java:47)
Caused by: io.trino.spi.TrinoException: line 1:1: Incorrect number of parameters: expected 0 but found 1
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.execution.QueryPreparer.validateParameters(QueryPreparer.java:88)
	at io.trino.execution.QueryPreparer.prepareQuery(QueryPreparer.java:80)
	at io.trino.execution.QueryPreparer.prepareQuery(QueryPreparer.java:56)
	at io.trino.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:179)
	at io.trino.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:148)
	at io.trino.$gen.Trino_409____20230310_081156_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

## Workarounds:

**Inline bind values:**

```java
try (PreparedStatement s = connection.prepareStatement("select json_object(key 'a' value 1)")) {
    try (ResultSet rs = s.executeQuery()) {
        while (rs.next())
            System.out.println(rs.getString(1));
    }
}
```

This produces the correct result:

```
{"a":1}
```

**Nest the expression and bind the value to a `VALUES` constructor**

```java
try (PreparedStatement s = connection.prepareStatement("select (select json_object(key 'a' value v) from (values (?)) as t (v))")) {
    s.setInt(1, 1);

    try (ResultSet rs = s.executeQuery()) {
        while (rs.next())
            System.out.println(rs.getString(1));
    }
}
```

**Comment by lukaseder** [comment]
`JSON_ARRAY` is also affected:

```java
try (PreparedStatement s = connection.prepareStatement("select json_array(?)")) {
    s.setInt(1, 1);

    try (ResultSet rs = s.executeQuery()) {
        while (rs.next())
            System.out.println(rs.getString(1));
    }
}
```

Same error:

```
Exception in thread "main" java.sql.SQLException: Query failed (#20230310_111657_40040_8hyv9): line 1:1: Incorrect number of parameters: expected 0 but found 1
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1943)
	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:319)
	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:62)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
	at io.trino.jdbc.TrinoPreparedStatement.executeQuery(TrinoPreparedStatement.java:135)
	at org.jooq.testscripts.JDBC.main(JDBC.java:47)
Caused by: io.trino.spi.TrinoException: line 1:1: Incorrect number of parameters: expected 0 but found 1
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.execution.QueryPreparer.validateParameters(QueryPreparer.java:88)
	at io.trino.execution.QueryPreparer.prepareQuery(QueryPreparer.java:80)
	at io.trino.execution.QueryPreparer.prepareQuery(QueryPreparer.java:56)
	at io.trino.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:179)
	at io.trino.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:148)
	at io.trino.$gen.Trino_409____20230310_081156_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
