### ISSUE TITLE
Queries fail while using native hive formats

### ISSUE THREAD

**Issue by guyco33** [trinodb/trino#16510]
Since version `409`  (with https://github.com/trinodb/trino/pull/15918) queries fail on `java.lang.IllegalArgumentException: Compressed files are not splittable` while using  configuration `{$format}.native-reader.enabled=true`

Issue happens when reading external hive tables and only during the time that the underline files are updated.

Issue doesn't happen when the underlined files are not updated.
It also doesn’t happen when
`native-reader.enabled=false`.

External table for example:
```
CREATE TABLE hive.temp.events (
   event_name varchar,
   event_at varchar,
   env varchar,
   payload varchar
)
WITH (
   csv_escape = U&'\0000',
   csv_separator = ',',
   external_location = 's3a://bucket-name/events/last_hour',
   format = 'CSV'
)
```

Files in `s3://bucket-name/events/last_hour`
```
-- Each one minute, a relevant file is replaced. 

s3://bucket-name/events/last_hour/00.gz
s3://bucket-name/events/last_hour/01.gz
s3://bucket-name/events/last_hour/02.gz
.
.
.
s3://bucket-name/events/last_hour/59.gz
```

Query using `events` table:
```
SELECT count(*) 
FROM events
WHERE event_name = 'some_event'
AND json_extract_scalar(payload, '$.status') = 'failed'
```

When `csv.native-reader.enabled=false` no issue happen 

When `csv.native-reader.enabled=true` (the default) queries fail from time to time:

```
io.trino.spi.TrinoException: Error opening Hive split s3a://bucket-name/events/last_hour/59.gz (offset=0, length=18736): Compressed files are not splittable
	at io.trino.plugin.hive.line.LinePageSourceFactory.createPageSource(LinePageSourceFactory.java:191)
	at io.trino.plugin.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:216)
	at io.trino.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:154)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:49)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:62)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:266)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:194)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:360)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:241)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:256)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:146)
	at io.trino.operator.Driver.processInternal(Driver.java:394)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:297)
	at io.trino.operator.Driver.tryWithLock(Driver.java:689)
	at io.trino.operator.Driver.process(Driver.java:289)
	at io.trino.operator.Driver.processForDuration(Driver.java:260)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:773)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
	at io.trino.$gen.Trino_409____20230312_083525_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Compressed files are not splittable
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at io.trino.hive.formats.line.text.TextLineReaderFactory.createLineReader(TextLineReaderFactory.java:71)
	at io.trino.plugin.hive.line.LinePageSourceFactory.createPageSource(LinePageSourceFactory.java:179)
	... 31 more
```

cc: @dain @electrum

**Comment by dain** [comment]
This is likely related to #16492
