### ISSUE TITLE
Error: Query does not roundtrip when using JDBC to call POSITION(? IN SUBSTRING(?, ?))

### ISSUE THREAD

**Issue by lukaseder** [trinodb/trino#16516]
I'm using trino 410 in docker, out of the box installation:

```
docker pull trinodb/trino
docker run -p 8080:8080 --name TRINO trinodb/trino
```

And connect to it with:

```
jdbc:trino://localhost:8080/memory/default
```

Try the following program:

```java
try (PreparedStatement s = connection.prepareStatement("""
    select position(? in substring(?, ?))
    """)) {

    int i = 1;
    s.setString(i++, "c");
    s.setString(i++, "abcdecde");
    s.setInt(i++, 5);

    try (ResultSet rs = s.executeQuery()) {
        while (rs.next()) {
            println(rs.getInt(1));
        }
    }
}
```

It fails with:

```
Exception in thread "main" java.sql.SQLException: Query failed (#20230313_094550_62964_f2dms): Query does not round-trip
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1943)
	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:319)
	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:62)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
	at io.trino.jdbc.TrinoPreparedStatement.<init>(TrinoPreparedStatement.java:119)
	at io.trino.jdbc.TrinoConnection.prepareStatement(TrinoConnection.java:172)
	at org.jooq.testscripts.JDBC.main(JDBC.java:43)
Caused by: io.trino.spi.TrinoException: Query does not round-trip
	at io.trino.sql.SqlFormatterUtil.formattingFailure(SqlFormatterUtil.java:54)
	at io.trino.sql.SqlFormatterUtil.getFormattedSql(SqlFormatterUtil.java:46)
	at io.trino.execution.PrepareTask.execute(PrepareTask.java:66)
	at io.trino.execution.PrepareTask.execute(PrepareTask.java:36)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_410____20230313_082913_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.RuntimeException: Statement: Query{queryBody=QuerySpecification{select=Select{distinct=false, selectItems=[strpos(substring(?, ?), ?)]}, from=Optional.empty, where=null, groupBy=Optional.empty, having=null, windows=null, orderBy=Optional.empty, offset=null, limit=null}, orderBy=Optional.empty}
		at io.trino.sql.SqlFormatterUtil.formattingFailure(SqlFormatterUtil.java:55)
		... 10 more
	Suppressed: java.lang.RuntimeException: Formatted: [SELECT strpos(substring(?, ?), ?)

]
		at io.trino.sql.SqlFormatterUtil.formattingFailure(SqlFormatterUtil.java:56)
		... 10 more
```

**Comment by ebyhr** [comment]
JDBC isn't required to reproduce the issue. We can reproduce the failure with below query in CLI. 
```sql
PREPARE my_select1 FROM SELECT position(? IN ?);
```

**Comment by lukaseder** [comment]
Thanks for the hint, @ebyhr. I'll try that directly next time I report a thing.
