### ISSUE TITLE
ClassCastException when nesting JSON_OBJECT(.. CAST(ARRAY_AGG(JSON_OBJECT(..)) AS JSON))

### ISSUE THREAD

**Issue by lukaseder** [trinodb/trino#16523]
I'm using trino 410 in docker, out of the box installation:

```
docker pull trinodb/trino
docker run -p 8080:8080 --name TRINO trinodb/trino
```

Using connector:

```sql
use memory.default;
```

This query fails:

```sql
select json_object(key 'x' value cast(array_agg(json_object(key 'a' value 'a')) as json));
```

When run in Dbeaver, it produces this stack trace:

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [65536]: Query failed (#20230313_140541_35312_f2dms): java.lang.RuntimeException: java.lang.ClassCastException: class io.trino.operator.aggregation.ParametricAggregation cannot be cast to class io.trino.metadata.SqlScalarFunction (io.trino.operator.aggregation.ParametricAggregation and io.trino.metadata.SqlScalarFunction are in unnamed module of loader 'app')
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:582)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:920)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3805)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5068)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Query failed (#20230313_140541_35312_f2dms): java.lang.RuntimeException: java.lang.ClassCastException: class io.trino.operator.aggregation.ParametricAggregation cannot be cast to class io.trino.metadata.SqlScalarFunction (io.trino.operator.aggregation.ParametricAggregation and io.trino.metadata.SqlScalarFunction are in unnamed module of loader 'app')
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1943)
	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:319)
	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:62)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassCastException: class io.trino.operator.aggregation.ParametricAggregation cannot be cast to class io.trino.metadata.SqlScalarFunction (io.trino.operator.aggregation.ParametricAggregation and io.trino.metadata.SqlScalarFunction are in unnamed module of loader 'app')
	at io.trino.metadata.FunctionManager.getScalarFunctionImplementation(FunctionManager.java:97)
	at io.trino.sql.InterpretedFunctionInvoker.invoke(InterpretedFunctionInvoker.java:63)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:1059)
	at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processWithExceptionHandling(ExpressionInterpreter.java:315)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitCast(ExpressionInterpreter.java:1232)
	at io.trino.sql.tree.Cast.accept(Cast.java:91)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processWithExceptionHandling(ExpressionInterpreter.java:315)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitCast(ExpressionInterpreter.java:1232)
	at io.trino.sql.tree.Cast.accept(Cast.java:91)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processWithExceptionHandling(ExpressionInterpreter.java:315)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitRow(ExpressionInterpreter.java:1432)
	at io.trino.sql.tree.Row.accept(Row.java:54)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processWithExceptionHandling(ExpressionInterpreter.java:315)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:1030)
	at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processWithExceptionHandling(ExpressionInterpreter.java:315)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:1030)
	at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.processWithExceptionHandling(ExpressionInterpreter.java:315)
	at io.trino.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:295)
	at io.trino.sql.planner.iterative.rule.SimplifyExpressions.rewrite(SimplifyExpressions.java:54)
	at io.trino.sql.planner.iterative.rule.SimplifyExpressions.lambda$createRewrite$0(SimplifyExpressions.java:79)
	at io.trino.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.lambda$apply$0(ExpressionRewriteRuleSet.java:142)
	at io.trino.sql.planner.plan.Assignments.lambda$rewrite$1(Assignments.java:124)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.sql.planner.plan.Assignments.rewrite(Assignments.java:125)
	at io.trino.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.apply(ExpressionRewriteRuleSet.java:142)
	at io.trino.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.apply(ExpressionRewriteRuleSet.java:123)
	at io.trino.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:203)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:170)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:133)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:252)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:135)
	at io.trino.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:118)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:245)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:220)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:215)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:466)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:447)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:388)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_410____20230313_082913_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: class io.trino.operator.aggregation.ParametricAggregation cannot be cast to class io.trino.metadata.SqlScalarFunction (io.trino.operator.aggregation.ParametricAggregation and io.trino.metadata.SqlScalarFunction are in unnamed module of loader 'app')
	at io.trino.metadata.InternalFunctionBundle.getScalarFunctionImplementation(InternalFunctionBundle.java:134)
	at io.trino.metadata.GlobalFunctionCatalog.getScalarFunctionImplementation(GlobalFunctionCatalog.java:173)
	at io.trino.metadata.FunctionManager.getScalarFunctionImplementationInternal(FunctionManager.java:104)
	at io.trino.metadata.FunctionManager.lambda$getScalarFunctionImplementation$0(FunctionManager.java:93)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
	at com.google.common.cache.ForwardingCache.get(ForwardingCache.java:55)
	at io.trino.collect.cache.CacheUtils.uncheckedCacheGet(CacheUtils.java:28)
	at io.trino.metadata.FunctionManager.getScalarFunctionImplementation(FunctionManager.java:93)
	... 59 more
Caused by: java.lang.ClassCastException: class io.trino.operator.aggregation.ParametricAggregation cannot be cast to class io.trino.metadata.SqlScalarFunction (io.trino.operator.aggregation.ParametricAggregation and io.trino.metadata.SqlScalarFunction are in unnamed module of loader 'app')
	at io.trino.metadata.InternalFunctionBundle.specializeScalarFunction(InternalFunctionBundle.java:141)
	at io.trino.metadata.InternalFunctionBundle.lambda$getScalarFunctionImplementation$1(InternalFunctionBundle.java:130)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
	at com.google.common.cache.ForwardingCache.get(ForwardingCache.java:55)
	at io.trino.collect.cache.CacheUtils.uncheckedCacheGet(CacheUtils.java:28)
	at io.trino.metadata.InternalFunctionBundle.getScalarFunctionImplementation(InternalFunctionBundle.java:127)
	... 72 more
```

The same error appears in the CLI:

```
trino> select json_object(key 'x' value cast(array_agg(json_object(key 'a' value 'a')) as json));
Query 20230313_140645_35313_f2dms failed: java.lang.RuntimeException: java.lang.ClassCastException: class io.trino.operator.aggregation.ParametricAggregation cannot be cast to class io.trino.metadata.SqlScalarFunction (io.trino.operator.aggregation.ParametricAggregation and io.trino.metadata.SqlScalarFunction are in unnamed module of loader 'app')
```

**Comment by kasiafi** [comment]
@lukaseder thanks for reporting the issue. The `ClassCastException` should be fixed via https://github.com/trinodb/trino/pull/16839.

However please note that the query
```
select json_object(key 'x' value cast(array_agg(json_object(key 'a' value 'a')) as json));
```
will still fail due to independent reasons. We cannot cast an array of type JSON resulting from the expression `cast(array_agg(json_object(key 'a' value 'a')) as json)` to `varchar`, and `varchar` is required for the `json_object` function.
This is covered by another issue https://github.com/trinodb/trino/issues/16522, which we might consider addressing in the future.
