### ISSUE TITLE
IllegalArgumentException when running INSERT INTO SELECT after updating to 410

### ISSUE THREAD

**Issue by domnikl** [trinodb/trino#16541]
After updating from Trino 407 to 410 I get this error message and stack trace for some queries which did run fine with 407:

```
java.lang.IllegalArgumentException: Invalid offset or length (4, 65544) in array of length 65544
	at io.airlift.compress.lz4.Lz4Decompressor.verifyRange(Lz4Decompressor.java:108)
	at io.airlift.compress.lz4.Lz4Decompressor.decompress(Lz4Decompressor.java:35)
	at io.trino.execution.buffer.PageDeserializer$SerializedPageInput.decompress(PageDeserializer.java:334)
	at io.trino.execution.buffer.PageDeserializer$SerializedPageInput.ensureReadable(PageDeserializer.java:261)
	at io.trino.execution.buffer.PageDeserializer$SerializedPageInput.readBytes(PageDeserializer.java:247)
	at io.airlift.slice.SliceInput.readBytes(SliceInput.java:222)
	at io.trino.spi.block.MapBlockEncoding.readBlock(MapBlockEncoding.java:106)
	at io.trino.metadata.InternalBlockEncodingSerde.readBlock(InternalBlockEncodingSerde.java:63)
	at io.trino.block.BlockSerdeUtil.readBlock(BlockSerdeUtil.java:43)
	at io.trino.execution.buffer.PagesSerdeUtil.readRawPage(PagesSerdeUtil.java:78)
	at io.trino.execution.buffer.PageDeserializer.deserialize(PageDeserializer.java:80)
	at io.trino.operator.ExchangeOperator.getOutput(ExchangeOperator.java:240)
	at io.trino.operator.Driver.processInternal(Driver.java:396)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:299)
	at io.trino.operator.Driver.tryWithLock(Driver.java:691)
	at io.trino.operator.Driver.process(Driver.java:291)
	at io.trino.operator.Driver.processForDuration(Driver.java:262)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:773)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
	at io.trino.$gen.Trino_410____20230313_141724_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I am using the `hive` connector, reading & writing Parquet files in an `INSERT INTO SELECT` query through dbt. I rolled back to 407 and reran the query resulting in a successful execution.

**Comment by ayush2904** [comment]
We are also facing this error intermittently in the recent version trino (v410) while insert into select query
error is

```
java.lang.IllegalArgumentException: Invalid offset or length (1, 65544) in array of length 65544
	at io.airlift.compress.lz4.Lz4Decompressor.verifyRange(Lz4Decompressor.java:108)
	at io.airlift.compress.lz4.Lz4Decompressor.decompress(Lz4Decompressor.java:35)
	at io.trino.execution.buffer.PageDeserializer$SerializedPageInput.decompress(PageDeserializer.java:334)
	at io.trino.execution.buffer.PageDeserializer$SerializedPageInput.ensureReadable(PageDeserializer.java:261)
	at io.trino.execution.buffer.PageDeserializer$SerializedPageInput.read(PageDeserializer.java:215)
	at java.base/java.io.InputStream.readNBytes(InputStream.java:409)
	at io.trino.spi.block.EncoderUtil.retrieveNullBits(EncoderUtil.java:120)
	at io.trino.spi.block.EncoderUtil.decodeNullBits(EncoderUtil.java:79)
	at io.trino.spi.block.VariableWidthBlockEncoding.readBlock(VariableWidthBlockEncoding.java:85)
	at io.trino.metadata.InternalBlockEncodingSerde.readBlock(InternalBlockEncodingSerde.java:63)
	at io.trino.spi.block.DictionaryBlockEncoding.readBlock(DictionaryBlockEncoding.java:69)
	at io.trino.metadata.InternalBlockEncodingSerde.readBlock(InternalBlockEncodingSerde.java:63)
	at io.trino.block.BlockSerdeUtil.readBlock(BlockSerdeUtil.java:43)
	at io.trino.execution.buffer.PagesSerdeUtil.readRawPage(PagesSerdeUtil.java:78)
	at io.trino.execution.buffer.PageDeserializer.deserialize(PageDeserializer.java:80)
	at io.trino.operator.ExchangeOperator.getOutput(ExchangeOperator.java:240)
	at io.trino.operator.Driver.processInternal(Driver.java:396)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:299)
	at io.trino.operator.Driver.tryWithLock(Driver.java:691)
	at io.trino.operator.Driver.process(Driver.java:291)
	at io.trino.operator.Driver.processForDuration(Driver.java:262)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:773)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
	at io.trino.$gen.Trino_410____20230314_162120_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
 Error is regarding invalid offset or length, which is coming from src/main/java/io/trino/execution/buffer/PageDeserializer.java  class.
 please help us to permanently fix that.
also when i checked the diff from 406 for this class (for few other class too)
` private static final int INSTANCE_SIZE = toIntExact(ClassLayout.parseClass(SerializedPageInput.class).instanceSize());`
is been replaced with
` private static final int INSTANCE_SIZE = instanceSize(SerializedPageInput.class);`
can this be a possible reason ?
suggest some workaround if possible

**Comment by losipiuk** [comment]
@dain does it relate to your recent Aircompressor changes?

**Comment by losipiuk** [comment]
The root cause (range assertions) come from https://github.com/airlift/aircompressor/commit/127b7f3c6330e6cc595f10648b68a197974b50bf - which were pulled to Trino with https://github.com/trinodb/trino/pull/16374/commits/1f6e20424b02b61e68642b32b48b21278a8ef941.

cc: @findepi

**Comment by ayush2904** [comment]
@losipiuk any workaround till this one gets fixed. 

can disabling this property `exchange.compression-enabled` resolve this one.

**Comment by losipiuk** [comment]
> can disabling this property exchange.compression-enabled resolve this one ?.

Yeah - it should
