### ISSUE TITLE
MySQL case-sensitive table names inconsistent behaviour

### ISSUE THREAD

**Issue by davseitsev** [trinodb/trino#16549]
We have upgraded Trino from 367 to 409 and some queries started failing. 
Minified example of failing query:
```sql
SELECT * 
FROM mysql.bd.daily_updating_table 
WHERE srole in (
  SELECT srole
    FROM mysql.bd.daily_updating_table
    WHERE 1=1
      and aid = '11938123193023'
      and day_of_change = current_date - interval '3' day
);
```
It works fine on Trino 367 but fails on version 406 with the exception:
```
io.trino.spi.TrinoException: Table 'bd.DAILY_Updating_Table' doesn't exist
	at io.trino.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:304)
	at io.trino.plugin.jdbc.JdbcRecordCursor.advanceNextPosition(JdbcRecordCursor.java:178)
	at io.trino.$gen.CursorProcessor_20230314_154617_2392.process(Unknown Source)
	at io.trino.operator.ScanFilterAndProjectOperator$RecordCursorToPages.process(ScanFilterAndProjectOperator.java:335)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:182)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils$BlockingProcess.process(WorkProcessorUtils.java:208)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:318)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:360)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:241)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:256)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:146)
	at io.trino.operator.Driver.processInternal(Driver.java:394)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:297)
	at io.trino.operator.Driver.tryWithLock(Driver.java:689)
	at io.trino.operator.Driver.process(Driver.java:289)
	at io.trino.operator.Driver.processForDuration(Driver.java:260)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:773)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
	at io.trino.$gen.Trino_409____20230314_143455_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLException: Table 'bd.DAILY_Updating_Table' doesn't exist
	at io.trino.plugin.jdbc.JdbcRecordCursor.advanceNextPosition(JdbcRecordCursor.java:158)
	... 33 more
Caused by: java.util.concurrent.ExecutionException: java.sql.SQLSyntaxErrorException: Table 'bd.DAILY_Updating_Table' doesn't exist
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at io.trino.plugin.jdbc.JdbcRecordCursor.advanceNextPosition(JdbcRecordCursor.java:154)
	... 33 more
Caused by: java.sql.SQLSyntaxErrorException: Table 'bd.DAILY_Updating_Table' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
	at io.trino.plugin.jdbc.JdbcRecordCursor.lambda$advanceNextPosition$1(JdbcRecordCursor.java:149)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:323)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:69)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:36)
	at io.trino.plugin.jdbc.JdbcRecordCursor.advanceNextPosition(JdbcRecordCursor.java:147)
	... 33 more
```
This one doesn't work as well
```sql
SELECT * 
FROM mysql.bd."DAILY_Updating_Table" 
WHERE srole in (
  SELECT srole
    FROM mysql.bd."DAILY_Updating_Table"
    WHERE 1=1
      and aid = '11938123193023'
      and day_of_change = current_date - interval '3' day
);
```

But simpler queries work fine, e.g.:
This works fine:
```sql
SELECT * 
FROM mysql.bd.daily_updating_table 
WHERE srole in (
  SELECT srole
    FROM mysql.bd.daily_updating_table
    WHERE 1=1
      -- and aid = '11938123193023'
      and day_of_change = current_date - interval '3' day
);
```
This works fine too:
```sql
-- SELECT * 
-- FROM mysql.bd.daily_updating_table 
-- WHERE srole in (
  SELECT srole
    FROM mysql.bd.daily_updating_table
    WHERE 1=1
      and aid = '11938123193023'
      and day_of_change = current_date - interval '3' day
-- );
```
And this is also fine:
```sql
  SELECT * FROM mysql.bd.daily_updating_table LIMIT 1
```

We didn't set config `case-insensitive-name-matching` so default value is `false`. When I changed it to `case-insensitive-name-matching=true` nothing has changed, it still fails. 
And it's interesting that the query works fine on old Trino 367 without the config.

I know that case-sentive support now is limited and we probably don't need it right now, it would be enough to have `case-insensitive-name-matching=true` working.

Let me know if I can provide more information.

**Comment by davseitsev** [comment]
When I disable dynamic filtering it works `set session mysql.dynamic_filtering_enabled =false`

**Comment by davseitsev** [comment]
I figured out the reason for different behavour in test and production databse. The root cause is different MySQL instalations. 
When Trino calls [BaseJdbcClient.getTableHandle](https://github.com/trinodb/trino/blob/c98bb407ea31b858e6c556dc39c6a790f50e6120/plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java#L220) it retrieves table info via `java.sql.Connection.getMetaData().getTables()` here 
https://github.com/trinodb/trino/blob/c98bb407ea31b858e6c556dc39c6a790f50e6120/plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java#L313-L317
Under the hood MySQL Driver runs `SELECT` statement to `information_schema.tables` with LIKE filter: `and table_name like 'DAILY\_Updating\_Table'`. By default `LIKE` is case-insensitive, but when you query `information_schema` its behavour depends on underlying file system, this is described in official docs [10.8.7 Using Collation in INFORMATION_SCHEMA Searches](https://dev.mysql.com/doc/refman/8.0/en/charset-collation-information-schema.html).

In our production cluster `lower-case-table-names=0` but `information_schema.tables` is case-insensitive, so we can query any table using lowercase names with config `case-insensitive-name-matching=false` but it causes problems with dynamic flters.

In Trino tests `information_schema.tables` is case-sensitive and behavior strictly depends on the value of `case-insensitive-name-matching` property.

Trying to reproduce the issue in unit tests.

**Comment by davseitsev** [comment]
We figured out that this issue is related to MySQL server configuration and not Trino issue.
Dynamic filters push-down feature was relased in Trino 393 and now MySQL statement contains WHERE clause with big `IN (...)` block. For some reason our MySQL returns `Table not found` when you run a query with big `IN` filter.
Trino made debugging harder as small change in a query can turn on or off dynamic filter pushdown. In a query plan we can see that dynamic filters are applied but we can't see if they are pushed down or not.

**Comment by hashhar** [comment]
@raunaqmorarka do we have information whether DF got pushed down or not during planning? If so maybe we can expose it in the EXPLAIN plan. It's useful to have in general.

**Comment by raunaqmorarka** [comment]
The dynamic filter symbols can be seen in the explain output after planning but you can't know about the actual dynamic filter used. We are printing the collected dynamic filter as part of EXPLAIN ANALYZE, but the exact DF used by the connector after applying domain compaction is not visible in the explain analyse output.
