### ISSUE TITLE
DoltHub causes column size not present in MySQL connector

### ISSUE THREAD

**Issue by sananguliyev** [trinodb/trino#16575]
I am using MySQL compatible server from DoltHub. When I connect with mysql-cli or some other MySQL clients it works fine but when I try it with Trino I get the error below.  Apparently, it's because of timestamp type but I do not have column which has timestamp column.

```
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: column size not present
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
	at io.trino.collect.cache.EvictableCache.get(EvictableCache.java:114)
	at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:666)
	at io.trino.plugin.jdbc.CachingJdbcClient.getColumns(CachingJdbcClient.java:163)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.getTableSchema(DefaultJdbcMetadata.java:635)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableSchema(ClassLoaderSafeConnectorMetadata.java:247)
	at io.trino.metadata.MetadataManager.getTableSchema(MetadataManager.java:439)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2191)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:479)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:496)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:4439)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2906)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:479)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:496)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:504)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1470)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:479)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:496)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:458)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:258)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:196)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:818)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:149)
	at io.trino.$gen.Trino_408____20230315_231618_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: column size not present
	at io.trino.collect.cache.EmptyCache.get(EmptyCache.java:103)
	at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:666)
	at io.trino.plugin.jdbc.CachingJdbcClient.getColumns(CachingJdbcClient.java:163)
	at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getColumns$3(CachingJdbcClient.java:163)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	... 39 more
Caused by: java.lang.IllegalStateException: column size not present
	at io.trino.plugin.jdbc.JdbcTypeHandle.lambda$getRequiredColumnSize$0(JdbcTypeHandle.java:79)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.trino.plugin.jdbc.JdbcTypeHandle.getRequiredColumnSize(JdbcTypeHandle.java:79)
	at io.trino.plugin.mysql.MySqlClient.toColumnMapping(MySqlClient.java:459)
	at io.trino.plugin.jdbc.BaseJdbcClient.getColumns(BaseJdbcClient.java:317)
	at io.trino.plugin.jdbc.ForwardingJdbcClient.getColumns(ForwardingJdbcClient.java:96)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getColumns$5(StatisticsAwareJdbcClient.java:116)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getColumns(StatisticsAwareJdbcClient.java:116)
	at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getColumns$3(CachingJdbcClient.java:163)
	at io.trino.collect.cache.EmptyCache.get(EmptyCache.java:97)
	... 47 more
```

Example table DDL:
```
CREATE TABLE `orders` (
  `id` bigint NOT NULL,
  `name` text COLLATE utf8mb4_general_ci,
  `email` text COLLATE utf8mb4_general_ci,
  `cancelled_at` datetime,
  `closed_at` datetime,
  `processed_at` datetime,
  `customer_id` bigint NOT NULL,
  `billing_address_id` bigint,
  `shipping_address_id` bigint,
  `currency` text COLLATE utf8mb4_general_ci,
  `total_price` decimal(10,4),
  `subtotal_price` decimal(10,4),
  `total_discounts` decimal(10,4),
  `total_line_items_price` decimal(10,4),
  `taxes_included` tinyint,
  `total_tax` decimal(10,4),
  `tax_lines` json,
  `total_weight` bigint NOT NULL,
  `financial_status` text COLLATE utf8mb4_general_ci,
  `fulfillment_status` text COLLATE utf8mb4_general_ci,
  `token` text COLLATE utf8mb4_general_ci,
  `cart_token` text COLLATE utf8mb4_general_ci,
  `number` bigint NOT NULL,
  `order_number` bigint NOT NULL,
  `note` text COLLATE utf8mb4_general_ci,
  `test` tinyint,
  `browser_ip` text COLLATE utf8mb4_general_ci,
  `buyer_accepts_marketing` tinyint,
  `cancel_reason` text COLLATE utf8mb4_general_ci,
  `note_attributes` json,
  `discount_codes` json,
  `app_id` bigint,
  `customer_locale` text COLLATE utf8mb4_general_ci,
  `landing_site` text COLLATE utf8mb4_general_ci,
  `referring_site` text COLLATE utf8mb4_general_ci,
  `source_name` text COLLATE utf8mb4_general_ci,
  `client_details_accept_language` text COLLATE utf8mb4_general_ci,
  `client_details_browser_height` bigint,
  `client_details_browser_ip` text COLLATE utf8mb4_general_ci,
  `client_details_browser_width` bigint,
  `client_details_session_hash` text COLLATE utf8mb4_general_ci,
  `client_details_user_agent` text COLLATE utf8mb4_general_ci,
  `tags` text COLLATE utf8mb4_general_ci,
  `location_id` bigint,
  `payment_gateway_names` json,
  `processing_method` text COLLATE utf8mb4_general_ci,
  `user_id` bigint,
  `order_status_url` text COLLATE utf8mb4_general_ci,
  `gateway` text COLLATE utf8mb4_general_ci,
  `confirmed` tinyint,
  `total_price_usd` decimal(10,4),
  `checkout_token` text COLLATE utf8mb4_general_ci,
  `reference` text COLLATE utf8mb4_general_ci,
  `source_identifier` text COLLATE utf8mb4_general_ci,
  `source_url` text COLLATE utf8mb4_general_ci,
  `device_id` bigint,
  `phone` text COLLATE utf8mb4_general_ci,
  `landing_site_ref` text COLLATE utf8mb4_general_ci,
  `checkout_id` bigint,
  `contact_email` text COLLATE utf8mb4_general_ci,
  `created_at` datetime NOT NULL,
  `updated_at` datetime,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
```

**Comment by ebyhr** [comment]
> Apparently, it's because of timestamp type but I do not have column which has timestamp column.

The table has `datetime` type. It's `Types.TIMESTAMP` type in JDBC world. 

> I am using MySQL compatible server from DoltHub.

The error message indicates DoltHub isn't **_fully_** compatible with MySQL.

**Comment by sananguliyev** [comment]
@ebyhr thanks for the answer. What is the expected size for datetime or timestamp, so I can patch the engine.

**Comment by ebyhr** [comment]
> What is the expected size for datetime or timestamp

I'm not familiar with DoltHub. Probably, it's 0 as I can't find the precision in their documentation. 

> so I can patch the engine.

Are you going to fix your Trino fork?

**Comment by sananguliyev** [comment]
> Are you going to fix your Trino fork?

No, I am going to fix the dolthub mysql server.

**Comment by ebyhr** [comment]
The expected column size depends on DoltHub. I would recommend asking the community.

**Comment by ebyhr** [comment]
I don't think so. We shouldn't set the default column size unless vanilla MySQL returns an empty value.
