### ISSUE TITLE
testReadMetadataWithRelationsConcurrentModifications flaky on h2

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#16658]
https://github.com/trinodb/trino/actions/runs/4481447910/jobs/7878271274?pr=16651

```
Error:  Tests run: 736, Failures: 1, Errors: 0, Skipped: 169, Time elapsed: 210.403 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.jdbc.TestJdbcConnectorTest.testReadMetadataWithRelationsConcurrentModifications  Time elapsed: 0.877 s  <<< FAILURE!
java.util.concurrent.ExecutionException: io.trino.testing.QueryFailedException: Error listing tables for catalog jdbc: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because "remoteTableName" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.trino.testing.BaseConnectorTest.testReadMetadataWithRelationsConcurrentModifications(BaseConnectorTest.java:1953)
	at io.trino.testing.BaseConnectorTest.testReadMetadataWithRelationsConcurrentModifications(BaseConnectorTest.java:1892)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:256)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:146)
	at io.trino.operator.Driver.processInternal(Driver.java:402)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:305)
	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
	at io.trino.operator.Driver.process(Driver.java:297)
	at io.trino.operator.Driver.processForDuration(Driver.java:268)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:838)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:537)
	at io.trino.$gen.Trino_testversion____20230321_164452_142.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because "remoteTableName" is null
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
	at io.trino.collect.cache.EvictableCache.get(EvictableCache.java:114)
	at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:702)
	at io.trino.plugin.jdbc.CachingJdbcClient.getTableNames(CachingJdbcClient.java:183)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.listTables(DefaultJdbcMetadata.java:670)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.listTables(ClassLoaderSafeConnectorMetadata.java:280)
	at io.trino.metadata.MetadataManager.listTables(MetadataManager.java:516)
	at io.trino.metadata.MetadataListing.doListTables(MetadataListing.java:121)
	at io.trino.metadata.MetadataListing.listTables(MetadataListing.java:112)
	... 41 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because "remoteTableName" is null
	at io.trino.collect.cache.EmptyCache.get(EmptyCache.java:103)
	at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:702)
	at io.trino.plugin.jdbc.CachingJdbcClient.getTableNames(CachingJdbcClient.java:183)
	at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getTableNames$2(CachingJdbcClient.java:183)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	... 51 more
Caused by: java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because "remoteTableName" is null
	at io.trino.plugin.jdbc.mapping.DefaultIdentifierMapping.fromRemoteTableName(DefaultIdentifierMapping.java:41)
	at io.trino.plugin.jdbc.BaseJdbcClient.getTableNames(BaseJdbcClient.java:206)
	at io.trino.plugin.jdbc.ForwardingJdbcClient.getTableNames(ForwardingJdbcClient.java:78)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getTableNames$2(StatisticsAwareJdbcClient.java:98)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getTableNames(StatisticsAwareJdbcClient.java:98)
	at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getTableNames$2(CachingJdbcClient.java:183)
	at io.trino.collect.cache.EmptyCache.get(EmptyCache.java:97)
	... 59 more

2023-03-21T10:48:11.428-0600	INFO	Thread-524	io.airlift.bootstrap.LifeCycleManager	JVM is shutting down, cleaning up
2023-03-21T10:48:11.428-0600	INFO	Thread-524	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
2023-03-21T10:48:11.428-0600	INFO	Thread-524	io.airlift.bootstrap.LifeCycleManager	Life cycle stopped
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestJdbcConnectorTest>BaseConnectorTest.testReadMetadataWithRelationsConcurrentModifications:1892->BaseConnectorTest.testReadMetadataWithRelationsConcurrentModifications:1953 » Execution
[INFO] 
Error:  Tests run: 736, Failures: 1, Errors: 0, Skipped: 169
[INFO] 
[INFO] 
```

**Comment by findepi** [comment]
Apparently on H2, `resultSet.getString("TABLE_NAME")` can be null for some rows within result set returned from   `java.sql.DatabaseMetaData#getTables`. I don't believe null is a valid table name, so I treat this is a H2's bug.
