### ISSUE TITLE
Getting partition location mismatch error for HIVE ACID in newer version(410) of trino 

### ISSUE THREAD

**Issue by ayush2904** [trinodb/trino#16715]
we are getting following error while querying in trino v410. this query works fine on v387. 

```

io.trino.spi.TrinoException: Partition location in OriginalFile 'abfs://clipped.blob.location/entity/extraction_bifrost/1/partition=2022-11-03/partition=2022-11-03/_tmp_b5bb098f-0f06-4236-8cfa-64f1846d1c80/base_0007044' does not match stored location 'abfs://clipped.blob.location/entity/extraction_bifrost/1/partition=2022-11-03/partition=2022-11-03' 	at io.trino.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:312) 	at io.trino.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38) 	at io.trino.$gen.Trino_410____20230321_092729_2.run(Unknown Source) 	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) 	at java.base/java.lang.Thread.run(Thread.java:833) Caused by: java.lang.IllegalArgumentException: Partition location in OriginalFile 'abfs://clipped.blob.location/entity/extraction_bifrost/1/partition=2022-11-03/partition=2022-11-03/_tmp_b5bb098f-0f06-4236-8cfa-64f1846d1c80/base_0007044' does not match stored location 'abfs://clipped.blob.location/entity/extraction_bifrost/1/partition=2022-11-03/partition=2022-11-03/' 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435) 	at io.trino.plugin.hive.AcidInfo$Builder.addOriginalFile(AcidInfo.java:236) 	at io.trino.plugin.hive.BackgroundHiveSplitLoader.getTransactionalSplits(BackgroundHiveSplitLoader.java:723) 	at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:541) 	at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:391) 	at io.trino.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:305) 	... 6 more

--
```

please help us in solving the issue we are using HIVE

**Comment by vinay-kl** [comment]
@electrum this seems to the issue with new Implementation to select the `folders & file` to read hive_acid tables

```
--------------------------------- v387 ---------------------------
AcidUtils.Directory directory = hdfsEnvironment.doAs(hdfsContext.getIdentity(), () -> AcidUtils.getAcidState(
                    path,
                    configuration,
                    validWriteIds.orElseThrow(() -> new IllegalStateException("No validWriteIds present")),
                    false,
                    true));
^^^ Making use of `hive libraries to filter`, this was `ignoring _tmp and other unwanted folders, it was selecting only `base, delta & delete_delta folders` from within the partition location directory

// initialize original files status list if present
            fileStatusOriginalFiles = directory.getOriginalFiles();

            for (HdfsFileStatusWithId hdfsFileStatusWithId : fileStatusOriginalFiles) {
                Path originalFilePath = hdfsFileStatusWithId.getFileStatus().getPath();
                long originalFileLength = hdfsFileStatusWithId.getFileStatus().getLen();
                if (originalFileLength == 0) {
                    continue;
                }
                // Hive requires "original" files of transactional tables to conform to the bucketed tables naming pattern, to match them with delete deltas.
                int bucketId = getRequiredBucketNumber(originalFilePath);
                acidInfoBuilder.addOriginalFile(originalFilePath, originalFileLength, bucketId);
            }


--------------------------------- new version ---------------------------

AcidState acidState = getAcidState(fileSystem, path.toString(), writeIds); 
^^^ current custom Implementation

for (FileEntry entry : acidState.originalFiles()) {
            // Hive requires "original" files of transactional tables to conform to the bucketed tables naming pattern, to match them with delete deltas.
            acidInfoBuilder.addOriginalFile(new Path(entry.location()), entry.length(), getRequiredBucketNumber(entry.location()));
        }
```
