### ISSUE TITLE
'Failed to read Parquet file' found while querying parquet files

### ISSUE THREAD

**Issue by akenO8** [trinodb/trino#16758]
Trino version: 406
When I use the hive connector to query the parquet table written by impala:
```
select * from tmp.tb1;
Query ... failed: Failed to read Parquet file: hdfs://...
```

trino log:
```
io.trino.spi.TrinoException: Failed to read Parquet file: hdfs://...
 ...
Caused by: java.lang.ClassCastException: class io.trino.parquet.DictionaryPage cannot be cast to class io.trino.parquet.DataPageV2 (io.trino.parquet.DictionaryPage and io.trino.parquet.DataPageV2 are in unnamed module of loader io.trino.server.PluginClassLoader @39c437e9)
        at io.trino.parquet.reader.PageReader.readPage(PageReader.java:120)
        at io.trino.parquet.reader.flat.FlatColumnReader.readPage(FlatColumnReader.java:233)
        at io.trino.parquet.reader.flat.FlatColumnReader.readNextPage(FlatColumnReader.java:208)
        at io.trino.parquet.reader.flat.FlatColumnReader.readNullable(FlatColumnReader.java:129)
        at io.trino.parquet.reader.flat.FlatColumnReader.readPrimitive(FlatColumnReader.java:349)
        at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:444)
        at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:529)
        at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:512)
        at io.trino.parquet.reader.ParquetReader.lambda$nextPage$3(ParquetReader.java:274)
        at io.trino.parquet.reader.ParquetBlockFactory$ParquetBlockLoader.load(ParquetBlockFactory.java:72)
        ... 17 more
```

**Comment by raunaqmorarka** [comment]
I believe this should be fixed by https://github.com/trinodb/trino/pull/15942
Please re-open if you still see this issue in 407 or newer release.
