### ISSUE TITLE
Cannot run ANALYZE on table with Array column if partition is empty

### ISSUE THREAD

**Issue by pangyifish** [trinodb/trino#16809]
Trino 406, Hive connector

Table:

```
CREATE TABLE hive.data_lake.table_A (
   idx bigint,
   idy bigint,
   type integer,
   time bigint,
   reason_list array(integer),
   response varchar,
   dt date,
   hour integer
)
WITH (
   external_location = 'xxx',
   format = 'PARQUET',
   partitioned_by = ARRAY['dt','hour']
)

```
SQL:     `ANALYZE data_lake.table_A WITH (PARTITIONS = ARRAY[ARRAY['2023-03-29', '6']])`

ANALYZE query would only fail if the partition is empty. 

Error from Trino UI:

```
java.lang.IllegalArgumentException: unsupported type: array<int>
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreUtil.createMetastoreColumnStatistics(ThriftMetastoreUtil.java:791)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$setPartitionColumnStatistics$22(ThriftHiveMetastore.java:590)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.setPartitionColumnStatistics(ThriftHiveMetastore.java:591)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.updatePartitionStatistics(ThriftHiveMetastore.java:574)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.lambda$updatePartitionStatistics$1(BridgingHiveMetastore.java:136)
	at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:68)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.updatePartitionStatistics(BridgingHiveMetastore.java:136)
	at io.trino.plugin.hive.metastore.ForwardingHiveMetastore.updatePartitionStatistics(ForwardingHiveMetastore.java:108)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.updatePartitionStatistics(CachingHiveMetastore.java:476)
	at io.trino.plugin.hive.HiveMetastoreClosure.updatePartitionStatistics(HiveMetastoreClosure.java:120)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.lambda$setPartitionStatistics$14(SemiTransactionalHiveMetastore.java:500)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1263)
	at io.trino.plugin.hive.HiveMetadata.commit(HiveMetadata.java:3535)
	at io.trino.plugin.hive.HiveTransactionManager.lambda$commit$0(HiveTransactionManager.java:59)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.plugin.hive.HiveTransactionManager.commit(HiveTransactionManager.java:57)
	at io.trino.plugin.hive.HiveConnector.commit(HiveConnector.java:216)
	at io.trino.metadata.CatalogTransaction.commit(CatalogTransaction.java:78)
	at io.trino.metadata.CatalogMetadata.commit(CatalogMetadata.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at io.trino.$gen.Trino_406____20230323_204742_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Kundannitp** [comment]
@pangyifish I'm planning to pick this up. Is it still open.

**Comment by gafeol** [comment]
Yes, still happening on latest versions
