### ISSUE TITLE
Ignite CI is cancelled by 1h limit

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#16882]
https://github.com/trinodb/trino/actions/runs/4608090991/jobs/8149220458?pr=16135#logs

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/4605398754/jobs/8142506436

**Comment by ebyhr** [comment]
cc: @chenjian2664

**Comment by chenjian2664** [comment]
```
java.lang.RuntimeException: Failed to execute statement: DROP TABLE test_unsupported_date_rangexekfbw8uhj
	at io.trino.plugin.ignite.TestingIgniteServer.execute(TestingIgniteServer.java:56)
	at io.trino.testing.sql.TestTable.close(TestTable.java:130)
	at io.trino.plugin.ignite.TestIgniteTypeMapping.testUnsupportedDateRange(TestIgniteTypeMapping.java:332)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLException: Failed to communicate with Ignite cluster.
	at org.apache.ignite.internal.jdbc.thin.JdbcThinConnection.sendRequest(JdbcThinConnection.java:1057)
	at org.apache.ignite.internal.jdbc.thin.JdbcThinStatement.execute0(JdbcThinStatement.java:234)
	at org.apache.ignite.internal.jdbc.thin.JdbcThinStatement.execute(JdbcThinStatement.java:560)
	at io.trino.plugin.ignite.TestingIgniteServer.execute(TestingIgniteServer.java:53)
	... 15 more
Caused by: java.io.IOException: Failed to read incoming message (not enough data).
	at org.apache.ignite.internal.jdbc.thin.JdbcThinTcpIo.read(JdbcThinTcpIo.java:618)
	at org.apache.ignite.internal.jdbc.thin.JdbcThinTcpIo.read(JdbcThinTcpIo.java:596)
	at org.apache.ignite.internal.jdbc.thin.JdbcThinTcpIo.readResponse(JdbcThinTcpIo.java:519)
	at org.apache.ignite.internal.jdbc.thin.JdbcThinTcpIo.sendRequest(JdbcThinTcpIo.java:497)
	at org.apache.ignite.internal.jdbc.thin.JdbcThinConnection.sendRequest(JdbcThinConnection.java:995)
	... 18 more
```
Suspect that the Ignite server is crashed that time, how to get the Ignite server log. I am not able to reproduce the problem on my local using this test(`TestIgniteTypeMapping.testUnsupportedDateRange`)

**Comment by ebyhr** [comment]
> how to get the Ignite server log

There's `GenericContainer#withLogConsumer` method. See #16923 for more details.

**Comment by chenjian2664** [comment]
Thanks! @ebyhr

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4666847568/jobs/8261978471?pr=16955
