### ISSUE TITLE
Flaky `TestDriver.testBrokenOperatorCloseWhileProcessing`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#16925]
```
2023-04-06T21:12:10.767-0600	ERROR	pool-24-thread-2	io.trino.testng.services.ProgressLoggingListener	[TEST FAILURE] io.trino.operator.TestDriver.testBrokenOperatorCloseWhileProcessing; (took: 0.0 seconds)
java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at io.trino.operator.TestDriver.testBrokenOperatorCloseWhileProcessing(TestDriver.java:209)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

https://github.com/trinodb/trino/actions/runs/4633865854/jobs/8199921229

**Comment by findepi** [comment]
```
Error:  Tests run: 8098, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,056.96 s <<< FAILURE! - in TestSuite
Error:  io.trino.operator.TestDriver.testBrokenOperatorCloseWhileProcessing  Time elapsed: 0.034 s  <<< FAILURE!
java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at io.trino.operator.TestDriver.testBrokenOperatorCloseWhileProcessing(TestDriver.java:209)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

cc @pettyjamesm per https://github.com/trinodb/trino/pull/15478 that modified the test recently

**Comment by pettyjamesm** [comment]
Removed race-prone assertions in https://github.com/trinodb/trino/pull/17144
