### ISSUE TITLE
Delta Lake plugin, with Minio storage, while creating hms table - getting error ClassNotFoundException: org.apache.hadoop.fs.s3a.S3AFileSystem not found

### ISSUE THREAD

**Issue by vikram-naik** [trinodb/trino#16942]
I have setup a local environment with below versions:

- Hive Standalone Metastore:  3.1.3
- Trino: using latest docker image as of (9th April 2023)
- Delta Lake: io.delta:delta-core_2.12:2.2.0
- Apache Spark: 3.3.2 ( for data ingestion as delta lake tables)
- minio: io.minio:minio:8.4.3 ( for storing delta lake tables on S3 compliant fs)

While trying to create table in HMS using trino - I'm getting below error. I'm aware which jars needs to be on classpath for providing the class it's looking for (hadoop-aws...), however how do I provide the jar on classpath as there is no such command line argument available to extend the classpath

Please suggest.

`trino:default> create table delta.default.demo_table1( dummy bigint ) with (location='s3a://delta-lake/delta-table1');
Query 20230409_095859_00014_me2kd failed: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
io.trino.spi.TrinoException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createTable(ThriftHiveMetastore.java:976)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.createTable(BridgingHiveMetastore.java:201)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.createTable(CachingHiveMetastore.java:787)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.createTable(CachingHiveMetastore.java:787)
	at io.trino.plugin.deltalake.metastore.HiveMetastoreBackedDeltaLakeMetastore.createTable(HiveMetastoreBackedDeltaLakeMetastore.java:164)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.createTable(DeltaLakeMetadata.java:763)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.createTable(ClassLoaderSafeConnectorMetadata.java:384)
	at io.trino.metadata.MetadataManager.createTable(MetadataManager.java:673)
	at io.trino.execution.CreateTableTask.internalExecute(CreateTableTask.java:285)
	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:122)
	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:88)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:146)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:251)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_412____20230409_094612_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.trino.hive.thrift.metastore.MetaException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:60707)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:60674)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$create_table_result.read(ThriftHiveMetastore.java:60599)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:93)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.recvCreateTable(ThriftHiveMetastore.java:1536)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.createTable(ThriftHiveMetastore.java:1523)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.createTable(ThriftHiveMetastoreClient.java:252)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.lambda$createTable$7(FailureAwareThriftMetastoreClient.java:131)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.runWithHandle(FailureAwareThriftMetastoreClient.java:459)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.createTable(FailureAwareThriftMetastoreClient.java:131)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$createTable$36(ThriftHiveMetastore.java:950)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
	at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createTable(ThriftHiveMetastore.java:948)
	... 17 more
`

**Comment by vikram-naik** [comment]
Post looking at the code - it seems like the exception is being thrown by the HMS ( Hive Standalone Metastore Server).

`                    .run("createTable", stats.getCreateTable().wrap(() -> {
                        try (ThriftMetastoreClient client = createMetastoreClient()) {
                            client.createTable(table);
                        }
                        return null;
                    }));`

**Comment by vikram-naik** [comment]
This issue was resolved by copying below jars to Hive Standalone Metastore `lib` dir.

- org.apache.hadoop:hadoop-aws:3.3.2
- com.amazonaws:aws-java-sdk-bundle:1.11.1026

(jar names with maven co-ordinates.. ) 
Closing the issue as resolved.

**Comment by smartydarren** [comment]
I am trying to use the same version with external meta store and it throws the following error.

2023-09-20 23:29:30 + : mysql
2023-09-20 23:29:30 + SKIP_SCHEMA_INIT=false
2023-09-20 23:29:30 + export HIVE_CONF_DIR=/opt/hive/conf
2023-09-20 23:29:30 + HIVE_CONF_DIR=/opt/hive/conf
2023-09-20 23:29:30 + '[' -d '' ']'
2023-09-20 23:29:30 + export 'HADOOP_CLIENT_OPTS= -Xmx1G '
2023-09-20 23:29:30 + HADOOP_CLIENT_OPTS=' -Xmx1G '
2023-09-20 23:29:30 + [[ false == \f\a\l\s\e ]]
2023-09-20 23:29:30 + initialize_hive
2023-09-20 23:29:30 + /opt/hive/bin/schematool -dbType mysql -initOrUpgradeSchema
2023-09-20 23:29:31 SLF4J: Class path contains multiple SLF4J bindings.
2023-09-20 23:29:31 SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-09-20 23:29:31 SLF4J: Found binding in [jar:file:/opt/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-09-20 23:29:31 SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2023-09-20 23:29:31 SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-09-20 23:29:32 HiveSchemaTool:Parsing failed.  Reason: Missing required option: [-help print this message, -alterCatalog Alter a catalog, requires --catalogLocation and/or --catalogDescription parameter as well, -initSchemaTo Schema initialization to a version, -upgradeSchemaFrom Schema upgrade from a version, -moveDatabase Move a database between catalogs.  Argument is the database name. Requires --fromCatalog and --toCatalog parameters as well, -moveTable Move a table to a different database.  Argument is the table name. Requires --fromCatalog, --toCatalog, --fromDatabase, and --toDatabase  parameters as well., -initSchema Schema initialization, -createCatalog Create a catalog, requires --catalogLocation parameter as well, -upgradeSchema Schema upgrade, -info Show config and schema details, -validate Validate the database]
2023-09-20 23:29:32 + '[' 1 -eq 0 ']'
2023-09-20 23:29:32 + echo 'Schema initialization failed!'
2023-09-20 23:29:32 + exit 1
2023-09-20 23:29:32 usage: schemaTool
2023-09-20 23:29:32  -alterCatalog <arg>                Alter a catalog, requires
2023-09-20 23:29:32                                     --catalogLocation and/or
2023-09-20 23:29:32                                     --catalogDescription parameter as well
2023-09-20 23:29:32  -catalogDescription <arg>          Description of new catalog
2023-09-20 23:29:32  -catalogLocation <arg>             Location of new catalog, required when
2023-09-20 23:29:32                                     adding a catalog
2023-09-20 23:29:32  -createCatalog <arg>               Create a catalog, requires
2023-09-20 23:29:32                                     --catalogLocation parameter as well
2023-09-20 23:29:32  -dbOpts <databaseOpts>             Backend DB specific options
2023-09-20 23:29:32  -dbType <databaseType>             Metastore database type
2023-09-20 23:29:32  -driver <driver>                   driver name for connection
2023-09-20 23:29:32  -dryRun                            list SQL scripts (no execute)
2023-09-20 23:29:32  -fromCatalog <arg>                 Catalog a moving database or table is
2023-09-20 23:29:32                                     coming from.  This is required if you
2023-09-20 23:29:32                                     are moving a database or table.
2023-09-20 23:29:32  -fromDatabase <arg>                Database a moving table is coming
2023-09-20 23:29:32                                     from.  This is required if you are
2023-09-20 23:29:32                                     moving a table.
2023-09-20 23:29:32  -help                              print this message
2023-09-20 23:29:32  -ifNotExists                       If passed then it is not an error to
2023-09-20 23:29:32                                     create an existing catalog
2023-09-20 23:29:32  -info                              Show config and schema details
2023-09-20 23:29:32  -initSchema                        Schema initialization
2023-09-20 23:29:32  -initSchemaTo <initTo>             Schema initialization to a version
2023-09-20 23:29:32  -metaDbType <metaDatabaseType>     Used only if upgrading the system
2023-09-20 23:29:32                                     catalog for hive
2023-09-20 23:29:32  -moveDatabase <arg>                Move a database between catalogs.
2023-09-20 23:29:32                                     Argument is the database name.
2023-09-20 23:29:32                                     Requires --fromCatalog and --toCatalog
2023-09-20 23:29:32                                     parameters as well
2023-09-20 23:29:32  -moveTable <arg>                   Move a table to a different database.
2023-09-20 23:29:32                                     Argument is the table name. Requires
2023-09-20 23:29:32                                     --fromCatalog, --toCatalog,
2023-09-20 23:29:32                                     --fromDatabase, and --toDatabase
2023-09-20 23:29:32                                     parameters as well.
2023-09-20 23:29:32  -passWord <password>               Override config file password
2023-09-20 23:29:32  -servers <serverList>              a comma-separated list of servers used
2023-09-20 23:29:32                                     in location validation in the format
2023-09-20 23:29:32                                     of scheme://authority (e.g.
2023-09-20 23:29:32                                     hdfs://localhost:8000)
2023-09-20 23:29:32  -toCatalog <arg>                   Catalog a moving database or table is
2023-09-20 23:29:32                                     going to.  This is required if you are
2023-09-20 23:29:32                                     moving a database or table.
2023-09-20 23:29:32  -toDatabase <arg>                  Database a moving table is going to.
2023-09-20 23:29:32                                     This is required if you are moving a
2023-09-20 23:29:32                                     table.
2023-09-20 23:29:32  -upgradeSchema                     Schema upgrade
2023-09-20 23:29:32  -upgradeSchemaFrom <upgradeFrom>   Schema upgrade from a version
2023-09-20 23:29:32  -url <url>                         connection url to the database
2023-09-20 23:29:32  -userName <user>                   Override config file user name
2023-09-20 23:29:32  -validate                          Validate the database
2023-09-20 23:29:32  -verbose                           only print SQL statements
2023-09-20 23:29:32 Schema initialization failed!
