### ISSUE TITLE
Spurious query failure due to concurrent modification during getTopRuleStats

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#16960]
example https://github.com/trinodb/trino/actions/runs/4667094946/jobs/8263103436?pr=16714

```
tests               | 2023-04-11 18:57:48 INFO: FAILURE     /    io.trino.tests.product.TestSqlCancel.cancelCreateTable (Groups: cancel_query) took 2.3 seconds
tests               | 2023-04-11 18:57:48 SEVERE: Failure cause:
tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20230411_131248_00092_rjb26): Index 51 out of bounds for length 51
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:54)
tests               | 	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
tests               | 	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
tests               | 	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
tests               | 	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
tests               | 	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:54)
tests               | 	at io.trino.tests.product.TestSqlCancel.cancelQuery(TestSqlCancel.java:146)
tests               | 	at io.trino.tests.product.TestSqlCancel.runAndCancelQuery(TestSqlCancel.java:124)
tests               | 	at io.trino.tests.product.TestSqlCancel.cancelCreateTable(TestSqlCancel.java:95)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
tests               | 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
tests               | Caused by: java.sql.SQLException: Query failed (#20230411_131248_00092_rjb26): Index 51 out of bounds for length 51
tests               | 	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1943)
tests               | 	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:295)
tests               | 	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:255)
tests               | 	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
tests               | 	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
tests               | 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1855)
tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292)
tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298)
tests               | 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
tests               | 	at io.trino.jdbc.TrinoResultSet$AsyncIterator.lambda$new$1(TrinoResultSet.java:180)
tests               | 	... 5 more
tests               | 	Suppressed: java.lang.Exception: Query: SELECT query_id from system.runtime.queries WHERE query = 'CREATE TABLE cancel_createtable_334256646058 AS SELECT * FROM tpch.sf1.lineitem' and state = 'RUNNING' LIMIT 2
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 		at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:54)
tests               | 		at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
tests               | 		at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
tests               | 		at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
tests               | 		at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
tests               | 		at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 		at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
tests               | 		at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:54)
tests               | 		at io.trino.tests.product.TestSqlCancel.cancelQuery(TestSqlCancel.java:146)
tests               | 		at io.trino.tests.product.TestSqlCancel.runAndCancelQuery(TestSqlCancel.java:124)
tests               | 		at io.trino.tests.product.TestSqlCancel.cancelCreateTable(TestSqlCancel.java:95)
tests               | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 		at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 		at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
tests               | 		at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
tests               | 		... 5 more
tests               | Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 51 out of bounds for length 51
tests               | 	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.accept(SortedOps.java:369)
tests               | 	at java.base/java.util.HashMap$EntrySpliterator.tryAdvance(HashMap.java:1871)
tests               | 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
tests               | 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
tests               | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
tests               | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
tests               | 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
tests               | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
tests               | 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
tests               | 	at io.trino.execution.querystats.PlanOptimizersStatsCollector.getTopRuleStats(PlanOptimizersStatsCollector.java:74)
tests               | 	at io.trino.execution.querystats.PlanOptimizersStatsCollector.getTopRuleStats(PlanOptimizersStatsCollector.java:65)
tests               | 	at io.trino.execution.QueryStateMachine.getQueryStats(QueryStateMachine.java:757)
tests               | 	at io.trino.execution.QueryStateMachine.getQueryInfo(QueryStateMachine.java:487)
tests               | 	at io.trino.execution.QueryStateMachine.updateQueryInfo(QueryStateMachine.java:1193)
tests               | 	at io.trino.execution.SqlQueryExecution.buildQueryInfo(SqlQueryExecution.java:675)
tests               | 	at io.trino.execution.SqlQueryExecution.lambda$getQueryInfo$5(SqlQueryExecution.java:652)
tests               | 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
tests               | 	at io.trino.execution.SqlQueryExecution.getQueryInfo(SqlQueryExecution.java:652)
tests               | 	at java.base/java.util.Optional.map(Optional.java:260)
tests               | 	at io.trino.dispatcher.LocalDispatchQuery.getFullQueryInfo(LocalDispatchQuery.java:269)
tests               | 	at java.base/java.util.Optional.map(Optional.java:260)
tests               | 	at io.trino.dispatcher.DispatchManager.getFullQueryInfo(DispatchManager.java:297)
tests               | 	at io.trino.connector.system.QuerySystemTable.cursor(QuerySystemTable.java:114)
tests               | 	at io.trino.connector.system.SystemPageSourceProvider$1.cursor(SystemPageSourceProvider.java:129)
tests               | 	at io.trino.plugin.base.MappedRecordSet.cursor(MappedRecordSet.java:53)
tests               | 	at io.trino.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
tests               | 	at io.trino.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:108)
tests               | 	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:62)
tests               | 	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:266)
tests               | 	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:194)
tests               | 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:360)
tests               | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
tests               | 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
tests               | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
tests               | 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
tests               | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
tests               | 	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
tests               | 	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:241)
tests               | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
tests               | 	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
tests               | 	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:256)
tests               | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
tests               | 	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:146)
tests               | 	at io.trino.operator.Driver.processInternal(Driver.java:402)
tests               | 	at io.trino.operator.Driver.lambda$process$8(Driver.java:305)
tests               | 	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
tests               | 	at io.trino.operator.Driver.process(Driver.java:297)
tests               | 	at io.trino.operator.Driver.processForDuration(Driver.java:268)
tests               | 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:845)
tests               | 	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
tests               | 	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:537)
tests               | 	at io.trino.$gen.Trino_412_56_gf091c06____20230411_131016_2.run(Unknown Source)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by findepi** [comment]
cc @Dith3r @martint per https://github.com/trinodb/trino/pull/16365
