### ISSUE TITLE
Flaky test TestHashSemiJoinOperator.testSemiJoinMemoryReservationYield

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#16987]
https://github.com/trinodb/trino/actions/runs/4675961675/jobs/8282707687 (https://github.com/trinodb/trino/pull/16970)

```
2023-04-12T03:45:20.036-0600	ERROR	pool-24-thread-2	io.trino.testng.services.ProgressLoggingListener	[TEST FAILURE] io.trino.operator.TestHashSemiJoinOperator.testSemiJoinMemoryReservationYield [bigint]; (took: 0.1 seconds)
java.lang.IllegalArgumentException: Invalid taskId another_query.0.0
	at io.trino.spi.QueryId.checkArgument(QueryId.java:114)
	at io.trino.spi.QueryId.parseDottedId(QueryId.java:103)
	at io.trino.execution.TaskId.getQueryId(TaskId.java:57)
	at io.trino.memory.MemoryPool.reserve(MemoryPool.java:133)
	at io.trino.operator.GroupByHashYieldAssertion.finishOperatorWithYieldingGroupByHash(GroupByHashYieldAssertion.java:108)
	at io.trino.operator.TestHashSemiJoinOperator.testSemiJoinMemoryReservationYield(TestHashSemiJoinOperator.java:241)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

```

**Comment by findepi** [comment]
cc @lukasz-stec @skrzypo987 @sopel39 per https://github.com/trinodb/trino/pull/12336

**Comment by findepi** [comment]
```
java.lang.IllegalArgumentException: Invalid taskId another_query.0.0
	at io.trino.spi.QueryId.checkArgument(QueryId.java:114)
	at io.trino.spi.QueryId.parseDottedId(QueryId.java:103)
	at io.trino.execution.TaskId.getQueryId(TaskId.java:57)
	at io.trino.memory.MemoryPool.reserve(MemoryPool.java:133)
	at io.trino.operator.GroupByHashYieldAssertion.finishOperatorWithYieldingGroupByHash(GroupByHashYieldAssertion.java:108)
	at io.trino.operator.TestHashSemiJoinOperator.testSemiJoinMemoryReservationYield(TestHashSemiJoinOperator.java:241)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by lukasz-stec** [comment]
I would add validation to the TaskId string constructor that it conforms to the required format cc @Dith3r

**Comment by Dith3r** [comment]
`QueryId` is validating arguments, `StageId` adds only integer to queryId, same as `TaskId`.
