### ISSUE TITLE
Flaky test TestBinPackingNodeAllocator.testNoMatchingNodeAvailableTimeoutReset

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#16986]
https://github.com/trinodb/trino/actions/runs/4675961675/jobs/8282707441 (https://github.com/trinodb/trino/pull/16970)

```
2023-04-12T03:43:56.067-0600	ERROR	pool-24-thread-2	io.trino.testng.services.ProgressLoggingListener	[TEST FAILURE] io.trino.execution.scheduler.TestBinPackingNodeAllocator.testNoMatchingNodeAvailableTimeoutReset; (took: 0.0 seconds)
java.lang.AssertionError: node lease acquired expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at io.trino.execution.scheduler.TestBinPackingNodeAllocator.assertNotAcquired(TestBinPackingNodeAllocator.java:678)
	at io.trino.execution.scheduler.TestBinPackingNodeAllocator.testNoMatchingNodeAvailableTimeoutReset(TestBinPackingNodeAllocator.java:385)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestBinPackingNodeAllocator.testNoMatchingNodeAvailableTimeoutReset:385->assertNotAcquired:678 node lease acquired expected [false] but found [true]
[INFO] 
Error:  Tests run: 7996, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
```

**Comment by findepi** [comment]
cc @losipiuk @arhimondr
