### ISSUE TITLE
Multiple X-Forwarded-Proto headers not handled 

### ISSUE THREAD

**Issue by elonazoulay** [trinodb/trino#1699]
We ran into this when using istio and lyft's presto-gateway which both add X-Forwarded-Proto headers:

```java.lang.IllegalArgumentException: The string "https,http" for the URI component SCHEME contains an invalid character, ',', at index 5.
        at org.glassfish.jersey.uri.UriComponent.validate(UriComponent.java:163)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.scheme(JerseyUriBuilder.java:274)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.scheme(JerseyUriBuilder.java:72)
        at io.prestosql.dispatcher.QueuedStatementResource.getQueuedUri(QueuedStatementResource.java:235)
        at io.prestosql.dispatcher.QueuedStatementResource.access$400(QueuedStatementResource.java:86)
        at io.prestosql.dispatcher.QueuedStatementResource$Query.lambda$getNextUri$2(QueuedStatementResource.java:406)
        at java.util.Optional.orElseGet(Optional.java:267)
        at io.prestosql.dispatcher.QueuedStatementResource$Query.getNextUri(QueuedStatementResource.java:406)
        at io.prestosql.dispatcher.QueuedStatementResource$Query.createQueryResults(QueuedStatementResource.java:382)
        at io.prestosql.dispatcher.QueuedStatementResource$Query.getQueryResults(QueuedStatementResource.java:356)
        at io.prestosql.dispatcher.QueuedStatementResource.postStatement(QueuedStatementResource.java:163)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
```

**Comment by hashhar** [comment]
According to https://github.com/trinodb/trino/pull/1696#issuecomment-828352694 this is obsolete.
