### ISSUE TITLE
Cannot query Hudi table 'xxx.yyy'

### ISSUE THREAD

**Issue by uniorder** [trinodb/trino#17008]
Hive version: 3.1.3
Hudi version: 0.13.0
Trino version: 413

Hudi saved categories to hms, when I use trino to query hudi table, get an error: Cannot query Hudi table.

But I can use beeline query this table in hive.

**Comment by ebyhr** [comment]
Could you share the full stacktrace and get the table definition from Hive?

**Comment by uniorder** [comment]
> 

Hello, I changed trino version to 390 than everything are ok.

Full stacktrace on  trino sql-client just show `Cannot query Hudi table`.

Maybe hudi doesn't support trino 413? I have being changed Trino's version to 413 in Hudi's `pom.xml`, build result is well, but not working in trino.

**Comment by ebyhr** [comment]
> Full stacktrace on trino sql-client just show Cannot query Hudi table.

You can get the full stacktrace from webui.

**Comment by spasalkar-uptycs** [comment]
https://github.com/trinodb/trino/blob/adef5f4754eb0edbeed23790d8520ead38ae0ad9/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java#L501-L502

```
io.trino.spi.TrinoException: Cannot query Hudi table 'upt_system.vulnerabilities_data_state_hudi'
	at io.trino.plugin.hive.HiveMetadata.getTableHandle(HiveMetadata.java:502)
	at io.trino.plugin.hive.HiveMetadata.getTableHandle(HiveMetadata.java:338)
	at io.trino.spi.connector.ConnectorMetadata.getTableHandle(ConnectorMetadata.java:123)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableHandle(ClassLoaderSafeConnectorMetadata.java:1086)
	at io.trino.tracing.TracingConnectorMetadata.getTableHandle(TracingConnectorMetadata.java:143)
	at io.trino.metadata.MetadataManager.lambda$getTableHandle$5(MetadataManager.java:283)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at io.trino.metadata.MetadataManager.getTableHandle(MetadataManager.java:277)
	at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1572)
	at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1564)
	at io.trino.tracing.TracingMetadata.getRedirectionAwareTableHandle(TracingMetadata.java:1273)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.getTableHandle(StatementAnalyzer.java:5404)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2182)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:484)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:501)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:4463)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2946)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:484)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:501)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:509)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1466)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:484)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:501)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:463)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:97)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:271)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:206)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:845)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:154)
	at io.trino.$gen.Trino_418____20230630_094611_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by nasireddi** [comment]
We are also facing the same issue after migrating to 411. what is the solution for this? we use hudi 0.10

**Comment by electrum** [comment]
This is expected in newer versions. Please use the Hudi connector instead. You can setup [table redirection](https://trino.io/docs/current/connector/hive.html#table-redirection) to automatically redirect reads for Hudi tables.
