### ISSUE TITLE
iceberg cannot migrate table from hive with timestamp(3) column

### ISSUE THREAD

**Issue by akenO8** [trinodb/trino#17006]
trino version: 413

hive connector:
```
trino:test> show create table test.tb3;
            Create Table            
------------------------------------
 CREATE TABLE hive.test.tb3 (       
    stime timestamp(3),             
    id varchar,                     
    name varchar,                   
    ptime bigint                    
 )                                  
 WITH (                             
    format = 'PARQUET',             
    partitioned_by = ARRAY['ptime'] 
 )                                  
(1 row)
```

iceberg connector:
```
trino> CALL iceberg.system.migrate(schema_name => 'test', table_name => 'tb3');
Query 20230413_033113_00096_dw2md failed: Timestamp precision (3) not supported for Iceberg. Use "timestamp(6)" instead.
```

We plan to migrate part of hive tables to iceberg. 
There are thousands of such tables. (with timestamp(3) column, created by hive/impala)
Is there any solution?

**Comment by yunrougong** [comment]
Is there an estimated time when the issue will be addressed?

**Comment by findinpath** [comment]
Stacktrace for the above mentioned scenario:

```
io.trino.spi.TrinoException: Timestamp precision (3) not supported for Iceberg. Use "timestamp(6)" instead.
	at io.trino.plugin.iceberg.TypeConverter.toIcebergTypeInternal(TypeConverter.java:169)
	at io.trino.plugin.iceberg.TypeConverter.toIcebergTypeForNewColumn(TypeConverter.java:107)
	at io.trino.plugin.iceberg.procedure.MigrateProcedure.toIcebergType(MigrateProcedure.java:327)
	at io.trino.plugin.iceberg.procedure.MigrateProcedure.toIcebergSchema(MigrateProcedure.java:309)
	at io.trino.plugin.iceberg.procedure.MigrateProcedure.doMigrate(MigrateProcedure.java:224)
	at io.trino.plugin.iceberg.procedure.MigrateProcedure.migrate(MigrateProcedure.java:194)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758)
	at io.trino.execution.CallTask.execute(CallTask.java:210)
	at io.trino.execution.CallTask.execute(CallTask.java:70)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:264)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at io.trino.$gen.Trino_435_189_g5fbf6b0____20240110_145307_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
