### ISSUE TITLE
Flaky test TestHiveFileFormats.testParquetPageSourceGzip

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#17021]
```
Error:  Tests run: 3807, Failures: 1, Errors: 0, Skipped: 152, Time elapsed: 2,534.667 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.hive.TestHiveFileFormats.testParquetPageSourceGzip[0, 0](1)  Time elapsed: 0.025 s  <<< FAILURE!
java.lang.IllegalArgumentException: maxCapacityHint can't be less than initialSlabSize 1024 100
	at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:57)
	at org.apache.parquet.bytes.CapacityByteArrayOutputStream.<init>(CapacityByteArrayOutputStream.java:153)
	at org.apache.parquet.column.values.plain.PlainValuesWriter.<init>(PlainValuesWriter.java:47)
	at org.apache.parquet.column.values.factory.DefaultV1ValuesWriterFactory.getFloatValuesWriter(DefaultV1ValuesWriterFactory.java:118)
	at org.apache.parquet.column.values.factory.DefaultV1ValuesWriterFactory.newValuesWriter(DefaultV1ValuesWriterFactory.java:67)
	at org.apache.parquet.column.values.factory.DefaultValuesWriterFactory.newValuesWriter(DefaultValuesWriterFactory.java:52)
	at org.apache.parquet.column.ParquetProperties.newValuesWriter(ParquetProperties.java:163)
	at org.apache.parquet.column.impl.ColumnWriterBase.<init>(ColumnWriterBase.java:83)
	at org.apache.parquet.column.impl.ColumnWriterV1.<init>(ColumnWriterV1.java:43)
	at org.apache.parquet.column.impl.ColumnWriteStoreV1.createColumnWriter(ColumnWriteStoreV1.java:50)
	at org.apache.parquet.column.impl.ColumnWriteStoreBase.<init>(ColumnWriteStoreBase.java:125)
	at org.apache.parquet.column.impl.ColumnWriteStoreV1.<init>(ColumnWriteStoreV1.java:44)
	at org.apache.parquet.column.ParquetProperties.newColumnWriteStore(ParquetProperties.java:216)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:116)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:101)
	at org.apache.parquet.hadoop.ParquetRecordWriter.<init>(ParquetRecordWriter.java:152)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:501)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:430)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:425)
	at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.<init>(ParquetRecordWriterWrapper.java:70)
	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getParquerRecordWriterWrapper(MapredParquetOutputFormat.java:137)
	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getHiveRecordWriter(MapredParquetOutputFormat.java:126)
	at io.trino.plugin.hive.AbstractTestHiveFileFormats.createTestFileHive(AbstractTestHiveFileFormats.java:634)
	at io.trino.plugin.hive.TestHiveFileFormats$FileFormatAssertion.assertRead(TestHiveFileFormats.java:1391)
	at io.trino.plugin.hive.TestHiveFileFormats$FileFormatAssertion.isReadableByPageSource(TestHiveFileFormats.java:1331)
	at io.trino.plugin.hive.TestHiveFileFormats.testParquetPageSourceGzip(TestHiveFileFormats.java:515)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

```

**Comment by findepi** [comment]
similar to https://github.com/trinodb/trino/issues/6193
