### ISSUE TITLE
Flaky test TestBigQueryAvroConnectorTest.testInsertRowConcurrently

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#17033]
https://github.com/trinodb/trino/actions/runs/4689111661/jobs/8314827871?pr=16885

```
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:  io.trino.plugin.bigquery.TestBigQueryAvroConnectorTest.testInsertRowConcurrently
[INFO]   Run 1: PASS
Error:    Run 2: TestBigQueryAvroConnectorTest>BaseConnectorTest.testInsertRowConcurrently:4440->BaseConnectorTest.lambda$testInsertRowConcurrently$55:4437->BaseConnectorTest.lambda$testInsertRowConcurrently$54:4437 » Runtime
Error:    Run 3: TestBigQueryAvroConnectorTest>BaseConnectorTest.testInsertRowConcurrently:4440->BaseConnectorTest.lambda$testInsertRowConcurrently$55:4437->BaseConnectorTest.lambda$testInsertRowConcurrently$54:4437 » Runtime
[INFO]   Run 4: PASS
[INFO] 
[INFO] 
Error:  Tests run: 553, Failures: 1, Errors: 0, Skipped: 165
```

```
Error:  Tests run: 556, Failures: 2, Errors: 0, Skipped: 165, Time elapsed: 2,060.655 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.bigquery.TestBigQueryAvroConnectorTest.testInsertRowConcurrently  Time elapsed: 15.806 s  <<< FAILURE!
java.lang.RuntimeException: Wait timed out
	at io.trino.testing.BaseConnectorTest.lambda$testInsertRowConcurrently$54(BaseConnectorTest.java:4437)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.trino.testing.BaseConnectorTest.lambda$testInsertRowConcurrently$55(BaseConnectorTest.java:4437)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.testing.BaseConnectorTest.testInsertRowConcurrently(BaseConnectorTest.java:4440)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Error:  io.trino.plugin.bigquery.TestBigQueryAvroConnectorTest.testInsertRowConcurrently  Time elapsed: 12.674 s  <<< FAILURE!
java.lang.RuntimeException: Wait timed out
	at io.trino.testing.BaseConnectorTest.lambda$testInsertRowConcurrently$54(BaseConnectorTest.java:4437)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.trino.testing.BaseConnectorTest.lambda$testInsertRowConcurrently$55(BaseConnectorTest.java:4437)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.testing.BaseConnectorTest.testInsertRowConcurrently(BaseConnectorTest.java:4440)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4719559108/jobs/8371088411?pr=16825

```
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:  io.trino.plugin.bigquery.TestBigQueryAvroConnectorTest.testInsertRowConcurrently
[INFO]   Run 1: PASS
[INFO]   Run 2: PASS
Error:    Run 3: TestBigQueryAvroConnectorTest>BaseConnectorTest.testInsertRowConcurrently:4426->BaseConnectorTest.lambda$testInsertRowConcurrently$52:4423->BaseConnectorTest.lambda$testInsertRowConcurrently$51:4423 » Runtime
[INFO]   Run 4: PASS
[INFO] 
[INFO] 
```
