### ISSUE TITLE
Potential "Self-suppression not permitted" failure when writing Iceberg table metadata

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#17052]
https://github.com/trinodb/trino/actions/runs/4700059557/jobs/8338918038?pr=17031

```
presto-master       | 2023-04-15T04:04:48.705+0545	ERROR	stage-scheduler	io.trino.execution.StageStateMachine	Stage 20230414_221947_00180_3xg63.1 failed
presto-master       | java.lang.IllegalArgumentException: Self-suppression not permitted
presto-master       | 	at java.base/java.lang.Throwable.addSuppressed(Throwable.java:1072)
presto-master       | 	at org.apache.iceberg.TableMetadataParser.$closeResource(TableMetadataParser.java:132)
presto-master       | 	at org.apache.iceberg.TableMetadataParser.internalWrite(TableMetadataParser.java:132)
presto-master       | 	at org.apache.iceberg.TableMetadataParser.write(TableMetadataParser.java:119)
presto-master       | 	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.writeNewMetadata(AbstractIcebergTableOperations.java:217)
presto-master       | 	at io.trino.plugin.iceberg.catalog.hms.HiveMetastoreTableOperations.commitToExistingTable(HiveMetastoreTableOperations.java:66)
presto-master       | 	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.commit(AbstractIcebergTableOperations.java:163)
presto-master       | 	at org.apache.iceberg.BaseTransaction.lambda$commitSimpleTransaction$5(BaseTransaction.java:403)
presto-master       | 	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:402)
presto-master       | 	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:212)
presto-master       | 	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
presto-master       | 	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:189)
presto-master       | 	at org.apache.iceberg.BaseTransaction.commitSimpleTransaction(BaseTransaction.java:394)
presto-master       | 	at org.apache.iceberg.BaseTransaction.commitTransaction(BaseTransaction.java:277)
presto-master       | 	at io.trino.plugin.iceberg.IcebergMetadata.finishWrite(IcebergMetadata.java:2148)
presto-master       | 	at io.trino.plugin.iceberg.IcebergMetadata.finishMerge(IcebergMetadata.java:1996)
presto-master       | 	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishMerge(ClassLoaderSafeConnectorMetadata.java:1062)
presto-master       | 	at io.trino.metadata.MetadataManager.finishMerge(MetadataManager.java:1073)
presto-master       | 	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$4(LocalExecutionPlanner.java:4151)
presto-master       | 	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
presto-master       | 	at io.trino.operator.Driver.processInternal(Driver.java:402)
presto-master       | 	at io.trino.operator.Driver.lambda$process$8(Driver.java:305)
presto-master       | 	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
presto-master       | 	at io.trino.operator.Driver.process(Driver.java:297)
presto-master       | 	at io.trino.operator.Driver.processForDuration(Driver.java:268)
presto-master       | 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:845)
presto-master       | 	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
presto-master       | 	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:537)
presto-master       | 	at io.trino.$gen.Trino_413_30_g7cc1c3d____20230414_221733_2.run(Unknown Source)
presto-master       | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
presto-master       | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
presto-master       | 	at java.base/java.lang.Thread.run(Thread.java:833)
presto-master       | Caused by: org.apache.hadoop.ipc.RemoteException: File /user/hive/warehouse/test_print_explain_analyze-9e4d7eb8bf4349d290576a5c1abc13f8/metadata/00004-19ab8454-fd00-49b6-b62a-8d2a9222dd17.metadata.json could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and no node(s) are excluded in this operation.
presto-master       | 	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2121)
presto-master       | 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:286)
presto-master       | 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2706)
presto-master       | 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:875)
presto-master       | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:561)
presto-master       | 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
presto-master       | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:524)
presto-master       | 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
presto-master       | 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:876)
presto-master       | 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:822)
presto-master       | 	at java.security.AccessController.doPrivileged(Native Method)
presto-master       | 	at javax.security.auth.Subject.doAs(Subject.java:422)
presto-master       | 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
presto-master       | 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2682)
presto-master       | 
presto-master       | 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1511)
presto-master       | 	at org.apache.hadoop.ipc.Client.call(Client.java:1457)
presto-master       | 	at org.apache.hadoop.ipc.Client.call(Client.java:1367)
presto-master       | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
presto-master       | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
presto-master       | 	at jdk.proxy6/jdk.proxy6.$Proxy471.addBlock(Unknown Source)
presto-master       | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:513)
presto-master       | 	at jdk.internal.reflect.GeneratedMethodAccessor770.invoke(Unknown Source)
presto-master       | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
presto-master       | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
presto-master       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
presto-master       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
presto-master       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
presto-master       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
presto-master       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
presto-master       | 	at jdk.proxy6/jdk.proxy6.$Proxy472.addBlock(Unknown Source)
presto-master       | 	at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1081)
presto-master       | 	at org.apache.hadoop.hdfs.DataStreamer.locateFollowingBlock(DataStreamer.java:1865)
presto-master       | 	at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1668)
presto-master       | 	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:716)
presto-master       | 
presto-master       | 
tests               | 2023-04-15 04:04:48 INFO: not retrying; @Flaky annotation not present
tests               | 2023-04-15 04:04:48 INFO: FAILURE     /    io.trino.tests.product.cli.TestTrinoCli.shouldPrintExplainAnalyzePlan (Groups: cli) took 4.4 seconds
tests               | 2023-04-15 04:04:48 SEVERE: Failure cause:
tests               | java.lang.AssertionError: 
tests               | Expecting ArrayList:
tests               |   ["",
tests               |     "Query 20230414_221947_00180_3xg63 [RUNNING] i[1 728B 577B] o[1 728B 577B] splits[0/6/5]",
tests               |     "Query 20230414_221947_00180_3xg63, FAILED, 1 node",
tests               |     "Splits: 11 total, 5 done (45.45%)",
tests               |     "1.30 [1 rows, 728B] [0 rows/s, 559B/s]",
tests               |     "",
tests               |     "Query 20230414_221947_00180_3xg63 failed: Self-suppression not permitted"]
tests               | to contain:
tests               |   ["UPDATE", "Query Plan"]
tests               | but could not find the following element(s):
tests               |   ["UPDATE", "Query Plan"]
tests               | 
tests               | 	at io.trino.tests.product.cli.TestTrinoCli.shouldPrintExplainAnalyzePlan(TestTrinoCli.java:424)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
tests               | 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
tests               | 

```

similar to https://github.com/trinodb/trino/issues/3326, but different code place.

**Comment by findinpath** [comment]
```
presto-master       | 2024-01-11T03:36:47.189+0545	ERROR	stage-scheduler	io.trino.execution.StageStateMachine	Stage 20240110_215146_00029_v5i9z.2 failed
presto-master       | io.trino.spi.TrinoException: Error committing write parquet to Hive
presto-master       | 	at io.trino.plugin.hive.parquet.ParquetFileWriter.commit(ParquetFileWriter.java:159)
presto-master       | 	at io.trino.plugin.iceberg.IcebergParquetFileWriter.commit(IcebergParquetFileWriter.java:114)
presto-master       | 	at io.trino.plugin.iceberg.IcebergPageSink.closeWriter(IcebergPageSink.java:412)
presto-master       | 	at io.trino.plugin.iceberg.IcebergPageSink.finish(IcebergPageSink.java:227)
presto-master       | 	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:84)
presto-master       | 	at io.trino.operator.TableWriterOperator.finish(TableWriterOperator.java:237)
presto-master       | 	at io.trino.operator.Driver.processInternal(Driver.java:416)
presto-master       | 	at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
presto-master       | 	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
presto-master       | 	at io.trino.operator.Driver.process(Driver.java:293)
presto-master       | 	at io.trino.operator.Driver.processForDuration(Driver.java:264)
presto-master       | 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
presto-master       | 	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
presto-master       | 	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
presto-master       | 	at io.trino.$gen.Trino_435_198_g7877429____20240110_215038_2.run(Unknown Source)
presto-master       | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
presto-master       | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
presto-master       | 	at java.base/java.lang.Thread.run(Thread.java:1583)
presto-master       | Caused by: org.apache.hadoop.ipc.RemoteException: File /user/hive/warehouse/test_print_explain_analyze-c0e062fdda1f4e35a05eab848de5ad8c/data/20240110_215146_00029_v5i9z-86cc79c7-67d1-4960-a532-1f6340e5b700.parquet could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and no node(s) are excluded in this operation.
presto-master       | 	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2121)
presto-master       | 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:286)
presto-master       | 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2706)
presto-master       | 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:875)
presto-master       | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:561)
presto-master       | 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
presto-master       | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:524)
presto-master       | 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
presto-master       | 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:876)
presto-master       | 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:822)
presto-master       | 	at java.security.AccessController.doPrivileged(Native Method)
presto-master       | 	at javax.security.auth.Subject.doAs(Subject.java:422)
presto-master       | 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
presto-master       | 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2682)
presto-master       | 
presto-master       | 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1584)
presto-master       | 	at org.apache.hadoop.ipc.Client.call(Client.java:1530)
presto-master       | 	at org.apache.hadoop.ipc.Client.call(Client.java:1427)
presto-master       | 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:258)
presto-master       | 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:139)
presto-master       | 	at jdk.proxy16/jdk.proxy16.$Proxy627.addBlock(Unknown Source)
presto-master       | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:531)
presto-master       | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
presto-master       | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
presto-master       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:433)
presto-master       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:166)
presto-master       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:158)
presto-master       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:96)
presto-master       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:362)
presto-master       | 	at jdk.proxy16/jdk.proxy16.$Proxy628.addBlock(Unknown Source)
presto-master       | 	at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1088)
presto-master       | 	at org.apache.hadoop.hdfs.DataStreamer.locateFollowingBlock(DataStreamer.java:1915)
presto-master       | 	at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1717)
presto-master       | 	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:713)
presto-master       | 
presto-master       | 
tests               | 2024-01-11 03:36:47 INFO: not retrying; @Flaky annotation not present
tests               | 2024-01-11 03:36:47 INFO: FAILURE     /    io.trino.tests.product.cli.TestTrinoCli.shouldPrintExplainAnalyzePlan (Groups: cli) took 4.4 seconds
tests               | 2024-01-11 03:36:47 SEVERE: Failure cause:
tests               | java.lang.AssertionError: 
tests               | Expecting ArrayList:
tests               |   ["",
tests               |     "Query 20240110_215146_00029_v5i9z, FAILED, 1 node",
tests               |     "Splits: 11 total, 1 done (9.09%)",
tests               |     "0.39 [0 rows, 0B] [0 rows/s, 0B/s]",
tests               |     "",
tests               |     "Query 20240110_215146_00029_v5i9z failed: Error committing write parquet to Hive"]
tests               | to contain:
tests               |   ["INSERT", "Query Plan"]
tests               | but could not find the following element(s):
tests               |   ["INSERT", "Query Plan"]
```

https://github.com/trinodb/trino/actions/runs/7479939271/job/20359673482
