### ISSUE TITLE
Flaky test TestDeltaLakeCheckConstraintCompatibility.testCheckConstraintCompatibility: Communication link failure

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#17058]
https://github.com/trinodb/trino/actions/runs/4699807665/jobs/8338137634?pr=16825

```
tests               | 2023-04-15 01:59:52 INFO: FAILURE     /    io.trino.tests.product.deltalake.TestDeltaLakeCheckConstraintCompatibility.testCheckConstraintCompatibility [a INT, b INT, a = b + 1, 2, 1, 2|1|, 2, 2] (Groups: profile_specific_tests, delta-lake-databricks, delta-lake-oss, delta-lake-exclude-73) took 2 minutes and 11 seconds
tests               | 2023-04-15 01:59:52 SEVERE: Failure cause:
tests               | java.lang.RuntimeException: java.sql.SQLException: [Databricks][DatabricksJDBCDriver](500593) Communication link failure. Failed to connect to server. Reason: com.databricks.client.jdbc42.internal.apache.http.conn.ConnectTimeoutException: Connect to dbc-e0e33308-33d5.cloud.databricks.com:443 [dbc-e0e33308-33d5.cloud.databricks.com/3.128.237.223] failed: Connection timed out.
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.openConnection(JdbcQueryExecutor.java:63)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:103)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$3.lambda$executeQuery$0(QueryExecutors.java:136)
tests               | 	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
tests               | 	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
tests               | 	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
tests               | 	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
tests               | 	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$3.executeQuery(QueryExecutors.java:136)
tests               | 	at io.trino.tests.product.deltalake.TestDeltaLakeCheckConstraintCompatibility.testCheckConstraintCompatibility(TestDeltaLakeCheckConstraintCompatibility.java:45)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
tests               | Caused by: java.sql.SQLException: [Databricks][DatabricksJDBCDriver](500593) Communication link failure. Failed to connect to server. Reason: com.databricks.client.jdbc42.internal.apache.http.conn.ConnectTimeoutException: Connect to dbc-e0e3[3308](https://github.com/trinodb/trino/actions/runs/4699807665/jobs/8338137634?pr=16825#step:7:3309)-33d5.cloud.databricks.com:443 [dbc-e0e[3330](https://github.com/trinodb/trino/actions/runs/4699807665/jobs/8338137634?pr=16825#step:7:3331)8-33d5.cloud.databricks.com/3.128.237.223] failed: Connection timed out.
tests               | 	at com.databricks.client.hivecommon.api.HS2Client.handleTTransportException(Unknown Source)
tests               | 	at com.databricks.client.spark.jdbc.DowloadableFetchClient.handleTTransportException(Unknown Source)
tests               | 	at com.databricks.client.hivecommon.api.HS2Client.openSession(Unknown Source)
tests               | 	at com.databricks.client.hivecommon.api.HS2Client.<init>(Unknown Source)
tests               | 	at com.databricks.client.spark.jdbc.DowloadableFetchClient.<init>(Unknown Source)
tests               | 	at com.databricks.client.spark.jdbc.DownloadableFetchClientFactory.createClient(Unknown Source)
tests               | 	at com.databricks.client.hivecommon.core.HiveJDBCCommonConnection.connectToServer(Unknown Source)
tests               | 	at com.databricks.client.spark.core.SparkJDBCConnection.connectToServer(Unknown Source)
tests               | 	at com.databricks.client.hivecommon.core.HiveJDBCCommonConnection.establishConnection(Unknown Source)
tests               | 	at com.databricks.client.spark.core.SparkJDBCConnection.establishConnection(Unknown Source)
tests               | 	at com.databricks.client.jdbc.core.LoginTimeoutConnection.connect(Unknown Source)
tests               | 	at com.databricks.client.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
tests               | 	at com.databricks.client.jdbc.common.AbstractDriver.connect(Unknown Source)
tests               | 	at io.trino.tempto.internal.query.NonPoolingJdbcDataSource.getConnection(NonPoolingJdbcDataSource.java:51)
tests               | 	at io.trino.tempto.query.JdbcConnectionsPool.connectionFor(JdbcConnectionsPool.java:37)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.openConnection(JdbcQueryExecutor.java:60)
tests               | 	... 24 more
tests               | Caused by: com.databricks.client.support.exceptions.ErrorException: [Databricks][DatabricksJDBCDriver](500593) Communication link failure. Failed to connect to server. Reason: com.databricks.client.jdbc42.internal.apache.http.conn.ConnectTimeoutException: Connect to dbc-e0e33308-33d5.cloud.databricks.com:443 [dbc-e0e33308-33d5.cloud.databricks.com/3.128.237.223] failed: Connection timed out.
tests               | 	... 40 more
tests               | Caused by: com.databricks.client.jdbc42.internal.apache.thrift.transport.TTransportException: com.databricks.client.jdbc42.internal.apache.http.conn.ConnectTimeoutException: Connect to dbc-e0e33308-33d5.cloud.databricks.com:443 [dbc-e0e33308-33d5.cloud.databricks.com/3.128.237.223] failed: Connection timed out
tests               | 	at com.databricks.client.hivecommon.api.TETHttpClient.flushUsingHttpClient(Unknown Source)
tests               | 	at com.databricks.client.hivecommon.api.TETHttpClient.flush(Unknown Source)
tests               | 	at com.databricks.client.jdbc42.internal.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73)
tests               | 	at com.databricks.client.jdbc42.internal.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
tests               | 	at com.databricks.client.jdbc42.internal.apache.hive.service.rpc.thrift.TCLIService$Client.send_OpenSession(TCLIService.java:147)
tests               | 	at com.databricks.client.hivecommon.api.HS2ClientWrapper.send_OpenSession(Unknown Source)
tests               | 	at com.databricks.client.jdbc42.internal.apache.hive.service.rpc.thrift.TCLIService$Client.OpenSession(TCLIService.java:139)
tests               | 	at com.databricks.client.hivecommon.api.HS2ClientWrapper.callOpenSession(Unknown Source)
tests               | 	at com.databricks.client.hivecommon.api.HS2ClientWrapper.access$1700(Unknown Source)
tests               | 	at com.databricks.client.hivecommon.api.HS2ClientWrapper$18.clientCall(Unknown Source)
tests               | 	at com.databricks.client.hivecommon.api.HS2ClientWrapper$18.clientCall(Unknown Source)
tests               | 	at com.databricks.client.hivecommon.api.HS2ClientWrapper.executeWithRetry(Unknown Source)
tests               | 	at com.databricks.client.hivecommon.api.HS2ClientWrapper.OpenSession(Unknown Source)
tests               | 	... 38 more
tests               | Caused by: com.databricks.client.jdbc42.internal.apache.http.conn.ConnectTimeoutException: Connect to dbc-e0e33308-33d5.cloud.databricks.com:443 [dbc-e0e33308-33d5.cloud.databricks.com/3.128.237.223] failed: Connection timed out
tests               | 	at com.databricks.client.jdbc42.internal.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
tests               | 	at com.databricks.client.jdbc42.internal.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:313)
tests               | 	at com.databricks.client.jdbc42.internal.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
tests               | 	at com.databricks.client.jdbc42.internal.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
tests               | 	at com.databricks.client.jdbc42.internal.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
tests               | 	at com.databricks.client.jdbc42.internal.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
tests               | 	at com.databricks.client.jdbc42.internal.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
tests               | 	at com.databricks.client.jdbc42.internal.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
tests               | 	at com.databricks.client.jdbc42.internal.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
tests               | 	at com.databricks.client.jdbc42.internal.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
tests               | 	at com.databricks.client.jdbc.http.extention.ExtendedHttpClient.execute(Unknown Source)
tests               | 	... 51 more
tests               | Caused by: java.net.ConnectException: Connection timed out
tests               | 	at java.base/sun.nio.ch.Net.connect0(Native Method)
tests               | 	at java.base/sun.nio.ch.Net.connect(Net.java:579)
tests               | 	at java.base/sun.nio.ch.Net.connect(Net.java:568)
tests               | 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
tests               | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
tests               | 	at java.base/java.net.Socket.connect(Socket.java:639)
tests               | 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
tests               | 	at com.databricks.client.jdbc42.internal.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
tests               | 	at com.databricks.client.jdbc42.internal.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
tests               | 	... 61 more
tests               |
```

**Comment by findepi** [comment]
cc @ebyhr

**Comment by findepi** [comment]
no retry -- 

```
tests               | 2023-04-15 01:59:52 WARNING: not retrying; stacktrace does not match pattern '\Q[Databricks][DatabricksJDBCDriver](500593) Communication link failure. Failed to connect to server. Reason: HTTP retry after response received with no Retry-After header, error: HTTP Response code: 503, Error message: Unknown.': [java.lang.RuntimeException: java.sql.SQLException: [Databricks][DatabricksJDBCDriver](500593) Communication link failure. Failed to connect to server. Reason: com.databricks.client.jdbc42.internal.apache.http.conn.ConnectTimeoutException: Connect to dbc-e0e33308-33d5.cloud.databricks.com:443 [dbc-e0e33308-33d5.cloud.databricks.com/3.128.237.223] failed: Connection timed out.
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.openConnection(JdbcQueryExecutor.java:63)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:103)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$3.lambda$executeQuery$0(QueryExecutors.java:136)
tests               | 	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
tests               | 	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
tests               | 	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
tests               | 	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
tests               | 	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$3.executeQuery(QueryExecutors.java:136)
tests               | 	at io.trino.tests.product.deltalake.TestDeltaLakeCheckConstraintCompatibility.testCheckConstraintCompatibility(TestDeltaLakeCheckConstraintCompatibility.java:45)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
tests               | Caused by: java.sql.SQLException: [Databricks][DatabricksJDBCDriver](500593) Communication link failure. Failed to connect to server. Reason: com.databricks.client.jdbc42.internal.apache.http.conn.ConnectTimeoutException: Connect to dbc-e0e33308-33d5.cloud.databricks.com:443 [dbc-e0e33308-33d5.cloud.databricks.com/3.128.237.223] failed: Connection timed out.
```
