### ISSUE TITLE
Failed to get stats from new PostgreSQL server version 

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#17061]
We can reproduce the issue by changing the image version in `TestingPostgreSqlServer` to `postgres:14.2` and then starting the query runner:
```
io.trino.testing.QueryFailedException: Failed fetching statistics for table: tpch.customer tpch.customer columns=[]
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:495)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:488)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:512)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:499)
	at io.trino.testing.QueryAssertions.copyTpchTables(QueryAssertions.java:491)
	at io.trino.plugin.postgresql.PostgreSqlQueryRunner.createPostgreSqlQueryRunner(PostgreSqlQueryRunner.java:81)
	at io.trino.plugin.postgresql.PostgreSqlQueryRunner.createPostgreSqlQueryRunner(PostgreSqlQueryRunner.java:47)
	at io.trino.plugin.postgresql.PostgreSqlQueryRunner.main(PostgreSqlQueryRunner.java:102)
	Suppressed: java.lang.Exception: SQL: SELECT count(*) FROM customer
		at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:499)
		... 7 more
Caused by: io.trino.spi.TrinoException: Failed fetching statistics for table: tpch.customer tpch.customer columns=[]
	at io.trino.plugin.postgresql.PostgreSqlClient.getTableStatistics(PostgreSqlClient.java:903)
	at io.trino.plugin.jdbc.ForwardingJdbcClient.getTableStatistics(ForwardingJdbcClient.java:287)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getTableStatistics$41(StatisticsAwareJdbcClient.java:368)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getTableStatistics(StatisticsAwareJdbcClient.java:368)
	at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getTableStatistics$7(CachingJdbcClient.java:439)
	at io.trino.collect.cache.EmptyCache.get(EmptyCache.java:97)
	at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:749)
	at io.trino.plugin.jdbc.CachingJdbcClient.getTableStatistics(CachingJdbcClient.java:439)
	at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getTableStatistics$7(CachingJdbcClient.java:439)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
	at io.trino.collect.cache.EvictableCache.get(EvictableCache.java:115)
	at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:749)
	at io.trino.plugin.jdbc.CachingJdbcClient.getTableStatistics(CachingJdbcClient.java:439)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.getTableStatistics(DefaultJdbcMetadata.java:1001)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableStatistics(ClassLoaderSafeConnectorMetadata.java:320)
	at io.trino.metadata.MetadataManager.getTableStatistics(MetadataManager.java:462)
	at io.trino.cost.CachingTableStatsProvider.getTableStatistics(CachingTableStatsProvider.java:45)
	at io.trino.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:62)
	at io.trino.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:38)
	at io.trino.cost.SimpleStatsRule.calculate(SimpleStatsRule.java:39)
	at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:85)
	at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:73)
	at io.trino.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:82)
	at io.trino.cost.CachingStatsProvider.getGroupStats(CachingStatsProvider.java:105)
	at io.trino.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:74)
	at io.trino.cost.AggregationStatsRule.doCalculate(AggregationStatsRule.java:67)
	at io.trino.cost.AggregationStatsRule.doCalculate(AggregationStatsRule.java:35)
	at io.trino.cost.SimpleStatsRule.calculate(SimpleStatsRule.java:39)
	at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:85)
	at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:73)
	at io.trino.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:82)
	at io.trino.sql.planner.iterative.rule.Rules.deriveTableStatisticsForPushdown(Rules.java:38)
	at io.trino.sql.planner.iterative.rule.PushAggregationIntoTableScan.pushAggregationIntoTableScan(PushAggregationIntoTableScan.java:237)
	at io.trino.sql.planner.iterative.rule.PushAggregationIntoTableScan.apply(PushAggregationIntoTableScan.java:124)
	at io.trino.sql.planner.iterative.rule.PushAggregationIntoTableScan.apply(PushAggregationIntoTableScan.java:71)
	at io.trino.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:209)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:176)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:139)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:259)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:141)
	at io.trino.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:123)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:253)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:228)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:223)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:473)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:453)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:394)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:251)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20230417_112618_75.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: rowCount must be greater than or equal to 0: -1.0
	at io.trino.spi.statistics.TableStatistics.<init>(TableStatistics.java:43)
	at io.trino.spi.statistics.TableStatistics$Builder.build(TableStatistics.java:118)
	at io.trino.plugin.postgresql.PostgreSqlClient.readTableStatistics(PostgreSqlClient.java:963)
	at io.trino.plugin.postgresql.PostgreSqlClient.getTableStatistics(PostgreSqlClient.java:899)
	... 59 more

```

**Comment by ebyhr** [comment]
cc: @kokosing @wendigo @hashhar

**Comment by wendigo** [comment]
`rowCount must be greater than or equal to 0: -1.0` so the -1.0 is new "no stats" :)?
