### ISSUE TITLE
Compiler failure with regexp_replace inside regexp_replace

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#17082]
From https://trinodb.slack.com/archives/CGB0QHWSW/p1679125686473609

```sql
select CAST(regexp_replace(id, '(.*)(.{4}$)', (x) -> concat(regexp_replace(x[1], '.', 'X'), x[2])) AS varchar) from pg.db.t1;
```

```
io.trino.spi.TrinoException: Compiler failed. Possible reasons include: the query may have too many or too complex expressions, or the underlying tables may have too many columns
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1964)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/trino/$gen/CursorProcessor_20230318_073750_45.project_0(Lio/trino/spi/connector/ConnectorSession;Lio/trino/spi/connector/RecordCursor;Lio/trino/spi/block/BlockBuilder;)V @67: invokedynamic
  Reason:
    Type 'io/airlift/slice/Slice' (current frame, stack[3]) is not assignable to 'io/trino/type/JoniRegexp'
  Current Frame:
    bci: @67
    flags: { }
    locals: { 'io/trino/$gen/CursorProcessor_20230318_073750_45', 'io/trino/spi/connector/ConnectorSession', 'io/trino/spi/connector/RecordCursor', 'io/trino/spi/block/BlockBuilder', integer }
    stack: { 'io/trino/spi/block/BlockBuilder', 'java/lang/Object', 'io/airlift/slice/Slice', 'io/airlift/slice/Slice', 'io/trino/sql/gen/lambda/UnaryFunctionInterface' }
  Bytecode:
    0000000: 0336 042d 2ab4 0076 2c03 b900 7a02 0099
    0000010: 000a 0436 0401 a700 0a2c 03b9 007e 0200
    0000020: 1504 9900 0957 5701 a700 27ba 0083 0000
    0000030: 1504 9900 0a57 5757 01a7 0016 2a2b ba00
    0000040: 9500 00ba 009a 0000 59c7 0006 0436 0415
    0000050: 0499 000d 57b9 00a0 0100 57a7 0015 3a05
    0000060: 3a06 ba00 a600 0019 0619 05b9 00ac 0300
    0000070: b1
  Stackmap Table:
    full_frame(@25,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#4]})
    full_frame(@32,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#4],Object[#114]})
    full_frame(@43,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#4],Object[#114]})
    full_frame(@60,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#4],Object[#114],Object[#114]})
    full_frame(@79,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#114]})
    full_frame(@94,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#114]})
    same_frame(@112)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4956)
	at com.google.common.cache.ForwardingLoadingCache.getUnchecked(ForwardingLoadingCache.java:51)
	at io.trino.sql.gen.ExpressionCompiler.compileCursorProcessor(ExpressionCompiler.java:84)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1929)
	... 79 more
Caused by: java.lang.RuntimeException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/trino/$gen/CursorProcessor_20230318_073750_45.project_0(Lio/trino/spi/connector/ConnectorSession;Lio/trino/spi/connector/RecordCursor;Lio/trino/spi/block/BlockBuilder;)V @67: invokedynamic
  Reason:
    Type 'io/airlift/slice/Slice' (current frame, stack[3]) is not assignable to 'io/trino/type/JoniRegexp'
  Current Frame:
    bci: @67
    flags: { }
    locals: { 'io/trino/$gen/CursorProcessor_20230318_073750_45', 'io/trino/spi/connector/ConnectorSession', 'io/trino/spi/connector/RecordCursor', 'io/trino/spi/block/BlockBuilder', integer }
    stack: { 'io/trino/spi/block/BlockBuilder', 'java/lang/Object', 'io/airlift/slice/Slice', 'io/airlift/slice/Slice', 'io/trino/sql/gen/lambda/UnaryFunctionInterface' }
  Bytecode:
    0000000: 0336 042d 2ab4 0076 2c03 b900 7a02 0099
    0000010: 000a 0436 0401 a700 0a2c 03b9 007e 0200
    0000020: 1504 9900 0957 5701 a700 27ba 0083 0000
    0000030: 1504 9900 0a57 5757 01a7 0016 2a2b ba00
    0000040: 9500 00ba 009a 0000 59c7 0006 0436 0415
    0000050: 0499 000d 57b9 00a0 0100 57a7 0015 3a05
    0000060: 3a06 ba00 a600 0019 0619 05b9 00ac 0300
    0000070: b1
  Stackmap Table:
    full_frame(@25,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#4]})
    full_frame(@32,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#4],Object[#114]})
    full_frame(@43,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#4],Object[#114]})
    full_frame(@60,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#4],Object[#114],Object[#114]})
    full_frame(@79,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#114]})
    full_frame(@94,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#114]})
    same_frame(@112)
	at io.airlift.bytecode.ClassGenerator.defineClasses(ClassGenerator.java:181)
	at io.airlift.bytecode.ClassGenerator.defineClass(ClassGenerator.java:117)
	at io.trino.util.CompilerUtils.defineClass(CompilerUtils.java:63)
	at io.trino.util.CompilerUtils.defineClass(CompilerUtils.java:57)
	at io.trino.sql.gen.ExpressionCompiler.compileProcessor(ExpressionCompiler.java:168)
	at io.trino.sql.gen.ExpressionCompiler.compile(ExpressionCompiler.java:135)
	at io.trino.sql.gen.ExpressionCompiler.lambda$new$0(ExpressionCompiler.java:71)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	... 86 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/trino/$gen/CursorProcessor_20230318_073750_45.project_0(Lio/trino/spi/connector/ConnectorSession;Lio/trino/spi/connector/RecordCursor;Lio/trino/spi/block/BlockBuilder;)V @67: invokedynamic
  Reason:
    Type 'io/airlift/slice/Slice' (current frame, stack[3]) is not assignable to 'io/trino/type/JoniRegexp'
  Current Frame:
    bci: @67
    flags: { }
    locals: { 'io/trino/$gen/CursorProcessor_20230318_073750_45', 'io/trino/spi/connector/ConnectorSession', 'io/trino/spi/connector/RecordCursor', 'io/trino/spi/block/BlockBuilder', integer }
    stack: { 'io/trino/spi/block/BlockBuilder', 'java/lang/Object', 'io/airlift/slice/Slice', 'io/airlift/slice/Slice', 'io/trino/sql/gen/lambda/UnaryFunctionInterface' }
  Bytecode:
    0000000: 0336 042d 2ab4 0076 2c03 b900 7a02 0099
    0000010: 000a 0436 0401 a700 0a2c 03b9 007e 0200
    0000020: 1504 9900 0957 5701 a700 27ba 0083 0000
    0000030: 1504 9900 0a57 5757 01a7 0016 2a2b ba00
    0000040: 9500 00ba 009a 0000 59c7 0006 0436 0415
    0000050: 0499 000d 57b9 00a0 0100 57a7 0015 3a05
    0000060: 3a06 ba00 a600 0019 0619 05b9 00ac 0300
    0000070: b1
  Stackmap Table:
    full_frame(@25,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#4]})
    full_frame(@32,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#4],Object[#114]})
    full_frame(@43,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#4],Object[#114]})
    full_frame(@60,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#4],Object[#114],Object[#114]})
    full_frame(@79,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#114]})
    full_frame(@94,{Object[#2],Object[#66],Object[#25],Object[#156],Integer},{Object[#156],Object[#114]})
    same_frame(@112)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at com.google.common.reflect.Reflection.initialize(Reflection.java:64)
	at io.airlift.bytecode.ClassGenerator.defineClasses(ClassGenerator.java:177)
	... 97 more

**Comment by takezoe** [comment]
This might have been solved by https://github.com/trinodb/trino/pull/20226.

**Comment by hashhar** [comment]
@takezoe Indeed, can no longer reproduce this issue starting from 438.
