### ISSUE TITLE
[Hive S3 security mappings] Getting access denied when using other IAM role that the default

### ISSUE THREAD

**Issue by jpereira431** [trinodb/trino#17126]
Hi,

I am working with Trino in order to develop an appication where Trino is expected to read/write in several different S3 buckets, that are managed by different clients. In order to manage security and segregation of the data in the buckets, we wanted to make use of the S3 security mappings. Here is an example configurations of "security-mapping.json":

```
{
  "mappings": [
    {
      "prefix": "s3://bucket-1/",
      "iamRole": "arn:aws:iam::1234567890:role/bucket-1-rw-access"
    },
    {
      "prefix": "s3://bucket-2/",
      "iamRole": "arn:aws:iam::1234567890:role/bucket-2-rw-access"
    }
  ]
}
```

Furthermore, our Trino cluster is being deployed in a EKS K8s namespace, using the official Trino Helm chart, and as such, we also configured a K8s Service Account for Trino, and attached the apllication's default AWS IAM role to it (this process is described in detail in https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html), like so:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trino-sa
  namespace: my-app-namespace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::1234567890:role/bucket-1-rw-access
```

When performing operations over the first bucket ("s3://bucket-1/"), which matches the default role configured in the K8s service account, everything works fine, meaning I can create, query or drop schemas/tables that point to that bucket.
However, when I try to perform the same operations over the second bucket ( "s3://bucket-2/"), every operation fails with the following error:
```
Query 20230419_162117_00000_jjetw failed: Got exception: java.nio.file.AccessDeniedException s3a://bucket-2/: getFileStatus on s3a://bucket-2/: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 79104EXAMPLEB723; S3 Extended Request ID: IOWQ4fDEXAMPLEQM+ey7N9WgVhSnQ6JEXAMPLEZb7hSQDASK+Jd1vEXAMPLEa3Km; Proxy: null), S3 Extended Request ID: IOWQ4fDEXAMPLEQM+ey7N9WgVhSnQ6JEXAMPLEZb7hSQDASK+Jd1vEXAMPLEa3Km:403 Forbidden
io.trino.spi.TrinoException: Got exception: java.nio.file.AccessDeniedException s3a://bucket-2/: getFileStatus on s3a://bucket-2/: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 79104EXAMPLEB723; S3 Extended Request ID: IOWQ4fDEXAMPLEQM+ey7N9WgVhSnQ6JEXAMPLEZb7hSQDASK+Jd1vEXAMPLEa3Km; Proxy: null), S3 Extended Request ID: IOWQ4fDEXAMPLEQM+ey7N9WgVhSnQ6JEXAMPLEZb7hSQDASK+Jd1vEXAMPLEa3Km:403 Forbidden
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createDatabase(ThriftHiveMetastore.java:866)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.createDatabase(BridgingHiveMetastore.java:160)
	at io.trino.plugin.hive.metastore.ForwardingHiveMetastore.createDatabase(ForwardingHiveMetastore.java:132)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.createDatabase(CachingHiveMetastore.java:526)
	at io.trino.plugin.hive.HiveMetastoreClosure.createDatabase(HiveMetastoreClosure.java:140)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.lambda$createDatabase$3(SemiTransactionalHiveMetastore.java:428)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1263)
	at io.trino.plugin.hive.HiveMetadata.commit(HiveMetadata.java:3535)
	at io.trino.plugin.hive.HiveTransactionManager.lambda$commit$0(HiveTransactionManager.java:59)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.plugin.hive.HiveTransactionManager.commit(HiveTransactionManager.java:57)
	at io.trino.plugin.hive.HiveConnector.commit(HiveConnector.java:216)
	at io.trino.metadata.CatalogTransaction.commit(CatalogTransaction.java:78)
	at io.trino.metadata.CatalogMetadata.commit(CatalogMetadata.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at io.trino.$gen.Trino_406____20230419_160747_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

To debug possible problems with the setup of roles and policies on AWS IAM side, I wrote a small script using the AWS SDK, and, using the same WebIdentityTokenFile that is configured in the Trino pods, I managed to proramatically assume both roles (using STS AssumeRoleWithWebIdentity action), so for now I am ruling out any issue with IAM.

Considering that both roles are created with the same process, and with the current security mapping, shouldn't Trino be able to assume either one of the roles when query the respective S3 buckets?

This issue was reproduced using Trino version 406 Trino Helm chart version 0.10.2 .

Can you tell if and what I am doing wrong with this configuration?

Thanks in advance!

**Comment by kenny291** [comment]
the sane issue with Trino version 418

**Comment by ruschecker** [comment]
I guess I found a reason. Well you've updated config for trino-side with security mapping . Did you updated Hive-site ?

**Comment by PiotrKurnik** [comment]
I can see similar issue in 454
