### ISSUE TITLE
TestFileSystemCache is flaky

### ISSUE THREAD

**Issue by homar** [trinodb/trino#17158]
Got this [here](https://github.com/trinodb/trino/actions/runs/4759636377/jobs/8459128326?pr=16205):
```
2023-04-21T02:54:35.2260637Z java.lang.AssertionError: expected [0] but found [1]
2023-04-21T02:54:35.2261163Z 	at org.testng.Assert.fail(Assert.java:94)
2023-04-21T02:54:35.2261867Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2023-04-21T02:54:35.2262408Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2023-04-21T02:54:35.2263426Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2023-04-21T02:54:35.2263939Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2023-04-21T02:54:35.2264618Z 	at org.testng.Assert.assertEquals(Assert.java:294)
2023-04-21T02:54:35.2265285Z 	at io.trino.hdfs.TestFileSystemCache.testFileSystemCacheConcurrency(TestFileSystemCache.java:116)
2023-04-21T02:54:35.2266237Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-04-21T02:54:35.2266980Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-04-21T02:54:35.2267980Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-04-21T02:54:35.2268660Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-04-21T02:54:35.2269887Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2023-04-21T02:54:35.2270580Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2023-04-21T02:54:35.2271360Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2023-04-21T02:54:35.2271966Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2023-04-21T02:54:35.2272827Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2023-04-21T02:54:35.2273498Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2023-04-21T02:54:35.2274540Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-04-21T02:54:35.2275318Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
``` 

also in the same run got this:
```
2023-04-21T02:54:35.2277142Z [ERROR] io.trino.hdfs.TestFileSystemCache.testFileSystemCacheException  Time elapsed: 0.026 s  <<< FAILURE!
2023-04-21T02:54:35.2280840Z java.lang.AssertionError: expected [11] but found [12]
2023-04-21T02:54:35.2281660Z 	at org.testng.Assert.fail(Assert.java:94)
2023-04-21T02:54:35.2282173Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2023-04-21T02:54:35.2282907Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2023-04-21T02:54:35.2283437Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2023-04-21T02:54:35.2284135Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2023-04-21T02:54:35.2284651Z 	at org.testng.Assert.assertEquals(Assert.java:294)
2023-04-21T02:54:35.2285493Z 	at io.trino.hdfs.TestFileSystemCache.testFileSystemCacheException(TestFileSystemCache.java:92)
2023-04-21T02:54:35.2286238Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-04-21T02:54:35.2287158Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-04-21T02:54:35.2287950Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-04-21T02:54:35.2288836Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-04-21T02:54:35.2289497Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2023-04-21T02:54:35.2290344Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2023-04-21T02:54:35.2290929Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2023-04-21T02:54:35.2291976Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2023-04-21T02:54:35.2331989Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2023-04-21T02:54:35.2332527Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2023-04-21T02:54:35.2333063Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-04-21T02:54:35.2333619Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-04-21T02:54:35.2334030Z 	at java.base/java.lang.Thread.run(Thread.java:833)
```

of course both passed locally several times.

**Comment by findepi** [comment]
```
-04-27T10:10:40.1165523Z [ERROR] io.trino.hdfs.TestFileSystemCache.testFileSystemCacheConcurrency  Time elapsed: 1.499 s  <<< FAILURE!
2023-04-27T10:10:40.1168087Z java.lang.AssertionError: Cache size is non zero expected [0] but found [1]
2023-04-27T10:10:40.1172635Z 	at org.testng.Assert.fail(Assert.java:94)
2023-04-27T10:10:40.1174614Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2023-04-27T10:10:40.1176713Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2023-04-27T10:10:40.1179126Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2023-04-27T10:10:40.1181241Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2023-04-27T10:10:40.1183785Z 	at io.trino.hdfs.TestFileSystemCache.testFileSystemCacheConcurrency(TestFileSystemCache.java:119)
2023-04-27T10:10:40.1188478Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
2023-04-27T10:10:40.1270113Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
2023-04-27T10:10:40.1272873Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2023-04-27T10:10:40.1295474Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2023-04-27T10:10:40.1297540Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2023-04-27T10:10:40.1299628Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2023-04-27T10:10:40.1301892Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2023-04-27T10:10:40.1304876Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2023-04-27T10:10:40.1307251Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2023-04-27T10:10:40.1309673Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2023-04-27T10:10:40.1311771Z 	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by findepi** [comment]
Looks related to https://github.com/trinodb/trino/pull/13243 cc @phd3 @jitheshtr

**Comment by wendigo** [comment]
Another one: https://github.com/trinodb/trino/actions/runs/4935944601/jobs/8822879530?pr=17434

**Comment by wendigo** [comment]
```
2023-05-10T12:55:20.8834275Z [ERROR] Tests run: 124, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.322 s <<< FAILURE! - in TestSuite
2023-05-10T12:55:20.8837811Z [ERROR] io.trino.hdfs.TestFileSystemCache.testFileSystemCacheConcurrency  Time elapsed: 0.842 s  <<< FAILURE!
2023-05-10T12:55:20.8838597Z java.lang.AssertionError: Cache size is non zero expected [0] but found [1]
2023-05-10T12:55:20.8839297Z 	at org.testng.Assert.fail(Assert.java:94)
2023-05-10T12:55:20.8840446Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2023-05-10T12:55:20.8840961Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2023-05-10T12:55:20.8841541Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2023-05-10T12:55:20.8842304Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2023-05-10T12:55:20.8843008Z 	at io.trino.hdfs.TestFileSystemCache.testFileSystemCacheConcurrency(TestFileSystemCache.java:118)
2023-05-10T12:55:20.8843777Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-05-10T12:55:20.8844600Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-05-10T12:55:20.8845386Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-05-10T12:55:20.8846101Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-05-10T12:55:20.8846801Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2023-05-10T12:55:20.8847660Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2023-05-10T12:55:20.8848271Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2023-05-10T12:55:20.8848846Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2023-05-10T12:55:20.8849453Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2023-05-10T12:55:20.8850046Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2023-05-10T12:55:20.8850655Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-05-10T12:55:20.8851296Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-05-10T12:55:20.8851809Z 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/4938776644/jobs/8828897364?pr=17214

```
2023-05-10T21:37:27.0393350Z 
2023-05-10T21:37:27.0484148Z [ERROR] Tests run: 124, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 15.383 s <<< FAILURE! - in TestSuite
2023-05-10T21:37:27.0485144Z [ERROR] io.trino.hdfs.TestFileSystemCache.testFileSystemCacheConcurrency  Time elapsed: 1.029 s  <<< FAILURE!
2023-05-10T21:37:27.0485945Z java.lang.AssertionError: Cache size is non zero expected [0] but found [1]
2023-05-10T21:37:27.0486498Z 	at org.testng.Assert.fail(Assert.java:94)
2023-05-10T21:37:27.0487026Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2023-05-10T21:37:27.0487603Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2023-05-10T21:37:27.0488169Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2023-05-10T21:37:27.0488713Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2023-05-10T21:37:27.0489461Z 	at io.trino.hdfs.TestFileSystemCache.testFileSystemCacheConcurrency(TestFileSystemCache.java:118)
2023-05-10T21:37:27.0490320Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-05-10T21:37:27.0491167Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-05-10T21:37:27.0492105Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-05-10T21:37:27.0492875Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-05-10T21:37:27.0493618Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2023-05-10T21:37:27.0494370Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2023-05-10T21:37:27.0495249Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2023-05-10T21:37:27.0496017Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2023-05-10T21:37:27.0496771Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2023-05-10T21:37:27.0497519Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2023-05-10T21:37:27.0498285Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-05-10T21:37:27.0499188Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-05-10T21:37:27.0499837Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-10T21:37:27.0500136Z 
2023-05-10T21:37:27.3936235Z [INFO] 
2023-05-10T21:37:27.3937599Z [INFO] Results:
2023-05-10T21:37:27.3938418Z [INFO] 
2023-05-10T21:37:27.3939073Z [ERROR] Failures: 
2023-05-10T21:37:27.3942470Z [ERROR]   TestFileSystemCache.testFileSystemCacheConcurrency:118 Cache size is non zero expected [0] but found [1]
2023-05-10T21:37:27.3943246Z [INFO] 
2023-05-10T21:37:27.3944005Z [ERROR] Tests run: 124, Failures: 1, Errors: 0, Skipped: 0
2023-05-10T21:37:27.3944622Z [INFO] 
2023-05-10T21:37:27.3951082Z [INFO] 
```

cc @jitheshtr @phd3

**Comment by jitheshtr** [comment]
As `TrinoFileSystemCache` is a singleton and globally accessible for all hdfs filesystem operations from across all the testing modules concurrently within a JVM, the test `testFileSystemCacheConcurrency()` validation could be interfering with other tests that access the cache. An option to fix this is to move `TestFileSystemCache` module to its own runner in CI. Exploring the same to fix this.

**Comment by homar** [comment]
https://github.com/trinodb/trino/actions/runs/4946649822/jobs/8845013753?pr=16205
```
2023-05-11T13:28:21.5631010Z [ERROR] Tests run: 124, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.773 s <<< FAILURE! - in TestSuite
2023-05-11T13:28:21.5631660Z [ERROR] io.trino.hdfs.TestFileSystemCache.testFileSystemCacheConcurrency  Time elapsed: 0.766 s  <<< FAILURE!
2023-05-11T13:28:21.5632611Z java.lang.AssertionError: Cache size is non zero expected [0] but found [1]
2023-05-11T13:28:21.5632961Z 	at org.testng.Assert.fail(Assert.java:94)
2023-05-11T13:28:21.5633302Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2023-05-11T13:28:21.5633660Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2023-05-11T13:28:21.5634025Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2023-05-11T13:28:21.5634370Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2023-05-11T13:28:21.5634853Z 	at io.trino.hdfs.TestFileSystemCache.testFileSystemCacheConcurrency(TestFileSystemCache.java:118)
2023-05-11T13:28:21.5635407Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-05-11T13:28:21.5636031Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-05-11T13:28:21.5637023Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-05-11T13:28:21.5637577Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-05-11T13:28:21.5638112Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2023-05-11T13:28:21.5638639Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2023-05-11T13:28:21.5639091Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2023-05-11T13:28:21.5639814Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2023-05-11T13:28:21.5640294Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2023-05-11T13:28:21.5640760Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2023-05-11T13:28:21.5641248Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-05-11T13:28:21.5641838Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-05-11T13:28:21.5642240Z 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by wendigo** [comment]
https://github.com/trinodb/trino/actions/runs/4982690046/jobs/8918718712?pr=17507

**Comment by losipiuk** [comment]
https://github.com/trinodb/trino/pull/17517

**Comment by chenjian2664** [comment]
https://github.com/trinodb/trino/actions/runs/5009046912/jobs/8977551409?pr=17196
