### ISSUE TITLE
HdfsEnvironment ExceptionInInitializerError after Trino Upgrade (410 to 414) in LocalQueryRunner

### ISSUE THREAD

**Issue by belen-pruvost** [trinodb/trino#17308]
I'm trying to run an integration test locally from IntelliJ which uses the `io.trino.testing.LocalQueryRunner`. The LocalQueryRunner attempts to create a delta lake catalog, calling `DeltaLakeConnectorFactory.create`.

This issue started happening when I upgraded from trino 410 to trino 414.

Could you please help me figure out how to fix this? 

```
Unable to create injector, see the following errors:

1) [Guice/ErrorInjectingConstructor]: ExceptionInInitializerError
  at HdfsEnvironment.<init>(HdfsEnvironment.java:62)
  at HdfsModule.configure(HdfsModule.java:32)
  at HdfsFileSystemFactory.<init>(HdfsFileSystemFactory.java:33)
      \_ for 1st parameter environment
  at HdfsFileSystemModule.configure(HdfsFileSystemModule.java:32)
      \_ installed by: InternalDeltaLakeConnectorFactory$$Lambda$1193/0x00000008011a6c68 -> HdfsFileSystemModule
  at HdfsFileSystemModule.createFileSystemFactory(HdfsFileSystemModule.java:39)
      \_ for 2nd parameter delegate
  at HdfsFileSystemModule.createFileSystemFactory(HdfsFileSystemModule.java:39)
      \_ installed by: InternalDeltaLakeConnectorFactory$$Lambda$1193/0x00000008011a6c68 -> HdfsFileSystemModule
  at S3NativeTransactionLogSynchronizer.<init>(S3NativeTransactionLogSynchronizer.java:70)
      \_ for 1st parameter fileSystemFactory
  while locating S3NativeTransactionLogSynchronizer
  at DeltaLakeS3Module.configure(DeltaLakeS3Module.java:34)
  while locating TransactionLogSynchronizer annotated with @Element(setName=,uniqueId=31, type=MAPBINDER, keyType=String)

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
Caused by: ExceptionInInitializerError
	at HdfsEnvironment$$FastClassByGuice$$17450493.GUICE$TRAMPOLINE(<generated>)
	at HdfsEnvironment$$FastClassByGuice$$17450493.apply(<generated>)
	at DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at ConstructorInjector.provision(ConstructorInjector.java:114)
	at ConstructorInjector.access$000(ConstructorInjector.java:33)
	at ConstructorInjector$1.call(ConstructorInjector.java:98)
	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at LifeCycleModule.provision(LifeCycleModule.java:54)
	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at ConstructorInjector.construct(ConstructorInjector.java:93)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.access$000(ConstructorInjector.java:33)
	at ConstructorInjector$1.call(ConstructorInjector.java:98)
	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at LifeCycleModule.provision(LifeCycleModule.java:54)
	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at ConstructorInjector.construct(ConstructorInjector.java:93)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ProviderMethod.doProvision(ProviderMethod.java:171)
	at InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at InternalProviderInstanceBindingImpl$CyclicFactory.access$300(InternalProviderInstanceBindingImpl.java:139)
	at InternalProviderInstanceBindingImpl$CyclicFactory$1.call(InternalProviderInstanceBindingImpl.java:169)
	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at LifeCycleModule.provision(LifeCycleModule.java:54)
	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:164)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.access$000(ConstructorInjector.java:33)
	at ConstructorInjector$1.call(ConstructorInjector.java:98)
	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at LifeCycleModule.provision(LifeCycleModule.java:54)
	at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at ConstructorInjector.construct(ConstructorInjector.java:93)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at FactoryProxy.get(FactoryProxy.java:60)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at Guice.createInjector(Guice.java:87)
	at Bootstrap.initialize(Bootstrap.java:270)
	at InternalDeltaLakeConnectorFactory.createConnector(InternalDeltaLakeConnectorFactory.java:120)
	at java.base/NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/Method.invoke(Method.java:568)
	at DeltaLakeConnectorFactory.create(DeltaLakeConnectorFactory.java:58)
	at MyTrinoPlugin$getConnectorFactories$1.create(MyTrinoPlugin.kt)
	at DefaultCatalogFactory.createConnector(DefaultCatalogFactory.java:221)
	at DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:130)
	at LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:45)
	at CoordinatorDynamicCatalogManager.lambda$createCatalog$4(CoordinatorDynamicCatalogManager.java:272)
	at java.base/ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at CoordinatorDynamicCatalogManager.createCatalog(CoordinatorDynamicCatalogManager.java:270)
	at LocalQueryRunner.createCatalog(LocalQueryRunner.java:781)
	at ViewsTestUtilsKt.withQueryRunner(ViewsTestUtils.kt:84)
	at MyTest.basic test(MyTest.kt:25)
	at java.base/NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/Method.invoke(Method.java:568)
	at ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at MethodInvocation.proceed(MethodInvocation.java:60)
	at InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at TimeoutExtension.intercept(TimeoutExtension.java:149)
	at TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at ThrowableCollector.execute(ThrowableCollector.java:73)
	at TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at ThrowableCollector.execute(ThrowableCollector.java:73)
	at NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at Node.around(Node.java:135)
	at NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at ThrowableCollector.execute(ThrowableCollector.java:73)
	at NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/ArrayList.forEach(ArrayList.java:1511)
	at SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at ThrowableCollector.execute(ThrowableCollector.java:73)
	at NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at Node.around(Node.java:135)
	at NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at ThrowableCollector.execute(ThrowableCollector.java:73)
	at NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/ArrayList.forEach(ArrayList.java:1511)
	at SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at ThrowableCollector.execute(ThrowableCollector.java:73)
	at NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at Node.around(Node.java:135)
	at NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at ThrowableCollector.execute(ThrowableCollector.java:73)
	at NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at NodeTestTask.execute(NodeTestTask.java:80)
	at SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at DefaultLauncher.execute(DefaultLauncher.java:114)
	at DefaultLauncher.execute(DefaultLauncher.java:86)
	at DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/Method.invoke(Method.java:568)
	at ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at TestWorker$3.run(TestWorker.java:193)
	at TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at TestWorker.execute(TestWorker.java:100)
	at TestWorker.execute(TestWorker.java:60)
	at ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at GradleWorkerMain.run(GradleWorkerMain.java:69)
	at GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: RuntimeException: failed to load Hadoop native library
	at HadoopNative.requireHadoopNative(HadoopNative.java:59)
	at HdfsEnvironment.<clinit>(HdfsEnvironment.java:39)
	... 164 more
Caused by: NoSuchMethodError: 'boolean NativeCodeLoader.buildSupportsZstd()'
	at ZStandardCodec.checkNativeCodeLoaded(ZStandardCodec.java:64)
	at ZStandardCodec.getDecompressorType(ZStandardCodec.java:211)
	at HadoopNative.loadAllCodecs(HadoopNative.java:72)
	at HadoopNative.requireHadoopNative(HadoopNative.java:53)
	... 165 more
```

**Comment by belen-pruvost** [comment]
Turns out the project on which this IT was defined is a gradle project that couldn't dynamically exclude dependencies excluded on trino's pom files, like [this one](https://github.com/trinodb/trino/blob/414/pom.xml#L1190) for apache hadoop. Explicitly excluding it also on the gradle project solves the problem.
