### ISSUE TITLE
trino-hive tests fail with OutOfMemoryError during TestRubixCaching

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#17412]
https://github.com/trinodb/trino/actions/runs/4925370678/jobs/8800356721?pr=17383

```
] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0:test (default-test) on project trino-hive: 
Error:  
Error:  Please refer to /home/runner/work/trino/trino/plugin/trino-hive/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/home/runner/work/trino/trino/plugin/trino-hive' && '/opt/hostedtoolcache/Java_Zulu_jdk/17.0.7-7/x64/bin/java' '-Duser.timezone=America/Bahia_Banderas' '-Duser.language=en' '-Duser.region=US' '-Dfile.encoding=UTF-8' '-Xmx3g' '-Xms3g' '-XX:+ExitOnOutOfMemoryError' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:-OmitStackTraceInFastThrow' '-XX:G1HeapRegionSize=32M' '-XX:+UnlockDiagnosticVMOptions' '-XX:GCLockerRetryAllocationCount=10' '-XX:-G1UsePreventiveGC' '-jar' '/home/runner/work/trino/trino/plugin/trino-hive/target/surefire/surefirebooter-20230509141123284_6.jar' '/home/runner/work/trino/trino/plugin/trino-hive/target/surefire' '2023-05-09T14-11-23_186-jvmRun1' 'surefire-20230509141123284_4tmp' 'surefire_1-20230509141123284_5tmp'
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 3
Error:  Crashed tests:
Error:  io.trino.plugin.hive.TestHiveConnectorTest
Error:  io.trino.plugin.hive.rubix.TestRubixCaching
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/home/runner/work/trino/trino/plugin/trino-hive' && '/opt/hostedtoolcache/Java_Zulu_jdk/17.0.7-7/x64/bin/java' '-Duser.timezone=America/Bahia_Banderas' '-Duser.language=en' '-Duser.region=US' '-Dfile.encoding=UTF-8' '-Xmx3g' '-Xms3g' '-XX:+ExitOnOutOfMemoryError' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:-OmitStackTraceInFastThrow' '-XX:G1HeapRegionSize=32M' '-XX:+UnlockDiagnosticVMOptions' '-XX:GCLockerRetryAllocationCount=10' '-XX:-G1UsePreventiveGC' '-jar' '/home/runner/work/trino/trino/plugin/trino-hive/target/surefire/surefirebooter-20230509141123284_6.jar' '/home/runner/work/trino/trino/plugin/trino-hive/target/surefire' '2023-05-09T14-11-23_186-jvmRun1' 'surefire-20230509141123284_4tmp' 'surefire_1-20230509141123284_5tmp'
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 3
Error:  Crashed tests:
Error:  io.trino.plugin.hive.TestHiveConnectorTest
Error:  io.trino.plugin.hive.rubix.TestRubixCaching
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1203)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1055)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:871)
Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
Error:  	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
Error:  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
Error:  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
Error:  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:827)
Error:  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:272)
Error:  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:195)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Error:  	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:47)
Error:  	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:156)
Error:  	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
```

**Comment by findepi** [comment]
- `io.trino.plugin.hive.rubix.TestRubixCaching#testLargeFile` doesn't pass with `-Xmx900m`. it's very memory hungry.
- passes with `-Xmx950m`, but not if i add invocationCount (with serial execution). perhaps because there is 3 concurrent reads

<img width="808" alt="image" src="https://github.com/trinodb/trino/assets/144328/e0b552ac-670c-4bab-8bf4-b12b773a6e87">

cc @sopel39
