### ISSUE TITLE
Flaky test TestHiveConnectorTest.testWriterTasksCountLimitPartitionedScaleWritersEnabled

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#17436]
https://github.com/trinodb/trino/actions/runs/4927231279/jobs/8806974752?pr=17411

```
Error:  Tests run: 3806, Failures: 1, Errors: 0, Skipped: 154, Time elapsed: 1,900.504 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.hive.TestHiveConnectorTest.testWriterTasksCountLimitPartitionedScaleWritersEnabled  Time elapsed: 0.677 s  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:284)
	at org.testng.Assert.assertEquals(Assert.java:294)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testLimitWriterTasks(BaseHiveConnectorTest.java:4147)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testWriterTasksCountLimitPartitionedScaleWritersEnabled(BaseHiveConnectorTest.java:4127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestHiveConnectorTest>BaseHiveConnectorTest.testWriterTasksCountLimitPartitionedScaleWritersEnabled:4127->BaseHiveConnectorTest.testLimitWriterTasks:4147 expected [2] but found [4]
[INFO] 
Error:  Tests run: 3806, Failures: 1, Errors: 0, Skipped: 154
[INFO] 
[INFO] ---------------------------------------------------
```

cc @radek-starburst @sopel39 @gaurav8297

**Comment by findepi** [comment]
```
Error:  io.trino.plugin.hive.TestHiveConnectorTest.testWriterTasksCountLimitPartitionedScaleWritersEnabled  Time elapsed: 11.102 s  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:284)
	at org.testng.Assert.assertEquals(Assert.java:294)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testLimitWriterTasks(BaseHiveConnectorTest.java:4152)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testWriterTasksCountLimitPartitionedScaleWritersEnabled(BaseHiveConnectorTest.java:4132)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

cc @sopel39

**Comment by raunaqmorarka** [comment]
fyi @gaurav8297

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/5230972160/jobs/9444857901

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/5530672864/jobs/10093888194?pr=18253

**Comment by findepi** [comment]
@gaurav8297 are you working on this?
per @martint 's https://github.com/trinodb/trino/pull/18202#issuecomment-1629415699 we should remove this test.

**Comment by homar** [comment]
https://github.com/trinodb/trino/actions/runs/5443594095/jobs/9900365476?pr=17928
