### ISSUE TITLE
Trino SQL engine cannot started by kyuubi 1.7.1

### ISSUE THREAD

**Issue by zhifanggao** [trinodb/trino#17476]
Can not start a trino engine with kyuubi 1.7.1
reproduce steps likes this:
1.  setup a trino cluster 

```
root@host-10-19-37-28:/home/puaiuc# kubectl get po
NAME                                        READY   STATUS    RESTARTS   AGE
trino-cluster-coordinator-fcff857bf-42tb2   1/1     Running   0          8m9s
trino-cluster-worker-6cdb755df8-62spz       1/1     Running   0          8m8s
trino-cluster-worker-6cdb755df8-8h2kh       1/1     Running   0          8m8s
root@host-10-19-37-28:/home/puaiuc# kubectl exec -it trino-cluster-coordinator-fcff857bf-42tb2 sh  ^C
root@host-10-19-37-28:/home/puaiuc# kubectl get svc
NAME                TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
trino-cluster-svc   NodePort   10.99.181.92   <none>        8080:31576/TCP   2d23h
root@host-10-19-37-28:/home/puaiuc# kubectl exec -it trino-cluster-coordinator-fcff857bf-42tb2 sh
sh-4.2$ trino --server 10.19.37.28:31576 --catalog hive --schema tpcds_bin_partitioned_orc_20000
trino:tpcds_bin_partitioned_orc_20000> show tables;
         Table
------------------------
 call_center
 catalog_page
 catalog_returns
 catalog_sales
 customer
 customer_address
 customer_demographics
 date_dim
 household_demographics
 income_band
 inventory
 item
 promotion
 reason
 ship_mode
 store
 store_returns
 store_sales
 time_dim
 warehouse
 web_page
 web_returns
 web_sales
 web_site
(24 rows)

Query 20230512_094807_00001_h9zcj, FINISHED, 3 nodes
Splits: 36 total, 36 done (100.00%)
3.18 [24 rows, 1.21KB] [7 rows/s, 390B/s]

trino:tpcds_bin_partitioned_orc_20000>
```

2.  Then I set the `kyuubi.session.engine.trino.connection.url=10.19.37.28:31576` and  `kyuubi.session.engine.trino.connection.catalog=hive` in the kyuubi's conf

3. setup a kyuubi cluster
```
[root@phy-10-19-95-40 ~]# kubectl get po  |grep kyuubi
kyuubi-default-c7c85b8b8-7k7x7                                                                    1/1     Running     0          122m
kyuubi-default-c7c85b8b8-d92bn                                                                    1/1     Running     0          122m
kyuubi-default-c7c85b8b8-q8zdr                                                                    1/1     Running     0          122m
kyuubi-user-spark-sql-ocdp-default-9b15e5a0-1b46-4451-ba03-55dc0273763c-798901880dffc874-driver   1/1     Running     0          6h23m
kyuubi-user-spark-sql-ocdp-default-c3608911-1c84-4c13-bd4f-736f10975e49-0e761f880a4d3221-driver   0/1     Completed   0          23h
[root@phy-10-19-95-40 ~]# kubectl get svc
NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
kyuubi-default                      NodePort    10.105.234.197   <none>        10009:30907/TCP              3d1h
``` 
4. using the kyuubi beeline to start trino sql engine
```
[root@phy-10-19-95-40 apache-kyuubi-1.7.1-bin]# ./bin/beeline -n ocdp -u "jdbc:hive2://10.19.95.40:30907/tpcds_bin_partitioned_orc_20000?kyuubi.engine.type=TRINO;"
Warn: Not find kyuubi environment file /home/gzhifang/1.7.1/apache-kyuubi-1.7.1-bin/conf/kyuubi-env.sh, using default ones...
Connecting to jdbc:hive2://10.19.95.40:30907/tpcds_bin_partitioned_orc_20000?kyuubi.engine.type=TRINO;
2023-05-12 09:27:42.249 INFO org.apache.kyuubi.operation.LaunchEngine: Processing ocdp's query[59cebac4-e820-43e7-8d58-bb9ee7c8343c]: PENDING_STATE -> RUNNING_STATE, statement:
LaunchEngine
2023-05-12 09:27:42.255 INFO org.apache.curator.framework.imps.CuratorFrameworkImpl: Starting
2023-05-12 09:27:42.256 INFO org.apache.zookeeper.ZooKeeper: Initiating client connection, connectString=zk-default-0.zk-default-svc.bigdata1.svc.cluster.local:2181,zk-default-1.zk-default-svc.bigdata1.svc.cluster.local:2181,zk-default-2.zk-default-svc.bigdata1.svc.cluster.local:2181, sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@21f5a49d
2023-05-12 09:27:42.261 INFO org.apache.zookeeper.ClientCnxn: Opening socket connection to server zk-default-2.zk-default-svc.bigdata1.svc.cluster.local/192.162.89.42:2181. Will not attempt to authenticate using SASL (unknown error)
2023-05-12 09:27:42.264 INFO org.apache.zookeeper.ClientCnxn: Socket connection established to zk-default-2.zk-default-svc.bigdata1.svc.cluster.local/192.162.89.42:2181, initiating session
2023-05-12 09:27:42.268 INFO org.apache.zookeeper.ClientCnxn: Session establishment complete on server zk-default-2.zk-default-svc.bigdata1.svc.cluster.local/192.162.89.42:2181, sessionid = 0x300b9c1a3a3002c, negotiated timeout = 40000
2023-05-12 09:27:42.269 INFO org.apache.curator.framework.state.ConnectionStateManager: State change: CONNECTED
2023-05-12 09:27:42.296 INFO org.apache.kyuubi.ha.client.zookeeper.ZookeeperDiscoveryClient: Get service instance:192.170.50.219:44310 and version:1.7.1 under /kyuubi_1.7.1_USER_TRINO/ocdp/default
2023-05-12 09:27:42.351 ERROR org.apache.kyuubi.session.KyuubiSessionImpl: Opening engine [kyuubi_USER_TRINO_ocdp_default_22675aab-747f-4ff1-9622-b24c2d4d590b 192.170.50.219:44310] for ocdp session failed
org.apache.kyuubi.KyuubiSQLException: Illegal character in scheme name at index 0: 10.19.37.28:31576
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69) ~[kyuubi-common_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:73) ~[kyuubi-common_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.session.SessionManager.openSession(SessionManager.scala:119) ~[kyuubi-common_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.service.AbstractBackendService.openSession(AbstractBackendService.scala:45) ~[kyuubi-common_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.service.TFrontendService.getSessionHandle(TFrontendService.scala:181) ~[kyuubi-common_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.service.TFrontendService.OpenSession(TFrontendService.scala:190) ~[kyuubi-common_2.12-1.7.1.jar:1.7.1]
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$OpenSession.getResult(TCLIService.java:1497) ~[hive-service-rpc-3.1.3.jar:3.1.3]
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$OpenSession.getResult(TCLIService.java:1482) ~[hive-service-rpc-3.1.3.jar:3.1.3]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36) ~[kyuubi-common_2.12-1.7.1.jar:1.7.1]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) ~[libthrift-0.9.3.jar:0.9.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_372]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_372]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_372]
Caused by: java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 10.19.37.28:31576
	at java.net.URI.create(URI.java:852) ~[?:1.8.0_372]
	at org.apache.kyuubi.engine.trino.session.TrinoSessionImpl.createClientSession(TrinoSessionImpl.scala:91) ~[?:?]
	at org.apache.kyuubi.engine.trino.session.TrinoSessionImpl.open(TrinoSessionImpl.scala:68) ~[?:?]
	at org.apache.kyuubi.session.SessionManager.openSession(SessionManager.scala:107) ~[kyuubi-common_2.12-1.7.1.jar:1.7.1]
Caused by: java.lang.RuntimeException: java.net.URISyntaxException:Illegal character in scheme name at index 0: 10.19.37.28:31576
	at java.net.URI$Parser.fail(URI.java:2847) ~[?:1.8.0_372]
	at java.net.URI$Parser.checkChars(URI.java:3020) ~[?:1.8.0_372]
	at java.net.URI$Parser.checkChar(URI.java:3030) ~[?:1.8.0_372]
	at java.net.URI$Parser.parse(URI.java:3046) ~[?:1.8.0_372]
	at java.net.URI.<init>(URI.java:588) ~[?:1.8.0_372]
	at java.net.URI.create(URI.java:850) ~[?:1.8.0_372]
2023-05-12 09:27:42.364 WARN org.apache.kyuubi.session.KyuubiSessionImpl: Error on closing broken client of engine [kyuubi_USER_TRINO_ocdp_default_22675aab-747f-4ff1-9622-b24c2d4d590b 192.170.50.219:44310]
java.lang.NullPointerException: null
	at org.apache.kyuubi.session.SessionHandle$.apply(SessionHandle.scala:39) ~[kyuubi-common_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.client.KyuubiSyncThriftClient.asyncRequestExecutor$lzycompute(KyuubiSyncThriftClient.scala:69) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.client.KyuubiSyncThriftClient.asyncRequestExecutor(KyuubiSyncThriftClient.scala:67) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.client.KyuubiSyncThriftClient.org$apache$kyuubi$client$KyuubiSyncThriftClient$$shutdownAsyncRequestExecutor(KyuubiSyncThriftClient.scala:78) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.client.KyuubiSyncThriftClient.closeSession(KyuubiSyncThriftClient.scala:235) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$2(KyuubiSessionImpl.scala:182) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$2$adapted(KyuubiSessionImpl.scala:123) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.ha.client.DiscoveryClientProvider$.withDiscoveryClient(DiscoveryClientProvider.scala:36) ~[kyuubi-ha_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1(KyuubiSessionImpl.scala:123) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.session.KyuubiSession.handleSessionException(KyuubiSession.scala:49) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.session.KyuubiSessionImpl.openEngineSession(KyuubiSessionImpl.scala:123) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
	at org.apache.kyuubi.operation.LaunchEngine.$anonfun$runInternal$2(LaunchEngine.scala:60) ~[kyuubi-server_2.12-1.7.1.jar:1.7.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_372]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_372]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_372]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_372]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_372]
2023-05-12 09:27:42.366 INFO org.apache.curator.framework.imps.CuratorFrameworkImpl: backgroundOperationsLoop exiting
2023-05-12 09:27:42.373 INFO org.apache.zookeeper.ZooKeeper: Session: 0x300b9c1a3a3002c closed
2023-05-12 09:27:42.373 INFO org.apache.zookeeper.ClientCnxn: EventThread shut down for session: 0x300b9c1a3a3002c
2023-05-12 09:27:42.384 INFO org.apache.kyuubi.operation.LaunchEngine: Processing ocdp's query[59cebac4-e820-43e7-8d58-bb9ee7c8343c]: RUNNING_STATE -> ERROR_STATE, time taken: 0.132 seconds
Error: org.apache.kyuubi.KyuubiSQLException: Illegal character in scheme name at index 0: 10.19.37.28:31576
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:73)
	at org.apache.kyuubi.session.SessionManager.openSession(SessionManager.scala:119)
	at org.apache.kyuubi.service.AbstractBackendService.openSession(AbstractBackendService.scala:45)
	at org.apache.kyuubi.service.TFrontendService.getSessionHandle(TFrontendService.scala:181)
	at org.apache.kyuubi.service.TFrontendService.OpenSession(TFrontendService.scala:190)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$OpenSession.getResult(TCLIService.java:1497)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$OpenSession.getResult(TCLIService.java:1482)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.kyuubi.service.authentication.TSetIpAddressProcessor.process(TSetIpAddressProcessor.scala:36)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 10.19.37.28:31576
	at java.net.URI.create(URI.java:852)
	at org.apache.kyuubi.engine.trino.session.TrinoSessionImpl.createClientSession(TrinoSessionImpl.scala:91)
	at org.apache.kyuubi.engine.trino.session.TrinoSessionImpl.open(TrinoSessionImpl.scala:68)
	at org.apache.kyuubi.session.SessionManager.openSession(SessionManager.scala:107)
Caused by: java.lang.RuntimeException: java.net.URISyntaxException:Illegal character in scheme name at index 0: 10.19.37.28:31576
	at java.net.URI$Parser.fail(URI.java:2847)
	at java.net.URI$Parser.checkChars(URI.java:3020)
	at java.net.URI$Parser.checkChar(URI.java:3030)
	at java.net.URI$Parser.parse(URI.java:3046)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850) (state=,code=0)
Beeline version 1.7.1 by Apache Kyuubi
``` 

==================================================
I am not sure if my steps are corrects, can anyone help about this?

**Comment by ebyhr** [comment]
I would recommend asking Kyuubi community.
