### ISSUE TITLE
Adding an http proxy option for the bigquery connector

### ISSUE THREAD

**Issue by metalshanked** [trinodb/trino#17508]
Is there a way to use set an HTTP proxy url for the bigquery connector (something like what is available for the hive.s3 settings) ?

Thanks!

**Comment by ebyhr** [comment]
#17067 is going to add support for proxy.

**Comment by metalshanked** [comment]
Hi @hashhar,  I was trying out 419 w/ bigquery proxy today and get the below on startup
I tried setting with and without the scheme `bigquery.rpc-proxy.uri=http://myproxy:123`  and `bigquery.rpc-proxy.uri=myproxy:123`

Is there something I am  doing wrong to use the feature?

Thanks!

```
2023-06-06T00:24:15.109Z	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle started
2023-06-05T19:24:15.114114628-05:00 2023-06-06T00:24:15.113Z	ERROR	main	io.trino.server.Server	Configuration errors:
2023-06-05T19:24:15.114137271-05:00 
2023-06-05T19:24:15.114141359-05:00 1) Error: Configuration property 'bigquery.rpc-proxy.uri' was not used

2023-06-05T19:24:15.114146789-05:00 1 error
2023-06-05T19:24:15.114149364-05:00 io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:
2023-06-05T19:24:15.114151758-05:00 
2023-06-05T19:24:15.114154664-05:00 1) Error: Configuration property 'bigquery.rpc-proxy.uri' was not used
2023-06-05T19:24:15.114157078-05:00 
2023-06-05T19:24:15.114159823-05:00 1 error
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:232)
2023-06-05T19:24:15.114165885-05:00 	at io.trino.plugin.bigquery.BigQueryConnectorFactory.create(BigQueryConnectorFactory.java:57)
	at io.trino.connector.DefaultCatalogFactory.createConnector(DefaultCatalogFactory.java:221)
	at io.trino.connector.DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:130)
2023-06-05T19:24:15.114174060-05:00 	at io.trino.connector.LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:45)
2023-06-05T19:24:15.114189429-05:00 	at io.trino.connector.StaticCatalogManager.lambda$loadInitialCatalogs$1(StaticCatalogManager.java:158)
2023-06-05T19:24:15.114192545-05:00 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-06-05T19:24:15.114197504-05:00 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-06-05T19:24:15.114202634-05:00 	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
2023-06-05T19:24:15.114205289-05:00 	at java.base/java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:184)
2023-06-05T19:24:15.114207864-05:00 	at io.trino.util.Executors.executeUntilFailure(Executors.java:41)
2023-06-05T19:24:15.114210499-05:00 	at io.trino.connector.StaticCatalogManager.loadInitialCatalogs(StaticCatalogManager.java:152)
	at io.trino.server.Server.doStart(Server.java:144)
2023-06-05T19:24:15.114215799-05:00 	at io.trino.server.Server.lambda$start$0(Server.java:91)
	at io.trino.$gen.Trino_419____20230606_002359_1.run(Unknown Source)
2023-06-05T19:24:15.114221379-05:00 	at io.trino.server.Server.start(Server.java:91)
2023-06-05T19:24:15.114223984-05:00 	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
2023-06-05T19:24:15.114226359-05:00 
2023-06-05T19:24:15.114228643-05:00 
```

**Comment by metalshanked** [comment]
Hi @hashhar @ebyhr - 
I tried the settings
`bigquery.rpc-proxy.enabled=true` and `bigquery.rpc-proxy.uri=http://myproxy:8080` 
But seem to get connect timeout errors as below

I confirmed connectivity via the proxy using curl 
`curl -i -s --no-buffer -x 'http://myproxy:8080' -v https://bigquery.googleapis.com`

```
com.google.cloud.bigquery.BigQueryException: Error getting access token for service account: Connect timed out, iss:id@myproj.iam.gserviceaccount.com
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getDataset(HttpBigQueryRpc.java:128)
	at com.google.cloud.bigquery.BigQueryImpl$6.call(BigQueryImpl.java:461)
	at com.google.cloud.bigquery.BigQueryImpl$6.call(BigQueryImpl.java:458)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.bigquery.BigQueryImpl.getDataset(BigQueryImpl.java:457)
	at io.trino.plugin.bigquery.BigQueryClient.getDataset(BigQueryClient.java:186)
	at io.trino.plugin.bigquery.BigQueryMetadata.lambda$schemaExists$4(BigQueryMetadata.java:173)
	at java.base/java.util.Optional.filter(Optional.java:218)
	at io.trino.plugin.bigquery.BigQueryMetadata.schemaExists(BigQueryMetadata.java:173)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.schemaExists(ClassLoaderSafeConnectorMetadata.java:175)
	at io.trino.tracing.TracingConnectorMetadata.schemaExists(TracingConnectorMetadata.java:116)
	at io.trino.metadata.MetadataManager.lambda$schemaExists$1(MetadataManager.java:238)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at io.trino.metadata.MetadataManager.schemaExists(MetadataManager.java:238)
	at io.trino.tracing.TracingMetadata.schemaExists(TracingMetadata.java:147)
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowTables(ShowQueriesRewrite.java:276)
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowTables(ShowQueriesRewrite.java:216)
	at io.trino.sql.tree.ShowTables.accept(ShowTables.java:72)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:213)
	at io.trino.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:54)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:92)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:271)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:206)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:845)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)
	at io.trino.$gen.Trino_419____20230606_012301_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.auth.oauth2.GoogleAuthException: Error getting access token for service account: Connect timed out, iss: id@myproj.iam.gserviceaccount.com
	at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointIOException(GoogleAuthException.java:166)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:543)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:269)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:266)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:633)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:581)
	at com.google.auth.oauth2.OAuth2Credentials.asyncFetch(OAuth2Credentials.java:232)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:182)
	at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadata(ServiceAccountCredentials.java:938)
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96)
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159)
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:91)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:442)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:552)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:493)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getDataset(HttpBigQueryRpc.java:126)
	... 45 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:538)
	... 62 more
	
```

**Comment by hashhar** [comment]
Does your proxy also provide connectivity to oauth2.googleapis.com? Also are you running the connector on a GCP VM or locally?

@wendigo ideas?

**Comment by wendigo** [comment]
@hashhar oauth2 - it should but not tested

**Comment by metalshanked** [comment]
Yes, had checked connectivity to `oauth2.googleapis.com` as well
`curl -vx http://myproxy:8080 https://oauth2.googleapis.com`

cURL Response
```
* Establish HTTP proxy tunnel to oauth2.googleapis.com:443 > CONNECT oauth2.googleapis.com:443 HTTP/1.1 > Host: oauth2.googleapis.com:443 > User-Agent: curl/7.81.0 > Proxy-Connection: Keep-Alive > < HTTP/1.0 200 Connection established
```
It is from local (not cloud hosted).

I could not find any hint from the trino error message that it was using the proxy setting at all.  I mean, i get the same error with or without the proxy settings in Bigquery connector.

**Comment by hashhar** [comment]
If you can't get it to work without the proxy then I don't think it's an issue with the proxy functionality at all. How do you provide credentials to BigQuery connector?

It'd be better to continue on Slack instead of derailing this issue thread and causing notification flood for others.

**Comment by metalshanked** [comment]
Without proxy, threre wont be connectvity allowed so going through a proxy is mandatory for this use case.
Eg:- using os.environ['https_proxy'] with the Python bigquery client works fine

biquery creds are done via the creds key property

Sure, will continue on slack. Thanks for looking into this!

**Comment by hashhar** [comment]
Continued the conversation at https://trinodb.slack.com/archives/C0305TQ05KL/p1686057135815789?thread_ts=1684173295.851759&cid=C0305TQ05KL
