### ISSUE TITLE
Incorrect schema infer during query processing

### ISSUE THREAD

**Issue by ravip1bsmart** [trinodb/trino#17513]
I am using trino to query Apache Pinot table.
I am facing an issue when querying the table.

```
Table schema is 
trino:default> desc ioteventsv2 ;
         Column          |     Type     | Extra | Comment
-------------------------+--------------+-------+---------
 fgpartnum               | varchar      |       |
 altitude                | real         |       |
 soc                     | real         |       |
 originalts              | timestamp(3) |       |
 ambientsensortemp       | real         |       |
 lon                     | real         |       |
 chargestatus            | varchar      |       |
 cellvolt                | json         |       |
 soh                     | real         |       |
 chargecycle             | integer      |       |
 speed                   | real         |       |
 current                 | real         |       |
 sop                     | real         |       |
 chargefetstatus         | boolean      |       |
 celltemp                | json         |       |
 temperature             | real         |       |
 maxchargingvoltage      | real         |       |
 chargingstatus          | integer      |       |
 hardwareversion         | varchar      |       |
 batterycapacity         | real         |       |
 caliberationversion     | varchar      |       |
 lat                     | real         |       |
 alarmencoded            | varchar      |       |
 deltavoltage            | real         |       |
 eventid                 | varchar      |       |
 schemaversion           | varchar      |       |
 dischargecycles         | integer      |       |
 heading                 | real         |       |
 location_st_point       | varbinary    |       |
 alarms                  | json         |       |
 canid                   | varchar      |       |
 consumedat              | timestamp(3) |       |
 deviceid                | varchar      |       |
 batterymanufacturername | varchar      |       |
 maxchargingcurrent      | real         |       |
 pushedat                | timestamp(3) |       |
 mosfettemp              | real         |       |
 voltage                 | real         |       |
 dischargefetstatus      | boolean      |       |
 deltacurrent            | real         |       |
 deltatemperature        | real         |       |
 softwareversion         | varchar      |       |
 ts                      | timestamp(3) |       |
(43 rows)

```
Trino is mistakenly treating `varchar` columns like `deviceid` or `eventid` as `varbinary` and giving `hex not encoded` error on values. This happens only when doing `select *` operation. 
```
trino:default> select * from default.ioteventsv2 where schemaversion = 'intellicar_v1' and consumedAt >= timestamp '2023-05-16 00:00:02' and consumedAt <= timestamp '2023-05-16 00:00:05';

Query 20230516_062139_24654_t82q7, FAILED, 2 nodes
https://trino.upgrid.in/ui/query.html?20230516_062139_24654_t82q7
Splits: 1,147 total, 1,146 done (99.91%)
CPU Time: 0.2s total,     0 rows/s,     0B/s, 1% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
Peak Memory: 256B
9.56 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20230516_062139_24654_t82q7 failed: Value: 01H0GXPN1JCFWZ2DYNAT5CNVQB is not Hex encoded
java.lang.IllegalArgumentException: Value: 01H0GXPN1JCFWZ2DYNAT5CNVQB is not Hex encoded
	at io.trino.plugin.pinot.decoders.VarbinaryDecoder.toBytes(VarbinaryDecoder.java:53)
	at io.trino.plugin.pinot.PinotSegmentPageSource.getSlice(PinotSegmentPageSource.java:347)
	at io.trino.plugin.pinot.PinotSegmentPageSource.writeSliceBlock(PinotSegmentPageSource.java:225)
	at io.trino.plugin.pinot.PinotSegmentPageSource.writeBlock(PinotSegmentPageSource.java:184)
	at io.trino.plugin.pinot.PinotSegmentPageSource.getNextPage(PinotSegmentPageSource.java:137)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:301)
	at io.trino.operator.Driver.processInternal(Driver.java:402)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:305)
	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
	at io.trino.operator.Driver.process(Driver.java:297)
	at io.trino.operator.Driver.processForDuration(Driver.java:268)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:845)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:537)
	at io.trino.$gen.Trino_412____20230512_052155_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.commons.codec.DecoderException: Illegal hexadecimal character H at index 2
	at org.apache.commons.codec.binary.Hex.toDigit(Hex.java:369)
	at org.apache.commons.codec.binary.Hex.decodeHex(Hex.java:107)
	at org.apache.commons.codec.binary.Hex.decodeHex(Hex.java:77)
	at io.trino.plugin.pinot.decoders.VarbinaryDecoder.toBytes(VarbinaryDecoder.java:50)
	... 17 more

```

I am getting result from table when specifying column names in select statement.
Example - 

```trino:default> select deviceid, eventid from default.ioteventsv2 where schemaversion = 'teltonika_v1' and consumedAt >= timestamp '2023-05-16 00:00:02'  and consumedAt <= timestamp '2023-05-16 00:00:05';
    deviceid     |             eventid
-----------------+----------------------------------
 350544503013255 | 8667e44a738f4aaebe91c810a724dc6d
 350544503020003 | 28645d49ba0a429784532046af05b3a7
 350544503448303 | 983bd82d78a04e149d7645e73e7b5274
 350544503019088 | 5bc8b2dbd9a74a208f747c02e06edea4
 350544503448485 | 9cf2c55242af4b7eb7f84329451047ed
 350544503089412 | b318c38ad9154a3a8a6271f2c3f8d836
 350544503085378 | c91b73a113224622b7c6eadfef944768
 350544503018304 | 28aa939324f84ec7b0c2724747d73324
 350544503449129 | 7228e32939cf47a38b096a9ecdaed1a8
 350544503088018 | 6316fd4e372242609328a7df81438807
 350544503452347 | 5752818cd9a0443b98e2230f19563a07
 350544503085840 | 79fd88434f72438095eabb34f24b7df5
 350544503606686 | f7106432d3c94d599db374cc2dcb8108
 350544503450374 | 329f715710e546eca37063da88b2936d
 357073293866436 | 2f7835b8c3f6483e965e7b93315942a5
 357073293866451 | cc112caacc5749a49c3d89ce73b87585
 350544503023247 | e95b1b278b20413ebea3565b9cdf6049
 350544503089990 | 6011e9bd61ae4bb39343c76a8d6ecb93
 350544503062088 | 0cfe57aecc2f4fde88bf311b26122b9e
 350544503089339 | dad40e997c0c4fc3bd9b45e10c212c30
 350544503450796 | 72e810db5ba14301a2a54db6ccb1a652
 350544503491956 | 14eb6bee71d2457db7b64adb462d151c
 350544503084322 | a137d7fbbedf49248212f6787b642654
 350544503606512 | eb449a8bb44b47ed880a8d1d224b265d
 350544503081419 | 7c6a318a3eba46299b8124bc1682603e
 350544503488077 | 3844c58e3c194298a7ef2431b699a3a6
 350544503491964 | 75325fff0d184ceca4e56172109947b7
 350544503087861 | adfc6391001342e882602130d4d6ec22
 350544503015615 | d2307ebf846648838b6f59f812ecb958
 350544503062625 | ea5bb7530afb4884b537d3cdb7e1e1e0
 350544503089818 | f9cd2f6d08b646f194c35cc24ae24085
 350544503088786 | 8a4129069e9945ec8e03002d08fcb369
 350544503019401 | f242d49c6e2e4d59989abf531ba312a9
 350544503020474 | 2f99f9716ffe4f45bd6d43a32030aa2f
 350544503491840 | ea750b2ebdfc4acf9e9d90bafe6aedbe
 357073293869109 | 75a022a94a7049ce81163dbc6e85036b
 350544503085832 | 38014a8b94d5469a9279490d6659dfe4
 350544503606694 | 7728480d6ea045bd87e2b6edc58c2ad5
 350544503081377 | 13bbeac236f3475791cee8806c914780
 350544503491774 | 4edb5c61d55f4616a710a5755c3e4656
 357073293852436 | acd975fdb5584e41ab3e83b138182b55
 350544503012992 | 1138c51f922e4c73978ac3f099b4e992

Query 20230516_072126_30336_t82q7, FINISHED, 2 nodes
https://trino.upgrid.in/ui/query.html?20230516_072126_30336_t82q7
Splits: 2,987 total, 2,987 done (100.00%)
CPU Time: 0.3s total,   170 rows/s, 7.83KB/s, 2% active
Per Node: 0.0 parallelism,     5 rows/s,   269B/s
Parallelism: 0.1
Peak Memory: 1.51KB
4.46 [51 rows, 2.34KB] [11 rows/s, 537B/s]

```

So, the question arises why is it inferring incorrect data type with `select *`?

**Comment by sumit-gupta-sgt** [comment]
Any update on this issue ?
