### ISSUE TITLE
Iceberg connector: `SELECT from partition` metadata table with `ORDER BY` fails if partition column value is `null`

### ISSUE THREAD

**Issue by osscm** [trinodb/trino#17577]
**Case**
1. partition column value is NULL 
2. that is the only column in the partition definition. 
3. SELECT * "tab$partition" ORDER BY partition;

then it fails.

**How to reproduce**

```
trino:tpch> CREATE TABLE test_table_null_partition (_varchar VARCHAR, _bigint BIGINT, _date timestamp(6) with time zone) WITH (partitioning = ARRAY['_date']);
CREATE TABLE
trino:tpch> INSERT INTO test_table_null_partition VALUES ('a', 0, CAST('2019-09-08 00:30:00.005000 UTC' AS TIMESTAMP)), ('a', 1, CAST('2019-09-08 00:30:00.005000 UTC' AS TIMESTAMP)), ('a', 0, CAST('2019-09-08 00:30:00.005000 UTC' AS TIMESTAMP)) , ('a', 2, null);
INSERT: 4 rows

Query 20230519_224533_00026_rp5iu, FINISHED, 3 nodes
Splits: 66 total, 66 done (100.00%)
0.31 [0 rows, 0B] [0 rows/s, 0B/s]

trino:tpch> SELECT partition FROM "test_table_null_partition$partitions";
               partition                
----------------------------------------
 {_date=NULL}                           
 {_date=2019-09-08 07:30:00.005000 UTC} 
(2 rows)

Query 20230519_224538_00027_rp5iu, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.05 [2 rows, 226B] [40 rows/s, 4.5KB/s]

trino:tpch> SELECT partition FROM "test_table_null_partition$partitions" ORDER BY partition DESC;

Query 20230519_224600_00028_rp5iu, FAILED, 3 nodes
Splits: 17 total, 15 done (88.24%)
0.06 [2 rows, 226B] [32 rows/s, 3.56KB/s]

Query 20230519_224600_00028_rp5iu failed: ROW comparison not supported for fields with null elements

trino:tpch> SELECT count(*) FROM test_table_null_partition;
 _col0 
-------
     4 
(1 row)

Query 20230519_224623_00029_rp5iu, FINISHED, 2 nodes
Splits: 7 total, 7 done (100.00%)
0.15 [4 rows, 1.01KB] [25 rows/s, 6.58KB/s]

trino:tpch> SELECT record_count,partition FROM "test_table_null_partition$partitions" ORDER BY record_count DESC;
 record_count |               partition                
--------------+----------------------------------------
            3 | {_date=2019-09-08 07:30:00.005000 UTC} 
            1 | {_date=NULL}                           
(2 rows)

trino:tpch> 
```

Stack trace:

```
2023-05-19T15:46:00.100-0700	ERROR	stage-scheduler	io.trino.execution.StageStateMachine	Stage 20230519_224600_00028_rp5iu.1 failed
io.trino.spi.TrinoException: ROW comparison not supported for fields with null elements
	at io.trino.spi.type.RowType.checkElementNotNull(RowType.java:696)
	at io.trino.spi.type.RowType.chainComparison(RowType.java:688)
	at io.trino.$gen.PagesIndexComparator_20230519_224600_352.compareTo(Unknown Source)
	at io.trino.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:59)
	at io.trino.operator.PagesIndexOrdering.sort(PagesIndexOrdering.java:37)
	at io.trino.operator.PagesIndex.sort(PagesIndex.java:424)
	at io.trino.operator.PagesIndex.sort(PagesIndex.java:418)
	at io.trino.operator.OrderByOperator.finish(OrderByOperator.java:230)
	at io.trino.operator.Driver.processInternal(Driver.java:420)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:305)
	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
	at io.trino.operator.Driver.process(Driver.java:297)
	at io.trino.operator.Driver.processForDuration(Driver.java:268)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:888)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:561)
	at io.trino.$gen.Trino_testversion____20230519_224434_75.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by osscm** [comment]
Looks like in the partition table is appending the NULL partition value as well.
I can add a fix.
