### ISSUE TITLE
Receiving Invalid row filter on querying system.jdbc.catalogs

### ISSUE THREAD

**Issue by kuripart** [trinodb/trino#17576]
Trino version: `406`
Executing Query:

```
SELECT table_cat FROM system.jdbc.catalogs ORDER BY table_cat;
Query 20230519_212504_00004_z8bzn failed: line 1:23: Invalid row filter for 'system.jdbc.catalogs': Column 'table_name' cannot be resolved
```

Table schema:

```
DESCRIBE system.jdbc.catalogs;
  Column   |  Type   | Extra | Comment 
-----------+---------+-------+---------
 table_cat | varchar |       |         
(1 row)
```

Full stack trace:

```
io.trino.spi.TrinoException: line 1:23: Invalid row filter for 'system.jdbc.catalogs': Column 'table_name' cannot be resolved
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeRowFilter(StatementAnalyzer.java:4634)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.lambda$analyzeFiltersAndMasks$54(StatementAnalyzer.java:2219)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFiltersAndMasks(StatementAnalyzer.java:2219)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2183)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:476)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:493)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:4416)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2878)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:476)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:493)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:501)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1449)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:476)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:493)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:455)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:267)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:204)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:856)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:143)
	at io.trino.$gen.Trino_406____20230519_212150_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.trino.spi.TrinoException: line 1:1: Column 'table_name' cannot be resolved
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:33)
	at io.trino.sql.analyzer.Scope.lambda$resolveField$7(Scope.java:228)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.trino.sql.analyzer.Scope.resolveField(Scope.java:228)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:664)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:581)
	at io.trino.sql.tree.Identifier.accept(Identifier.java:91)
	at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:604)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.coerceToSingleType(ExpressionAnalyzer.java:3181)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitInPredicate(ExpressionAnalyzer.java:2256)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitInPredicate(ExpressionAnalyzer.java:581)
	at io.trino.sql.tree.InPredicate.accept(InPredicate.java:58)
	at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:604)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.coerceType(ExpressionAnalyzer.java:3139)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitLogicalExpression(ExpressionAnalyzer.java:788)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitLogicalExpression(ExpressionAnalyzer.java:581)
	at io.trino.sql.tree.LogicalExpression.accept(LogicalExpression.java:80)
	at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:604)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:485)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:3441)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeRowFilter(StatementAnalyzer.java:4622)
	... 34 more
```

**Comment by mosabua** [comment]
You somehow have a row filter defined in an access control system that points at a column that does not exist. The error messages just says that. There is no issue in Trino .. it purely a misconfiguration of your access control.

**Comment by mosabua** [comment]
Somehow this is related to Tableau firing that query towards Trino .. as discussed on https://trinodb.slack.com/archives/CKB39FVQT/p1684948413118139
