### ISSUE TITLE
Delta vacuum fails when table location is with trailing slash

### ISSUE THREAD

**Issue by pajaks** [trinodb/trino#17634]
Reference test case:
https://github.com/trinodb/trino/blob/f211b890d417022baccf80ab2bd78c1e668dc255/plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java#L1601

Fails with exception:
```
2023-05-24T13:31:10.2825134Z io.trino.testing.QueryFailedException: Failure when vacuuming tpch.test_vacuum_qemj6q20um with retention 10m: java.lang.IllegalStateException: Unexpected path [s3://galaxy-trino-ci/galaxy/trailing_slash/test_vacuum_qemj6q20um/delta_log/00000000000000000000.json] returned when listing files under [s3://galaxy-trino-ci/galaxy/trailing_slash/test_vacuum_qemj6q20um/]
2023-05-24T13:31:10.2828038Z 	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
2023-05-24T13:31:10.2830393Z 	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:493)
2023-05-24T13:31:10.2832418Z 	at io.trino.testing.QueryAssertions.assertDistributedUpdate(QueryAssertions.java:107)
2023-05-24T13:31:10.2834310Z 	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:63)
2023-05-24T13:31:10.2836348Z 	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:400)
2023-05-24T13:31:10.2838529Z 	at io.trino.plugin.objectstore.TestObjectStoreDeltaS3.testVacuum(TestObjectStoreDeltaS3.java:164)
2023-05-24T13:31:10.2840742Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
2023-05-24T13:31:10.2842620Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
2023-05-24T13:31:10.2844543Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2023-05-24T13:31:10.2846348Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2023-05-24T13:31:10.2848309Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2023-05-24T13:31:10.2850063Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2023-05-24T13:31:10.2852098Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2023-05-24T13:31:10.2853948Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2023-05-24T13:31:10.2855929Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2023-05-24T13:31:10.2858007Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2023-05-24T13:31:10.2859824Z 	at java.base/java.lang.Thread.run(Thread.java:1589)
2023-05-24T13:31:10.2862131Z 	Suppressed: java.lang.Exception: SQL: CALL system.vacuum(schema_name => CURRENT_SCHEMA, table_name => 'test_vacuum_qemj6q20um', retention => '10m')
2023-05-24T13:31:10.2864407Z 		at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:497)
2023-05-24T13:31:10.2866045Z 		... 15 more
2023-05-24T13:31:10.2868952Z Caused by: io.trino.spi.TrinoException: Failure when vacuuming tpch.test_vacuum_qemj6q20um with retention 10m: java.lang.IllegalStateException: Unexpected path [s3://galaxy-trino-ci/galaxy/trailing_slash/test_vacuum_qemj6q20um/delta_log/00000000000000000000.json] returned when listing files under [s3://galaxy-trino-ci/galaxy/trailing_slash/test_vacuum_qemj6q20um/]
2023-05-24T13:31:10.2871741Z 	at io.trino.execution.CallTask.execute(CallTask.java:218)
2023-05-24T13:31:10.2873338Z 	at io.trino.execution.CallTask.execute(CallTask.java:71)
2023-05-24T13:31:10.2875138Z 	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:146)
2023-05-24T13:31:10.2877013Z 	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:258)
2023-05-24T13:31:10.2879000Z 	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:148)
2023-05-24T13:31:10.2881128Z 	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:132)
2023-05-24T13:31:10.2883230Z 	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:569)
2023-05-24T13:31:10.2885114Z 	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:544)
2023-05-24T13:31:10.2886992Z 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
2023-05-24T13:31:10.2937461Z 	at io.trino.$gen.Trino_testversion____20230524_132457_401.run(Unknown Source)
2023-05-24T13:31:10.2939665Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2023-05-24T13:31:10.2941768Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2023-05-24T13:31:10.2943469Z 	at java.base/java.lang.Thread.run(Thread.java:1589)
2023-05-24T13:31:10.2946706Z Caused by: java.lang.RuntimeException: Failure when vacuuming tpch.test_vacuum_qemj6q20um with retention 10m: java.lang.IllegalStateException: Unexpected path [s3://galaxy-trino-ci/galaxy/trailing_slash/test_vacuum_qemj6q20um/delta_log/00000000000000000000.json] returned when listing files under [s3://galaxy-trino-ci/galaxy/trailing_slash/test_vacuum_qemj6q20um/]
2023-05-24T13:31:10.2949832Z 	at io.trino.plugin.deltalake.procedure.VacuumProcedure.vacuum(VacuumProcedure.java:134)
2023-05-24T13:31:10.2951858Z 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
2023-05-24T13:31:10.2953827Z 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758)
2023-05-24T13:31:10.2955578Z 	at io.trino.execution.CallTask.execute(CallTask.java:211)
2023-05-24T13:31:10.2956992Z 	... 12 more
2023-05-24T13:31:10.2959447Z Caused by: java.lang.IllegalStateException: Unexpected path [s3://galaxy-trino-ci/galaxy/trailing_slash/test_vacuum_qemj6q20um/delta_log/00000000000000000000.json] returned when listing files under [s3://galaxy-trino-ci/galaxy/trailing_slash/test_vacuum_qemj6q20um/]
2023-05-24T13:31:10.2962150Z 	at com.google.common.base.Preconditions.checkState(Preconditions.java:821)
2023-05-24T13:31:10.2964218Z 	at io.trino.plugin.deltalake.procedure.VacuumProcedure.doVacuum(VacuumProcedure.java:222)
2023-05-24T13:31:10.2966467Z 	at io.trino.plugin.deltalake.procedure.VacuumProcedure.vacuum(VacuumProcedure.java:127)
2023-05-24T13:31:10.2968070Z 	... 15 more
```

**Comment by findepi** [comment]
fixed in https://github.com/trinodb/trino/pull/17848
