### ISSUE TITLE
Clickhouse - java.io.IOException: Reached end of input stream after reading ... of ... bytes

### ISSUE THREAD

**Issue by benrifkind** [trinodb/trino#17758]
I am getting the following error using the Trino Clickhouse connector
> java.io.IOException: Reached end of input stream after reading ... of ... bytes

I have a Clickhouse table like

|column_name | data_type|
|-----------|---------|
|date|date|
|advertisable_eid|varbinary|
|domain|varbinary|

If  I query over multiple dates the query fails with the above error. Example query
```sql
select 
date,
from_utf8(domain)
from <table>
where 
  from_utf8(advertisable_eid) = 'x'
  and from_utf8(domain) = 'y'
  and date(date) in (date'2023-06-01', date'2023-06-02') limit 10;
```

If I restrict this query to one date, it succeeds. A similar query succeeds if we directly query Clickhouse.

Thanks in advance for any help!

**Comment by ebyhr** [comment]
Can you share the entire stacktrace? You can get it from CLI --debug option or webui.

**Comment by benrifkind** [comment]
@ebyhr
```
io.trino.spi.TrinoException: java.io.IOException: Reached end of input stream after reading 44 of 79 bytes
	at io.trino.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:305)
	at io.trino.plugin.jdbc.JdbcRecordCursor.advanceNextPosition(JdbcRecordCursor.java:179)
	at io.trino.$gen.CursorProcessor_20230605_222332_12580.process(Unknown Source)
	at io.trino.operator.ScanFilterAndProjectOperator$RecordCursorToPages.process(ScanFilterAndProjectOperator.java:348)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:182)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$7(WorkProcessorUtils.java:296)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$3(WorkProcessorUtils.java:219)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$4(WorkProcessorUtils.java:234)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:150)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:752)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:519)
	at io.trino.$gen.Trino_dbf8baa____20230605_120649_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLException: java.io.IOException: Reached end of input stream after reading 44 of 79 bytes
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:76)
	at com.clickhouse.jdbc.ClickHouseResultSet.next(ClickHouseResultSet.java:710)
	at io.trino.plugin.jdbc.JdbcRecordCursor.advanceNextPosition(JdbcRecordCursor.java:176)
	... 32 more
Caused by: java.io.IOException: Reached end of input stream after reading 44 of 79 bytes
	at com.clickhouse.client.ClickHouseInputStream.readBytes(ClickHouseInputStream.java:461)
	at com.clickhouse.client.http.ClickHouseHttpResponse.readBytes(ClickHouseHttpResponse.java:146)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$MappedFunctions.lambda$buildMappingsForDataTypes$64(ClickHouseRowBinaryProcessor.java:337)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$MappedFunctions.deserialize(ClickHouseRowBinaryProcessor.java:465)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$Records.readNextRow(ClickHouseRowBinaryProcessor.java:519)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$Records.next(ClickHouseRowBinaryProcessor.java:549)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$Records.next(ClickHouseRowBinaryProcessor.java:494)
	at com.clickhouse.jdbc.ClickHouseResultSet.next(ClickHouseResultSet.java:708)
	... 33 more
```

**Comment by zhicwu** [comment]
Hi @benrifkind, could you try latest ClickHouse JDBC driver v0.4.6?

**Comment by benrifkind** [comment]
@zhicwu I'll give it a shot. Do I install this on the Trino cluster? Can I just drop in a replacement for the trino-clickhouse JAR that is bundled with Trino. This is what I see on my Trino cluster. I'm running Trino 405.
```
/usr/local/trino-server/plugin/clickhouse/trino-clickhouse-405.jar
/usr/local/trino-server/plugin/clickhouse/clickhouse-jdbc-0.3.2-patch3-all.jar
/usr/local/trino-server/plugin/clickhouse/trino-clickhouse-405-services.jar
```

**Comment by ebyhr** [comment]
You can try the latest Trino version. It uses ClickHouse 0.4.6 JDBC driver internally.

**Comment by benrifkind** [comment]
Hey folks. I tried with Trino 419 and am still getting the same error. Here's the stack trace.
> io.trino.spi.TrinoException: java.io.StreamCorruptedException: Reached end of input stream after reading 67 of 105 bytes
	at io.trino.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:314)
	at io.trino.plugin.jdbc.JdbcRecordCursor.advanceNextPosition(JdbcRecordCursor.java:188)
	at io.trino.$gen.CursorProcessor_20230606_182405_41.process(Unknown Source)
	at io.trino.operator.ScanFilterAndProjectOperator$RecordCursorToPages.process(ScanFilterAndProjectOperator.java:335)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:182)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils$BlockingProcess.process(WorkProcessorUtils.java:208)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:318)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:360)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:241)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:256)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:146)
	at io.trino.operator.Driver.processInternal(Driver.java:402)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:305)
	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
	at io.trino.operator.Driver.process(Driver.java:297)
	at io.trino.operator.Driver.processForDuration(Driver.java:268)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:888)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:556)
	at io.trino.$gen.Trino_4b6b80d____20230606_182241_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLException: java.io.StreamCorruptedException: Reached end of input stream after reading 67 of 105 bytes
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:45)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
	at com.clickhouse.jdbc.ClickHouseResultSet.next(ClickHouseResultSet.java:729)
	at io.trino.plugin.jdbc.JdbcRecordCursor.advanceNextPosition(JdbcRecordCursor.java:185)
	... 33 more
Caused by: java.io.StreamCorruptedException: Reached end of input stream after reading 67 of 105 bytes
	at com.clickhouse.data.stream.AbstractByteArrayInputStream.readBytes(AbstractByteArrayInputStream.java:237)
	at com.clickhouse.data.format.BinaryDataProcessor.readBinaryString(BinaryDataProcessor.java:674)
	at com.clickhouse.data.format.ClickHouseRowBinaryProcessor.readAndFill(ClickHouseRowBinaryProcessor.java:254)
	at com.clickhouse.data.ClickHouseDataProcessor.nextRecord(ClickHouseDataProcessor.java:204)
	at com.clickhouse.data.ClickHouseDataProcessor.access$200(ClickHouseDataProcessor.java:25)
	at com.clickhouse.data.ClickHouseDataProcessor$RecordsIterator.next(ClickHouseDataProcessor.java:124)
	at com.clickhouse.data.ClickHouseDataProcessor$RecordsIterator.next(ClickHouseDataProcessor.java:110)
	at com.clickhouse.jdbc.ClickHouseResultSet.next(ClickHouseResultSet.java:727)
	... 34 more

**Comment by ebyhr** [comment]
@benrifkind I suspect this is ClickHouse JDBC driver's bug rather than the connector. Can you reproduce the issue without Trino?

**Comment by zhicwu** [comment]
Could be something wrong when deserializing binary string or the query got killed somehow by the server.

> A similar query succeeds if we directly query Clickhouse.

@benrifkind, did you check table `system.query_log` or error log in ClickHouse? Just trying to understand if there's any clue there and the exact query being sent to ClickHouse. I'll setup trino after work to see if I can reproduce.

**Comment by benrifkind** [comment]
I think it is what @zhicwu suggested. From the query logs, it looks like the date filter is not being pushed down into clickhouse, so it ends up querying the entire table.


The Trino query is
```sql
select 
date,
from_utf8(domain)
from <table>
where 
  from_utf8(advertisable_eid) = 'x'
  and from_utf8(domain) = 'y'
  and date(date) in (date'2023-06-01', date'2023-06-02') 
  limit 10
```

Here's what the query looks like in the `system.query_log` 
```sql
SELECT "date", "advertisable_eid", "domain" FROM "<table>"
```

Restricting to a specific date in Trino:
```sql
select 
date,
from_utf8(domain)
from <table>
where 
  from_utf8(advertisable_eid) = 'x'
  and from_utf8(domain) = 'y'
  and date(date) = date'2023-06-01'
  limit 10
```
And the corresponding query in the `system.query_log` 
```sql
SELECT "date", "advertisable_eid", "domain" 
FROM "rollworks"."historical_domain_and_tal_tag_mappings" 
WHERE ("date" >= '2023-06-01' AND "date" < '2023-06-02')
```

**Comment by zhicwu** [comment]
@benrifkind, is there any error in system.query_log or error log in ClickHouse for the query? It could be an issue with the JDBC driver if no error in ClickHouse.

**Comment by zhicwu** [comment]
Thanks @benrifkind. Not sure if ClickHouse/ClickHouse#45087 will be fixed or not, but I'll improve the error message in JDBC driver by adding query_id for ease of troubleshooting.

**Comment by benrifkind** [comment]
Thanks @zhicwu !

Is there anything I can do to fix the query so that the date filter is passed from Trino to Clickhouse so that this query does not result in a full Clickhouse table scan?

**Comment by benrifkind** [comment]
It's not too bad. We can use a Jinja template to generate this `union all` query. Appreciate all your help @zhicwu!

**Comment by T-M-L-C** [comment]
> Hi @benrifkind, could you try latest ClickHouse JDBC driver v0.4.6?

which issue?

**Comment by T-M-L-C** [comment]
> You can try the latest Trino version. It uses ClickHouse 0.4.6 JDBC driver internally.

which issue?

**Comment by ebyhr** [comment]
@T-M-L-C https://github.com/trinodb/trino/pull/17469

**Comment by LuGuangming** [comment]
@ebyhr Hello, Please conform whether it be fixed?
