### ISSUE TITLE
Flaky `TestDeltaLakeMinioAndHmsConnectorSmokeTest`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#17780]
```
Error:  Failures: 
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest.testDeltaColumnInvariant:181->AbstractTestQueryFramework.assertUpdate:395->AbstractTestQueryFramework.assertUpdate:400 » QueryFailed Failed checking table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_invariants_wfh9jx8v5i
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest.testSchemaEvolutionOnTableWithColumnInvariant:200 » QueryFailed Failed checking table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_schema_evolution_on_table_with_column_invariant_fua8o8k8si
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testSelectOldDate:941->AbstractTestQueryFramework.assertQuery:339 Execution of 'actual' query 20230606_225426_00564_k3g2p failed: SELECT * FROM old_dates
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testSelectOldTimestamps:951->AbstractTestQueryFramework.assertQuery:339 Execution of 'actual' query 20230606_225547_00565_k3g2p failed: SELECT CAST(ts AS VARCHAR), i FROM old_timestamps
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testShowCreateTable:373->AbstractTestQueryFramework.computeScalar:309->AbstractTestQueryFramework.computeScalar:314->AbstractTestQueryFramework.computeActual:304 » QueryFailed Error getting snapshot for smoke_test.person
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testStatsSplitPruningBasedOnSepCreatedCheckpoint:1514->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed failed to read statistics with table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_sep_checkpoint_stats_pruning_hm8d31cryb
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testStatsSplitPruningBasedOnSepCreatedCheckpointOnTopOfCheckpointWithJustStructStats:1552->BaseDeltaLakeAwsConnectorSmokeTest.registerTableFromResources:39 » QueryFailed Failed checking table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_sep_checkpoint_stats_pruning_struct_stats_43t8kaoexr
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testTimestampWithTimeZoneInArrayType:833->AbstractTestQueryFramework.assertUpdate:395->AbstractTestQueryFramework.assertUpdate:400 » QueryFailed Unable to access file system for: s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_timestamp_with_time_zone_xwmzyj9c90
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testTimestampWithTimeZoneInMapType:855->AbstractTestQueryFramework.assertUpdate:395->AbstractTestQueryFramework.assertUpdate:400 » QueryFailed Unable to access file system for: s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_timestamp_with_time_zone_j43gibm04g
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testTimestampWithTimeZoneInNestedField:900->AbstractTestQueryFramework.assertUpdate:395->AbstractTestQueryFramework.assertUpdate:400 » QueryFailed Unable to access file system for: s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_timestamp_with_time_zone_erpgioaxod
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testTimestampWithTimeZoneInRowType:878->AbstractTestQueryFramework.assertUpdate:395->AbstractTestQueryFramework.assertUpdate:400 » QueryFailed Unable to access file system for: s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_timestamp_with_time_zone_ywvfiu7x8q
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testTimestampWithTimeZoneMillis:805->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed failed to read statistics with table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_timestamp_with_time_zone_vuwnpfrxdp
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testUnregisterBrokenTable:1978->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed Unable to access file system for: s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/smoke_test/test_unregister_broken_table_lowip0fzfu-5be79dbc153a4200b9c1c97def4e58b2
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testUnregisterTable:1961->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed Unable to access file system for: s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/smoke_test/test_unregister_table_kwdpxiqxcp-d4fb207c00bf4c9a98d178771d57d1bf
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testUnregisterTableAccessControl:2038->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed Unable to access file system for: s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/smoke_test/test_unregister_table_access_control_at09zoq7uq-88aa39177dcd45e58bfcbde5e70ad4ac
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testUppercaseColumnNames:1028->AbstractTestQueryFramework.assertQuery:339 Execution of 'actual' query 20230606_230514_00584_k3g2p failed: SELECT * FROM uppercase_columns
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testVacuum:1593->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed failed to read statistics with table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_vacuumh5oa744z7o
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testVacuumAccessControl:1654->AbstractTestQueryFramework.assertUpdate:385->AbstractTestQueryFramework.assertUpdate:390 Execution of 'actual' query 20230606_230716_00586_k3g2p failed: CREATE TABLE test_deny_vacuum_yinwqhpkky WITH (location = 's3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_deny_vacuum_yinwqhpkky') AS SELECT * FROM orders
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testVacuumParameterValidation:1634->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed failed to read statistics with table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_vacuum_parameter_validation_9j5w153xiu
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest.testWritesLockExpired:130->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed failed to read statistics with table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_writes_locked4pcupm43pj
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest.testWritesLockExpired:130->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed failed to read statistics with table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_writes_lockedeyqqd4az6x
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest.testWritesLockExpired:130->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed failed to read statistics with table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_writes_lockediejenssysp
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest.testWritesLockInvalidContents:160->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed failed to read statistics with table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_writes_locked3v385t8m5x
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest.testWritesLockInvalidContents:160->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed failed to read statistics with table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_writes_lockedpjl7s2kzhz
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest.testWritesLockInvalidContents:160->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed failed to read statistics with table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_writes_lockedksmk6kz7h4
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest.testWritesLocked:111->AbstractTestQueryFramework.assertUpdate:395->AbstractTestQueryFramework.assertUpdate:400 » QueryFailed line 1:1: Table 'delta.smoke_test.test_writes_lockedok8z58saow' does not exist
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest.testWritesLocked:111->AbstractTestQueryFramework.assertUpdate:395->AbstractTestQueryFramework.assertUpdate:400 » QueryFailed line 1:1: Table 'delta.smoke_test.test_writes_lockedeby5h1me3c' does not exist
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest.testWritesLocked:111->AbstractTestQueryFramework.assertUpdate:395->AbstractTestQueryFramework.assertUpdate:400 » QueryFailed line 1:1: Table 'delta.smoke_test.test_writes_lockedm07gjnrbtj' does not exist
```

https://github.com/trinodb/trino/actions/runs/5193535642/jobs/9364596979
https://github.com/trinodb/trino/actions/runs/5193658423/jobs/9364918683

**Comment by ebyhr** [comment]
The exception comes from AWS client. Might relate to https://github.com/trinodb/trino/pull/17754
```
Error:  io.trino.plugin.deltalake.TestDeltaLakeMinioAndHmsConnectorSmokeTest.testWritesLockInvalidContents[UPDATE %s SET a_string = 'kota' WHERE a_number = 2, VALUES (1,'ala'), (2,'kota')](2)  Time elapsed: 40.493 s  <<< FAILURE!
io.trino.testing.QueryFailedException: failed to read statistics with table location s3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_writes_lockedksmk6kz7h4
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:493)
	at io.trino.testing.QueryAssertions.assertDistributedUpdate(QueryAssertions.java:107)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:63)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:410)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:405)
	at io.trino.plugin.deltalake.TestDeltaLakeMinioAndHmsConnectorSmokeTest.testWritesLockInvalidContents(TestDeltaLakeMinioAndHmsConnectorSmokeTest.java:160)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE test_writes_lockedksmk6kz7h4 (a_number, a_string) WITH (location = 's3://test-delta-lake-integration-smoke-test-hzh7tojgoz/test_writes_lockedksmk6kz7h4') AS VALUES (1, 'ala'), (2, 'ma')
		at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:497)
		... 18 more
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:52)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	... 64 more
```

**Comment by ebyhr** [comment]
I expect #17743 fixes the failure.
