### ISSUE TITLE
Concurrent CREATE OR REPLACE VIEW generate TableAlreadyExistsException

### ISSUE THREAD

**Issue by Guesswhoisback99** [trinodb/trino#17971]
Hello,

When I call twice CREATE OR REPLACE VIEW I get:

```
Caused by: java.sql.SQLException: Query failed (#20230620_095631_00214_q7frz): Table already exists: 'schema1.view1'
at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:295)
at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:255)
at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:295)
at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:207)
at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:162)
at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:301)
at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
at io.trino.jdbc.TrinoResultSet$AsyncIterator.lambda$new$1(TrinoResultSet.java:180)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 3 common frames omitted
Caused by: io.trino.jdbc.$internal.client.FailureInfo$FailureException: Table already exists: 'schema.view1'
at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createTable(ThriftHiveMetastore.java:938)
at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.createTable(BridgingHiveMetastore.java:201)
at io.trino.plugin.hive.metastore.ForwardingHiveMetastore.createTable(ForwardingHiveMetastore.java:156)
at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.createTable(CachingHiveMetastore.java:479)
at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.createTable(CachingHiveMetastore.java:479)
at io.trino.plugin.hive.HiveMetastoreClosure.createTable(HiveMetastoreClosure.java:165)
at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$CreateTableOperation.run(SemiTransactionalHiveMetastore.java:3460)
at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeAddTableOperations(SemiTransactionalHiveMetastore.java:2300)
at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:1636)
at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1355)
at io.trino.plugin.hive.HiveMetadata.commit(HiveMetadata.java:3739)
at io.trino.plugin.hive.HiveTransactionManager.lambda$commit$0(HiveTransactionManager.java:59)
at java.base/java.util.Optional.ifPresent(Optional.java:178)
at io.trino.plugin.hive.HiveTransactionManager.commit(HiveTransactionManager.java:57)
at io.trino.plugin.hive.HiveConnector.commit(HiveConnector.java:216)
at io.trino.metadata.CatalogTransaction.commit(CatalogTransaction.java:78)
at io.trino.metadata.CatalogMetadata.commit(CatalogMetadata.java:154)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
at io.trino.$gen.Trino_405____20230620_090151_2.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
```

Do you know any way to prevent such situation?

**Comment by RameshByndoor** [comment]
Could you update more details like version/catalog conf and env.

**Comment by Guesswhoisback99** [comment]
Trino 405, Hive metastore standalone 3.0

config:
```
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8443
discovery.uri=http://trino:8443
http-server.process-forwarded=true
http-server.authentication.type=password,header
```

catalog:
```
connector.name=hive
hive.hdfs.impersonation.enabled=false
hive.metastore.uri=thrift://metastore:9083
hive.storage-format=PARQUET
hive.config.resources=/xxx/core-site.xml,/xxx/hdfs-site.xml
hive.security=allow-all
```
