### ISSUE TITLE
Query failed with Multiple tables matched when connecting to Databend in MySQL connector

### ISSUE THREAD

**Issue by Firstero** [trinodb/trino#17985]
I tried to connect to Databend, a data warehouse that is compatible with the MySQL protocol, using Trino's MySQL Connector. While there were no issues connecting directly with the MySQL client, the Trino MySQL Connector produced the error mentioned above. Below are screenshots comparing the two terminal executions.
![image](https://github.com/trinodb/trino/assets/68093523/d0c4b78d-7d88-4b35-bf74-990c4d7ab5c5)

**Comment by ebyhr** [comment]
> a data warehouse that is compatible with the MySQL protocol, using Trino's MySQL Connector.

The failure probably means Databend isn't **_fully_** compatible with MySQL. 

> While there were no issues connecting directly with the MySQL client

I would recommend debugging with JDBC driver instead of MySQL client.

**Comment by Firstero** [comment]
@ebyhr I wrote a simple test demo using the MySQL JDBC driver, and the previous 'describe table' and query commands can also run successfully. I used version 8.0.30 of mysql-connector-java, and the result is shown in the screenshot. 
jdbc:
![image](https://github.com/trinodb/trino/assets/68093523/8bad302a-d2d8-42f7-b3ff-ae3a4ff5ced7)
mysql-client:
![image](https://github.com/trinodb/trino/assets/68093523/10e072bb-edcb-466e-a28a-10dd4acc44bc)

It doesn't seem to be a compatibility issue with Databend JDBC, right?

**Comment by ebyhr** [comment]
Please copy some code from https://github.com/trinodb/trino/blob/dd9a53ad8b41a7d7b006cab31a9171924fb07e9e/plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java#L204-L227

**Comment by ebyhr** [comment]
No need to use the plugin. You can simply copy the code with some adjustments.

**Comment by Firstero** [comment]
I directly used the trino-jdbc package for testing, and the error message during testing is as follows.
Caused by: io.trino.spi.TrinoException: Multiple tables matched: trino.t1
        at io.trino.plugin.jdbc.BaseJdbcClient.getTableHandle(BaseJdbcClient.java:219)
        at io.trino.plugin.jdbc.ForwardingJdbcClient.getTableHandle(ForwardingJdbcClient.java:87)
        at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getTableHandle$3(StatisticsAwareJdbcClient.java:108)
        at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
        at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getTableHandle(StatisticsAwareJdbcClient.java:108)
        at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getTableHandle$4(CachingJdbcClient.java:345)
        at io.trino.collect.cache.EmptyCache.get(EmptyCache.java:97)
        at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:749)
        at io.trino.plugin.jdbc.CachingJdbcClient.getTableHandle(CachingJdbcClient.java:345)
        at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getTableHandle$4(CachingJdbcClient.java:345)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
        at io.trino.collect.cache.EvictableCache.get(EvictableCache.java:115)
        at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:749)
        at io.trino.plugin.jdbc.CachingJdbcClient.getTableHandle(CachingJdbcClient.java:345)
        at io.trino.plugin.jdbc.DefaultJdbcMetadata.getTableHandle(DefaultJdbcMetadata.java:138)
        at io.trino.plugin.jdbc.DefaultJdbcMetadata.getTableHandle(DefaultJdbcMetadata.java:103)
        at io.trino.spi.connector.ConnectorMetadata.getTableHandle(ConnectorMetadata.java:122)
        at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableHandle(ClassLoaderSafeConnectorMetadata.java:1064)
        at io.trino.metadata.MetadataManager.lambda$getTableHandle$5(MetadataManager.java:283)
        at java.base/java.util.Optional.flatMap(Optional.java:289)
        at io.trino.metadata.MetadataManager.getTableHandle(MetadataManager.java:277)
        at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1547)
        at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1539)
        at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowColumns(ShowQueriesRewrite.java:484)
        at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowColumns(ShowQueriesRewrite.java:216)
        at io.trino.sql.tree.ShowColumns.accept(ShowColumns.java:68)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:213)
        at io.trino.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:53)
        at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:76)
        at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
        at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:258)
        at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:196)
        at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:818)
        at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:149)
        at io.trino.$gen.Trino_411____20230620_074012_2.call(Unknown Source)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ebyhr** [comment]
I would recommend debugging why multiple entries appear in the method.

**Comment by Firstero** [comment]
@ebyhr  I directly executed the Trino MySQL connector to execute the 'describe t1' query, and the query statement was sent to Databend. Databend did indeed return two records:
![image](https://github.com/trinodb/trino/assets/68093523/250daefa-510a-46cc-a2ef-0785e0c9bcb6)
query was `SELECT TABLE_SCHEMA AS TABLE_CAT, NULL AS TABLE_SCHEM, TABLE_NAME, CASE WHEN (TABLE_TYPE = 'BASE TABLE') THEN CASE WHEN ((TABLE_SCHEMA = 'mysql') OR (TABLE_SCHEMA = 'performance_schema')) THEN 'SYSTEM TABLE' ELSE 'TABLE' END WHEN (TABLE_TYPE = 'TEMPORARY') THEN 'LOCAL_TEMPORARY' ELSE TABLE_TYPE END AS TABLE_TYPE, TABLE_COMMENT AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME, NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION FROM INFORMATION_SCHEMA.TABLES WHERE ((TABLE_SCHEMA = 'trino') AND (TABLE_NAME = 't1')) HAVING TABLE_TYPE IN('TABLE', 'VIEW', NULL, NULL, NULL) ORDER BY TABLE_TYPE, TABLE_SCHEMA, TABLE_NAME`
