### ISSUE TITLE
Elasticsearch "ignore_throttled" is deprecated

### ISSUE THREAD

**Issue by metalshanked** [trinodb/trino#18033]
The elasticsearch connector seems to use the `ignore_throttled` query param for searches which is deprecated.

```
request [POST https://elastic_server:9200/myindex-001/_search?rest_total_hits_as_int=true&typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&preference=_shards%3A0&ignore_throttled=true&scroll=600000ms&search_type=query_then_fetch&batched_reduce_size=512] 
returned 1 warnings: [299 Elasticsearch-8.8.0-c01029875a091076ed42cdb3a41c10b1a9a5a20f "[ignore_throttled] parameter is deprecated because frozen indices have been deprecated. Consider cold or frozen tiers in place of frozen indices."]
```

**Comment by ZhongmingFan** [comment]
I also meet this problem, how to fix it?

**Comment by zhouzhuangjie** [comment]
```
2023-07-28T15:29:49.193+0800	WARN	I/O dispatcher 5	org.elasticsearch.client.RestClient	request [POST http://elastic_server:9200/cw_uac_alarm_event_v1-000001/_search?rest_total_hits_as_int=true&typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&preference=_shards%3A0&ignore_throttled=true&scroll=1000000ms&search_type=query_then_fetch&batched_reduce_size=512] returned 1 warnings: [299 Elasticsearch-7.16.1-5b38441b16b1ebb16a27c107a4c3865776e20c53 "[ignore_throttled] parameter is deprecated because frozen indices have been deprecated. Consider cold or frozen tiers in place of frozen indices."]
2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr	Exception in thread "I/O dispatcher 5" 
2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr	java.lang.AssertionError

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.elasticsearch.client.Response.assertWarningValue(Response.java:193)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.elasticsearch.client.Response.extractWarningValueFromWarningHeader(Response.java:183)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.elasticsearch.client.Response.getWarnings(Response.java:205)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:546)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:537)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)

2023-07-28T15:29:49.193+0800	INFO	I/O dispatcher 5	stderr		at java.base/java.lang.Thread.run(Thread.java:833)

2023-07-28T15:29:50.168+0800	ERROR	pool-47-thread-1	org.apache.http.impl.nio.client.InternalHttpAsyncClient	I/O reactor terminated abnormally
org.apache.http.nio.reactor.IOReactorException: I/O dispatch worker terminated abnormally
```
`ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&preference=_shards%3A0&ignore_throttled=true&scroll=1000000ms&search_type=query_then_fetch&batched_reduce_size=512` 
these params is not supported in es 7.16.1.
