### ISSUE TITLE
Rows in index don't match rows in partition

### ISSUE THREAD

**Issue by charlesjmorgan** [trinodb/trino#18030]
This error is being thrown by the Trino operator:

```
java.lang.IllegalStateException: Total number of rows in index does not match number of rows in partitions within that index
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
	at io.trino.operator.WindowInfo$IndexInfoBuilder.build(WindowInfo.java:222)
	at io.trino.operator.WindowInfo$DriverWindowInfoBuilder.build(WindowInfo.java:93)
	at io.trino.operator.WindowOperator.close(WindowOperator.java:929)
	at io.trino.operator.Driver.closeAndDestroyOperators(Driver.java:558)
	at io.trino.operator.Driver.destroyIfNecessary(Driver.java:520)
	at io.trino.operator.Driver.tryWithLock(Driver.java:705)
	at io.trino.operator.Driver.process(Driver.java:297)
	at io.trino.operator.Driver.processForDuration(Driver.java:268)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:888)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:561)
	at io.trino.$gen.Trino_417.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

I'm not sure what causes it or what queries are being run

**Comment by losipiuk** [comment]
cc: @kasiafi @sopel39

**Comment by sopel39** [comment]
@charlesjmorgan thanks for report. Do you have a repro?
