### ISSUE TITLE
Hive view containing `substr` returns different result from Hive

### ISSUE THREAD

**Issue by jerryleooo** [trinodb/trino#18099]
```
hive> create view view_test_substr as select substr('123', 0, 2);

trino> select * from view_test_substr;
Query 20230630_032216_00009_svkmk failed: line 1:15: View 'hive.default.view_test_substr' is stale or in invalid state: a column of type varchar(3) projected from query view at position 0 has no name
io.trino.spi.TrinoException: line 1:15: View 'hive.default.view_test_substr' is stale or in invalid state: a column of type varchar(3) projected from query view at position 0 has no name
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.lambda$createScopeForView$56(StatementAnalyzer.java:2406)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.createScopeForView(StatementAnalyzer.java:2406)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.createScopeForView(StatementAnalyzer.java:2369)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2165)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:484)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:501)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:4466)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2933)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:484)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:501)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:509)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1460)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:484)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:501)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:463)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:264)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:199)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:826)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:154)
	at io.trino.$gen.Trino_trino413____20230630_030933_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Trino version 413, may relate to https://github.com/trinodb/trino/issues/5606

**Comment by ebyhr** [comment]
Please note that "a column of type varchar(3) projected from query view at position 0 has no name" isn't specific to `substr` function. The error happens when you created Hive views without column names.

**Comment by jerryleooo** [comment]
@ebyhr thanks for the reply

after adding column name, Trino gave different results:

```
hive> create view view_test_substr as select substr('123', 0, 2) as a;
hive> select * from view_test_substr;
12

trino> select * from view_test_substr;
 a
---

(1 row)
```

**Comment by ebyhr** [comment]
@jerryleooo Could you file an issue to https://github.com/linkedin/coral/issues/new?

**Comment by jerryleooo** [comment]
@ebyhr sure, https://github.com/linkedin/coral/issues/433

**Comment by Cloudj111** [comment]
I think substring is start index to '1' in Hive and Trino.
Here is document I saw.

https://trino.io/docs/current/functions/string.html?highlight=substr#substring
https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substr


And I try to substr in hive using trino-cli.
I got this result. If you want, refer to this result.

```
trino:default> create view view_test_substr as select substr('123', 1, 2) as a;
CREATE VIEW
trino:default> SELECT * FROM `view_test_substr;`
 a
----
 12
(1 row)

Query 20231219_101543_00128_fkf78, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.46 [0 rows, 0B] [0 rows/s, 0B/s]

```

**Comment by ebyhr** [comment]
@jerryleooo Thanks for working on Coral PR (https://github.com/linkedin/coral/pull/434). Do you want to send another PR (dependency bump + test) to Trino repository?

**Comment by jerryleooo** [comment]
@ebyhr sure👌
