### ISSUE TITLE
Fetching all hive metadata failed issues

### ISSUE THREAD

**Issue by heechan3006** [trinodb/trino#18111]
Hi all. I'm trying to find solution about fetching all hive metadata tables. Here is the information.

### Environment

trino version - 419
hive version - 2.3.3 or 3.1.3

`hive.metastore-timeout=5m`

### Problem

When I execute below query, it failed due to hive metastore timeout error. but under trino 417 works well within 3~4 minutes.

`select * from hive.information_schema.tables`

![image](https://github.com/trinodb/trino/assets/56464741/f15f0425-d2af-443f-956f-72591e0194ba)

### Root Cause

https://github.com/trinodb/trino/pull/17127

after 418 version, fetching all hive metadata logic has been changed.

For the < 418 version, it follows below logics

1. get all schemas
2. get all tables each schema
3. concat the results and return it.

For the >= 418 version,  it follows below logics

1. get all tables at once.
2. concat the results and return it.

This changes may happened too much load for hive metastore so that needed lots of memory compared with before.
In my case, # of tables are around 500,000 so it definitely get too much stress for hivemetastore.

Is there any solution about this?

**Comment by findepi** [comment]
cc @huberty89 @kokosing

**Comment by kokosing** [comment]
> hive version - 2.3.3 or 3.1.3

Is it vanilla Hive, or provided by some vendor like Cloudera?

Can you please share the entire stack trace for the error you got?

**Comment by heechan3006** [comment]
Hi @kokosing 

>  Is it vanilla Hive, or provided by some vendor like Cloudera?

Actually, we are using AWS EMR 6.7.0 version

> Can you please share the entire stack trace for the error you got?

```
io.trino.spi.TrinoException: Error listing tables for catalog hive: ip-10-210-216-228.ap-northeast-2.compute.internal:9083: Socket is closed by peer.
	at io.trino.metadata.MetadataListing.handleListingException(MetadataListing.java:327)
	at io.trino.metadata.MetadataListing.listTables(MetadataListing.java:115)
	at io.trino.connector.informationschema.InformationSchemaPageSource.addTablesRecords(InformationSchemaPageSource.java:273)
	at io.trino.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:214)
	at io.trino.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:178)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:301)
	at io.trino.operator.Driver.processInternal(Driver.java:402)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:305)
	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
	at io.trino.operator.Driver.process(Driver.java:297)
	at io.trino.operator.Driver.processForDuration(Driver.java:268)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:888)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:561)
	at io.trino.$gen.Trino_418____20230703_103627_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.trino.spi.TrinoException: ip-10-210-216-228.ap-northeast-2.compute.internal:9083: Socket is closed by peer.
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getAllTables(ThriftHiveMetastore.java:880)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.getAllTables(BridgingHiveMetastore.java:160)
	at io.trino.plugin.hive.metastore.ForwardingHiveMetastore.getAllTables(ForwardingHiveMetastore.java:120)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadAllTables(CachingHiveMetastore.java:765)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.lambda$new$1(CachingHiveMetastore.java:365)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:193)
	at io.trino.collect.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:450)
	at io.trino.collect.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:436)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
	at io.trino.collect.cache.EvictableCache.get(EvictableCache.java:148)
	at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:51)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getOptional(CachingHiveMetastore.java:452)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getAllTables(CachingHiveMetastore.java:760)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadAllTables(CachingHiveMetastore.java:765)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.lambda$new$1(CachingHiveMetastore.java:365)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at io.trino.collect.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:450)
	at io.trino.collect.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:436)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
	at io.trino.collect.cache.EvictableCache.get(EvictableCache.java:148)
	at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:51)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getOptional(CachingHiveMetastore.java:452)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getAllTables(CachingHiveMetastore.java:760)
	at io.trino.plugin.hive.HiveMetastoreClosure.getAllTables(HiveMetastoreClosure.java:157)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.getAllTables(SemiTransactionalHiveMetastore.java:254)
	at io.trino.plugin.hive.HiveMetadata.listTables(HiveMetadata.java:778)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.listTables(ClassLoaderSafeConnectorMetadata.java:288)
	at io.trino.tracing.TracingConnectorMetadata.listTables(TracingConnectorMetadata.java:270)
	at io.trino.metadata.MetadataManager.listTables(MetadataManager.java:527)
	at io.trino.tracing.TracingMetadata.listTables(TracingMetadata.java:305)
	at io.trino.metadata.MetadataListing.doListTables(MetadataListing.java:121)
	at io.trino.metadata.MetadataListing.listTables(MetadataListing.java:112)
	... 16 more
Caused by: org.apache.thrift.transport.TTransportException: ip-10-210-216-228.ap-northeast-2.compute.internal:9083: Socket is closed by peer.
	at io.trino.plugin.hive.metastore.thrift.Transport.rewriteException(Transport.java:95)
	at io.trino.plugin.hive.metastore.thrift.Transport$TTransportWrapper.readAll(Transport.java:129)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:457)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:359)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.recvGetTableMeta(ThriftHiveMetastore.java:2002)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.getTableMeta(ThriftHiveMetastore.java:1987)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.trino.plugin.base.util.LoggingInvocationHandler.handleInvocation(LoggingInvocationHandler.java:60)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at jdk.proxy5/jdk.proxy5.$Proxy336.getTableMeta(Unknown Source)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.lambda$getAllTables$1(ThriftHiveMetastoreClient.java:204)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.alternativeCall(ThriftHiveMetastoreClient.java:800)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.getAllTables(ThriftHiveMetastoreClient.java:200)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.lambda$getAllTables$2(FailureAwareThriftMetastoreClient.java:98)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.runWithHandle(FailureAwareThriftMetastoreClient.java:455)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.getAllTables(FailureAwareThriftMetastoreClient.java:98)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$getAllTables$33(ThriftHiveMetastore.java:875)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
	at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getAllTables(ThriftHiveMetastore.java:873)
	... 60 more
Caused by: org.apache.thrift.transport.TTransportException: Socket is closed by peer.
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:176)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:100)
	at io.trino.plugin.hive.metastore.thrift.Transport$TTransportWrapper.readAll(Transport.java:126)
	... 83 more
```

**Comment by heechan3006** [comment]
@kokosing This is the error log in hive metastore.
```
FailedObject:56612709[OID]org.apache.hadoop.hive.metastore.model.MTable
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:564)
	at org.datanucleus.api.jdo.JDOAdapter.getApiExceptionForNucleusException(JDOAdapter.java:678)
	at org.datanucleus.state.StateManagerImpl.isLoaded(StateManagerImpl.java:2929)
	at org.apache.hadoop.hive.metastore.model.MTable.dnGetdatabase(MTable.java)
	at org.apache.hadoop.hive.metastore.model.MTable.getDatabase(MTable.java:222)
	at org.apache.hadoop.hive.metastore.ObjectStore.getTableMeta(ObjectStore.java:1616)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:97)
	at com.sun.proxy.$Proxy48.getTableMeta(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_table_meta(HiveMetaStore.java:2954)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invokeInternal(RetryingHMSHandler.java:147)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:108)
	at com.sun.proxy.$Proxy66.get_table_meta(Unknown Source)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$get_table_meta.getResult(ThriftHiveMetastore.java:15256)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$get_table_meta.getResult(ThriftHiveMetastore.java:15240)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.hadoop.hive.metastore.TUGIBasedProcessor.process(TUGIBasedProcessor.java:104)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
NestedThrowablesStackTrace:
No such database row
org.datanucleus.exceptions.NucleusObjectNotFoundException: No such database row
	at org.datanucleus.store.rdbms.request.FetchRequest.execute(FetchRequest.java:348)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.fetchObject(RDBMSPersistenceHandler.java:319)
	at org.datanucleus.state.AbstractStateManager.loadFieldsFromDatastore(AbstractStateManager.java:1147)
	at org.datanucleus.state.StateManagerImpl.loadSpecifiedFields(StateManagerImpl.java:2564)
	at org.datanucleus.state.StateManagerImpl.isLoaded(StateManagerImpl.java:2918)
	at org.apache.hadoop.hive.metastore.model.MTable.dnGetdatabase(MTable.java)
	at org.apache.hadoop.hive.metastore.model.MTable.getDatabase(MTable.java:222)
	at org.apache.hadoop.hive.metastore.ObjectStore.getTableMeta(ObjectStore.java:1616)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:97)
	at com.sun.proxy.$Proxy48.getTableMeta(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_table_meta(HiveMetaStore.java:2954)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invokeInternal(RetryingHMSHandler.java:147)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:108)
	at com.sun.proxy.$Proxy66.get_table_meta(Unknown Source)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$get_table_meta.getResult(ThriftHiveMetastore.java:15256)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$get_table_meta.getResult(ThriftHiveMetastore.java:15240)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.hadoop.hive.metastore.TUGIBasedProcessor.process(TUGIBasedProcessor.java:104)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by kokosing** [comment]
It seems related to https://issues.apache.org/jira/browse/HIVE-21028

@heechan3006 is this problem permanent or intermittent? Is possible that someone dropped a database while retrieval of all databases by Trino?

**Comment by heechan3006** [comment]
@kokosing It seems that there is no impact on other databases. This problem only happen when I execute below query.
```
select * from hive.information_schema.tables
```
But if there is some where clause, it works well.
```
select * from hive.information_schema.tables where and table_schema="example_schema"
```

**Comment by kokosing** [comment]
Yes. But from UX perspective it is Trino issue, as everything was working and then after update it is failing. So I think kill switch is needed to mitigate issues during the transition period when people will start to use HMS which is free from this issue.

@heechan3006 Is it possible for you to update HMS and check if the issue is still there?

**Comment by heechan3006** [comment]
@kokosing As I said previously we are using EMR 6.7.0 version. Even we are trying to upgrade EMR as latest version (6.11.0), hive version won’t be upgraded refer to https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-6110-release.html

**Comment by kokosing** [comment]
Yes. So this problem will be exposed by many Glue users. So kill switch seems to be required. CC: @Praveen2112 @huberty89

**Comment by heechan3006** [comment]
@kokosing Can you tell me which version of trino it will be released on?

**Comment by huberty89** [comment]
> Yes. So this problem will be exposed by many Glue users. So kill switch seems to be required.

I think Glue is not affected - Glue API does not have ability to fetch all tables from all the schemas/databases

**Comment by huberty89** [comment]
> @huberty89 would you like to post a PR and create a kill switch?

On it

**Comment by heechan3006** [comment]
Hi @huberty89 . Is there any updates?

**Comment by kokosing** [comment]
@heechan3006 are you able to test https://github.com/trinodb/trino/pull/18274 if it is solving your problem?

**Comment by heechan3006** [comment]
@kokosing Sure. Could you please share how to build tar file for those changes?

**Comment by heechan3006** [comment]
Hi @kokosing @huberty89 . I've tested [#18274 ](https://github.com/trinodb/trino/pull/18274) and I've confirmed that query was executed well. Thanks for support!

![image](https://github.com/trinodb/trino/assets/56464741/986664e4-00e5-4523-8101-3529ae0fa0ae)

**Comment by anjosma** [comment]
Hi! I'm facing a similar issue upgrading Trino from 426 to 449. This parameter `hive.metastore.thrift.batch-fetch.enabled` is not available anymore. 
I'm looking for but have not found a parameter that replaces this one, which is not available on 449 version

<img width="1151" alt="image" src="https://github.com/user-attachments/assets/471304db-d488-48bd-bae4-d97d191c680d">
