### ISSUE TITLE
Trino cannot read hive views

### ISSUE THREAD

**Issue by zhongqishang** [trinodb/trino#18122]
Trino : 417

I have a hive view as follow, it's via sparksql created, catalog is iceberg format.

`show create table view_name;`
```
CREATE VIEW dwd.table_name_view (
  id,
  data_status,
  create_date,
  update_date,
  ...)
AS select *
 from iceberg.ods_iceberg_db.table_name
```

When i query from trino via `select * from dwd.table_name_view`, I meet the follow error.

```
io.trino.spi.TrinoException: Failed to translate Hive view 'dwd.iceberg_manage_enterprise_db_comp_non_soe_notice': com.linkedin.coral.hive.hive2rel.parsetree.parser.ParseException: line 2:46 cannot recognize input near '.' 'comp_non_soe_notice' '<EOF>' in table source
	at io.trino.plugin.hive.ViewReaderUtil$HiveViewReader.decodeViewData(ViewReaderUtil.java:246)
	at io.trino.plugin.hive.HiveMetadata.lambda$toConnectorViewDefinition$78(HiveMetadata.java:2757)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.trino.plugin.hive.HiveMetadata.toConnectorViewDefinition(HiveMetadata.java:2751)
	at io.trino.plugin.hive.HiveMetadata.getView(HiveMetadata.java:2744)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getView(ClassLoaderSafeConnectorMetadata.java:630)
	at io.trino.tracing.TracingConnectorMetadata.getView(TracingConnectorMetadata.java:754)
	at io.trino.metadata.MetadataManager.getViewInternal(MetadataManager.java:1242)
	at io.trino.metadata.MetadataManager.getView(MetadataManager.java:1217)
	at io.trino.tracing.TracingMetadata.getView(TracingMetadata.java:776)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2168)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:483)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:500)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:4456)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2939)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:483)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:500)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:508)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1459)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:483)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:500)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:462)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:97)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:271)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:206)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:845)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:154)
	at io.trino.$gen.Trino_417____20230605_095730_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: com.linkedin.coral.hive.hive2rel.parsetree.parser.ParseException: line 2:46 cannot recognize input near '.' 'comp_non_soe_notice' '<EOF>' in table source
	at com.linkedin.coral.hive.hive2rel.parsetree.ParseTreeBuilder.process(ParseTreeBuilder.java:111)
	at com.linkedin.coral.hive.hive2rel.HiveToRelConverter.toSqlNode(HiveToRelConverter.java:95)
	at com.linkedin.coral.common.ToRelConverter.processView(ToRelConverter.java:152)
	at com.linkedin.coral.common.ToRelConverter.convertView(ToRelConverter.java:123)
	at io.trino.plugin.hive.ViewReaderUtil$HiveViewReader.decodeViewData(ViewReaderUtil.java:225)
	... 40 more
Caused by: com.linkedin.coral.hive.hive2rel.parsetree.parser.ParseException: line 2:46 cannot recognize input near '.' 'comp_non_soe_notice' '<EOF>' in table source
	at com.linkedin.coral.hive.hive2rel.parsetree.parser.CoralParseDriver.parse(CoralParseDriver.java:38)
	at com.linkedin.coral.hive.hive2rel.parsetree.ParseTreeBuilder.process(ParseTreeBuilder.java:108)
	... 44 more
```

### I found some related issue:
https://github.com/trinodb/trino/issues/5785
https://github.com/linkedin/coral/pull/19

Now is there some way to solve this scenario?

**Comment by ebyhr** [comment]
Could you share the entire view defintion?

**Comment by zhongqishang** [comment]
@ebyhr 
```
CREATE VIEW dwd.table_name_view
AS select *
from iceberg.ods_iceberg_db.table_name
```
