### ISSUE TITLE
Flaky test TestHiveCoercionOnPartitionedTable. testHiveCoercionParquet & testHiveCoercionSequence

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#18134]
from https://github.com/trinodb/trino/actions/runs/5458592625/jobs/9933986391?pr=18131#logs (build for https://github.com/trinodb/trino/pull/18131, passed after re-running)

```
tests               | 2023-07-05 04:39:02 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveCoercionOnPartitionedTable.testHiveCoercionParquet (Groups: hive_coercion, jdbc) took 15.5 seconds
tests               | 2023-07-05 04:39:02 SEVERE: Failure cause:
tests               | java.lang.AssertionError: Could not find rows:
tests               | [null]
tests               | [null]
tests               | 
tests               | actual rows:
tests               | [2]
tests               | [2]
tests               | 	at io.trino.tests.product.hive.BaseTestHiveCoercion.assertQueryResults(BaseTestHiveCoercion.java:690)
tests               | 	at io.trino.tests.product.hive.BaseTestHiveCoercion.assertNestedSubFields(BaseTestHiveCoercion.java:560)
tests               | 	at io.trino.tests.product.hive.BaseTestHiveCoercion.doTestHiveCoercion(BaseTestHiveCoercion.java:145)
tests               | 	at io.trino.tests.product.hive.TestHiveCoercionOnPartitionedTable.testHiveCoercionParquet(TestHiveCoercionOnPartitionedTable.java:289)
```

**Comment by ebyhr** [comment]
`testHiveCoercionSequence` failed at https://github.com/trinodb/trino/actions/runs/6719468274/job/18262149607?pr=17725
```
io.trino.tests.product.hive.TestHiveCoercionOnPartitionedTable.testHiveCoercionSequence (Groups: hive_coercion, jdbc) took 6.3 seconds
tests               | 2023-11-01 18:58:17 SEVERE: Failure cause:
tests               | java.lang.AssertionError: Could not find rows:
tests               | [null]
tests               | 
tests               | actual rows:
tests               | [12345.12345]
tests               | [NaN]
tests               | 	at io.trino.tests.product.hive.BaseTestHiveCoercion.assertQueryResults(BaseTestHiveCoercion.java:824)
tests               | 	at io.trino.tests.product.hive.BaseTestHiveCoercion.doTestHiveCoercion(BaseTestHiveCoercion.java:159)
tests               | 	at io.trino.tests.product.hive.TestHiveCoercionOnPartitionedTable.testHiveCoercionSequence(TestHiveCoercionOnPartitionedTable.java:342)
tests               | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/19905/checks?check_run_id=19068082233

```
Could not find rows:
[null]

actual rows:
[12345.12345]
[NaN]
```

**Comment by findepi** [comment]
```
tests               | 2024-06-19 20:01:32 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveCoercionOnPartitionedTable.testHiveCoercionRcText (Groups: jdbc) took 6.7 seconds
tests               | 2024-06-19 20:01:32 SEVERE: Failure cause:
tests               | java.lang.AssertionError: Could not find rows:
tests               | [null]
tests               | 
tests               | actual rows:
tests               | [12345.12345]
tests               | [NaN]
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/24714195932/job/72288074407?pr=29181

```
tests               | 2026-04-21 15:34:52 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveCoercionOnPartitionedTable.testHiveCoercionRcBinary (Groups: jdbc) took 13.8 seconds
tests               | 2026-04-21 15:34:52 SEVERE: Failure cause:
tests               | java.lang.AssertionError: Could not find rows:
tests               | [null]
tests               | [null]
tests               | 
tests               | actual rows:
tests               | [true]
tests               | [false]
```
