### ISSUE TITLE
Hive sorted writes fail when user identity contains the `@` AT sign

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#18132]
```
java.lang.IllegalArgumentException: Path missing in file system location: file:///tmp/presto-admin@example.com
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
	at io.trino.filesystem.Location.of(Location.java:99)
	at io.trino.plugin.hive.HiveWriterFactory.setSchemeToFileIfAbsent(HiveWriterFactory.java:815)
	at io.trino.plugin.hive.HiveWriterFactory.createWriter(HiveWriterFactory.java:589)
	at io.trino.plugin.hive.HivePageSink.getWriterIndexes(HivePageSink.java:409)
	at io.trino.plugin.hive.HivePageSink.writePage(HivePageSink.java:303)
	at io.trino.plugin.hive.HivePageSink.doAppend(HivePageSink.java:297)
	at io.trino.plugin.hive.HivePageSink.lambda$appendPage$3(HivePageSink.java:285)
	at io.trino.hdfs.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:26)
	at io.trino.hdfs.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.hdfs.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:25)
	at io.trino.hdfs.HdfsEnvironment.doAs(HdfsEnvironment.java:129)
	at io.trino.plugin.hive.HivePageSink.appendPage(HivePageSink.java:285)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:68)
	at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:255)
	at io.trino.operator.Driver.processInternal(Driver.java:398)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:296)
	at io.trino.operator.Driver.tryWithLock(Driver.java:692)
	at io.trino.operator.Driver.process(Driver.java:288)
	at io.trino.operator.Driver.processForDuration(Driver.java:259)
```

**Comment by findepi** [comment]
This fails since https://github.com/trinodb/trino/pull/17923, but uncovers a pre-existing problem that `Location` parses such locations in a unexpected manner, treating `/tmp/presto-admin` as userInfo, `example.com` as location's host name, and inferring empty path component.
