### ISSUE TITLE
Flaky test TestHiveTransactionalTable.testOrcColumnDropAdd

### ISSUE THREAD

**Issue by krvikash** [trinodb/trino#18216]
https://github.com/trinodb/trino/actions/runs/5506378530/jobs/10038333884?pr=17863

```
2023-07-10T16:49:17.3295360Z tests               | 2023-07-10 22:34:17 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveTransactionalTable.testOrcColumnDropAdd [false] (Groups: hive_transactional) took 11.3 seconds
2023-07-10T16:49:17.3579764Z tests               | 2023-07-10 22:34:17 SEVERE: Failure cause:
2023-07-10T16:49:17.3581160Z tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error executing query: java.net.SocketTimeoutException: timeout
2023-07-10T16:49:17.3581844Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
2023-07-10T16:49:17.3582415Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2023-07-10T16:49:17.3586671Z tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:54)
2023-07-10T16:49:17.3587882Z tests               | 	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
2023-07-10T16:49:17.3588342Z tests               | 	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
2023-07-10T16:49:17.3588846Z tests               | 	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
2023-07-10T16:49:17.3589399Z tests               | 	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
2023-07-10T16:49:17.3589890Z tests               | 	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
2023-07-10T16:49:17.3590639Z tests               | 	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
2023-07-10T16:49:17.3591423Z tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:54)
2023-07-10T16:49:17.3594582Z tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.lambda$testOrcColumnDropAdd$38(TestHiveTransactionalTable.java:1108)
2023-07-10T16:49:17.3597971Z tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.withTemporaryTable(TestHiveTransactionalTable.java:1814)
2023-07-10T16:49:17.3598963Z tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.testOrcColumnDropAdd(TestHiveTransactionalTable.java:1103)
2023-07-10T16:49:17.3600010Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-07-10T16:49:17.3600960Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-07-10T16:49:17.3601932Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-07-10T16:49:17.3624079Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-07-10T16:49:17.3624918Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2023-07-10T16:49:17.3625619Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2023-07-10T16:49:17.3626140Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2023-07-10T16:49:17.3626611Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2023-07-10T16:49:17.3627154Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2023-07-10T16:49:17.3627817Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2023-07-10T16:49:17.3628367Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-07-10T16:49:17.3628946Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-07-10T16:49:17.3629408Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-07-10T16:49:17.3630610Z tests               | Caused by: java.sql.SQLException: Error executing query: java.net.SocketTimeoutException: timeout
2023-07-10T16:49:17.3631189Z tests               | 	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:287)
2023-07-10T16:49:17.3631766Z tests               | 	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
2023-07-10T16:49:17.3632469Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
2023-07-10T16:49:17.3633079Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
2023-07-10T16:49:17.3642428Z tests               | 	... 25 more
2023-07-10T16:49:17.3642926Z tests               | 	Suppressed: java.lang.Exception: Query: ALTER TABLE test_test_orc_add_drop_false_NONE_vm7r1875foqk824f038r DROP COLUMN old_state
2023-07-10T16:49:17.3643778Z tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
2023-07-10T16:49:17.3644207Z tests               | 		... 26 more

...
...
...

2023-07-10T16:49:23.5584123Z presto-master       | io.trino.spi.TrinoException: Malformed ORC file. Cannot read SQL type 'integer' from ORC stream '.row.age' of type BYTE with attributes {} [hdfs://hadoop-master:9000/user/hive/warehouse/test_test_orc_column_type_change_false_none_5lzqmloqshy7uw3s8u35/delta_0000001_0000001_0000/bucket_00000]
2023-07-10T16:49:23.5680041Z presto-master       | 	at io.trino.plugin.hive.orc.OrcPageSourceFactory.createOrcPageSource(OrcPageSourceFactory.java:457)
2023-07-10T16:49:23.5684247Z presto-master       | 	at io.trino.plugin.hive.orc.OrcPageSourceFactory.createPageSource(OrcPageSourceFactory.java:202)
2023-07-10T16:49:23.5685487Z presto-master       | 	at io.trino.plugin.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:219)
2023-07-10T16:49:23.5691649Z presto-master       | 	at io.trino.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:153)
2023-07-10T16:49:23.5693432Z presto-master       | 	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:48)
2023-07-10T16:49:23.5699070Z presto-master       | 	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
2023-07-10T16:49:23.5699827Z presto-master       | 	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:296)
2023-07-10T16:49:23.5704942Z presto-master       | 	at io.trino.operator.Driver.processInternal(Driver.java:395)
2023-07-10T16:49:23.5705757Z presto-master       | 	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
2023-07-10T16:49:23.5710600Z presto-master       | 	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
2023-07-10T16:49:23.5711453Z presto-master       | 	at io.trino.operator.Driver.process(Driver.java:290)
2023-07-10T16:49:23.5712490Z presto-master       | 	at io.trino.operator.Driver.processForDuration(Driver.java:261)
2023-07-10T16:49:23.5717845Z presto-master       | 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
2023-07-10T16:49:23.5718700Z presto-master       | 	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
2023-07-10T16:49:23.5724743Z presto-master       | 	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:555)
2023-07-10T16:49:23.5725675Z presto-master       | 	at io.trino.$gen.Trino_421_46_g878dc53____20230710_160610_2.run(Unknown Source)
2023-07-10T16:49:23.5734254Z presto-master       | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-07-10T16:49:23.5735331Z presto-master       | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-07-10T16:49:23.5736040Z presto-master       | 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-07-10T16:49:23.5742509Z presto-master       | Caused by: io.trino.orc.OrcCorruptionException: Malformed ORC file. Cannot read SQL type 'integer' from ORC stream '.row.age' of type BYTE with attributes {} [hdfs://hadoop-master:9000/user/hive/warehouse/test_test_orc_column_type_change_false_none_5lzqmloqshy7uw3s8u35/delta_0000001_0000001_0000/bucket_00000]
2023-07-10T16:49:23.5743561Z presto-master       | 	at io.trino.orc.reader.ReaderUtils.invalidStreamType(ReaderUtils.java:45)
2023-07-10T16:49:23.5750055Z presto-master       | 	at io.trino.orc.reader.ColumnReaders.createColumnReader(ColumnReaders.java:69)
2023-07-10T16:49:23.5753152Z presto-master       | 	at io.trino.orc.OrcRecordReader.createColumnReaders(OrcRecordReader.java:612)
2023-07-10T16:49:23.5757400Z presto-master       | 	at io.trino.orc.OrcRecordReader.<init>(OrcRecordReader.java:262)
2023-07-10T16:49:23.5758253Z presto-master       | 	at io.trino.orc.OrcReader.createRecordReader(OrcReader.java:308)
2023-07-10T16:49:23.5759073Z presto-master       | 	at io.trino.plugin.hive.orc.OrcPageSourceFactory.createOrcPageSource(OrcPageSourceFactory.java:392)
2023-07-10T16:49:23.5770358Z presto-master       | 	... 18 more
2023-07-10T16:49:23.5770752Z presto-master       | 
2023-07-10T16:49:23.5777847Z presto-master       | 
```

**Comment by findinpath** [comment]
```
io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error executing query: java.net.SocketTimeoutException: timeout
	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
	at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:55)
	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
	at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:55)
	at io.trino.tests.product.hive.TestHiveTransactionalTable.execute(TestHiveTransactionalTable.java:1796)
	at io.trino.tests.product.hive.TestHiveTransactionalTable.lambda$testUnpartitionedDeleteAll$15(TestHiveTransactionalTable.java:762)
	at io.trino.tests.product.hive.TestHiveTransactionalTable.withTemporaryTable(TestHiveTransactionalTable.java:1815)
	at io.trino.tests.product.hive.TestHiveTransactionalTable.testUnpartitionedDeleteAll(TestHiveTransactionalTable.java:759)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLException: Error executing query: java.net.SocketTimeoutException: timeout
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:287)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
	... 25 more
	Suppressed: java.lang.Exception: Query: DELETE FROM test_unpartitioned_delete_all_false_NONE_b3umjkcxhjos60kxyyw9
		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
		... 26 more
Caused by: java.io.UncheckedIOException: java.net.SocketTimeoutException: timeout
	at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:146)
	at io.trino.jdbc.$internal.client.StatementClientV1.<init>(StatementClientV1.java:130)
	at io.trino.jdbc.$internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:28)
	at io.trino.jdbc.TrinoConnection.startQuery(TrinoConnection.java:771)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:252)
	... 28 more
```

https://github.com/trinodb/trino/pull/19520/checks?check_run_id=18024266334
