### ISSUE TITLE
TestDeltaLakeDatabricksMinioReads.testReadRegionTable  flaky

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#18226]
```
ILURE     /    io.trino.tests.product.deltalake.TestDeltaLakeDatabricksMinioReads.testReadRegionTable (Groups: profile_specific_tests, delta-lake-minio) took 3.9 seconds
tests               | 2023-07-11 04:07:40 SEVERE: Failure cause:
tests               | java.lang.AssertionError: Expected notification s3:ObjectAccessed:Get for 'region_databricks/_delta_log/00000000000000000000.json' 1 time(s) but got 0: []
tests               | 	at io.trino.tests.product.utils.MinioNotificationsAssertions.assertNotificationsCount(MinioNotificationsAssertions.java:116)
tests               | 	at io.trino.tests.product.deltalake.BaseTestDeltaLakeMinioReads.testReadRegionTable(BaseTestDeltaLakeMinioReads.java:83)
tests               | 	at io.trino.tests.product.deltalake.TestDeltaLakeDatabricksMinioReads.testReadRegionTable(TestDeltaLakeDatabricksMinioReads.java:35)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
tests               | 
presto-master       | 2023-07-11T04:07:40.381+0545	INFO	dispatcher-query-0	io.trino.event.QueryMonitor	TIMELINE: Query 20230710_222240_00021_3usd4 :: FINISHED :: elapsed 22ms :: planning 0ms :: waiting 0ms :: scheduling 22ms :: running 0ms :: finishing 22ms :: begin 2023-07-11T04:07:40.358+05:45 :: end 2023-07-11T04:07:40.380+05:45
tests               | 2023-07-11 04:07:40 WARNING: Notification listener for bucket delta-test-basic-reads threw exception
tests               | java.lang.RuntimeException: io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error executing query: null
tests               | 	at io.trino.testing.minio.MinioClient$NotificationListener.run(MinioClient.java:280)
tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
tests               | 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
tests               | 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
tests               | 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
tests               | Caused by: io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error executing query: null
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:54)
tests               | 	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
tests               | 	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
tests               | 	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
tests               | 	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
tests               | 	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:54)
tests               | 	at io.trino.tests.product.utils.MinioNotificationsAssertions.recordNotification(MinioNotificationsAssertions.java:76)
tests               | 	at io.trino.tests.product.deltalake.BaseTestDeltaLakeMinioReads.lambda$setUp$0(BaseTestDeltaLakeMinioReads.java:62)
tests               | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
tests               | 	at io.trino.testing.minio.MinioClient$NotificationListener.run(MinioClient.java:276)
tests               | 	... 7 more
tests               | Caused by: java.sql.SQLException: Error executing query: null
tests               | 	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:287)
tests               | 	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 	... 20 more
tests               | 	Suppressed: java.lang.Exception: Query: INSERT INTO memory.default."read_region_notifications" (name, time, request, response, user_agent, bucket, object_key, object_size, object_version, object_etag, sequencer) VALUES ('OBJECT_ACCESSED_GET', from_iso8601_timestamp('2023-07-10T22:22:39.363Z'), map(ARRAY['principalId', 'range', 'region', 'sourceIPAddress'], ARRAY['minio-access-key', 'bytes=107-212', '', '172.18.0.4']), map(ARRAY['content-length', 'x-amz-request-id', 'x-minio-deployment-id', 'x-minio-origin-endpoint'], ARRAY['106', '1770A1CC5C94DED2', '9a094478-55cd-4012-b4f2-947991f2c583', 'http://0.0.0.0:9080']), ', aws-sdk-java/1.12.493 Linux/5.15.0-1041-azure OpenJDK_64-Bit_Server_VM/17.0.5+8-LTS java/17.0.5 kotlin/1.8.21 vendor/Azul_Systems,_Inc. cfg/retry-mode/legacy, Trino', 'delta-test-basic-reads', url_decode('region_databricks/part-00000-98195ace-e492-4cd7-97d1-9b955202874b-c000.snappy.parquet'), 1482, '', '97743085777e5b2099f3[5085](https://github.com/trinodb/trino/actions/runs/5510698232/jobs/10048114895?pr=18175#step:7:5086)194584aa', '1770A1CC5C9EB085')
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
tests               | 		... 21 more
tests               | Caused by: io.trino.jdbc.$internal.guava.base.VerifyException
tests               | 	at io.trino.jdbc.$internal.guava.base.Verify.verify(Verify.java:102)
tests               | 	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:313)
tests               | 	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:61)
tests               | 	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
tests               | 	... 23 more

```

**Comment by findepi** [comment]
obsolete 🤞
