### ISSUE TITLE
Use TDigestHistogram in connectorMetrics

### ISSUE THREAD

**Issue by leetcode-1533** [trinodb/trino#18267]
I tried to use TDigestHistogram in the https://github.com/trinodb/trino/pull/6232 implementation. For example, in the `OrcPageSource` code, I tried to do:

```
public Metrics getMetrics()
    {
        ImmutableMap.Builder<String, Metric<?>> metrics = ImmutableMap.<String, Metric<?>>builder();
        metrics.put(ORC_CODEC_METRIC_PREFIX + compressionKind.name(), new LongCount(recordReader.getTotalDataLength()));
        metrics.put("NewKey, new TDigestHistogram(300));

        return new Metrics(metrics.build());
    }
```

It is surprising to me that LongCount works but not TDigestHistogram. It is also surprising to me, that operatorStatistics already have:
```
    public static Metrics getOperatorMetrics(Metrics operatorMetrics, long inputPositions, double cpuTimeSeconds, double wallTimeSeconds, double blockedWallSeconds)
    {
        return operatorMetrics.mergeWith(new Metrics(ImmutableMap.of(
                "Input rows distribution", TDigestHistogram.fromValue(inputPositions),
                "CPU time distribution (s)", TDigestHistogram.fromValue(cpuTimeSeconds),
                "Scheduled time distribution (s)", TDigestHistogram.fromValue(wallTimeSeconds),
                "Blocked time distribution (s)", TDigestHistogram.fromValue(blockedWallSeconds))));
    }
```

So in summary, `metrics` field at the operatorStatistics can have TDigestHistogram but `connectorMetrics` field cannot. 

https://trinodb.slack.com/archives/CGB0QHWSW/p1647483959910239

```
2022-03-15T16:17:56.469+0800    ERROR   Task-20220315_081744_00000_wy3gg.1.3.0-228      io.trino.event.SplitMonitor     Error processing split completion event for task 20220315_081744_00000_wy3gg.1.3.0
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.airlift.stats.TDigest and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.trino.operator.DriverStats["operatorStats"]->com.google.common.collect.RegularImmutableList[0]->io.trino.operator.OperatorStats["connectorMetrics"]->java.util.ImmutableCollections$MapN["iceberg_indexReadTimeInMillis"]->io.trino.plugin.base.metrics.TDigestHistogram["digest"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
        at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:46)
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:29)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:657)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeTypedFields(MapSerializer.java:1027)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:779)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
        at com.fasterxml.jackson.databind.ser.std.JsonValueSerializer.serialize(JsonValueSerializer.java:253)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4569)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3822)
        at io.trino.event.SplitMonitor.splitCompletedEvent(SplitMonitor.java:108)
        at io.trino.event.SplitMonitor.splitCompletedEvent(SplitMonitor.java:53)
        at io.trino.execution.SqlTaskExecution$1.onSuccess(SqlTaskExecution.java:570)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1139)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by leetcode-1533** [comment]
This error seems is due to the serializer and deserializer of TDigest from TDigestHistogram's Java annotation not successfully recognized at the trino-hive package.

**Comment by leetcode-1533** [comment]
https://trinodb.slack.com/archives/CGB0QHWSW/p1647483959910239

**Comment by sopel39** [comment]
I'm not sure why it's not picked up. Maybe it's due to some classloader issue. cc @electrum

**Comment by electrum** [comment]
The problem is that TDigestHistogram uses databind annotations. We only support `com.fasterxml.jackson.annotation` for plugins. This can be fixed by changing TDigestHistogram to use supported annotations, probably with a separate constructor or factory for serialization.
