### ISSUE TITLE
 Failed to Read Parquet File with Decimal Precision > 16 for INT_64 Primitive Type

### ISSUE THREAD

**Issue by UrvashiDang354** [trinodb/trino#18271]
Description
An error occurs when trying to read parquet files that have a decimal column with precision greater than 16. This issue specifically arises when using the INT_64 primitive type and not enabling the useBatchedColumnReaders option.
```
Caused by: java.lang.IllegalArgumentException: Type length 18 should be <= 16 for short decimal column [localamount] optional int64 localamount (DECIMAL(18,6))
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:326)
        at io.trino.parquet.reader.ShortDecimalColumnReader.<init>(ShortDecimalColumnReader.java:49)
        at io.trino.parquet.reader.DecimalColumnReaderFactory.createReader(DecimalColumnReaderFactory.java:28)
        at io.trino.parquet.reader.ColumnReaderFactory.lambda$createDecimalColumnReader$3(ColumnReaderFactory.java:372)
        at java.base/java.util.Optional.map(Optional.java:260)
        at io.trino.parquet.reader.ColumnReaderFactory.createDecimalColumnReader(ColumnReaderFactory.java:372)
        at io.trino.parquet.reader.ColumnReaderFactory.create(ColumnReaderFactory.java:303)
        at io.trino.parquet.reader.ParquetReader.initializeColumnReaders(ParquetReader.java:491)
        at io.trino.parquet.reader.ParquetReader.advanceToNextRowGroup(ParquetReader.java:345)
        at io.trino.parquet.reader.ParquetReader.nextBatch(ParquetReader.java:301)
        at io.trino.parquet.reader.ParquetReader.nextPage(ParquetReader.java:274)
        at io.trino.plugin.hive.parquet.ParquetPageSource.getNextPage(ParquetPageSource.java:96)
        ... 14 more

```
Steps to reproduce :

1. Create table with a decimal column using the following syntax:
```
 `column_name` decimal(18,6))
```
2. Use Parquet File having INT_64 primitive type.

The error occurs in the following section of code:
```
     ShortDecimalColumnReader(PrimitiveField field, DecimalType parquetDecimalType)
    {
        super(field);
        this.parquetDecimalType = requireNonNull(parquetDecimalType, "parquetDecimalType is null");
        int typeLength = field.getDescriptor().getPrimitiveType().getTypeLength();
        checkArgument(typeLength <= 16, "Type length %s should be <= 16 for short decimal column %s", typeLength, field.getDescriptor());
    }

```

**Comment by UrvashiDang354** [comment]
https://github.com/trinodb/trino/pull/18312

**Comment by raunaqmorarka** [comment]
Closing this as legacy parquet reader code has now been removed https://github.com/trinodb/trino/pull/18639
