### ISSUE TITLE
Flaky TestHashAggregationOperator.testMemoryReservationYield, TestMarkDistinctOperator.testMemoryReservationYield on JDK 21

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#18272]
Continuation of https://github.com/trinodb/trino/issues/16933 this time for JDK 21.

```
2023-07-12T14:20:16.8851932Z java.lang.IllegalArgumentException: Invalid taskId another_query��.0.0
2023-07-12T14:20:16.8852703Z 	at io.trino.spi.QueryId.checkArgument(QueryId.java:114)
2023-07-12T14:20:16.8854695Z 	at io.trino.spi.QueryId.parseDottedId(QueryId.java:103)
2023-07-12T14:20:16.8855125Z 	at io.trino.execution.TaskId.getQueryId(TaskId.java:57)
2023-07-12T14:20:16.8855565Z 	at io.trino.memory.MemoryPool.reserve(MemoryPool.java:132)
2023-07-12T14:20:16.8856305Z 	at io.trino.operator.GroupByHashYieldAssertion.finishOperatorWithYieldingGroupByHash(GroupByHashYieldAssertion.java:108)
2023-07-12T14:20:16.8857199Z 	at io.trino.operator.TestTopNRankingOperator.testMemoryReservationYield(TestTopNRankingOperator.java:300)
2023-07-12T14:20:16.8857966Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
2023-07-12T14:20:16.8858517Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2023-07-12T14:20:16.8859079Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2023-07-12T14:20:16.8859651Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2023-07-12T14:20:16.8860125Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2023-07-12T14:20:16.8860617Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2023-07-12T14:20:16.8861191Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2023-07-12T14:20:16.8861756Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2023-07-12T14:20:16.8862313Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2023-07-12T14:20:16.8862922Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2023-07-12T14:20:16.8863386Z 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by wendigo** [comment]
cc @martint @findepi
