### ISSUE TITLE
Hive view translation containing a `UNION` between a `varchar(65535)` and a `char(1)` fails because of coercion to `char(65535)`

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#18337]
Assume having the table created in Hive

```
jdbc:hive2://localhost:10000/default> create table tbl(col char(1));
```

Now create the following Hive view:

```
0: jdbc:hive2://localhost:10000/default> create view v_tbl
. . . . . . . . . . . . . . . . . . . .> as
. . . . . . . . . . . . . . . . . . . .> select cast(col as varchar(65535)) active_flag from tbl
. . . . . . . . . . . . . . . . . . . .> union all
. . . . . . . . . . . . . . . . . . . .> select coalesce(col, 'N') as active_flag from tbl;
```

Use in `hive.properties` from Trino the setting

```
hive.translate-hive-views=true
```

Selecting in Trino from the view will not work:

```
trino> select * from hive.default.v_tbl;
Query 20230719_095212_00000_pyang failed: line 1:15: View 'hive.default.v_tbl' is stale or in invalid state: column [active_flag] of type char(65535) projected from query view at position 0 cannot be coerced to column [active_flag] of type varchar stored in view definition
io.trino.spi.TrinoException: line 1:15: View 'hive.default.v_tbl' is stale or in invalid state: column [active_flag] of type char(65535) projected from query view at position 0 cannot be coerced to column [active_flag] of type varchar stored in view definition
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.lambda$createScopeForView$56(StatementAnalyzer.java:2454)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.createScopeForView(StatementAnalyzer.java:2454)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.createScopeForView(StatementAnalyzer.java:2417)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2214)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:488)
	at io.trino.sql.tree.Table.accept(Table.java:60)
```

The Trino SQL retrieved from Coral is:

https://github.com/trinodb/trino/blob/1e188a17655d81dbf29ccd879f05c3f0d577cd6c/plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java#L229

```
SELECT CAST("tbl"."col" AS VARCHAR(65535)) AS "active_flag"
FROM "default"."tbl" AS "tbl"
UNION ALL
SELECT CASE WHEN "tbl0"."col" IS NOT NULL THEN "tbl0"."col" ELSE 'N' END AS "active_flag"
FROM "default"."tbl" AS "tbl0"
```

https://github.com/trinodb/trino/blob/55ecbe4a6f7ec860b16bf630d4ddd0874f176a4d/core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java#L3101

When we want the common super type for:

- `char(1)`
- `varchar(65535)`

```
Optional<Type> commonSuperType = typeCoercion.getCommonSuperType(outputFieldTypes[i], descFieldType);
```

we obtain `char(65535)`. This is linked to https://github.com/trinodb/trino/issues/9031

The type char(65535) can't be coerced to varchar reason why the staleness check is not passing

https://github.com/trinodb/trino/blob/55ecbe4a6f7ec860b16bf630d4ddd0874f176a4d/core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java#L4631-L4639

A possible workaround for the query above is flipping the `UNION` `SELECT` queries which would cause the `SELECT` from `v_tbl` in Trino to work:

```
0: jdbc:hive2://localhost:10000/default> create view v_tbl
. . . . . . . . . . . . . . . . . . . .> as
. . . . . . . . . . . . . . . . . . . .> select coalesce(col, 'N') as active_flag from tbl
. . . . . . . . . . . . . . . . . . . .> union all
. . . . . . . . . . . . . . . . . . . .> select cast(col as varchar(65535)) active_flag from tbl;
```

This is caused by how `UNION` is being analyzed 

https://github.com/trinodb/trino/blob/bb88cbd5a3c33dd89f41ad9bd505065cc21af7a4/core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java#L3101-L3112

I tried a CTAS with the output of the Hive view translation and met the same kind of issues.
The problem is rather linked to Trino. See https://github.com/trinodb/trino/issues/4394
```
CREATE TABLE test1 AS 
   SELECT CAST("tbl"."col" AS VARCHAR(65535)) AS "active_flag"
       FROM "default"."tbl" AS "tbl"
   UNION ALL
   SELECT CASE WHEN "tbl0"."col" IS NOT NULL THEN "tbl0"."col" ELSE 'N' END AS "active_flag"
       FROM "default"."tbl" AS "tbl0";
```

```
Query 20230727_195003_00018_yapbu failed: Unsupported Hive type: char(65535). Supported CHAR types: CHAR(<=255).
io.trino.spi.TrinoException: Unsupported Hive type: char(65535). Supported CHAR types: CHAR(<=255).
```

**Comment by findinpath** [comment]
I have discussed the topic with @findepi  and got a few directions to potentially fix this kind of issue:

1. Change character literal treatment and char/varchar coercion in Trino by addressing #9031 .
2. Identify in Coral while doing the view translation that the types in the `UNION` branches of the selected columns differ and proactively do for char/varchar a `CAST` to the common Hive super-type of the columns. This direction needs potentially changes in the https://github.com/linkedin/coral library
cc @wmoustafa
4. While analyzing the outcome of the view translation query in Trino https://github.com/trinodb/trino/blob/1e188a17655d81dbf29ccd879f05c3f0d577cd6c/plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java#L229 do in the analysis phase the `CAST` to the correct common super type. This option would eventually require less changes than #9031 because it would be limited (currently) to Hive view translations.

**Comment by findinpath** [comment]
https://github.com/linkedin/coral/pull/442 has been merged
Using https://github.com/linkedin/coral/releases/tag/v2.2.9 to try out the workaround
