### ISSUE TITLE
Global OpenTelemetry conflict

### ISSUE THREAD

**Issue by gaeljw** [trinodb/trino#18348]
When upgrading from Trino JDBC driver 419 to 422, I'm facing initialization errors related to the global `OpenTelemetry` instance.

_To be honest, this might be an issue with our code and not Trino itself but I think it's worth creating the issue for people to find it anyway._

Our application also use OpenTelemetry on its own and is supposed to be the one defining/setting the global OTEL instance but apparently Trino driver tries to do the same.

The error we are facing (not on every environment, which makes me think it's also related to initialization order of various services) are:
```
Caused by: java.lang.IllegalStateException: GlobalOpenTelemetry.set has already been called. GlobalOpenTelemetry.set must be called only once before any calls to GlobalOpenTelemetry.get. If you are using the OpenTelemetrySdk, use OpenTelemetrySdkBuilder.buildAndRegisterGlobal instead. Previous invocation set to cause of this exception.
         at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:104)
         at io.opentelemetry.sdk.OpenTelemetrySdkBuilder.buildAndRegisterGlobal(OpenTelemetrySdkBuilder.java:85)
         at com.myapp.metrics.setup.OTELService.<init>(OTELService.scala:41)
         at com.myapp.metrics.setup.OTELService$$FastClassByGuice$$1270092a.newInstance(<generated>)
         at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
...
Caused by: java.lang.Throwable
         at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:112)
         at io.opentelemetry.api.GlobalOpenTelemetry.get(GlobalOpenTelemetry.java:82)
         at io.trino.jdbc.NonRegisteringTrinoDriver.instrumentClient(NonRegisteringTrinoDriver.java:68)
         at io.trino.jdbc.NonRegisteringTrinoDriver.connect(NonRegisteringTrinoDriver.java:62)
         at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
         at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
```

Our code is using Guice for dependency injection and is probably instantiating Trino driver (Hikari datasource) before our own OpenTelemetry setup in some cases.

Our code, for reference (Scala code actually that I translated to Java to make it easier to understand):
```java
@Singleton
class OTELService implements Provider<OpenTelemetry> {

  OpenTelemetrySdk openTelemetrySdk = OpenTelemetrySdk
    .builder()
    .setMeterProvider(...)
    .buildAndRegisterGlobal();

  public OpenTelemetry get() {
    return openTelemetrySdk;
  }

}
```

Seems related to https://github.com/trinodb/trino/pull/17101.

I'm not sure what are the best practices around OpenTelemetry for apps and libs. I will look to enforce our code is called first to define the global instance of `OpenTelemetry` but not entirely sure if there's something that could be done in Trino driver to help?

**Comment by gaeljw** [comment]
In comparison, with Hikari, we are able to give our own `OpenTelemetry` instance rather than Hikari trying to get and set the global instance:

```java
var HikariDataSource datasource = // injected
var OpenTelemetry otel = // our own instance injected
var hikariTelemetry = HikariTelemetry.create(otel);
datasource.setMetricsTrackerFactory(hikariTelemetry.createMetricsTrackerFactory())
```

**Comment by nineinchnick** [comment]
The jdbc driver is supposed to detect when the opemtelemetry api is available and instrument the http client it's using. It should not configure opemtelemetry itself. I'll try to reproduce this.

**Comment by gaeljw** [comment]
I'll be happy to help by providing more details to reproduce if you need to :)

**Comment by nineinchnick** [comment]
When the JDBC driver checks if OpenTelemetry is configured, OTEL sets a _noop_ implementation to make subsequent checks cheaper: https://github.com/open-telemetry/opentelemetry-java/blob/abada8101825bdac76233a3fa499172a5cb5047a/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java#L82

Looks like you should configure OTEL earlier, before loading the JDBC driver.

**Comment by gaeljw** [comment]
> Looks like you should configure OTEL earlier, before loading the JDBC driver.

Yup, will look into enforcing that but that may not always be easy to do.

OTEL states [the following](https://opentelemetry.io/docs/instrumentation/java/manual/) though:
> As an aside, if you are writing library instrumentation, it is strongly recommended that you provide your users the ability to inject an instance of `OpenTelemetry` into your instrumentation code.

**Comment by nineinchnick** [comment]
That would also imply delaying this check, I mentioned. We can now provide objects other than strings as JDBC connection properties, so we can allow providing the OTEL explicitly.

**Comment by nineinchnick** [comment]
I suggest adding two connection properties:
* `OpenTelemetryType=AUTO|MANUAL|NONE`, defaults to `AUTO`, that calls `GlobalOpenTelemetry.get()`
* `OpenTelemetry` that requires an `OpenTelemetry` object when `OpenTelemetryType` is set to `MANUAL`

**Comment by gaeljw** [comment]
It's not clear to me how that would translate in terms of API or configuration: how would one pass the `OpenTelemetry` instance to Trino?

**Comment by nineinchnick** [comment]
Like this:
```
Properties driverProperties = new Properties();
OpenTelemetry openTelemetry = GlobalOpenTelemetry.get()
driverProperties.put("OpenTelemetry", openTelemetry);
Connection conn = DriverManager.getConnection(CONNECTION_URI, driverProperties)
```

**Comment by gaeljw** [comment]
I see, not sure how it fits in a declarative approach then. Most people (I guess) are used to define driver settings in a yaml/hocon file and their framework/library (Spring/Hikari/...) take care of the `Connection` instantiations.

**Comment by nineinchnick** [comment]
In that case, you'd have to use the auto instrumentation and set the global OpenTelemetry object. But adding these parameters would delay the check to when a new connection is opened.

**Comment by gaeljw** [comment]
FYI, I ended up forcing my `OpenTelemetry` instance to be loaded before Trino connection is loaded, which in my case, means before instantiating the Hikari connection pool.

**Comment by gaeljw** [comment]
For anyone coming here, I described a way to do it for PlayFramework apps using Guice at https://stackoverflow.com/a/76826177/5389127
