### ISSUE TITLE
Flaky/broken TestIcebergMinioOrcConnectorTest.testOptimizeTableAfterDeleteWithFormatVersion2

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#18408]
```
2023-07-25T11:24:34.8687072Z [ERROR] io.trino.plugin.iceberg.TestIcebergMinioOrcConnectorTest.testOptimizeTableAfterDeleteWithFormatVersion2  Time elapsed: 0.985 s  <<< FAILURE!
2023-07-25T11:24:34.8687852Z java.lang.AssertionError: 
2023-07-25T11:24:34.8688283Z 
2023-07-25T11:24:34.8688568Z Expected size: 1 but was: 2 in:
2023-07-25T11:24:34.8689543Z ["s3://test-iceberg-orc-13rbja3ybl/iceberg_data/tpch/test_optimize_pi4c2ru9tp-a865d1104ae34733ae8c0aeb6bad4ebb/data/20230725_111220_05377_agmni-6678f086-b6e9-49d5-b8d1-ec7ce0b3b1c5.orc",
2023-07-25T11:24:34.8690607Z     "s3://test-iceberg-orc-13rbja3ybl/iceberg_data/tpch/test_optimize_pi4c2ru9tp-a865d1104ae34733ae8c0aeb6bad4ebb/data/20230725_111220_05377_agmni-8d315e4c-d105-426d-b785-513822e4f0ea.orc"]
2023-07-25T11:24:34.8691529Z 	at io.trino.plugin.iceberg.BaseIcebergConnectorTest.testOptimizeTableAfterDeleteWithFormatVersion2(BaseIcebergConnectorTest.java:5148)
2023-07-25T11:24:34.8692291Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-07-25T11:24:34.8692908Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-07-25T11:24:34.8693515Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-07-25T11:24:34.8694006Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-07-25T11:24:34.8694480Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2023-07-25T11:24:34.8694953Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2023-07-25T11:24:34.8695359Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2023-07-25T11:24:34.8695774Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2023-07-25T11:24:34.8696246Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2023-07-25T11:24:34.8696722Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2023-07-25T11:24:34.8697208Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-07-25T11:24:34.8697721Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-07-25T11:24:34.8698120Z 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by wendigo** [comment]
https://github.com/trinodb/trino/actions/runs/5655740141/job/15321566151#step:6:50460

**Comment by ebyhr** [comment]
Reverting #18388 fixed the failure as far as I tried locally. 

@gaurav8297 @raunaqmorarka Could you confirm this issue?
