### ISSUE TITLE
Flaky TestDeltaLakeAdlsConnectorSmokeTest.testDeltaLakeTableLocationChangedPartitioned

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#18509]
The test failed in https://github.com/trinodb/trino/actions/runs/5745174053/job/15573014949?pr=17477
Unfortunately, there was no helpful error message. 
```
Error:  io.trino.plugin.deltalake.TestDeltaLakeAdlsConnectorSmokeTest.testDeltaLakeTableLocationChangedPartitioned[true, true](3)  Time elapsed: 3.928 s  <<< FAILURE!
java.lang.RuntimeException: Timed out waiting on table to reflect new data from new location
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testDeltaLakeTableLocationChanged(BaseDeltaLakeConnectorSmokeTest.java:1452)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testDeltaLakeTableLocationChangedPartitioned(BaseDeltaLakeConnectorSmokeTest.java:1374)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/9241534805/job/25423167186
