### ISSUE TITLE
Run-as identity must be set for a run-as definer view

### ISSUE THREAD

**Issue by antonysouthworth-halter** [trinodb/trino#18573]
Hi

I am experimenting with using Trino as an alternative and/or supplement to Amazon Athena. For this basic test I just want to try some sample queries against our existing data in S3, using Glue as the Hive metastore.

I have set up the [Docker container](https://trino.io/docs/current/installation/containers.html) on my workstation with the following shell script:

```bash
#!/bin/bash
set -euo pipefail

mkdir -p trino-catalogs
cat >trino-catalogs/mycatalog.properties <<EOF
connector.name=hive
hive.metastore=glue
hive.metastore.glue.region=ap-southeast-2
hive.hive-views.run-as-invoker=true
EOF

docker kill trino || true
docker rm trino || true

docker run \
  --name trino \
  -d \
  -p 8080:8080 \
  -e AWS_ACCESS_KEY_ID=xxx \
  -e AWS_SECRET_ACCESS_KEY=xxx \
  -e AWS_SESSION_TOKEN=xxx \
  -e AWS_DEFAULT_REGION=ap-southeast-2 \
  -v "$(pwd)/trino-catalogs/:/etc/trino/catalog" \
  trinodb/trino

while [ "$(docker inspect --format='{{json .State.Health.Status}}' trino)" != '"healthy"' ]
do
  sleep 1
done
```

I then open the Trino CLI with `docker exec -it trino trino --catalog=mycatalog --schema=halter`.

But when I execute the SQL statement `select * from <schema>.<view-name> limit 10` Trino responds with the following error:

```
Run-as identity must be set for a run-as definer view: <catalog>.<schema>.<view-name>
```

I don't understand this error message at all. Does anyone know what I need to do to allow Trino to access my data?

The view I am trying to access was created from the Athena query editor in the AWS console.

**Comment by antonysouthworth-halter** [comment]
#9227 and #12221 would indicate to me that `hive.hive-views.run-as-invoker=true` should fix this issue? but you can see I already set that and I still get the error.

[this](https://github.com/trinodb/trino/blob/39271c569631dbfb005f3b17d9d0596393bedac4/core/trino-main/src/main/java/io/trino/metadata/ViewDefinition.java#L81) seems to be the offending line, this lines up with this stack trace I pulled from the Trino web UI:

<details><summary>click to expand</summary>

```
io.trino.spi.TrinoException: Run-as identity must be set for a run-as definer view: mycatalog.halter.cow_behaviour_bins
	at io.trino.metadata.ViewDefinition.<init>(ViewDefinition.java:81)
	at io.trino.metadata.ViewDefinition.<init>(ViewDefinition.java:58)
	at io.trino.metadata.MetadataManager.lambda$getView$20(MetadataManager.java:1226)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.trino.metadata.MetadataManager.getView(MetadataManager.java:1226)
	at io.trino.tracing.TracingMetadata.getView(TracingMetadata.java:784)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2211)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:488)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:505)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:4503)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2981)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:488)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:505)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:513)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1501)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:488)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:505)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:467)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:97)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:270)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:205)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:844)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)
	at io.trino.$gen.Trino_422____20230808_011948_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

I'm guessing the view created by Athena actually has "run as" set to null rather than false.

**Comment by antonysouthworth-halter** [comment]
figured it out after asking AWS Support, seems it's a known issue with views created by the V2 Athena Engine.

The V2 engine uses an old version of Trino (actually presto) that does not define the security for the views.

The V3 engine _does_... but still seems to break with `Catalog awsdatacatalog does not exist` 🤷

**Comment by hafizmujadidKhalid** [comment]
@antonysouthworth-halter!
Were you able to solve this issue?
