### ISSUE TITLE
Inconsistent metadata handling in Kafka connector

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#18600]
`KafkaMetadata.listTableColumns` may succeed when called with `SchemaTablePrefix` pointing at specific table, even though `getTableHandle` fails with

```
io.trino.spi.TrinoException: Internal Kafka column names conflict with column names from the table. Consider changing kafka.internal-column-prefix configuration property. topic=write_test.test_internal_fields_prefix_3awwm6t2t6, Conflicting names=[_key]
	at io.trino.plugin.kafka.KafkaMetadata.getColumnHandles(KafkaMetadata.java:159)
	at io.trino.plugin.kafka.KafkaMetadata.lambda$getTableHandle$0(KafkaMetadata.java:103)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.trino.plugin.kafka.KafkaMetadata.getTableHandle(KafkaMetadata.java:93)
	at io.trino.plugin.kafka.KafkaMetadata.getTableHandle(KafkaMetadata.java:63)
	at io.trino.spi.connector.ConnectorMetadata.getTableHandle(ConnectorMetadata.java:130)
```

This points at inconsistency: `KafkaMetadata.getTableHandle` verified there is no conflict between topic's and internal column names, whereas `KafkaMetadata.getTableMetadata` does not and simply adds the internal columns to the list.

**Comment by athultr1997** [comment]
@findepi What should happen if we do a `SELECT * FROM information_schema.columns` when one of the tables in kafka is having conflicting schema ? Should the conflict exception be thrown ? If so this would alter the `TestKafkaConnectorTest` significantly since many of the tests consider the invalid `TABLE_INTERNAL_FIELD_PREFIX` to not throw an exception.
