### ISSUE TITLE
Kudu connector fails with "Unexpected java value for column {decimal column}: Slice" when querying with predicate on long decimal column

### ISSUE THREAD

**Issue by antoinemartin59000** [trinodb/trino#1861]
I have this table:
```
CREATE TABLE default.event_decimal (
    serialno varchar WITH (primary_key = true),
    num_decimal1 decimal(38,20),
    num_decimal2 decimal(38,20)
) WITH (
    partition_by_hash_columns = ARRAY['serialno'],
    partition_by_hash_buckets = 4,
    number_of_replicas = 1
);
```
When executing the bellow query with Dbeaver 6.2.2.201910072100 (presto-jdbc-318.jar):
select * from default.event_decimal where num_decimal1 = 3;

This exception is raised:
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [65536]: Query failed (#20191016_112743_00259_zxqn7): Unexpected java value for column num_decimal: Slice{base=[J@40f2ae, address=16, length=16}(class io.airlift.slice.Slice)
               at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
               at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:463)
               at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
               at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:148)
               at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:394)
               at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:764)
               at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2928)
               at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
               at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:148)
               at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
               at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3427)
               at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
               at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Query failed (#20191016_112743_00259_zxqn7): Unexpected java value for column num_decimal: Slice{base=[J@40f2ae, address=16, length=16}(class io.airlift.slice.Slice)
               at io.prestosql.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1839)
               at io.prestosql.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1749)
               at io.prestosql.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:118)
               at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:249)
               at io.prestosql.jdbc.PrestoStatement.execute(PrestoStatement.java:227)
               at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
               at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
               ... 12 more
Caused by: java.lang.IllegalStateException: Unexpected java value for column num_decimal: Slice{base=[J@40f2ae, address=16, length=16}(class io.airlift.slice.Slice)
               at io.prestosql.plugin.kudu.KuduClientSession.createComparisonPredicate(KuduClientSession.java:561)
               at io.prestosql.plugin.kudu.KuduClientSession.createEqualsPredicate(KuduClientSession.java:520)
               at io.prestosql.plugin.kudu.KuduClientSession.addConstraintPredicates(KuduClientSession.java:474)
               at io.prestosql.plugin.kudu.KuduClientSession.buildKuduSplits(KuduClientSession.java:149)
               at io.prestosql.plugin.kudu.KuduSplitManager.getSplits(KuduSplitManager.java:47)
               at io.prestosql.split.SplitManager.getSplits(SplitManager.java:83)
               at io.prestosql.sql.planner.DistributedExecutionPlanner$Visitor.visitScanAndFilter(DistributedExecutionPlanner.java:189)
               at io.prestosql.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:257)
               at io.prestosql.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:149)
               at io.prestosql.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
               at io.prestosql.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:119)
               at io.prestosql.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:124)
               at io.prestosql.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:96)
               at io.prestosql.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:433)
               at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:339)
               at io.prestosql.$gen.Presto_320____20191015_083122_1.run(Unknown Source)
               at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:239)
               at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$4(LocalDispatchQuery.java:107)
               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
               at java.lang.Thread.run(Thread.java:748)
```
In KuduClientSession.createComparisonPredicate(), TypeHelper.getJavaValue(type, value) seems to return an object of type Slice. But this is not handled.

**Comment by findepi** [comment]
`decimal(n, x)` for n <= 18 are represented as `long` values (8 byte) (aka "short decimals")
`(decimal(n, x)` for n > 18 are represented as 16 byte `Slice` values (aka "long decimals")

Seems Kudu can't properly handle the so called "long decimal" values.

**Comment by hassanahmadkhani** [comment]
in presto 333 kudu connector works fine for decimal fields

Create Table :
`CREATE TABLE kudu.default.users ( 
  user_id int WITH (primary_key = true),
  dec_filed1 DECIMAL(16,2),
  dec_filed2 DECIMAL(18,4),
  dec_filed3 DECIMAL(38,4),
  first_name varchar,
  last_name varchar
) WITH (
  partition_by_hash_columns = ARRAY['user_id'],
  partition_by_hash_buckets = 2,
  number_of_replicas=1
);
`


Insert :
`INSERT INTO kudu.default.users VALUES (1, 1.1 , 1.2 , 1.3,'Hassan', 'Ahmadkhani');
INSERT INTO kudu.default.users VALUES (3, 11111111111.11 , 11111111111111.2222 , 1111111111111111111111111111.333,'Hassan', 'Ahmadkhani');
`

-------- Sample Queries

`presto> select * from kudu.default.users where dec_filed1=1.1;
`

Result : 
`       1 |       1.10 |     1.2000 |     1.3000 | Hassan     | Ahmadkhani
(1 row)`



`presto> select * from kudu.default.users;
`

Result :
`        1 |           1.10 |              1.2000 |                            1.3000 | Hassan     | Ahmadkhani
       3 | 11111111111.11 | 11111111111111.2222 | 1111111111111111111111111111.3330 | Hassan     | Ahmadkhani
(2 rows)`



`presto> select * from kudu.default.users where dec_filed2=11111111111111.2222;
`

Result :
`       3 | 11111111111.11 | 11111111111111.2222 | 1111111111111111111111111111.3330 | Hassan     | Ahmadkhani
(1 row)`


and for decimal(38,4)
`presto> select * from kudu.default.users where dec_filed3=1111111111111111111111111111.333;
`


Result :


`  3 | 11111111111.11 | 11111111111111.2222 | 1111111111111111111111111111.3330 | Hassan     | Ahmadkhani
(1 row)`

**Comment by hashhar** [comment]
Thanks for confirming @hassanahmadkhani . It was indeed fixed in https://github.com/trinodb/trino/commit/dd2f342220c0335860cec2aa59dca61c5513027f (first landed in 327) while the bug report if from 320.

I'm closing this issue since it's resolved.
