### ISSUE TITLE
Read iceberg v2 table which has equality deletes with nested fields failed

### ISSUE THREAD

**Issue by Heltman** [trinodb/trino#18625]
Iceberg v2 table with equality deletes should support nested fields as delete column, but when read, it will throw error like below:
```log
2023-08-09T15:16:47.338-0600	ERROR	stage-scheduler	io.trino.execution.StageStateMachine	Stage 20230809_211647_00008_s6wq4.0 failed
io.trino.spi.TrinoException: Multiple entries with same key: 3=f1 and 3=root.f1
	at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:142)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:299)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
```

For example:
```sql
-- create schema below
CREATE TABLE iceberg.default.test (id BIGINT, root ROW(nested BIGINT, nested_other BIGINT);
-- delete by `nested` to generate equality deletes
...
-- query table throw exception
SELECT * FROM iceberg.default.test;
```

**Comment by Heltman** [comment]
See: https://github.com/trinodb/trino/pull/17115#discussion_r1289209308
find by @findinpath

**Comment by ebyhr** [comment]
> -- delete by `nested` to generate equality deletes

Please share the exact steps to reproduce.

**Comment by findinpath** [comment]
@Heltman can you pls add a test PR to showcase this limitation?

**Comment by Heltman** [comment]
Can we use sql to write a delete file to iceberg v2 table? Or I just add a unit test for this problem? @findinpath

**Comment by findinpath** [comment]
> Or I just add a unit test for this problem? 

unit test will be just fine - similar to https://github.com/trinodb/trino/pull/17115#discussion_r1289209308 

so that we can showcase that the current Trino code has an issue.

**Comment by findinpath** [comment]
@Heltman  is this still relevant?

**Comment by ebyhr** [comment]
This issue still remains.
