### ISSUE TITLE
Cannot read partition & id or name column mapping mode tables created by `CREATE TABLE AS SELECT`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#18661]
Transaction log created by `CREATE TABLE AS SELECT` is incorrect when it's partitioned with id or name column mapping mode. 
```sql
CREATE TABLE test  WITH (column_mapping_mode = 'name',partitioned_by = ARRAY['b']) AS 
SELECT 1 AS a, 2 AS b;
```

```
SELECT * FROM test;
io.trino.spi.TrinoException: DELTA_LAKE_BAD_DATA
	at io.trino.plugin.deltalake.DeltaLakePageSource.getNextPage(DeltaLakePageSource.java:189)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:299)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:555)
	at io.trino.$gen.Trino_testversion____20230813_223059_75.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

**Comment by sumanshusamarora** [comment]
Thanks @ebyhr
