### ISSUE TITLE
Hive fails to create bucketed table when native writers disable and creating empty buckets enabled

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#18667]
Reproducible with `io.trino.plugin.hive.HiveQueryRunner#main`

```sql
SET SESSION hive.create_empty_bucket_files = true;
SET SESSION hive.text_file_native_writer_enabled = false;

CREATE TABLE foo WITH (format='TEXTFILE', bucketed_by=ARRAY['regionkey'], bucket_count=16)
AS TABLE tpch.tiny.region;
```

```
SET SESSION
SET SESSION

Query 20230814_102349_00035_6pbbn, FAILED, 3 nodes
http://localhost:8080/ui/query.html?20230814_102349_00035_6pbbn
Splits: 95 total, 90 done (94.74%)
CPU Time: 0.0s total,   166 rows/s,     0B/s, 57% active
Per Node: 0.1 parallelism,    21 rows/s,     0B/s
Parallelism: 0.4
Peak Memory: 27.8KB
0.08 [5 rows, 0B] [64 rows/s, 0B/s]

Query 20230814_102349_00035_6pbbn failed: Writing not supported for StorageFormat{serde=org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, inputFormat=org.apache.hadoop.mapred.TextInputFormat, outputFormat=org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat}
io.trino.spi.TrinoException: Writing not supported for StorageFormat{serde=org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, inputFormat=org.apache.hadoop.mapred.TextInputFormat, outputFormat=org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat}
	at io.trino.plugin.hive.HiveMetadata.lambda$createEmptyFiles$58(HiveMetadata.java:1911)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.trino.plugin.hive.HiveMetadata.createEmptyFiles(HiveMetadata.java:1911)
	at io.trino.plugin.hive.HiveMetadata.finishCreateTable(HiveMetadata.java:1748)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishCreateTable(ClassLoaderSafeConnectorMetadata.java:548)
	at io.trino.tracing.TracingConnectorMetadata.finishCreateTable(TracingConnectorMetadata.java:618)
	at io.trino.metadata.MetadataManager.finishCreateTable(MetadataManager.java:1047)
	at io.trino.tracing.TracingMetadata.finishCreateTable(TracingMetadata.java:580)
	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$4(LocalExecutionPlanner.java:4135)
	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:555)
	at io.trino.$gen.Trino_testversion____20230814_101939_75.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/18235 looks potentially related.
