### ISSUE TITLE
Flaky test TestHiveConnectorTest.testScaleWriters

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#18670]
When I run `TestHiveConnectorTest`  locally, `testScaleWriters` test fails very frequently.

Example failure when run locally

```
java.lang.AssertionError: Failure for format AVRO with properties {}

	at org.testng.Assert.fail(Assert.java:83)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testWithStorageFormat(BaseHiveConnectorTest.java:8795)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testWithAllStorageFormats(BaseHiveConnectorTest.java:8782)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testScaleWriters(BaseHiveConnectorTest.java:4042)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.AssertionError: 
Expecting actual:
  1L
to be between:
  [2L, 3L]
```

**Comment by findepi** [comment]
cc @gaurav8297 @radek-starburst @sopel39 @raunaqmorarka

**Comment by findepi** [comment]
Seems pretty consistently failing for me

<img width="257" alt="image" src="https://github.com/trinodb/trino/assets/144328/fdc1d56b-bade-4338-8b24-7156b7067a45">

it seems always same message
```
java.lang.AssertionError: Failure for format ORC with properties {hive={csv_native_reader_enabled=true, json_native_reader_enabled=true, avro_native_reader_enabled=true, sequence_file_native_reader_enabled=true, text_file_native_writer_enabled=true, avro_native_writer_enabled=true, csv_native_writer_enabled=true, json_native_writer_enabled=true, regex_native_reader_enabled=true, text_file_native_reader_enabled=true, sequence_file_native_writer_enabled=true}}

	at org.testng.Assert.fail(Assert.java:83)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testWithStorageFormat(BaseHiveConnectorTest.java:8796)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testWithAllStorageFormats(BaseHiveConnectorTest.java:8783)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testScaleWriters(BaseHiveConnectorTest.java:4043)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.AssertionError: 
Expecting actual:
  1L
to be between:
  [2L, 3L]
```
