### ISSUE TITLE
Query execution error when using a sub-query with a table function.

### ISSUE THREAD

**Issue by vineet-k** [trinodb/trino#18712]
When attempting to execute the following query that includes a sub-query using a table function, an error occurs during query execution. The query involves selecting data from a table named 'vchar_test' in the 'postgresql.public' schema and utilizing a table function 'batch_process'.

Query:
`select (SELECT tf.processed FROM TABLE(batch_process(COLUMN => vchar1, SECRET => 'AES128')) tf WHERE tf.original = vchar1) from postgresql.public.vchar_test`

The implementation for the sample table function 'batch_process' used in the above query is provided in the code snippet below:
```
package io.trino.operator.table;

import static com.google.common.collect.Iterables.getOnlyElement;
import static io.trino.metadata.GlobalFunctionCatalog.BUILTIN_SCHEMA;
import static io.trino.spi.StandardErrorCode.INVALID_FUNCTION_ARGUMENT;
import static io.trino.spi.function.table.ReturnTypeSpecification.GenericTable.GENERIC_TABLE;
import static io.trino.spi.function.table.TableFunctionProcessorState.Finished.FINISHED;
import static io.trino.spi.function.table.TableFunctionProcessorState.Processed.usedInputAndProduced;
import static io.trino.spi.type.VarcharType.VARCHAR;

import java.util.List;
import java.util.Map;
import java.util.Optional;

import com.google.common.collect.ImmutableList;
import com.google.inject.Provider;

import io.airlift.slice.Slice;
import io.trino.plugin.base.classloader.ClassLoaderSafeConnectorTableFunction;
import io.trino.spi.TrinoException;
import io.trino.spi.connector.ConnectorAccessControl;
import io.trino.spi.connector.ConnectorSession;
import io.trino.spi.connector.ConnectorTransactionHandle;
import io.trino.spi.function.table.AbstractConnectorTableFunction;
import io.trino.spi.function.table.Argument;
import io.trino.spi.function.table.ConnectorTableFunction;
import io.trino.spi.function.table.ConnectorTableFunctionHandle;
import io.trino.spi.function.table.Descriptor;
import io.trino.spi.function.table.ScalarArgument;
import io.trino.spi.function.table.ScalarArgumentSpecification;
import io.trino.spi.function.table.TableFunctionAnalysis;
import io.trino.spi.function.table.TableFunctionDataProcessor;
import io.trino.spi.function.table.TableFunctionProcessorProvider;

public class BatchProcess
        implements Provider<ConnectorTableFunction>
{
    public static final String SCHEMA_NAME = "system";
    public static final String NAME = "batch_process";

    @Override
    public ConnectorTableFunction get()
    {
        return new ClassLoaderSafeConnectorTableFunction(new BatchProcessFunction(), getClass().getClassLoader());
    }

    public static class BatchProcessFunction
            extends AbstractConnectorTableFunction
    {
        private static final String COLUMN_ARGUMENT_NAME = "COLUMN";
        private static final String PROCESS_ARGUMENT_NAME = "PROCESS";

        public BatchProcessFunction()
        {
            super(
                    BUILTIN_SCHEMA,
                    NAME,
                    List.of(ScalarArgumentSpecification.builder()
                                .name(COLUMN_ARGUMENT_NAME)
                                .type(VARCHAR)
                                .build(),
                            ScalarArgumentSpecification.builder()
                                .name(PROCESS_ARGUMENT_NAME)
                                .type(VARCHAR)
                                .build()),
                    GENERIC_TABLE);
        }

        @Override
        public TableFunctionAnalysis analyze(
                ConnectorSession session,
                ConnectorTransactionHandle transaction,
                Map<String, Argument> arguments,
                ConnectorAccessControl accessControl)
        {
            String columnValue = ((Slice) ((ScalarArgument) arguments.get(COLUMN_ARGUMENT_NAME)).getValue()).toStringUtf8();
            if (columnValue == null) {
                throw new TrinoException(INVALID_FUNCTION_ARGUMENT, "Column is null");
            }

            String processValue = ((Slice) ((ScalarArgument) arguments.get(PROCESS_ARGUMENT_NAME)).getValue()).toStringUtf8();
            if (processValue == null) {
                throw new TrinoException(INVALID_FUNCTION_ARGUMENT, "Process is null");
            }

            ImmutableList.Builder<Descriptor.Field> returnedColumns = ImmutableList.builder();
            returnedColumns.add(new Descriptor.Field("original", Optional.of(VARCHAR)));
            returnedColumns.add(new Descriptor.Field("processed", Optional.of(VARCHAR)));
            List<Descriptor.Field> returnedType = returnedColumns.build();
            
            return TableFunctionAnalysis.builder()
            .handle(new BatchProcessFunctionHandle())
            .returnedType(new Descriptor(returnedType))
            .build();
        }
    }

    public static TableFunctionProcessorProvider getBatchProcessFunctionProcessorProvider()
    {
        return new TableFunctionProcessorProvider()
        {
            @Override
            public TableFunctionDataProcessor getDataProcessor(ConnectorTableFunctionHandle handle)
            {
                return input -> {
                    if (input == null) {
                        return FINISHED;
                    }
                    return usedInputAndProduced(getOnlyElement(input).orElseThrow());
                };
            }
        };
    }

    public record BatchProcessFunctionHandle()
            implements ConnectorTableFunctionHandle
    {
        // there's no information to remember. All logic is effectively delegated to the engine via `requiredColumns`.
    }
}
```

**Environment details:**
Trino Version: 422
database: PostgreSQL

**Comment by kokosing** [comment]
Can you please share the entire stack trace and the DDL for `postgresql.public.vchar_test`?

As I understand `vchar1` comes from the `postgresql.public.vchar_test`, so this is a correlated subquery. 

@kasiafi Do we support correlated subqueries with table function?

**Comment by vineet-k** [comment]
Below is the DDL for `postgresql.public.vchar_test`:
```
CREATE TABLE public.vchar_test (
	vchar1 varchar NULL,
	text1 text NULL,
	vchar2 varchar NULL
);
```

Additionally, the full stack trace is provided below:
```
trino> select (SELECT tf.processed FROM TABLE(batch_process(COLUMN => vchar1, SECRET => 'AES128')) tf WHERE tf.original = vchar1) from postgresql.public.vchar_test;
Query 20230816_141359_00000_9s7fj failed: line 1:64: Column 'vchar1' cannot be resolved
io.trino.spi.TrinoException: line 1:64: Column 'vchar1' cannot be resolved
        at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
        at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
        at io.trino.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:33)
        at io.trino.sql.analyzer.Scope.lambda$resolveField$7(Scope.java:227)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at io.trino.sql.analyzer.Scope.resolveField(Scope.java:227)
        at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:664)
        at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:581)
        at io.trino.sql.tree.Identifier.accept(Identifier.java:91)
        at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
        at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:604)
        at io.trino.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:479)
        at io.trino.sql.planner.ExpressionInterpreter.evaluateConstantExpression(ExpressionInterpreter.java:214)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeScalarArgument(StatementAnalyzer.java:1995)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeArgument(StatementAnalyzer.java:1868)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeArguments(StatementAnalyzer.java:1796)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTableFunctionInvocation(StatementAnalyzer.java:1598)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTableFunctionInvocation(StatementAnalyzer.java:487)
        at io.trino.sql.tree.TableFunctionInvocation.accept(TableFunctionInvocation.java:56)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:504)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:2764)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:487)
        at io.trino.sql.tree.AliasedRelation.accept(AliasedRelation.java:71)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:504)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:4490)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2968)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:487)
        at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:504)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:512)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1488)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:487)
        at io.trino.sql.tree.Query.accept(Query.java:107)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:504)
        at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:466)
        at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:460)
        at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.analyzeSubquery(ExpressionAnalyzer.java:2329)
        at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitSubqueryExpression(ExpressionAnalyzer.java:2274)
        at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitSubqueryExpression(ExpressionAnalyzer.java:581)
        at io.trino.sql.tree.SubqueryExpression.accept(SubqueryExpression.java:51)
        at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
        at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:604)
        at io.trino.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:485)
        at io.trino.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:3444)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:4644)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelectSingleColumn(StatementAnalyzer.java:4453)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:4239)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2975)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:487)
        at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:504)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:512)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1488)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:487)
        at io.trino.sql.tree.Query.accept(Query.java:107)
        at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:504)
        at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:466)
        at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:97)
        at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
        at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:270)
        at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:205)
        at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:844)
        at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)
        at io.trino.$gen.Trino_dev____20230816_141244_2.call(Unknown Source)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1623)
select (SELECT tf.processed FROM TABLE(batch_process(COLUMN => vchar1, SECRET => 'AES128')) tf WHERE tf.original = vchar1) from postgresql.public.vchar_test
```

**Comment by freakyzoidberg** [comment]
Shouldn't you quote `vchar1`  in batch_process COLUMN argument? The table function except a varchar here.

**Comment by martint** [comment]
The reason is that the expressions in the table function invocation are not being properly resolved against the outer query scope. Here's a simpler reproduction:

```sql
SELECT (
    SELECT *
    FROM TABLE(sequence(v, v)) s
) FROM (VALUES 1, 2, 3) t(v)
```

The query should produce:
```
1
2
3
```

But it fails with:

```
Query 20230818_221255_00009_z2hes failed: line 3:25: Column 'v' cannot be resolved
SELECT (
    SELECT *
    FROM TABLE(sequence(v, v)) s
                        ^--- at this location
) FROM (VALUES 1, 2, 3) t(v)
