### ISSUE TITLE
Flaky io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionJoinQueries.testJoinWithMultipleInSubqueryClauses

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#18752]
```
io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionJoinQueries.testJoinWithMultipleInSubqueryClauses -- Time elapsed: 5.468 s <<< FAILURE!
java.lang.AssertionError: 
For query 20230820_102103_00134_jjg4k: 
 SELECT * FROM (VALUES 1,2,3,4) t(x)  JOIN (VALUES 1,2,3,5) t2(y) ON (x in (VALUES 1,2)) = (y in (VALUES 1,2)) AND (x in (VALUES 1)) = (y in (VALUES 3))
not equal
Actual rows (up to 100 of 1 extra rows shown, 3 rows in total):
    [2, 5]
Expected rows (up to 100 of 2 missing rows shown, 4 rows in total):
    [2, 2]
    [2, 1]

	at org.testng.Assert.fail(Assert.java:94)
	at io.trino.testing.QueryAssertions.assertEqualsIgnoreOrder(QueryAssertions.java:382)
	at io.trino.testing.QueryAssertions.assertDistributedQuery(QueryAssertions.java:348)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:184)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:157)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:339)
	at io.trino.testing.AbstractTestJoinQueries.testJoinWithMultipleInSubqueryClauses(AbstractTestJoinQueries.java:836)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by wendigo** [comment]
Happens on master: https://github.com/trinodb/trino/actions/runs/5916705531/job/16044332781

**Comment by wendigo** [comment]
```
Error:    TestHiveFaultTolerantExecutionJoinQueries>AbstractTestJoinQueries.testJoinWithMultipleInSubqueryClauses:850->AbstractTestQueryFramework.assertQuery:339 For query 20230819_081231_00137_3kcyh: 
 SELECT * FROM (VALUES 1,2,3,4) t(x) left JOIN (VALUES 1,2,3,5) t2(y) ON (x in (VALUES 1,2,3)) = (y in (VALUES 1,2,3)) AND (x in (VALUES 1,2,4)) = (y in (VALUES 1,2,4))
not equal
Actual rows (up to 100 of 1 extra rows shown, 5 rows in total):
    [2, 3]
Expected rows (up to 100 of 2 missing rows shown, 6 rows in total):
    [2, 2]
    [2, 1]
```

https://github.com/trinodb/trino/actions/runs/5910210369/job/16031581718

**Comment by wendigo** [comment]
I'm suspecting this change: https://github.com/trinodb/trino/pull/18106 as first flaky occurance happened right after cc @dain

**Comment by losipiuk** [comment]
```
873e50e1d130ec365aa95b76fb99dc0c64843d64 is the first bad commit
commit 873e50e1d130ec365aa95b76fb99dc0c64843d64
Author: Dain Sundstrom <dain@iq80.com>
Date:   Mon Jun 26 20:18:52 2023 -0700
```

**Comment by losipiuk** [comment]
Sometime there is following exception logged prior to failed assertion:
```
2023-08-21T03:00:36.560-0600	ERROR	SplitRunner-0-81	io.trino.execution.executor.timesharing.TimeSharingTaskExecutor	Error processing Split 20230821_090036_00096_gmv9t.1.0.0-11  (start = 9.5920110344275E8, wall = 23 ms, cpu = 0 ms, wait = 2 ms, calls = 3)
java.lang.IllegalArgumentException: Invalid position 1 in block with 1 positions
	at io.trino.spi.block.BlockUtil.checkValidPosition(BlockUtil.java:70)
	at io.trino.spi.block.BlockUtil.checkReadablePosition(BlockUtil.java:76)
	at io.trino.spi.block.IntArrayBlock.isNull(IntArrayBlock.java:146)
	at io.trino.operator.FlatHashStrategy.valueNotDistinctFrom(FlatHashStrategy.java:254)
	at io.trino.operator.FlatHash.valueNotDistinctFrom(FlatHash.java:448)
	at io.trino.operator.FlatHash.matchInVector(FlatHash.java:241)
	at io.trino.operator.FlatHash.getIndex(FlatHash.java:221)
	at io.trino.operator.FlatHash.contains(FlatHash.java:184)
	at io.trino.operator.FlatGroupByHash.contains(FlatGroupByHash.java:173)
	at io.trino.operator.ChannelSet.contains(ChannelSet.java:66)
	at io.trino.operator.HashSemiJoinOperator$SemiJoinPages.process(HashSemiJoinOperator.java:210)
	at io.trino.operator.HashSemiJoinOperator$SemiJoinPages.process(HashSemiJoinOperator.java:145)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:359)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorOperatorAdapter.getOutput(WorkProcessorOperatorAdapter.java:173)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_testversion____20230821_090015_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by dain** [comment]
Here is a simpler reproduction:
```
        while (true) {
            assertQuery(
                    "SELECT * FROM (VALUES 1,2,3,4) t(x)  JOIN (VALUES 1,2,3,5) t2(y) ON (x in (VALUES 1,2,3)) = (y in (VALUES 1,2,3)) AND (x in (VALUES 1,2,4)) = (y in (VALUES 1,2,4))",
                    "VALUES (1,1), (1,2), (2,2), (2,1), (3,3)");
        }
```

**Comment by dain** [comment]
The issue is with the ChannelSet integration with the new FlatGrouByHash.  I'm working on a fix.
