### ISSUE TITLE
DROP TABLE may fail if drop_table metastore call is retried

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#18848]
```
tests               | 2023-08-29 18:55:29 INFO: FAILURE     /    io.trino.tests.product.hive.TestAbfsSyncPartitionMetadata.testDropPartition (Groups: azure) took 32.0 seconds
tests               | 2023-08-29 18:55:29 SEVERE: Failure cause:
tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20230829_131014_00063_65xm3): The following metastore delete operations failed: drop table default.test_sync_partition_metadata_drop_partition
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:55)
tests               | 	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
tests               | 	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
tests               | 	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
tests               | 	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
tests               | 	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:55)
tests               | 	at io.trino.tests.product.hive.BaseTestSyncPartitionMetadata.cleanup(BaseTestSyncPartitionMetadata.java:244)
tests               | 	at io.trino.tests.product.hive.BaseTestSyncPartitionMetadata.testDropPartition(BaseTestSyncPartitionMetadata.java:92)
tests               | 	at io.trino.tests.product.hive.TestAbfsSyncPartitionMetadata.testDropPartition(TestAbfsSyncPartitionMetadata.java:79)
tests               | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:1589)
tests               | Caused by: java.sql.SQLException: Query failed (#20230829_131014_00063_65xm3): The following metastore delete operations failed: drop table default.test_sync_partition_metadata_drop_partition
tests               | 	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
tests               | 	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:294)
tests               | 	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:254)
tests               | 	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
tests               | 	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
tests               | 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1931)
tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292)
tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298)
tests               | 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
tests               | 	at io.trino.jdbc.TrinoResultSet$AsyncIterator.lambda$new$1(TrinoResultSet.java:179)
tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
tests               | 	... 3 more
tests               | 	Suppressed: java.lang.Exception: Query: DROP TABLE test_sync_partition_metadata_drop_partition
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 		at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:55)
tests               | 		at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
tests               | 		at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
tests               | 		at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
tests               | 		at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
tests               | 		at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 		at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
tests               | 		at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:55)
tests               | 		at io.trino.tests.product.hive.BaseTestSyncPartitionMetadata.cleanup(BaseTestSyncPartitionMetadata.java:244)
tests               | 		at io.trino.tests.product.hive.BaseTestSyncPartitionMetadata.testDropPartition(BaseTestSyncPartitionMetadata.java:92)
tests               | 		at io.trino.tests.product.hive.TestAbfsSyncPartitionMetadata.testDropPartition(TestAbfsSyncPartitionMetadata.java:79)
tests               | 		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
tests               | 		at java.base/java.lang.reflect.Method.invoke(Method.java:578)
tests               | 		at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 		at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 		at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 		at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 		at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 		at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 		... 3 more
tests               | Caused by: io.trino.spi.TrinoException: The following metastore delete operations failed: drop table default.test_sync_partition_metadata_drop_partition
tests               | 	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeIrreversibleMetastoreOperations(SemiTransactionalHiveMetastore.java:2300)
tests               | 	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:1629)
tests               | 	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1287)
tests               | 	at io.trino.plugin.hive.HiveMetadata.commit(HiveMetadata.java:3729)
tests               | 	at io.trino.plugin.hive.HiveTransactionManager.lambda$commit$0(HiveTransactionManager.java:58)
tests               | 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
tests               | 	at io.trino.plugin.hive.HiveTransactionManager.commit(HiveTransactionManager.java:56)
tests               | 	at io.trino.plugin.hive.HiveConnector.commit(HiveConnector.java:236)
tests               | 	at io.trino.metadata.CatalogTransaction.commit(CatalogTransaction.java:85)
tests               | 	at io.trino.metadata.CatalogMetadata.commit(CatalogMetadata.java:154)
tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
tests               | 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
tests               | 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
tests               | 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
tests               | 	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:79)
Source)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:1589)
tests               | 	Suppressed: io.trino.spi.connector.TableNotFoundException: Table 'default.test_sync_partition_metadata_drop_partition' not found
tests               | 		at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.dropTable(ThriftHiveMetastore.java:1076)
tests               | 		at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.dropTable(BridgingHiveMetastore.java:219)
tests               | 		at io.trino.plugin.hive.metastore.ForwardingHiveMetastore.dropTable(ForwardingHiveMetastore.java:174)
tests               | 		at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.dropTable(CachingHiveMetastore.java:855)
tests               | 		at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.dropTable(CachingHiveMetastore.java:855)
tests               | 		at io.trino.plugin.hive.HiveMetastoreClosure.dropTable(HiveMetastoreClosure.java:197)
tests               | 		at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.lambda$prepareDropTable$0(SemiTransactionalHiveMetastore.java:1692)
tests               | 		at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$IrreversibleMetastoreOperation.run(SemiTransactionalHiveMetastore.java:3226)
tests               | 		at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.lambda$executeIrreversibleMetastoreOperations$18(SemiTransactionalHiveMetastore.java:2275)
tests               | 		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
tests               | 		at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:79)
tests               | 		... 3 more
```

**Comment by findepi** [comment]
we probably need logic similar to how Hive CREATE TABLE handles this
https://github.com/trinodb/trino/blob/37c9c81e6c5bf0f92d150f9d0d9349d9b5c53495/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java#L3268-L3269
or Delta's CREATE SCHEMA
https://github.com/trinodb/trino/blob/481fc7c76e21d1c687f2dd5f9c991b0f4dd98b07/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java#L774-L778

cc @ebyhr @findinpath

**Comment by ebyhr** [comment]
Doing the similar approach of CREATE looks difficult because we can't get query id from non-existing tables. 
Probably, just ignoring `TableNotFoundException` and deleting the directory if needed?

**Comment by findepi** [comment]
Would it be possible to ignore TableNotFoundException but only when there was a retry?
