### ISSUE TITLE
Queries Failed on trino 425 : `map keys cannot be null` (GENERIC_INTERNAL_ERROR)

### ISSUE THREAD

**Issue by wannte** [trinodb/trino#18863]
While changing trino version from 423 to 425, some of queries failed with `map keys cannot be null` exception.

Our query format looks like below. It happens when distinct `map<varchar, varchar>` table join query.
```sql
WITH WITH_1 (  
  SELECT
    DISTINCT 
    a, 
    b, 
    map_value -- map<varchar, varchar>
  FROM
    TABLE_1
)
SELECT
  WITH_1.a, WITH_1.b, TABLE_2.c
FROM
  TABLE_2
  JOIN WITH_1
  ON TABLE_2.a = WITH_1.a
  AND TABLE_2.b = WITH_1.b
```

```
java.lang.IllegalArgumentException: map keys cannot be null
	at io.trino.spi.block.MapHashTables.getHashPosition(MapHashTables.java:260)
	at io.trino.spi.block.MapHashTables.buildHashTableInternal(MapHashTables.java:139)
	at io.trino.spi.block.MapHashTables.buildHashTable(MapHashTables.java:130)
	at io.trino.spi.block.MapBlockBuilder.buildEntry(MapBlockBuilder.java:203)
	at io.trino.spi.type.MapType.readFlatToBlock(MapType.java:547)
	at io.trino.spi.type.ArrayType.readFlatElements(ArrayType.java:404)
	at io.trino.spi.type.ArrayType.lambda$readFlatToBlock$2(ArrayType.java:392)
	at io.trino.spi.block.ArrayBlockBuilder.buildEntry(ArrayBlockBuilder.java:158)
	at io.trino.spi.type.ArrayType.readFlatToBlock(ArrayType.java:391)
	at io.trino.spi.type.MapType.readFlatEntries(MapType.java:593)
	at io.trino.spi.type.MapType.lambda$readFlatToBlock$2(MapType.java:548)
	at io.trino.spi.block.MapBlockBuilder.buildEntry(MapBlockBuilder.java:194)
	at io.trino.spi.type.MapType.readFlatToBlock(MapType.java:547)
	at io.trino.spi.type.ArrayType.readFlatElements(ArrayType.java:404)
	at io.trino.spi.type.ArrayType.readFlat(ArrayType.java:376)
	at io.trino.operator.FlatHashStrategy.valueNotDistinctFrom(FlatHashStrategy.java:254)
	at io.trino.operator.FlatHash.valueNotDistinctFrom(FlatHash.java:448)
	at io.trino.operator.FlatHash.matchInVector(FlatHash.java:241)
	at io.trino.operator.FlatHash.getIndex(FlatHash.java:221)
	at io.trino.operator.FlatHash.putIfAbsent(FlatHash.java:197)
	at io.trino.operator.FlatGroupByHash.putIfAbsent(FlatGroupByHash.java:173)
	at io.trino.operator.FlatGroupByHash$AddNonDictionaryPageWork.process(FlatGroupByHash.java:315)
	at io.trino.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:444)
	at io.trino.operator.Driver.processInternal(Driver.java:400)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_425____20230829_225615_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by guyco33** [comment]
It might be related to change done by https://github.com/trinodb/trino/pull/18471
@dain

**Comment by dain** [comment]
@wannte I'm going to need some help tracking this down.  Are you 100% sure about the datat type in `WITH_1` is `map<varchar, varchar>:
```
WITH WITH_1 AS (
  SELECT
    DISTINCT map_value -- map<varchar, varchar>
```
I ask because the stacktrace implies that it is an `array<map<...>`

Also, can you try narrowing down issue further.  For example, the query you provided will optimize to something like:
```
SELECT DISTINCT map_value -- map<varchar, varchar>
FROM TABLE_1
WHERE conditions
LIMIT 1000
```

Also, are there a specific set of map values that cause this problem (BTW I'm focusing on the second comment as it looks more approachable).  Also are there more than 1000 distinct values in the query?

**Comment by dain** [comment]
@wannte ya, I cannot recreate a stack that looks like that unless the type is `Array<Map<?, Array<Map<?, Array<varchar>>>>`

**Comment by dain** [comment]
Does the entry you are running distinct on contain any null values?

**Comment by dain** [comment]
I have a reproduction, but answers to my questions above would help
