### ISSUE TITLE
Regression: Queries fail with INTERNAL ERROR since 423

### ISSUE THREAD

**Issue by guyco33** [trinodb/trino#18860]
Since `423` the following simple query fails:

```
WITH poly AS (
    SELECT 100 poly_id, ST_GeometryFromText('POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))') AS poly
)
SELECT o.lon, o.lat, p.poly_id
FROM (values (0.5, 0.5),(2, 2)) as o(lon,lat)
LEFT JOIN poly p
ON st_contains(p.poly, st_point(o.lon, o.lat))
```

stack trace:
```
java.lang.NullPointerException: Cannot read the array length because "original" is null
	at java.base/java.util.Arrays.copyOf(Arrays.java:3586)
	at it.unimi.dsi.fastutil.ints.IntArrayList.toArray(IntArrayList.java:748)
	at it.unimi.dsi.fastutil.ints.AbstractIntCollection.toIntArray(AbstractIntCollection.java:143)
	at io.trino.operator.PagesRTreeIndex.findJoinPositions(PagesRTreeIndex.java:177)
	at io.trino.operator.SpatialJoinOperator.processProbe(SpatialJoinOperator.java:249)
	at io.trino.operator.SpatialJoinOperator.getOutput(SpatialJoinOperator.java:218)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:555)
	at io.trino.$gen.Trino_423____20230830_141119_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

`INNER JOIN` and `RIGHT JOIN` works

**Comment by martint** [comment]
It's caused by 5e9bb46e0a48fe94c1a7e0f9b726e1020a94c85b

cc @wendigo
