### ISSUE TITLE
Query Pulsar using Trino

### ISSUE THREAD

**Issue by Atiqul-Islam** [trinodb/trino#18901]
I am wondering, what is the process for using pulsar sql with trino.

We have a pulsar cluster for streaming data and a trino cluster for querying data from different data sources.

Is it possible to query data on our pulsar topic using trino? We are using the process and plugins specified in the following article: https://pulsar.apache.org/docs/next/sql-deployment-configurations/
We a pulser cluster running Apache Pulsar 3.0.0 and a trino cluster running version 393 of trino.
The pulsar cluster and trino clusters are deployed using the helm charts specified below:
Pulsar -> https://pulsar.apache.org/charts
Trino -> https://valeriano-manassero.github.io/helm-charts
After copying the pulser-presto-plugin from https://archive.apache.org/dist/pulsar/pulsar-3.1.0/apache-pulsar-3.1.0-bin.tar.gz into the trino plugin folder, we are getting the following error messages from trino.

```
2023-09-02T03:28:00.026Z	ERROR	main	io.trino.server.Server	No service providers of type io.trino.spi.Plugin in the classpath: [file:/usr/lib/trino/plugin/pulsar-presto-connector/aircompressor-0.20.jar, file:/usr/lib/trino/plugin/pulsar-presto-connector/animal-sniffer-annotations-1.19.jar, file:/usr/lib/trino/plugin/pulsar-presto-connector/annotations-4.1.1.4.jar, file:/usr/lib/trino/plugin/pulsar-presto-connector/aopalliance-1.0.jar, ....]
	at com.google.common.base.Preconditions.checkState(Preconditions.java:821)
	at io.trino.server.PluginManager.loadPlugin(PluginManager.java:164)
	at io.trino.server.PluginManager.loadPlugin(PluginManager.java:154)
	at io.trino.server.ServerPluginsProvider.lambda$loadPlugins$1(ServerPluginsProvider.java:58)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at java.base/java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:184)
	at io.trino.util.Executors.executeUntilFailure(Executors.java:41)
	at io.trino.server.ServerPluginsProvider.loadPlugins(ServerPluginsProvider.java:53)
	at io.trino.server.PluginManager.loadPlugins(PluginManager.java:136)
	at io.trino.server.Server.doStart(Server.java:136)
	at io.trino.server.Server.lambda$start$0(Server.java:88)
	at io.trino.$gen.Trino_393____20230902_032751_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:88)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38
```	
	
Seems like some form of dependency related error. 
I am wondering is there any trino specific configuration, I need to use for using the connector?

**Comment by ebyhr** [comment]
Please ask the Pulsar community because the connector is managed in Pulsar side.
