### ISSUE TITLE
OAuth2 - Access Denied: User XXX cannot impersonate user trino

### ISSUE THREAD

**Issue by andreyolv** [trinodb/trino#18935]
I'm running cli using --external-authentication that is configured with OAuth2 for (AAD) Azure Active Directory.

I desire run query with my AAD user, not with user trino. I don't know why it tries to impersonate the user trino and how not to happen.

CLI log:
```
trino> select count(*) from tpch.tiny.nations;
Query 20230905_144732_00004_e5mj3 failed: Access Denied: User XXXXXX cannot impersonate user trino
io.trino.spi.security.AccessDeniedException: Access Denied: User XXXXXX cannot impersonate user trino
        at io.trino.spi.security.AccessDeniedException.denyImpersonateUser(AccessDeniedException.java:50)
        at io.trino.spi.security.AccessDeniedException.denyImpersonateUser(AccessDeniedException.java:45)
        at io.trino.plugin.base.security.FileBasedSystemAccessControl.checkCanImpersonateUser(FileBasedSystemAccessControl.java:251)
        at io.trino.plugin.base.security.ForwardingSystemAccessControl.checkCanImpersonateUser(ForwardingSystemAccessControl.java:61)
        at io.trino.security.AccessControlManager.lambda$checkCanImpersonateUser$2(AccessControlManager.java:230)
        at io.trino.security.AccessControlManager.systemAuthorizationCheck(AccessControlManager.java:1363)
        at io.trino.security.AccessControlManager.checkCanImpersonateUser(AccessControlManager.java:230)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.trino.plugin.base.util.LoggingInvocationHandler.handleInvocation(LoggingInvocationHandler.java:60)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
        at jdk.proxy2/jdk.proxy2.$Proxy107.checkCanImpersonateUser(Unknown Source)
        at io.trino.security.ForwardingAccessControl.checkCanImpersonateUser(ForwardingAccessControl.java:58)
        at io.trino.tracing.TracingAccessControl.checkCanImpersonateUser(TracingAccessControl.java:76)
        at io.trino.server.QuerySessionSupplier.createSession(QuerySessionSupplier.java:84)
        at io.trino.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:185)
        at io.trino.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:160)
        at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
        at io.trino.$gen.Trino_423____20230905_142519_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Coordinator log:
```
2023-09-05T14:47:32.062Z        DEBUG   dispatcher-query-6      io.trino.security.AccessControl Invocation of checkCanImpersonateUser(identity=Identity{user='XXXXXX', principal=XXXXXX}, userName='trino') took 66.30us and failed with io.trino.spi.security.AccessDeniedException: Access Denied: User XXXXXX cannot impersonate user trino
```

**Comment by andreyolv** [comment]
OK, if I add this to rules, it works:
```
{
            "catalogs": [
              {
                "user": "trino",
                "allow": "all"
              }
            ],
            "schemas": [
              {
                "user": "trino",
                "owner": true
              }
            ],
            "tables": [
              {
                "user": "trino",
                "privileges": ["SELECT", "INSERT", "DELETE", "UPDATE", "OWNERSHIP"]
              }
            ],
            "impersonation": [
              {
                "original_user": "XXXXX",
                "new_user": "trino"
              }
            ]
          }
```

But I would like to continue using the AAD user

**Comment by andreyolv** [comment]
I found solution [here](https://github.com/trinodb/trino/issues/11547).
Even with --external-authentication it is necessary to pass --user XXXX, otherwise user trino will be the default.

**Comment by deebify** [comment]
I had a similar issue [here](https://github.com/trinodb/trino/issues/20289)
