### ISSUE TITLE
Unable to read glue table stored as parquet files on s3 using glue catalog.

### ISSUE THREAD

**Issue by keenborder786** [trinodb/trino#18932]
I have a glue table stored on s3 as parquet files with the following structure:

- sold_item/
  - partition_0/
    - partition_1/
      - partition_2/
        - partition_3/

When I try to read the table using Presto v 0.283 with their glue catalog then it is read perfectly. However, when I try to read the same table using Trino v425 with glue catalog it gives me the following error:

```console
2023-09-05T11:11:25.381Z	ERROR	stage-scheduler	io.trino.execution.StageStateMachine	Stage 20230905_111121_00004_hnun5.0 failed
io.trino.spi.TrinoException: Failed to read Parquet file: s3://rayn-rudderstack-events/events/rudder-datalake/python_dev/sold_item/2023/06/08/14/1686234250.2Qs4ebWm23yYuoI2IoT0RP1gOWB.7a3dc880-7adf-4e13-bdd1-737696f7adc2.sold_item.15918b3c-5f9c-410d-9495-d3938cbdeba8.parquet
	at io.trino.plugin.hive.parquet.ParquetPageSource.handleException(ParquetPageSource.java:200)
	at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.lambda$createPageSource$1(ParquetPageSourceFactory.java:284)
	at io.trino.parquet.reader.ParquetBlockFactory$ParquetBlockLoader.load(ParquetBlockFactory.java:75)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:405)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:384)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:291)
	at io.trino.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.setupDictionaryBlockProjection(DictionaryAwarePageProjection.java:206)
	at io.trino.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.lambda$getResult$0(DictionaryAwarePageProjection.java:194)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:405)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:384)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:291)
	at io.trino.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:360)
	at io.trino.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:219)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:317)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:359)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils$BlockingProcess.process(WorkProcessorUtils.java:207)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:317)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:359)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:255)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:145)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IndexOutOfBoundsException: Range [0, 0 + 4) out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:82)
	at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:361)
	at java.base/java.util.Objects.checkFromIndexSize(Objects.java:413)
	at io.airlift.slice.Slice.getInt(Slice.java:278)
	at io.trino.parquet.reader.decoders.PlainByteArrayDecoders$BinaryPlainValueDecoder.read(PlainByteArrayDecoders.java:156)
	at io.trino.parquet.reader.decoders.PlainByteArrayDecoders$BinaryPlainValueDecoder.read(PlainByteArrayDecoders.java:135)
	at io.trino.parquet.reader.flat.FlatColumnReader$DataValuesBuffer.readNonNullValues(FlatColumnReader.java:358)
	at io.trino.parquet.reader.flat.FlatColumnReader.readNonNull(FlatColumnReader.java:188)
	at io.trino.parquet.reader.flat.FlatColumnReader.readPrimitive(FlatColumnReader.java:90)
	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:439)
	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:524)
	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:507)
	at io.trino.parquet.reader.ParquetReader.lambda$nextPage$3(ParquetReader.java:272)
	at io.trino.parquet.reader.ParquetBlockFactory$ParquetBlockLoader.load(ParquetBlockFactory.java:72)
	... 43 more
```

 My Catalog configuration are as follow:

```yaml
connector.name=hive
hive.metastore=glue
hive.s3.path-style-access=true
hive.s3.aws-access-key=
hive.s3.aws-secret-key=
hive.non-managed-table-writes-enabled=true
hive.parquet.use-column-names=true
hive.metastore.glue.region=us-east-1
hive.metastore.glue.aws-access-key=
hive.metastore.glue.aws-secret-key=

```

I have double-checked that my schema is correct in the glue catalog through parquet-tools. I don't understand why it works in Presto but not in Trino. Might be because of parquet version incompatibility or a possible bug in Trino. Please have a look and let me know.

**Comment by ebyhr** [comment]
Can you share the CREATE TABLE statement and attache the Parquet file? 

cc: @raunaqmorarka

**Comment by keenborder786** [comment]
Tables are being created by Glue Crawler but I still got the Create statement through sqlalchemy:

```console
CREATE EXTERNAL TABLE sold_item (
        `_timestamp` TIMESTAMP,
        channel STRING,
        context_destination_id STRING,
        context_destination_type STRING,
        context_ip STRING,
        context_library_name STRING,
        context_library_version STRING,
        context_request_ip STRING,
        context_source_id STRING,
        context_source_type STRING,
        event STRING,
        event_text STRING,
        id STRING,
        item_barcode STRING,
        item_description STRING,
        item_id INT,
        item_name STRING,
        item_owner INT,
        item_price INT,
        original_timestamp TIMESTAMP,
        received_at TIMESTAMP,
        sent_at TIMESTAMP,
        user_email STRING,
        user_id STRING,
        uuid_ts TIMESTAMP
)
PARTITIONED BY (
        partition_0 STRING,
        partition_1 STRING,
        partition_2 STRING,
        partition_3 STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
WITH SERDEPROPERTIES (
        'serialization.format' = '1'
)
STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION 's3://rayn-rudderstack-events/events/rudder-datalake/python_dev/sold_item/'
TBLPROPERTIES (
        'CrawlerSchemaDeserializerVersion' = '1.0',
        'CrawlerSchemaSerializerVersion' = '1.0',
        'UPDATED_BY_CRAWLER' = 'glue_crawler_events',
        'UpdatedByJobRun' = '12431da8-8e80-4873-bf55-4c1406425edb',
        'averageRecordSize' = '2070',
        'classification' = 'parquet',
        'compressionType' = 'none',
        'exclusions' = '["s3://rayn-rudderstack-events/events/rudder-datalake/python_dev/delta_tables/**"]',
        'inputformat' = 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat',
        'location' = 's3://rayn-rudderstack-events/events/rudder-datalake/python_dev/sold_item/',
        'objectCount' = '3779',
        'outputformat' = 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat',
        'recordCount' = '86942',
        'serde.serialization.lib' = 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe',
        'sizeKey' = '229071262',
        'typeOfData' = 'file',
        'useGlueParquetWriter' = 'true'
)
```

[1686234250.2Qs4ebWm23yYuoI2IoT0RP1gOWB.7a3dc880-7adf-4e13-bdd1-737696f7adc2.sold_item.15918b3c-5f9c-410d-9495-d3938cbdeba8.zip](https://github.com/trinodb/trino/files/12528848/1686234250.2Qs4ebWm23yYuoI2IoT0RP1gOWB.7a3dc880-7adf-4e13-bdd1-737696f7adc2.sold_item.15918b3c-5f9c-410d-9495-d3938cbdeba8.zip)

**Comment by keenborder786** [comment]
@ebyhr and @raunaqmorarka please see ^^

**Comment by raunaqmorarka** [comment]
I looked into the shared file. The issue here is that the `item_description` column has a `NULL` value in the data, but the column statistics about it incorrectly specify that the column has no nulls.
```
parquet meta ~/Downloads/1686234250.2Qs4ebWm23yYuoI2IoT0RP1gOWB.7a3dc880-7adf-4e13-bdd1-737696f7adc2.sold_item.15918b3c-5f9c-410d-9495-d3938cbdeba8.parquet

Created by: null
Properties: (none)
Schema:
message parquet_go_root {
 ...
  optional binary item_description (STRING) = 0;
...
}


Row group 0:  count: 11  3.081 kB records  start: 4  total(compressed): 33.896 kB total(uncompressed):34.900 kB
--------------------------------------------------------------------------------
                          type      encodings count     avg size   nulls   min / max
...
item_description          BINARY    S RB_     11        1.631 kB   0       "<p>The Overcooked Gourmet..." / "”A deserted island... a l..."
...
```

```
parquet check-stats ~/Downloads/1686234250.2Qs4ebWm23yYuoI2IoT0RP1gOWB.7a3dc880-7adf-4e13-bdd1-737696f7adc2.sold_item.15918b3c-5f9c-410d-9495-d3938cbdeba8.parquet
1686234250.2Qs4ebWm23yYuoI2IoT0RP1gOWB.7a3dc880-7adf-4e13-bdd1-737696f7adc2.sold_item.15918b3c-5f9c-410d-9495-d3938cbdeba8.parquet has corrupt stats: Number of nulls doesn't match.
```
Trino parquet reader has an optimisation to switch to a non-nulls optimized code path when no nulls are expected for a column based on column stats. That's why it runs into an error while reading the data because it's expecting actual data where there is a NULL (4th page, 7th row) due to the incorrect column statistics.
This would also give you incorrect result on a query like `SELECT item_description from sold_item WHERE item_description IS NULL` which will give empty result instead of a NULL due to the incorrect null statistic.
Please pursue a fix in the application which produced this file.
fyi @sopel39 @findepi @martint

**Comment by findepi** [comment]
thank you @raunaqmorarka for getting to the bottom of this
