### ISSUE TITLE
ParquetCorruptionException caused by cannot use empty rangeList

### ISSUE THREAD

**Issue by antonysouthworth-halter** [trinodb/trino#18985]
i get the same "cannot use empty rangeList" error in 414 (on Amazon EMR)

<details>
<summary>
stack trace
</summary>

```
io.trino.spi.TrinoException: Corrupted statistics for column "filter_farm_id" in Parquet file "s3://XXX/XXX/XXX/partition_metric_name=XXX/partition_utc_year=2023/partition_utc_month=08/partition_utc_day=26/225439bd-8e0c-4a7c-b992-cbdcc4ce779e.parquet.snappy". Corrupted column index: [Boundary order: UNORDERED
                      null count  min                                       max                                     
page-0                         0  <none>                                    <none>                                  
]
	at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:309)
	at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:183)
	at io.trino.plugin.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:216)
	at io.trino.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:154)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:49)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:62)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:266)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:194)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:360)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:241)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:256)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:146)
	at io.trino.operator.Driver.processInternal(Driver.java:402)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:305)
	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
	at io.trino.operator.Driver.process(Driver.java:297)
	at io.trino.operator.Driver.processForDuration(Driver.java:268)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:888)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:561)
	at io.trino.$gen.Trino_414____20230907_005824_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.trino.parquet.ParquetCorruptionException: Corrupted statistics for column "filter_farm_id" in Parquet file "s3://XXX/XXX/XXX/partition_metric_name=XXX/partition_utc_year=2023/partition_utc_month=08/partition_utc_day=26/225439bd-8e0c-4a7c-b992-cbdcc4ce779e.parquet.snappy". Corrupted column index: [Boundary order: UNORDERED
                      null count  min                                       max                                     
page-0                         0  <none>                                    <none>                                  
]
	at io.trino.parquet.predicate.TupleDomainParquetPredicate.corruptionException(TupleDomainParquetPredicate.java:601)
	at io.trino.parquet.predicate.TupleDomainParquetPredicate.getDomain(TupleDomainParquetPredicate.java:542)
	at io.trino.parquet.predicate.TupleDomainParquetPredicate.matches(TupleDomainParquetPredicate.java:219)
	at io.trino.parquet.predicate.PredicateUtils.predicateMatches(PredicateUtils.java:157)
	at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:255)
	... 32 more
Caused by: java.lang.IllegalArgumentException: cannot use empty rangeList
	at io.trino.spi.predicate.SortedRangeSet.of(SortedRangeSet.java:247)
	at io.trino.spi.predicate.SortedRangeSet$Builder.build(SortedRangeSet.java:1019)
	at io.trino.parquet.predicate.TupleDomainParquetPredicate.getDomain(TupleDomainParquetPredicate.java:434)
	at io.trino.parquet.predicate.TupleDomainParquetPredicate.getDomain(TupleDomainParquetPredicate.java:539)
	... 35 more
```
</details>

it seems weird to me because Amazon Athena (V3 engine) is able to query this data just fine 🤷

_Originally posted by @antonysouthworth-halter in https://github.com/trinodb/trino/issues/9424#issuecomment-1711134453_

**Comment by antonysouthworth-halter** [comment]
I was able to dodge the error by setting `parquet.use-column-index=false` as suggested by @hashhar

https://github.com/trinodb/trino/issues/9424#issuecomment-1711198974

thanks @hashhar!

i would still be curious why I needed to do this at all, and also a bit worried about the presumably large negative performance impact of this change, so i'll post a link to some example data and query here soon

**Comment by hashhar** [comment]
@raunaqmorarka

**Comment by raunaqmorarka** [comment]
There isn't much perf benefit provided by `parquet.use-column-index`, it's safe to disable.
Can we get an example file and query here ?

**Comment by antonysouthworth-halter** [comment]
no, sorry, I don't have the query or data available anymore since this was quite a while ago and we don't use Trino at all any more.

no worries if you want to close
