### ISSUE TITLE
'Error reading metrics' frequently when connect to prometheus 

### ISSUE THREAD

**Issue by akenO8** [trinodb/trino#19040]
trino version: 424

query:
```
from prom.default.scdn_gulu_sched_execute_info_req_cnt
where "timestamp">=timestamp '2023-09-13 00:00:00'
and "timestamp"<timestamp '2023-09-14 00:00:00'
```

Occasionally, this query can be successfully queried, and occasionally an error will be reported:

Error Type: EXTERNAL ERROR
Error Code: PROMETHEUS_UNKNOWN_ERROR (84475904)

```
io.trino.spi.TrinoException: Error reading metrics
	at io.trino.plugin.prometheus.PrometheusClient.fetchUri(PrometheusClient.java:179)
	at io.trino.plugin.prometheus.PrometheusRecordSet.<init>(PrometheusRecordSet.java:46)
	at io.trino.plugin.prometheus.PrometheusRecordSetProvider.getRecordSet(PrometheusRecordSetProvider.java:51)
	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:265)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:193)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:359)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:255)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:145)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_424____20230914_114120_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.EOFException: undefined
	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:381)
	at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:437)
	at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:416)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.kt:197)
	at okio.InflaterSource.refill(InflaterSource.kt:112)
	at okio.InflaterSource.readOrInflate(InflaterSource.kt:76)
	at okio.InflaterSource.read(InflaterSource.kt:49)
	at okio.GzipSource.read(GzipSource.kt:69)
	at okio.Buffer.writeAll(Buffer.kt:1290)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.kt:236)
	at okhttp3.ResponseBody.bytes(ResponseBody.kt:124)
	at io.trino.plugin.prometheus.PrometheusClient.fetchUri(PrometheusClient.java:170)
	... 31 more
```

What might be the problem? Thanks

**Comment by akenO8** [comment]
@ebyhr Could you look at this problem
