### ISSUE TITLE
io.trino.faulttolerant.TestDistributedFaultTolerantEngineOnlyQueries.testMetadataOnlyQueries is failing

### ISSUE THREAD

**Issue by raunaqmorarka** [trinodb/trino#19045]
```
org.opentest4j.AssertionFailedError: 
expected: STARTING
 but was: FINISHED
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at io.trino.faulttolerant.TestDistributedFaultTolerantEngineOnlyQueries.testMetadataOnlyQueries(TestDistributedFaultTolerantEngineOnlyQueries.java:150)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
https://github.com/trinodb/trino/actions/runs/6185872820/job/16792693078?pr=19041

**Comment by raunaqmorarka** [comment]
cc: @losipiuk @arhimondr

**Comment by wendigo** [comment]
Closed via https://github.com/trinodb/trino/pull/19046
