### ISSUE TITLE
Query failure when ORDER BY references column selected explicitly and with *

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#19110]
Selecting a column, followed by `*` is useful when working with wide tables over some sort of CLI or UI.
However, when doing so, one can filter

```
trino> SELECT custkey, *
    -> FROM tpch.tiny.customer
    -> WHERE custkey < 10;
```

but cannot sort on such a column

```
trino> SELECT custkey, *
    -> FROM tpch.tiny.customer
    -> ORDER BY custkey LIMIT 10;
Query 20230920_152843_00004_gkh4m failed: line 3:10: Column 'custkey' is ambiguous
io.trino.spi.TrinoException: line 3:10: Column 'custkey' is ambiguous
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.sql.analyzer.SemanticExceptions.ambiguousAttributeException(SemanticExceptions.java:38)
	at io.trino.sql.analyzer.Scope.resolveField(Scope.java:248)
	at io.trino.sql.analyzer.Scope.tryResolveField(Scope.java:241)
	at io.trino.sql.analyzer.Scope.resolveField(Scope.java:227)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:664)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:581)
	at io.trino.sql.tree.Identifier.accept(Identifier.java:91)
	at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:604)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:485)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:3452)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeOrderBy(StatementAnalyzer.java:5283)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:3023)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:495)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:514)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:522)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1523)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:495)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:514)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:474)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:463)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:96)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:85)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:270)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:205)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:844)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)
	at io.trino.$gen.Trino_426____20230920_152658_2.call(Unknown Source)
```

from user perspective, this is a rather unfortunate limitation
especially because there is no real ambiguity as the error message stipulates.

**Comment by martint** [comment]
It's not quite specwise, since the SQL spec does not allow a combination like: `custkey, *` in the select clause:

```
<select list> ::=
    <asterisk>
  | <select sublist> [ { <comma> <select sublist> }... ]

<select sublist> ::= <derived column>
  | <qualified asterisk>
```

The query would need to be written as:

```
SELECT custkey, customer.*
FROM ...
```

However, assuming that syntax is allowed, the behavior is consistent with the spec:

For the SELECT clause:

```
The row type RT of TQS is defined by the sequence of (<field name>, <data type>) pairs indicated
by the sequence of column descriptors of TQS taken in order.
```

For the ORDER BY clause:

```
i) If IC is contained in an <order by clause> simply contained in a <query expression> QE, and the result of QE has a column DC whose column name is equivalent to IC, then PIC1 is a candidate basis, the scope of PIC1 is QE, and the referent of PIC1 is the column
DC.

[...]

c) There shall be exactly one candidate basis CB. The basis of IC is CB. The basis length is the
length of CB. The basis scope is the scope of CB. The referent of IC is the referent of CB.
```

Therefore, this is not a bug. If anything, it's a feature enhancement request. I do agree that it'd be worth considering such an enhancement, but we need to evaluate how it would interact with other forms such as the ones below, and what it would take to pull it off given the current design of the analyzer and planner.

```sql
SELECT custkey, customer.* FROM ... ORDER BY custkey

SELECT custkey, custkey FROM ... ORDER BY custkey

SELECT custkey, 1 AS custkey FROM ... ORDER BY custkey

SELECT 1 AS custkey, 1 AS custkey FROM ... ORDER BY custkey

SELECT 1 AS custkey, * FROM ... ORDER BY custkey

SELECT *, customer.* FROM ... ORDER BY custkey

SELECT custkey, customer.* AS (..., custkey, ...) FROM ... ORDER BY custkey
```
