### ISSUE TITLE
Trino 390 SSL issue

### ISSUE THREAD

**Issue by HoiDam** [trinodb/trino#19117]
Trino 390 was installed with keystore cert.

When using trino-cli-426-executable.jar to connect

java -jar .\trino-cli-426-executable.jar --debug --server {ip:port} --user={user} --password=true --insecure

error prompted:
```
java.lang.IllegalArgumentException: [31;1mjava.sql.SQLException: TLS/SSL required for authentication with username and password[0m
        at io.trino.cli.ClientOptions.getTrinoUri(ClientOptions.java:430)
        at io.trino.cli.Console.run(Console.java:124)
        at io.trino.cli.Console.call(Console.java:109)
        at io.trino.cli.Console.call(Console.java:79)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.trino.cli.Trino.main(Trino.java:47)
Caused by: java.sql.SQLException: TLS/SSL required for authentication with username and password
        at io.trino.client.uri.TrinoUri.<init>(TrinoUri.java:277)
        at io.trino.client.uri.TrinoUri.<init>(TrinoUri.java:115)
        at io.trino.client.uri.TrinoUri$Builder.build(TrinoUri.java:1246)
        at io.trino.cli.ClientOptions.getTrinoUri(ClientOptions.java:416)
        ... 12 more
```

**Comment by nineinchnick** [comment]
If you're using a port different than 443, you need to add the HTTPS protocol:
```
java -jar .\trino-cli-426-executable.jar --debug --server https://{ip:port} --user={user} --password=true --insecure
```

**Comment by HoiDam** [comment]
Hi @nineinchnick , thanks for your reply! However, i have already set httpsNodePort & ssl = true and connecting to this httpsnodeport, etc. May i know if anything i missed to set and cause this error? Thanks a lot!!

**Comment by hashhar** [comment]
In addition to the port and `ssl=true` you need to make sure the URL passed to `--server` matches `https://<host>:<port>`.

**Comment by HoiDam** [comment]
Thanks for the help. It works!!
