### ISSUE TITLE
Memory leak in LIKE operator on Trino 423

### ISSUE THREAD

**Issue by jkylling** [trinodb/trino#19146]
We are seeing something which looks like a memory leak in the LIKE operator on Trino 423.

Here is a way to reproduce it using `tpch`:
```
with data as (SELECT lpad(comment, cast(700 * random() as integer), 'a') as comment from tpch.sf100.orders) select * from data where comment like '%a__b__c__d________________________________________e________________________________________f__h__g__i__j____k__l____m__n__o________________________________________p________________________________________q__r__s_t__u____v__w____x__y____z____a____b____c__d____e____f____g____h__i____j____k__l__m__n________________________________________o________________________________________p__q__r__s__t__u__v________________________________________w________________________________________x__y__z__a__b__c__d________________________________________e________________________________________f__g__h__i____j____k____l____m____n__o____p__q________________________________________r____s__t%';
```
On a worker we print heap histograms, before execution, during execution, after cancelling the query, and after running GC:
```
Heap histograms:
Before query starts:
trino@sandbox-ayotm-0-workers-0:/$  jcmd 1 GC.class_histogram | head -n 10
1:
 num     #instances         #bytes  class name (module)
-------------------------------------------------------
   1:          1175      352555928  [J (java.base@17.0.8)
   2:        623801      267267552  [B (java.base@17.0.8)
   3:         32975       27022792  [I (java.base@17.0.8)
   4:        594500       19024000  java.lang.String (java.base@17.0.8)
   5:        368799       14751960  java.util.concurrent.ConcurrentHashMap$Node (java.base@17.0.8)
   6:         88010       12673440  java.lang.reflect.Method (java.base@17.0.8)
   7:        107990       11486216  [Ljava.lang.Object; (java.base@17.0.8)

While query is running:
trino@sandbox-ayotm-0-workers-0:/$  jcmd 1 GC.class_histogram | head -n 10
1:
 num     #instances         #bytes  class name (module)
-------------------------------------------------------
   1:     176238014     4229712336  io.trino.likematcher.DFA$Transition
   2:       1620002     2301058128  [Ljava.lang.Object; (java.base@17.0.8)
   3:      48880957     2253990184  [I (java.base@17.0.8)
   4:      48847496     1172339904  it.unimi.dsi.fastutil.ints.IntArraySet
   5:        637379      664520864  [B (java.base@17.0.8)
   6:          1177      352588768  [J (java.base@17.0.8)
   7:       3164605      303802080  java.util.HashMap$TreeNode (java.base@17.0.8)

After query is cancelled in CLI:
trino@sandbox-ayotm-0-workers-0:/$ jcmd 1 GC.class_histogram | head -n 10
1:
 num     #instances         #bytes  class name (module)
-------------------------------------------------------
   1:    1030729300    24737503200  io.trino.likematcher.DFA$Transition
   2:     297653895    14213376408  [I (java.base@17.0.8)
   3:       8245447    14076082480  [Ljava.lang.Object; (java.base@17.0.8)
   4:     297620400     7142889600  it.unimi.dsi.fastutil.ints.IntArraySet
   5:      19001577     1824151392  java.util.HashMap$TreeNode (java.base@17.0.8)
   6:        637725      664538496  [B (java.base@17.0.8)
   7:      11284630      361108160  java.util.ArrayList (java.base@17.0.8)

After running GC with jcmd:
trino@sandbox-ayotm-0-workers-0:/$ jcmd 1 GC.class_histogram | head -n 10
1:
 num     #instances         #bytes  class name (module)
-------------------------------------------------------
   1:    1191809552    28603429248  io.trino.likematcher.DFA$Transition
   2:     342966481    16417973176  [I (java.base@17.0.8)
   3:       9490064    15751099224  [Ljava.lang.Object; (java.base@17.0.8)
   4:     342932961     8230391064  it.unimi.dsi.fastutil.ints.IntArraySet
   5:      21988653     2110910688  java.util.HashMap$TreeNode (java.base@17.0.8)
   6:        637867      664545456  [B (java.base@17.0.8)
   7:      13026192      416838144  java.util.ArrayList (java.base@17.0.8)
```

The `io.trino.likematcher.DFA$Transition` instances keep on increasing, even after the query is cancelled, and nothing else runs on the cluster. This seems to be because the `LikeMatcher` keeps on running after the query is cancelled (extract of`jcmd 1 Thread.print`, after query is cancelled):
```
"20230925_133433_00007_pxrcz.1.4.0-50-76" #76 prio=5 os_prio=0 cpu=732678.02ms elapsed=1061.40s tid=0x0000ffffa17435a0 nid=0xf9 runnable  [0x0000ffc5613fc000]
   java.lang.Thread.State: RUNNABLE
        at it.unimi.dsi.fastutil.ints.IntArraySet.findKey(IntArraySet.java:204)
        at it.unimi.dsi.fastutil.ints.IntArraySet.contains(IntArraySet.java:347)
        at it.unimi.dsi.fastutil.ints.AbstractIntCollection.containsAll(AbstractIntCollection.java:189)
        at it.unimi.dsi.fastutil.ints.AbstractIntSet.equals(AbstractIntSet.java:43)
        at java.util.HashMap$TreeNode.find(java.base@17.0.8/HashMap.java:2018)
        at java.util.HashMap$TreeNode.find(java.base@17.0.8/HashMap.java:2028)
        at java.util.HashMap$TreeNode.find(java.base@17.0.8/HashMap.java:2028)
        at java.util.HashMap$TreeNode.find(java.base@17.0.8/HashMap.java:2028)
        at java.util.HashMap$TreeNode.find(java.base@17.0.8/HashMap.java:2028)
        at java.util.HashMap$TreeNode.find(java.base@17.0.8/HashMap.java:2028)
        at java.util.HashMap$TreeNode.find(java.base@17.0.8/HashMap.java:2028)
        at java.util.HashMap$TreeNode.find(java.base@17.0.8/HashMap.java:2028)
        at java.util.HashMap$TreeNode.find(java.base@17.0.8/HashMap.java:2028)
        at java.util.HashMap$TreeNode.getTreeNode(java.base@17.0.8/HashMap.java:2040)
        at java.util.HashMap.getNode(java.base@17.0.8/HashMap.java:574)
        at java.util.HashMap.get(java.base@17.0.8/HashMap.java:556)
        at io.trino.likematcher.NFA.toDfa(NFA.java:85)
        at io.trino.likematcher.DenseDfaMatcher$DenseDfa.newInstance(DenseDfaMatcher.java:75)
        at io.trino.likematcher.DenseDfaMatcher.match(DenseDfaMatcher.java:48)
        at io.trino.likematcher.LikeMatcher.match(LikeMatcher.java:171)
        at io.trino.type.LikeFunctions.likeVarchar(LikeFunctions.java:54)
        at java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.base@17.0.8/DirectMethodHandle$Holder)
        at java.lang.invoke.LambdaForm$MH/0x000000d8013f2c00.linkToTargetMethod(java.base@17.0.8/LambdaForm$MH)
        at io.trino.$gen.CursorProcessor_20230925_133433_63.filter(Unknown Source)
        at io.trino.$gen.CursorProcessor_20230925_133433_63.process(Unknown Source)
        at io.trino.operator.ScanFilterAndProjectOperator$RecordCursorToPages.process(ScanFilterAndProjectOperator.java:334)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
        at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
        at io.trino.operator.WorkProcessorUtils$BlockingProcess.process(WorkProcessorUtils.java:207)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
        at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:317)
        at io.trino.operator.WorkProcessorUtils$$Lambda$3637/0x000000d803346b48.process(Unknown Source)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:359)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
        at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:240)
        at io.trino.operator.WorkProcessorUtils$$Lambda$3641/0x000000d803347408.process(Unknown Source)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
        at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:255)
        at io.trino.operator.WorkProcessorUtils$$Lambda$3643/0x000000d803347858.process(Unknown Source)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
        at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:145)
        at io.trino.operator.Driver.processInternal(Driver.java:395)
        at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
        at io.trino.operator.Driver$$Lambda$3323/0x000000d8032f5670.get(Unknown Source)
        at io.trino.operator.Driver.tryWithLock(Driver.java:694)
        at io.trino.operator.Driver.process(Driver.java:290)
        at io.trino.operator.Driver.processForDuration(Driver.java:261)
        at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
        at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
        at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:555)
        at io.trino.$gen.Trino_418_1124_g31857b9____20230925_133009_2.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.8/ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.8/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17.0.8/Thread.java:833)
```

This can also be reproduced with
```
select comment from tpch.sf10.orders where comment like '%a________________%' limit 10;
```
although I've not done as careful heap histograms when testing with this. Changing the length of the `_` line makes the query complete or fail.

**Comment by jkylling** [comment]
Thanks a lot for fixing this so quickly! We have deployed the fix and can confirm that it works.
