### ISSUE TITLE
With OpenXJson/Hive Json, read data failing at DistinctMapKeys.selectDistinctKeys

### ISSUE THREAD

**Issue by guptashailesh92** [trinodb/trino#19142]
Hi,

When the json field which is defined as map has more than 128 keys, it throws the error with native implementation whereas it passes with hive serde.

data.json
```
{"data":{"key1":"value1","key2":"value2","key3":"value3","key4":"value4","key5":"value5","key6":"value6","key7":"value7","key8":"value8","key9":"value9","key10":"value10","key11":"value11","key12":"value12","key13":"value13","key14":"value14","key15":"value15","key16":"value16","key17":"value17","key18":"value18","key19":"value19","key20":"value20","key21":"value21","key22":"value22","key23":"value23","key24":"value24","key25":"value25","key26":"value26","key27":"value27","key28":"value28","key29":"value29","key30":"value30","key31":"value31","key32":"value32","key33":"value33","key34":"value34","key35":"value35","key36":"value36","key37":"value37","key38":"value38","key39":"value39","key40":"value40","key41":"value41","key42":"value42","key43":"value43","key44":"value44","key45":"value45","key46":"value46","key47":"value47","key48":"value48","key49":"value49","key50":"value50","key51":"value51","key52":"value52","key53":"value53","key54":"value54","key55":"value55","key56":"value56","key57":"value57","key58":"value58","key59":"value59","key60":"value60","key61":"value61","key62":"value62","key63":"value63","key64":"value64","key65":"value65","key66":"value66","key67":"value67","key68":"value68","key69":"value69","key70":"value70","key71":"value71","key72":"value72","key73":"value73","key74":"value74","key75":"value75","key76":"value76","key77":"value77","key78":"value78","key79":"value79","key80":"value80","key81":"value81","key82":"value82","key83":"value83","key84":"value84","key85":"value85","key86":"value86","key87":"value87","key88":"value88","key89":"value89","key90":"value90","key91":"value91","key92":"value92","key93":"value93","key94":"value94","key95":"value95","key96":"value96","key97":"value97","key98":"value98","key99":"value99","key100":"value100","key101":"value101","key102":"value102","key103":"value103","key104":"value104","key105":"value105","key106":"value106","key107":"value107","key108":"value108","key109":"value109","key110":"value110","key111":"value111","key112":"value112","key113":"value113","key114":"value114","key115":"value115","key116":"value116","key117":"value117","key118":"value118","key119":"value119","key120":"value120","key121":"value121","key122":"value122","key123":"value123","key124":"value124","key125":"value125","key126":"value126","key127":"value127","key128":"value128","key129":"value129","key130":"value130","key131":"value131","key132":"value132","key133":"value133","key134":"value134","key135":"value135","key136":"value136","key137":"value137","key138":"value138","key139":"value139","key140":"value140","key141":"value141","key142":"value142","key143":"value143","key144":"value144","key145":"value145","key146":"value146","key147":"value147","key148":"value148","key149":"value149","key150":"value150","a":"1231"}}
```

create table statement
```
 CREATE TABLE logs (
    data map(varchar, varchar)
 )
 WITH (
    external_location = 's3://<>'
 )
```

Query
```
select * from logs
```

output with hive serde
```
{key118=value118, key117=value117, key119=value119, key40=value40, key114=value114, key113=value113, key116=value116, key115=value115, key44=value44, key110=value110, key43=value43, key42=value42, key112=value112, key41=value41, key111=value111, key37=value37, key36=value36, key35=value35, key34=value34, key39=value39, key38=value38, key129=value129, key128=value128, key51=value51, key125=value125, key50=value50, key124=value124, key127=value127, key126=value126, key55=value55, key121=value121, key54=value54, key120=value120, key53=value53, key123=value123, key52=value52, key122=value122, key48=value48, key47=value47, key46=value46, key45=value45, key49=value49, key62=value62, key61=value61, key60=value60, key66=value66, key65=value65, key64=value64, key63=value63, key59=value59, key58=value58, key57=value57, key56=value56, a=1231, key107=value107, key106=value106, key109=value109, key108=value108, key73=value73, key103=value103, key72=value72, key102=value102, key71=value71, key105=value105, key70=value70, key104=value104, key77=value77, key76=value76, key75=value75, key101=value101, key74=value74, key100=value100, key69=value69, key68=value68, key67=value67, key1=value1, key2=value2, key5=value5, key80=value80, key6=value6, key3=value3, key4=value4, key9=value9, key84=value84, key83=value83, key7=value7, key82=value82, key8=value8, key81=value81, key88=value88, key87=value87, key86=value86, key85=value85, key150=value150, key79=value79, key78=value78, key91=value91, key90=value90, key95=value95, key94=value94, key93=value93, key92=value92, key11=value11, key99=value99, key10=value10, key98=value98, key97=value97, key96=value96, key89=value89, key139=value139, key136=value136, key135=value135, key138=value138, key137=value137, key22=value22, key132=value132, key21=value21, key131=value131, key20=value20, key134=value134, key133=value133, key15=value15, key14=value14, key13=value13, key130=value130, key12=value12, key19=value19, key18=value18, key17=value17, key16=value16, key147=value147, key146=value146, key149=value149, key148=value148, key33=value33, key143=value143, key32=value32, key142=value142, key31=value31, key145=value145, key30=value30, key144=value144, key26=value26, key25=value25, key24=value24, key141=value141, key23=value23, key140=value140, key29=value29, key28=value28, key27=value27}
```

output with native implementation
```
io.trino.spi.TrinoException: Failed to read file at s3://<>/data.json
	at io.trino.plugin.hive.line.LinePageSource.getNextPage(LinePageSource.java:74)
	at io.trino.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:203)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:304)
	at io.trino.operator.Driver.processInternal(Driver.java:402)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:305)
	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
	at io.trino.operator.Driver.process(Driver.java:297)
	at io.trino.operator.Driver.processForDuration(Driver.java:268)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1017)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:606)
	at io.trino.$gen.Trino_dev____20230925_104522_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 296 out of bounds for length 256
	at io.trino.hive.formats.DistinctMapKeys.selectDistinctKeys(DistinctMapKeys.java:71)
	at io.trino.hive.formats.line.openxjson.OpenXJsonDeserializer$MapDecoder.decodeValue(OpenXJsonDeserializer.java:714)
	at io.trino.hive.formats.line.openxjson.OpenXJsonDeserializer$Decoder.decode(OpenXJsonDeserializer.java:233)
	at io.trino.hive.formats.line.openxjson.OpenXJsonDeserializer$RowDecoder.decodeValueFromMap(OpenXJsonDeserializer.java:828)
	at io.trino.hive.formats.line.openxjson.OpenXJsonDeserializer$RowDecoder.decodeValue(OpenXJsonDeserializer.java:782)
	at io.trino.hive.formats.line.openxjson.OpenXJsonDeserializer$RowDecoder.decode(OpenXJsonDeserializer.java:765)
	at io.trino.hive.formats.line.openxjson.OpenXJsonDeserializer.deserialize(OpenXJsonDeserializer.java:159)
	at io.trino.plugin.hive.line.LinePageSource.getNextPage(LinePageSource.java:61)
	... 14 more

```

**Comment by pettyjamesm** [comment]
Fixed via https://github.com/trinodb/trino/pull/19151
