### ISSUE TITLE
"Failed to read Parquet file" in trino v414

### ISSUE THREAD

**Issue by zp-stripe** [trinodb/trino#19284]
Hi folks,

We recently encountered various queries hitting `Failed to read Parquet file` errors in v414 for queries which were succeeding in v358.

This fails:
```
SELECT
  _id
FROM
  iceberg_table
WHERE
  day_partition = '20220808'
  and test_uid LIKE '%//pattern%'
  and body LIKE '%pattern%'
```
but this succeeds:
```
with ids as (
  SELECT
    _id,
    test_uid
  FROM
    iceberg_table
  WHERE
    day_partition = '20220808'
    and body LIKE '%pattern%'
)
select
  _id
from
  ids
where
  test_uid LIKE '%pattern%'
```

Stack trace:
```
io.trino.spi.TrinoException: Failed to read Parquet file: 
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.handleException(IcebergPageSourceProvider.java:1320)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.lambda$createParquetPageSource$26(IcebergPageSourceProvider.java:1011)
	at io.trino.parquet.reader.ParquetBlockFactory$ParquetBlockLoader.load(ParquetBlockFactory.java:75)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:406)
	at io.trino.spi.block.LazyBlock$LazyData.getTopLevelBlock(LazyBlock.java:375)
	at io.trino.spi.block.LazyBlock.getBlock(LazyBlock.java:280)
	at io.trino.spi.block.LazyBlock.isNull(LazyBlock.java:263)
	at io.trino.$gen.PageFilter_20231005_210916_12475.filter(Unknown Source)
	at io.trino.$gen.PageFilter_20231005_210916_12475.filter(Unknown Source)
	at io.trino.operator.project.PageProcessor.createWorkProcessor(PageProcessor.java:128)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.lambda$processPageSource$1(ScanFilterAndProjectOperator.java:291)
	at io.trino.operator.WorkProcessorUtils.lambda$flatMap$4(WorkProcessorUtils.java:286)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:360)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils$BlockingProcess.process(WorkProcessorUtils.java:208)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:318)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:360)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:241)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:256)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:146)
	at io.trino.operator.Driver.processInternal(Driver.java:402)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:305)
	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
	at io.trino.operator.Driver.process(Driver.java:297)
	at io.trino.operator.Driver.processForDuration(Driver.java:268)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:888)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:561)
	at io.trino.$gen.Trino_414_stripe_6____20231005_154233_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NegativeArraySizeException: -1748426231
	at io.airlift.slice.Slices.allocate(Slices.java:89)
	at io.trino.parquet.reader.flat.BinaryBuffer.asSlice(BinaryBuffer.java:91)
	at io.trino.parquet.reader.flat.BinaryColumnAdapter.createNonNullBlock(BinaryColumnAdapter.java:76)
	at io.trino.parquet.reader.flat.BinaryColumnAdapter.createNonNullBlock(BinaryColumnAdapter.java:27)
	at io.trino.parquet.reader.flat.FlatColumnReader$DataValuesBuffer.createNonNullBlock(FlatColumnReader.java:390)
	at io.trino.parquet.reader.flat.FlatColumnReader.readNonNull(FlatColumnReader.java:187)
	at io.trino.parquet.reader.flat.FlatColumnReader.readPrimitive(FlatColumnReader.java:84)
	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:440)
	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:525)
	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:508)
	at io.trino.parquet.reader.ParquetReader.lambda$nextPage$3(ParquetReader.java:273)
	at io.trino.parquet.reader.ParquetBlockFactory$ParquetBlockLoader.load(ParquetBlockFactory.java:72)
	... 42 more
```

**Comment by zp-stripe** [comment]
Also if I do `set session iceberg.parquet_max_read_block_row_count=1024` then the failing snippet above completes successfully.

**Comment by zp-stripe** [comment]
Some of the strings in the underlying data are very long.

**Comment by raunaqmorarka** [comment]
The underlying problem here is that we need to store strings in a contiguous memory location per batch due to using byte arrays and this fails when the length of strings in the batch exceeds the max possible size of a Java byte array.
We had raised max page size produced by parquet reader in 405 release https://github.com/trinodb/trino/pull/15257 for performance reasons. There is also logic in `io.trino.parquet.reader.ParquetReader#readPrimitive` to regulate parquet batch sizes based on observed block sizes. However, that doesn't help when there is a sudden jump in string value sizes.
For outlier cases like this, it is best to use `parquet_max_read_block_row_count` property to get past the problem.
