### ISSUE TITLE
Hive partitions are too many and queries are too slow

### ISSUE THREAD

**Issue by wangmiao1002** [trinodb/trino#19350]
Version ：426
In our environment, there is a hive table with multiple partitions, and every time a query is made, a Read timed out will appear,
    The presto we used to use can quickly return results. How can we avoid it

`io.trino.spi.TrinoException: dx-loghdfs08.dx:9083: java.net.SocketTimeoutException: Read timed out
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getPartitionNamesByFilter(ThriftHiveMetastore.java:1224)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.getPartitionNamesByFilter(BridgingHiveMetastore.java:347)
	at io.trino.plugin.hive.metastore.ForwardingHiveMetastore.getPartitionNamesByFilter(ForwardingHiveMetastore.java:251)
	at io.trino.plugin.hive.aws.athena.PartitionProjectionMetastoreDecorator$PartitionProjectionMetastore.getPartitionNamesByFilter(PartitionProjectionMetastoreDecorator.java:78)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadPartitionNamesByFilter(CachingHiveMetastore.java:995)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:447)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:433)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4012)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5011)
	at io.trino.cache.EvictableCache.get(EvictableCache.java:145)
	at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:53)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getOptional(CachingHiveMetastore.java:451)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getPartitionNamesByFilter(CachingHiveMetastore.java:990)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadPartitionNamesByFilter(CachingHiveMetastore.java:995)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:447)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:433)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4012)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5011)
	at io.trino.cache.EvictableCache.get(EvictableCache.java:145)
	at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:53)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getOptional(CachingHiveMetastore.java:451)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getPartitionNamesByFilter(CachingHiveMetastore.java:990)
	at io.trino.plugin.hive.HiveMetastoreClosure.getPartitionNamesByFilter(HiveMetastoreClosure.java:247)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.doGetPartitionNames(SemiTransactionalHiveMetastore.java:872)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.getPartitionNamesByFilter(SemiTransactionalHiveMetastore.java:843)
	at io.trino.plugin.hive.HivePartitionManager.getFilteredPartitionNames(HivePartitionManager.java:247)
	at io.trino.plugin.hive.HivePartitionManager.lambda$getPartitions$2(HivePartitionManager.java:110)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.trino.plugin.hive.HivePartitionManager.getPartitions(HivePartitionManager.java:110)
	at io.trino.plugin.hive.HiveMetadata.lambda$getTableProperties$89(HiveMetadata.java:2929)
	at java.base/java.util.Optional.or(Optional.java:313)
	at io.trino.plugin.hive.HiveMetadata.getTableProperties(HiveMetadata.java:2925)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableProperties(ClassLoaderSafeConnectorMetadata.java:897)
	at io.trino.tracing.TracingConnectorMetadata.getTableProperties(TracingConnectorMetadata.java:1055)
	at io.trino.metadata.MetadataManager.getTableProperties(MetadataManager.java:400)
	at io.trino.tracing.TracingMetadata.getTableProperties(TracingMetadata.java:233)
	at io.trino.sql.planner.planprinter.TableInfoSupplier.apply(TableInfoSupplier.java:47)
	at io.trino.sql.planner.planprinter.TableInfoSupplier.apply(TableInfoSupplier.java:31)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitScanFilterAndProjectInfo(PlanPrinter.java:1263)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitProject(PlanPrinter.java:1228)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitProject(PlanPrinter.java:656)
	at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.processChildren(PlanPrinter.java:1949)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitLimit(PlanPrinter.java:818)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitLimit(PlanPrinter.java:656)
	at io.trino.sql.planner.plan.LimitNode.accept(LimitNode.java:123)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitScanFilterAndProjectInfo(PlanPrinter.java:1342)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitProject(PlanPrinter.java:1231)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitProject(PlanPrinter.java:656)
	at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitScanFilterAndProjectInfo(PlanPrinter.java:1342)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitProject(PlanPrinter.java:1231)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitProject(PlanPrinter.java:656)
	at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitScanFilterAndProjectInfo(PlanPrinter.java:1342)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitProject(PlanPrinter.java:1231)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitProject(PlanPrinter.java:656)
	at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.processChildren(PlanPrinter.java:1949)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitOutput(PlanPrinter.java:1464)
	at io.trino.sql.planner.planprinter.PlanPrinter$Visitor.visitOutput(PlanPrinter.java:656)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at io.trino.sql.planner.planprinter.PlanPrinter.<init>(PlanPrinter.java:235)
	at io.trino.sql.planner.planprinter.PlanPrinter.textLogicalPlan(PlanPrinter.java:398)
	at io.trino.sql.planner.planprinter.PlanPrinter.textLogicalPlan(PlanPrinter.java:373)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:250)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:239)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:234)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:482)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:462)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:400)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:256)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at io.trino.$gen.Trino_426____20231011_122212_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.thrift.transport.TTransportException: dx-loghdfs08.dx:9083: java.net.SocketTimeoutException: Read timed out
	at io.trino.plugin.hive.metastore.thrift.Transport.rewriteException(Transport.java:95)
	at io.trino.plugin.hive.metastore.thrift.Transport$TTransportWrapper.readAll(Transport.java:129)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:519)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:387)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:271)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.recvGetPartitionNames(ThriftHiveMetastore.java:3146)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.getPartitionNames(ThriftHiveMetastore.java:3131)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.trino.plugin.base.util.LoggingInvocationHandler.handleInvocation(LoggingInvocationHandler.java:60)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at jdk.proxy5/jdk.proxy5.$Proxy261.getPartitionNames(Unknown Source)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.getPartitionNames(ThriftHiveMetastoreClient.java:441)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.lambda$getPartitionNames$20(FailureAwareThriftMetastoreClient.java:224)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.runWithHandle(FailureAwareThriftMetastoreClient.java:455)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.getPartitionNames(FailureAwareThriftMetastoreClient.java:224)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$getPartitionNamesByFilter$45(ThriftHiveMetastore.java:1207)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:41)
	at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:116)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getPartitionNamesByFilter(ThriftHiveMetastore.java:1205)
	... 92 more
	Suppressed: org.apache.thrift.transport.TTransportException: dx-loghdfs08.dx:9083: java.net.SocketTimeoutException: Read timed out
		... 115 more
	Caused by: org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
		at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:171)
		at org.apache.thrift.transport.TTransport.readAll(TTransport.java:100)
		at io.trino.plugin.hive.metastore.thrift.Transport$TTransportWrapper.readAll(Transport.java:126)
		... 113 more
	Caused by: java.net.SocketTimeoutException: Read timed out
		at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
		at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
		at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
		at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
		at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
		at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
		at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
		at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
		at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:169)
		... 115 more
	Suppressed: org.apache.thrift.transport.TTransportException: dx-loghdfs08.dx:9083: java.net.SocketTimeoutException: Read timed out
		... 115 more
	Caused by: org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
		at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:171)
		at org.apache.thrift.transport.TTransport.readAll(TTransport.java:100)
		at io.trino.plugin.hive.metastore.thrift.Transport$TTransportWrapper.readAll(Transport.java:126)
		... 113 more
	Caused by: java.net.SocketTimeoutException: Read timed out
		at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
		at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
		at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
		at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
		at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
		at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
		at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
		at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
		at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:169)
		... 115 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:171)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:100)
	at io.trino.plugin.hive.metastore.thrift.Transport$TTransportWrapper.readAll(Transport.java:126)
	... 113 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:169)
	... 115 more`

**Comment by akenO8** [comment]
@wangmiao1002  I also encountered this problem, how did you solve it
