### ISSUE TITLE
when i query the clickhouse data happend the EOFException

### ISSUE THREAD

**Issue by MurderWind** [trinodb/trino#19367]
trino：401
clickhouse server info : 23.1.8

io.trino.spi.TrinoException: java.io.EOFException
	at io.trino.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:305)
	at io.trino.plugin.jdbc.JdbcRecordCursor.advanceNextPosition(JdbcRecordCursor.java:179)
	at io.trino.$gen.CursorProcessor_20231012_021734_4310.process(Unknown Source)
	at io.trino.operator.ScanFilterAndProjectOperator$RecordCursorToPages.process(ScanFilterAndProjectOperator.java:348)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:182)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$7(WorkProcessorUtils.java:296)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$3(WorkProcessorUtils.java:219)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$4(WorkProcessorUtils.java:234)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:150)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:749)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:515)
	at io.trino.$gen.Trino_2_2_4_release_13_g3d308fd____20230927_023106_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLException: java.io.EOFException
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:76)
	at com.clickhouse.jdbc.ClickHouseResultSet.next(ClickHouseResultSet.java:710)
	at io.trino.plugin.jdbc.JdbcRecordCursor.advanceNextPosition(JdbcRecordCursor.java:176)
	... 32 more
Caused by: java.io.EOFException: undefined
	at com.clickhouse.client.data.ClickHouseLZ4InputStream.readFully(ClickHouseLZ4InputStream.java:85)
	at com.clickhouse.client.data.ClickHouseLZ4InputStream.readNextBlock(ClickHouseLZ4InputStream.java:63)
	at com.clickhouse.client.data.ClickHouseLZ4InputStream.checkNext(ClickHouseLZ4InputStream.java:35)
	at com.clickhouse.client.data.ClickHouseLZ4InputStream.read(ClickHouseLZ4InputStream.java:157)
	at com.clickhouse.client.ClickHouseInputStream.readBytes(ClickHouseInputStream.java:449)
	at com.clickhouse.client.http.ClickHouseHttpResponse.readBytes(ClickHouseHttpResponse.java:146)
	at com.clickhouse.client.data.BinaryStreamUtils.readInt64(BinaryStreamUtils.java:808)
	at com.clickhouse.client.data.BinaryStreamUtils.readDateTime64(BinaryStreamUtils.java:1488)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$MappedFunctions.lambda$buildMappingsForDataTypes$56(ClickHouseRowBinaryProcessor.java:314)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$MappedFunctions.deserialize(ClickHouseRowBinaryProcessor.java:465)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$Records.readNextRow(ClickHouseRowBinaryProcessor.java:519)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$Records.next(ClickHouseRowBinaryProcessor.java:549)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$Records.next(ClickHouseRowBinaryProcessor.java:494)
	at com.clickhouse.jdbc.ClickHouseResultSet.next(ClickHouseResultSet.java:708)
	... 33 more

**Comment by findinpath** [comment]
cc @mayankvadariya

**Comment by mayankvadariya** [comment]
@MurderWind thanks for reporting. Can you please try with the lates Trino and confirm if you still see the same issue?
Also, confirm if issue occurs with specific query or any select would result in this exception? Is it anyhow related to datatype of underlying table?

**Comment by ebyhr** [comment]
Let me close this issue because there's no response for a while, the version is too old, the steps to reproduce is unclear.
