### ISSUE TITLE
Flaky `TestMinWorkerRequirement.testMultipleRequiredWorkerNodesSessionOverride`

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#19446]
```
Error:  io.trino.tests.TestMinWorkerRequirement.testMultipleRequiredWorkerNodesSessionOverride -- Time elapsed: 1.568 s <<< FAILURE!
java.lang.AssertionError: expected:<10.00s> to be less than <10.00s>
	at io.airlift.testing.Assertions.fail(Assertions.java:323)
	at io.airlift.testing.Assertions.assertLessThan(Assertions.java:190)
	at io.airlift.testing.Assertions.assertLessThan(Assertions.java:162)
	at io.trino.testing.DistributedQueryRunner.waitForAllNodesGloballyVisible(DistributedQueryRunner.java:302)
	at io.trino.testing.DistributedQueryRunner.addServers(DistributedQueryRunner.java:294)
	at io.trino.tests.TestMinWorkerRequirement.testMultipleRequiredWorkerNodesSessionOverride(TestMinWorkerRequirement.java:219)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

https://github.com/findinpath/trino/actions/runs/6563658160/job/17828519960

**Comment by dominikzalewski** [comment]
Confirming: https://github.com/trinodb/trino/actions/runs/6560170025/job/17817609285?pr=19413

Error:  io.trino.tests.TestMinWorkerRequirement.testMultipleRequiredWorkerNodesSessionOverride -- Time elapsed: 0.574 s <<< FAILURE!
java.lang.AssertionError: expected:<10.01s> to be less than <10.00s>
        at io.airlift.testing.Assertions.fail(Assertions.java:323)
        at io.airlift.testing.Assertions.assertLessThan(Assertions.java:190)
        at io.airlift.testing.Assertions.assertLessThan(Assertions.java:162)
        at io.trino.testing.DistributedQueryRunner.waitForAllNodesGloballyVisible(DistributedQueryRunner.java:302)
        at io.trino.testing.DistributedQueryRunner.addServers(DistributedQueryRunner.java:294)
        at io.trino.tests.TestMinWorkerRequirement.testMultipleRequiredWorkerNodesSessionOverride(TestMinWorkerRequirement.java:219)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by kasiafi** [comment]
Failed also on https://github.com/trinodb/trino/pull/19488:
java.lang.AssertionError: expected:<10.00s> to be less than <10.00s>
 	at io.airlift.testing.Assertions.fail(Assertions.java:323)
 	at io.airlift.testing.Assertions.assertLessThan(Assertions.java:190)
 	at io.airlift.testing.Assertions.assertLessThan(Assertions.java:162)
 	at io.trino.testing.DistributedQueryRunner.waitForAllNodesGloballyVisible(DistributedQueryRunner.java:302)
 	at io.trino.testing.DistributedQueryRunner.addServers(DistributedQueryRunner.java:294)
 	at io.trino.tests.TestMinWorkerRequirement.testMultipleRequiredWorkerNodesSessionOverride(TestMinWorkerRequirement.java:219)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/actions/runs/6615036857/job/17966463297?pr=13681
Failed on https://github.com/trinodb/trino/pull/13681

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/6639481727/job/18038506566?pr=19523

```
Error:  io.trino.tests.TestMinWorkerRequirement.testMultipleRequiredWorkerNodesSessionOverride -- Time elapsed: 4.204 s <<< FAILURE!
java.lang.AssertionError: expected:<10.01s> to be less than <10.00s>
	at io.airlift.testing.Assertions.fail(Assertions.java:323)
	at io.airlift.testing.Assertions.assertLessThan(Assertions.java:190)
	at io.airlift.testing.Assertions.assertLessThan(Assertions.java:162)
	at io.trino.testing.DistributedQueryRunner.waitForAllNodesGloballyVisible(DistributedQueryRunner.java:303)
	at io.trino.testing.DistributedQueryRunner.addServers(DistributedQueryRunner.java:295)
	at io.trino.tests.TestMinWorkerRequirement.testMultipleRequiredWorkerNodesSessionOverride(TestMinWorkerRequirement.java:219)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by findepi** [comment]
cc @raunaqmorarka @dain

**Comment by electrum** [comment]
https://github.com/trinodb/trino/actions/runs/6711280869/job/18239620900?pr=19566
```
Error:  io.trino.tests.TestMinWorkerRequirement.testMultipleRequiredWorkerNodesSessionOverride -- Time elapsed: 1.087 s <<< FAILURE!
java.lang.AssertionError: expected:<10.01s> to be less than <10.00s>
	at io.airlift.testing.Assertions.fail(Assertions.java:323)
	at io.airlift.testing.Assertions.assertLessThan(Assertions.java:190)
	at io.airlift.testing.Assertions.assertLessThan(Assertions.java:162)
	at io.trino.testing.DistributedQueryRunner.waitForAllNodesGloballyVisible(DistributedQueryRunner.java:303)
	at io.trino.testing.DistributedQueryRunner.addServers(DistributedQueryRunner.java:295)
	at io.trino.tests.TestMinWorkerRequirement.testMultipleRequiredWorkerNodesSessionOverride(TestMinWorkerRequirement.java:219)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/actions/runs/6773256059/job/18407903813?pr=19520

```
Error:  Tests run: 1561, Failures: 1, Errors: 0, Skipped: 378, Time elapsed: 723.8 s <<< FAILURE! -- in TestSuite
Error:  io.trino.tests.TestMinWorkerRequirement.testMultipleRequiredWorkerNodesSessionOverride -- Time elapsed: 20.80 s <<< FAILURE!
java.lang.AssertionError: expected:<10.01s> to be less than <10.00s>
	at io.airlift.testing.Assertions.fail(Assertions.java:323)
	at io.airlift.testing.Assertions.assertLessThan(Assertions.java:190)
	at io.airlift.testing.Assertions.assertLessThan(Assertions.java:162)
	at io.trino.testing.DistributedQueryRunner.waitForAllNodesGloballyVisible(DistributedQueryRunner.java:303)
```

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/actions/runs/6781596183/job/18432966690
