### ISSUE TITLE
Flaky TestDeltaLakeAdlsConnectorSmokeTest.testVacuumWithTrailingSlash

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#19461]
https://github.com/trinodb/trino/actions/runs/6579766410/job/17876435012
```
Error:  io.trino.plugin.deltalake.TestDeltaLakeAdlsConnectorSmokeTest.testVacuumWithTrailingSlash -- Time elapsed: 3.813 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: 
  ["abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=2/20231019_203058_00359_mmswa_02a6981f-9bce-44e6-b2dc-b6c04ccfae77",
      "abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=3/20231019_203058_00359_mmswa_e0e23e69-fe64-4ee9-baa3-f0e2ec4c047f",
      "abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=4/20231019_203058_00359_mmswa_eec3385d-6289-4cac-a9da-71c45aec120e",
      "abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=0/20231019_203058_00359_mmswa_09fb95d5-d1c3-4368-b60c-34a8fbb102dd",
      "abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=1/20231019_203058_00359_mmswa_6c4811bf-c499-4212-ab88-63476cd49857"]
 but was: 
  ["abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=0/20231019_203057_00357_mmswa_42df4a0a-3744-46f5-bba3-72e8c337bc6f",
      "abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=0/20231019_203058_00359_mmswa_09fb95d5-d1c3-4368-b60c-34a8fbb102dd",
      "abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=1/20231019_203057_00357_mmswa_13edcf44-7fae-4080-a26e-ecc0a32809b2",
      "abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=1/20231019_203058_00359_mmswa_6c4811bf-c499-4212-ab88-63476cd49857",
      "abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=2/20231019_203057_00357_mmswa_5af7238c-d384-4a49-bdf0-a6cfc6ba79bc",
      "abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=2/20231019_203058_00359_mmswa_02a6981f-9bce-44e6-b2dc-b6c04ccfae77",
      "abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=3/20231019_203057_00357_mmswa_868a1bee-5ef2-4325-9798-724f6f90eca8",
      "abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=3/20231019_203058_00359_mmswa_e0e23e69-fe64-4ee9-baa3-f0e2ec4c047f",
      "abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=4/20231019_203057_00357_mmswa_8b44c4c8-dff5-4283-9a34-7a5de3116b69",
      "abfs://***@***.dfs.core.windows.net/test-delta-lake-integration-smoke-test-eni03z90dq/test_vacuumy6c4tu2vis/regionkey=4/20231019_203058_00359_mmswa_eec3385d-6289-4cac-a9da-71c45aec120e"]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testVacuumWithTrailingSlash(BaseDeltaLakeConnectorSmokeTest.java:1712)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/11507317315/job/32033279899

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/13358122437/job/37303711769

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/13535472637

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/13549751375/job/37870295972

**Comment by ebyhr** [comment]
testVacuum also failed:
```
Error:    TestDeltaLakeAdlsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testVacuum:1748 
expected: 
  ["abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=0/20250226_173415_00146_3jqmh_1405bd1c-d9b8-4a31-9d00-b88ee273dd05",
      "abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=4/20250226_173415_00146_3jqmh_5acff14c-07be-40a9-9bc4-7edfc2a9c348",
      "abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=1/20250226_173415_00146_3jqmh_6f770fad-f068-4e29-89ec-20ef8a8b000e",
      "abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=2/20250226_173415_00146_3jqmh_64fda640-2513-49a1-802c-54ded96632b4",
      "abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=3/20250226_173415_00146_3jqmh_29cd5508-84f7-4e5c-83cb-59a6eabd2d99"]
 but was: 
  ["abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=0/20250226_173414_00144_3jqmh_73ccad06-376c-4714-9a68-718b9182f844",
      "abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=0/20250226_173415_00146_3jqmh_1405bd1c-d9b8-4a31-9d00-b88ee273dd05",
      "abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=1/20250226_173414_00144_3jqmh_5a968809-9eab-4f5f-978d-3934385da9b5",
      "abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=1/20250226_173415_00146_3jqmh_6f770fad-f068-4e29-89ec-20ef8a8b000e",
      "abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=2/20250226_173414_00144_3jqmh_c01712b8-5018-44aa-b4f1-37b41b590042",
      "abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=2/20250226_173415_00146_3jqmh_64fda640-2513-49a1-802c-54ded96632b4",
      "abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=3/20250226_173414_00144_3jqmh_b1563a32-d0dc-42c8-bb64-970d9adcdffa",
      "abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=3/20250226_173415_00146_3jqmh_29cd5508-84f7-4e5c-83cb-59a6eabd2d99",
      "abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=4/20250226_173414_00144_3jqmh_[838](https://github.com/trinodb/trino/actions/runs/13549751375/job/37870295972#step:12:839)4f596-cf60-4c93-97ce-a30dac472533",
      "abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-3at82t535c/test_vacuum8g14qfoc74/regionkey=4/20250226_173415_00146_3jqmh_5acff14c-07be-40a9-9bc4-7edfc2a9c348"]
```
https://github.com/trinodb/trino/actions/runs/13549751375/job/37870295972

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/13764289621/job/38487190491

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/13914129549/job/38934009797?pr=25334#step:12:799

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/13957141057/job/39070972215

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/14235495109/job/39894004168
