### ISSUE TITLE
Flaky TestParquetReader.testArrayOfMapOfArray 

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#19469]
```
Error:  Tests run: 188, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1058 s <<< FAILURE! -- in TestSuite
Error:  io.trino.plugin.hive.parquet.TestParquetReader.testArrayOfMapOfArray -- Time elapsed: 1.365 s <<< FAILURE!
java.lang.IllegalArgumentException: maxCapacityHint can't be less than initialSlabSize 1024 100
	at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:97)
	at org.apache.parquet.bytes.CapacityByteArrayOutputStream.<init>(CapacityByteArrayOutputStream.java:153)
	at org.apache.parquet.column.values.plain.PlainValuesWriter.<init>(PlainValuesWriter.java:47)
	at org.apache.parquet.column.values.factory.DefaultV1ValuesWriterFactory.getBinaryValuesWriter(DefaultV1ValuesWriterFactory.java:84)
	at org.apache.parquet.column.values.factory.DefaultV1ValuesWriterFactory.newValuesWriter(DefaultV1ValuesWriterFactory.java:57)
	at org.apache.parquet.column.values.factory.DefaultValuesWriterFactory.newValuesWriter(DefaultValuesWriterFactory.java:52)
	at org.apache.parquet.column.ParquetProperties.newValuesWriter(ParquetProperties.java:167)
	at org.apache.parquet.column.impl.ColumnWriterBase.<init>(ColumnWriterBase.java:84)
	at org.apache.parquet.column.impl.ColumnWriterV1.<init>(ColumnWriterV1.java:43)
	at org.apache.parquet.column.impl.ColumnWriteStoreV1.createColumnWriter(ColumnWriteStoreV1.java:50)
	at org.apache.parquet.column.impl.ColumnWriteStoreBase.<init>(ColumnWriteStoreBase.java:125)
	at org.apache.parquet.column.impl.ColumnWriteStoreV1.<init>(ColumnWriteStoreV1.java:44)
	at org.apache.parquet.column.ParquetProperties.newColumnWriteStore(ParquetProperties.java:220)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:116)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:101)
	at org.apache.parquet.hadoop.ParquetRecordWriter.<init>(ParquetRecordWriter.java:152)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:505)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:432)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:427)
	at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.<init>(ParquetRecordWriterWrapper.java:70)
	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getParquerRecordWriterWrapper(MapredParquetOutputFormat.java:137)
	at io.trino.plugin.hive.parquet.write.TestingMapredParquetOutputFormat.getHiveRecordWriter(TestingMapredParquetOutputFormat.java:69)
	at io.trino.plugin.hive.parquet.ParquetTester.writeParquetColumn(ParquetTester.java:632)
	at io.trino.plugin.hive.parquet.ParquetTester.assertRoundTripWithHiveWriter(ParquetTester.java:390)
	at io.trino.plugin.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:347)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:312)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:289)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:275)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:249)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:242)
	at io.trino.plugin.hive.parquet.AbstractTestParquetReader.testArrayOfMapOfArray(AbstractTestParquetReader.java:462)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by wendigo** [comment]
https://github.com/trinodb/trino/actions/runs/6589961684/job/17905656144

**Comment by wendigo** [comment]
cc @raunaqmorarka

**Comment by wendigo** [comment]
Haven't see that in a while. Closing
