### ISSUE TITLE
trino-cli crashes with ` Error executing '/opt/homebrew/opt/coreutils/libexec/gnubin/stty icrnl ixon echo icanon iexten min 1 time 0': stty: 'standard input': unable to perform all requested operations`

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#19549]
```
master$ client/trino-cli/target/trino-cli-431-SNAPSHOT-executable.jar
trino> s;
Exception in thread "main" java.io.IOError: java.io.IOException: Error executing '/opt/homebrew/opt/coreutils/libexec/gnubin/stty icrnl ixon echo icanon iexten min 1 time 0': stty: 'standard input': unable to perform all requested operations
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:57)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:774)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:553)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:538)
	at io.trino.cli.InputReader.readLine(InputReader.java:71)
	at io.trino.cli.Console.runConsole(Console.java:244)
	at io.trino.cli.Console.run(Console.java:192)
	at io.trino.cli.Console.call(Console.java:109)
	at io.trino.cli.Console.call(Console.java:79)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.trino.cli.Trino.main(Trino.java:47)
Caused by: java.io.IOException: Error executing '/opt/homebrew/opt/coreutils/libexec/gnubin/stty icrnl ixon echo icanon iexten min 1 time 0': stty: 'standard input': unable to perform all requested operations
	at org.jline.utils.ExecHelper.exec(ExecHelper.java:48)
	at org.jline.terminal.impl.exec.ExecPty.doSetAttr(ExecPty.java:104)
	at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:46)
	at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:55)
	... 17 more
master$
```

**Comment by findepi** [comment]
reverting https://github.com/trinodb/trino/pull/19534 solves the problem for me
cc @wendigo

**Comment by wendigo** [comment]
It works for me. Why do you have stty in your homebrew?

**Comment by wendigo** [comment]
https://github.com/jline/jline3/issues/97

**Comment by findepi** [comment]
> Why do you have stty in your homebrew?

I have absolutely no idea.

**Comment by findepi** [comment]
> [jline/jline3#97](https://github.com/jline/jline3/issues/97)

i thought this means the bug is fixed and we're just waiting for a release. But now i noticed it's a 6 year old issue.

**Comment by wendigo** [comment]
I've reported it back to jline: https://github.com/jline/jline3/issues/889

It works with the stty shipped with MacOS Sonoma. I can reproduce it with the homebrew coreutils:

```
❯ PATH=/opt/homebrew/opt/coreutils/libexec/gnubin/:$PATH ./client/trino-cli/target/trino-cli-431-SNAPSHOT-executable.jar
```

**Comment by findepi** [comment]
thank you @wendigo
