### ISSUE TITLE
TestBackgroundHiveSplitLoader tests fail locally

### ISSUE THREAD

**Issue by martint** [trinodb/trino#19555]
`testSplitsGenerationWithAbortedTransactions()` and `testFullAcidTableWithOriginalFiles()` fail with:

```
java.lang.AssertionError: /var/folders/_v/2kb9fsms6zl47z4m635n3scc0000gn/T/TestBackgroundHiveSplitLoader6904566940452452979/delta_0000001_0000001_0000/bucket_00000 not found in splits [] expected [true] but found [false]

	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at io.trino.plugin.hive.TestBackgroundHiveSplitLoader.testSplitsGenerationWithAbortedTransactions(TestBackgroundHiveSplitLoader.java:577)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by martint** [comment]
If seems to fail because on MacOS, the temporary path created by the tests looks like `/var/folders/_v/2kb9fsms6zl47z4m635n3scc0000gn/T/TestBackgroundHiveSplitLoader6332615007675128291` and AcidTables.listFiles() filters out any paths that contain `_`

**Comment by martint** [comment]
This is the commit that broke this behavior, which changed the check from `startsWith(...)` to `contains(...)`: 76a98c70cedfa801e0eb229de61274d81f90e63a
