### ISSUE TITLE
Query fails with inline function

### ISSUE THREAD

**Issue by guyco33** [trinodb/trino#19561]
Success:
```
WITH FUNCTION my_func(x bigint) RETURNS bigint RETURN x * 2
SELECT my_func(nationkey) FROM tpch.tiny.nation
WHERE nationkey >= 1
```

Fails:
```
WITH FUNCTION my_func(x bigint) RETURNS bigint RETURN x * 2
SELECT my_func(nationkey) FROM tpch.tiny.nation
```

```
INTERNAL_ERROR

GENERIC_INTERNAL_ERROR (65536)

java.lang.IllegalArgumentException: Connector expressions cannot reference inline functions: system.$query.my_func
	at io.trino.sql.planner.ConnectorExpressionTranslator$SqlToConnectorExpressionTranslator.visitFunctionCall(ConnectorExpressionTranslator.java:704)
	at io.trino.sql.planner.ConnectorExpressionTranslator$SqlToConnectorExpressionTranslator.visitFunctionCall(ConnectorExpressionTranslator.java:544)
	at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at io.trino.sql.planner.PartialTranslator$Visitor.visitExpression(PartialTranslator.java:73)
	at io.trino.sql.planner.PartialTranslator$Visitor.visitExpression(PartialTranslator.java:57)
	at io.trino.sql.tree.AstVisitor.visitFunctionCall(AstVisitor.java:312)
	at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at io.trino.sql.planner.PartialTranslator.extractPartialTranslations(PartialTranslator.java:53)
	at io.trino.sql.planner.iterative.rule.PushProjectionIntoTableScan.lambda$apply$0(PushProjectionIntoTableScan.java:112)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.sql.planner.iterative.rule.PushProjectionIntoTableScan.apply(PushProjectionIntoTableScan.java:119)
	at io.trino.sql.planner.iterative.rule.PushProjectionIntoTableScan.apply(PushProjectionIntoTableScan.java:69)
	at io.trino.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:209)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:176)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:139)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:259)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:141)
	at io.trino.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:123)
	at io.trino.sql.planner.LogicalPlanner.runOptimizer(LogicalPlanner.java:299)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:269)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:238)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:233)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:486)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:466)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:404)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:256)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at io.trino.$gen.Trino_431____20231028_172033_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by guyco33** [comment]
cc @martint @electrum @dain

**Comment by mosabua** [comment]
Imho this should actually fail .. although I dont know what the spec says. Of course the error message should be something like

Declared inline routine test() is not used in the query. Remove the declaration or add usage of the routine.

**Comment by martint** [comment]
@mosabua, the function *is* used in the query:

> WITH FUNCTION my_func(x bigint) RETURNS bigint RETURN x * 2
> SELECT **my_func(nationkey)** FROM tpch.tiny.nation

Regardless, it's not an error if a function is not referenced in the query.

**Comment by mosabua** [comment]
Oh .. sorry .. completely overlooked that.
