### ISSUE TITLE
Flaky or broken TestDeltaLakeCreateTableAsSelectCompatibility.testReplaceTableWithSchemaChangeOnCheckpoint on 9.1 LTS

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#19580]
https://github.com/trinodb/trino/actions/runs/6700193910/job/18206194746?pr=19564

```
tests               | 2023-10-31 06:37:50 INFO: FAILURE     /    io.trino.tests.product.deltalake.TestDeltaLakeCreateTableAsSelectCompatibility.testReplaceTableWithSchemaChangeOnCheckpoint (Groups: profile_specific_tests, delta-lake-databricks, delta-lake-exclude-133, delta-lake-oss) took 36.9 seconds
tests               | 2023-10-31 06:37:50 SEVERE: Failure cause:
tests               | java.lang.AssertionError: expected [00000000000000000011.json] but found [00000000000000000012.json]
tests               | 	at org.testng.Assert.fail(Assert.java:94)
tests               | 	at org.testng.Assert.failNotEquals(Assert.java:513)
tests               | 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
tests               | 	at org.testng.Assert.assertEquals(Assert.java:116)
tests               | 	at org.testng.Assert.assertEquals(Assert.java:190)
tests               | 	at org.testng.Assert.assertEquals(Assert.java:200)
tests               | 	at io.trino.tests.product.deltalake.TransactionLogAssertions.assertTransactionLogVersion(TransactionLogAssertions.java:50)
tests               | 	at io.trino.tests.product.deltalake.TestDeltaLakeCreateTableAsSelectCompatibility.testReplaceTableWithSchemaChangeOnCheckpoint(TestDeltaLakeCreateTableAsSelectCompatibility.java:195)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ebyhr** [comment]
The test passed locally. I guess OPTIMIZE or something happened in Databricks side.
