### ISSUE TITLE
query fails inconsistently in trino 431 that works in <= 430 with aggregates

### ISSUE THREAD

**Issue by brokenjacobs** [trinodb/trino#19596]
The oddest thing is this works for some partitions and not others. I'm not sure WHAT in the query is failing but rolling back to trino 430 causes it to work everywhere:
```
select 
  load_ds,count(1) as msg_count,array_sort(array_distinct(flatten(array_agg(distinct(readout_days))))) as data_days 
  from hive.l0files.messages 
  where load_ds > '2023-09-15' and site='TECR' 
  group by load_ds order by load_ds;
```

```
SQL Error [65536]: Query failed (#20231031_141015_20118_afx4r): Invalid position 2 in block with 2 positions
```

**Comment by wendigo** [comment]
cc @dain

**Comment by Gingernaut** [comment]
+1 on this issue

**Comment by martint** [comment]
Can you post the full stack trace?

**Comment by brokenjacobs** [comment]
So I got the stack traces, also a bit more info. This query succeeds when I run with only one worker in my cluster. When I go to 2 workers I get a slightly different error message than before, and with 3 or more workers I get the same error as before. I have included both stack traces:

```
java.lang.IllegalArgumentException: Invalid position 1 in block with 1 positions
	at io.trino.spi.block.BlockUtil.checkValidPosition(BlockUtil.java:70)
	at io.trino.spi.block.DictionaryBlock.getId(DictionaryBlock.java:571)
	at io.trino.spi.type.ArrayType.hashOperator(ArrayType.java:587)
	at io.trino.operator.InterpretedHashGenerator.nullSafeHash(InterpretedHashGenerator.java:104)
	at io.trino.operator.InterpretedHashGenerator.hashPosition(InterpretedHashGenerator.java:85)
	at io.trino.operator.HashGenerator.getPartition(HashGenerator.java:24)
	at io.trino.sql.planner.HashBucketFunction.getBucket(HashBucketFunction.java:39)
	at io.trino.operator.BucketPartitionFunction.getPartition(BucketPartitionFunction.java:46)
	at io.trino.operator.output.PagePartitioner.partitionPageByRow(PagePartitioner.java:200)
	at io.trino.operator.output.PagePartitioner.partitionPage(PagePartitioner.java:154)
	at io.trino.operator.output.PartitionedOutputOperator.addInput(PartitionedOutputOperator.java:335)
	at io.trino.operator.Driver.processInternal(Driver.java:400)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_431____20231106_200103_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
When running with 3 or more worker nodes (tested up to 6):
```
java.lang.IllegalArgumentException: Invalid position 2 in block with 2 positions
	at io.trino.spi.block.BlockUtil.checkValidPosition(BlockUtil.java:70)
	at io.trino.spi.block.DictionaryBlock.getId(DictionaryBlock.java:571)
	at io.trino.spi.type.ArrayType.hashOperator(ArrayType.java:587)
	at io.trino.operator.InterpretedHashGenerator.nullSafeHash(InterpretedHashGenerator.java:104)
	at io.trino.operator.InterpretedHashGenerator.hashPosition(InterpretedHashGenerator.java:85)
	at io.trino.operator.HashGenerator.getPartition(HashGenerator.java:24)
	at io.trino.sql.planner.HashBucketFunction.getBucket(HashBucketFunction.java:39)
	at io.trino.operator.BucketPartitionFunction.getPartition(BucketPartitionFunction.java:46)
	at io.trino.operator.output.PagePartitioner.partitionPageByRow(PagePartitioner.java:200)
	at io.trino.operator.output.PagePartitioner.partitionPage(PagePartitioner.java:154)
	at io.trino.operator.output.PartitionedOutputOperator.addInput(PartitionedOutputOperator.java:335)
	at io.trino.operator.Driver.processInternal(Driver.java:400)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_431____20231106_200103_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by brokenjacobs** [comment]
@martint anything else you need?

**Comment by martint** [comment]
Not at this time. That's very helpful. Thanks! We're investigating.
