### ISSUE TITLE
Flaky OutOfMemoryError in suite-delta-lake-oss product test

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#19602]
It took 37.84m on https://github.com/trinodb/trino/actions/runs/6709602167/job/18234966681

```
TestDeltaLakeDeleteCompatibility.testDeleteOnAppendOnlyWriterFeature took 59.76s
TestDeltaLakeDeleteCompatibility.testDeleteOnEnforcedConstraintsReturnsRowsCount [true] took 1.01m
TestDeltaLakeDeleteCompatibility.testDeleteOnEnforcedConstraintsReturnsRowsCount [false] took 1.68m
TestDeltaLakeDeleteCompatibility.testDeletionVectors [none] took 2.90m
TestDeltaLakeDeleteCompatibility.testDeletionVectors [name] took 3.13m
TestDeltaLakeDeleteCompatibility.testDeletionVectors [id] took 3.48m
TestDeltaLakeDeleteCompatibility.testDeletionVectorsAbsolutePath took 4.14m
TestDeltaLakeDeleteCompatibility.testDeletionVectorsAcrossAddFile [true] took 4.13m
TestDeltaLakeDeleteCompatibility.testDeletionVectorsAcrossAddFile [false] took 4.85m
TestDeltaLakeDeleteCompatibility.testDeletionVectorsDeleteFrom took 2.80m
TestDeltaLakeDeleteCompatibility.testDeletionVectorsLargeNumbers took 3.34m
TestDeltaLakeDeleteCompatibility.testDeletionVectorsMergeDelete took 2.23m
TestDeltaLakeDeleteCompatibility.testDeletionVectorsOptimize took 59.74s
TestDeltaLakeDeleteCompatibility.testDisableDeletionVectors took 31.46s
TestDeltaLakeDeleteCompatibility took 37.84m
```

**Comment by ebyhr** [comment]
Note: The test finished in 5m on my laptop.

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/6729002204/job/18289611717

```
tests               | 2023-11-02 13:34:00 WARNING: No test started or completed in 8.00m. Running tests:
tests               | 	io.trino.tests.product.deltalake.TestDeltaLakeDeleteCompatibility running for 39.18m
tests               | 	io.trino.tests.product.deltalake.TestDeltaLakeDeleteCompatibility.testDeletionVectorsOptimize running for 8.07m.
tests               | 
tests               | Full Thread Dump:
tests               | "main" prio=5 Id=1 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@55c12096
tests               | 	at java.base@21.0.1/jdk.internal.misc.Unsafe.park(Native Method)
tests               | 	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@55c12096
tests               | 	at java.base@21.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
tests               | 	at java.base@21.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1758)
tests               | 	at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1475)
tests               | 	at app//org.testng.TestRunner.privateRun(TestRunner.java:735)
tests               | 	at app//org.testng.TestRunner.run(TestRunner.java:610)
tests               | 	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
tests               | 	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
tests               | 	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
tests               | 	at app//org.testng.SuiteRunner.run(SuiteRunner.java:289)
tests               | 	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
tests               | 	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
tests               | 	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
tests               | 	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
tests               | 	at app//org.testng.TestNG.runSuites(TestNG.java:1133)
tests               | 	at app//org.testng.TestNG.run(TestNG.java:1104)
tests               | 	at app//io.trino.tempto.runner.TemptoRunner.run(TemptoRunner.java:93)
tests               | 	at app//io.trino.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:65)
tests               | 	at app//io.trino.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:53)
tests               | 	at app//io.trino.tests.product.TemptoProductTestRunner.main(TemptoProductTestRunner.java:27)
tests               | 
tests               | 
tests               | "Reference Handler" daemon prio=10 Id=5 RUNNABLE
tests               | 	at java.base@21.0.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
tests               | 	at java.base@21.0.1/java.lang.ref.Reference.processPendingReferences(Reference.java:246)
tests               | 	at java.base@21.0.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:208)
tests               | 
tests               | 
tests               | "pool-2-thread-1" prio=5 Id=21 RUNNABLE (in native)
tests               | 	at java.base@21.0.1/sun.nio.ch.SocketDispatcher.read0(Native Method)
tests               | 	at java.base@21.0.1/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47)
tests               | 	at java.base@21.0.1/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:256)
tests               | 	at java.base@21.0.1/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:307)
tests               | 	at java.base@21.0.1/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
tests               | 	at java.base@21.0.1/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
tests               | 	at java.base@21.0.1/java.net.Socket$SocketInputStream.read(Socket.java:1099)
tests               | 	at java.base@21.0.1/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
tests               | 	at java.base@21.0.1/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
tests               | 	at java.base@21.0.1/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
tests               | 	at java.base@21.0.1/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
tests               | 	at org.apache.hive.org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
tests               | 	at org.apache.hive.org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
tests               | 	at org.apache.hive.org.apache.thrift.transport.TSaslTransport.readLength(TSaslTransport.java:376)
tests               | 	at org.apache.hive.org.apache.thrift.transport.TSaslTransport.readFrame(TSaslTransport.java:453)
tests               | 	at org.apache.hive.org.apache.thrift.transport.TSaslTransport.read(TSaslTransport.java:435)
tests               | 	at org.apache.hive.org.apache.thrift.transport.TSaslClientTransport.read(TSaslClientTransport.java:37)
tests               | 	at org.apache.hive.org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
tests               | 	at org.apache.hive.org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
tests               | 	at org.apache.hive.org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
tests               | 	at org.apache.hive.org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
tests               | 	at org.apache.hive.org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
tests               | 	at org.apache.hive.service.rpc.thrift.TCLIService$Client.recv_GetOperationStatus(TCLIService.java:475)
tests               | 	at org.apache.hive.service.rpc.thrift.TCLIService$Client.GetOperationStatus(TCLIService.java:462)
tests               | 	at java.base@21.0.1/java.lang.invoke.LambdaForm$DMH/0x00007f6fd46a4000.invokeInterface(LambdaForm$DMH)
tests               | 	at java.base@21.0.1/java.lang.invoke.LambdaForm$MH/0x00007f6fd46d7400.invoke(LambdaForm$MH)
tests               | 	at java.base@21.0.1/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
tests               | 	at java.base@21.0.1/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
tests               | 	at java.base@21.0.1/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
tests               | 	at java.base@21.0.1/java.lang.reflect.Method.invoke(Method.java:580)
tests               | 	at org.apache.hive.jdbc.HiveConnection$SynchronizedHandler.invoke(HiveConnection.java:1585)
tests               | 	at jdk.proxy3/jdk.proxy3.$Proxy59.GetOperationStatus(Unknown Source)
tests               | 	at org.apache.hive.jdbc.HiveStatement.waitForOperationToComplete(HiveStatement.java:378)
tests               | 	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:266)
tests               | 	at app//io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
tests               | 	at app//io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 	at app//io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at app//io.trino.tests.product.utils.QueryExecutors$3.lambda$executeQuery$0(QueryExecutors.java:136)
tests               | 	at app//io.trino.tests.product.utils.QueryExecutors$3$$Lambda/0x00007f6fd4639bd0.get(Unknown Source)
tests               | 	at app//dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
tests               | 	at app//dev.failsafe.Functions$$Lambda/0x00007f6fd444aa68.get(Unknown Source)
tests               | 	at app//dev.failsafe.Functions.lambda$get$0(Functions.java:46)
tests               | 	at app//dev.failsafe.Functions$$Lambda/0x00007f6fd444b810.apply(Unknown Source)
tests               | 	at app//dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
tests               | 	at app//dev.failsafe.internal.RetryPolicyExecutor$$Lambda/0x00007f6fd4449000.apply(Unknown Source)
tests               | 	at app//dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
tests               | 	at app//dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 	at app//dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
tests               | 	at app//io.trino.tests.product.utils.QueryExecutors$3.executeQuery(QueryExecutors.java:136)
tests               | 	at app//io.trino.tests.product.deltalake.TestDeltaLakeDeleteCompatibility.testDeletionVectorsOptimize(TestDeltaLakeDeleteCompatibility.java:501)
tests               | 	at java.base@21.0.1/java.lang.invoke.LambdaForm$DMH/0x00007f6fd40d8000.invokeVirtual(LambdaForm$DMH)
tests               | 	at java.base@21.0.1/java.lang.invoke.LambdaForm$MH/0x00007f6fd4448400.invoke(LambdaForm$MH)
tests               | 	at java.base@21.0.1/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
tests               | 	at java.base@21.0.1/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:153)
tests               | 	at java.base@21.0.1/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
tests               | 	at java.base@21.0.1/java.lang.reflect.Method.invoke(Method.java:580)
tests               | 	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at app//org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at app//org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at app//org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
tests               | 	at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
tests               | 	at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
tests               | 	at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)
tests               | 
tests               | 	locked synchronizers:
tests               | 	- java.util.concurrent.locks.ReentrantLock$NonfairSync@499d9016
tests               | 	- java.util.concurrent.locks.ReentrantLock$NonfairSync@1504dc23
tests               | 	- java.util.concurrent.locks.ReentrantLock$FairSync@4ead4195
tests               | 	- java.util.concurrent.ThreadPoolExecutor$Worker@2e013ba1
tests               | 
tests               | 
tests               | "java-sdk-http-connection-reaper" daemon prio=5 Id=25 TIMED_WAITING
tests               | 	at java.base@21.0.1/java.lang.Thread.sleep0(Native Method)
tests               | 	at java.base@21.0.1/java.lang.Thread.sleep(Thread.java:509)
tests               | 	at app//com.amazonaws.http.IdleConnectionReaper.run(IdleConnectionReaper.java:188)
```

```
spark               | java.lang.OutOfMemoryError: Java heap space
spark               | Uncaught exception in thread Thread[Executor task launch worker for task 27.0 in stage 6124.0 (TID 50417),5,main]
spark               | java.lang.OutOfMemoryError: Java heap space
spark               | Task 27 in stage 6124.0 failed 1 times; aborting job
spark               | Error running hive query as user : hive
spark               | java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
spark               | This stopped SparkContext was created at:
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/pull/19588

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/6844776862/job/18609309593?pr=19588
