### ISSUE TITLE
Table repeatedly corrupted with ICEBERG_CANNOT_OPEN_SPLIT

### ISSUE THREAD

**Issue by erikcw** [trinodb/trino#19638]
For the 4th consecutive week (always over the weekend interestingly enough), I've had an iceberg table corrupted and Trino erroring out on queries with `ICEBERG_CANNOT_OPEN_SPLIT`.  I'm currently on Trino v431 (though this also happened on the previous version(s).) with the iceberg table metadata hosted on AWS Glue backed by parquet file on S3.

```sql
-- SELECT * FROM my_table limit 100

io.trino.spi.TrinoException: Error opening Iceberg split s3://BUCKET/parquet/campaigns-pre-id-iceberg3/data/campaign=ae7eb86e-affe-4148-a18d-032194d5aa80/version=a/00105-365-b96a6baf-9c49-4ec0-a851-b8f428737422-00001.parquet (offset=4, length=1952052): File s3://BUCKET/parquet/campaigns-pre-id-iceberg3/data/campaign=ae7eb86e-affe-4148-a18d-032194d5aa80/version=a/00105-365-b96a6baf-9c49-4ec0-a851-b8f428737422-00001.parquet not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: STFD5CGNN5AM8074; S3 Extended Request ID: bq7drp2SpzqJKJYBcoE6u2Ln0gfuHa2M/VVuNidqYwEIdBB67CRW/hD+/QHF+BagPRy1/xVJfI2isl+LE0MS0g==; Proxy: null) (Bucket: BUCKET, Key: parquet/campaigns-pre-id-iceberg3/data/campaign=ae7eb86e-affe-4148-a18d-032194d5aa80/version=a/00105-365-b96a6baf-9c49-4ec0-a851-b8f428737422-00001.parquet)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createParquetPageSource(IcebergPageSourceProvider.java:1139)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createDataPageSource(IcebergPageSourceProvider.java:577)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createPageSource(IcebergPageSourceProvider.java:364)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createPageSource(IcebergPageSourceProvider.java:263)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:48)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:265)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:193)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:359)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:255)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:145)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_431____20231105_150418_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.FileNotFoundException: File s3://BUCKET/parquet/campaigns-pre-id-iceberg3/data/campaign=ae7eb86e-affe-4148-a18d-032194d5aa80/version=a/00105-365-b96a6baf-9c49-4ec0-a851-b8f428737422-00001.parquet not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: STFD5CGNN5AM8074; S3 Extended Request ID: bq7drp2SpzqJKJYBcoE6u2Ln0gfuHa2M/VVuNidqYwEIdBB67CRW/hD+/QHF+BagPRy1/xVJfI2isl+LE0MS0g==; Proxy: null) (Bucket: BUCKET, Key: parquet/campaigns-pre-id-iceberg3/data/campaign=ae7eb86e-affe-4148-a18d-032194d5aa80/version=a/00105-365-b96a6baf-9c49-4ec0-a851-b8f428737422-00001.parquet)
	at io.trino.filesystem.hdfs.HdfsInput.readTail(HdfsInput.java:68)
	at io.trino.filesystem.TrinoInput.readTail(TrinoInput.java:43)
	at io.trino.filesystem.tracing.TracingInput.lambda$readTail$3(TracingInput.java:81)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
	at io.trino.filesystem.tracing.TracingInput.readTail(TracingInput.java:81)
	at io.trino.plugin.hive.parquet.MemoryParquetDataSource.<init>(MemoryParquetDataSource.java:56)
	at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createDataSource(ParquetPageSourceFactory.java:346)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createParquetPageSource(IcebergPageSourceProvider.java:1000)
	... 32 more
Caused by: java.io.FileNotFoundException: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: STFD5CGNN5AM8074; S3 Extended Request ID: bq7drp2SpzqJKJYBcoE6u2Ln0gfuHa2M/VVuNidqYwEIdBB67CRW/hD+/QHF+BagPRy1/xVJfI2isl+LE0MS0g==; Proxy: null) (Bucket: bidder.clickcertain.com, Key: parquet/campaigns-pre-id-iceberg3/data/campaign=ae7eb86e-affe-4148-a18d-032194d5aa80/version=a/00105-365-b96a6baf-9c49-4ec0-a851-b8f428737422-00001.parquet)
	at io.trino.hdfs.s3.TrinoS3FileSystem.throwIfFileNotFound(TrinoS3FileSystem.java:2074)
	at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3InputStream.lambda$openStream$2(TrinoS3FileSystem.java:1580)
	at io.trino.hdfs.s3.RetryDriver.run(RetryDriver.java:125)
	at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3InputStream.openStream(TrinoS3FileSystem.java:1557)
	at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3InputStream.openStream(TrinoS3FileSystem.java:1542)
	at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3InputStream.seekStream(TrinoS3FileSystem.java:1535)
	at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3InputStream.lambda$read$1(TrinoS3FileSystem.java:1479)
	at io.trino.hdfs.s3.RetryDriver.run(RetryDriver.java:125)
	at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3InputStream.read(TrinoS3FileSystem.java:1478)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at java.base/java.io.DataInputStream.read(DataInputStream.java:151)
	at java.base/java.io.DataInputStream.read(DataInputStream.java:151)
	at io.trino.hdfs.FSDataInputStreamTail.readTail(FSDataInputStreamTail.java:59)
	at io.trino.filesystem.hdfs.HdfsInput.readTail(HdfsInput.java:63)
	... 39 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: STFD5CGNN5AM8074; S3 Extended Request ID: bq7drp2SpzqJKJYBcoE6u2Ln0gfuHa2M/VVuNidqYwEIdBB67CRW/hD+/QHF+BagPRy1/xVJfI2isl+LE0MS0g==; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5520)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5467)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1554)
	at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3InputStream.lambda$openStream$2(TrinoS3FileSystem.java:1563)
	... 52 more

```

When I check s3, the file `s3://BUCKET/parquet/campaigns-pre-id-iceberg3/data/campaign=ae7eb86e-affe-4148-a18d-032194d5aa80/version=a/00105-365-b96a6baf-9c49-4ec0-a851-b8f428737422-00001.parquet` does not exist.

I'm not sure what the root cause is.  Since the file doesn't exist, I'm guessing trino may be crashing when writing results leaving orphan pointers in the metadata.

I've attempted to rollback to previous snapshots as well as manually edit the iceberg metadata, but the same error persists.

My current workaround for getting the table back into production is creating a Hive table pointing at `s3://BUCKET/parquet/campaigns-pre-id-iceberg3/data/` as well as a brand new iceberg table and then `INSERT INTO iceberg SELECT * FROM hive_table`.

Is there a better way to do an "inplace" repair of and iceberg table?

**Comment by raunaqmorarka** [comment]
cc: @alexjo2144 @findinpath

**Comment by findinpath** [comment]
@erikcw are you possibly using fault taulerant execution mode ?

https://github.com/trinodb/trino/blob/066f0cf90fcdb17ad564be892792f3437d460bed/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L2355-L2358

cc @losipiuk

**Comment by erikcw** [comment]
@findinpath @losipiuk No, I'm not using fault tolerant execution.  I do have `spill-enabled=true` if that matters.

**Comment by tbaeg** [comment]
@erikcw Since it seems to consistently be over the weekend, it may be worthwhile to check and see if you have a data being deleted from underneath of it. One place to check would be the S3 bucket policy. 

Similarly, I wonder if it's a table curation process that might be hosing the table. One scenario I have ran into is..

1. Long running insert takes place and parquet files are being written to S3 but not yet committed to iceberg metadata.
2. Curation process occurs, expiring snapshots and removing orphaned files and also now deletes "new" data (since orphaned files are anything that are not tracked in the metadata).
3. Table is now missing data and corrupted.

Hopefully this gives you some possible paths to the root cause.

**Comment by hashhar** [comment]
One other thing to think of is if the table is registered to multiple Iceberg catalogs. That is also a possible case where the manifest or table scans will complain about files that don't actually exist.

**Comment by ravenac95** [comment]
@erikcw did you happen to get any resolution to this. It seems we are also running into similar issues with iceberg on gcs and the rest catalog via nessie.

**Comment by mannerni** [comment]
Hi, We have faced similar error while using trino (479) with iceberg REST catalog (1.10.1). I suspect the issue is with optimization commands. We run optimize table by sizes (2/4/40/128MB) -> optmize manifest -> remove-snapshots -> remove-orphan-files. These 4 commands are run without any wait in between them. 
The leading command causing seems to be remove-orphan-files. The severe problem is we are not able to read that parquet file at all. Need some reliable handling and recommendation to avoid file corruption etc.
Error detail:
(Error opening Iceberg split s3://xxxxx-us-east-1-ts-zbc/t001/tablename/data/time_month=2022-03/id_bucket=3/20260209_035531_00064_t2j6q-856320fd-41db-4f68-acd1-317788e9238e.parquet (offset=14926945, length=3745233): s3://xxxxx-us-east-1-ts-zbc/t001/tablename/data/time_month=2022-03/id_bucket=3/20260209_035531_00064_t2j6q-856320fd-41db-4f68-acd1-317788e9238e.parquet)".
