### ISSUE TITLE
Flaky TestDeltaLakePartitioningCompatibility.testSparkCanReadFromTableUpdatedByTrino

### ISSUE THREAD

**Issue by lukasz-stec** [trinodb/trino#19641]
https://github.com/trinodb/trino/actions/runs/6756937275/job/18367118068
https://github.com/trinodb/trino/actions/runs/6760290728/job/18374048729
https://github.com/trinodb/trino/actions/runs/6763903372/job/18383694788

The source seems to be `OutOfMemoryError` in spark

```
+---------------+--------+---------+---------+--------+------+---------+---------+
|     container |    cpu |     mem | max mem |  mem % | pids |  net in | net out |
+---------------+--------+---------+---------+--------+------+---------+---------+
| hadoop-master |  0.37% | 15.61GB |  1.84GB | 11.81% |  776 |  3.14MB |  6.78MB |
|         minio |    n/a |         |         |        |      |         |         |
| presto-master |  0.22% | 15.61GB |  3.04GB | 19.47% |  278 | 15.34MB | 19.57MB |
|         spark | 91.61% | 15.61GB |  1.82GB | 11.68% |  139 | 38.41MB | 38.81MB |
|         tests |  0.01% | 15.61GB |  0.55GB |  3.52% |   23 |  6.24MB |  4.05MB |
+---------------+--------+---------+---------+--------+------+---------+---------+
spark               | Exception in task 2.0 in stage 6345.0 (TID 51907)
spark               | java.lang.OutOfMemoryError: Java heap space
spark               | 	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:61) ~[?:?]
spark               | 	at java.nio.ByteBuffer.allocate(ByteBuffer.java:348) ~[?:?]
spark               | 	at org.apache.spark.storage.memory.SerializedValuesHolder.$anonfun$allocator$1(MemoryStore.scala:715) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.storage.memory.SerializedValuesHolder.$anonfun$allocator$1$adapted(MemoryStore.scala:715) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.storage.memory.SerializedValuesHolder$$Lambda$4474/0x0000000101b8d040.apply(Unknown Source) ~[?:?]
spark               | 	at org.apache.spark.util.io.ChunkedByteBufferOutputStream.allocateNewChunkIfNeeded(ChunkedByteBufferOutputStream.scala:87) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.util.io.ChunkedByteBufferOutputStream.write(ChunkedByteBufferOutputStream.scala:75) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.storage.memory.RedirectableOutputStream.write(MemoryStore.scala:809) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1873) ~[?:?]
spark               | 	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1782) ~[?:?]
spark               | 	at java.io.ObjectOutputStream.<init>(ObjectOutputStream.java:244) ~[?:?]
spark               | 	at org.apache.spark.serializer.JavaSerializationStream.<init>(JavaSerializer.scala:35) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.serializer.JavaSerializerInstance.serializeStream(JavaSerializer.scala:133) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.storage.memory.SerializedValuesHolder.<init>(MemoryStore.scala:725) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsBytes(MemoryStore.scala:350) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1618) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.storage.BlockManager$$Lambda$2813/0x00000001015c0040.apply(Unknown Source) ~[?:?]
spark               | 	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1528) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1592) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1389) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.storage.BlockManager.getOrElseUpdateRDDBlock(BlockManager.scala:1343) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:376) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:326) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328) ~[spark-core_2.12-3.5.0.jar:3.5.0]
spark               | Task 2 in stage 6345.0 failed 1 times; aborting job
```

**Comment by findepi** [comment]
obsolete 🤞
