### ISSUE TITLE
describe Iceberg table throws Unsupported principal type: GROUP

### ISSUE THREAD

**Issue by rstyp** [trinodb/trino#19661]
Describe table is failing with Iceberg connector on 421 if database owner principal type is `group`, same works with hive connector. The recent [changes](https://github.com/trinodb/trino/pull/18895) might cause hive connector to throw same error with latest versions.

Full stacktrace:
```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unsupported principal type: GROUP
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2085)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4011)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4034)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5010)
	at io.trino.cache.EvictableCache.get(EvictableCache.java:145)
	at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:53)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getOptional(CachingHiveMetastore.java:452)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getDatabase(CachingHiveMetastore.java:575)
	at io.trino.plugin.iceberg.catalog.hms.TrinoHiveCatalog.namespaceExists(TrinoHiveCatalog.java:152)
	at io.trino.plugin.iceberg.IcebergMetadata.schemaExists(IcebergMetadata.java:349)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.schemaExists(ClassLoaderSafeConnectorMetadata.java:183)
	at io.trino.tracing.TracingConnectorMetadata.schemaExists(TracingConnectorMetadata.java:116)
	at io.trino.metadata.MetadataManager.lambda$schemaExists$1(MetadataManager.java:237)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at io.trino.metadata.MetadataManager.schemaExists(MetadataManager.java:237)
	at io.trino.tracing.TracingMetadata.schemaExists(TracingMetadata.java:147)
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowColumns(ShowQueriesRewrite.java:501)
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowColumns(ShowQueriesRewrite.java:220)
	at io.trino.sql.tree.ShowColumns.accept(ShowColumns.java:68)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:217)
	at io.trino.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:54)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:92)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:270)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:205)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:844)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)
	at io.trino.$gen.Trino_421.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Unsupported principal type: GROUP
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreUtil.fromMetastoreApiPrincipalType(ThriftMetastoreUtil.java:662)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreUtil.fromMetastoreApiDatabase(ThriftMetastoreUtil.java:356)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.getDatabase(BridgingHiveMetastore.java:81)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadDatabase(CachingHiveMetastore.java:580)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:447)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:433)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3570)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2312)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079)
	... 44 more
```

**Comment by findinpath** [comment]
Relevant code

https://github.com/trinodb/trino/blob/dabf2dc7341c328109f090c69017c35301c74bf5/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java#L635-L648
