### ISSUE TITLE
Flaky io.trino.jdbc.TestJdbcPreparedStatement.testExecuteImmediate

### ISSUE THREAD

**Issue by dominikzalewski** [trinodb/trino#19671]
https://github.com/trinodb/trino/actions/runs/6796848012/job/18477892822?pr=19623

```
Error:  io.trino.jdbc.TestJdbcPreparedStatement.testExecuteImmediate -- Time elapsed: 0.019 s <<< ERROR!
java.sql.SQLException: Query failed (#20231108_103235_00642_k2azw): line 1:1: Table 'blackhole.blackhole.test_table' already exists
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:318)
	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:61)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
	at io.trino.jdbc.TrinoStatement.executeLargeUpdate(TrinoStatement.java:485)
	at io.trino.jdbc.TrinoStatement.executeUpdate(TrinoStatement.java:457)
	at io.trino.jdbc.TestJdbcPreparedStatement.testExplicitPrepareSetting(TestJdbcPreparedStatement.java:1431)
	at io.trino.jdbc.TestJdbcPreparedStatement.testExecuteImmediate(TestJdbcPreparedStatement.java:1400)
```

Looks like the 'DELETE' is not executed always after the test, but only if the test passes 

```
        try (Connection connection = createConnection(explicitPrepare)) {
            try (Statement statement = connection.createStatement()) {
                assertEquals(statement.executeUpdate("CREATE TABLE blackhole.blackhole.test_table (x bigint, y varchar)"), 0);
            }
            
            ... DO SOME TESTING ...
            
            try (Statement statement = connection.createStatement()) {
                assertEquals(statement.executeUpdate("DROP TABLE blackhole.blackhole.test_table"), 0);
            }
         }
```
      
or it might be that a parallel execution is causing this. 

- Changing to 'CREATE TABLE IF NOT EXISTS ...' 
- and putting also the 'DELETE' at the entry of the method (not only at the end)

might only partially solves the issue.

**Comment by hashhar** [comment]
FYI @lpoulain @aalbu

**Comment by lpoulain** [comment]
@hashhar looking at it

**Comment by dominikzalewski** [comment]
@lpoulain https://github.com/trinodb/trino/pull/19672
