### ISSUE TITLE
Problem with regexp_replace function when working with Hive tables containing row(map<varchar, varchar>) data type

### ISSUE THREAD

**Issue by needlssj** [trinodb/trino#19689]
I encountered an issue when using the regexp_replace function in Trino with Hive tables that have a field of type row(map<varchar, varchar>). The problem is that when attempting to search and replace values within the map, I am experiencing a bug.  

Please refer to the attached screenshot, which illustrates the problem.

<img width="1054" alt="企业微信截图_e54c067d-f620-4cf2-a8bf-6830de652efb" src="https://github.com/trinodb/trino/assets/132727326/245333d3-f7e9-43aa-aac1-b124d52e834e">

### Steps to reproduce:
1. Create a Hive table with a column of type row(map<varchar, varchar>).  e.g., `CREATE TABLE hive.tmp.trino_test_11_09 ( event ROW( event_info map(varchar, varchar) ) ) WITH (format = 'ORC');`
3. Execute a query using the regexp_replace function on that column, e.g., regexp_replace(map_column['key'], 'old_value', 'new_value'). e.g., `SELECT "regexp_replace"("event"."event_info" [ 'tags' ], '', '' ) FROM tmp.trino_test_11_09;`

### We are using Trino version 432

**Comment by needlssj** [comment]
### Stack Treace

```
io.trino.spi.TrinoException: Compiler failed. Possible reasons include: the query may have too many or too complex expressions, or the underlying tables may have too many columns
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:2088)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:1971)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:886)
	at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:975)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:886)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at io.trino.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:645)
	at io.trino.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:544)
	at io.trino.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:84)
	at io.trino.execution.SqlTask.tryCreateSqlTaskExecution(SqlTask.java:545)
	at io.trino.execution.SqlTask.updateTask(SqlTask.java:497)
	at io.trino.execution.SqlTaskManager.doUpdateTask(SqlTaskManager.java:544)
	at io.trino.execution.SqlTaskManager.lambda$updateTask$9(SqlTaskManager.java:485)
	at io.trino.$gen.Trino_432____20231109_073339_2.call(Unknown Source)
	at io.trino.execution.SqlTaskManager.updateTask(SqlTaskManager.java:485)
	at io.trino.server.TaskResource.createOrUpdateTask(TaskResource.java:153)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:357)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:62)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/trino/$gen/CursorProcessor_20231109_073634_40.project_0(Lio/trino/spi/connector/ConnectorSession;Lio/trino/spi/connector/RecordCursor;Lio/trino/spi/block/BlockBuilder;)V @115: invokedynamic
  Reason:
    Type 'io/airlift/slice/Slice' (current frame, stack[2]) is not assignable to 'io/trino/type/JoniRegexp'
  Current Frame:
    bci: @115
    flags: { }
    locals: { 'io/trino/$gen/CursorProcessor_20231109_073634_40', 'io/trino/spi/connector/ConnectorSession', 'io/trino/spi/connector/RecordCursor', 'io/trino/spi/block/BlockBuilder', integer }
    stack: { 'io/trino/spi/block/BlockBuilder', 'io/airlift/slice/Slice', 'io/airlift/slice/Slice', 'io/airlift/slice/Slice' }
  Bytecode:
    0000000: 0336 042d 2b2c 03b9 0044 0200 9900 0a04
    0000010: 3604 01a7 000d 2c03 b900 4802 00c0 004a
    0000020: 1504 9900 0957 5701 a700 20ba 0057 0000
    0000030: 1504 9900 0a57 5757 01a7 000f ba00 5d00
    0000040: 0059 c700 0604 3604 1504 9900 0857 01a7
    0000050: 0029 ba00 6200 0015 0499 0009 5757 01a7
    0000060: 0019 ba00 6700 0015 0499 000a 5757 5701
    0000070: a700 08ba 006d 0000 1504 9900 0d57 b900
    0000080: 7301 0057 a700 153a 053a 06ba 0079 0000
    0000090: 1906 1905 b900 7f03 00b1               
  Stackmap Table:
    full_frame(@22,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#64]})
    full_frame(@32,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#64],Object[#74]})
    full_frame(@43,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#64],Object[#74]})
    full_frame(@60,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#64],Object[#74],Object[#134]})
    full_frame(@72,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134]})
    full_frame(@82,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134]})
    full_frame(@98,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134],Object[#134]})
    full_frame(@115,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134],Object[#134],Object[#134]})
    full_frame(@120,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134]})
    full_frame(@135,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134]})
    same_frame(@153)

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2086)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4012)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5013)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5020)
	at com.google.common.cache.ForwardingLoadingCache.getUnchecked(ForwardingLoadingCache.java:54)
	at io.trino.sql.gen.ExpressionCompiler.compileCursorProcessor(ExpressionCompiler.java:85)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:2053)
	... 81 more
Caused by: java.lang.RuntimeException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/trino/$gen/CursorProcessor_20231109_073634_40.project_0(Lio/trino/spi/connector/ConnectorSession;Lio/trino/spi/connector/RecordCursor;Lio/trino/spi/block/BlockBuilder;)V @115: invokedynamic
  Reason:
    Type 'io/airlift/slice/Slice' (current frame, stack[2]) is not assignable to 'io/trino/type/JoniRegexp'
  Current Frame:
    bci: @115
    flags: { }
    locals: { 'io/trino/$gen/CursorProcessor_20231109_073634_40', 'io/trino/spi/connector/ConnectorSession', 'io/trino/spi/connector/RecordCursor', 'io/trino/spi/block/BlockBuilder', integer }
    stack: { 'io/trino/spi/block/BlockBuilder', 'io/airlift/slice/Slice', 'io/airlift/slice/Slice', 'io/airlift/slice/Slice' }
  Bytecode:
    0000000: 0336 042d 2b2c 03b9 0044 0200 9900 0a04
    0000010: 3604 01a7 000d 2c03 b900 4802 00c0 004a
    0000020: 1504 9900 0957 5701 a700 20ba 0057 0000
    0000030: 1504 9900 0a57 5757 01a7 000f ba00 5d00
    0000040: 0059 c700 0604 3604 1504 9900 0857 01a7
    0000050: 0029 ba00 6200 0015 0499 0009 5757 01a7
    0000060: 0019 ba00 6700 0015 0499 000a 5757 5701
    0000070: a700 08ba 006d 0000 1504 9900 0d57 b900
    0000080: 7301 0057 a700 153a 053a 06ba 0079 0000
    0000090: 1906 1905 b900 7f03 00b1               
  Stackmap Table:
    full_frame(@22,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#64]})
    full_frame(@32,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#64],Object[#74]})
    full_frame(@43,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#64],Object[#74]})
    full_frame(@60,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#64],Object[#74],Object[#134]})
    full_frame(@72,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134]})
    full_frame(@82,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134]})
    full_frame(@98,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134],Object[#134]})
    full_frame(@115,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134],Object[#134],Object[#134]})
    full_frame(@120,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134]})
    full_frame(@135,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134]})
    same_frame(@153)

	at io.airlift.bytecode.ClassGenerator.defineClasses(ClassGenerator.java:112)
	at io.airlift.bytecode.ClassGenerator.defineClass(ClassGenerator.java:90)
	at io.trino.util.CompilerUtils.defineClass(CompilerUtils.java:81)
	at io.trino.util.CompilerUtils.defineClass(CompilerUtils.java:75)
	at io.trino.sql.gen.ExpressionCompiler.compileProcessor(ExpressionCompiler.java:170)
	at io.trino.sql.gen.ExpressionCompiler.compile(ExpressionCompiler.java:141)
	at io.trino.sql.gen.ExpressionCompiler.lambda$new$0(ExpressionCompiler.java:70)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080)
	... 88 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/trino/$gen/CursorProcessor_20231109_073634_40.project_0(Lio/trino/spi/connector/ConnectorSession;Lio/trino/spi/connector/RecordCursor;Lio/trino/spi/block/BlockBuilder;)V @115: invokedynamic
  Reason:
    Type 'io/airlift/slice/Slice' (current frame, stack[2]) is not assignable to 'io/trino/type/JoniRegexp'
  Current Frame:
    bci: @115
    flags: { }
    locals: { 'io/trino/$gen/CursorProcessor_20231109_073634_40', 'io/trino/spi/connector/ConnectorSession', 'io/trino/spi/connector/RecordCursor', 'io/trino/spi/block/BlockBuilder', integer }
    stack: { 'io/trino/spi/block/BlockBuilder', 'io/airlift/slice/Slice', 'io/airlift/slice/Slice', 'io/airlift/slice/Slice' }
  Bytecode:
    0000000: 0336 042d 2b2c 03b9 0044 0200 9900 0a04
    0000010: 3604 01a7 000d 2c03 b900 4802 00c0 004a
    0000020: 1504 9900 0957 5701 a700 20ba 0057 0000
    0000030: 1504 9900 0a57 5757 01a7 000f ba00 5d00
    0000040: 0059 c700 0604 3604 1504 9900 0857 01a7
    0000050: 0029 ba00 6200 0015 0499 0009 5757 01a7
    0000060: 0019 ba00 6700 0015 0499 000a 5757 5701
    0000070: a700 08ba 006d 0000 1504 9900 0d57 b900
    0000080: 7301 0057 a700 153a 053a 06ba 0079 0000
    0000090: 1906 1905 b900 7f03 00b1               
  Stackmap Table:
    full_frame(@22,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#64]})
    full_frame(@32,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#64],Object[#74]})
    full_frame(@43,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#64],Object[#74]})
    full_frame(@60,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#64],Object[#74],Object[#134]})
    full_frame(@72,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134]})
    full_frame(@82,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134]})
    full_frame(@98,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134],Object[#134]})
    full_frame(@115,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134],Object[#134],Object[#134]})
    full_frame(@120,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134]})
    full_frame(@135,{Object[#2],Object[#64],Object[#23],Object[#111],Integer},{Object[#111],Object[#134]})
    same_frame(@153)

	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at com.google.common.reflect.Reflection.initialize(Reflection.java:64)
	at io.airlift.bytecode.ClassGenerator.defineClasses(ClassGenerator.java:108)
	... 99 more
```

**Comment by takezoe** [comment]
This might have been solved by https://github.com/trinodb/trino/pull/20226.

**Comment by hashhar** [comment]
indeed this works since 438.
