### ISSUE TITLE
Trino Formatting Issue with Negation in SQL Queries

### ISSUE THREAD

**Issue by ngina** [trinodb/trino#19695]
I am reaching out because I've encountered an issue with Trino's SQL query formatting when using negation operators. Specifically, it seems that Trino is adding extra parentheses in certain cases, resulting in failures when parsing the SQL query.

```
io.trino.spi.TrinoException: Query does not round-trip
	at io.trino.sql.SqlFormatterUtil.formattingFailure
	at io.trino.sql.SqlFormatterUtil.getFormattedSql
```

I've reviewed the syntax of the query, and is appears to be correct. However, during the formatting process, I notice that additional parentheses are introduced around negated expressions, leading to unexpected results. The same query successfully runs in Presto.

I wanted to check if any community members have experienced similar behavior and if there are known workarounds or solutions to address this formatting issue. I am currently using Trino version 417, and I've checked the documentation, but I couldn't find specific information related to this problem.

If you have any insights, tips, or workarounds that could help resolve or mitigate this issue, I would greatly appreciate your assistance. Additionally, if there are any plans to address this in future releases, please let me know.

**Comment by martint** [comment]
Can you provide an example of a query that shows the problem you're describing?

**Comment by ricardopereira33** [comment]
Hey @martint @findepi !

We are facing the same issue. An example of a query that fails:

```sql
CREATE VIEW sandbox.test_view_negation_sql AS
    WITH config AS (
        SELECT date('2025-08-20') as test_date
    )
    SELECT - (SELECT test_date FROM config)
```

Running Trino 476 version. Error trace:

```
io.trino.spi.TrinoException: Query does not round-trip
	at io.trino.sql.SqlFormatterUtil.formattingFailure(SqlFormatterUtil.java:50)
	at io.trino.sql.SqlFormatterUtil.getFormattedSql(SqlFormatterUtil.java:42)
	at io.trino.execution.CreateViewTask.execute(CreateViewTask.java:110)
	at io.trino.execution.CreateViewTask.execute(CreateViewTask.java:53)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:152)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:272)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:150)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$1(LocalDispatchQuery.java:134)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:570)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:545)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at io.trino.$gen.Trino_476____20250813_101818_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.base/java.lang.Thread.run(Thread.java:1447)
	Suppressed: java.lang.RuntimeException: Statement: Query{with=With{recursive=false, queries=[WithQuery{name=config, query=Query{queryBody=QuerySpecification{select=Select{distinct=false, selectItems=[date('2025-08-20') test_date]}}}, columnNames=Optional.empty}]}, queryBody=QuerySpecification{select=Select{distinct=false, selectItems=[-((SELECT test_date
FROM
  config
))]}}}
		at io.trino.sql.SqlFormatterUtil.formattingFailure(SqlFormatterUtil.java:51)
		... 14 more
	Suppressed: java.lang.RuntimeException: Formatted: [WITH
  config AS (
   SELECT date('2025-08-20') test_date

) 
SELECT -((SELECT test_date
FROM
  config
))

]
		at io.trino.sql.SqlFormatterUtil.formattingFailure(SqlFormatterUtil.java:52)
		... 14 more
```

**Comment by JohnFitzpatrick44** [comment]
Hello, mind if I take this on?
