### ISSUE TITLE
Class org.apache.hadoop.net.StandardSocketFactory not found when reading Iceberg table with delete files

### ISSUE THREAD

**Issue by yohengyang** [trinodb/trino#19716]
trino version: 432

java.lang.RuntimeException: Socket Factory class not found: java.lang.ClassNotFoundException: Class org.apache.hadoop.net.StandardSocketFactory not found

Stack Trace
```
org.apache.hadoop.net.NetUtils.getSocketFactoryFromProperty()
        at org.apache.hadoop.net.NetUtils.getDefaultSocketFactory(NetUtils.java:128)
        at org.apache.hadoop.net.NetUtils.getSocketFactory(NetUtils.java:106)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:327)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:308)
        at org.apache.hadoop.hdfs.DistributedFileSystem.initDFSClient(DistributedFileSystem.java:202)
        at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:187)
        at io.trino.hdfs.TrinoFileSystemCache.createFileSystem(TrinoFileSystemCache.java:160)
        at io.trino.hdfs.TrinoFileSystemCache$FileSystemHolder.createFileSystemOnce(TrinoFileSystemCache.java:298)
        at io.trino.hdfs.TrinoFileSystemCache.getInternal(TrinoFileSystemCache.java:140)
        at io.trino.hdfs.TrinoFileSystemCache.get(TrinoFileSystemCache.java:91)
        at org.apache.hadoop.fs.ForwardingFileSystemCache.get(ForwardingFileSystemCache.java:39)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:557)
        at com.iqiyi.bigdata.qbfs.proxy.AbstractFsProxy$1.run(AbstractFsProxy.java:58)
        at com.iqiyi.bigdata.qbfs.proxy.AbstractFsProxy$1.run(AbstractFsProxy.java:55)
        at java.security.AccessController.doPrivileged(AccessController.java:712)
        at javax.security.auth.Subject.doAs(Subject.java:439)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)
        at com.iqiyi.bigdata.qbfs.proxy.AbstractFsProxy.getFileSystem(AbstractFsProxy.java:55)
        at com.iqiyi.bigdata.qbfs.proxy.AbstractFsProxy.invokeMethod(AbstractFsProxy.java:28)
        at com.iqiyi.bigdata.qbfs.proxy.DefaultFsProxy.invoke(DefaultFsProxy.java:23)
        at com.iqiyi.bigdata.qbfs.proxy.FsProxy.invokeSingle(FsProxy.java:13)
        at com.iqiyi.bigdata.qbfs.AbstractQBFSFileSystem.open(AbstractQBFSFileSystem.java:62)
        at com.iqiyi.bigdata.qbfs.QBFS.open(QBFS.java:171)
        at io.trino.hdfs.TrinoFileSystemCache$FileSystemWrapper.open(TrinoFileSystemCache.java:346)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:1004)
        at io.trino.filesystem.hdfs.HdfsInputFile.lambda$openFile$1(HdfsInputFile.java:119)
        at io.trino.hdfs.authentication.UserGroupInformationUtils.lambda$executeActionInDoAs$0(UserGroupInformationUtils.java:29)
        at java.security.AccessController.doPrivileged(AccessController.java:399)
        at javax.security.auth.Subject.doAs(Subject.java:376)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1876)
        at io.trino.hdfs.authentication.UserGroupInformationUtils.executeActionInDoAs(UserGroupInformationUtils.java:27)
        at io.trino.hdfs.authentication.ImpersonatingHdfsAuthentication.doAs(ImpersonatingHdfsAuthentication.java:41)
        at io.trino.hdfs.HdfsEnvironment.doAs(HdfsEnvironment.java:130)
        at io.trino.filesystem.hdfs.HdfsInputFile.openFile(HdfsInputFile.java:117)
        at io.trino.filesystem.hdfs.HdfsInputFile.newInput(HdfsInputFile.java:65)
        at io.trino.filesystem.tracing.TracingInputFile.lambda$newInput$0(TracingInputFile.java:53)
        at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
        at io.trino.filesystem.tracing.TracingInputFile.newInput(TracingInputFile.java:53)  
        at io.trino.plugin.hive.parquet.MemoryParquetDataSource.<init>(MemoryParquetDataSource.java:54)
        at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createDataSource(ParquetPageSourceFactory.java:346)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.createParquetPageSource(IcebergPageSourceProvider.java:1000)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.createDataPageSource(IcebergPageSourceProvider.java:577)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.openDeletes(IcebergPageSourceProvider.java:520)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.readDeletes(IcebergPageSourceProvider.java:490)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.lambda$createPageSource$9(IcebergPageSourceProvider.java:392)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
        at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:125)
        at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:266)
        at io.trino.operator.Driver.processInternal(Driver.java:395)
        at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
        at io.trino.operator.Driver.tryWithLock(Driver.java:694)
        at io.trino.operator.Driver.process(Driver.java:290)
        at io.trino.operator.Driver.processForDuration(Driver.java:261)
        at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
        at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
        at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
        at io.trino.$gen.Trino_364_qiyi_1_9709_g6b00167_dirty____20231113_061944_2.run(null:-1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)
```

**Comment by electrum** [comment]
Based on the stack trace, it looks like you've modified your Trino installation?

**Comment by electrum** [comment]
Can you try with Trino 434? We made some significant changes to how HDFS is loaded in that version, which might resolve your issue.

**Comment by yohengyang** [comment]
> 434

The problem has been resolved after upgrading to version 434. Thanks so much.

**Comment by hashhar** [comment]
Closing since confirmed as resolved after version 434.
