### ISSUE TITLE
Flaky test TestRubixCaching 

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#19715]
https://github.com/trinodb/trino/actions/runs/6843654475/job/18606542842

```
Error:  Tests run: 32, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 3.408 s <<< FAILURE! -- in TestSuite
Error:  io.trino.hdfs.rubix.TestRubixCaching.closeRubix -- Time elapsed: 0.078 s <<< FAILURE!
java.nio.file.FileSystemException: /tmp/TestRubixCaching8412445585394459368: failed to delete one or more files; see suppressed exceptions for details
	at com.google.common.io.MoreFiles.throwDeleteFailed(MoreFiles.java:803)
	at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:554)
	at io.trino.hdfs.rubix.TestRubixCaching.lambda$closeRubix$3(TestRubixCaching.java:243)
	at com.google.common.io.Closer.close(Closer.java:218)
	at io.trino.hdfs.rubix.TestRubixCaching.closeRubix(TestRubixCaching.java:269)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:[851](https://github.com/trinodb/trino/actions/runs/6843654475/job/18606542842#step:5:852))
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	Suppressed: java.nio.file.DirectoryNotEmptyException
		at java.base/sun.nio.fs.UnixSecureDirectoryStream.implDelete(UnixSecureDirectoryStream.java:207)
		at java.base/sun.nio.fs.UnixSecureDirectoryStream.deleteDirectory(UnixSecureDirectoryStream.java:224)
		at java.base/sun.nio.fs.UnixSecureDirectoryStream.deleteDirectory(UnixSecureDirectoryStream.java:42)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:630)
		at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:531)
		... 16 more
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/7007541110/job/19063114068?pr=19905

```
Error:  Tests run: 17, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.294 s <<< FAILURE! -- in io.trino.hdfs.s3.TestS3SecurityMappingsParser
Error:  io.trino.hdfs.rubix.TestRubixCaching.testCacheWrite -- Time elapsed: 0.623 s <<< ERROR!
java.nio.file.FileSystemException: /tmp/TestRubixCaching1767696123925875094: failed to delete one or more files; see suppressed exceptions for details
	at com.google.common.io.MoreFiles.throwDeleteFailed(MoreFiles.java:803)
	at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:554)
	at io.trino.hdfs.rubix.TestRubixCaching.lambda$closeRubix$3(TestRubixCaching.java:246)
	at com.google.common.io.Closer.close(Closer.java:218)
	at io.trino.hdfs.rubix.TestRubixCaching.closeRubix(TestRubixCaching.java:272)
	at io.trino.hdfs.rubix.TestRubixCaching.testCacheWrite(TestRubixCaching.java:405)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:[387](https://github.com/trinodb/trino/actions/runs/7007541110/job/19063114068?pr=19905#step:5:388))
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: java.nio.file.DirectoryNotEmptyException
		at java.base/sun.nio.fs.UnixSecureDirectoryStream.implDelete(UnixSecureDirectoryStream.java:207)
		at java.base/sun.nio.fs.UnixSecureDirectoryStream.deleteDirectory(UnixSecureDirectoryStream.java:224)
		at java.base/sun.nio.fs.UnixSecureDirectoryStream.deleteDirectory(UnixSecureDirectoryStream.java:42)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:630)
		at com.google.common.io.MoreFiles.deleteDirectoryContentsSecure(MoreFiles.java:652)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:624)
		at com.google.common.io.MoreFiles.deleteDirectoryContentsSecure(MoreFiles.java:652)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:624)
		at com.google.common.io.MoreFiles.deleteDirectoryContentsSecure(MoreFiles.java:652)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:624)
		at com.google.common.io.MoreFiles.deleteDirectoryContentsSecure(MoreFiles.java:652)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:624)
		at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:531)
		... 11 more
```
