### ISSUE TITLE
Flaky TestIcebergMinioOrcConnectorTest.testReadMetadataWithRelationsConcurrentModifications

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#19747]
https://github.com/trinodb/trino/actions/runs/6873067772/job/18692583921?pr=19727

```
Error:  Tests run: 430, Failures: 0, Errors: 1, Skipped: 8, Time elapsed: 634.1 s <<< FAILURE! -- in io.trino.plugin.iceberg.TestIcebergMinioOrcConnectorTest
Error:  io.trino.plugin.iceberg.TestIcebergMinioOrcConnectorTest.testReadMetadataWithRelationsConcurrentModifications -- Time elapsed: 150.5 s <<< ERROR!
com.google.common.base.VerifyException: Task did not completed before timeout; completed tasks: 0, current poll timeout: 150 s
	at com.google.common.base.Verify.verifyNotNull(Verify.java:503)
	at io.trino.testing.BaseConnectorTest.testReadMetadataWithRelationsConcurrentModifications(BaseConnectorTest.java:2051)
	at io.trino.testing.BaseConnectorTest.testReadMetadataWithRelationsConcurrentModifications(BaseConnectorTest.java:1990)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.AssertTimeoutPreemptively.lambda$submitTask$3(AssertTimeoutPreemptively.java:95)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/6936585131/job/18869161533

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/6946778695/job/18899433695

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/6959734449/job/18937997729?pr=19863

```
Error:  io.trino.plugin.iceberg.TestIcebergMinioOrcConnectorTest.testReadMetadataWithRelationsConcurrentModifications -- Time elapsed: 150.5 s <<< ERROR!
com.google.common.base.VerifyException: Task did not completed before timeout; completed tasks: 0, current poll timeout: 150 s
	at com.google.common.base.Verify.verifyNotNull(Verify.java:503)
	at io.trino.testing.BaseConnectorTest.testReadMetadataWithRelationsConcurrentModifications(BaseConnectorTest.java:2047)
	at io.trino.testing.BaseConnectorTest.testReadMetadataWithRelationsConcurrentModifications(BaseConnectorTest.java:1986)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.AssertTimeoutPreemptively.lambda$submitTask$3(AssertTimeoutPreemptively.java:95)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
