### ISSUE TITLE
OrcInputStream#seekToCheckpoint may have a critical bug

### ISSUE THREAD

**Issue by zhangminglei** [trinodb/trino#19775]
An online query failed with the following error when reading an ORC file.

```
Caused by: java.lang.IndexOutOfBoundsException: index (-16) must not be negative
	at io.airlift.slice.Preconditions.checkPositionIndex(Preconditions.java:59)
	at io.airlift.slice.Preconditions.checkPositionIndex(Preconditions.java:52)
	at io.airlift.slice.BasicSliceInput.setPosition(BasicSliceInput.java:59)
	at io.trino.orc.stream.OrcInputStream.seekToCheckpoint(OrcInputStream.java:169)
	at io.trino.orc.stream.LongInputStreamV2.seekToCheckpoint(LongInputStreamV2.java:423)
	at io.trino.orc.stream.LongInputStreamV2.seekToCheckpoint(LongInputStreamV2.java:29)
	at io.trino.orc.stream.CheckpointInputStreamSource.openStream(CheckpointInputStreamSource.java:57)
	at io.trino.orc.reader.SliceDictionaryColumnReader.openRowGroup(SliceDictionaryColumnReader.java:268)
	at io.trino.orc.reader.SliceDictionaryColumnReader.readBlock(SliceDictionaryColumnReader.java:119)
	at io.trino.orc.reader.SliceColumnReader.readBlock(SliceColumnReader.java:75)
	at io.trino.orc.OrcBlockFactory$OrcBlockLoader.load(OrcBlockFactory.java:76)
	... 21 more

```

I took a quick look at the erroring code and it seems that the position value must be non-negative to seek to a new checkpoint within the buffer. However, I'm not sure why the `decompressedOffset` value would be less than the `currentDecompressedBufferOffset` value. Do we expect the value of the checkpoint after `decodeDecompressedOffset` to be monotonically increasing? It doesn't seem so.

```
    public void seekToCheckpoint(long checkpoint)
            throws IOException
    {
        int compressedOffset = decodeCompressedBlockOffset(checkpoint);
        int decompressedOffset = decodeDecompressedOffset(checkpoint);
        // if checkpoint is within the current buffer, seek locally
        int currentDecompressedBufferOffset = decodeDecompressedOffset(lastCheckpoint);
        if (current != null && compressedOffset == decodeCompressedBlockOffset(lastCheckpoint) && decompressedOffset < currentDecompressedBufferOffset + current.length()) {
            current.setPosition(decompressedOffset - currentDecompressedBufferOffset);
            return;
        }
        // otherwise, drop the current buffer and seek the underlying data loader
        current = EMPTY_SLICE.getInput();
        chunkLoader.seekToCheckpoint(checkpoint);
        lastCheckpoint = checkpoint;
    }
```

**Comment by zhangminglei** [comment]
@dain Could you please take a look at this issue ?

**Comment by lirui-apache** [comment]
Is this the same issue as #19934?
