### ISSUE TITLE
Flaky test TestRaptorIntegrationSmokeTestBucketed.testCreateBucketedTable and TestRaptorMetadata.testCreateBucketedTable 

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#1977]
```
[ERROR] Tests run: 1150, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,405.751 s <<< FAILURE! - in TestSuite
[ERROR] testCreateBucketedTable(io.prestosql.plugin.raptor.legacy.TestRaptorIntegrationSmokeTestBucketed)  Time elapsed: 5.264 s  <<< FAILURE!
java.lang.AssertionError: 
For query: 
 SELECT count(DISTINCT "$shard_uuid") FROM orders_bucketed
not equal
Actual rows (up to 100 of 1 extra rows shown, 1 rows in total):
    [87]
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
    [100]

	at org.testng.Assert.fail(Assert.java:94)
	at io.prestosql.tests.QueryAssertions.assertEqualsIgnoreOrder(QueryAssertions.java:237)
	at io.prestosql.tests.QueryAssertions.assertQuery(QueryAssertions.java:203)
	at io.prestosql.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at io.prestosql.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:137)
	at io.prestosql.plugin.raptor.legacy.TestRaptorIntegrationSmokeTest.testCreateBucketedTable(TestRaptorIntegrationSmokeTest.java:451)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by findepi** [comment]
Same for `TestRaptorIntegrationSmokeTestMySql.testCreateBucketedTable` - https://github.com/prestosql/presto/pull/2991/checks?check_run_id=483588543

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/3001/checks?check_run_id=485676509

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/519051893

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/641930179

**Comment by electrum** [comment]
I think we can fix this by disabling compaction for the tests.

**Comment by findepi** [comment]
Does the compaction affect the data being visible in the table?
Or is it just that the table in test is compacted, so it has fewer data pieces?

If the latter, is it possible to disable or delay compaction for a selected table only?

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/674974548

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/772557446

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/830949736

**Comment by findepi** [comment]
> I think we can fix this by disabling compaction for the tests.

@electrum would you mind?

**Comment by electrum** [comment]
Yes, this should be an easy fix.

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/835611515

**Comment by sopel39** [comment]
https://github.com/prestosql/presto/pull/5203/checks?check_run_id=1129303312

**Comment by findepi** [comment]
https://github.com/findepi/presto/runs/1206332230?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1279830864

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1476878852

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/6899665933/job/18771648846
