### ISSUE TITLE
Failed to read Parquet file when file is compressed using snappy

### ISSUE THREAD

**Issue by cksac** [trinodb/trino#19788]
got Failed to read Parquet file when query table with following exception:

```java
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:555)
	at io.trino.$gen.Trino_____20230925_043702_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.airlift.compress.MalformedInputException: Malformed input: offset=4454
	at io.airlift.compress.snappy.SnappyRawDecompressor.uncompressAll(SnappyRawDecompressor.java:153)
	at io.airlift.compress.snappy.SnappyRawDecompressor.decompress(SnappyRawDecompressor.java:53)
	at io.airlift.compress.snappy.SnappyDecompressor.decompress(SnappyDecompressor.java:50)
	at io.trino.parquet.ParquetCompressionUtils.decompress(ParquetCompressionUtils.java:150)
	at io.trino.parquet.ParquetCompressionUtils.decompressSnappy(ParquetCompressionUtils.java:78)
	at io.trino.parquet.ParquetCompressionUtils.decompress(ParquetCompressionUtils.java:56)
	at io.trino.parquet.reader.PageReader.readPage(PageReader.java:109)
	at io.trino.parquet.reader.flat.FlatColumnReader.readPage(FlatColumnReader.java:257)
	at io.trino.parquet.reader.flat.FlatColumnReader.readNextPage(FlatColumnReader.java:232)
	at io.trino.parquet.reader.flat.FlatColumnReader.readNonNull(FlatColumnReader.java:178)
	at io.trino.parquet.reader.flat.FlatColumnReader.readPrimitive(FlatColumnReader.java:90)
	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:439)
	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:524)
	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:507)
	at io.trino.parquet.reader.ParquetReader.lambda$nextPage$3(ParquetReader.java:272)
	at io.trino.parquet.reader.ParquetBlockFactory$ParquetBlockLoader.load(ParquetBlockFactory.java:72)
	... 41 more
```
possible cause:
https://github.com/airlift/aircompressor/issues/148

**Comment by raunaqmorarka** [comment]
How was this file created ? Can you provide steps to reproduce or share the relevant file ?
Is this file successfully read by parquet tools or other engines like Hive and Spark ?
cc: @martint

**Comment by raunaqmorarka** [comment]
Please re-open when you're able to provide the above info
