### ISSUE TITLE
TestEvictableCache.testLoadFailure is flaky

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#19882]
```Error:  Tests run: 50, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.452 s <<< FAILURE! -- in io.trino.cache.TestEvictableCache
Error:  io.trino.cache.TestEvictableCache.testLoadFailure -- Time elapsed: 0.035 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting actual:
  ["com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: first attempt is poised to fail",
    "success"]
to contain exactly (and in same order):
  ["com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: first attempt is poised to fail",
    "com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: first attempt is poised to fail"]
but some elements were not found:
  ["com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: first attempt is poised to fail"]
and others were not expected:
  ["success"]

	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.trino.cache.TestEvictableCache.testLoadFailure(TestEvictableCache.java:333)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.468 s -- in io.trino.cache.TestEvictableLoadingCache
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:  io.trino.cache.TestEvictableCache.testLoadFailure
[INFO]   Run 1: PASS
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
[INFO]   Run 4: PASS
Error:    Run 5: TestEvictableCache.testLoadFailure:333 
Expecting actual:
  ["com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: first attempt is poised to fail",
    "success"]
to contain exactly (and in same order):
  ["com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: first attempt is poised to fail",
    "com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: first attempt is poised to fail"]
but some elements were not found:
  ["com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: first attempt is poised to fail"]
and others were not expected:
  ["success"]

[INFO]   Run 6: PASS
[INFO]   Run 7: PASS
[INFO]   Run 8: PASS
[INFO]   Run 9: PASS
[INFO]   Run 10: PASS
[INFO] 
```

**Comment by losipiuk** [comment]
cc: @findepi

**Comment by findepi** [comment]
How can the test be flaky if it doesn't run on CI?
https://github.com/trinodb/trino/pull/19894

**Comment by findepi** [comment]
Don't know/remember what the code author had in mind, but this looks suspicious

https://github.com/trinodb/trino/blob/6c369ef5ae687ffc8dcdaae6ff47107045c6fe1f/lib/trino-cache/src/test/java/io/trino/cache/TestEvictableCache.java#L313

commenting the sleep out makes the test very flaky (~50%) locally, so it looks the test relies on sleep(1) for synchronization
