### ISSUE TITLE
Flaky test TestS3FileSystemAwsS3.testInputFile: SocketException: Connection reset

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#19888]
https://github.com/trinodb/trino/actions/runs/6979361767/job/18992641468?pr=19863

```
Error:  Tests run: 18, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 43.85 s <<< FAILURE! -- in io.trino.filesystem.s3.TestS3FileSystemAwsS3
Error:  io.trino.filesystem.s3.TestS3FileSystemAwsS3.testInputFile -- Time elapsed: 7.531 s <<< ERROR!
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:243)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1509)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1480)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:119)
	at software.amazon.awssdk.services.s3.checksums.ChecksumValidatingInputStream.read(ChecksumValidatingInputStream.java:112)
	at java.base/java.io.InputStream.skip(InputStream.java:551)
	at java.base/java.io.FilterInputStream.skip(FilterInputStream.java:138)
	at software.amazon.awssdk.core.io.SdkFilterInputStream.skip(SdkFilterInputStream.java:72)
	at io.trino.filesystem.s3.S3InputStream.doSkip(S3InputStream.java:239)
	at io.trino.filesystem.s3.S3InputStream.skip(S3InputStream.java:126)
	at io.trino.filesystem.AbstractTestTrinoFileSystem.testInputFile(AbstractTestTrinoFileSystem.java:303)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:1[94](https://github.com/trinodb/trino/actions/runs/6979361767/job/18992641468?pr=19863#step:8:95))
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by findepi** [comment]
Can we safely assume this is just a test problem, or is it also a production problem?
