### ISSUE TITLE
Fail to initialize TestDeltaLakeGcsConnectorSmokeTest & TestIcebergGcsConnectorSmokeTest when disabled native GCS

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#19924]
```
java.lang.NoClassDefFoundError: Could not initialize class com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.OpenCensusUtils
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpRequest.<init>(HttpRequest.java:203)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpTransport.buildRequest(HttpTransport.java:115)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:86)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:415)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:525)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:466)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:576)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getObject(GoogleCloudStorageImpl.java:2142)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfo(GoogleCloudStorageImpl.java:2046)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.listFileInfo(GoogleCloudStorageFileSystem.java:1037)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.listStatus(GoogleHadoopFileSystemBase.java:928)
	at org.apache.hadoop.fs.FilterFileSystem.listStatus(FilterFileSystem.java:274)
	at io.trino.filesystem.hdfs.HdfsFileSystem.hierarchical(HdfsFileSystem.java:447)
	at io.trino.filesystem.hdfs.HdfsFileSystem.lambda$directoryExists$6(HdfsFileSystem.java:263)
	at io.trino.hdfs.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.hdfs.HdfsEnvironment.doAs(HdfsEnvironment.java:134)
	at io.trino.filesystem.hdfs.HdfsFileSystem.directoryExists(HdfsFileSystem.java:261)
	at io.trino.filesystem.manager.SwitchingFileSystem.directoryExists(SwitchingFileSystem.java:117)
	at io.trino.filesystem.tracing.TracingFileSystem.lambda$directoryExists$5(TracingFileSystem.java:119)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
	at io.trino.filesystem.tracing.TracingFileSystem.directoryExists(TracingFileSystem.java:119)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.lambda$createSchema$20(DeltaLakeMetadata.java:816)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.createSchema(DeltaLakeMetadata.java:814)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.createSchema(ClassLoaderSafeConnectorMetadata.java:409)
	at io.trino.tracing.TracingConnectorMetadata.createSchema(TracingConnectorMetadata.java:348)
	at io.trino.metadata.MetadataManager.createSchema(MetadataManager.java:771)
	at io.trino.tracing.TracingMetadata.createSchema(TracingMetadata.java:370)
	at io.trino.execution.CreateSchemaTask.internalExecute(CreateSchemaTask.java:128)
	at io.trino.execution.CreateSchemaTask.execute(CreateSchemaTask.java:82)
	at io.trino.execution.CreateSchemaTask.execute(CreateSchemaTask.java:54)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:256)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at io.trino.$gen.Trino_testversion____20231127_222635_1336.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
https://github.com/trinodb/trino/actions/runs/7011304869/job/19073726685

**Comment by ebyhr** [comment]
The different error message pattern:
```
java.util.ServiceConfigurationError: Provider io.opentelemetry.opencensusshim.OpenTelemetryTraceComponentImpl could not be instantiated.
	at com.google.cloud.hadoop.repackaged.gcs.io.opencensus.internal.Provider.createInstance(Provider.java:46)
	at com.google.cloud.hadoop.repackaged.gcs.io.opencensus.trace.Tracing.loadTraceComponent(Tracing.java:95)
	at com.google.cloud.hadoop.repackaged.gcs.io.opencensus.trace.Tracing.<clinit>(Tracing.java:38)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.OpenCensusUtils.<clinit>(OpenCensusUtils.java:56)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpRequest.<init>(HttpRequest.java:203)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpTransport.buildRequest(HttpTransport.java:115)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:86)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:415)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:525)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:466)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:576)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getObject(GoogleCloudStorageImpl.java:2142)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfo(GoogleCloudStorageImpl.java:2046)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.listFileInfo(GoogleCloudStorageFileSystem.java:1037)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.listStatus(GoogleHadoopFileSystemBase.java:928)
	at org.apache.hadoop.fs.FilterFileSystem.listStatus(FilterFileSystem.java:274)
	at io.trino.filesystem.hdfs.HdfsFileSystem.hierarchical(HdfsFileSystem.java:447)
	at io.trino.filesystem.hdfs.HdfsFileSystem.lambda$directoryExists$6(HdfsFileSystem.java:263)
	at io.trino.hdfs.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.hdfs.HdfsEnvironment.doAs(HdfsEnvironment.java:134)
	at io.trino.filesystem.hdfs.HdfsFileSystem.directoryExists(HdfsFileSystem.java:261)
	at io.trino.filesystem.manager.SwitchingFileSystem.directoryExists(SwitchingFileSystem.java:117)
	at io.trino.filesystem.tracing.TracingFileSystem.lambda$directoryExists$5(TracingFileSystem.java:119)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
	at io.trino.filesystem.tracing.TracingFileSystem.directoryExists(TracingFileSystem.java:119)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.lambda$createSchema$20(DeltaLakeMetadata.java:816)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.createSchema(DeltaLakeMetadata.java:814)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.createSchema(ClassLoaderSafeConnectorMetadata.java:409)
	at io.trino.tracing.TracingConnectorMetadata.createSchema(TracingConnectorMetadata.java:348)
	at io.trino.metadata.MetadataManager.createSchema(MetadataManager.java:771)
	at io.trino.tracing.TracingMetadata.createSchema(TracingMetadata.java:370)
	at io.trino.execution.CreateSchemaTask.internalExecute(CreateSchemaTask.java:128)
	at io.trino.execution.CreateSchemaTask.execute(CreateSchemaTask.java:82)
	at io.trino.execution.CreateSchemaTask.execute(CreateSchemaTask.java:54)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:256)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at io.trino.$gen.Trino_testversion____20231127_210650_1324.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassCastException: class io.opentelemetry.opencensusshim.OpenTelemetryTraceComponentImpl
	at java.base/java.lang.Class.asSubclass(Class.java:4102)
	at com.google.cloud.hadoop.repackaged.gcs.io.opencensus.internal.Provider.createInstance(Provider.java:43)
	... 45 more
```
https://github.com/trinodb/trino/actions/runs/7010135638/job/19071175581

**Comment by ebyhr** [comment]
TestIcebergGcsConnectorSmokeTest  https://github.com/trinodb/trino/actions/runs/7008402419/job/19067266337

**Comment by ebyhr** [comment]
Note: I can run the test after removing `io.opentelemetry:opentelemetry-opencensus-shim` from trino-filesystem-gcs.

**Comment by ebyhr** [comment]
The test is green on the latest master, but it still fails without 4a0294c2f149832d90c94b47691e8bedf90817ac

**Comment by findepi** [comment]
Marked as a blocker per https://trinodb.slack.com/archives/CP1MUNEUX/p1701170191840389?thread_ts=1701133569.080639&cid=CP1MUNEUX

**Comment by electrum** [comment]
This is only a problem for units tests, which don't use classloader isolation. It should be fine in production usage or in a product test.
