### ISSUE TITLE
"Error creating Parquet file" when trying to replace iceberg table

### ISSUE THREAD

**Issue by erikcw** [trinodb/trino#20046]
I'm attempting to replace an iceberg table using a CTAS query as described here: https://trino.io/docs/current/connector/iceberg.html#replacing-tables

My goal is to remove some duplicate records from the original table.

```sql
CREATE OR REPLACE TABLE iceberg.ddt.ccid_hem_2022_12_02
AS SELECT d.hem, d.ccid
FROM (
  SELECT
  ROW_NUMBER() OVER (PARTITION BY hem,ccid) AS RN,
        c.hem
      , c.ccid
  FROM iceberg.ddt.ccid_hem_2022_12_02 c) d
WHERE RN < 2
```

Stacktrace:
Error Type	EXTERNAL
Error Code	ICEBERG_WRITER_OPEN_ERROR (84148231)
```
io.trino.spi.TrinoException: Error creating Parquet file
	at io.trino.plugin.iceberg.IcebergFileWriterFactory.createParquetWriter(IcebergFileWriterFactory.java:197)
	at io.trino.plugin.iceberg.IcebergFileWriterFactory.createDataFileWriter(IcebergFileWriterFactory.java:129)
	at io.trino.plugin.iceberg.IcebergPageSink.createWriter(IcebergPageSink.java:408)
	at io.trino.plugin.iceberg.IcebergPageSink.getWriterIndexes(IcebergPageSink.java:365)
	at io.trino.plugin.iceberg.IcebergPageSink.writePage(IcebergPageSink.java:266)
	at io.trino.plugin.iceberg.IcebergPageSink.doAppend(IcebergPageSink.java:260)
	at io.trino.plugin.iceberg.IcebergPageSink.appendPage(IcebergPageSink.java:213)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:68)
	at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:255)
	at io.trino.operator.Driver.processInternal(Driver.java:400)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_434____20231204_230403_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Creation of file hdfs://ip-172-20-30-193.ec2.internal:8020/user/hive/warehouse/ddt.db/ccid_hem_2022_12_02-ea73761a6f5f44cbb2f6c749de26246c/data/20231206_215235_02064_yy6hs-8adcac34-e22c-4210-b499-b3f6b3f50e30.parquet failed: Call From pulumi-trino-coordinator-7df54b8885-698j6/192.168.34.66 to ip-172-20-30-193.ec2.internal:8020 failed on socket timeout exception: org.apache.hadoop.net.ConnectTimeoutException: 500 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=ip-172-20-30-193.ec2.internal/172.20.30.193:8020]; For more details see:  http://wiki.apache.org/hadoop/SocketTimeout
	at io.trino.filesystem.hdfs.HdfsOutputFile.create(HdfsOutputFile.java:106)
	at io.trino.filesystem.hdfs.HdfsOutputFile.create(HdfsOutputFile.java:62)
	at io.trino.filesystem.tracing.TracingOutputFile.lambda$create$3(TracingOutputFile.java:77)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
	at io.trino.filesystem.tracing.TracingOutputFile.create(TracingOutputFile.java:77)
	at io.trino.plugin.hive.parquet.ParquetFileWriter.<init>(ParquetFileWriter.java:84)
	at io.trino.plugin.iceberg.IcebergParquetFileWriter.<init>(IcebergParquetFileWriter.java:75)
	at io.trino.plugin.iceberg.IcebergFileWriterFactory.createParquetWriter(IcebergFileWriterFactory.java:194)
	... 20 more
Caused by: org.apache.hadoop.net.ConnectTimeoutException: Call From pulumi-trino-coordinator-7df54b8885-698j6/192.168.34.66 to ip-172-20-30-193.ec2.internal:8020 failed on socket timeout exception: org.apache.hadoop.net.ConnectTimeoutException: 500 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=ip-172-20-30-193.ec2.internal/172.20.30.193:8020]; For more details see:  http://wiki.apache.org/hadoop/SocketTimeout
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:930)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:865)
	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1588)
	at org.apache.hadoop.ipc.Client.call(Client.java:1530)
	at org.apache.hadoop.ipc.Client.call(Client.java:1427)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:258)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:139)
	at jdk.proxy14/jdk.proxy14.$Proxy607.create(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.create(ClientNamenodeProtocolTranslatorPB.java:383)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:433)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:166)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:158)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:96)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:362)
	at jdk.proxy14/jdk.proxy14.$Proxy608.create(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream.newStreamForCreate(DFSOutputStream.java:280)
	at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1271)
	at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1250)
	at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1232)
	at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1170)
	at org.apache.hadoop.hdfs.DistributedFileSystem$8.doCall(DistributedFileSystem.java:556)
	at org.apache.hadoop.hdfs.DistributedFileSystem$8.doCall(DistributedFileSystem.java:553)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.create(DistributedFileSystem.java:567)
	at org.apache.hadoop.hdfs.DistributedFileSystem.create(DistributedFileSystem.java:494)
	at io.trino.hdfs.TrinoFileSystemCache$FileSystemWrapper.create(TrinoFileSystemCache.java:366)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1240)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1217)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1098)
	at io.trino.filesystem.hdfs.HdfsOutputFile.lambda$create$1(HdfsOutputFile.java:98)
	at io.trino.hdfs.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.hdfs.HdfsEnvironment.doAs(HdfsEnvironment.java:134)
	at io.trino.filesystem.hdfs.HdfsOutputFile.create(HdfsOutputFile.java:113)
	at io.trino.filesystem.hdfs.HdfsOutputFile.create(HdfsOutputFile.java:98)
	... 27 more
Caused by: org.apache.hadoop.net.ConnectTimeoutException: 500 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=ip-172-20-30-193.ec2.internal/172.20.30.193:8020]
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:603)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:668)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:790)
	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:363)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1649)
	at org.apache.hadoop.ipc.Client.call(Client.java:1474)
	... 59 more
```

Trino v434.  The table is back by S3 and using AWS Glue as the Hive Metastore.

**Comment by erikcw** [comment]
Ok, looks like this is may be more of a documentation issue.  If I supply a `location`, then it works:

```sql
CREATE TABLE my_table (
    a BIGINT,
    b DATE,
    c BIGINT)
WITH (location = 's3://bucket/tmp/x_my_table');


insert into my_table values
(1, date  '2023-12-01', 111),
(2, date '2023-12-02', 222);

select * from my_table;


create or replace table ddt.my_table
WITH (location = 's3://bucket/tmp/x_my_table')
as select a, b, c+1 as c from ddt.my_table
union all 
select 3 a, date '2023-12-03' b, 333 c;

select * from my_table;

select * from my_table FOR VERSION AS of 2330540277039541282;

select * from "my_table$snapshots" order by committed_at desc;
```

My iceberg connector is defined as:
```
        connector.name=iceberg
        iceberg.catalog.type=glue
        iceberg.file-format=PARQUET
```

Kind of surprising that it wouldn't automatically pick up the `location` from the "source" table.  Or am I missing something config wise?

**Comment by hashhar** [comment]
cc: @findinpath @mdesmet

**Comment by findinpath** [comment]
I just tried to reproduce the issue posted here while testing against Hive & Glue metastores.
I create a schema with a location, i create a table within this schema, i replace the table - all successful.

```
trino> create schema iceberg.findinpath20231213 with (location='s3://test-bucket/findinpath20231213');
CREATE SCHEMA
trino> create table iceberg.findinpath20231213.t1 (col integer);
CREATE TABLE
trino> insert into iceberg.findinpath20231213.t1 values 1;
INSERT: 1 row

trino> show create table iceberg.findinpath20231213.t1;
                                          Create Table                         >
------------------------------------------------------------------------------->
 CREATE TABLE iceberg.findinpath20231213.t1 (                                  >
    col integer                                                                >
 )                                                                             >
 WITH (                                                                        >
    format = 'PARQUET',                                                        >
    format_version = 2,                                                        >
    location = 's3://test-bucket/findinpath20231213/t1-32e8bd96939b43c39>
 )                                                                             >
(1 row)


trino> create or replace table iceberg.findinpath20231213.t1 as select 2 as col;

CREATE TABLE: 1 row

trino> show create table iceberg.findinpath20231213.t1;
                                          Create Table                         >
------------------------------------------------------------------------------->
 CREATE TABLE iceberg.findinpath20231213.t1 (                                  >
    col integer                                                                >
 )                                                                             >
 WITH (                                                                        >
    format = 'PARQUET',                                                        >
    format_version = 2,                                                        >
    location = 's3://test-bucket/findinpath20231213/t1-9c58fee8b6d54579a>
 )                                                                             >
(1 row)

trino> select * from  iceberg.findinpath20231213.t1;
 col 
-----
   2 
(1 row)
```

**Comment by findinpath** [comment]
Does `iceberg.ddt` have a location?

**Comment by erikcw** [comment]
It does!  However, it is specified on hdfs.  the schema was originally created in AWS Athena for hive style tables.  I wonder if this is (or at some point was) an AWS default.  Anyway, this location aligns with the hdfs location referenced in the original traceback.

```sql

show create schema iceberg.ddt;

 CREATE SCHEMA iceberg.ddt
 WITH (
    location = 'hdfs://ip-172-20-30-193.ec2.internal:8020/user/hive/warehouse/ddt.db'
 )
```

**Comment by findinpath** [comment]
Pls  showcase the output of `SHOW CREATE TABLE` for a newly created table within this schema.

**Comment by findinpath** [comment]
I've tried again

```
trino> create or replace table iceberg.default.t1 (c integer);
CREATE TABLE
trino> show create table iceberg.default.t1;
                                           Create Table                                            
---------------------------------------------------------------------------------------------------
 CREATE TABLE iceberg.default.t1 (                                                                 
    c integer                                                                                      
 )                                                                                                 
 WITH (                                                                                            
    format = 'PARQUET',                                                                            
    format_version = 2,                                                                            
    location = 'hdfs://hadoop-master:9000/user/hive/warehouse/t1-666b92a6ee794f86b2b1ac4ad071fb9c' 
 )                                                                                                 
(1 row)

trino> insert into iceberg.default.t1 values 1;
INSERT: 1 row

trino> create or replace table iceberg.default.t1  as select 2 as c;
CREATE TABLE: 1 row

trino> show create table iceberg.default.t1;
                                           Create Table                                            
---------------------------------------------------------------------------------------------------
 CREATE TABLE iceberg.default.t1 (                                                                 
    c integer                                                                                      
 )                                                                                                 
 WITH (                                                                                            
    format = 'PARQUET',                                                                            
    format_version = 2,                                                                            
    location = 'hdfs://hadoop-master:9000/user/hive/warehouse/t1-9f87c0cec0144862b31ddfb622030fbc' 
 )                                                                                                 
(1 row)
```

As can be seen from the listing above, the `CREATE OR REPLACE AS SELECT` succeeds in creating the table, but it seems to be changing the location of the table. This is definitely a bug.

Initial location: `hdfs://hadoop-master:9000/user/hive/warehouse/t1-666b92a6ee794f86b2b1ac4ad071fb9c`
Current location: `hdfs://hadoop-master:9000/user/hive/warehouse/t1-9f87c0cec0144862b31ddfb622030fbc`
