### ISSUE TITLE
system.sync_partition_metadata() procedure cannot handle special character on partition path properly, not like as before.

### ISSUE THREAD

**Issue by okayhooni** [trinodb/trino#20071]
We recently upgraded our Trino cluster from `v412` to `v433` and noticed that `system.sync_partition_metadata()` procedure cannot handle special character like `#` in partition path properly with AWS Glue metastore, not like as before(`v412`)

ex) `s3://our_bucket/temp/okayhooni_table/part_date=2023-12-01/model_ver=1.0#2023-11-27/example.parquet`

I know, special character in the partition path is not the standard spec. of Hive table, and `#` has to be converted to `%23` to be compatible with official Hive spec.

I found lots of changes on the Trino codebase related to this procedure logic, following https://github.com/trinodb/trino/issues/15921
- https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java
- https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java

Could you fix this issue for supporting backward-compatibility of Trino?

example stack trace 1) [When calling `system.sync_partition_metadata()` with `ADD` option more than 1 time]
```
io.trino.spi.TrinoException: Partition already exists.
	at io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.propagatePartitionErrorToTrinoException(GlueHiveMetastore.java:1080)
	at io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.lambda$addPartitions$39(GlueHiveMetastore.java:1049)
	at io.trino.plugin.hive.aws.AwsApiCallStats.call(AwsApiCallStats.java:36)
	at io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.addPartitions(GlueHiveMetastore.java:1033)
	at io.trino.plugin.hive.metastore.ForwardingHiveMetastore.addPartitions(ForwardingHiveMetastore.java:270)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.addPartitions(CachingHiveMetastore.java:887)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.addPartitions(CachingHiveMetastore.java:887)
	at io.trino.plugin.hive.HiveMetastoreClosure.addPartitions(HiveMetastoreClosure.java:275)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$PartitionAdder.execute(SemiTransactionalHiveMetastore.java:3448)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeAddPartitionOperations(SemiTransactionalHiveMetastore.java:2176)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:1603)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1301)
	at io.trino.plugin.hive.procedure.SyncPartitionMetadataProcedure.syncPartitions(SyncPartitionMetadataProcedure.java:219)
	at io.trino.plugin.hive.procedure.SyncPartitionMetadataProcedure.doSyncPartitionMetadata(SyncPartitionMetadataProcedure.java:148)
	at io.trino.plugin.hive.procedure.SyncPartitionMetadataProcedure.syncPartitionMetadata(SyncPartitionMetadataProcedure.java:108)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:757)
	at io.trino.execution.CallTask.execute(CallTask.java:210)
	at io.trino.execution.CallTask.execute(CallTask.java:70)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:256)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at io.trino.$gen.Trino_0ed1b46____20231207_204712_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

example stack trace 2) [When calling `system.sync_partition_metadata()` with `FULL` option]
```
io.trino.spi.TrinoException: dropping a partition added in the same transaction is not supported: temp okayhooni_table [2023-12-01, 1.0#2023-11-27]
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.dropPartition(SemiTransactionalHiveMetastore.java:1026)
	at io.trino.plugin.hive.procedure.SyncPartitionMetadataProcedure.dropPartitions(SyncPartitionMetadataProcedure.java:248)
	at io.trino.plugin.hive.procedure.SyncPartitionMetadataProcedure.syncPartitions(SyncPartitionMetadataProcedure.java:217)
	at io.trino.plugin.hive.procedure.SyncPartitionMetadataProcedure.doSyncPartitionMetadata(SyncPartitionMetadataProcedure.java:148)
	at io.trino.plugin.hive.procedure.SyncPartitionMetadataProcedure.syncPartitionMetadata(SyncPartitionMetadataProcedure.java:108)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:757)
	at io.trino.execution.CallTask.execute(CallTask.java:210)
	at io.trino.execution.CallTask.execute(CallTask.java:70)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:256)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at io.trino.$gen.Trino_0ed1b46____20231207_204712_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
cc/ @electrum

**Comment by electrum** [comment]
This should be fixed by https://github.com/trinodb/trino/pull/19296
