### ISSUE TITLE
Flaky tests due to insufficient synchronization in FileHiveMetastore

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#20130]
https://github.com/trinodb/trino/actions/runs/7207006810/job/19633156255?pr=20059

Example:

```
Error:  io.trino.plugin.iceberg.TestIcebergConnectorSmokeTest.testRenameTable -- Time elapsed: 0.109 s <<< ERROR!
io.trino.testing.QueryFailedException: Error listing tables for catalog iceberg: com.google.common.util.concurrent.UncheckedExecutionException: io.trino.spi.TrinoException: /tmp/TrinoTest1047714890305165641/iceberg_data/tpch/test_merge_avh7kswykq-868db740a943472abcf7cdebe9406892/data/20231214_095739_00224_u4hjy-f1581e67-d5f2-4918-bff4-053c9df38364.orc
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:531)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:523)
	at io.trino.sql.query.QueryAssertions$QueryAssert.newQueryAssert(QueryAssertions.java:303)
	at io.trino.sql.query.QueryAssertions.query(QueryAssertions.java:125)
	at io.trino.testing.AbstractTestQueryFramework.query(AbstractTestQueryFramework.java:333)
	at io.trino.testing.AbstractTestQueryFramework.query(AbstractTestQueryFramework.java:328)
	at io.trino.testing.BaseConnectorSmokeTest.testRenameTable(BaseConnectorSmokeTest.java:449)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: java.lang.Exception: SQL: SHOW TABLES LIKE 'test_rename_old_tmfb004rs4'
		at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:535)
		... 13 more
Caused by: io.trino.spi.TrinoException: Error listing tables for catalog iceberg: com.google.common.util.concurrent.UncheckedExecutionException: io.trino.spi.TrinoException: /tmp/TrinoTest1047714890305165641/iceberg_data/tpch/test_merge_avh7kswykq-868db740a943472abcf7cdebe9406892/data/20231214_095739_00224_u4hjy-f1581e67-d5f2-4918-bff4-053c9df38364.orc
	at io.trino.metadata.MetadataListing.handleListingException(MetadataListing.java:358)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getTables(CachingHiveMetastore.java:598)
	at io.trino.plugin.iceberg.catalog.hms.TrinoHiveCatalog.listTables(TrinoHiveCatalog.java:363)
	at io.trino.plugin.iceberg.IcebergMetadata.listTables(IcebergMetadata.java:688)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.listTables(ClassLoaderSafeConnectorMetadata.java:294)
	at io.trino.tracing.TracingConnectorMetadata.listTables(TracingConnectorMetadata.java:266)
	at io.trino.metadata.MetadataManager.listTables(MetadataManager.java:533)
	at io.trino.tracing.TracingMetadata.listTables(TracingMetadata.java:316)
	at io.trino.metadata.MetadataListing.doListTables(MetadataListing.java:128)
	at io.trino.metadata.MetadataListing.listTables(MetadataListing.java:119)
	... 41 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: io.trino.spi.TrinoException: /tmp/TrinoTest1047714890305165641/iceberg_data/tpch/test_merge_avh7kswykq-868db740a943472abcf7cdebe9406892/data/20231214_095739_00224_u4hjy-f1581e67-d5f2-4918-bff4-053c9df38364.orc
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2087)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4019)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4042)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5024)
	at io.trino.cache.EvictableCache.get(EvictableCache.java:145)
	at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:53)
	at io.trino.plugin.hive.metastore.file.FileHiveMetastore.listAllTables(FileHiveMetastore.java:585)
	at io.trino.plugin.hive.metastore.file.FileHiveMetastore.getTables(FileHiveMetastore.java:537)
	at io.trino.plugin.hive.metastore.tracing.TracingHiveMetastore.lambda$getTables$8(TracingHiveMetastore.java:179)
	at io.trino.plugin.hive.metastore.tracing.Tracing.withTracing(Tracing.java:39)
	at io.trino.plugin.hive.metastore.tracing.TracingHiveMetastore.getTables(TracingHiveMetastore.java:178)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadAllTables(CachingHiveMetastore.java:603)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:447)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:433)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3576)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2318)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2191)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2081)
	... 56 more
Caused by: io.trino.spi.TrinoException: /tmp/TrinoTest1047714890305165641/iceberg_data/tpch/test_merge_avh7kswykq-868db740a943472abcf7cdebe9406892/data/20231214_095739_00224_u4hjy-f1581e67-d5f2-4918-bff4-053c9df38364.orc
	at io.trino.plugin.hive.metastore.file.FileHiveMetastore.doListAllTables(FileHiveMetastore.java:625)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:447)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:433)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3576)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2318)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2191)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2081)
	... 74 more
Caused by: java.nio.file.NoSuchFileException: /tmp/TrinoTest1047714890305165641/iceberg_data/tpch/test_merge_avh7kswykq-868db740a943472abcf7cdebe9406892/data/20231214_095739_00224_u4hjy-f1581e67-d5f2-4918-bff4-053c9df38364.orc
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1853)
	at java.base/java.nio.file.Files.size(Files.java:2462)
	at io.trino.filesystem.local.LocalFileIterator.next(LocalFileIterator.java:80)
	at io.trino.plugin.hive.metastore.file.FileHiveMetastore.doListAllTables(FileHiveMetastore.java:605)
	... 81 more
```

**Comment by findepi** [comment]
This can be easily reproduced by running `TestIcebergConnectorSmokeTest.testRenameTable` with `@RepeatedTest(100)` and parallelism. 
The failing query seems benign https://github.com/trinodb/trino/blob/99ed3f5dc725a1f80b97bd856713221dd2475c5d/testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java#L461 

The culprit seems to be the line https://github.com/trinodb/trino/blob/11a024fd08b23725eee8090fa20e3665c7de21d5/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java#L603
which lists files recursively (perhaps since https://github.com/trinodb/trino/commit/a33044eb7e7e2cac51df76248ba85790fd71fa9a) and fails when those files (eg some table data files) are being modified concurrently.

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/20134 changed listTables in FileHiveMetastore. The listDatabases is IMO still affected.
will keep the issue opem

**Comment by findepi** [comment]
@ebyhr did you maybe have fixed this?

**Comment by ebyhr** [comment]
Yes, this should be fixed by https://github.com/trinodb/trino/pull/20526 (merged on Feb 21). Let me close.
