### ISSUE TITLE
Query throws exception on mongodb connector if database have duplicate collection name as case insensitive

### ISSUE THREAD

**Issue by iercan** [trinodb/trino#20167]
Hi. 
Recently I've encountered below exception when I try to get collection list through superset on sql lab. 

```
io.trino.spi.TrinoException: Error listing tables for catalog mongodb: Duplicate key xxxxxx (attempted merging values TABLE and TABLE)
	at io.trino.metadata.MetadataListing.handleListingException(MetadataListing.java:358)
	at io.trino.metadata.MetadataListing.getRelationTypes(MetadataListing.java:144)
	at io.trino.connector.informationschema.InformationSchemaPageSource.addTablesRecords(InformationSchemaPageSource.java:284)
	at io.trino.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:221)
	at io.trino.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:185)
	at io.trino.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:379)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils$BlockingProcess.process(WorkProcessorUtils.java:207)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:317)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:359)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:255)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:132)
	at io.trino.operator.Driver.processInternal(Driver.java:398)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
	at io.trino.operator.Driver.process(Driver.java:293)
	at io.trino.operator.Driver.processForDuration(Driver.java:264)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_435____20231219_074717_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: Duplicate key xxxxx (attempted merging values TABLE and TABLE)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.spi.connector.ConnectorMetadata.getRelationTypes(ConnectorMetadata.java:295)
	at io.trino.tracing.TracingConnectorMetadata.getRelationTypes(TracingConnectorMetadata.java:275)
	at io.trino.metadata.MetadataManager.getRelationTypes(MetadataManager.java:570)
	at io.trino.tracing.TracingMetadata.getRelationTypes(TracingMetadata.java:325)
	at io.trino.metadata.MetadataListing.doGetRelationTypes(MetadataListing.java:150)
	at io.trino.metadata.MetadataListing.getRelationTypes(MetadataListing.java:141)
	... 41 more
```
Thanks to @ebyhr , I've realized this is because we have duplicate collection name as case insensitive.
My mongodb connector settings looks like below 
```
connector.name=mongodb
mongodb.connection-url=mongodb://nodeA:27017,nodeB:27017,nodeC:27017,nodeD:27017,nodeE:27017/?readPreference=secondary&maxStalenessSeconds=120&replicaSet=myReplicaSet&readPreferenceTags=usage:data
mongodb.read-preference=SECONDARY
mongodb.case-insensitive-name-matching=true
mongodb.socket-timeout=60000
```
version: 
trino : 435
mongodb : 6.0.3
trino python client: 0.327
superset: 2.1.1

**Comment by hashhar** [comment]
This is expected until we address #17.

Today Trino is all lowercase so once you enable `mongodb.case-insensitive-name-matching=true` we can start matching `table` to `tAbLe` on Mongo side but if both `TABLE` and `tAbLe` exist on Mongo side then we have ambiguity and hence fail.

**Comment by iercan** [comment]
@hashhar @ebyhr  I realized this issue occurs not only for duplication.  If a collection name contains another collection name i.e. `table_foo` and `table` still getting this error.

**Comment by iercan** [comment]
With further investigation I finally solved my issue, I realized there is more than one row for same table in _schema collection, one of them was named `table` and other was `Table`. We are using trino for long time maybe old versions inserted it I'm not sure. I cleared one of them and it worked.
