### ISSUE TITLE
Flaky test TestRaptorStorageManager

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#20198]
https://github.com/trinodb/trino/actions/runs/7287026131/job/19856994898?pr=20194

```
2023-12-21T04:53:59.342-0600	INFO	ForkJoinPool-1-worker-1	io.trino.plugin.raptor.legacy.storage.ShardRecoveryManager	Copying shard d8a554a7-4a8a-47e1-866c-2b756f1965be from backup...
2023-12-21T04:53:59.344-0600	INFO	ForkJoinPool-1-worker-1	io.trino.plugin.raptor.legacy.storage.ShardRecoveryManager	Copied shard d8a554a7-4a8a-47e1-866c-2b756f1965be from backup in 1.88ms (430B at 223.12kB/s)
Error:  Tests run: 14, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.495 s <<< FAILURE! -- in io.trino.plugin.raptor.legacy.storage.TestRaptorStorageManager
Error:  io.trino.plugin.raptor.legacy.storage.TestRaptorStorageManager.testWriterRollback -- Time elapsed: 0.034 s <<< ERROR!
java.nio.file.FileSystemException: /tmp/4993829403019729919: failed to delete one or more files; see suppressed exceptions for details
	at com.google.common.io.MoreFiles.throwDeleteFailed(MoreFiles.java:803)
	at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:554)
	at io.trino.plugin.raptor.legacy.storage.TestRaptorStorageManager.tearDown(TestRaptorStorageManager.java:167)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: java.nio.file.DirectoryNotEmptyException
		at java.base/sun.nio.fs.UnixSecureDirectoryStream.implDelete(UnixSecureDirectoryStream.java:207)
		at java.base/sun.nio.fs.UnixSecureDirectoryStream.deleteDirectory(UnixSecureDirectoryStream.java:224)
		at java.base/sun.nio.fs.UnixSecureDirectoryStream.deleteDirectory(UnixSecureDirectoryStream.java:42)
		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:630)
		at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:531)
		... 8 more
```

and then (note that the above apparent test failure is no longer reported)

```
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    TestRaptorStorageManager.tearDown:167 » FileSystem /tmp/4993829403019729919: failed to delete one or more files; see suppressed exceptions for details
[INFO] 
Error:  Tests run: 1029, Failures: 0, Errors: 1, Skipped: 162
[INFO] 
```

**Comment by ebyhr** [comment]
This might be the same issue as https://github.com/trinodb/trino/issues/12385 (PR https://github.com/trinodb/trino/pull/12802)

cc: @electrum

**Comment by findepi** [comment]
clsoing in favor of https://github.com/trinodb/trino/issues/12385
