### ISSUE TITLE
Internal error on overflow in sum aggregate of decimal

### ISSUE THREAD

**Issue by jkylling** [trinodb/trino#20227]
If a sum aggregate of decimals overflows an internal error is thrown. This should instead be a user error and trigger `NUMERIC_VALUE_OUT_OF_RANGE` instead, similar to:
```
select sum(n) from (values 1, 9223372036854775807) s(n);
```

To reproduce:
```
select sum(n) from (values decimal '1', decimal '99999999999999999999999999999999999999') s(n);
```

The exception thrown is:
```
java.lang.ArithmeticException: Decimal overflow
	at io.trino.operator.aggregation.DecimalSumAggregation.outputDecimal(DecimalSumAggregation.java:123)
	at io.trino.$gen.sumAccumulator_20231227_105506_1994.evaluateFinal(Unknown Source)
	at io.trino.operator.aggregation.Aggregator.evaluate(Aggregator.java:93)
	at io.trino.operator.AggregationOperator.getOutput(AggregationOperator.java:161)
        ...
```

**Comment by macohen** [comment]
I'd like to give this one a shot. Can you confirm that https://github.com/trinodb/trino/blob/2a9db69d5987b4cc0acfdfd524c8961013608fb1/core/trino-spi/src/main/java/io/trino/spi/type/Decimals.java#L298 should never throw an ArithmeticException? Instead, it should throw a TrinoException...

**Comment by macohen** [comment]
I'm switching this to use assertj and fixing some checkstyle things...

**Comment by macohen** [comment]
I realized in my test that "99999999999999999999999999999999999999" does not throw an exception, but adding another 9 like "999999999999999999999999999999999999999" does throw the exception. I'm going to switch the PR to a draft. I could also use any pointers as to where this may be going wrong. Thanks!

**Comment by jkylling** [comment]
@macohen there is already handling of overflows of Decimals for the ordinary addition operation, please see https://github.com/trinodb/trino/blob/7de78c4ba36b13ee895244d3ef870b4e50491613/core/trino-main/src/main/java/io/trino/type/DecimalOperators.java#L144

What is throwing an internal exception is the overflow handling in the sum aggregation operation of decimals, which is a different operation. There is already overflow handling for the decimal sum aggregation, but it throws an `ArithmeticException`: https://github.com/trinodb/trino/blob/0c0af9d3c7bf2e21d73bbd74bd1bc14e9e5a668a/core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalSumAggregation.java#L123 and https://github.com/trinodb/trino/blob/0c0af9d3c7bf2e21d73bbd74bd1bc14e9e5a668a/core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalSumAggregation.java#L132

We may want to change the exception on line 123 to an `TrinoException(NUMERIC_VALUE_OUT_OF_RANGE, "Decimal overflow");`, and wrap the `ArithmeticException` thrown on line 132 in a `TrinoException(NUMERIC_VALUE_OUT_OF_RANGE, "Decimal overflow", e);`

It looks like the way we handle overflow for the `DECIMAL` type and the `BIGINT` type is different, so unfortunately we cannot mirror the code for `LongSumAggregation`.

**Comment by macohen** [comment]
Thanks! I think I have it and will submit a new PR today.
Here's the output based on the updates suggested from the CLI:
```
trino> select sum(n) from (values decimal '1', decimal '99999999999999999999999999999999999999') s(n);
Query 20240102_145659_00000_8ug7d failed: Decimal overflow
```
...and the stack trace from TpchQueryRunner:
```
2024-01-02T09:57:03.628-0500	ERROR	stage-scheduler	io.trino.execution.StageStateMachine	Stage 20240102_145659_00000_8ug7d.0 failed
io.trino.spi.TrinoException: Decimal overflow
	at io.trino.operator.aggregation.DecimalSumAggregation.outputDecimal(DecimalSumAggregation.java:137)
	at io.trino.$gen.sumAccumulator_20240102_145703_114.evaluateFinal(Unknown Source)
	at io.trino.operator.aggregation.Aggregator.evaluate(Aggregator.java:93)
	at io.trino.operator.AggregationOperator.getOutput(AggregationOperator.java:161)
	at io.trino.operator.Driver.processInternal(Driver.java:398)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
	at io.trino.operator.Driver.process(Driver.java:293)
	at io.trino.operator.Driver.processForDuration(Driver.java:264)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_testversion____20240102_145642_75.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ArithmeticException: Decimal overflow
	at io.trino.spi.type.Decimals.throwIfOverflows(Decimals.java:301)
	at io.trino.operator.aggregation.DecimalSumAggregation.outputDecimal(DecimalSumAggregation.java:134)
	... 15 more
```

**Comment by traitsisgiorgos** [comment]
is this issue still open?
