### ISSUE TITLE
Hive connector doesn't support GMT timezone type

### ISSUE THREAD

**Issue by borderlayout** [trinodb/trino#20220]
### Reproduce：
I use trino to query hive. When the following GMT time zone parameters are configured, an error occurs when starting trino.

### Configuration
etc/catalog/hive1.properties 
connector.name=hive
hive.metastore.uri=thrift://kc1:9083
hive.config.resources=/etc/core-site.xml,/etc/hdfs-site.xml
**hive.orc.time-zone=GMT+8**

### The error log
`
1) [Guice/ErrorInjectingConstructor]: IllegalArgumentException: The datetime zone id 'GMT+8' is not recognised
  at OrcPageSourceFactory.<init>(OrcPageSourceFactory.java:130)
  while locating OrcPageSourceFactory
  at HiveModule.configure(HiveModule.java:126)
  while locating HivePageSourceFactory annotated with @Element(setName=,uniqueId=137, type=MULTIBINDER, keyType=)
  at HivePageSourceProvider.<init>(HivePageSourceProvider.java:91)
      \_ for 3rd parameter pageSourceFactories
  while locating HivePageSourceProvider
  at HiveModule.configure(HiveModule.java:110)
  while locating ConnectorPageSourceProvider annotated with @RealOptionalBinder$Default

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
Caused by: IllegalArgumentException: The datetime zone id 'GMT+8' is not recognised
    at DateTimeZone.forID(DateTimeZone.java:249)
    at HiveConfig.getOrcLegacyDateTimeZone(HiveConfig.java:697)
    at OrcPageSourceFactory.<init>(OrcPageSourceFactory.java:134)
    at OrcPageSourceFactory$$FastClassByGuice$$2aba9b7.GUICE$TRAMPOLINE(<generated>)
    at OrcPageSourceFactory$$FastClassByGuice$$2aba9b7.apply(<generated>)
    at DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
    at ConstructorInjector.provision(ConstructorInjector.java:114)
    at ConstructorInjector.access$000(ConstructorInjector.java:33)
    at ConstructorInjector$1.call(ConstructorInjector.java:98)
    at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
.......

2) [Guice/ErrorInjectingConstructor]: IllegalArgumentException: The datetime zone id 'GMT+8' is not recognised
  at OrcPageSourceFactory.<init>(OrcPageSourceFactory.java:130)
  while locating OrcPageSourceFactory
  at HiveModule.configure(HiveModule.java:126)
  while locating HivePageSourceFactory annotated with @Element(setName=,uniqueId=137, type=MULTIBINDER, keyType=)

`

**Comment by borderlayout** [comment]
PR：https://github.com/trinodb/trino/pull/20221

**Comment by hashhar** [comment]
Fixed via https://github.com/trinodb/trino/pull/20221
