### ISSUE TITLE
Flaky test TestDriver.testUnblocksOnTimeout

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#20245]
https://github.com/trinodb/trino/actions/runs/7357271602/job/20028850348?pr=20244 

```
Error:  Tests run: 163, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.69 s <<< FAILURE! -- in io.trino.operator.TestDriver
Error:  io.trino.operator.TestDriver.testUnblocksOnTimeout -- Time elapsed: 0.290 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting value to be true but was false
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.trino.operator.TestDriver.testUnblocksOnTimeout(TestDriver.java:308)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1351)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:422)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)


```

**Comment by ravijoisher** [comment]
Hello @findepi,

I recently setup trino project on my laptop and came across this bug. Is it ok if I take a look at this bug?

PS - This is my first issue/contribution.

**Comment by ksobolew** [comment]
https://github.com/trinodb/trino/actions/runs/7842991784/job/21402567809?pr=20641

**Comment by pajaks** [comment]
Should be fixed with: https://github.com/trinodb/trino/pull/20644
