### ISSUE TITLE
TestOracleQueryFailureRecoveryTest is flaky

### ISSUE THREAD

**Issue by homar** [trinodb/trino#20309]
Stack trace:

```
024-01-09T15:00:48.8055537Z [ERROR] io.trino.plugin.oracle.TestOracleQueryFailureRecoveryTest.testExplainAnalyze -- Time elapsed: 113.5 s <<< FAILURE!
2024-01-09T15:00:48.8056993Z org.opentest4j.AssertionFailedError: 
2024-01-09T15:00:48.8057931Z [There should be no remaining tmp_trino tables that are queryable. They are:
2024-01-09T15:00:48.8059392Z 	For queryId [20240109_150038_00340_jbg2s] (prefix [tmp_trino_e4d6677f_]) remaining tables: [tmp_trino_e4d6677f_ddcda619]
2024-01-09T15:00:48.8060490Z 		With errors: [
2024-01-09T15:00:48.8060977Z 			Expecting code to raise a throwable.]] 
2024-01-09T15:00:48.8061660Z Expecting value to be true but was false
2024-01-09T15:00:48.8062750Z 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
2024-01-09T15:00:48.8064402Z 	at io.trino.testing.BaseFailureRecoveryTest.checkTemporaryTables(BaseFailureRecoveryTest.java:422)
2024-01-09T15:00:48.8066412Z 	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.cleansUpTemporaryTables(BaseFailureRecoveryTest.java:583)
2024-01-09T15:00:48.8068313Z 	at io.trino.testing.BaseFailureRecoveryTest.testNonSelect(BaseFailureRecoveryTest.java:368)
2024-01-09T15:00:48.8070028Z 	at io.trino.testing.BaseFailureRecoveryTest.testTableModification(BaseFailureRecoveryTest.java:306)
2024-01-09T15:00:48.8071842Z 	at io.trino.testing.BaseFailureRecoveryTest.testTableModification(BaseFailureRecoveryTest.java:301)
2024-01-09T15:00:48.8073580Z 	at io.trino.testing.BaseFailureRecoveryTest.testExplainAnalyze(BaseFailureRecoveryTest.java:278)
2024-01-09T15:00:48.8074948Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2024-01-09T15:00:48.8076133Z 	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
2024-01-09T15:00:48.8077438Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
2024-01-09T15:00:48.8078943Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
2024-01-09T15:00:48.8080397Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
2024-01-09T15:00:48.8081991Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
2024-01-09T15:00:48.8083497Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

Executed here: https://github.com/trinodb/trino/actions/runs/7462636617/job/20305568854?pr=20211

**Comment by hashhar** [comment]
might be worth checking if it's the Oracle recycle bin causing issues. See https://satya-dba.blogspot.com/2009/02/recycle-bin.html for context.

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/7747877177/job/21129917583?pr=20539

```
Error:  Failures: 
Error:    TestOracleQueryFailureRecoveryTest>BaseFailureRecoveryTest.testExplainAnalyze:279->BaseFailureRecoveryTest.testTableModification:302->BaseFailureRecoveryTest.testTableModification:307->BaseFailureRecoveryTest.testNonSelect:339->BaseFailureRecoveryTest.checkTemporaryTables:423 [There should be no remaining tmp_trino tables that are queryable. They are:
	For queryId [20240201_221055_00298_wq9ez] (prefix [tmp_trino_f5b6bce2_]) remaining tables: [tmp_trino_f5b6bce2_b34b89a2]
		With errors: [
			Expecting code to raise a throwable.]] 
Expecting value to be true but was false
```

**Comment by Praveen2112** [comment]
https://github.com/trinodb/trino/actions/runs/7846202911/job/21412495866?pr=20445

 	For queryId [20240209_155453_00340_wac4h] (prefix [tmp_trino_56864193_]) remaining tables: [tmp_trino_56864193_6c30b365]
		With errors: [
			Expecting code to raise a throwable.]]

**Comment by Praveen2112** [comment]
But for Oracle recycle bin - the table would be renamed right to a specific pattern ? Here the it looks like the normal Trino table we create

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/7874385993/job/21484893211?pr=20661

```
[INFO] 
Error:  Failures: 
Error:    TestOracleQueryFailureRecoveryTest>BaseFailureRecoveryTest.testExplainAnalyze:279->BaseFailureRecoveryTest.testTableModification:302->BaseFailureRecoveryTest.testTableModification:307->BaseFailureRecoveryTest.testNonSelect:330->BaseFailureRecoveryTest.checkTemporaryTables:423 [There should be no remaining tmp_trino tables that are queryable. They are:
	For queryId [20240212_164405_00273_agxde] (prefix [tmp_trino_315a4aa9_]) remaining tables: [tmp_trino_315a4aa9_d08bf33a]
		With errors: [
			Expecting code to raise a throwable.]] 
Expecting value to be true but was false
[INFO] 
Error:  Tests run: 421, Failures: 1, Errors: 0, Skipped: 92
```

cc @losipiuk @dekimir

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/8114072250/job/22179928376
```
Error:    TestOracleTaskFailureRecoveryTest>BaseFailureRecoveryTest.testExplainAnalyze:279->BaseFailureRecoveryTest.testTableModification:302->BaseFailureRecoveryTest.testTableModification:307->BaseFailureRecoveryTest.testNonSelect:330->BaseFailureRecoveryTest.checkTemporaryTables:423 [There should be no remaining tmp_trino tables that are queryable. They are:
	For queryId [20240301_165606_00203_tex2e] (prefix [tmp_trino_715387f8_]) remaining tables: [tmp_trino_715387f8_b56ecb7a]
		With errors: [
			Expecting throwable message:
			  "Table 'trino_test.tmp_trino_715387f8_b56ecb7a' has no supported columns (all 0 columns are not supported)"
			to contain:
			  ".tmp_trino_715387f8_b56ecb7a' does not exist"
			but did not.
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/8179694894/job/22366298498?pr=17909

**Comment by ksobolew** [comment]
https://github.com/trinodb/trino/actions/runs/8567330556/job/23479059695

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/8605621096/job/23582676260
```
Error:    TestOracleQueryFailureRecoveryTest>BaseFailureRecoveryTest.testCreateTable:186->BaseFailureRecoveryTest.testTableModification:302->BaseFailureRecoveryTest.testTableModification:307->BaseFailureRecoveryTest.testNonSelect:369->BaseFailureRecoveryTest.checkTemporaryTables:423 [There should be no remaining tmp_trino tables that are queryable. They are:
	For queryId [20240408_203032_00341_rdk8y] (prefix [tmp_trino_0501af79_]) remaining tables: [tmp_trino_0501af79_21db1e87]
		With errors: [
			Expecting code to raise a throwable.]] 
Expecting value to be true but was false
```

**Comment by ebyhr** [comment]
This test looks very flaky now. 
https://github.com/trinodb/trino/actions/runs/8615878328/job/23618702951
cc: @losipiuk

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/actions/runs/8622811102/job/23635002663?pr=18521

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8633937206/job/23668306155?pr=21470

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8692149788/job/23836185914?pr=21559
