### ISSUE TITLE
Failing test TestTrinoGlueCatalog.testListTables: Schema already exists

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#20324]
https://github.com/trinodb/trino/actions/runs/7473286460/job/20338170171?pr=19996

```
Error:  Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 22.34 s <<< FAILURE! -- in io.trino.plugin.iceberg.catalog.glue.TestIcebergGlueTableOperationsInsertFailure
Error:  io.trino.plugin.iceberg.catalog.glue.TestTrinoGlueCatalog.testListTables -- Time elapsed: 0.128 s <<< ERROR!
io.trino.plugin.hive.SchemaAlreadyExistsException: Schema already exists: 'ns1'
	at io.trino.plugin.iceberg.catalog.glue.TrinoGlueCatalog.createNamespace(TrinoGlueCatalog.java:335)
	at io.trino.plugin.iceberg.catalog.BaseTrinoCatalogTest.testListTables(BaseTrinoCatalogTest.java:397)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1351)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:422)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: com.amazonaws.services.glue.model.AlreadyExistsException: Database already exists. (Service: AWSGlue; Status Code: 400; Error Code: AlreadyExistsException; Request ID: 4bf20aae-b9c2-4d55-bb0e-bf8ce19c4922; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.glue.AWSGlueClient.doInvoke(AWSGlueClient.java:14501)
	at com.amazonaws.services.glue.AWSGlueClient.invoke(AWSGlueClient.java:14468)
	at com.amazonaws.services.glue.AWSGlueClient.invoke(AWSGlueClient.java:14457)
	at com.amazonaws.services.glue.AWSGlueClient.executeCreateDatabase(AWSGlueClient.java:2125)
	at com.amazonaws.services.glue.AWSGlueClient.createDatabase(AWSGlueClient.java:2094)
	at io.trino.plugin.iceberg.catalog.glue.TrinoGlueCatalog.lambda$createNamespace$3(TrinoGlueCatalog.java:331)
	at io.trino.plugin.hive.metastore.glue.AwsApiCallStats.call(AwsApiCallStats.java:36)
	at io.trino.plugin.iceberg.catalog.glue.TrinoGlueCatalog.createNamespace(TrinoGlueCatalog.java:330)
	... 13 more
```

**Comment by findepi** [comment]
because of https://github.com/trinodb/trino/pull/19980

maybe not flaky at all
