### ISSUE TITLE
Flaky Iceberg Nessie test TestIcebergNessieCatalogConnectorSmokeTest: Cannot commit: ref hash is out of date. Update the ref 'main' and try again

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#20323]
https://github.com/trinodb/trino/actions/runs/7473387641/job/20338755528?pr=20316

```
Error:  io.trino.plugin.iceberg.catalog.nessie.TestIcebergNessieCatalogConnectorSmokeTest.testHiddenPathColumn -- Time elapsed: 2.032 s <<< ERROR!
io.trino.testing.QueryFailedException: Cannot commit: ref hash is out of date. Update the ref 'main' and try again
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:531)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:523)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:517)
	at io.trino.testing.sql.TestTable.createAndInsert(TestTable.java:55)
	at io.trino.testing.sql.TestTable.<init>(TestTable.java:46)
	at io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.testHiddenPathColumn(BaseIcebergConnectorSmokeTest.java:114)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1351)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:422)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1351)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:422)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: java.lang.Exception: SQL: INSERT INTO hidden_file_pathjgppuo8qm2 VALUES ((1, 'a'))
		at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:535)
		... 22 more
Caused by: org.apache.iceberg.exceptions.CommitFailedException: Cannot commit: ref hash is out of date. Update the ref 'main' and try again
	at io.trino.plugin.iceberg.catalog.nessie.IcebergNessieTableOperations.commitToExistingTable(IcebergNessieTableOperations.java:136)
	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.commit(AbstractIcebergTableOperations.java:175)
	at org.apache.iceberg.BaseTransaction.lambda$commitSimpleTransaction$3(BaseTransaction.java:417)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
	at org.apache.iceberg.BaseTransaction.commitSimpleTransaction(BaseTransaction.java:413)
	at org.apache.iceberg.BaseTransaction.commitTransaction(BaseTransaction.java:308)
	at io.trino.plugin.iceberg.IcebergMetadata.finishInsert(IcebergMetadata.java:1128)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishInsert(ClassLoaderSafeConnectorMetadata.java:617)
	at io.trino.tracing.TracingConnectorMetadata.finishInsert(TracingConnectorMetadata.java:697)
	at io.trino.metadata.MetadataManager.finishInsert(MetadataManager.java:1140)
	at io.trino.tracing.TracingMetadata.finishInsert(TracingMetadata.java:694)
	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$4(LocalExecutionPlanner.java:4159)
	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
	at io.trino.operator.Driver.processInternal(Driver.java:398)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
	at io.trino.operator.Driver.process(Driver.java:293)
	at io.trino.operator.Driver.processForDuration(Driver.java:264)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_testversion____20240110_113450_7114.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.projectnessie.error.NessieReferenceConflictException: Key 'tpch.hidden_file_pathjgppuo8qm2' has conflicting put-operation from commit '02520482f59768f642716a96d0fc6dcb813b510a0a51580d711dccc95e5b53f8'.
	at org.projectnessie.error.ErrorCode.lambda$asException$1(ErrorCode.java:66)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.projectnessie.error.ErrorCode.asException(ErrorCode.java:66)
	at org.projectnessie.client.rest.ResponseCheckFilter.checkResponse(ResponseCheckFilter.java:68)
	at org.projectnessie.client.rest.NessieHttpResponseFilter.filter(NessieHttpResponseFilter.java:29)
	at org.projectnessie.client.http.impl.jdk11.JavaRequest.lambda$executeRequest$1(JavaRequest.java:140)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
	at org.projectnessie.client.http.impl.jdk11.JavaRequest.executeRequest(JavaRequest.java:140)
	at org.projectnessie.client.http.HttpRequest.post(HttpRequest.java:90)
	at org.projectnessie.client.rest.v1.RestV1TreeClient.commitMultipleOperations(RestV1TreeClient.java:204)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.projectnessie.client.rest.v1.RestV1Client$ExceptionRewriter.invoke(RestV1Client.java:78)
	at jdk.proxy2/jdk.proxy2.$Proxy319.commitMultipleOperations(Unknown Source)
	at org.projectnessie.client.rest.v1.HttpCommitMultipleOperations.commit(HttpCommitMultipleOperations.java:34)
	at org.apache.iceberg.nessie.NessieIcebergClient.commitTable(NessieIcebergClient.java:483)
	at io.trino.plugin.iceberg.catalog.nessie.IcebergNessieTableOperations.commitToExistingTable(IcebergNessieTableOperations.java:129)
	... 27 more
```

**Comment by findepi** [comment]
cc @nastra

**Comment by nastra** [comment]
@ajantha-bhat can you take a look please?

**Comment by ajantha-bhat** [comment]
I ran the whole file 20 times and no test case failed. 
<img width="931" alt="image" src="https://github.com/trinodb/trino/assets/5889404/cc621f7b-c4c0-4925-8b99-5154c30fca95">

I have analyzed the table, Unless there is a concurrent insert on `tpch.hidden_file_pathjgppuo8qm2`, this error won't be reposted.  I checked and no other test is using this table name. So, not sure how multiple concurrent inserts of value (1, 'a') happened for this table. 

Is there a configuration of re-executing all the tests in a file if any of the test failed?

**Comment by findepi** [comment]
> Is there a configuration of re-executing all the tests in a file if any of the test failed?

no

@ajantha-bhat thanks for looking into this. Obviously, I don't know how to reproduce this problem either. It happened on the CI, see link in the description for full logs.

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8248151215/job/22558015276?pr=21031

```
Error:  Tests run: 29, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 24.61 s <<< FAILURE! -- in io.trino.plugin.iceberg.TestIcebergOrcSystemTables
Error:  io.trino.plugin.iceberg.catalog.nessie.TestIcebergNessieCatalogConnectorSmokeTest.testPartitionFilterRequired -- Time elapsed: 2.204 s <<< ERROR!
io.trino.testing.QueryFailedException: Cannot commit: ref hash is out of date. Update the ref 'main' and try again
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
	at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:501)
	at io.trino.testing.DistributedQueryRunner.executeWithPlan(DistributedQueryRunner.java:490)
	at io.trino.testing.QueryAssertions.assertDistributedUpdate(QueryAssertions.java:108)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:62)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:420)
	at io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.testPartitionFilterRequired(BaseIcebergConnectorSmokeTest.java:721)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: java.lang.Exception: SQL: INSERT INTO test_partition_4vepu1dnfx (id, a, ds) VALUES (1, 'a', 'a')
		at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:508)
		... 12 more
Caused by: org.apache.iceberg.exceptions.CommitFailedException: Cannot commit: ref hash is out of date. Update the ref 'main' and try again
	at io.trino.plugin.iceberg.catalog.nessie.IcebergNessieTableOperations.commitToExistingTable(IcebergNessieTableOperations.java:136)
	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.commit(AbstractIcebergTableOperations.java:175)
	at org.apache.iceberg.BaseTransaction.lambda$commitSimpleTransaction$3(BaseTransaction.java:417)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
	at org.apache.iceberg.BaseTransaction.commitSimpleTransaction(BaseTransaction.java:413)
	at org.apache.iceberg.BaseTransaction.commitTransaction(BaseTransaction.java:308)
	at io.trino.plugin.iceberg.IcebergMetadata.finishInsert(IcebergMetadata.java:1127)
	at io.trino.spi.connector.ConnectorMetadata.finishInsert(ConnectorMetadata.java:873)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishInsert(ClassLoaderSafeConnectorMetadata.java:633)
	at io.trino.tracing.TracingConnectorMetadata.finishInsert(TracingConnectorMetadata.java:718)
	at io.trino.metadata.MetadataManager.finishInsert(MetadataManager.java:1164)
	at io.trino.tracing.TracingMetadata.finishInsert(TracingMetadata.java:706)
	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$4(LocalExecutionPlanner.java:4147)
	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
	at io.trino.operator.Driver.processInternal(Driver.java:398)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
	at io.trino.operator.Driver.process(Driver.java:293)
	at io.trino.operator.Driver.processForDuration(Driver.java:264)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:76)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:191)
	at io.trino.$gen.Trino_testversion____20240312_115630_7163.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:192)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:174)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:161)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.projectnessie.error.NessieReferenceConflictException: Key 'tpch.test_partition_4vepu1dnfx' has conflicting put-operation from commit '7191dc401305cf2c78f0b1e[1443](https://github.com/trinodb/trino/actions/runs/8248151215/job/22558015276?pr=21031#step:5:1444)2f6599797fc45a7d01e21a8ec59e4218b6329'.
	at org.projectnessie.error.ErrorCode.lambda$asException$1(ErrorCode.java:66)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.projectnessie.error.ErrorCode.asException(ErrorCode.java:66)
	at org.projectnessie.client.rest.ResponseCheckFilter.checkResponse(ResponseCheckFilter.java:68)
	at org.projectnessie.client.rest.NessieHttpResponseFilter.filter(NessieHttpResponseFilter.java:29)
	at org.projectnessie.client.http.impl.jdk11.JavaRequest.lambda$executeRequest$1(JavaRequest.java:140)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
	at org.projectnessie.client.http.impl.jdk11.JavaRequest.executeRequest(JavaRequest.java:140)
	at org.projectnessie.client.http.HttpRequest.post(HttpRequest.java:90)
	at org.projectnessie.client.rest.v1.RestV1TreeClient.commitMultipleOperations(RestV1TreeClient.java:204)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.projectnessie.client.rest.v1.RestV1Client$ExceptionRewriter.invoke(RestV1Client.java:78)
	at jdk.proxy2/jdk.proxy2.$Proxy294.commitMultipleOperations(Unknown Source)
	at org.projectnessie.client.rest.v1.HttpCommitMultipleOperations.commit(HttpCommitMultipleOperations.java:34)
	at org.apache.iceberg.nessie.NessieIcebergClient.commitTable(NessieIcebergClient.java:483)
	at io.trino.plugin.iceberg.catalog.nessie.IcebergNessieTableOperations.commitToExistingTable(IcebergNessieTableOperations.java:129)
	... 35 more
```

**Comment by wendigo** [comment]
@ajantha-bhat can you take a look?

**Comment by ajantha-bhat** [comment]
I have already checked when reported but couldn't reproduce it. Is it observed recently? 

I also tried code review. Unless there are some concurrent commits, issue shouldn't happen.

**Comment by wendigo** [comment]
Yes, it happens on the master

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/8852914099/job/24313200894
```
Error:    TestIcebergNessieCatalogConnectorSmokeTest.testRegisterTableWithComments:157 
Expecting throwable message:
  "Cannot commit: ref hash is out of date. Update the ref 'main' and try again"
to contain:
  "register_table procedure is disabled"
but did not.
```

**Comment by findepi** [comment]
@ajantha-bhat who can fix this?

**Comment by ajantha-bhat** [comment]
>  @ajantha-bhat who can fix this?

will take a look this week. Mostly tomorrow.

**Comment by ajantha-bhat** [comment]
1. I tried running the `TestIcebergNessieCatalogConnectorSmokeTest` 20 times from IDE and no failures were observed.
<img width="1554" alt="Screenshot 2024-04-29 at 6 02 20 PM" src="https://github.com/trinodb/trino/assets/5889404/86f6df13-0d54-4502-a59a-da10fe244a88">

2. I ran the below command 10 times from maven (same command as CI but without git incremental builder)
`mvn test -B -Dmaven.source.skip=true -Dair.check.skip-all --fail-at-end -pl plugin/trino-iceberg`
No failure is observed related to Nessie. 

`[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 124.4 s -- in io.trino.plugin.iceberg.catalog.nessie.TestIcebergNessieCatalogConnectorSmokeTest`

3. I did code review, when concurrently some commit happens on the same branch, Nessie backend will throw `NessieReferenceConflictException` for the current commit. So, in Trino, `IcebergNessieTableOperations` will throw  `CommitFailedException` for that. But Iceberg will retry that commit from `BaseTransaction.commitSimpleTransaction` with latest hash and it should succeed if no other concurrent commit happened.  

Question for @findepi, @ebyhr:  
a) Is there a concurrent operation from CI? 
b) Can anyone help in reproducing it?
c) There are no Iceberg logs for (Retrying task after failure: ) from `Tasks.java`, so, why the retry didn't happen even for `CommitFailedException`? or Iceberg logs disabled?

@dimas-b, @adutra: WDYT?

**Comment by ajantha-bhat** [comment]
I found the concurrent execution from Junit (was looking for maven!), the TestIcebergNessieCatalogConnectorSmokeTest -> BaseIcebergConnectorSmokeTest -> BaseConnectorSmokeTest -> AbstractTestQueryFramework

the `AbstractTestQueryFramework` has `@Execution(CONCURRENT)`, so the child class is inheriting the execution mode. I can raise a PR to override execution mode for `TestIcebergNessieCatalogConnectorSmokeTest` to `@Execution(SAME_THREAD)` and that should avoid the problem. 

Still curious to know why there are no iceberg logs related to retry from `Tasks.java`

**Comment by ajantha-bhat** [comment]
Awesome. Thanks @ebyhr
