### ISSUE TITLE
`No catalog '...'` sporadic failures when using dynamic catalogs

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#20326]
eg https://github.com/trinodb/trino/actions/runs/7474305862/job/20341354556?pr=20320 

```
Error:  io.trino.plugin.iceberg.TestIcebergPartitionEvolution -- Time elapsed: 64.18 s <<< ERROR!
io.trino.testing.QueryFailedException: No catalog 'iceberg'
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:531)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:523)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:529)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:522)
	at io.trino.testing.QueryAssertions.copyTpchTables(QueryAssertions.java:515)
	at io.trino.plugin.iceberg.SchemaInitializer.accept(SchemaInitializer.java:55)
	at io.trino.plugin.iceberg.IcebergQueryRunner$Builder.build(IcebergQueryRunner.java:143)
	at io.trino.plugin.iceberg.TestIcebergPartitionEvolution.createQueryRunner(TestIcebergPartitionEvolution.java:39)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:112)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE IF NOT EXISTS nation AS SELECT * FROM tpch.tiny.nation
		at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:535)
		... 15 more
Caused by: java.lang.IllegalArgumentException: No catalog 'iceberg'
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
	at io.trino.connector.WorkerDynamicCatalogManager.getConnectorServices(WorkerDynamicCatalogManager.java:160)
	at io.trino.connector.ConnectorCatalogServiceProvider.getService(ConnectorCatalogServiceProvider.java:40)
	at io.trino.split.PageSinkManager.providerFor(PageSinkManager.java:78)
	at io.trino.split.PageSinkManager.createPageSink(PageSinkManager.java:48)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:141)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:130)
	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:105)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:665)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:876)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_testversion____20240110_132029_7770.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[....]

Error:    TestIcebergInputInfo>AbstractTestQueryFramework.init:112->createQueryRunner:40 » QueryFailed No catalog 'iceberg'
Error:    TestIcebergMigrateProcedure.testMigrateUnsupportedColumnType:311->AbstractTestQueryFramework.assertUpdate:414->AbstractTestQueryFramework.assertUpdate:419 » QueryFailed No catalog 'hive'
Error:    TestIcebergOrcWithBloomFilters>BaseOrcWithBloomFiltersTest.testOrcBloomFilterIsWrittenDuringInsert:67->AbstractTestQueryFramework.assertUpdate:414->AbstractTestQueryFramework.assertUpdate:419 » QueryFailed No catalog 'iceberg'
Error:    TestIcebergParquetSystemTables>BaseIcebergSystemTables.setUp:62->AbstractTestQueryFramework.assertUpdate:414->AbstractTestQueryFramework.assertUpdate:419 » QueryFailed No catalog 'iceberg'
Error:    TestIcebergParquetWithBloomFilters>BaseTestParquetWithBloomFilters.testBloomFilterRowGroupPruning:55->AbstractTestQueryFramework.assertQueryStats:573 » QueryFailed No catalog 'iceberg'
Error:    TestIcebergPartitionEvolution>AbstractTestQueryFramework.init:112->createQueryRunner:39 » QueryFailed No catalog 'iceberg'
Error:    TestIcebergRegisterTableProcedure.testRegisterTableWithDroppedTable:245->AbstractTestQueryFramework.assertUpdate:414->AbstractTestQueryFramework.assertUpdate:419 » QueryFailed No catalog 'iceberg'
Error:    TestIcebergV2>AbstractTestQueryFramework.init:112->createQueryRunner:117 » QueryFailed No catalog 'iceberg'
Error:    TestSharedHiveMetastore>AbstractTestQueryFramework.init:112->createQueryRunner:90 » QueryFailed No catalog 'iceberg'
Error:    TestIcebergTrinoRestCatalogConnectorSmokeTest>AbstractTestQueryFramework.init:112->createQueryRunner:107 » QueryFailed No catalog 'tpch'
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/7489779443/job/20388253018?pr=20328

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/7493648969/job/20400126277?pr=20328 
cc @jklamer

**Comment by jklamer** [comment]
Continuing to monitor after https://github.com/trinodb/trino/pull/20648 goes in.

**Comment by findepi** [comment]
https://github.com/starburstdata/cork/actions/runs/8427085920/job/23077153140?pr=512

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8430970220/job/23087770966?pr=21255

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/8432843586/job/23092753963

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8432023918/job/23090954652?pr=21259

**Comment by nineinchnick** [comment]
https://github.com/trinodb/trino/actions/runs/8449500139/job/23143758605?pr=21280

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/actions/runs/8543978956/job/23409050448

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8545062193/job/23412725829?pr=21378

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8554759250/job/23440802314?pr=21397

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8555921101/job/23444967735?pr=21400

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8555887544/job/23444551572?pr=21244

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8567473904/job/23479630031?pr=21411

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8567473904/job/23482135401?pr=21411

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8597126560/job/23555174260?pr=21444

**Comment by pettyjamesm** [comment]
https://github.com/trinodb/trino/actions/runs/8606357785/job/23619679424?pr=21164
