### ISSUE TITLE
Error: "Manifest file from the location [...] contains non-existent path: ..."

### ISSUE THREAD

**Issue by i-93** [trinodb/trino#20344]
The refactoring, which involved [Remove usage of InputFormat for generating symlink splits](https://github.com/trinodb/trino/commit/a231676237ca5f0b940b3447ca7f09921b5241dd#diff-475942f07e5fe59183513e321c071f2e5c1b83eae9246ed831688f3bbb501a2c) and [Fail query when the symlink file contains non-existent paths](https://github.com/trinodb/trino/commit/c7e96a6183ceda27bcabcbd4db2931f72b7474ed), has led to a regression.

When **`hive.file-status-cache-tables`** is enabled, the **directoryLister** fails to display new files until the **`hive.file-status-cache-expire-time`** is reached. Consequently, if the expiration time is set to a reasonable duration of 10-15 minutes, queries will result in errors during the first 10-15 minutes.

Prior to the refactoring, if a file's status was not found, it was directly loaded from the location specified in the manifest.

Although the refactoring significantly streamlines and simplifies the code, it comes with a substantial downside. We are no longer able to use file status caching, which significantly reduces speed and increases costs, especially for S3 backends.

**Comment by findinpath** [comment]
Please sketch a reproduction scenario

**Comment by i-93** [comment]
> Please sketch a reproduction scenario

1. Configure hive to enable file status cache, like
```
hive.file-status-cache-tables=*
hive.file-status-cache-expire-time=900s
```
2. Create a file in FS and symlink manifest pointing to that file.
3. Run the query (or execute `loadPartition()` for this manifest.
4. Add another file to FS and the manifest
5. Repeat (2). Because of cache you will get the 'non-existing path' exception. 

Thanks!

**Comment by findinpath** [comment]
Stacktrace with the scenario outline in the description of the issue and the setup info from https://github.com/trinodb/trino/pull/19364

```
Query 20240117_142351_00010_m2b2f failed: Manifest file from the location [hdfs://hadoop-master:9000/user/hive/warehouse/testsimpleparquet] contains non-existent path: hdfs://hadoop-master:9000/user/hive/warehouse/testsimpleparquet/000000_0_copy_3
io.trino.spi.TrinoException: Manifest file from the location [hdfs://hadoop-master:9000/user/hive/warehouse/testsimpleparquet] contains non-existent path: hdfs://hadoop-master:9000/user/hive/warehouse/testsimpleparquet/000000_0_copy_3
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.lambda$buildManifestFileIterator$5(BackgroundHiveSplitLoader.java:527)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1685)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:374)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:280)
	at io.trino.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
	at io.trino.$gen.Trino_dev____20240117_141516_2.run(Unknown Source)
```

**Comment by raunaqmorarka** [comment]
Fixed by https://github.com/trinodb/trino/pull/20414
