### ISSUE TITLE
Flaky  TestHashJoinOperator.testYield

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#20391]
```
Error:  io.trino.operator.join.unspilled.TestHashJoinOperator.testYield -- Time elapsed: 6.704 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 
[Expected join to stop processing (yield) after calling filter function once] 
expected: 1
 but was: 0
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.trino.operator.join.unspilled.TestHashJoinOperator.testYield(TestHashJoinOperator.java:367)
	at io.trino.operator.join.unspilled.TestHashJoinOperator.testYield(TestHashJoinOperator.java:310)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1351)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:422)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

https://github.com/trinodb/trino/actions/runs/7543003856/job/20533200537

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8822717720/job/24221659281?pr=21691

```
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestHashJoinOperator.testYield:311->testYield:367 [Expected join to stop processing (yield) after calling filter function once] 
expected: 1
 but was: 0
[INFO] 
Error:  Tests run: 8274, Failures: 1, Errors: 0, Skipped: 5
```
