### ISSUE TITLE
Consuming large results with table functions causes "Query exceeded per-node memory limit" error

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#20398]
```sql
SELECT *
FROM TABLE(exclude_columns(
 input => TABLE(tpch.sf100.orders),
 columns => DESCRIPTOR(orderstatus)));

 orderkey  | custkey  | totalprice | orderdate  |  orderpriority  |      clerk      | shippriority |                    >
-----------+----------+------------+------------+-----------------+-----------------+--------------+-------------------->
 500000001 |  9605725 |   63881.33 | 1994-10-28 | 4-NOT SPECIFIED | Clerk#000002414 |            0 | e of the carefully >
...

Query 20240117_021243_00035_3g5dg, FAILED, 3 nodes
http://localhost:8080/ui/query.html?20240117_021243_00035_3g5dg
Splits: 30 total, 21 done (70.00%)
CPU Time: 64.3s total, 1.53M rows/s,     0B/s, 69% active
Per Node: 2.8 parallelism, 4.23M rows/s,     0B/s
Parallelism: 8.3
Peak Memory: 13.6GB
7.73 [98.1M rows, 0B] [12.7M rows/s, 0B/s]

Query 20240117_021243_00035_3g5dg failed: Query exceeded per-node memory limit of 4.80GB [Allocated: 4.80GB, Delta: 497.44kB, Top Consumers: {PartitionAndSort=4.77GB, LazyOutputBuffer=26.40MB, TableScanOperator=2.90MB}]
io.trino.ExceededMemoryLimitException: Query exceeded per-node memory limit of 4.80GB [Allocated: 4.80GB, Delta: 497.44kB, Top Consumers: {PartitionAndSort=4.77GB, LazyOutputBuffer=26.40MB, TableScanOperator=2.90MB}]
	at io.trino.ExceededMemoryLimitException.exceededLocalUserMemoryLimit(ExceededMemoryLimitException.java:40)
	at io.trino.memory.QueryContext.enforceUserMemoryLimit(QueryContext.java:330)
	at io.trino.memory.QueryContext.updateUserMemory(QueryContext.java:165)
	at io.trino.memory.QueryContext.lambda$addTaskContext$0(QueryContext.java:250)
	at io.trino.memory.QueryContext$QueryMemoryReservationHandler.reserveMemory(QueryContext.java:311)
	at io.trino.memory.context.RootAggregatedMemoryContext.updateBytes(RootAggregatedMemoryContext.java:37)
	at io.trino.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
	at io.trino.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
	at io.trino.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
	at io.trino.memory.context.SimpleLocalMemoryContext.setBytes(SimpleLocalMemoryContext.java:65)
	at io.trino.operator.OperatorContext$InternalLocalMemoryContext.setBytes(OperatorContext.java:710)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:312)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_testversion____20240117_015825_75.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

The following query doesn't cause such error. 
```sql
SELECT orderkey, totalprice, orderdate, orderpriority, clerk, shippriority, comment FROM tpch.sf100.orders;
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/21378 might help

**Comment by dikuchan** [comment]
We are also encountering this issue with our custom table function. Neither row nor set semantics help.

Hi @findepi, thank you for your work on the [related PR](https://github.com/trinodb/trino/pull/21558). Do you have any updates on its progress? I'd be happy to help with testing or any other tasks needed to get it merged.

**Comment by dikuchan** [comment]
Hi @kasiafi,

I'm hoping to get your insight on the implementation of table function semantics.

It appears that table functions using _row semantics_ for an input table can lead to `ExceededMemoryLimitException` on large datasets. My understanding is that this occurs because row semantics is not distinguished from set semantics at the implementation level ([comment](https://github.com/trinodb/trino/blob/aec2d2a4f0f57a0a0c9d4aee3a1dd59fcb513438/core/trino-main/src/main/java/io/trino/operator/function/RegularTableFunctionPartition.java#L227)), causing Trino to collect the entire table argument into a single partition.

This behavior is particularly limiting because row semantics prevents using a `PARTITION BY` clause on the input, a workaround that makes it possible to manage large datasets with set semantics. As a result, row semantics is paradoxically less scalable.

This behavior seems to be the issue that @findepi's [PR](https://github.com/trinodb/trino/pull/21558) was aiming to solve.

Are there any plans to change this internal behavior to better support row semantics? If not, would a contribution be welcome to revive or continue the work from the aforesaid PR?

**Comment by tbaeg** [comment]
> Hi [@kasiafi](https://github.com/kasiafi),
> 
> I'm hoping to get your insight on the implementation of table function semantics.
> 
> It appears that table functions using _row semantics_ for an input table can lead to `ExceededMemoryLimitException` on large datasets. My understanding is that this occurs because row semantics is not distinguished from set semantics at the implementation level ([comment](https://github.com/trinodb/trino/blob/aec2d2a4f0f57a0a0c9d4aee3a1dd59fcb513438/core/trino-main/src/main/java/io/trino/operator/function/RegularTableFunctionPartition.java#L227)), causing Trino to collect the entire table argument into a single partition.
> 
> This behavior is particularly limiting because row semantics prevents using a `PARTITION BY` clause on the input, a workaround that makes it possible to manage large datasets with set semantics. As a result, row semantics is paradoxically less scalable.
> 
> This behavior seems to be the issue that [@findepi](https://github.com/findepi)'s [PR](https://github.com/trinodb/trino/pull/21558) was aiming to solve.
> 
> Are there any plans to change this internal behavior to better support row semantics? If not, would a contribution be welcome to revive or continue the work from the aforesaid PR?

Do you have more than 1 table argument in your function? IIRC, if you do, everything will be buffered in memory.

Also, FWIW, we have a fork with the mentioned PR in production for over a year now with a lot of success.

**Comment by dikuchan** [comment]
> Do you have more than 1 table argument in your function? IIRC, if you do, everything will be buffered in memory.

No, the function has just a single table argument. This issue still persists.

> Also, FWIW, we have a fork with the mentioned PR in production for over a year now with a lot of success.

Thanks, that's great to hear! Given that fact, it seems the best path forward would be to get this functionality merged upstream.
