### ISSUE TITLE
HUDI connector error with loading compaction file

### ISSUE THREAD

**Issue by willzgw** [trinodb/trino#20423]
Recently, I found a few issues with `HudiTableFileSystemView` while testing HUDI MOR and have resolved them, so if you're experiencing similar issues, I hope this ticket will help you.

1. Hudi misses compaction-related files when scanning for files.
The root cause is an error in the file extension definition: https://github.com/trinodb/trino/blob/292c101db17e77db7a8e475f85a04c797f1ad1ab/plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/timeline/HudiTimeline.java#L27-L71
```
String INFLIGHT_COMPACTION_EXTENSION = join(".", COMPACTION_ACTION, INFLIGHT_EXTENSION);    // result is 'compaction..inflight', with a redundant '.' in the middle.

String REQUESTED_COMPACTION_SUFFIX = join("", COMPACTION_ACTION, REQUESTED_EXTENSION);
String REQUESTED_COMPACTION_EXTENSION = join(".", REQUESTED_COMPACTION_SUFFIX);    // result is 'result is 'compaction.requested', missing a '.' at the beginning of the
String INFLIGHT_COMPACTION_EXTENSION = join(".", COMPACTION_ACTION, INFLIGHT_EXTENSION);    // esult is 'result is 'compaction.inflight', missing a '.' at the beginning of the
```

2. org.apache.avro.AvroRuntimeException: Not a Specific class: class
```
org.apache.avro.AvroRuntimeException: Not a Specific class: class io.trino.plugin.hudi.compaction.HudiCompactionPlan
    at org.apache.avro.specific.SpecificData.createSchema(SpecificData.java:403)
    at org.apache.avro.specific.SpecificData.lambda$new$3(SpecificData.java:337)
    at org.apache.avro.util.internal.ClassValueCache$1.computeValue(ClassValueCache.java:35)
    at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
    at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
    at java.base/java.lang.ClassValue.get(ClassValue.java:116)
    at org.apache.avro.util.internal.ClassValueCache.apply(ClassValueCache.java:45)
    at org.apache.avro.specific.SpecificData.getSchema(SpecificData.java:346)
    at org.apache.avro.specific.SpecificDatumReader.<init>(SpecificDatumReader.java:40)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.deserializeAvroMetadata(HudiTableFileSystemView.java:183)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.getCompactionPlan(HudiTableFileSystemView.java:149)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.lambda$getAllPendingCompactionPlans$3(HudiTableFileSystemView.java:137)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
    at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.getAllPendingCompactionPlans(HudiTableFileSystemView.java:143)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.getAllPendingCompactionOperations(HudiTableFileSystemView.java:105)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.<init>(HudiTableFileSystemView.java:96)
    at io.trino.plugin.hudi.query.HudiReadOptimizedDirectoryLister.<init>(HudiReadOptimizedDirectoryLister.java:52)
    at io.trino.plugin.hudi.HudiSplitSource.<init>(HudiSplitSource.java:95)
    at io.trino.plugin.hudi.HudiSplitManager.getSplits(HudiSplitManager.java:109)
    at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorSplitManager.getSplits(ClassLoaderSafeConnectorSplitManager.java:51)
    at io.trino.split.SplitManager.getSplits(SplitManager.java:67)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.createSplitSource(SplitSourceFactory.java:186)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:159)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:130)
    at io.trino.sql.planner.plan.TableScanNode.accept(TableScanNode.java:222)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.visitOutput(SplitSourceFactory.java:363)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.visitOutput(SplitSourceFactory.java:130)
    at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
    at io.trino.sql.planner.SplitSourceFactory.createSplitSources(SplitSourceFactory.java:110)
    at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.createStageScheduler(PipelinedQueryScheduler.java:1055)
    at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.create(PipelinedQueryScheduler.java:931)
    at io.trino.execution.scheduler.PipelinedQueryScheduler.createDistributedStagesScheduler(PipelinedQueryScheduler.java:312)
    at io.trino.execution.scheduler.PipelinedQueryScheduler.start(PipelinedQueryScheduler.java:293)
    at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:468)
    at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:256)
    at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
    at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
    at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
    at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
    at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
    at io.trino.$gen.Trino_trino426_sql_hudi_test_006_dirty____20240118_020750_2.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833) 
```
https://github.com/apache/avro/blob/main/lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java#L525
According to the source code of apache avro, the field name in a specific class must be `SCHEMA$` instead of `SCHMEA`

3. org.apache.avro.AvroRuntimeException: java.lang.IllegalAccessException
```
org.apache.avro.AvroRuntimeException: java.lang.IllegalAccessException: class org.apache.avro.specific.SpecificData cannot access a member of class io.trino.plugin.hudi.compaction.HudiCompactionPlan with modifiers "private static final"
    at org.apache.avro.specific.SpecificData.createSchema(SpecificData.java:405)
    at org.apache.avro.specific.SpecificData.lambda$new$3(SpecificData.java:337)
    at org.apache.avro.util.internal.ClassValueCache$1.computeValue(ClassValueCache.java:35)
    at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
    at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
    at java.base/java.lang.ClassValue.get(ClassValue.java:116)
    at org.apache.avro.util.internal.ClassValueCache.apply(ClassValueCache.java:45)
    at org.apache.avro.specific.SpecificData.getSchema(SpecificData.java:346)
    at org.apache.avro.specific.SpecificDatumReader.<init>(SpecificDatumReader.java:40)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.deserializeAvroMetadata(HudiTableFileSystemView.java:183)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.getCompactionPlan(HudiTableFileSystemView.java:149)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.lambda$getAllPendingCompactionPlans$3(HudiTableFileSystemView.java:137)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
    at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.getAllPendingCompactionPlans(HudiTableFileSystemView.java:143)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.getAllPendingCompactionOperations(HudiTableFileSystemView.java:105)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.<init>(HudiTableFileSystemView.java:96)
    at io.trino.plugin.hudi.query.HudiReadOptimizedDirectoryLister.<init>(HudiReadOptimizedDirectoryLister.java:52)
    at io.trino.plugin.hudi.HudiSplitSource.<init>(HudiSplitSource.java:95)
    at io.trino.plugin.hudi.HudiSplitManager.getSplits(HudiSplitManager.java:109)
    at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorSplitManager.getSplits(ClassLoaderSafeConnectorSplitManager.java:51)
    at io.trino.split.SplitManager.getSplits(SplitManager.java:67)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.createSplitSource(SplitSourceFactory.java:186)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:159)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:130)
    at io.trino.sql.planner.plan.TableScanNode.accept(TableScanNode.java:222)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.visitOutput(SplitSourceFactory.java:363)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.visitOutput(SplitSourceFactory.java:130)
    at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
    at io.trino.sql.planner.SplitSourceFactory.createSplitSources(SplitSourceFactory.java:110)
    at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.createStageScheduler(PipelinedQueryScheduler.java:1055)
    at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.create(PipelinedQueryScheduler.java:931)
    at io.trino.execution.scheduler.PipelinedQueryScheduler.createDistributedStagesScheduler(PipelinedQueryScheduler.java:312)
    at io.trino.execution.scheduler.PipelinedQueryScheduler.start(PipelinedQueryScheduler.java:293)
    at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:468)
    at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:256)
    at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
    at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
    at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
    at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
    at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
    at io.trino.$gen.Trino_trino426_sql_hudi_test_008_dirty____20240118_075604_2.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalAccessException: class org.apache.avro.specific.SpecificData cannot access a member of class io.trino.plugin.hudi.compaction.HudiCompactionPlan with modifiers "private static final"
    at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
    at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
    at java.base/java.lang.reflect.Field.checkAccess(Field.java:1102)
    at java.base/java.lang.reflect.Field.get(Field.java:423)
    at org.apache.avro.specific.SpecificData.createSchema(SpecificData.java:396)
    ... 50 more
```
**Root cause**: `SCHEMA$` should be declared as **public**.

4. java.lang.ClassCastException: class org.apache.avro.generic.GenericData$Record cannot be cast to class org.apache.avro.specific.SpecificRecordBase
```
java.lang.ClassCastException: class org.apache.avro.generic.GenericData$Record cannot be cast to class org.apache.avro.specific.SpecificRecordBase (org.apache.avro.generic.GenericData$Record and org.apache.avro.specific.SpecificRecordBase are in unnamed module of loader io.trino.server.PluginClassLoader @3082f7eb)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.deserializeAvroMetadata(HudiTableFileSystemView.java:186)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.getCompactionPlan(HudiTableFileSystemView.java:149)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.lambda$getAllPendingCompactionPlans$3(HudiTableFileSystemView.java:137)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
    at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.getAllPendingCompactionPlans(HudiTableFileSystemView.java:143)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.getAllPendingCompactionOperations(HudiTableFileSystemView.java:105)
    at io.trino.plugin.hudi.table.HudiTableFileSystemView.<init>(HudiTableFileSystemView.java:96)
    at io.trino.plugin.hudi.query.HudiReadOptimizedDirectoryLister.<init>(HudiReadOptimizedDirectoryLister.java:52)
    at io.trino.plugin.hudi.HudiSplitSource.<init>(HudiSplitSource.java:95)
    at io.trino.plugin.hudi.HudiSplitManager.getSplits(HudiSplitManager.java:109)
    at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorSplitManager.getSplits(ClassLoaderSafeConnectorSplitManager.java:51)
    at io.trino.split.SplitManager.getSplits(SplitManager.java:67)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.createSplitSource(SplitSourceFactory.java:186)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:159)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.visitTableScan(SplitSourceFactory.java:130)
    at io.trino.sql.planner.plan.TableScanNode.accept(TableScanNode.java:222)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.visitOutput(SplitSourceFactory.java:363)
    at io.trino.sql.planner.SplitSourceFactory$Visitor.visitOutput(SplitSourceFactory.java:130)
    at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
    at io.trino.sql.planner.SplitSourceFactory.createSplitSources(SplitSourceFactory.java:110)
    at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.createStageScheduler(PipelinedQueryScheduler.java:1055)
    at io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.create(PipelinedQueryScheduler.java:931)
    at io.trino.execution.scheduler.PipelinedQueryScheduler.createDistributedStagesScheduler(PipelinedQueryScheduler.java:312)
    at io.trino.execution.scheduler.PipelinedQueryScheduler.start(PipelinedQueryScheduler.java:293)
    at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:468)
    at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:256)
    at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
    at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
    at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
    at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
    at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
    at io.trino.$gen.Trino_trino426_sql_hudi_test_009_dirty____20240118_085531_2.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833) 
```
**Root cause**: Wrong class names was used in `HudiCompactionPlan` schema (SCHEMA$).
**Solution**: Use `HudiCompactionPlan` and `HudiCompactionOperation` instead of `HoodieCompactionPlan` and `HoodieCompactionOperation`.

**Comment by willzgw** [comment]
This problem no longer exists since Trino reintroduced the HUDI dependency and replaced the `HudiTableFileSystem` maintained by Trino.
