### ISSUE TITLE
Flaky TestIcebergGlueTableOperationsInsertFailure.testInsertFailureDoesNotCorruptTheTableMetadata

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#20471]
```
Error:  io.trino.plugin.iceberg.catalog.glue.TestIcebergGlueTableOperationsInsertFailure.testInsertFailureDoesNotCorruptTheTableMetadata -- Time elapsed: 3.525 s <<< FAILURE!
java.lang.AssertionError: 

Expecting actual throwable to be an instance of:
  org.apache.iceberg.exceptions.CommitStateUnknownException
but was:
  io.trino.testing.QueryFailedException: Test-simulated Glue timeout exception
Cannot determine whether the commit was successful or not, the underlying data files may or may not be needed. Manual intervention via the Remove Orphan Files Action can remove these files when a connection to the Catalog can be re-established if the commit was actually unsuccessful.
Please check to see whether or not your commit was successful before retrying this commit. Retrying an already successful operation will result in duplicate records or unintentional modifications.
At this time no files will be deleted including possibly unused manifest lists.
	at io.trino.testing.DirectTrinoClient.toMaterializedRows(DirectTrinoClient.java:159)
	at io.trino.testing.DirectTrinoClient.execute(DirectTrinoClient.java:135)
	at io.trino.testing.DirectTrinoClient.execute(DirectTrinoClient.java:84)
	...(55 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
	at io.trino.plugin.iceberg.catalog.glue.TestIcebergGlueTableOperationsInsertFailure.testInsertFailureDoesNotCorruptTheTableMetadata(TestIcebergGlueTableOperationsInsertFailure.java:127)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
https://github.com/trinodb/trino/actions/runs/7658421188/job/20871459013

**Comment by ebyhr** [comment]
cc: @findinpath

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/7663196188/job/20885736946
