### ISSUE TITLE
Flaky test TestSqlTaskManagerRaceWithCatalogPrune.testMultipleTaskUpdatesWithMultipleCatalogPrunes

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#20517]
Failed for me when running locally

```
org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.util.concurrent.TimeoutException: Waited 2 minutes (plus 44320291 nanoseconds delay) for TrustedListenableFutureTask@56fbcbf9[status=PENDING, info=[task=[running=[RUNNING ON pool-4226-thread-1], java.util.concurrent.Executors$RunnableAdapter@3c2d44ee[Wrapped task = io.trino.execution.TestSqlTaskManagerRaceWithCatalogPrune$$Lambda/0x000000e0037d1ed0@4969b328]]]]

	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:84)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:75)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:58)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3228)
	at io.trino.execution.TestSqlTaskManagerRaceWithCatalogPrune.testMultipleTaskUpdatesWithMultipleCatalogPrunes(TestSqlTaskManagerRaceWithCatalogPrune.java:239)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.concurrent.TimeoutException: Waited 2 minutes (plus 44320291 nanoseconds delay) for TrustedListenableFutureTask@56fbcbf9[status=PENDING, info=[task=[running=[RUNNING ON pool-4226-thread-1], java.util.concurrent.Executors$RunnableAdapter@3c2d44ee[Wrapped task = io.trino.execution.TestSqlTaskManagerRaceWithCatalogPrune$$Lambda/0x000000e0037d1ed0@4969b328]]]]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:533)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:99)
	at io.trino.execution.TestSqlTaskManagerRaceWithCatalogPrune.lambda$testMultipleTaskUpdatesWithMultipleCatalogPrunes$3(TestSqlTaskManagerRaceWithCatalogPrune.java:239)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:71)
	... 10 more

```

**Comment by findepi** [comment]
cc @jklamer @dain

**Comment by jklamer** [comment]
2 options:
1) Increase the timeout. Hard to believe that the test itself is taking that long without some sort of resource contention.
2) Delete the test. It existed to reproduce the bug, but now that the lock is in place, it's not at a huge risk of being deleted

**Comment by findepi** [comment]
does it mean @jklamer it's a problem with the test only?

**Comment by findepi** [comment]
```
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 120.2 s <<< FAILURE! -- in io.trino.execution.TestSqlTaskManagerRaceWithCatalogPrune
Error:  io.trino.execution.TestSqlTaskManagerRaceWithCatalogPrune.testMultipleTaskUpdatesWithMultipleCatalogPrunes -- Time elapsed: 120.1 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.util.concurrent.TimeoutException: Waited 2 minutes (plus 386640 nanoseconds delay) for TrustedListenableFutureTask@200de162[status=PENDING, info=[task=[running=[RUNNING ON pool-493-thread-1], java.util.concurrent.Executors$RunnableAdapter@3ec7a745[Wrapped task = io.trino.execution.TestSqlTaskManagerRaceWithCatalogPrune$$Lambda/0x0000794118385320@3c6df708]]]]
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:84)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:75)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:58)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3228)
	at io.trino.execution.TestSqlTaskManagerRaceWithCatalogPrune.testMultipleTaskUpdatesWithMultipleCatalogPrunes(TestSqlTaskManagerRaceWithCatalogPrune.java:240)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.util.concurrent.TimeoutException: Waited 2 minutes (plus 386640 nanoseconds delay) for TrustedListenableFutureTask@200de162[status=PENDING, info=[task=[running=[RUNNING ON pool-493-thread-1], java.util.concurrent.Executors$RunnableAdapter@3ec7a745[Wrapped task = io.trino.execution.TestSqlTaskManagerRaceWithCatalogPrune$$Lambda/0x0000794118385320@3c6df708]]]]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:533)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:99)
	at io.trino.execution.TestSqlTaskManagerRaceWithCatalogPrune.lambda$testMultipleTaskUpdatesWithMultipleCatalogPrunes$3(TestSqlTaskManagerRaceWithCatalogPrune.java:240)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:71)
	... 10 more
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/13669255850/job/38216285780?pr=24882
