### ISSUE TITLE
Flaky test TestDistributedFaultTolerantEngineOnlyQueries.testMetadataOnlyQueries

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#20521]
https://github.com/trinodb/trino/actions/runs/7717950095/job/21038443120?pr=20509

```
Error:  io.trino.faulttolerant.TestDistributedFaultTolerantEngineOnlyQueries.testMetadataOnlyQueries -- Time elapsed: 26.40 s <<< ERROR!
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:[377](https://github.com/trinodb/trino/actions/runs/7717950095/job/21038443120?pr=20509#step:5:378))
	at io.trino.faulttolerant.TestDistributedFaultTolerantEngineOnlyQueries.testMetadataOnlyQueries(TestDistributedFaultTolerantEngineOnlyQueries.java:165)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by findepi** [comment]
Failure mode is different than in https://github.com/trinodb/trino/issues/19045

Can this be because the test code contains `Thread.sleep(1000)`?

cc @losipiuk @wweiss-starburst
