### ISSUE TITLE
Query mail fail with QUERY_QUEUE_FULL when resource group admission fails

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#20551]
found by Ci

```
[INFO] 
Error:  Failures: 
Error:    TestQueuesDb.testSelectorPriority:272 
expected: QUERY_QUEUE_FULL:131074
 but was: GENERIC_INTERNAL_ERROR:65536
[INFO] 
Error:  Tests run: 3427, Failures: 1, Errors: 0, Skipped: 145
```

after modifying the test to show the failure i got this

```
Suppressed: java.lang.IllegalStateException: Query not registered: 20240202_162622_00107_xg34p
		at io.trino.metadata.LanguageFunctionManager.getQueryFunctions(LanguageFunctionManager.java:140)
		at io.trino.metadata.LanguageFunctionManager.getFunctions(LanguageFunctionManager.java:155)
		at io.trino.metadata.MetadataManager.getFunctions(MetadataManager.java:2509)
		at io.trino.metadata.MetadataManager.lambda$getFunctions$66(MetadataManager.java:2477)
		at java.base/java.util.Optional.map(Optional.java:260)
		at io.trino.metadata.MetadataManager.getFunctions(MetadataManager.java:2477)
		at io.trino.tracing.TracingMetadata.getFunctions(TracingMetadata.java:1236)
		at io.trino.metadata.FunctionResolver.isFunctionKind(FunctionResolver.java:111)
		at io.trino.metadata.FunctionResolver.isAggregationFunction(FunctionResolver.java:95)
		at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:1232)
		at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:624)
		at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
		at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
		at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:647)
		at io.trino.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:492)
		at io.trino.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:3512)
		at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:5037)
		at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelectSingleColumn(StatementAnalyzer.java:4840)
		at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:4615)
```

**Comment by findepi** [comment]
there is a race in QueryStateMachine causing original failure cause being lost


```java
    public boolean transitionToFailed(Throwable throwable)
    {
        cleanupQueryQuietly();   // 1️⃣ this releases resources and may cause some other thread (planner) to fail and call transitionToFailed(); perhaps with GENERIC_INTERNAL_ERROR
        queryStateTimer.endQuery();

        // NOTE: The failure cause must be set before triggering the state change, so
        // listeners can observe the exception. This is safe because the failure cause
        // can only be observed if the transition to FAILED is successful.
        requireNonNull(throwable, "throwable is null");
        failureCause.compareAndSet(null, toFailure(throwable)); // 2️⃣ only now we register the failure, but someone could register a different one in the mean time. Original failure cause is lost
```


cc @dain @sopel39 @losipiuk @arhimondr @pettyjamesm for QueryStateMachine thoughts
cc @electrum for `LanguageFunctionManager` being involved
cc @martint  for planner (StatementAnalyzer thread) being involved

**Comment by losipiuk** [comment]
> for QueryStateMachine thoughts

Can we set `failureCause` before we call out to `cleanupQueryQuietly`? Or leave the call place but mark in QueryStateMachine which thread calls out to `cleanupQueryQuietly` and make sure that `throwable` from this thread wins the race of setting it to `failureCause` field?

**Comment by findepi** [comment]
> Can we set `failureCause` before we call out to `cleanupQueryQuietly`?

that's my thinking too.

i shared the problem internally with @trinodb/maintainers for more perspective, since there may be some not obvious concurrency aspects of that

**Comment by sopel39** [comment]
I think it's just a bug unless someone is actually assuming that completed `failureCause` means query doesn't allocate any resources.

**Comment by findepi** [comment]
proposed solution: https://github.com/trinodb/trino/pull/20582
