### ISSUE TITLE
IndexOutOfBoundsException when writing huge ORC chunk

### ISSUE THREAD

**Issue by oneonestar** [trinodb/trino#20587]
Probability related to #17386

https://github.com/trinodb/trino/blob/46e991e3c8c74d6d6c3b17884a6bb61a64169419/lib/trino-orc/src/main/java/io/trino/orc/OrcWriter.java#L267-L269

I think this should be:
```java
chunk = page.getRegion(writeOffset, chunk.getPositionCount() / 2);
```

Error Slack:
```
java.lang.IndexOutOfBoundsException: Invalid position 1066 and length 1012 in page with 2024 positions
	at io.trino.spi.Page.getRegion(Page.java:157)
	at io.trino.orc.OrcWriter.write(OrcWriter.java:268)
	at io.trino.plugin.hive.orc.OrcFileWriter.appendRows(OrcFileWriter.java:173)
	at io.trino.plugin.hive.HiveWriter.append(HiveWriter.java:85)
	at io.trino.plugin.hive.HivePageSink.writePage(HivePageSink.java:325)
	at io.trino.plugin.hive.HivePageSink.appendPage(HivePageSink.java:274)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:68)
	at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:276)
	at io.trino.operator.Driver.processInternal(Driver.java:403)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
	at io.trino.operator.Driver.process(Driver.java:293)
	at io.trino.operator.Driver.processForDuration(Driver.java:264)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:76)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:177)
	at io.trino.$gen.Trino_428_1642_gbc85d90_dirty____20240205_033821_2.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:178)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:174)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:161)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by oneonestar** [comment]
@findepi
