### ISSUE TITLE
Incorrect type in error message for window in aggregation in expression

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#20593]
```sql
SELECT a / max(max(a) OVER (), 10)
FROM (VALUES 1, 2, 3) t(a)
```

```
io.trino.spi.TrinoException: line 1:10: Cannot apply operator: integer / array(integer)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:52)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.getOperator(ExpressionAnalyzer.java:3186)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitArithmeticBinary(ExpressionAnalyzer.java:1001)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitArithmeticBinary(ExpressionAnalyzer.java:624)
	at io.trino.sql.tree.ArithmeticBinaryExpression.accept(ArithmeticBinaryExpression.java:85)
	at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:647)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:492)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:3513)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:5031)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelectSingleColumn(StatementAnalyzer.java:4834)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:4609)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:3071)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:522)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:541)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:549)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1559)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:522)
	at io.trino.sql.tree.Query.accept(Query.java:118)
```

but there is no array, is there?

expected same error as for 
```sql
SELECT max(max(a) OVER (), 10)
FROM (VALUES 1, 2, 3) t(a)
```

i.e.
```
io.trino.spi.TrinoException: line 1:8: Cannot nest window functions or row pattern measures inside aggregation 'max': [max(a) OVER ()]
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:52)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:46)
	at io.trino.sql.analyzer.AggregationAnalyzer$Visitor.visitFunctionCall(AggregationAnalyzer.java:391)
	at io.trino.sql.analyzer.AggregationAnalyzer$Visitor.visitFunctionCall(AggregationAnalyzer.java:216)
	at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.AggregationAnalyzer$Visitor.process(AggregationAnalyzer.java:789)
	at io.trino.sql.analyzer.AggregationAnalyzer.analyze(AggregationAnalyzer.java:208)
	at io.trino.sql.analyzer.AggregationAnalyzer.verifySourceAggregations(AggregationAnalyzer.java:141)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeAggregations(StatementAnalyzer.java:4915)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:3132)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:522)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
```

**Comment by martint** [comment]
There is an array. `max(max(a) OVER (), 10)` is an invocation of the "max N" aggregation function, which returns an array:  https://trino.io/docs/current/functions/aggregate.html?#max

**Comment by findepi** [comment]
Now it makes sense.
