### ISSUE TITLE
Invalid position %s in block with %s positions error

### ISSUE THREAD

**Issue by GukjinHan** [trinodb/trino#20607]
error raised by

```sql
WITH A AS (
    SELECT 1 AS id, ROW('T') AS val
    UNION ALL
    SELECT 2 AS id, NULL AS val
), B AS (
    SELECT 1 AS id
)
SELECT *
FROM A
WHERE A.id NOT IN (SELECT id FROM B WHERE id = A.id)
```
-> `Query failed: Invalid position 0 in block with 0 positions`

In my view, this probably occurs when position validation fails if a null is included in the row type column while using correlated subquery.

I know correlated subqueries are not recommended, but can you check if this error is a bug or intended?

**Comment by raunaqmorarka** [comment]
Can you share the full error stacktrace and the version of Trino that you're using ?
cc: @dain

**Comment by GukjinHan** [comment]
here is my enviroment information

- Trino 426
- AWS EMR 6.15.0 (emr-6.15.0)

stacktrace
```
java.lang.IllegalArgumentException: Invalid position 0 in block with 0 positions
	at io.trino.spi.block.BlockUtil.checkValidPosition(BlockUtil.java:70)
	at io.trino.spi.block.BlockUtil.checkReadablePosition(BlockUtil.java:76)
	at io.trino.spi.block.AbstractVariableWidthBlock.isNull(AbstractVariableWidthBlock.java:147)
	at io.trino.spi.block.AbstractSingleRowBlock.isNull(AbstractSingleRowBlock.java:48)
	at io.trino.spi.type.RowType.getFlatVariableWidthSize(RowType.java:308)
	at io.trino.operator.FlatHashStrategy.getTotalVariableWidth(FlatHashStrategy.java:209)
	at io.trino.operator.FlatHash.addNewGroup(FlatHash.java:292)
	at io.trino.operator.FlatHash.putIfAbsent(FlatHash.java:217)
	at io.trino.operator.FlatGroupByHash.putIfAbsent(FlatGroupByHash.java:173)
	at io.trino.operator.FlatGroupByHash$GetNonDictionaryGroupIdsWork.process(FlatGroupByHash.java:480)
	at io.trino.operator.TransformWork.process(TransformWork.java:40)
	at io.trino.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:444)
	at io.trino.operator.Driver.processInternal(Driver.java:400)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_426____20240206_070230_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

---

+) I was previously using trino 388 (388.AMZN.0), and it worked well without any problems.

**Comment by raunaqmorarka** [comment]
Could you try with latest version of Trino ? This has most likely already been fixed

**Comment by GukjinHan** [comment]
Yes, it is okay at trino 438

but EMR 7.0.0, the latest version of AWS EMR, still supports trino up to 426, so I have no choice but to modify the query and use it :(

Thanks for your help.

**Comment by lxqfy** [comment]
I faced a similar problem with Trino 426. Using set session flat_group_by_hash=false serves as a workaround. I'll investigate which commit addressed this since I need to remain on version 426 for some time.

**Comment by GukjinHan** [comment]
In our case, the correlated subquery were defined once more in the with clause.
like this

```sql
WITH A AS (
    SELECT 1 AS id, ROW('T') AS val
    UNION ALL
    SELECT 2 AS id, NULL AS val
), B AS (
    SELECT 1 AS id
), C AS (
    SELECT id FROM B WHERE id = A.id
)
SELECT *
FROM A
WHERE A.id NOT IN C
```

But, Thanks for the good advice :)

**Comment by EugeneChung** [comment]
What version has fixed the problem?
I found [a PR](https://github.com/trinodb/trino/pull/18770) related to flat_group_by_hash, but it's applied to 425, meaning the PR does not completely resolve the problem.
