### ISSUE TITLE
Flaky test TestThrottledAsyncQueue.testThrottle: Expecting value to be false but was true

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#20651]
https://github.com/trinodb/trino/actions/runs/7847471851/job/21416973734?pr=20648

```
Error:  Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.225 s <<< FAILURE! -- in io.trino.plugin.hive.util.TestThrottledAsyncQueue
Error:  io.trino.plugin.hive.util.TestThrottledAsyncQueue.testThrottle -- Time elapsed: 1.906 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting value to be false but was true
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.trino.plugin.hive.util.TestThrottledAsyncQueue.testThrottle(TestThrottledAsyncQueue.java:86)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.AssertTimeoutPreemptively.lambda$submitTask$3(AssertTimeoutPreemptively.java:95)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by findepi** [comment]
Might be different than the previous issue about this test: https://github.com/trinodb/trino/issues/2797

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8177410116/job/22359062237?pr=20961

```
Error:  Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.889 s <<< FAILURE! -- in io.trino.plugin.hive.util.TestThrottledAsyncQueue
Error:  io.trino.plugin.hive.util.TestThrottledAsyncQueue.testThrottle -- Time elapsed: 1.383 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting value to be false but was true
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.trino.plugin.hive.util.TestThrottledAsyncQueue.testThrottle(TestThrottledAsyncQueue.java:86)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.AssertTimeoutPreemptively.lambda$submitTask$3(AssertTimeoutPreemptively.java:95)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8797678348/job/24144081114?pr=21654
```
Error:  io.trino.plugin.hive.util.TestThrottledAsyncQueue.testThrottle -- Time elapsed: 1.493 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting value to be false but was true
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.trino.plugin.hive.util.TestThrottledAsyncQueue.testThrottle(TestThrottledAsyncQueue.java:86)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.AssertTimeoutPreemptively.lambda$submitTask$3(AssertTimeoutPreemptively.java:95)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```
