### ISSUE TITLE
hive properties support for 

### ISSUE THREAD

**Issue by fcomte** [trinodb/trino#20804]
Hello,

I am trying to access data on S3 with a hive metastore.
I only have temporary credentials and it seems that I can't specify a hive.s3.aws-session-token

As a workaround I also tried to add hadoop-aws jar into the lib directory for hive plugins plugin/hive/hdfs/
and add a core-site.xml 
```
<property>
  <name>fs.s3a.aws.credentials.provider</name>
  <value>org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider</value>
</property>
```
and also fs.s3a.session.token , key and secret

the TemporaryAWSCredentialsProvider is loaded but I get this nocredential error

```
io.trino.spi.TrinoException: Provider TemporaryAWSCredentialsProvider has no credentials: 
	at io.trino.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:288)
	at io.trino.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
	at io.trino.$gen.Trino_439____20240222_100425_2.run(Unknown Source)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:79)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.apache.hadoop.fs.s3a.CredentialInitializationException: Provider TemporaryAWSCredentialsProvider has no credentials: 
	at org.apache.hadoop.fs.s3a.auth.AbstractSessionCredentialsProvider.getCredentials(AbstractSessionCredentialsProvider.java:138)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1269)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:845)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:794)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5520)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5467)
	at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:1001)
	at io.trino.hdfs.s3.TrinoS3FileSystem.listObjects(TrinoS3FileSystem.java:856)
	at io.trino.hdfs.s3.TrinoS3FileSystem.listPath(TrinoS3FileSystem.java:831)
	at io.trino.hdfs.s3.TrinoS3FileSystem.listFiles(TrinoS3FileSystem.java:452)
	at io.trino.hdfs.TrinoFileSystemCache$FileSystemWrapper.listFiles(TrinoFileSystemCache.java:396)
	at io.trino.filesystem.hdfs.HdfsFileSystem.lambda$listFiles$5(HdfsFileSystem.java:236)
	at io.trino.hdfs.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.hdfs.HdfsEnvironment.doAs(HdfsEnvironment.java:134)
	at io.trino.filesystem.hdfs.HdfsFileSystem.listFiles(HdfsFileSystem.java:234)
	at io.trino.filesystem.manager.SwitchingFileSystem.listFiles(SwitchingFileSystem.java:110)
	at io.trino.filesystem.tracing.TracingFileSystem.lambda$listFiles$4(TracingFileSystem.java:109)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
	at io.trino.filesystem.tracing.TracingFileSystem.listFiles(TracingFileSystem.java:109)
	at io.trino.plugin.hive.fs.CachingDirectoryLister.listFilesRecursively(CachingDirectoryLister.java:97)
	at io.trino.plugin.hive.fs.TransactionScopeCachingDirectoryLister.createListingRemoteIterator(TransactionScopeCachingDirectoryLister.java:97)
	at io.trino.plugin.hive.fs.TransactionScopeCachingDirectoryLister.lambda$listInternal$0(TransactionScopeCachingDirectoryLister.java:78)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4955)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3589)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2328)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2187)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2081)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4036)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4950)
	at io.trino.cache.EvictableCache.get(EvictableCache.java:112)
	at io.trino.plugin.hive.fs.TransactionScopeCachingDirectoryLister.listInternal(TransactionScopeCachingDirectoryLister.java:78)
	at io.trino.plugin.hive.fs.TransactionScopeCachingDirectoryLister.listFilesRecursively(TransactionScopeCachingDirectoryLister.java:70)
	at io.trino.plugin.hive.fs.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:140)
	at io.trino.plugin.hive.fs.HiveFileIterator.<init>(HiveFileIterator.java:57)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.createInternalHiveSplitIterator(BackgroundHiveSplitLoader.java:639)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:493)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:367)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:281)
	... 6 more

```

In this workaround it seems that credentials properties are not seen by hadoop libraries.

How can I try to use a session token to access data on S3 ?

**Comment by Praveen2112** [comment]
There are a few alternatives discussed here - https://github.com/trinodb/trino/pull/6102, Can we try something like that ?

**Comment by fcomte** [comment]
I don't understand how I can configure it based on #6102

**Comment by hashhar** [comment]
It's not about configuring.

AWS Session Tokens are short-lived. If you use it then you somehow need to also manage updating the config and to restart Trino everytime the session token expires.

It's simply much better to use IAM for such temporary credential purposes. See https://github.com/trinodb/trino/pull/6102#pullrequestreview-585649053 and https://github.com/trinodb/trino/pull/6102#issuecomment-784668293 are I think what we're trying to suggest.

**Comment by fcomte** [comment]
I can start trino cluster on demand on a kubernetes cluster
My AWS Session tokens is quite long (more than 1 week). Storage is Minio 
I can't do anything else that trying to use this token.

**Comment by fcomte** [comment]
I am using this service (in fact I develop it) : 

https://datalab.sspcloud.fr/catalog/databases

**Comment by fcomte** [comment]
I finally sucess to use session token for object storage by setting the following properties in core-site.xml with the standard docker image : 
```
<property>
    <name>trino.s3.session-token</name>
    <value></value>
</property>
<property>
    <name>trino.s3.access-key</name>
    <value></value>
</property>
<property>
    <name>trino.s3.secret-key</name>
    <value></value>
</property>
<property>
