### ISSUE TITLE
Restrict drop column operations for hive tables

### ISSUE THREAD

**Issue by Praveen2112** [trinodb/trino#20807]
As per the Hive docs - https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-AlterTable/Partition/Column

REPLACE COLUMNS removes all existing columns and adds the new set of columns. This can be done only for tables with a native SerDe (DynamicSerDe, MetadataTypedColumnsetSerDe, LazySimpleSerDe and ColumnarSerDe). Refer to [Hive SerDe](https://cwiki.apache.org/confluence/display/Hive/DeveloperGuide#DeveloperGuide-HiveSerDe) for more information. REPLACE COLUMNS can also be used to drop columns. For example, "ALTER TABLE test_change REPLACE COLUMNS (a int, b int);" will remove column 'c' from test_change's schema. 

But we try to run replace columns operation for all the file formats which provides inconsistent behavior both from Trino's hive connector and querying hive directly.

**Comment by pojith** [comment]
.take

**Comment by jksimoniii** [comment]
@Praveen2112 @pojith How should we handle `REPLACE COLUMNS` for non-native SerDe? Should an exception be thrown?

**Comment by Praveen2112** [comment]
I think we should mimic Hive's behaviour with respect to various supported formats supported by the Trino

**Comment by timurturbil** [comment]
@Praveen2112 is this bug still exists? If it is, I can work on it.

**Comment by bbreak** [comment]
Looking into this issue now. It seems the Hive docs are out of date, since at least one additional SerDe supports dropping a column. I created a Parquet table, which automatically uses org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe...
```create external table col_del_parq (a int, b int, c int) stored as parquet;```
...then tried dropping one of its columns: 
```alter table col_del_parq replace columns (a int, b int);
INFO  : Compiling command(queryId=hive_20260622224804_07e2351f-0441-463d-beb7-dbd0bed51375): alter table col_del_parq replace columns (a int, b int)
INFO  : Semantic Analysis Completed (retrial = false)
INFO  : Created Hive schema: Schema(fieldSchemas:null, properties:null)
INFO  : Completed compiling command(queryId=hive_20260622224804_07e2351f-0441-463d-beb7-dbd0bed51375); Time taken: 0.025 seconds
INFO  : Executing command(queryId=hive_20260622224804_07e2351f-0441-463d-beb7-dbd0bed51375): alter table col_del_parq replace columns (a int, b int)
INFO  : Starting task [Stage-0:DDL] in serial mode
INFO  : Completed executing command(queryId=hive_20260622224804_07e2351f-0441-463d-beb7-dbd0bed51375); Time taken: 0.085 seconds
INFO  : OK
```

However, trying the same thing with a managed Orc table failed: 
```alter table col_del_orc_mgd replace columns (a int, b int);

INFO  : Compiling command(queryId=hive_20260622224936_6a483929-2f40-4daa-911b-ea47fc9fe4c4): alter table col_del_orc_mgd replace columns (a int, b int)
INFO  : Semantic Analysis Completed (retrial = false)
INFO  : Created Hive schema: Schema(fieldSchemas:null, properties:null)
INFO  : Completed compiling command(queryId=hive_20260622224936_6a483929-2f40-4daa-911b-ea47fc9fe4c4); Time taken: 0.029 seconds
INFO  : Executing command(queryId=hive_20260622224936_6a483929-2f40-4daa-911b-ea47fc9fe4c4): alter table col_del_orc_mgd replace columns (a int, b int)
INFO  : Starting task [Stage-0:DDL] in serial mode
ERROR : Failed
org.apache.hadoop.hive.ql.metadata.HiveException: Replacing columns cannot drop columns for table default.col_del_orc_mgd. SerDe may be incompatible
	at org.apache.hadoop.hive.ql.ddl.table.column.replace.AlterTableReplaceColumnsOperation.doAlteration(AlterTableReplaceColumnsOperation.java:74) ~[hive-exec-3.1.3000.2025.0.21.2-9.jar:3.1.3000.2025.0.21.2-9]
	at org.apache.hadoop.hive.ql.ddl.table.AbstractAlterTableOperation.execute(AbstractAlterTableOperation.java:76) ~[hive-exec-3.1.3000.2025.0.21.2-9.jar:3.1.3000.2025.0.21.2-9]
	at org.apache.hadoop.hive.ql.ddl.DDLTask.execute(DDLTask.java:84) ~[hive-exec-3.1.3000.2025.0.21.2-9.jar:3.1.3000.2025.0.21.2-9]
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:213) ~[hive-exec-3.1.3000.2025.0.21.2-9.jar:3.1.3000.2025.0.21.2-9] [...]
```
So it's definitely an issue with some SerDes. My hunch is that we may need to test the built-in SerDes, allow dropping columns only on the ones that work, and treat all others (including plug-in SerDes) as if dropping columns is unsupported.

The  https://hive.apache.org/community/resources/developerguide/#hive-serde, the built-in SerDes are MetadataTypedColumnsetSerDe, LazySimpleSerDe, ThriftSerDe, DynamicSerDe, JsonSerDe, AvroSerDe, OrcSerde, ParquetHiveSerDe, and OpenCSVSerde. I can test those nine, and I'll also check whether the latest version of Hive has any others.

**Comment by bbreak** [comment]
Found 28 SerDe candidates in the Hive repo. Plan to start testing today.

**Comment by bbreak** [comment]
SerDes that support dropping columns (based on my testing): ColumnarSerDe, LazySimpleSerDe, MetadataTypedColumnsetSerDe, ParquetHiveSerDe.

SerDes that do not support it: AvroSerDe, BinarySortableSerDe, BinarySortableSerDeWithEndPrefix, DelimitedJSONSerDe, JsonSerDe, LazyBinarySerDe, LazyBinarySerDe2, MultiDelimitSerDe, OpenCSVSerde, OrcSerde, ThriftJDBCBinarySerDe.

SerDes that weren't recognized (maybe because they aren't present in the version of Hive I was using, or maybe I got something wrong):  ByteStreamTypedSerDe, LazyBinaryColumnarSerDe, TeradataBinarySerde, ThriftByteStreamTypedSerDe.

As a side note, [HIVE-15984](https://issues.apache.org/jira/browse/HIVE-15984) apparently adds support for ALTER TABLE DROP COLUMN syntax in Hive 4.1, but it doesn't change the requirement for SerDes to support the functionality.

**Comment by bbreak** [comment]
There are a few existing tests that drop columns and default to using the Orc format, such as BaseConnectorTest.testAddAndDropColumnName, which fail after adding this change. I can address these failures by changing the tests to explicitly use Parquet, which seems like a reasonable adjustment. 

However, TestHiveTransactionalTable.testOrcColumnDropAdd explicitly tests dropping a column on an Orc table. It seems the available options for this test are to change it to expect failure, thereby inverting its original intention, or to remove it entirely. @Praveen2112 or @findepi, could you please comment?

**Comment by bbreak** [comment]
Actually, on further consideration, it seems to me that there's no way around causing a test that explicitly tests dropping a column on an Orc table to fail as a result of this change. I'll go ahead and change the expected result on that test.

**Comment by bbreak** [comment]
OK, all tests passed. Squashing into a single commit.

**Comment by zhang-arvin** [comment]
I'd like to work on this. I have extensive experience with Hive DDL semantics and understand the REPLACE COLUMNS behavior. Will submit a PR to add the restriction.
