### ISSUE TITLE
Casting error from VariableWidthBlock to ArrayBlock for array(varchar) column

### ISSUE THREAD

**Issue by nmkarvekar** [trinodb/trino#20889]
Suppose we have field of type array(varchar) , when we try to use that field in where clause in sql query something like this:

select * from mycatalog.default.query where returned_fields=ARRAY['name','address']

we see below error:
**io.trino.spi.block.VariableWidthBlock cannot be cast to class io.trino.spi.block.ArrayBlock (io.trino.spi.block.VariableWidthBlock and io.trino.spi.block.ArrayBlock** 

**here is the stack trace:**
	at io.trino.spi.type.ArrayType.getObject(ArrayType.java:262)
	at pl.net.was.JsonTrinoConverter.convert(JsonTrinoConverter.java:321)
	at pl.net.was.OpenApiClient.serializeMap(OpenApiClient.java:334)
	at pl.net.was.OpenApiClient.getRows(OpenApiClient.java:129)
	at pl.net.was.OpenApiRecordSetProvider.getRecordSet(OpenApiRecordSetProvider.java:75)
	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:263)
	at io.trino.operator.Driver.processInternal(Driver.java:398)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
	at io.trino.operator.Driver.process(Driver.java:293)

**Comment by nineinchnick** [comment]
This was supposed to be reported as https://github.com/nineinchnick/trino-openapi/issues/79
