### ISSUE TITLE
Flaky TestBigQueryAvroConnectorTest.testDelete

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#20894]
```
Error:  io.trino.plugin.bigquery.TestBigQueryAvroConnectorTest.testDelete -- Time elapsed: 35.03 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 
[For query 20240301_002809_01178_mvk2g: 
 DELETE FROM test_delete_yyycch8p1t WHERE custkey <= 500
:] 
expected: 0L
 but was: 1989L
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.trino.testing.QueryAssertions.assertDistributedQuery(QueryAssertions.java:360)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:187)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:160)
2024-02-29T18:44:28.638-0600	INFO	ForkJoinPool-1-worker-1	io.trino.testing.services.junit.LogTestDurationListener	Test TestBigQueryAvroConnectorTest took 43.50m
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:400)
2024-02-29T18:44:28.639-0600	INFO	main	io.trino.testing.services.junit.LogTestDurationListener	Test JUnit Jupiter took 43.50m
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:395)
2024-02-29T18:44:28.645-0600	INFO	main	io.trino.testing.containers.junit.ReportLeakedContainers	DockerClientFactory not initialized, so there should be no leaked containers, skipping the check
	at io.trino.testing.BaseConnectorTest.testDelete(BaseConnectorTest.java:4414)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
https://github.com/trinodb/trino/actions/runs/8104242016/job/22150475692

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/8144814021/job/22259779072

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/8149162364/job/22275630529

**Comment by findepi** [comment]
```
Error:  io.trino.plugin.bigquery.TestBigQueryAvroConnectorTest.testRowLevelDelete -- Time elapsed: 19.02 s <<< FAILURE!
2024-03-18T08:51:45.189-0600	INFO	ForkJoinPool-1-worker-1	io.trino.testing.services.junit.LogTestDurationListener	Test TestBigQueryAvroConnectorTest took 24.24m
org.opentest4j.AssertionFailedError: 
2024-03-18T08:51:45.191-0600	INFO	main	io.trino.testing.services.junit.LogTestDurationListener	Test JUnit Jupiter took 24.25m
2024-03-18T08:51:45.200-0600	INFO	main	io.trino.testing.containers.junit.ReportLeakedContainers	DockerClientFactory not initialized, so there should be no leaked containers, skipping the check
[update count for query 20240318_143943_00950_39sea] 
expected: 1L
 but was: 0L
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.trino.testing.QueryAssertions.assertDistributedUpdate(QueryAssertions.java:144)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:62)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:420)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:415)
	at io.trino.testing.BaseConnectorTest.testRowLevelDelete(BaseConnectorTest.java:4622)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
