### ISSUE TITLE
 BoundedExecutor is in a failed state

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#20899]
I faced below error messages on trion **406** cluster and this cluster are running for a couple of months but faced this issue frequently recently since last week. When can be the root cause for it? is there any way to fix it.
```
2024-03-01T02:41:21.450+0800	ERROR	http-client-scheduler-2064381	com.google.common.util.concurrent.AbstractFuture	RuntimeException while executing runnable CallbackListener{io.trino.server.remotetask.SimpleHttpResponseHandler@45bced42} with executor io.airlift.concurrent.BoundedExecutor@4b515f86
java.util.concurrent.RejectedExecutionException: BoundedExecutor is in a failed state
	at io.airlift.concurrent.BoundedExecutor.execute(BoundedExecutor.java:56)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
	at io.airlift.http.client.jetty.JettyResponseFuture.completed(JettyResponseFuture.java:84)
	at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:90)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:424)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:374)
	at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:597)
	at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1722)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1551)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:208)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:148)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:80)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:172)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by electrum** [comment]
This happens when the JVM cannot create a native thread. This should be treated as a fatal condition. You can use this agent to forcibly kill the JVM when this occurs: https://github.com/airlift/jvmkill

If you run Trino from Docker, this happens automatically using the default `jvm.config` file:
```
-agentpath:/usr/lib/trino/bin/libjvmkill.so
```

**Comment by hashhar** [comment]
In addition to what David said, please check what's the limits for `nproc` (via `ulimits -a`) for the user Trino process runs as. A low limit there means a low limit for native threads which can lead to this situation. See the recommended limits in the docs at https://trino.io/docs/current/installation/deployment.html#linux-operating-system

**Comment by njalan** [comment]
@electrum @hashhar Thanks for your reply. It looks like I forget to config max jvm process.

**Comment by njalan** [comment]
@electrum is there any link to download libjvmkill.so?

**Comment by electrum** [comment]
It is in the Trino Docker image: `/usr/lib/trino/bin/libjvmkill.so`

**Comment by njalan** [comment]
@electrum Thanks a lot
