### ISSUE TITLE
Run sql  but status alway stay starting, Is there any suggestions for  resolving this problem?

### ISSUE THREAD

**Issue by zhuzhengjun01** [trinodb/trino#20915]
Hi Team:
I just fount this problem like this picture 
![image](https://github.com/trinodb/trino/assets/75296820/a0444fb6-cf0d-4873-9f37-23f7911f7919)
this job do not stop and stay starting status, I use trino 433 version  and select hudi cow table.

```[tasklist]
### Tasks
```

**Comment by zhuzhengjun01** [comment]
Here is my stack info 
Query-20240304_082128_00000_uptxk-189" Id=189 TIMED_WAITING on io.airlift.concurrent.ExtendedSettableFuture@52383614
    at java.base@17.0.9/jdk.internal.misc.Unsafe.park(Native Method)
    -  waiting on io.airlift.concurrent.ExtendedSettableFuture@52383614
    at java.base@17.0.9/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
    at app//com.google.common.util.concurrent.OverflowAvoidingLockSupport.parkNanos(OverflowAvoidingLockSupport.java:38)
    at app//com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:456)
    at app//io.airlift.concurrent.MoreFutures.tryGetFutureValue(MoreFutures.java:252)
    at app//io.airlift.concurrent.MoreFutures.tryGetFutureValue(MoreFutures.java:231)
    at app//io.trino.execution.scheduler.PipelinedQueryScheduler$DistributedStagesScheduler.schedule(PipelinedQueryScheduler.java:1305)
    at app//io.trino.execution.scheduler.PipelinedQueryScheduler$$Lambda$2791/0x00007f46997e0400.run(Unknown Source)
    at java.base@17.0.9/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base@17.0.9/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base@17.0.9/java.lang.Thread.run(Thread.java:842)

**Comment by zhuzhengjun01** [comment]
Coordinator says
 ERROR	splits-manager-callback-0	io.airlift.concurrent.BoundedExecutor	Task failed
java.lang.IllegalStateException: Already finished or closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:512)
	at io.trino.split.ConnectorAwareSplitSource.getNextBatch(ConnectorAwareSplitSource.java:72)
	at io.trino.split.TracingSplitSource.getNextBatch(TracingSplitSource.java:63)
	at io.trino.split.BufferingSplitSource$GetNextBatch.fetchSplits(BufferingSplitSource.java:120)
	at io.trino.split.BufferingSplitSource$GetNextBatch$2.onSuccess(BufferingSplitSource.java:159)
	at io.trino.split.BufferingSplitSource$GetNextBatch$2.onSuccess(BufferingSplitSource.java:151)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:79)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)


2024-03-04T08:53:04.669Z	INFO	hudi-split-manager-4	io.trino.plugin.hudi.table.HudiTableFileSystemView	Building file system view for partition ()
2024-03-04T08:55:07.119Z	ERROR	splits-manager-callback-1	io.airlift.concurrent.BoundedExecutor	Task failed
java.lang.IllegalStateException: Already finished or closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:512)
	at io.trino.split.ConnectorAwareSplitSource.getNextBatch(ConnectorAwareSplitSource.java:72)
	at io.trino.split.TracingSplitSource.getNextBatch(TracingSplitSource.java:63)
	at io.trino.split.BufferingSplitSource$GetNextBatch.fetchSplits(BufferingSplitSource.java:120)
	at io.trino.split.BufferingSplitSource$GetNextBatch$2.onSuccess(BufferingSplitSource.java:159)
	at io.trino.split.BufferingSplitSource$GetNextBatch$2.onSuccess(BufferingSplitSource.java:151)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:79)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by zhuzhengjun01** [comment]
There is a hudi bug，Marker file is a 0 size parquet file

**Comment by alberttwong** [comment]
I'm not sure if it's a bug in Hudi.  I would try Trino 418.
