### ISSUE TITLE
Flaky test TestExecutionJmxMetrics.testQueryStats

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#20958]
verified with https://github.com/trinodb/trino/pull/20614, see https://github.com/trinodb/trino/actions/runs/7814434818/job/21315955729?pr=20614

```
Error:  Tests run: 15, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 940.4 s <<< FAILURE! -- in io.trino.execution.TestExecutionJmxMetrics
Error:  io.trino.execution.TestExecutionJmxMetrics.testQueryStats -- Time elapsed: 30.99 s <<< ERROR!
java.util.concurrent.TimeoutException: testQueryStats() timed out after 30 seconds
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1351)
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8551989897/job/23432221388?pr=21244
