### ISSUE TITLE
Flaky TestIndexer.testMutationIndexWithVisibilities in Accumulo connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#20965]
```
Error:  io.trino.plugin.accumulo.index.TestIndexer.testMutationIndexWithVisibilities -- Time elapsed: 5.548 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: "1"
 but was: "2"
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.trino.plugin.accumulo.index.TestIndexer.assertKeyValuePair(TestIndexer.java:336)
	at io.trino.plugin.accumulo.index.TestIndexer.testMutationIndexWithVisibilities(TestIndexer.java:309)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
https://github.com/trinodb/trino/actions/runs/8179694894/job/22366292735?pr=17909

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/actions/runs/9074689092/job/24934230737?pr=21727

```
Error:    TestIndexer.testMutationIndexWithVisibilities:309->assertKeyValuePair:336 
expected: "1"
 but was: "2"
```
