### ISSUE TITLE
Regression: aggregation analysis not yet implemented for io.trino.sql.tree.CurrentTimestamp

### ISSUE THREAD

**Issue by guyco33** [trinodb/trino#21005]
In version `440`:
```
WITH ds AS (SELECT * FROM (VALUES (1),(2)) AS t(c))
SELECT max(c), current_timestamp 
FROM ds
```

fails with `INTERNAL_ERROR`
```
java.lang.UnsupportedOperationException: aggregation analysis not yet implemented for: io.trino.sql.tree.CurrentTimestamp
	at io.trino.sql.analyzer.AggregationAnalyzer$Visitor.visitExpression(AggregationAnalyzer.java:222)
	at io.trino.sql.analyzer.AggregationAnalyzer$Visitor.visitExpression(AggregationAnalyzer.java:216)
	at io.trino.sql.tree.AstVisitor.visitCurrentTimestamp(AstVisitor.java:52)
	at io.trino.sql.tree.CurrentTimestamp.accept(CurrentTimestamp.java:55)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.AggregationAnalyzer$Visitor.process(AggregationAnalyzer.java:784)
	at io.trino.sql.analyzer.AggregationAnalyzer.analyze(AggregationAnalyzer.java:208)
	at io.trino.sql.analyzer.AggregationAnalyzer.verifySourceAggregations(AggregationAnalyzer.java:141)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeAggregations(StatementAnalyzer.java:4935)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:3154)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:523)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:542)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:550)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1566)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:523)
	at io.trino.sql.tree.Query.accept(Query.java:118)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:542)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:502)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:491)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:97)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:274)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:209)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:850)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)
	at io.trino.$gen.Trino_440____20240311_064701_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

While the following succeed:
```
WITH ds AS (SELECT * FROM (VALUES (1),(2)) AS t(c))
SELECT max(c),  now() 
FROM ds
```

Both queries succeed in `439`

**Comment by wendigo** [comment]
Cc @martint for recent ir/ast changes

**Comment by guyco33** [comment]
Same error for `current_date` but it works for `current_time`
