### ISSUE TITLE
Flaky test TestCassandraTypeMapping.testDate 

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#21032]
https://github.com/trinodb/trino/actions/runs/8248151215/job/22558012491?pr=21031

```
Error:  io.trino.plugin.cassandra.TestCassandraTypeMapping.testDate -- Time elapsed: 29.31 s <<< ERROR!
java.lang.RuntimeException: 
Error executing sql:
CREATE TABLE test_datej4w70xtb7a AS SELECT CAST(NULL AS date) col_0,
CAST(DATE '-5877641-06-23' AS date) col_1,
CAST(DATE '0001-01-01' AS date) col_2,
CAST(DATE '1582-10-04' AS date) col_3,
CAST(DATE '1582-10-05' AS date) col_4,
CAST(DATE '1582-10-14' AS date) col_5,
CAST(DATE '1952-04-03' AS date) col_6,
CAST(DATE '1970-01-01' AS date) col_7,
CAST(DATE '1970-02-03' AS date) col_8,
CAST(DATE '1983-04-01' AS date) col_9,
CAST(DATE '1983-10-01' AS date) col_10,
CAST(DATE '2017-07-01' AS date) col_11,
CAST(DATE '2017-01-01' AS date) col_12,
CAST(DATE '5881580-07-11' AS date) col_13
	at io.trino.testing.sql.TrinoSqlExecutor.execute(TrinoSqlExecutor.java:45)
	at io.trino.testing.sql.TestTable.createAndInsert(TestTable.java:51)
	at io.trino.testing.sql.TestTable.<init>(TestTable.java:46)
	at io.trino.testing.sql.TestTable.<init>(TestTable.java:38)
	at io.trino.testing.datatype.CreateAsSelectDataSetup.setupTemporaryRelation(CreateAsSelectDataSetup.java:46)
	at io.trino.testing.datatype.CreateAsSelectDataSetup.setupTemporaryRelation(CreateAsSelectDataSetup.java:25)
	at io.trino.testing.datatype.SqlDataTypeTest.execute(SqlDataTypeTest.java:89)
	at io.trino.plugin.cassandra.TestCassandraTypeMapping.testDate(TestCassandraTypeMapping.java:490)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: io.trino.testing.QueryFailedException: Query timed out after PT12S
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
	at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:[501](https://github.com/trinodb/trino/actions/runs/8248151215/job/22558012491?pr=21031#step:5:502))
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:484)
	at io.trino.testing.sql.TrinoSqlExecutor.execute(TrinoSqlExecutor.java:42)
2024-03-12T05:52:17.173-0600	INFO	ForkJoinPool-1-worker-9	io.trino.testing.services.junit.LogTestDurationListener	Test TestCassandraTypeMapping took 3.10m
	... 14 more
	Suppressed: java.lang.Exception: SQL: CREATE TABLE test_datej4w70xtb7a AS SELECT CAST(NULL AS date) col_0,
CAST(DATE '-5877641-06-23' AS date) col_1,
CAST(DATE '0001-01-01' AS date) col_2,
CAST(DATE '1582-10-04' AS date) col_3,
CAST(DATE '1582-10-05' AS date) col_4,
CAST(DATE '1582-10-14' AS date) col_5,
CAST(DATE '1952-04-03' AS date) col_6,
CAST(DATE '1970-01-01' AS date) col_7,
CAST(DATE '1970-02-03' AS date) col_8,
CAST(DATE '1983-04-01' AS date) col_9,
CAST(DATE '1983-10-01' AS date) col_10,
CAST(DATE '2017-07-01' AS date) col_11,
CAST(DATE '2017-01-01' AS date) col_12,
CAST(DATE '5881580-07-11' AS date) col_13
		at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:[508](https://github.com/trinodb/trino/actions/runs/8248151215/job/22558012491?pr=21031#step:5:509))
		... 16 more
Caused by: com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT12S
```

**Comment by findinpath** [comment]
We can potentially set `cassandra.client.read-timeout` to a value greater than 12 seconds if this flake happens more often.

**Comment by findepi** [comment]
IMO this flake happens frequent enough to do _something_ about it.
whether adding read timeout is the right thing, or whether this helps at all -- i have no opinion

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/10948394262/job/30399451678
