### ISSUE TITLE
Content-Type header is not set: JettyResponse{statusCode=200, headers={Connection=[close], Vary=[Accept-Encoding, User-Agent], Date=[Wed, 28 Feb 2024 22:20:01 GMT]}}

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#21066]
Trino version is 397:
Error processing Split 20240228_221855_02165_wf5x6.12.1.0-33  (start = 3.339727810780704E10, wall = 62188 ms, cpu = 2909 ms, wait = 11547 ms, calls = 2668): PAGE_TRANSPORT_ERROR: Error fetching http://xxx:8084/v1/task/20240228_221855_02165_wf5x6.13.3.0/results/1/2003: Content-Type header is not set: JettyResponse{statusCode=200, headers={Connection=[close], Vary=[Accept-Encoding, User-Agent], Date=[Wed, 28 Feb 2024 22:20:01 GMT]}}
io.trino.operator.PageTransportErrorException: Error fetching http://xxx:8084/v1/task/20240228_221855_02165_wf5x6.13.3.0/results/1/2003: Content-Type header is not set: JettyResponse{statusCode=200, headers={Connection=[close], Vary=[Accept-Encoding, User-Agent], Date=[Wed, 28 Feb 2024 22:20:01 GMT]}}
        at io.trino.operator.HttpPageBufferClient$PageResponseHandler.handle(HttpPageBufferClient.java:703)
        at io.trino.operator.HttpPageBufferClient$PageResponseHandler.handle(HttpPageBufferClient.java:619)
        at io.airlift.http.client.jetty.JettyResponseFuture.processResponse(JettyResponseFuture.java:99)
        at io.airlift.http.client.jetty.JettyResponseFuture.completed(JettyResponseFuture.java:76)
        at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:90)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
        at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481)
        at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461)
        at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:424)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:365)
        at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:597)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1603)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:259)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:181)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:79)
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:172)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.trino.operator.PageTransportErrorException: Content-Type header is not set: JettyResponse{statusCode=200, headers={Connection=[close], Vary=[Accept-Encoding, User-Agent], Date=[Wed, 28 Feb 2024 22:20:01 GMT]}}
        at io.trino.operator.HttpPageBufferClient$PageResponseHandler.handle(HttpPageBufferClient.java:674)

**Comment by ebyhr** [comment]
Let me close this issue because the version 397 is too old. Please feel free to reopen if the issue still occurs in the latest version.
