### ISSUE TITLE
unable to read symbol link table:Unsupported input format: serde=xxx.OpenCSVSerde, format=xxx.SymlinkTextInputFormat

### ISSUE THREAD

**Issue by ubyyj** [trinodb/trino#21072]
We are getting the below error while reading a symbol link hive table, where s3 inventory data is stored. The table can be read by Trino 407 without issue, but fails for Trino 435.

Below is the error:
```
io.trino.spi.TrinoException: Unsupported input format: serde=org.apache.hadoop.hive.serde2.OpenCSVSerde, format=org.apache.hadoop.hive.ql.io.SymlinkTextInputFormat, partition=dt=2024-03-13-01-00, path=s3://<mybucket>/data/f6e5d774-503b-4380-849a-05a90285dfca.csv.gz
  at io.trino.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:160)
  at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:48)
  at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
  at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:259)
  at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:190)
  at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:359)
```

Below is the hive table DDL
```
CREATE EXTERNAL TABLE `cost.mytable`(
  `bucket` string COMMENT 'from deserializer', 
  `key` string COMMENT 'from deserializer', 
  `version_id` string COMMENT 'from deserializer', 
  `is_latest` string COMMENT 'from deserializer', 
  `is_delete_marker` string COMMENT 'from deserializer', 
  `size` string COMMENT 'from deserializer', 
  `last_modified_date` string COMMENT 'from deserializer', 
  `storage_class` string COMMENT 'from deserializer', 
  `replication_status` string COMMENT 'from deserializer')
PARTITIONED BY ( 
  `dt` string)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.SymlinkTextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://<mybucket>/hive'
```

**Comment by wendigo** [comment]
Cc @dain
