### ISSUE TITLE
Partial aggregation over long decimals fails if pushed below join

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#21099]
```
Query failed: class io.trino.spi.block.DictionaryBlock cannot be cast to class io.trino.spi.block.VariableWidthBlock

Caused by: java.lang.ClassCastException: class io.trino.spi.block.DictionaryBlock cannot be cast to class io.trino.spi.block.VariableWidthBlock (io.trino.spi.block.DictionaryBlock and io.trino.spi.block.VariableWidthBlock are in unnamed module of loader 'app')
 	at io.trino.operator.aggregation.state.LongDecimalWithOverflowStateSerializer.deserialize(LongDecimalWithOverflowStateSerializer.java:67)
 	at io.trino.operator.aggregation.state.LongDecimalWithOverflowStateSerializer.deserialize(LongDecimalWithOverflowStateSerializer.java:26)
 	at io.trino.$gen.sumGroupedAccumulator_20240313_131249_42.addIntermediate(Unknown Source)
 	at io.trino.operator.aggregation.GroupedAggregator.processPage(GroupedAggregator.java:93)
 	at io.trino.operator.aggregation.builder.InMemoryHashAggregationBuilder.lambda$processPage$1(InMemoryHashAggregationBuilder.java:157)
 	at io.trino.operator.TransformWork.process(TransformWork.java:44)
 	at io.trino.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:443)
 	at io.trino.operator.Driver.processInternal(Driver.java:400)
```

**Comment by findepi** [comment]
this is apparently a regression in 440 (https://github.com/trinodb/trino/pull/19816)

can be reproduced 

```java
Session session = Session.builder(assertions.getDefaultSession())
        .setSystemProperty(PUSH_PARTIAL_AGGREGATION_THROUGH_JOIN, "true")
        .build();
assertThat(assertions.query(session, """
        SELECT l.i, sum(v)
        FROM (VALUES 1, 2, 2, 3, 3, 3) l(i)
        JOIN (VALUES
            (1, DECIMAL '12345678901234567890.1234567890'),
            (1, DECIMAL '11111111111111111111.1234567890'),
            (2, DECIMAL '22222222222222222222.1234567890'),
            (3, DECIMAL '33333333333333333333.1234567890'),
            (7, DECIMAL '77777777777777777777.1234567890')) r(i, v) ON l.i = r.i
        GROUP BY l.i
        """))
        .matches("""
                VALUES
                    (1, CAST(DECIMAL '23456790012345679001.2469135780' AS decimal(38, 10))),
                    (2, CAST(DECIMAL '44444444444444444444.2469135780' AS decimal(38, 10))),
                    (3, CAST(DECIMAL '99999999999999999999.3703703670' AS decimal(38, 10)))
                """);
```
