### ISSUE TITLE
Hive tables' columns listing may fail when a table dropped concurrently

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#21109]
https://github.com/trinodb/trino/actions/runs/8301157452/job/22720729910?pr=21107

```
Error:  Tests run: 50, Failures: 0, Errors: 1, Skipped: 11, Time elapsed: 11.74 s <<< FAILURE! -- in io.trino.plugin.hive.metastore.thrift.TestHiveMetastoreAccessOperations
Error:  io.trino.plugin.hive.TestHiveConnectorTest.testView -- Time elapsed: 19.57 s <<< ERROR!
io.trino.testing.QueryFailedException: Error listing table columns for catalog hive_bucketed: Table 'tpch.test_add_col_9t75m4jt9n' not found
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
	at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:501)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:484)
	at io.trino.sql.query.QueryAssertions$QueryAssert.lambda$new$1(QueryAssertions.java:314)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
	at io.trino.sql.query.QueryAssertions$QueryAssert.result(QueryAssertions.java:433)
	at io.trino.sql.query.QueryAssertions$QueryAssert.containsAll(QueryAssertions.java:379)
	at io.trino.testing.BaseConnectorTest.testView(BaseConnectorTest.java:964)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
	at io.trino.operator.Driver.process(Driver.java:293)
	at io.trino.operator.Driver.processForDuration(Driver.java:264)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:76)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:191)
	at io.trino.$gen.Trino_testversion____20240315_191532_14856.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:192)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:174)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:161)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.trino.spi.connector.TableNotFoundException: Table 'tpch.test_add_col_9t75m4jt9n' not found
	at io.trino.plugin.hive.metastore.file.FileHiveMetastore.lambda$getRequiredTable$5(FileHiveMetastore.java:480)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.trino.plugin.hive.metastore.file.FileHiveMetastore.getRequiredTable(FileHiveMetastore.java:480)
	at io.trino.plugin.hive.metastore.file.FileHiveMetastore.listTablePrivileges(FileHiveMetastore.java:1205)
	at io.trino.plugin.hive.metastore.tracing.TracingHiveMetastore.lambda$listTablePrivileges$45(TracingHiveMetastore.java:553)
	at io.trino.plugin.hive.metastore.tracing.Tracing.withTracing(Tracing.java:39)
	at io.trino.plugin.hive.metastore.tracing.TracingHiveMetastore.listTablePrivileges(TracingHiveMetastore.java:553)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadTablePrivileges(CachingHiveMetastore.java:1127)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.lambda$new$4(CachingHiveMetastore.java:215)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at io.trino.cache.EmptyCache.lambda$get$0(EmptyCache.java:58)
	at io.trino.cache.EmptyCache.get(EmptyCache.java:94)
	at io.trino.cache.EmptyCache.get(EmptyCache.java:58)
	at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:53)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:274)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.listTablePrivileges(CachingHiveMetastore.java:1064)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadTablePrivileges(CachingHiveMetastore.java:1127)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.lambda$new$4(CachingHiveMetastore.java:215)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:447)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:433)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3589)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2328)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2187)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2081)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4036)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4059)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5041)
	at io.trino.cache.EvictableCache.get(EvictableCache.java:145)
	at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:53)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:274)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.listTablePrivileges(CachingHiveMetastore.java:1064)
	at io.trino.plugin.hive.HiveMetastoreClosure.listTablePrivileges(HiveMetastoreClosure.java:328)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.listTablePrivileges(SemiTransactionalHiveMetastore.java:1218)
	at io.trino.plugin.hive.security.SemiTransactionalSqlStandardAccessControlMetastore.listTablePrivileges(SemiTransactionalSqlStandardAccessControlMetastore.java:52)
	at io.trino.plugin.hive.security.SqlStandardAccessControl.hasAnyTablePermission(SqlStandardAccessControl.java:777)
	at io.trino.plugin.hive.security.SqlStandardAccessControl.filterColumns(SqlStandardAccessControl.java:275)
	at io.trino.plugin.hive.security.SqlStandardAccessControl.lambda$filterColumns$0(SqlStandardAccessControl.java:270)
	at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$7(CollectCollectors.java:196)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.plugin.hive.security.SqlStandardAccessControl.filterColumns(SqlStandardAccessControl.java:268)
	at io.trino.plugin.hive.security.SystemTableAwareAccessControl.filterColumns(SystemTableAwareAccessControl.java:91)
	at io.trino.plugin.hive.security.SystemTableAwareAccessControl.lambda$filterColumns$0(SystemTableAwareAccessControl.java:81)
	at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$7(CollectCollectors.java:196)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.plugin.hive.security.SystemTableAwareAccessControl.filterColumns(SystemTableAwareAccessControl.java:78)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorAccessControl.filterColumns(ClassLoaderSafeConnectorAccessControl.java:196)
	at io.trino.security.AccessControlManager.filterColumns(AccessControlManager.java:672)
	at io.trino.testing.TestingAccessControlManager.filterColumns(TestingAccessControlManager.java:651)
	at io.trino.tracing.TracingAccessControl.filterColumns(TracingAccessControl.java:330)
	at io.trino.metadata.MetadataListing.doListTableColumns(MetadataListing.java:286)
	at io.trino.metadata.MetadataListing.listTableColumns(MetadataListing.java:251)
	... 27 more

```

**Comment by findepi** [comment]
direct cause probably concurrent test execution: https://github.com/trinodb/trino/pull/20937

but the problem is real production problem

**Comment by findepi** [comment]
@ebyhr can you PTAL?

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/21110 should fix this
