### ISSUE TITLE
Flaky test TestDeltaLakeAlluxioCacheMinioAndHmsConnectorSmokeTest.testCreateOrReplaceTableConcurrently: `Read -1 bytes from cache`

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#21112]
```
Error:  Tests run: 160, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 465.9 s <<< FAILURE! -- in io.trino.plugin.deltalake.TestDeltaLakeMinioAndHmsConnectorSmokeTest
Error:  io.trino.plugin.deltalake.TestDeltaLakeAlluxioCacheMinioAndHmsConnectorSmokeTest.testCreateOrReplaceTableConcurrently -- Time elapsed: 1.184 s <<< ERROR!
com.google.common.util.concurrent.ExecutionError: java.lang.AssertionError: Unexpected concurrent CREATE OR REPLACE failure
	at com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1385)
	at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1378)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testCreateOrReplaceTableConcurrently(BaseDeltaLakeConnectorSmokeTest.java:2391)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.AssertTimeoutPreemptively.lambda$submitTask$3(AssertTimeoutPreemptively.java:95)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.AssertionError: Unexpected concurrent CREATE OR REPLACE failure
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.lambda$testCreateOrReplaceTableConcurrently$12(BaseDeltaLakeConnectorSmokeTest.java:2379)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.lambda$testCreateOrReplaceTableConcurrently$13(BaseDeltaLakeConnectorSmokeTest.java:2366)
	... 4 more
	Suppressed: io.trino.testing.QueryFailedException: Error opening Hive split s3://test-delta-lake-integration-smoke-test-jcfjpjo25b/smoke_test/test_create_or_replace4mjyhqtso5-27faf01e8f814586907ba5225752d203/20240315_195711_00553_kjqaa_4ecef611-dbe4-458d-b9b5-45a0a9a40b8b (offset=0, length=201): Read -1 bytes from cache
		at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
		at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:503)
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:488)
		at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:314)
		at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:309)
		at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.lambda$testCreateOrReplaceTableConcurrently$12(BaseDeltaLakeConnectorSmokeTest.java:2368)
		... 7 more
		Suppressed: java.lang.Exception: SQL: SELECT * FROM test_create_or_replace4mjyhqtso5
			at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:506)
			... 11 more
	Caused by: io.trino.spi.TrinoException: Error opening Hive split s3://test-delta-lake-integration-smoke-test-jcfjpjo25b/smoke_test/test_create_or_replace4mjyhqtso5-27faf01e8f814586907ba5225752d203/20240315_195711_00553_kjqaa_4ecef611-dbe4-458d-b9b5-45a0a9a40b8b (offset=0, length=201): Read -1 bytes from cache
		at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:304)
		at io.trino.plugin.deltalake.DeltaLakePageSourceProvider.createPageSource(DeltaLakePageSourceProvider.java:238)
		at io.trino.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:46)
		at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:100)
		at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:65)
		at io.trino.split.TableAwarePageSourceProvider.lambda$createPageSource$1(TableAwarePageSourceProvider.java:81)
		at java.base/java.util.Optional.orElseGet(Optional.java:364)
		at io.trino.split.TableAwarePageSourceProvider.createPageSource(TableAwarePageSourceProvider.java:81)
		at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:288)
		at io.trino.operator.Driver.processInternal(Driver.java:395)
		at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
		at io.trino.operator.Driver.tryWithLock(Driver.java:701)
		at io.trino.operator.Driver.process(Driver.java:290)
		at io.trino.operator.Driver.processForDuration(Driver.java:261)
		at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
		at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
		at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
		at io.trino.$gen.Trino_testversion____20240315_195554_4460.run(Unknown Source)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
		at java.base/java.lang.Thread.run(Thread.java:1583)
	Caused by: java.io.IOException: Read -1 bytes from cache
		at io.trino.filesystem.alluxio.AlluxioInputHelper.doInternalCacheRead(AlluxioInputHelper.java:120)
		at io.trino.filesystem.alluxio.AlluxioInputHelper.lambda$doCacheRead$0(AlluxioInputHelper.java:89)
		at io.trino.filesystem.alluxio.AlluxioTracing.withTracing(AlluxioTracing.java:29)
		at io.trino.filesystem.alluxio.AlluxioInputHelper.doCacheRead(AlluxioInputHelper.java:87)
		at io.trino.filesystem.alluxio.AlluxioInput.readFully(AlluxioInput.java:79)
		at io.trino.filesystem.alluxio.AlluxioInput.readTail(AlluxioInput.java:128)
		at io.trino.filesystem.TrinoInput.readTail(TrinoInput.java:43)
		at io.trino.filesystem.tracing.TracingInput.lambda$readTail$3(TracingInput.java:81)
		at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
		at io.trino.filesystem.tracing.TracingInput.readTail(TracingInput.java:81)
		at io.trino.plugin.hive.parquet.MemoryParquetDataSource.<init>(MemoryParquetDataSource.java:56)
		at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createDataSource(ParquetPageSourceFactory.java:319)
		at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:222)
		... 20 more
Caused by: [CIRCULAR REFERENCE: io.trino.spi.TrinoException: Error opening Hive split s3://test-delta-lake-integration-smoke-test-jcfjpjo25b/smoke_test/test_create_or_replace4mjyhqtso5-27faf01e8f814586907ba5225752d203/20240315_195711_00553_kjqaa_4ecef611-dbe4-458d-b9b5-45a0a9a40b8b (offset=0, length=201): Read -1 bytes from cache]

```

**Comment by findepi** [comment]
cc @jkylling @Pluies

**Comment by findepi** [comment]
my bad. this happened internally and currently cannot happen in Trino.
 i will close the issue, as containing no actionable repro steps
i do believe the stacktrace is caused by a real existing problem with the Alluxio intergration, so someone still may want to take a look into this

**Comment by jkylling** [comment]
We might have seen similar issues. Are there any errors or warnings from Alluxio preceding this which mentions something about inconsistent metdata state? How large is your cache? Are you able to share the test used?
