### ISSUE TITLE
Flaky TestHiveRuntimeAdaptivePartitioningFaultTolerantExecutionJoinQueries.testJoinWithMultipleInSubqueryClauses

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#21153]
https://github.com/trinodb/trino/actions/runs/8334770270/job/22809046684

```
io.trino.faulttolerant.hive.TestHiveRuntimeAdaptivePartitioningFaultTolerantExecutionJoinQueries.testJoinWithMultipleInSubqueryClauses -- Time elapsed: 3.943 s <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query 20240318_230920_00279_sumez failed: SELECT * FROM (VALUES 1,2,3,4) t(x) right JOIN (VALUES 1,2,3,5) t2(y) ON (x in (VALUES 1,2,3)) = (y in (VALUES 1,2,3)) AND (x in (VALUES 1,2,4)) = (y in (VALUES 1,2,4))
	at io.trino.testing.QueryAssertions.assertDistributedQuery(QueryAssertions.java:299)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:187)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:160)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:350)
	at io.trino.testing.AbstractTestJoinQueries.testJoinWithMultipleInSubqueryClauses(AbstractTestJoinQueries.java:854)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: io.trino.testing.QueryFailedException: Number of stages in the query (152) exceeds the allowed maximum (150). If the query contains multiple aggregates with DISTINCT over different columns, please set the 'mark_distinct_strategy' session property to 'none'. If the query contains WITH clauses that are referenced more than once, please create temporary table(s) for the queries in those clauses.
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
	at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:501)
	at io.trino.testing.DistributedQueryRunner.executeWithPlan(DistributedQueryRunner.java:490)
	at io.trino.testing.QueryAssertions.assertDistributedQuery(QueryAssertions.java:290)
	... 11 more
	Suppressed: java.lang.Exception: SQL: SELECT * FROM (VALUES 1,2,3,4) t(x) right JOIN (VALUES 1,2,3,5) t2(y) ON (x in (VALUES 1,2,3)) = (y in (VALUES 1,2,3)) AND (x in (VALUES 1,2,4)) = (y in (VALUES 1,2,4))
		at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:508)
		... 13 more
```

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/actions/runs/8489328059/job/23259301903?pr=21330

```
Error:  io.trino.faulttolerant.hive.TestHiveRuntimeAdaptivePartitioningFaultTolerantExecutionJoinQueries.testSemiJoin -- Time elapsed: 14.14 s <<< FAILURE!
java.lang.AssertionError: 
Execution of 'actual' query 20240330_075443_00062_udb2m failed: SELECT *, o2.custkey
  IN (
    SELECT orderkey
    FROM lineitem
    WHERE orderkey % 5 = 0)
FROM (SELECT * FROM orders WHERE custkey % 256 = 0) o1
JOIN (SELECT * FROM orders WHERE custkey % 256 = 0) o2
  ON (o1.orderkey IN (SELECT orderkey FROM lineitem WHERE orderkey % 4 = 0)) = (o2.orderkey IN (SELECT orderkey FROM lineitem WHERE orderkey % 4 = 0))
WHERE o1.orderkey
  IN (
    SELECT orderkey
    FROM lineitem
    WHERE orderkey % 4 = 0)
ORDER BY o1.orderkey
  IN (
    SELECT orderkey
    FROM lineitem
    WHERE orderkey % 7 = 0)
	at io.trino.testing.QueryAssertions.assertDistributedQuery(QueryAssertions.java:299)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:187)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:160)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:345)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:340)
	at io.trino.testing.AbstractTestJoinQueries.testSemiJoin(AbstractTestJoinQueries.java:1[763](https://github.com/trinodb/trino/actions/runs/8489328059/job/23259301903?pr=21330#step:5:764))
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1534)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2269)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:495)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:662)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: io.trino.testing.QueryFailedException: Number of stages in the query (152) exceeds the allowed maximum (150). If the query contains multiple aggregates with DISTINCT over different columns, please set the 'mark_distinct_strategy' session property to 'none'. If the query contains WITH clauses that are referenced more than once, please create temporary table(s) for the queries in those clauses.
```

cc @losipiuk @dekimir

**Comment by losipiuk** [comment]
Should be fixed with https://github.com/trinodb/trino/pull/21318.

@gaurav8297 plase confirm and close
