### ISSUE TITLE
Iceberg optimizer timeout

### ISSUE THREAD

**Issue by vinay1331** [trinodb/trino#21154]
when querying the iceberg with glue catalog a simple query like select * from table customer_order where item_id in (1,2,3)
If values in the in grows to some thousand (tested with 20K values ids) the query fails in planning. The planning time in trino 438 for same query is 15 sec. But after 438 it fails to execute  

select lead_id,
                value as i1_verdict 
                from 
                   test 
                    where type='dummy' 
                    and date(created_time) >=date(last_day_of_month(current_date - interval '2' day - interval '2' month) + interval '1' day)
                    and value is not null
                    and lead_id in ({list with 20K values})

io.trino.spi.TrinoException: The optimizer exhausted the time limit of 180000 ms: Top rules: {
		io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan: 258699 ms, 2 invocations, 1 applications,
		io.trino.sql.planner.iterative.rule.PruneTableScanColumns: 0 ms, 1 invocations, 0 applications }
	at io.trino.sql.planner.iterative.IterativeOptimizer$Context.checkTimeoutNotExhausted(IterativeOptimizer.java:391)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:168)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:144)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:266)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:146)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:266)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:146)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:266)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:146)
	at io.trino.sql.planner.iterative.IterativeOptimizer.optimizeAndMarkPlanChanges(IterativeOptimizer.java:129)
	at io.trino.sql.planner.optimizations.AdaptivePlanOptimizer.optimize(AdaptivePlanOptimizer.java:33)
	at io.trino.sql.planner.LogicalPlanner.runOptimizer(LogicalPlanner.java:308)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:269)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:240)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:235)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:498)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:477)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:415)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:264)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1135)
	at io.trino.$gen.Trino_442____20240318_092557_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by martint** [comment]
This should be fixed in master (to be released in 443). Are you able to build the latest snapshot and try it to see if it works for you now?

**Comment by findinpath** [comment]
Tried with `440` the following scenario:

```
trino> create table iceberg.default.t1(id integer, data varchar);
CREATE TABLE
trino> select * from iceberg.default.t1;
 id | data 
----+------
(0 rows)

trino> use iceberg.default;
USE
trino:default> insert into t1 values (1, 'A');
INSERT: 1 row

trino:default> insert into t1 values (2, 'B');
INSERT: 1 row

-- trying with a filter having 2K values
trino:default: select * from t1 where id in (1, 2, ...., 2000);

Query 20240320_115100_00007_d5q3m, FINISHED, 1 node
http://localhost:8080/ui/query.html?20240320_115100_00007_d5q3m
Splits: 2 total, 2 done (100.00%)
CPU Time: 0.0s total,    47 rows/s, 14.5KB/s, 18% active
Per Node: 0.0 parallelism,     1 rows/s,   314B/s
Parallelism: 0.0
Peak Memory: 320B
1.99 [2 rows, 624B] [1 rows/s, 314B/s]

-- trying with a filter having 20K values
trino:default: select * from t1 where id in (1, 2, ...., 20000);
 id | data 
----+------
  2 | B    
  1 | A    
(2 rows)

Query 20240320_115145_00008_d5q3m, FINISHED, 1 node
http://localhost:8080/ui/query.html?20240320_115145_00008_d5q3m
Splits: 2 total, 2 done (100.00%)
CPU Time: 0.0s total,   105 rows/s, 32.1KB/s, 12% active
Per Node: 0.0 parallelism,     0 rows/s,     5B/s
Parallelism: 0.0
Peak Memory: 320B
2:07 [2 rows, 624B] [0 rows/s, 5B/s]
```

**Comment by vinay1331** [comment]
Thanks @findinpath @martint
