### ISSUE TITLE
Connect failed to ElasticSearch 7.1.1

### ISSUE THREAD

**Issue by rickw1028** [trinodb/trino#2120]
Presto version , 325
ES version: 7.1.1 ( no security config)

elasticsearch.properties 
```
connector.name=elasticsearch
elasticsearch.host=hadoop1.xxxx.org
elasticsearch.port=9200
elasticsearch.default-schema-name=default
```

When i try to load table list in Presto ( i am using DBeaver , it can connect to Presto successfully)
presto throw exceptions as below . ES has 3 nodes , hadoop1/hadoop2/hadoop3.xxxx.org, all work.

Can anyone help ?

```
io.prestosql.spi.PrestoException: hadoop3.xxxx.org/10.16.130.43: Name or service not known
	at io.prestosql.elasticsearch.client.ElasticsearchClient.doRequest(ElasticsearchClient.java:560)
	at io.prestosql.elasticsearch.client.ElasticsearchClient.getIndexes(ElasticsearchClient.java:399)
	at io.prestosql.elasticsearch.ElasticsearchMetadata.listTables(ElasticsearchMetadata.java:190)
	at io.prestosql.metadata.MetadataManager.listTables(MetadataManager.java:516)
	at io.prestosql.metadata.MetadataListing.listTables(MetadataListing.java:64)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.addTablesRecords(InformationSchemaPageSource.java:266)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:208)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:171)
	at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:286)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_325____20191127_093245_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: hadoop3.xxxx.org/10.16.130.43: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:609)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:580)
	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:427)
	at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:276)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:266)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:363)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:125)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:344)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:326)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:219)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:192)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:154)
	at io.prestosql.elasticsearch.client.ElasticsearchClient.doRequest(ElasticsearchClient.java:557)
	... 19 more
```

**Comment by findepi** [comment]
Can you verify whether adding `-Djava.net.preferIPv4Stack=true` to Presto `jvm.config` changes anything?

**Comment by rickw1028** [comment]
> Can you verify whether adding `-Djava.net.preferIPv4Stack=true` to Presto `jvm.config` changes anything?

Hi @findepi  , Thanks for you reply , i tried add -Djava.net.preferIPv4Stack=true , but this is not work . same exception. 

jvm.config
```
-server
-Xmx16G
-XX:-UseBiasedLocking
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+ExitOnOutOfMemoryError
-XX:+UseGCOverheadLimit
-XX:+HeapDumpOnOutOfMemoryError
-XX:ReservedCodeCacheSize=512M
-Djdk.nio.maxCachedBufferSize=2000000
-Djava.net.preferIPv4Stack=true
```

**Comment by erhlee-bird** [comment]
ElasticSearch 7.x changed behavior such that the publish_host now returns "{hostname}/{ipaddr}:{port}"

- https://github.com/elastic/elasticsearch/pull/45626/files

How it is addressed in other language clients.

- https://github.com/elastic/go-elasticsearch/blob/master/estransport/discovery.go#L170
- https://github.com/elastic/elasticsearch-py/pull/1039/files

Possible patch looking at the other clients.

```
diff --git a/presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/NodesResponse.java b/presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/NodesResponse.java
index b7896e62cd..62a81b09b9 100644
--- a/presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/NodesResponse.java
+++ b/presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/NodesResponse.java
@@ -73,7 +73,17 @@ public class NodesResponse
         @JsonCreator
         public Http(@JsonProperty("publish_address") String address)
         {
-            this.address = address;
+            // ES 7.x supports publish_address in ip:port or hostname/ip:port
+            // format.
+            boolean isSlashFound = address.indexOf("/") != 1 ? true : false;
+            if (isSlashFound) {
+                String[] strParts = address.split("/", 2);
+                String[] ipParts = strParts[1].split(":", 2);
+                String newStr = String.join(":", strParts[0], ipParts[1]);
+                this.address = newStr;
+            } else {
+                this.address = address;
+            }
         }
 
         public String getAddress()
```

**Comment by Praveen2112** [comment]
Can I take up this issue ?

**Comment by rickw1028** [comment]
After change the elasticsearch http.host as below , issue fixed. 

`# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 0.0.0.0
`

**Comment by hashhar** [comment]
Closing since @rickw1028 confirmed it was fixed.

**Comment by sundarexp** [comment]
@rickw1028 kindly let me know what have you did to fix, which file need to be changed, is it elasticsearch connector file?
I'm using aws es service , im getting the same error you are getting. 
thanks
