### ISSUE TITLE
Resource groups failure when processing group usage: negative CPU millis duration

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#21254]
observed on CI https://github.com/trinodb/trino/actions/runs/8428261972/job/23080714614?pr=21244

```
Error:  Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 20.57 s <<< FAILURE! -- in io.trino.tests.TestMetadataManager
Error:  io.trino.execution.resourcegroups.TestResourceGroupIntegration.testPathToRoot -- Time elapsed: 17.34 s <<< ERROR!
java.lang.IllegalArgumentException: value is negative: -1.0
	at io.airlift.units.Duration.<init>(Duration.java:79)
	at io.airlift.units.Duration.succinctDuration(Duration.java:66)
	at io.trino.execution.resourcegroups.InternalResourceGroup.getInfo(InternalResourceGroup.java:196)
	at io.trino.execution.resourcegroups.InternalResourceGroup.getPathToRoot(InternalResourceGroup.java:266)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.trino.execution.resourcegroups.InternalResourceGroupManager.tryGetPathToRoot(InternalResourceGroupManager.java:106)
	at io.trino.execution.resourcegroups.TestResourceGroupIntegration.testPathToRoot(TestResourceGroupIntegration.java:59)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Comment by findepi** [comment]
somewhat related to https://github.com/trinodb/trino/issues/11039
