### ISSUE TITLE
COMPILER_ERROR

### ISSUE THREAD

**Issue by laidongxu** [trinodb/trino#21336]
run this sql 
`
select * from tmp_boss_trino.day_hour1 
where ds='2023-01-01' and  bg in ('634805371','634808101','634813706','634814556','634817394','634820822','634835167','634836705','634839401','634851948','634886323','634930805','634931658','634956095','634974635','634986648','634994153','635005183','635006361','635039150','63505660','635080513','63508133','635098411','635103660','635104384','635115017','635131291','635136357','635167199','635195901','635197255','635206920','635220691','635224430','635230542','63524350','635250097','635280656','635333878','635348444','635366639','635368006','635389851','635393351','635395874','635420268','635443979','635450478','635468285','635504783','635508932','635522392','635528267','635538187','635595539','635602694','635636218','635642530','63567107','635685048','635717559','635752375','635754317','635817252','635822798','635824753','635837287','635849316','635868243','635883600','635885014','635895812','635912533','635931554','635935207','635954054','635960192','635960425','635963475','635984044','636006030','636008593','636019399','636068045','636092684','63610611','636144281','636155742','636174897','636231229','636250885','636266983','636267895','636270927','636279778','636335988','636351434','636356226','636359144','636375982','636381655','636388159','636398282','636410572','636411933','636434554','636437969','636440250','636446169','636460137','636464414','636465690','636467139','636477796','636482879','636491461','636546580','636553434','636553730','636557241','636572360','636572983','636578124','636579273','636584980','636595747','636609436','636613504','636617014','636619657','636625622','636646513','636648023','636650525','636660781','636675816','636686098','636686452','636696122','636735128','636758039','636838904','636843708','636859988','636871213','636877282','636918714','636933114','636934343','636952854','637004341','637032851','637035480','637039116','63704173','637051111','63706215','637086501','637088762','637097578','637102222','637103244','637118546','637164891','637179022','637183308','637183447','637199254','637221439','637239410','637242675','637246223','637253329','637261246','63728422','637285759','637285853','637290022','637299023','637312558','637349857','637366446','637382508','637384699','637385768','637391573','637402947','637429334','637451924','637490824','637514707','637516950','637535548','637557178','637558970','637569987','637576238','637588186','637605553','637617780','637709173','637714880','63772858','637751541','637796888','637799373','637833907','63783436','637845693','637866900','637871544','637878729','637896490','637914537','637923803','63792936','637942502','637975702','637977902','637981984','637984685','638005854','638035999','638041052','638049088','638051152','638056534','638115608','638131250','638153726','638158723','638165028','638170964','638184043','638219878','638220588','638225944','638228007','638234203','638297669','638304059','638319275','638342357','638346792','638364064','638372414','638373480','638375800','638391676','638399917','638407156','638430514','638441676','638472708','638481770','638529129','638530852','638535924','638537483','638555688','638556746','638564872','638565076','638580544','638610861','638620782','638621834','638671332','638696033','638702997','638712812','638747147','638748959','638770553','638773962','638775267','638786333','638792676','638802359','638813706','638824436','638824961','638840330','638841188','638845708','638855687','638886993','638887799','638888325','638897004','638899938','638914094','638924884','638936577','638938033','638974850','638987242','639010349','639072202','639072632','639073118','639093676','639101085','639121298','639121375','639122003','639153701','639155833','639189357','639191854','639206451','639209855','639216880','639239149','639249685','639277831','639280539','639288539','639323120','639325047','639385853','639387963','639388436','639388968','639395310','639400316','639407383','639408775','639414446','639428805','639438363','639443993','63945025','639455612','639456896','639463087','639467755','639475860','639476978','639496650','639497285','639506313','639544853','639545817','639576697','639614868','639622311','639626702','639630502','639642985','639646583','639676264','639728129','639733573','639738258','63974007','639746360','639755742','639787361','639815610','639816373','639822355','639824473','639844831','639848472','639862524','639877093','639885611','639893637','639894914','639897089','639899535','639902235','639933676','639949767','639957248','639960774','639978696','639989560','640010869','640043029','640043317','640046761','640077495','640083858','640107731','640126392','640132493','640134775','640135434','640139170','640141556','640152090','640152914','640169366','640169660','640200283','640211823','640219247','640222575','640228451','640238242','640244821','640257492','640260569','640272099','640276957','640283525','640288614','640295572','640309182','640335662','640390147','640422692','640425523','640430453','640439661','640440239','640453842','640459549','640464710','640470146','640478451','640495958','640496777','640505621','640509648','640531759','640554994','640556300','640593208','640628434','640633431','640669315','640670820','640685815','640702093','640719903','640748036','640751290','640771712','640777054','640786890','640796676','640802699','640818434','640819393','640822350','640865288','640907227','640918732','640925992','640937032','640941433','640970312','640983594','640990926','640993194','641001542','641002788','641004893','641012959','64104189','641042962','641054081','641066371','641080463','641101730','641102209','641104249','641105050','641144131','641165249','641177120','641180963','641197726','641198418','641200596','641226592','641259955','641260091','64127401','641299715','641303072','641309336','641323344','641323922','641324846','641331225','641349479','641350704','641381904','641392341','641402614','641405617','641420160','641420660','641422407','641434182','641435205','641464625','641477257','641485228','641497686','641508374','641519541','641528489','641530085','641543529','641544157','641545195','641564245','641571334','641577618','641580829','641590213','641598025','641607542','641612255','641623075','641626757','641627596','641632892','641646905','641651941','641656115','641660532','641687402','641693850','641702780','641723422','64173800','641740250','641757038','641768602','641777178','641803965','64181508','641828340','641833305','641868582','641886502','641890346','641898753','641904982','641911446','641998562','642004795','642009961','642013062','642032414','642042164','642044091','642046968','642052129','642053496','642071068','642092929','642092956','642096166','642100486','642109045','642121766','642126152','642148742','642150626','642156426','642160901','642182615','64221092','642219717','642220894','642253010','642253138','642273446','642292600','642302734','642317801','642318987','642379185','642390615','642400608','642444915','642454682','642458277','642466380','642474340','642484821','642530108','642555246','642569562','642575452','642585201','642585676','64261272','642620449','642626984','642629993','642633885','642674618','642685287','642697406','642713998','642720496','642737430','642738735','642739504','64274177','642757140','642764498','64276723','642782504','642786860','642794132','642807202','642824086','642837632','642838941','642840123','642843389','642845224','64287530','642878897','642880451','642918576','642925391','642951287','642955614','642958059','642964298','642965977','642971205','642971515','642972180','643004811','643005942','643007146','643013319','643023698','64302919','643064192','643066403','643079820','643086057','643113013','643118170','643159012','643166974','643187256','643194101','643238775','643314864','643321694','643324372','643343800','643427700','643745239','64389387','643957619','644237747','644272738','6444190','644505636','64461265','644696229','64489170','64626049','64661473','64696165','64716268','64778089','64883839','64902428','64999843','65030410','65109978','65139792','65183686','65278522','65335013','65376172','65387712','6552722','65532559','65534280','65550267','6563352','65676912','65736207','65850555','65894442','65952280','65976751','66000360','66135621','66150745','66176154','66196588','66238574','66261194','66382308','66391860','66402897','66403512','66579515','66611021','66664130','66672933','66726172','66818460','66866752','66883431','66964688','66969687','66983968','67028509','67045475','67050845','67057881','67166138','67235979','67262999','67307378','67380771','67403126','67438420','67487940','67516743','67597113','67607194','67654885','67684424','67746389','6777684','67848137','67868035','67883668','67909625','67947784','67969447','68077855','68095894','68211061','68303167','68365663','68439622','68520725','68525830','68534342','68538538','68585933','68593810','68715875','68746898','68800651','68847120','6893796','68970605','68977363','68977597','69090780','69114546','69220690','69256080','69272811','69293449','69313476','69396637','69432131','69464209','69550426','69550977','69587040','69639607','69827070','69836666','69902196','69902248','6990593','69972840','7008822','70117289','70219061','70230616','70281408','70282195','70425603','70436054','70478457','70557590','70567180','70584431','70591070','70607010','70773623','70911979','71053941','71137576','71158235','71201348','7121217','71227513','71253814','71318106','71325759','71326570','71355980','71511016','71534685','71562269','7163161','71632862','71783498','71807875','71956665','71983373','72028058','72154839','72235043','72249689','72302274','72377198','72580266','72617762','72693706','72802090','72808653','72870987','72880045','72882857','72987170','72997699','73056678','73142429','73171430','73213863','7322619','73268992','73273784','73275408','73288494','73327553','73597778','73614014','73618695','73699128','73784639','73812610','73835574','73947814','73948794','73979370','73988773','74034182','74054147','74126178','74142203','74215224','74456575','74467132','74747275','74817317','74834343','74843791','74897684','75046090','75095986','75114056','75138325','75144242','75145097','75174466','75312937','75321969','75440378','75465792','75506453','75568805','75584109','75615094','75645095','75725204','75752357','75769803','75798461','75826537','75964152',
'75971718','76012809','76106636','76122969','76235126','76241865','76289847','76292660','76312335','76315975','76327157','76374577','76410753','76421544','76563395','76693651','76717467','76786560','76806739','76829258','76902514','76974007','77004451','77025438','77149093','77149745','77159228','77233218','77254668','77468064','77468941','77475175','77484703','77709809','77817333','77872553','77898921','77902435','77951953','77972183','78013192','78023507','78130071','78146293','78149434','78152807','78244836','78277313','78285551','78620489','78697794','78752484','78788968','78800850','78813161','78837120','78839942','78850980','78856483','78857062','78887929','78978984','79072830','79212374','79275559','79331472','79426589','79435308','79454092','79571656','79638058','79638439','79808176','79823832','79848779','79859338','79867690','79869908','80025749','80047628','80134344','80246819','80265206','80359031','80451709','80571067','80664436','80745834','80759047','80808448','80891242','80896150','80944021','81088494','81132747','81145258','81193107','81195672','81429658','81439037','81478888','81519461','81700482','81724723','81802331','81846714','81869418','81917722','81936798','81989716','82023846','82047471','82078673','82134541','82168086','82279312','82291891','82299323','82310246','82453356','82462952','82575109','82578922','82596755','82692059','82763680','82790626','82813322','82866359','83003024','83126256','83170746','83327201','83342809','83494587','83495489','83578795','83621989','83721185','83804238','84025624','84057331','84131225','84162674','84201','84302867','84304810','84316037','84341598','84453836','84455597','84473879','84481300','84571481','84598761','84599384','84650068','84685077','84759689','84808033','84889302','84930763','84934889','85131802','85171357','85198235','85262554','85277093','85283374','85373088','85401236','85417493','85457349','85568704','85571046','85579201','85604696','85734908','85751999','85769153','85795030','85832186','85855986','85937769','85971751','86026364','86035922','87072','91798924','91819641','91974060','92104423','92171542','92175807','92193001','92243433','92263264','92282926','92351026','92383070','92386130','92406214','92416959','92553540','92658877','92843825','92873991','92929263') ;`

**found TrinoException**
`io.trino.spi.TrinoException: Compiler failed. Possible reasons include: the query may have too many or too complex expressions, or the underlying tables may have too many columns
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:2088)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:1971)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:886)
	at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitAggregation(LocalExecutionPlanner.java:1906)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitAggregation(LocalExecutionPlanner.java:886)
	at io.trino.sql.planner.plan.AggregationNode.accept(AggregationNode.java:221)
	at io.trino.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:645)
	at io.trino.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:544)
	at io.trino.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:84)
	at io.trino.execution.SqlTask.tryCreateSqlTaskExecution(SqlTask.java:545)
	at io.trino.execution.SqlTask.updateTask(SqlTask.java:497)
	at io.trino.execution.SqlTaskManager.doUpdateTask(SqlTaskManager.java:544)
	at io.trino.execution.SqlTaskManager.lambda$updateTask$9(SqlTaskManager.java:485)
	at io.trino.$gen.Trino_trino_432_21_g0f2a79a_dirty____20240325_121454_2.call(Unknown Source)
	at io.trino.execution.SqlTaskManager.updateTask(SqlTaskManager.java:485)
	at io.trino.server.TaskResource.createOrUpdateTask(TaskResource.java:153)
	at jdk.internal.reflect.GeneratedMethodAccessor814.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:357)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:62)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: io.airlift.bytecode.CompilationException: Error compiling class: io/trino/$gen/CursorProcessor_20240401_024415_32563
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2086)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4012)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5013)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5020)
	at com.google.common.cache.ForwardingLoadingCache.getUnchecked(ForwardingLoadingCache.java:54)
	at io.trino.sql.gen.ExpressionCompiler.compileCursorProcessor(ExpressionCompiler.java:85)
	at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:2053)
	... 82 more
Caused by: io.airlift.bytecode.CompilationException: Error compiling class: io/trino/$gen/CursorProcessor_20240401_024415_32563
	at io.airlift.bytecode.ByteCodeGenerator.generateByteCode(ByteCodeGenerator.java:106)
	at io.airlift.bytecode.ClassGenerator.defineClasses(ClassGenerator.java:100)
	at io.airlift.bytecode.ClassGenerator.defineClass(ClassGenerator.java:90)
	at io.trino.util.CompilerUtils.defineClass(CompilerUtils.java:81)
	at io.trino.util.CompilerUtils.defineClass(CompilerUtils.java:75)
	at io.trino.sql.gen.ExpressionCompiler.compileProcessor(ExpressionCompiler.java:170)
	at io.trino.sql.gen.ExpressionCompiler.compile(ExpressionCompiler.java:141)
	at io.trino.sql.gen.ExpressionCompiler.lambda$new$0(ExpressionCompiler.java:70)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080)
	... 89 more
Caused by: org.objectweb.asm.MethodTooLargeException: Method too large: io/trino/$gen/CursorProcessor_20240401_024415_32563.filter (Lio/trino/spi/connector/ConnectorSession;Lio/trino/spi/connector/RecordCursor;)Z
	at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2088)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:512)
	at io.airlift.bytecode.ByteCodeGenerator.generateByteCode(ByteCodeGenerator.java:103)
	... 101 more`

**Comment by Akanksha-kedia** [comment]
@laidongxu i suspect Increasing JVM Heap Size would help considering complexity of query.

**Comment by wendigo** [comment]
@martint can you take a look?

**Comment by laidongxu** [comment]
trino  version is 432 ,  trino worker  jvm heap size is 80 GB

**Comment by martint** [comment]
Can you provide the output of `SHOW CREATE TABLE tmp_boss_trino.day_hour1` ?

**Comment by martint** [comment]
I believe this is specific to queries involving RecordCursor (vs PageSource), which only applies to certain formats. Also, it may be fixed in newer versions (443+), but I need to be able to reproduce it in order to be sure.

**Comment by laidongxu** [comment]
> SHOW CREATE TABLE tmp_boss_trino.day_hour1

CREATE TABLE `tmp_boss_trino.day_hour1`(
  `id` string COMMENT '',
  `bg` int COMMENT '')
PARTITIONED BY (
  `ds` string,
  `hour` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  'hdfs://dap-hdfs-qa/user/hive/warehouse/tmp_boss_trino.db/day_hour1'
TBLPROPERTIES (
  'bucketing_version'='2',
  'transient_lastDdlTime'='1693213145')
