### ISSUE TITLE
Race condition in Alluxio cache

### ISSUE THREAD

**Issue by Praveen2112** [trinodb/trino#21342]
This issue is seen when we trying to run `testCreateOrReplaceTableConcurrently()`  which will be introduced as a part of https://github.com/trinodb/trino/pull/19991. 

When two different threads in a worker are trying to read a same file, then it fails to read the data file with the following message 

```
	Caused by: java.io.IOException: Read -1 bytes from cache
		at io.trino.filesystem.alluxio.AlluxioInputHelper.doInternalCacheRead(AlluxioInputHelper.java:120)
		at io.trino.filesystem.alluxio.AlluxioInputHelper.lambda$doCacheRead$0(AlluxioInputHelper.java:89)
		at io.trino.filesystem.alluxio.AlluxioTracing.withTracing(AlluxioTracing.java:29)
		at io.trino.filesystem.alluxio.AlluxioInputHelper.doCacheRead(AlluxioInputHelper.java:87)
		at io.trino.filesystem.alluxio.AlluxioInput.readFully(AlluxioInput.java:79)
		at io.trino.filesystem.alluxio.AlluxioInput.readTail(AlluxioInput.java:128)
		at io.trino.filesystem.TrinoInput.readTail(TrinoInput.java:43)
		at io.trino.filesystem.tracing.TracingInput.lambda$readTail$3(TracingInput.java:81)
		at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
		at io.trino.filesystem.tracing.TracingInput.readTail(TracingInput.java:81)
		at io.trino.plugin.hive.parquet.MemoryParquetDataSource.<init>(MemoryParquetDataSource.java:56)
		at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createDataSource(ParquetPageSourceFactory.java:319)
		at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:222)
		... 20 more
```

It looks like there `CacheHelper#put` doesn't guarantee that file is written by Alluxio and it is ready to be read. From the CacheManager Javadocs 

```
* Puts a page into the cache manager. This method is best effort. It is possible that this put operation returns without page written.
```

**Comment by Praveen2112** [comment]
cc: @findepi

**Comment by oneonestar** [comment]
Not sure is #21147 related.

```
Error:  io.trino.plugin.iceberg.TestIcebergMinioParquetCachingConnectorSmokeTest.testDeleteRowsConcurrently -- Time elapsed: 1.029 s <<< FAILURE!
java.lang.AssertionError: 

Expecting actual:
  "Error opening Iceberg split s3://test-iceberg-minio-smoke-test-644dgh92cp/tpch_parquet/
test_concurrent_deletedzqste2fpa-7540993bf63649f5bb31eaf43bc95bf2/data/
20240318_020344_00308_w4ntw-57b8d9ba-5aa4-4dae-8803-7b6343df0b2d.parquet (offset=0, length=746): Read -1 bytes from cache"
to contain at least one of the following elements:
  ["Failed to commit Iceberg update to table:",
    "Failed to replace table due to concurrent updates:"]
but none were found 
	at io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$0(BaseIcebergConnectorSmokeTest.java:153)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Praveen2112** [comment]
I think both are related

**Comment by jkylling** [comment]
This might be because we incorrectly (?) throw an exception when `CacheManager.get` returns `-1`, which is supposed to [indicate an error](https://docs.alluxio.io/os/javadoc/stable/index.html?alluxio/client/file/cache/CacheManager.html). The corresponding code in Alluxio treats cache misses and cache errors the same way https://github.com/Alluxio/alluxio/blob/fd5478e69cd176501c7173df1148285608cefd09/dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java#L199-L202 So probably we should handle `-1` in a non-exceptional way. This is a bit unfortunate, as I believe the `-1` return code is the only way some wrong cache setups will be detected (e.g., if we do not have read/write permission to the cache directory).

Does the test become non-flaky if you change https://github.com/trinodb/trino/blob/0c1fdcb2a736673fad219ea34a7f16dc70104582/lib/trino-filesystem-cache-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioInputHelper.java#L116 to use `if (bytesReadFromCache <= 0) {`?

**Comment by Praveen2112** [comment]
I was looking on a similar fix and I have opened a similar PR for the same https://github.com/trinodb/trino/pull/21350 - PTAL at your spare time.

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8638178590/job/23682392340?pr=21498

```
2024-04-10T16:27:44.855-0600	WARN	Query-20240410_222744_00271_ngzde-1188	io.trino.plugin.iceberg.catalog.hms.TrinoHiveCatalog	Failed to delete table data referenced by metadata
org.apache.iceberg.exceptions.NotFoundException: Failed to open input stream for file: s3://test-iceberg-minio-smoke-test-z3xmdpaq7p/tpch_parquet/test_drop_table_with_missing_snapshot_file_6o0u2k656t-7967aa53d7f3498ba254b07d2cb14aff/metadata/snap-5122265470032172303-1-175948bf-9a3f-4a7b-bced-360db6e6f367.avro
	at io.trino.plugin.iceberg.fileio.ForwardingInputFile.newStream(ForwardingInputFile.java:55)
	at org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:102)
	at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77)
	at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:37)
	at org.apache.iceberg.relocated.com.google.common.collect.Iterables.addAll(Iterables.java:333)
	at org.apache.iceberg.relocated.com.google.common.collect.Lists.newLinkedList(Lists.java:241)
	at org.apache.iceberg.ManifestLists.read(ManifestLists.java:45)
	at org.apache.iceberg.BaseSnapshot.cacheManifests(BaseSnapshot.java:146)
	at org.apache.iceberg.BaseSnapshot.allManifests(BaseSnapshot.java:164)
	at org.apache.iceberg.CatalogUtil.dropTableData(CatalogUtil.java:100)
	at io.trino.plugin.iceberg.catalog.hms.TrinoHiveCatalog.dropTable(TrinoHiveCatalog.java:399)
	at io.trino.plugin.iceberg.IcebergMetadata.dropTable(IcebergMetadata.java:1772)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.dropTable(ClassLoaderSafeConnectorMetadata.java:465)
	at io.trino.tracing.TracingConnectorMetadata.dropTable(TracingConnectorMetadata.java:403)
	at io.trino.metadata.MetadataManager.dropTable(MetadataManager.java:1007)
	at io.trino.tracing.TracingMetadata.dropTable(TracingMetadata.java:562)
	at io.trino.execution.DropTableTask.execute(DropTableTask.java:88)
	at io.trino.execution.DropTableTask.execute(DropTableTask.java:36)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:146)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:272)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:570)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:545)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1137)
	at io.trino.$gen.Trino_testversion____20240410_222659_646.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.io.FileNotFoundException: s3://test-iceberg-minio-smoke-test-z3xmdpaq7p/tpch_parquet/test_drop_table_with_missing_snapshot_file_6o0u2k656t-7967aa53d7f3498ba254b07d2cb14aff/metadata/snap-51222654700[321](https://github.com/trinodb/trino/actions/runs/8638178590/job/23682392340?pr=21498#step:5:322)72303-1-175948bf-9a3f-4a7b-bced-360db6e6f367.avro
	at io.trino.filesystem.s3.S3InputFile.length(S3InputFile.java:71)
	at io.trino.filesystem.alluxio.AlluxioFileSystemCache.uriStatus(AlluxioFileSystemCache.java:93)
	at io.trino.filesystem.alluxio.AlluxioFileSystemCache.cacheStream(AlluxioFileSystemCache.java:71)
	at io.trino.filesystem.alluxio.AlluxioCoordinatorFileSystemCache.cacheStream(AlluxioCoordinatorFileSystemCache.java:78)
	at io.trino.filesystem.tracing.TracingFileSystemCache.lambda$cacheStream$1(TracingFileSystemCache.java:64)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
	at io.trino.filesystem.tracing.TracingFileSystemCache.cacheStream(TracingFileSystemCache.java:64)
	at io.trino.filesystem.cache.CacheInputFile.newStream(CacheInputFile.java:58)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
	at io.trino.filesystem.tracing.TracingInputFile.newStream(TracingInputFile.java:64)
	at io.trino.plugin.iceberg.fileio.ForwardingInputFile.newStream(ForwardingInputFile.java:52)
	... 28 more


2024-04-10T16:27:51.213-0600	ERROR	SplitRunner-20240410_222751_00332_ngzde.2.0.0-1-1259	alluxio.client.file.cache.LocalCacheManager	Data corrupted page PageId{FileId=bfeb368ea7760fa25b6230a575fe2ef0, PageIndex=0} from pageStore
alluxio.exception.PageCorruptedException: The page PageId{FileId=bfeb368ea7760fa25b6230a575fe2ef0, PageIndex=0} (/tmp/cache3468081240987933578/LOCAL/1048576/649/bfeb368ea7760fa25b6230a575fe2ef0/0) probably has been corrupted, page-offset 0, bytes to read 746, page file length 0
	at alluxio.client.file.cache.store.LocalPageStore.get(LocalPageStore.java:106)
	at alluxio.client.file.cache.LocalCacheManager.getPage(LocalCacheManager.java:971)
	at alluxio.client.file.cache.LocalCacheManager.get(LocalCacheManager.java:623)
	at alluxio.client.file.cache.CacheManager.get(CacheManager.java:281)
	at alluxio.client.file.cache.NoExceptionCacheManager.get(NoExceptionCacheManager.java:123)
	at io.trino.filesystem.alluxio.TracingCacheManager.lambda$get$15(TracingCacheManager.java:231)
	at io.trino.filesystem.alluxio.AlluxioTracing.withTracing(AlluxioTracing.java:29)
	at io.trino.filesystem.alluxio.TracingCacheManager.get(TracingCacheManager.java:231)
	at io.trino.filesystem.alluxio.AlluxioInputHelper.readPageFromCache(AlluxioInputHelper.java:150)
	at io.trino.filesystem.alluxio.AlluxioInputHelper.doInternalCacheRead(AlluxioInputHelper.java:115)
	at io.trino.filesystem.alluxio.AlluxioInputHelper.lambda$doCacheRead$0(AlluxioInputHelper.java:89)
	at io.trino.filesystem.alluxio.AlluxioTracing.withTracing(AlluxioTracing.java:29)
	at io.trino.filesystem.alluxio.AlluxioInputHelper.doCacheRead(AlluxioInputHelper.java:87)
	at io.trino.filesystem.alluxio.AlluxioInput.readFully(AlluxioInput.java:79)
	at io.trino.filesystem.alluxio.AlluxioInput.readTail(AlluxioInput.java:128)
	at io.trino.filesystem.TrinoInput.readTail(TrinoInput.java:43)
	at io.trino.filesystem.tracing.TracingInput.lambda$readTail$3(TracingInput.java:81)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
	at io.trino.filesystem.tracing.TracingInput.readTail(TracingInput.java:81)
	at io.trino.plugin.hive.parquet.MemoryParquetDataSource.<init>(MemoryParquetDataSource.java:56)
	at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createDataSource(ParquetPageSourceFactory.java:315)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createParquetPageSource(IcebergPageSourceProvider.java:998)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createDataPageSource(IcebergPageSourceProvider.java:635)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createPageSource(IcebergPageSourceProvider.java:373)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createPageSource(IcebergPageSourceProvider.java:265)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:48)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:259)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:190)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:359)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:255)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:132)
	at io.trino.operator.Driver.processInternal(Driver.java:403)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:306)
	at io.trino.operator.Driver.tryWithLock(Driver.java:709)
	at io.trino.operator.Driver.process(Driver.java:298)
	at io.trino.operator.Driver.processForDuration(Driver.java:269)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:76)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:191)
	at io.trino.$gen.Trino_testversion____20240410_222657_572.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:192)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:174)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:161)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)


2024-04-10T16:27:57.900-0600	WARN	http-client-node-manager-894	io.trino.metadata.RemoteNodeState	Error fetching node state from http://127.0.0.1:33749/v1/info/state: Server refused connection: http://127.0.0.1:33749/v1/info/state
2024-04-10T16:27:58.190-0600	WARN	http-client-memoryManager-1035	io.trino.memory.RemoteNodeMemory	Error fetching memory info from http://127.0.0.1:33749/v1/memory: Server refused connection: http://127.0.0.1:33749/v1/memory
2024-04-10T16:27:58.971-0600	INFO	docker-java-stream-1678708200	container.Hadoop	(exited)
2024-04-10T16:27:58.971-0600	INFO	docker-java-stream-1678708200	container.Hadoop	(exited)
2024-04-10T16:27:59.165-0600	INFO	pool-132-thread-1	io.trino.testing.minio.MinioClient	Completed notification listener for bucket test-iceberg-minio-smoke-test-z3xmdpaq7p
Error:  Tests run: 74, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 79.38 s <<< FAILURE! -- in io.trino.plugin.iceberg.TestIcebergMinioParquetCachingConnectorSmokeTest
Error:  io.trino.plugin.iceberg.TestIcebergMinioParquetCachingConnectorSmokeTest.testDeleteRowsConcurrently -- Time elapsed: 0.776 s <<< FAILURE!
java.lang.AssertionError: 

Expecting actual:
  "Error opening Iceberg split s3://test-iceberg-minio-smoke-test-z3xmdpaq7p/tpch_parquet/test_concurrent_deletelj1ne49p4g-354309a6978c40c6b2abf3ea9be28678/data/20240410_222750_00[331](https://github.com/trinodb/trino/actions/runs/8638178590/job/23682392340?pr=21498#step:5:332)_ngzde-4048b9e9-58a0-41c9-a4a8-1178bad03c37.parquet (offset=0, length=746): Read -1 bytes from cache"
to contain at least one of the following elements:
  ["Failed to commit Iceberg update to table:",
    "Failed to replace table due to concurrent updates:"]
but none were found 
	at io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$0(BaseIcebergConnectorSmokeTest.java:153)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```
