### ISSUE TITLE
Invalid method name: 'get_table_meta' while listing tables from hive database

### ISSUE THREAD

**Issue by bmurashin** [trinodb/trino#21438]
Hi, Everyone!
Having issue listing tables `show tables from <hive_catalog>.<db>` using hive connector

**Environment:**
Hive: 1.2.1000 (Hortonworks HDP 2.6.5)
Trino: 444

**Error message:**
```
Query ... failed: Error listing tables for catalog hive: Invalid method name: 'get_table_meta'
io.trino.spi.TrinoException: Error listing tables for catalog hive: Invalid method name: 'get_table_meta'
        at io.trino.metadata.MetadataListing.handleListingException(MetadataListing.java:358)
        at io.trino.metadata.MetadataListing.listTables(MetadataListing.java:122)
        at io.trino.connector.informationschema.InformationSchemaPageSource.addTablesRecords(InformationSchemaPageSource.java:292)
        at io.trino.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:221)
        at io.trino.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:185)
        ...
Caused by: io.trino.spi.TrinoException: Invalid method name: 'get_table_meta'
        ...
```

I've found this changes in metastore client https://github.com/trinodb/trino/blob/444/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java#L176
to be absent in version 442 https://github.com/trinodb/trino/blob/442/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java#L190
and confirmed 442 executing `show tables from ...` without issues in my environment

**Comment by Akanksha-kedia** [comment]
can i work on this?

**Comment by bmurashin** [comment]
> can i work on this?

Who is eligible to say yes? I'd be happy this issue to be worked on

**Comment by wendigo** [comment]
We've dropped support and testing for HDP2.6 some time ago and there is no plan to bring it back. Sorry
