### ISSUE TITLE
Read big length column will cause NegativeArraySizeException.

### ISSUE THREAD

**Issue by Heltman** [trinodb/trino#21443]
We received an error when reading a table with a certain column that has a large length. After inspection, we found that the length exceeded the size of the Slice by 2GB. 

After investigation, it is because Trino reads files in batches. The batch size is generally 4096, and our column size is 500 KB, thus exceeding the limit of Slice.

I use trino 421 version, but I guess this is a common problem. We have discussed it on slack, @wendigo @electrum 

I built a minimal reproducible case as follows：
```sql
-- a,b,c,d columns added for fold aa column to avoid trino-cli OOM
select * from (select 'a' a,'b' b,'c' c,'d' d,  repeat('a', 512000) aa) x cross join unnest (sequence(1,5000));
```

error:
```java
java.lang.NegativeArraySizeException: -1734967296
	at io.airlift.slice.Slices.allocate(Slices.java:89)
	at io.trino.spi.block.VariableWidthBlock.copyPositions(VariableWidthBlock.java:204)
	at io.trino.spi.block.DictionaryBlockEncoding.readBlock(DictionaryBlockEncoding.java:69)
	at io.trino.metadata.InternalBlockEncodingSerde.readBlock(InternalBlockEncodingSerde.java:62)
	at io.trino.block.BlockSerdeUtil.readBlock(BlockSerdeUtil.java:43)
	at io.trino.execution.buffer.PagesSerdeUtil.readRawPage(PagesSerdeUtil.java:78)
	at io.trino.execution.buffer.PageDeserializer.deserialize(PageDeserializer.java:80)
	at io.trino.server.protocol.Query.removePagesFromExchange(Query.java:545)
	at io.trino.server.protocol.Query.getNextResult(Query.java:416)
	at io.trino.server.protocol.Query.lambda$waitForResults$2(Query.java:292)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:252)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:242)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:123)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:79)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by Heltman** [comment]
The error reporting location is as follows, but the location that needs to be processed may not be here.
https://github.com/trinodb/trino/blob/4bd0f8de39512ddd6f0b52b601c48b7a9106bac3/lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BinaryBuffer.java#L81-L99

**Comment by wendigo** [comment]
@raunaqmorarka can you take a look?

**Comment by martint** [comment]
The example query above doesn't work run, but here's one that does:

```
SELECT * 
FROM (
    SELECT concat_ws('', repeat(concat_ws('', repeat('a', 1000)), 500))), unnest(sequence(1, 5000)
)
```

**Comment by wendigo** [comment]
@raunaqmorarka I think that this is unrelated to parquet. The example that Martin shared is not using parquet files.

**Comment by jshmchenxi** [comment]
We also experience this issue with Trino version 451. Turning down `parquet.max-read-block-row-count` config helped as a workaround.

**Comment by maswin** [comment]
Any update on why this issue happens? We are also facing this. Setting parquet.max-read-block-row-count to 1024 fixes the issue

**Comment by raunaqmorarka** [comment]
I think https://github.com/trinodb/trino/pull/25256 unintentionally fixed the specific scenario in https://github.com/trinodb/trino/issues/21443#issuecomment-2044254485 by forcing dictionary pages to be split up more agressively before the exchange in `io.trino.execution.buffer.PageSplitterUtil#splitAndSerializePage` as the DictionaryBlock size is now calculated as-if it were already flattened.
It turns out to be okay for this case as the receiving side of the exchange always flattens the dictionary.
fyi @dain @lukasz-stec
