### ISSUE TITLE
Flaky TestDeltaLakeAdlsConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#21554]
```
Error:  Tests run: 203, Failures: 0, Errors: 2, Skipped: 2, Time elapsed: 642.3 s <<< FAILURE! -- in io.trino.plugin.deltalake.metastore.glue.TestDeltaS3AndGlueMetastoreTest
Error:  io.trino.plugin.deltalake.TestDeltaLakeAdlsConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable -- Time elapsed: 24.76 s <<< ERROR!
java.lang.RuntimeException: Wait timed out
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.lambda$testConcurrentInsertsSelectingFromTheSameTable$16(BaseDeltaLakeConnectorSmokeTest.java:2396)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.lambda$testConcurrentInsertsSelectingFromTheSameTable$17(BaseDeltaLakeConnectorSmokeTest.java:2396)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:729)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable(BaseDeltaLakeConnectorSmokeTest.java:2398)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable(BaseDeltaLakeConnectorSmokeTest.java:2350)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1534)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2269)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:495)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1003)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

Error:  io.trino.plugin.deltalake.TestDeltaLakeAdlsConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable -- Time elapsed: 27.91 s <<< ERROR!
java.lang.RuntimeException: Wait timed out
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.lambda$testConcurrentInsertsSelectingFromTheSameTable$16(BaseDeltaLakeConnectorSmokeTest.java:2396)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.lambda$testConcurrentInsertsSelectingFromTheSameTable$17(BaseDeltaLakeConnectorSmokeTest.java:2396)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:729)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable(BaseDeltaLakeConnectorSmokeTest.java:2398)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable(BaseDeltaLakeConnectorSmokeTest.java:2351)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1534)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2269)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:495)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1003)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

https://github.com/trinodb/trino/actions/runs/8673807420/job/23786003063

cc: @findinpath

**Comment by findepi** [comment]
```
Error:  Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 20.43 s <<< FAILURE! -- in io.trino.plugin.deltalake.TestDeltaLakeSharedGlueMetastoreWithTableRedirections
Error:  io.trino.plugin.deltalake.TestDeltaLakeAdlsConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable -- Time elapsed: 24.46 s <<< ERROR!
java.lang.RuntimeException: Wait timed out
```

**Comment by findepi** [comment]
cc @findinpath

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/8726437921/job/23943355850?pr=21597
