### ISSUE TITLE
Some Redshift tests are broken

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#21626]
https://github.com/trinodb/trino/actions/runs/8749315702/job/24010872826?pr=21622
```
Error:  io.trino.plugin.redshift.TestRedshiftConnectorTest.testJoinPushdownWithLongIdentifiers -- Time elapsed: 5.013 s <<< FAILURE!
java.lang.AssertionError: 
Plan does not match, expected [

- node(OutputNode)
    - node(TableScanNode)
2024-04-19T00:56:42.061-0600	INFO	main	io.trino.testing.containers.junit.ReportLeakedContainers	DockerClientFactory not initialized, so there should be no leaked containers, skipping the check

] but found [

Output[columnNames = [colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz, colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz]]
│   Layout: [colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz:bigint, colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz:bigint]
└─ InnerJoin[criteria = (colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz = colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz_0), distribution = PARTITIONED]
   │   Layout: [colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz:bigint]
   │   Distribution: PARTITIONED
   │   dynamicFilterAssignments = {colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz_0 -> #df_216}
   ├─ RemoteExchange[type = REPARTITION]
   │  │   Layout: [colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz:bigint]
   │  └─ ScanFilter[table = redshift:test_schema.test_long_id_lyk8p5s8owv testdb.test_schema.test_long_id_lyk8p5s8owv, dynamicFilters = {colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz = #df_216}]
   │         Layout: [colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz:bigint]
   │         colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz := colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz:bigint:int8
   └─ LocalExchange[partitioning = SINGLE]
      │   Layout: [colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz_0:bigint]
      └─ RemoteExchange[type = REPARTITION]
         │   Layout: [colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz_0:bigint]
         └─ TableScan[table = redshift:test_schema.test_long_id_ryt1xiismzc testdb.test_schema.test_long_id_ryt1xiismzc]
                Layout: [colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz_0:bigint]
                colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz_0 := colzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz:bigint:int8

]
	at io.trino.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:58)
	at io.trino.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:49)
	at io.trino.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:43)
	at io.trino.sql.query.QueryAssertions$QueryAssert.lambda$isFullyPushedDown$5(QueryAssertions.java:452)
	at io.trino.testing.TransactionBuilder.lambda$execute$1(TransactionBuilder.java:130)
	at io.trino.testing.TransactionBuilder.execute(TransactionBuilder.java:162)
	at io.trino.testing.TransactionBuilder.execute(TransactionBuilder.java:129)
	at io.trino.sql.query.QueryAssertions$QueryAssert.isFullyPushedDown(QueryAssertions.java:450)
	at io.trino.plugin.jdbc.BaseJdbcConnectorTest.testJoinPushdownWithLongIdentifiers(BaseJdbcConnectorTest.java:2062)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

```
Error:  io.trino.plugin.redshift.TestRedshiftConnectorTest.testAggregationPushdown -- Time elapsed: 112.9 s <<< FAILURE!
java.lang.AssertionError: 
Plan does not match, expected [

- node(OutputNode)
    - node(TableScanNode)

] but found [

Output[columnNames = [regionkey, acctbals]]
│   Layout: [regionkey:bigint, sum:double]
│   acctbals := sum
└─ Aggregate[type = FINAL, keys = [regionkey]]
   │   Layout: [regionkey:bigint, sum:double]
   │   sum := sum(sum_6)
   └─ LocalExchange[partitioning = HASH, arguments = [regionkey::bigint]]
      │   Layout: [regionkey:bigint, sum_6:double]
      └─ RemoteExchange[type = REPARTITION]
         │   Layout: [regionkey:bigint, sum_6:double]
         └─ Aggregate[type = PARTIAL, keys = [regionkey]]
            │   Layout: [regionkey:bigint, sum_6:double]
            │   sum_6 := sum(acctbal)
            └─ LeftJoin[criteria = (nationkey = nationkey_1), distribution = PARTITIONED]
               │   Layout: [regionkey:bigint, acctbal:double]
               │   Distribution: PARTITIONED
               ├─ RemoteExchange[type = REPARTITION]
               │  │   Layout: [nationkey:bigint, regionkey:bigint]
               │  └─ TableScan[table = redshift:test_schema.nation_even_m7ifmi8u1k testdb.test_schema.nation_even_m7ifmi8u1k columns=[nationkey:bigint:int8, regionkey:bigint:int8]]
               │         Layout: [nationkey:bigint, regionkey:bigint]
               │         regionkey := regionkey:bigint:int8
               │         nationkey := nationkey:bigint:int8
               └─ LocalExchange[partitioning = SINGLE]
                  │   Layout: [nationkey_1:bigint, acctbal:double]
                  └─ RemoteExchange[type = REPARTITION]
                     │   Layout: [nationkey_1:bigint, acctbal:double]
                     └─ TableScan[table = redshift:test_schema.customer_even_vwl7qcyk3k testdb.test_schema.customer_even_vwl7qcyk3k columns=[nationkey:bigint:int8, acctbal:double:float8]]
                            Layout: [nationkey_1:bigint, acctbal:double]
                            acctbal := acctbal:double:float8
                            nationkey_1 := nationkey:bigint:int8

]
	at io.trino.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:58)
	at io.trino.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:49)
	at io.trino.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:43)
	at io.trino.sql.query.QueryAssertions$QueryAssert.lambda$isFullyPushedDown$5(QueryAssertions.java:452)
	at io.trino.testing.TransactionBuilder.lambda$execute$1(TransactionBuilder.java:130)
	at io.trino.testing.TransactionBuilder.execute(TransactionBuilder.java:162)
	at io.trino.testing.TransactionBuilder.execute(TransactionBuilder.java:129)
	at io.trino.sql.query.QueryAssertions$QueryAssert.isFullyPushedDown(QueryAssertions.java:450)
	at io.trino.plugin.redshift.TestRedshiftConnectorTest.testAggregationPushdown(TestRedshiftConnectorTest.java:468)
	at io.trino.plugin.redshift.TestRedshiftConnectorTest.testAggregationPushdown(TestRedshiftConnectorTest.java:404)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1534)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2269)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:495)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:662)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

```
Error:  io.trino.plugin.redshift.TestRedshiftConnectorTest.testLimitPushdown -- Time elapsed: 75.16 s <<< FAILURE!
java.lang.AssertionError: 
Plan does not match, expected [

- node(OutputNode)
    - node(TableScanNode)

] but found [

Output[columnNames = [name, name]]
│   Layout: [name:varchar(25), name_1:varchar(25)]
│   name := name_1
└─ Limit[count = 30]
   │   Layout: [name:varchar(25), name_1:varchar(25)]
   └─ LocalExchange[partitioning = SINGLE]
      │   Layout: [name:varchar(25), name_1:varchar(25)]
      └─ RemoteExchange[type = GATHER]
         │   Layout: [name:varchar(25), name_1:varchar(25)]
         └─ LimitPartial[count = 30]
            │   Layout: [name:varchar(25), name_1:varchar(25)]
            └─ LeftJoin[criteria = (regionkey = regionkey_0), distribution = PARTITIONED]
               │   Layout: [name:varchar(25), name_1:varchar(25)]
               │   Distribution: PARTITIONED
               ├─ RemoteExchange[type = REPARTITION]
               │  │   Layout: [name:varchar(25), regionkey:bigint]
               │  └─ TableScan[table = redshift:test_schema.nation testdb.test_schema.nation limit=30 columns=[name:varchar(25):varchar, regionkey:bigint:int8]]
               │         Layout: [name:varchar(25), regionkey:bigint]
               │         name := name:varchar(25):varchar
               │         regionkey := regionkey:bigint:int8
               └─ LocalExchange[partitioning = SINGLE]
                  │   Layout: [regionkey_0:bigint, name_1:varchar(25)]
                  └─ RemoteExchange[type = REPARTITION]
                     │   Layout: [regionkey_0:bigint, name_1:varchar(25)]
                     └─ TableScan[table = redshift:test_schema.region testdb.test_schema.region columns=[regionkey:bigint:int8, name:varchar(25):varchar]]
                            Layout: [regionkey_0:bigint, name_1:varchar(25)]
                            name_1 := name:varchar(25):varchar
                            regionkey_0 := regionkey:bigint:int8

]
	at io.trino.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:58)
	at io.trino.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:49)
	at io.trino.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:43)
	at io.trino.sql.query.QueryAssertions$QueryAssert.lambda$isFullyPushedDown$5(QueryAssertions.java:452)
	at io.trino.testing.TransactionBuilder.lambda$execute$1(TransactionBuilder.java:130)
	at io.trino.testing.TransactionBuilder.execute(TransactionBuilder.java:162)
	at io.trino.testing.TransactionBuilder.execute(TransactionBuilder.java:129)
	at io.trino.sql.query.QueryAssertions$QueryAssert.isFullyPushedDown(QueryAssertions.java:450)
	at io.trino.plugin.jdbc.BaseJdbcConnectorTest.assertConditionallyPushedDown(BaseJdbcConnectorTest.java:1[366](https://github.com/trinodb/trino/actions/runs/8749315702/job/24010872826?pr=21622#step:19:367))
	at io.trino.plugin.jdbc.BaseJdbcConnectorTest.testLimitPushdown(BaseJdbcConnectorTest.java:928)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1534)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2269)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:495)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:662)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

```
Error:  io.trino.plugin.redshift.TestRedshiftConnectorTest.testComplexJoinPushdown -- Time elapsed: 2.020 s <<< ERROR!
java.lang.IllegalStateException: 
Join node should be present in explain plan, when pushdown is not applied:
        Output[columnNames = [name, orderstatus]]
        │   Layout: [name:varchar(25), orderstatus:varchar(1)]
        └─ ScanFilterProject[table = redshift:Query[SELECT l."orderkey" AS "orderkey_0", l."custkey" AS "custkey_1", l."orderstatus" AS "orderstatus_2", r."nationkey" AS "nationkey_3", r."name" AS "name_4", r."regionkey" AS "regionkey_5" FROM (SELECT "orderkey", "custkey", "orderstatus" FROM "testdb"."test_schema"."orders") l INNER JOIN (SELECT "nationkey", "name", "regionkey" FROM "testdb"."test_schema"."nation") r ON l."orderkey" = r."regionkey"] columns=[orderstatus_2:varchar(1):varchar, custkey_1:bigint:int8, name_4:varchar(25):varchar, nationkey_3:bigint:int8], filterPredicate = ($operator$subtract($operator$add(nationkey, custkey), bigint '3') = bigint '0')]
               Layout: [name:varchar(25), orderstatus:varchar(1)]
               name := name_4:varchar(25):varchar
               orderstatus := orderstatus_2:varchar(1):varchar
               custkey := custkey_1:bigint:int8
               nationkey := nationkey_3:bigint:int8

	at io.trino.sql.query.QueryAssertions$QueryAssert.lambda$joinIsNotFullyPushedDown$9(QueryAssertions.java:550)
	at io.trino.testing.TransactionBuilder.lambda$execute$1(TransactionBuilder.java:130)
	at io.trino.testing.TransactionBuilder.execute(TransactionBuilder.java:162)
	at io.trino.testing.TransactionBuilder.execute(TransactionBuilder.java:129)
	at io.trino.sql.query.QueryAssertions$QueryAssert.joinIsNotFullyPushedDown(QueryAssertions.java:543)
	at io.trino.plugin.jdbc.BaseJdbcConnectorTest.testComplexJoinPushdown(BaseJdbcConnectorTest.java:1341)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1534)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2269)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:495)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:662)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

```
Error:  io.trino.plugin.redshift.TestRedshiftConnectorTest.testJoinPushdown -- Time elapsed: 7.617 s <<< FAILURE!
java.lang.AssertionError: 
Plan does not match, expected [

- node(OutputNode)
    - node(TableScanNode)

] but found [

Output[columnNames = [name, name]]
│   Layout: [name_1:varchar(25), name:varchar(25)]
│   name := name_1
└─ InnerJoin[criteria = (regionkey = regionkey_0), distribution = PARTITIONED]
   │   Layout: [name:varchar(25), name_1:varchar(25)]
   │   Distribution: PARTITIONED
   │   dynamicFilterAssignments = {regionkey_0 -> #df_250}
   ├─ RemoteExchange[type = REPARTITION]
   │  │   Layout: [name:varchar(25), regionkey:bigint]
   │  └─ ScanFilter[table = redshift:test_schema.nation testdb.test_schema.nation columns=[name:varchar(25):varchar, regionkey:bigint:int8], dynamicFilters = {regionkey = #df_250}]
   │         Layout: [name:varchar(25), regionkey:bigint]
   │         name := name:varchar(25):varchar
   │         regionkey := regionkey:bigint:int8
   └─ LocalExchange[partitioning = SINGLE]
      │   Layout: [regionkey_0:bigint, name_1:varchar(25)]
      └─ RemoteExchange[type = REPARTITION]
         │   Layout: [regionkey_0:bigint, name_1:varchar(25)]
         └─ TableScan[table = redshift:test_schema.region testdb.test_schema.region columns=[regionkey:bigint:int8, name:varchar(25):varchar]]
                Layout: [regionkey_0:bigint, name_1:varchar(25)]
                name_1 := name:varchar(25):varchar
                regionkey_0 := regionkey:bigint:int8

]
	at io.trino.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:58)
	at io.trino.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:49)
	at io.trino.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:43)
	at io.trino.sql.query.QueryAssertions$QueryAssert.lambda$isFullyPushedDown$5(QueryAssertions.java:[452](https://github.com/trinodb/trino/actions/runs/8749315702/job/24010872826?pr=21622#step:19:453))
	at io.trino.testing.TransactionBuilder.lambda$execute$1(TransactionBuilder.java:130)
	at io.trino.testing.TransactionBuilder.execute(TransactionBuilder.java:162)
	at io.trino.testing.TransactionBuilder.execute(TransactionBuilder.java:129)
	at io.trino.sql.query.QueryAssertions$QueryAssert.isFullyPushedDown(QueryAssertions.java:450)
	at io.trino.plugin.jdbc.BaseJdbcConnectorTest.testJoinPushdown(BaseJdbcConnectorTest.java:1224)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1534)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2269)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:495)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:662)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Comment by ebyhr** [comment]
Good catch! Let me close this issue.
