### ISSUE TITLE
Flaky test `TestHiveConnectorTest.testCreateTableWithEmptyBucketsAndCompressionCodec`: "Target directory for table already exists"

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#21649]
https://github.com/trinodb/trino/actions/runs/8780949572/job/24091963713?pr=21647

```
Error:  Tests run: 148, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 350.1 s <<< FAILURE! -- in io.trino.plugin.hive.TestHiveConnectorTest
Error:  io.trino.plugin.hive.TestHiveConnectorTest.testCreateTableWithEmptyBucketsAndCompressionCodec -- Time elapsed: 0.095 s <<< FAILURE!
java.lang.AssertionError: Failure for format ORC with properties {}
	at io.trino.plugin.hive.BaseHiveConnectorTest.testWithStorageFormat(BaseHiveConnectorTest.java:9345)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testWithAllStorageFormats(BaseHiveConnectorTest.java:9332)
	at io.trino.plugin.hive.BaseHiveConnectorTest.testCreateTableWithEmptyBucketsAndCompressionCodec(BaseHiveConnectorTest.java:8198)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:218)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:214)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:139)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:570)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:545)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1137)
	at io.trino.$gen.Trino_testversion____20240422_083953_13624.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
	Suppressed: java.lang.Exception: Current plan:
                Output[columnNames = [rows]]
                │   Layout: [rows:bigint]
                └─ TableCommit[target = hive.tpch.test_table_with_compression_none]
                   │   Layout: [rows:bigint]
                   │   Collected statistics:
                   │   aggregations =>
                   │       min[nationkey] => [min_nationkey := min(min)]
                   │       max[nationkey] => [max_nationkey := max(max)]
                   │       approx_distinct[nationkey] => [approx_distinct_nationkey := approx_distinct(approx_distinct)]
                   │       count[nationkey] => [count_nationkey := count(count)]
                   │       count[name] => [count_name := count(count_4)]
                   │       approx_distinct[name] => [approx_distinct_name := approx_distinct(approx_distinct_5)]
                   │       TOTAL_SIZE_IN_BYTES[name] => [total_size_in_bytes_name := $internal$sum_data_size_for_stats(internal_sum_data_size_for_stats)]
                   │       MAX_VALUE_SIZE_IN_BYTES[name] => [max_value_size_in_bytes_name := $internal$max_data_size_for_stats(internal_max_data_size_for_stats)]
                   │       min[regionkey] => [min_regionkey := min(min_6)]
                   │       max[regionkey] => [max_regionkey := max(max_7)]
                   │       approx_distinct[regionkey] => [approx_distinct_regionkey := approx_distinct(approx_distinct_8)]
                   │       count[regionkey] => [count_regionkey := count(count_9)]
                   │       count[comment] => [count_comment := count(count_10)]
                   │       approx_distinct[comment] => [approx_distinct_comment := approx_distinct(approx_distinct_11)]
                   │       TOTAL_SIZE_IN_BYTES[comment] => [total_size_in_bytes_comment := $internal$sum_data_size_for_stats(internal_sum_data_size_for_stats_12)]
                   │       MAX_VALUE_SIZE_IN_BYTES[comment] => [max_value_size_in_bytes_comment := $internal$max_data_size_for_stats(internal_max_data_size_for_stats_13)]
                   │       grouped by => []
                   └─ LocalExchange[partitioning = SINGLE]
                      │   Layout: [partialrows:bigint, fragment:varbinary, min:bigint, max:bigint, approx_distinct:HyperLogLog, count:bigint, count_4:bigint, approx_distinct_5:HyperLogLog, internal_sum_data_size_for_stats:bigint, internal_max_data_size_for_stats:bigint, min_6:bigint, max_7:bigint, approx_distinct_8:HyperLogLog, count_9:bigint, count_10:bigint, approx_distinct_11:HyperLogLog, internal_sum_data_size_for_stats_12:bigint, internal_max_data_size_for_stats_13:bigint]
                      └─ RemoteExchange[type = GATHER]
                         │   Layout: [partialrows:bigint, fragment:varbinary, min:bigint, max:bigint, approx_distinct:HyperLogLog, count:bigint, count_4:bigint, approx_distinct_5:HyperLogLog, internal_sum_data_size_for_stats:bigint, internal_max_data_size_for_stats:bigint, min_6:bigint, max_7:bigint, approx_distinct_8:HyperLogLog, count_9:bigint, count_10:bigint, approx_distinct_11:HyperLogLog, internal_sum_data_size_for_stats_12:bigint, internal_max_data_size_for_stats_13:bigint]
                         └─ TableWriter[]
                            │   Layout: [partialrows:bigint, fragment:varbinary, min:bigint, max:bigint, approx_distinct:HyperLogLog, count:bigint, count_4:bigint, approx_distinct_5:HyperLogLog, internal_sum_data_size_for_stats:bigint, internal_max_data_size_for_stats:bigint, min_6:bigint, max_7:bigint, approx_distinct_8:HyperLogLog, count_9:bigint, count_10:bigint, approx_distinct_11:HyperLogLog, internal_sum_data_size_for_stats_12:bigint, internal_max_data_size_for_stats_13:bigint]
                            │   nationkey := nationkey
                            │   name := name
                            │   regionkey := regionkey
                            │   comment := comment
                            │   Collected statistics:
                            │   aggregations =>
                            │       min[nationkey] => [min := min(nationkey)]
                            │       max[nationkey] => [max := max(nationkey)]
                            │       approx_distinct[nationkey] => [approx_distinct := approx_distinct(nationkey)]
                            │       count[nationkey] => [count := count(nationkey)]
                            │       count[name] => [count_4 := count(name)]
                            │       approx_distinct[name] => [approx_distinct_5 := approx_distinct(name)]
                            │       TOTAL_SIZE_IN_BYTES[name] => [internal_sum_data_size_for_stats := $internal$sum_data_size_for_stats(name)]
                            │       MAX_VALUE_SIZE_IN_BYTES[name] => [internal_max_data_size_for_stats := $internal$max_data_size_for_stats(name)]
                            │       min[regionkey] => [min_6 := min(regionkey)]
                            │       max[regionkey] => [max_7 := max(regionkey)]
                            │       approx_distinct[regionkey] => [approx_distinct_8 := approx_distinct(regionkey)]
                            │       count[regionkey] => [count_9 := count(regionkey)]
                            │       count[comment] => [count_10 := count(comment)]
                            │       approx_distinct[comment] => [approx_distinct_11 := approx_distinct(comment)]
                            │       TOTAL_SIZE_IN_BYTES[comment] => [internal_sum_data_size_for_stats_12 := $internal$sum_data_size_for_stats(comment)]
                            │       MAX_VALUE_SIZE_IN_BYTES[comment] => [internal_max_data_size_for_stats_13 := $internal$max_data_size_for_stats(comment)]
                            │       grouped by => []
                            └─ LocalExchange[partitioning = hive:HivePartitioningHandle{buckets=7, hiveTypes=[bigint]} (scale writers), arguments = [regionkey::bigint]]
                               │   Layout: [nationkey:bigint, name:varchar(25), regionkey:bigint, comment:varchar(152)]
                               └─ RemoteExchange[scaleWriters = true, type = REPARTITION]
                                  │   Layout: [nationkey:bigint, name:varchar(25), regionkey:bigint, comment:varchar(152)]
                                  └─ TableScan[table = tpch:tiny:nation]
                                         Layout: [nationkey:bigint, name:varchar(25), regionkey:bigint, comment:varchar(152)]
                                         name := tpch:name
                                         nationkey := tpch:nationkey
                                         comment := tpch:comment
                                         regionkey := tpch:regionkey

		at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:84)
		... 17 more

```

**Comment by ebyhr** [comment]
The table name looks conflicted between testCreateTableWithCompressionCodec and testCreateTableWithEmptyBucketsAndCompressionCodec. 

@pajaks Can you take a look?

**Comment by losipiuk** [comment]
Failed for https://github.com/trinodb/trino/issues/21649
