### ISSUE TITLE
java.lang.NoClassDefFoundError: io/trino/plugin/base/metrics/LongCount

### ISSUE THREAD

**Issue by novisfff** [trinodb/trino#21640]
When I execute an SQL query on the Paimon catalog, an error occurs.
java:17
trino:427
```
java.lang.NoClassDefFoundError: io/trino/plugin/base/metrics/LongCount
	at io.trino.plugin.hive.orc.OrcPageSource.getMetrics(OrcPageSource.java:259)
	at org.apache.paimon.trino.DirectTrinoPageSource.getMetrics(DirectTrinoPageSource.java:115)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:321)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_427____20240420_045354_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: io.trino.plugin.base.metrics.LongCount
	... 15 more
```

classpath:
```
java.class.path=/opt/trino-server-427/lib/HdrHistogram-2.1.9.jar\:/opt/trino-server-427/lib/RoaringBitmap-0.9.49.jar\:/opt/trino-server-427/lib/accessors-smart-2.5.0.jar\:/opt/trino-server-427/lib/aircompressor-0.25.jar\:/opt/trino-server-427/lib/angus-activation-2.0.0.jar\:/opt/trino-server-427/lib/annotations-19.0.0.jar\:/opt/trino-server-427/lib/antlr4-runtime-4.13.1.jar\:/opt/trino-server-427/lib/aopalliance-1.0.jar\:/opt/trino-server-427/lib/asm-9.5.jar\:/opt/trino-server-427/lib/asm-analysis-9.5.jar\:/opt/trino-server-427/lib/asm-tree-9.5.jar\:/opt/trino-server-427/lib/asm-util-9.5.jar\:/opt/trino-server-427/lib/bootstrap-235.jar\:/opt/trino-server-427/lib/byte-buddy-1.14.8.jar\:/opt/trino-server-427/lib/bytecode-1.5.jar\:/opt/trino-server-427/lib/checker-qual-3.37.0.jar\:/opt/trino-server-427/lib/classmate-1.5.1.jar\:/opt/trino-server-427/lib/commons-codec-1.16.0.jar\:/opt/trino-server-427/lib/commons-math3-3.6.1.jar\:/opt/trino-server-427/lib/concurrent-235.jar\:/opt/trino-server-427/lib/configuration-235.jar\:/opt/trino-server-427/lib/content-type-2.2.jar\:/opt/trino-server-427/lib/discovery-235.jar\:/opt/trino-server-427/lib/discovery-server-1.36.jar\:/opt/trino-server-427/lib/error_prone_annotations-2.22.0.jar\:/opt/trino-server-427/lib/esri-geometry-api-2.2.4.jar\:/opt/trino-server-427/lib/event-235.jar\:/opt/trino-server-427/lib/event-http-235.jar\:/opt/trino-server-427/lib/failsafe-3.3.2.jar\:/opt/trino-server-427/lib/failureaccess-1.0.1.jar\:/opt/trino-server-427/lib/fastutil-8.5.12.jar\:/opt/trino-server-427/lib/guava-32.1.1-jre.jar\:/opt/trino-server-427/lib/guice-7.0.0.jar\:/opt/trino-server-427/lib/hibernate-validator-8.0.0.Final.jar\:/opt/trino-server-427/lib/hk2-api-3.0.4.jar\:/opt/trino-server-427/lib/hk2-locator-3.0.4.jar\:/opt/trino-server-427/lib/hk2-utils-3.0.4.jar\:/opt/trino-server-427/lib/http-client-235.jar\:/opt/trino-server-427/lib/http-server-235.jar\:/opt/trino-server-427/lib/http2-client-11.0.15.jar\:/opt/trino-server-427/lib/http2-common-11.0.15.jar\:/opt/trino-server-427/lib/http2-hpack-11.0.15.jar\:/opt/trino-server-427/lib/http2-http-client-transport-11.0.15.jar\:/opt/trino-server-427/lib/http2-server-11.0.15.jar\:/opt/trino-server-427/lib/istack-commons-runtime-4.1.1.jar\:/opt/trino-server-427/lib/j2objc-annotations-2.8.jar\:/opt/trino-server-427/lib/jackson-annotations-2.15.2.jar\:/opt/trino-server-427/lib/jackson-core-2.15.2.jar\:/opt/trino-server-427/lib/jackson-databind-2.15.2.jar\:/opt/trino-server-427/lib/jackson-dataformat-smile-2.15.2.jar\:/opt/trino-server-427/lib/jackson-datatype-guava-2.15.2.jar\:/opt/trino-server-427/lib/jackson-datatype-jdk8-2.15.2.jar\:/opt/trino-server-427/lib/jackson-datatype-joda-2.15.2.jar\:/opt/trino-server-427/lib/jackson-datatype-jsr310-2.15.2.jar\:/opt/trino-server-427/lib/jackson-module-parameter-names-2.15.2.jar\:/opt/trino-server-427/lib/jakarta.activation-api-2.1.0.jar\:/opt/trino-server-427/lib/jakarta.annotation-api-2.1.1.jar\:/opt/trino-server-427/lib/jakarta.inject-api-2.0.1.jar\:/opt/trino-server-427/lib/jakarta.validation-api-3.0.2.jar\:/opt/trino-server-427/lib/jakarta.ws.rs-api-3.1.0.jar\:/opt/trino-server-427/lib/jakarta.xml.bind-api-4.0.0.jar\:/opt/trino-server-427/lib/javassist-3.29.2-GA.jar\:/opt/trino-server-427/lib/jaxb-core-4.0.2.jar\:/opt/trino-server-427/lib/jaxb-runtime-4.0.2.jar\:/opt/trino-server-427/lib/jaxrs-235.jar\:/opt/trino-server-427/lib/jboss-logging-3.4.1.Final.jar\:/opt/trino-server-427/lib/jcip-annotations-1.0-1.jar\:/opt/trino-server-427/lib/jcl-over-slf4j-2.0.7.jar\:/opt/trino-server-427/lib/jersey-client-3.1.2.jar\:/opt/trino-server-427/lib/jersey-common-3.1.2.jar\:/opt/trino-server-427/lib/jersey-container-servlet-3.1.2.jar\:/opt/trino-server-427/lib/jersey-container-servlet-core-3.1.2.jar\:/opt/trino-server-427/lib/jersey-hk2-3.1.2.jar\:/opt/trino-server-427/lib/jersey-server-3.1.2.jar\:/opt/trino-server-427/lib/jetty-alpn-client-11.0.15.jar\:/opt/trino-server-427/lib/jetty-alpn-java-client-11.0.15.jar\:/opt/trino-server-427/lib/jetty-client-11.0.15.jar\:/opt/trino-server-427/lib/jetty-http-11.0.15.jar\:/opt/trino-server-427/lib/jetty-io-11.0.15.jar\:/opt/trino-server-427/lib/jetty-jakarta-servlet-api-5.0.2.jar\:/opt/trino-server-427/lib/jetty-jmx-11.0.15.jar\:/opt/trino-server-427/lib/jetty-security-11.0.15.jar\:/opt/trino-server-427/lib/jetty-server-11.0.15.jar\:/opt/trino-server-427/lib/jetty-servlet-11.0.15.jar\:/opt/trino-server-427/lib/jetty-util-11.0.15.jar\:/opt/trino-server-427/lib/jjwt-api-0.11.5.jar\:/opt/trino-server-427/lib/jjwt-impl-0.11.5.jar\:/opt/trino-server-427/lib/jjwt-jackson-0.11.5.jar\:/opt/trino-server-427/lib/jmx-235.jar\:/opt/trino-server-427/lib/jmx-http-235.jar\:/opt/trino-server-427/lib/jmx-http-rpc-235.jar\:/opt/trino-server-427/lib/jmxutils-1.23.jar\:/opt/trino-server-427/lib/jna-5.13.0.jar\:/opt/trino-server-427/lib/jna-platform-5.13.0.jar\:/opt/trino-server-427/lib/joda-time-2.12.5.jar\:/opt/trino-server-427/lib/jol-core-0.17.jar\:/opt/trino-server-427/lib/joni-2.1.5.3.jar\:/opt/trino-server-427/lib/json-235.jar\:/opt/trino-server-427/lib/json-simple-1.1.1.jar\:/opt/trino-server-427/lib/json-smart-2.5.0.jar\:/opt/trino-server-427/lib/jsr305-3.0.2.jar\:/opt/trino-server-427/lib/jts-core-1.16.1.jar\:/opt/trino-server-427/lib/jts-io-common-1.16.1.jar\:/opt/trino-server-427/lib/log-235.jar\:/opt/trino-server-427/lib/kotlin-stdlib-1.9.0.jar\:/opt/trino-server-427/lib/kotlin-stdlib-common-1.9.0.jar\:/opt/trino-server-427/lib/kotlin-stdlib-jdk7-1.9.0.jar\:/opt/trino-server-427/lib/kotlin-stdlib-jdk8-1.9.0.jar\:/opt/trino-server-427/lib/lang-tag-1.7.jar\:/opt/trino-server-427/lib/leveldb-0.12.jar\:/opt/trino-server-427/lib/leveldb-api-0.12.jar\:/opt/trino-server-427/lib/log-manager-235.jar\:/opt/trino-server-427/lib/log4j-api-2.17.1.jar\:/opt/trino-server-427/lib/log4j-over-slf4j-2.0.7.jar\:/opt/trino-server-427/lib/log4j-to-slf4j-2.17.1.jar\:/opt/trino-server-427/lib/logback-core-1.4.8.jar\:/opt/trino-server-427/lib/lucene-analyzers-common-8.4.1.jar\:/opt/trino-server-427/lib/lucene-core-8.4.1.jar\:/opt/trino-server-427/lib/modernizer-maven-annotations-2.6.0.jar\:/opt/trino-server-427/lib/nimbus-jose-jwt-9.35.jar\:/opt/trino-server-427/lib/node-235.jar\:/opt/trino-server-427/lib/oauth2-oidc-sdk-10.15-jdk11.jar\:/opt/trino-server-427/lib/okhttp-4.11.0.jar\:/opt/trino-server-427/lib/okio-3.3.0.jar\:/opt/trino-server-427/lib/okio-jvm-3.3.0.jar\:/opt/trino-server-427/lib/openmetrics-235.jar\:/opt/trino-server-427/lib/opentelemetry-api-1.30.1.jar\:/opt/trino-server-427/lib/opentelemetry-api-events-1.30.1-alpha.jar\:/opt/trino-server-427/lib/opentelemetry-context-1.30.1.jar\:/opt/trino-server-427/lib/opentelemetry-exporter-common-1.30.1.jar\:/opt/trino-server-427/lib/opentelemetry-exporter-otlp-1.30.1.jar\:/opt/trino-server-427/lib/opentelemetry-exporter-otlp-common-1.30.1.jar\:/opt/trino-server-427/lib/opentelemetry-exporter-sender-okhttp-1.30.1.jar\:/opt/trino-server-427/lib/opentelemetry-extension-incubator-1.30.1-alpha.jar\:/opt/trino-server-427/lib/opentelemetry-sdk-1.30.1.jar\:/opt/trino-server-427/lib/opentelemetry-sdk-common-1.30.1.jar\:/opt/trino-server-427/lib/opentelemetry-sdk-extension-autoconfigure-spi-1.30.1.jar\:/opt/trino-server-427/lib/opentelemetry-sdk-logs-1.30.1.jar\:/opt/trino-server-427/lib/opentelemetry-sdk-metrics-1.30.1.jar\:/opt/trino-server-427/lib/opentelemetry-sdk-trace-1.30.1.jar\:/opt/trino-server-427/lib/opentelemetry-semconv-1.30.1-alpha.jar\:/opt/trino-server-427/lib/osgi-resource-locator-1.0.3.jar\:/opt/trino-server-427/lib/oshi-core-6.4.5.jar\:/opt/trino-server-427/lib/pcollections-4.0.1.jar\:/opt/trino-server-427/lib/re2j-1.6.jar\:/opt/trino-server-427/lib/security-235.jar\:/opt/trino-server-427/lib/shims-0.9.49.jar\:/opt/trino-server-427/lib/slf4j-api-2.0.7.jar\:/opt/trino-server-427/lib/slf4j-jdk14-2.0.7.jar\:/opt/trino-server-427/lib/slice-2.2.jar\:/opt/trino-server-427/lib/stats-235.jar\:/opt/trino-server-427/lib/stream-2.9.8.jar\:/opt/trino-server-427/lib/trace-token-235.jar\:/opt/trino-server-427/lib/tracing-235.jar\:/opt/trino-server-427/lib/trino-array-427.jar\:/opt/trino-server-427/lib/trino-cache-427.jar\:/opt/trino-server-427/lib/trino-client-427.jar\:/opt/trino-server-427/lib/trino-geospatial-toolkit-427.jar\:/opt/trino-server-427/lib/trino-grammar-427.jar\:/opt/trino-server-427/lib/trino-main-427.jar\:/opt/trino-server-427/lib/trino-matching-427.jar\:/opt/trino-server-427/lib/trino-memory-context-427.jar\:/opt/trino-server-427/lib/trino-parser-427.jar\:/opt/trino-server-427/lib/trino-plugin-toolkit-427.jar\:/opt/trino-server-427/lib/trino-server-main-427.jar\:/opt/trino-server-427/lib/trino-spi-427.jar\:/opt/trino-server-427/lib/txw2-4.0.2.jar\:/opt/trino-server-427/lib/units-1.10.jar
```

**Comment by wendigo** [comment]
Seems like it's faulty paimon integration. Please report it there

**Comment by novisfff** [comment]
> Seems like it's faulty paimon integration. Please report it there

Thank you. Copy `trino-plugin-toolkit-427.jar` to `plugin/paimon/trino-plugin-toolkit-427.jar` fix it
