### ISSUE TITLE
"Table has exceeded max number of active streams" error happens in BigQuery connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#21651]
https://github.com/trinodb/trino/actions/runs/8751706370/job/24017920223?pr=21628

```
Error:  io.trino.plugin.bigquery.TestBigQueryQueryFailureRecoveryTest.testCreateTable -- Time elapsed: 196.7 s <<< ERROR!
io.trino.testing.QueryFailedException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Table has exceeded max number of active streams. Please use existing streams or finalize unused streams. Table=505084745097:tpch.tmp_trino_1516d0b4_12bccd97. ActiveStreamCount=916035320. MaxAllowed=20000. Entity: projects/sep-bq-cicd/datasets/tpch/tables/tmp_trino_1516d0b4_12bccd97
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
	at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:501)
	at io.trino.testing.DistributedQueryRunner.executeWithPlan(DistributedQueryRunner.java:490)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.execute(BaseFailureRecoveryTest.java:534)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.executeExpected(BaseFailureRecoveryTest.java:494)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.lambda$failsWithoutRetries$10(BaseFailureRecoveryTest.java:707)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.getFailureStageId(BaseFailureRecoveryTest.java:731)
	at io.trino.testing.BaseFailureRecoveryTest$FailureRecoveryAssert.failsWithoutRetries(BaseFailureRecoveryTest.java:707)
	at io.trino.testing.BaseFailureRecoveryTest.testNonSelect(BaseFailureRecoveryTest.java:367)
	at io.trino.testing.BaseFailureRecoveryTest.testTableModification(BaseFailureRecoveryTest.java:307)
	at io.trino.testing.BaseFailureRecoveryTest.testTableModification(BaseFailureRecoveryTest.java:302)
	at io.trino.testing.BaseFailureRecoveryTest.testCreateTable(BaseFailureRecoveryTest.java:186)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE table_2f3xb7iems AS SELECT * FROM orders
		at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:508)
		... 17 more
Caused by: com.google.api.gax.rpc.FailedPreconditionException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Table has exceeded max number of active streams. Please use existing streams or finalize unused streams. Table=505084745097:tpch.tmp_trino_1516d0b4_12bccd97. ActiveStreamCount=916035320. MaxAllowed=20000. Entity: projects/sep-bq-cicd/datasets/tpch/tables/tmp_trino_1516d0b4_12bccd97
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:102)
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1130)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1298)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1059)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:809)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:568)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:570)
	at io.opentelemetry.instrumentation.grpc.v1_6.TracingClientInterceptor$TracingClientCall$TracingClientCallListener.onClose(TracingClientInterceptor.java:159)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.bigquery.storage.v1.BigQueryWriteClient.createWriteStream(BigQueryWriteClient.java:373)
		at io.trino.plugin.bigquery.BigQueryPageSink.getOrCreateWriteStream(BigQueryPageSink.java:124)
		at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
		at io.trino.plugin.bigquery.BigQueryPageSink.insertWithCommitted(BigQueryPageSink.java:108)
		at io.trino.plugin.bigquery.BigQueryPageSink.appendPage(BigQueryPageSink.java:102)
		at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:276)
		at io.trino.operator.Driver.processInternal(Driver.java:408)
		at io.trino.operator.Driver.lambda$process$8(Driver.java:306)
		at io.trino.operator.Driver.tryWithLock(Driver.java:709)
		at io.trino.operator.Driver.process(Driver.java:298)
		at io.trino.operator.Driver.processForDuration(Driver.java:269)
		at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:890)
		at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:76)
		at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:191)
		at io.trino.$gen.Trino_testversion____20240419_100342_321.run(Unknown Source)
		at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:192)
		at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:174)
		at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:161)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
		at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
		at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
		at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
		... 3 more
Caused by: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Table has exceeded max number of active streams. Please use existing streams or finalize unused streams. Table=505084745097:tpch.tmp_trino_1516d0b4_12bccd97. ActiveStreamCount=916035320. MaxAllowed=20000. Entity: projects/sep-bq-cicd/datasets/tpch/tables/tmp_trino_1516d0b4_12bccd97
	at io.grpc.Status.asRuntimeException(Status.java:533)
	... 18 more
```

**Comment by randalpinto** [comment]
Any insight in what this error could be? I am getting a similar error in one of my projects with some huge ActiveStreamCount number like in you case but cannot logically explain how my system would have hundreds of millions of active streams as I am not even attempting to open those many streams.

**Comment by jihedbfr-art** [comment]
Looking at BigQueryPageSink, abort() only calls client.close() - it never
finalizes or explicitly closes the WriteStream that got created in
getOrCreateWriteStream(). The stream type is COMMITTED, not PENDING, so I'm not
100% sure of BigQuery's cleanup behavior there, but if a task gets retried a lot
under fault-tolerant execution (which is what was happening in the failing test),
each retry creates a brand new page sink and a brand new write stream without
cleaning up the one from the previous attempt. Might be worth checking if that
adds up over enough retries.

The reported ActiveStreamCount (916035320) is obviously not a real count of
actual open streams, so that part's probably just a weird number from BigQuery's
side, but the underlying "streams aren't being cleaned up on abort" thing seems
worth checking regardless.
