### ISSUE TITLE
Deployment trino-server-445  NullPointerException

### ISSUE THREAD

**Issue by jxlining** [trinodb/trino#21669]
/opt/programs/trino-server/etc/resource-groups.properties
resource-groups.configuration-manager=db
resource-groups.config-db-url=jdbc:mysql://xxxxx:3306/resource_groups_445
resource-groups.config-db-user=mytrino
resource-groups.config-db-password=xxxxx

2024-04-23T17:47:03.808+0800    INFO    main    io.trino.plugin.resourcegroups.db.FlywayMigration       Performed 0 migrations
2024-04-23T17:47:03.819+0800    ERROR   main    io.trino.server.Server  null
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:233)
        at com.google.common.collect.Maps.fromProperties(Maps.java:1429)
        at io.airlift.configuration.ConfigurationLoader.getSystemProperties(ConfigurationLoader.java:70)
        at io.airlift.bootstrap.Bootstrap.configure(Bootstrap.java:177)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:246)
        at io.trino.plugin.resourcegroups.db.DbResourceGroupConfigurationManagerFactory.create(DbResourceGroupConfigurationManagerFactory.java:57)
        at io.trino.execution.resourcegroups.InternalResourceGroupManager.setConfigurationManager(InternalResourceGroupManager.java:162)
        at io.trino.execution.resourcegroups.InternalResourceGroupManager.loadConfigurationManager(InternalResourceGroupManager.java:146)
        at io.trino.server.Server.doStart(Server.java:174)
        at io.trino.server.Server.lambda$start$0(Server.java:94)
        at io.trino.$gen.Trino_445____20240423_094644_1.run(Unknown Source)
        at io.trino.server.Server.start(Server.java:94)
        at io.trino.server.TrinoServer.main(TrinoServer.java:38)
        
not using the resource groups properties method     is  success  

```[tasklist]
### Tasks
```

**Comment by jxlining** [comment]
trino-403  using the resource groups properties  issuccess

**Comment by akenO8** [comment]
I also encountered this problem when I upgraded to 445, is it the mysql version problem?

**Comment by akenO8** [comment]
I thought it was the `polyglot.engine.WarnInterpreterOnly` attribute is not set at 445.
Add `-Dpolyglot.engine.WarnInterpreterOnly=[true/false]` to jvm.config, It looks like both true and false will work.

@ebyhr Does it have anything to do with this?
https://github.com/flyway/flyway/issues/3882

**Comment by ebyhr** [comment]
Closing as https://github.com/trinodb/trino/pull/21641. Please reopen if this issue still happens with newer versions.

**Comment by findepi** [comment]
I believe the problem remains.

**Comment by findepi** [comment]
This should help: https://github.com/airlift/airlift/pull/1167

**Comment by findepi** [comment]
airlift change merged. let's close this issue when we upgrade airlift.

**Comment by akenO8** [comment]
I think your pr does not solve this problem. 
When the initial system properties have null, it is inevitable. Should we check or avoid these illegal system properties in `getSystemProperties()`?

**Comment by akenO8** [comment]
![image](https://github.com/trinodb/trino/assets/37773807/bf9c27a6-b990-4379-bd3b-655c0e8541ab)
I'm sorry I didn't understand you.
As far as validate properties are concerned, I think we can add a method to remove validate property. I implemented it and avoided the exception of this issue.
