### ISSUE TITLE
Unable to insert a large volume of data into S3 bucket

### ISSUE THREAD

**Issue by SGH-N** [trinodb/trino#21680]
Hello,

I'm using Trino 443 to copy data to S3 bucket using the Hive connector. This works perfectly with small data volumes, but I encountered an error when trying to insert a large volume of data (800GB) into S3.

java.sql.SQLException: Query failed (#20240419_135144_00139_3ujh7): Error committing write to Hive
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:294)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:254)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Unknown Source)
	at io.trino.jdbc.TrinoResultSet$AsyncIterator.lambda$new$1(TrinoResultSet.java:179)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.trino.spi.TrinoException: Error committing write to Hive
	at io.trino.plugin.hive.orc.OrcFileWriter.commit(OrcFileWriter.java:197)
	at io.trino.plugin.hive.HiveWriter.commit(HiveWriter.java:92)
	at io.trino.plugin.hive.HivePageSink.closeWriter(HivePageSink.java:346)
	at io.trino.plugin.hive.HivePageSink.doInsertSinkFinish(HivePageSink.java:220)
	at io.trino.plugin.hive.HivePageSink.finish(HivePageSink.java:194)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:84)
	at io.trino.operator.TableWriterOperator.finish(TableWriterOperator.java:235)
	at io.trino.operator.Driver.processInternal(Driver.java:416)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
	at io.trino.operator.Driver.process(Driver.java:293)
	at io.trino.operator.Driver.processForDuration(Driver.java:264)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:76)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:191)
	at io.trino.$gen.Trino_443____20240419_105431_2.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:192)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:174)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:161)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 1713537579694516; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.close(TrinoS3FileSystem.java:1873)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:77)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at io.trino.filesystem.hdfs.HdfsOutputStream.close(HdfsOutputStream.java:87)
	at io.airlift.slice.OutputStreamSliceOutput.close(OutputStreamSliceOutput.java:88)
	at io.trino.orc.OutputStreamOrcDataSink.close(OutputStreamOrcDataSink.java:81)
	at io.trino.orc.OrcWriter.close(OrcWriter.java:462)
	at io.trino.plugin.hive.orc.OrcFileWriter.commit(OrcFileWriter.java:187)
	... 25 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 1713537579694516; S3 Extended Request ID: null; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5520)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5467)
	at com.amazonaws.services.s3.AmazonS3Client.completeMultipartUpload(AmazonS3Client.java:3671)
	at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.finishUpload(TrinoS3FileSystem.java:1991)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.close(TrinoS3FileSystem.java:1869)
	... 34 more
	Suppressed: com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 1713535275984798; S3 Extended Request ID: null; Proxy: null)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
		at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
		at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
		at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5520)
		at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5467)
		at com.amazonaws.services.s3.AmazonS3Client.abortMultipartUpload(AmazonS3Client.java:3623)
		at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.lambda$abortUpload$1(TrinoS3FileSystem.java:2000)
		at java.base/java.util.Optional.ifPresent(Optional.java:178)
		at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.abortUpload(TrinoS3FileSystem.java:2000)
		at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.abortUploadSuppressed(TrinoS3FileSystem.java:2007)
		at io.trino.hdfs.s3.TrinoS3FileSystem$TrinoS3StreamingOutputStream.close(TrinoS3FileSystem.java:1872)
		... 34 more

query I use: create table hive_s3.s3.tble  with (format='ORC',  partitioning  = array['nationkey'])  as * from hive.sc.table

Hive properties:
          connector.name=hive
          hive.metastore.uri=thrift://hive:9083
          hive.s3.aws-access-key=xxx
          hive.s3.aws-secret-key=xxx
          hive.s3.endpoint=https://xx:10445
          hive.non-managed-table-writes-enabled=true
          hive.recursive-directories=true
          hive.security=allow-all
          hive.metastore.thrift.delete-files-on-drop=true
          hive.compression-codec=ZSTD
          hive.partition-projection-enabled=true
          hive.s3.streaming.enabled=true
          hive.s3.streaming.part-size=5MB

**Comment by marcinsbd** [comment]
Can you increase hive.s3.streaming.part-size=5MB up to 100MB  and check if it  solve the issue?
