### ISSUE TITLE
[Trino JDBC] NoClassDefFoundError io/opentelemetry/semconv/SemanticAttributes

### ISSUE THREAD

**Issue by gaeljw** [trinodb/trino#21689]
## Preamble

I'm logging this as an issue to help other people facing it to find the explanation and solution but I believe the root cause is the same as the one described in https://github.com/trinodb/trino/issues/21104.

## Issue

Getting `java.lang.NoClassDefFoundError: io/opentelemetry/semconv/SemanticAttributes` when:
- using `trino-jdbc` 445
- having `io.opentelemetry:opentelemetry-api` (and others OTEL dependencies) as a dependency in the classpath with a relatively old version
- BUT NOT having `io.opentelemetry.semconv:opentelemetry-semconv` as a dependency in the classpath because it's still the old `io.opentelemetry:opentelemetry-semconv` (notice the groupId change) that is pulled in the classpath

Complete stacktrace:
<details>
<pre>
[error] Caused by: java.lang.NoClassDefFoundError: io/opentelemetry/semconv/SemanticAttributes
[error]     at io.trino.jdbc.$internal.opentelemetry.instrumentation.api.semconv.http.HttpCommonAttributesExtractor.onStart(HttpCommonAttributesExtractor.java:61)
[error]     at io.trino.jdbc.$internal.opentelemetry.instrumentation.api.semconv.http.HttpClientAttributesExtractor.onStart(HttpClientAttributesExtractor.java:71)
[error]     at io.trino.jdbc.$internal.opentelemetry.instrumentation.api.instrumenter.Instrumenter.doStart(Instrumenter.java:179)
[error]     at io.trino.jdbc.$internal.opentelemetry.instrumentation.api.instrumenter.Instrumenter.startAndEnd(Instrumenter.java:158)
[error]     at io.trino.jdbc.$internal.opentelemetry.instrumentation.api.instrumenter.Instrumenter$1.startAndEnd(Instrumenter.java:272)
[error]     at io.trino.jdbc.$internal.opentelemetry.instrumentation.api.internal.InstrumenterUtil.startAndEnd(InstrumenterUtil.java:44)
[error]     at io.trino.jdbc.$internal.opentelemetry.instrumentation.okhttp.v3_0.internal.ConnectionErrorSpanInterceptor.intercept(ConnectionErrorSpanInterceptor.java:47)
[error]     at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[error]     at io.trino.jdbc.$internal.opentelemetry.instrumentation.okhttp.v3_0.ContextInterceptor.intercept(ContextInterceptor.java:28)
[error]     at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
[error]     at io.trino.jdbc.$internal.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
[error]     at io.trino.jdbc.$internal.okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
[error]     at io.trino.jdbc.$internal.opentelemetry.instrumentation.okhttp.v3_0.TracingCallFactory$TracingCall.execute(TracingCallFactory.java:100)
[error]     at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:113)
[error]     at io.trino.jdbc.$internal.client.StatementClientV1.executeRequest(StatementClientV1.java:401)
[error]     at io.trino.jdbc.$internal.client.StatementClientV1.<init>(StatementClientV1.java:132)
[error]     at io.trino.jdbc.$internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:28)
[error]     at io.trino.jdbc.TrinoConnection.startQuery(TrinoConnection.java:771)
[error]     at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:252)
[error]     at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
</pre>
</details>

## Fix

Force to have a more recent version of opentelemetry dependencies in the classpath, especially the `io.opentelemetry.semconv:opentelemetry-semconv`  one.

Note that this is somehow standard version management as we are used to in Maven _but_ here the fact that the `opentelemetry-semconv` changed its groupId over time is adding confusion to the mix. Be sure to check the groupId of the dependency you have in your classpath.

**Comment by gaeljw** [comment]
Closing in favour of https://github.com/trinodb/trino/issues/21104

**Comment by gaeljw** [comment]
I reopen because it's actually a different issue than #21104: having `trino-jdbc` + `opentelemetry-api` in the classpath and using the opentelemetry java agent leads to this issue. It's not only a dependency version conflict. It's a missing needed dependency (not pulled via Maven POM declarations).

**Comment by kaushik-revefi** [comment]
Hitting the same issue

**Comment by lukaseder** [comment]
I'm running into this as well. It appears to me that shading isn't done properly for various opentelemetry dependencies?

```xml
                <relocation>
                  <pattern>io.opentelemetry.extension</pattern>
                  <shadedPattern>${shadeBase}.opentelemetry.extension</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>io.opentelemetry.instrumentation</pattern>
                  <shadedPattern>${shadeBase}.opentelemetry.instrumentation</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>io.opentelemetry.api.incubator</pattern>
                  <shadedPattern>${shadeBase}.opentelemetry.api.incubator</shadedPattern>
                </relocation>
```

Alternatively, make the API a non-provided dependency:

```xml
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-api</artifactId>
      <version>1.39.0</version>
      <scope>provided</scope>
    </dependency>
```

**Comment by wendigo** [comment]
OTEL shouldn't be shaded at all. I'll merge soon a change that excludes OTEL entirely so it will be provided only externally.
