### ISSUE TITLE
Flaky test `TestSqlFunctions.testSession`

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#21741]
https://github.com/trinodb/trino/actions/runs/8853474329/job/24314568185?pr=21730

```
Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.409 s <<< FAILURE! -- in io.trino.operator.scalar.interval.TestIntervalDayTime
Error:  io.trino.sql.routine.TestSqlFunctions.testSession -- Time elapsed: 0.484 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: 1.714162123E9
 but was: 1.714162124E9
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.trino.sql.routine.TestSqlFunctions.lambda$testSingleExpression$16(TestSqlFunctions.java:544)
	at io.trino.sql.routine.TestSqlFunctions.lambda$assertFunction$17(TestSqlFunctions.java:557)
	at io.trino.testing.TransactionBuilder.lambda$execute$1(TransactionBuilder.java:130)
	at io.trino.testing.TransactionBuilder.execute(TransactionBuilder.java:162)
	at io.trino.testing.TransactionBuilder.execute(TransactionBuilder.java:129)
	at io.trino.sql.routine.TestSqlFunctions.assertFunction(TestSqlFunctions.java:552)
	at io.trino.sql.routine.TestSqlFunctions.testSingleExpression(TestSqlFunctions.java:537)
	at io.trino.sql.routine.TestSqlFunctions.testSingleExpression(TestSqlFunctions.java:525)
	at io.trino.sql.routine.TestSqlFunctions.testSession(TestSqlFunctions.java:507)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1534)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2269)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:495)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:662)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/20618085991/job/59214640308?pr=27803

**Comment by findepi** [comment]
For the record, here is the failing assertion
```
testSingleExpression(UNKNOWN, null, DOUBLE, floor(SESSION.getStart().toEpochMilli() / 1000.0), "floor(to_unixtime(localtimestamp))");
```

`to_unixtime` returns a double value and flooring it should yield second-of-epoch
`SESSION.getStart().toEpochMilli()` is obviously positive, divided by 1000 would return second-of-epoch
The test should work.

The failure is off by 1.0 on the compared values. It's not a double rounding problem. Double has enough significant decimal digits not to have an error like that.

The test fails when testing session start time (Instant) has nano-of-second is at least `999_499_500`.
Clearly it's an effect of rounding twice something.

**Comment by findepi** [comment]
Both rounding appear next to each other

- https://github.com/trinodb/trino/issues/27806

**Comment by findepi** [comment]
Once we merge 
- https://github.com/trinodb/trino/pull/27808

~then the test will work correctly for  session start time (Instant) has nano-of-second being 999_499_500.~

~but it will still fail when nano-of-second is 999_500_000 or more.~

<details>

<summary>how to repro diff</summary>

```diff
diff --git core/trino-main/src/test/java/io/trino/sql/routine/TestSqlFunctions.java core/trino-main/src/test/java/io/trino/sql/routine/TestSqlFunctions.java
index 83c8e57f5b0..9d87c4334f2 100644
--- core/trino-main/src/test/java/io/trino/sql/routine/TestSqlFunctions.java
+++ core/trino-main/src/test/java/io/trino/sql/routine/TestSqlFunctions.java
@@ -43,6 +43,7 @@ import org.intellij.lang.annotations.Language;
 import org.junit.jupiter.api.Test;

 import java.lang.invoke.MethodHandle;
+import java.time.Instant;
 import java.util.Map;
 import java.util.concurrent.atomic.AtomicLong;

@@ -75,7 +76,9 @@ class TestSqlFunctions
     private static final PlannerContext PLANNER_CONTEXT = plannerContextBuilder()
             .withTransactionManager(TRANSACTION_MANAGER)
             .build();
-    private static final Session SESSION = testSessionBuilder().build();
+    private static final Session SESSION = testSessionBuilder()
+            .setStart(Instant.ofEpochSecond(1126351860, 999_500_000))
+            .build();
     private static final JsonCodec<IrRoutine> IR_ROUTINE_CODEC;
```

</details>

This is because in the test assertion:
```
testSingleExpression(UNKNOWN, null, DOUBLE, floor(SESSION.getStart().toEpochMilli() / 1000.0), "floor(to_unixtime(localtimestamp))");
```

the first expression _truncates_ to epoch milli, whereas the right _rounds_.


**Edit**
i've included the fix for the above in
- https://github.com/trinodb/trino/pull/27808
