### ISSUE TITLE
Flaky TestPinotConnectorSmokeTest.createQueryRunner

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#21777]
```
Error:  io.trino.plugin.pinot.TestPinotConnectorSmokeTest -- Time elapsed: 127.5 s <<< ERROR!
UnexpectedResponseException{request=POST http://localhost:32777/tables, statusCode=400, headers={Pinot-Controller-Version=[Unknown], Access-Control-Allow-Origin=[*], Access-Control-Allow-Methods=[GET, POST, PUT, OPTIONS, DELETE], Connection=[close], Pinot-Controller-Host=[5fc4e4861f7d], Content-Length=[157], Access-Control-Allow-Headers=[*], Content-Type=[application/json]}}
	at io.airlift.http.client.JsonResponseHandler.handle(JsonResponseHandler.java:70)
	at io.airlift.http.client.jetty.JettyHttpClient.doExecute(JettyHttpClient.java:739)
	at io.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:646)
	at io.trino.plugin.pinot.TestingPinotCluster.lambda$addRealTimeTable$2(TestingPinotCluster.java:225)
	at io.trino.plugin.pinot.TestingPinotCluster.doWithRetries(TestingPinotCluster.java:297)
	at io.trino.plugin.pinot.TestingPinotCluster.addRealTimeTable(TestingPinotCluster.java:225)
	at io.trino.plugin.pinot.BasePinotConnectorSmokeTest.createAndPopulateAllTypesTopic(BasePinotConnectorSmokeTest.java:195)
	at io.trino.plugin.pinot.BasePinotConnectorSmokeTest.createQueryRunner(BasePinotConnectorSmokeTest.java:146)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:113)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
...
Error:    TestPinotConnectorSmokeTest>AbstractTestQueryFramework.init:113->BasePinotConnectorSmokeTest.createQueryRunner:146->BasePinotConnectorSmokeTest.createAndPopulateAllTypesTopic:195 » UnexpectedResponse Expected response code to be [200, 201, 202, 203, 204, 205, 206], but was 400
```
https://github.com/trinodb/trino/actions/runs/8901798338/job/24446486590

**Comment by ebyhr** [comment]
cc: @elonazoulay

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/8977404394/job/24656269641
