### ISSUE TITLE
Flaky Iceberg tests: `testDeleteRowsConcurrently`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#21862]
```
Error:  io.trino.plugin.iceberg.catalog.rest.TestIcebergVendingRestCatalogConnectorSmokeTest.testDeleteRowsConcurrently -- Time elapsed: 26.84 s <<< ERROR!
java.lang.IllegalStateException: Task 0 did not complete in time
	at com.google.common.base.Preconditions.checkState(Preconditions.java:589)
	at io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2(BaseIcebergConnectorSmokeTest.java:161)
	at com.google.common.collect.Streams$1Splitr.tryAdvance(Streams.java:500)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:702)
	at io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently(BaseIcebergConnectorSmokeTest.java:165)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```
https://github.com/trinodb/trino/actions/runs/8997761463/job/24716675721

**Comment by findepi** [comment]
Same for `TestIcebergConnectorSmokeTest` & `TestIcebergJdbcCatalogConnectorSmokeTest`

https://github.com/trinodb/trino/actions/runs/9032124170/job/24820406673?pr=21908

```
Error:  Errors: 
Error:  io.trino.plugin.iceberg.TestIcebergConnectorSmokeTest.testDeleteRowsConcurrently
[INFO]   Run 1: PASS
[INFO]   Run 2: PASS
Error:    Run 3: TestIcebergConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:165->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:161 » IllegalState Task 0 did not complete in time
Error:    Run 4: TestIcebergConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:165->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:161 » IllegalState Task 0 did not complete in time
[INFO] 
Error:  io.trino.plugin.iceberg.catalog.jdbc.TestIcebergJdbcCatalogConnectorSmokeTest.testDeleteRowsConcurrently
[INFO]   Run 1: PASS
Error:    Run 2: TestIcebergJdbcCatalogConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:165->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:161 » IllegalState Task 0 did not complete in time
Error:    Run 3: TestIcebergJdbcCatalogConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:165->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:161 » IllegalState Task 0 did not complete in time
[INFO]   Run 4: PASS
[INFO] 
```

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/actions/runs/10145286959/job/28050850161?pr=22857
```
 Error:  io.trino.plugin.iceberg.catalog.jdbc.TestIcebergJdbcCatalogConnectorSmokeTest.testDeleteRowsConcurrently
Error:    Run 1: TestIcebergJdbcCatalogConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:164->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:160 » IllegalState Task 0 did not complete in time
```

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/actions/runs/10164471836/job/28110111251?pr=22879

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/10243730686/job/28335512332

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/10372654044/job/28717301885
```
Error:  Errors: 
Error:  io.trino.plugin.iceberg.catalog.glue.TestIcebergGlueCatalogConnectorSmokeTest.testDeleteRowsConcurrently
Error:    Run 1: TestIcebergGlueCatalogConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:164->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:160 » IllegalState Task 1 did not complete in time
Error:    Run 2: TestIcebergGlueCatalogConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:164->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:160 » IllegalState Task 1 did not complete in time
Error:    Run 3: TestIcebergGlueCatalogConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:164->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:160 » IllegalState Task 0 did not complete in time
Error:    Run 4: TestIcebergGlueCatalogConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:164->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:160 » IllegalState Task 0 did not complete in time
```

**Comment by sopel39** [comment]
this is still happening. @alexjo2144 @ebyhr do you have some ideas?
