### ISSUE TITLE
Metadata listing fails when Glue database (schema) dropped concurrently

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#21917]
Should be TrinoException

https://github.com/trinodb/trino/actions/runs/9029579771/job/24812629214?pr=21908

```
Error:  Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.330 s <<< FAILURE! -- in io.trino.plugin.deltalake.metastore.glue.TestDeltaLakeGlueMetastore
Error:  io.trino.plugin.deltalake.metastore.glue.TestDeltaLakeGlueMetastore.testHideNonDeltaLakeTable -- Time elapsed: 3.748 s <<< ERROR!
com.google.common.util.concurrent.UncheckedExecutionException: software.amazon.awssdk.services.glue.model.EntityNotFoundException: Database test_shared_schema_views_1fpnzxci9v not found. (Service: Glue, Status Code: 400, Request ID: 2dc28c0d-1434-4593-8a7c-b05dbc0f543d)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2087)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4019)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4042)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5024)
	at io.trino.cache.EvictableCache.get(EvictableCache.java:145)
	at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:53)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:264)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getTables(CachingHiveMetastore.java:560)
	at io.trino.plugin.deltalake.metastore.HiveMetastoreBackedDeltaLakeMetastore.getAllTables(HiveMetastoreBackedDeltaLakeMetastore.java:63)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.lambda$listTables$15(DeltaLakeMetadata.java:736)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:288)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:702)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.listTables(DeltaLakeMetadata.java:738)
	at io.trino.plugin.deltalake.metastore.glue.TestDeltaLakeGlueMetastore.testHideNonDeltaLakeTable(TestDeltaLakeGlueMetastore.java:217)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: software.amazon.awssdk.services.glue.model.EntityNotFoundException: Database test_shared_schema_views_1fpnzxci9v not found. (Service: Glue, Status Code: 400, Request ID: 2dc28c0d-1434-4593-8a7c-b05dbc0f543d)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:38)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:55)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:224)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:173)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:80)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)
	at software.amazon.awssdk.services.glue.DefaultGlueClient.getTables(DefaultGlueClient.java:8448)
	at software.amazon.awssdk.services.glue.paginators.GetTablesIterable$GetTablesResponseFetcher.nextPage(GetTablesIterable.java:111)
	at software.amazon.awssdk.services.glue.paginators.GetTablesIterable$GetTablesResponseFetcher.nextPage(GetTablesIterable.java:102)
	at software.amazon.awssdk.core.pagination.sync.PaginatedResponsesIterator.next(PaginatedResponsesIterator.java:58)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:622)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:631)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:637)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:642)
	at io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.getTablesInternal(GlueHiveMetastore.java:437)
	at io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.lambda$getTables$15(GlueHiveMetastore.java:420)
	at io.trino.plugin.hive.metastore.glue.InMemoryGlueCache.lambda$getTables$4(InMemoryGlueCache.java:151)
	at io.trino.plugin.hive.metastore.glue.InMemoryGlueCache$ValueHolder.getValue(InMemoryGlueCache.java:416)
	at io.trino.plugin.hive.metastore.glue.InMemoryGlueCache.getTables(InMemoryGlueCache.java:151)
	at io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.getTables(GlueHiveMetastore.java:420)
	at io.trino.plugin.hive.metastore.tracing.TracingHiveMetastore.lambda$getTables$7(TracingHiveMetastore.java:166)
	at io.trino.plugin.hive.metastore.tracing.Tracing.withTracing(Tracing.java:39)
	at io.trino.plugin.hive.metastore.tracing.TracingHiveMetastore.getTables(TracingHiveMetastore.java:[165](https://github.com/trinodb/trino/actions/runs/9029579771/job/24812629214?pr=21908#step:12:166))
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadTablesNew(CachingHiveMetastore.java:565)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:447)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:433)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3576)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2318)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2191)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2081)
	... 25 more
```

probably relates to https://github.com/trinodb/trino/pull/20657

**Comment by findepi** [comment]
This might be behavioral regression in https://github.com/trinodb/trino/pull/20657, so let me label this as a release-blocker
