### ISSUE TITLE
spill is not work in Joins

### ISSUE THREAD

**Issue by AkiRaT0117** [trinodb/trino#22006]
I referred to the official [Trino document ](https://trino.io/docs/current/admin/spill.html)   

my configuration is as follows:

> spill-enabled=true  
> spiller-spill-path=/tmp/spill  
> query.max-memory=800MB  
> query.max-memory-per-node=100MB  

When I use `Order by` or `Aggregations` operations. I see that the spill is activated. as shown in the following image.  
![image](https://github.com/trinodb/trino/assets/57334937/9cb088af-8794-4566-b031-ff8d5f4f532a)

When I use the join operator, it does not successfully spill as before, but instead returns the following error.

`io.trino.ExceededMemoryLimitException: Query exceeded per-node memory limit of 100MB [Allocated: 99.30MB, Delta: 1.20MB, Top Consumers: {LazyOutputBuffer=59.41MB, MergeOperator=32.24MB, MergeSortedPages=7.65MB}]
	at io.trino.ExceededMemoryLimitException.exceededLocalUserMemoryLimit(ExceededMemoryLimitException.java:40)
	at io.trino.memory.QueryContext.enforceUserMemoryLimit(QueryContext.java:330)
	at io.trino.memory.QueryContext.updateUserMemory(QueryContext.java:165)
	at io.trino.memory.QueryContext.lambda$addTaskContext$0(QueryContext.java:250)`

I wonder know what caused the join operation unable to spill. Is there any parameter or method to resolve.

**Comment by sug-ghosh** [comment]
In Trino, you can enable join spilling by setting the following session properties:

SET SESSION join_distribution_type = 'PARTITIONED';

join-distribution-type = 'BROADCAST' or 'PARTITIONED'.

In a broadcast join, one of the tables (usually the smaller one) is broadcast to all the nodes that hold parts of the larger table. Each node then performs a local join of the broadcast table with the part of the larger table it has. This operation is performed entirely in memory.

Spilling is a mechanism that comes into play when there's not enough memory to hold intermediate results of a computation. In the case of a broadcast join, the entire smaller table must fit into memory. If it doesn't, Trino doesn't perform the join and throws an out of memory exception.

The reason for this is efficiency. The idea behind a broadcast join is to save on the data shuffling across the network. If the smaller table has to be spilled to disk, it defeats the purpose of the broadcast join as disk I/O operations are generally slower than in-memory operations.
