### ISSUE TITLE
Iceberg (and possibly Hive?) Connector do not support ENV secrets for hive.metastore.uri

### ISSUE THREAD

**Issue by joshuagrisham-karolinska** [trinodb/trino#22280]
When trying to use environment variables as "secrets" (per https://trino.io/docs/current/security/secrets.html) for v 449's Iceberg connector's `hive.metastore.uri` I am getting a failure:

```
2024-06-05T15:28:57.268Z        ERROR   main    io.trino.connector.CoordinatorDynamicCatalogManager     -- Failed to load catalog hive_iceberg using connector iceberg --
io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Error invoking configuration method [public StaticMetastoreConfig StaticMetastoreConfig.setMetastoreUris(String)]
Caused by: IllegalArgumentException: Illegal character in authority at index 10: thrift://${ENV.METASTORE_HOST}:9083
        at java.base/URI.create(URI.java:932)
        at java.base/ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
        at java.base/Iterator.forEachRemaining(Iterator.java:133)
        at java.base/Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
        at java.base/AbstractPipeline.copyInto(AbstractPipeline.java:556)
        at java.base/AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
        at java.base/ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/AbstractPipeline.evaluate(AbstractPipeline.java:265)
        at java.base/ReferencePipeline.collect(ReferencePipeline.java:702)
        at StaticMetastoreConfig.setMetastoreUris(StaticMetastoreConfig.java:54)
        at java.base/DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/Method.invoke(Method.java:580)
        at ConfigurationFactory.setConfigProperty(ConfigurationFactory.java:497)
        at ConfigurationFactory.build(ConfigurationFactory.java:402)
        at ConfigurationFactory.build(ConfigurationFactory.java:330)
        at ConfigurationFactory.build(ConfigurationFactory.java:325)
        at AbstractConfigurationAwareModule.buildConfigObject(AbstractConfigurationAwareModule.java:73)
        at ThriftMetastoreModule.setup(ThriftMetastoreModule.java:47)
        at AbstractConfigurationAwareModule.configure(AbstractConfigurationAwareModule.java:48)
        at Elements$RecordingBinder.install(Elements.java:426)
        at AbstractConfigurationAwareModule.install(AbstractConfigurationAwareModule.java:87)
        at IcebergHiveMetastoreCatalogModule.setup(IcebergHiveMetastoreCatalogModule.java:46)
        at AbstractConfigurationAwareModule.configure(AbstractConfigurationAwareModule.java:48)
        at Elements$RecordingBinder.install(Elements.java:426)
        at AbstractConfigurationAwareModule.install(AbstractConfigurationAwareModule.java:87)
        at ConditionalModule.setup(ConditionalModule.java:90)
        at AbstractConfigurationAwareModule.configure(AbstractConfigurationAwareModule.java:48)
        at Elements$RecordingBinder.install(Elements.java:426)
        at AbstractConfigurationAwareModule.install(AbstractConfigurationAwareModule.java:87)
        at IcebergCatalogModule.bindCatalogModule(IcebergCatalogModule.java:55)
        at IcebergCatalogModule.setup(IcebergCatalogModule.java:44)
        at AbstractConfigurationAwareModule.configure(AbstractConfigurationAwareModule.java:48)
        at Elements$RecordingBinder.install(Elements.java:426)
        at Elements.getElements(Elements.java:113)
        at Elements.getElements(Elements.java:106)
        at ConfigurationFactory.registerConfigurationClasses(ConfigurationFactory.java:186)
        at Bootstrap.configure(Bootstrap.java:202)
        at Bootstrap.initialize(Bootstrap.java:246)
        at IcebergConnectorFactory.createConnector(IcebergConnectorFactory.java:116)
        at IcebergConnectorFactory.create(IcebergConnectorFactory.java:78)
        at DefaultCatalogFactory.createConnector(DefaultCatalogFactory.java:202)
        at DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:120)
        at LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:45)
        at CoordinatorDynamicCatalogManager.lambda$loadInitialCatalogs$0(CoordinatorDynamicCatalogManager.java:143)
        at java.base/FutureTask.run(FutureTask.java:317)
        at java.base/Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/FutureTask.run(FutureTask.java:317)
        at DirectExecutor.execute(DirectExecutor.java:31)
        at java.base/ExecutorCompletionService.submit(ExecutorCompletionService.java:186)
        at Executors.executeUntilFailure(Executors.java:46)
        at CoordinatorDynamicCatalogManager.loadInitialCatalogs(CoordinatorDynamicCatalogManager.java:135)
        at Server.doStart(Server.java:155)
        at Server.lambda$start$0(Server.java:93)
        at io.trino.$gen.Trino_449____20240605_152822_1.run(Unknown Source)
        at Server.start(Server.java:93)
        at TrinoServer.main(TrinoServer.java:37)
Caused by: URISyntaxException: Illegal character in authority at index 10: thrift://${ENV.METASTORE_HOST}:9083
        at java.base/URI$Parser.fail(URI.java:2995)
        at java.base/URI$Parser.parseAuthority(URI.java:3344)
        at java.base/URI$Parser.parseHierarchical(URI.java:3240)
        at java.base/URI$Parser.parse(URI.java:3196)
        at java.base/URI.<init>(URI.java:645)
        at java.base/URI.create(URI.java:930)
        ... 55 more
```

When setting a normal string value then everything is working fine.

**Comment by ebyhr** [comment]
`${ENV.METASTORE_HOST}` should be `${ENV:METASTORE_HOST}`. Please use `:` instead.
