### ISSUE TITLE
IcebergSplit Class Loader

### ISSUE THREAD

**Issue by TonBits** [trinodb/trino#22331]
I ran into this error where at first, I thought this was something to do with the data in iceberg getting corrupted.
When this error started to show up, anything that has something to do with Iceberg will fail, even a simple **select * from**

I restarted the entire trino cluster including the coordinator and workers and the problem disappeared.

Not sure what caused the issue and how to recreate it. But it showed up again today. Just recording the exception.

```
java.lang.ClassCastException: class io.trino.plugin.iceberg.IcebergSplit cannot be cast to class io.trino.plugin.iceberg.IcebergSplit (io.trino.plugin.iceberg.IcebergSplit is in unnamed module of loader io.trino.server.PluginClassLoader @269ae588; io.trino.plugin.iceberg.IcebergSplit is in unnamed module of loader io.trino.server.PluginClassLoader @4f38a6b8)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createPageSource(IcebergPageSourceProvider.java:231)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:48)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:296)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_426____20240601_032326_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

Version 426

**Comment by findinpath** [comment]
Maybe different Trino versions running on the coordinator and workers?

Closing this one because it doesn't seem to be relevant anymore.
