### ISSUE TITLE
unable to connect hudi from trino 

### ISSUE THREAD

**Issue by Pavan792reddy** [trinodb/trino#22357]
hi Team ,
i am getting the below error for configuring the trino with hudi on GCP dataproc cluster .

version of trino:- 432

2024-06-11T10:38:02.867Z        INFO    main    io.trino.connector.StaticCatalogManager -- Added catalog hive using connector hive --
2024-06-11T10:38:02.872Z        ERROR   main    io.trino.server.Server  Configuration errors:

1) Error: Configuration property 'fs.native-gcs.enabled' was not used

2) Error: Configuration property 'gcs.json-key' was not used

3) Error: Configuration property 'gcs.json-key-file-path' was not used

4) Error: Configuration property 'gcs.use-access-token' was not used

4 errors
io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Configuration property 'fs.native-gcs.enabled' was not used

2) Error: Configuration property 'gcs.json-key' was not used

3) Error: Configuration property 'gcs.json-key-file-path' was not used

4) Error: Configuration property 'gcs.use-access-token' was not used

4 errors
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:232)
        at io.trino.plugin.hudi.InternalHudiConnectorFactory.createConnector(InternalHudiConnectorFactory.java:87)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.trino.plugin.hudi.HudiConnectorFactory.create(HudiConnectorFactory.java:48)
        at io.trino.connector.DefaultCatalogFactory.createConnector(DefaultCatalogFactory.java:224)
        at io.trino.connector.DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:133)
        at io.trino.connector.LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:45)
        at io.trino.connector.StaticCatalogManager.lambda$loadInitialCatalogs$1(StaticCatalogManager.java:157)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at java.base/java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:184)
        at io.trino.util.Executors.executeUntilFailure(Executors.java:41)
        at io.trino.connector.StaticCatalogManager.loadInitialCatalogs(StaticCatalogManager.java:151)
        at io.trino.server.Server.doStart(Server.java:144)
        at io.trino.server.Server.lambda$start$0(Server.java:91)
        at io.trino.$gen.Trino_432____20240611_103652_1.run(Unknown Source)
        at io.trino.server.Server.start(Server.java:91)
        at io.trino.server.TrinoServer.main(TrinoServer.java:38)

**Comment by ebyhr** [comment]
Those configurations work in newer versions. I would recommend upgrading your cluster. https://trino.io/download

**Comment by Pavan792reddy** [comment]
@ebyhr  can you please let me know the intail version of GCP and hudi integration with trino.
