### ISSUE TITLE
Failed to run the  optimize command to merge small files in Iceberg after upgrading Trino to  version  444

### ISSUE THREAD

**Issue by never-wang** [trinodb/trino#22377]
We are using the `optimize` command to merge small files in Iceberg.
When upgrading Trino from version 436 to 444, we found that many statement failed.

One example SQL statement is :
```
alter table iceberg.dataplatform_caspain_bp_china.dwd_test_flower_cn_client_events_fact_log_realtime EXECUTE optimize(file_size_threshold => '100MB') WHERE bp_timestamp >= cast('2024-05-25 00:00:00+00' as timestamp(6) with time zone) and bp_timestamp < cast('2024-05-26 00:00:00+00' as timestamp(6) with time zone);
```

The table creation sql is:
```
 CREATE TABLE iceberg.dataplatform_caspain_bp_china.dwd_test_flower_cn_client_events_fact_log_realtime ( 
    adaction varchar,                                                                                    
    appplacement varchar,                                                                                
    adecpm double,                                                                                       
    adplacement varchar,                                                                                 
    adcode bigint,                                                                                       
    channelinfo varchar,                                                                                 
    adreason varchar,                                                                                    
    adcpminfo double,                                                                                    
    event_id varchar,                                                                                    
    event_name varchar,                                                                                  
    country varchar,                                                                                     
    user_segment bigint,                                                                                 
    app_info_version_name varchar,                                                                       
    app_info_version_code bigint,                                                                        
    app_info_first_launch_time bigint,                                                                   
    app_info_first_launch_date bigint,                                                                   
    app_info_first_launch_timestamp timestamp(6) with time zone,                                         
    channel_info_store varchar,                                                                          
    channel_info_media varchar,                                                                          
    channel_info_channel varchar,                                                                        
    channel_info_agency varchar,                                                                         
    channel_info_custom varchar,                                                                         
    device_info_geo_country varchar,                                                                     
    device_info_brand varchar,                                                                           
    device_info_category varchar,                                                                        
    device_info_product varchar,                                                                         
    device_info_os_version bigint,                                                                       
    device_info_language varchar,                                                                        
    device_info_timezone_offset_seconds bigint,                                                          
    event_info_date bigint,                                                                              
    event_info_time bigint,                                                                              
    event_info_timestamp timestamp(6) with time zone,                                                    
    user_info_id varchar,                                                                                
    user_info_pseudo_id varchar,                                                                         
    user_info_advertising_id varchar,                                                                    
    bp_app_id varchar,                                                                                   
    bp_ip varchar,                                                                                       
    bp_timestamp timestamp(6) with time zone,                                                            
    if_vibrator_open boolean,                                                                            
    interstitial_time_switch bigint,                                                                     
    splash_switch boolean,                                                                               
    adcount bigint,                                                                                      
    adduration bigint,                                                                                   
    cpm_value bigint,                                                                                    
    ecpm_value double,                                                                                   
    type varchar,                                                                                        
    user_book_level varchar,                                                                             
    value bigint,                                                                                        
    configid bigint,                                                                                     
    seconds bigint,                                                                                      
    period_sec bigint,                                                                                   
    price double,                                                                                        
    coin_value bigint,                                                                                   
    withdraw_source varchar,                                                                             
    withdraw_value_double double,                                                                        
    withdraw_value_float double,                                                                         
    network varchar,                                                                                     
    resolution varchar,                                                                                  
    city varchar,                                                                                        
    code varchar,                                                                                        
    task varchar,                                                                                        
    taskcount varchar,                                                                                   
    category varchar,                                                                                    
    name varchar,                                                                                        
    reason varchar,                                                                                      
    stack varchar,                                                                                       
    "0" bigint,                                                                                          
    "1" bigint,                                                                                          
    "2" bigint,                                                                                          
    "3" bigint,                                                                                          
    "4" bigint,                                                                                          
    "5" bigint,                                                                                          
    permission varchar,                                                                                  
    cash double,                                                                                         
    result boolean,                                                                                      
    mode varchar,                                                                                        
    times varchar,                                                                                       
    current varchar,                                                                                     
    last varchar,                                                                                        
    cuid varchar,                                                                                        
    redpacket_ad boolean,                                                                                
    isinvited varchar,                                                                                   
    hour varchar,                                                                                        
    level varchar,                                                                                       
    day varchar,                                                                                         
    "from" varchar,                                                                                      
    userfirstvideoecpm bigint,                                                                           
    fontsize double,                                                                                     
    blue_enabled boolean                                                                                 
 )                                                                                                       
 WITH (                                                                                                  
    format = 'PARQUET',                                                                                  
    format_version = 1,                                                                                  
    location = 's3://8033-caspian-userdata/iceberg-dwd/app_id=APPFUIHTAVRWVL2V',                         
    partitioning = ARRAY['hour(bp_timestamp)']                                                           
 )
```

The stack trace:
```
java.lang.IllegalStateException: Unexpected FilterNode found in plan; probably connector was not able to handle provided WHERE expression
	at io.trino.sql.planner.sanity.TableExecuteStructureValidator.lambda$validate$1(TableExecuteStructureValidator.java:53)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:423)
	at io.trino.sql.planner.sanity.TableExecuteStructureValidator.validate(TableExecuteStructureValidator.java:51)
	at io.trino.sql.planner.sanity.PlanSanityChecker.lambda$validate$0(PlanSanityChecker.java:107)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:423)
	at io.trino.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:107)
	at io.trino.sql.planner.sanity.PlanSanityChecker.validateFinalPlan(PlanSanityChecker.java:78)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:272)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:236)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:231)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:498)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:478)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:416)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:272)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:570)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:545)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1137)
	at io.trino.$gen.Trino_444____20240613_073439_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
	Suppressed: java.lang.Exception: Current plan:
                Output[columnNames = [rows]]
                │   Layout: [rows:bigint]
                └─ TableCommit[target = iceberg:schemaTableName:dataplatform_caspain_bp_china.dwd_test_flower_cn_client_events_fact_log_realtime, procedureId:OPTIMIZE, procedureHandle:{IcebergOptimizeHandle{snapshotId=Optional[6935855075073050926], schemaAsJson={"type":"struct","schema-id":0,"fields":[{"id":1,"name":"adaction","required":false,"type":"string"},{"id":2,"name":"appplacement","required":false,"type":"string"},{"id":3,"name":"adecpm","required":false,"type":"double"},{"id":4,"name":"adplacement","required":false,"type":"string"},{"id":5,"name":"adcode","required":false,"type":"long"},{"id":6,"name":"channelinfo","required":false,"type":"string"},{"id":7,"name":"adreason","required":false,"type":"string"},{"id":8,"name":"adcpminfo","required":false,"type":"double"},{"id":9,"name":"event_id","required":false,"type":"string"},{"id":10,"name":"event_name","required":false,"type":"string"},{"id":11,"name":"country","required":false,"type":"string"},{"id":12,"name":"user_segment","required":false,"type":"long"},{"id":13,"name":"app_info_version_name","required":false,"type":"string"},{"id":14,"name":"app_info_version_code","required":false,"type":"long"},{"id":15,"name":"app_info_first_launch_time","required":false,"type":"long"},{"id":16,"name":"app_info_first_launch_date","required":false,"type":"long"},{"id":17,"name":"app_info_first_launch_timestamp","required":false,"type":"timestamptz"},{"id":18,"name":"channel_info_store","required":false,"type":"string"},{"id":19,"name":"channel_info_media","required":false,"type":"string"},{"id":20,"name":"channel_info_channel","required":false,"type":"string"},{"id":21,"name":"channel_info_agency","required":false,"type":"string"},{"id":22,"name":"channel_info_custom","required":false,"type":"string"},{"id":23,"name":"device_info_geo_country","required":false,"type":"string"},{"id":24,"name":"device_info_brand","required":false,"type":"string"},{"id":25,"name":"device_info_category","required":false,"type":"string"},{"id":26,"name":"device_info_product","required":false,"type":"string"},{"id":27,"name":"device_info_os_version","required":false,"type":"long"},{"id":28,"name":"device_info_language","required":false,"type":"string"},{"id":29,"name":"device_info_timezone_offset_seconds","required":false,"type":"long"},{"id":30,"name":"event_info_date","required":false,"type":"long"},{"id":31,"name":"event_info_time","required":false,"type":"long"},{"id":32,"name":"event_info_timestamp","required":false,"type":"timestamptz"},{"id":33,"name":"user_info_id","required":false,"type":"string"},{"id":34,"name":"user_info_pseudo_id","required":false,"type":"string"},{"id":35,"name":"user_info_advertising_id","required":false,"type":"string"},{"id":36,"name":"bp_app_id","required":false,"type":"string"},{"id":37,"name":"bp_ip","required":false,"type":"string"},{"id":38,"name":"bp_timestamp","required":false,"type":"timestamptz"},{"id":39,"name":"if_vibrator_open","required":false,"type":"boolean"},{"id":40,"name":"interstitial_time_switch","required":false,"type":"long"},{"id":41,"name":"splash_switch","required":false,"type":"boolean"},{"id":42,"name":"adcount","required":false,"type":"long"},{"id":43,"name":"adduration","required":false,"type":"long"},{"id":44,"name":"cpm_value","required":false,"type":"long"},{"id":45,"name":"ecpm_value","required":false,"type":"double"},{"id":46,"name":"type","required":false,"type":"string"},{"id":47,"name":"user_book_level","required":false,"type":"string"},{"id":48,"name":"value","required":false,"type":"long"},{"id":49,"name":"configid","required":false,"type":"long"},{"id":50,"name":"seconds","required":false,"type":"long"},{"id":51,"name":"period_sec","required":false,"type":"long"},{"id":52,"name":"price","required":false,"type":"double"},{"id":53,"name":"coin_value","required":false,"type":"long"},{"id":54,"name":"withdraw_source","required":false,"type":"string"},{"id":55,"name":"withdraw_value_double","required":false,"type":"double"},{"id":56,"name":"withdraw_value_float","required":false,"type":"double"},{"id":57,"name":"network","required":false,"type":"string"},{"id":58,"name":"resolution","required":false,"type":"string"},{"id":59,"name":"city","required":false,"type":"string"},{"id":60,"name":"code","required":false,"type":"string"},{"id":61,"name":"task","required":false,"type":"string"},{"id":62,"name":"taskcount","required":false,"type":"string"},{"id":63,"name":"category","required":false,"type":"string"},{"id":64,"name":"name","required":false,"type":"string"},{"id":65,"name":"reason","required":false,"type":"string"},{"id":66,"name":"stack","required":false,"type":"string"},{"id":67,"name":"0","required":false,"type":"long"},{"id":68,"name":"1","required":false,"type":"long"},{"id":69,"name":"2","required":false,"type":"long"},{"id":70,"name":"3","required":false,"type":"long"},{"id":71,"name":"4","required":false,"type":"long"},{"id":72,"name":"5","required":false,"type":"long"},{"id":73,"name":"permission","required":false,"type":"string"},{"id":74,"name":"cash","required":false,"type":"double"},{"id":75,"name":"result","required":false,"type":"boolean"},{"id":76,"name":"mode","required":false,"type":"string"},{"id":77,"name":"times","required":false,"type":"string"},{"id":78,"name":"current","required":false,"type":"string"},{"id":79,"name":"last","required":false,"type":"string"},{"id":80,"name":"cuid","required":false,"type":"string"},{"id":81,"name":"redpacket_ad","required":false,"type":"boolean"},{"id":82,"name":"isinvited","required":false,"type":"string"},{"id":83,"name":"hour","required":false,"type":"string"},{"id":84,"name":"level","required":false,"type":"string"},{"id":85,"name":"day","required":false,"type":"string"},{"id":86,"name":"from","required":false,"type":"string"},{"id":87,"name":"userfirstvideoecpm","required":false,"type":"long"},{"id":88,"name":"fontsize","required":false,"type":"double"},{"id":89,"name":"blue_enabled","required":false,"type":"boolean"}]}, partitionSpecAsJson={"spec-id":0,"fields":[{"name":"bp_timestamp_hour","transform":"hour","source-id":38,"field-id":1000}]}, tableColumns=[1:adaction:varchar, 2:appplacement:varchar, 3:adecpm:double, 4:adplacement:varchar, 5:adcode:bigint, 6:channelinfo:varchar, 7:adreason:varchar, 8:adcpminfo:double, 9:event_id:varchar, 10:event_name:varchar, 11:country:varchar, 12:user_segment:bigint, 13:app_info_version_name:varchar, 14:app_info_version_code:bigint, 15:app_info_first_launch_time:bigint, 16:app_info_first_launch_date:bigint, 17:app_info_first_launch_timestamp:timestamp(6) with time zone, 18:channel_info_store:varchar, 19:channel_info_media:varchar, 20:channel_info_channel:varchar, 21:channel_info_agency:varchar, 22:channel_info_custom:varchar, 23:device_info_geo_country:varchar, 24:device_info_brand:varchar, 25:device_info_category:varchar, 26:device_info_product:varchar, 27:device_info_os_version:bigint, 28:device_info_language:varchar, 29:device_info_timezone_offset_seconds:bigint, 30:event_info_date:bigint, 31:event_info_time:bigint, 32:event_info_timestamp:timestamp(6) with time zone, 33:user_info_id:varchar, 34:user_info_pseudo_id:varchar, 35:user_info_advertising_id:varchar, 36:bp_app_id:varchar, 37:bp_ip:varchar, 38:bp_timestamp:timestamp(6) with time zone, 39:if_vibrator_open:boolean, 40:interstitial_time_switch:bigint, 41:splash_switch:boolean, 42:adcount:bigint, 43:adduration:bigint, 44:cpm_value:bigint, 45:ecpm_value:double, 46:type:varchar, 47:user_book_level:varchar, 48:value:bigint, 49:configid:bigint, 50:seconds:bigint, 51:period_sec:bigint, 52:price:double, 53:coin_value:bigint, 54:withdraw_source:varchar, 55:withdraw_value_double:double, 56:withdraw_value_float:double, 57:network:varchar, 58:resolution:varchar, 59:city:varchar, 60:code:varchar, 61:task:varchar, 62:taskcount:varchar, 63:category:varchar, 64:name:varchar, 65:reason:varchar, 66:stack:varchar, 67:0:bigint, 68:1:bigint, 69:2:bigint, 70:3:bigint, 71:4:bigint, 72:5:bigint, 73:permission:varchar, 74:cash:double, 75:result:boolean, 76:mode:varchar, 77:times:varchar, 78:current:varchar, 79:last:varchar, 80:cuid:varchar, 81:redpacket_ad:boolean, 82:isinvited:varchar, 83:hour:varchar, 84:level:varchar, 85:day:varchar, 86:from:varchar, 87:userfirstvideoecpm:bigint, 88:fontsize:double, 89:blue_enabled:boolean], fileFormat=PARQUET, tableStorageProperties={write.metadata.delete-after-commit.enabled=true, commit.manifest.target-size-bytes=838860, write.format.default=PARQUET, write.metadata.previous-versions-max=20}, maxScannedFileSize=100MB, retriesEnabled=true}}]
                   │   Layout: [rows:bigint]
                   └─ LocalExchange[partitioning = SINGLE]
                      │   Layout: [partialrows:bigint, fragment:varbinary]
                      └─ RemoteExchange[type = GATHER]
                         │   Layout: [partialrows:bigint, fragment:varbinary]
                         └─ TableExecute[]
                            │   Layout: [partialrows:bigint, fragment:varbinary]
                            │   adaction := adaction
                            │   appplacement := appplacement
                            │   adecpm := adecpm
                            │   adplacement := adplacement
                            │   adcode := adcode
                            │   channelinfo := channelinfo
                            │   adreason := adreason
                            │   adcpminfo := adcpminfo
                            │   event_id := event_id
                            │   event_name := event_name
                            │   country := country
                            │   user_segment := user_segment
                            │   app_info_version_name := app_info_version_name
                            │   app_info_version_code := app_info_version_code
                            │   app_info_first_launch_time := app_info_first_launch_time
                            │   app_info_first_launch_date := app_info_first_launch_date
                            │   app_info_first_launch_timestamp := app_info_first_launch_timestamp
                            │   channel_info_store := channel_info_store
                            │   channel_info_media := channel_info_media
                            │   channel_info_channel := channel_info_channel
                            │   channel_info_agency := channel_info_agency
                            │   channel_info_custom := channel_info_custom
                            │   device_info_geo_country := device_info_geo_country
                            │   device_info_brand := device_info_brand
                            │   device_info_category := device_info_category
                            │   device_info_product := device_info_product
                            │   device_info_os_version := device_info_os_version
                            │   device_info_language := device_info_language
                            │   device_info_timezone_offset_seconds := device_info_timezone_offset_seconds
                            │   event_info_date := event_info_date
                            │   event_info_time := event_info_time
                            │   event_info_timestamp := event_info_timestamp
                            │   user_info_id := user_info_id
                            │   user_info_pseudo_id := user_info_pseudo_id
                            │   user_info_advertising_id := user_info_advertising_id
                            │   bp_app_id := bp_app_id
                            │   bp_ip := bp_ip
                            │   bp_timestamp := bp_timestamp
                            │   if_vibrator_open := if_vibrator_open
                            │   interstitial_time_switch := interstitial_time_switch
                            │   splash_switch := splash_switch
                            │   adcount := adcount
                            │   adduration := adduration
                            │   cpm_value := cpm_value
                            │   ecpm_value := ecpm_value
                            │   type := type
                            │   user_book_level := user_book_level
                            │   value := value
                            │   configid := configid
                            │   seconds := seconds
                            │   period_sec := period_sec
                            │   price := price
                            │   coin_value := coin_value
                            │   withdraw_source := withdraw_source
                            │   withdraw_value_double := withdraw_value_double
                            │   withdraw_value_float := withdraw_value_float
                            │   network := network
                            │   resolution := resolution
                            │   city := city
                            │   code := code
                            │   task := task
                            │   taskcount := taskcount
                            │   category := category
                            │   name := name
                            │   reason := reason
                            │   stack := stack
                            │   0 := 0
                            │   1 := 1
                            │   2 := 2
                            │   3 := 3
                            │   4 := 4
                            │   5 := 5
                            │   permission := permission
                            │   cash := cash
                            │   result := result
                            │   mode := mode
                            │   times := times
                            │   current := current
                            │   last := last
                            │   cuid := cuid
                            │   redpacket_ad := redpacket_ad
                            │   isinvited := isinvited
                            │   hour := hour
                            │   level := level
                            │   day := day
                            │   from := from
                            │   userfirstvideoecpm := userfirstvideoecpm
                            │   fontsize := fontsize
                            │   blue_enabled := blue_enabled
                            └─ LocalExchange[partitioning = iceberg:IcebergPartitioningHandle{partitioning=[hour(bp_timestamp)]}, arguments = [bp_timestamp::timestamp(6) with time zone]]
                               │   Layout: [adaction:varchar, appplacement:varchar, adecpm:double, adplacement:varchar, adcode:bigint, channelinfo:varchar, adreason:varchar, adcpminfo:double, event_id:varchar, event_name:varchar, country:varchar, user_segment:bigint, app_info_version_name:varchar, app_info_version_code:bigint, app_info_first_launch_time:bigint, app_info_first_launch_date:bigint, app_info_first_launch_timestamp:timestamp(6) with time zone, channel_info_store:varchar, channel_info_media:varchar, channel_info_channel:varchar, channel_info_agency:varchar, channel_info_custom:varchar, device_info_geo_country:varchar, device_info_brand:varchar, device_info_category:varchar, device_info_product:varchar, device_info_os_version:bigint, device_info_language:varchar, device_info_timezone_offset_seconds:bigint, event_info_date:bigint, event_info_time:bigint, event_info_timestamp:timestamp(6) with time zone, user_info_id:varchar, user_info_pseudo_id:varchar, user_info_advertising_id:varchar, bp_app_id:varchar, bp_ip:varchar, bp_timestamp:timestamp(6) with time zone, if_vibrator_open:boolean, interstitial_time_switch:bigint, splash_switch:boolean, adcount:bigint, adduration:bigint, cpm_value:bigint, ecpm_value:double, type:varchar, user_book_level:varchar, value:bigint, configid:bigint, seconds:bigint, period_sec:bigint, price:double, coin_value:bigint, withdraw_source:varchar, withdraw_value_double:double, withdraw_value_float:double, network:varchar, resolution:varchar, city:varchar, code:varchar, task:varchar, taskcount:varchar, category:varchar, name:varchar, reason:varchar, stack:varchar, 0:bigint, 1:bigint, 2:bigint, 3:bigint, 4:bigint, 5:bigint, permission:varchar, cash:double, result:boolean, mode:varchar, times:varchar, current:varchar, last:varchar, cuid:varchar, redpacket_ad:boolean, isinvited:varchar, hour:varchar, level:varchar, day:varchar, from:varchar, userfirstvideoecpm:bigint, fontsize:double, blue_enabled:boolean]
                               └─ RemoteExchange[type = REPARTITION]
                                  │   Layout: [adaction:varchar, appplacement:varchar, adecpm:double, adplacement:varchar, adcode:bigint, channelinfo:varchar, adreason:varchar, adcpminfo:double, event_id:varchar, event_name:varchar, country:varchar, user_segment:bigint, app_info_version_name:varchar, app_info_version_code:bigint, app_info_first_launch_time:bigint, app_info_first_launch_date:bigint, app_info_first_launch_timestamp:timestamp(6) with time zone, channel_info_store:varchar, channel_info_media:varchar, channel_info_channel:varchar, channel_info_agency:varchar, channel_info_custom:varchar, device_info_geo_country:varchar, device_info_brand:varchar, device_info_category:varchar, device_info_product:varchar, device_info_os_version:bigint, device_info_language:varchar, device_info_timezone_offset_seconds:bigint, event_info_date:bigint, event_info_time:bigint, event_info_timestamp:timestamp(6) with time zone, user_info_id:varchar, user_info_pseudo_id:varchar, user_info_advertising_id:varchar, bp_app_id:varchar, bp_ip:varchar, bp_timestamp:timestamp(6) with time zone, if_vibrator_open:boolean, interstitial_time_switch:bigint, splash_switch:boolean, adcount:bigint, adduration:bigint, cpm_value:bigint, ecpm_value:double, type:varchar, user_book_level:varchar, value:bigint, configid:bigint, seconds:bigint, period_sec:bigint, price:double, coin_value:bigint, withdraw_source:varchar, withdraw_value_double:double, withdraw_value_float:double, network:varchar, resolution:varchar, city:varchar, code:varchar, task:varchar, taskcount:varchar, category:varchar, name:varchar, reason:varchar, stack:varchar, 0:bigint, 1:bigint, 2:bigint, 3:bigint, 4:bigint, 5:bigint, permission:varchar, cash:double, result:boolean, mode:varchar, times:varchar, current:varchar, last:varchar, cuid:varchar, redpacket_ad:boolean, isinvited:varchar, hour:varchar, level:varchar, day:varchar, from:varchar, userfirstvideoecpm:bigint, fontsize:double, blue_enabled:boolean]
                                  └─ ScanFilter[table = iceberg:dataplatform_caspain_bp_china.dwd_test_flower_cn_client_events_fact_log_realtime$data@6935855075073050926, filterPredicate = ((bp_timestamp >= timestamp(6) with time zone '2024-05-25 00:00:00.000000 UTC') AND (bp_timestamp < timestamp(6) with time zone '2024-05-26 00:00:00.000000 UTC'))]
                                         Layout: [adaction:varchar, appplacement:varchar, adecpm:double, adplacement:varchar, adcode:bigint, channelinfo:varchar, adreason:varchar, adcpminfo:double, event_id:varchar, event_name:varchar, country:varchar, user_segment:bigint, app_info_version_name:varchar, app_info_version_code:bigint, app_info_first_launch_time:bigint, app_info_first_launch_date:bigint, app_info_first_launch_timestamp:timestamp(6) with time zone, channel_info_store:varchar, channel_info_media:varchar, channel_info_channel:varchar, channel_info_agency:varchar, channel_info_custom:varchar, device_info_geo_country:varchar, device_info_brand:varchar, device_info_category:varchar, device_info_product:varchar, device_info_os_version:bigint, device_info_language:varchar, device_info_timezone_offset_seconds:bigint, event_info_date:bigint, event_info_time:bigint, event_info_timestamp:timestamp(6) with time zone, user_info_id:varchar, user_info_pseudo_id:varchar, user_info_advertising_id:varchar, bp_app_id:varchar, bp_ip:varchar, bp_timestamp:timestamp(6) with time zone, if_vibrator_open:boolean, interstitial_time_switch:bigint, splash_switch:boolean, adcount:bigint, adduration:bigint, cpm_value:bigint, ecpm_value:double, type:varchar, user_book_level:varchar, value:bigint, configid:bigint, seconds:bigint, period_sec:bigint, price:double, coin_value:bigint, withdraw_source:varchar, withdraw_value_double:double, withdraw_value_float:double, network:varchar, resolution:varchar, city:varchar, code:varchar, task:varchar, taskcount:varchar, category:varchar, name:varchar, reason:varchar, stack:varchar, 0:bigint, 1:bigint, 2:bigint, 3:bigint, 4:bigint, 5:bigint, permission:varchar, cash:double, result:boolean, mode:varchar, times:varchar, current:varchar, last:varchar, cuid:varchar, redpacket_ad:boolean, isinvited:varchar, hour:varchar, level:varchar, day:varchar, from:varchar, userfirstvideoecpm:bigint, fontsize:double, blue_enabled:boolean]
                                         bp_app_id := 36:bp_app_id:varchar
                                         country := 11:country:varchar
                                         reason := 65:reason:varchar
                                         channel_info_channel := 20:channel_info_channel:varchar
                                         stack := 66:stack:varchar
                                         userfirstvideoecpm := 87:userfirstvideoecpm:bigint
                                         app_info_version_name := 13:app_info_version_name:varchar
                                         adecpm := 3:adecpm:double
                                         ecpm_value := 45:ecpm_value:double
                                         fontsize := 88:fontsize:double
                                         splash_switch := 41:splash_switch:boolean
                                         type := 46:type:varchar
                                         resolution := 58:resolution:varchar
                                         channel_info_custom := 22:channel_info_custom:varchar
                                         mode := 76:mode:varchar
                                         seconds := 50:seconds:bigint
                                         interstitial_time_switch := 40:interstitial_time_switch:bigint
                                         price := 52:price:double
                                         adplacement := 4:adplacement:varchar
                                         from := 86:from:varchar
                                         app_info_version_code := 14:app_info_version_code:bigint
                                         cash := 74:cash:double
                                         isinvited := 82:isinvited:varchar
                                         day := 85:day:varchar
                                         adreason := 7:adreason:varchar
                                         bp_ip := 37:bp_ip:varchar
                                         cuid := 80:cuid:varchar
                                         last := 79:last:varchar
                                         adcode := 5:adcode:bigint
                                         level := 84:level:varchar
                                         user_segment := 12:user_segment:bigint
                                         event_info_date := 30:event_info_date:bigint
                                         app_info_first_launch_date := 16:app_info_first_launch_date:bigint
                                         0 := 67:0:bigint
                                         1 := 68:1:bigint
                                         2 := 69:2:bigint
                                         task := 61:task:varchar
                                         3 := 70:3:bigint
                                         4 := 71:4:bigint
                                         5 := 72:5:bigint
                                         app_info_first_launch_timestamp := 17:app_info_first_launch_timestamp:timestamp(6) with time zone
                                         configid := 49:configid:bigint
                                         name := 64:name:varchar
                                         appplacement := 2:appplacement:varchar
                                         event_name := 10:event_name:varchar
                                         event_info_timestamp := 32:event_info_timestamp:timestamp(6) with time zone
                                         channel_info_agency := 21:channel_info_agency:varchar
                                         user_info_id := 33:user_info_id:varchar
                                         period_sec := 51:period_sec:bigint
                                         device_info_product := 26:device_info_product:varchar
                                         device_info_language := 28:device_info_language:varchar
                                         code := 60:code:varchar
                                         event_info_time := 31:event_info_time:bigint
                                         adcount := 42:adcount:bigint
                                         user_info_advertising_id := 35:user_info_advertising_id:varchar
                                         city := 59:city:varchar
                                         app_info_first_launch_time := 15:app_info_first_launch_time:bigint
                                         channel_info_store := 18:channel_info_store:varchar
                                         network := 57:network:varchar
                                         result := 75:result:boolean
                                         channelinfo := 6:channelinfo:varchar
                                         device_info_category := 25:device_info_category:varchar
                                         user_info_pseudo_id := 34:user_info_pseudo_id:varchar
                                         times := 77:times:varchar
                                         current := 78:current:varchar
                                         device_info_brand := 24:device_info_brand:varchar
                                         withdraw_source := 54:withdraw_source:varchar
                                         taskcount := 62:taskcount:varchar
                                         hour := 83:hour:varchar
                                         withdraw_value_float := 56:withdraw_value_float:double
                                         cpm_value := 44:cpm_value:bigint
                                         user_book_level := 47:user_book_level:varchar
                                         if_vibrator_open := 39:if_vibrator_open:boolean
                                         withdraw_value_double := 55:withdraw_value_double:double
                                         value := 48:value:bigint
                                         adduration := 43:adduration:bigint
                                         redpacket_ad := 81:redpacket_ad:boolean
                                         device_info_os_version := 27:device_info_os_version:bigint
                                         device_info_geo_country := 23:device_info_geo_country:varchar
                                         coin_value := 53:coin_value:bigint
                                         device_info_timezone_offset_seconds := 29:device_info_timezone_offset_seconds:bigint
                                         adaction := 1:adaction:varchar
                                         channel_info_media := 19:channel_info_media:varchar
                                         permission := 73:permission:varchar
                                         blue_enabled := 89:blue_enabled:boolean
                                         event_id := 9:event_id:varchar
                                         adcpminfo := 8:adcpminfo:double
                                         bp_timestamp := 38:bp_timestamp:timestamp(6) with time zone
                                         category := 63:category:varchar

		at io.trino.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:120)
		... 17 more
```

**Comment by wendigo** [comment]
cc @ebyhr @findinpath

**Comment by ebyhr** [comment]
I think the root cause is same as https://github.com/trinodb/trino/issues/22268

**Comment by eldaramir** [comment]
hi, have any of you solved it?

@never-wang 
@netanelm-upstream

**Comment by kenjitakatuzi** [comment]
Hi @eldaramir , could you give more details on how you resolved your problem? I'm facing the same issue when using `... WHERE CAST(__timestamp AS DATE) >= DATE '2022-01-04' and CAST(__timestamp AS DATE) <= DATE '2022-07-29'` with the `OPTIMIZE` command.

**Comment by eldaramir** [comment]
Hi @kenjitakatuzi, in the config section  under properties of the model file you need to have the the partitioning that you want it to be on.  for example 
adding on that you must add the partitioning to each model you want to optimize and make sure the column exists in that model cause dbt won't let it run through hope it'll help you :) 
{{
     config ( 
           properties= { 
                   "format": "'parquet'",
                    "partitioning": "ARRAY['what_you_want_to_partition_by']",
                    "sorted_by": ......


},

tags= ....
materialized= .....
......
)


the rest of the model code
