### ISSUE TITLE
Presto CLI throws error when new CLI connects to old presto server

### ISSUE THREAD

**Issue by wyukawa** [trinodb/trino#224]
Invalid JSON error occured when presto CLI 302 connects to presto 0.197

```
$ java -jar presto-cli-302-executable.jar --server ...
presto:default> SELECT cast(row(1, 2) as row(a bigint, b bigint));
java.lang.RuntimeException: Error fetching next at https://somehost/v1/statement/20190213_024622_00750_q6mdj/1 returned an invalid response: JsonResponse{statusCode=200, statusMessage=OK, headers={content-type=[application/json], date=[Wed, 13 Feb 2019 02:46:22 GMT], vary=[Accept-Encoding, User-Agent], x-content-type-options=[nosniff]}, hasValue=false} [Error: {"id":"20190213_024622_00750_q6mdj","infoUri":"https://somehost/query.html?20190213_024622_00750_q6mdj","partialCancelUri":"http://10.120.20.154:12080/v1/stage/20190213_024622_00750_q6mdj.0","nextUri":"https://somehost/v1/statement/20190213_024622_00750_q6mdj/2","columns":[{"name":"_col0","type":"row(a bigint,b bigint)","typeSignature":{"rawType":"row","typeArguments":[{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]},{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":["a","b"],"arguments":[{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"a","typeSignature":"bigint"}},{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"b","typeSignature":"bigint"}}]}}],"data":[[[1,2]]],"stats":{"state":"RUNNING","queued":false,"scheduled":true,"nodes":1,"totalSplits":17,"queuedSplits":17,"runningSplits":0,"completedSplits":0,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"queuedTimeMillis":0,"elapsedTimeMillis":105,"processedRows":0,"processedBytes":0,"peakMemoryBytes":0,"rootStage":{"stageId":"0","state":"RUNNING","done":false,"nodes":1,"totalSplits":17,"queuedSplits":17,"runningSplits":0,"completedSplits":0,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":0,"processedBytes":0,"subStages":[]},"progressPercentage":0.0}}
]
        at io.prestosql.client.StatementClientV1.requestFailedException(StatementClientV1.java:463)
        at io.prestosql.client.StatementClientV1.advance(StatementClientV1.java:402)
        at io.prestosql.cli.StatusPrinter.printInitialStatusUpdates(StatusPrinter.java:130)
        at io.prestosql.cli.Query.renderQueryOutput(Query.java:146)
        at io.prestosql.cli.Query.renderOutput(Query.java:129)
        at io.prestosql.cli.Console.process(Console.java:313)
        at io.prestosql.cli.Console.runConsole(Console.java:257)
        at io.prestosql.cli.Console.run(Console.java:147)
        at io.prestosql.cli.Presto.main(Presto.java:31)
Caused by: java.lang.IllegalArgumentException: Unable to create class io.prestosql.client.QueryResults from JSON response:
[{"id":"20190213_024622_00750_q6mdj","infoUri":"https://somehost/query.html?20190213_024622_00750_q6mdj","partialCancelUri":"http://10.120.20.154:12080/v1/stage/20190213_024622_00750_q6mdj.0","nextUri":"https://somehost/v1/statement/20190213_024622_00750_q6mdj/2","columns":[{"name":"_col0","type":"row(a bigint,b bigint)","typeSignature":{"rawType":"row","typeArguments":[{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]},{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":["a","b"],"arguments":[{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"a","typeSignature":"bigint"}},{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"b","typeSignature":"bigint"}}]}}],"data":[[[1,2]]],"stats":{"state":"RUNNING","queued":false,"scheduled":true,"nodes":1,"totalSplits":17,"queuedSplits":17,"runningSplits":0,"completedSplits":0,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"queuedTimeMillis":0,"elapsedTimeMillis":105,"processedRows":0,"processedBytes":0,"peakMemoryBytes":0,"rootStage":{"stageId":"0","state":"RUNNING","done":false,"nodes":1,"totalSplits":17,"queuedSplits":17,"runningSplits":0,"completedSplits":0,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":0,"processedBytes":0,"subStages":[]},"progressPercentage":0.0}}
]
        at io.prestosql.client.JsonResponse.<init>(JsonResponse.java:70)
        at io.prestosql.client.JsonResponse.execute(JsonResponse.java:144)
        at io.prestosql.client.StatementClientV1.advance(StatementClientV1.java:388)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: Invalid JSON string for [simple type, class io.prestosql.client.QueryResults]
        at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:137)
        at io.prestosql.client.JsonResponse.<init>(JsonResponse.java:67)
        ... 9 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `io.prestosql.client.ClientTypeSignature` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('bigint')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.prestosql.client.QueryResults["columns"]->java.util.ArrayList[0]->io.prestosql.client.Column["typeSignature"]->io.prestosql.client.ClientTypeSignature["arguments"]->java.util.ArrayList[0]->io.prestosql.client.NamedClientTypeSignature["typeSignature"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1032)
        at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1373)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:171)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
        at io.prestosql.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:145)
        at io.prestosql.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:127)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042)
        at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:134)
        ... 10 more
```

maybe same as https://github.com/prestodb/presto/issues/11216

In our use case, we need to access various kinds of presto including old version presto with https://github.com/yanagishima/yanagishima which uses presto-client
So, if new presto client supports old presto server, it would be great.

**Comment by electrum** [comment]
Within reason, clients and servers should be compatible in both directions. We do need better testing in this area. This might be the same as the linked issue but I'll need to dig into it.

Note that `presto-client` is an internal library used by the CLI and JDBC driver. It's not intended or developed as a public interface. The API is not very good and it's hard to use correctly. I've been moving in the direction of making the CLI use the JDBC driver. Once that happens, we would likely remove `presto-client` as a separate library.

Please let me know what features you need from the JDBC driver. It does have a progress feature (should be documented):

```java
connection.unwrap(PrestoConnection.class).setProgressMonitor(stats -> {
    System.out.println(format("%s %s", stats.getQueryId(), stats.getState()));
});
```

**Comment by findepi** [comment]
@electrum can it have anything do to with the fact that `JsonProperty` name is different between versions?

https://github.com/prestosql/presto/blob/0.197/presto-spi/src/main/java/com/facebook/presto/spi/type/NamedTypeSignature.java#L30
`@JsonProperty("name") String name`

https://github.com/prestosql/presto/blob/302/presto-client/src/main/java/io/prestosql/client/NamedClientTypeSignature.java#L32
`@JsonProperty("fieldName") Optional<RowFieldName> fieldName,` where `RowFieldName` is a struct `{name: ..., delimited: ...}`

**Comment by hashhar** [comment]
We now have tests that verify backward compatibility across last 15 releases (every 3rd release from current 5 times).
