### ISSUE TITLE
Experimental CatalogStore in Plugin doesn't work.

### ISSUE THREAD

**Issue by sebadiaz** [trinodb/trino#22554]
When we start trio (tested in the docker image with the config.properties file), the server crash.

To test,  set in config:
 
       catalog.store=test
       catalog.management=DYNAMIC

Guice emit a binding error for a double optional class declaration. 

I make a pull request in this problem : https://github.com/trinodb/trino/pull/22553

@dain please make the correction. thanks for your help.

regards

**Comment by hashhar** [comment]
For brevity the errors are of the form:

```
2024-07-23T16:19:37.124+0545	ERROR	main	io.trino.server.Server	Unable to create injector, see the following errors:
presto-master       |
presto-master       | 1) [Guice/RecursiveBinding]: Binding points to itself. Key: CatalogStoreManager
presto-master       |   at CatalogManagerModule.setup(CatalogManagerModule.java:31)
presto-master       |       \_ installed by: CatalogManagerModule -> RealOptionalBinder
presto-master       |
presto-master       | 2) [Guice/RecursiveBinding]: Binding points to itself. Key: CatalogStoreManager
presto-master       |   at DynamicCatalogManagerModule.setup(DynamicCatalogManagerModule.java:47)
presto-master       |       \_ installed by: CatalogManagerModule -> DynamicCatalogManagerModule
presto-master       |
presto-master       | 3) [Guice/BindingAlreadySet]: CatalogStoreManager was bound multiple times.
presto-master       |
presto-master       | Bound at:
presto-master       | 1  : DynamicCatalogManagerModule.setup(DynamicCatalogManagerModule.java:47)
presto-master       |       \_ installed by: CatalogManagerModule -> DynamicCatalogManagerModule
presto-master       | 2  : java.base/DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
presto-master       |       \_ installed by: CatalogManagerModule -> DynamicCatalogManagerModule
presto-master       |
presto-master       | Learn more:
presto-master       |   https://github.com/google/guice/wiki/BINDING_ALREADY_SET
presto-master       |
presto-master       | 3 errors
presto-master       |
presto-master       | ======================
presto-master       | Full classname legend:
presto-master       | ======================
presto-master       | CatalogManagerModule:        "io.trino.connector.CatalogManagerModule"
presto-master       | CatalogStoreManager:         "io.trino.connector.CatalogStoreManager"
presto-master       | DirectMethodHandleAccessor:  "jdk.internal.reflect.DirectMethodHandleAccessor"
presto-master       | DynamicCatalogManagerModule: "io.trino.connector.DynamicCatalogManagerModule"
presto-master       | RealOptionalBinder:          "com.google.inject.internal.RealOptionalBinder"
presto-master       | ========================
presto-master       | End of classname legend:
presto-master       | ========================
presto-master       |
presto-master       | com.google.inject.CreationException: Unable to create injector, see the following errors:
presto-master       |
presto-master       | 1) [Guice/RecursiveBinding]: Binding points to itself. Key: CatalogStoreManager
presto-master       |   at CatalogManagerModule.setup(CatalogManagerModule.java:31)
presto-master       |       \_ installed by: CatalogManagerModule -> RealOptionalBinder
presto-master       |
presto-master       | 2) [Guice/RecursiveBinding]: Binding points to itself. Key: CatalogStoreManager
presto-master       |   at DynamicCatalogManagerModule.setup(DynamicCatalogManagerModule.java:47)
presto-master       |       \_ installed by: CatalogManagerModule -> DynamicCatalogManagerModule
presto-master       |
presto-master       | 3) [Guice/BindingAlreadySet]: CatalogStoreManager was bound multiple times.
presto-master       |
presto-master       | Bound at:
presto-master       | 1  : DynamicCatalogManagerModule.setup(DynamicCatalogManagerModule.java:47)
presto-master       |       \_ installed by: CatalogManagerModule -> DynamicCatalogManagerModule
presto-master       | 2  : java.base/DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
presto-master       |       \_ installed by: CatalogManagerModule -> DynamicCatalogManagerModule
presto-master       |
presto-master       | Learn more:
presto-master       |   https://github.com/google/guice/wiki/BINDING_ALREADY_SET
presto-master       |
presto-master       | 3 errors
presto-master       |
presto-master       | ======================
presto-master       | Full classname legend:
presto-master       | ======================
presto-master       | CatalogManagerModule:        "io.trino.connector.CatalogManagerModule"
presto-master       | CatalogStoreManager:         "io.trino.connector.CatalogStoreManager"
presto-master       | DirectMethodHandleAccessor:  "jdk.internal.reflect.DirectMethodHandleAccessor"
presto-master       | DynamicCatalogManagerModule: "io.trino.connector.DynamicCatalogManagerModule"
presto-master       | RealOptionalBinder:          "com.google.inject.internal.RealOptionalBinder"
presto-master       | ========================
presto-master       | End of classname legend:
presto-master       | ========================
presto-master       |
presto-master       | 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:589)
presto-master       | 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163)
presto-master       | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
presto-master       | 	at com.google.inject.Guice.createInjector(Guice.java:87)
presto-master       | 	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:264)
presto-master       | 	at io.trino.server.Server.doStart(Server.java:141)
presto-master       | 	at io.trino.server.Server.lambda$start$0(Server.java:93)
presto-master       | 	at io.trino.$gen.Trino_452_109_g3daeff4_dirty____20240723_103424_1.run(Unknown Source)
presto-master       | 	at io.trino.server.Server.start(Server.java:93)
presto-master       | 	at io.trino.server.TrinoServer.main(TrinoServer.java:37)
```

**Comment by hashhar** [comment]
I've a fix available and will send a PR with some tests - current tests are insufficient.
