### ISSUE TITLE
Issue of Excessive CPU Usage by Worker Threads

### ISSUE THREAD

**Issue by youngjinkim0706** [trinodb/trino#22642]
When setting the number of max-worker-threads to cpus*2 and executing queries, CPU usage nearly reaches 100%, leading to resource starvation for the thread responsible for communication between worker and coordinator, resulting in a 503 error. 
This issue persists even when using the hardCpuLimit in the resource-group config. 
What are the best practices to resolve this issue? Alternatively, can this problem be solved by modifying other configurations?

here is error message
```
2024-07-04T08:07:13.550Z        WARN    query-management-1      io.trino.memory.RemoteNodeMemory        Memory info update request to http://172.30.0.4:8080/v1/memory has not returned in 10.50s
2024-07-04T08:07:25.528Z        WARN    node-state-poller-0     io.trino.metadata.RemoteNodeState       Node state update request to http://172.30.0.4:8080/v1/info/state has not returned in 11.11s
2024-07-04T08:07:53.740Z        WARN    query-management-3      io.trino.memory.RemoteNodeMemory        Memory info update request to http://172.30.0.4:8080/v1/memory has not returned in 59.15s
2024-07-04T08:08:33.059Z        WARN    node-state-poller-0     io.trino.metadata.RemoteNodeState       Node state update request to http://172.30.0.4:8080/v1/info/state has not returned in 87.41s
2024-07-04T08:08:35.645Z        WARN    query-management-0      io.trino.memory.RemoteNodeMemory        Memory info update request to http://172.30.0.4:8080/v1/memory has not returned in 100.94s
2024-07-04T08:08:39.222Z        WARN    node-state-poller-0     io.trino.metadata.RemoteNodeState       Node state update request to http://172.30.0.4:8080/v1/info/state has not returned in 93.23s
2024-07-04T08:08:39.416Z        WARN    query-management-2      io.trino.memory.RemoteNodeMemory        Memory info update request to http://172.30.0.4:8080/v1/memory has not returned in 104.83s
2024-07-04T08:08:44.261Z        WARN    query-management-3      io.trino.memory.RemoteNodeMemory        Memory info update request to http://172.30.0.4:8080/v1/memory has not returned in 109.67s
2024-07-04T08:08:44.743Z        WARN    node-state-poller-0     io.trino.metadata.RemoteNodeState       Node state update request to http://172.30.0.4:8080/v1/info/state has not returned in 99.11s
2024-07-04T08:08:47.148Z        WARN    query-management-1      io.trino.memory.RemoteNodeMemory        Memory info update request to http://172.30.0.4:8080/v1/memory has not returned in 112.56s
2024-07-04T08:08:49.813Z        WARN    query-management-4      io.trino.memory.RemoteNodeMemory        Memory info update request to http://172.30.0.4:8080/v1/memory has not returned in 115.22s
2024-07-04T08:08:49.824Z        WARN    node-state-poller-0     io.trino.metadata.RemoteNodeState       Node state update request to http://172.30.0.4:8080/v1/info/state has not returned in 104.20s
2024-07-04T08:08:50.814Z        WARN    query-management-0      io.trino.memory.RemoteNodeMemory        Memory info update request to http://172.30.0.4:8080/v1/memory has not returned in 116.23s
2024-07-04T08:08:50.847Z        WARN    http-client-node-manager-50     io.trino.metadata.RemoteNodeState       Error fetching node state from http://172.30.0.4:8080/v1/info/state: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
2024-07-04T08:08:50.848Z        WARN    http-client-memoryManager-scheduler-1   io.trino.memory.RemoteNodeMemory        Error fetching memory info from http://172.30.0.4:8080/v1/memory: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
2024-07-04T08:08:50.848Z        WARN    TaskInfoFetcher-20240704_080620_00005_4yit8.6.0.0-506   io.trino.server.remotetask.RequestErrorTracker  Error getting info for task 20240704_080620_00005_4yit8.6.0.0: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://172.30.0.4:8080/v1/task/20240704_080620_00005_4yit8.6.0.0
2024-07-04T08:08:50.820Z        WARN    ContinuousTaskStatusFetcher-20240704_080620_00005_4yit8.1.0.0-458       io.trino.server.remotetask.RequestErrorTracker  Error getting task status 20240704_080620_00005_4yit8.1.0.0: http://172.30.0.4:8080/v1/task/20240704_080620_00005_4yit8.1.0.0
io.trino.server.remotetask.SimpleHttpResponseHandler$ServiceUnavailableException: Server returned SERVICE_UNAVAILABLE: http://172.30.0.4:8080/v1/task/20240704_080620_00005_4yit8.1.0.0/status
        at io.trino.server.remotetask.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:52)
        at io.trino.server.remotetask.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:27)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
        at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)

```

**Comment by raunaqmorarka** [comment]
Trino is designed to fully utilize CPU when there is enough parallelism in the workload, it usually doesn't lead to communication threads getting starved. Was there full GC or a crash of the worker ?
Which release of Trino is this ? Could you check if disabling `experimental.thread-per-driver-scheduler-enabled` makes a difference ?
Resource groups only provide admission control, it does not affect resource usage of running queries.
If this happens under high concurrency, you can look at configuration a lower limit on `query.max-concurrent-queries`. If it's due to specific queries being resource heavy, then tuning `task.max-drivers-per-task` lower may help.

**Comment by youngjinkim0706** [comment]
Thank you for your response, @raunaqmorarka.
I'm going to check the parameters which you let me know. 

FYI, 
I executed queries on both Trino 403 and 450 versions, the 503 error occured in both trino release. And these queries were run sequentially, meaning only a single query was executed in the Trino cluster at any given time.

There was a Major GC, not a Full GC, and the worker container was restarted. I suspect this occurred because an exception was thrown in the execute function of HiveSplitManager.java:
```
public void execute(Runnable command)
{
    try {
        delegate.execute(command);
    }
    catch (RejectedExecutionException e) {
        throw new TrinoException(SERVER_SHUTTING_DOWN, "Server is shutting down", e);
    }
}
```

**Comment by youngjinkim0706** [comment]
Additionally, when I set the `task.max-worker-threads` parameter lower than the CPU resources allocated to the pod and executed the query, the query ran successfully.

What I am curious about is, if the value of `max-worker-threads` is high, it seems to occupy resources meant for communication, leading to the error that occurred earlier. Is there a way at the Trino configuration level to prioritize or allocate static resources specifically for communication threads? If not, can the CPU usage priority for threads be set in the JVM?

**Comment by raunaqmorarka** [comment]
> There was a Major GC, not a Full GC, and the worker container was restarted

You should look into why the worker was restarted. You might need to reduce JVM heap size or increase `memory.heap-headroom-per-node` if the pod was oom killed by k8s or the JVM crashed on OOM.

**Comment by akenO8** [comment]
Can't get `trino.execution.executor:name=TaskExecutor.RunningSplits` from `http://worker:9300/v1/jmx/mbean`
![image](https://github.com/user-attachments/assets/16c2d36e-db6d-40bc-8f76-b81b1fb41b5a)

**Comment by okayhooni** [comment]
I am not sure that your case is same as mine. but in my situation, the issue was linked to the default enablement of `parquet.experimental.vectorized-decoding` (introduced in v448) on worker containers running on AWS Graviton 2&3 (arm64) nodes.

If you are deploying Trino on these instance types, it could potentially be relevant to your scenario.

**Comment by raunaqmorarka** [comment]
> I executed queries on both Trino 403 and 450 versions, the 503 error occured in both trino release

Based on that, it's probably not related to recent changes

**Comment by okayhooni** [comment]
I found this issue was reproduced even with lower `task.max-worker-threads` configuration.

In my case, this issue was just another side-effect of thread-per-driver scheduler, reported on the issue below.
- https://github.com/trinodb/trino/issues/21512

Experimental config. `experimental.thread-per-driver-scheduler-enabled` was enabled by default since `v438`

When I disabled it, then this issue was removed..! I guess this is helpful also on your case :)

**Comment by wwbbcjeyc** [comment]
> Can't get `trino.execution.executor:name=TaskExecutor.RunningSplits` from `http://worker:9300/v1/jmx/mbean` ![image](https://private-user-images.githubusercontent.com/37773807/348622919-16c2d36e-db6d-40bc-8f76-b81b1fb41b5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDE3NjEsIm5iZiI6MTcyNDE0MTQ2MSwicGF0aCI6Ii8zNzc3MzgwNy8zNDg2MjI5MTktMTZjMmQzNmUtZGI2ZC00MGJjLThmNzYtYjgxYjFmYjQxYjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA4MTEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MmRiZGUyNGQ5NDNjN2Q1ZDVlNjM4YTJjNmE4YzljODE0Y2M1ZmY3Y2FiM2QzNmJlMjFiMWRmNDNlNjdkMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8qfEzON3p46oXltKPuBX7WFqJwGbjfHcYp_BJJGG2kw)

I found that when experimental.thread-per-driver-scheduler-enabled=true, it could not be obtained normally "Trino. Execution. Executor: name = TaskExecutor. RunningSplits" indicators,
You need to set "experiment.thread-per-driver-scheduler-enabled" to "false"

**Comment by dain** [comment]
If anyone is still seeing this problem, please open a new issue.
