### ISSUE TITLE
Regression on handling CAST(varchar_partition_field AS date) > date_type_filter_value on query planning

### ISSUE THREAD

**Issue by okayhooni** [trinodb/trino#22643]
We updated some of our Trino clusters from `v433` to latest `v451`, and found the query with filter like `CAST(varchar_partition_field AS date) > date_type_filter_value` cannot use partition-pruning on `ScanFilterProject` of query plan, NOT like as before!

so, it raises `HIVE_EXCEEDED_PARTITION_LIMIT` with `hive.max-partitions-per-scan` config, NOT like as before.

I guess it is the same issue as https://github.com/trinodb/trino/issues/12925 by @ubyyj 
That issue was solved on https://github.com/trinodb/trino/pull/13567 by @findepi 
But this issue appear to be revived? between `v433` and `v451`.

Example) query to `market:date_string_partitioned_table` : partitioned with string type `part_date` field
```
    ...
    WHERE 
        CAST(ois.part_date as DATE) BETWEEN CAST('2024-07-09' as DATE) - INTERVAL '1' DAY AND CAST('2024-07-09' as DATE)
```

plan on `v433`
```
Fragment 6 [SOURCE]
    Output layout: [order_summary_id_2, substr]
    Output partitioning: BROADCAST []
    InnerJoin[criteria = ("shop_id" = "shop_id_42"), distribution = REPLICATED]
    │   Layout: [order_summary_id_2:varchar, substr:varchar]
    │   Estimates: {rows: 3360 (223.13kB), cpu: 554.95k, memory: 27.24kB, network: 0B}
    │   Distribution: REPLICATED
    │   dynamicFilterAssignments = {shop_id_42 -> #df_2450}
    ├─ ScanFilterProject[table = hive:market:date_string_partitioned_table, filterPredicate = (("status" = VARCHAR 'COMPLETED') AND (NOT ("shop_id" IN (VARCHAR '11', VARCHAR '25', VARCHAR '72', VARCHAR '78'))) AND (CAST("part_date_7" AS DATE) >= DATE '2024-07-08') AND (CAST("part_date_7" AS DATE) <= DATE '2024-07-09')), dynamicFilters = {"shop_id" = #df_2450}]
    │      Layout: [order_summary_id_2:varchar, shop_id:varchar]
    │      Estimates: {rows: 129901 (2.55MB), cpu: 6.10M, memory: 0B, network: 0B}/{rows: 13825 (278.44kB), cpu: 6.10M, memory: 0B, network: 0B}/{rows: 13825 (278.44kB), cpu: 278.44k, memory: 0B, network: 0B}
    │      shop_id := shop_id:string:REGULAR
    │      order_summary_id_2 := order_summary_id:string:REGULAR
    │      part_date_7 := part_date:string:PARTITION_KEY
    │          :: [[2024-07-08], [2024-07-09]]
    │      status := status:string:REGULAR
    └─ LocalExchange[partitioning = SINGLE]
       │   Layout: [shop_id_42:varchar, substr:varchar]
       │   Estimates: {rows: 18 (1.09kB), cpu: 0, memory: 0B, network: 0B}
       └─ RemoteSource[sourceFragmentIds = [7]]
              Layout: [shop_id_42:varchar, substr:varchar]
```

plan on `v451`
```
Fragment 5 [SOURCE]
Output layout: [order_summary_id_0, shop_id, part_date_5]
Output partitioning: HASH [order_summary_id_0]
ScanFilterProject[table = hive:market:date_string_partitioned_table, filterPredicate = ($not((shop_id IN (varchar '11', varchar '25', varchar '72', varchar '78'))) AND (status = varchar 'COMPLETED')), dynamicFilters = {shop_id = #df_2268}]
Layout: [order_summary_id_0:varchar, shop_id:varchar, part_date_5:varchar]
Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: 0B}/{rows: ? (?), cpu: ?, memory: 0B, network: 0B}/{rows: ? (?), cpu: ?, memory: 0B, network: 0B}
shop_id := shop_id:string:REGULAR
order_summary_id_0 := order_summary_id:string:REGULAR
part_date_5 := part_date:string:PARTITION_KEY
status := status:string:REGULAR
```
There is no `(CAST("part_date_7" AS DATE) >= DATE '2024-07-08') AND (CAST("part_date_7" AS DATE) <= DATE '2024-07-09')` filter on `ScanFilterProject`.
so it raises `HIVE_EXCEEDED_PARTITION_LIMIT` with `hive.max-partitions-per-scan=1500` config.
```
io.trino.spi.TrinoException: Query over table 'market.date_string_partitioned_table' can potentially read more than 1500 partitions
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:358)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:281)
	at io.trino.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
	at io.trino.$gen.Trino_f2ca449____20240709_050900_2.run(Unknown Source)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:79)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by ebyhr** [comment]
Is this same issue as #22268?

**Comment by okayhooni** [comment]
> Is this the same issue as #22268?

Thank you for sharing the issue link..!

I am not sure it is exactly same issue, but it looks certain to be related..!

**Comment by okayhooni** [comment]
@ebyhr , thanks to your mention and the comment by @marcinsbd below, I found this issue was the same as #22268 
- https://github.com/trinodb/trino/issues/22268#issuecomment-2168540671

When I revert the commit(since `v445`) on `processInnerJoin()` of `PredicatePushDown`, this issue was removed.
- https://github.com/trinodb/trino/pull/21429
