### ISSUE TITLE
450 -> 451 io.airlift.discovery.client.CachingServiceSelector 

### ISSUE THREAD

**Issue by raphaelauv** [trinodb/trino#22652]
Using the container version 450 I have no problem but when I try to use 451 , all the workers fail with

```log
ERROR   Discovery-2     io.airlift.discovery.client.CachingServiceSelector
Cannot connect to discovery server for refresh (trino/general)
io.airlift.discovery.client.DiscoveryException: Lookup of trino failed with status code 406
        at io.airlift.discovery.client.HttpDiscoveryLookupClient$1.handle(HttpDiscoveryLookupClient.java:138)
        at io.airlift.discovery.client.HttpDiscoveryLookupClient$1.handle(HttpDiscoveryLookupClient.java:126)
        at io.airlift.http.client.jetty.JettyResponseFuture.processResponse(JettyResponseFuture.java:135)
        at io.airlift.http.client.jetty.JettyResponseFuture.completed(JettyResponseFuture.java:109)
        at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:89)
        at org.eclipse.jetty.client.transport.ResponseListeners.notifyComplete(ResponseListeners.java:350)
        at org.eclipse.jetty.client.transport.ResponseListeners.lambda$addCompleteListener$7(ResponseListeners.java:335)
        at org.eclipse.jetty.client.transport.ResponseListeners.notifyComplete(ResponseListeners.java:350)
        at org.eclipse.jetty.client.transport.ResponseListeners.notifyComplete(ResponseListeners.java:342)
        at org.eclipse.jetty.client.transport.HttpReceiver.terminateResponse(HttpReceiver.java:420)
        at org.eclipse.jetty.client.transport.HttpReceiver.terminateResponse(HttpReceiver.java:402)
        at org.eclipse.jetty.client.transport.HttpReceiver.lambda$responseSuccess$3(HttpReceiver.java:367)
        at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
        at org.eclipse.jetty.util.thread.SerializedInvoker.run(SerializedInvoker.java:117)
        at org.eclipse.jetty.client.transport.HttpReceiver.responseHeaders(HttpReceiver.java:243)
```

using the helm chart 0.24.0 , any reason ? thanks

**Comment by raphaelauv** [comment]
it was related to a new istio -> https://stackoverflow.com/a/77313811/6227500
