### ISSUE TITLE
Concurrent Writes with iceberg connector gives error

### ISSUE THREAD

**Issue by nikhilm29** [trinodb/trino#22672]
Using Trino version 451
We are experiencing an issue when executing concurrent write operations. Specifically, when running a batch of 10-15 queries that include MERGE operations simultaneously, we encounter frequent error.

```
org.apache.iceberg.exceptions.CommitFailedException: Metadata location [s3a://bucket/folder/metadata/00125-11640b79-6b12-485b-bf1d-dabe7f176b62.metadata.json] is not same as table metadata location [s3a://bucket/folder/metadata/00126-30499939-27f3-4674-b6b2-ce27ef000c55.metadata.json] for schema.table_name
	at io.trino.plugin.iceberg.catalog.hms.HiveMetastoreTableOperations.commitTableUpdate(HiveMetastoreTableOperations.java:100)
	at io.trino.plugin.iceberg.catalog.hms.HiveMetastoreTableOperations.commitToExistingTable(HiveMetastoreTableOperations.java:68)
	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.commit(AbstractIcebergTableOperations.java:175)
	at org.apache.iceberg.BaseTransaction.lambda$commitSimpleTransaction$3(BaseTransaction.java:427)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
	at org.apache.iceberg.BaseTransaction.commitSimpleTransaction(BaseTransaction.java:423)
	at org.apache.iceberg.BaseTransaction.commitTransaction(BaseTransaction.java:318)
	at io.trino.plugin.iceberg.IcebergMetadata.finishWrite(IcebergMetadata.java:2513)
	at io.trino.plugin.iceberg.IcebergMetadata.finishMerge(IcebergMetadata.java:2414)
	at io.trino.spi.connector.ConnectorMetadata.finishMerge(ConnectorMetadata.java:980)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishMerge(ClassLoaderSafeConnectorMetadata.java:1260)
	at io.trino.tracing.TracingConnectorMetadata.finishMerge(TracingConnectorMetadata.java:816)
	at io.trino.metadata.MetadataManager.finishMerge(MetadataManager.java:1344)
	at io.trino.tracing.TracingMetadata.finishMerge(TracingMetadata.java:841)
	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$4(LocalExecutionPlanner.java:4133)
	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
	at io.trino.operator.Driver.processInternal(Driver.java:403)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:306)
	at io.trino.operator.Driver.tryWithLock(Driver.java:709)
	at io.trino.operator.Driver.process(Driver.java:298)
	at io.trino.operator.Driver.processForDuration(Driver.java:269)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:890)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:77)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:191)
	at io.trino.$gen.Trino_451____20240715_174254_2.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:192)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:168)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:155)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

Our tables are partitioned on two columns. It is important to note that the simultaneous queries do not target the same partitions, which suggests that the issue is not related to contention on the same partition.

Any help or guidance would be appreciated!

**Comment by findinpath** [comment]
This is related to increasing the number of retries on the table.

`commit.retry.num-retries`

See https://iceberg.apache.org/docs/1.5.2/configuration/#write-properties

We've discussed previously about this topic.
Our opinion is that the number of retries should not be related to a table property, but rather to the engine.

We should add in `apache/iceberg` a way to plug in from a Trino sesion property the number of retries and make use of a session property in Trino to control the retries on the table.

cc @ebyhr @raunaqmorarka @rdblue
