### ISSUE TITLE
Trino with iceberg catalog using hive-metastore raise MaxMessageSize reached error

### ISSUE THREAD

**Issue by haowanv** [trinodb/trino#22763]
My trino can work with the catalog configuration below(using \<service-name\>:\<port\> format):

```
datalake.properties: |
    connector.name=iceberg
    iceberg.catalog.type=hive_metastore
    hive.metastore.uri=thrift://hive-standalone-metastore:9083
    hive.s3.aws-access-key=${ENV:AWS_ACCESS_KEY_ID}
    hive.s3.aws-secret-key=${ENV:AWS_SECRET_ACCESS_KEY}
    hive.s3.endpoint=http://aws.s3.com/
    iceberg.file-format=PARQUET
```

But if I create a ingress for my hive-standalone-metastore and configure hostname in catalog, trino raise error in running `show schemas in catalog` command
```
datalake.properties: |
    connector.name=iceberg
    iceberg.catalog.type=hive_metastore
    hive.metastore.uri=thrift://hive-standalone-metastore.com:80
    hive.s3.aws-access-key=${ENV:AWS_ACCESS_KEY_ID}
    hive.s3.aws-secret-key=${ENV:AWS_SECRET_ACCESS_KEY}
    hive.s3.endpoint=http://aws.s3.com/
    iceberg.file-format=PARQUET
```

This is the error: 
```
Caused by: io.trino.spi.TrinoException: MaxMessageSize reached
        at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getAllDatabases(ThriftHiveMetastore.java:228)
        at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.getAllDatabases(BridgingHiveMetastore.java:95)
        at io.trino.plugin.hive.metastore.tracing.TracingHiveMetastore.lambda$getAllDatabases$1(TracingHiveMetastore.java:89)
        at io.trino.plugin.hive.metastore.tracing.Tracing.withTracing(Tracing.java:39)
        at io.trino.plugin.hive.metastore.tracing.TracingHiveMetastore.getAllDatabases(TracingHiveMetastore.java:88)
        at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadAllDatabases(CachingHiveMetastore.java:438)
        at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.lambda$new$0(CachingHiveMetastore.java:206)
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
        at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:447)
        at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:433)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3576)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2318)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2191)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2081)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4019)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4042)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5024)
        at io.trino.cache.EvictableCache.get(EvictableCache.java:145)
        at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:53)
        at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:277)
        at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getAllDatabases(CachingHiveMetastore.java:433)
        at io.trino.plugin.iceberg.catalog.hms.TrinoHiveCatalog.listNamespaces(TrinoHiveCatalog.java:191)
        at io.trino.plugin.iceberg.IcebergMetadata.listSchemaNames(IcebergMetadata.java:362)
        at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.listSchemaNames(ClassLoaderSafeConnectorMetadata.java:198)
        at io.trino.tracing.TracingConnectorMetadata.listSchemaNames(TracingConnectorMetadata.java:131)
        at io.trino.metadata.MetadataManager.listSchemaNames(MetadataManager.java:256)
        at io.trino.tracing.TracingMetadata.listSchemaNames(TracingMetadata.java:168)
        at io.trino.metadata.MetadataListing.doListSchemas(MetadataListing.java:105)
        at io.trino.metadata.MetadataListing.listSchemas(MetadataListing.java:96)
        ... 17 more
```

**Comment by haowanv** [comment]
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hive-standalone-metastore
  namespace: pinot
spec:
  ingressClassName: nginx
  rules:
  - host: hive-standalone-metastore.com
    http:
      paths:
      - path: /
        backend:
          service:
            name: hive-standalone-metastore
            port:
              number: 9083
        pathType: Prefix
```

**Comment by haowanv** [comment]
This is the ingress I used and the command works if I use 
```
hive.metastore.uri=thrift://hive-standalone-metastore:9083
```
trino> show schemas in datalake;
       Schema       
 ---------------------   
 information_schema      
(8 rows)

Query 20240723_044952_01806_qeurz, FINISHED, 2 nodes
Splits: 35 total, 35 done (100.00%)
0.17 [8 rows, 111B] [47 rows/s, 653B/s]
