### ISSUE TITLE
Planning failure due to PreAggregateCaseAggregations

### ISSUE THREAD

**Issue by martint** [trinodb/trino#22806]
This query: 

```sql
SELECT
    a,
    SUM(CASE WHEN b = 1 THEN c ELSE 0 END),
    SUM(CASE WHEN b = 2 THEN 0 ELSE c END),
    SUM(CASE WHEN b = 3 THEN 0 ELSE d END),
    SUM(CASE WHEN b = 4 THEN d ELSE 0 END)
FROM (
  VALUES
    (1,1,1,1),
) t(a, b, c, d)
GROUP BY 1
```

fails with:

```
Query 20240724_222646_00000_9bzqi failed: Invalid node. Expression dependencies ([field_0::[integer], sum_23::[bigint], field_1::[integer]]) not in source plan output ([field_0::[integer], field::[integer], sum_21::[bigint], sum_23::[bigint], sum_25::[bigint], sum_27::[bigint]])
java.lang.IllegalArgumentException: Invalid node. Expression dependencies ([field_0::[integer], sum_23::[bigint], field_1::[integer]]) not in source plan output ([field_0::[integer], field::[integer], sum_21::[bigint], sum_23::[bigint], sum_25::[bigint], sum_27::[bigint]])
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:167)
	at io.trino.sql.planner.sanity.ValidateDependenciesChecker.checkDependencies(ValidateDependenciesChecker.java:945)
	at io.trino.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:453)
	at io.trino.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:115)
	at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at io.trino.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAggregation(ValidateDependenciesChecker.java:146)
	at io.trino.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAggregation(ValidateDependenciesChecker.java:115)
	at io.trino.sql.planner.plan.AggregationNode.accept(AggregationNode.java:221)
	at io.trino.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:498)
	at io.trino.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:115)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at io.trino.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:112)
	at io.trino.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:107)
	at io.trino.sql.planner.sanity.PlanSanityChecker.lambda$validate$0(PlanSanityChecker.java:107)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:423)
	at io.trino.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:107)
	at io.trino.sql.planner.sanity.PlanSanityChecker.validateFinalPlan(PlanSanityChecker.java:78)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:274)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:238)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:233)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:498)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:478)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:416)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:272)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:150)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:134)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:570)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:545)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1137)
	at io.trino.$gen.Trino_testversion____20240724_222641_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
	Suppressed: java.lang.Exception: Current plan:
                Output[columnNames = [a, _col1, _col2, _col3, _col4, _col5, _col6]]
                │   Layout: [field:integer, sum:bigint, sum_15:bigint, sum_16:bigint, sum_17:bigint, sum_18:bigint, sum_19:bigint]
                │   a := field
                │   _col1 := sum
                │   _col2 := sum_15
                │   _col3 := sum_16
                │   _col4 := sum_17
                │   _col5 := sum_18
                │   _col6 := sum_19
                └─ Aggregate[keys = [field]]
                   │   Layout: [field:integer, sum:bigint, sum_15:bigint, sum_16:bigint, sum_17:bigint, sum_18:bigint, sum_19:bigint]
                   │   sum := sum(sum_28)
                   │   sum_15 := sum(sum_29)
                   │   sum_16 := sum(sum_30)
                   │   sum_17 := sum(sum_31)
                   │   sum_18 := sum(sum_32)
                   │   sum_19 := sum(sum_33)
                   └─ Project[]
                      │   Layout: [field:integer, sum_28:bigint, sum_29:bigint, sum_30:bigint, sum_31:bigint, sum_32:bigint, sum_33:bigint]
                      │   sum_28 := (CASE WHEN (field_0 = integer '1') THEN sum_21 ELSE bigint '0' END)
                      │   sum_29 := (CASE WHEN (field_0 = integer '2') THEN sum_23 ELSE CAST(field_1 AS bigint) END)
                      │   sum_30 := (CASE WHEN (field_0 = integer '3') THEN sum_23 ELSE CAST(field_2 AS bigint) END)
                      │   sum_31 := (CASE WHEN (field_0 = integer '4') THEN sum_25 ELSE bigint '0' END)
                      │   sum_32 := (CASE WHEN (field_0 = integer '5') THEN sum_27 ELSE bigint '0' END)
                      │   sum_33 := (CASE WHEN (field_0 = integer '6') THEN sum_23 ELSE CAST(field_3 AS bigint) END)
                      └─ Aggregate[type = FINAL, keys = [field_0, field]]
                         │   Layout: [field_0:integer, field:integer, sum_21:bigint, sum_23:bigint, sum_25:bigint, sum_27:bigint]
                         │   sum_21 := sum(sum_34)
                         │   sum_23 := sum(sum_35)
                         │   sum_25 := sum(sum_36)
                         │   sum_27 := sum(sum_37)
                         └─ LocalExchange[partitioning = HASH, arguments = [field::integer]]
                            │   Layout: [field_0:integer, field:integer, sum_34:bigint, sum_35:bigint, sum_36:bigint, sum_37:bigint]
                            └─ Aggregate[type = PARTIAL, keys = [field_0, field]]
                               │   Layout: [field_0:integer, field:integer, sum_34:bigint, sum_35:bigint, sum_36:bigint, sum_37:bigint]
                               │   sum_34 := sum(expr_20)
                               │   sum_35 := sum(expr_22)
                               │   sum_36 := sum(expr_24)
                               │   sum_37 := sum(expr_26)
                               └─ Values[]
                                      Layout: [field_0:integer, field:integer, expr_20:bigint, expr_22:bigint, expr_24:bigint, expr_26:bigint]
                                      (integer '1', integer '1', bigint '1', bigint '0', bigint '1', bigint '1')
                                      (integer '2', integer '2', bigint '2', bigint '0', bigint '2', bigint '2')
                                      (integer '3', integer '3', bigint '3', bigint '0', bigint '3', bigint '3')

		at io.trino.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:120)
		... 17 more
```

Disabling PreAggregateCaseAggregations (via pre_aggregate_case_aggregations_enabled) makes the query succeed.

**Comment by martint** [comment]
cc @sopel39
