### ISSUE TITLE
Flaky io.trino.plugin.deltalake.TestDeltaLakeAlluxioCacheFileOperations 

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#22860]
https://github.com/trinodb/trino/actions/runs/10142042323/job/28050729742?pr=22827

```
 java.lang.IllegalArgumentException: Invalid prefix or suffix
	at java.base/java.nio.file.TempFileHelper.generatePath(TempFileHelper.java:60)
	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:125)
	at java.base/java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:171)
	at java.base/java.nio.file.Files.createTempDirectory(Files.java:1017)
	at io.trino.plugin.deltalake.TestDeltaLakeAlluxioCacheFileOperations.createQueryRunner(TestDeltaLakeAlluxioCacheFileOperations.java:58)
	at io.trino.plugin.deltalake.TestDeltaLakeAlluxioCacheFileOperations.createQueryRunner(TestDeltaLakeAlluxioCacheFileOperations.java:50)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:113)
```

Might be due to https://stackoverflow.com/questions/60417342/uploading-archive-with-xcode-invalid-prefix-or-suffix

**Comment by mosabua** [comment]
fyi @JiamingMai .. can you maybe help.

**Comment by sopel39** [comment]
This was issue with my PR
