### ISSUE TITLE
Failed to connect oceanbase-ce mysql mode

### ISSUE THREAD

**Issue by Billccx** [trinodb/trino#22982]
Hello, I tried to connect oceanbase-ce mysql mode with latest Trino version but failed with error:
![网页捕获_8-8-2024_154146_localhost](https://github.com/user-attachments/assets/77c2bb0e-459a-4fc1-9cd9-4c5b7adc3d3d)

```
io.trino.spi.TrinoException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at io.trino.plugin.jdbc.JdbcRemoteIdentifiers$JdbcRemoteIdentifiersFactory.storesUpperCaseIdentifiers(JdbcRemoteIdentifiers.java:100)
	at io.trino.plugin.jdbc.JdbcRemoteIdentifiers$JdbcRemoteIdentifiersFactory.createJdbcRemoteIdentifies(JdbcRemoteIdentifiers.java:86)
	at io.trino.plugin.jdbc.BaseJdbcClient.getRemoteIdentifiers(BaseJdbcClient.java:1814)
	at io.trino.plugin.jdbc.BaseJdbcClient.getTableHandle(BaseJdbcClient.java:230)
	at io.trino.plugin.jdbc.ForwardingJdbcClient.getTableHandle(ForwardingJdbcClient.java:90)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getTableHandle$3(StatisticsAwareJdbcClient.java:111)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:34)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getTableHandle(StatisticsAwareJdbcClient.java:111)
	at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getTableHandle$5(CachingJdbcClient.java:370)
	at io.trino.cache.EmptyCache.get(EmptyCache.java:94)
	at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:793)
	at io.trino.plugin.jdbc.CachingJdbcClient.getTableHandle(CachingJdbcClient.java:370)
	at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getTableHandle$5(CachingJdbcClient.java:370)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4903)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3574)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2316)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4017)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4898)
	at io.trino.cache.EvictableCache.get(EvictableCache.java:118)
	at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:793)
	at io.trino.plugin.jdbc.CachingJdbcClient.getTableHandle(CachingJdbcClient.java:370)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.getTableHandle(DefaultJdbcMetadata.java:165)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.getTableHandle(DefaultJdbcMetadata.java:120)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableHandle(ClassLoaderSafeConnectorMetadata.java:1268)
	at io.trino.tracing.TracingConnectorMetadata.getTableHandle(TracingConnectorMetadata.java:141)
	at io.trino.metadata.MetadataManager.lambda$getTableHandle$5(MetadataManager.java:287)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at io.trino.metadata.MetadataManager.getTableHandle(MetadataManager.java:278)
	at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1940)
	at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1932)
	at io.trino.tracing.TracingMetadata.getRedirectionAwareTableHandle(TracingMetadata.java:1494)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.getTableHandle(StatementAnalyzer.java:5842)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2291)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:520)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:539)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:4891)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:3091)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:520)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:539)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:547)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1562)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:520)
	at io.trino.sql.tree.Query.accept(Query.java:118)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:539)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:499)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:488)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:97)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:285)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:218)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:884)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)
	at io.trino.$gen.Trino_dev____20240808_073238_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
	Suppressed: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
		at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:885)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:810)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189)
		at io.trino.plugin.jdbc.TracingDataSource$JdbcDataSource.getConnection(TracingDataSource.java:69)
		at io.opentelemetry.instrumentation.jdbc.datasource.OpenTelemetryDataSource.wrapCall(OpenTelemetryDataSource.java:156)
		at io.opentelemetry.instrumentation.jdbc.datasource.OpenTelemetryDataSource.getConnection(OpenTelemetryDataSource.java:94)
		at io.trino.plugin.jdbc.TracingDataSource.getConnection(TracingDataSource.java:48)
		at io.trino.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:60)
		at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:45)
		at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:34)
		at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:45)
		at io.trino.plugin.jdbc.RetryingConnectionFactory.lambda$openConnection$2(RetryingConnectionFactory.java:67)
		at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
		at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
		at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
		at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
		at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
		at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
		at io.trino.plugin.jdbc.RetryingConnectionFactory.openConnection(RetryingConnectionFactory.java:67)
		at io.trino.plugin.jdbc.LazyConnectionFactory.lambda$openConnection$0(LazyConnectionFactory.java:44)
		at io.trino.plugin.jdbc.LazyConnectionFactory$LazyConnection.delegate(LazyConnectionFactory.java:75)
		at io.trino.plugin.jdbc.ForwardingConnection.isClosed(ForwardingConnection.java:110)
		at io.trino.plugin.jdbc.ReusableConnectionFactory$CachedConnection.close(ReusableConnectionFactory.java:179)
		at io.trino.plugin.jdbc.BaseJdbcClient.getTableHandle(BaseJdbcClient.java:228)
		... 62 more
	Caused by: com.mysql.cj.exceptions.CJException: Unknown or incorrect time zone: 'Asia/Shanghai'
[172.17.0.3:2882] [2024-08-08 07:41:15.806889] [YB42AC110003-00061F26C4837D4B-0-0]
		at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:104)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:149)
		at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:127)
		at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:848)
		at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:771)
		at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701)
		at com.mysql.cj.protocol.a.NativeProtocol.configureTimeZone(NativeProtocol.java:2276)
		at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2282)
		at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1269)
		at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:848)
		... 87 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:885)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:810)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189)
	at io.trino.plugin.jdbc.TracingDataSource$JdbcDataSource.getConnection(TracingDataSource.java:69)
	at io.opentelemetry.instrumentation.jdbc.datasource.OpenTelemetryDataSource.wrapCall(OpenTelemetryDataSource.java:156)
	at io.opentelemetry.instrumentation.jdbc.datasource.OpenTelemetryDataSource.getConnection(OpenTelemetryDataSource.java:94)
	at io.trino.plugin.jdbc.TracingDataSource.getConnection(TracingDataSource.java:48)
	at io.trino.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:60)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:45)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:34)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:45)
	at io.trino.plugin.jdbc.RetryingConnectionFactory.lambda$openConnection$2(RetryingConnectionFactory.java:67)
	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
	at io.trino.plugin.jdbc.RetryingConnectionFactory.openConnection(RetryingConnectionFactory.java:67)
	at io.trino.plugin.jdbc.LazyConnectionFactory.lambda$openConnection$0(LazyConnectionFactory.java:44)
	at io.trino.plugin.jdbc.LazyConnectionFactory$LazyConnection.delegate(LazyConnectionFactory.java:75)
	at io.trino.plugin.jdbc.ForwardingConnection.getMetaData(ForwardingConnection.java:117)
	at io.trino.plugin.jdbc.ForwardingConnection.getMetaData(ForwardingConnection.java:117)
	at io.trino.plugin.jdbc.JdbcRemoteIdentifiers$JdbcRemoteIdentifiersFactory.storesUpperCaseIdentifiers(JdbcRemoteIdentifiers.java:95)
	... 65 more
Caused by: com.mysql.cj.exceptions.CJException: Unknown or incorrect time zone: 'Asia/Shanghai'
[172.17.0.3:2882] [2024-08-08 07:41:11.797934] [YB42AC110003-00061F26C2537DFF-0-0]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:104)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:149)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:127)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:848)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:771)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701)
	at com.mysql.cj.protocol.a.NativeProtocol.configureTimeZone(NativeProtocol.java:2276)
	at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2282)
	at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1269)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:848)
	... 90 more
```

This is my JVM config:

```
#
# WARNING
# ^^^^^^^
# This configuration file is for development only and should NOT be used
# in production. For example configuration, see the Trino documentation.
#
-server
-Xmx4G
-XX:InitialRAMPercentage=80
-XX:MaxRAMPercentage=80
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+ExitOnOutOfMemoryError
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-XX:ReservedCodeCacheSize=512M
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-Djdk.attach.allowAttachSelf=true
-Djdk.nio.maxCachedBufferSize=2000000
-XX:+UnlockDiagnosticVMOptions
-XX:+UseAESCTRIntrinsics
-Duser.timezone=Etc/GMT-8

```

This is oceanbase.properties:
```
connector.name=mysql
connection-url=jdbc:mysql://localhost:2881
connection-user=ccx
connection-password=142857
```

I have read this issue, but still not work: https://github.com/trinodb/trino/issues/20033

It work well on trino-server-392, but on latest version 454, it failed.

Would you please give me some advice? Thanks in advance.

**Comment by ebyhr** [comment]
This should be an issue on the database side, not the connector. Please take a look at https://dev.mysql.com/doc/refman/9.0/en/time-zone-support.html
