### ISSUE TITLE
Don't suport subquery (select *)

### ISSUE THREAD

**Issue by Heltman** [trinodb/trino#23009]
Trino support subquery like below:

```sql
select (select x, y) from (select 1 x,2 y) a;
```

but don't support 
```sql
select (select *) from (select 1 x,2 y) a;
```

will raise exception:

```log
io.trino.spi.TrinoException: line 1:16: SELECT * not allowed in queries without FROM clause
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:52)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:46)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelectAllColumns(StatementAnalyzer.java:4748)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:4667)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:3095)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:521)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:540)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:548)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1569)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:521)
	at io.trino.sql.tree.Query.accept(Query.java:118)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:540)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:500)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:494)
```

**Comment by wendigo** [comment]
@martint is this a correct behaviour?

**Comment by martint** [comment]
This is expected behavior. SELECT * resolves columns from the FROM clause, and the subquery has no FROM clause.

The first query works because the column references are resolved from the outer scope (I.e., it’s a correlated subquery).
