### ISSUE TITLE
testRegisterTableWithDroppedTable is flaky

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#23082]
https://github.com/trinodb/trino/actions/runs/10470425943/job/28995599329?pr=23081

```
 Expecting actual:
  "java.lang.AssertionError: Expected query to fail: CALL system.register_table (CURRENT_SCHEMA, 'test_register_table_with_dropped_table_lv66znb962_new', 'file:///tmp/d15b33d7-9420-48c9-a325-62b318190d74/tpch/test_register_table_with_dropped_table_lv66znb962-2d03c7cf223f4c96a81e612d323fd1bb') [QueryId: 20240820_112857_00291_qd6in]
	at io.trino.testing.QueryAssertions.assertQueryFails(QueryAssertions.java:466)
	at io.trino.testing.AbstractTestQueryFramework.assertQueryFails(AbstractTestQueryFramework.java:445)
	at io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.testRegisterTableWithDroppedTable(BaseIcebergConnectorSmokeTest.java:322)
```

Perhaps there is a race between removing files and registering tables

**Comment by ebyhr** [comment]
Closing as https://github.com/trinodb/trino/pull/23099
