### ISSUE TITLE
Pinot connector issues

### ISSUE THREAD

**Issue by codrepeat** [trinodb/trino#23130]
We have multiple issues using the Pinot connector for Trino.
(Tested versions: 452 Trino + 1.1.0 Pinot, also 452 Trino + 1.2.0 Pinot)

1)
As noted in the connector docs:

> The connector performs pushdown where performance may be improved, but in order to preserve correctness an operation may not be pushed down. When pushdown of an operation may result in better performance but risks correctness, the connector prioritizes correctness.

However, in our experience, the connector rarely performs any pushdown for queries which use e.g. `date_trunc` and aggregations.

Why is there no way to force the pushdown completely? The current way is basically a dice roll and queries which take 10s using Pinot directly (e.g. via Superset) can take up to 4 minutes.

2)
There is a way around this using "[dynamic tables](https://trino.io/docs/current/connector/pinot.html#dynamic-tables)". However, when we try to use Pinot functions inside the PQL part of the query, such as `dateTrunc` or `cast` we keep getting the following error: `trino error: Unknown index id: dictionary`. This is a case for queries which are working as desired when querying e.g. via Pinot UI or Superset.

Example PQL query:

```
SELECT
  dateTrunc('day',event_timestamp_local) AS event_date
  , COUNT(*) AS count
FROM tft_fd_cdn
WHERE dateTrunc('day',event_timestamp_local) >= fromDateTime('2024-08-07', 'yyyy-MM-dd')
  AND dateTrunc('day',event_timestamp_local) < fromDateTime('2024-08-22', 'yyyy-MM-dd')
GROUP BY 1
ORDER BY 1
LIMIT 10000
``` 

Using this PQL as part of the Trino query (using the dynamic table functionality) however throws the mentioned error. Even for Pinot tables without any dictionary indices.

I think found the error handling in Pinot source code [here](https://github.com/apache/pinot/blob/ef3caa391fe297ca405d39aa6b64b7fdecbe856f/pinot-segment-spi/src/main/java/org/apache/pinot/segment/spi/index/IndexService.java#L144), but it doesn't seem like the error itself is on Pinot's side, as using direct Superset->Pinot connection is working fine.

In our Trino->Pinot connection we use the following properties:
`pinot.controller-urls`, `pinot.broker-url` + AUTH options and we also tested explicitly enabling `pinot.aggregation-pushdown.enabled` and `pinot.count-distinct-pushdown.enabled`.

**Comment by sthandassery** [comment]
I see similar issue with dynamic tables. I am on Trino 464.

java.lang.IllegalArgumentException: Unknown index id: dictionary
        at org.apache.pinot.segment.spi.index.IndexService.get(IndexService.java:144)
        at org.apache.pinot.segment.spi.index.StandardIndexes.dictionary(StandardIndexes.java:92)
        at org.apache.pinot.segment.local.segment.index.datasource.BaseDataSource.getDictionary(BaseDataSource.java:67)
        at org.apache.pinot.core.operator.ColumnContext.fromDataSource(ColumnContext.java:65)
        at org.apache.pinot.core.operator.transform.function.TransformFunctionFactory.lambda$get$0(TransformFunctionFactory.java:356)
        at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:300)
        at org.apache.pinot.core.operator.transform.function.TransformFunctionFactory.get(TransformFunctionFactory.java:356)
        at io.trino.plugin.pinot.query.PinotTypeResolver.resolveExpressionType(PinotTypeResolver.java:78)
        at io.trino.plugin.pinot.query.DynamicTableBuilder.getPinotColumnHandle(DynamicTableBuilder.java:168)
        at io.trino.plugin.pinot.query.DynamicTableBuilder.getPinotColumns(DynamicTableBuilder.java:148)
        at io.trino.plugin.pinot.query.DynamicTableBuilder.buildFromPql(DynamicTableBuilder.java:100)
        at io.trino.plugin.pinot.PinotMetadata.getTableHandle(PinotMetadata.java:237)
        at io.trino.plugin.pinot.PinotMetadata.getTableHandle(PinotMetadata.java:140)
        at io.trino.tracing.TracingConnectorMetadata.getTableHandle(TracingConnectorMetadata.java:142)
        at io.trino.metadata.MetadataManager.lambda$getTableHandle$5(MetadataManager.java:292)
        at java.base/java.util.Optional.flatMap(Optional.java:289)
        at io.trino.metadata.MetadataManager.getTableHandle(MetadataManager.java:283)
        at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1968)
        at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1960)
        at io.trino.tracing.TracingMetadata.getRedirectionAwareTableHandle(TracingMetadata.java:1494)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.getTableHandle(StatementAnalyzer.java:5847)
        at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2296)

**Comment by sthandassery** [comment]
I think the IndexService class loader is unable to see and load the IndexPlugin implementations [here](https://github.com/apache/pinot/blob/ef3caa391fe297ca405d39aa6b64b7fdecbe856f/pinot-segment-spi/src/main/java/org/apache/pinot/segment/spi/index/IndexService.java#L93)
