### ISSUE TITLE
Iceberg time travel query thorw column connot be resolved

### ISSUE THREAD

**Issue by learnting** [trinodb/trino#23295]
trino version 422
sql
```sql
drop table if exists test;
CREATE TABLE test( _id varchar) WITH (format = 'ORC', format_version = 2); 
select _id from test FOR TIMESTAMP AS OF TIMESTAMP '2024-09-05 03:44:00 UTC'; 
 _id 
-----
(0 rows)

alter table test add column str varchar; 
select str from test;
 str 
-----
(0 rows)

select str from test FOR TIMESTAMP AS OF TIMESTAMP '2024-09-05 03:44:40 UTC'; 
Query 20240905_034441_02663_xmkpd failed: line 1:8: Column 'str' cannot be resolved
select str from test FOR TIMESTAMP AS OF TIMESTAMP '2024-09-05 03:44:40 UTC'
```
[hdfs_info.txt](https://github.com/user-attachments/files/16883748/hdfs_info.txt)

**Comment by findinpath** [comment]
@learnting 

changing the schema of the table does not automatically create a new snapshot of the table.
It only creates a new metadata file.

if you create a new snapshot of the table, you'll be able to view the newly added column.

However, maybe we should revisit this special use case.

https://github.com/trinodb/trino/blob/a071a795ff3758a121a483c584e50d43929ab55e/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L450


Because the table is queryable without time travel, we should be able to query it also with time travel even though there's not a snapshot of the table at the requested timestamp.

```
trino> select _id, str from iceberg.default.test ;
 _id | str 
-----+-----
(0 rows)

Query 20240909_103109_00011_6ixat, FINISHED, 1 node
http://localhost:8080/ui/query.html?20240909_103109_00011_6ixat
Splits: 1 total, 1 done (100.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 0% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
Peak Memory: 0B
0.08 [0 rows, 0B] [0 rows/s, 0B/s]

trino> select _id, str from iceberg.default.test FOR TIMESTAMP AS OF TIMESTAMP '2024-09-09 12:30:00.000 Europe/Vienna';
Query 20240909_103117_00012_6ixat failed: line 1:13: Column 'str' cannot be resolved
io.trino.spi.TrinoException: line 1:13: Column 'str' cannot be resolved
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:52)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:46)
	at io.trino.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:34)
	at io.trino.sql.analyzer.Scope.lambda$resolveField$7(Scope.java:227)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.trino.sql.analyzer.Scope.resolveField(Scope.java:227)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:738)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:645)
```
