### ISSUE TITLE
Flaky TestParquetReader.testComplexNestedStructs

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#2330]
```
2019-12-20T13:38:22.1711546Z [ERROR] Tests run: 1545, Failures: 1, Errors: 0, Skipped: 58, Time elapsed: 1,451.957 s <<< FAILURE! - in TestSuite
2019-12-20T13:38:22.1721158Z [ERROR] testComplexNestedStructs(io.prestosql.plugin.hive.parquet.TestParquetReader)  Time elapsed: 0.021 s  <<< FAILURE!
2019-12-20T13:38:22.1726596Z java.lang.IllegalArgumentException: struct field values cannot be empty
2019-12-20T13:38:22.1732906Z 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
2019-12-20T13:38:22.1742356Z 	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.lambda$createTestStructs$6(AbstractTestParquetReader.java:1620)
2019-12-20T13:38:22.1746637Z 	at java.util.ArrayList.forEach(ArrayList.java:1257)
2019-12-20T13:38:22.1755530Z 	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.createTestStructs(AbstractTestParquetReader.java:1620)
2019-12-20T13:38:22.1764461Z 	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.createNullableTestStructs(AbstractTestParquetReader.java:1629)
2019-12-20T13:38:22.1773090Z 	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.testComplexNestedStructs(AbstractTestParquetReader.java:580)
2019-12-20T13:38:22.1778165Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019-12-20T13:38:22.1784414Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019-12-20T13:38:22.1791215Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019-12-20T13:38:22.1795469Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2019-12-20T13:38:22.1802445Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2019-12-20T13:38:22.1805479Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2019-12-20T13:38:22.1807152Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2019-12-20T13:38:22.1808955Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2019-12-20T13:38:22.1810881Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2019-12-20T13:38:22.1812673Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2019-12-20T13:38:22.1814622Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-12-20T13:38:22.1816476Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-12-20T13:38:22.1818082Z 	at java.lang.Thread.run(Thread.java:748)
2019-12-20T13:38:22.1818353Z 
```

**Comment by hashhar** [comment]
Fixed in https://github.com/trinodb/trino/pull/9349
