### ISSUE TITLE
Fix `pt (default, suite-all-connectors-smoke, )` failure

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#23396]
The job keeps failing maybe after merged https://github.com/trinodb/trino/pull/12802

https://github.com/trinodb/trino/actions/runs/10837561257/job/30076161119

```sh
2024-09-12T21:17:44.4965347Z 2024-09-13T03:02:22.103+0545	WARN	startup-1	io.trino.plugin.raptor.legacy.metadata.SchemaDaoUtil	Failed to connect to database. Will retry again in 2.00s. Exception: org.h2.jdbc.JdbcSQLNonTransientConnectionException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:retry:mem:raptor;DB_CLOSE_DELAY=-1". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-232]
2024-09-12T21:17:44.4966091Z 2024-09-13T03:02:23.649+0545	ERROR	NodeRefresher	io.trino.plugin.elasticsearch.client.ElasticsearchClient	Error refreshing nodes
2024-09-12T21:17:44.4966398Z io.trino.spi.TrinoException: host1.invalid
2024-09-12T21:17:44.4966909Z 	at io.trino.plugin.elasticsearch.client.ElasticsearchClient.doRequest(ElasticsearchClient.java:742)
2024-09-12T21:17:44.4967416Z 	at io.trino.plugin.elasticsearch.client.ElasticsearchClient.fetchNodes(ElasticsearchClient.java:291)
2024-09-12T21:17:44.4967937Z 	at io.trino.plugin.elasticsearch.client.ElasticsearchClient.refreshNodes(ElasticsearchClient.java:173)
2024-09-12T21:17:44.4968324Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
2024-09-12T21:17:44.4968694Z 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
2024-09-12T21:17:44.4969309Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
2024-09-12T21:17:44.4969764Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2024-09-12T21:17:44.4970196Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-09-12T21:17:44.4970421Z 	at java.base/java.lang.Thread.run(Thread.java:1570)
2024-09-12T21:17:44.4970629Z Caused by: java.io.IOException: host1.invalid
2024-09-12T21:17:44.4971030Z 	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:937)
2024-09-12T21:17:44.4971391Z 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:300)
2024-09-12T21:17:44.4971746Z 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
2024-09-12T21:17:44.4972349Z 	at io.trino.plugin.elasticsearch.client.BackpressureRestClient.lambda$performRequest$0(BackpressureRestClient.java:83)
2024-09-12T21:17:44.4972667Z 	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
2024-09-12T21:17:44.4972996Z 	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
2024-09-12T21:17:44.4973428Z 	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
2024-09-12T21:17:44.4973775Z 	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
2024-09-12T21:17:44.4974079Z 	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
2024-09-12T21:17:44.4974370Z 	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
2024-09-12T21:17:44.4974969Z 	at io.trino.plugin.elasticsearch.client.BackpressureRestClient.executeWithRetries(BackpressureRestClient.java:141)
2024-09-12T21:17:44.4975534Z 	at io.trino.plugin.elasticsearch.client.BackpressureRestClient.performRequest(BackpressureRestClient.java:83)
2024-09-12T21:17:44.4976038Z 	at io.trino.plugin.elasticsearch.client.ElasticsearchClient.doRequest(ElasticsearchClient.java:739)
2024-09-12T21:17:44.4976169Z 	... 8 more
2024-09-12T21:17:44.4976415Z Caused by: java.net.UnknownHostException: host1.invalid
2024-09-12T21:17:44.4976819Z 	at java.base/java.net.InetAddress$CachedLookup.get(InetAddress.java:998)
2024-09-12T21:17:44.4977138Z 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1806)
2024-09-12T21:17:44.4977458Z 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1676)
2024-09-12T21:17:44.4978009Z 	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
2024-09-12T21:17:44.4978844Z 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:666)
2024-09-12T21:17:44.4979664Z 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:637)
2024-09-12T21:17:44.4980169Z 	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:472)
2024-09-12T21:17:44.4980581Z 	at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:280)
2024-09-12T21:17:44.4981291Z 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:295)
2024-09-12T21:17:44.4981939Z 	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:381)
2024-09-12T21:17:44.4982611Z 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:130)
2024-09-12T21:17:44.4983176Z 	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:116)
2024-09-12T21:17:44.4983680Z 	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138)
2024-09-12T21:17:44.4984032Z 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
2024-09-12T21:17:44.4984156Z 	... 19 more
```

**Comment by wendigo** [comment]
Actually it's a merge conflict between https://github.com/trinodb/trino/pull/12802 and https://github.com/trinodb/trino/commit/8b302523fd2a7a46ae685097889134a98ed899ca

**Comment by ebyhr** [comment]
The integration test is still flaky. https://github.com/trinodb/trino/issues/23399
