### ISSUE TITLE
"Unsupported class file major version" when using opensearch connector

### ISSUE THREAD

**Issue by ilsaloving** [trinodb/trino#23402]
I am using Trino 457 and when I try to create a data source for Opensearch, I get the following in my logs:

```
trino-1  | 2024-09-13T13:46:21.279Z     INFO    main    io.trino.connector.StaticCatalogManager -- Loading catalog my-opensearch --
trino-1  | 2024-09-13T13:46:21.364Z     INFO    main    org.hibernate.validator.internal.util.Version   HV000001: Hibernate Validator 8.0.1.Final
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       PROPERTY                                DEFAULT     RUNTIME                     DESCRIPTION
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       jmx.base-name                           ----        ----
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.backoff-init-delay           500.00ms    500.00ms                    Initial delay to wait between backpressure retries
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.backoff-max-delay            20.00s      20.00s                      Maximum delay to wait between backpressure retries
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.connect-timeout              1.00s       1.00s                       OpenSearch connect timeout
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.default-schema-name          default     default                     Default schema name to use
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.host                         ----        [siem.3pillarglobal.com]
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.http-thread-count            4           4                           Number of threads handling HTTP connections to OpenSearch cluster
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.ignore-publish-address       false       false
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.tls.keystore-password        [REDACTED]  [REDACTED]
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.tls.keystore-path            ----        /etc/trino/certs/certs.pem
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.max-http-connections         25          25                          Maximum number of persistent HTTP connections to OpenSearch cluster
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.max-retry-time               30.00s      30.00s                      Maximum timeout in case of multiple retries
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.node-refresh-interval        1.00m       1.00m                       How often to refresh the list of available nodes in the OpenSearch cluster
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.port                         9200        9200
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.projection-pushdown-enabled  true        true                        Read only required fields from a row type
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.request-timeout              10.00s      10.00s                      OpenSearch request timeout
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.scroll-size                  1000        1000                        Scroll batch size
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.scroll-timeout               1.00m       1.00m                       Scroll timeout
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.security                     ----        PASSWORD
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.tls.enabled                  false       true
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.tls.truststore-path          ----        /etc/trino/certs/keys.pem
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.tls.truststore-password      [REDACTED]  [REDACTED]
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.tls.verify-hostnames         true        false
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.auth.password                [REDACTED]  [REDACTED]
trino-1  | 2024-09-13T13:46:21.531Z     INFO    main    Bootstrap       opensearch.auth.user                    ----        admin
trino-1  | 2024-09-13T13:46:21.753Z     WARN    main    com.google.inject.internal.util.LineNumbers     Failed loading line numbers. ASM is probably out of date. Further failures won't be logged.
trino-1  | java.lang.IllegalArgumentException: Unsupported class file major version 66
trino-1  |      at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:199)
trino-1  |      at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:180)
trino-1  |      at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:166)
trino-1  |      at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:287)
trino-1  |      at com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:74)
trino-1  |      at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:48)
trino-1  |      at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:44)
trino-1  |      at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3574)
trino-1  |      at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2316)
trino-1  |      at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189)
trino-1  |      at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079)
trino-1  |      at com.google.common.cache.LocalCache.get(LocalCache.java:4017)
trino-1  |      at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4040)
trino-1  |      at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4989)
trino-1  |      at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4996)
trino-1  |      at com.google.inject.internal.util.StackTraceElements.forMember(StackTraceElements.java:67)
trino-1  |      at com.google.inject.internal.SourceFormatter.formatMember(SourceFormatter.java:91)
trino-1  |      at com.google.inject.internal.SourceFormatter.formatInjectionPoint(SourceFormatter.java:97)
trino-1  |      at com.google.inject.internal.SourceFormatter.format(SourceFormatter.java:49)
trino-1  |      at com.google.inject.internal.GenericErrorDetail.formatDetail(GenericErrorDetail.java:26)
trino-1  |      at com.google.inject.spi.ErrorDetail.format(ErrorDetail.java:64)
trino-1  |      at com.google.inject.internal.Messages.formatMessages(Messages.java:90)
trino-1  |      at com.google.inject.CreationException.getMessage(CreationException.java:50)
trino-1  |      at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:420)
trino-1  |      at java.base/java.lang.Throwable.toString(Throwable.java:519)
trino-1  |      at java.base/java.lang.Throwable.<init>(Throwable.java:334)
trino-1  |      at java.base/java.lang.Exception.<init>(Exception.java:103)
trino-1  |      at java.base/java.util.concurrent.ExecutionException.<init>(ExecutionException.java:90)
trino-1  |      at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
trino-1  |      at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
trino-1  |      at io.airlift.concurrent.MoreFutures.getFutureValue(MoreFutures.java:193)
trino-1  |      at io.airlift.concurrent.MoreFutures.getFutureValue(MoreFutures.java:176)
trino-1  |      at io.airlift.concurrent.MoreFutures.getDone(MoreFutures.java:280)
trino-1  |      at io.trino.util.Executors.executeUntilFailure(Executors.java:50)
trino-1  |      at io.trino.connector.StaticCatalogManager.loadInitialCatalogs(StaticCatalogManager.java:155)
trino-1  |      at io.trino.server.Server.doStart(Server.java:162)
trino-1  |      at io.trino.server.Server.lambda$start$0(Server.java:97)
trino-1  |      at io.trino.$gen.Trino_457____20240913_134614_1.run(Unknown Source)
trino-1  |      at io.trino.server.Server.start(Server.java:97)
trino-1  |      at io.trino.server.TrinoServer.main(TrinoServer.java:37)
trino-1  | 
trino-1  | 
trino-1  | 2024-09-13T13:46:21.782Z     ERROR   main    io.trino.server.Server  Unable to create injector, see the following errors:
trino-1  | 
trino-1  | 1) [Guice/ErrorInjectingConstructor]: TrinoException: toDerInputStream rejects tag type 45
trino-1  |   at OpenSearchClient.<init>(Unknown Source)
trino-1  |   at java.base/DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)

```

Cursory research says that this occurs when the library is too old for the JRE.

**Comment by wendigo** [comment]
The warning that you see is not important at all - this is Guice augmentation that introduces a noise but it isn't the cause of failure. The cause is in the exception: `toDerInputStream rejects tag type 45` so it seems like a misconfiguration on your end.

**Comment by wendigo** [comment]
The supplied key is in PEM format, not p12 which is causing this error. Closing.

**Comment by ilsaloving** [comment]
The documentation (https://trino.io/docs/current/connector/opensearch.html#connection-security-with-tls) makes no mention that the certificate format must be in p12.  In fact, it specifically says TO use PEM.

**Comment by mosabua** [comment]
Hm ... thats interesting and weird @wendigo  .. contrary to a whole bunch of docs. I am not sure how to proceed with a doc update here

**Comment by wendigo** [comment]
@mosabua it's about what opensearch supports

**Comment by hashhar** [comment]
I think something is wrong with docs. Java never supported PEM as a "keystore", it supports P12 (PKCS) or JKS.

(A PEM can contain both the certs and the private keys but it rarely does in practice).

The tests we have use a JKS (see https://github.com/trinodb/trino/blob/c0aa7d9dd65652d82d63cc00398b4906171ce099/plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/TestPasswordAuthentication.java#L82).

**Comment by ilsaloving** [comment]
@wendigo As @hashhar said, this is not about connecting to opensearch.  It's about the trino opensearch connector, accessing the truststore that holds the desired certificates.  
> If your cluster uses globally-trusted certificates, you only need to enable TLS. If you require custom configuration for certificates, the connector supports key stores and trust stores in PEM or Java Key Store (JKS) format.

The documentation should not indicate the connector supports .pem files, if the connector doesn't actually support that.

**Comment by mosabua** [comment]
Docs update in https://github.com/trinodb/trino/pull/23811
