### ISSUE TITLE
`fault_tolerant_execution_adaptive_join_reordering_enabled` is causing previous working queries to fail

### ISSUE THREAD

**Issue by kirkhansen** [trinodb/trino#23407]
A query like:

```sql
WITH distinct_things AS (
    SELECT DISTINCT pff.id
    FROM
        <table_1> AS ceg
    JOIN <table_2> AS pff
        ON ceg.id = pff.id
)
SELECT
    df.id,
    simplify_geometry(ST_GeomFromBinary(ceg.geometry), 0.01) AS geometry
FROM
    distinct_things AS df
JOIN <table_2> AS ceg
    ON df.id = ceg.id;
```

 worked on Trino version 448. We recently upgraded Trino to 457, and started seeing this error
```
java.lang.IllegalArgumentException: Unable to remove plan node as it contains 0 or more than 1 children
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
	at io.trino.sql.planner.optimizations.PlanNodeSearcher.removeFirstRecursive(PlanNodeSearcher.java:175)
	at io.trino.sql.planner.optimizations.PlanNodeSearcher.removeFirst(PlanNodeSearcher.java:167)
	at io.trino.sql.planner.iterative.rule.AdaptiveReorderPartitionedJoin.removeLocalExchangeFromBuildSide(AdaptiveReorderPartitionedJoin.java:165)
	at io.trino.sql.planner.iterative.rule.AdaptiveReorderPartitionedJoin.apply(AdaptiveReorderPartitionedJoin.java:142)
	at io.trino.sql.planner.iterative.rule.AdaptiveReorderPartitionedJoin.apply(AdaptiveReorderPartitionedJoin.java:79)
	at io.trino.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:216)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:181)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:144)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:264)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:146)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:264)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:146)
	at io.trino.sql.planner.iterative.IterativeOptimizer.optimizeAndMarkPlanChanges(IterativeOptimizer.java:129)
	at io.trino.sql.planner.AdaptivePlanner.optimizePlan(AdaptivePlanner.java:185)
	at io.trino.sql.planner.AdaptivePlanner.optimize(AdaptivePlanner.java:148)
	at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.optimizePlan(EventDrivenFaultTolerantQueryScheduler.java:1126)
	at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.optimize(EventDrivenFaultTolerantQueryScheduler.java:1085)
	at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.schedule(EventDrivenFaultTolerantQueryScheduler.java:1017)
	at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.run(EventDrivenFaultTolerantQueryScheduler.java:843)
	at io.trino.$gen.Trino_457____20240913_153010_2.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```
Doing a `SET SESSION fault_tolerant_execution_adaptive_join_reordering_enabled=false`, and re-executing the query returns the desired rows without error.

All tables involved are using an iceberg catalog backed by a hive metastore.

**Comment by wendigo** [comment]
cc @gaurav8297 @losipiuk
