### ISSUE TITLE
Hive use Alluxio cluster Bug

### ISSUE THREAD

**Issue by luhea** [trinodb/trino#23528]
Trino version:452
External alluxio cluster version:2.9.1
Trino deployment k8s,Alluxio deployment physical machine,Trino use socket read Alluxio cluster data
In new version trino have a error :
![image](https://github.com/user-attachments/assets/985c5e45-6fa0-456b-8478-a616c07f0d38)

**Comment by raunaqmorarka** [comment]
This is not support at the moment, but will be after https://github.com/trinodb/trino/pull/21603

**Comment by luhea** [comment]
> This is not support at the moment, but will be after [#21603](https://github.com/trinodb/trino/pull/21603)

Hello,@raunaqmorarka ,in Trino 462，config fs.alluxio.enabled=true in Hive catalog,
use：./trino-cli-462 https://trino-test.test.tech --user=hive --catalog hive --password --debug

Error:

io.trino.spi.TrinoException: Failed to list directory: alluxio://alluxio.bd.test.tech:29998/hive/warehouse/test.db/test1/pt_dt=2024-11-02
        at io.trino.plugin.hive.fs.HiveFileIterator$FileStatusIterator.processException(HiveFileIterator.java:176)
        at io.trino.plugin.hive.fs.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:145)
        at io.trino.plugin.hive.fs.HiveFileIterator.<init>(HiveFileIterator.java:57)
        at io.trino.plugin.hive.BackgroundHiveSplitLoader.listBucketFiles(BackgroundHiveSplitLoader.java:505)
        at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:493)
        at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:371)
        at io.trino.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:285)
        at io.trino.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
        at io.trino.$gen.Trino_462____20241112_093635_2.run(Unknown Source)
        at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:79)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.io.IOException: Error listFiles alluxio://alluxio.bd.test.tech:29998/hive/warehouse/test.db/test1/pt_dt=2024-11-02
        at io.trino.filesystem.alluxio.AlluxioFileSystem.listFiles(AlluxioFileSystem.java:208)
        at io.trino.filesystem.switching.SwitchingFileSystem.listFiles(SwitchingFileSystem.java:116)
        at io.trino.filesystem.tracing.TracingFileSystem.lambda$listFiles$4(TracingFileSystem.java:119)
        at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
        at io.trino.filesystem.tracing.TracingFileSystem.listFiles(TracingFileSystem.java:119)
        at io.trino.plugin.hive.fs.CachingDirectoryLister.listFilesRecursively(CachingDirectoryLister.java:118)
        at io.trino.plugin.hive.fs.TransactionScopeCachingDirectoryLister.createListingRemoteIterator(TransactionScopeCachingDirectoryLister.java:97)
        at io.trino.plugin.hive.fs.TransactionScopeCachingDirectoryLister.lambda$listInternal$0(TransactionScopeCachingDirectoryLister.java:78)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4903)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3574)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2316)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4017)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4898)
        at io.trino.cache.EvictableCache.get(EvictableCache.java:118)
        at io.trino.plugin.hive.fs.TransactionScopeCachingDirectoryLister.listInternal(TransactionScopeCachingDirectoryLister.java:78)
        at io.trino.plugin.hive.fs.TransactionScopeCachingDirectoryLister.listFilesRecursively(TransactionScopeCachingDirectoryLister.java:70)
        at io.trino.plugin.hive.fs.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:140)
        ... 11 more
Caused by: alluxio.exception.AccessControlException: Permission denied: user=trino, access=r--, path=/hive/warehouse/pdc_event.db/event_pdc_halllogin_loginfailed/pt_dt=2024-11-02: failed at pt_dt=2024-11-02, inode owner=hive, inode group=hive, inode mode=rwxrwx--x
        at alluxio.exception.status.AlluxioStatusException.toAlluxioException(AlluxioStatusException.java:89)
        at alluxio.client.file.BaseFileSystem.wrapAndThrowAlluxioStatusException(BaseFileSystem.java:724)
        at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:701)
        at alluxio.client.file.BaseFileSystem.listStatus(BaseFileSystem.java:329)
        at alluxio.client.file.MetadataCachingFileSystem.listStatus(MetadataCachingFileSystem.java:192)
        at io.trino.filesystem.alluxio.AlluxioFileSystem.listFiles(AlluxioFileSystem.java:203)
        ... 29 more
Caused by: alluxio.exception.status.PermissionDeniedException: Permission denied: user=trino, access=r--, path=/hive/warehouse/test.db/test1/pt_dt=2024-11-02: failed at pt_dt=2024-11-02, inode owner=hive, inode group=hive, inode mode=rwxrwx--x
        at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:145)
        at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:215)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:486)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:450)
        at alluxio.AbstractClient.retryRPC(AbstractClient.java:439)
        at alluxio.client.file.RetryHandlingFileSystemMasterClient.listStatus(RetryHandlingFileSystemMasterClient.java:299)
        at alluxio.client.file.BaseFileSystem.lambda$listStatus$10(BaseFileSystem.java:333)
        at alluxio.client.file.BaseFileSystem.rpc(BaseFileSystem.java:699)
        ... 32 more
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission denied: user=trino, access=r--, path=/hive/warehouse/test.db/test1/pt_dt=2024-11-02: failed at pt_dt=2024-11-02, inode owner=hive, inode group=hive, inode mode=rwxrwx--x
        at io.grpc.Status.asRuntimeException(Status.java:532)
        at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:631)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
        at alluxio.client.file.RetryHandlingFileSystemMasterClient.lambda$listStatus$19(RetryHandlingFileSystemMasterClient.java:304)
        at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:484)
        ... 37 more


but In trino 429 is ok?what's wrong?

**Comment by raunaqmorarka** [comment]
@JiamingMai @apc999 PTAL at above

**Comment by luhea** [comment]
> [@JiamingMai](https://github.com/JiamingMai) [@apc999](https://github.com/apc999) PTAL at above

config  alluxio.security.login.username=root in alluxio-site.properties    not error,but  many log like ：


2024-11-12T18:16:35.885537013+08:00 2024-11-12T10:16:35.885Z	WARN	hive-datalake-31	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.3)
2024-11-12T18:16:35.906401864+08:00 2024-11-12T10:16:35.906Z	WARN	hive-datalake-8	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.3)
2024-11-12T10:16:35.988Z	WARN	hive-datalake-58	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.3)
2024-11-12T18:16:36.009677112+08:00 2024-11-12T10:16:36.009Z	WARN	hive-datalake-50	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.3)
2024-11-12T10:16:36.030Z	WARN	hive-datalake-48	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.3)
2024-11-12T10:16:36.030Z	WARN	hive-datalake-61	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.3)
2024-11-12T10:16:36.051Z	WARN	hive-datalake-6	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.3)
2024-11-12T18:16:36.052048889+08:00 2024-11-12T10:16:36.051Z	WARN	hive-datalake-37	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.3)
2024-11-12T10:16:36.154Z	WARN	hive-datalake-29	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.3)
2024-11-12T10:16:36.216Z	WARN	hive-datalake-35	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.3)
2024-11-12T18:16:36.236325766+08:00 2024-11-12T10:16:36.236Z	WARN	hive-datalake-13	alluxio.conf.Configuration	Alluxio CLIENT version (2.9.6) does not match Alluxio cluster version (2.9.3)


version is not compatible ？
