### ISSUE TITLE
IndexOutOfBoundsException with fault tolerance using RETRY-POLICY=TASK

### ISSUE THREAD

**Issue by arundh93** [trinodb/trino#23531]
Getting a `IndexOutOfBoundsException` when using fault tolerance mode of `TASK` 

Tried this is the latest `458` build. My setup is using a mount NFS as the exchange manager

logs

```
java.lang.IndexOutOfBoundsException: Range [353, 353 + 4) out of bounds for length 353
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:118)
	at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:397)
	at java.base/java.util.Objects.checkFromIndexSize(Objects.java:417)
	at io.airlift.slice.Slice.getInt(Slice.java:278)
	at io.trino.execution.buffer.PageDeserializer$ReadBuffer.readInt(PageDeserializer.java:606)
	at io.trino.execution.buffer.PageDeserializer$SerializedPageInput.decrypt(PageDeserializer.java:346)
	at io.trino.execution.buffer.PageDeserializer$SerializedPageInput.ensureReadable(PageDeserializer.java:332)
	at io.trino.execution.buffer.PageDeserializer$SerializedPageInput.readBytes(PageDeserializer.java:235)
	at io.airlift.slice.SliceInput.readBytes(SliceInput.java:185)
	at io.trino.metadata.InternalBlockEncodingSerde.readLengthPrefixedString(InternalBlockEncodingSerde.java:117)
	at io.trino.metadata.InternalBlockEncodingSerde.readBlock(InternalBlockEncodingSerde.java:56)
	at io.trino.block.BlockSerdeUtil.readBlock(BlockSerdeUtil.java:43)
	at io.trino.execution.buffer.PagesSerdeUtil.readRawPage(PagesSerdeUtil.java:77)
	at io.trino.execution.buffer.PageDeserializer.deserialize(PageDeserializer.java:82)
	at io.trino.operator.ExchangeOperator.getOutput(ExchangeOperator.java:241)
	at io.trino.operator.Driver.processInternal(Driver.java:403)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:306)
	at io.trino.operator.Driver.tryWithLock(Driver.java:709)
	at io.trino.operator.Driver.process(Driver.java:298)
	at io.trino.operator.Driver.processForDuration(Driver.java:269)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:890)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:77)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:201)
	at io.trino.$gen.Trino_458____20240923_135058_2.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:202)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:172)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:159)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
	Suppressed: java.lang.RuntimeException: Task 20240923_135607_00011_dhq8q.0.0.0 failed
		at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.lambda$checkComplete$4(EventDrivenFaultTolerantQueryScheduler.java:1040)
		at java.base/java.util.ArrayDeque.forEach(ArrayDeque.java:887)
		at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.checkComplete(EventDrivenFaultTolerantQueryScheduler.java:1040)
		at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.schedule(EventDrivenFaultTolerantQueryScheduler.java:1014)
		at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.run(EventDrivenFaultTolerantQueryScheduler.java:843)
		at io.trino.$gen.Trino_458____20240923_135058_2.run(Unknown Source)
```

**Comment by victorouttes** [comment]
Hey, @arundh93, how did you solve that?

**Comment by aikuyun** [comment]
+1

**Comment by aikuyun** [comment]
> Hey, @arundh93, how did you solve that?

hey，did you solve that?

**Comment by arundh93** [comment]
No I was not able to solve this, reopening this issue

**Comment by therealslimjp** [comment]
we are experiencing a similar error message using a s3bucket as exchange manager location

**Comment by livelace** [comment]
479 + alluxio fte + TASK retry policy = same
