### ISSUE TITLE
Flaky TestBigQueryAvroConnectorTest.testBigQueryMaterializedView

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#23582]
https://github.com/trinodb/trino/actions/runs/11050681149/job/30699095049
```
2024-09-26T05:11:40.959-0600	INFO	main	io.trino.testing.containers.junit.ReportLeakedContainers	DockerClientFactory not initialized, so there should be no leaked containers, skipping the check
java.lang.IllegalStateException: No valid spans, queries were executing concurrently
	at com.google.common.base.Preconditions.checkState(Preconditions.java:513)
	at io.trino.testing.DistributedQueryRunner.getSpans(DistributedQueryRunner.java:406)
	at io.trino.plugin.bigquery.BaseBigQueryConnectorTest.assertStorageApiInvocations(BaseBigQueryConnectorTest.java:706)
	at io.trino.plugin.bigquery.BaseBigQueryConnectorTest.lambda$testBigQueryMaterializedView$24(BaseBigQueryConnectorTest.java:682)
	at io.trino.testing.AbstractTestQueryFramework.executeExclusively(AbstractTestQueryFramework.java:601)
	at io.trino.plugin.bigquery.BaseBigQueryConnectorTest.testBigQueryMaterializedView(BaseBigQueryConnectorTest.java:681)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1499)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2272)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:495)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:662)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/11616409808/job/32349377312

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/12060069850/job/33629859936
