### ISSUE TITLE
Flaky test `TestAlluxioFileSystem` and `TestAlluxioFileSystemExchangeManager`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#23596]
https://github.com/trinodb/trino/actions/runs/11073808274/job/30771180097
```
Error:  io.trino.filesystem.alluxio.TestAlluxioFileSystem -- Time elapsed: 90.72 s <<< ERROR!
java.util.concurrent.ExecutionException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image alluxio/alluxio:2.9.5
	at java.base/java.util.concurrent.CompletableFuture.wrapInExecutionException(CompletableFuture.java:345)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:440)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2117)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:327)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.start(TestcontainersExtension.java:276)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.access$200(TestcontainersExtension.java:263)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$null$4(TestcontainersExtension.java:83)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$startContainers$5(TestcontainersExtension.java:83)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.startContainers(TestcontainersExtension.java:83)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.beforeAll(TestcontainersExtension.java:57)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image alluxio/alluxio:2.9.5
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:831)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:526)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:344)
	... 6 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:563)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:354)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 7 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Primary started*
'
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:500)
	... 9 more
```

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/11081935647/job/30794284771?pr=23419

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/11081955893/job/30794333467?pr=23598

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/11096912427/job/30827307239

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/11100241591/job/30835722630

**Comment by ebyhr** [comment]
@jja725 Could you run stress tests locally and send a PR? This test is very flaky. I hope you will fix it soon.

**Comment by ebyhr** [comment]
@jja725 Reopen as it happened again. Please take another look.
```
Error:  io.trino.filesystem.alluxio.TestAlluxioFileSystem -- Time elapsed: 207.6 s <<< ERROR!
java.util.concurrent.ExecutionException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image alluxio/alluxio:2.9.5
	at java.base/java.util.concurrent.CompletableFuture.wrapInExecutionException(CompletableFuture.java:345)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:440)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2117)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:327)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.start(TestcontainersExtension.java:276)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.access$200(TestcontainersExtension.java:263)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$null$4(TestcontainersExtension.java:83)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$startContainers$5(TestcontainersExtension.java:83)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.startContainers(TestcontainersExtension.java:83)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.beforeAll(TestcontainersExtension.java:57)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image alluxio/alluxio:2.9.5
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:831)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:526)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:344)
	... 6 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:563)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:354)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 7 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Primary started*
'
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:500)
	... 9 more
``` 
https://github.com/trinodb/trino/actions/runs/11157959013/job/31013228602

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/11204592382/job/31143156194?pr=23690

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/11208961823/job/31153442299

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/11317299889/job/31470574492

**Comment by jja725** [comment]
@JiamingMai do you mind take a look since I would not be available recently? Probably add more timeout like previous fix

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/11359681622/job/31596149268

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/11513454496/job/32050184041

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/11587724367/job/32260330705

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/11713967184/job/32627752858
@JiamingMai @jja725

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/12060069850/job/33629825950
@JiamingMai @jja725

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/12113366621/job/33768204967?pr=24329
@JiamingMai @jja725

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/12209038546/job/34063219357
@JiamingMai @jja725

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/12215345028/job/34077188235
@JiamingMai @jja725

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/13284125497/job/37088935092?pr=24994

**Comment by ebyhr** [comment]
@JiamingMai @jja725 What's the current status of this issue?

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/14029004934/job/39272670831?pr=25395

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/commit/ceb0a8fd76ce5f45de5a1b12a8dbe63c4a1f69b4#annotation_33138524987

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/14095776999/job/39482798585?pr=18390

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/15012524722/job/42183807546

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/15037400988/job/42261621194

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/17394539973/job/49373944915

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/17413234423/job/49435430032
https://github.com/trinodb/trino/actions/runs/17410769170/job/49427218248

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/17842514026/job/50735277661

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/18470171202/job/52621935385?pr=26918

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/18710000184/job/53355940795?pr=27014

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/18707665256/job/53348732356?pr=27040

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/18709186173/job/53353530976

```
Error:  io.trino.filesystem.alluxio.TestAlluxioFileSystem -- Time elapsed: 326.0 s <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image alluxio/alluxio:2.9.5
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:346)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
	at io.trino.filesystem.alluxio.TestAlluxioFileSystem.setup(TestAlluxioFileSystem.java:61)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:331)
	... 2 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:551)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:341)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 3 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Primary started*
'
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:904)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:487)
	... 5 more
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/18711658739/job/53361332332?pr=27036

```
Error:  io.trino.plugin.exchange.filesystem.alluxio.TestAlluxioFileSystemExchangeManager -- Time elapsed: 210.3 s <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image alluxio/alluxio:2.9.5
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:346)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
	at io.trino.plugin.exchange.filesystem.containers.AlluxioStorage.createAlluxioMasterContainer(AlluxioStorage.java:59)
	at io.trino.plugin.exchange.filesystem.containers.AlluxioStorage.start(AlluxioStorage.java:36)
	at io.trino.plugin.exchange.filesystem.alluxio.TestAlluxioFileSystemExchangeManager.createExchangeManager(TestAlluxioFileSystemExchangeManager.java:34)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:331)
	... 4 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:551)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:341)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 5 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Primary started*
'
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:904)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:487)
	... 7 more
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/18712443643/job/53363916476?pr=27036

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/18715668691/job/53374465856?pr=27036

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/18771350606/job/53556409809?pr=27070

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/19035690732/job/54359385173

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/19063108033/job/54447196227

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/19247362691/job/55024625898

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/19323136810/job/55268430657

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/21610542388/job/62278149594

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/23871751788/job/69605961070?pr=28966

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/actions/runs/24555023659/job/71789433310
