### ISSUE TITLE
Exchange partition output count on FTE

### ISSUE THREAD

**Issue by florianMalbranque** [trinodb/trino#23756]
I am running:

Trino 460 in fault tolerant mode using GCS bucket as spooling

After setting:
```
fault-tolerant-execution-max-partition-count=200
```
in properties, and running a query that requires multiple partitions, I am getting this stacktrace: 
```
io.trino.spi.TrinoException: Max number of output partitions exceeded for exchange 'external-exchange-3'. Allowed: 50. Requested: 200.
	at io.trino.plugin.exchange.filesystem.FileSystemExchangeManager.createExchange(FileSystemExchangeManager.java:98)
	at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.createStageExecution(EventDrivenFaultTolerantQueryScheduler.java:1463)
	at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.updateStageExecutions(EventDrivenFaultTolerantQueryScheduler.java:1170)
	at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.schedule(EventDrivenFaultTolerantQueryScheduler.java:1018)
	at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.run(EventDrivenFaultTolerantQueryScheduler.java:838)
	at io.trino.$gen.Trino_460____20241011_130449_2.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)

```

I don't see any parameters to tune max exchange partition output count in the documentation

**Comment by raunaqmorarka** [comment]
cc: @losipiuk

**Comment by losipiuk** [comment]
To bump the value above 50 you need to also change `exchange.max-output-partition-count` to higher value in `exchange.properties`.
The limit of 50 put by filesystem exchange is on purpose.  Number of files created for hash based exchanges is ~proportional to number_of_tasks*number_of_partitions.
And if we have to many of those we will reach scalability limits.

**Comment by losipiuk** [comment]
This should solve your problem. Please reach out on slack if it does not.
