### ISSUE TITLE
PluginClassLoader error

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#23798]
I faced below error message when query some mysql tables:

Query failed (#20241016_075201_00111_dkz7f): class io.trino.plugin.jdbc.JdbcSplit cannot be cast to class io.trino.plugin.jdbc.JdbcSplit (io.trino.plugin.jdbc.JdbcSplit is in unnamed module of loader io.trino.server.PluginClassLoader @6bc45472; io.trino.plugin.jdbc.JdbcSplit is in unnamed module of loader io.trino.server.PluginClassLoader @5135b8a3)

trino:397
mysql:8.0.21

**Comment by ebyhr** [comment]
@njalan Version 397 is too old. Can you reproduce the issue with the latest version? Also, please share the steps to reproduce, and the full stacktrace.

**Comment by phzietsman** [comment]
I'm getting the same issue.

```
SQL Error [65536]: Query failed (#20250128_164747_00012_qwvra): class io.trino.plugin.jdbc.JdbcSplit cannot be cast to class io.trino.plugin.jdbc.JdbcSplit (io.trino.plugin.jdbc.JdbcSplit is in unnamed module of loader io.trino.server.PluginClassLoader @3e11cc3a; io.trino.plugin.jdbc.JdbcSplit is in unnamed module of loader io.trino.server.PluginClassLoader @64d347b0)
```

Trino Version: 462
PostgreSQL version: 16.4


```
  prd_hive_ms: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://server.postgres.database.azure.com:5432/trino_logging
    connection-user=user_name
    connection-password=password
```


## Trace
```
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [65536]: Query failed (#20250128_164747_00012_qwvra): class io.trino.plugin.jdbc.JdbcSplit cannot be cast to class io.trino.plugin.jdbc.JdbcSplit (io.trino.plugin.jdbc.JdbcSplit is in unnamed module of loader io.trino.server.PluginClassLoader @3e11cc3a; io.trino.plugin.jdbc.JdbcSplit is in unnamed module of loader io.trino.server.PluginClassLoader @64d347b0)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.nextRow(JDBCResultSetImpl.java:183)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:194)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:191)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5148)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Query failed (#20250128_164747_00012_qwvra): class io.trino.plugin.jdbc.JdbcSplit cannot be cast to class io.trino.plugin.jdbc.JdbcSplit (io.trino.plugin.jdbc.JdbcSplit is in unnamed module of loader io.trino.server.PluginClassLoader @3e11cc3a; io.trino.plugin.jdbc.JdbcSplit is in unnamed module of loader io.trino.server.PluginClassLoader @64d347b0)
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:294)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:254)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Unknown Source)
	at io.trino.jdbc.TrinoResultSet$AsyncIterator.lambda$new$1(TrinoResultSet.java:179)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class io.trino.plugin.jdbc.JdbcSplit cannot be cast to class io.trino.plugin.jdbc.JdbcSplit (io.trino.plugin.jdbc.JdbcSplit is in unnamed module of loader io.trino.server.PluginClassLoader @3e11cc3a; io.trino.plugin.jdbc.JdbcSplit is in unnamed module of loader io.trino.server.PluginClassLoader @64d347b0)
	at io.trino.plugin.jdbc.JdbcRecordSetProvider.getRecordSet(JdbcRecordSetProvider.java:58)
	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
	at io.trino.split.PageSourceManager$PageSourceProviderInstance.createPageSource(PageSourceManager.java:79)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:265)
	at io.trino.operator.Driver.processInternal(Driver.java:403)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:306)
	at io.trino.operator.Driver.tryWithLock(Driver.java:709)
	at io.trino.operator.Driver.process(Driver.java:298)
	at io.trino.operator.Driver.processForDuration(Driver.java:269)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:890)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:77)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:201)
	at io.trino.$gen.Trino_462____20250121_092408_2.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:202)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:172)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:159)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```
