### ISSUE TITLE
Too large results exception when pulling data from Hudi residing on GCS with BigLake metastore

### ISSUE THREAD

**Issue by bindiego** [trinodb/trino#23933]
Too large results exception when pulling data from Hudi residing on GCS with BigLake metastore. Same operation against hive-metastore works. Seems like not a resource exhaustion issue. Would you please help to narrow down the problem? 

Below are the logs output.

```
com.google.cloud.bigquery.BigQueryException: Response too large to return. Consider specifying a destination table in your job configuration. For more details, see https://cloud.google.com/bigquery/troubleshooting-errors
        at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)
        at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:694)
        at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1410)
        at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1405)
        at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
        at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)
        at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)
        at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1404)
        at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1388)
        at com.google.cloud.bigquery.Job$1.call(Job.java:338)
        at com.google.cloud.bigquery.Job$1.call(Job.java:335)
        at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
        at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)
        at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)
        at com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:334)
        at com.google.cloud.bigquery.Job.getQueryResults(Job.java:295)
        at com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1303)
        at io.trino.plugin.bigquery.BigQueryClient.query(BigQueryClient.java:236)
        at io.trino.plugin.bigquery.BigQueryQueryPageSource.<init>(BigQueryQueryPageSource.java:101)
        at io.trino.plugin.bigquery.BigQueryPageSourceProvider.createQueryPageSource(BigQueryPageSourceProvider.java:108)
        at io.trino.plugin.bigquery.BigQueryPageSourceProvider.createPageSource(BigQueryPageSourceProvider.java:90)
        at io.trino.plugin.bigquery.BigQueryPageSourceProvider.createPageSource(BigQueryPageSourceProvider.java:79)
        at io.trino.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:43)
        at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:62)
        at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:279)
        at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:207)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
        at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
        at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$3(WorkProcessorUtils.java:219)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
        at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
        at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$4(WorkProcessorUtils.java:234)
        at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
        at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:150)
        at io.trino.operator.Driver.processInternal(Driver.java:411)
        at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
        at io.trino.operator.Driver.tryWithLock(Driver.java:706)
        at io.trino.operator.Driver.process(Driver.java:306)
        at io.trino.operator.Driver.processForDuration(Driver.java:277)
        at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:741)
        at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
        at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:546)
        at io.trino.$gen.Trino_402_200_gdd4a67c____20241021_205158_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by ebyhr** [comment]
We don't offer BigLake metastore support. Could you please share your catalog properties file? You can redact confidential info.

**Comment by bindiego** [comment]
It's actually very simple like what has been described here: https://trino.io/docs/current/connector/bigquery.html#configuration

bellow is the actually configurations,

```
connector.name=bigquery
bigquery.project-id=<project-id>
bigquery.parent-project-id=<project-id>
```

moreover, it works for most of the queries. Only having this issue for a query may potentially have around 10million records. Applying `limit` doesn't help which is reasonable if the trino computing node need all raw data for a particular job. I could be wrong since I am not very familiar with Trino, hope didn't mislead anything.

**Comment by ebyhr** [comment]
Please share the table definition on BigQuery (not Trino), SELECT statement and EXPLAIN result. I knew the connector can't handle large results when REST API is internally used (#17069), but I want to understand why Storage API isn't used in your case.
