### ISSUE TITLE
mysql view with substring will return View xxx  is stale or in invalid state

### ISSUE THREAD

**Issue by boson234** [trinodb/trino#23972]
trino version 399
mysql 5.x, 8.x 

mysql> create table substr_test(date varchar(20),id int);
Query OK, 0 rows affected (0.03 sec)

mysql> create view view_substr as select substring(date ,1, 7) mon  from substr_test;
Query OK, 0 rows affected (0.01 sec)

trino:hetudb> select * from view_substr;
Query 20241030_084704_00035_5q5vj failed: line 1:15: View 'mysql_auto.hetudb.view_substr' is stale or in invalid state: column [mon] of type varchar(20) projected from query view at position 0 cannot be coerced to column [mon] of type varchar(7) stored in view definition
io.trino.spi.TrinoException: line 1:15: View 'mysql_auto.hetudb.view_substr' is stale or in invalid state: column [mon] of type varchar(20) projected from query view at position 0 cannot be coerced to column [mon] of type varchar(7) stored in view definition
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:54)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:49)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.lambda$createScopeForView$57(StatementAnalyzer.java:2646)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.createScopeForView(StatementAnalyzer.java:2646)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.createScopeForView(StatementAnalyzer.java:2587)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2358)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:503)
	at io.trino.sql.tree.Table.accept(Table.java:123)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:68)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:520)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:4650)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:3079)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:503)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:166)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:68)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:520)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:528)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1694)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:503)
	at io.trino.sql.tree.Query.accept(Query.java:113)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:68)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:520)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:482)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:95)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:80)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:274)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:211)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:866)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:149)
	at io.trino.$gen.Trino_399____20241029_121114_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
select * from view_substr

**Comment by ebyhr** [comment]
I can't reproduce the issue on master branch. 

Version 399 is too old. Please feel free to reopen if you can reproduce the issue on the latest version.
