### ISSUE TITLE
Connection leaks on native Azure filesystem

### ISSUE THREAD

**Issue by cccs-nik** [trinodb/trino#24116]
Since switching to the new Azure native FS in our environments we've been seeing a lot of connection leaks and java.lang.IllegalStateException: Unbalanced enter/exit exceptions. The native FS seemed to cause stability issues in earlier versions of Trino (like in Trino 452) so we had switched off back to legacy but in version 460 where it's required it seems ok. I'm not sure if our past stability issues in other versions were unrelated to the leaks or they're now mitigated due to other changes.

We get the following exceptions when running most queries:
```java
ERROR	SplitRunner-20241025_163311_00004_872jn.1.0.0-4-283	reactor.core.publisher.Operators	Operator called default onErrorDropped
java.lang.IllegalStateException: Unbalanced enter/exit
	at okio.AsyncTimeout.enter(AsyncTimeout.kt:58)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:384)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:194)
	at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:339)
	at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:376)
	at okhttp3.internal.Util.skipAll(Util.kt:344)
	at okhttp3.internal.Util.discard(Util.kt:365)
	at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.close(Http1ExchangeCodec.kt:395)
	at okio.ForwardingSource.close(ForwardingSource.kt:32)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.close(Exchange.kt:314)
	at okio.RealBufferedSource.close(RealBufferedSource.kt:486)
	at okhttp3.internal.Util.closeQuietly(Util.kt:495)
	at okhttp3.ResponseBody.close(ResponseBody.kt:192)
	at com.azure.core.http.okhttp.implementation.OkHttpAsyncResponse.close(OkHttpAsyncResponse.java:119)
	at com.azure.core.http.okhttp.implementation.OkHttpAsyncResponse.lambda$getBody$1(OkHttpAsyncResponse.java:61)
	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.cleanup(FluxUsing.java:334)
	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.cancel(FluxUsing.java:328)
	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.cancel(FluxUsing.java:326)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.cancel(FluxMapFuseable.java:176)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2425)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2393)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2205)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.cancel(Operators.java:2086)
	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.cancel(FluxDefaultIfEmpty.java:103)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.cancel(Operators.java:2086)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.cancel(MonoCollect.java:150)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.cancel(FluxMapFuseable.java:176)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.cancel(FluxMapFuseable.java:176)
	at reactor.core.publisher.Operators.terminate(Operators.java:1328)
	at reactor.core.publisher.MonoZip$ZipInner.cancel(MonoZip.java:548)
	at reactor.core.publisher.MonoZip$ZipCoordinator.cancel(MonoZip.java:313)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:207)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:199)
	at reactor.core.publisher.BlockingSingleSubscriber.dispose(BlockingSingleSubscriber.java:74)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:94)
	at reactor.core.publisher.Mono.block(Mono.java:1779)
	at com.azure.storage.blob.specialized.BlobClientBase.openInputStream(BlobClientBase.java:394)
	at com.azure.storage.blob.specialized.BlobClientBase.openInputStream(BlobClientBase.java:324)
	at io.trino.filesystem.azure.AzureInput.readFully(AzureInput.java:61)
	at io.trino.filesystem.tracing.TracingInput.lambda$readFully$0(TracingInput.java:53)
	at io.trino.filesystem.tracing.Tracing.lambda$withTracing$1(Tracing.java:38)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:37)
	at io.trino.filesystem.tracing.TracingInput.readFully(TracingInput.java:53)
	at io.trino.plugin.hive.parquet.TrinoParquetDataSource.readInternal(TrinoParquetDataSource.java:64)
	at io.trino.parquet.AbstractParquetDataSource.readFully(AbstractParquetDataSource.java:122)
	at io.trino.parquet.AbstractParquetDataSource$ReferenceCountedReader.read(AbstractParquetDataSource.java:332)
	at io.trino.parquet.ChunkReader.readUnchecked(ChunkReader.java:31)
	at io.trino.parquet.reader.ChunkedInputStream.readNextChunk(ChunkedInputStream.java:149)
	at io.trino.parquet.reader.ChunkedInputStream.read(ChunkedInputStream.java:93)
	at shaded.parquet.org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:170)
	at shaded.parquet.org.apache.thrift.transport.TTransport.readAll(TTransport.java:100)
	at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.readByte(TCompactProtocol.java:632)
	at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.readFieldBegin(TCompactProtocol.java:532)
	at org.apache.parquet.format.InterningProtocol.readFieldBegin(InterningProtocol.java:188)
	at org.apache.parquet.format.PageHeader$PageHeaderStandardScheme.read(PageHeader.java:1003)
	at org.apache.parquet.format.PageHeader$PageHeaderStandardScheme.read(PageHeader.java:995)
	at org.apache.parquet.format.PageHeader.read(PageHeader.java:870)
	at org.apache.parquet.format.Util.read(Util.java:390)
	at org.apache.parquet.format.Util.readPageHeader(Util.java:133)
	at org.apache.parquet.format.Util.readPageHeader(Util.java:128)
	at io.trino.parquet.reader.ParquetColumnChunkIterator.readPageHeader(ParquetColumnChunkIterator.java:116)
	at io.trino.parquet.reader.ParquetColumnChunkIterator.next(ParquetColumnChunkIterator.java:83)
	at io.trino.parquet.reader.ParquetColumnChunkIterator.next(ParquetColumnChunkIterator.java:42)
	at com.google.common.collect.Iterators$PeekingImpl.peek(Iterators.java:1219)
	at io.trino.parquet.reader.PageReader.readDictionaryPage(PageReader.java:160)
	at io.trino.parquet.reader.AbstractColumnReader.setPageReader(AbstractColumnReader.java:79)
	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:460)
	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:543)
	at io.trino.parquet.reader.ParquetReader.readStruct(ParquetReader.java:373)
	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:534)
	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:526)
	at io.trino.parquet.reader.ParquetReader.lambda$nextPage$3(ParquetReader.java:252)
	at io.trino.parquet.reader.ParquetBlockFactory$ParquetBlockLoader.load(ParquetBlockFactory.java:72)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:312)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:291)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:186)
	at io.trino.spi.Page.getLoadedPage(Page.java:244)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:271)
	at io.trino.operator.Driver.processInternal(Driver.java:403)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:306)
	at io.trino.operator.Driver.tryWithLock(Driver.java:709)
	at io.trino.operator.Driver.process(Driver.java:298)
	at io.trino.operator.Driver.processForDuration(Driver.java:269)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:890)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:77)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:201)
	at io.trino.$gen.Trino_460_220_g1e499ed____20241025_161104_2.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:202)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:172)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:159)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

Followed by connection leak warnings:
```java
WARN OkHttp ConnectionPool okhttp3.OkHttpClient A connection to https://<domain>.blob.core.windows.net/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

And I believe we get the following stack traces as a result of turning logging up:
```java
WARN OkHttp ConnectionPool okhttp3.OkHttpClient	A connection to https://<domain>.blob.core.windows.net/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.kt:145)
	at okhttp3.internal.connection.RealCall.callStart(RealCall.kt:170)
	at okhttp3.internal.connection.RealCall.enqueue(RealCall.kt:163)
	at com.azure.core.http.okhttp.OkHttpAsyncHttpClient.lambda$send$2(OkHttpAsyncHttpClient.java:125)
	at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:171)
	at reactor.core.publisher.MonoCallable$MonoCallableSubscription.request(MonoCallable.java:156)
	at reactor.core.publisher.LambdaMonoSubscriber.onSubscribe(LambdaMonoSubscriber.java:121)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:48)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4576)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4642)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4542)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4478)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4450)
	at com.azure.core.http.okhttp.OkHttpAsyncHttpClient.lambda$send$3(OkHttpAsyncHttpClient.java:122)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.onRequest(MonoCreate.java:225)
	at com.azure.core.http.okhttp.OkHttpAsyncHttpClient.lambda$send$4(OkHttpAsyncHttpClient.java:108)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:241)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:204)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:155)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRepeatWhen$RepeatWhenMainSubscriber.onNext(FluxRepeatWhen.java:143)
	at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.onNext(MonoUsing.java:231)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
	at reactor.core.publisher.MonoMaterialize$MaterializeSubscriber.drain(MonoMaterialize.java:133)
	at reactor.core.publisher.MonoMaterialize$MaterializeSubscriber.onComplete(MonoMaterialize.java:127)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
	at reactor.core.publisher.MonoUsing.subscribe(MonoUsing.java:102)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.MonoFromFluxOperator.subscribe(MonoFromFluxOperator.java:83)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4576)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:265)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4576)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:205)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:63)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4576)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:205)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4560)
	at reactor.core.publisher.Mono.block(Mono.java:1778)
	at com.azure.storage.blob.specialized.BlobClientBase.openInputStream(BlobClientBase.java:394)
	at com.azure.storage.blob.specialized.BlobClientBase.openInputStream(BlobClientBase.java:324)
	at io.trino.filesystem.azure.AzureInput.readFully(AzureInput.java:61)
	at io.trino.filesystem.tracing.TracingInput.lambda$readFully$0(TracingInput.java:53)
	at io.trino.filesystem.tracing.Tracing.lambda$withTracing$1(Tracing.java:38)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:37)
	at io.trino.filesystem.tracing.TracingInput.readFully(TracingInput.java:53)
	at io.trino.plugin.hive.parquet.TrinoParquetDataSource.readInternal(TrinoParquetDataSource.java:64)
	at io.trino.parquet.AbstractParquetDataSource.readFully(AbstractParquetDataSource.java:122)
	at io.trino.parquet.AbstractParquetDataSource$ReferenceCountedReader.read(AbstractParquetDataSource.java:332)
	at io.trino.parquet.ChunkReader.readUnchecked(ChunkReader.java:31)
	at io.trino.parquet.reader.ChunkedInputStream.readNextChunk(ChunkedInputStream.java:149)
	at io.trino.parquet.reader.ChunkedInputStream.read(ChunkedInputStream.java:93)
	at shaded.parquet.org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:170)
	at shaded.parquet.org.apache.thrift.transport.TTransport.readAll(TTransport.java:100)
	at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.readByte(TCompactProtocol.java:632)
	at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.readFieldBegin(TCompactProtocol.java:532)
	at org.apache.parquet.format.InterningProtocol.readFieldBegin(InterningProtocol.java:188)
	at org.apache.parquet.format.PageHeader$PageHeaderStandardScheme.read(PageHeader.java:1003)
	at org.apache.parquet.format.PageHeader$PageHeaderStandardScheme.read(PageHeader.java:995)
	at org.apache.parquet.format.PageHeader.read(PageHeader.java:870)
	at org.apache.parquet.format.Util.read(Util.java:390)
	at org.apache.parquet.format.Util.readPageHeader(Util.java:133)
	at org.apache.parquet.format.Util.readPageHeader(Util.java:128)
	at io.trino.parquet.reader.ParquetColumnChunkIterator.readPageHeader(ParquetColumnChunkIterator.java:116)
	at io.trino.parquet.reader.ParquetColumnChunkIterator.next(ParquetColumnChunkIterator.java:83)
	at io.trino.parquet.reader.ParquetColumnChunkIterator.next(ParquetColumnChunkIterator.java:42)
	at com.google.common.collect.Iterators$PeekingImpl.peek(Iterators.java:1219)
	at io.trino.parquet.reader.PageReader.readDictionaryPage(PageReader.java:160)
	at io.trino.parquet.reader.AbstractColumnReader.setPageReader(AbstractColumnReader.java:79)
	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:460)
	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:543)
	at io.trino.parquet.reader.ParquetReader.readStruct(ParquetReader.java:373)
	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:534)
	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:526)
	at io.trino.parquet.reader.ParquetReader.lambda$nextPage$3(ParquetReader.java:252)
	at io.trino.parquet.reader.ParquetBlockFactory$ParquetBlockLoader.load(ParquetBlockFactory.java:72)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:312)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:291)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:186)
	at io.trino.spi.Page.getLoadedPage(Page.java:244)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:271)
	at io.trino.operator.Driver.processInternal(Driver.java:403)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:306)
	at io.trino.operator.Driver.tryWithLock(Driver.java:709)
	at io.trino.operator.Driver.process(Driver.java:298)
	at io.trino.operator.Driver.processForDuration(Driver.java:269)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:890)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:77)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:201)
	at io.trino.$gen.Trino_460_220_g1e499ed____20241025_161104_2.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:202)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:172)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:159)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

I'm not able to reproduce the issue 100% of the time but it's nonetheless very easy to reproduce on our end. Querying any catalog using the native Azure FS for a small amount of data (like 1000+ rows) will almost certainly throw the Unbalanced enter/exit exceptions later followed by connection leak warnings. For example, since switching to trino 460 on October 16th in one of our clusters, we've had roughly 430k queries, 157k unbalanced enter/exit exceptions and 107k connection leak warnings in our logs.

I tried investigating the issue on my own but it's not really clear to me what's happening or where the issue is between Trino/Azure SDK/OkHttp. Different versions of Trino and Azure SDK all exhibit the same problem in my experience.

**Comment by nineinchnick** [comment]
@cccs-nik you're reporting some issue that's not manifesting itself anymore since 460? Is it worth investigating? It might have been an issue in the Azure SDK, and we're constantly upgrading it to the latest version.

**Comment by cccs-nik** [comment]
@nineinchnick Sorry for the confusion, what I meant was that we are not crashing as a result of using the native Azure FS anymore in 460, but the Unbalanced enter/exits and connection leak warnings are most definitely still happening.

**Comment by findinpath** [comment]
Cc @anusudarsan

**Comment by gustavoatt** [comment]
we are also seeing this error here. Wondering if you have a workaround or just reverting back to the legacy Azure filesystem?

For reference we are on version 463 and are still seeing the same issue

**Comment by wendigo** [comment]
Does it make cluster unstable or is it just annoying that these are logged?

**Comment by gustavoatt** [comment]
currently it makes the cluster unstable, around 40% of simple queries like the one below fail.

```sql
select col_a, col_b
from table
limit 5
```

I'm trying to switch back to the legacy filesystem to see if we have more luck. For context this is using the Delta Lake connector and our config for the azure file system is:

```
fs.native-azure.enabled=true
azure.auth-type=DEFAULT
azure.max-http-requests=100
```

**Comment by wendigo** [comment]
@gustavoatt can you test Trino build with following change: https://github.com/trinodb/trino/pull/24773?

**Comment by gustavoatt** [comment]
@wendigo that does seem to have fixed the issue in one query that I could consistently get to fail ~40-50% of the time. Appreciate you looking at this!

**Comment by wendigo** [comment]
@gustavoatt Yeah I was worried that okhttp is to blame

**Comment by wendigo** [comment]
@gustavoatt Yeah I was worried that okhttp is to blame

**Comment by gustavoatt** [comment]
yeah, if okhttp was not maintained then it makes sense to switch to netty. I will deploy the change to one of our clusters and reach out if I see any issues but I don't expect it to. Specially since the native filesystem seems to be slightly faster than the Hadoop one at least for the queries that I was testing on

**Comment by cccs-nik** [comment]
Thanks for the fix @wendigo! I couldn't test right away because the conditions which made the connection leaks happen for us changed and we were getting less of them. I updated our prod deployment with the fix last week and it's been solid with 0 leaks since 👍
