### ISSUE TITLE
465 Trino PAGE_TRANSPORT_TIMEOUT every day after update from 458! All queries stuck.

### ISSUE THREAD

**Issue by Albel-Analyst** [trinodb/trino#24272]
After update from 458 to 465 trino in k8s
Every day +- at the same time when a critical mass of requests is being collected, I get a completely inoperable cluster!
All requests hang and fall on timeout with PAGE_TRANSPORT_ERROR
All requests are made in the iceberg connector with the rest catalog.
Only the restart of the workers and the coordinator helps

**Comment by Albel-Analyst** [comment]
```
io.trino.operator.PageTransportTimeoutException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://...:8080/v1/task/20241127_083138_01150_4am4x.0.0.0/results/0/0 - 7 failures, failure duration 61.35s, total failed request time 71.35s)
	at io.trino.operator.HttpPageBufferClient$1.onFailure(HttpPageBufferClient.java:505)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
[11:36](https://trinodb.slack.com/archives/CGB0QHWSW/p1732696561270339?thread_ts=1732692577.147859&cid=CGB0QHWSW)
```

Also I see many errors on workers like this
```
2024-11-27T08:29:11.449Z	ERROR	async-http-response-590	org.glassfish.jersey.server.ServerRuntime$Responder	Error while closing the output stream in order to commit response.
java.lang.IllegalStateException: Request/Response does not exist (likely recycled)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.getServletContextResponse(ServletChannel.java:283)
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.isResponseCommitted(ServletChannelState.java:360)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.isCommitted(ServletChannel.java:772)
	at org.eclipse.jetty.ee10.servlet.ServletApiResponse.isCommitted(ServletApiResponse.java:423)
	at org.eclipse.jetty.ee10.servlet.ServletApiResponse.setContentLengthLong(ServletApiResponse.java:348)
	at org.eclipse.jetty.ee10.servlet.ServletApiResponse.setContentLength(ServletApiResponse.java:339)
	at org.glassfish.jersey.servlet.internal.ResponseWriter.writeResponseStatusAndHeaders(ResponseWriter.java:122)
	at org.glassfish.jersey.server.ServerRuntime$Responder$1.getOutputStream(ServerRuntime.java:681)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:174)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:279)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:235)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:250)
	at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:568)
	at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:403)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:763)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:398)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:450)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:928)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:963)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:914)
	at io.airlift.jaxrs.AsyncResponseHandler$1.onSuccess(AsyncResponseHandler.java:99)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1137)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:79)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)

```2024-11-27T07:50:34.550Z	WARN	async-http-response-292	org.glassfish.jersey.server.ServerRuntime$Responder	Attempt to release request processing resources has failed for a request.
java.lang.IllegalStateException: s=HANDLING rs=ERRORING os=OPEN is=IDLE awp=false se=false i=false al=0
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.complete(ServletChannelState.java:817)
	at org.eclipse.jetty.ee10.servlet.AsyncContextState.complete(AsyncContextState.java:61)
	at org.glassfish.jersey.servlet.async.AsyncContextDelegateProviderImpl$ExtensionImpl.complete(AsyncContextDelegateProviderImpl.java:102)
	at org.glassfish.jersey.servlet.internal.ResponseWriter.commit(ResponseWriter.java:168)
	at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:404)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
	at org.glassfish.jersey.server.ServerRuntime$Responder.release(ServerRuntime.java:788)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:389)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:926)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:963)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:914)
	at io.airlift.jaxrs.AsyncResponseHandler$1.onSuccess(AsyncResponseHandler.java:99)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1137)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:79)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)```

**Comment by Albel-Analyst** [comment]
can it be related to this?
https://github.com/trinodb/trino/issues/24253

**Comment by sorcerer-git** [comment]
@Albel-Analyst encountered the same issue. It seems there is a problem with HTTP/2. Try disabling it, it should work.
`internal-communication.http2.enabled=false`

**Comment by raunaqmorarka** [comment]
cc: @wendigo

**Comment by wendigo** [comment]
@raunaqmorarka root cause is already identified and fixed in Jetty - I am now waiting for a release. nothing to do here.

**Comment by loustler** [comment]
@wendigo 
Sorry if I'm bothering you, I wonder what caused it, can I know the issue or PR of jetty?

**Comment by wendigo** [comment]
We suspect that the underlying issue is https://github.com/jetty/jetty.project/commit/f93c75f3de1081e4492a8845cd7c9fe7d48a1b81

There is a reproduction in the https://github.com/jetty/jetty.project/pull/12610 which simulates how the nodes communicate with each other, including cancellations of in-flight requests

**Comment by nikita-sheremet-java-developer** [comment]
@wendigo 

I also appologies if  I'm bothering you, but [12553](https://github.com/jetty/jetty.project/commit/f93c75f3de1081e4492a8845cd7c9fe7d48a1b81) looks like released in jetty [12.0.16](https://github.com/jetty/jetty.project/releases/tag/jetty-12.0.16) (just 4h ago).

So waiting for new release with fixed jetty

**Comment by wendigo** [comment]
@nikita-sheremet-java-developer correct. We will update as soon as we benchmark it with our code

**Comment by nikita-sheremet-java-developer** [comment]
Some queries leads to:

```
2024-12-10T06:18:07.774Z	WARN	async-http-response-1533	io.trino.server.IoExceptionSuppressingWriterInterceptor	Could not write to output: EofException(null)
```

Even when http2 is disabled. is it related to this jersey bug?

**Comment by ka-weihe** [comment]
Has this been fixed?

**Comment by wendigo** [comment]
We haven't observed any issues in the recent releases. Closing as fixed.
