### ISSUE TITLE
Flaky io.prestosql.plugin.hive.TestHive#testBucketedTableEvolution

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#2435]
```
2020-01-07T21:41:11.5422095Z [INFO] -------------------------------------------------------
2020-01-07T21:41:11.5422621Z [INFO]  T E S T S
2020-01-07T21:41:11.5423317Z [INFO] -------------------------------------------------------
2020-01-07T21:41:12.0713030Z [INFO] Running io.prestosql.plugin.hive.TestHive
2020-01-07T21:41:48.9462604Z 2020-01-07T15:41:48.937-0600 INFO Test io.prestosql.plugin.hive.TestHive::testBucketedTableEvolution took 31.02s
2020-01-07T21:42:44.8277238Z 2020-01-07T15:42:44.826-0600 WARNING Tests from io.prestosql.plugin.hive.TestHive took 1.50m
2020-01-07T21:42:45.0119208Z [ERROR] Tests run: 71, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 92.894 s <<< FAILURE! - in io.prestosql.plugin.hive.TestHive
2020-01-07T21:42:45.0127233Z [ERROR] testTransactionDeleteInsert(io.prestosql.plugin.hive.TestHive)  Time elapsed: 2.469 s  <<< FAILURE!
2020-01-07T21:42:45.0130270Z java.lang.NullPointerException
2020-01-07T21:42:45.0136194Z 	at io.prestosql.plugin.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:64)
2020-01-07T21:42:45.0142341Z 	at io.prestosql.plugin.hive.AbstractTestHive.listDirectory(AbstractTestHive.java:4526)
2020-01-07T21:42:45.0148174Z 	at io.prestosql.plugin.hive.AbstractTestHive.access$100(AbstractTestHive.java:275)
2020-01-07T21:42:45.0156030Z 	at io.prestosql.plugin.hive.AbstractTestHive$DirectoryRenameFailure.verifyAndCleanup(AbstractTestHive.java:4906)
2020-01-07T21:42:45.0162938Z 	at io.prestosql.plugin.hive.AbstractTestHive.doTestTransactionDeleteInsert(AbstractTestHive.java:4703)
2020-01-07T21:42:45.0169962Z 	at io.prestosql.plugin.hive.AbstractTestHive.doTestTransactionDeleteInsert(AbstractTestHive.java:4615)
2020-01-07T21:42:45.0176828Z 	at io.prestosql.plugin.hive.AbstractTestHive.testTransactionDeleteInsert(AbstractTestHive.java:4538)
2020-01-07T21:42:45.0181700Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-01-07T21:42:45.0187304Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-01-07T21:42:45.0193383Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-01-07T21:42:45.0197904Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-01-07T21:42:45.0204171Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-01-07T21:42:45.0209338Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-01-07T21:42:45.0214233Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-01-07T21:42:45.0219166Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-01-07T21:42:45.0225068Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-01-07T21:42:45.0230124Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-01-07T21:42:45.0236138Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-01-07T21:42:45.0241953Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-01-07T21:42:45.0245396Z 	at java.lang.Thread.run(Thread.java:748)
2020-01-07T21:42:45.0250409Z 	Suppressed: java.lang.AssertionError: Test did not commit or rollback
2020-01-07T21:42:45.0258984Z 		at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.testOnlyCheckIsReadOnly(SemiTransactionalHiveMetastore.java:1774)
2020-01-07T21:42:45.0265626Z 		at io.prestosql.plugin.hive.AbstractTestHive$HiveTransaction.close(AbstractTestHive.java:894)
2020-01-07T21:42:45.0273615Z 		at io.prestosql.plugin.hive.AbstractTestHive.doTestTransactionDeleteInsert(AbstractTestHive.java:4706)
```

**Comment by sopel39** [comment]
Failed: https://github.com/prestosql/presto/pull/2429/checks?check_run_id=378282472

**Comment by sopel39** [comment]
another one: https://github.com/prestosql/presto/pull/3731/checks?check_run_id=674619571
