### ISSUE TITLE
Delta lake connector Azure Databricks Unity Catalog https connection gives 400/404

### ISSUE THREAD

**Issue by saikiran1208** [trinodb/trino#24388]
I have been trying to configure an Azure Databricks hosted unity catalog in Trino. I am getting HTTP 400 or HTTP 404 errors and can't connect to the unity catalog schemas. Trino version is 465.

Catalog config:

 `connector.name=delta_lake`
 `hive.metastore.uri=https://<workspace url>/api/2.1/unity-catalog/catalogs`
 `hive.metastore.http.client.authentication.type=BEARER`
 `hive.metastore.http.client.bearer-token=*****`
 `hive.metastore.http.client.additional-headers=X-Databricks-Catalog-Name:[catalog_name]`
 `fs.native-azure.enabled=true`
 `azure.auth-type=ACCESS_KEY`
 `azure.access-key=<key-secret>`

With above config I get HTTP 400.

 `connector.name=delta_lake`
 `hive.metastore.uri=https://<workspace url>/api/2.1/unity-catalog/catalogs/[catalog_name]`
 `hive.metastore.http.client.authentication.type=BEARER`
 `hive.metastore.http.client.bearer-token=*****`
 `fs.native-azure.enabled=true`
 `azure.auth-type=ACCESS_KEY`
 `azure.access-key=<key-secret>`

With above config I get HTTP 404.

HTTP 404 error:
`2024-12-05T12:09:22.125Z	DEBUG	SplitRunner-xxxx-1-257	io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient	Invocation of getAllDatabases() took 102.60ms and failed with org.apache.thrift.transport.TTransportException: java.io.IOException: HTTP Response code: 404`
`2024-12-05T12:09:22.126Z	DEBUG	SplitRunner-xxxx-257	io.trino.plugin.hive.util.RetryDriver	Failed on executing getAllDatabases with attempt 10, will retry. Exception: java.io.IOException: HTTP Response code: 404`
`2024-12-05T12:09:24.379Z	DEBUG	SplitRunner-xxxx-257	io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient	Invocation of getAllDatabases() took 129.04ms and failed with org.apache.thrift.transport.TTransportException: java.io.IOException: HTTP Response code: 404`
`2024-12-05T12:09:24.383Z	DEBUG	task-notification-3	io.trino.execution.TaskStateMachine	Task xxxx_p8dt9.2.0.0 is FAILING`
`2024-12-05T12:09:24.385Z	DEBUG	task-notification-3	io.trino.execution.TaskStateMachine	Task xxxx_p8dt9.2.0.0 is FAILED`
`2024-12-05T12:09:24.383Z	DEBUG	SplitRunner-0	io.trino.execution.executor.dedicated.SplitProcessor	Error listing schemas for catalog databricks: java.io.IOException: HTTP Response code: 404`
`io.trino.spi.TrinoException: Error listing schemas for catalog databricks: java.io.IOException: HTTP Response code: 404`
	`at io.trino.metadata.MetadataListing.handleListingException(MetadataListing.java:358)
	at io.trino.metadata.MetadataListing.listSchemas(MetadataListing.java:99)
	at io.trino.metadata.MetadataListing.listSchemas(MetadataListing.java:90)
	at io.trino.connector.system.jdbc.SchemaJdbcTable.cursor(SchemaJdbcTable.java:78)
	at io.trino.spi.connector.SystemTable.cursor(SystemTable.java:47)
	at io.trino.connector.system.SystemPageSourceProvider$1.cursor(SystemPageSourceProvider.java:140)
	at io.trino.plugin.base.MappedRecordSet.cursor(MappedRecordSet.java:53)
	at io.trino.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
	at io.trino.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:119)
	at io.trino.split.PageSourceManager$PageSourceProviderInstance.createPageSource(PageSourceManager.java:79)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:261)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:192)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:359)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:423)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:423)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:423)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:423)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:255)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:423)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:133)
	at io.trino.operator.Driver.processInternal(Driver.java:403)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:306)
	at io.trino.operator.Driver.tryWithLock(Driver.java:709)
	at io.trino.operator.Driver.process(Driver.java:298)
	at io.trino.operator.Driver.processForDuration(Driver.java:269)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:890)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:77)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:201)
	at io.trino.$gen.Trino_465____xxxx_2.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:202)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:172)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:159)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: io.trino.spi.TrinoException: java.io.IOException: HTTP Response code: 404
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getAllDatabases(ThriftHiveMetastore.java:216)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.getAllDatabases(BridgingHiveMetastore.java:95)
	at io.trino.metastore.tracing.TracingHiveMetastore.lambda$getAllDatabases$1(TracingHiveMetastore.java:86)
	at io.trino.metastore.tracing.Tracing.withTracing(Tracing.java:39)
	at io.trino.metastore.tracing.TracingHiveMetastore.getAllDatabases(TracingHiveMetastore.java:85)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadAllDatabases(CachingHiveMetastore.java:425)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.lambda$new$0(CachingHiveMetastore.java:204)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at io.trino.cache.EmptyCache.lambda$get$0(EmptyCache.java:58)
	at io.trino.cache.EmptyCache.get(EmptyCache.java:94)
	at io.trino.cache.EmptyCache.get(EmptyCache.java:58)
	at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:53)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:263)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getAllDatabases(CachingHiveMetastore.java:420)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadAllDatabases(CachingHiveMetastore.java:425)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.lambda$new$0(CachingHiveMetastore.java:204)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:471)
	at io.trino.cache.EvictableCache$TokenCacheLoader.load(EvictableCache.java:457)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3574)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2316)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4017)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4040)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4989)
	at io.trino.cache.EvictableCache.get(EvictableCache.java:147)
	at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:53)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:263)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getAllDatabases(CachingHiveMetastore.java:420)
	at io.trino.plugin.deltalake.metastore.HiveMetastoreBackedDeltaLakeMetastore.getAllDatabases(HiveMetastoreBackedDeltaLakeMetastore.java:51)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.listSchemaNames(DeltaLakeMetadata.java:564)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.listSchemaNames(ClassLoaderSafeConnectorMetadata.java:200)
	at io.trino.tracing.TracingConnectorMetadata.listSchemaNames(TracingConnectorMetadata.java:133)
	at io.trino.metadata.MetadataManager.listSchemaNames(MetadataManager.java:260)
	at io.trino.tracing.TracingMetadata.listSchemaNames(TracingMetadata.java:172)
	at io.trino.metadata.MetadataListing.doListSchemas(MetadataListing.java:105)
	at io.trino.metadata.MetadataListing.listSchemas(MetadataListing.java:96)
	... 42 more
Caused by: org.apache.thrift.transport.TTransportException: java.io.IOException: HTTP Response code: 404
	at org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:287)
	at org.apache.thrift.transport.THttpClient.flush(THttpClient.java:296)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:75)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:64)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.sendGetAllDatabases(ThriftHiveMetastore.java:1216)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.getAllDatabases(ThriftHiveMetastore.java:1209)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.trino.plugin.base.util.LoggingInvocationHandler.handleInvocation(LoggingInvocationHandler.java:60)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at jdk.proxy4/jdk.proxy4.$Proxy311.getAllDatabases(Unknown Source)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.getAllDatabases(ThriftHiveMetastoreClient.java:176)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$getAllDatabases$0(ThriftHiveMetastore.java:211)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:41)
	at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:117)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getAllDatabases(ThriftHiveMetastore.java:209)
	... 79 more
	Suppressed: org.apache.thrift.transport.TTransportException: java.io.IOException: HTTP Response code: 404
		... 95 more
	Caused by: java.io.IOException: HTTP Response code: 404
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:20)
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:13)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:213)
		at org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:283)
		... 94 more
	Suppressed: org.apache.thrift.transport.TTransportException: java.io.IOException: HTTP Response code: 404
		... 95 more
	Caused by: java.io.IOException: HTTP Response code: 404
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:20)
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:13)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:213)
		at org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:283)
		... 94 more
	Suppressed: org.apache.thrift.transport.TTransportException: java.io.IOException: HTTP Response code: 404
		... 95 more
	Caused by: java.io.IOException: HTTP Response code: 404
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:20)
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:13)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:213)
		at org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:283)
		... 94 more
	Suppressed: org.apache.thrift.transport.TTransportException: java.io.IOException: HTTP Response code: 404
		... 95 more
	Caused by: java.io.IOException: HTTP Response code: 404
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:20)
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:13)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:213)
		at org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:283)
		... 94 more
	Suppressed: org.apache.thrift.transport.TTransportException: java.io.IOException: HTTP Response code: 404
		... 95 more
	Caused by: java.io.IOException: HTTP Response code: 404
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:20)
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:13)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:213)
		at org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:283)
		... 94 more
	Suppressed: org.apache.thrift.transport.TTransportException: java.io.IOException: HTTP Response code: 404
		... 95 more
	Caused by: java.io.IOException: HTTP Response code: 404
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:20)
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:13)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:213)
		at org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:283)
		... 94 more
	Suppressed: org.apache.thrift.transport.TTransportException: java.io.IOException: HTTP Response code: 404
		... 95 more
	Caused by: java.io.IOException: HTTP Response code: 404
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:20)
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:13)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:213)
		at org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:283)
		... 94 more
	Suppressed: org.apache.thrift.transport.TTransportException: java.io.IOException: HTTP Response code: 404
		... 95 more
	Caused by: java.io.IOException: HTTP Response code: 404
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:20)
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:13)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:213)
		at org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:283)
		... 94 more
	Suppressed: org.apache.thrift.transport.TTransportException: java.io.IOException: HTTP Response code: 404
		... 95 more
	Caused by: java.io.IOException: HTTP Response code: 404
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:20)
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:13)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:213)
		at org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:283)
		... 94 more
	Suppressed: org.apache.thrift.transport.TTransportException: java.io.IOException: HTTP Response code: 404
		... 95 more
	Caused by: java.io.IOException: HTTP Response code: 404
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:20)
		at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:13)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
		at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:213)
		at org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:283)
		... 94 more
Caused by: java.io.IOException: HTTP Response code: 404
	at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:20)
	at org.apache.thrift.THttpClientResponseHandler.handleResponse(THttpClientResponseHandler.java:13)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:213)
	at org.apache.thrift.transport.THttpClient.flushUsingHttpClient(THttpClient.java:283)
	... 94 more
`

**Comment by ebyhr** [comment]
You should use `/api/2.1/unity-catalog/iceberg` (not `/catalogs`) in the 1st example.

**Comment by saikiran1208** [comment]
@ebyhr - we do not have iceberg tables in our databricks workspace, so the only way  to talk to unity catalog from trino is via this iceberg endpoint?
