### ISSUE TITLE
Fix hive4 tests failing with `location must not be root path`

### ISSUE THREAD

**Issue by mayankvadariya** [trinodb/trino#24453]
Fix certain tests failing with `location must not be root path` in `TestHive4OnDataLake`.

```java
Caused by: io.trino.hive.thrift.metastore.InvalidObjectException: test_sync_partition_on_bucket_root_39h7u99fo2 location must not be root path
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:60697)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:60673)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$create_table_result.read(ThriftHiveMetastore.java:60598)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:93)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.recvCreateTable(ThriftHiveMetastore.java:1535)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.createTable(ThriftHiveMetastore.java:1522)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.createTable(ThriftHiveMetastoreClient.java:240)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$createTable$31(ThriftHiveMetastore.java:846)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:41)
	at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:117)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createTable(ThriftHiveMetastore.java:844)
```

**Comment by hashhar** [comment]
this is something we should report to Hive folks instead and get them to fix properly.

Instead of fixing bug where DROP TABLE on root location threw NPE they simply disallowed creating such tables. That doesn't even help since people can have already existing tables pointing to root locations.

See https://issues.apache.org/jira/browse/HIVE-25912 + https://github.com/apache/hive/pull/3009

**Comment by okumin** [comment]
> since people can have already existing tables pointing to root locations

Do you know if this is an actual use case?

**Comment by milnomada** [comment]
We are facing the issue of not being able to create hive tables at the root path of a bucket.

```sql
CREATE TABLE hive.default.data (
    id varchar,
    country varchar,
    year integer WITH (partition_projection_range = ARRAY['2025','2035'], partition_projection_type = 'INTEGER'),
    month integer WITH (partition_projection_range = ARRAY['01','12'], partition_projection_type = 'INTEGER')
) WITH (
    external_location = 's3a://bucket-us-data/',
    format = 'PARQUET',
    partition_projection_location_template = 's3a://bucket-us-data/year=${year}/month=${month}/',
    partitioned_by = ARRAY['year', 'month']
)
```

```
Caused by: io.trino.hive.thrift.metastore.InvalidObjectException: data location must not be root path
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:62807)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:62783)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$create_table_result.read(ThriftHiveMetastore.java:62708)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:93)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.recvCreateTable(ThriftHiveMetastore.java:1535)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.createTable(ThriftHiveMetastore.java:1522)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.createTable(ThriftHiveMetastoreClient.java:264)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.lambda$createTable$0(FailureAwareThriftMetastoreClient.java:128)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.runWithHandle(FailureAwareThriftMetastoreClient.java:484)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.createTable(FailureAwareThriftMetastoreClient.java:128)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$createTable$0(ThriftHiveMetastore.java:873)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:41)
	at io.trino.plugin.hive.metastore.thrift.RetryDriver.run(RetryDriver.java:117)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createTable(ThriftHiveMetastore.java:871)
```
Most of our hive tables are stored into a single bucket. The path structure being similar to
```bash
s3a://bucket-us-data/year=2025/month=01/...
```
The following create table sentence works regardless `external_location` is provided or not:
```sql
CREATE TABLE hive.default.data (
    id varchar,
    country varchar,
    year integer WITH (partition_projection_range = ARRAY['2025','2035'], partition_projection_type = 'INTEGER'),
    month integer WITH (partition_projection_range = ARRAY['01','12'], partition_projection_type = 'INTEGER')
) WITH (
    external_location = 's3a://bucket-us-data/non-existing-path/',
    format = 'PARQUET',
    partition_projection_location_template = 's3a://bucket-us-data/year=${year}/month=${month}/',
    partitioned_by = ARRAY['year', 'month']
)
```
Unfortunately a SELECT on that table will provide zero results, so no visibility on the existing parquet files:
```sql
SELECT id, country
FROM hive.default.data
WHERE year = 2026 and month = 05;

id | country
---+--------
(0 rows)
```

If `external_location` is omitted, the SHOW CREATE TABLE sentence will show a generated (_non provided_) external_location with the following value:
```
external_location = 's3a://bucket-us-data/data/'
```
where `data` is the name of the table used on the CREATE TABLE statement.


I do not see the reason why the Hive Connector doesn't allow us to create a table on the root path of a bucket.
This should be supported as a basic feature, the root path is as valid as any other path on the s3 filesystem.
