### ISSUE TITLE
Fix hive4 test failing with `Processor has no capabilities, cannot create an ACID table`

### ISSUE THREAD

**Issue by mayankvadariya** [trinodb/trino#24454]
Fix `TestHive4OnDataLake#testInsertOverwritePartitionedAndBucketedAcidTable` test which fails with `Processor has no capabilities, cannot create an ACID table`.

```java
Caused by: io.trino.hive.thrift.metastore.MetaException: Processor has no capabilities, cannot create an ACID table.
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:60706)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:60673)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$create_table_result.read(ThriftHiveMetastore.java:60598)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:93)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.recvCreateTable(ThriftHiveMetastore.java:1535)
	at io.trino.hive.thrift.metastore.ThriftHiveMetastore$Client.createTable(ThriftHiveMetastore.java:1522)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.createTable(ThriftHiveMetastoreClient.java:240)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$createTable$31(ThriftHiveMetastore.java:846)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:41)
	at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:117)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createTable(ThriftHiveMetastore.java:844)
```

**Comment by okumin** [comment]
We had [a related discussion in Slack](https://trinodb.slack.com/archives/C0305TQ05KL/p1738695135713999).

I can also reproduce the issue using Trino 413.
- Hive 3.1.2 -> OK
- Hive 4.0.0 -> KO
- Hive 4.0.1 -> KO

We found that Hive 4 requires clients to present their capabilities explicitly when using Hive ACID. The new validations make sense to me, as clients must follow some ACID rules. I believe Trino can correctly write data in an ACID table, and I am trying to let Trino pass the new parameters to HMS.

**Comment by raphaelauv** [comment]
Trino 477 and Hive 4.1.0 

```sql
CREATE TABLE  hive.example.request_logs3 (
  request_time TIMESTAMP
)
WITH (
    transactional=true
);
```

```log
org.apache.hadoop.hive.metastore.api.MetaException: Processor has no capabilities, cannot create an ACID table.
 	at org.apache.hadoop.hive.metastore.MetastoreDefaultTransformer.transformCreateTable(MetastoreDefaultTransformer.java:682) ~[hive-exec-4.1.0.jar:4.1.0]
```

**Comment by okumin** [comment]
Thanks for the feedback. The first PR is already drafted. We can make a progress once the Trino maintainer chimes in.
https://github.com/trinodb/hive-thrift/pull/7
