### ISSUE TITLE
Flaky TestPrestoDriver.testQueryCancelByInterrupt

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#2497]
```
2020-01-14T02:39:52.0647438Z 2020-01-13T20:39:52.063-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.1.0-1182	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.1.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0
2020-01-14T02:39:52.0680472Z 2020-01-13T20:39:52.067-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.0.0-1182	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.0.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0
2020-01-14T02:39:52.5659609Z 2020-01-13T20:39:52.564-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.1.0-1182	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.1.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0
2020-01-14T02:39:52.5699368Z 2020-01-13T20:39:52.568-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.0.0-1182	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.0.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0
2020-01-14T02:39:52.5951819Z 2020-01-13T20:39:52.594-0600	WARN	TaskInfoFetcher-20200114_023937_00118_c4isa.1.0-1182	io.prestosql.server.remotetask.RequestErrorTracker	Error getting info for task 20200114_023937_00118_c4isa.1.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0?summarize: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0
2020-01-14T02:39:52.5953267Z 2020-01-13T20:39:52.594-0600	WARN	TaskInfoFetcher-20200114_023937_00118_c4isa.0.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting info for task 20200114_023937_00118_c4isa.0.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0?summarize: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0
2020-01-14T02:39:53.0671519Z 2020-01-13T20:39:53.066-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.1.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.1.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0
2020-01-14T02:39:53.0695665Z 2020-01-13T20:39:53.068-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.0.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.0.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0
2020-01-14T02:39:53.3804326Z 2020-01-13T20:39:53.379-0600	WARN	http-client-node-manager-1004	io.prestosql.metadata.RemoteNodeState	Error fetching node state from http://127.0.0.1:35851/v1/info/state: Server refused connection: http://127.0.0.1:35851/v1/info/state
2020-01-14T02:39:53.4213631Z 2020-01-13T20:39:53.420-0600	WARN	http-client-memoryManager-986	io.prestosql.memory.RemoteNodeMemory	Error fetching memory info from http://127.0.0.1:35851/v1/memory: Server refused connection: http://127.0.0.1:35851/v1/memory
2020-01-14T02:39:53.5678915Z 2020-01-13T20:39:53.567-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.1.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.1.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0
2020-01-14T02:39:53.5700629Z 2020-01-13T20:39:53.569-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.0.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.0.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0
2020-01-14T02:39:54.0690114Z 2020-01-13T20:39:54.068-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.1.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.1.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0
2020-01-14T02:39:54.0711065Z 2020-01-13T20:39:54.070-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.0.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.0.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0
2020-01-14T02:39:54.4229031Z 2020-01-13T20:39:54.422-0600	WARN	http-client-memoryManager-991	io.prestosql.memory.RemoteNodeMemory	Error fetching memory info from http://127.0.0.1:35851/v1/memory: Server refused connection: http://127.0.0.1:35851/v1/memory
2020-01-14T02:39:54.5699434Z 2020-01-13T20:39:54.569-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.1.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.1.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0
2020-01-14T02:39:54.5719526Z 2020-01-13T20:39:54.570-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.0.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.0.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0
2020-01-14T02:39:55.0709980Z 2020-01-13T20:39:55.070-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.1.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.1.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0
2020-01-14T02:39:55.0725133Z 2020-01-13T20:39:55.071-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.0.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.0.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0
2020-01-14T02:39:55.5719044Z 2020-01-13T20:39:55.570-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.1.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.1.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0
2020-01-14T02:39:55.5732122Z 2020-01-13T20:39:55.572-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.0.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.0.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0
2020-01-14T02:39:55.5979876Z 2020-01-13T20:39:55.596-0600	WARN	TaskInfoFetcher-20200114_023937_00118_c4isa.1.0-1182	io.prestosql.server.remotetask.RequestErrorTracker	Error getting info for task 20200114_023937_00118_c4isa.1.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0?summarize: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0
2020-01-14T02:39:55.5982488Z 2020-01-13T20:39:55.597-0600	WARN	TaskInfoFetcher-20200114_023937_00118_c4isa.0.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting info for task 20200114_023937_00118_c4isa.0.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0?summarize: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0
2020-01-14T02:39:56.0728459Z 2020-01-13T20:39:56.071-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.1.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.1.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0
2020-01-14T02:39:56.0739653Z 2020-01-13T20:39:56.073-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.0.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.0.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0
2020-01-14T02:39:56.4252958Z 2020-01-13T20:39:56.424-0600	WARN	http-client-memoryManager-986	io.prestosql.memory.RemoteNodeMemory	Error fetching memory info from http://127.0.0.1:35851/v1/memory: Server refused connection: http://127.0.0.1:35851/v1/memory
2020-01-14T02:39:56.5738788Z 2020-01-13T20:39:56.572-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.1.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.1.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.1.0
2020-01-14T02:39:56.5747595Z 2020-01-13T20:39:56.573-0600	WARN	ContinuousTaskStatusFetcher-20200114_023937_00118_c4isa.0.0-1163	io.prestosql.server.remotetask.RequestErrorTracker	Error getting task status 20200114_023937_00118_c4isa.0.0: Server refused connection: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0/status: http://127.0.0.1:35851/v1/task/20200114_023937_00118_c4isa.0.0
2020-01-14T02:39:56.6933565Z 2020-01-13T20:39:56.692-0600	INFO	pool-1-thread-1	io.airlift.bootstrap.LifeCycleManager	Life cycle stopped.
2020-01-14T02:39:56.9665324Z [ERROR] Tests run: 113, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 75.254 s <<< FAILURE! - in TestSuite
2020-01-14T02:39:56.9673593Z [ERROR] testQueryCancelByInterrupt(io.prestosql.jdbc.TestPrestoDriver)  Time elapsed: 1.29 s  <<< FAILURE!
2020-01-14T02:39:56.9677812Z java.lang.AssertionError: expected [FAILED] but found [RUNNING]
2020-01-14T02:39:56.9681753Z 	at org.testng.Assert.fail(Assert.java:94)
2020-01-14T02:39:56.9686643Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2020-01-14T02:39:56.9701028Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2020-01-14T02:39:56.9705217Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2020-01-14T02:39:56.9709710Z 	at org.testng.Assert.assertEquals(Assert.java:179)
2020-01-14T02:39:56.9715885Z 	at io.prestosql.jdbc.TestPrestoDriver.testQueryCancelByInterrupt(TestPrestoDriver.java:786)
2020-01-14T02:39:56.9725061Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-01-14T02:39:56.9731421Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-01-14T02:39:56.9737748Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-01-14T02:39:56.9741886Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-01-14T02:39:56.9749054Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-01-14T02:39:56.9754689Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-01-14T02:39:56.9760405Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-01-14T02:39:56.9765474Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-01-14T02:39:56.9770287Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-01-14T02:39:56.9775986Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-01-14T02:39:56.9781844Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-01-14T02:39:56.9785239Z 	at java.lang.Thread.run(Thread.java:748)
2020-01-14T02:39:56.9786112Z 
2020-01-14T02:39:57.3230654Z [INFO] 
2020-01-14T02:39:57.3231231Z [INFO] Results:
2020-01-14T02:39:57.3231433Z [INFO] 
2020-01-14T02:39:57.3231713Z [ERROR] Failures: 
2020-01-14T02:39:57.3231915Z [ERROR]   TestPrestoDriver.testQueryCancelByInterrupt:786 expected [FAILED] but found [RUNNING]
2020-01-14T02:39:57.3232150Z [INFO] 
2020-01-14T02:39:57.3232691Z [ERROR] Tests run: 113, Failures: 1, Errors: 0, Skipped: 0
```

https://github.com/prestosql/presto/pull/2496
https://github.com/prestosql/presto/pull/2496/checks?check_run_id=388195610

**Comment by sopel39** [comment]
Failed again: https://pipelines.actions.githubusercontent.com/sJrKZtZsjYLeyqPixYxcTJp8fX9YNlwyJbmEGSC0oymXVDSpbK/_apis/pipelines/1/runs/4300/signedlogcontent/7?urlExpires=2020-01-31T11%3A16%3A01.3540988Z&urlSigningMethod=HMACV1&urlSignature=id9n3uz5ATprKvoJngJ4ZyjGtOmYHUZhBMdsQMZoRzg%3D

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/2898/checks?check_run_id=460408354

**Comment by hashhar** [comment]
Not seen recently. Most likely fixed via https://github.com/trinodb/trino/commit/9485e428ba90edf424f86d700646929578993983
