### ISSUE TITLE
CTAS failure during commit leaves table behind, cannot be retried

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#2537]
**Given**

```
presto> USE hive.default;

presto> CREATE TABLE nation AS SELECT * FROM tpch.tiny.nation;
```

**When**
```
presto> SET SESSION query_max_execution_time = '5s';
presto> CREATE TABLE t WITH (partitioned_by=ARRAY['comment']) AS SELECT * FROM nation;

Query 20200117_094529_00005_nfxfs, FAILED, 1 node
http://localhost:8080/ui/query.html?20200117_094529_00005_nfxfs
Splits: 35 total, 35 done (100.00%)
CPU Time: 0.4s total,    63 rows/s, 3.76KB/s, 20% active
Per Node: 0.1 parallelism,     4 rows/s,   255B/s
Parallelism: 0.1
Peak Memory: 0B
0:06 [25 rows, 1.49KB] [4 rows/s, 255B/s]

Query 20200117_094529_00005_nfxfs failed: Query exceeded the maximum execution time limit of 5.00s
io.prestosql.spi.PrestoException: Query exceeded the maximum execution time limit of 5.00s
	at io.prestosql.execution.QueryTracker.enforceTimeLimits(QueryTracker.java:184)
	at io.prestosql.execution.QueryTracker.lambda$start$0(QueryTracker.java:88)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Yet**
```
presto:default> SHOW TABLES;
 Table
--------
 nation
 t
(2 rows)
```

**Expected**
* query cancels (and leaves nothing behind) or query succeeds

**Notes**
The query writes data fast (less than 5s), but it takes a lot time to commit transaction, as this includes quite a few calls to the metastore.
Query gets killed after 5s run time, yet commit completes.

Query cannot be tried, because the table already exists.

**Comment by sopel39** [comment]
Query is stuck in `FINISHING` state, which cannot be terminated. What would be the solution here?

It seems that client should be resilient against such state, because it might happen for other reasons too (e.g lost communication between client and Presto).

**Comment by findepi** [comment]
My think is -- the `FINISHING` state is either short (nothing to commit)m or cannot be interrupted (because apparently we cannot abort transaction during its commit phase).
So I think that `FINISHING` state should be uninterruptible and attempt to fail/cancel query in this state should be ineffective (ideally: should throw).

I am aware this isn't ideal (committing can take considerable amount of time). But the apparently only alternative -- fail query but continue work and retain all results -- is less appealing.

cc @dain @electrum

**Comment by electrum** [comment]
I agree, we should not interrupt the connector in the middle of commit or abort calls.

**Comment by dain** [comment]
We discussed offline and agreed to:
* Change `TransactionManager.asyncCommit` to return a specialized commit job/task object
* Change `QueryStateMachine` fail calls delegate to commit object, so failure after commit starts is "owned" by the commit object.
* Change SPI `ConnectorTransactionMetadata.commit` to return a  specialized commit job/task object that has an `abort` method.
* On failure during commit, add commit tasks are aborted, and a timer started. 
  * If already committed, failure is ignored.
  * If abort completes successfully, query fails with original failure message.
  * Commit abort has a timeout.  If timeout triggers, abort is abandoned (may continue to run in background), and query is failed with original failure with suppressed abort timed exception and a query warning stating final transaction state is unknown.

Proposed interface changes in SPI
```java
public interface Connector
{
    /**
     * Commit the transaction. Will be called at most once and will not be called if
     * {@link #rollback(ConnectorTransactionHandle)} is called.  When commit is completed
     * or rolled back, the callback must be notified.  If possible, the returned {@link CommitTask}
     * should be implemented, so if the commit is aborted a rollback is triggered.
     */
    default CommitTask commit(ConnectorTransactionHandle transactionHandle, Consumer<CommitState> callback) {}
}

public interface CommitTask
{
    void abort();
}

public static final class CommitState
{
    public enum State
    {
        /**
         * The commit was completed successfully.
         */
        COMMITTED,
        /**
         * The commit was rolled back successfully.
         */
        ROLLED_BACK,
        /**
         * The commit state is unknown.  The transaction may fully committed,
         * rolled back, or partially committed.
         */
        UNKNOWN
    }

    public static CommitState committed()
    {
        return new CommitState(State.COMMITTED, Optional.empty());
    }

    public static CommitState rolledBack(Optional<Throwable> throwable)
    {
        return new CommitState(State.ROLLED_BACK, throwable);
    }

    public static CommitState unknown(Throwable throwable)
    {
        return new CommitState(State.UNKNOWN, Optional.of(throwable));
    }

    private final State state;
    private final Optional<Throwable> exception;

    private CommitState(State state, Optional<Throwable> exception)
    {
        this.state = state;
        this.exception = exception;
    }

    public State getState()
    {
        return state;
    }

    public Optional<Throwable> getException()
    {
        return exception;
    }
}
```
