### ISSUE TITLE
Flaky test io.prestosql.tests.TestInformationSchemaConnector

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#2894]
```
2020-02-21T11:59:32.2492429Z [ERROR] io.prestosql.tests.TestInformationSchemaConnector
2020-02-21T11:59:32.2492572Z [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
2020-02-21T11:59:32.2493663Z [ERROR] Command was /bin/sh -c cd /home/runner/work/presto/presto/presto-tests && /opt/hostedtoolcache/jdk/8.0.242/x64/jre/bin/java -Dfile.encoding=UTF-8 -Xmx2g -Xms2g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -jar /home/runner/work/presto/presto/presto-tests/target/surefire/surefirebooter2433489527337364074.jar /home/runner/work/presto/presto/presto-tests/target/surefire 2020-02-21T11-37-37_842-jvmRun1 surefire1674944895439323457tmp surefire_08033847260995622906tmp
2020-02-21T11:59:32.2493844Z [ERROR] Error occurred in starting fork, check output in log
2020-02-21T11:59:32.2493957Z [ERROR] Process Exit Code: 3
2020-02-21T11:59:32.2494063Z [ERROR] Crashed tests:
2020-02-21T11:59:32.2494153Z [ERROR] io.prestosql.tests.TestInformationSchemaConnector
2020-02-21T11:59:32.2494277Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
2020-02-21T11:59:32.2494408Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
2020-02-21T11:59:32.2494539Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
2020-02-21T11:59:32.2494655Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
2020-02-21T11:59:32.2494790Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
2020-02-21T11:59:32.2494937Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
2020-02-21T11:59:32.2495079Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:868)
2020-02-21T11:59:32.2495215Z [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
2020-02-21T11:59:32.2495341Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
2020-02-21T11:59:32.2495579Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
2020-02-21T11:59:32.2495710Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
2020-02-21T11:59:32.2495849Z [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
2020-02-21T11:59:32.2495988Z [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
2020-02-21T11:59:32.2496139Z [ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
2020-02-21T11:59:32.2496262Z [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
2020-02-21T11:59:32.2496386Z [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
2020-02-21T11:59:32.2496505Z [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
2020-02-21T11:59:32.2496626Z [ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
2020-02-21T11:59:32.2496730Z [ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
2020-02-21T11:59:32.2496850Z [ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
2020-02-21T11:59:32.2496964Z [ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
2020-02-21T11:59:32.2497080Z [ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-02-21T11:59:32.2497254Z [ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-02-21T11:59:32.2497386Z [ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-02-21T11:59:32.2497509Z [ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-02-21T11:59:32.2497632Z [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
2020-02-21T11:59:32.2497757Z [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
2020-02-21T11:59:32.2497878Z [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
2020-02-21T11:59:32.2498005Z [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
2020-02-21T11:59:32.2498126Z [ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-02-21T11:59:32.2498248Z [ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-02-21T11:59:32.2498380Z [ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-02-21T11:59:32.2498488Z [ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-02-21T11:59:32.2498607Z [ERROR] 	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
2020-02-21T11:59:32.2498732Z [ERROR] 	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
2020-02-21T11:59:32.2498858Z [ERROR] 	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
2020-02-21T11:59:32.2499156Z [ERROR] -> [Help 1]
```

Happened at https://github.com/prestosql/presto/pull/2823/checks?check_run_id=460037759

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/460223494 (on master)

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/3000/checks?check_run_id=485665800
