### ISSUE TITLE
Flaky test TestIndexer.testMutationIndex

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#3291]
```
2020-03-30T23:54:55.0469533Z [ERROR] testMutationIndex(io.prestosql.plugin.accumulo.index.TestIndexer)  Time elapsed: 0.002 s  <<< FAILURE!
2020-03-30T23:54:55.0471957Z java.lang.NullPointerException
2020-03-30T23:54:55.0476080Z 	at org.apache.accumulo.core.data.Mutation.serialize(Mutation.java:96)
2020-03-30T23:54:55.0480256Z 	at org.apache.accumulo.core.data.Mutation.getUpdates(Mutation.java:805)
2020-03-30T23:54:55.0484338Z 	at io.prestosql.plugin.accumulo.index.Indexer.index(Indexer.java:216)
2020-03-30T23:54:55.0489352Z 	at io.prestosql.plugin.accumulo.index.TestIndexer.testMutationIndex(TestIndexer.java:126)
2020-03-30T23:54:55.0494475Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-03-30T23:54:55.0498851Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-03-30T23:54:55.0503529Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-03-30T23:54:55.0506694Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-03-30T23:54:55.0511467Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-03-30T23:54:55.0515009Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-03-30T23:54:55.0518751Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-03-30T23:54:55.0522984Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-03-30T23:54:55.0529462Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-03-30T23:54:55.0533904Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-03-30T23:54:55.0538421Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-03-30T23:54:55.0542829Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-03-30T23:54:55.0545487Z 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/547069501

**Comment by hashhar** [comment]
Long time without occurrence.
