### ISSUE TITLE
"Self-suppression not permitted" possible when writing sequence file fails

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#3326]
```
[2020-04-02T12:48:06.159Z] ptl-presto-master   | java.lang.IllegalArgumentException: Self-suppression not permitted
[2020-04-02T12:48:06.159Z] ptl-presto-master   | 	at java.lang.Throwable.addSuppressed(Throwable.java:1072)
[2020-04-02T12:48:06.159Z] ptl-presto-master   | 	at io.prestosql.plugin.hive.util.SequenceFileRecordWriter.close(SequenceFileRecordWriter.java:72)
[2020-04-02T12:48:06.159Z] ptl-presto-master   | 	at io.prestosql.plugin.hive.RecordFileWriter.commit(RecordFileWriter.java:180)
[2020-04-02T12:48:06.159Z] ptl-presto-master   | 	at io.prestosql.plugin.hive.HiveWriter.commit(HiveWriter.java:86)
[2020-04-02T12:48:06.159Z] ptl-presto-master   | 	at io.prestosql.plugin.hive.HivePageSink.doFinish(HivePageSink.java:190)
[2020-04-02T12:48:06.159Z] ptl-presto-master   | 	at io.prestosql.plugin.hive.authentication.UserGroupInformationUtils.lambda$executeActionInDoAs$0(UserGroupInformationUtils.java:29)
...
[2020-04-02T12:48:06.159Z] ptl-presto-master   | 	at io.prestosql.$gen.Presto_0c13d16____20200402_124218_2.run(Unknown Source)
```

https://github.com/prestosql/presto/blob/f65f87f03f11bd3ff1c45320ab833b54c1ceea14/presto-hive/src/main/java/io/prestosql/plugin/hive/util/SequenceFileRecordWriter.java#L67-L72

**Comment by floreasorin** [comment]
Since this a good first issue I would like to work on this if nobody wants to take it.

**Comment by findepi** [comment]
@floreasorin thanks, go for it!

you may want to check the code for `// Self-suppression not permitted` comments for the start

**Comment by electrum** [comment]
Do you know what data source causes this?

**Comment by electrum** [comment]
Do you know what data source causes this? The "Caused by" for the `IllegalArgumentException` is missing from the original bug report.

**Comment by findepi** [comment]
Yeah, i should have retained full stack. There is  `SequenceFileRecordWriter`  in the stacktrace retained.

**Comment by zhang-arvin** [comment]
I investigated this issue and found that the `SequenceFileRecordWriter` class has been removed from the codebase (commit `0cae5088` - "Remove legacy Hive writers", Jul 2023). The current `SequenceFileWriter` in `lib/trino-hive-formats` uses Guava's `Closer` which already handles the self-suppression case with a guard: `if (thrown == suppressed) return;`.

The bug is no longer present in the current codebase. This issue can be closed.
