### ISSUE TITLE
Flaky test TestConnectorEventListener.testConnectorEventHandlerReceivingEvents

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#3364]
```
2020-04-07T07:25:47.5983180Z [ERROR] testConnectorEventHandlerReceivingEvents(io.prestosql.execution.TestConnectorEventListener)  Time elapsed: 0.519 s  <<< FAILURE!
2020-04-07T07:25:47.5983356Z java.lang.AssertionError: 
2020-04-07T07:25:47.5983564Z 
2020-04-07T07:25:47.5984046Z Expecting:
2020-04-07T07:25:47.5984665Z  <0>
2020-04-07T07:25:47.5984972Z to be equal to:
2020-04-07T07:25:47.5985960Z  <1>
2020-04-07T07:25:47.5987723Z but was not.
2020-04-07T07:25:47.5995476Z 	at io.prestosql.execution.TestConnectorEventListener.testConnectorEventHandlerReceivingEvents(TestConnectorEventListener.java:79)
2020-04-07T07:25:47.5999773Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-04-07T07:25:47.6006310Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-04-07T07:25:47.6013092Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-04-07T07:25:47.6016902Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-04-07T07:25:47.6022758Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-04-07T07:25:47.6027085Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-04-07T07:25:47.6031547Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-04-07T07:25:47.6036333Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-04-07T07:25:47.6041783Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-04-07T07:25:47.6046733Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-04-07T07:25:47.6051919Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-04-07T07:25:47.6057452Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-04-07T07:25:47.6060827Z 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by findepi** [comment]
When run locally, this test fails 50% times.

cc @s2lomon

**Comment by s2lomon** [comment]
Thanks for noticing. I will increase the timeout for now.

**Comment by s2lomon** [comment]
@findepi here is the pr: https://github.com/prestosql/presto/pull/3369

**Comment by ebyhr** [comment]
Going to close this issue since af42e81 was already merged.

**Comment by findepi** [comment]
according to @nineinchnick 's https://nineinchnick.github.io/trino-cicd/reports/flaky/#flaky-test-classes-in-last-30-days
`TestConnectorEventListener` is the most flaky test class (and `testConnectorEventHandlerReceivingEvents` is its only test method)

shall we reopen?

or should i be worried no-one manually commented under this issue since April when it was closed?

**Comment by findepi** [comment]
the timeout inside test was bumped from 2 to 3 in af42e81b6ad25fab0002ee700caeb6bff903a63e
and then bumped to 30 in https://github.com/trinodb/trino/pull/13321
but even under that PR @raunaqmorarka reported https://github.com/trinodb/trino/pull/13321#issuecomment-1193081114 30 is not enough

The https://nineinchnick.github.io/trino-cicd/reports/flaky/#flaky-test-classes-in-last-30-days reports the test would fail with these exception messages

```
[Query did not complete in 30.00s, Query did not complete in 3.00s]
```
