### ISSUE TITLE
Kudu tests cannot be run on Mac

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#3415]
Currently tests like `TestKuduDistributedQueries` run on CI but cannot be run on Mac.

```
java.lang.RuntimeException: cannot complete before timeout: ScanRequest(scannerId=null, tablet=84f2567282344016a97d23a692e85342, attempt=7, KuduRpc(method=Scan, tablet=84f2567282344016a97d23a692e85342, attempt=7, TimeoutTracker(timeout=30000, elapsed=30012), Trace Summary(20159 ms): Sent(7), Received(6), Delayed(3), MasterRefresh(3), AuthRefresh(0), Truncated: false
 Sent: (a6d9d482c7214d67ab91ced77b9e22db, [ Scan, 4 ]), (master-localhost:32769, [ GetTableLocations, 3 ])
 Received: (a6d9d482c7214d67ab91ced77b9e22db, [ NETWORK_ERROR, 3 ]), (master-localhost:32769, [ OK, 3 ])
 Delayed: (UNKNOWN, [ Scan, 3 ])))

	at io.prestosql.testing.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:114)
	at io.prestosql.testing.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:79)
	at io.prestosql.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:431)
	at io.prestosql.plugin.kudu.KuduQueryRunnerFactory.installKuduConnector(KuduQueryRunnerFactory.java:102)
	at io.prestosql.plugin.kudu.KuduQueryRunnerFactory.createKuduQueryRunnerTpch(KuduQueryRunnerFactory.java:71)
	at io.prestosql.plugin.kudu.TestKuduDistributedQueries.createQueryRunner(TestKuduDistributedQueries.java:41)
	at io.prestosql.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: io.prestosql.spi.PrestoException: cannot complete before timeout: ScanRequest(scannerId=null, tablet=84f2567282344016a97d23a692e85342, attempt=7, KuduRpc(method=Scan, tablet=84f2567282344016a97d23a692e85342, attempt=7, TimeoutTracker(timeout=30000, elapsed=30012), Trace Summary(20159 ms): Sent(7), Received(6), Delayed(3), MasterRefresh(3), AuthRefresh(0), Truncated: false
 Sent: (a6d9d482c7214d67ab91ced77b9e22db, [ Scan, 4 ]), (master-localhost:32769, [ GetTableLocations, 3 ])
 Received: (a6d9d482c7214d67ab91ced77b9e22db, [ NETWORK_ERROR, 3 ]), (master-localhost:32769, [ OK, 3 ])
 Delayed: (UNKNOWN, [ Scan, 3 ])))
	at io.prestosql.plugin.kudu.schema.SchemaEmulationByTableNameConvention.listSchemaNames(SchemaEmulationByTableNameConvention.java:148)
	at io.prestosql.plugin.kudu.KuduClientSession.listSchemaNames(KuduClientSession.java:93)
	at io.prestosql.plugin.kudu.KuduMetadata.listSchemaNames(KuduMetadata.java:77)
	at io.prestosql.spi.connector.ConnectorMetadata.schemaExists(ConnectorMetadata.java:54)
	at io.prestosql.metadata.MetadataManager.lambda$schemaExists$0(MetadataManager.java:278)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at io.prestosql.metadata.MetadataManager.schemaExists(MetadataManager.java:278)
	at io.prestosql.execution.DropSchemaTask.execute(DropSchemaTask.java:60)
	at io.prestosql.execution.DropSchemaTask.execute(DropSchemaTask.java:35)
	at io.prestosql.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:167)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132)
	at io.prestosql.$gen.Presto_null__testversion____20200412_191531_3.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kudu.client.NonRecoverableException: cannot complete before timeout: ScanRequest(scannerId=null, tablet=84f2567282344016a97d23a692e85342, attempt=7, KuduRpc(method=Scan, tablet=84f2567282344016a97d23a692e85342, attempt=7, TimeoutTracker(timeout=30000, elapsed=30012), Trace Summary(20159 ms): Sent(7), Received(6), Delayed(3), MasterRefresh(3), AuthRefresh(0), Truncated: false
 Sent: (a6d9d482c7214d67ab91ced77b9e22db, [ Scan, 4 ]), (master-localhost:32769, [ GetTableLocations, 3 ])
 Received: (a6d9d482c7214d67ab91ced77b9e22db, [ NETWORK_ERROR, 3 ]), (master-localhost:32769, [ OK, 3 ])
 Delayed: (UNKNOWN, [ Scan, 3 ])))
	at org.apache.kudu.client.KuduException.transformException(KuduException.java:110)
	at org.apache.kudu.client.KuduClient.joinAndHandleException(KuduClient.java:413)
	at org.apache.kudu.client.KuduScanner.nextRows(KuduScanner.java:72)
	at io.prestosql.plugin.kudu.schema.SchemaEmulationByTableNameConvention.listSchemaNames(SchemaEmulationByTableNameConvention.java:137)
	... 25 more
	Suppressed: org.apache.kudu.client.KuduException.OriginalException: Original asynchronous stack trace
		at org.apache.kudu.client.KuduRpc$RpcTimeoutTask.run(KuduRpc.java:457)
		at org.apache.kudu.shaded.org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
		at org.apache.kudu.shaded.org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
		at org.apache.kudu.shaded.org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
		at org.apache.kudu.shaded.org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
		... 1 more


```

**Comment by findepi** [comment]
Maybe we should convert the tests into product tests?

**Comment by Praveen2112** [comment]
If Docker's networking problem wrt to Mac exists then we have to convert them to product tests..

**Comment by martint** [comment]
> If Docker's networking problem wrt to Mac exists then we have to convert them to product tests..

I've been able to run the Kudu connector on my mac by running Kudu directly (not via TestContainers). I just followed https://kudu.apache.org/docs/quickstart.html.

**Comment by grantatspothero** [comment]
> If Docker's networking problem wrt to Mac exists then we have to convert them to product tests..

@Praveen2112 @findepi any more context around what "docker's networking problem WRT to Mac" means? I'm running into this issue currently

**Comment by grantatspothero** [comment]
I was able to get the tests running in testcontainers using a fixed port mapping (what the linked kudu docker compose is doing).

Since testcontainers strongly suggests not using fixed port mappings, I'm attempting to workaround that by either:
1. Choosing a random open port and then using a fixed port mapping  
2. Getting testcontainers to inject information about the mapped port into the container somehow  (mount docker socket and hit the docker API?) 

But both of those sound bad. 

If this is a problem people have encountered before with testcontainers and they know a better workaround definitely let me know :)
