### ISSUE TITLE
Mongo connector fails on INSERT when column contains a dot

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#3460]
```
CREATE TABLE t("a.dot" varchar);

INSERT INTO t VALUES ('abc');

java.lang.IllegalArgumentException: Invalid BSON field name a.dot
	at org.bson.AbstractBsonWriter.writeName(AbstractBsonWriter.java:531)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:198)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:141)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:45)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.operation.BulkWriteBatch$WriteRequestEncoder.encode(BulkWriteBatch.java:381)
	at com.mongodb.operation.BulkWriteBatch$WriteRequestEncoder.encode(BulkWriteBatch.java:371)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:74)
	at com.mongodb.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:58)
	at com.mongodb.connection.BsonWriterHelper.writePayloadArray(BsonWriterHelper.java:50)
	at com.mongodb.connection.SplittablePayloadBsonWriter.writeEndDocument(SplittablePayloadBsonWriter.java:52)
	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:118)
	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:41)
	at com.mongodb.connection.CommandMessage.addDocumentWithPayload(CommandMessage.java:166)
	at com.mongodb.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:148)
	at com.mongodb.connection.RequestMessage.encode(RequestMessage.java:145)
	at com.mongodb.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:244)
	at com.mongodb.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:98)
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:441)
	at com.mongodb.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:189)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:263)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:126)
	at com.mongodb.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:373)
	at com.mongodb.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:255)
	at com.mongodb.operation.MixedBulkWriteOperation.access$700(MixedBulkWriteOperation.java:66)
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:199)
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:190)
	at com.mongodb.operation.OperationHelper.withReleasableConnection(OperationHelper.java:432)
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:190)
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:66)
	at com.mongodb.Mongo$3.execute(Mongo.java:833)
	at com.mongodb.MongoCollectionImpl.executeInsertMany(MongoCollectionImpl.java:552)
	at com.mongodb.MongoCollectionImpl.insertMany(MongoCollectionImpl.java:524)
	at io.prestosql.plugin.mongodb.MongoPageSink.appendPage(MongoPageSink.java:115)
	at io.prestosql.operator.TableWriterOperator.addInput(TableWriterOperator.java:238)
	at io.prestosql.operator.Driver.processInternal(Driver.java:384)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
```

**Comment by ebyhr** [comment]
As far as I know, it is MongoDB driver's limitation. The approach we can take might be limited.
https://jira.mongodb.org/browse/JAVA-3452
https://jira.mongodb.org/browse/DOCS-12043

**Comment by academy-codex** [comment]
@findepi @ebyhr Shat do you guys think of an approach of replacing . with unicode equivalent and reverse mapping it while querying ?

**Comment by hashhar** [comment]
> @findepi @ebyhr What do you guys think of an approach of replacing . with unicode equivalent and reverse mapping it while querying ?

It's a workaround but it won't work in all cases. What if you have a field in MongoDB that leads to a collision after the name replacement? We might end up silently overwriting a field. Also, people generally don't expect unexpected and unobvious things to happen.

I agree with @ebyhr's approach of providing a better error message given that [MongoDB itself recommends against](https://docs.mongodb.com/manual/reference/limits/#mongodb-limit-Restrictions-on-Field-Names) using fields with `$` or `.` in their names.
