### ISSUE TITLE
Initialisation of Rubix cache fails on coordinator if cache directory is not present

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#3488]
Initialisation of Rubix cache fails on coordinator if cache directory is not present. This happens even if split scheduling is disabled for coordinator.

Snippet from logs:
```
2020-04-20T14:01:44.470Z        ERROR   pool-51-thread-1        com.qubole.rubix.bookkeeper.BookKeeperServer    Could not start BookKeeper daemon. Exception:
com.qubole.rubix.bookkeeper.exception.BookKeeperInitializationException: java.io.FileNotFoundException: None of the cache parent directories exists
        at com.qubole.rubix.bookkeeper.BookKeeper.setupCacheDirectory(BookKeeper.java:149)
        at com.qubole.rubix.bookkeeper.BookKeeper.<init>(BookKeeper.java:134)
        at com.qubole.rubix.bookkeeper.CoordinatorBookKeeper.<init>(CoordinatorBookKeeper.java:68)
        at com.qubole.rubix.bookkeeper.CoordinatorBookKeeper.<init>(CoordinatorBookKeeper.java:62)
        at com.qubole.rubix.bookkeeper.BookKeeperServer.setupServer(BookKeeperServer.java:119)
        at com.qubole.rubix.bookkeeper.BookKeeperServer.startServer(BookKeeperServer.java:89)
        at io.prestosql.plugin.hive.rubix.RubixInitializer.lambda$initializeRubix$2(RubixInitializer.java:97)
        at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:233)
        at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:223)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:110)
        at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:992)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.FileNotFoundException: None of the cache parent directories exists
        at com.qubole.rubix.spi.CacheUtil.createCacheDirectories(CacheUtil.java:77)
        at com.qubole.rubix.bookkeeper.BookKeeper.setupCacheDirectory(BookKeeper.java:146)
        ... 13 more
```

**Comment by tnatssb** [comment]
An easy solution to this is to create the /data directory on the coordinator in our AMI even though it won't be used. Of of course modify the Rubix code so it doesn't depend upon it.

**Comment by losipiuk** [comment]
@stagraqubole is Rubix expected to ever write something to caching directory on coordinator if splits scheduling for coordinator is disabled? Some metadata maybe? Or is it safe to not have cache directory at all?

**Comment by losipiuk** [comment]
It looks like currently Rubix itself will always require cache directory, no matter if it is on master or not. For now I propose a Presto only workaround. During Rubix initialization on coordinator, if `node-scheduler.include-coordinator=false` we check if directory configured as cache is present and accessible. If so we continue. If it does not exist we fallback to temporary directory. WDYT?

**Comment by stagraqubole** [comment]
Right, rubix expects cache location to be mounted on all nodes. The workaround lgtm.

Separately we can add this kind of mode natively in rubix where we add assertions if we ever break the assumption of cache usage in coordinator at runtime. We will need a rubix version upgrade once #3494 is fixed, i will try to make this change part of that release.

**Comment by losipiuk** [comment]
> Separately we can add this kind of mode natively in rubix where we add assertions if we ever break the assumption of cache usage in coordinator at runtime

Makes sense I will create an issue for that and send PR

**Comment by losipiuk** [comment]
> Right, rubix expects cache location to be mounted on all nodes. The workaround lgtm.
> 
> Separately we can add this kind of mode natively in rubix where we add assertions if we ever break the assumption of cache usage in coordinator at runtime. We will need a rubix version upgrade once #3494 is fixed, i will try to make this change part of that release.

@stagraqubole, https://github.com/qubole/rubix/pull/365 is an attempt to address that, though I am not sure if that is how it should look like. In that PR I initialize `Bookkeeper` with stubbed internal cache implementations, which would throw if someone tries to add anything to them.
But why do we need `Bookkeeper` at all on master node in such case. Is it needed for anything more than heartbits? Please comment on PR :)

**Comment by stagraqubole** [comment]
Yes, apart from heartbeat there is not other use of bookkeeper on master. Client/Presto will never talk to bookkeeper on master.

**Comment by tnatssb** [comment]
Would there ever be a scenario where data is written to the coordinator cache dir? I can't seem to reproduce it but I had an instance last week where that happened. If it's not possible, maybe I was imaging things...

**Comment by stagraqubole** [comment]
@tnatssb any chance `node-scheduler.include-coordinator=true` was set?

**Comment by tnatssb** [comment]
It was not. It was a standard CFT deployment. I’ll try to get time to test
again this week. It was strange for sure.
