### ISSUE TITLE
Flaky test TestHiveCaching.testReadFromCache

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#3822]
```
2020-05-22T14:47:16.7413117Z tests               | 2020-05-22 20:32:16 INFO: FAILURE     /    io.prestosql.tests.hive.TestHiveCaching.testReadFromCache (Groups: profile_specific_tests, hive_caching) took 41.8 seconds
2020-05-22T14:47:16.7462195Z presto-master       | 2020-05-22T20:32:16.745+0545	INFO	dispatcher-query-20	io.prestosql.event.QueryMonitor	TIMELINE: Query 20200522_144716_00317_u7g4y :: Transaction:[6f91725f-be05-4f9f-bd33-cbcf2d8c2bd6] :: elapsed 82ms :: planning 26ms :: waiting 0ms :: scheduling 7ms :: running 18ms :: finishing 31ms :: begin 2020-05-22T20:32:16.654+05:45 :: end 2020-05-22T20:32:16.736+05:45
2020-05-22T14:47:16.7489051Z tests               | 2020-05-22 20:32:16 SEVERE: Failure cause:
2020-05-22T14:47:16.7502015Z tests               | java.lang.AssertionError: expected [816] but found [818]
2020-05-22T14:47:16.7502561Z tests               | 	at org.testng.Assert.fail(Assert.java:94)
2020-05-22T14:47:16.7502723Z tests               | 	at org.testng.Assert.failNotEquals(Assert.java:513)
2020-05-22T14:47:16.7502890Z tests               | 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2020-05-22T14:47:16.7503033Z tests               | 	at org.testng.Assert.assertEquals(Assert.java:116)
2020-05-22T14:47:16.7503174Z tests               | 	at org.testng.Assert.assertEquals(Assert.java:284)
2020-05-22T14:47:16.7503294Z tests               | 	at org.testng.Assert.assertEquals(Assert.java:294)
2020-05-22T14:47:16.7503446Z tests               | 	at io.prestosql.tests.hive.TestHiveCaching.lambda$testReadFromTable$1(TestHiveCaching.java:82)
2020-05-22T14:47:16.7503797Z tests               | 	at io.prestosql.testing.assertions.Assert.assertEventually(Assert.java:58)
2020-05-22T14:47:16.7504281Z tests               | 	at io.prestosql.tests.hive.TestHiveCaching.testReadFromTable(TestHiveCaching.java:77)
2020-05-22T14:47:16.7504617Z tests               | 	at io.prestosql.tests.hive.TestHiveCaching.testReadFromCache(TestHiveCaching.java:42)
2020-05-22T14:47:16.7509746Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-05-22T14:47:16.7509928Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-05-22T14:47:16.7510083Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-05-22T14:47:16.7510226Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-05-22T14:47:16.7510355Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-05-22T14:47:16.7510494Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-05-22T14:47:16.7510625Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-05-22T14:47:16.7510757Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-05-22T14:47:16.7511120Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-05-22T14:47:16.7511418Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-05-22T14:47:16.7511560Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-05-22T14:47:16.7511882Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-05-22T14:47:16.7512014Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
```

cc @sopel39

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/699832988

**Comment by sopel39** [comment]
temp fix https://github.com/prestosql/presto/pull/3823

**Comment by sopel39** [comment]
Fixed via: https://github.com/prestosql/presto/pull/3823

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/2129979538

```
2021-03-17T11:59:36.3871758Z tests               | 2021-03-17 17:44:36 INFO: FAILURE     /    io.trino.tests.hive.TestHiveCaching.testReadFromCache (Groups: profile_specific_tests, hive_caching) took 59.5 seconds
2021-03-17T11:59:36.3891611Z tests               | 2021-03-17 17:44:36 SEVERE: Failure cause:
2021-03-17T11:59:36.3897126Z tests               | java.lang.AssertionError: expected [1104] but found [1105]
2021-03-17T11:59:36.3901082Z tests               | 	at org.testng.Assert.fail(Assert.java:94)
2021-03-17T11:59:36.3902635Z tests               | 	at org.testng.Assert.failNotEquals(Assert.java:513)
2021-03-17T11:59:36.3906836Z tests               | 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2021-03-17T11:59:36.3910717Z tests               | 	at org.testng.Assert.assertEquals(Assert.java:116)
2021-03-17T11:59:36.3915745Z tests               | 	at org.testng.Assert.assertEquals(Assert.java:284)
2021-03-17T11:59:36.3919265Z tests               | 	at org.testng.Assert.assertEquals(Assert.java:294)
2021-03-17T11:59:36.3921278Z tests               | 	at io.trino.tests.hive.TestHiveCaching.lambda$testReadFromTable$1(TestHiveCaching.java:90)
2021-03-17T11:59:36.3923720Z tests               | 	at io.trino.tests.utils.QueryAssertions.assertEventually(QueryAssertions.java:38)
2021-03-17T11:59:36.3928005Z tests               | 	at io.trino.tests.hive.TestHiveCaching.testReadFromTable(TestHiveCaching.java:76)
2021-03-17T11:59:36.3932153Z tests               | 	at io.trino.tests.hive.TestHiveCaching.testReadFromCache(TestHiveCaching.java:46)
```
