### ISSUE TITLE
Optimizer timeout error when querying Cassandra table with indexes

### ISSUE THREAD

**Issue by dekelev** [trinodb/trino#3894]
The following example will end up with query optimizer timeout error during Presto's query prepare phase:

```
create table test
(
    id uuid primary key,
    name text,
    "phonenumber" text
);

CREATE CUSTOM INDEX test_name_idx ON test (name) USING 'org.apache.cassandra.index.sasi.SASIIndex';

CREATE CUSTOM INDEX test_phone_idx ON test ("phonenumber") USING 'org.apache.cassandra.index.sasi.SASIIndex';

SELECT * FROM cassandra.default.test where name = 'Test' and phonenumber = '123';
```

Error Type | INTERNAL_ERROR
-- | --
Error Code | OPTIMIZER_TIMEOUT (65556)
Stack Trace | io.prestosql.spi.PrestoException: The optimizer exhausted the time limit of 180000 ms 	at io.prestosql.sql.planner.iterative.IterativeOptimizer$Context.checkTimeoutNotExhausted(IterativeOptimizer.java:291) 	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:129) 	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:105) 	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:190) 	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:107) 	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:190) 	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:107) 	at io.prestosql.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:96) 	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:198) 	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:187) 	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:182) 	at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:393) 	at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:381) 	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:336) 	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237) 	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132) 	at io.prestosql.$gen.Presto_334____20200601_081636_2.run(Unknown Source) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 	at java.base/java.lang.Thread.run(Thread.java:834)

There is no issue running this query in the CQL client.

The query will succeed when:
- Changing column name from `phonenumber` to `phoneNumber`
- Omitting one or both of the indexes

Presto v334
Cassandra v3.11.3
Mac OS Catalina v10.15.4

**Comment by losipiuk** [comment]
Thanks for the report. 

Is it a regression in 334 and used to work before. Not sure how familiar you are with Presto development, but If it is a regression, would it be possible for you to binary search the commit space and find the commit which introduced it?

**Comment by dekelev** [comment]
I'm not familiar with Presto development (yet). I do see the same behavior in Presto v333.

**Comment by ebyhr** [comment]
Confirmed this issue happens on version >= 304.

**Comment by dekelev** [comment]
Is there any plan to fix this regression?

This issue makes the the connector pretty useless to us in most cases.

**Comment by findepi** [comment]
> Confirmed this issue happens on version >= 304.

@ebyhr do you mean this did not happen in 303?

**Comment by ebyhr** [comment]
@findepi Sorry for my late response. Yes, it doesn't happen in 303.
