### ISSUE TITLE
Flaky test: hive.parquet.TestParquetReader.testComplexNestedStructs

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#4063]
See https://github.com/prestosql/presto/runs/778875407?check_suite_focus=true#step:5:22755 for the exact CI run.

Stack trace below:

```
2020-06-17T03:12:47.5908574Z [ERROR] testComplexNestedStructs(io.prestosql.plugin.hive.parquet.TestParquetReader)  Time elapsed: 0.015 s  <<< FAILURE!
2020-06-17T03:12:47.5948052Z java.lang.IllegalArgumentException: struct field values cannot be empty
2020-06-17T03:12:47.5948261Z 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
2020-06-17T03:12:47.5948646Z 	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.lambda$createTestStructs$7(AbstractTestParquetReader.java:1714)
2020-06-17T03:12:47.5948819Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
2020-06-17T03:12:47.5948977Z 	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.createTestStructs(AbstractTestParquetReader.java:1714)
2020-06-17T03:12:47.5949147Z 	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.createNullableTestStructs(AbstractTestParquetReader.java:1723)
2020-06-17T03:12:47.5949315Z 	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.testComplexNestedStructs(AbstractTestParquetReader.java:561)
2020-06-17T03:12:47.5949474Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-06-17T03:12:47.5949631Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-06-17T03:12:47.5949800Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-06-17T03:12:47.5949953Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-06-17T03:12:47.5950087Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-06-17T03:12:47.5950232Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-06-17T03:12:47.5950370Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-06-17T03:12:47.5950507Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-06-17T03:12:47.5950653Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-06-17T03:12:47.5950797Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-06-17T03:12:47.5950943Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-06-17T03:12:47.5951101Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-06-17T03:12:47.5951242Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by losipiuk** [comment]
It is reproducable with
```
    @Test(invocationCount = 5000)
    public void testComplexNestedStructs()
```
still requires a few runs though.

**Comment by losipiuk** [comment]
Sometimes it fails at different point:
```
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.lambda$createTestStructs$7(AbstractTestParquetReader.java:1714)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.createTestStructs(AbstractTestParquetReader.java:1714)
	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.createNullableTestStructs(AbstractTestParquetReader.java:1723)
	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.testComplexNestedStructs(AbstractTestParquetReader.java:585)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
```

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1524036509 

https://github.com/prestosql/presto/pull/6272 -- mark

**Comment by hashhar** [comment]
Fixed in https://github.com/trinodb/trino/pull/9349

**Comment by findepi** [comment]
I just reopened https://github.com/trinodb/trino/issues/2330, see https://github.com/trinodb/trino/issues/2330#issuecomment-1090052876
