### ISSUE TITLE
TestingPrestoClient cannot handle nested columns with hyphens

### ISSUE THREAD

**Issue by alexjo2144** [trinodb/trino#4073]
Using the memory connector, this works on the cli:
```
presto:default> create table foo (a varchar, root ROW (b boolean, "c-d" boolean));
presto:default> insert into foo VALUES ('a', ROW (true, false));
presto:default> SELECT * FROM foo;
 a |        root         
---+---------------------
 a | {b=true, c-d=false} 
(1 row)
```

But doing the same queries via a test's `QueryRunner` like in `TestMemorySmoke` causes an exn:
```
java.lang.AssertionError: Execution of 'actual' query failed: SELECT * FROM foo

	at org.testng.Assert.fail(Assert.java:83)
	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at io.prestosql.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:130)
	at io.prestosql.plugin.memory.TestMemorySmoke.testNestedColumnWithHyphens(TestMemorySmoke.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: io.prestosql.sql.parser.ParsingException: line 1:16: mismatched input '-'. Expecting: ')', ','
	at io.prestosql.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:108)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:377)
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:275)
	at io.prestosql.sql.parser.SqlBaseParser.type(SqlBaseParser.java:10134)
	at io.prestosql.sql.parser.SqlBaseParser.standaloneType(SqlBaseParser.java:386)
	at io.prestosql.sql.parser.SqlParser.invokeParser(SqlParser.java:156)
	at io.prestosql.sql.parser.SqlParser.createType(SqlParser.java:105)
	at io.prestosql.metadata.TypeRegistry.fromSqlType(TypeRegistry.java:164)
	at io.prestosql.metadata.MetadataManager.fromSqlType(MetadataManager.java:1379)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.prestosql.testing.AbstractTestingPrestoClient.getTypes(AbstractTestingPrestoClient.java:198)
	at io.prestosql.testing.TestingPrestoClient$MaterializedResultSession.addResults(TestingPrestoClient.java:131)
	at io.prestosql.testing.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:90)
	at io.prestosql.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:443)
	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 27 more
```

**Comment by hashhar** [comment]
There are lots of other things TestingTrinoClient cannot handle. e.g. ROW types.

Closing since in general for `TestingTrinoClient` we implement missing functionality when it's needed and not proactively.

Feel free to re-open if there's a specific case where you need it (and plan to implement it).
