### ISSUE TITLE
Flaky test TestQuerySerializationFailures.shouldFailOnFirstSerializationError

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#4173]
https://github.com/prestosql/presto/runs/788200669

```
020-06-19T14:19:45.8412263Z [ERROR] shouldFailOnFirstSerializationError(io.prestosql.tests.TestQuerySerializationFailures)  Time elapsed: 0.22 s  <<< FAILURE!
2020-06-19T14:19:45.8415562Z java.lang.AssertionError: Expected query to fail: SELECT * FROM (VALUES BOGUS(true), BOGUS(false), BOGUS(true))
2020-06-19T14:19:45.8417300Z 	at org.testng.Assert.fail(Assert.java:94)
2020-06-19T14:19:45.8419920Z 	at io.prestosql.testing.QueryAssertions.assertQueryFails(QueryAssertions.java:291)
2020-06-19T14:19:45.8422956Z 	at io.prestosql.testing.AbstractTestQueryFramework.assertQueryFails(AbstractTestQueryFramework.java:221)
2020-06-19T14:19:45.8426566Z 	at io.prestosql.tests.TestQuerySerializationFailures.shouldFailOnFirstSerializationError(TestQuerySerializationFailures.java:54)
2020-06-19T14:19:45.8429047Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-06-19T14:19:45.8432062Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-06-19T14:19:45.8435191Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-06-19T14:19:45.8437240Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-06-19T14:19:45.8440086Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-06-19T14:19:45.8442105Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-06-19T14:19:45.8444297Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-06-19T14:19:45.8446545Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-06-19T14:19:45.8449053Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-06-19T14:19:45.8451394Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-06-19T14:19:45.8454162Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-06-19T14:19:45.8457927Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-06-19T14:19:45.8459537Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
cc @wendigo

**Comment by wendigo** [comment]
There is a possibility I described in one of the comments on the original PR that there can be a race condition between marking query as FINISHED and failing it (we disallow transition from FINISHED to FAILED). I'll investigate how can this be mitigated.

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1130384768

**Comment by electrum** [comment]
https://github.com/prestosql/presto/runs/1188836626

**Comment by sopel39** [comment]
https://github.com/prestosql/presto/pull/2674/checks?check_run_id=1353869319

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1406595247
