### ISSUE TITLE
Flaky TestRaptorIntegrationSmokeTestBucketed

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#4357]
```
2020-07-06T13:39:11.4822447Z java.lang.RuntimeException: java.io.UncheckedIOException: java.nio.file.FileSystemException: /tmp/PrestoTest4106246762023028228: failed to delete one or more files; see suppressed exceptions for details
2020-07-06T13:39:11.4827614Z 	at io.airlift.testing.Closeables.closeAllRuntimeException(Closeables.java:87)
2020-07-06T13:39:11.4833508Z 	at io.prestosql.testing.AbstractTestQueryFramework.close(AbstractTestQueryFramework.java:87)
2020-07-06T13:39:11.4839132Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-06T13:39:11.4845466Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-06T13:39:11.4909582Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-06T13:39:11.4914647Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-07-06T13:39:11.4967262Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-07-06T13:39:11.4973250Z 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
2020-07-06T13:39:11.4978308Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
2020-07-06T13:39:11.4984092Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
2020-07-06T13:39:11.4990484Z 	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
2020-07-06T13:39:11.4995502Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
2020-07-06T13:39:11.5002167Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-07-06T13:39:11.5008470Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-07-06T13:39:11.5012140Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-06T13:39:11.5023262Z Caused by: java.io.UncheckedIOException: java.nio.file.FileSystemException: /tmp/PrestoTest4106246762023028228: failed to delete one or more files; see suppressed exceptions for details
2020-07-06T13:39:11.5030924Z 	at io.prestosql.testing.DistributedQueryRunner.close(DistributedQueryRunner.java:495)
2020-07-06T13:39:11.5036067Z 	at io.airlift.testing.Closeables.closeAllRuntimeException(Closeables.java:82)
2020-07-06T13:39:11.5037940Z 	... 14 more
2020-07-06T13:39:11.5047294Z Caused by: java.nio.file.FileSystemException: /tmp/PrestoTest4106246762023028228: failed to delete one or more files; see suppressed exceptions for details
2020-07-06T13:39:11.5052060Z 	at com.google.common.io.MoreFiles.throwDeleteFailed(MoreFiles.java:786)
2020-07-06T13:39:11.5056800Z 	at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:552)
2020-07-06T13:39:11.5062802Z 	at io.prestosql.server.testing.TestingPrestoServer.lambda$close$3(TestingPrestoServer.java:335)
2020-07-06T13:39:11.5066629Z 	at com.google.common.io.Closer.close(Closer.java:213)
2020-07-06T13:39:11.5072142Z 	at io.prestosql.server.testing.TestingPrestoServer.close(TestingPrestoServer.java:344)
2020-07-06T13:39:11.5075948Z 	at com.google.common.io.Closer.close(Closer.java:213)
2020-07-06T13:39:11.5082912Z 	at io.prestosql.testing.DistributedQueryRunner.close(DistributedQueryRunner.java:492)
2020-07-06T13:39:11.5084626Z 	... 15 more
2020-07-06T13:39:11.5088373Z 	Suppressed: java.nio.file.DirectoryNotEmptyException
2020-07-06T13:39:11.5094506Z 		at java.base/sun.nio.fs.UnixSecureDirectoryStream.implDelete(UnixSecureDirectoryStream.java:204)
2020-07-06T13:39:11.5100847Z 		at java.base/sun.nio.fs.UnixSecureDirectoryStream.deleteDirectory(UnixSecureDirectoryStream.java:221)
2020-07-06T13:39:11.5107295Z 		at java.base/sun.nio.fs.UnixSecureDirectoryStream.deleteDirectory(UnixSecureDirectoryStream.java:42)
2020-07-06T13:39:11.5112495Z 		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:627)
2020-07-06T13:39:11.5118189Z 		at com.google.common.io.MoreFiles.deleteDirectoryContentsSecure(MoreFiles.java:648)
2020-07-06T13:39:11.5123488Z 		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:621)
2020-07-06T13:39:11.5129653Z 		at com.google.common.io.MoreFiles.deleteDirectoryContentsSecure(MoreFiles.java:648)
2020-07-06T13:39:11.5135164Z 		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:621)
2020-07-06T13:39:11.5140354Z 		at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:535)
2020-07-06T13:39:11.5142063Z 		... 20 more
2020-07-06T13:39:11.5143213Z 
2020-07-06T13:39:11.5243076Z 2020-07-06T08:39:11.523-0500 INFO JVM is shutting down, cleaning up
2020-07-06T13:39:11.5248236Z 2020-07-06T08:39:11.524-0500 INFO Life cycle stopping...
2020-07-06T13:39:11.5254577Z 2020-07-06T08:39:11.525-0500 INFO Life cycle stopped
2020-07-06T13:39:14.7094497Z [INFO] 
2020-07-06T13:39:14.7095275Z [INFO] Results:
2020-07-06T13:39:14.7095622Z [INFO] 
2020-07-06T13:39:14.7095944Z [ERROR] Failures: 
2020-07-06T13:39:14.7096928Z [ERROR]   TestRaptorIntegrationSmokeTestBucketed>AbstractTestQueryFramework.close:87 » Runtime
```

**Comment by wendigo** [comment]
https://github.com/prestosql/presto/pull/4355/checks?check_run_id=841485559
