### ISSUE TITLE
Select in information_schema.tables for Google sheet Connector throws error

### ISSUE THREAD

**Issue by Cabeda** [trinodb/trino#4375]
Running on version 329 and when trying to run the following query on a google sheet connector,
```sql
SELECT * FROM "googlesheet-bi".information_schema.tables
```

it throws the following error:

```
 Query failed (#20200707_155858_00120_ses95): Schema not present - Optional.empty
```

The stack trace is the following:

```java.lang.IllegalStateException: Query already begun: Optional[20200707_155425_00082_ses95] while starting query 20200707_155425_00082_ses95
	at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.beginQuery(SemiTransactionalHiveMetastore.java:989)
	at io.prestosql.plugin.hive.HiveMetadata.beginQuery(HiveMetadata.java:2336)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.beginQuery(ClassLoaderSafeConnectorMetadata.java:373)
	at io.prestosql.metadata.MetadataManager$QueryCatalogs.registerCatalog(MetadataManager.java:1577)
	at io.prestosql.metadata.MetadataManager$QueryCatalogs.access$100(MetadataManager.java:1559)
	at io.prestosql.metadata.MetadataManager.registerCatalogForQuery(MetadataManager.java:1550)
	at io.prestosql.metadata.MetadataManager.lambda$getOptionalCatalogMetadata$20(MetadataManager.java:1512)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.prestosql.metadata.MetadataManager.getOptionalCatalogMetadata(MetadataManager.java:1512)
	at io.prestosql.metadata.MetadataManager.listTables(MetadataManager.java:534)
	at io.prestosql.metadata.MetadataListing.listTables(MetadataListing.java:64)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.addTablesRecords(InformationSchemaPageSource.java:271)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:213)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:176)
	at io.prestosql.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:362)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.access$000(WorkProcessorUtils.java:37)
	at io.prestosql.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:148)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_329____20200706_225847_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by findepi** [comment]
Google Sheets connector does not implement `AbstractTestIntegrationSmokeTest` yet.
This should have covered the issue.

cc @puneetjaiswal

**Comment by ebyhr** [comment]
I can list `information_schema.tables` in  Google Sheets connector and the provided stacktrace comes from Hive connector. I would recommend filing a new issue with the latest stacktrace if it's still reproducible.
