### ISSUE TITLE
Column type to string for CSV tables on Glue metastore 

### ISSUE THREAD

**Issue by yunrougong** [trinodb/trino#4531]
Following up on #4457, the PR improvement is Hive metastore specific.
Can we make the same improvement (OpenCSVSerde deserializes columns into strings only) on the AWS Glue Data catalog?

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
at io.prestosql.plugin.hive.GenericHiveRecordCursor.parseBooleanColumn(GenericHiveRecordCursor.java:254)
at io.prestosql.plugin.hive.GenericHiveRecordCursor.parseColumn(GenericHiveRecordCursor.java:474)
at io.prestosql.plugin.hive.GenericHiveRecordCursor.isNull(GenericHiveRecordCursor.java:465)
at io.prestosql.plugin.hive.HiveRecordCursor.isNull(HiveRecordCursor.java:239)
at io.prestosql.spi.connector.RecordPageSource.getNextPage(RecordPageSource.java:96)
at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:301)
at io.prestosql.operator.Driver.processInternal(Driver.java:379)
at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
at io.prestosql.operator.Driver.processFor(Driver.java:276)
at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
at io.prestosql.$gen.Presto_339____20200722_033558_2.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by vjtadepalli** [comment]
Hi, I would like to work on this, How do I get started?

**Comment by wendigo** [comment]
Hi @vjtadepalli. You can start here: https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/converter/GlueToPrestoConverter.java#L66

**Comment by vjtadepalli** [comment]
Thanks, below is my observation.

private static Column convertColumn(com.amazonaws.services.glue.model.Column glueColumn)
    {
        return new Column(glueColumn.getName(), HiveType.valueOf(glueColumn.getType().toLowerCase(Locale.ENGLISH)), Optional.ofNullable(glueColumn.getComment()));
    }

should be changed to:

private static Column convertColumn(com.amazonaws.services.glue.model.Column glueColumn)
    {
        return new Column(glueColumn.getName(), HiveType. HIVE_STRING, Optional.ofNullable(glueColumn.getComment()));
    }

**Comment by wendigo** [comment]
@vjtadepalli yeah, but only if table serde is opencsv

**Comment by vjtadepalli** [comment]
@wendigo 

Here is the proposed change to convertColumn method. If you are ok with it, I will raise PR after adding unit tests also.

private static Column convertColumn(com.amazonaws.services.glue.model.Column glueColumn, StorageDescriptor storageDescriptor)
{
    if(storageDescriptor.getSerdeInfo().getName() != null &&
            ! ((storageDescriptor.getSerdeInfo().getName().contains("csv")) ||
                    (storageDescriptor.getSerdeInfo().getName().contains("CSV")))) {
        return new Column(glueColumn.getName(), HiveType.valueOf(glueColumn.getType().toLowerCase(Locale.ENGLISH)), Optional.ofNullable(glueColumn.getComment()));}
    else{
        return new Column(glueColumn.getName(), HiveType. HIVE_STRING, Optional.ofNullable(glueColumn.getComment()));
    }
}

**Comment by wendigo** [comment]
@vjtadepalli Please open PR - I will review it and you can continue working on that :)

**Comment by findepi** [comment]
@vjtadepalli are you working on this?

**Comment by abhisheksp** [comment]
I can work on this if the issue is available

**Comment by findepi** [comment]
Steps to reproduce:

1. spin up 1-node EMR cluster connected to Glue metastore
2. in EMR Hive, define a CSV table (`STORED AS CSV`) with some column types other than varchar, e.g. integer, bigint, double
3. run Presto connected to Glue metastore -- doesn't have to be on EMR, can be local development instance
4. query the new table from Presto

**Comment by rshramz** [comment]
I see this issue is still open. Can i pick this up. Will drive it closure asap.

**Comment by findepi** [comment]
There is a PR from @vjtadepalli: https://github.com/trinodb/trino/pull/4603
@vjtadepalli are you planning to work on this? Otherwise @rshramz you can draw inspiration from it and add necessary tests that were missing from there.

**Comment by rshramz** [comment]
created a pr for this issue: https://github.com/trinodb/trino/pull/7059
