### ISSUE TITLE
CREATE TABLE leaves /tmp/presto-{USER}/xxx

### ISSUE THREAD

**Issue by byungnam** [trinodb/trino#4868]
## Problem
While using Presto, I found 1 million of `/tmp/presto-{USER}/xxx` directories and my Hadoop namenode is complaining about it: `The directory item limit of /tmp/presto-**** is exceeded`. 

It seems something went wrong and the directory is not cleaned up.

## Presto version
331

## How to reproduce
Actually, no idea.

Not sure but we have many Presto query failures in some circumstances including when upgrading and restarting Presto, Hive fails to write HDFS (due to heavy IO), Presto worker fails (OOM is observed). So that could be a reason maybe?

ref: [Slack thread link](https://prestosql.slack.com/archives/CGB0QHWSW/p1597383256408900)

**Comment by byungnam** [comment]
I found the cause of this behavior. It's still happening from Trino 355.

How to reproduce:
1. Call `call system.create_empty_partition()`
2. Above call fails (due to partition already exists)

Example:
Call this
```
call system.create_empty_partition(schema_name => 'toros_analysis', table_name => 'o_aurochs_feedback_log', partition_columns => ARRAY['date_hour'], partition_values => ARRAY['2021091610'])
```
and fails with
```
io.trino.spi.TrinoException: Partition already exists
	at io.trino.plugin.hive.procedure.CreateEmptyPartitionProcedure.doCreateEmptyPartition(CreateEmptyPartitionProcedure.java:125)
	at io.trino.plugin.hive.procedure.CreateEmptyPartitionProcedure.createEmptyPartition(CreateEmptyPartitionProcedure.java:102)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:735)
	at io.trino.execution.CallTask.execute(CallTask.java:194)
	at io.trino.execution.CallTask.execute(CallTask.java:67)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:170)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_355_kakao____20210906_064002_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
then the /tmp/presto-{USER} directory is created but not removed.

**Comment by byungnam** [comment]
Dang. I was a bit in haste and found there were several other queries ran in same time with `call create_empty_partition`.  I re-tested in a clean environment and confirmed the problem was not `call create_empty_partition` but was `CREATE TABLE` statement.

Reproduce steps are simple:
- Run any `CREATE TABLE` statement 
- Then you get one additional /tmp/presto-{USER} directory

Tested statements:
- CREATE TABLE test001 (col1 varchar);
- CREATE TABLE test002 (col1 varchar) WITH (format='TEXTFILE');
- CREATE TABLE test003 (col1 varchar, col2 int) WITH (format = 'TEXTFILE');
- CREATE TABLE IF NOT EXISTS test004 (col1 varchar, col2 int) WITH (format = 'ORC');

**Comment by byungnam** [comment]
fixed by: https://github.com/trinodb/trino/pull/14830
