### ISSUE TITLE
TestHiveTransactionalTable.testReadFullAcidBucketed is flaky: "Hive table is is corrupt. Found sub-directory in bucket directory for partition"

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#4927]
```
io.prestosql.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20200821_135435_00036_5scqv): Hive table 'default.test_read_full_acid_false_bucketed_default_u6jtzs06bwif' is corrupt. Found sub-directory in bucket directory for partition: <UNPARTITIONED>
	at io.prestosql.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:114)
	at io.prestosql.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:82)
	at io.prestosql.tempto.query.QueryExecutor.query(QueryExecutor.java:57)
	at io.prestosql.tests.hive.TestHiveTransactionalTable.doTestReadFullAcid(TestHiveTransactionalTable.java:131)
	at io.prestosql.tests.hive.TestHiveTransactionalTable.testReadFullAcidBucketed(TestHiveTransactionalTable.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.SQLException: Query failed (#20200821_135435_00036_5scqv): Hive table 'default.test_read_full_acid_false_bucketed_default_u6jtzs06bwif' is corrupt. Found sub-directory in bucket directory for partition: <UNPARTITIONED>
	at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1757)
	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:225)
	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:185)
	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at io.prestosql.jdbc.PrestoResultSet$AsyncIterator.lambda$new$0(PrestoResultSet.java:131)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	... 3 more
Caused by: io.prestosql.spi.PrestoException: Hive table 'default.test_read_full_acid_false_bucketed_default_u6jtzs06bwif' is corrupt. Found sub-directory in bucket directory for partition: <UNPARTITIONED>
	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:519)
	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:303)
	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:232)
	at io.prestosql.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
	at io.prestosql.$gen.Presto_005021c____20200821_135006_2.run(Unknown Source)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
Same applies to `TestHiveTransactionalTable > testReadFullAcidBucketedV2`, so i assume `testReadFullAcidBucketedV1` may be affected too.

**Comment by findepi** [comment]
btw i think this flakiness is a regression, or an environmental change. I am seeing this every day now (at random) and I don't recall seeing it earlier than "recently" (past weeks?).

IMO we should try bisecting this.

**Comment by findepi** [comment]
I run `TestHiveTransactionalTable#testReadFullAcidBucketed` 100 times locally (in sequence), on singlenode-hdp3 environment.
All runs passed. Took about 2h 20'.

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/runs/1194570748

```
2020-10-01T18:43:24.6286718Z tests               | 2020-10-02 00:28:24 INFO: FAILURE     /    io.prestosql.tests.hive.TestHiveTransactionalTable.testReadFullAcidPartitionedBucketed (Groups: storage_formats, hive_transactional) took 3 minutes and 49 seconds
2020-10-01T18:43:24.6312036Z tests               | 2020-10-02 00:28:24 SEVERE: Failure cause:
2020-10-01T18:43:24.6409594Z tests               | io.prestosql.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20201001_184323_01004_i6htf): Hive table 'default.test_read_full_acid_true_bucketed_default_3rwyywd4bk0t' is corrupt. Found sub-directory 'hdfs://hadoop-master:9000/user/hive/warehouse/test_read_full_acid_true_bucketed_default_3rwyywd4bk0t/part_col=2/delta_0000002_0000005/delta_0000002_0000005' in bucket directory for partition: part_col=2
2020-10-01T18:43:24.6412927Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:114)
2020-10-01T18:43:24.6415513Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:82)
2020-10-01T18:43:24.6417921Z tests               | 	at io.prestosql.tempto.query.QueryExecutor.query(QueryExecutor.java:57)
2020-10-01T18:43:24.6420205Z tests               | 	at io.prestosql.tests.hive.TestHiveTransactionalTable.doTestReadFullAcid(TestHiveTransactionalTable.java:142)
2020-10-01T18:43:24.6423878Z tests               | 	at io.prestosql.tests.hive.TestHiveTransactionalTable.testReadFullAcidPartitionedBucketed(TestHiveTransactionalTable.java:87)
2020-10-01T18:43:24.6426977Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-10-01T18:43:24.6428958Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-10-01T18:43:24.6431303Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-10-01T18:43:24.6433019Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-10-01T18:43:24.6434619Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-10-01T18:43:24.6436595Z tests               | 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-10-01T18:43:24.6438063Z tests               | 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-10-01T18:43:24.6439315Z tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-10-01T18:43:24.6440338Z tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-10-01T18:43:24.6441808Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-10-01T18:43:24.6444319Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-10-01T18:43:24.6445509Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-10-01T18:43:24.6451776Z tests               | Caused by: java.sql.SQLException: Query failed (#20201001_184323_01004_i6htf): Hive table 'default.test_read_full_acid_true_bucketed_default_3rwyywd4bk0t' is corrupt. Found sub-directory 'hdfs://hadoop-master:9000/user/hive/warehouse/test_read_full_acid_true_bucketed_default_3rwyywd4bk0t/part_col=2/delta_0000002_0000005/delta_0000002_0000005' in bucket directory for partition: part_col=2
2020-10-01T18:43:24.6454847Z tests               | 	at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1761)
2020-10-01T18:43:24.6457170Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:228)
2020-10-01T18:43:24.6459068Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:188)
2020-10-01T18:43:24.6461414Z tests               | 	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2020-10-01T18:43:24.6463854Z tests               | 	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2020-10-01T18:43:24.6466086Z tests               | 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
2020-10-01T18:43:24.6468098Z tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
2020-10-01T18:43:24.6470544Z tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
2020-10-01T18:43:24.6473003Z tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
2020-10-01T18:43:24.6475568Z tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
2020-10-01T18:43:24.6477204Z tests               | 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
2020-10-01T18:43:24.6478574Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$AsyncIterator.lambda$new$0(PrestoResultSet.java:134)
2020-10-01T18:43:24.6480309Z tests               | 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
2020-10-01T18:43:24.6481267Z tests               | 	... 3 more
2020-10-01T18:43:24.6488586Z tests               | Caused by: io.prestosql.spi.PrestoException: Hive table 'default.test_read_full_acid_true_bucketed_default_3rwyywd4bk0t' is corrupt. Found sub-directory 'hdfs://hadoop-master:9000/user/hive/warehouse/test_read_full_acid_true_bucketed_default_3rwyywd4bk0t/part_col=2/delta_0000002_0000005/delta_0000002_0000005' in bucket directory for partition: part_col=2
2020-10-01T18:43:24.6491543Z tests               | 	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:537)
2020-10-01T18:43:24.6494479Z tests               | 	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:321)
2020-10-01T18:43:24.6497245Z tests               | 	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:250)
2020-10-01T18:43:24.6499530Z tests               | 	at io.prestosql.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
2020-10-01T18:43:24.6500513Z tests               | 	at io.prestosql.$gen.Presto_9d52209____20201001_182700_2.run(Unknown Source)
2020-10-01T18:43:24.6501585Z tests               | 	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
2020-10-01T18:43:24.6503597Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-10-01T18:43:24.6545383Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-10-01T18:43:24.6546688Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/issues/8920 seems to describe potential mechanics of the problem

**Comment by findepi** [comment]
Closing in favor of https://github.com/trinodb/trino/issues/16315
