### ISSUE TITLE
TestMemoryManager.testResourceOverCommit is flaky

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#4948]
```
2020-08-21T13:57:31.7192504Z [ERROR] testResourceOverCommit(io.prestosql.memory.TestMemoryManager)  Time elapsed: 7.825 s  <<< FAILURE!
2020-08-21T13:57:31.7203351Z java.lang.RuntimeException: Query exceeded per-node total memory limit of 1kB [Allocated: 1.83kB, Delta: 340B, Top Consumers: {PartitionedOutputOperator=1.83kB}]
2020-08-21T13:57:31.7210574Z 	at io.prestosql.testing.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:114)
2020-08-21T13:57:31.7216861Z 	at io.prestosql.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:442)
2020-08-21T13:57:31.7223292Z 	at io.prestosql.memory.TestMemoryManager.testResourceOverCommit(TestMemoryManager.java:107)
2020-08-21T13:57:31.7229168Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-08-21T13:57:31.7236062Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-08-21T13:57:31.7243434Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-08-21T13:57:31.7248424Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-08-21T13:57:31.7254993Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-08-21T13:57:31.7260848Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-08-21T13:57:31.7266486Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-08-21T13:57:31.7272487Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-08-21T13:57:31.7277931Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-08-21T13:57:31.7284846Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-08-21T13:57:31.7292641Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-08-21T13:57:31.7296757Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-21T13:57:31.7309038Z Caused by: io.prestosql.ExceededMemoryLimitException: Query exceeded per-node total memory limit of 1kB [Allocated: 1.83kB, Delta: 340B, Top Consumers: {PartitionedOutputOperator=1.83kB}]
2020-08-21T13:57:31.7339897Z 	at io.prestosql.ExceededMemoryLimitException.exceededLocalTotalMemoryLimit(ExceededMemoryLimitException.java:46)
2020-08-21T13:57:31.7346215Z 	at io.prestosql.memory.QueryContext.enforceTotalMemoryLimit(QueryContext.java:340)
2020-08-21T13:57:31.7351952Z 	at io.prestosql.memory.QueryContext.updateSystemMemory(QueryContext.java:175)
2020-08-21T13:57:31.7359105Z 	at io.prestosql.memory.QueryContext$QueryMemoryReservationHandler.reserveMemory(QueryContext.java:313)
2020-08-21T13:57:31.7366760Z 	at io.prestosql.memory.context.RootAggregatedMemoryContext.updateBytes(RootAggregatedMemoryContext.java:37)
2020-08-21T13:57:31.7374246Z 	at io.prestosql.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
2020-08-21T13:57:31.7381729Z 	at io.prestosql.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
2020-08-21T13:57:31.7396954Z 	at io.prestosql.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
2020-08-21T13:57:31.7404838Z 	at io.prestosql.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
2020-08-21T13:57:31.7411744Z 	at io.prestosql.memory.context.SimpleLocalMemoryContext.setBytes(SimpleLocalMemoryContext.java:66)
2020-08-21T13:57:31.7418848Z 	at io.prestosql.operator.OperatorContext$InternalLocalMemoryContext.setBytes(OperatorContext.java:671)
2020-08-21T13:57:31.7427796Z 	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.lambda$processColumnSource$0(ScanFilterAndProjectOperator.java:272)
2020-08-21T13:57:31.7434990Z 	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:201)
2020-08-21T13:57:31.7442088Z 	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2020-08-21T13:57:31.7448673Z 	at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
2020-08-21T13:57:31.7454632Z 	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
2020-08-21T13:57:31.7461643Z 	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2020-08-21T13:57:31.7467607Z 	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
2020-08-21T13:57:31.7475517Z 	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2020-08-21T13:57:31.7481715Z 	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
2020-08-21T13:57:31.7489199Z 	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
2020-08-21T13:57:31.7496286Z 	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2020-08-21T13:57:31.7502549Z 	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
2020-08-21T13:57:31.7509123Z 	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
2020-08-21T13:57:31.7516199Z 	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2020-08-21T13:57:31.7523957Z 	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:149)
2020-08-21T13:57:31.7529023Z 	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
2020-08-21T13:57:31.7534424Z 	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
2020-08-21T13:57:31.7539104Z 	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
2020-08-21T13:57:31.7543731Z 	at io.prestosql.operator.Driver.processFor(Driver.java:276)
2020-08-21T13:57:31.7550928Z 	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
2020-08-21T13:57:31.7557780Z 	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
2020-08-21T13:57:31.7563918Z 	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
2020-08-21T13:57:31.7571578Z 	at io.prestosql.$gen.Presto_testversion____20200821_135340_18206.run(Unknown Source)
2020-08-21T13:57:31.7578151Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-08-21T13:57:31.7584675Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-08-21T13:57:31.7588817Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-21T13:57:31.7589986Z 
```

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1325585545

**Comment by findepi** [comment]
The failure is reproducible locally with `@Test(invocationCount = 1000)`.
I got 4 failures in first 150 iterations (210s).
