### ISSUE TITLE
Flay build:  Unexpected EOF in archive

### ISSUE THREAD

**Issue by iirekm** [trinodb/trino#5033]
They are unrelated to changes made, rebase didn't help:

https://github.com/prestosql/presto/pull/4872/checks

**Comment by iirekm** [comment]
More details (just in case GHA results become deleted):

https://github.com/prestosql/presto/pull/4872/checks?check_run_id=1050650449 :
```
2020-08-31T06:50:49.202-0500 WARNING Failed to rewrite TEST_QUERY for shadowing. Skipping.
java.sql.SQLException: No suitable driver found for invalid:url
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at io.prestosql.verifier.QueryRewriter.shadowQuery(QueryRewriter.java:108)
	at io.prestosql.verifier.VerifyCommand.lambda$rewriteQueries$2(VerifyCommand.java:279)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

https://github.com/prestosql/presto/pull/4872/checks?check_run_id=1050650444 :
```
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/temp_1169863014 -f /home/runner/work/_temp/0d630228-9318-4b12-ae39-a48eda1b65ca

gzip: stdin: unexpected end of file
/bin/tar: Unexpected EOF in archive
/bin/tar: Unexpected EOF in archive
/bin/tar: Error is not recoverable: exiting now
##[error]The process '/bin/tar' failed with exit code 2
```

**Comment by ssheikin** [comment]
```
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/temp_1541730422 -f /home/runner/work/_temp/5d973049-8f2c-43f8-88f5-50f1667239af

gzip: stdin: unexpected end of file
/usr/bin/tar: Unexpected EOF in archive
/usr/bin/tar: Unexpected EOF in archive
/usr/bin/tar: Error is not recoverable: exiting now
Error: The process '/usr/bin/tar' failed with exit code 2
```
noticed here: https://github.com/trinodb/trino/pull/8108/checks?check_run_id=2709868896

**Comment by kokosing** [comment]
Replaced with https://github.com/trinodb/trino/issues/8146
