### ISSUE TITLE
Wrong exception when calling ResultSet.getTimestamp on TIME value

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#5315]
```
java.lang.IllegalArgumentException: Expected column to be a timestamp type but is time(3)
	at io.prestosql.jdbc.AbstractPrestoResultSet.getTimestamp(AbstractPrestoResultSet.java:362)
	at io.prestosql.jdbc.AbstractPrestoResultSet.getTimestamp(AbstractPrestoResultSet.java:327)
	at io.prestosql.jdbc.PrestoResultSet.getTimestamp(PrestoResultSet.java:44)
```

should be `SQLException`

**Comment by rafatmunshi** [comment]
I would like to work on this. You just need the type of exception changed right?

**Comment by findepi** [comment]
Hm... looking at the javadoc for `java.sql.ResultSet#getTimestamp(int)` again. 
The javadoc does not mandate use of SQLException in this case.
@rafatmunshi would you be able to check what's eg PostgreSQL's and Oracle's JDBC behavior here?

**Comment by rafatmunshi** [comment]
Hi, checked Oracle and Postgres JDBC docs. Both mention throws SQLException. Logically also I believe it should throw SQLException only as you suggested @findepi .  So I think we just need to change the Exception type in the file and do the relevant change in the tests. Hope I am not missing something?

**Comment by findepi** [comment]
@jetsasank recently did similar improvement for `getDate`, @rafatmunshi please check this out: https://github.com/prestosql/presto/pull/5510

**Comment by rafatmunshi** [comment]
Checked it. Clarifies my earlier query. Will send a PR soon. Thanks!

**Comment by somayaj** [comment]
hi, is this available for a commit?

**Comment by rafatmunshi** [comment]
Hi @somayaj , I am working on a PR linked to this now. Thanks

**Comment by keyuyan1145** [comment]
Hi @findepi . Is this issue addressed?
