### ISSUE TITLE
Crashed tests in presto-hive

### ISSUE THREAD

**Issue by phd3** [trinodb/trino#5527]
Tests on PR #4680 failed with the following errors:

```
2020-10-09T16:06:11.5123896Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project presto-hive: There are test failures.
2020-10-09T16:06:11.5125055Z [ERROR] 
2020-10-09T16:06:11.5126379Z [ERROR] Please refer to /home/runner/work/presto/presto/presto-hive/target/surefire-reports for the individual test results.
2020-10-09T16:06:11.5128033Z [ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
2020-10-09T16:06:11.5137459Z [ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
2020-10-09T16:06:11.5150886Z [ERROR] Command was /bin/sh -c cd /home/runner/work/presto/presto/presto-hive && /opt/hostedtoolcache/jdk/11.0.8/x64/bin/java -Dfile.encoding=UTF-8 -Xmx3g -Xms3g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -jar /home/runner/work/presto/presto/presto-hive/target/surefire/surefirebooter8080345497120439857.jar /home/runner/work/presto/presto/presto-hive/target/surefire 2020-10-09T15-34-03_644-jvmRun1 surefire17131638368935347303tmp surefire_16991763481603338326tmp
2020-10-09T16:06:11.5154861Z [ERROR] Error occurred in starting fork, check output in log
2020-10-09T16:06:11.5156588Z [ERROR] Process Exit Code: 3
2020-10-09T16:06:11.5158189Z [ERROR] Crashed tests:
2020-10-09T16:06:11.5160503Z [ERROR] io.prestosql.plugin.hive.TestHiveIntegrationSmokeTest
2020-10-09T16:06:11.5163377Z [ERROR] io.prestosql.plugin.hive.rubix.TestRubixCaching
2020-10-09T16:06:11.5167017Z [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
2020-10-09T16:06:11.5172864Z [ERROR] Command was /bin/sh -c cd /home/runner/work/presto/presto/presto-hive && /opt/hostedtoolcache/jdk/11.0.8/x64/bin/java -Dfile.encoding=UTF-8 -Xmx3g -Xms3g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -jar /home/runner/work/presto/presto/presto-hive/target/surefire/surefirebooter8080345497120439857.jar /home/runner/work/presto/presto/presto-hive/target/surefire 2020-10-09T15-34-03_644-jvmRun1 surefire17131638368935347303tmp surefire_16991763481603338326tmp
2020-10-09T16:06:11.5182074Z [ERROR] Error occurred in starting fork, check output in log
2020-10-09T16:06:11.5220921Z [ERROR] Process Exit Code: 3
2020-10-09T16:06:11.5221361Z [ERROR] Crashed tests:
2020-10-09T16:06:11.5222433Z [ERROR] io.prestosql.plugin.hive.TestHiveIntegrationSmokeTest
2020-10-09T16:06:11.5224103Z [ERROR] io.prestosql.plugin.hive.rubix.TestRubixCaching
2020-10-09T16:06:11.5226088Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
2020-10-09T16:06:11.5228621Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
2020-10-09T16:06:11.5231105Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
2020-10-09T16:06:11.5235567Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
2020-10-09T16:06:11.5250791Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
2020-10-09T16:06:11.5254816Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
2020-10-09T16:06:11.5258498Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:868)
2020-10-09T16:06:11.5261322Z [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
2020-10-09T16:06:11.5263892Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
2020-10-09T16:06:11.5266082Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
2020-10-09T16:06:11.5268289Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
2020-10-09T16:06:11.5271149Z [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
2020-10-09T16:06:11.5274689Z [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
2020-10-09T16:06:11.5278857Z [ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
2020-10-09T16:06:11.5282452Z [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
2020-10-09T16:06:11.5284410Z [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
2020-10-09T16:06:11.5285785Z [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
2020-10-09T16:06:11.5287424Z [ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
2020-10-09T16:06:11.5288668Z [ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
2020-10-09T16:06:11.5290036Z [ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
2020-10-09T16:06:11.5291154Z [ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
2020-10-09T16:06:11.5292704Z [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-10-09T16:06:11.5294972Z [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-10-09T16:06:11.5297644Z [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-10-09T16:06:11.5299587Z [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-10-09T16:06:11.5301667Z [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
2020-10-09T16:06:11.5304193Z [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
2020-10-09T16:06:11.5306639Z [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
2020-10-09T16:06:11.5309020Z [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
2020-10-09T16:06:11.5315169Z [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-10-09T16:06:11.5317451Z [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-10-09T16:06:11.5320116Z [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-10-09T16:06:11.5322043Z [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-10-09T16:06:11.5323879Z [ERROR] 	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
2020-10-09T16:06:11.5325890Z [ERROR] 	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
2020-10-09T16:06:11.5328495Z [ERROR] 	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
2020-10-09T16:06:11.5330771Z [ERROR] -> [Help 1]
```

wondering if this is a known issue with forking and whether we can fix it.

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/4916468461

**Comment by findepi** [comment]
if this is due to OOM, https://github.com/apache/maven-surefire/pull/407 might help.

**Comment by findepi** [comment]
Closing in favor of https://github.com/trinodb/trino/issues/11848
