### ISSUE TITLE
Oracle session not disconnected

### ISSUE THREAD

**Issue by walter-weinmann** [trinodb/trino#5648]
### Execution protocol:

```
2020-10-22 12:50:36,484 [I9999.java] INFO  Start main() ==================================================
2020-10-22 12:50:36,488 [I9999.java] INFO  Reset the database ============================================
2020-10-22 12:50:36,489 [I9999.java] INFO  connecting ...
2020-10-22 12:50:36,491 [I9999.java] INFO  driver    ='oracle.jdbc.driver.OracleDriver'
2020-10-22 12:50:36,493 [I9999.java] INFO  url       ='jdbc:oracle:thin:@//localhost:1521/orclpdb1'
2020-10-22 12:50:36,496 [I9999.java] INFO  user      ='SYS AS SYSDBA'
2020-10-22 12:50:36,498 [I9999.java] INFO  password  ='oracle'
2020-10-22 12:50:36,502 [I9999.java] INFO  autocommit='false'
2020-10-22 12:50:37,506 [I9999.java] INFO  ==========> now connected
2020-10-22 12:50:37,577 [I9999.java] INFO  sqlStmnt='SELECT COUNT(*) FROM ALL_USERS WHERE username = 'KXN_USER''
2020-10-22 12:50:37,632 [I9999.java] INFO  sqlStmnt='DROP USER KXN_USER CASCADE'
2020-10-22 12:50:38,483 [I9999.java] INFO  disconnecting ...
2020-10-22 12:50:38,485 [I9999.java] INFO  commiting ...
2020-10-22 12:50:38,491 [I9999.java] INFO  ==========> now disconnected
2020-10-22 12:50:38,493 [I9999.java] INFO  Setup the database ============================================
2020-10-22 12:50:38,495 [I9999.java] INFO  connecting ...
2020-10-22 12:50:38,497 [I9999.java] INFO  driver    ='oracle.jdbc.driver.OracleDriver'
2020-10-22 12:50:38,498 [I9999.java] INFO  url       ='jdbc:oracle:thin:@//localhost:1521/orclpdb1'
2020-10-22 12:50:38,500 [I9999.java] INFO  user      ='SYS AS SYSDBA'
2020-10-22 12:50:38,501 [I9999.java] INFO  password  ='oracle'
2020-10-22 12:50:38,506 [I9999.java] INFO  autocommit='false'
2020-10-22 12:50:38,566 [I9999.java] INFO  ==========> now connected
2020-10-22 12:50:38,568 [I9999.java] INFO  sqlStmnt='CREATE USER KXN_USER IDENTIFIED BY "oracle"'
2020-10-22 12:50:38,625 [I9999.java] INFO  sqlStmnt='ALTER USER KXN_USER QUOTA UNLIMITED ON users'
2020-10-22 12:50:38,638 [I9999.java] INFO  sqlStmnt='GRANT CREATE SEQUENCE TO KXN_USER'
2020-10-22 12:50:38,647 [I9999.java] INFO  sqlStmnt='GRANT CREATE SESSION TO KXN_USER'
2020-10-22 12:50:38,653 [I9999.java] INFO  sqlStmnt='GRANT CREATE TABLE TO KXN_USER'
2020-10-22 12:50:38,658 [I9999.java] INFO  sqlStmnt='GRANT UNLIMITED TABLESPACE TO KXN_USER'
2020-10-22 12:50:38,664 [I9999.java] INFO  disconnecting ...
2020-10-22 12:50:38,666 [I9999.java] INFO  commiting ...
2020-10-22 12:50:38,670 [I9999.java] INFO  ==========> now disconnected
2020-10-22 12:50:38,671 [I9999.java] INFO  connecting ...
2020-10-22 12:50:38,673 [I9999.java] INFO  driver    ='oracle.jdbc.driver.OracleDriver'
2020-10-22 12:50:38,674 [I9999.java] INFO  url       ='jdbc:oracle:thin:@//localhost:1521/orclpdb1'
2020-10-22 12:50:38,678 [I9999.java] INFO  user      ='KXN_USER'
2020-10-22 12:50:38,680 [I9999.java] INFO  password  ='oracle'
2020-10-22 12:50:38,682 [I9999.java] INFO  autocommit='false'
2020-10-22 12:50:38,726 [I9999.java] INFO  ==========> now connected
2020-10-22 12:50:38,728 [I9999.java] INFO  sqlStmnt='CREATE TABLE issue_table (
    column_pk        NUMBER         NOT NULL
)
'
2020-10-22 12:50:38,757 [I9999.java] INFO  disconnecting ...
2020-10-22 12:50:38,759 [I9999.java] INFO  commiting ...
2020-10-22 12:50:38,763 [I9999.java] INFO  ==========> now disconnected
2020-10-22 12:50:38,765 [I9999.java] INFO  Run the demo with the Presto JDBC driver ======================
2020-10-22 12:50:38,766 [I9999.java] INFO  connecting ...
2020-10-22 12:50:38,767 [I9999.java] INFO  driver    ='io.prestosql.jdbc.PrestoDriver'
2020-10-22 12:50:38,771 [I9999.java] INFO  url       ='jdbc:presto://localhost:8080/db_seeder_oracle/kxn_user?user=presto'
2020-10-22 12:50:38,773 [I9999.java] INFO  user      ='null'
2020-10-22 12:50:38,774 [I9999.java] INFO  password  ='null'
2020-10-22 12:50:38,775 [I9999.java] INFO  autocommit='true'
2020-10-22 12:50:39,144 [I9999.java] INFO  ==========> now connected
2020-10-22 12:50:39,960 [I9999.java] INFO  disconnecting ...
2020-10-22 12:50:39,962 [I9999.java] INFO  ==========> now disconnected
2020-10-22 12:50:39,964 [I9999.java] INFO  Reset the database ============================================
2020-10-22 12:50:39,965 [I9999.java] INFO  connecting ...
2020-10-22 12:50:39,966 [I9999.java] INFO  driver    ='oracle.jdbc.driver.OracleDriver'
2020-10-22 12:50:39,967 [I9999.java] INFO  url       ='jdbc:oracle:thin:@//localhost:1521/orclpdb1'
2020-10-22 12:50:39,969 [I9999.java] INFO  user      ='SYS AS SYSDBA'
2020-10-22 12:50:39,970 [I9999.java] INFO  password  ='oracle'
2020-10-22 12:50:39,971 [I9999.java] INFO  autocommit='false'
2020-10-22 12:50:40,012 [I9999.java] INFO  ==========> now connected
2020-10-22 12:50:40,014 [I9999.java] INFO  sqlStmnt='SELECT COUNT(*) FROM ALL_USERS WHERE username = 'KXN_USER''
2020-10-22 12:50:40,020 [I9999.java] INFO  sqlStmnt='DROP USER KXN_USER CASCADE'
java.sql.SQLSyntaxErrorException: ORA-01940: Ein Benutzer, der gerade mit der DB verbunden ist, kann nicht gelöscht werden

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41)
        at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:928)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
        at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1823)
        at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1778)
        at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:303)
        at ch.konnexions.db_seeder.samples.presto.I9999.executeDdlStmnts(I9999.java:140)
        at ch.konnexions.db_seeder.samples.presto.I9999.dropUser(I9999.java:129)
        at ch.konnexions.db_seeder.samples.presto.I9999.resetDatabase(I9999.java:199)
        at ch.konnexions.db_seeder.samples.presto.I9999.main(I9999.java:182)
Caused by: Error : 1940, Position : 0, Sql = DROP USER KXN_USER CASCADE, OriginalSql = DROP USER KXN_USER CASCADE, Error Msg = ORA-01940: Ein Benutzer, der gerade mit der DB verbunden ist, kann nicht gelöscht werden

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
        ... 16 more
```

### Minimal source file:

```
package ch.konnexions.db_seeder.samples.presto;

import org.apache.log4j.Logger;

import java.sql.*;

/**
 * Example program for Issues Oracle Connector.
 * 
 * @author  walter@konnexions.ch
 * @since   2020-10-22
 */
public final class I9999 {

  private static Connection connection;
  private static String     connectionHost      = "localhost";
  private static int        connectionPort      = 1521;

  private static String     driverOriginal      = "oracle.jdbc.driver.OracleDriver";
  private static String     driverPresto        = "io.prestosql.jdbc.PrestoDriver";

  private static Logger     logger              = Logger.getLogger(I9999.class);

  private static String     password            = "oracle";

  private static String     service             = "orclpdb1";
  private static String     sqlStmntCreateTable = """
                                                  CREATE TABLE issue_table (
                                                      column_pk        NUMBER         NOT NULL
                                                  )
                                                  """;
  private static String     sqlStmntInsert      = "INSERT INTO issue_table (column_pk) VALUES (?)";
  private static Statement  statement;

  private static String     userName            = "kxn_user";
  private static String     userNameSys         = "SYS AS SYSDBA";

  private static String     urlSys              = "jdbc:oracle:thin:@//" + connectionHost + ":" + connectionPort + "/" + service;
  private static String     urlPresto           = "jdbc:presto://localhost:8080/db_seeder_oracle/" + userName + "?user=presto";
  private static String     urlUser             = "jdbc:oracle:thin:@//" + connectionHost + ":" + connectionPort + "/" + service;

  private static Connection connect(String url, String driver, String user, String password, boolean autoCommit) {
    logger.info("connecting ...");
    logger.info("driver    ='" + driver + "'");
    logger.info("url       ='" + url + "'");
    logger.info("user      ='" + user + "'");
    logger.info("password  ='" + password + "'");
    logger.info("autocommit='" + autoCommit + "'");

    try {
      Class.forName(driver);
    } catch (ClassNotFoundException e) {
      e.printStackTrace();
      System.exit(1);
    }

    Connection connection = null;

    try {
      if (user == null && password == null) {
        connection = DriverManager.getConnection(url);
      } else {
        connection = DriverManager.getConnection(url,
                                                 user,
                                                 password);
      }

      connection.setAutoCommit(autoCommit);
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }

    logger.info("==========> now connected");

    return connection;
  }

  private static void demonstratePresto() {
    logger.info("Run the demo with the Presto JDBC driver ======================");

    connection = connect(urlPresto,
                         driverPresto,
                         null,
                         null,
                         true);

    insertData();

    disconnect(connection);
  }

  private static void disconnect(Connection connection) {
    logger.info("disconnecting ...");

    try {
      if (!(connection.getAutoCommit())) {
        logger.info("commiting ...");
        connection.commit();
      }

      connection.close();

    } catch (SQLException ec) {
      ec.printStackTrace();
      System.exit(1);
    }

    logger.info("==========> now disconnected");
  }

  private static void dropUser(String userName) {
    try {
      int    count    = 0;

      String sqlStmnt = "SELECT COUNT(*) FROM ALL_USERS WHERE username = '" + userName + "'";

      logger.info("sqlStmnt='" + sqlStmnt + "'");

      ResultSet resultSet = statement.executeQuery(sqlStmnt);

      while (resultSet.next()) {
        count = resultSet.getInt(1);
      }

      resultSet.close();

      if (count > 0) {
        executeDdlStmnts("DROP USER " + userName + " CASCADE");
      }
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }
  }

  private static void executeDdlStmnts(String firstDdlStmnt, String... remainingDdlStmnts) {
    try {
      logger.info("sqlStmnt='" + firstDdlStmnt + "'");
      statement.execute(firstDdlStmnt);

      for (String sqlStmnt : remainingDdlStmnts) {
        logger.info("sqlStmnt='" + sqlStmnt + "'");
        statement.execute(sqlStmnt);
      }
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }
  }

  private static void insertData() {
    try {
      PreparedStatement preparedStatement = connection.prepareStatement(sqlStmntInsert);

      preparedStatement.setLong(1,
                                1);

      if (preparedStatement.executeUpdate() != 1) {
        logger.fatal("Program abort: row not inserted");
      }

      preparedStatement.close();
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }

  }

  /**
   * The main method.
   *
   * @param args the arguments
   */
  public static void main(String[] args) {
    logger.info("Start main() ==================================================");

    resetDatabase();
    setupDatabase();
    demonstratePresto();
    resetDatabase();

    logger.info("End   main() ==================================================");
  }

  private static void resetDatabase() {
    logger.info("Reset the database ============================================");

    connection = connect(urlSys,
                         driverOriginal,
                         userNameSys,
                         password,
                         false);

    try {
      statement = connection.createStatement();

      dropUser(userName.toUpperCase());

      statement.close();
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }

    disconnect(connection);
  }

  private static void setupDatabase() {
    logger.info("Setup the database ============================================");

    connection = connect(urlSys,
                         driverOriginal,
                         userNameSys,
                         password,
                         false);

    try {
      statement = connection.createStatement();

      executeDdlStmnts("CREATE USER " + userName.toUpperCase() + " IDENTIFIED BY \"" + password + "\"",
                       "ALTER USER " + userName.toUpperCase() + " QUOTA UNLIMITED ON users",
                       "GRANT CREATE SEQUENCE TO " + userName.toUpperCase(),
                       "GRANT CREATE SESSION TO " + userName.toUpperCase(),
                       "GRANT CREATE TABLE TO " + userName.toUpperCase(),
                       "GRANT UNLIMITED TABLESPACE TO " + userName.toUpperCase());

      statement.close();
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }

    disconnect(connection);

    connection = connect(urlUser,
                         driverOriginal,
                         userName.toUpperCase(),
                         password,
                         false);

    try {
      statement = connection.createStatement();

      executeDdlStmnts(sqlStmntCreateTable);

      statement.close();
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }

    disconnect(connection);
  }
}


```

**Comment by walter-weinmann** [comment]
## Short version:

If you connect to the Oracle database with the Presto JDBC driver, insert data into a table and then close the connection again, the corresponding database session will not be closed.

## Long version:

The following steps will cause the error:

### 1. with the Oracle driver: 

**a) Create database connection with user SYS
b) Creation of the user kxn_user
c) Close database connection**

```
2020-10-22 12:50:36,488 [I9999.java] INFO  Reset the database ============================================
2020-10-22 12:50:36,489 [I9999.java] INFO  connecting ...
2020-10-22 12:50:36,491 [I9999.java] INFO  driver    ='oracle.jdbc.driver.OracleDriver'
2020-10-22 12:50:36,493 [I9999.java] INFO  url       ='jdbc:oracle:thin:@//localhost:1521/orclpdb1'
2020-10-22 12:50:36,496 [I9999.java] INFO  user      ='SYS AS SYSDBA'
2020-10-22 12:50:36,498 [I9999.java] INFO  password  ='oracle'
2020-10-22 12:50:36,502 [I9999.java] INFO  autocommit='false'
2020-10-22 12:50:37,506 [I9999.java] INFO  ==========> now connected
2020-10-22 12:50:37,577 [I9999.java] INFO  sqlStmnt='SELECT COUNT(*) FROM ALL_USERS WHERE username = 'KXN_USER''
2020-10-22 12:50:37,632 [I9999.java] INFO  sqlStmnt='DROP USER KXN_USER CASCADE'
2020-10-22 12:50:38,483 [I9999.java] INFO  disconnecting ...
2020-10-22 12:50:38,485 [I9999.java] INFO  commiting ...
2020-10-22 12:50:38,491 [I9999.java] INFO  ==========> now disconnected
2020-10-22 12:50:38,493 [I9999.java] INFO  Setup the database ============================================
2020-10-22 12:50:38,495 [I9999.java] INFO  connecting ...
2020-10-22 12:50:38,497 [I9999.java] INFO  driver    ='oracle.jdbc.driver.OracleDriver'
2020-10-22 12:50:38,498 [I9999.java] INFO  url       ='jdbc:oracle:thin:@//localhost:1521/orclpdb1'
2020-10-22 12:50:38,500 [I9999.java] INFO  user      ='SYS AS SYSDBA'
2020-10-22 12:50:38,501 [I9999.java] INFO  password  ='oracle'
2020-10-22 12:50:38,506 [I9999.java] INFO  autocommit='false'
2020-10-22 12:50:38,566 [I9999.java] INFO  ==========> now connected
2020-10-22 12:50:38,568 [I9999.java] INFO  sqlStmnt='CREATE USER KXN_USER IDENTIFIED BY "oracle"'
2020-10-22 12:50:38,625 [I9999.java] INFO  sqlStmnt='ALTER USER KXN_USER QUOTA UNLIMITED ON users'
2020-10-22 12:50:38,638 [I9999.java] INFO  sqlStmnt='GRANT CREATE SEQUENCE TO KXN_USER'
2020-10-22 12:50:38,647 [I9999.java] INFO  sqlStmnt='GRANT CREATE SESSION TO KXN_USER'
2020-10-22 12:50:38,653 [I9999.java] INFO  sqlStmnt='GRANT CREATE TABLE TO KXN_USER'
2020-10-22 12:50:38,658 [I9999.java] INFO  sqlStmnt='GRANT UNLIMITED TABLESPACE TO KXN_USER'
2020-10-22 12:50:38,664 [I9999.java] INFO  disconnecting ...
2020-10-22 12:50:38,666 [I9999.java] INFO  commiting ...
2020-10-22 12:50:38,670 [I9999.java] INFO  ==========> now disconnected
```

**d) Create database connection with user kxn_user
c) Creation of the database table issue_table
e) End database connection**

```
2020-10-22 12:50:38,671 [I9999.java] INFO  connecting ...
2020-10-22 12:50:38,673 [I9999.java] INFO  driver    ='oracle.jdbc.driver.OracleDriver'
2020-10-22 12:50:38,674 [I9999.java] INFO  url       ='jdbc:oracle:thin:@//localhost:1521/orclpdb1'
2020-10-22 12:50:38,678 [I9999.java] INFO  user      ='KXN_USER'
2020-10-22 12:50:38,680 [I9999.java] INFO  password  ='oracle'
2020-10-22 12:50:38,682 [I9999.java] INFO  autocommit='false'
2020-10-22 12:50:38,726 [I9999.java] INFO  ==========> now connected
2020-10-22 12:50:38,728 [I9999.java] INFO  sqlStmnt='CREATE TABLE issue_table (
    column_pk        NUMBER         NOT NULL
)
'
2020-10-22 12:50:38,757 [I9999.java] INFO  disconnecting ...
2020-10-22 12:50:38,759 [I9999.java] INFO  commiting ...
2020-10-22 12:50:38,763 [I9999.java] INFO  ==========> now disconnected

```
### 2. with the Presto driver:

**a) Create database connection with user presto / kxn_user
b) Insert row in the database table issue_table
c) Close database connection**

```
2020-10-22 12:50:38,765 [I9999.java] INFO  Run the demo with the Presto JDBC driver ======================
2020-10-22 12:50:38,766 [I9999.java] INFO  connecting ...
2020-10-22 12:50:38,767 [I9999.java] INFO  driver    ='io.prestosql.jdbc.PrestoDriver'
2020-10-22 12:50:38,771 [I9999.java] INFO  url       ='jdbc:presto://localhost:8080/db_seeder_oracle/kxn_user?user=presto'
2020-10-22 12:50:38,773 [I9999.java] INFO  user      ='null'
2020-10-22 12:50:38,774 [I9999.java] INFO  password  ='null'
2020-10-22 12:50:38,775 [I9999.java] INFO  autocommit='true'
2020-10-22 12:50:39,144 [I9999.java] INFO  ==========> now connected
2020-10-22 12:50:39,960 [I9999.java] INFO  disconnecting ...
2020-10-22 12:50:39,962 [I9999.java] INFO  ==========> now disconnected

```
### 3. with the Oracle driver: 

**a) Create database connection with user SYS
b) Delete the user kxn_user**

```
2020-10-22 12:50:39,964 [I9999.java] INFO  Reset the database ============================================
2020-10-22 12:50:39,965 [I9999.java] INFO  connecting ...
2020-10-22 12:50:39,966 [I9999.java] INFO  driver    ='oracle.jdbc.driver.OracleDriver'
2020-10-22 12:50:39,967 [I9999.java] INFO  url       ='jdbc:oracle:thin:@//localhost:1521/orclpdb1'
2020-10-22 12:50:39,969 [I9999.java] INFO  user      ='SYS AS SYSDBA'
2020-10-22 12:50:39,970 [I9999.java] INFO  password  ='oracle'
2020-10-22 12:50:39,971 [I9999.java] INFO  autocommit='false'
2020-10-22 12:50:40,012 [I9999.java] INFO  ==========> now connected
2020-10-22 12:50:40,014 [I9999.java] INFO  sqlStmnt='SELECT COUNT(*) FROM ALL_USERS WHERE username = 'KXN_USER''
2020-10-22 12:50:40,020 [I9999.java] INFO  sqlStmnt='DROP USER KXN_USER CASCADE'
java.sql.SQLSyntaxErrorException: ORA-01940: Ein Benutzer, der gerade mit der DB verbunden ist, kann nicht gelöscht werden

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41)
        at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:928)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
        at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1823)
        at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1778)
        at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:303)
        at ch.konnexions.db_seeder.samples.presto.I9999.executeDdlStmnts(I9999.java:140)
        at ch.konnexions.db_seeder.samples.presto.I9999.dropUser(I9999.java:129)
        at ch.konnexions.db_seeder.samples.presto.I9999.resetDatabase(I9999.java:199)
        at ch.konnexions.db_seeder.samples.presto.I9999.main(I9999.java:182)
Caused by: Error : 1940, Position : 0, Sql = DROP USER KXN_USER CASCADE, OriginalSql = DROP USER KXN_USER CASCADE, Error Msg = ORA-01940: Ein Benutzer, der gerade mit der DB verbunden ist, kann nicht gelöscht werden



```

**Comment by walter-weinmann** [comment]
This is still an issue in version 347.

**Comment by walter-weinmann** [comment]
This is still an issue in version 352.

**Comment by walter-weinmann** [comment]
Issue solved with version 371.
