### ISSUE TITLE
ArithmeticException: integer overflow when querying large Parquet files with large row group (2GB)

### ISSUE THREAD

**Issue by davigust** [trinodb/trino#5729]
Queries failing against large parquet files in release 341. @martint kindly suggested that the issue could be a row group exceeding 2GB.  

```java
DiskRange range = new DiskRange(chunkMetadata.getStartingPos(), toIntExact(chunkMetadata.getTotalSize()));
```

https://github.com/prestosql/presto/issues/2730#issuecomment-718119044

```
io.prestosql.spi.PrestoException: Error opening Hive split abfs://xxxxxxxx@xxxxxxxx.dfs.core.windows.net/xxxxxxxx/day=2020-10-19/20201019_010801727_suez-859f9f6b9-85zw7 (offset=0, length=67108864): integer overflow
	at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:247)
	at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:134)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:171)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:101)
	at io.prestosql.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:68)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:66)
	at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:254)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:182)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:149)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_341____20201027_161202_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ArithmeticException: integer overflow
	at java.base/java.lang.Math.toIntExact(Math.java:1071)
	at io.prestosql.parquet.reader.ParquetReader.<init>(ParquetReader.java:121)
	at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:222)
	... 32 more
```

**Comment by martint** [comment]
Can you post the output of `parquet-tools meta` for that file?

**Comment by davigust** [comment]
Some of the data values have been scrubbed.

Looks like one big rowgroup.

```
file:             file:/Users/gustafson/Downloads/20201019_010801727_suez-859f9f6b9-85zw7
creator:          parquet-go version latest

file schema:      parquet_go_root
--------------------------------------------------------------------------------
repo_id:          REQUIRED INT32 L:INTEGER(32,false) R:0 D:0
repo_owner:       REQUIRED BINARY L:STRING R:0 D:0
repo_name:        REQUIRED BINARY L:STRING R:0 D:0
repo_visibility:  REQUIRED BINARY L:STRING R:0 D:0
pushed_at:        REQUIRED INT64 L:TIMESTAMP(MILLIS,true) R:0 D:0
actor_name:       REQUIRED BINARY L:STRING R:0 D:0
ref_name:         REQUIRED BINARY L:STRING R:0 D:0
commit_id:        REQUIRED BINARY L:STRING R:0 D:0
path:             REQUIRED BINARY L:STRING R:0 D:0
filename:         REQUIRED BINARY L:STRING R:0 D:0
extension:        REQUIRED BINARY L:STRING R:0 D:0
object_id:        REQUIRED BINARY L:STRING R:0 D:0
is_deleted:       REQUIRED BOOLEAN R:0 D:0
content:          REQUIRED BINARY R:0 D:0
content_size:     REQUIRED INT64 R:0 D:0
is_binary:        REQUIRED BOOLEAN R:0 D:0
is_utf8:          REQUIRED BOOLEAN R:0 D:0
language:         REQUIRED BINARY L:STRING R:0 D:0
language_type:    REQUIRED BINARY L:STRING R:0 D:0
mime_type:        REQUIRED BINARY L:STRING R:0 D:0
is_dot_file:      REQUIRED BOOLEAN R:0 D:0
is_image:         REQUIRED BOOLEAN R:0 D:0
is_vendored:      REQUIRED BOOLEAN R:0 D:0
is_documentation: REQUIRED BOOLEAN R:0 D:0

row group 1:      RC:675 TS:2262294203 OFFSET:4
--------------------------------------------------------------------------------
repo_id:           INT32 GZIP DO:0 FPO:4 SZ:933/3149/3.38 VC:675 ENC:BIT_PACKED,RLE,PLAIN ST:[min: 295575720, max: 305228280, num_nulls not defined]
repo_owner:        BINARY GZIP DO:937 FPO:1102 SZ:723/448/0.62 VC:675 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY,PLAIN,RLE_DICTIONARY ST:[min: ..., max: ..., num_nulls not defined]
repo_name:         BINARY GZIP DO:1660 FPO:1818 SZ:716/473/0.66 VC:675 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY,PLAIN,RLE_DICTIONARY ST:[min: ..., max: ..., num_nulls not defined]
repo_visibility:   BINARY GZIP DO:2376 FPO:2424 SZ:546/271/0.50 VC:675 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY,PLAIN,RLE_DICTIONARY ST:[min: PUBLIC, max: PUBLIC, num_nulls not defined]
pushed_at:         INT64 GZIP DO:0 FPO:2922 SZ:1149/6010/5.23 VC:675 ENC:BIT_PACKED,RLE,PLAIN ST:[min: 2020-10-19T01:07:30.338+0000, max: 2020-10-19T01:08:27.481+0000, num_nulls not defined]
actor_name:        BINARY GZIP DO:4071 FPO:4219 SZ:706/453/0.64 VC:675 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY,PLAIN,RLE_DICTIONARY ST:[min: ..., max: ..., num_nulls not defined]
ref_name:          BINARY GZIP DO:4777 FPO:4856 SZ:618/343/0.56 VC:675 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY,PLAIN,RLE_DICTIONARY ST:[min: refs/heads/main, max: refs/heads/master, num_nulls not defined]
commit_id:         BINARY GZIP DO:5395 FPO:5673 SZ:836/763/0.91 VC:675 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY,PLAIN,RLE_DICTIONARY ST:[min: 14b5d766178339b021a268fa902a5d0692ab8718, max: fa8a8f6d33aff6579a7cd25e3d34113443e27150, num_nulls not defined]
path:              BINARY GZIP DO:6231 FPO:9662 SZ:5033/30623/6.08 VC:675 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY,PLAIN,RLE_DICTIONARY ST:[min: .gitignore, max: ..., num_nulls not defined]
filename:          BINARY GZIP DO:11264 FPO:14211 SZ:4547/20696/4.55 VC:675 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY,PLAIN,RLE_DICTIONARY ST:[min: .gitignore, max: views.py, num_nulls not defined]
extension:         BINARY GZIP DO:15811 FPO:15975 SZ:796/580/0.73 VC:675 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY,PLAIN,RLE_DICTIONARY ST:[min: , max: .yml, num_nulls not defined]
object_id:         BINARY GZIP DO:16607 FPO:31832 SZ:16813/32371/1.93 VC:675 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY,PLAIN,RLE_DICTIONARY ST:[min: 00e0056209dfdc5d13aa1f548b4937b953638708, max: febb3874ca258cb4680085edbe7ea9f6b2c4dacf, num_nulls not defined]
is_deleted:        BOOLEAN GZIP DO:0 FPO:33420 SZ:658/408/0.62 VC:675 ENC:BIT_PACKED,RLE,PLAIN ST:[min: false, max: false, num_nulls not defined]
content:           BINARY GZIP DO:0 FPO:34078 SZ:2258997273/2262187396/1.00 VC:675 ENC:BIT_PACKED,RLE,PLAIN ST:[min: ..., num_nulls not defined]
content_size:      INT64 GZIP DO:0 FPO:2259031351 SZ:3793/6019/1.59 VC:675 ENC:BIT_PACKED,RLE,PLAIN ST:[min: 19, max: 15724974, num_nulls not defined]
is_binary:         BOOLEAN GZIP DO:0 FPO:2259035144 SZ:658/408/0.62 VC:675 ENC:BIT_PACKED,RLE,PLAIN ST:[min: false, max: true, num_nulls not defined]
is_utf8:           BOOLEAN GZIP DO:0 FPO:2259035802 SZ:658/408/0.62 VC:675 ENC:BIT_PACKED,RLE,PLAIN ST:[min: false, max: true, num_nulls not defined]
language:          BINARY GZIP DO:2259036460 FPO:2259036615 SZ:783/566/0.72 VC:675 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY,PLAIN,RLE_DICTIONARY ST:[min: , max: YAML, num_nulls not defined]
language_type:     BINARY GZIP DO:2259037243 FPO:2259037345 SZ:698/482/0.69 VC:675 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY,PLAIN,RLE_DICTIONARY ST:[min: DATA, max: PROSE, num_nulls not defined]
mime_type:         BINARY GZIP DO:2259037941 FPO:2259038065 SZ:855/704/0.82 VC:675 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY,PLAIN,RLE_DICTIONARY ST:[min: , max: text/xml, num_nulls not defined]
is_dot_file:       BOOLEAN GZIP DO:0 FPO:2259038796 SZ:658/408/0.62 VC:675 ENC:BIT_PACKED,RLE,PLAIN ST:[min: false, max: true, num_nulls not defined]
is_image:          BOOLEAN GZIP DO:0 FPO:2259039454 SZ:658/408/0.62 VC:675 ENC:BIT_PACKED,RLE,PLAIN ST:[min: false, max: true, num_nulls not defined]
is_vendored:       BOOLEAN GZIP DO:0 FPO:2259040112 SZ:658/408/0.62 VC:675 ENC:BIT_PACKED,RLE,PLAIN ST:[min: false, max: true, num_nulls not defined]
is_documentation:  BOOLEAN GZIP DO:0 FPO:2259040770 SZ:658/408/0.62 VC:675 ENC:BIT_PACKED,RLE,PLAIN ST:[min: false, max: true, num_nulls not defined]
```

**Comment by findepi** [comment]
cc @martint @skrzypo987

**Comment by harsh-tamr** [comment]
@davigust any luck
