### ISSUE TITLE
Flaky TestKafkaIntegrationPushDown.testTimestampLogAppendModePushDown

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#5734]
```
2020-10-28T16:18:13.1960677Z [ERROR] testTimestampLogAppendModePushDown(io.prestosql.plugin.kafka.TestKafkaIntegrationPushDown)  Time elapsed: 0.499 s  <<< FAILURE!
2020-10-28T16:18:13.1962678Z java.lang.AssertionError: expected [2] but found [1]
2020-10-28T16:18:13.1963579Z 	at org.testng.Assert.fail(Assert.java:94)
2020-10-28T16:18:13.1964542Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2020-10-28T16:18:13.1965686Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2020-10-28T16:18:13.1966812Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2020-10-28T16:18:13.1968081Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2020-10-28T16:18:13.1969238Z 	at org.testng.Assert.assertEquals(Assert.java:294)
2020-10-28T16:18:13.1972464Z 	at io.prestosql.plugin.kafka.TestKafkaIntegrationPushDown.testTimestampLogAppendModePushDown(TestKafkaIntegrationPushDown.java:166)
2020-10-28T16:18:13.1976200Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-10-28T16:18:13.1978719Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-10-28T16:18:13.1982661Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-10-28T16:18:13.1986954Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-10-28T16:18:13.1988632Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-10-28T16:18:13.1990455Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-10-28T16:18:13.1991791Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-10-28T16:18:13.2001118Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-10-28T16:18:13.2002959Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-10-28T16:18:13.2004774Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-10-28T16:18:13.2006492Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-10-28T16:18:13.2008321Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-10-28T16:18:13.2009699Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-10-28T16:18:13.2010096Z 
2020-10-28T16:18:13.6469116Z [INFO] 
2020-10-28T16:18:13.6471392Z [INFO] Results:
2020-10-28T16:18:13.6471710Z [INFO] 
2020-10-28T16:18:13.6472522Z [ERROR] Failures: 
2020-10-28T16:18:13.6474846Z [ERROR]   TestKafkaIntegrationPushDown.testTimestampLogAppendModePushDown:166 expected [2] but found [1]
```

**Comment by ebyhr** [comment]
#5726

**Comment by findepi** [comment]
cc @wangli-td @losipiuk

**Comment by wangli-td** [comment]
@ebyhr Hi ehyhr, Thanks. How would you reproduce the issue. Seems my test always pass.

**Comment by ebyhr** [comment]
@wangli-td Unfortunately, I'm not sure about the steps to reproduce. The failure frequency isn't so high I think.

**Comment by wangli-td** [comment]
the normal case:
index:0,partition:0,offset:0, lastTimeStamp:1604025064176
index:1,partition:1,offset:0, lastTimeStamp:1604025064258
index:2,partition:0,offset:1, lastTimeStamp:1604025064284 startTime:2020-10-30 02:31:04.284
index:3,partition:1,offset:1, lastTimeStamp:1604025064318
index:4,partition:0,offset:2, lastTimeStamp:1604025064345 endTime:2020-10-30 02:31:04.345
offsetTimestampRanged:Optional[Range{begin=1604025064284000, end=1604025064345000}]
kafkaFilteringResult:KafkaFilteringResult{
	partitionInfos=[...],
	partitionBeginOffsets={1=1, 0=1}, partitionEndOffsets={1=2, 0=2}}

**Comment by wangli-td** [comment]
Or the timestamp in kafka docker may not elapse when local time elapses. I may refine here.

**Comment by wangli-td** [comment]
It seems I can't reproduce it in my env util now.
@losipiuk hi losipiuk do you have some clue, do I need add some dump like below when assert fail?
dump sql:SELECT count(*) FROM default.test_push_down_log_append_471b8ed7_f84d_41eb_83db_1f8b9ea6f542
	WHERE _timestamp >= timestamp '**2020-10-30 07:23:25.976**' and _timestamp < timestamp '**2020-10-30 07:23:26.033**'

dump:_partition_id:0, _partition_offset:0, _timestamp:2020-10-30T07:23:25.870
dump:_partition_id:1, _partition_offset:0, _timestamp:2020-10-30T07:23:25.948
dump:_partition_id:0, _partition_offset:1, _timestamp:**2020-10-30T07:23:25.976**
dump:_partition_id:1, _partition_offset:1, _timestamp:2020-10-30T07:23:26.004
dump:_partition_id:0, _partition_offset:2, _timestamp:**2020-10-30T07:23:26.033**
dump:_partition_id:1, _partition_offset:2, _timestamp:2020-10-30T07:23:26.062
dump:_partition_id:1, _partition_offset:3, _timestamp:2020-10-30T07:23:26.062
dump:_partition_id:1, _partition_offset:4, _timestamp:2020-10-30T07:23:26.062
dump:_partition_id:0, _partition_offset:3, _timestamp:2020-10-30T07:23:26.064
dump:_partition_id:0, _partition_offset:4, _timestamp:2020-10-30T07:23:26.064
dump:_partition_id:1, _partition_offset:5, _timestamp:2020-10-30T07:23:26.068
dump:_partition_id:0, _partition_offset:5, _timestamp:2020-10-30T07:23:26.069

**Comment by findepi** [comment]
The failing assertion seems to be:
```
assertEquals(getQueryInfo(queryRunner, queryResult).getQueryStats().getProcessedInputPositions(), 2);
```

The test may be flaky because of https://github.com/prestosql/presto/issues/5172.

cc @sopel39

**Comment by findepi** [comment]
I run the test with `@Test(invocationCount = 1000)` and got 3 fails (270s overall):

once:
```
java.lang.AssertionError: expected [2] but found [500]
Expected :2
Actual   :500

	at org.testng.Assert.assertEquals(Assert.java:294)
	at io.prestosql.plugin.kafka.TestKafkaIntegrationPushDown.testTimestampLogAppendModePushDown(TestKafkaIntegrationPushDown.java:166)
```

twice:
```
java.lang.AssertionError: expected [2] but found [3]
Expected :2
Actual   :3

	at org.testng.Assert.assertEquals(Assert.java:294)
	at io.prestosql.plugin.kafka.TestKafkaIntegrationPushDown.testTimestampLogAppendModePushDown(TestKafkaIntegrationPushDown.java:166)
```


the concerning thing is that the `processedInputPositions` is **higher** than expected, so it can be something else than https://github.com/prestosql/presto/issues/5172 after all.

**Comment by sopel39** [comment]
> the concerning thing is that the processedInputPositions is higher than expected, so it can be something else than #5172 after all.

Yeah, it shouldn't be higher.

**Comment by losipiuk** [comment]
>It seems I can't reproduce it in my env util now.
@losipiuk hi losipiuk do you have some clue, do I need add some dump like below when assert fail?

Can you prepare the dump content upfront, before assertion, and then add it to assertion message?
Like this:
```
        assertThat(getQueryInfo(queryRunner, queryResult).getQueryStats().getProcessedInputPositions()).describedAs("with dump: %s", dump).isEqualTo(2);
```

**Comment by wangli-td** [comment]
Yes, I reproduce it with 1000 times test. And It seems the timestamp in LogAppendMode may have some possibilities generated in-order out-of-order. 
timestamp:1604064555784: partitionId:0, offset:170000
**timestamp:1604064555808: partitionId:0, offset:170001
timestamp:1604064555799: partitionId:0, offset:170002**
timestamp:1604064555824: partitionId:0, offset:170003
timestamp:1604064555851: partitionId:0, offset:170004

**Comment by wangli-td** [comment]
#5762 adds some optimizes for in-order test messages case. Also add some dump messages when fail.

**Comment by phd3** [comment]
Recently got a similar one on #6539 for `TestKafkaWithConfluentSchemaRegistryMinimalFunctionality` cc @Praveen2112 

```
io.trino.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality took 2.62m
2021-01-08T01:08:20.7114903Z [ERROR] Tests run: 242, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 648.501 s <<< FAILURE! - in TestSuite
2021-01-08T01:08:20.7117080Z [ERROR] testTimestampLogAppendModePushDown(io.trino.plugin.kafka.TestKafkaIntegrationPushDown)  Time elapsed: 3.411 s  <<< FAILURE!
2021-01-08T01:08:20.7120109Z org.junit.ComparisonFailure: expected:<[2]L> but was:<[0]L>
2021-01-08T01:08:20.7122031Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2021-01-08T01:08:20.7130961Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2021-01-08T01:08:20.7134638Z 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2021-01-08T01:08:20.7138983Z 	at io.trino.plugin.kafka.TestKafkaIntegrationPushDown.testTimestampLogAppendModePushDown(TestKafkaIntegrationPushDown.java:162)
2021-01-08T01:08:20.7142495Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-01-08T01:08:20.7144768Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-01-08T01:08:20.7147332Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-01-08T01:08:20.7149220Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-01-08T01:08:20.7151029Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-01-08T01:08:20.7152668Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-01-08T01:08:20.7156043Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-01-08T01:08:20.7157377Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-01-08T01:08:20.7158995Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-01-08T01:08:20.7160596Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-01-08T01:08:20.7162151Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-01-08T01:08:20.7163781Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-01-08T01:08:20.7164830Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by losipiuk** [comment]
Thanks @phd3. We could maybe track it and fix the test, if not https://github.com/trinodb/trino/commit/15c8d61dec389fcbc8d0bf87bc9f7f6e9e955525.
@kokosing the debug information was there for a reason. As we know the test is flaky we wanted to have more data when the issue reoccurs.

**Comment by kokosing** [comment]
Maybe we can simply mark this as `@Flaky`?

**Comment by losipiuk** [comment]
> Maybe we can simply mark this as `@Flaky`?

Yeah - maybe an option. Though I am not sure if the tests are designed to be run multiple times. And each of the runs would load new data into same, preexisting topic.

**Comment by kokosing** [comment]
Same similar issues with kafka schema registry. There I created dedicated query runner and kafka container per each test 😞
