### ISSUE TITLE
Flaky test TestHttpRemoteTask.testDynamicFilters

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#5809]
eg https://github.com/prestosql/presto/runs/1348766195

```
2020-11-03T17:22:21.4026628Z [ERROR] Tests run: 6679, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 962.094 s <<< FAILURE! - in TestSuite
2020-11-03T17:22:21.4033927Z [ERROR] testDynamicFilters(io.prestosql.server.remotetask.TestHttpRemoteTask)  Time elapsed: 0.197 s  <<< FAILURE!
2020-11-03T17:22:21.4039406Z java.lang.AssertionError: expected [2] but found [3]
2020-11-03T17:22:21.4043528Z 	at org.testng.Assert.fail(Assert.java:94)
2020-11-03T17:22:21.4048350Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2020-11-03T17:22:21.4053977Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2020-11-03T17:22:21.4059012Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2020-11-03T17:22:21.4063850Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2020-11-03T17:22:21.4068472Z 	at org.testng.Assert.assertEquals(Assert.java:294)
2020-11-03T17:22:21.4077006Z 	at io.prestosql.server.remotetask.TestHttpRemoteTask.testDynamicFilters(TestHttpRemoteTask.java:262)
2020-11-03T17:22:21.4085474Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-11-03T17:22:21.4094796Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-11-03T17:22:21.4172140Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-03T17:22:21.4178315Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-11-03T17:22:21.4184898Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-11-03T17:22:21.4191230Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-11-03T17:22:21.4198641Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-11-03T17:22:21.4206227Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-11-03T17:22:21.4212869Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-11-03T17:22:21.4220958Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-11-03T17:22:21.4228274Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-11-03T17:22:21.4232410Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
cc @sopel39 @raunaqmorarka

**Comment by findepi** [comment]
Normally the test method finishes in 0.5-3 s
Interestingly, when i did `@Test(timeOut = 30000, invocationCount = 100)`, it passed couple times and then started to consistently fail (with a timeout), even though i do not see any state shared between the test runs.

**Comment by phd3** [comment]
Saw another instance of this: https://github.com/trinodb/trino/pull/5813#issuecomment-760470649

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/pull/9275/checks?check_run_id=3685232588

**Comment by sopel39** [comment]
this is probably no longer relevant. Closing. When someone sees it again, we can reopen
