### ISSUE TITLE
NPE when refreshFromMetadataLocation() in iceberg connector

### ISSUE THREAD

**Issue by waterlx** [trinodb/trino#5875]
```
Caused by: java.lang.NullPointerException
	at io.prestosql.plugin.iceberg.HiveTableOperations.refreshFromMetadataLocation(HiveTableOperations.java:308)
	at io.prestosql.plugin.iceberg.HiveTableOperations.refresh(HiveTableOperations.java:154)
	at io.prestosql.plugin.iceberg.HiveTableOperations.current(HiveTableOperations.java:130)
	at org.apache.iceberg.BaseTable.schema(BaseTable.java:59)
	at io.prestosql.plugin.iceberg.IcebergMetadata.getColumnMetadatas(IcebergMetadata.java:524)
	at io.prestosql.plugin.iceberg.IcebergMetadata.getTableMetadata(IcebergMetadata.java:511)
	at io.prestosql.plugin.iceberg.IcebergMetadata.getTableMetadata(IcebergMetadata.java:219)
```

https://github.com/prestosql/presto/blob/c690d8511ffbcec6dca33c65d92dcecd9d875c38/presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/HiveTableOperations.java#L308

It seems we could get null from newMetadata.get()?

**Comment by waterlx** [comment]
I am trying to find more.  @Parth-Brahmbhatt @electrum FYI.

**Comment by joshthoward** [comment]
@waterlx do you have a way to reproduce this bug?

**Comment by findepi** [comment]
let's talk under #8873. Seems this is the same.
