### ISSUE TITLE
'getExplainPlan' with partitioning column of type 'int', 'date' etc fails for Iceberg tables

### ISSUE THREAD

**Issue by anjalinorwood** [trinodb/trino#5918]
Following test case reproduces the issue. 
```java
assertUpdate("CREATE TABLE base_table3 (_varchar VARCHAR, _int INT, _date DATE) WITH (partitioning = ARRAY['_int'])");

assertUpdate("INSERT INTO base_table3 VALUES ('a', 0, DATE '2019-09-08')", 1);

String plan = getExplainPlan("SELECT * from base_table3", ExplainType.Type.IO);
```

`getExplainPlan` fails with 

`PartitionTable.java::convert` needs to take into account all supported Iceberg types. 

This issue causes failures in Materialized View test cases as well (though, the issue is not specific to materialized views). @findepi FYI.

I am working on a PR.

**Comment by findepi** [comment]
@anjalinorwood what is the failure's stacktrace?

**Comment by anjalinorwood** [comment]
@findepi Here is the stack-trace.
`java.lang.IllegalArgumentException: Object '0' does not match type long

	at io.prestosql.spi.predicate.NullableValue.<init>(NullableValue.java:46)
	at io.prestosql.spi.predicate.NullableValue.of(NullableValue.java:67)
	at io.prestosql.plugin.iceberg.TableStatisticsMaker.makeNullableValue(TableStatisticsMaker.java:233)
	at io.prestosql.plugin.iceberg.TableStatisticsMaker.dataFileMatches(TableStatisticsMaker.java:221)
	at io.prestosql.plugin.iceberg.TableStatisticsMaker.makeTableStatistics(TableStatisticsMaker.java:131)
	at io.prestosql.plugin.iceberg.TableStatisticsMaker.getTableStatistics(TableStatisticsMaker.java:72)
	at io.prestosql.plugin.iceberg.IcebergMetadata.getTableStatistics(IcebergMetadata.java:722)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableStatistics(ClassLoaderSafeConnectorMetadata.java:276)
	at io.prestosql.metadata.MetadataManager.getTableStatistics(MetadataManager.java:524)
	at io.prestosql.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:64)
	at io.prestosql.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:39)
	at io.prestosql.cost.SimpleStatsRule.calculate(SimpleStatsRule.java:39)
	at io.prestosql.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:82)
	at io.prestosql.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:70)
	at io.prestosql.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:80)
	at io.prestosql.cost.ExchangeStatsRule.doCalculate(ExchangeStatsRule.java:54)
	at io.prestosql.cost.ExchangeStatsRule.doCalculate(ExchangeStatsRule.java:32)
	at io.prestosql.cost.SimpleStatsRule.calculate(SimpleStatsRule.java:39)
	at io.prestosql.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:82)
	at io.prestosql.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:70)
	at io.prestosql.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:80)
	at io.prestosql.cost.OutputStatsRule.calculate(OutputStatsRule.java:41)
	at io.prestosql.cost.OutputStatsRule.calculate(OutputStatsRule.java:27)
	at io.prestosql.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:82)
	at io.prestosql.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:70)
	at io.prestosql.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:80)
	at io.prestosql.cost.StatsAndCosts.create(StatsAndCosts.java:87)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:222)
	at io.prestosql.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:197)
	at io.prestosql.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:133)
	at io.prestosql.testing.AbstractTestQueryFramework.lambda$getExplainPlan$3(AbstractTestQueryFramework.java:352)
	at io.prestosql.transaction.TransactionBuilder.execute(TransactionBuilder.java:150)
	at io.prestosql.testing.AbstractTestQueryFramework.getExplainPlan(AbstractTestQueryFramework.java:351)
	at io.prestosql.plugin.iceberg.TestIcebergMaterializedViews.testReplace(TestIcebergMaterializedViews.java:256)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

`

Adding the following to the 'convert' method fixes this particular problem, but seeing problems with other data types. 
`        if (type instanceof Types.IntegerType) {
            return Long.parseLong(value.toString());
        }`

**Comment by anjalinorwood** [comment]
We started seeing this issue and failures in materialized view tests because stats calculator failures were not propagated. This commit https://github.com/prestosql/presto/commit/28095d9fff8d1df49eb13f3f2d60b6ede35e46a9 started propagating failures exposing this issue.

**Comment by findepi** [comment]
> . This commit [28095d9](https://github.com/prestosql/presto/commit/28095d9fff8d1df49eb13f3f2d60b6ede35e46a9) started propagating failures exposing this issue.

Yet another benefit of that change.

**Comment by anjalinorwood** [comment]
https://github.com/prestosql/presto/pull/5942

**Comment by findepi** [comment]
Maybe fixed by https://github.com/trinodb/trino/pull/8616 .
