### ISSUE TITLE
Flaky test TestEventListener.testPlanningFailure

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#5922]
https://github.com/prestosql/presto/runs/1386057381

```
2020-11-11T16:45:57.6822217Z [ERROR] Tests run: 2082, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 2,162.941 s <<< FAILURE! - in TestSuite
2020-11-11T16:45:57.6823688Z [ERROR] testPlanningFailure(io.prestosql.execution.TestEventListener)  Time elapsed: 0.019 s  <<< FAILURE!
2020-11-11T16:45:57.6825688Z java.lang.IllegalArgumentException: expected one element but was: <io.prestosql.spi.eventlistener.QueryCompletedEvent@7142368e, io.prestosql.spi.eventlistener.QueryCompletedEvent@4b216d17>
2020-11-11T16:45:57.6827721Z 	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:315)
2020-11-11T16:45:57.6829025Z 	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:254)
2020-11-11T16:45:57.6830576Z 	at io.prestosql.execution.TestEventListener.assertFailedQuery(TestEventListener.java:243)
2020-11-11T16:45:57.6832346Z 	at io.prestosql.execution.TestEventListener.assertFailedQuery(TestEventListener.java:235)
2020-11-11T16:45:57.6834519Z 	at io.prestosql.execution.TestEventListener.testPlanningFailure(TestEventListener.java:164)
2020-11-11T16:45:57.6839232Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-11-11T16:45:57.6846082Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-11-11T16:45:57.6854238Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-11T16:45:57.6860892Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-11-11T16:45:57.6869367Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-11-11T16:45:57.6876055Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-11-11T16:45:57.6881417Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-11-11T16:45:57.6886531Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-11-11T16:45:57.6892121Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-11-11T16:45:57.6897339Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-11-11T16:45:57.6904472Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-11-11T16:45:57.6912367Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-11-11T16:45:57.6917184Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
cc @losipiuk (https://github.com/prestosql/presto/pull/5815 related?)

**Comment by losipiuk** [comment]
> cc @losipiuk (#5815 related?)

I would expect so. I actually saw it once, but could not repro locally. Will try more.

**Comment by losipiuk** [comment]
![image](https://user-images.githubusercontent.com/890111/98945348-b1e20f80-24f2-11eb-82a4-152517e834c4.png)

damn

**Comment by sopel39** [comment]
https://github.com/prestosql/presto/pull/5949/checks?check_run_id=1395236336

**Comment by losipiuk** [comment]
Fixed by https://github.com/prestosql/presto/pull/5944

**Comment by lukasz-walkiewicz** [comment]
I'm afraid it's still flaky: https://github.com/prestosql/presto/pull/5355/checks?check_run_id=1472968160

```
2020-11-30T10:22:50.1440796Z [ERROR] Tests run: 2086, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 2,166.121 s <<< FAILURE! - in TestSuite
2020-11-30T10:22:50.1461232Z [ERROR] testPlanningFailure(io.prestosql.execution.TestEventListenerBasic)  Time elapsed: 1.039 s  <<< FAILURE!
2020-11-30T10:22:50.1469840Z java.lang.IllegalArgumentException: expected one element but was: <QueryCompletedEvent[queryId='20201130_101733_00008_x6yan', queryState='FAILED'], QueryCompletedEvent[queryId='20201130_101733_00008_x6yan', queryState='FAILED']>
2020-11-30T10:22:50.1477318Z 	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:315)
2020-11-30T10:22:50.1488719Z 	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:254)
2020-11-30T10:22:50.1495324Z 	at io.prestosql.execution.TestEventListenerBasic.assertFailedQuery(TestEventListenerBasic.java:224)
2020-11-30T10:22:50.1501657Z 	at io.prestosql.execution.TestEventListenerBasic.assertFailedQuery(TestEventListenerBasic.java:216)
2020-11-30T10:22:50.1510641Z 	at io.prestosql.execution.TestEventListenerBasic.testPlanningFailure(TestEventListenerBasic.java:145)
2020-11-30T10:22:50.1518916Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-11-30T10:22:50.1542029Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-11-30T10:22:50.1548422Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-30T10:22:50.1553249Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-11-30T10:22:50.1559439Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-11-30T10:22:50.1564605Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-11-30T10:22:50.1569327Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-11-30T10:22:50.1574189Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-11-30T10:22:50.1579669Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-11-30T10:22:50.1584511Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-11-30T10:22:50.1590280Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-11-30T10:22:50.1596063Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-11-30T10:22:50.1600972Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-30T10:22:50.1601609Z 
2020-11-30T10:22:50.1665431Z 2020-11-30T04:22:50.166-0600 INFO JVM is shutting down, cleaning up
2020-11-30T10:22:50.1669718Z 2020-11-30T04:22:50.166-0600 INFO Life cycle stopping...
2020-11-30T10:22:50.1674297Z 2020-11-30T04:22:50.167-0600 INFO JVM is shutting down, cleaning up
2020-11-30T10:22:50.1675382Z 2020-11-30T04:22:50.167-0600 INFO Life cycle stopping...
2020-11-30T10:22:50.1706367Z 2020-11-30T04:22:50.170-0600 INFO JVM is shutting down, cleaning up
2020-11-30T10:22:50.1707856Z 2020-11-30T04:22:50.170-0600 INFO Life cycle stopping...
2020-11-30T10:22:50.1713457Z 2020-11-30T04:22:50.170-0600 INFO JVM is shutting down, cleaning up
2020-11-30T10:22:50.1714671Z 2020-11-30T04:22:50.170-0600 INFO JVM is shutting down, cleaning up
2020-11-30T10:22:50.1718506Z 2020-11-30T04:22:50.171-0600 INFO Life cycle stopping...
2020-11-30T10:22:50.1720416Z 2020-11-30T04:22:50.171-0600 INFO JVM is shutting down, cleaning up
2020-11-30T10:22:50.1721967Z 2020-11-30T04:22:50.171-0600 INFO Life cycle stopping...
2020-11-30T10:22:50.1725349Z 2020-11-30T04:22:50.171-0600 INFO JVM is shutting down, cleaning up
2020-11-30T10:22:50.1726463Z 2020-11-30T04:22:50.172-0600 INFO Life cycle stopping...
2020-11-30T10:22:50.1728160Z 2020-11-30T04:22:50.172-0600 INFO Life cycle stopping...
2020-11-30T10:22:53.2979565Z [INFO] 
2020-11-30T10:22:53.2980300Z [INFO] Results:
2020-11-30T10:22:53.2980795Z [INFO] 
2020-11-30T10:22:53.2981290Z [ERROR] Failures: 
2020-11-30T10:22:53.3027556Z [ERROR]   TestEventListenerBasic.testPlanningFailure:145->assertFailedQuery:216->assertFailedQuery:224 » IllegalArgument
2020-11-30T10:22:53.3029112Z [INFO] 
2020-11-30T10:22:53.3029651Z [ERROR] Tests run: 2086, Failures: 1, Errors: 0, Skipped: 1
2020-11-30T10:22:53.3030156Z [INFO] 
2020-11-30T10:22:53.3066563Z [INFO] ------------------------------------------------------------------------
2020-11-30T10:22:53.3067476Z [INFO] BUILD FAILURE
2020-11-30T10:22:53.3068461Z [INFO] ------------------------------------------------------------------------
2020-11-30T10:22:53.3080063Z [INFO] Total time:  36:15 min
2020-11-30T10:22:53.3083142Z [INFO] Finished at: 2020-11-30T10:22:53Z
2020-11-30T10:22:53.3084230Z [INFO] ------------------------------------------------------------------------
```

**Comment by losipiuk** [comment]
> I'm afraid it's still flaky

Technically it is very different code path. But outcome similar :/

**Comment by losipiuk** [comment]
Duplicate event stack traces:

1. 
```
2020-12-01T11:35:18.5497996Z java.lang.Throwable
2020-12-01T11:35:18.5500433Z 	at io.prestosql.execution.EventsCollector.addQueryCompleted(EventsCollector.java:79)
2020-12-01T11:35:18.5502980Z 	at io.prestosql.execution.TestingEventListener.queryCompleted(TestingEventListener.java:46)
2020-12-01T11:35:18.5505911Z 	at io.prestosql.testing.TestingEventListenerManager.queryCompleted(TestingEventListenerManager.java:63)
2020-12-01T11:35:18.5509120Z 	at io.prestosql.event.QueryMonitor.queryCompletedEvent(QueryMonitor.java:209)
2020-12-01T11:35:18.5512384Z 	at io.prestosql.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:237)
2020-12-01T11:35:18.5525745Z 	at io.prestosql.execution.QueryStateMachine.lambda$addQueryInfoStateChangeListener$16(QueryStateMachine.java:975)
2020-12-01T11:35:18.5528253Z 	at io.prestosql.execution.StateMachine.fireStateChangedListener(StateMachine.java:241)
2020-12-01T11:35:18.5530338Z 	at io.prestosql.execution.StateMachine.lambda$fireStateChanged$0(StateMachine.java:233)
2020-12-01T11:35:18.5531831Z 	at io.prestosql.$gen.Presto_testversion____20201201_112113_18615.run(Unknown Source)
2020-12-01T11:35:18.5533266Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-12-01T11:35:18.5535154Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-12-01T11:35:18.5536390Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

2.

```
2020-12-01T11:35:18.5539965Z java.lang.Throwable
2020-12-01T11:35:18.5541390Z 	at io.prestosql.execution.EventsCollector.addQueryCompleted(EventsCollector.java:79)
2020-12-01T11:35:18.5545103Z 	at io.prestosql.execution.TestingEventListener.queryCompleted(TestingEventListener.java:46)
2020-12-01T11:35:18.5548112Z 	at io.prestosql.testing.TestingEventListenerManager.queryCompleted(TestingEventListenerManager.java:63)
2020-12-01T11:35:18.5551009Z 	at io.prestosql.event.QueryMonitor.queryImmediateFailureEvent(QueryMonitor.java:152)
2020-12-01T11:35:18.5553309Z 	at io.prestosql.dispatcher.DispatchManager.lambda$queryCreated$2(DispatchManager.java:256)
2020-12-01T11:35:18.5555004Z 	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:519)
2020-12-01T11:35:18.5556544Z 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
2020-12-01T11:35:18.5557956Z 	at io.prestosql.$gen.Presto_testversion____20201201_112113_18615.run(Unknown Source)
2020-12-01T11:35:18.5559414Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-12-01T11:35:18.5561292Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-12-01T11:35:18.5562561Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by losipiuk** [comment]
I think the reason for flakiness here is race on execution of listeners registered via `stateMachine.addStateChangeListener`. So listener for `QueryState.FAILED` is executed before listener for state `QueryState.PLANNING`.

As a result the code in `LocalDispatchQuery()`:
```java
        stateMachine.addStateChangeListener(state -> {
            if (state == QueryState.FAILED) {
                // if query is failed and dispatching was not finished yet, marking dispatching as failed
                submitted.set(FAILED);
                queryExecutionFuture.cancel(true);
            }

            if (state.ordinal() > QueryState.DISPATCHING.ordinal()) {
                // we went past dispatching phase; marking submitted as successful
                submitted.set(DISPATCHED);
            }
        });
```
assumes that query was not dispatched yet and sends completion event itself.
Then the event completion listener registered in `SqlQueryManager.createQuery` triggers.

**Comment by losipiuk** [comment]
Fix attempt: https://github.com/prestosql/presto/pull/6185

**Comment by findepi** [comment]
Thanks @dain for the fix

**Comment by dain** [comment]
I'm not sure this is fixed.  I saw a repo in a PR and it had the new message I added.  It said there were no events at all.
