### ISSUE TITLE
Product tests launcher hung before running product tets

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#6117]
```
2020-11-27T05:38:54.0003490Z 2020-11-27T05:38:53.999Z	INFO	main	org.testcontainers.dockerclient.DockerClientProviderStrategy	Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
2020-11-27T05:38:54.0016310Z 2020-11-27T05:38:54.001Z	INFO	main	org.testcontainers.DockerClientFactory	Docker host IP address is localhost
2020-11-27T05:38:54.0287609Z 2020-11-27T05:38:54.028Z	INFO	main	org.testcontainers.DockerClientFactory	Connected to docker: 
2020-11-27T05:38:54.0289401Z   Server Version: 19.03.11
2020-11-27T05:38:54.0290275Z   API Version: 1.40
2020-11-27T05:38:54.0291263Z   Operating System: Ubuntu 18.04.5 LTS
2020-11-27T05:38:54.0292264Z   Total Memory: 63525 MB
2020-11-27T05:38:54.0316568Z 2020-11-27T05:38:54.031Z	INFO	main	org.testcontainers.utility.ImageNameSubstitutor	Image name substitution will be performed by: DefaultImageNameSubstitutor (ConfigurationFileImageNameSubstitutor)
2020-11-27T07:23:43.4007331Z 2020-11-27T07:23:43.399Z	WARN	TestRun-diagnostic	io.prestosql.tests.product.launcher.cli.SuiteRun	Test execution is not finished yet, a deadlock or hang is suspected. Thread dump will follow.
2020-11-27T07:23:43.4362744Z 2020-11-27T07:23:43.435Z	WARN	TestRun-diagnostic	io.prestosql.tests.product.launcher.cli.SuiteRun	Full Thread Dump:
2020-11-27T07:23:43.4365144Z "main" prio=5 Id=1 RUNNABLE
2020-11-27T07:23:43.4367115Z 	at app//org.testcontainers.shaded.okio.Buffer.indexOf(Buffer.java:1463)
2020-11-27T07:23:43.4370833Z 	at app//org.testcontainers.shaded.okio.RealBufferedSource.indexOf(RealBufferedSource.java:352)
2020-11-27T07:23:43.4375792Z 	at app//org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
2020-11-27T07:23:43.4381590Z 	at app//org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:224)
2020-11-27T07:23:43.4387397Z 	at app//org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.java:489)
2020-11-27T07:23:43.4393453Z 	at app//org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471)
2020-11-27T07:23:43.4398143Z 	at app//org.testcontainers.shaded.okhttp3.internal.Util.skipAll(Util.java:204)
2020-11-27T07:23:43.4401759Z 	at app//org.testcontainers.shaded.okhttp3.internal.Util.discard(Util.java:186)
2020-11-27T07:23:43.4403941Z 	...
2020-11-27T07:23:43.4404394Z 
2020-11-27T07:23:43.4404839Z 
2020-11-27T07:23:43.4405845Z "Reference Handler" daemon prio=10 Id=2 RUNNABLE
2020-11-27T07:23:43.4408277Z 	at java.base@11.0.9/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
2020-11-27T07:23:43.4411685Z 	at java.base@11.0.9/java.lang.ref.Reference.processPendingReferences(Reference.java:241)
2020-11-27T07:23:43.4414434Z 	at java.base@11.0.9/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)
2020-11-27T07:23:43.4415701Z 
2020-11-27T07:23:43.4416149Z 
2020-11-27T07:23:43.4417639Z "Finalizer" daemon prio=8 Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@acc5456
2020-11-27T07:23:43.4419557Z 	at java.base@11.0.9/java.lang.Object.wait(Native Method)
2020-11-27T07:23:43.4421911Z 	-  waiting on java.lang.ref.ReferenceQueue$Lock@acc5456
2020-11-27T07:23:43.4424147Z 	at java.base@11.0.9/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
2020-11-27T07:23:43.4426781Z 	at java.base@11.0.9/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
2020-11-27T07:23:43.4429211Z 	at java.base@11.0.9/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)
2020-11-27T07:23:43.4430444Z 
2020-11-27T07:23:43.4430896Z 
2020-11-27T07:23:43.4431879Z "Signal Dispatcher" daemon prio=9 Id=4 RUNNABLE
2020-11-27T07:23:43.4432648Z 
2020-11-27T07:23:43.4433105Z 
2020-11-27T07:23:43.4434978Z "Common-Cleaner" daemon prio=8 Id=11 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@a486f20
2020-11-27T07:23:43.4436949Z 	at java.base@11.0.9/java.lang.Object.wait(Native Method)
2020-11-27T07:23:43.4439225Z 	-  waiting on java.lang.ref.ReferenceQueue$Lock@a486f20
2020-11-27T07:23:43.4441446Z 	at java.base@11.0.9/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
2020-11-27T07:23:43.4443912Z 	at java.base@11.0.9/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
2020-11-27T07:23:43.4446000Z 	at java.base@11.0.9/java.lang.Thread.run(Thread.java:834)
2020-11-27T07:23:43.4448147Z 	at java.base@11.0.9/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)
2020-11-27T07:23:43.4449614Z 
2020-11-27T07:23:43.4450061Z 
2020-11-27T07:23:43.4451407Z "TestRun-diagnostic" daemon prio=5 Id=15 RUNNABLE
2020-11-27T07:23:43.4453477Z 	at java.management@11.0.9/sun.management.ThreadImpl.dumpThreads0(Native Method)
2020-11-27T07:23:43.4456305Z 	at java.management@11.0.9/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
2020-11-27T07:23:43.4459260Z 	at java.management@11.0.9/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
2020-11-27T07:23:43.4463001Z 	at app//io.prestosql.tests.product.launcher.cli.SuiteRun$Execution.reportSuspectedTimeout(SuiteRun.java:326)
2020-11-27T07:23:43.4466876Z 	at app//io.prestosql.tests.product.launcher.cli.SuiteRun$Execution.lambda$call$0(SuiteRun.java:180)
2020-11-27T07:23:43.4470374Z 	at app//io.prestosql.tests.product.launcher.cli.SuiteRun$Execution$$Lambda$333/0x0000000100261c40.run(Unknown Source)
2020-11-27T07:23:43.4473431Z 	at java.base@11.0.9/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-11-27T07:23:43.4475932Z 	at java.base@11.0.9/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-11-27T07:23:43.4477477Z 	...
2020-11-27T07:23:43.4477928Z 
2020-11-27T07:23:43.4478841Z 	Number of locked synchronizers = 1
2020-11-27T07:23:43.4480891Z 	- java.util.concurrent.ThreadPoolExecutor$Worker@2424686b
2020-11-27T07:23:43.4482172Z 
2020-11-27T07:23:43.4482608Z 
2020-11-27T07:23:43.4485284Z "FailsafeDelayScheduler" daemon prio=5 Id=16 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@5a611e6f
2020-11-27T07:23:43.4488592Z 	at java.base@11.0.9/jdk.internal.misc.Unsafe.park(Native Method)
2020-11-27T07:23:43.4491781Z 	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@5a611e6f
2020-11-27T07:23:43.4495322Z 	at java.base@11.0.9/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
2020-11-27T07:23:43.4499621Z 	at java.base@11.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
2020-11-27T07:23:43.4504723Z 	at java.base@11.0.9/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
2020-11-27T07:23:43.4509480Z 	at java.base@11.0.9/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
2020-11-27T07:23:43.4513626Z 	at java.base@11.0.9/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
2020-11-27T07:23:43.4517372Z 	at java.base@11.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
2020-11-27T07:23:43.4520847Z 	at java.base@11.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-11-27T07:23:43.4522762Z 	...
2020-11-27T07:23:43.4523236Z 
2020-11-27T07:23:43.4523670Z 
2020-11-27T07:23:43.4526996Z "OkHttp ConnectionPool" daemon prio=5 Id=19 TIMED_WAITING on org.testcontainers.shaded.okhttp3.internal.connection.RealConnectionPool@5e4bce6b
2020-11-27T07:23:43.4530736Z 	at java.base@11.0.9/java.lang.Object.wait(Native Method)
2020-11-27T07:23:43.4534557Z 	-  waiting on org.testcontainers.shaded.okhttp3.internal.connection.RealConnectionPool@5e4bce6b
2020-11-27T07:23:43.4537995Z 	at java.base@11.0.9/java.lang.Object.wait(Object.java:462)
2020-11-27T07:23:43.4542196Z 	at app//org.testcontainers.shaded.okhttp3.internal.connection.RealConnectionPool.lambda$new$0(RealConnectionPool.java:62)
2020-11-27T07:23:43.4548560Z 	at app//org.testcontainers.shaded.okhttp3.internal.connection.RealConnectionPool$$Lambda$416/0x00000001002ebc40.run(Unknown Source)
2020-11-27T07:23:43.4553257Z 	at java.base@11.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-11-27T07:23:43.4556750Z 	at java.base@11.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-11-27T07:23:43.4559234Z 	at java.base@11.0.9/java.lang.Thread.run(Thread.java:834)
2020-11-27T07:23:43.4560138Z 
2020-11-27T07:23:43.4561031Z 	Number of locked synchronizers = 1
2020-11-27T07:23:43.4563173Z 	- java.util.concurrent.ThreadPoolExecutor$Worker@4ee502e5
2020-11-27T07:23:43.4564464Z 
2020-11-27T07:23:43.4564902Z 
2020-11-27T07:23:43.4566448Z "docker-java-stream-1824481532" daemon prio=5 Id=21 RUNNABLE
2020-11-27T07:23:43.4568831Z 	at app//org.testcontainers.shaded.okio.Buffer.getByte(Buffer.java:312)
2020-11-27T07:23:43.4573545Z 	at app//org.testcontainers.shaded.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:310)
2020-11-27T07:23:43.4579797Z 	at app//org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.java:492)
2020-11-27T07:23:43.4585799Z 	at app//org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471)
2020-11-27T07:23:43.4591145Z 	at app//org.testcontainers.shaded.okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
2020-11-27T07:23:43.4595525Z 	at app//org.testcontainers.shaded.okio.RealBufferedSource$1.read(RealBufferedSource.java:436)
2020-11-27T07:23:43.4601413Z 	at app//org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:30)
2020-11-27T07:23:43.4609104Z 	at app//org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:12)
2020-11-27T07:23:43.4613263Z 	...
2020-11-27T07:23:43.4613734Z 
2020-11-27T07:23:43.4614166Z 
2020-11-27T07:23:43.4615971Z "testcontainers-ryuk" daemon prio=5 Id=22 TIMED_WAITING on java.util.ArrayList@36cd4f10
2020-11-27T07:23:43.4617882Z 	at java.base@11.0.9/java.lang.Object.wait(Native Method)
2020-11-27T07:23:43.4619630Z 	-  waiting on java.util.ArrayList@36cd4f10
2020-11-27T07:23:43.4622160Z 	at app//org.testcontainers.utility.ResourceReaper.lambda$null$1(ResourceReaper.java:142)
2020-11-27T07:23:43.4625358Z 	at app//org.testcontainers.utility.ResourceReaper$$Lambda$479/0x0000000100424c40.run(Unknown Source)
2020-11-27T07:23:43.4628653Z 	at app//org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
2020-11-27T07:23:43.4632275Z 	at app//org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:133)
2020-11-27T07:23:43.4635450Z 	at app//org.testcontainers.utility.ResourceReaper$$Lambda$478/0x0000000100424840.run(Unknown Source)
2020-11-27T07:23:43.4637640Z 	at java.base@11.0.9/java.lang.Thread.run(Thread.java:834)
2020-11-27T07:23:43.4638529Z 
2020-11-27T07:23:43.4638982Z 
2020-11-27T07:33:57.1586278Z ##[error]The operation was canceled.
```

**Comment by kokosing** [comment]
@findepi Thank you for thread dump!

**Comment by kokosing** [comment]
This one looks like the most interesting, however I see `...` which are not helpful.

```
2020-11-27T07:23:43.4365144Z "main" prio=5 Id=1 RUNNABLE
2020-11-27T07:23:43.4367115Z 	at app//org.testcontainers.shaded.okio.Buffer.indexOf(Buffer.java:1463)
2020-11-27T07:23:43.4370833Z 	at app//org.testcontainers.shaded.okio.RealBufferedSource.indexOf(RealBufferedSource.java:352)
2020-11-27T07:23:43.4375792Z 	at app//org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
2020-11-27T07:23:43.4381590Z 	at app//org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:224)
2020-11-27T07:23:43.4387397Z 	at app//org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.java:489)
2020-11-27T07:23:43.4393453Z 	at app//org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471)
2020-11-27T07:23:43.4398143Z 	at app//org.testcontainers.shaded.okhttp3.internal.Util.skipAll(Util.java:204)
2020-11-27T07:23:43.4401759Z 	at app//org.testcontainers.shaded.okhttp3.internal.Util.discard(Util.java:186)
2020-11-27T07:23:43.4403941Z 	...
```

@wendigo Is this anyhow familiar to you?

**Comment by wendigo** [comment]
@kokosing I came across such behavior locally and it was always due to Docker hanging (issuing other commands like `docker ps` would also hang).

**Comment by kokosing** [comment]
Oh. I got such issues when I was stressing local docker. Usually restart helps. So it is more infrastructure issue, not the tests code itself.

**Comment by wendigo** [comment]
Let's close this issue.
