### ISSUE TITLE
Support public S3 bucket access (unsigned requests/anonymousCredentials)

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#6127]
1. - https://github.com/prestosql/presto/pull/6131  for below:

how to make presto read data from a public s3 bucket? ie the details on https://registry.opendata.aws/deutsche-boerse-pds/.  when I try to create external table it complains that s3 access key/secret key must be provided. But AWS CLI commands work

"We would need equivalent of --no-sign-request probably"

Some research:
https://issues.apache.org/jira/browse/HADOOP-13237
https://github.com/aws/aws-sdk-java/issues/1122

My guess would be https://github.com/prestosql/presto/blob/347/presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java#L891 adding a check if certain config set then use AnonymousAWSCredentialsProvider

2. hive.s3.endpoint=https://s3.amazonaws.com or not setting hive.s3.endpoint solves below:

Different public datasets are in different regions. ie https://registry.opendata.aws/rapid7-fdns-any/ and https://registry.opendata.aws/fsf-flood-risk/
a) creating a separate presto catalog per s3 region does not feel right. It can lead to a clutter of catalogs being setup (with less than 5 tables each catalog), need to bounce presto server and users will need to lookup system.jdbc.tables to know which public dataset belongs to each catalog, whereas if CREATE TABLE syntax accepted s3 region argument then there could be single presto catalog for all s3 datasets. Or 2nd-best would be one presto catalog for company's private s3 (let's assume its single region) and a different catalog for public s3 (can be across many regions, ie us-west-2, us-east-1, eu-central-1..etc)
b) perhaps defining region can be completely optional? ie aws s3 ls s3://deutsche-boerse-eurex-pds/ --no-sign-request works without specifying any region

3. - https://github.com/prestosql/presto/pull/6182 for below:

this particular dataset does not follow hive style partitioning ie it uses s3://deutsche-boerse-eurex-pds/2020-11-26/ instead of s3://deutsche-boerse-eurex-pds/mystringcolumnname=2020-11-26/
can presto still interpret all these partitions positionally ie if it is one folder deep and my table DDL has partitioned_by = ARRAY['mystringcolumnname']? using single command to sync all partitions, else I can fallback to manual ADD PARTITION for each one with full path

APPENDIX for point 1
1. trying to create table in hiveserver2
Error: org.apache.hive.service.cli.HiveSQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain)
	at org.apache.hive.service.cli.operation.Operation.toSQLException(Operation.java:380)
	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:257)
	at org.apache.hive.service.cli.operation.SQLOperation.access$800(SQLOperation.java:91)
	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork$1.run(SQLOperation.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork.run(SQLOperation.java:362)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain)
	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:862)
	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:867)
	at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:4356)
	at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:354)
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:199)
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:100)
	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:2183)
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1839)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1526)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1237)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1232)
	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:255)
	... 11 more
Caused by: MetaException(message:com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:42070)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:42038)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result.read(ThriftHiveMetastore.java:41964)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_table_with_environment_context(ThriftHiveMetastore.java:1199)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_table_with_environment_context(ThriftHiveMetastore.java:1185)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.create_table_with_environment_context(HiveMetaStoreClient.java:2399)
	at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.create_table_with_environment_context(SessionHiveMetaStoreClient.java:93)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:752)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:740)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:173)
	at com.sun.proxy.$Proxy27.createTable(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2330)
	at com.sun.proxy.$Proxy27.createTable(Unknown Source)
	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:852)
	... 22 more (state=08S01,code=1)
2. add <property>
        <name>fs.s3a.aws.credentials.provider</name>
        <value>org.apache.hadoop.fs.s3a.AnonymousAWSCredentialsProvider</value>
      </property> to hive-site.xml
3. create table in hiveserver2 and select from table in hiveserver2 works
4. select from table in presto gives this error:
io.prestosql.spi.PrestoException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), com.amazonaws.auth.profile.ProfileCredentialsProvider@1037c40f: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@28877425: Unable to load credentials from service endpoint]
        	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:207)
        	at io.prestosql.plugin.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)
        	at io.prestosql.plugin.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)
        	at io.prestosql.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)
        	at io.prestosql.$gen.Presto_318____20201128_084331_1.run(Unknown Source)
        	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
        	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        	at java.lang.Thread.run(Thread.java:748)
        Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), com.amazonaws.auth.profile.ProfileCredentialsProvider@1037c40f: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@28877425: Unable to load credentials from service endpoint]
        	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:136)
        	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1225)
        	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:801)
        	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:751)
        	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
        	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
        	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
        	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
        	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
        	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
        	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4921)
        	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4867)
        	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4861)
        	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:880)
        	at io.prestosql.plugin.hive.s3.PrestoS3FileSystem.listPrefix(PrestoS3FileSystem.java:524)
        	at io.prestosql.plugin.hive.s3.PrestoS3FileSystem.access$000(PrestoS3FileSystem.java:132)
        	at io.prestosql.plugin.hive.s3.PrestoS3FileSystem$1.<init>(PrestoS3FileSystem.java:304)
        	at io.prestosql.plugin.hive.s3.PrestoS3FileSystem.listLocatedStatus(PrestoS3FileSystem.java:302)
        	at org.apache.hadoop.fs.FilterFileSystem.listLocatedStatus(FilterFileSystem.java:283)
        	at io.prestosql.plugin.hive.CachingDirectoryLister.list(CachingDirectoryLister.java:81)
        	at io.prestosql.plugin.hive.util.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:134)
        	at io.prestosql.plugin.hive.util.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:122)
        	at io.prestosql.plugin.hive.util.HiveFileIterator.getLocatedFileStatusRemoteIterator(HiveFileIterator.java:111)
        	at io.prestosql.plugin.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:104)
        	at io.prestosql.plugin.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:38)
        	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
        	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
        	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
        	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:295)
        	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:207)
        	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:162)
        	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:301)
        	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
        	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:274)
        	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:100)
        	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:200)
        	... 8 more
5. try create within presto gives:
      io.prestosql.spi.PrestoException: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified by setting the fs.s3.awsAccessKeyId and fs.s3.awsSecretAccessKey properties (respectively).
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.createTable(ThriftHiveMetastore.java:862)
	at io.prestosql.plugin.hive.metastore.thrift.BridgingHiveMetastore.createTable(BridgingHiveMetastore.java:164)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.createTable(CachingHiveMetastore.java:431)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.createTable(CachingHiveMetastore.java:431)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore$CreateTableOperation.run(SemiTransactionalHiveMetastore.java:2404)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeAddTableOperations(SemiTransactionalHiveMetastore.java:1424)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.access$1000(SemiTransactionalHiveMetastore.java:1043)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:986)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:891)
	at io.prestosql.plugin.hive.HiveMetadata.commit(HiveMetadata.java:2212)
	at io.prestosql.plugin.hive.HiveConnector.commit(HiveConnector.java:198)
	at io.prestosql.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:595)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified by setting the fs.s3.awsAccessKeyId and fs.s3.awsSecretAccessKey properties (respectively).
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:52658)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:52626)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_result.read(ThriftHiveMetastore.java:52552)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_table(ThriftHiveMetastore.java:1490)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_table(ThriftHiveMetastore.java:1477)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.createTable(ThriftHiveMetastoreClient.java:135)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$createTable$36(ThriftHiveMetastore.java:850)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
	at io.prestosql.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.createTable(ThriftHiveMetastore.java:848)
	... 19 more

https://github.com/verdict-project/docker-presto-with-hadoop used for the experiments since Hadoop 2.8 minimum required

**Comment by metadaddy** [comment]
@tooptoop4 I discovered a configuration that allows anonymous access to public S3 buckets, no code changes required:

https://github.com/trinodb/trino/pull/15246#issuecomment-1332607435

If this works for you, I think we can close this issue. I'll open an issue and create a PR at https://github.com/trinodb/docs.trino.io
