### ISSUE TITLE
SSL errors after updating OkHttp to a version >= 3.10.0

### ISSUE THREAD

**Issue by lukasz-walkiewicz** [trinodb/trino#6172]
After upgrading the OkHttp library to a version >= 3.10.0 presto-jdbc no longer resolves certificates using it's `CN` field due to deprecation of the fall back mechanism.
```
   New: Don’t fall back to common name (CN) verification for hostnames.
   This behavior was deprecated with RFC 2818 in May 2000 and was 
   recently dropped from major web browsers.
```
According to the RFC:
```
   If a subjectAltName extension of type dNSName is present, that MUST
   be used as the identity. Otherwise, the (most specific) Common Name
   field in the Subject field of the certificate MUST be used. Although
   the use of the Common Name is existing practice, it is deprecated and
   Certification Authorities are encouraged to use the dNSName instead.
```
For example: an exception from a product test after updating the library to 3.14.9 (the newest 3.x.x version):
```
tests               | 2020-12-02 01:14:02 SEVERE: Failure cause:
tests               | java.lang.RuntimeException: java.sql.SQLException: Error executing query
tests               | 	at io.prestosql.tests.hive.TestHiveStorageFormats.setAdminRole(TestHiveStorageFormats.java:585)
tests               | 	at io.prestosql.tests.hive.TestHiveStorageFormats.setAdminRole(TestHiveStorageFormats.java:572)
tests               | 	at io.prestosql.tests.hive.TestHiveStorageFormats.testInsertIntoTable(TestHiveStorageFormats.java:109)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
tests               | Caused by: java.sql.SQLException: Error executing query
tests               | 	at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:274)
tests               | 	at io.prestosql.jdbc.PrestoStatement.execute(PrestoStatement.java:227)
tests               | 	at io.prestosql.tests.utils.JdbcDriverUtils.setRole(JdbcDriverUtils.java:29)
tests               | 	at io.prestosql.tests.hive.TestHiveStorageFormats.setAdminRole(TestHiveStorageFormats.java:582)
tests               | 	... 15 more
tests               | Caused by: java.io.UncheckedIOException: javax.net.ssl.SSLPeerUnverifiedException: Hostname presto-master.docker.cluster not verified:
tests               |     certificate: sha256/nqKmtqtHhs51BdYnTNMtdovsu+DksPMexDKtRBW97Yc=
tests               |     DN: CN=*.docker.cluster, OU=, O=, L=, ST=, C=
tests               |     subjectAltNames: []
tests               | 	at io.prestosql.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:154)
tests               | 	at io.prestosql.jdbc.$internal.client.StatementClientV1.<init>(StatementClientV1.java:135)
tests               | 	at io.prestosql.jdbc.$internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24)
tests               | 	at io.prestosql.jdbc.QueryExecutor.startQuery(QueryExecutor.java:46)
tests               | 	at io.prestosql.jdbc.PrestoConnection.startQuery(PrestoConnection.java:728)
tests               | 	at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:239)
tests               | 	... 18 more
tests               | Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname presto-master.docker.cluster not verified:
tests               |     certificate: sha256/nqKmtqtHhs51BdYnTNMtdovsu+DksPMexDKtRBW97Yc=
tests               |     DN: CN=*.docker.cluster, OU=, O=, L=, ST=, C=
tests               |     subjectAltNames: []
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:350)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
tests               | 	at io.prestosql.jdbc.$internal.client.SpnegoHandler.intercept(SpnegoHandler.java:123)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
tests               | 	at io.prestosql.jdbc.$internal.client.OkHttpUtil.lambda$userAgent$0(OkHttpUtil.java:71)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
tests               | 	at io.prestosql.jdbc.$internal.okhttp3.RealCall.execute(RealCall.java:81)
tests               | 	at io.prestosql.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:131)
tests               | 	... 23 more
```
I've prepared a PR (#6151) in which I've fixed this for product tests by regenerating the certificate and adding `*.docker.cluster` value to the `SAN` field but this means that all of Presto users have to do the same if they're using the deprecated fall back mechanism (whether they know about it or not). Merging this PR may break many environments so I'm opening up this issue to start a discussion about possible solutions mitigating this problem.

**Comment by kokosing** [comment]
@lukasz-walkiewicz Please correct me if I am wrong. The recommended way (of not using `CN` when resolving certificates) is also supported and we could possibly update our tests without updating Okhttp library. If is true, then we are not sure how many Presto users were using this actually. It might be that it is not a problem actually as there are not many such users.

If so can we update tests to use newer certificates without updating Okhttp?

**Comment by lukasz-walkiewicz** [comment]
> @lukasz-walkiewicz Please correct me if I am wrong. The recommended way (of not using `CN` when resolving certificates) is also supported and we could possibly update our tests without updating Okhttp library. If is true, then we are not sure how many Presto users were using this actually. It might be that it is not a problem actually as there are not many such users.
> 
> If so can we update tests to use newer certificates without updating Okhttp?

Yes, that's correct. Updating the OkHttp library is optional.

**Comment by electrum** [comment]
Do other tools like `curl` work with `CN`?

**Comment by electrum** [comment]
It looks like `curl` does not work:
```bash
keytool -export -storepass 123456 -alias docker.cluster -file mydomain.der -keystore /docker/presto-product-tests/conf/presto/etc/docker.cluster.jks
openssl x509 -inform der -in mydomain.der -out certificate.pem
curl --cacert certificate.pem -v https://172.18.0.5:7778/
```
```
* About to connect() to 172.18.0.5 port 7778 (#0)
*   Trying 172.18.0.5...
* Connected to 172.18.0.5 (172.18.0.5) port 7778 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: certificate.pem
  CApath: none
* Server certificate:
* 	subject: CN=*.docker.cluster,OU=,O=,L=,ST=,C=
* 	start date: Dec 08 16:03:47 2017 GMT
* 	expire date: Sep 23 16:03:47 2291 GMT
* 	common name: *.docker.cluster
* 	issuer: CN=*.docker.cluster,OU=,O=,L=,ST=,C=
* NSS error -12276 (SSL_ERROR_BAD_CERT_DOMAIN)
* Unable to communicate securely with peer: requested domain name does not match the server's certificate.
* Closing connection 0
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.
```

**Comment by electrum** [comment]
It looks like `curl` works here:
```
$ keytool -export -storepass 123456 -alias docker.cluster -file mydomain.der -keystore /docker/presto-product-
tests/conf/presto/etc/docker.cluster.jks

$ openssl x509 -inform der -in mydomain.der -out certificate.pem

$ curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets 

curl --cacert certificate.pem -v https://presto-master.docker.cluster:7778/v1/info
* About to connect() to presto-master.docker.cluster port 7778 (#0)
*   Trying 172.18.0.5...
* Connected to presto-master.docker.cluster (172.18.0.5) port 7778 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: certificate.pem
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=*.docker.cluster,OU=,O=,L=,ST=,C=
* 	start date: Dec 08 16:03:47 2017 GMT
* 	expire date: Sep 23 16:03:47 2291 GMT
* 	common name: *.docker.cluster
* 	issuer: CN=*.docker.cluster,OU=,O=,L=,ST=,C=
> GET /v1/info HTTP/1.1
> User-Agent: curl/7.29.0
> Host: presto-master.docker.cluster:7778
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 07 Jan 2021 01:14:24 GMT
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< Vary: Accept-Encoding, User-Agent
< Content-Length: 120
< 
{"nodeVersion":{"version":"351-1-g0e5ff00"},"environment":"test","coordinator":true,"starting":false,"uptime":"26.45m"}
* Connection #0 to host presto-master.docker.cluster left intact
```

**Comment by kokosing** [comment]
> It looks like curl works here:

Is this prevents us from upgrade?

**Comment by kokosing** [comment]
Fixed with: https://github.com/trinodb/trino/pull/6540

**Comment by dyhyao6** [comment]
https://github.com/trinodb/trino/issues/6780#issue-798016277能帮我解决这个问题吗？谢谢 @kokosing @electrum
