### ISSUE TITLE
testDoubleNaNInfinity(io.prestosql.plugin.hive.parquet.TestFullParquetReader) maxCapacityHint can't be less than initialSlabSize

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#6193]
```
testDoubleNaNInfinity(io.prestosql.plugin.hive.parquet.TestFullParquetReader)  Time elapsed: 0.424 s  <<< FAILURE!
java.lang.IllegalArgumentException: maxCapacityHint can't be less than initialSlabSize 1024 100
	at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:53)
	at org.apache.parquet.bytes.CapacityByteArrayOutputStream.<init>(CapacityByteArrayOutputStream.java:153)
	at org.apache.parquet.column.values.plain.PlainValuesWriter.<init>(PlainValuesWriter.java:47)
	at org.apache.parquet.column.values.factory.DefaultV2ValuesWriterFactory.getDoubleValuesWriter(DefaultV2ValuesWriterFactory.java:107)
	at org.apache.parquet.column.values.factory.DefaultV2ValuesWriterFactory.newValuesWriter(DefaultV2ValuesWriterFactory.java:68)
	at org.apache.parquet.column.values.factory.DefaultValuesWriterFactory.newValuesWriter(DefaultValuesWriterFactory.java:52)
	at org.apache.parquet.column.ParquetProperties.newValuesWriter(ParquetProperties.java:149)
	at org.apache.parquet.column.impl.ColumnWriterBase.<init>(ColumnWriterBase.java:66)
	at org.apache.parquet.column.impl.ColumnWriterV2.<init>(ColumnWriterV2.java:59)
	at org.apache.parquet.column.impl.ColumnWriteStoreV2.createColumnWriter(ColumnWriteStoreV2.java:35)
	at org.apache.parquet.column.impl.ColumnWriteStoreBase.<init>(ColumnWriteStoreBase.java:94)
	at org.apache.parquet.column.impl.ColumnWriteStoreV2.<init>(ColumnWriteStoreV2.java:30)
	at org.apache.parquet.column.ParquetProperties.newColumnWriteStore(ParquetProperties.java:182)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:106)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:96)
	at org.apache.parquet.hadoop.ParquetRecordWriter.<init>(ParquetRecordWriter.java:153)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:487)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:416)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:411)
	at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.<init>(ParquetRecordWriterWrapper.java:70)
	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getParquerRecordWriterWrapper(MapredParquetOutputFormat.java:137)
	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getHiveRecordWriter(MapredParquetOutputFormat.java:126)
	at io.prestosql.plugin.hive.parquet.write.TestMapredParquetOutputFormat.getHiveRecordWriter(TestMapredParquetOutputFormat.java:64)
	at io.prestosql.plugin.hive.parquet.ParquetTester.writeParquetColumn(ParquetTester.java:584)
	at io.prestosql.plugin.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:323)
	at io.prestosql.plugin.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:284)
	at io.prestosql.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:203)
	at io.prestosql.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:178)
	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.testDoubleNaNInfinity(AbstractTestParquetReader.java:1490)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by wendigo** [comment]
https://github.com/prestosql/presto/pull/6169/checks?check_run_id=1492249667

**Comment by sopel39** [comment]
fyi @dain

**Comment by losipiuk** [comment]
https://github.com/prestosql/presto/pull/6165

**Comment by findepi** [comment]
https://github.com/trinodb/trino/actions/runs/6265822106/job/17015567492?pr=19060

```
Error:  Tests run: 188, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1337 s <<< FAILURE! -- in TestSuite
Error:  io.trino.plugin.hive.parquet.TestFullParquetReader.testArrayOfArrayOfStructOfArray -- Time elapsed: 0.517 s <<< FAILURE!
java.lang.IllegalArgumentException: maxCapacityHint can't be less than initialSlabSize 1024 100
	at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:97)
	at org.apache.parquet.bytes.CapacityByteArrayOutputStream.<init>(CapacityByteArrayOutputStream.java:153)
	at org.apache.parquet.column.values.plain.PlainValuesWriter.<init>(PlainValuesWriter.java:47)
	at org.apache.parquet.column.values.factory.DefaultV1ValuesWriterFactory.getInt32ValuesWriter(DefaultV1ValuesWriterFactory.java:89)
	at org.apache.parquet.column.values.factory.DefaultV1ValuesWriterFactory.newValuesWriter(DefaultV1ValuesWriterFactory.java:59)
	at org.apache.parquet.column.values.factory.DefaultValuesWriterFactory.newValuesWriter(DefaultValuesWriterFactory.java:52)
	at org.apache.parquet.column.ParquetProperties.newValuesWriter(ParquetProperties.java:167)
	at org.apache.parquet.column.impl.ColumnWriterBase.<init>(ColumnWriterBase.java:84)
	at org.apache.parquet.column.impl.ColumnWriterV1.<init>(ColumnWriterV1.java:43)
	at org.apache.parquet.column.impl.ColumnWriteStoreV1.createColumnWriter(ColumnWriteStoreV1.java:50)
	at org.apache.parquet.column.impl.ColumnWriteStoreBase.<init>(ColumnWriteStoreBase.java:125)
	at org.apache.parquet.column.impl.ColumnWriteStoreV1.<init>(ColumnWriteStoreV1.java:44)
	at org.apache.parquet.column.ParquetProperties.newColumnWriteStore(ParquetProperties.java:220)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:116)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:101)
	at org.apache.parquet.hadoop.ParquetRecordWriter.<init>(ParquetRecordWriter.java:152)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:505)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:432)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:427)
	at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.<init>(ParquetRecordWriterWrapper.java:70)
	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getParquerRecordWriterWrapper(MapredParquetOutputFormat.java:137)
	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getHiveRecordWriter(MapredParquetOutputFormat.java:126)
	at io.trino.plugin.hive.parquet.write.TestingMapredParquetOutputFormat.getHiveRecordWriter(TestingMapredParquetOutputFormat.java:71)
	at io.trino.plugin.hive.parquet.ParquetTester.writeParquetColumn(ParquetTester.java:628)
	at io.trino.plugin.hive.parquet.ParquetTester.assertRoundTripWithHiveWriter(ParquetTester.java:389)
	at io.trino.plugin.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:346)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:305)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:288)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:274)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:248)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:236)
	at io.trino.plugin.hive.parquet.AbstractTestParquetReader.testArrayOfArrayOfStructOfArray(AbstractTestParquetReader.java:274)
```
