### ISSUE TITLE
PushProjectionIntoTableScan  fails with: "Multiple entries with same key"

### ISSUE THREAD

**Issue by wangfeigithub** [trinodb/trino#6200]

**Comment by wangfeigithub** [comment]
When I upgraded PreSTO338 to 344,Here's what happened;
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: @2452f4c3: null=null and @2452f4c3: null=null
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:146)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:109)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:394)
	at io.prestosql.sql.planner.iterative.rule.PushProjectionIntoTableScan.apply(PushProjectionIntoTableScan.java:149)
	at io.prestosql.sql.planner.iterative.rule.PushProjectionIntoTableScan.apply(PushProjectionIntoTableScan.java:56)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:168)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:143)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:115)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:110)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:110)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:110)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:99)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:206)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:195)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:190)
	at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:444)
	at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:424)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:376)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:245)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:139)
	at io.prestosql.$gen.Presto_346____20201204_011754_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by wangfeigithub** [comment]
hi!
Then I tested Presto with 345 and 346, and this error occurred even though my production environment was 338.

**Comment by sopel39** [comment]
cc @martint

**Comment by sopel39** [comment]
Can you share a query that caused this failure?

**Comment by findepi** [comment]
@wangfeigithub we need your help in reproducing the problem.
What is your query and which connector is it using?

**Comment by wangfeigithub** [comment]
Perform the following
![image](https://user-images.githubusercontent.com/29723968/101303312-b04d0280-3878-11eb-992e-5b221bf0ce34.png)

**Comment by wangfeigithub** [comment]
insert into hive.dw.fact_bsc_signbody_log 
select 
    concat('9045', _id) as row_id,
    '20201016' as etl_proc_wid,
    current_timestamp  as w_insert_dt,
    current_timestamp  as w_update_dt,
    '9045' as datasource_num_id,
    'batch' as data_flag,
    null as timezone,
    null as exchange_rate,
    _id as signbody_log_id,
    AccountCode as account_code,
    ChangeType as change_type,
    case cast(ChangeType as varchar) 
        when '0' then '创建'
        when '1' then '编辑'
        when '2' then '状态变更'
        when '3' then '信用额度调整'
    else cast(ChangeType as varchar) end as change_type_val,
    OperationType as operation_type,
    case cast(OperationType as varchar) 
        when '0' then '签约主体变更'
        when '1' then '签约业务更新'
        when '2' then '服务主体更新'
        when '3' then '委托代理协议更新'
        when '4' then '出账周期'
        when '5' then '联系人'
        when '6' then '联系电话'
        when '7' then '联系邮箱'
        when '8' then '公司地址'
        when '9' then '备注信息更新'
        when '10' then '状态变更'
        when '11' then '创建'
        when '12' then '固定额度调整'
        when '13' then '临时额度调整'
        when '14' then '临额期限调整'
        when '15' then '注册地区'
        when '16' then '营业执照'
        when '17' then '税务登记证'
        when '18' then '对账周期'
    else cast(OperationType as varchar) end as operation_type_val,
    cast (UserId as varchar) as user_id,
    UserName as user_name,
    DataFrom as data_from,
    DataTo as data_to,
    IPAddress as ip_address,
    SystemType as system_type,
    AddTime as add_time,
    Remark as remark,
    if(AddTime is null,'190001',substr(regexp_replace(cast(AddTime as varchar), '-' , ''),1,6)) as month_key
from 
    real_mysql.mongodb.sign_body_log   
where AddTime >=date_add('month',-3,date_trunc('month', now()));

**Comment by wangfeigithub** [comment]
CREATE TABLE hive.dw.fact_bsc_signbody_log (
   row_id varchar,
   etl_proc_wid varchar,
   w_insert_dt timestamp(3),
   w_update_dt timestamp(3),
   datasource_num_id varchar,
   data_flag varchar,
   timezone integer,
   exchange_rate decimal(18, 4),
   signbody_log_id varchar,
   account_code varchar,
   change_type integer,
   change_type_val varchar,
   operation_type integer,
   operation_type_val varchar,
   user_id varchar,
   user_name varchar,
   data_from varchar,
   data_to varchar,
   ip_address varchar,
   system_type integer,
   add_time timestamp(3),
   remark varchar,
   month_key varchar
)
WITH (
   format = 'ORC'
)

**Comment by wangfeigithub** [comment]
CREATE TABLE real_mysql.mongodb.sign_body_log (
   _id varchar(255) NOT NULL,
   accountcode varchar(255),
   changetype integer,
   operationtype integer,
   userid integer,
   username varchar(255),
   datafrom varchar(255),
   datato varchar(255),
   remark varchar(255),
   ipaddress varchar(255),
   systemtype integer,
   addtime timestamp(3)
)

this is mysql source

**Comment by wangfeigithub** [comment]
hi,Is this bug being resolved?

**Comment by dreamay** [comment]
Hi,Is this bug being resolved?Did you have resolved the problem?

**Comment by wangfeigithub** [comment]
> Hi,Is this bug being resolved?Did you have resolved the problem?

I am using version 338 here and have not done the upgrade. I do not know whether the community has fixed it or not. You can test the latest version

**Comment by takezoe** [comment]
I got the same error even on the latest Trino which is 356. The simplest queries to reproduce are:

```sql
SELECT null GROUP BY 1, 1;
SELECT null, null GROUP BY 1, 2;
```
As far as I investigated, this error started to happen from this commit: https://github.com/trinodb/trino/commit/edb4b8b12a01d4b5ecad3395b87bc92daa829902

**Comment by findepi** [comment]
@takezoe awesome repro step! i confirm `SELECT null GROUP BY 1, 1;` fails on 356.

note however that this fails in `QueryPlanner` while original stacktrace was for `PushProjectionIntoTableScan` rule 
therefore, @takezoe can you please file a separate issue for this?

**Comment by takezoe** [comment]
@findepi Oh, I see. I will file a new one.

**Comment by takezoe** [comment]
Filed https://github.com/trinodb/trino/issues/8027

**Comment by JamesRTaylor** [comment]
PR that fixes this issue is here: https://github.com/trinodb/trino/pull/9222
