### ISSUE TITLE
Flaky io.prestosql.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter: testExpiredAccessToken, testSuccessfulFlow

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#6223]
```
java.lang.NullPointerException
	at io.prestosql.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.lambda$testExpiredAccessToken$1(TestOAuth2WebUiAuthenticationFilter.java:205)
	at io.prestosql.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.withSuccessfulAuthentication(TestOAuth2WebUiAuthenticationFilter.java:235)
	at io.prestosql.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.testExpiredAccessToken(TestOAuth2WebUiAuthenticationFilter.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by wendigo** [comment]
https://github.com/prestosql/presto/pull/6167/checks?check_run_id=1510122834

**Comment by wendigo** [comment]
cc @kokosing

**Comment by findepi** [comment]
cc @lukasz-walkiewicz

**Comment by electrum** [comment]
https://github.com/prestosql/presto/pull/6289/checks?check_run_id=1533226427

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1539609301

**Comment by kokosing** [comment]
Marked as flaky for now with https://github.com/prestosql/presto/pull/6298.

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/pull/6462/checks?check_run_id=1621491961

**Comment by findepi** [comment]
`testSuccessfulFlow` too

```
Error:  testSuccessfulFlow(io.prestosql.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter)  Time elapsed: 5.844 s  <<< FAILURE!
java.lang.NullPointerException
	at io.prestosql.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.assertPrestoCookie(TestOAuth2WebUiAuthenticationFilter.java:279)
	at io.prestosql.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.lambda$testSuccessfulFlow$0(TestOAuth2WebUiAuthenticationFilter.java:196)
	at io.prestosql.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.withSuccessfulAuthentication(TestOAuth2WebUiAuthenticationFilter.java:238)
	at io.prestosql.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.testSuccessfulFlow(TestOAuth2WebUiAuthenticationFilter.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by wendigo** [comment]
https://github.com/trinodb/trino/pull/6571/checks?check_run_id=1685036783

**Comment by findepi** [comment]
merging https://github.com/trinodb/trino/issues/6632 into this

> https://github.com/trinodb/trino/runs/1721101742?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/1894763778?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/1894763778?check_suite_focus=true 

```
Error:  Tests run: 7311, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,247.356 s <<< FAILURE! - in TestSuite
Error:  testSuccessfulFlow(io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter)  Time elapsed: 6.649 s  <<< FAILURE!
io.jsonwebtoken.ExpiredJwtException: JWT expired at 2021-02-13T14:03:50Z. Current time: 2021-02-13T14:03:50Z, a difference of 92 milliseconds.  Allowed clock skew: 0 milliseconds.
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:385)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:481)
	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:541)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.assertTrinoCookie(TestOAuth2WebUiAuthenticationFilter.java:345)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.lambda$testSuccessfulFlow$0(TestOAuth2WebUiAuthenticationFilter.java:249)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.withSuccessfulAuthentication(TestOAuth2WebUiAuthenticationFilter.java:293)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.testSuccessfulFlow(TestOAuth2WebUiAuthenticationFilter.java:247)
```

**Comment by kokosing** [comment]
@lukasz-walkiewicz The recent one is new, can you please take a look?

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/1935447466

```
Error:  testExpiredAccessToken(io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter)  Time elapsed: 12.538 s  <<< FAILURE!
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for url to match the regex "https://host.testcontainers.internal:34327/ui/". Current url: "http://consent:3000/login?login_challenge=a6282b3a2dc54aaabf64efb7929f52e3" (tried for 5 second(s) with 500 milliseconds interval)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'fv-az180-656', ip: '10.1.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1039-azure', java.version: '11.0.10'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 88.0.4324.96, chrome: {chromedriverVersion: 88.0.4324.96 (68dba2d8a0b14..., userDataDir: /tmp/.com.google.Chrome.tfc7Lc}, goog:chromeOptions: {debuggerAddress: localhost:42011}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 675228b216748c9748dc508e775...}
Session ID: 675228b216748c9748dc508e775b5cc4
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.withSuccessfulAuthentication(TestOAuth2WebUiAuthenticationFilter.java:291)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.testExpiredAccessToken(TestOAuth2WebUiAuthenticationFilter.java:259)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Error:  testSuccessfulFlow(io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter)  Time elapsed: 2.692 s  <<< FAILURE!
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for url to match the regex "https://host.testcontainers.internal:34327/ui/". Current url: "http://consent:3000/login?login_challenge=9af067dad48040aebeff7a82593f2aaa" (tried for 5 second(s) with 500 milliseconds interval)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'fv-az180-656', ip: '10.1.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1039-azure', java.version: '11.0.10'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 88.0.4324.96, chrome: {chromedriverVersion: 88.0.4324.96 (68dba2d8a0b14..., userDataDir: /tmp/.com.google.Chrome.bgSl3g}, goog:chromeOptions: {debuggerAddress: localhost:46743}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: f7db07fe6b3b2705188cb01a07e...}
Session ID: f7db07fe6b3b2705188cb01a07e75b22
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.withSuccessfulAuthentication(TestOAuth2WebUiAuthenticationFilter.java:291)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.testSuccessfulFlow(TestOAuth2WebUiAuthenticationFilter.java:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Praveen2112** [comment]
```
Error:  testSuccessfulFlow(io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter)  Time elapsed: 2.405 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[200]> but was:<[303]>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.assertUICallWithCookie(TestOAuth2WebUiAuthenticationFilter.java:365)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.lambda$testSuccessfulFlow$0(TestOAuth2WebUiAuthenticationFilter.java:250)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.withSuccessfulAuthentication(TestOAuth2WebUiAuthenticationFilter.java:293)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.testSuccessfulFlow(TestOAuth2WebUiAuthenticationFilter.java:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

https://github.com/trinodb/trino/runs/1950087278

**Comment by nineinchnick** [comment]
```
Error:  testSuccessfulFlow(io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter)  Time elapsed: 17.048 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[200]> but was:<[303]>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.assertUICallWithCookie(TestOAuth2WebUiAuthenticationFilter.java:365)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.lambda$testSuccessfulFlow$0(TestOAuth2WebUiAuthenticationFilter.java:250)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.withSuccessfulAuthentication(TestOAuth2WebUiAuthenticationFilter.java:293)
	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.testSuccessfulFlow(TestOAuth2WebUiAuthenticationFilter.java:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
https://github.com/trinodb/trino/pull/6983/checks?check_run_id=1950265321

**Comment by byungnam** [comment]
Here I write my own case and workaround.

I was constantly getting failures from this test on my linux machine. For me, it was not even flaky and every test has failed from here. I've only got errors same to this comment: https://github.com/trinodb/trino/issues/6223#issuecomment-782922053

After a long investigation, I found the problem. It was the **slow** selenium testcontainer making tokens expired even before the page is loaded and ready. So the timeout tests with tokens were completely messed up. After I increased token timeout from 5 seconds to like 100 seconds, the test started to succeed. But I have no idea why the selenium testcontainer is slow at 32-core, 64GB-memory machine, fully idle situation.

Google says there are cases like me, so this may happen to others.
- https://stackoverflow.com/questions/16179808/chromedriver-is-extremely-slow-on-a-specific-machine-using-selenium-grid-and-ne
- https://github.com/SeleniumHQ/docker-selenium/issues/135
- https://stackoverflow.com/questions/58606020/selenium-webdriver-chromedriver-slow-to-launch-why

Can we increase the timeout to larger value or find some other way to resolve this problem?

Slack thread about this: https://trinodb.slack.com/archives/CGB0QHWSW/p1612492914246000

**Comment by kokosing** [comment]
> Can we increase the timeout to larger value or find some other way to resolve this problem?

@byungnam Can you please post a PR for this?

**Comment by byungnam** [comment]
@kokosing Sure, but how much should we increase? 100 seconds did good for me. Would it be enough?

**Comment by kokosing** [comment]
Do you need that much? How about 30 seconds? Is this going to make tests run longer in happy path?

@lukasz-walkiewicz @s2lomon any ideas?

**Comment by byungnam** [comment]
@kokosing 
> Do you need that much? How about 30 seconds? Is this going to make tests run longer in happy path?

I've tried 30, 60 and 100 seconds respectively, and only 100 seconds passed the test. It seems selenium is extremely slow for some reason. 

And, yes, it increases 100 seconds to finish the test. Though, there are only two tests affected by this so it only increases the whole test time about 200 seconds.

**Comment by kokosing** [comment]
Is there a way we can detect this and set timeout dynamically?

**Comment by byungnam** [comment]
For dynamic timeout, I think we need to check how much time selenium takes to load trino web ui and set timeout longer than that. But I'm not familiar to selenium nor "dynamic" unit test, so it may take a long time to change.

**Comment by lukasz-walkiewicz** [comment]
Fixed in: https://github.com/trinodb/trino/pull/7951
