### ISSUE TITLE
Unable to decode JWK response from Azure JWK

### ISSUE THREAD

**Issue by aakashnand** [trinodb/trino#6290]
Current jwt authenticator fails with following stack trace if set `http-server.authentication.jwt.key-file` to `https://login.microsoftonline.com/TENANT_ID/discovery/v2.0/keys`

Relevant Discussion on slack: https://prestosql.slack.com/archives/CGGL0EZ9N/p1607500620014400

```
Caused by: java.lang.RuntimeException: Unable to decode JWK response from https://login.microsoftonline.com/TENANT_ID/discovery/v2.0/keys
  at io.prestosql.server.security.jwt.JwkService.fetchKeys(JwkService.java:149)
  at io.prestosql.server.security.jwt.JwkService.<init>(JwkService.java:69)
  at io.prestosql.server.security.jwt.JwkService.<init>(JwkService.java:60)
  at io.prestosql.server.security.jwt.JwkService$$FastClassByGuice$$13916454.newInstance(<generated>)
  at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
  at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
  at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
  at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
  at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
  at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
  at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
  at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
  at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
  at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
  at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
  at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
  at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
  at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
  at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
  at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
  at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
  at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
  at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
  at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
  at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
  at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
  at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
  at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
  at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
  at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
  at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
  at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
  at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
  at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
  at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
  at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
  at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
  at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
  at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
  at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
  at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
  at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
  at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
  at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
  at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
  at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
  at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
  at com.google.inject.internal.RealOptionalBinder$JavaOptionalProvider.doProvision(RealOptionalBinder.java:279)
  at com.google.inject.internal.RealOptionalBinder$JavaOptionalProvider.doProvision(RealOptionalBinder.java:240)
  at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory$1.call(InternalProviderInstanceBindingImpl.java:120)
  at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
  at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
  at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
  at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
  at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:115)
  at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
  at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
  at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
  at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
  at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
  at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
  at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
  at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
  at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
  at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
  at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
  at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
  at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
  at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
  at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
  at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
  at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
  at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
  at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
  at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
  at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
  at com.google.inject.Guice.createInjector(Guice.java:87)
  at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:276)
  at io.prestosql.server.Server.doStart(Server.java:111)
  at io.prestosql.server.Server.lambda$start$0(Server.java:73)
  at io.prestosql.$gen.Presto_345____20201210_072203_1.run(Unknown Source)
  at io.prestosql.server.Server.start(Server.java:73)
  at io.prestosql.server.PrestoServer.main(PrestoServer.java:38)
Caused by: java.lang.IllegalArgumentException: Invalid JSON string for [simple type, class io.prestosql.server.security.jwt.JwkDecoder$Keys]
  at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:137)
  at io.prestosql.server.security.jwt.JwkDecoder.decodeKeys(JwkDecoder.java:47)
  at io.prestosql.server.security.jwt.JwkService.fetchKeys(JwkService.java:146)
  ... 82 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (String)"{"keys":[{"kty":"RSA","use":"sig","kid":"kg2LYs2T0CTjIfj4rt6JIynen38","x5t":"kg2LYs2T0CTjIfj4rt6JIynen38","n":"yTKa6m5GFOllz7oIHFCkvRJoBv7wLMuKIPLHbFGh5yOiO8o3akoqMhf1x6MxINGhZo6dkIrhVlVfWJhEJZPVaQdvyvVmlIZruhcbz3PGMqPAbjq2JqbB1mMnsyGHx-ovP0Cm5xj8sgI8wm67p3nosqzqFvg6mPKVO-w1QBr5seDU2AwU2DR88LF2v03Zjgn4mGvPdUOXihTQoNlf-nJFduXMDyRgZabnR2HlYHhagHwy1beWW1WtEaPz8iBN_0bGkGw705aDBUHJkdTty1mzsCZRur_n0imqXu9IzoSyiq5d0yKrRA5xkA-K3DMeRMquZ5QvPT9Eee4EZfFL97zBfQ","e":"AQAB","x5c":["MIIDBTCCAe2gAwIBAgIQQiR8gZ"[truncated 4262 chars]; line: 1, column: 473] (through reference chain: io.prestosql.server.security.jwt.JwkDecoder$Keys["keys"]->java.util.ArrayList[0]->java.util.LinkedHashMap["x5c"])
  at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
  at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1445)
  at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1219)
  at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:714)
  at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:40)
  at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1292)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
  at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
  at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1261)
  at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:134)
  ... 84 more
```

**Comment by aakashnand** [comment]
As far as I know, this is happening because of this line of code. https://github.com/prestosql/presto/blob/f72fadfc814906f1ceb182f984281878b6b5b861/presto-main/src/main/java/io/prestosql/server/security/jwt/JwkDecoder.java#L161

The map of the key is defined as <String, String> but the JWT has a key with an array of string for key `x5c`.
This can be confirmed from this response as well. https://login.microsoftonline.com/common/discovery/keys

I would like to work on this issue. With some help from @dain
