### ISSUE TITLE
Respect hive.timestamp-precision in Hive VIEW

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6295]
Following should be supported

- hive view outputting a timestamp column -- this should respect `hive.timestamp-precision`
- hive view using a timestamp column (e.g. in a filter or as `CAST(a_timestamp AS varchar)`) -- this should probably respect `hive.timestamp-precision` as well because there seems to be no better alternative

This should be tested in matrix wrt `hive.legacy-hive-view-translation` since the code paths are significantly different around type handling.
For example
https://github.com/prestosql/presto/blob/16c38d05a82de0a3f60e643ecde4b555072ad745/presto-hive/src/main/java/io/prestosql/plugin/hive/LegacyHiveViewReader.java#L42

**Comment by losipiuk** [comment]
Additionally, currently it is not possible to query Hive views that return `TIMESTAMP` columns if `hive.timestamp-precision` config property is set to `MICROSECONDS` or `NANOSECONDS`.

In such setup you will get following exception:
```
io.prestosql.spi.PrestoException: line 1:33: View 'hive_timestamp_nanos.default.timestamp_hive_view' is stale or in invalid state: column [ts] of type timestamp(9) projected from query view at position 0 cannot be coerced to column [ts] of type timestamp(3) stored in view definition
	at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.lambda$createScopeForView$18(StatementAnalyzer.java:1379)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.createScopeForView(StatementAnalyzer.java:1379)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1217)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:329)
	at io.prestosql.sql.tree.Table.accept(Table.java:53)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:346)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2529)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1553)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:329)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:346)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:356)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1061)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:329)
	at io.prestosql.sql.tree.Query.accept(Query.java:107)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:346)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:315)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:263)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:186)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:768)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:129)
	at io.prestosql.$gen.Presto_348_99_g18b0e65_dirty____20201222_110904_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
