### ISSUE TITLE
Flaky test io.trino.tests.product.TestSqlCancel.cancelSelect

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#6315]
```
2020-12-11T19:14:00.5936836Z tests               | 2020-12-12 00:59:00 INFO: [61 of 523] io.prestosql.tests.TestSqlCancel.cancelSelect (Groups: cancel_query)
2020-12-11T19:14:01.0723699Z tests               | 2020-12-12 00:59:01 INFO: not retrying; @Flaky annotation not present
2020-12-11T19:14:01.0740962Z presto-worker       | 2020-12-12T00:59:01.073+0545	ERROR	page-buffer-client-callback-22	io.prestosql.operator.HttpPageBufferClient	Request to delete http://172.18.0.3:8080/v1/task/20201211_191400_00085_axcak.1.0/results/0 failed java.util.concurrent.CancellationException: Task was cancelled.
2020-12-11T19:14:01.0760715Z tests               | 2020-12-12 00:59:01 INFO: FAILURE     /    io.prestosql.tests.TestSqlCancel.cancelSelect (Groups: cancel_query) took 0.5 seconds
2020-12-11T19:14:01.0857901Z tests               | 2020-12-12 00:59:01 SEVERE: Failure cause:
2020-12-11T19:14:01.0859145Z tests               | io.prestosql.tempto.query.QueryExecutionException: java.sql.SQLException: Connection is closed
2020-12-11T19:14:01.0861177Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
2020-12-11T19:14:01.0863297Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2020-12-11T19:14:01.0865162Z tests               | 	at io.prestosql.tempto.query.QueryExecutor.query(QueryExecutor.java:57)
2020-12-11T19:14:01.0866689Z tests               | 	at io.prestosql.tests.TestSqlCancel.cancelQuery(TestSqlCancel.java:142)
2020-12-11T19:14:01.0868346Z tests               | 	at io.prestosql.tests.TestSqlCancel.runAndCancelQuery(TestSqlCancel.java:120)
2020-12-11T19:14:01.0870060Z tests               | 	at io.prestosql.tests.TestSqlCancel.cancelSelect(TestSqlCancel.java:112)
2020-12-11T19:14:01.0871782Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-11T19:14:01.0873803Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-11T19:14:01.0876187Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-11T19:14:01.0877942Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-12-11T19:14:01.0879569Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-12-11T19:14:01.0881634Z tests               | 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-12-11T19:14:01.0883379Z tests               | 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-12-11T19:14:01.0884908Z tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-12-11T19:14:01.0886149Z tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-12-11T19:14:01.0887688Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-12-11T19:14:01.0889444Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-12-11T19:14:01.0890811Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-11T19:14:01.0891586Z tests               | Caused by: java.sql.SQLException: Connection is closed
2020-12-11T19:14:01.0892743Z tests               | 	at io.prestosql.jdbc.PrestoStatement.connection(PrestoStatement.java:622)
2020-12-11T19:14:01.0895174Z tests               | 	at io.prestosql.jdbc.PrestoStatement.checkOpen(PrestoStatement.java:611)
2020-12-11T19:14:01.0896840Z tests               | 	at io.prestosql.jdbc.PrestoStatement.getResultSet(PrestoStatement.java:301)
2020-12-11T19:14:01.0898960Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:129)
2020-12-11T19:14:01.0901183Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
2020-12-11T19:14:01.0902305Z tests               | 	... 17 more
2020-12-11T19:14:01.0903716Z tests               | 	Suppressed: java.lang.Exception: Query: SELECT query_id from system.runtime.queries WHERE query = 'SELECT * FROM tpch.sf1.lineitem AS cancel_select_976936274102' and state = 'RUNNING' LIMIT 2
2020-12-11T19:14:01.0906073Z tests               | 		at io.prestosql.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
2020-12-11T19:14:01.0907781Z tests               | 		... 18 more
```
https://github.com/prestosql/presto/pull/6296/checks?check_run_id=1538893954

**Comment by sopel39** [comment]
https://github.com/prestosql/presto/pull/6296

**Comment by lukasz-walkiewicz** [comment]
https://github.com/trinodb/trino/runs/5586083624?check_suite_focus=true

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/6517159896
