### ISSUE TITLE
cluster becomes slower and slower

### ISSUE THREAD

**Issue by ImTangYun** [trinodb/trino#6405]
From web ui we see that many query ware running, but work parallelism almost 0, and cpu usage is very low

![slow](https://user-images.githubusercontent.com/5945486/102759537-386df480-43af-11eb-8b23-9d52124e398a.png)

After we restart cluster, the cluster performs quit well, but slow down quikly after about 1 to 2hours, do you know why? does presto need to be restarted frequently at facebook?

Some important info:
Our querys are quit big, many querys scan 5+TB physical data. We see that the cluster slow down slower when querys are small

![fast](https://user-images.githubusercontent.com/5945486/102759620-50457880-43af-11eb-8a35-4fcb94c0c6c8.png)

**the key configs:**

we had clusters with about 41 worker nodes, the hardware is:

cpu with 96 cores

512GB memory

1 ssd

10 Gigabit Ethernet

presto version: 332
hive connector with data stored at hdfs

**jvm：**
-server
-Xms450G
-Xmx450G
-Xss8M
-XX:+UseG1GC
-XX:G1HeapWastePercent=5
-XX:+ParallelRefProcEnabled
-XX:ParallelGCThreads=48
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:OnOutOfMemoryError=kill -9 %p
-DHADOOP_USER_NAME=hdfs
-Dpresto-temporarily-allow-java8=true
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-XX:ReservedCodeCacheSize=2G
-XX:+UseCodeCacheFlushing
-XX:NativeMemoryTracking=detail
-XX:+PrintCompilation
-XX:+CITime
-XX:+PrintCodeCache
-Djdk.nio.maxCachedBufferSize=4000000
-Djdk.attach.allowAttachSelf=true
-XX:G1HeapRegionSize=32M

**presto config,properties:**
query.max-memory=2500GB
query.max-history=3000
experimental.reserved-pool-disabled=true
http-server.log.max-size=100MB
http-server.http.port=8286
log.max-size=100MB
node-scheduler.include-coordinator=false
node-scheduler.max-splits-increment-for-caching=300
query.low-memory-killer.delay=1m
http-server.accept-queue-size=16000
distributed-sort=true
exchange.http-client.idle-timeout=1m
log.max-history=10
optimizer.enable-intermediate-aggregations=true
query.low-memory-killer.policy=total-reservation-on-blocked-nodes
task.concurrency=32
http-server.http.selector-threads=32
query.max-total-memory=8000GB
task.max-worker-threads=100
join-distribution-type=AUTOMATIC
node-scheduler.use-cacheable-white-list=true
query.client.timeout=5m
query.max-memory-per-node=200GB
optimizer.default-filter-factor-enabled=true
exchange.compression-enabled=true
task.max-leaf-splits-per-node=50
node-scheduler.max-splits-per-node=100
http-server.threads.max=500
query.max-total-memory-per-node=256GB
join-max-broadcast-table-size=2GB
http-server.http.acceptor-threads=32
writer-min-size=128MB
http-server.threads.min=50
discovery.uri=http://master:8000
optimizer.join-reordering-strategy=AUTOMATIC
http-server.log.max-history=10
memory.heap-headroom-per-node=48GB
optimizer.optimize-mixed-distinct-aggregations=true
optimizer.use-mark-distinct=true
query.max-length=600000
coordinator=false

**many worker threads stuck at:**
![stack1](https://user-images.githubusercontent.com/5945486/102958030-f8298600-4516-11eb-9875-e761a5546a08.png)

java.lang.Thread.State: RUNNABLE
at jdk.internal.misc.Unsafe.defineAnonymousClass0(java.base@11.0.8/Native Method)
at jdk.internal.misc.Unsafe.defineAnonymousClass(java.base@11.0.8/Unsafe.java:1225)
at java.lang.invoke.InvokerBytecodeGenerator.loadAndInitializeInvokerClass(java.base@11.0.8/InvokerBytecodeGenerator.java:295)
at java.lang.invoke.InvokerBytecodeGenerator.loadMethod(java.base@11.0.8/InvokerBytecodeGenerator.java:287)
at java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCode(java.base@11.0.8/InvokerBytecodeGenerator.java:693)
at java.lang.invoke.LambdaForm.compileToBytecode(java.base@11.0.8/LambdaForm.java:871)
at java.lang.invoke.LambdaForm.customize(java.base@11.0.8/LambdaForm.java:506)
at java.lang.invoke.MethodHandle.customize(java.base@11.0.8/MethodHandle.java:1675)
at java.lang.invoke.Invokers.maybeCustomize(java.base@11.0.8/Invokers.java:582)
at java.lang.invoke.Invokers.checkCustomized(java.base@11.0.8/Invokers.java:573)
at java.lang.invoke.Invokers$Holder.invoke_MT(java.base@11.0.8/Invokers$Holder)
at io.prestosql.operator.project.GeneratedPageProjection.project(GeneratedPageProjection.java:76)
at io.prestosql.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:330)
at io.prestosql.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:205)
at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
at io.prestosql.operator.WorkProcessorUtils$$Lambda$3039/0x00007ebdf82cb840.process(Unknown Source)
at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
at io.prestosql.operator.WorkProcessorUtils$$Lambda$3090/0x00007ebdf835d8b0.process(Unknown Source)
at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
at io.prestosql.operator.WorkProcessorUtils$$Lambda$3039/0x00007ebdf82cb840.process(Unknown Source)
at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)

**Flame graph**

![p1](https://user-images.githubusercontent.com/5945486/102958369-a6cdc680-4517-11eb-86dc-1a7818c63f90.png)
![p2](https://user-images.githubusercontent.com/5945486/102958373-a9c8b700-4517-11eb-9ffd-51e1fe1a23fe.png)
![p3](https://user-images.githubusercontent.com/5945486/102958376-aa614d80-4517-11eb-996d-a595b53c1dc6.png)
![p4](https://user-images.githubusercontent.com/5945486/102958378-ab927a80-4517-11eb-8eb8-abd1100996fc.png)

**Comment by tooptoop4** [comment]
similar to https://github.com/prestodb/presto/issues/11952#issuecomment-734006863 restarting workers every 5 days seems to solve for me

**Comment by ImTangYun** [comment]
> similar to [prestodb/presto#11952 (comment)](https://github.com/prestodb/presto/issues/11952#issuecomment-734006863) restarting workers every 5 days seems to solve for me

Our clusters become slow only after 1~2hours, and restart every 1hour is not a good choice, do you have any ideas for the core cause of slow?

**Comment by tooptoop4** [comment]
@ImTangYun can u take some diagnostic dumps like jmap/jstack, 10 minutes after restart vs 4 hours after restart and compare them? My guess is some memory leak

**Comment by ImTangYun** [comment]
> @ImTangYun can u take some diagnostic dumps like jmap/jstack, 10 minutes after restart vs 4 hours after restart and compare them? My guess is some memory leak

Sounds a good way to find the problem, i'll try it these days,thanks

**Comment by shuai-xu** [comment]
Is there anybody know what is 'io.prestosql.operator.project.GeneratedPageProjection.project(GeneratedPageProjection.java)'  doing? Why the stack always shows the thread is hanging here when worker become slow?

**Comment by tooptoop4** [comment]
@yingsu00

**Comment by findepi** [comment]
> Is there anybody know what is 'io.prestosql.operator.project.GeneratedPageProjection.project(GeneratedPageProjection.java)' doing? Why the stack always shows the thread is hanging here when worker become slow?

(also reported as https://github.com/prestosql/presto/issues/6435)

**Comment by zhanglistar** [comment]
Any updates?

**Comment by sopel39** [comment]
@ImTangYun

* Could you set JVM properties
`PerMethodRecompilationCutoff=10000` and `PerBytecodeRecompilationCutoff=10000` and report if it did help regression issue?

**Comment by zhanglistar** [comment]
> @ImTangYun
> 
> * Could you set JVM properties
>   `PerMethodRecompilationCutoff=10000` and `PerBytecodeRecompilationCutoff=10000` and report if it did help regression issue?

Already set, see the config above.

**Comment by gjhkael** [comment]
Our cluster had the same problem, we restart the cluster every two weeks. @ImTangYun do you have solved the problem?

**Comment by ImTangYun** [comment]
> Our cluster had the same problem, we restart the cluster every two weeks. @ImTangYun do you have solved the problem?

No we restart the cluster every 2hours [破涕为笑]

**Comment by sopel39** [comment]
@ImTangYun Is it possible to isolate this issue to a particular query? Or it degrades after you run mix of queries? Did you try newest Trino version?

**Comment by wangli-td** [comment]
Hi, guys is there any updates for this issue? Seems it happens sometimes. Some works still becomes slowly with below jvm parmeters alreay set.

**Comment by tooptoop4** [comment]
has anyone tested after https://github.com/trinodb/trino/pull/13064 fix?

**Comment by zhumengzhu** [comment]
> Hi, guys is there any updates for this issue? Seems it happens sometimes. Some works still becomes slowly with below jvm parmeters alreay set. -XX:PerMethodRecompilationCutoff=10000 -XX:PerBytecodeRecompilationCutoff=10000

It seems this is an issue caused by [JDK-8243615](https://bugs.openjdk.org/browse/JDK-8243615). You can see more details [here](https://mail.openjdk.org/pipermail/hotspot-compiler-dev/2020-May/038204.html).

The default Cutoff parameters are:
```bash
java -XX:+PrintFlagsFinal -version | grep Cutoff                                                                                                                                                        
     intx LiveNodeCountInliningCutoff              = 40000                                  {C2 product} {default}
     intx PerBytecodeRecompilationCutoff           = 200                                       {product} {default}
     intx PerMethodRecompilationCutoff             = 400                                       {product} {default}
```
So, IMO, tuning these parameters just delays the slow problem but does not solve it. Maybe the only way is to fix it in JDK.

**Comment by ArjunMenonPe** [comment]
Any permanent fix you found for this issue? @ImTangYun @findepi @zhumengzhu

**Comment by george-zubrienko** [comment]
I can add a couple of observations here. We encountered this issue on a cluster growing from 2 nodes to 30 nodes for rather large queries, causing all remaining queries to get stalled for 10+ minutes.
After examining query plans we found out that they were waiting on exchange phases, which gave us an idea to try increase number of exchange buckets from 3 to 6 and the problem was gone. Even though Trino documentation states that we should see something like S3 Slowdown errors, I didn't see any, but once we added more exchange buckets, even on a 20 node cluster everything worked fine
For reference, nodes are 16c 128gb r7gd machines.

**Comment by ArjunMenonPe** [comment]
@george-zubrienko Can you please elaborate on how exactly we can increase the bucket counts? We are using trino with hive connector which queries data residing in Google Cloud Storage. I would like to try the same approach on my end.

**Comment by george-zubrienko** [comment]
> @george-zubrienko Can you please elaborate on how exactly we can increase the bucket counts? We are using trino with hive connector which queries data residing in Google Cloud Storage. I would like to try the same approach on my end.
> 
> Are you referring to this property: **exchange.concurrent-request-multiplier**?

This one: `exchange.base-directories`. We use AWS S3 though, but i think same logic applies to other storages. From Trino docs:
```

You can configure multiple S3 buckets for the exchange manager to distribute spooled data across buckets, reducing the I/O load on any one bucket. If a query fails with the error message “software.amazon.awssdk.services.s3.model.S3Exception: Please reduce your request rate”, this indicates that the workload is I/O intensive, and you should specify multiple S3 buckets in exchange.base-directories to balance the load:
```

**Comment by ArjunMenonPe** [comment]
@george-zubrienko We have not enabled fault tolerant execution on trino yet. These configs seems to come into picture once fault tolerance is enabled.

**Comment by ArjunMenonPe** [comment]
@sopel39 / @tooptoop4 - Any suggestions or workaround for this? We are facing this issue for about a month now. Thanks.

**Comment by sopel39** [comment]
@ArjunMenonPe which version do you use? which java? Could you share you jvm.config?

**Comment by ArjunMenonPe** [comment]
@sopel39 Thanks for responding. Please find the configs below.

**Coordinator**
cat config.properties 
coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
query.max-memory=30GB
query.max-memory-per-node=5GB
discovery.uri=http://localhost:8080
http-server.authentication.type=PASSWORD

task.concurrency=8
task.max-worker-threads=16
task.http-response-threads=500
log.format=JSON
internal-communication.shared-secret=trino-internal-comm-secret
http-server.authentication.allow-insecure-over-http=true
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/etc/trino/generated/tls.pem
jmx.rmiregistry.port=9080
jmx.rmiserver.port=9081

 cat jvm.config 
-server
-agentpath:/usr/lib/trino/bin/libjvmkill.so
-Xmx16G
-Xms4G
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:+ExitOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-XX:ReservedCodeCacheSize=512M
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-Djdk.attach.allowAttachSelf=true
-Djdk.nio.maxCachedBufferSize=2000000
# Allow loading dynamic agent used by JOL
-XX:+EnableDynamicAgentLoading

**Worker**

 cat jvm.config 
-server
-agentpath:/usr/lib/trino/bin/libjvmkill.so
-Xmx16G
-Xms4G
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:+ExitOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-XX:ReservedCodeCacheSize=512M
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-Djdk.attach.allowAttachSelf=true
-Djdk.nio.maxCachedBufferSize=2000000
# Allow loading dynamic agent used by JOL
-XX:+EnableDynamicAgentLoading

# https://bugs.openjdk.org/browse/JDK-8329528
-XX:+UnlockDiagnosticVMOptions
-XX:G1NumCollectionsKeepPinned=10000000
cat config.properties 
coordinator=false
http-server.http.port=8080
query.max-memory=30GB
query.max-memory-per-node=5GB
discovery.uri=http://metabase-trino-trino:8080

task.concurrency=8
task.max-worker-threads=16
task.http-response-threads=500
internal-communication.shared-secret=trino-internal-comm-secret
http-server.authentication.allow-insecure-over-http=true
shutdown.grace-period=900s


Java version

[trino@trino]$ java --version
openjdk 22.0.1 2024-04-16
OpenJDK Runtime Environment Temurin-22.0.1+8 (build 22.0.1+8)
OpenJDK 64-Bit Server VM Temurin-22.0.1+8 (build 22.0.1+8, mixed mode, sharing)

**Comment by sopel39** [comment]
I think your worker nodes are pretty small `-Xmx16G`. How many of them do you use? Could you use fewer, but larger?

**Comment by ArjunMenonPe** [comment]
We had tried this too before but that also degrades the cluster performance after a point. We are running about 20 workers.

**Comment by sopel39** [comment]
> We had tried this too before but that also degrades the cluster performance after a point. We are running about 20 workers.

Wdym degrades performance? Definitely I would suggest 4 or 8 workers that that substantially larger. Trino will have issues running with low Xmx.

**Comment by ArjunMenonPe** [comment]
@sopel39 when we do a deployment , for the first few minutes the cluster performance is great but as time goes, querying get slower and slower. I have tried decreasing the workers with bigger sizes but still I am seeing the same issues.

Here are the latest configs I am trying with

[trino@airflow-trino-trino-worker-77c9847d5f-z85vj trino]$ cat jvm.config 
-server
-agentpath:/usr/lib/trino/bin/libjvmkill.so
-Xmx50G
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:+ExitOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-XX:ReservedCodeCacheSize=512M
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-Djdk.attach.allowAttachSelf=true
-Djdk.nio.maxCachedBufferSize=2000000
# Allow loading dynamic agent used by JOL
-XX:+EnableDynamicAgentLoading

# https://bugs.openjdk.org/browse/JDK-8329528
-XX:+UnlockDiagnosticVMOptions
-XX:G1NumCollectionsKeepPinned=10000000
[trino@airflow-trino-trino-worker-77c9847d5f-z85vj trino]$ cat config.properties 
coordinator=false
http-server.http.port=8080
query.max-memory=100GB
query.max-memory-per-node=15GB
discovery.uri=http://airflow-trino-trino:8080

task.concurrency=8
task.max-worker-threads=8
task.http-response-threads=500
internal-communication.shared-secret=trino-internal-comm-secret
http-server.authentication.allow-insecure-over-http=true


Just FYI, I have DAGs running queries that consume input data of around 8-10GB as well. Can you please help if I am doing something fundamentally wrong.

**Comment by sopel39** [comment]
@ArjunMenonPe do you observe any increased GC activity, e.g: full GC? Is the heap getting full? Which Trino version is it?

**Comment by ArjunMenonPe** [comment]
@sopel39 - Heap memory usage is quite low across the workers and the pods are pretty underutilised![Image](https://github.com/user-attachments/assets/2087790b-70b7-48c7-aa62-1270c51a9d12)


Trino version I am using is 449. Do you think I am limiting the workers in any of the configs from using the available memory and cpu?

**Comment by sopel39** [comment]
The config generally looks fine (apart from Xmx which is a bit lowish). However, I wonder if there is a specific workload that causes a slowdown.

**Comment by ramcasa** [comment]
I have experienced the same issue, even with Express One Buckets, which have very big rate limits, which suggests the issue is on Trino's side. In addition, I also see that downloads of data files from S3 are quite slow. This would suggest that there is some issue with the download and write speed to S3 inside the Trino and the reason why adding more buckets solves it for the `Exchange` operator is that there are more copies of an internal resource that deals with each individual bucket.

**Comment by raunaqmorarka** [comment]
The original issue reported here was about something in expression compiler and is now nearly 5 years old.
Meanwhile, because of the vague title, it seems this issue keeps attracting reports of unrelated issues with similar symptoms.
So I'm closing this issue as stale, new issues should be dealt with a fresh investigation.
