### ISSUE TITLE
SQL Server "Expected zero to one elements, but found multiple"

### ISSUE THREAD

**Issue by carlosfvp** [trinodb/trino#6464]
SQL Query fails with a simple select * from to any table on the database.
Also tried multiple instances of SQL Server.

![imagen](https://user-images.githubusercontent.com/4541969/103301749-015f9a80-49d0-11eb-9314-1488fdd2a4d3.png)

There is no error when the table it's empty:

![imagen](https://user-images.githubusercontent.com/4541969/103301735-fad12300-49cf-11eb-89cc-98399b7d198f.png)

Trino:
```
java.lang.IllegalStateException: Expected zero to one elements, but found multiple
	at org.jdbi.v3.core.result.ResultIterable.findOne(ResultIterable.java:163)
	at io.prestosql.plugin.sqlserver.SqlServerClient.getTableDataCompression(SqlServerClient.java:437)
	at io.prestosql.plugin.sqlserver.SqlServerClient.getTableProperties(SqlServerClient.java:378)
	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.getTableProperties(ForwardingJdbcClient.java:288)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getTableProperties(StatisticsAwareJdbcClient.java:305)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.getTableProperties(CachingJdbcClient.java:365)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.getTableProperties(CachingJdbcClient.java:365)
	at io.prestosql.plugin.jdbc.JdbcMetadata.getTableMetadata(JdbcMetadata.java:344)
	at io.prestosql.metadata.MetadataManager.getTableMetadata(MetadataManager.java:508)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1231)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:329)
	at io.prestosql.sql.tree.Table.accept(Table.java:53)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:346)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2529)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1553)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:329)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:346)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:356)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1061)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:329)
	at io.prestosql.sql.tree.Query.accept(Query.java:107)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:346)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:315)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:263)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:186)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:768)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:129)
	at io.prestosql.$gen.Presto_350____20211229_170343_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by electrum** [comment]
@carlosfvp Can you run this query against your SQL Server instance?
```sql
SELECT t.object_id, p.partition_id, i.index_id, data_compression_desc
FROM sys.partitions p 
INNER JOIN sys.tables t ON p.object_id = t.object_id 
INNER JOIN sys.indexes i ON t.object_id = i.object_id 
WHERE SCHEMA_NAME(t.schema_id) = :schema
  AND t.name = :table_name
  AND i.type IN (0,1) 
  AND i.data_space_id NOT IN (SELECT data_space_id FROM sys.partition_schemes)
```
Replace `:schema` and `:table_name` with the schema and table name you are querying. This will help us determine why the query is returning multiple results.

@Praveen2112 we may want to change the query to join against `sys.schemas` since that might have a better chance to use indexes than the `schema_name()` function.

**Comment by carlosfvp** [comment]
I think the table have multiple indexes

![imagen](https://user-images.githubusercontent.com/4541969/103318143-7399a480-49fb-11eb-9ef2-2a953aa13b14.png)

**Comment by inglesp** [comment]
I've reproduced this.  The problem is to do with MSSQL columns with a unique constraint.

Specifically, the following table can be queried via presto:

```
create table good (c integer null)
```

But the following cannot, giving the "Expected zero to one elements, but found multiple" error:

```
create table bad (c integer null, unique (c))
````

This is a regression between docker release [348](https://hub.docker.com/layers/prestosql/presto/348/images/sha256-052582da46fdde74e82994d67448cc080b6ef930ab54baec1ac97be81760563a) (which works) and [release 350](https://hub.docker.com/layers/prestosql/presto/350/images/sha256-adcf41a1fdf551be1d26a26b6ac75caae5d97fb2a6adc5151f5c9abb435704b4) (which doesn't).

**Comment by inglesp** [comment]
It's very possible this should have been raised this against https://github.com/prestodb/presto/

**Comment by inglesp** [comment]
> It's very possible this should have been raised this against https://github.com/prestodb/presto/

Maybe not.  I'd not realised that presto and trino were different things until five minutes ago, and so had then assumed that the prestosql/presto docker image was for the presto repo.  (This docker image is the only way I've used presto so far.)  But it was released by @electrum who seems to be part of the trino gang.

Sorry for the noise!

**Comment by findepi** [comment]
>  I'd not realised that presto and trino were different things until five minutes ago

they were not different things until about five minutes (ok, five days) ago.
read more @ https://trino.io/blog/2020/12/27/announcing-trino.html

Anyway, we hope https://github.com/trinodb/trino/pull/6471 will fix the problem. 
@Praveen2112 can you please add a test there for `create table bad (c integer null, unique (c))` case as well?

@inglesp in the meantime please continue to use Presto 348 as a workaround. Sorry for inconvenience.
