### ISSUE TITLE
Query failure by BigQuery complex type condition

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#6524]
Steps to reproduce:
```
bigquery> create table test.test_row (a STRUCT<b INT64>);

trino> select * from bigquery.test.test_row where a is null;
Query 20210106_084105_00000_zc8pp failed: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: row filter '`a` IS NULL' is too complex to be processed in filtering; consider executing a query instead
com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: row filter '`a` IS NULL' is too complex to be processed in filtering; consider executing a query instead
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1083)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:760)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:413)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:721)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.bigquery.storage.v1beta1.BigQueryStorageClient.createReadSession(BigQueryStorageClient.java:237)
		at io.trino.plugin.bigquery.ReadSessionCreator.create(ReadSessionCreator.java:89)
		at io.trino.plugin.bigquery.BigQuerySplitManager.readFromBigQuery(BigQuerySplitManager.java:112)
		at io.trino.plugin.bigquery.BigQuerySplitManager.getSplits(BigQuerySplitManager.java:94)
		at io.trino.split.SplitManager.getSplits(SplitManager.java:87)
		at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitScanAndFilter(DistributedExecutionPlanner.java:203)
		at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:272)
		at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:156)
		at io.trino.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
		at io.trino.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:124)
		at io.trino.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:131)
		at io.trino.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:101)
		at io.trino.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:470)
		at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:386)
		at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
		at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
		at io.trino.$gen.Trino_testversion____20210106_084054_3.run(Unknown Source)
		... 3 more
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: row filter '`a` IS NULL' is too complex to be processed in filtering; consider executing a query instead
	at io.grpc.Status.asRuntimeException(Status.java:533)
	... 13 more
```

https://trinodb.slack.com/archives/CGB0QHWSW/p1609917193169400

**Comment by ebyhr** [comment]
It seems this issue was resolved by BigQuery side. We can close this after adding a test.
