### ISSUE TITLE
ArrayIndexOutOfBoundsException error occurs when trying to insert into a presto iceberg table with parquet format using more than 100 million rows

### ISSUE THREAD

**Issue by Xiangakun** [trinodb/trino#6558]
Following attempts I tried, all works fine:
a. Insert same data set (over 100 million) into presto hive table with parquet format  using presto engine
b. Insert same data set (over 100 million) into Iceberg table with parquet format using spark engine
c. Insert same data set (over 10 million) into presto iceberg table with parquet format using presto engine

However, when try the case d. below, the ArrayIndexOutOfBoundsException occurs
d. Insert same data set (over `100` million) into `presto iceberg table` with parquet format using presto engine

The error stack is as follows:

java.lang.ArrayIndexOutOfBoundsException: Index 7603 out of bounds for length 1
	at org.apache.parquet.column.values.dictionary.DictionaryValuesWriter$PlainBinaryDictionaryValuesWriter.fallBackDictionaryEncodedData(DictionaryValuesWriter.java:295)
	at org.apache.parquet.column.values.dictionary.DictionaryValuesWriter.fallBackAllValuesTo(DictionaryValuesWriter.java:130)
	at org.apache.parquet.column.values.fallback.FallbackValuesWriter.fallBack(FallbackValuesWriter.java:153)
	at org.apache.parquet.column.values.fallback.FallbackValuesWriter.checkFallback(FallbackValuesWriter.java:147)
	at org.apache.parquet.column.values.fallback.FallbackValuesWriter.writeBytes(FallbackValuesWriter.java:169)
	at io.prestosql.parquet.writer.valuewriter.CharValueWriter.write(CharValueWriter.java:45)
	at io.prestosql.parquet.writer.PrimitiveColumnWriter.writeBlock(PrimitiveColumnWriter.java:124)
	at io.prestosql.parquet.writer.ParquetWriter.writeChunk(ParquetWriter.java:157)
	at io.prestosql.parquet.writer.ParquetWriter.write(ParquetWriter.java:147)
	at io.prestosql.plugin.hive.parquet.ParquetFileWriter.appendRows(ParquetFileWriter.java:110)
	at io.prestosql.plugin.iceberg.IcebergPageSink.writePage(IcebergPageSink.java:260)
	at io.prestosql.plugin.iceberg.IcebergPageSink.doAppend(IcebergPageSink.java:213)
	at io.prestosql.plugin.iceberg.IcebergPageSink.lambda$appendPage$0(IcebergPageSink.java:152)
	at io.prestosql.plugin.hive.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:24)
	at io.prestosql.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at io.prestosql.plugin.hive.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:23)
	at io.prestosql.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:101)
	at io.prestosql.plugin.iceberg.IcebergPageSink.appendPage(IcebergPageSink.java:152)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:69)
	at io.prestosql.operator.TableWriterOperator.addInput(TableWriterOperator.java:257)
	at io.prestosql.operator.Driver.processInternal(Driver.java:384)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_347_14_g1a73f83_dirty____20210106_091221_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by findepi** [comment]
I believe this is the same as https://github.com/trinodb/trino/issues/5518. Please reopen if it is not.

**Comment by Xiangakun** [comment]
@findepi   I don't think it's same as #5518, since I don't open the switch `experimental_parquet_optimized_writer_enabled`. In my case, the value of `experimental_parquet_optimized_writer_enabled` is `false` as default.

**Comment by findepi** [comment]
@Xiangakun good point.
The `experimental_parquet_optimized_writer_enabled` is Hive connector's session property, determining which Parquet writer to use: old or new ("optimized").
Iceberg connector uses the new one unconditionally though.

**Comment by Xiangakun** [comment]
@findepi Thanks for your reply. Have you got any idea about how to fix the problem?  Thanks!

**Comment by findepi** [comment]
Currently i do not.

**Comment by polaris6** [comment]
@Xiangakun This problem has not been resolved, do you consider reopen it?

**Comment by findepi** [comment]
@polaris6 this is tracked in #5518 
The issue talks about optimized Parquet writer, which is opt-in in Hive connector, but used unconditionally in Iceberg connector.

no need to reopen this one.
