### ISSUE TITLE
AbstractTestIndexedQueries#testHighCardinalityIndexJoinResult is flaky

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#6577]
```
2021-01-12T10:39:19.5999200Z [ERROR]   TestDistributedQueriesIndexed>AbstractTestIndexedQueries.testHighCardinalityIndexJoinResult:393->AbstractTestQueryFramework.assertQuery:149->AbstractTestQueryFramework.assertQuery:154 Execution of 'actual' query failed: SELECT *
2021-01-12T10:39:19.6029041Z FROM (
2021-01-12T10:39:19.6029438Z   SELECT *
2021-01-12T10:39:19.6029803Z   FROM orders
2021-01-12T10:39:19.6030258Z   WHERE orderkey % 10000 = 0) o1
2021-01-12T10:39:19.6030648Z JOIN (
2021-01-12T10:39:19.6030993Z   SELECT *
2021-01-12T10:39:19.6031349Z   FROM orders
2021-01-12T10:39:19.6031756Z   WHERE orderkey % 4 = 0) o2
2021-01-12T10:39:19.6032474Z   ON o1.orderstatus = o2.orderstatus AND o1.shippriority = o2.shippriority
2021-01-12T10:39:19.6033115Z [INFO] 
2021-01-12T10:39:19.6033618Z [ERROR] Tests run: 2112, Failures: 1, Errors: 0, Skipped: 1
```

**Comment by sopel39** [comment]
cc @erichwang

**Comment by kokosing** [comment]
```
2021-01-12T10:39:16.1623823Z [ERROR] testHighCardinalityIndexJoinResult(io.trino.tests.TestDistributedQueriesIndexed)  Time elapsed: 0.925 s  <<< FAILURE!
2021-01-12T10:39:16.1625636Z java.lang.AssertionError: 
2021-01-12T10:39:16.1628736Z Execution of 'actual' query failed: SELECT *
2021-01-12T10:39:16.1629936Z FROM (
2021-01-12T10:39:16.1630402Z   SELECT *
2021-01-12T10:39:16.1630872Z   FROM orders
2021-01-12T10:39:16.1631400Z   WHERE orderkey % 10000 = 0) o1
2021-01-12T10:39:16.1631886Z JOIN (
2021-01-12T10:39:16.1632776Z   SELECT *
2021-01-12T10:39:16.1633229Z   FROM orders
2021-01-12T10:39:16.1633748Z   WHERE orderkey % 4 = 0) o2
2021-01-12T10:39:16.1634553Z   ON o1.orderstatus = o2.orderstatus AND o1.shippriority = o2.shippriority
2021-01-12T10:39:16.1635522Z 	at org.testng.Assert.fail(Assert.java:83)
2021-01-12T10:39:16.1637115Z 	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:150)
2021-01-12T10:39:16.1639714Z 	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:106)
2021-01-12T10:39:16.1642083Z 	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:154)
2021-01-12T10:39:16.1645924Z 	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:149)
2021-01-12T10:39:16.1649654Z 	at io.trino.testing.AbstractTestIndexedQueries.testHighCardinalityIndexJoinResult(AbstractTestIndexedQueries.java:393)
2021-01-12T10:39:16.1655843Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-01-12T10:39:16.1658223Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-01-12T10:39:16.1661013Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-01-12T10:39:16.1663081Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-01-12T10:39:16.1664963Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-01-12T10:39:16.1668060Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-01-12T10:39:16.1669588Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-01-12T10:39:16.1671212Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-01-12T10:39:16.1673223Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-01-12T10:39:16.1675215Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-01-12T10:39:16.1677150Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-01-12T10:39:16.1679163Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-01-12T10:39:16.1680515Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-12T10:39:16.1681744Z Caused by: java.lang.RuntimeException: Expected response code from http://127.0.0.1:33839/v1/task/20210112_101505_00012_imq8z.1.0?summarize to be 200, but was 500
2021-01-12T10:39:16.1683639Z java.lang.IllegalArgumentException: Expected operatorType to be PagesIndexBuilderOperator but was PageBufferOperator
2021-01-12T10:39:16.1685692Z 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:441)
2021-01-12T10:39:16.1687384Z 	at io.trino.operator.OperatorStats.add(OperatorStats.java:478)
2021-01-12T10:39:16.1772855Z 	at io.trino.operator.OperatorStats.add(OperatorStats.java:428)
2021-01-12T10:39:16.1774716Z 	at io.trino.operator.PipelineContext.getPipelineStats(PipelineContext.java:413)
2021-01-12T10:39:16.1776448Z 	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
2021-01-12T10:39:16.1778205Z 	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
2021-01-12T10:39:16.1780355Z 	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:459)
2021-01-12T10:39:16.1782240Z 	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:847)
2021-01-12T10:39:16.1784909Z 	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:275)
2021-01-12T10:39:16.1786944Z 	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:232)
2021-01-12T10:39:16.1788624Z 	at io.trino.operator.TaskContext.getTaskStats(TaskContext.java:417)
2021-01-12T10:39:16.1790100Z 	at io.trino.execution.SqlTask.getTaskStats(SqlTask.java:350)
2021-01-12T10:39:16.1791499Z 	at io.trino.execution.SqlTask.createTaskInfo(SqlTask.java:372)
2021-01-12T10:39:16.1792875Z 	at io.trino.execution.SqlTask.getTaskInfo(SqlTask.java:234)
2021-01-12T10:39:16.1794413Z 	at io.trino.execution.SqlTaskManager.getTaskInfo(SqlTaskManager.java:316)
2021-01-12T10:39:16.1796055Z 	at io.trino.server.TaskResource.getTaskInfo(TaskResource.java:160)
2021-01-12T10:39:16.1797876Z 	at jdk.internal.reflect.GeneratedMethodAccessor519.invoke(Unknown Source)
2021-01-12T10:39:16.1800515Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-01-12T10:39:16.1802573Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-01-12T10:39:16.1805992Z 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
2021-01-12T10:39:16.1811238Z 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
2021-01-12T10:39:16.1816436Z 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
2021-01-12T10:39:16.1821716Z 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:183)
2021-01-12T10:39:16.1827083Z 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
2021-01-12T10:39:16.1831310Z 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
2021-01-12T10:39:16.1932310Z 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
2021-01-12T10:39:16.1935317Z 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
2021-01-12T10:39:16.1937581Z 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
2021-01-12T10:39:16.1939037Z 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
2021-01-12T10:39:16.1940876Z 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
2021-01-12T10:39:16.1942323Z 	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
2021-01-12T10:39:16.1943868Z 	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
2021-01-12T10:39:16.1945435Z 	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
2021-01-12T10:39:16.1947540Z 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
2021-01-12T10:39:16.1949872Z 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
2021-01-12T10:39:16.1952043Z 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
2021-01-12T10:39:16.1954290Z 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
2021-01-12T10:39:16.1956345Z 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
2021-01-12T10:39:16.1958449Z 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
2021-01-12T10:39:16.1960727Z 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
2021-01-12T10:39:16.1962988Z 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
2021-01-12T10:39:16.1965044Z 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
2021-01-12T10:39:16.1966927Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
2021-01-12T10:39:16.1968883Z 	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
2021-01-12T10:39:16.1971037Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
2021-01-12T10:39:16.1972974Z 	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
2021-01-12T10:39:16.1974761Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
2021-01-12T10:39:16.1976757Z 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
2021-01-12T10:39:16.1978851Z 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
2021-01-12T10:39:16.1981095Z 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
2021-01-12T10:39:16.1983361Z 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
2021-01-12T10:39:16.1985805Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
2021-01-12T10:39:16.1988200Z 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
2021-01-12T10:39:16.1990572Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
2021-01-12T10:39:16.1992747Z 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
2021-01-12T10:39:16.1994903Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
2021-01-12T10:39:16.1997255Z 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
2021-01-12T10:39:16.1999496Z 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
2021-01-12T10:39:16.2001840Z 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
2021-01-12T10:39:16.2004326Z 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
2021-01-12T10:39:16.2006582Z 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
2021-01-12T10:39:16.2008710Z 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
2021-01-12T10:39:16.2010510Z 	at org.eclipse.jetty.server.Server.handle(Server.java:501)
2021-01-12T10:39:16.2092253Z 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
2021-01-12T10:39:16.2094058Z 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
2021-01-12T10:39:16.2096214Z 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
2021-01-12T10:39:16.2100521Z 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272)
2021-01-12T10:39:16.2102533Z 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
2021-01-12T10:39:16.2105072Z 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
2021-01-12T10:39:16.2106922Z 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
2021-01-12T10:39:16.2108977Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
2021-01-12T10:39:16.2111673Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
2021-01-12T10:39:16.2114852Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
2021-01-12T10:39:16.2117703Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
2021-01-12T10:39:16.2121267Z 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
2021-01-12T10:39:16.2123988Z 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
2021-01-12T10:39:16.2126117Z 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
2021-01-12T10:39:16.2127537Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-12T10:39:16.2128000Z 
2021-01-12T10:39:16.2129808Z 	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:115)
2021-01-12T10:39:16.2132917Z 	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:462)
2021-01-12T10:39:16.2135127Z 	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:147)
2021-01-12T10:39:16.2136195Z 	... 17 more
2021-01-12T10:39:16.2137207Z Caused by: io.trino.spi.TrinoException: Expected response code from http://127.0.0.1:33839/v1/task/20210112_101505_00012_imq8z.1.0?summarize to be 200, but was 500
2021-01-12T10:39:16.2139054Z java.lang.IllegalArgumentException: Expected operatorType to be PagesIndexBuilderOperator but was PageBufferOperator
2021-01-12T10:39:16.2141112Z 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:441)
2021-01-12T10:39:16.2142770Z 	at io.trino.operator.OperatorStats.add(OperatorStats.java:478)
2021-01-12T10:39:16.2144103Z 	at io.trino.operator.OperatorStats.add(OperatorStats.java:428)
2021-01-12T10:39:16.2145956Z 	at io.trino.operator.PipelineContext.getPipelineStats(PipelineContext.java:413)
2021-01-12T10:39:16.2147691Z 	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
2021-01-12T10:39:16.2149425Z 	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
2021-01-12T10:39:16.2151565Z 	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:459)
2021-01-12T10:39:16.2153423Z 	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:847)
2021-01-12T10:39:16.2155140Z 	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:275)
2021-01-12T10:39:16.2156917Z 	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:232)
2021-01-12T10:39:16.2158617Z 	at io.trino.operator.TaskContext.getTaskStats(TaskContext.java:417)
2021-01-12T10:39:16.2160076Z 	at io.trino.execution.SqlTask.getTaskStats(SqlTask.java:350)
2021-01-12T10:39:16.2161466Z 	at io.trino.execution.SqlTask.createTaskInfo(SqlTask.java:372)
2021-01-12T10:39:16.2162850Z 	at io.trino.execution.SqlTask.getTaskInfo(SqlTask.java:234)
2021-01-12T10:39:16.2164385Z 	at io.trino.execution.SqlTaskManager.getTaskInfo(SqlTaskManager.java:316)
2021-01-12T10:39:16.2166037Z 	at io.trino.server.TaskResource.getTaskInfo(TaskResource.java:160)
2021-01-12T10:39:16.2167842Z 	at jdk.internal.reflect.GeneratedMethodAccessor519.invoke(Unknown Source)
2021-01-12T10:39:16.2170386Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-01-12T10:39:16.2249815Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-01-12T10:39:16.2255134Z 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
2021-01-12T10:39:16.2260407Z 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
2021-01-12T10:39:16.2265473Z 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
2021-01-12T10:39:16.2270750Z 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:183)
2021-01-12T10:39:16.2276162Z 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
2021-01-12T10:39:16.2280399Z 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
2021-01-12T10:39:16.2283330Z 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
2021-01-12T10:39:16.2286222Z 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
2021-01-12T10:39:16.2288490Z 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
2021-01-12T10:39:16.2289931Z 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
2021-01-12T10:39:16.2291199Z 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
2021-01-12T10:39:16.2292761Z 	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
2021-01-12T10:39:16.2294333Z 	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
2021-01-12T10:39:16.2296120Z 	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
2021-01-12T10:39:16.2298213Z 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
2021-01-12T10:39:16.2300539Z 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
2021-01-12T10:39:16.2302684Z 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
2021-01-12T10:39:16.2304942Z 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
2021-01-12T10:39:16.2306997Z 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
2021-01-12T10:39:16.2310274Z 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
2021-01-12T10:39:16.2313287Z 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
2021-01-12T10:39:16.2315689Z 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
2021-01-12T10:39:16.2317889Z 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
2021-01-12T10:39:16.2319887Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
2021-01-12T10:39:16.2321984Z 	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
2021-01-12T10:39:16.2324061Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
2021-01-12T10:39:16.2325995Z 	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
2021-01-12T10:39:16.2327936Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
2021-01-12T10:39:16.2330011Z 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
2021-01-12T10:39:16.2333160Z 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
2021-01-12T10:39:16.2337014Z 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
2021-01-12T10:39:16.2339322Z 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
2021-01-12T10:39:16.2341672Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
2021-01-12T10:39:16.2344113Z 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
2021-01-12T10:39:16.2346503Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
2021-01-12T10:39:16.2349091Z 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
2021-01-12T10:39:16.2351269Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
2021-01-12T10:39:16.2353617Z 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
2021-01-12T10:39:16.2355902Z 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
2021-01-12T10:39:16.2358227Z 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
2021-01-12T10:39:16.2360750Z 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
2021-01-12T10:39:16.2363018Z 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
2021-01-12T10:39:16.2365179Z 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
2021-01-12T10:39:16.2366973Z 	at org.eclipse.jetty.server.Server.handle(Server.java:501)
2021-01-12T10:39:16.2368485Z 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
2021-01-12T10:39:16.2370204Z 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
2021-01-12T10:39:16.2374142Z 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
2021-01-12T10:39:16.2376053Z 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272)
2021-01-12T10:39:16.2378078Z 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
2021-01-12T10:39:16.2379875Z 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
2021-01-12T10:39:16.2381635Z 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
2021-01-12T10:39:16.2383675Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
2021-01-12T10:39:16.2386374Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
2021-01-12T10:39:16.2389185Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
2021-01-12T10:39:16.2391787Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
2021-01-12T10:39:16.2394317Z 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
2021-01-12T10:39:16.2396918Z 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
2021-01-12T10:39:16.2399060Z 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
2021-01-12T10:39:16.2400454Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-12T10:39:16.2400935Z 
2021-01-12T10:39:16.2402658Z 	at io.trino.server.remotetask.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:62)
2021-01-12T10:39:16.2405808Z 	at io.trino.server.remotetask.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:27)
2021-01-12T10:39:16.2408259Z 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
2021-01-12T10:39:16.2410149Z 	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
2021-01-12T10:39:16.2412377Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-01-12T10:39:16.2414424Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-01-12T10:39:16.2415752Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-12T10:39:16.2416227Z 
```

**Comment by findepi** [comment]
Duplicates https://github.com/trinodb/trino/issues/6220
