### ISSUE TITLE
Flaky io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.assertTrinoCookie

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#6632]
```
io.trino.testng.services.FlakyTestRetryAnalyzer	not retrying; stacktrace 'java.lang.NullPointerException
2021-01-18T12:58:40.4733816Z 	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.assertTrinoCookie(TestOAuth2WebUiAuthenticationFilter.java:326)
2021-01-18T12:58:40.4738385Z 	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.lambda$testSuccessfulFlow$0(TestOAuth2WebUiAuthenticationFilter.java:247)
2021-01-18T12:58:40.4743134Z 	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.withSuccessfulAuthentication(TestOAuth2WebUiAuthenticationFilter.java:285)
2021-01-18T12:58:40.4748169Z 	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.testSuccessfulFlow(TestOAuth2WebUiAuthenticationFilter.java:245)
2021-01-18T12:58:40.4754875Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-01-18T12:58:40.4756948Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-01-18T12:58:40.4759340Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-01-18T12:58:40.4761101Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-01-18T12:58:40.4762717Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-01-18T12:58:40.4764434Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-01-18T12:58:40.4765741Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-01-18T12:58:40.4767136Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-01-18T12:58:40.4768879Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-01-18T12:58:40.4770591Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-01-18T12:58:40.4772259Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-01-18T12:58:40.4774154Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-01-18T12:58:40.4775308Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-18T12:58:40.4776352Z ' does not match pattern 'Trino-OAuth2-Token is missing'
```

**Comment by wendigo** [comment]
https://github.com/trinodb/trino/runs/1721101742?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/trinodb/trino/issues/6223
