### ISSUE TITLE
Transactions does not work when session properties are set using Session Property Manager

### ISSUE THREAD

**Issue by parasupreti** [trinodb/trino#6642]
When session properties are configured in presto server, transactions does not work and throws the issue.
Session properties cannot be overridden once a transaction is active
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at io.prestosql.Session.withDefaultProperties(Session.java:381)
	at io.prestosql.server.SessionPropertyDefaults.newSessionWithDefaultProperties(SessionPropertyDefaults.java:109)
	at io.prestosql.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:349)
	at io.prestosql.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:301)
	at io.prestosql.$gen.Presto_305____20201130_094529_1.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/Session.java#L397-L400

**Comment by findinpath** [comment]
Reproduce the issue:


As described in the documentation page:

https://trino.io/docs/current/admin/session-property-managers.html


Create a file `session-property-config.json` in `{trino_installation_dir}/etc` with the content:

```

    {
        "group": "global.*",
        "sessionProperties": {
            "query_max_execution_time": "8h"
        }
    },
    {
        "group": "global.interactive.*",
        "sessionProperties": {
            "query_max_execution_time": "1h"
        }
    },
    {
        "group": "global.pipeline.*",
        "clientTags": ["etl"],
        "sessionProperties": {
            "scale_writers": "true",
            "writer_min_size": "1GB",
            "hive.insert_existing_partitions_behavior": "overwrite"
        }
    }
]
```


```
START TRANSACTION;

SELECT * FROM tpch.sf1.nation LIMIT 1;
```
