### ISSUE TITLE
Flaky TestKafkaWithConfluentSchemaRegistryMinimalFunctionality - unable to start schema-registry docker

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#6646]
```
2021-01-19T15:25:54.6833038Z [ERROR] testBasicTopic(io.trino.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality)  Time elapsed: 55.607 s  <<< FAILURE!
2021-01-19T15:25:54.6841542Z org.testcontainers.containers.ContainerLaunchException: Container startup failed
2021-01-19T15:25:54.6849194Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
2021-01-19T15:25:54.6856534Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
2021-01-19T15:25:54.6862726Z 	at io.trino.testing.kafka.TestingKafka.start(TestingKafka.java:115)
2021-01-19T15:25:54.6870345Z 	at io.trino.plugin.kafka.KafkaQueryRunnerBuilder.build(KafkaQueryRunnerBuilder.java:68)
2021-01-19T15:25:54.6880110Z 	at io.trino.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.createQueryRunner(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:83)
2021-01-19T15:25:54.6888179Z 	at io.trino.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.testBasicTopic(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:92)
2021-01-19T15:25:54.6894039Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-01-19T15:25:54.6897185Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-01-19T15:25:54.6910024Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-01-19T15:25:54.6911775Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-01-19T15:25:54.6913349Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-01-19T15:25:54.6915031Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-01-19T15:25:54.6916308Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-01-19T15:25:54.6917702Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-01-19T15:25:54.6919405Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-01-19T15:25:54.6921094Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-01-19T15:25:54.6922861Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-01-19T15:25:54.6924552Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-01-19T15:25:54.6925662Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-19T15:25:54.6926815Z Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
2021-01-19T15:25:54.6928732Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
2021-01-19T15:25:54.6930828Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
2021-01-19T15:25:54.6931955Z 	... 18 more
2021-01-19T15:25:54.6933273Z Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
2021-01-19T15:25:54.6935255Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:497)
2021-01-19T15:25:54.6937400Z 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
2021-01-19T15:25:54.6939493Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
2021-01-19T15:25:54.6940725Z 	... 19 more
2021-01-19T15:25:54.6941998Z Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32801] should be listening)
2021-01-19T15:25:54.6944868Z 	at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:49)
2021-01-19T15:25:54.6948343Z 	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
2021-01-19T15:25:54.6951601Z 	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:892)
2021-01-19T15:25:54.6954103Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:440)
2021-01-19T15:25:54.6955274Z 	... 21 more
```

**Comment by findepi** [comment]
we already have two other issues for `TestKafkaWithConfluentSchemaRegistryMinimalFunctionality`

**Comment by kokosing** [comment]
This is one is about docker environment failing to start, so it is different.

**Comment by findepi** [comment]
> This is one is about docker environment failing to start, so it is different.

that's too subtle for me (i want to search issues by class name and get a straight answer), but i get the point

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/1741402857
```
2021-01-21T12:56:09.7997914Z org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32797] should be listening)
2021-01-21T12:56:09.8001462Z 	at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:49)
2021-01-21T12:56:09.8012192Z 	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
2021-01-21T12:56:09.8016060Z 	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:892)
2021-01-21T12:56:09.8022631Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:440)
2021-01-21T12:56:09.8025113Z 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
2021-01-21T12:56:09.8070763Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
2021-01-21T12:56:09.8073618Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
2021-01-21T12:56:09.8075921Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
2021-01-21T12:56:09.8077809Z 	at io.trino.testing.kafka.TestingKafka.start(TestingKafka.java:115)
2021-01-21T12:56:09.8079790Z 	at io.trino.plugin.kafka.KafkaQueryRunnerBuilder.build(KafkaQueryRunnerBuilder.java:68)
2021-01-21T12:56:09.8085293Z 	at io.trino.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.createQueryRunner(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:83)
2021-01-21T12:56:09.8094804Z 	at io.trino.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.testBasicTopic(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:92)
2021-01-21T12:56:09.8100899Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-01-21T12:56:09.8103296Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-01-21T12:56:09.8106160Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-01-21T12:56:09.8108076Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-01-21T12:56:09.8109843Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-01-21T12:56:09.8111727Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-01-21T12:56:09.8113130Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-01-21T12:56:09.8114662Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-01-21T12:56:09.8116533Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-01-21T12:56:09.8118401Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-01-21T12:56:09.8120368Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-01-21T12:56:09.8122418Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-01-21T12:56:09.8123738Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kokosing** [comment]
> that's too subtle for me (i want to search issues by class name and get a straight answer), but i get the point

That depends on how we want categorize flaky tests. I was thinking that maybe `Timed out waiting for container port to open ` can occur in other tests as well.

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/2129650515
```
2021-03-17T10:31:01.1975822Z [ERROR] testBasicTopic(io.trino.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality)  Time elapsed: 52.848 s  <<< FAILURE!
2021-03-17T10:31:01.1981491Z org.testcontainers.containers.ContainerLaunchException: Container startup failed
2021-03-17T10:31:01.1984047Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
2021-03-17T10:31:01.1986688Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
2021-03-17T10:31:01.1989346Z 	at io.trino.testing.kafka.TestingKafka.start(TestingKafka.java:115)
2021-03-17T10:31:01.1991568Z 	at io.trino.plugin.kafka.KafkaQueryRunnerBuilder.build(KafkaQueryRunnerBuilder.java:68)
2021-03-17T10:31:01.1997744Z 	at io.trino.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.createQueryRunner(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:83)
2021-03-17T10:31:01.2050116Z 	at io.trino.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.testBasicTopic(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:92)
2021-03-17T10:31:01.2056249Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-03-17T10:31:01.2059168Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-03-17T10:31:01.2062671Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-03-17T10:31:01.2064758Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-03-17T10:31:01.2066780Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-03-17T10:31:01.2068943Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-03-17T10:31:01.2070582Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-03-17T10:31:01.2072572Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-03-17T10:31:01.2074624Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-03-17T10:31:01.2076720Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-03-17T10:31:01.2078775Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-03-17T10:31:01.2080934Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-03-17T10:31:01.2082301Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-03-17T10:31:01.2083799Z Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
2021-03-17T10:31:01.2085938Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
2021-03-17T10:31:01.2088724Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
2021-03-17T10:31:01.2090128Z 	... 18 more
2021-03-17T10:31:01.2129095Z Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
2021-03-17T10:31:01.2135584Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:497)
2021-03-17T10:31:01.2138124Z 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
2021-03-17T10:31:01.2140699Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
2021-03-17T10:31:01.2142206Z 	... 19 more
2021-03-17T10:31:01.2143758Z Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [49181] should be listening)
2021-03-17T10:31:01.2147316Z 	at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:49)
2021-03-17T10:31:01.2151556Z 	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
2021-03-17T10:31:01.2155502Z 	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:892)
2021-03-17T10:31:01.2158545Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:440)
2021-03-17T10:31:01.2159952Z 	... 21 more
```
