### ISSUE TITLE
trino + ranger presto plugin problem

### ISSUE THREAD

**Issue by SessionBest** [trinodb/trino#6670]
trino + ranger presto plugin
```
trino version : 333
ranger version: 2.1
```

cli:

`java -jar presto-cli-333-executable.jar --server 127.0.0.1:8080 --catalog hive --schema default --user test`

error message:

```
presto:default> select * from db_test.t_test;
Query 20210121_030439_00004_paf4b failed: Access Denied: Cannot select from table db_test.t_test
```

other:
```
presto:default> show catalogs;
 Catalog
---------
 hive
 jmx
 system
(3 rows)
Query 20210121_031212_00008_paf4b, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

```

log:
`xaaudit	{"repoType":17,"repo":"prestodev","reqUser":"test","evtTime":"2021-01-21 11:12:12.996","resource":"system","resType":"catalog","action":"select","result":1,"agent":"presto","policy":7,"enforcer":"ranger-acl","agentHost":"data-mirror01","logType":"RangerAudit","id":"80f2016e-6487-4615-b804-bfd2c62971ff-69","seq_num":139,"event_count":1,"event_dur_ms":1,"tags":[],"cluster_name":"","policy_version":10}`

policy:
```
catalog : *
schema : *
table : *
cloumn : *
Permissions : all(select,insert,update,delete,show......)
Select User: root,test
```
Everything is fine for root users. Non-root users have problems.
How can I solve it?

**Comment by SessionBest** [comment]
![image](https://user-images.githubusercontent.com/22487139/105356210-15449800-5c2e-11eb-8a20-10aef95e7c28.png)

**Comment by SessionBest** [comment]
other msg:

```
io.prestosql.spi.security.AccessDeniedException: Access Denied: Cannot select from table db_test.t_test
	at io.prestosql.spi.security.AccessDeniedException.denySelectTable(AccessDeniedException.java:246)
	at io.prestosql.spi.security.AccessDeniedException.denySelectTable(AccessDeniedException.java:241)
	at io.prestosql.plugin.hive.security.SqlStandardAccessControl.checkCanSelectFromColumns(SqlStandardAccessControl.java:260)
	at io.prestosql.plugin.hive.security.SystemTableAwareAccessControl.checkCanSelectFromColumns(SystemTableAwareAccessControl.java:90)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorAccessControl.checkCanSelectFromColumns(ClassLoaderSafeConnectorAccessControl.java:204)
	at io.prestosql.security.AccessControlManager.lambda$checkCanSelectFromColumns$57(AccessControlManager.java:679)
	at io.prestosql.security.AccessControlManager.catalogAuthorizationCheck(AccessControlManager.java:907)
	at io.prestosql.security.AccessControlManager.checkCanSelectFromColumns(AccessControlManager.java:679)
	at io.prestosql.security.ForwardingAccessControl.checkCanSelectFromColumns(ForwardingAccessControl.java:279)
	at io.prestosql.sql.analyzer.Analyzer.lambda$analyze$0(Analyzer.java:88)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at io.prestosql.sql.analyzer.Analyzer.lambda$analyze$1(Analyzer.java:87)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:217)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:176)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:93)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:705)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
	at io.prestosql.$gen.Presto_333____20210122_030442_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
this last stacktrace is not apparently related to ranger (comes from `hive.security=sql-standard`'s impl)

can you please reach out for help on the `#troubleshooting` channel  on [our slack](https://trino.io/slack.html)?
we then would be able to close this issue

**Comment by SessionBest** [comment]
> this last stacktrace is not apparently related to ranger (comes from `hive.security=sql-standard`'s impl)
> 
> can you please reach out for help on the `#troubleshooting` channel on [our slack](https://trino.io/slack.html)?
> we then would be able to close this issue

`hive.security=sql-standard`  The reason for this, has now been solved

thanks very much.

**Comment by liujilei-97** [comment]
> trino + ranger presto plugin
> 
> ```
> trino version : 333
> ranger version: 2.1
> ```
> 
> cli:
> 
> `java -jar presto-cli-333-executable.jar --server 127.0.0.1:8080 --catalog hive --schema default --user test`
> 
> error message:
> 
> ```
> presto:default> select * from db_test.t_test;
> Query 20210121_030439_00004_paf4b failed: Access Denied: Cannot select from table db_test.t_test
> ```
> 
> other:
> 
> ```
> presto:default> show catalogs;
>  Catalog
> ---------
>  hive
>  jmx
>  system
> (3 rows)
> Query 20210121_031212_00008_paf4b, FINISHED, 1 node
> Splits: 19 total, 19 done (100.00%)
> 0:00 [0 rows, 0B] [0 rows/s, 0B/s]
> ```
> 
> log:
> `xaaudit {"repoType":17,"repo":"prestodev","reqUser":"test","evtTime":"2021-01-21 11:12:12.996","resource":"system","resType":"catalog","action":"select","result":1,"agent":"presto","policy":7,"enforcer":"ranger-acl","agentHost":"data-mirror01","logType":"RangerAudit","id":"80f2016e-6487-4615-b804-bfd2c62971ff-69","seq_num":139,"event_count":1,"event_dur_ms":1,"tags":[],"cluster_name":"","policy_version":10}`
> 
> policy:
> 
> ```
> catalog : *
> schema : *
> table : *
> cloumn : *
> Permissions : all(select,insert,update,delete,show......)
> Select User: root,test
> ```
> 
> Everything is fine for root users. Non-root users have problems.
> How can I solve it?


> trino + ranger presto plugin
> 
> ```
> trino version : 333
> ranger version: 2.1
> ```
> 
> cli:
> 
> `java -jar presto-cli-333-executable.jar --server 127.0.0.1:8080 --catalog hive --schema default --user test`
> 
> error message:
> 
> ```
> presto:default> select * from db_test.t_test;
> Query 20210121_030439_00004_paf4b failed: Access Denied: Cannot select from table db_test.t_test
> ```
> 
> other:
> 
> ```
> presto:default> show catalogs;
>  Catalog
> ---------
>  hive
>  jmx
>  system
> (3 rows)
> Query 20210121_031212_00008_paf4b, FINISHED, 1 node
> Splits: 19 total, 19 done (100.00%)
> 0:00 [0 rows, 0B] [0 rows/s, 0B/s]
> ```
> 
> log:
> `xaaudit {"repoType":17,"repo":"prestodev","reqUser":"test","evtTime":"2021-01-21 11:12:12.996","resource":"system","resType":"catalog","action":"select","result":1,"agent":"presto","policy":7,"enforcer":"ranger-acl","agentHost":"data-mirror01","logType":"RangerAudit","id":"80f2016e-6487-4615-b804-bfd2c62971ff-69","seq_num":139,"event_count":1,"event_dur_ms":1,"tags":[],"cluster_name":"","policy_version":10}`
> 
> policy:
> 
> ```
> catalog : *
> schema : *
> table : *
> cloumn : *
> Permissions : all(select,insert,update,delete,show......)
> Select User: root,test
> ```
> 
> Everything is fine for root users. Non-root users have problems.
> How can I solve it?

能分享下你的ranger对接prestosql的文档嘛

**Comment by AllenWod** [comment]
can you share you document
