### ISSUE TITLE
Oracle connector ignore column which data type is number without precision and scale

### ISSUE THREAD

**Issue by wgzhao** [trinodb/trino#6700]
## issue

If oracle table include a column that the column's data type is `number`  without precision and scale,  Oracle connector will ignore it .

## reappear

The following instructions can reappear the above 

```sql
-- create table in oracle
CREATE TABLE eam.trino_tbl (col1 NUMBER(10), col2 NUMBER, col3 varchar2(10) );
```
query above table in trino with oracle connector

```sql
trino:eam> select * from eam.trino_tbl;
 col1 | col3
------+------
(0 rows)

Query 20210123_063845_00007_e7vng, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
1.58 [0 rows, 0B] [0 rows/s, 0B/s]

trino:eam> desc eam.trino_tbl;
 Column |     Type      | Extra | Comment
--------+---------------+-------+---------
 col1   | decimal(10,0) |       |
 col3   | varchar(10)   |       |
(2 rows)

Query 20210123_063904_00008_e7vng, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
1.00 [2 rows, 134B] [1 rows/s, 134B/s]
```

## env

- OS: MacOS Big Sur
- Trino version: 351
- Oracle Database version: Oracle database enterprise 11.2.0.1.0

**Comment by ebyhr** [comment]
It's duplicate of https://github.com/trinodb/trino/issues/4764, please set `oracle.number.default-scale` property.

**Comment by wgzhao** [comment]
Yes, I saw the guide later, but it's confused to me, I have the above table  and has the following records:

```sql
SELECT * FROM eam.TRINO_TBL tt ;

COL1|COL2                                     |COL3 |
----|-----------------------------------------|-----|
  10|                         1234568.12345678|hello|
  10|                      1234568.12345678912|hello|
  10|  1234567891234567891234567891.1234567891|hello|
  10| 12345678912345678912345678912.1234567891|hello|
  10|123456789123456789123456789124.1234567891|hello|
  10| 12345678912345678912345678912412345.1235|hello|
```

I try to set `oracle.number.default-scale` property,  error occurred.

## setup 1

```ini
oracle.number.default-scale=10
```

**result:**

```sql
trino:eam> desc eam.trino_tbl ;
 Column |      Type      | Extra | Comment
--------+----------------+-------+---------
 col1   | decimal(10,0)  |       |
 col2   | decimal(38,10) |       |
 col3   | varchar(10)    |       |
(3 rows)

Query 20210123_074713_00000_cx8zw, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
4.34 [3 rows, 203B] [0 rows/s, 47B/s]

trino:eam> select * from eam.trino_tbl;

Query 20210123_074723_00001_cx8zw, FAILED, 1 node
Splits: 17 total, 0 done (0.00%)
0.65 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20210123_074723_00001_cx8zw failed: Rounding necessary
```

## setup 2

```ini
# oracle.number.default-scale=10
oracle.number.rounding-mode= CEILING
```

**result**

```
trino:eam> desc eam.trino_tbl;
 Column |     Type      | Extra | Comment
--------+---------------+-------+---------
 col1   | decimal(10,0) |       |
 col3   | varchar(10)   |       |
(2 rows)
```

## setup 3

```ini
oracle.number.default-scale=5
```

**result**

```sql
trino:eam> desc eam.trino_tbl;
 Column |     Type      | Extra | Comment
--------+---------------+-------+---------
 col1   | decimal(10,0) |       |
 col2   | decimal(38,5) |       |
 col3   | varchar(10)   |       |
(3 rows)

trino:eam> select * from eam.trino_tbl;

Query 20210123_075055_00001_vu5s6, FAILED, 1 node
Splits: 17 total, 0 done (0.00%)
0.77 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20210123_075055_00001_vu5s6 failed: Decimal overflow
```

## setup 4

```ini
oracle.number.default-scale=-5
oracle.number.rounding-mode= CEILING
```

**result**

```
2021-01-23T15:52:27.993+0800	ERROR	main	io.trino.server.Server	Configuration errors:

1) Error: Invalid configuration property oracle.number.default-scale: must be greater than or equal to 0 (for class io.trino.plugin.oracle.OracleConfig.defaultNumberScale)

1 error
io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Invalid configuration property oracle.number.default-scale: must be greater than or equal to 0 (for class io.trino.plugin.oracle.OracleConfig.defaultNumberScale)

1 error
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:239)
	at io.trino.plugin.jdbc.JdbcConnectorFactory.create(JdbcConnectorFactory.java:84)
	at io.trino.connector.ConnectorManager.createConnector(ConnectorManager.java:354)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:211)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:203)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:189)
	at io.trino.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
	at io.trino.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at io.trino.server.Server.doStart(Server.java:119)
	at io.trino.server.Server.lambda$start$0(Server.java:73)
	at io.trino.$gen.Trino_351____20210123_075220_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:73)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
```

**Comment by ebyhr** [comment]
In setup 4, please fix `-5`.

**Comment by wgzhao** [comment]
## case 5

```ini
oracle.number.default-scale=10
oracle.number.rounding-mode= CEILING
```

**result**

```sql
desc ema.trino_tbl

trino:eam> desc eam.trino_tbl;
 Column |      Type      | Extra | Comment
--------+----------------+-------+---------
 col1   | decimal(10,0)  |       |
 col2   | decimal(38,10) |       |
 col3   | varchar(10)    |       |
(3 rows)

Query 20210123_095443_00002_27ivn, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
1.49 [3 rows, 203B] [2 rows/s, 136B/s]

trino:eam> select * from trino_tbl;

Query 20210123_095451_00003_27ivn, FAILED, 1 node
Splits: 17 total, 0 done (0.00%)
0.60 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20210123_095451_00003_27ivn failed: Decimal overflow
```

All cases failed, the root cause is how to configure `oracle.number.default-scale` to  match dynamic precision and scale.

the number type in  Oracle, its precision and scale can be dynamic, as long as the sum of the two does not exceed 40.
So it is allowed to the length of  precision is greater than 38 or the length of  scale is greater than 10.
 In trino,  using decimal to express the number type, and fixing the length of precision not to exceed 38, which makes the value  such as ` 12345678912345678912345678912345678912412345.1235`  will be overflow when querying

**Comment by findepi** [comment]
As discussed in https://github.com/trinodb/trino/issues/4764, mapping the Oracle's NUMBER, without any downsides or implicit lossy conversions, would require introducing a new type to Trino.


I am closing this in favor of https://github.com/trinodb/trino/issues/2274

**Comment by findepi** [comment]
Finally fixed in
- https://github.com/trinodb/trino/pull/28748
