### ISSUE TITLE
Flaky TestJoinQueriesWithoutDynamicFiltering.testOutputDuplicatesInsensitiveJoin

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#6715]
```
2021-01-25T17:19:45.6321786Z [ERROR] testOutputDuplicatesInsensitiveJoin(io.trino.tests.TestJoinQueriesWithoutDynamicFiltering)  Time elapsed: 0.317 s  <<< FAILURE!
2021-01-25T17:19:45.6323613Z java.lang.AssertionError: expected [1] but found [0]
2021-01-25T17:19:45.6326014Z 	at org.testng.Assert.fail(Assert.java:94)
2021-01-25T17:19:45.6329052Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2021-01-25T17:19:45.6332193Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2021-01-25T17:19:45.6334982Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2021-01-25T17:19:45.6338047Z 	at org.testng.Assert.assertEquals(Assert.java:389)
2021-01-25T17:19:45.6340920Z 	at org.testng.Assert.assertEquals(Assert.java:399)
2021-01-25T17:19:45.6347655Z 	at io.trino.testing.AbstractTestJoinQueries.assertJoinOutputPositions(AbstractTestJoinQueries.java:2343)
2021-01-25T17:19:45.6354004Z 	at io.trino.testing.AbstractTestJoinQueries.testOutputDuplicatesInsensitiveJoin(AbstractTestJoinQueries.java:2311)
2021-01-25T17:19:45.6357740Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-01-25T17:19:45.6363344Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-01-25T17:19:45.6369269Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-01-25T17:19:45.6371811Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-01-25T17:19:45.6404321Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-01-25T17:19:45.6409713Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-01-25T17:19:45.6413410Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-01-25T17:19:45.6417607Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-01-25T17:19:45.6422360Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-01-25T17:19:45.6425989Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-01-25T17:19:45.6431325Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-01-25T17:19:45.6436196Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-01-25T17:19:45.6438596Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sopel39** [comment]
Another occurrence of: https://github.com/trinodb/trino/issues/5172

**Comment by kokosing** [comment]
I don't think we should close this. The issue is still there.

**Comment by sopel39** [comment]
What do you mean? Don't we close issues when we add `@Flaky` annotation. In reality this is another instance of https://github.com/trinodb/trino/issues/5172
