### ISSUE TITLE
Debugger the source, it popup error:  java.io.FileNotFoundException: etc/config.properties (No such file or directory)

### ISSUE THREAD

**Issue by hgq108** [trinodb/trino#6737]
I have downloaded the trino 351 sourcecode ,and try to debug in VM. It pop up such error msg:

---------------------------------------------------------------------------------------------------------------------------------------
Connected to the target VM, address: '127.0.0.1:49355', transport: 'socket'
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Jan 27, 2021 9:13:46 PM io.airlift.log.Logger info
INFO: Java version: 11.0.9.1
2021-01-27T21:13:46.139+0800	INFO	main	io.airlift.log.Logging	Logging to stderr
2021-01-27T21:13:46.144+0800	INFO	main	Bootstrap	Loading configuration
2021-01-27T21:13:46.147+0800	ERROR	main	io.trino.server.Server	java.io.FileNotFoundException: etc/config.properties (No such file or directory)
java.io.UncheckedIOException: java.io.FileNotFoundException: etc/config.properties (No such file or directory)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:185)
	at io.trino.server.Server.doStart(Server.java:111)
	at io.trino.server.Server.lambda$start$0(Server.java:73)
	at io.trino.$gen.Trino_unknown____20210127_131345_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:73)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
Caused by: java.io.FileNotFoundException: etc/config.properties (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at io.airlift.configuration.ConfigurationLoader.loadPropertiesFrom(ConfigurationLoader.java:60)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:182)
	... 5 more

Disconnected from the target VM, address: '127.0.0.1:49355', transport: 'socket'

Process finished with exit code 1
------------------------------------------------------------------------------------------------------------------------------------
Actually, the path etc/config.properties exists;
![trino_error](https://user-images.githubusercontent.com/3616578/105998023-32261300-60e7-11eb-816c-9044b2d6ecdc.png)

**Comment by hgq108** [comment]
The setting of Working directory was wrong . It's ok now.
