### ISSUE TITLE
Oracle connector opens too many connections when  inserting into oracle table

### ISSUE THREAD

**Issue by lupengfei-johnson** [trinodb/trino#6801]
Oracle connector use connection-pool with this configuration :

oracle.connection-pool.max-size=40  
oracle.connection-pool.min-size=1  
oracle.connection-pool.inactive-timeout=20m  

Some queries failed when I run 30+ queries ,error msg is :
`
io.trino.spi.TrinoException: 获取连接时出现异常错误: oracle.ucp.UniversalConnectionPoolException: Universal Connection Pool 中的所有连接均在使用中 
	at io.trino.plugin.jdbc.JdbcPageSink.<init>(JdbcPageSink.java:57)
	at io.trino.plugin.jdbc.JdbcPageSinkProvider.createPageSink(JdbcPageSinkProvider.java:47)
	at io.trino.split.PageSinkManager.createPageSink(PageSinkManager.java:61)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:122)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:113)
	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:114)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:942)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1070)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_351____20210201_113054_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.SQLException: 获取连接时出现异常错误: oracle.ucp.UniversalConnectionPoolException: Universal Connection Pool 中的所有连接均在使用中
	at oracle.ucp.util.UCPErrorHandler.newSQLException(UCPErrorHandler.java:456)
	at oracle.ucp.util.UCPErrorHandler.throwSQLException(UCPErrorHandler.java:133)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:2004)
	at oracle.ucp.jdbc.PoolDataSourceImpl.access$400(PoolDataSourceImpl.java:201)
	at oracle.ucp.jdbc.PoolDataSourceImpl$31.build(PoolDataSourceImpl.java:4279)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1917)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1880)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1865)
	at io.trino.plugin.oracle.OraclePoolConnectionFactory.openConnection(OraclePoolConnectionFactory.java:83)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:42)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:42)
	at io.trino.plugin.jdbc.BaseJdbcClient.getConnection(BaseJdbcClient.java:730)
	at io.trino.plugin.jdbc.ForwardingJdbcClient.getConnection(ForwardingJdbcClient.java:191)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getConnection$26(StatisticsAwareJdbcClient.java:244)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getConnection(StatisticsAwareJdbcClient.java:244)
	at io.trino.plugin.jdbc.CachingJdbcClient.getConnection(CachingJdbcClient.java:265)
	at io.trino.plugin.jdbc.JdbcPageSink.<init>(JdbcPageSink.java:54)
	... 13 more
Caused by: oracle.ucp.UniversalConnectionPoolException: Universal Connection Pool 中的所有连接均在使用中
	at oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:336)
	at oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:59)
	at oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:106)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionWithoutCountingRequests(UniversalConnectionPoolImpl.java:289)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionAndValidate(UniversalConnectionPoolImpl.java:153)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnection(UniversalConnectionPoolImpl.java:122)
	at oracle.ucp.jdbc.JDBCConnectionPool.borrowConnection(JDBCConnectionPool.java:174)
	at oracle.ucp.jdbc.oracle.OracleJDBCConnectionPool.borrowConnection(OracleJDBCConnectionPool.java:613)
	at oracle.ucp.jdbc.oracle.OracleConnectionConnectionPool.borrowConnection(OracleConnectionConnectionPool.java:103)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1981)
`  

The connection-pool is used up. It may cause high pressure on Oracle if setting connection-pool size too large , how to slove it ?

**Comment by losipiuk** [comment]
With `task.writer-count=1` (default)  INSERT queries should use a single connection to Oracle per node per query to do writing. If data is also read from Oracle then extra connection for reading will be used; but for that a single connection on arbitrary worker node will be used per query.

If you set up the pool limit to 40 and run 30+ queries you are near boundary just on write tasks. And if you are also reading from Oracle you can easily cross it.
Nothing better than throttling number of queries which execute concurrently comes to my mind. You should be able to use resource groups mechanism for that. See https://trino.io/docs/current/admin/resource-groups.html.

I will close this issue now. If you need more help with that please reach out on #troubleshooting channel on http://trinodb.slack.com.
