### ISSUE TITLE
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/Request when starting trinodb on a fresh install

### ISSUE THREAD

**Issue by mujahid** [trinodb/trino#6830]
Facing the following error on single node startup: 
**bin/launcher run**: 
```
Feb 05, 2021 11:23:49 PM io.airlift.log.Logger info
INFO: Java version: 11.0.10
2021-02-05T23:23:49.980+0530    INFO    main    io.airlift.log.Logging  Logging to stderr
2021-02-05T23:23:49.982+0530    INFO    main    Bootstrap       Loading configuration
2021-02-05T23:23:50.198+0530    INFO    main    Bootstrap       Initializing logging
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/data/trino/trino-sib/guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.Protect
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-02-05T23:23:50.557+0530    ERROR   main    io.trino.server.Server  org/eclipse/jetty/server/Request
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/Request
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3191)
        at java.base/java.lang.Class.getMethods(Class.java:1904)
        at io.airlift.event.client.AnnotationUtils.findAnnotatedMethods(AnnotationUtils.java:40)
        at io.airlift.event.client.EventTypeMetadata.<init>(EventTypeMetadata.java:107)
        at io.airlift.event.client.EventTypeMetadata.getEventTypeMetadata(EventTypeMetadata.java:70)
        at io.airlift.event.client.EventBinder.bindGenericEventClient(EventBinder.java:67)
        at io.airlift.event.client.EventBinder.bindGenericEventClient(EventBinder.java:54)
        at io.airlift.event.client.EventBinder.bindEventClient(EventBinder.java:48)
        at io.airlift.http.server.HttpServerModule.configure(HttpServerModule.java:81)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:347)
        at com.google.inject.spi.Elements.getElements(Elements.java:104)
        at com.google.inject.spi.Elements.getElements(Elements.java:97)
        at io.airlift.configuration.ConfigurationFactory.registerConfigurationClasses(ConfigurationFactory.java:164)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:223)
        at io.trino.server.Server.doStart(Server.java:111)
        at io.trino.server.Server.lambda$start$0(Server.java:73)
        at io.trino.$gen.Trino_351____20210205_175349_1.run(Unknown Source)
        at io.trino.server.Server.start(Server.java:73)
        at io.trino.server.TrinoServer.main(TrinoServer.java:38)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.Request
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base
```

**OS:** 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
```
**Java:** 
```
openjdk 11.0.10 2021-01-19 LTS
OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)
```

**Configs :** 

 **jvm.config**
```
-server
-Xmx8G
-XX:-UseBiasedLocking
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+ExitOnOutOfMemoryError
-XX:+HeapDumpOnOutOfMemoryError
-XX:ReservedCodeCacheSize=512M
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-Djdk.attach.allowAttachSelf=true
-Djdk.nio.maxCachedBufferSize=2000000
```
**node.properties**
```
node.environment=production
node.id=worker-cordinator-1
node.data-dir=/data/trino/data
```
**config.properties**
```
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
query.max-memory=5GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
discovery-server.enabled=true
discovery.uri=http://localhost:8080

```

**Comment by electrum** [comment]
This is strange. How did you install Trino? It’s possible one of the JAR files in your installation is corrupt. Can you try to unpack the server tarball again?

**Comment by mujahid** [comment]
It was due to a storage issue. Unpacking it  a different set up worked as expected. Thanks for the direction
