### ISSUE TITLE
CREATE TABLE ... AS TABLE fails at planning when source table has hidden columns: VerifyException

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6835]
```
trino> USE postgresql.public;
USE 

trino:public> CREATE TABLE orders AS TABLE tpch.tiny.orders;
Query 20210206_133916_00024_fhi28 failed: columnNames.size() != symbols.size(): [orderkey, custkey, orderstatus, totalprice, orderdate, orderpriority, clerk, shippriority, comment] and [orderkey, custkey, orderstatus, totalprice, orderdate, orderpriority, clerk, shippriority, comment, row_number]
com.google.common.base.VerifyException: columnNames.size() != symbols.size(): [orderkey, custkey, orderstatus, totalprice, orderdate, orderpriority, clerk, shippriority, comment] and [orderkey, custkey, orderstatus, totalprice, orderdate, orderpriority, clerk, shippriority, comment, row_number]
	at com.google.common.base.Verify.verify(Verify.java:424)
	at io.trino.sql.planner.LogicalPlanner.createTableWriterPlan(LogicalPlanner.java:516)
	at io.trino.sql.planner.LogicalPlanner.createTableCreationPlan(LogicalPlanner.java:358)
	at io.trino.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:246)
	at io.trino.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:237)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:202)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:197)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:192)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:450)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:430)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:382)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20210206_133422_3.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

relates to: https://github.com/trinodb/trino/issues/6837

**Comment by kasiafi** [comment]
Fixed by https://github.com/trinodb/trino/pull/6841

**Comment by peter-long-nguyen** [comment]
**Query SQL:** Select statement from iceberg catalog
**Errror:** com.google.common.base.VerifyException: undefined
	at com.google.common.base.Verify.verify(Verify.java:102)
	at io.trino.sql.planner.AdaptivePlanner.addAdaptivePlanNode(AdaptivePlanner.java:219)
	at io.trino.sql.planner.AdaptivePlanner.addAdaptivePlanNode(AdaptivePlanner.java:224)
	at io.trino.sql.planner.AdaptivePlanner.addAdaptivePlanNode(AdaptivePlanner.java:224)
	at io.trino.sql.planner.AdaptivePlanner.addAdaptivePlanNode(AdaptivePlanner.java:224)
	at io.trino.sql.planner.AdaptivePlanner.addAdaptivePlanNode(AdaptivePlanner.java:224)
	at io.trino.sql.planner.AdaptivePlanner.addAdaptivePlanNode(AdaptivePlanner.java:224)
	at io.trino.sql.planner.AdaptivePlanner.addAdaptivePlanNode(AdaptivePlanner.java:224)
	at io.trino.sql.planner.AdaptivePlanner.addAdaptivePlanNode(AdaptivePlanner.java:224)
	at io.trino.sql.planner.AdaptivePlanner.addAdaptivePlanNode(AdaptivePlanner.java:224)
	at io.trino.sql.planner.AdaptivePlanner.optimize(AdaptivePlanner.java:156)
	at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.optimizePlan(EventDrivenFaultTolerantQueryScheduler.java:1130)
	at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.optimize(EventDrivenFaultTolerantQueryScheduler.java:1089)
	at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.schedule(EventDrivenFaultTolerantQueryScheduler.java:1021)
	at io.trino.execution.scheduler.faulttolerant.EventDrivenFaultTolerantQueryScheduler$Scheduler.run(EventDrivenFaultTolerantQueryScheduler.java:847)
	at io.trino.$gen.Trino_470____20251016_103033_2.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by findepi** [comment]
@peter-long-nguyen can you please make sure this reproduces on the lates release and create a new issue?
This one was closed 4 years ago.
