### ISSUE TITLE
Failure when CTE defined with TABLE having hidden columns: IllegalArgumentException

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6837]
```
trino:public> WITH t AS (TABLE tpch.tiny.nation)
           -> SELECT * FROM t;
Query 20210206_165624_00002_aaadx failed: Internal error
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
	at io.trino.sql.planner.QueryPlanner.coerce(QueryPlanner.java:1266)
	at io.trino.sql.planner.RelationPlanner.visitTable(RelationPlanner.java:188)
	at io.trino.sql.planner.RelationPlanner.visitTable(RelationPlanner.java:105)
	at io.trino.sql.tree.Table.accept(Table.java:53)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.QueryPlanner.planFrom(QueryPlanner.java:584)
	at io.trino.sql.planner.QueryPlanner.plan(QueryPlanner.java:373)
	at io.trino.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:786)
	at io.trino.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:105)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:575)
	at io.trino.sql.planner.QueryPlanner.plan(QueryPlanner.java:183)
	at io.trino.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:779)
	at io.trino.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:105)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:690)
	at io.trino.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:266)
	at io.trino.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:237)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:202)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:197)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:192)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:450)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:430)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:382)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_unknown____20210206_165502_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

same also if the hidden column is referenced
```
trino:public> WITH t AS (TABLE tpch.tiny.nation)
           -> SELECT *, row_number FROM t;
Query 20210206_171536_00018_aaadx failed: Internal error
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
	at io.trino.sql.planner.QueryPlanner.coerce(QueryPlanner.java:1266)
...
```
(here _probably_ the `row_number` should not be selectable anymore?)

relates to: https://github.com/trinodb/trino/issues/6835

**Comment by martint** [comment]
Probably related to https://github.com/trinodb/trino/pull/4423

**Comment by kasiafi** [comment]
Fixed by https://github.com/trinodb/trino/pull/6838
