### ISSUE TITLE
Unit test fails at memsql plugin

### ISSUE THREAD

**Issue by byungnam** [trinodb/trino#6845]
## Problem
Unit test fails at memsql plugin. The error says that env var `memsql.license` is not set?

```
[ERROR] Tests run: 207, Failures: 4, Errors: 0, Skipped: 200, Time elapsed: 5.682 s <<< FAILURE! - in TestSuite
[ERROR] init(io.trino.plugin.memsql.TestMemSqlDistributedQueries)  Time elapsed: 1.185 s  <<< FAILURE!
java.lang.ExceptionInInitializerError
	at io.trino.plugin.memsql.TestMemSqlDistributedQueries.createQueryRunner(TestMemSqlDistributedQueries.java:38)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: memsql.license is not set
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at io.trino.plugin.memsql.TestingMemSqlServer.<clinit>(TestingMemSqlServer.java:31)
	... 15 more
...
```

## Test Environment
- Trino version: 351
- OS: Centos 7
- Java: Adopt Open JDK 11.0.8+10

**Comment by hashhar** [comment]
You need to set the JVM property `memsql.license` to a string containing your MemSQL license.

See https://docs.singlestore.com/v7.3/guides/deploy-memsql/self-managed/docker/step-1/#get-a-license-key for how to get the license.

Please feel free to continue this discussion on #troubleshooting on the Trino slack at https://trino.io/slack.html.

**Comment by byungnam** [comment]
@hashhar 
Thank you for the information. I'll try that.

But I feel somewhat awkward that I need to put some extra information for the unit test. I hope Trino can get rid of it in the future if possible. :)

**Comment by findepi** [comment]
> But I feel somewhat awkward that I need to put some extra information for the unit test. I hope Trino can get rid of it in the future if possible. :)

@byungnam i couldn't agree more. However, this is not our choice  -- MemSQL is not a free software.
The only solution on _our side_ would be to delete the tests... 

Note that you can easily skip tests when running locally with `-DskipTests`.
Also, we could move the tests requiring the MemSQL's license to a profile, so that they are not run by default for a local build.
