### ISSUE TITLE
MySQL connector serialize issue for timestamp with precision higher than 3

### ISSUE THREAD

**Issue by sparkheo7** [trinodb/trino#6852]
Dear Team,
I am facing a column serialize issue while querying the MySQL table having a DateTime column. I got this error on Trino CLI as and in DBeaver via JDBC driver. 

Environment details are as mentioned below.
**Trino JDBC** :- trino-jdbc-351
**Trino CLI** :- trino-cli-351
**Mysql Column data type** :- created_ts datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
Stack trace error for same is as mentioned below.
```
Query 20210209_004107_00005_pcxwf failed: Could not serialize column 'created_ts' of type 'timestamp(3)' at position 1:3
io.trino.spi.TrinoException: Could not serialize column 'created_ts' of type 'timestamp(3)' at position 1:3
	at io.trino.server.protocol.QueryResultRows.lambda$propagateException$3(QueryResultRows.java:261)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.trino.server.protocol.QueryResultRows.propagateException(QueryResultRows.java:261)
	at io.trino.server.protocol.QueryResultRows.getRowValues(QueryResultRows.java:183)
	at io.trino.server.protocol.QueryResultRows.computeNext(QueryResultRows.java:154)
	at io.trino.server.protocol.QueryResultRows.computeNext(QueryResultRows.java:64)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serializeContents(IterableSerializer.java:83)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:74)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:12)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1513)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1005)
	at io.airlift.jaxrs.JsonMapper.write(JsonMapper.java:108)
	at io.airlift.jaxrs.AbstractJacksonMapper.writeTo(AbstractJacksonMapper.java:157)
	at io.airlift.jaxrs.JsonMapper.writeTo(JsonMapper.java:44)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:662)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:884)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:916)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872)
	at io.airlift.jaxrs.AsyncResponseHandler$1.onSuccess(AsyncResponseHandler.java:102)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Expected 0s for digits beyond precision 3: epochMicros = 1607056982713280
	at io.trino.spi.type.SqlTimestamp.newInstance(SqlTimestamp.java:51)
	at io.trino.spi.type.ShortTimestampType.getObjectValue(ShortTimestampType.java:125)
	at io.trino.server.protocol.QueryResultRows.getRowValues(QueryResultRows.java:176)
	... 44 more
```

**Comment by sparkheo7** [comment]
I tried this with trino-jdbc-353.jar and I am still facing the same issue. Is this fix part of trino-jdbc-353.jar ?

**Comment by hashhar** [comment]
The bug was on the server not the JDBC driver. So updating the JDBC driver isn't going to solve this. You need to update the Trino version to 353.

**Comment by sparkheo7** [comment]
oh ok. Thank you @hashhar for a quick update. Will try and update you on the same.

**Comment by sparkheo7** [comment]
It's working. Thank you @hashhar
