### ISSUE TITLE
Enable cross cluster search via Elasticsearch connector

### ISSUE THREAD

**Issue by MusKaya** [trinodb/trino#6939]
**Introduction:**
Elasticsearch can be setup in a way that we can run a single search request against one or more remote clusters ([cross-cluster search](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/modules-cross-cluster-search.html)).

This basically works when we query against an [Elasticsearch cluster which has remote clusters configured to it](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/cluster-remote-info.html).

For instance, assuming that _my-search-head-cluster_ is such a cluster (with remote clusters configured to it), I can execute `curl http://my-search-head-cluster:9200/*:index-prefix*/_search` and receive results **from all indices** that start with `index-prefix` (the pattern after the `:`) **from across all remote clusters** configured on _my-es-host_ (note the wildcard `*` before the `:`).

This is a pretty neat future if you're dealing with high volumes of data something that is indispensable. 

**Problem Statement:**
However, as of the date of writing, Trino does not support such searches. When I run a query like `SELECT 1 FROM elasticsearch_searchhead.indices."*:prefix*" LIMIT 1`, I receive the following error (note that the mentioned `some_column_name:data_type` on the error message varies from error to error - so it's getting picked arbitrarily).

```
trino> SELECT 1 FROM elasticsearch_searchhead.indices."*:prefix*" LIMIT 1;
Query 20210218_013912_00000_a8aup failed: Unknown field elasticsearch_searchhead.indices.*:prefix*.some_column_name:data_type
java.lang.IllegalArgumentException: Unknown field elasticsearch_searchhead.indices.*:maat*.some_column_name:data_type
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1247)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:329)
	at io.trino.sql.tree.Table.accept(Table.java:53)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:346)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2529)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1553)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:329)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:346)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:356)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1061)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:329)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:346)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:315)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:263)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:186)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:768)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:129)
	at io.trino.$gen.Trino_351____20210218_013857_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
``` 

**Additional Info:**
As per @bitsondatadev :
> So that wildcard will enumerate any elasticsearch index that exists on that cluster. It currently only chooses the mapping of the first index right now So you may be using a mapping that doesn’t have the completed field and yet a document that has one.
So, #2748 might be why the error is thrown in the first place.

**Thoughts**
One caveat, by design, of cross-cluster-search is that the index mappings of the remote clusters are not visible to _my-search-head-cluster_. --> Could there be a similar solution such as [#2508](https://github.com/trinodb/trino/issues/2508), where we poll a sample set of documents and infer the mapping from them?

**Comment by findinpath** [comment]
@MusKaya  this sound a bit like what is being done in Kibana for querying Elasticsearch logs right?

**Comment by MusKaya** [comment]
yes

**Comment by MusKaya** [comment]
> @MusKaya this sound a bit like what is being done in Kibana for querying Elasticsearch logs right?

yes
