### ISSUE TITLE
/dev by zero with Elastic Cloud

### ISSUE THREAD

**Issue by letmagnau** [trinodb/trino#6950]
Hi All,

i'm using trino db with the elasticsearch plugin on Elastic Cloud managed byAzure
I'm not have problem with config , the plugin works and I'm able to connect with ES instance and
see alla catalogs and schemas and table but , when I'm trying to execute a simple query on any
table , it fails whit the error :

**rg.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [65536]: Query failed (#20210218_151706_00047_xr6qj): / by zero
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:509)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:440)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:427)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:812)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3220)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:119)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4516)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Query failed (#20210218_151706_00047_xr6qj): / by zero
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1912)
	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:242)
	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:53)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:249)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:227)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:327)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	... 12 more
Caused by: java.lang.ArithmeticException: / by zero
	at io.trino.plugin.elasticsearch.client.ElasticsearchClient.getSearchShards(ElasticsearchClient.java:425)
	at io.trino.plugin.elasticsearch.ElasticsearchSplitManager.getSplits(ElasticsearchSplitManager.java:60)
	at io.trino.split.SplitManager.getSplits(SplitManager.java:87)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitScanAndFilter(DistributedExecutionPlanner.java:203)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:185)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:156)
	at io.trino.sql.planner.plan.TableScanNode.accept(TableScanNode.java:143)
	at io.trino.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:124)
	at io.trino.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:131)
	at io.trino.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:101)
	at io.trino.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:470)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:386)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_351____20210218_115835_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)**

I'm not understanding exactly why. I've found the problem is here, in class ElasticsearchClient.java at the method 

public List<Shard> getSearchShards(String index) 

            SearchShardsResponse.Shard chosen;
            ElasticsearchNode node;
            if (candidate.isEmpty()) {
                // pick an arbitrary shard with and assign to an arbitrary node
                chosen = shardGroup.stream()
                        .min(this::shardPreference)
                        .get();
                **### node = nodes.get(chosen.getShard() % nodes.size());**
            }
            else {
                chosen = candidate.get();
                node = nodeById.get(chosen.getNode());
            }

   I'm also noted that in my system.nodes , table nodes is empty. can means anything?

Thanks in advance

Piero

**Comment by aalbu** [comment]
It looks like Trino might not be able to get a list of nodes from ES.  Do you see anything relevant in the logs?  What do you get back if you run:
```
curl http://<elasticsearch ip>:<elasticsearch port>/_nodes/http?pretty
```

**Comment by martint** [comment]
You might be able to work around this issue by enabling the `elasticsearch.ignore-publish-address` option in the catalog config file.

**Comment by letmagnau** [comment]
> It looks like Trino might not be able to get a list of nodes from ES. Do you see anything relevant in the logs? What do you get back if you run:
> 
> ```
> curl http://<elasticsearch ip>:<elasticsearch port>/_nodes/http?pretty
> ```

Hi aalbu, i've no problem with this request, it works perfectly and it says me all the nodes available on my cluster. Obviously I run it on https , can be a problem in trino startup ?

**Comment by letmagnau** [comment]
> You might be able to work around this issue by enabling the `elasticsearch.ignore-publish-address` option in the catalog config file.

this is not a solution. It not works.
I've tryied to add in my catalog properties it , but no it's changed

**Comment by letmagnau** [comment]
> > It looks like Trino might not be able to get a list of nodes from ES. Do you see anything relevant in the logs? What do you get back if you run:
> > ```
> > curl http://<elasticsearch ip>:<elasticsearch port>/_nodes/http?pretty
> > ```
> 
> Hi aalbu, i've no problem with this request, it works perfectly and it says me all the nodes available on my cluster. Obviously I run it on https , can be a problem in trino startup ?

Seems that he query curl `https://<elasticsearch ip>:<elasticsearch port>/_nodes/**https**?pretty` to create table nodes, and it is empty
I think there is a bug even if you want to access to cluster in https, because if I call : 
curl `https://<elasticsearch ip>:<elasticsearch port>/_nodes/http?pretty`  , the attending output was good.

regards

**Comment by aalbu** [comment]
> Obviously I run it on https

Right, however you have it configured.

Could you post the result of the call
```curl https://<elasticsearch ip>:<elasticsearch port>/_nodes/http?pretty```

Note that the URL path should be `/_nodes/http`, not `/_nodes/https`.

**Comment by letmagnau** [comment]
sure, in attachment you can find it

but form my point of view this seems to be strange
as you told , /_nodes/http, not /_nodes/https is [different](url)
but why if i query _nodes/http it answer me the correct way  and 
_nodes/https will retrun zero record? It seems that trino use the last endpoint 
to create the System.nodes when I'm trying to use the plugin in that way :

**Comment by aalbu** [comment]
So the reason why Trino is not showing any nodes is because Trino is looking for nodes with the generic `data` role  and you have a multi-tier deployment (`data_content` and `data_hot`).

**Comment by aalbu** [comment]
> but why if i query _nodes/http it answer me the correct way and
> _nodes/https will retrun zero record?

ES exposes an endpoint for [node metrics](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html).  It's at `/_nodes/<metric>`.  Trino is requesting the metric `http` - that's just the name of the metric and it is not related to the protocol used to access the endpoint.

**Comment by letmagnau** [comment]
> So the reason why Trino is not showing any nodes is because Trino is looking for nodes with the generic `data` role and you have a multi-tier deployment (`data_content` and `data_hot`). That's a limitation in the connector.

so , I can't use Trino on ElasticCloud? Maybe I can't remove the basic tier of ESCloud , they have data_content and data_hot as mandatory.

Seems to be a  big problem?

**Comment by letmagnau** [comment]
so I can fix here? 
https://github.com/trinodb/trino/blob/master/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java#L387

and trying to pick up  all the nodes containing  data_hot and data_content? 
It's a right assumption?

regards

**Comment by aalbu** [comment]
Yes, feel free to submit a PR - the nice thing is you have an environment where you can validate the fix.  Those features are not available in open source, as far as I know.

**Comment by letmagnau** [comment]
sure!  fix was submitted and waiting to be approved.
To do a best try we needs to have the docker-image of that (253 ??)
How can we have that?

regards

**Comment by aalbu** [comment]
Thanks for submitting the fix.  The easiest way to test may be to run Trino locally, from your IDE (see `README.md` in the project root directory for instructions).  If you want to build a custom Docker image containing your fix, run `core/docker/build-local.sh` (see `README.md` in that directory for additional information).

**Comment by letmagnau** [comment]
any news on our fix? we need to create a docker image in order to test

**Comment by aalbu** [comment]
Ideally, you would create the Docker image for testing from your branch, before this is merged to `master`.  Have you tried?  Also, note that you will need to file a CLA to have the PR merged.

**Comment by letmagnau** [comment]
Hi , we have create our docker image starting from the how to read me (build-local-sh) and we have deployed the patched versione with success!
It fix the problem managing the multilayer structure of the data in ES Cloud
But we want to ask you , we note that the nested filed in ES not are recognized by presto schema? this is usual in presto standard? or not? regards

**Comment by aalbu** [comment]
If you are you asking about `nested` fields, they should be supported (they are mapped just like `object` fields).  Btw, are you on the [Slack channel](https://trino.io/slack.html)?  You can get faster answers there, we have a great community.

**Comment by letmagnau** [comment]
Thanks for reply , can you answer me on issue  #7121 ?

**Comment by dingdayu** [comment]
> Thanks for reply , can you answer me on issue #7121 ?

Hi, I encountered the same problem. I observed that PR #7017  was not incorporated. Please advise how to solve it.

**Comment by aaron-dsouza** [comment]
I am facing this exact same issue. Is the fix incorporated into trino? If so, how do I check if my version of trino has the fix? I am using Starburst version 364-e.3.
Also, it is not clear whether setting up this property is mandatory to solve the issue
elasticsearch.ignore-publish-address=true
