### ISSUE TITLE
Trino does not start up with Rubix configured

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7064]
Problematic commit is 8fa406d4e10dbb70023bff0d8f86db59a0d18422 @sopel39 please fix or revert.

```
2021-02-27T19:19:32.679+0545	ERROR	main	io.trino.server.Server	Unable to create injector, see the following errors:

1) Error injecting constructor, java.util.NoSuchElementException: No value present
  at io.trino.plugin.hive.rubix.RubixModule$RubixStarter.<init>(RubixModule.java:1)
  at io.trino.plugin.hive.rubix.RubixModule.configure(RubixModule.java:51) (via modules: io.airlift.configuration.ConditionalModule -> io.trino.plugin.hive.rubix.RubixModule)
  while locating io.trino.plugin.hive.rubix.RubixModule$RubixStarter

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.util.NoSuchElementException: No value present
  at io.trino.plugin.hive.rubix.RubixModule$RubixStarter.<init>(RubixModule.java:1)
  at io.trino.plugin.hive.rubix.RubixModule.configure(RubixModule.java:51) (via modules: io.airlift.configuration.ConditionalModule -> io.trino.plugin.hive.rubix.RubixModule)
  while locating io.trino.plugin.hive.rubix.RubixModule$RubixStarter

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:188)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:276)
	at io.trino.plugin.hive.InternalHiveConnectorFactory.createConnector(InternalHiveConnectorFactory.java:117)
	at io.trino.plugin.hive.InternalHiveConnectorFactory.createConnector(InternalHiveConnectorFactory.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.trino.plugin.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:63)
	at io.trino.connector.ConnectorManager.createConnector(ConnectorManager.java:359)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:216)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:208)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:194)
	at io.trino.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
	at io.trino.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at io.trino.server.Server.doStart(Server.java:119)
	at io.trino.server.Server.lambda$start$0(Server.java:73)
	at io.trino.$gen.Trino_unknown____20210227_133412_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:73)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at io.trino.plugin.hive.rubix.RubixInitializer.getRubixServerConfiguration(RubixInitializer.java:278)
	at io.trino.plugin.hive.rubix.RubixInitializer.setupRubixMetrics(RubixInitializer.java:270)
	at io.trino.plugin.hive.rubix.RubixInitializer.initializeRubix(RubixInitializer.java:164)
	at io.trino.plugin.hive.rubix.RubixModule$RubixStarter.<init>(RubixModule.java:63)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.google.inject.internal.DefaultConstructionProxyFactory$ReflectiveProxy.newInstance(DefaultConstructionProxyFactory.java:126)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	... 21 more

```

**Comment by findepi** [comment]
> Trino does not start up with Rubix configured

Sounds like something that should be caught by existing tests. 
@sopel39 would that be possible?

**Comment by sopel39** [comment]
tests failed, but I mistaken them for flakyness. my bad

**Comment by findepi** [comment]
> tests failed, but I mistaken them for flakyness. my bad

Huh, happens. That only emphasizes importance of doing away with flakes!

It's good we have a test though.
