### ISSUE TITLE
Non-Transactional to Transactional table.

### ISSUE THREAD

**Issue by rafaelcmonteiro** [trinodb/trino#7083]
Hello,

We were doing some queries via Presto and ran into an issue when trying to do UPDATE and DELETE. At this point we were able to do INSERT and SELECT, but when trying to DELETE a single row we got the log below:

```
    Query 20210226_145742_00128_8m4u3 failed: Deletes must match whole partitions for non-transactional tables.
```

We have searched a solution to this and found out that the issue could be solved changing the transactional option to true, this would enable us to do DELETE and UPDATE. So we tried to create another table but this time setting the transactional option with value true, see the code below:

```sql
CREATE TABLE new_users
WITH (
    format='ORC',
    transactional=true
)
AS select uid,name from old_users
```
Presto/Trino returned the following error:

```
io.trino.spi.TrinoException: The table must be stored using an ACID compliant format (such as ORC): gcp_external12.new_users
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createTable(ThriftHiveMetastore.java:1080)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.createTable(BridgingHiveMetastore.java:204)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.createTable(CachingHiveMetastore.java:508)
	at io.trino.plugin.hive.HiveMetastoreClosure.createTable(HiveMetastoreClosure.java:149)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$CreateTableOperation.run(SemiTransactionalHiveMetastore.java:3050)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeAddTableOperations(SemiTransactionalHiveMetastore.java:1955)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:1387)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1143)
	at io.trino.plugin.hive.HiveMetadata.commit(HiveMetadata.java:2911)
	at io.trino.plugin.hive.HiveConnector.commit(HiveConnector.java:212)
	at io.trino.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:594)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at io.trino.$gen.Trino_352____20210301_125159_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: The table must be stored using an ACID compliant format (such as ORC): gcp_external12.new_users
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:54068)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:54036)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_result.read(ThriftHiveMetastore.java:53962)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_table(ThriftHiveMetastore.java:1531)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_table(ThriftHiveMetastore.java:1518)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.createTable(ThriftHiveMetastoreClient.java:172)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.lambda$createTable$7(FailureAwareThriftMetastoreClient.java:132)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.runWithHandle(FailureAwareThriftMetastoreClient.java:467)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.createTable(FailureAwareThriftMetastoreClient.java:132)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$createTable$51(ThriftHiveMetastore.java:1068)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
	at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createTable(ThriftHiveMetastore.java:1066)
	... 19 more
```

We have tried the same resolution in two different environments, and both of them got the same error.

Environments: 

- Presto/Trino 347
- HMS 3.0.0

and 

- Presto/Trino 352
- HMS 3.1.2

<b>To persist our data we're using bucket GCS(Google Cloud Storage). We want to know if this is a bug or any sort of trino's issue.</b>

Thank you in advance.

**Comment by findepi** [comment]
This should work, unless we have a bug somewhere, or metastore is configured to do something weird (the error is coming from the metastore).

Can you try running `CREATE TABLE` and then `INSERT` separately?

**Comment by rafael31101995** [comment]
Hello, <br>
We did the test that you mentioned but it didn't work.

Test:

```sql
create table trino_test (a int, b int) with (format='ORC', transactional=true);
```
Log:
```
Query 20210303_175933_00473_n7vqz failed: The table must be stored using an ACID compliant format (such as ORC): gcp_external.trino_test
```

When trying to create a new table without configuring the transactional property the code runs without problem but the table is created non-transactional.
```sql
create table trino_test (a int, b int) with (format='ORC');
```

<b>we're using a hive-standalone version.</b>

**Comment by findepi** [comment]
You can enable `DEBUG` logging on `io.trino.plugin.hive.metastore.thrift` to verify parameters being sent to metastore.
I bet ORC is still there, so it's something on your metastore side and may be version-dependent.
I'd typically hook up a debugger into metastore and see what is it doing with this particular request, but hopefully there may be some other, more sane option to find out.

( If you're on GCP, you can perhaps try Starburst managed deployment which has an option to start Hive Metastore as well.
That version/configuration may hopefully work better out of the box.
https://docs.starburst.io/marketplace/index.html )

**Comment by findepi** [comment]
Closing as (hopefully) obsolete.
