### ISSUE TITLE
Flaky testPivotExceedingMaximumArraySize

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#7084]
```
2021-03-01T17:56:16.7715419Z [INFO] 
2021-03-01T17:56:16.7717999Z [INFO] Results:
2021-03-01T17:56:16.7719696Z [INFO] 
2021-03-01T17:56:16.7722411Z [ERROR] Failures: 
2021-03-01T17:56:16.7731943Z [ERROR]   TestDistributedEngineOnlyQueries>AbstractTestEngineOnlyQueries.testPivotExceedingMaximumArraySize:5158 
2021-03-01T17:56:16.7735029Z Expecting:
2021-03-01T17:56:16.7740309Z   <java.lang.RuntimeException: Too many arguments for array constructor>
2021-03-01T17:56:16.7742925Z to be an instance of:
2021-03-01T17:56:16.7745945Z   <io.trino.spi.TrinoException>
2021-03-01T17:56:16.7747729Z but was:
2021-03-01T17:56:16.7753232Z   <"java.lang.RuntimeException: Too many arguments for array constructor
2021-03-01T17:56:16.7759894Z 	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:120)
2021-03-01T17:56:16.7763990Z 	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:491)
2021-03-01T17:56:16.7776429Z 	at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:129)
2021-03-01T17:56:16.7781322Z 	at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:124)
2021-03-01T17:56:16.7788126Z 	at io.trino.tests.AbstractTestEngineOnlyQueries.lambda$testPivotExceedingMaximumArraySize$6(AbstractTestEngineOnlyQueries.java:5157)
2021-03-01T17:56:16.7790417Z 	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
2021-03-01T17:56:16.7795024Z 	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:877)
2021-03-01T17:56:16.7798889Z 	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1306)
2021-03-01T17:56:16.7802512Z 	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1178)
2021-03-01T17:56:16.7808183Z 	at io.trino.tests.AbstractTestEngineOnlyQueries.testPivotExceedingMaximumArraySize(AbstractTestEngineOnlyQueries.java:5157)
2021-03-01T17:56:16.7813269Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-03-01T17:56:16.7817726Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-03-01T17:56:16.7822576Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-03-01T17:56:16.7826265Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-03-01T17:56:16.7830089Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-03-01T17:56:16.7834394Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-03-01T17:56:16.7838402Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-03-01T17:56:16.7842409Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-03-01T17:56:16.7847100Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-03-01T17:56:16.7851703Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-03-01T17:56:16.7856131Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-03-01T17:56:16.7860869Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-03-01T17:56:16.7864390Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-03-01T17:56:16.7868145Z Caused by: io.trino.spi.TrinoException: Too many arguments for array constructor
2021-03-01T17:56:16.7871681Z 	at io.trino.util.Failures.checkCondition(Failures.java:64)
2021-03-01T17:56:16.7876468Z 	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitArrayConstructor(ExpressionInterpreter.java:1211)
2021-03-01T17:56:16.7880952Z 	at io.trino.sql.tree.ArrayConstructor.accept(ArrayConstructor.java:55)
2021-03-01T17:56:16.7884997Z 	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
2021-03-01T17:56:16.7888745Z 	at io.trino.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:294)
2021-03-01T17:56:16.7894045Z 	at io.trino.sql.planner.iterative.rule.SimplifyExpressions.rewrite(SimplifyExpressions.java:54)
2021-03-01T17:56:16.7937752Z 	at io.trino.sql.planner.iterative.rule.SimplifyExpressions.lambda$createRewrite$0(SimplifyExpressions.java:79)
2021-03-01T17:56:16.7940524Z 	at io.trino.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.lambda$apply$0(ExpressionRewriteRuleSet.java:124)
2021-03-01T17:56:16.7942721Z 	at io.trino.sql.planner.plan.Assignments.lambda$rewrite$1(Assignments.java:124)
2021-03-01T17:56:16.7944090Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
2021-03-01T17:56:16.7945693Z 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
2021-03-01T17:56:16.7947148Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2021-03-01T17:56:16.7948809Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-03-01T17:56:16.7950437Z 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
2021-03-01T17:56:16.7951866Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-03-01T17:56:16.7953376Z 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
2021-03-01T17:56:16.7954846Z 	at io.trino.sql.planner.plan.Assignments.rewrite(Assignments.java:125)
2021-03-01T17:56:16.7956981Z 	at io.trino.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.apply(ExpressionRewriteRuleSet.java:124)
2021-03-01T17:56:16.7959924Z 	at io.trino.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.apply(ExpressionRewriteRuleSet.java:105)
2021-03-01T17:56:16.7962463Z 	at io.trino.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:168)
2021-03-01T17:56:16.7964681Z 	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:143)
2021-03-01T17:56:16.7967128Z 	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:108)
2021-03-01T17:56:16.7969590Z 	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
2021-03-01T17:56:16.7971997Z 	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:110)
2021-03-01T17:56:16.7974450Z 	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
2021-03-01T17:56:16.7976872Z 	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:110)
2021-03-01T17:56:16.7979096Z 	at io.trino.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:99)
2021-03-01T17:56:16.7980796Z 	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:209)
2021-03-01T17:56:16.7982084Z 	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:198)
2021-03-01T17:56:16.7983356Z 	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:193)
2021-03-01T17:56:16.7984835Z 	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:450)
2021-03-01T17:56:16.7986486Z 	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:430)
2021-03-01T17:56:16.7988011Z 	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:382)
2021-03-01T17:56:16.7989511Z 	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
2021-03-01T17:56:16.7991155Z 	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
2021-03-01T17:56:16.7992373Z 	at io.trino.$gen.Trino_testversion____20210301_173031_5141.run(Unknown Source)
2021-03-01T17:56:16.7993614Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-03-01T17:56:16.7995299Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
```

**Comment by sopel39** [comment]
cc @wendigo

**Comment by sopel39** [comment]
duplicate of: https://github.com/trinodb/trino/issues/7085
