### ISSUE TITLE
Failure in testPivotExceedingMaximumArraySize

### ISSUE THREAD

**Issue by phd3** [trinodb/trino#7096]
Looks related to #7023. 

```
Error:    TestDistributedEngineOnlyQueries>AbstractTestEngineOnlyQueries.testPivotExceedingMaximumArraySize:5158 
Expecting:
  <java.lang.RuntimeException: Too many arguments for array constructor>
to be an instance of:
  <io.trino.spi.TrinoException>
but was:
  <"java.lang.RuntimeException: Too many arguments for array constructor
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:120)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:491)
	at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:129)
	at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:124)
	at io.trino.tests.AbstractTestEngineOnlyQueries.lambda$testPivotExceedingMaximumArraySize$6(AbstractTestEngineOnlyQueries.java:5157)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:877)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1306)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1178)
	at io.trino.tests.AbstractTestEngineOnlyQueries.testPivotExceedingMaximumArraySize(AbstractTestEngineOnlyQueries.java:5157)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.trino.spi.TrinoException: Too many arguments for array constructor
	at io.trino.util.Failures.checkCondition(Failures.java:64)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitArrayConstructor(ExpressionInterpreter.java:1211)
	at io.trino.sql.tree.ArrayConstructor.accept(ArrayConstructor.java:55)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:294)
	at io.trino.sql.planner.iterative.rule.SimplifyExpressions.rewrite(SimplifyExpressions.java:54)
	at io.trino.sql.planner.iterative.rule.SimplifyExpressions.lambda$createRewrite$0(SimplifyExpressions.java:79)
	at io.trino.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.lambda$apply$0(ExpressionRewriteRuleSet.java:124)
	at io.trino.sql.planner.plan.Assignments.lambda$rewrite$1(Assignments.java:124)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.trino.sql.planner.plan.Assignments.rewrite(Assignments.java:125)
	at io.trino.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.apply(ExpressionRewriteRuleSet.java:124)
	at io.trino.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.apply(ExpressionRewriteRuleSet.java:105)
	at io.trino.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:168)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:143)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:108)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:110)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:110)
	at io.trino.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:99)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:209)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:198)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:193)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:450)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:430)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:382)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20210301_153429_5144.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
">
[INFO] 
Error:  Tests run: 2135, Failures: 1, Errors: 0, Skipped: 1
```

Saw on many PRs. Looks like a minor test issue. @wendigo @findepi

**Comment by sopel39** [comment]
should be fixed by: https://github.com/trinodb/trino/issues/7085

**Comment by wendigo** [comment]
Thank @losipiuk for a quick fix :)
