### ISSUE TITLE
ES catalog : is possible that presto can manage field array only for instance of Map type???

### ISSUE THREAD

**Issue by letmagnau** [trinodb/trino#7121]
i read here 

 ```java
public void decode(SearchHit hit, Supplier<Object> getter, BlockBuilder output)
    {
        Object data = getter.get();

        if (data == null) {
            output.appendNull();
        }
        else if (data instanceof Map) {
            BlockBuilder row = output.beginBlockEntry();
            for (int i = 0; i < decoders.size(); i++) {
                String field = fieldNames.get(i);
                decoders.get(i).decode(hit, () -> getField((Map<String, Object>) data, field), row);
            }
            output.closeEntry();
        }
        else {
            throw new TrinoException(TYPE_MISMATCH, format("Expected object for field '%s' of type ROW: %s [%s]", path, data, data.getClass().getSimpleName()));
        }
    }

```

it means that if I have a ES index with a field as List , it can't manage it?? 

Of course ES admit filed as array as [1,2,,3 ] or  [aaa,bbb,ccc] but that was managed as ROW on ROW Decoder but that are not Map...
Am I wrong?

**Comment by letmagnau** [comment]
?? any news??

**Comment by PChou** [comment]
@letmagnau Map handles as RowType, while Array handles as ArrayType, please go to `ElasticsearchMetadata#toTrinoType` to see the type mapping

**Comment by bitsondatadev** [comment]
Could you be a little more concise on the instance variable you use in the example?

`"aaa","bbb"."ccc"`

is this an array?

`["aaa","bbb","ccc"]`

1. And could you also provide a more concrete example for me to use when recreating your bug?
2. Can you share the elasticsearch mapping and an example document that causes an exception?
3. Can you show us the stacktrace you get?

This will help us actually understand the issue you're having better. I think I vaguely understand the issue you have but I'd like to be sure. I'll also post this on the issue.

**Comment by letmagnau** [comment]
sure,

obviously is an array yes, but it cuold be of all of type available.
Example is:

we would use presto to have an initial query engine able to read heterogeneous type of storing, one of this is an existing ES CLOUD instance that have data ingested form another system.
In that instance , data was stored as ARRAY using the availability of ES to do this 
**Arrays
In Elasticsearch, arrays do not require a dedicated field data type. Any field can contain zero or more values by default, however, all values in the array must be of the same field type**

in practice they store an index that have some fields  like 
```
 "autori": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
```
this is a tipycal output of "_mapping" endpoint of ES
so the field _meta was not set and as that issue seems to put in evidence trino needs to have starting from the ES ingest
https://github.com/trinodb/trino/issues/7012

when I configure the trino connector to elastic , and try to read some "table"
it give me the error: 

```
Caused by: java.sql.SQLException: Query failed (#20210310_161602_00018_q5drz): Expected a string or numeric value for field 'autori' of type VARCHAR: [] [ArrayList]
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1912)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:218)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:178)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at io.trino.jdbc.TrinoResultSet$AsyncIterator.lambda$new$0(TrinoResultSet.java:124)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.trino.spi.TrinoException: Expected a string or numeric value for field 'autori' of type VARCHAR: [] [ArrayList]
	at io.trino.plugin.elasticsearch.decoders.VarcharDecoder.decode(VarcharDecoder.java:49)
	at io.trino.plugin.elasticsearch.ScanQueryPageSource.getNextPage(ScanQueryPageSource.java:189)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:301)
	at io.trino.operator.Driver.processInternal(Driver.java:387)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_352_131_gab136fe_dirty____20210310_160100_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```



from this our analysis about the needs to have a way  to undestand that that filed is and Array of any type
and try to active the code of managing array without have the _meta data, injecting inside the correct Decoder for the value inside,

    if (type instanceof ArrayType) {
            Type elementType = ((ArrayType) type).getElementType();

            return new ArrayDecoder(path, createDecoder(path, elementType));

I hope that I'm almost clear now, so I don't If I'm saying the truth but if yes , we think that is a problem that much impact 
our use of trino

**Comment by bitsondatadev** [comment]
Hi @letmagnau,

Okay so this is the key statement right here.

> field _meta was not set and as that issue seems to put in evidence trino needs to have starting from the ES ingest

Trino uses a SQL standard to represent and model the data. It has to treat column fields using the same type and we use the _mapping to determine those types. Since there is [no real concept of arrays in Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html) I added a way for Trino to indicate that specific columns are going to be treated as arrays by sticking an equivalent object in the [_meta field](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-meta-field.html) (see #2441).

This issue going on in #7012 is based on how we're not handling scalar values inserted into elasticsearch when the field is marked as an array in the _meta field and @martint just added a fix for that.

In short you'll need to add a structure in your _meta field. Something equivalent to the following if the autori field is at the root of your document:

`curl --request PUT \
    --url localhost:9200/doc/_mapping \
    --header 'content-type: application/json' \
    --data '
{
    "_meta": {
        "presto":{
            "autori":{
                "isArray":true
            },
        }
    }
}'`

or something like this if it's nested in an object field or something.

`curl --request PUT \
    --url localhost:9200/doc/_mapping \
    --header 'content-type: application/json' \
    --data '
{
    "_meta": {
        "presto":{
            "object_field":{
                "autori":{
                    "isArray":true
                }
            },
        }
    }
}'`

Please see [the docs on array types](https://trino.io/docs/current/connector/elasticsearch.html#array-types) for more info and let me know if this works. If it does we can close this out.

**Comment by letmagnau** [comment]
It's seems to be a too  strong limitation
If I'n not the manger of the data in Elastic , I will not see nothing in presto
am I wrong ??

**Comment by bitsondatadev** [comment]
If you consider ANSI SQL to have too strong of a limitations then yes, it is a strong limitation. SQL requires you to know the type upfront. Elasticsearch is a little more liberal on how it models types just due to how the underlying Lucene models document data (everything is a list of values in an inverted array). Mapping one to the other is never straightforward.

Coordinating schemas across teams is a problem that Trino doesn't solve. It's comes back to a data cataloging problem where you would need to coordinate with the team that manages that data to understand how they intend to store that data. There's no silver bullet there.
 
We have an open ticket creating a procedure (See #2508) that will sample some of the documents to try and infer which fields are arrays and which ones are scalar but unless you sample every single last document in the elasticsearch index, you may have some fields that are pushed as a scalar value while others are arrays and you happen to only get the scalar ones. 

Further, even if you scan all the documents, someone can push a new document that now has an array where previously there were only scalar values. So this problem isn't really up to Trino to solve, it's a consequence of how data is modeled between two systems and will then require coordination between teams if your Elasticsearch team is not the same team as your Trino managers.

Does that make sense?

**Comment by letmagnau** [comment]
we will try with the workaround with data ingested by ourself , but the main feature of read the data not managed by us I think will wait...

thanks

**Comment by bitsondatadev** [comment]
Okay! I wish I had a better answer for you that solved these issues but they are inherently difficult issues to solve and fall out of the purview of Trino our main goal is to adhere to ANSI SQL. Do you mind if I close this ticket then?

You can feel free to open a new one and let me know if #2508 would help you all in your situation. I can try to push to implement this if it helps.
