### ISSUE TITLE
TestOAuth2WebUiAuthenticationFilter.setup is flaky

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#7148]
```
021-03-03T19:51:16.0690425Z Unable to create injector, see the following errors:
2021-03-03T19:51:16.0690893Z 
2021-03-03T19:51:16.0695891Z 1) Error in custom provider, java.lang.NullPointerException
2021-03-03T19:51:16.0710245Z   at io.airlift.discovery.client.DiscoveryBinder.bindServiceAnnouncement(DiscoveryBinder.java:79) (via modules: io.trino.server.ServerMainModule -> io.trino.server.CoordinatorModule)
2021-03-03T19:51:16.0719185Z   while locating io.airlift.discovery.client.ServiceAnnouncement annotated with @com.google.inject.internal.Element(setName=,uniqueId=1870, type=MULTIBINDER, keyType=)
2021-03-03T19:51:16.0723513Z   while locating java.util.Set<io.airlift.discovery.client.ServiceAnnouncement>
2021-03-03T19:51:16.0729486Z     for the 2nd parameter of io.airlift.discovery.client.Announcer.<init>(Announcer.java:68)
2021-03-03T19:51:16.0737655Z   at io.airlift.discovery.client.testing.TestingDiscoveryModule.configure(TestingDiscoveryModule.java:49)
2021-03-03T19:51:16.0739954Z   while locating io.airlift.discovery.client.Announcer
2021-03-03T19:51:16.0752822Z     for the 2nd parameter of io.airlift.discovery.client.testing.TestingDiscoveryModule.createMergingServiceSelectorFactory(TestingDiscoveryModule.java:69)
2021-03-03T19:51:16.0760715Z   at io.airlift.discovery.client.testing.TestingDiscoveryModule.createMergingServiceSelectorFactory(TestingDiscoveryModule.java:69)
2021-03-03T19:51:16.0764574Z   while locating io.airlift.discovery.client.MergingServiceSelectorFactory
2021-03-03T19:51:16.0772135Z   at io.airlift.discovery.client.testing.TestingDiscoveryModule.configure(TestingDiscoveryModule.java:55)
2021-03-03T19:51:16.0775631Z   while locating io.airlift.discovery.client.ServiceSelectorFactory
2021-03-03T19:51:16.0785857Z     for the 1st parameter of io.airlift.discovery.client.ServiceSelectorProvider.setServiceSelectorFactory(ServiceSelectorProvider.java:50)
2021-03-03T19:51:16.0788811Z   at io.trino.server.ServerMainModule.setup(ServerMainModule.java:232)
2021-03-03T19:51:16.0792826Z Caused by: java.lang.NullPointerException
2021-03-03T19:51:16.0799113Z 	at io.airlift.discovery.client.DiscoveryBinder$HttpAnnouncementProvider.get(DiscoveryBinder.java:128)
2021-03-03T19:51:16.0805716Z 	at io.airlift.discovery.client.DiscoveryBinder$HttpAnnouncementProvider.get(DiscoveryBinder.java:108)
2021-03-03T19:51:16.0812674Z 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
2021-03-03T19:51:16.0821851Z 	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:57)
2021-03-03T19:51:16.0825264Z 	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:66)
2021-03-03T19:51:16.0832364Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
2021-03-03T19:51:16.0837399Z 	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
2021-03-03T19:51:16.0846880Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
2021-03-03T19:51:16.0854943Z 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2021-03-03T19:51:16.0861923Z 	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
2021-03-03T19:51:16.0871499Z 	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
2021-03-03T19:51:16.0878621Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
2021-03-03T19:51:16.0882264Z 	at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:198)
2021-03-03T19:51:16.0886928Z 	at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:151)
2021-03-03T19:51:16.0938576Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory$1.call(InternalProviderInstanceBindingImpl.java:120)
2021-03-03T19:51:16.0942063Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
2021-03-03T19:51:16.0944593Z 	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
2021-03-03T19:51:16.0947395Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
2021-03-03T19:51:16.0950831Z 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2021-03-03T19:51:16.0954386Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:115)
2021-03-03T19:51:16.0957522Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
2021-03-03T19:51:16.0960204Z 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
2021-03-03T19:51:16.0962780Z 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
2021-03-03T19:51:16.0965142Z 	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
2021-03-03T19:51:16.0967274Z 	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
2021-03-03T19:51:16.0969868Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
2021-03-03T19:51:16.0972399Z 	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
2021-03-03T19:51:16.0974933Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
2021-03-03T19:51:16.0978462Z 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2021-03-03T19:51:16.0981456Z 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
2021-03-03T19:51:16.0983831Z 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
2021-03-03T19:51:16.0986679Z 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2021-03-03T19:51:16.0989186Z 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
2021-03-03T19:51:16.0991687Z 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
2021-03-03T19:51:16.0994735Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
2021-03-03T19:51:16.0997400Z 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
2021-03-03T19:51:16.0999844Z 	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
2021-03-03T19:51:16.1002886Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
2021-03-03T19:51:16.1006695Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.access$300(InternalProviderInstanceBindingImpl.java:139)
2021-03-03T19:51:16.1010382Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory$1.call(InternalProviderInstanceBindingImpl.java:169)
2021-03-03T19:51:16.1013827Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
2021-03-03T19:51:16.1045032Z 	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
2021-03-03T19:51:16.1047610Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
2021-03-03T19:51:16.1050957Z 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2021-03-03T19:51:16.1054561Z 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:164)
2021-03-03T19:51:16.1058656Z 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2021-03-03T19:51:16.1061165Z 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
2021-03-03T19:51:16.1063700Z 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
2021-03-03T19:51:16.1066287Z 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
2021-03-03T19:51:16.1068886Z 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2021-03-03T19:51:16.1071430Z 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
2021-03-03T19:51:16.1073941Z 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
2021-03-03T19:51:16.1077011Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
2021-03-03T19:51:16.1079697Z 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
2021-03-03T19:51:16.1082208Z 	at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:82)
2021-03-03T19:51:16.1084806Z 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:147)
2021-03-03T19:51:16.1087609Z 	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
2021-03-03T19:51:16.1089950Z 	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:245)
2021-03-03T19:51:16.1091741Z 	at com.google.inject.internal.Initializer.injectAll(Initializer.java:140)
2021-03-03T19:51:16.1094338Z 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:178)
2021-03-03T19:51:16.1097415Z 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
2021-03-03T19:51:16.1099389Z 	at com.google.inject.Guice.createInjector(Guice.java:87)
2021-03-03T19:51:16.1100764Z 	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:276)
2021-03-03T19:51:16.1102450Z 	at io.trino.server.testing.TestingTrinoServer.<init>(TestingTrinoServer.java:271)
2021-03-03T19:51:16.1104301Z 	at io.trino.server.testing.TestingTrinoServer$Builder.build(TestingTrinoServer.java:641)
2021-03-03T19:51:16.1107355Z 	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.setup(TestOAuth2WebUiAuthenticationFilter.java:153)
2021-03-03T19:51:16.1110505Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-03-03T19:51:16.1112856Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-03-03T19:51:16.1115608Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-03-03T19:51:16.1117632Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-03-03T19:51:16.1119484Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-03-03T19:51:16.1121820Z 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
2021-03-03T19:51:16.1123697Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
2021-03-03T19:51:16.1125450Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
2021-03-03T19:51:16.1127702Z 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
2021-03-03T19:51:16.1129996Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
2021-03-03T19:51:16.1131787Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-03-03T19:51:16.1133871Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-03-03T19:51:16.1135181Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-03-03T19:51:16.1216441Z 
2021-03-03T19:51:16.1217329Z 2) Error injecting constructor, java.io.UncheckedIOException: Failed to bind to localhost/127.0.0.1:46629
2021-03-03T19:51:16.1218754Z   at io.airlift.http.server.HttpServerInfo.<init>(HttpServerInfo.java:48)
2021-03-03T19:51:16.1221066Z   at io.airlift.http.server.testing.TestingHttpServerModule.configure(TestingHttpServerModule.java:65)
2021-03-03T19:51:16.1223214Z   while locating io.airlift.http.server.HttpServerInfo
2021-03-03T19:51:16.1225641Z     for the 1st parameter of io.airlift.http.server.LocalAnnouncementHttpServerInfo.<init>(LocalAnnouncementHttpServerInfo.java:31)
2021-03-03T19:51:16.1228002Z   while locating io.airlift.http.server.LocalAnnouncementHttpServerInfo
2021-03-03T19:51:16.1229841Z   while locating io.airlift.discovery.client.AnnouncementHttpServerInfo
2021-03-03T19:51:16.1232629Z     for the 1st parameter of io.airlift.discovery.client.DiscoveryBinder$HttpAnnouncementProvider.setAnnouncementHttpServerInfo(DiscoveryBinder.java:122)
2021-03-03T19:51:16.1237413Z   at io.airlift.discovery.client.DiscoveryBinder.bindServiceAnnouncement(DiscoveryBinder.java:79) (via modules: io.trino.server.ServerMainModule -> io.trino.server.CoordinatorModule)
2021-03-03T19:51:16.1240189Z Caused by: java.io.UncheckedIOException: Failed to bind to localhost/127.0.0.1:46629
2021-03-03T19:51:16.1241797Z 	at io.airlift.http.server.HttpServerInfo.createChannel(HttpServerInfo.java:164)
2021-03-03T19:51:16.1339838Z 	at io.airlift.http.server.HttpServerInfo.<init>(HttpServerInfo.java:61)
2021-03-03T19:51:16.1341480Z 	at io.airlift.http.server.HttpServerInfo$$FastClassByGuice$$bd4c327f.newInstance(<generated>)
2021-03-03T19:51:16.1344092Z 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
2021-03-03T19:51:16.1347052Z 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
2021-03-03T19:51:16.1349441Z 	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
2021-03-03T19:51:16.1351572Z 	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
2021-03-03T19:51:16.1354175Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
2021-03-03T19:51:16.1356709Z 	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
2021-03-03T19:51:16.1359255Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
2021-03-03T19:51:16.1362613Z 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2021-03-03T19:51:16.1365651Z 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
2021-03-03T19:51:16.1367991Z 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
2021-03-03T19:51:16.1370835Z 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2021-03-03T19:51:16.1373337Z 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
2021-03-03T19:51:16.1375968Z 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
2021-03-03T19:51:16.1378987Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
2021-03-03T19:51:16.1381669Z 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
2021-03-03T19:51:16.1384233Z 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
2021-03-03T19:51:16.1386610Z 	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
2021-03-03T19:51:16.1388755Z 	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
2021-03-03T19:51:16.1391337Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
2021-03-03T19:51:16.1394207Z 	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
2021-03-03T19:51:16.1396748Z 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
2021-03-03T19:51:16.1400177Z 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2021-03-03T19:51:16.1403262Z 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
2021-03-03T19:51:16.1405639Z 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
2021-03-03T19:51:16.1407574Z 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
2021-03-03T19:51:16.1409739Z 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
2021-03-03T19:51:16.1412371Z 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
2021-03-03T19:51:16.1415053Z 	at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:82)
2021-03-03T19:51:16.1448314Z 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:147)
2021-03-03T19:51:16.1450921Z 	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
2021-03-03T19:51:16.1453356Z 	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:245)
2021-03-03T19:51:16.1455036Z 	at com.google.inject.internal.Initializer.injectAll(Initializer.java:140)
2021-03-03T19:51:16.1457506Z 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:178)
2021-03-03T19:51:16.1460294Z 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
2021-03-03T19:51:16.1462084Z 	at com.google.inject.Guice.createInjector(Guice.java:87)
2021-03-03T19:51:16.1463565Z 	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:276)
2021-03-03T19:51:16.1465215Z 	at io.trino.server.testing.TestingTrinoServer.<init>(TestingTrinoServer.java:271)
2021-03-03T19:51:16.1467077Z 	at io.trino.server.testing.TestingTrinoServer$Builder.build(TestingTrinoServer.java:641)
2021-03-03T19:51:16.1470118Z 	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.setup(TestOAuth2WebUiAuthenticationFilter.java:153)
2021-03-03T19:51:16.1473204Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-03-03T19:51:16.1475582Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-03-03T19:51:16.1478318Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-03-03T19:51:16.1480348Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-03-03T19:51:16.1482190Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-03-03T19:51:16.1484483Z 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
2021-03-03T19:51:16.1486352Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
2021-03-03T19:51:16.1488091Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
2021-03-03T19:51:16.1490335Z 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
2021-03-03T19:51:16.1492559Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
2021-03-03T19:51:16.1494457Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-03-03T19:51:16.1496540Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-03-03T19:51:16.1497832Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-03-03T19:51:16.1498671Z Caused by: java.net.BindException: Address already in use
2021-03-03T19:51:16.1499505Z 	at java.base/sun.nio.ch.Net.bind0(Native Method)
2021-03-03T19:51:16.1500415Z 	at java.base/sun.nio.ch.Net.bind(Net.java:455)
2021-03-03T19:51:16.1501123Z 	at java.base/sun.nio.ch.Net.bind(Net.java:447)
2021-03-03T19:51:16.1502407Z 	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
2021-03-03T19:51:16.1504147Z 	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
2021-03-03T19:51:16.1505987Z 	at io.airlift.http.server.HttpServerInfo.createChannel(HttpServerInfo.java:160)
2021-03-03T19:51:16.1507199Z 	... 54 more
2021-03-03T19:51:16.1507503Z 
2021-03-03T19:51:16.1508322Z 3) Error injecting constructor, java.io.UncheckedIOException: Failed to bind to localhost/127.0.0.1:46629
2021-03-03T19:51:16.1509719Z   at io.airlift.http.server.HttpServerInfo.<init>(HttpServerInfo.java:48)
2021-03-03T19:51:16.1512018Z   at io.airlift.http.server.testing.TestingHttpServerModule.configure(TestingHttpServerModule.java:65)
2021-03-03T19:51:16.1514170Z   while locating io.airlift.http.server.HttpServerInfo
2021-03-03T19:51:16.1516333Z     for the 1st parameter of io.airlift.http.server.LocalAnnouncementHttpServerInfo.<init>(LocalAnnouncementHttpServerInfo.java:31)
2021-03-03T19:51:16.1518865Z   while locating io.airlift.http.server.LocalAnnouncementHttpServerInfo
2021-03-03T19:51:16.1520849Z   while locating io.airlift.discovery.client.AnnouncementHttpServerInfo
2021-03-03T19:51:16.1656366Z     for the 1st parameter of io.airlift.discovery.client.DiscoveryBinder$HttpAnnouncementProvider.setAnnouncementHttpServerInfo(DiscoveryBinder.java:122)
2021-03-03T19:51:16.1659822Z   at io.airlift.discovery.client.DiscoveryBinder.bindServiceAnnouncement(DiscoveryBinder.java:79)
2021-03-03T19:51:16.1661869Z Caused by: java.io.UncheckedIOException (same stack trace as error #2)
2021-03-03T19:51:16.1662583Z 3 errors
2021-03-03T19:51:16.1664266Z 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
2021-03-03T19:51:16.1667451Z 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
2021-03-03T19:51:16.1670441Z 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
2021-03-03T19:51:16.1672392Z 	at com.google.inject.Guice.createInjector(Guice.java:87)
2021-03-03T19:51:16.1673771Z 	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:276)
2021-03-03T19:51:16.1675406Z 	at io.trino.server.testing.TestingTrinoServer.<init>(TestingTrinoServer.java:271)
2021-03-03T19:51:16.1677270Z 	at io.trino.server.testing.TestingTrinoServer$Builder.build(TestingTrinoServer.java:641)
2021-03-03T19:51:16.1680374Z 	at io.trino.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.setup(TestOAuth2WebUiAuthenticationFilter.java:153)
2021-03-03T19:51:16.1683790Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-03-03T19:51:16.1686122Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-03-03T19:51:16.1688869Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-03-03T19:51:16.1690880Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-03-03T19:51:16.1692763Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-03-03T19:51:16.1695046Z 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
2021-03-03T19:51:16.1697123Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
2021-03-03T19:51:16.1698863Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
2021-03-03T19:51:16.1701123Z 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
2021-03-03T19:51:16.1703302Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
2021-03-03T19:51:16.1705188Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-03-03T19:51:16.1707189Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-03-03T19:51:16.1708779Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-03-03T19:51:16.1709253Z 
2021-03-03T19:51:16.5994681Z [INFO] 
2021-03-03T19:51:16.5997484Z [INFO] Results:
2021-03-03T19:51:16.5999356Z [INFO] 
2021-03-03T19:51:16.6002425Z [ERROR] Failures: 
2021-03-03T19:51:16.6038605Z [ERROR]   TestOAuth2WebUiAuthenticationFilter.setup:153 » Creation Unable to create inje...
2021-03-03T19:51:16.6041644Z [INFO] 
```

**Comment by kokosing** [comment]
https://github.com/trinodb/trino/pull/7089#issuecomment-790064425

**Comment by lukasz-walkiewicz** [comment]
It shouldn't be a problem anymore as after: https://github.com/trinodb/trino/pull/7951 the port for Trino server is generated as everywhere else.
