### ISSUE TITLE
TestRemarksReportingOraclePoolConnectorTest.testInsert test flaky with ORA-00054

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7183]
```
Errror:  Tests run: 415, Failures: 1, Errors: 0, Skipped: 27, Time elapsed: 1,271.032 s <<< FAILURE! - in TestSuite
Error:  testInsert(io.trino.plugin.oracle.TestRemarksReportingOraclePoolConnectorTest)  Time elapsed: 6.191 s  <<< FAILURE!
java.lang.RuntimeException: 
ORA-00054: resource busy and acquire with NOWAIT specified or timeout expired

	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:120)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:491)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:215)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:210)
	at io.trino.testing.AbstractTestDistributedQueries.testInsert(AbstractTestDistributedQueries.java:586)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.trino.spi.TrinoException: ORA-00054: resource busy and acquire with NOWAIT specified or timeout expired

	at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:976)
	at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:962)
	at io.trino.plugin.jdbc.BaseJdbcClient.dropTable(BaseJdbcClient.java:776)
	at io.trino.plugin.jdbc.ForwardingJdbcClient.dropTable(ForwardingJdbcClient.java:200)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$dropTable$25(StatisticsAwareJdbcClient.java:254)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:47)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.dropTable(StatisticsAwareJdbcClient.java:254)
	at io.trino.plugin.jdbc.CachingJdbcClient.dropTable(CachingJdbcClient.java:287)
	at io.trino.plugin.jdbc.CachingJdbcClient.dropTable(CachingJdbcClient.java:287)
	at io.trino.plugin.jdbc.JdbcMetadata.dropTable(JdbcMetadata.java:566)
	at io.trino.metadata.MetadataManager.dropTable(MetadataManager.java:746)
	at io.trino.execution.DropTableTask.execute(DropTableTask.java:67)
	at io.trino.execution.DropTableTask.execute(DropTableTask.java:35)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:170)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20210305_191602_45.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.RuntimeException: Query: DROP TABLE "TRINO_TEST"."TEST_INSERT_B93KE"
		at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:977)
		... 19 more
Caused by: java.sql.SQLException: ORA-00054: resource busy and acquire with NOWAIT specified or timeout expired

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:928)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1823)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1778)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:303)
	at oracle.ucp.jdbc.proxy.oracle$1ucp$1jdbc$1proxy$1oracle$1StatementProxy$2oracle$1jdbc$1internal$1OracleStatement$$$Proxy.execute(Unknown Source)
	at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:973)
	... 19 more
Caused by: oracle.jdbc.OracleDatabaseException: ORA-00054: resource busy and acquire with NOWAIT specified or timeout expired

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
	... 33 more


Error:    TestRemarksReportingOraclePoolConnectorTest>AbstractTestDistributedQueries.testInsert:586->AbstractTestQueryFramework.assertUpdate:210->AbstractTestQueryFramework.assertUpdate:215 » Runtime
```

**Comment by findepi** [comment]
This class no longer exists.

**Comment by losipiuk** [comment]
True :) Still I think the issue existsts. Just for the BaseConnectorTest.<something>

**Comment by findepi** [comment]
Likely, but note that the "pooling + remarks" is now a connector _smoke_ test (`TestOraclePoolRemarksReportingConnectorSmokeTest`), so the `testInsert` is a new test.

**Comment by ebyhr** [comment]
I don't see this failure for a while. Let me close. I will reopen if needed.
