### ISSUE TITLE
Query cancellation can sometimes fail

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#7191]
Apparently invoking query cancellation can fail with "Unknown transaction ID: 8423de1d-af0b-4bc0-8131-a89bedb6e613. Possibly expired? Commands ignored until end of transaction block"

```
io.trino.NotInTransactionException: Unknown transaction ID: 8423de1d-af0b-4bc0-8131-a89bedb6e613. Possibly expired? Commands ignored until end of transaction block
	at io.trino.transaction.InMemoryTransactionManager.getTransactionMetadata(InMemoryTransactionManager.java:257)
	at io.trino.transaction.InMemoryTransactionManager.getTransactionInfo(InMemoryTransactionManager.java:155)
	at io.trino.transaction.TransactionManager.isAutoCommit(TransactionManager.java:37)
	at io.trino.execution.QueryStateMachine.lambda$transitionToCanceled$15(QueryStateMachine.java:925)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.trino.execution.QueryStateMachine.transitionToCanceled(QueryStateMachine.java:924)
	at io.trino.execution.SqlQueryExecution.cancelQuery(SqlQueryExecution.java:540)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.trino.execution.SqlQueryManager.cancelQuery(SqlQueryManager.java:255)
	at io.trino.testing.DistributedQueryRunner.cancelAllQueries(DistributedQueryRunner.java:553)
	at io.trino.testing.DistributedQueryRunner.close(DistributedQueryRunner.java:539)
	at io.trino.util.AutoCloseableCloser.close(AutoCloseableCloser.java:52)
	at io.trino.testing.AbstractTestQueryFramework.close(AbstractTestQueryFramework.java:105)
	at jdk.internal.reflect.GeneratedMethodAccessor1339.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Observed in tests (https://github.com/trinodb/trino/issues/6723), but looking at the code the problem seems general.

**Comment by findepi** [comment]
I will retrofit https://github.com/trinodb/trino/issues/6723 instead.
