### ISSUE TITLE
Support Hive VIEW with UNION (DISTINCT)

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#7295]
Hive view with `UNION ALL` works, but `UNION` does not 

```
io.prestosql.spi.PrestoException: Failed to translate Hive view 'default.union_view_from_hive': com.linkedin.coral.hive.hive2rel.parsetree.parser.ParseException: line 1:43 missing ALL at 'select' near '<EOF>'
	at io.prestosql.plugin.hive.ViewReaderUtil$HiveViewReader.decodeViewData(ViewReaderUtil.java:157)
	at io.prestosql.plugin.hive.HiveMetadata.lambda$getView$60(HiveMetadata.java:1927)
...
Caused by: java.lang.RuntimeException: com.linkedin.coral.hive.hive2rel.parsetree.parser.ParseException: line 1:43 missing ALL at 'select' near '<EOF>'
	at com.linkedin.coral.hive.hive2rel.parsetree.ParseTreeBuilder.process(ParseTreeBuilder.java:161)
	at com.linkedin.coral.hive.hive2rel.parsetree.ParseTreeBuilder.processViewOrTable(ParseTreeBuilder.java:127)
	at com.linkedin.coral.hive.hive2rel.parsetree.ParseTreeBuilder.processView(ParseTreeBuilder.java:142)
	at com.linkedin.coral.hive.hive2rel.HiveToRelConverter.convertView(HiveToRelConverter.java:103)
	at io.prestosql.plugin.hive.ViewReaderUtil$HiveViewReader.decodeViewData(ViewReaderUtil.java:138)
	... 36 more
Caused by: com.linkedin.coral.hive.hive2rel.parsetree.parser.ParseException: line 1:43 missing ALL at 'select' near '<EOF>'
	at com.linkedin.coral.hive.hive2rel.parsetree.parser.ParseDriver.parse(ParseDriver.java:189)
	at com.linkedin.coral.hive.hive2rel.parsetree.ParseTreeBuilder.process(ParseTreeBuilder.java:158)
	... 40 more
```

**Comment by findepi** [comment]
Since it worked in Presto 344, i am marking this as a bug.
