### ISSUE TITLE
Handle fields that are not able to be inferred by returning the raw json

### ISSUE THREAD

**Issue by bitsondatadev** [trinodb/trino#7308]
Currently if you write an array of arrays to elasticsearch, it will internally flatten that list, and store only the type of that field in the mapping for indexing. Elasticsearch, will also store the original document that was submitted as text, which effectively preserves the array of arrays. When querying for the field, it returns this field. Unfortunately, Trino has no way to infer when elasticsearch is storing an array of arrays or just a single array. We currently only have the isArray to distinguish between fields that are expected to have list values, or fields that are expected to be scalar.

Here is an example of one such issue:
```
# create a test index "test3" on a local ES container
~ % curl -X PUT localhost:9200/test3/
>>> {"acknowledged":true,"shards_acknowledged":true,"index":"test3"}%
# push a document in with a single field "arr_of_arrays" which is an array of arrays
~ % curl -X PUT localhost:9200/test3/_doc/1 -H "Content-Type: application/json" -d '{"arr_of_arrays": [["abc", "def"]]}'
>>> {"_index":"test3","_type":"_doc","_id":"1","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":0,"_primary_term":1}%
# ES recognizes "arr_of_arrays" as a text fields since it doesn't care about arrays
~ % curl localhost:9200/test3/_mapping
>>> {"test3":{"mappings":{"properties":{"arr_of_arrays":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}}}%
# Trino also follows ES, classifies "arr_of_arrays" as a varchar column
~ % tcli --execute 'show columns from elasticsearch_local.indices.test3'
>>> "arr_of_arrays","varchar","",""
# insert the _meta field to denote that "arr_of_arrays" is an Array type
~ % curl -X PUT localhost:9200/test3/_mapping -H "Content-Type: application/json" -d '{"_meta": {"presto": {"arr_of_arrays": {"isArray": true}}}}'
>>> {"acknowledged":true}%
# now Trino classifies "arr_of_arrays" as an Array type
~ % tcli --execute 'show columns from elasticsearch_local.indices.test3'
>>> "arr_of_arrays","array(varchar)","",""
# however we still cannot retrieve data because Trino thinks that it is an array of varchar's. However it is an array of arrays.
# And there is no way to fix this column type on Trino's end and retrieve data from it.
~ % tcli --execute 'select * from elasticsearch_local.indices.test3'
>>> Query 20210316_203012_00071_3vy2g failed: Expected a string or numeric value for field 'arr_of_arrays' of type VARCHAR: [abc, def] [ArrayList]
io.trino.spi.TrinoException: Expected a string or numeric value for field 'arr_of_arrays' of type VARCHAR: [abc, def] [ArrayList]
	at io.trino.plugin.elasticsearch.decoders.VarcharDecoder.decode(VarcharDecoder.java:49)
	at io.trino.plugin.elasticsearch.decoders.ArrayDecoder.lambda$decode$1(ArrayDecoder.java:49)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at io.trino.plugin.elasticsearch.decoders.ArrayDecoder.decode(ArrayDecoder.java:49)
	at io.trino.plugin.elasticsearch.ScanQueryPageSource.getNextPage(ScanQueryPageSource.java:189)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:301)
	at io.trino.operator.Driver.processInternal(Driver.java:387)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_352____20210316_183929_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

To handle this, @martint and I have proposed adding another field identifier called `isRawJson` that would be placed in the same `_meta.presto` (soon to be renamed `_meta.trino`) properties in the `_meta` fields of the elasticsearch mapping.

 This will indicate to Trino, to return the raw json. In our example above, `arr_of_arrays` will be returned as a VARCHAR that contains the raw json. 

 ```
 ~ % curl -X PUT localhost:9200/test3/_mapping -H "Content-Type: application/json" -d '{"_meta": {"presto": {"arr_of_arrays": {"isRawJson": true}}}}'
>>> {"acknowledged":true}%

~ % tcli --execute 'show columns from elasticsearch_local.indices.test3'
>>> "arr_of_arrays","varchar","",""

~ % tcli --execute 'select * from elasticsearch_local.indices.test3'
"arr_of_arrays"|
---------------+
"[abc, def]"    |
 ```
 
 This now returns raw json that can be [parsed and use all the json functions we have](https://trino.io/docs/current/functions/json.html) or simply get the query returning correctly.

**Comment by MusKaya** [comment]
thanks @bitsondatadev 

after the `"isRawJson": true` mapping is set, why do you prefer classifying the column as `varchar` instead of `json`?

**Comment by bitsondatadev** [comment]
Good question @MusKaya. There's a performance hit by having to parse json (and it's not small, especially if there are a large number of rows). Let's just say you want the query to return and you actually don't care about that field (you do a SELECT *) then we pay a penalty of parsing that json for nothing. We can defer that to the user to do in the SELECT statement if they actually care about that field.

```
SELECT json_parse(arr_of_arrays) from elasticsearch_local.indices.test3;
```

This will have the same effect if we returned the field as JSON but only happens if the user cares to do it and ultimately will run faster if they don't care about parsing the field.

**Comment by MusKaya** [comment]
makes sense @bitsondatadev, thanks!

**Comment by martint** [comment]
Additionally, using VARCHAR will play better with the SQL 2016 JSON features once we implement them, which operate on binary or varchar fields (there's no JSON type in the SQL spec)
