### ISSUE TITLE
Elasticsearch connector: Handle coerced long values

### ISSUE THREAD

**Issue by MusKaya** [trinodb/trino#7340]
**Background**
Elasticsearch has a by default on "coercion" feature such that it coerces an input value to match the field mapping.

For instance if we have a field called `long_field`, and if we want to insert 1.5, it stores the value 1.5 in the `_source`, however it indexes the value 1 for this document.

As a result, we can have a document that has the value 1.5 for a long field in the _source.

Further reading:
https://www.elastic.co/guide/en/elasticsearch/reference/current/coerce.html
https://discuss.elastic.co/t/storing-a-floating-point-value-in-a-long-field-what-no-mapping-error/80238

**Problem**
Trino ES connector retrieves the document data from the `_source`. And if there is a `long` field that has such a coerced value that cannot be interpreted as a `bigint`, it throws out an error. See the example snippet in the bottom.
**Note that** ES connector can handle the cases where we have a document that has a "string" as the value of the "long" field. For instance if we push a document that has value `"2"` for the "long" field, it is (understandably) interpreted as a "bigint".

**Suggestion**
For the ES connector, replicate the ES behavior for coerced values such that if we have a float value for a `long` field (Trino equivalent: `bigint`), then truncate the value of the float value to an integer.

**Example**
```
# create a local test index
~ % curl -X PUT localhost:9200/test4/
>>> {"acknowledged":true,"shards_acknowledged":true,"index":"test4"}%
# push a document with a field "long_field" that has value 0
~ % curl -X PUT localhost:9200/test4/_doc/1 -H "Content-Type: application/json" -d '{"long_field": 0}'
>>> {"_index":"test4","_type":"_doc","_id":"1","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":0,"_primary_term":1}%
# ES classifies it as "long" type
~ % curl localhost:9200/test4/_mapping
>>> {"test4":{"mappings":{"properties":{"long_field":{"type":"long"}}}}}%
# so does Trino
~ % tcli --execute "show columns from elasticsearch_local.indices.test4"
>>> "long_field","bigint","",""
# everything normal until here
~ % tcli --execute "select * from elasticsearch_local.indices.test4"
>>> "0"
# now, ES allows me to push a document to the same index that has a string value for that "long_field"...
~ % curl -X PUT localhost:9200/test4/_doc/2 -H "Content-Type: application/json" -d '{"long_field": "1.5"}'
>>> {"_index":"test4","_type":"_doc","_id":"2","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":1,"_primary_term":1}%
# ES mapping still is the same
~ % curl localhost:9200/test4/_mapping
>>> {"test4":{"mappings":{"properties":{"long_field":{"type":"long"}}}}}%
# And I can get the results from ES
~ % curl localhost:9200/test4/_search
>>> {"took":2,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":2,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"test4","_type":"_doc","_id":"1","_score":1.0,"_source":{"long_field": 0}},{"_index":"test4","_type":"_doc","_id":"2","_score":1.0,"_source":{"long_field": "1.5"}}]}}%
# The column definition at Trino is also the same
~ % tcli --execute "show columns from elasticsearch_local.indices.test4"
>>> "long_field","bigint","",""
# However, Trino throws out an error since we now have a value for the field "long_field" that is not of type "Bigint"...
~ % tcli --execute "select * from elasticsearch_local.indices.test4"
>>> Query 20210316_214657_00090_3vy2g failed: Cannot parse value for field 'long_field' as BIGINT: 1.5
io.trino.spi.TrinoException: Cannot parse value for field 'long_field' as BIGINT: 1.5
	at io.trino.plugin.elasticsearch.decoders.BigintDecoder.decode(BigintDecoder.java:52)
	at io.trino.plugin.elasticsearch.ScanQueryPageSource.getNextPage(ScanQueryPageSource.java:189)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:301)
	at io.trino.operator.Driver.processInternal(Driver.java:387)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_352____20210316_183929_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by MusKaya** [comment]
@bitsondatadev fyi

**Comment by bitsondatadev** [comment]
Thanks for creating this! I'll take a look tomorrow!

**Comment by lpoulain** [comment]
What should be the right behavior in such a case? Should it return a null value? Something else?
