### ISSUE TITLE
Query error when using EXCEPT in sub-query.

### ISSUE THREAD

**Issue by adeubank** [trinodb/trino#7342]
When using the `EXCEPT` clause, this works.

```sql
SELECT id
FROM (
         VALUES (1, 'a'),
                (2, 'b'),
                (3, 'c')
     ) AS t1 (id, name)
    EXCEPT
SELECT id
FROM (
         VALUES (1, 'a')
     ) AS t2 (id, name);
```

But, this fails with  `java.lang.UnsupportedOperationException: not yet implemented: io.trino.sql.tree.Except`

```sql
SELECT *
FROM (
         VALUES (1, 'a'),
                (2, 'b'),
                (3, 'c')
     ) AS t (id, name)
WHERE (id IN (
    SELECT id
    FROM (
             VALUES (1, 'a'),
                    (2, 'b'),
                    (3, 'c')
         ) AS t1 (id, name)
        EXCEPT
    SELECT id
    FROM (
             VALUES (1, 'a')
         ) AS t2 (id, name)
));
```

<details><summary>stacktrace</summary>

```
java.lang.UnsupportedOperationException: not yet implemented: io.trino.sql.tree.Except
	at io.trino.sql.tree.Node.shallowEquals(Node.java:60)
	at io.trino.sql.planner.ScopeAware.scopeAwareComparison(ScopeAware.java:137)
	at io.trino.sql.util.AstUtils.treeEqual(AstUtils.java:47)
	at io.trino.sql.util.AstUtils.treeEqual(AstUtils.java:61)
	at io.trino.sql.util.AstUtils.treeEqual(AstUtils.java:61)
	at io.trino.sql.planner.ScopeAware.equals(ScopeAware.java:94)
	at com.google.common.collect.SingletonImmutableBiMap.get(SingletonImmutableBiMap.java:56)
	at io.trino.sql.planner.TranslationMap.tryGetMapping(TranslationMap.java:304)
	at io.trino.sql.planner.TranslationMap$1.rewriteExpression(TranslationMap.java:166)
	at io.trino.sql.planner.TranslationMap$1.rewriteExpression(TranslationMap.java:162)
	at io.trino.sql.tree.ExpressionRewriter.rewriteSubqueryExpression(ExpressionRewriter.java:135)
	at io.trino.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitSubqueryExpression(ExpressionTreeRewriter.java:705)
	at io.trino.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitSubqueryExpression(ExpressionTreeRewriter.java:70)
	at io.trino.sql.tree.SubqueryExpression.accept(SubqueryExpression.java:51)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.tree.ExpressionTreeRewriter.rewrite(ExpressionTreeRewriter.java:58)
	at io.trino.sql.tree.ExpressionTreeRewriter.rewriteWith(ExpressionTreeRewriter.java:37)
	at io.trino.sql.planner.TranslationMap.rewrite(TranslationMap.java:161)
	at io.trino.sql.planner.PlanBuilder.translate(PlanBuilder.java:83)
	at io.trino.sql.planner.QueryPlanner.coerce(QueryPlanner.java:1319)
	at io.trino.sql.planner.SubqueryPlanner.planInPredicate(SubqueryPlanner.java:208)
	at io.trino.sql.planner.SubqueryPlanner.planInPredicate(SubqueryPlanner.java:185)
	at io.trino.sql.planner.SubqueryPlanner.handleSubqueries(SubqueryPlanner.java:118)
	at io.trino.sql.planner.QueryPlanner.filter(QueryPlanner.java:600)
	at io.trino.sql.planner.QueryPlanner.plan(QueryPlanner.java:376)
	at io.trino.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:786)
	at io.trino.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:105)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:576)
	at io.trino.sql.planner.QueryPlanner.plan(QueryPlanner.java:185)
	at io.trino.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:779)
	at io.trino.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:105)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.RelationPlanner.visitTableSubquery(RelationPlanner.java:771)
	at io.trino.sql.planner.RelationPlanner.visitTableSubquery(RelationPlanner.java:105)
	at io.trino.sql.tree.TableSubquery.accept(TableSubquery.java:53)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:576)
	at io.trino.sql.planner.QueryPlanner.plan(QueryPlanner.java:185)
	at io.trino.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:779)
	at io.trino.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:105)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:691)
	at io.trino.sql.planner.LogicalPlanner.getInsertPlan(LogicalPlanner.java:381)
	at io.trino.sql.planner.LogicalPlanner.createInsertPlan(LogicalPlanner.java:468)
	at io.trino.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:254)
	at io.trino.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:238)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:203)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:198)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:193)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:450)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:430)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:382)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_353____20210315_221938_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
</details>

**Comment by AdamLandis** [comment]
Impressive turn around Martin

**Comment by bitsondatadev** [comment]
Feel free to add a star to the Trino repo if this impressed you on a scale of no star to star!
