### ISSUE TITLE
org.apache.phoenix.query.DefaultGuidePostsCacheFactory

### ISSUE THREAD

**Issue by yamingd** [trinodb/trino#7363]
I used dbeaver to connect to Trino of Phoenix, and there was such an error  Could not load/instantiate class org.apache.phoenix.query.DefaultGuidePostsCacheFactory this my configuration

hbase version 2.3.4
phoenix version 5.1
trino version 353
phoenix5 jar phoenix-client-embedded-hbase-2.3-5.1.0.jar

![1616147367749](https://user-images.githubusercontent.com/639157/111808275-d02ba200-890e-11eb-8b5e-6c2fef183b93.png)

**Comment by findepi** [comment]
@yamingd would you be able to copy the error stacktrace as text?

also, what's our phoenix catalog properties file?

**Comment by yamingd** [comment]
2021-03-19T18:25:01.900+0800	ERROR	remote-task-callback-2	io.trino.execution.StageStateMachine	Stage 20210319_102501_00003_cwsiw.1 failed
io.trino.spi.TrinoException: org.apache.phoenix.exception.PhoenixNonRetryableRuntimeException: Could not load/instantiate class org.apache.phoenix.query.DefaultGuidePostsCacheFactory
	at io.trino.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:270)
	at io.trino.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:107)
	at io.trino.plugin.jdbc.JdbcRecordSet.cursor(JdbcRecordSet.java:60)
	at io.trino.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
	at io.trino.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:68)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:298)
	at io.trino.operator.Driver.processInternal(Driver.java:387)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_353____20210319_101838_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.phoenix.thirdparty.com.google.common.util.concurrent.UncheckedExecutionException: org.apache.phoenix.exception.PhoenixNonRetryableRuntimeException: Could not load/instantiate class org.apache.phoenix.query.DefaultGuidePostsCacheFactory
	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache.get(LocalCache.java:3849)
	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4711)
	at org.apache.phoenix.jdbc.PhoenixDriver.getConnectionQueryServices(PhoenixDriver.java:241)
	at org.apache.phoenix.jdbc.PhoenixEmbeddedDriver.createConnection(PhoenixEmbeddedDriver.java:144)
	at org.apache.phoenix.jdbc.PhoenixDriver.connect(PhoenixDriver.java:221)
	at io.trino.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:65)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:42)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:42)
	at io.trino.plugin.jdbc.BaseJdbcClient.getConnection(BaseJdbcClient.java:415)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getConnection$10(StatisticsAwareJdbcClient.java:150)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getConnection(StatisticsAwareJdbcClient.java:150)
	at io.trino.plugin.jdbc.ForwardingJdbcClient.getConnection(ForwardingJdbcClient.java:131)
	at io.trino.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:73)
	... 17 more
Caused by: org.apache.phoenix.exception.PhoenixNonRetryableRuntimeException: Could not load/instantiate class org.apache.phoenix.query.DefaultGuidePostsCacheFactory
	at org.apache.phoenix.query.GuidePostsCacheProvider.loadAndGetGuidePostsCacheFactory(GuidePostsCacheProvider.java:57)
	at org.apache.phoenix.query.GuidePostsCacheProvider.getGuidePostsCache(GuidePostsCacheProvider.java:73)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl.<init>(ConnectionQueryServicesImpl.java:457)
	at org.apache.phoenix.jdbc.PhoenixDriver$3.call(PhoenixDriver.java:248)
	at org.apache.phoenix.jdbc.PhoenixDriver$3.call(PhoenixDriver.java:241)
	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4716)
	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3445)
	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2194)
	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2153)
	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2043)
	... 32 more


connector.name=phoenix5
phoenix.connection-url=jdbc:phoenix:172.16.163.16,172.16.163.17,172.16.163.18:2181:/hbase
phoenix.config.resources=/opt/software/phoenix-conf/hbase-site.xml

**Comment by findepi** [comment]
cc @vincentpoon @lhofhansl

**Comment by yamingd** [comment]
@vincentpoon @lhofhansl  any thoughts ?

**Comment by sontt710** [comment]
Hello,

I having the same issue, Anyone have solution for this?

Thanks!

**Comment by xiaojun90713** [comment]
I having the same issue too, Anyone have solution for this?

**Comment by vincentpoon** [comment]
@xiaojun90713 @sontt710 @yamingd This is fixed in Trino 366.  You need this patch:
https://github.com/trinodb/trino/commit/44c385478c3b6d75f7a166b6623ef586095251c6

**Comment by jayramdubey** [comment]
I have the same issue, Does Anyone have a solution for this?

Thanks!
