### ISSUE TITLE
Handle ambiguous dereference as semantic error

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#7398]
This query should fail during analysis:
```sql
SELECT CAST(ROW(1, 2) AS ROW(a BIGINT, A DOUBLE)).a
```
But it fails during planning:
```
java.lang.IllegalArgumentException: Ambiguous field io.trino.spi.type.RowType$Field@226de93c in type row(a bigint, a double)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:441)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitDereferenceExpression(ExpressionInterpreter.java:318)
```

**Comment by electrum** [comment]
There is an existing test for this in `io.trino.type.TestRowOperators#testRowCast` which probably needs to be moved to `AbstractTestEngineOnlyQueries`.
