### ISSUE TITLE
Fantom queries on workers, cancelation issue

### ISSUE THREAD

**Issue by davseitsev** [trinodb/trino#7409]
Sometime we got into the situation when a query is missing on coordinator but is present on workers.
It could happen when heavy query is killed via web UI or when it reaches `query.max-execution-time`.

Such queries keep consumming CPU/Memory resources on workers. They are shown in the memory pool on worker UI.
Also they apper in thread and heap dumps. Latest case that we had was related to windows function
 `sum(app_count) over(partition by mmid order by action_date)`:

Here is stack trace from worker
```
"20210324_074915_21411_umf85.1.7-184-70" #70 prio=5 os_prio=0 cpu=6891505.10ms elapsed=20442.07s tid=0x00007f1ed7687600 nid=0x2b22 runnable  [0x00007f06dd7d7000]
   java.lang.Thread.State: RUNNABLE
        at io.prestosql.$gen.PagesIndexComparator_20210324_075059_33239.compareTo(Unknown Source)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:59)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.sort(PagesIndexOrdering.java:37)
        at io.prestosql.operator.PagesIndex.sort(PagesIndex.java:393)
        at io.prestosql.operator.WindowOperator.sortPagesIndexIfNecessary(WindowOperator.java:850)
        at io.prestosql.operator.WindowOperator$PagesToPagesIndexes.process(WindowOperator.java:528)
        at io.prestosql.operator.WindowOperator$PagesToPagesIndexes.process(WindowOperator.java:484)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WindowOperator.getOutput(WindowOperator.java:367)
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver$$Lambda$7205/0x00007f056dd97cb0.get(Unknown Source)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_346____20210324_035507_2.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.10/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.10/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)
```

I also described case which we had with regexp_like https://github.com/trinodb/trino/issues/7159#issuecomment-802819589

I think such queries should be shown in coordinator UI with `FINISHING` or `CANCELLING` state.
Also it would be great to find approach how to kill them from workers completely.

**Comment by davseitsev** [comment]
Also queries keep running on workers after coordinator restart

**Comment by sopel39** [comment]
Do you have
```
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
```
set in Trino JVM config?

**Comment by davseitsev** [comment]
Yes, we do

**Comment by sopel39** [comment]
Wasn't that fixed in https://github.com/trinodb/trino/issues/7416#issuecomment-817604494
?

**Comment by davseitsev** [comment]
These are two different problems. 

The issue which you point to is about particular case of stuck queries. In that context stuck  query doesn't necessarily mean fantom (not visible on coordinator).

Current issue is about fantom queries which don't appear on coordinator, which coordinator does'n know about and doesn't consider in splits scheduling. The cause of such problem could be different, I provided 2 examples: long sorting and regexp filtering.

**Comment by sopel39** [comment]
Queries that don't yield or capture interrupted exception will be running on worker even after cancellation.

> The cause of such problem could be different, I provided 2 examples: long sorting and regexp filtering.

Is long sorting still an issue for you? How long does it run after cancellation?

**Comment by davseitsev** [comment]
> Queries that don't yield or capture interrupted exception will be running on worker even after cancellation
That's the issue. Also the issue is that they are shown in coordinator.

After cancellation queries can run different time, it depends on the query. On the graph above you can see that after restart  the longest fantom query finished in 30 minutes. But we often meet queries which can run for hours until we restart the whole cluster. We would like to see these queries in coordinator UI.

**Comment by sopel39** [comment]
Ideally, query should cancel immediately. We know couple of places that can be improved (e.g regular expressions), but maybe there are others that we don't know

**Comment by davseitsev** [comment]
Can we at least show such queries on coordinator? To let users know that their query is still running and to disallow users run more queries according to resource groups configuration.

**Comment by sopel39** [comment]
Query information cannot be rebuild on coordinator from worker data. Worker doesn't have full information to do so.

**Comment by davseitsev** [comment]
> Query information cannot be rebuild on coordinator from worker data. Worker doesn't have full information to do so.

I agree that after coordinator restart it's impossible to rebuilt full query information , but what about the case when the query is killed or failed or exceeded timeout. Is it possible to retrieve information about splits on workers and just **keep** query on coordinator in `FINISHING` state until it takes resource on workers ignoring `query.min-expire-age` property?

**Comment by hashhar** [comment]
This should be fixed by https://github.com/trinodb/trino/pull/13064.

Closing. Feel free to re-open if still relevant.
