### ISSUE TITLE
Queries with sorting in window get stuck

### ISSUE THREAD

**Issue by davseitsev** [trinodb/trino#7416]
After we have upgraded the cluster from 326 to 346 version some queries started to stuck. It happens to queries with sorting in the window. For example:
```
create table if not exists prod.s.first_sessions as
with running_sums as(
  select mmid, action_date, sum(app_count) over(partition by mmid order by action_date) num_of_sessions 
  from prod.s.filtered_tbl
)
select mmid, min(action_date) first_session_date from running_sums
  where num_of_sessions >= 10
  group by 1
```
If cluster is has no load the query finishes in 2 minutes but if you run a couple of such queries of cluster is loaded on 30-40% the query fails in 2 hours and get stuck on workers like I described here https://github.com/trinodb/trino/issues/7409.

The query always stuck on a single worker in quickSort
```
"20210324_074915_21411_umf85.1.7-184-70" #70 prio=5 os_prio=0 cpu=6891505.10ms elapsed=20442.07s tid=0x00007f1ed7687600 nid=0x2b22 runnable  [0x00007f06dd7d7000]
   java.lang.Thread.State: RUNNABLE
        at io.prestosql.$gen.PagesIndexComparator_20210324_075059_33239.compareTo(Unknown Source)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:59)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at io.prestosql.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at io.prestosql.operator.PagesIndexOrdering.sort(PagesIndexOrdering.java:37)
        at io.prestosql.operator.PagesIndex.sort(PagesIndex.java:393)
        at io.prestosql.operator.WindowOperator.sortPagesIndexIfNecessary(WindowOperator.java:850)
        at io.prestosql.operator.WindowOperator$PagesToPagesIndexes.process(WindowOperator.java:528)
        at io.prestosql.operator.WindowOperator$PagesToPagesIndexes.process(WindowOperator.java:484)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WindowOperator.getOutput(WindowOperator.java:367)
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
```

But there is no data skew on particular mmid. On the screen you can see that single worker processes the same number of rows and amount of data like other workers but it's running for 1h30m when other worked proceeded in about 2 minutes. CPU is not overloaded, memory usage is moderate.
Top util show CPU usage ~40% for stuck query.
![image](https://user-images.githubusercontent.com/1793410/112456682-a7b70400-8d63-11eb-96ce-72b42c5ae1e6.png)
I got through the heap dump and found nothing weird.

Let me know if I can provide more information. I appreciate any help about this.

**Comment by martint** [comment]
Can you paste the output of EXPLAIN for both versions?

**Comment by davseitsev** [comment]
Attaching output for `explain` and `explain analyze`
[presto-326-explain-and-explain-analyze.txt](https://github.com/trinodb/trino/files/6205485/presto-326-explain-and-explain-analyze.txt)
[presto-346-explain-and-explain-analyze.txt](https://github.com/trinodb/trino/files/6205486/presto-346-explain-and-explain-analyze.txt)

Elapsed time on 326 with 3 workers: 5.57m
Elapsed time on 346 with 100+ workers: 46.46m

**Comment by martint** [comment]
Thanks!

The difference is in this section:

346:
```
         └─ Window[partition by (mmid), order by (action_date ASC_NULLS_LAST)][$hashvalue]
              │   Layout: [action_date:varchar, mmid:varchar, app_count:bigint, $hashvalue:bigint, sum:bigint]
              │   CPU: 8.02h (96.99%), Scheduled: 10.36h (95.37%), Output: 676421027 rows (52.29GB)
              │   Input avg.: 10569078.55 rows, Input std.dev.: 0.58%
              │   sum := sum("app_count") RANGE UNBOUNDED_PRECEDING CURRENT_ROW
```

326:
```
           └─ Window[partition by (mmid), order by (action_date ASC_NULLS_LAST)][$hashvalue]
              │   Layout: [action_date:varchar, mmid:varchar, app_count:bigint, $hashvalue:bigint, sum:bigint]
              │   CPU: 55.08m (73.56%), Scheduled: 55.26m (63.87%), Output: 676421027 rows (52.29GB)
              │   Input avg.: 56368418.92 rows, Input std.dev.: 0.24%
              │   sum := sum("app_count") RANGE UNBOUNDED_PRECEDING CURRENT_ROW
```

It's the same amount of data processed, so it points to an issue during execution (vs a difference in query plans).

Is there a change you could help bisect this to the version that introduced the issue? Is 346 the first version that reproduces the issue? Specifically, can you try on 345?

**Comment by davseitsev** [comment]
I will try to gather more information and update here

**Comment by findepi** [comment]
Do you have spill enabled?

**Comment by sopel39** [comment]
Do you have query json for slow query?

**Comment by davseitsev** [comment]
Spill is not enabled.

Here are query json for fast and slow runs (same query same cluster after restart):
[20210326_150018_36177_duxqn-fast.json.gz](https://github.com/trinodb/trino/files/6212876/20210326_150018_36177_duxqn-fast.json.gz)
[20210325_133712_48947_2g2e8-slow.json.gz](https://github.com/trinodb/trino/files/6212878/20210325_133712_48947_2g2e8-slow.json.gz)

I'm thinking whether it could be related to JIT. We increased code cache from 350M to 512M and aded additional jvm configs to workers:
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000

I will update about results.

**Comment by davseitsev** [comment]
I think we proved problem with JIT. After we had added above JVM options we didn't see any stuck queries.
Then we rolled back the change and the problem started to reproduce.

Here is result of `pstack` from worker:
```
Thread 273 (Thread 0x7f5380129700 (LWP 28180)):
#0  0x00007f6c9599ba35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f6c948743e3 in os::PlatformEvent::park() () from /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-1.el7_9.x86_64/lib/server/libjvm.so
#2  0x00007f6c9481c008 in Monitor::ILock(Thread*) () from /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-1.el7_9.x86_64/lib/server/libjvm.so
#3  0x00007f6c9481ca48 in Monitor::lock_without_safepoint_check() () from /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-1.el7_9.x86_64/lib/server/libjvm.so
#4  0x00007f6c943294e3 in Events::log_deopt_message(Thread*, char const*, ...) () from /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-1.el7_9.x86_64/lib/server/libjvm.so
#5  0x00007f6c943274a2 in Deoptimization::uncommon_trap_inner(JavaThread*, int) () from /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-1.el7_9.x86_64/lib/server/libjvm.so
#6  0x00007f6c94328822 in Deoptimization::uncommon_trap(JavaThread*, int, int) () from /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-1.el7_9.x86_64/lib/server/libjvm.so
#7  0x00007f6c6daa4121 in ?? ()
#8  0x00007f565eb38608 in ?? ()
#9  0x00007f6c7a470d98 in ?? ()
...
```

It's very similar to the problem described in this article: [Presto System load is too high problem investigation](https://www.programmersought.com/article/49146323844/)

I believe the issue could be closed.

**Comment by sopel39** [comment]
Thanks for reporting. We know recommend using
```
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
```
as default settings
