### ISSUE TITLE
java.lang.UnsupportedOperationException: io.prestosql.spi.type.DoubleType on PrestoSQL 343 on EMR

### ISSUE THREAD

**Issue by SrushtiBhoyar** [trinodb/trino#7418]
I am trying to query tables using PrestoSQL 343 on EMR v6.2.0 but getting the error below.

Also tried setting hive.parquet.use-column-names=true but no luck...
I also checked if there is schema mismatch between parquet file and glue metastore using parquet-tools but both places suggest that the column type is double.

Also the same query works on Athena.

```
2021-03-25T14:31:58.669Z	ERROR	remote-task-callback-314	io.prestosql.execution.StageStateMachine	Stage 20210325_143158_00054_hre5c.1 failed
java.lang.UnsupportedOperationException: io.prestosql.spi.type.DoubleType
	at io.prestosql.spi.type.AbstractType.writeSlice(AbstractType.java:133)
	at io.prestosql.parquet.reader.BinaryColumnReader.readValue(BinaryColumnReader.java:55)
	at io.prestosql.parquet.reader.PrimitiveColumnReader.lambda$readValues$2(PrimitiveColumnReader.java:183)
	at io.prestosql.parquet.reader.PrimitiveColumnReader.processValues(PrimitiveColumnReader.java:203)
	at io.prestosql.parquet.reader.PrimitiveColumnReader.readValues(PrimitiveColumnReader.java:182)
	at io.prestosql.parquet.reader.PrimitiveColumnReader.readPrimitive(PrimitiveColumnReader.java:170)
	at io.prestosql.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:262)
	at io.prestosql.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:314)
	at io.prestosql.parquet.reader.ParquetReader.readBlock(ParquetReader.java:297)
	at io.prestosql.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:164)
	at io.prestosql.spi.block.LazyBlock$LazyData.load(LazyBlock.java:381)
	at io.prestosql.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:360)
	at io.prestosql.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:276)
	at io.prestosql.spi.Page.getLoadedPage(Page.java:273)
	at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:304)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_343____20210325_081006_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by findepi** [comment]
> I also checked if there is schema mismatch between parquet file and glue metastore using parquet-tools but both places suggest that the column type is double.

For a double parquet field the `BinaryColumnReader` (as shown on stacktrace) shouldn't be used.
Does your table contain multiple partitions or multiple files?

**Comment by findepi** [comment]
Also, i  encourage you to reach out for help on the `#troubleshooting` channel  on [our slack](https://trino.io/slack.html)

**Comment by raunaqmorarka** [comment]
Issue is obsolete as the relevant code has changed a lot
