### ISSUE TITLE
IllegalStateException in WindowOperator.close()

### ISSUE THREAD

**Issue by martint** [trinodb/trino#7419]
This query succeeds but produces an exception in the logs:

```sql
SELECT sum(totalprice) OVER (PARTITION BY custkey ORDER BY orderdate) v
FROM tpch.sf1.orders
LIMIT 1
```

```
java.lang.IllegalStateException: Total number of rows in index does not match number of rows in partitions within that index
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at io.trino.operator.WindowInfo$IndexInfoBuilder.build(WindowInfo.java:205)
	at io.trino.operator.WindowInfo$DriverWindowInfoBuilder.build(WindowInfo.java:76)
	at io.trino.operator.WindowOperator.close(WindowOperator.java:906)
	at io.trino.operator.Driver.closeAndDestroyOperators(Driver.java:554)
	at io.trino.operator.Driver.destroyIfNecessary(Driver.java:517)
	at io.trino.operator.Driver.tryWithLock(Driver.java:691)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
```

It happens on versions as early as 312 (that's the oldest one I tried) and it's still present as of 354.

**Comment by findepi** [comment]
Probably that's obvious by now -- the check is that fails is reasonable when window partition is consumed fully. 
And this is not the case of a LIMIT query, which is short-circuited, and WindowOperator gets a `close()` "in the middle".

We should remove the check and adjust `windowInfo` reporting appropriately.

(BTW I wish we had a mechanism for finding problems being logged and ignored during testing.
It's not easy, but certainly doable. For example, one can attach a custom logging handler to capture logs during tests' execution.)

**Comment by findepi** [comment]
Alternatively, we can remove 
https://github.com/trinodb/trino/blob/ecde09c3f809f5d96e096ace83417d7f53c1a0fb/core/trino-main/src/main/java/io/trino/operator/WindowOperator.java#L906
-- ie `windowInfo` creation during `close`.

**Comment by Chaho12** [comment]
Fixed by https://github.com/trinodb/trino/issues/18030 ?
