### ISSUE TITLE
NullPointerException while executing Cassandra query 

### ISSUE THREAD

**Issue by sreeharicheerla** [trinodb/trino#7433]
Hi,  We are getting the following exception while  executing the Cassandra query with presto 330. Can someone please help  in resolving this issue ?

failed
java.lang.NullPointerException
	at io.prestosql.plugin.cassandra.CassandraRecordCursor.getLong(CassandraRecordCursor.java:106)
	at io.prestosql.$gen.CursorProcessor_20210326_132550_3.filter(Unknown Source)
	at io.prestosql.$gen.CursorProcessor_20210326_132550_3.process(Unknown Source)
	at io.prestosql.operator.ScanFilterAndProjectOperator$RecordCursorToPages.process(ScanFilterAndProjectOperator.java:312)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.access$000(WorkProcessorUtils.java:37)
	at io.prestosql.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:148)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_330____20210326_132407_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sreeharicheerla** [comment]
Query we are using is :
SELECT *  FROM table_name WHERE (created_date >= CAST('2020-12-29 10:30:00.000' AS timestamp))

**Comment by findepi** [comment]
Thanks for filing an issue. This has been discussed one day on Slack https://trinodb.slack.com/archives/CFLB9AMBN/p1602162537199200

>  ebyhr what i can tell is NPE because `com.datastax.driver.core.AbstractGettableByIndexData#getTimestamp` returned null even though `com.datastax.driver.core.GettableByIndexData#isNull` did not return true. i think the reponsible piece is the `bytes != null && bytes.remaining() != 0` check in
`com.datastax.driver.core.TypeCodec.TimestampCodec#deserialize`

> the driver is apparently reading empty bytes buffer

**Comment by findepi** [comment]
@sreeharicheerla do you happen to have steps to reproduce?

cc @ebyhr

**Comment by sreeharicheerla** [comment]
@findepi  This is reproducible consistently in our environment and can't be shared. But we have a cassandra DB with too much data and when we execute the above query, we are getting the exception.

**Comment by ebyhr** [comment]
@sreeharicheerla Could you try simplifying steps to reproduce with sample data? You don't need to share the actual data.

**Comment by Cabeda** [comment]
I'm getting the same issue when using DataStax driver (in a scala application) to encode an Optional[LocalDateTime] to a timestamp column

**Comment by asantoz** [comment]
This issue happens when a timestamp column is saved as an empty string (in DataStax java driver the conversion of an optional LocalDateTime with `saveNullFields` enable is a `ByteBuffer.allocate(0)` which is similar to a string).
This bug seems to happen on [line 109 of CassandraRecordCursor](https://github.com/trinodb/trino/blob/8bac01572d458e100c98e8b6c432a41215391f52/plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRecordCursor.java#L109) with the unsafe null operation of `.getTime()`.

**Comment by ebyhr** [comment]
@asantoz I can reproduce now. Thank you for your information!

**Comment by ebyhr** [comment]
Fixed TIMESTAMP locally and looking into other types now.

**Comment by asantoz** [comment]
awesome @ebyhr 👏

**Comment by sreeharicheerla** [comment]
@ebyhr Awesome. Thanks you . Please let us know when this one will be released.

**Comment by ebyhr** [comment]
@sreeharicheerla This fix will be included in the next release. Please wait for a while.
