### ISSUE TITLE
Flaky TestSqlServerTypeMapping

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#7453]
```
Error:  Tests run: 174, Failures: 1, Errors: 0, Skipped: 72, Time elapsed: 419.621 s <<< FAILURE! - in TestSuite
Error:  init(io.trino.plugin.sqlserver.TestSqlServerTypeMapping)  Time elapsed: 18.349 s  <<< FAILURE!
java.lang.RuntimeException: Failed to execute statement: CREATE DATABASE database_200ad1cb63574e61b0174992e56ce3bc
	at io.trino.plugin.sqlserver.TestingSqlServer.execute(TestingSqlServer.java:60)
	at io.trino.plugin.sqlserver.TestingSqlServer.setUpDatabase(TestingSqlServer.java:93)
	at io.trino.plugin.sqlserver.TestingSqlServer.start(TestingSqlServer.java:73)
	at io.trino.plugin.sqlserver.TestSqlServerTypeMapping.createQueryRunner(TestSqlServerTypeMapping.java:51)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: An unexpected error occurred while checking the sector size for file '/var/opt/mssql/data/database_200ad1cb63574e61b0174992e56ce3bc_log.ldf'. Move the file to a local NTFS volume, where the sector size can be retrieved. Check the SQL Server error log for more information.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:872)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:743)
	at io.trino.plugin.sqlserver.TestingSqlServer.execute(TestingSqlServer.java:57)
	... 17 more

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestSqlServerTypeMapping>AbstractTestQueryFramework.init:93->createQueryRunner:51 » Runtime
[INFO] 

````

**Comment by findepi** [comment]
@hovaesco can you please take a look?

**Comment by hovaesco** [comment]
The issue pops out during SQL server container setup in method `setUpDatabase()`. I did a small research and it seems that it is intermittent and exists on various versions of SQL server docker image. One of the solutions would be to configure retry policy as suggested here: https://github.com/microsoft/mssql-docker/issues/623#issuecomment-652042300

**Comment by kokosing** [comment]
Duplicate of https://github.com/trinodb/trino/issues/7872 which is fixed.
