### ISSUE TITLE
Flaky TestDistributedSpilledQueries.testExplainAnalyzeReportSpilledDataSize

### ISSUE THREAD

**Issue by skrzypo987** [trinodb/trino#7463]
Easily repeatable locally. With high iteration count there can be as much as 30% failed tests.

```
java.lang.AssertionError: 
Expecting:
  "Fragment 1 [tpch:orders:15000]
    CPU: 149.58ms, Scheduled: 615.57ms, Input: 15000 rows (0B); per task: avg.: 7500.00 std.dev.: 12.00, Output: 15000 rows (131.84kB)
    Output layout: [sum]
    Output partitioning: SINGLE []
    Stage Execution Strategy: UNGROUPED_EXECUTION
    Project[]
    │   Layout: [sum:bigint]
    │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
    │   CPU: 26.00ms (17.57%), Scheduled: 201.00ms (33.11%), Output: 15000 rows (131.84kB)
    │   Input avg.: 468.75 rows, Input std.dev.: 0.89%
    └─ Window[partition by (<orderkey>)][$hashvalue]
       │   Layout: [orderkey:bigint, custkey:bigint, $hashvalue:bigint, sum:bigint]
       │   CPU: 62.00ms (41.89%), Scheduled: 234.00ms (38.55%), Output: 15000 rows (527.34kB), Spilled: 1.16kB
       │   Input avg.: 468.75 rows, Input std.dev.: 0.89%
       │   sum := sum("custkey") RANGE UNBOUNDED_PRECEDING CURRENT_ROW
       └─ ScanProject[table = tpch:orders:sf0.01, grouped = false]
              Layout: [orderkey:bigint, custkey:bigint, $hashvalue:bigint]
              Estimates: {rows: 15000 (395.51kB), cpu: 263.67k, memory: 0B, network: 0B}/{rows: 15000 (395.51kB), cpu: 659.18k, memory: 0B, network: 0B}
              CPU: 60.00ms (40.54%), Scheduled: 172.00ms (28.34%), Output: 15000 rows (395.51kB)
              Input avg.: 468.75 rows, Input std.dev.: 0.89%
              $hashvalue := combine_hash(bigint '0', COALESCE("$operator$hash_code"("orderkey"), 0))
              orderkey := tpch:orderkey
              custkey := tpch:custkey
              tpch:orderstatus
                  :: [[F], [O], [P]]
              Input: 15000 rows (0B), Filtered: 0.00%

"
to contain pattern:
  ", Spilled: [1-9][0-9]*\wB"

	at io.trino.tests.TestDistributedSpilledQueries.testExplainAnalyzeReportSpilledDataSize(TestDistributedSpilledQueries.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

**Comment by sopel39** [comment]
cc @findepi
