### ISSUE TITLE
query gets stuck at 100% and then times out after 5 min

### ISSUE THREAD

**Issue by zyxue** [trinodb/trino#7480]
I'm running multiple queries of similar size in a cloud environment with [argo](https://argoproj.github.io/) workflow . If the query succeeds, it usually takes about 50s.

But often I see some (when I run 4 ~ 8 queries, 1 may be stuck, which exact one would fail seems random) get stuck at 100% (from the web UI), and then it stays 100% for about 4min until time out after 5min in total

The Trino error is like

```
io.trino.spi.TrinoException: Query 20210401_204307_00983_dkxdd has not been accessed since 2021-04-01T20:43:50.978Z: currentTime 2021-04-01T20:48:51.231Z
	at io.trino.execution.QueryTracker.failAbandonedQueries(QueryTracker.java:259)
	at io.trino.execution.QueryTracker.lambda$start$0(QueryTracker.java:81)
	at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:705)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

If I rerun the failed query, it would finish fine.

I'm using the [trino-python-client](https://github.com/trinodb/trino-python-client) (`trino==0.305.0`) 

Any idea what could be the cause?

**Comment by findepi** [comment]
"Query ... has not been accessed since" means client didn't ask for the query results.

So it's an issue with the client. Not the Python client itself, but rather how Argo is using that.

I will close this as not-an-issue in Trino.
We can continue conversation here, or on `#troubleshooting` channel on [our slack](https://trino.io/slack.html).
