### ISSUE TITLE
TestHiveViews.testRichSqlSyntax is flaky when executing control query on Hive

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#7535]
```
2021-04-01T13:13:33.1762300Z tests               | 2021-04-01 18:58:33 INFO: FAILURE     /    io.trino.tests.hive.TestHiveViews.testRichSqlSyntax (Groups: hive_views) took 4.2 seconds
2021-04-01T13:13:33.1777680Z tests               | 2021-04-01 18:58:33 SEVERE: Failure cause:
2021-04-01T13:13:33.1779768Z tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
2021-04-01T13:13:33.1782535Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
2021-04-01T13:13:33.1784547Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2021-04-01T13:13:33.1786836Z tests               | 	at io.trino.tests.hive.AbstractTestHiveViews.assertViewQuery(AbstractTestHiveViews.java:349)
2021-04-01T13:13:33.1789378Z tests               | 	at io.trino.tests.hive.AbstractTestHiveViews.testRichSqlSyntax(AbstractTestHiveViews.java:192)
2021-04-01T13:13:33.1792043Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-04-01T13:13:33.1794578Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-04-01T13:13:33.1797385Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-04-01T13:13:33.1799473Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-04-01T13:13:33.1801412Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-04-01T13:13:33.1803430Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-04-01T13:13:33.1805000Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-04-01T13:13:33.1806750Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-04-01T13:13:33.1808817Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-04-01T13:13:33.1810866Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-04-01T13:13:33.1812835Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-04-01T13:13:33.1814918Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-04-01T13:13:33.1816291Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-04-01T13:13:33.1817918Z tests               | Caused by: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
2021-04-01T13:13:33.1820240Z tests               | 	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:275)
2021-04-01T13:13:33.1822458Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
2021-04-01T13:13:33.1824862Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
2021-04-01T13:13:33.1826047Z tests               | 	... 16 more
2021-04-01T13:13:33.1827513Z tests               | 	Suppressed: java.lang.Exception: Query: SELECT   n_nationkey, n_name, region_between_1_2, starts_with_a, not_peru, contains_n, is_something, coalesced_name,   rounded_tan, the_orderdate, arithmetic FROM view_with_rich_syntax WHERE n_regionkey < 3 AND (n_nationkey < 5 OR n_nationkey IN (12, 17))
2021-04-01T13:13:33.1830121Z tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
2021-04-01T13:13:33.1831716Z tests               | 		... 17 more
2021-04-01T13:13:33.1832097Z tests               | 
2021-04-01T13:13:33.1881331Z tests               | 2021-04-01 18:58:33 INFO: [371 of 567] io.trino.tests.hive.TestHiveViews.testSelectFromHiveViewWithoutDefaultCatalogAndSchema (Groups: )
````

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/2305323931

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/2333074873 with CDH5.

@kokosing did you originally observe this with CDH5 as well?

**Comment by kokosing** [comment]
Not sure.

**Comment by findepi** [comment]
`io.trino.tests.hive.TestHiveViews.testRichSqlSyntax` passed 100 times on CDH5 locally for me.
but it's far less green @ https://github.com/trinodb/trino/pull/7592. seems like memory pressure related?

**Comment by findepi** [comment]
In a stress test https://github.com/trinodb/trino/pull/7592 cdh5 suite-1 failed 20 of 50 runs.
`TestHiveViews.testRichSqlSyntax` failure was in every from first 6 failures i checked. I did not check remaining 14 failures.

**Comment by findepi** [comment]
Supposedly fixed by https://github.com/trinodb/trino/pull/9595. Please reopen this (or maybe https://github.com/trinodb/trino/issues
/9472) if seen again.
cc @homar

**Comment by findinpath** [comment]
https://github.com/trinodb/trino/pull/15470#issuecomment-1362397525


```
2022-12-22 11:04:50 INFO: [303 of 478] io.trino.tests.product.hive.TestHiveViews.testRichSqlSyntax (Groups: hive_views)
tests               | 2022-12-22 11:04:51 WARNING: not retrying; stacktrace 'io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. Error caching map.xml: java.nio.channels.ClosedByInterruptException
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.hive.AbstractTestHiveViews.assertViewQuery(AbstractTestHiveViews.java:761)
tests               | 	at io.trino.tests.product.hive.AbstractTestHiveViews.testRichSqlSyntax(AbstractTestHiveViews.java:340)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
tests               | Caused by: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. Error caching map.xml: java.nio.channels.ClosedByInterruptException
tests               | 	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:275)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 	... 16 more
tests               | 	Suppressed: java.lang.Exception: Query: SELECT   n_nationkey, n_name, region_between_1_2, starts_with_a, not_peru, contains_n, is_something, coalesced_name,   rounded_tan, the_orderdate, arithmetic FROM view_with_rich_syntax WHERE n_regionkey < 3 AND (n_nationkey < 5 OR n_nationkey IN (12, 17))
```

**Comment by findepi** [comment]
@findinpath did you mean to reopen?

i did it for you.
since this is a flakiness on hive side, we should add some retry there

**Comment by findepi** [comment]
Improving retry pattern in https://github.com/trinodb/trino/pull/16707
