### ISSUE TITLE
Flaky test TestExternalAuthenticator.testAuthenticationFromMultipleThreadsWithCachedTokenAfterAuthenticateTimesOut

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#7559]
https://github.com/trinodb/trino/runs/2318804031

```
2021-04-11T20:52:55.7095840Z [ERROR] Tests run: 40, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.117 s <<< FAILURE! - in TestSuite
2021-04-11T20:52:55.7111879Z [ERROR] testAuthenticationFromMultipleThreadsWithCachedTokenAfterAuthenticateTimesOut(io.trino.client.auth.external.TestExternalAuthenticator)  Time elapsed: 0.029 s  <<< FAILURE!
2021-04-11T20:52:55.7120465Z org.junit.ComparisonFailure: expected:<[1]> but was:<[2]>
2021-04-11T20:52:55.7126524Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2021-04-11T20:52:55.7132559Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2021-04-11T20:52:55.7140268Z 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2021-04-11T20:52:55.7152285Z 	at io.trino.client.auth.external.TestExternalAuthenticator.testAuthenticationFromMultipleThreadsWithCachedTokenAfterAuthenticateTimesOut(TestExternalAuthenticator.java:255)
2021-04-11T20:52:55.7178546Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-04-11T20:52:55.7184166Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-04-11T20:52:55.7187160Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-04-11T20:52:55.7189163Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-04-11T20:52:55.7191009Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-04-11T20:52:55.7193390Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2021-04-11T20:52:55.7195371Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2021-04-11T20:52:55.7197820Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-04-11T20:52:55.7199938Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-04-11T20:52:55.7201838Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-04-11T20:52:55.7203838Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-04-11T20:52:55.7205154Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

cc @s2lomon

**Comment by wendigo** [comment]
https://github.com/trinodb/trino/pull/7625/checks?check_run_id=2371223686

**Comment by s2lomon** [comment]
I'm working on a fix, sorry for it beeing flaky in a first place.

**Comment by s2lomon** [comment]
https://github.com/trinodb/trino/pull/7704 that should fix it.

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/2422619586

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/2448389654

**Comment by findepi** [comment]
> #7704 that should fix it.

where are we with that?
