### ISSUE TITLE
Flaky logs collection from docker container in product tests

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#7577]
```
2021-04-11T20:08:49.5881785Z java.lang.RuntimeException: Could not execute command '/usr/bin/find /var/trino/var/log -type f -print' in container presto-master: /usr/bin/find: `/var/trino/var/log': No such file or directory
2021-04-11T20:08:49.5886584Z 
2021-04-11T20:08:49.5889174Z 	at io.trino.tests.product.launcher.env.DockerContainer.execCommand(DockerContainer.java:255)
2021-04-11T20:08:49.5895108Z 	at io.trino.tests.product.launcher.env.DockerContainer.listFilesInContainer(DockerContainer.java:353)
2021-04-11T20:08:49.5902395Z 	at io.trino.tests.product.launcher.env.DockerContainer.copyLogsToHostPath(DockerContainer.java:282)
2021-04-11T20:08:49.5910224Z 	at io.trino.tests.product.launcher.env.EnvironmentListener$3.containerStopping(EnvironmentListener.java:212)
2021-04-11T20:08:49.5914401Z 	at io.trino.tests.product.launcher.env.EnvironmentListener$1.lambda$containerStopping$6(EnvironmentListener.java:139)
2021-04-11T20:08:49.5920248Z 	at io.trino.tests.product.launcher.env.EnvironmentListener.lambda$tryInvokeListener$0(EnvironmentListener.java:80)
2021-04-11T20:08:49.5924375Z 	at net.jodah.failsafe.Functions.lambda$toCtxSupplier$13(Functions.java:261)
2021-04-11T20:08:49.5926924Z 	at net.jodah.failsafe.Functions.lambda$getPromise$1(Functions.java:81)
2021-04-11T20:08:49.5929298Z 	at net.jodah.failsafe.Functions.lambda$null$3(Functions.java:103)
2021-04-11T20:08:49.5932889Z 	at net.jodah.failsafe.internal.util.DelegatingScheduler.lambda$schedule$0(DelegatingScheduler.java:141)
2021-04-11T20:08:49.5936572Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-04-11T20:08:49.5939812Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-04-11T20:08:49.5943536Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-04-11T20:08:49.5946065Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kokosing** [comment]
Just before logs say:
```
2021-04-11T20:08:47.7157027Z tests               | 2021-04-12 01:53:47 INFO: Completed 2 tests
2021-04-11T20:08:47.7158562Z tests               | 2021-04-12 01:53:47 INFO: 2 SUCCEEDED      /      0 FAILED      /      0 SKIPPED
2021-04-11T20:08:47.7160128Z tests               | 2021-04-12 01:53:47 INFO: Tests execution took 11.6 seconds
2021-04-11T20:08:47.8727717Z tests               | 
2021-04-11T20:08:47.8728596Z tests               | ===============================================
2021-04-11T20:08:47.8730161Z tests               | tempto-tests
2021-04-11T20:08:47.8731220Z tests               | Total tests run: 2, Failures: 0, Skips: 0
2021-04-11T20:08:47.8732327Z tests               | ===============================================
2021-04-11T20:08:47.8733220Z tests               | 
2021-04-11T20:08:48.2371184Z tests               | (exited)
```
