### ISSUE TITLE
Kafka SSL configuration error

### ISSUE THREAD

**Issue by afilimonov** [trinodb/trino#7583]
I'm trying to configure Kafka SSL connection. My configuration is below

```
connector.name=kafka
kafka.nodes=xxxx
kafka.table-names=techhub.clickstream
kafka.security-protocol=SSL
kafka.ssl.keystore.location=/var/ssl/kafka.client.keystore.jks
kafka.ssl.keystore.password=xxx
kafka.ssl.truststore.location=/var/ssl/kafka.client.truststore.jks
kafka.ssl.truststore.password=xxx
kafka.ssl.key.password=xxx
```

However the server fails to start with this message

```
2021-04-13T16:49:40.164Z	INFO	main	io.trino.metadata.StaticCatalogStore	-- Loading catalog etc/catalog/kafka.properties --
2021-04-13T16:49:40.483Z	ERROR	main	io.trino.server.Server	Configuration errors:

1) Error: Configuration property 'kafka.security-protocol' was not used

2) Error: Configuration property 'kafka.ssl.key.password' was not used

3) Error: Configuration property 'kafka.ssl.keystore.location' was not used

4) Error: Configuration property 'kafka.ssl.keystore.password' was not used

5) Error: Configuration property 'kafka.ssl.truststore.location' was not used

6) Error: Configuration property 'kafka.ssl.truststore.password' was not used

6 errors
io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Configuration property 'kafka.security-protocol' was not used

2) Error: Configuration property 'kafka.ssl.key.password' was not used

3) Error: Configuration property 'kafka.ssl.keystore.location' was not used

4) Error: Configuration property 'kafka.ssl.keystore.password' was not used

5) Error: Configuration property 'kafka.ssl.truststore.location' was not used

6) Error: Configuration property 'kafka.ssl.truststore.password' was not used

6 errors
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:239)
	at io.trino.plugin.kafka.KafkaConnectorFactory.create(KafkaConnectorFactory.java:73)
	at io.trino.connector.ConnectorManager.createConnector(ConnectorManager.java:359)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:216)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:208)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:194)
	at io.trino.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
	at io.trino.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at io.trino.server.Server.doStart(Server.java:123)
	at io.trino.server.Server.lambda$start$0(Server.java:77)
	at io.trino.$gen.Trino_355____20210413_164931_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:77)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)


2021-04-13T16:49:40.485Z	INFO	Thread-72	io.airlift.bootstrap.LifeCycleManager	JVM is shutting down, cleaning up
```

I'm using the latest 355 Trino Docker image. Is Kafka SSL supported. I thought it was introduced in 354.

**Comment by kokosing** [comment]
It will be supported from 356.
