### ISSUE TITLE
TestIcebergParquetSmoke.testMonthTransformDate is flaky

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#7619]
```
2021-04-15T21:33:18.9998449Z 2021-04-15T16:33:18.999-0500 INFO Life cycle stopped
2021-04-15T21:33:19.4259244Z [ERROR] Tests run: 267, Failures: 1, Errors: 0, Skipped: 10, Time elapsed: 506.677 s <<< FAILURE! - in TestSuite
2021-04-15T21:33:19.4285269Z [ERROR] testMonthTransformDate(io.trino.plugin.iceberg.TestIcebergParquetSmoke)  Time elapsed: 0.157 s  <<< FAILURE!
2021-04-15T21:33:19.4290902Z java.lang.RuntimeException: line 1:1: Table 'iceberg.tpch.test_month_transform_date' already exists
2021-04-15T21:33:19.4296460Z 	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:120)
2021-04-15T21:33:19.4302009Z 	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:476)
2021-04-15T21:33:19.4493333Z 	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
2021-04-15T21:33:19.4495349Z 	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:225)
2021-04-15T21:33:19.4498191Z 	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:220)
2021-04-15T21:33:19.4502277Z 	at io.trino.plugin.iceberg.AbstractTestIcebergSmoke.testMonthTransformDate(AbstractTestIcebergSmoke.java:837)
2021-04-15T21:33:19.4505127Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-04-15T21:33:19.4507347Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-04-15T21:33:19.4510178Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-04-15T21:33:19.4512446Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-04-15T21:33:19.4514228Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-04-15T21:33:19.4563801Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-04-15T21:33:19.4565238Z 	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
2021-04-15T21:33:19.4566678Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
2021-04-15T21:33:19.4568614Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-04-15T21:33:19.4570587Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-04-15T21:33:19.4572829Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-04-15T21:33:19.4574752Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-04-15T21:33:19.4576004Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-04-15T21:33:19.4578098Z 	Suppressed: java.lang.Exception: SQL: CREATE TABLE test_month_transform_date (d DATE, b BIGINT) WITH (partitioning = ARRAY['month(d)'])
2021-04-15T21:33:19.4579919Z 		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:479)
2021-04-15T21:33:19.4581111Z 		... 17 more
2021-04-15T21:33:19.4582290Z Caused by: io.trino.spi.TrinoException: line 1:1: Table 'iceberg.tpch.test_month_transform_date' already exists
2021-04-15T21:33:19.4584198Z 	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
2021-04-15T21:33:19.4586583Z 	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
2021-04-15T21:33:19.4588776Z 	at io.trino.execution.CreateTableTask.internalExecute(CreateTableTask.java:117)
2021-04-15T21:33:19.4590553Z 	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:104)
2021-04-15T21:33:19.4592168Z 	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:79)
2021-04-15T21:33:19.4594009Z 	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:170)
2021-04-15T21:33:19.4595960Z 	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
2021-04-15T21:33:19.4597837Z 	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
2021-04-15T21:33:19.4599223Z 	at io.trino.$gen.Trino_testversion____20210415_212626_496.run(Unknown Source)
2021-04-15T21:33:19.4600647Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-04-15T21:33:19.4602565Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-04-15T21:33:19.4603815Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-04-15T21:33:19.4604281Z 
2021-04-15T21:33:19.9285954Z [INFO] 
2021-04-15T21:33:19.9286904Z [INFO] Results:
2021-04-15T21:33:19.9287422Z [INFO] 
2021-04-15T21:33:19.9287947Z [ERROR] Failures: 
2021-04-15T21:33:19.9290372Z [ERROR] io.trino.plugin.iceberg.TestIcebergParquetSmoke.testMonthTransformDate(io.trino.plugin.iceberg.TestIcebergParquetSmoke)
2021-04-15T21:33:19.9293069Z [INFO]   Run 1: PASS
2021-04-15T21:33:19.9297356Z [ERROR]   Run 2: TestIcebergParquetSmoke>AbstractTestIcebergSmoke.testMonthTransformDate:837->AbstractTestQueryFramework.assertUpdate:220->AbstractTestQueryFramework.assertUpdate:225 » Runtime
2021-04-15T21:33:19.9300108Z [INFO] 
```

**Comment by electrum** [comment]
This was moved to TestIcebergParquetConnectorTest via BaseIcebergConnectorTest and is no longer marked as flaky.
