### ISSUE TITLE
Incorrect query results when reading Hive VIEW with nested GROUP BYs

### ISSUE THREAD

**Issue by gjhkael** [trinodb/trino#7635]
You can use the following test case to reproduce the issue.
```sql
  public static final TestTable TABLE_FIVE = new TestTable("dwd_ogv_app_play_click_tf_inc_d", ImmutableMap.of("r_type", SqlTypeName.INTEGER,
      "ogv_type_name", SqlTypeName.VARCHAR, "buvid", SqlTypeName.VARCHAR, "log_date", SqlTypeName.VARCHAR));

  @Test
  public void testSelect() {
    String sql = String.format("select t.ogv_type_name, count(1) as user_amt from (SELECT ogv_type_name,\n" +
        "buvid\n" +
        "FROM dwd_ogv_app_play_click_tf_inc_d\n" +
        "WHERE log_date = '20210312'\n" +
        "AND r_type = 1\n" +
        "AND ogv_type_name IS NOT NULL\n" +
        "GROUP BY ogv_type_name, buvid) t GROUP BY\n" +
        "t.ogv_type_name", tableFive);
    String expectedSql = "";
    testConversion(sql, expectedSql);
  }
```

After convert, the presto query is below:
```sql
SELECT "ogv_type_name" AS "OGV_TYPE_NAME", COUNT(*) AS "USER_AMT"
FROM "dwd_ogv_app_play_click_tf_inc_d"
WHERE "log_date" = '20210312' AND "r_type" = 1 AND "ogv_type_name" IS NOT NULL
GROUP BY "ogv_type_name"
```
The semantics of the two Queries are clearly inconsistent.

https://github.com/linkedin/coral/issues/72

**Comment by losipiuk** [comment]
A more syntetic testcase to be put in `TestHiveViews.java` in Trino:
```
    @Test(groups = HIVE_VIEWS)
    public void testNestedGroupBy()
    {
        onHive().executeQuery("DROP VIEW IF EXISTS test_nested_group_by_view");
        onHive().executeQuery("CREATE VIEW test_nested_group_by_view AS " +
                        " SELECT n_regionkey, count(1) count " +
                        " FROM (" +
                        "   SELECT n_regionkey " +
                        "   FROM nation " +
                        "   GROUP BY n_regionkey " +
                        " ) t " +
                        " GROUP BY n_regionkey");

        assertViewQuery(
                "SELECT * FROM test_nested_group_by_view",
                queryAssert -> queryAssert.containsOnly(
                        row(0, 1),
                        row(1, 1),
                        row(2, 1),
                        row(3, 1),
                        row(4, 1)));
    }
```

Currently fails with:
```
2021-04-19T09:10:05.609-0500 SEVERE Failure cause:
java.lang.AssertionError: Could not find rows:
[0, 1]
[1, 1]
[2, 1]
[3, 1]
[4, 1]

actual rows:
[0, 5]
[1, 5]
[4, 5]
[3, 5]
[2, 5]
	at io.trino.tests.hive.TestHiveViews.lambda$testNestedGroupBy$5(TestHiveViews.java:155)
	at io.trino.tests.hive.AbstractTestHiveViews.assertViewQuery(AbstractTestHiveViews.java:353)
	at io.trino.tests.hive.TestHiveViews.testNestedGroupBy(TestHiveViews.java:153)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

2021-04-19T09:10:05.633-0500 INFO 

java.lang.AssertionError: Could not find rows:
[0, 1]
[1, 1]
[2, 1]
[3, 1]
[4, 1]

actual rows:
[0, 5]
[1, 5]
[4, 5]
[3, 5]
[2, 5]
```

**Comment by findepi** [comment]
Per https://github.com/linkedin/coral/issues/72#issuecomment-834114152 this can be solved by https://issues.apache.org/jira/browse/CALCITE-3466
