### ISSUE TITLE
Flaky testAuthenticationFromMultipleThreadsWithCachedTokenAfterAuthenticateFails

### ISSUE THREAD

**Issue by phd3** [trinodb/trino#7697]
looks related to https://github.com/trinodb/trino/pull/7309 

cc @kokosing 

```
2021-04-21T22:30:40.7188667Z [ERROR] testAuthenticationFromMultipleThreadsWithCachedTokenAfterAuthenticateFails(io.trino.client.auth.external.TestExternalAuthenticator)  Time elapsed: 0.041 s  <<< FAILURE!
2021-04-21T22:30:40.7194591Z java.lang.AssertionError: 
2021-04-21T22:30:40.7196333Z 
2021-04-21T22:30:40.7198414Z Expecting:
2021-04-21T22:30:40.7200903Z   <[null, null]>
2021-04-21T22:30:40.7205326Z to contain exactly (and in same order):
2021-04-21T22:30:40.7208317Z   <[null, null, null]>
2021-04-21T22:30:40.7212710Z but could not find the following elements:
2021-04-21T22:30:40.7214912Z   <[null]>
2021-04-21T22:30:40.7216169Z 
2021-04-21T22:30:40.7228404Z 	at io.trino.client.auth.external.TestExternalAuthenticator.testAuthenticationFromMultipleThreadsWithCachedTokenAfterAuthenticateFails(TestExternalAuthenticator.java:231)
2021-04-21T22:30:40.7235888Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-04-21T22:30:40.7239735Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-04-21T22:30:40.7243975Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-04-21T22:30:40.7247590Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-04-21T22:30:40.7255842Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-04-21T22:30:40.7258242Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2021-04-21T22:30:40.7260396Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2021-04-21T22:30:40.7262177Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-04-21T22:30:40.7265243Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-04-21T22:30:40.7267095Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-04-21T22:30:40.7271340Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-04-21T22:30:40.7272727Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-04-21T22:30:40.7273259Z 
2021-04-21T22:30:41.0564129Z [INFO] 
2021-04-21T22:30:41.0564983Z [INFO] Results:
2021-04-21T22:30:41.0565505Z [INFO] 
2021-04-21T22:30:41.0566059Z [ERROR] Failures: 
2021-04-21T22:30:41.0569385Z [ERROR]   TestExternalAuthenticator.testAuthenticationFromMultipleThreadsWithCachedTokenAfterAuthenticateFails:231 
2021-04-21T22:30:41.0572713Z Expecting:
2021-04-21T22:30:41.0573276Z   <[null, null]>
2021-04-21T22:30:41.0573912Z to contain exactly (and in same order):
2021-04-21T22:30:41.0574533Z   <[null, null, null]>
2021-04-21T22:30:41.0575207Z but could not find the following elements:
2021-04-21T22:30:41.0575859Z   <[null]>
```

**Comment by phd3** [comment]
failure instance: https://github.com/trinodb/trino/pull/7696/checks?check_run_id=2404900936

**Comment by kokosing** [comment]
Related to https://github.com/trinodb/trino/issues/7559

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/2422622744
