### ISSUE TITLE
Product test launcher is flaky (unable to delete not existing files)

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#7703]
```
2021-04-21T15:18:53.0449013Z java.nio.file.FileSystemException: /tmp/docker-files-265a7342-1546-4d00-a060-4460b66ed660: failed to delete one or more files; see suppressed exceptions for details
2021-04-21T15:18:53.0451052Z 	at com.google.common.io.MoreFiles.throwDeleteFailed(MoreFiles.java:786)
2021-04-21T15:18:53.0452787Z 	at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:552)
2021-04-21T15:18:53.0454842Z 	at io.trino.tests.product.launcher.docker.DockerFiles.close(DockerFiles.java:57)
2021-04-21T15:18:53.0456929Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-04-21T15:18:53.0459154Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-04-21T15:18:53.0461958Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-04-21T15:18:53.0463913Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-04-21T15:18:53.0465519Z 	at io.airlift.bootstrap.LifeCycleManager.stopInstance(LifeCycleManager.java:225)
2021-04-21T15:18:53.0467352Z 	at io.airlift.bootstrap.LifeCycleManager.stop(LifeCycleManager.java:193)
2021-04-21T15:18:53.0469014Z 	at io.airlift.bootstrap.LifeCycleManager.stop(LifeCycleManager.java:158)
2021-04-21T15:18:53.0470769Z 	at io.airlift.bootstrap.LifeCycleManager.lambda$start$0(LifeCycleManager.java:111)
2021-04-21T15:18:53.0472115Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-04-21T15:18:53.0473779Z 	Suppressed: java.nio.file.NoSuchFileException: docker-files-265a7342-1546-4d00-a060-4460b66ed660
2021-04-21T15:18:53.0475658Z 		at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
2021-04-21T15:18:53.0477473Z 		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
2021-04-21T15:18:53.0479247Z 		at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
2021-04-21T15:18:53.0481481Z 		at java.base/sun.nio.fs.UnixSecureDirectoryStream$BasicFileAttributeViewImpl.readAttributes(UnixSecureDirectoryStream.java:375)
2021-04-21T15:18:53.0483578Z 		at com.google.common.io.MoreFiles.isDirectory(MoreFiles.java:338)
2021-04-21T15:18:53.0485329Z 		at com.google.common.io.MoreFiles.deleteRecursivelySecure(MoreFiles.java:619)
2021-04-21T15:18:53.0487196Z 		at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:535)
2021-04-21T15:18:53.0488265Z 		... 10 more
```

**Comment by kokosing** [comment]
Even though all tests passed, job was marked as failed because of this.
