### ISSUE TITLE
Kudu grouped execution property cause exception when query a hive view over kudu table

### ISSUE THREAD

**Issue by lzeiming** [trinodb/trino#7738]
```
presto:ta> show create view v_user_318;
            Create View            
-----------------------------------
 CREATE VIEW hive.ta.v_user_318 AS 
 SELECT *                          
 FROM                              
   kudu.ta.ta_user_318    

presto:ta> set session kudu.grouped_execution=true;
SET SESSION 

presto:ta> select * from v_user_318 limit 5;
Query 20210425_085929_00029_drudx failed: bucketCount must be positive
java.lang.IllegalArgumentException: bucketCount must be positive
	at io.prestosql.spi.connector.ConnectorBucketNodeMap.<init>(ConnectorBucketNodeMap.java:41)
	at io.prestosql.spi.connector.ConnectorBucketNodeMap.createBucketNodeMap(ConnectorBucketNodeMap.java:30)
	at io.prestosql.plugin.kudu.KuduNodePartitioningProvider.getBucketNodeMap(KuduNodePartitioningProvider.java:67)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeNodePartitioningProvider.getBucketNodeMap(ClassLoaderSafeNodePartitioningProvider.java:72)
	at io.prestosql.sql.planner.NodePartitioningManager.getConnectorBucketNodeMap(NodePartitioningManager.java:208)
	at io.prestosql.sql.planner.NodePartitioningManager.getBucketNodeMap(NodePartitioningManager.java:175)
	at io.prestosql.execution.scheduler.SqlQueryScheduler.createStages(SqlQueryScheduler.java:410)
	at io.prestosql.execution.scheduler.SqlQueryScheduler.lambda$createStages$9(SqlQueryScheduler.java:320)
	at io.prestosql.execution.scheduler.SqlQueryScheduler.createStages(SqlQueryScheduler.java:455)
	at io.prestosql.execution.scheduler.SqlQueryScheduler.<init>(SqlQueryScheduler.java:197)
	at io.prestosql.execution.scheduler.SqlQueryScheduler.createSqlQueryScheduler(SqlQueryScheduler.java:144)
	at io.prestosql.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:492)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:385)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:245)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:139)
	at io.prestosql.$gen.Presto_unknown____20210425_073318_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

After reviewing the code, I find when isKuduGroupedExecutionEnabled(session) == true, the count should be positive.
The issue exists because We query a hive view over a kudu table. If we query the Kudu table directly, the issue does not exist.
The cause is that in StatementAnalyzer.createViewSession(), connectorProperties are not copied from the original session.

Then with the view session a KuduTableHandle with empty bucketCount is created in KuduMetaData.getTableHandle(). Later with the original session the KuduTableHandle is used to create a KuduPartitioningHandle with zero bucketCount in KuduMetaData.getTableProperties() and cause the exception.

**Comment by Praveen2112** [comment]
Fixed by #7745
