### ISSUE TITLE
Flaky TestFullParquetReader.testFloatNaNInfinity

### ISSUE THREAD

**Issue by martint** [trinodb/trino#7753]
```
Error:  testFloatNaNInfinity(io.trino.plugin.hive.parquet.TestFullParquetReader)  Time elapsed: 1.036 s  <<< FAILURE!
java.lang.IllegalArgumentException: maxCapacityHint can't be less than initialSlabSize 1024 100
	at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:53)
	at org.apache.parquet.bytes.CapacityByteArrayOutputStream.<init>(CapacityByteArrayOutputStream.java:153)
	at org.apache.parquet.column.values.plain.PlainValuesWriter.<init>(PlainValuesWriter.java:47)
	at org.apache.parquet.column.values.factory.DefaultV2ValuesWriterFactory.getFloatValuesWriter(DefaultV2ValuesWriterFactory.java:112)
	at org.apache.parquet.column.values.factory.DefaultV2ValuesWriterFactory.newValuesWriter(DefaultV2ValuesWriterFactory.java:70)
	at org.apache.parquet.column.values.factory.DefaultValuesWriterFactory.newValuesWriter(DefaultValuesWriterFactory.java:52)
	at org.apache.parquet.column.ParquetProperties.newValuesWriter(ParquetProperties.java:149)
	at org.apache.parquet.column.impl.ColumnWriterBase.<init>(ColumnWriterBase.java:66)
	at org.apache.parquet.column.impl.ColumnWriterV2.<init>(ColumnWriterV2.java:59)
	at org.apache.parquet.column.impl.ColumnWriteStoreV2.createColumnWriter(ColumnWriteStoreV2.java:35)
	at org.apache.parquet.column.impl.ColumnWriteStoreBase.<init>(ColumnWriteStoreBase.java:94)
	at org.apache.parquet.column.impl.ColumnWriteStoreV2.<init>(ColumnWriteStoreV2.java:30)
	at org.apache.parquet.column.ParquetProperties.newColumnWriteStore(ParquetProperties.java:182)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:106)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:96)
	at org.apache.parquet.hadoop.ParquetRecordWriter.<init>(ParquetRecordWriter.java:153)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:487)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:416)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:411)
	at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.<init>(ParquetRecordWriterWrapper.java:70)
	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getParquerRecordWriterWrapper(MapredParquetOutputFormat.java:137)
	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getHiveRecordWriter(MapredParquetOutputFormat.java:126)
	at io.trino.plugin.hive.parquet.write.TestMapredParquetOutputFormat.getHiveRecordWriter(TestMapredParquetOutputFormat.java:64)
	at io.trino.plugin.hive.parquet.ParquetTester.writeParquetColumn(ParquetTester.java:584)
	at io.trino.plugin.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:323)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:281)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:203)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:178)
	at io.trino.plugin.hive.parquet.AbstractTestParquetReader.testFloatNaNInfinity(AbstractTestParquetReader.java:1475)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sopel39** [comment]
https://github.com/trinodb/trino/pull/9275/checks?check_run_id=3685232306
