### ISSUE TITLE
Flaky test TestCassandraConnectorTest.testDropColumn

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#7755]
https://github.com/trinodb/trino/runs/2442277021

```
2021-04-26T21:00:39.4265693Z [ERROR] testDropColumn(io.trino.plugin.cassandra.TestCassandraConnectorTest)  Time elapsed: 0.619 s  <<< FAILURE!
2021-04-26T21:00:39.4267608Z java.lang.AssertionError: 
2021-04-26T21:00:39.4268270Z 
2021-04-26T21:00:39.4268997Z Expecting message to be:
2021-04-26T21:00:39.4269625Z   <"This connector does not support dropping columns">
2021-04-26T21:00:39.4270213Z but was:
2021-04-26T21:00:39.4271625Z   <"An unexpected error occurred server side on localhost/0:0:0:0:0:0:0:1:49155: java.lang.AssertionError: Unknown keyspace keyspace_5">
2021-04-26T21:00:39.4272383Z 
2021-04-26T21:00:39.4273955Z Throwable that failed the check:
2021-04-26T21:00:39.4274301Z 
2021-04-26T21:00:39.4278917Z java.lang.RuntimeException: An unexpected error occurred server side on localhost/0:0:0:0:0:0:0:1:49155: java.lang.AssertionError: Unknown keyspace keyspace_5
2021-04-26T21:00:39.4281205Z 	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:120)
2021-04-26T21:00:39.4288972Z 	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:476)
2021-04-26T21:00:39.4290781Z 	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
2021-04-26T21:00:39.4293008Z 	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:235)
2021-04-26T21:00:39.4295832Z 	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:230)
2021-04-26T21:00:39.4298974Z 	at io.trino.testing.AbstractTestDistributedQueries.testDropColumn(AbstractTestDistributedQueries.java:438)
2021-04-26T21:00:39.4301972Z 	at io.trino.plugin.cassandra.TestCassandraConnectorTest.lambda$testDropColumn$3(TestCassandraConnectorTest.java:189)
2021-04-26T21:00:39.4304588Z 	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
2021-04-26T21:00:39.4306829Z 	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:877)
2021-04-26T21:00:39.4309040Z 	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1306)
2021-04-26T21:00:39.4310820Z 	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1178)
2021-04-26T21:00:39.4313415Z 	at io.trino.plugin.cassandra.TestCassandraConnectorTest.testDropColumn(TestCassandraConnectorTest.java:189)
2021-04-26T21:00:39.4315972Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-04-26T21:00:39.4318297Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-04-26T21:00:39.4321400Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-04-26T21:00:39.4323288Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-04-26T21:00:39.4325357Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-04-26T21:00:39.4327455Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-04-26T21:00:39.4329075Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-04-26T21:00:39.4330604Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-04-26T21:00:39.4332558Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-04-26T21:00:39.4334661Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-04-26T21:00:39.4337453Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-04-26T21:00:39.4362918Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-04-26T21:00:39.4365582Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-04-26T21:00:39.4376995Z 	Suppressed: java.lang.Exception: SQL: CREATE TABLE test_drop_column_1m83x AS SELECT 123 x, 456 y, 111 a
2021-04-26T21:00:39.4378639Z 		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:479)
2021-04-26T21:00:39.4379843Z 		... 23 more
2021-04-26T21:00:39.4381260Z Caused by: com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on localhost/0:0:0:0:0:0:0:1:49155: java.lang.AssertionError: Unknown keyspace keyspace_5
2021-04-26T21:00:39.4383516Z 	at com.datastax.driver.core.exceptions.ServerError.copy(ServerError.java:63)
2021-04-26T21:00:39.4385284Z 	at com.datastax.driver.core.exceptions.ServerError.copy(ServerError.java:25)
2021-04-26T21:00:39.4387218Z 	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
2021-04-26T21:00:39.4389834Z 	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
2021-04-26T21:00:39.4392197Z 	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
2021-04-26T21:00:39.4393867Z 	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:43)
2021-04-26T21:00:39.4395769Z 	at io.trino.plugin.cassandra.CassandraSession.lambda$execute$11(CassandraSession.java:432)
2021-04-26T21:00:39.4398026Z 	at io.trino.plugin.cassandra.CassandraSession.executeWithSession(CassandraSession.java:538)
2021-04-26T21:00:39.4400064Z 	at io.trino.plugin.cassandra.CassandraSession.execute(CassandraSession.java:432)
2021-04-26T21:00:39.4401982Z 	at io.trino.plugin.cassandra.CassandraMetadata.createTable(CassandraMetadata.java:313)
2021-04-26T21:00:39.4404329Z 	at io.trino.plugin.cassandra.CassandraMetadata.beginCreateTable(CassandraMetadata.java:277)
2021-04-26T21:00:39.4406524Z 	at io.trino.metadata.MetadataManager.beginCreateTable(MetadataManager.java:868)
2021-04-26T21:00:39.4410880Z 	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:208)
2021-04-26T21:00:39.4413334Z 	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:159)
2021-04-26T21:00:39.4418479Z 	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:78)
2021-04-26T21:00:39.4420978Z 	at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
2021-04-26T21:00:39.4423106Z 	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
2021-04-26T21:00:39.4425209Z 	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
2021-04-26T21:00:39.4427061Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
2021-04-26T21:00:39.4428511Z 	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
2021-04-26T21:00:39.4429907Z 	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
2021-04-26T21:00:39.4431466Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2021-04-26T21:00:39.4433284Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-04-26T21:00:39.4435150Z 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
2021-04-26T21:00:39.4436856Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-04-26T21:00:39.4438798Z 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
2021-04-26T21:00:39.4440960Z 	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
2021-04-26T21:00:39.4443208Z 	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
2021-04-26T21:00:39.4445812Z 	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
2021-04-26T21:00:39.4447845Z 	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
2021-04-26T21:00:39.4449800Z 	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
2021-04-26T21:00:39.4451639Z 	at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
2021-04-26T21:00:39.4454868Z 	at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:75)
2021-04-26T21:00:39.4457573Z 	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:208)
2021-04-26T21:00:39.4459385Z 	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:197)
2021-04-26T21:00:39.4460839Z 	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:192)
2021-04-26T21:00:39.4462477Z 	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:482)
2021-04-26T21:00:39.4464300Z 	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:462)
2021-04-26T21:00:39.4466163Z 	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:405)
2021-04-26T21:00:39.4467994Z 	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
2021-04-26T21:00:39.4469820Z 	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
2021-04-26T21:00:39.4471179Z 	at io.trino.$gen.Trino_testversion____20210426_205455_3.run(Unknown Source)
2021-04-26T21:00:39.4472595Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-04-26T21:00:39.4474600Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-04-26T21:00:39.4475886Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-04-26T21:00:39.4477701Z Caused by: com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on localhost/0:0:0:0:0:0:0:1:49155: java.lang.AssertionError: Unknown keyspace keyspace_5
2021-04-26T21:00:39.4479632Z 	at com.datastax.driver.core.Responses$Error.asException(Responses.java:108)
2021-04-26T21:00:39.4481226Z 	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:506)
2021-04-26T21:00:39.4483082Z 	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1070)
2021-04-26T21:00:39.4484669Z 	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:993)
2021-04-26T21:00:39.4486809Z 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
2021-04-26T21:00:39.4490966Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-04-26T21:00:40.2574101Z 2021-04-26T16:00:39.189-0500 SEVERE [Control connection] Cannot connect to any host, scheduling retry in 2000 milliseconds
2021-04-26T21:00:40.2576903Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-04-26T21:00:40.2580053Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
2021-04-26T21:00:40.2583024Z 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
2021-04-26T21:00:40.2585671Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-04-26T21:00:40.2590083Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-04-26T21:00:40.2593148Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
2021-04-26T21:00:40.2595958Z 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
2021-04-26T21:00:40.2598767Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-04-26T21:00:40.2601857Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-04-26T21:00:40.2604906Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
2021-04-26T21:00:40.2607646Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
2021-04-26T21:00:40.2610329Z 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
2021-04-26T21:00:40.2613024Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-04-26T21:00:40.2616115Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-04-26T21:00:40.2619151Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
2021-04-26T21:00:40.2621641Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1280)
2021-04-26T21:00:40.2624202Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-04-26T21:00:40.2627285Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-04-26T21:00:40.2630022Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:890)
2021-04-26T21:00:40.2632234Z 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
2021-04-26T21:00:40.2634197Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564)
2021-04-26T21:00:40.2636389Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505)
2021-04-26T21:00:40.2638588Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419)
2021-04-26T21:00:40.2640213Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
2021-04-26T21:00:40.2644649Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
2021-04-26T21:00:40.2646982Z 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
2021-04-26T21:00:40.2648487Z 	... 1 more
2021-04-26T21:00:40.2648714Z 
2021-04-26T21:00:40.2650457Z 	at io.trino.plugin.cassandra.TestCassandraConnectorTest.testDropColumn(TestCassandraConnectorTest.java:189)
2021-04-26T21:00:40.2653040Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-04-26T21:00:40.2655203Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-04-26T21:00:40.2657754Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-04-26T21:00:40.2659634Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-04-26T21:00:40.2661565Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-04-26T21:00:40.2663424Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-04-26T21:00:40.2665069Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-04-26T21:00:40.2666562Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-04-26T21:00:40.2668410Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-04-26T21:00:40.2670245Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-04-26T21:00:40.2672117Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-04-26T21:00:40.2674053Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-04-26T21:00:40.2675420Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ebyhr** [comment]
Let me close because I don't see the failure for a long time. Please feel free to reopen if it happens again.
