### ISSUE TITLE
presto worker not getting added using password authenticator

### ISSUE THREAD

**Issue by datta90** [trinodb/trino#7767]
i am trying to add presto worker after enabling TLS .
Using prestosql version 350

my config properties on worker node
coordinator=false
query.max-memory=15GB
query.max-memory-per-node=5GB
query.max-total-memory-per-node=10GB
query.initial-hash-partitions=10
discovery.uri=https://10.128.xx.xx:8084
internal-communication.https.required=true
internal-communication.shared-secret=cxcddfsffs
node.internal-address=10.128.xx.xx
internal-communication.https.keystore.path=/home/presto/certs/finalkeystore.jks
internal-communication.https.keystore.key=AAAA
http-server.http.enabled=false

node properties
ode.environment=rrasandbox
node.id=6c06ed66-a696-11eb-a8f2-3cd92b05d4c2
node.data-dir=/home/presto/data350
node.launcher-log-file=/home/presto/logs350/launcher.log
node.server-log-file=/home/presto/logs350/server.log

while trying to run launcher run i am getting this error

 Error injecting constructor, java.lang.IllegalStateException: INVARIANT: current node not returned from service selector
  at io.prestosql.metadata.DiscoveryNodeManager.<init>(DiscoveryNodeManager.java:104)
  at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
  while locating io.prestosql.metadata.DiscoveryNodeManager
  at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
  while locating io.prestosql.metadata.InternalNodeManager
    for the 1st parameter of io.prestosql.execution.scheduler.UniformNodeSelectorFactory.<init>(UniformNodeSelectorFactory.java:69)
  while locating io.prestosql.execution.scheduler.UniformNodeSelectorFactory
  at io.prestosql.execution.scheduler.UniformNodeSelectorModule.configure(UniformNodeSelectorModule.java:26) (via modules: io.prestosql.server.ServerMainModule -> io.airlift.configuration.ConditionalModule -> io.prestosql.execution.scheduler.UniformNodeSelectorModule)
  while locating io.prestosql.execution.scheduler.NodeSelectorFactory

**Comment by datta90** [comment]
solved this by adding below properties in worker
http-server.https.enabled=true
http-server.https.port=8084
http-server.https.keystore.path=<path>
http-server.https.keystore.key=AAAA
