### ISSUE TITLE
LocalQueryRunner cannot CTAS from Hive table

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#7778]
`LocalQueryRunner` does not support `CREATE TABLE`, only `CREATE TABLE AS`

When doing `CREATE TABLE AS` from Hive (non-transactional) table into a Hive table

```
java.lang.IllegalStateException: Invalid query id 20210428_101423_00000_9i2tu while current query is [Optional.empty]

	at com.google.common.base.Preconditions.checkState(Preconditions.java:826)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.getValidWriteIds(SemiTransactionalHiveMetastore.java:1288)
	at io.trino.plugin.hive.HiveSplitManager.getSplits(HiveSplitManager.java:243)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorSplitManager.getSplits(ClassLoaderSafeConnectorSplitManager.java:74)
	at io.trino.split.SplitManager.getSplits(SplitManager.java:86)
	at io.trino.testing.LocalQueryRunner.createDrivers(LocalQueryRunner.java:788)
	at io.trino.testing.LocalQueryRunner.executeInternal(LocalQueryRunner.java:681)
	at io.trino.testing.LocalQueryRunner.lambda$executeWithPlan$4(LocalQueryRunner.java:649)
	at io.trino.transaction.TransactionBuilder.execute(TransactionBuilder.java:150)
	at io.trino.testing.LocalQueryRunner.inTransaction(LocalQueryRunner.java:661)
	at io.trino.testing.LocalQueryRunner.executeWithPlan(LocalQueryRunner.java:649)
	at io.trino.testing.LocalQueryRunner.execute(LocalQueryRunner.java:643)
	at io.trino.testing.LocalQueryRunner.execute(LocalQueryRunner.java:637)
```

this limitation makes writing tests harder.

**Comment by kokosing** [comment]
Is this because that `LocalQueryRunner` does not support running DDL statements?
We know that `LocalQueryRunner` is limited and so once I proposed: https://github.com/trinodb/trino/pull/4456

**Comment by findepi** [comment]
> Is this because that `LocalQueryRunner` does not support running DDL statements?

CTAS is supported, e.g. from VALUES, so this is something more subtle

> We know that LocalQueryRunner is limited and so once I proposed: #4456

`BasePlanTest` relies on `LocalQueryRunner`. If we could change that, that would be even better.

**Comment by damnMeddlingKid** [comment]
I believe this happens whenever the plan has a tableScanNode. Those plans access the split manager to get splits which calls `getValidWriteIds` here https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java#L1351 and fails.
