### ISSUE TITLE
OAuth2 with Keycloak not working

### ISSUE THREAD

**Issue by ricosega** [trinodb/trino#7788]
Hi there,

Just followed the [documentation](https://trino.io/docs/current/security/oauth2.html) but the coordinator node does not work.
This is the configuration options I used:
```
http-server.authentication.type=oauth2
http-server.authentication.oauth2.auth-url=https://keycloak.local/auth/realms/master/protocol/openid-connect/auth
http-server.authentication.oauth2.token-url=https://keycloak.local/auth/realms/master/protocol/openid-connect/token
http-server.authentication.oauth2.jwks-url=https://keycloak.local/auth/realms/master/protocol/openid-connect/certs
http-server.authentication.oauth2.client-id=trinodb
http-server.authentication.oauth2.client-secret=SECRET
web-ui.authentication.type=oauth2
```
And this is the error output I get:
```
11) [Guice/ErrorInCustomProvider]: RuntimeException: Error reading JWK keys from https://keycloak.local/auth/realms/master/protocol/openid-connect/certs
  at OAuth2ServiceModule.createSigningKeyResolver(OAuth2ServiceModule.java:60)
      \_ installed by: ServerSecurityModule -> ConditionalModule -> ConfigurationAwareModule$1 -> OAuth2AuthenticationSupportModule -> OAuth2ServiceModule
  at OAuth2Service.<init>(OAuth2Service.java:73)
      \_ for 2nd parameter signingKeyResolver
  at GeneratedMethodAccessor27.invoke(Unknown Source)
      \_ installed by: ServerSecurityModule -> ConditionalModule -> ConfigurationAwareModule$1 -> OAuth2AuthenticationSupportModule -> OAuth2ServiceModule
  while locating OAuth2Service

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER
Caused by: RuntimeException: Error reading JWK keys from https://keycloak.local/auth/realms/master/protocol/openid-connect/certs
        at JwkService.fetchKeys(JwkService.java:140)
        at JwkService.<init>(JwkService.java:69)
        at OAuth2ServiceModule.createSigningKeyResolver(OAuth2ServiceModule.java:60)
        at OAuth2ServiceModule$$FastClassByGuice$$5077256.GUICE$TRAMPOLINE(<generated>)
        at OAuth2ServiceModule$$FastClassByGuice$$5077256.apply(<generated>)
        at ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
        at ProviderMethod.doProvision(ProviderMethod.java:171)
        at InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at InternalProviderInstanceBindingImpl$CyclicFactory.access$300(InternalProviderInstanceBindingImpl.java:139)
        at InternalProviderInstanceBindingImpl$CyclicFactory$1.call(InternalProviderInstanceBindingImpl.java:169)
        at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at LifeCycleModule.provision(LifeCycleModule.java:54)
        at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:164)
        at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at SingletonScope$1.get(SingletonScope.java:169)
        at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at SingleParameterInjector.inject(SingleParameterInjector.java:40)
        at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
        at ConstructorInjector.provision(ConstructorInjector.java:113)
        at ConstructorInjector.access$000(ConstructorInjector.java:33)
        at ConstructorInjector$1.call(ConstructorInjector.java:98)
        at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at LifeCycleModule.provision(LifeCycleModule.java:54)
        at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at ConstructorInjector.construct(ConstructorInjector.java:93)
        at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
        at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at SingletonScope$1.get(SingletonScope.java:169)
        at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
        at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
        at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
        at Guice.createInjector(Guice.java:87)
        at Bootstrap.initialize(Bootstrap.java:276)
        at Server.doStart(Server.java:115)
        at Server.lambda$start$0(Server.java:77)
        at io.trino.$gen.Trino_355____20210428_174146_1.run(Unknown Source)
        at Server.start(Server.java:77)
        at TrinoServer.main(TrinoServer.java:38)
Caused by: UncheckedIOException: SSLHandshakeException: PKIX path building failed: SunCertPathBuilderException: unable to find valid certification path to requested target
        at ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:21)
        at StringResponseHandler.handleException(StringResponseHandler.java:51)
        at StringResponseHandler.handleException(StringResponseHandler.java:34)
        at JettyHttpClient.execute(JettyHttpClient.java:532)
        at JwkService.fetchKeys(JwkService.java:137)
        ... 41 more
Caused by: SSLHandshakeException: PKIX path building failed: SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/Alert.createSSLException(Alert.java:131)
        at java.base/TransportContext.fatal(TransportContext.java:349)
        at java.base/TransportContext.fatal(TransportContext.java:292)
        at java.base/TransportContext.fatal(TransportContext.java:287)
        at java.base/CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1356)
        at java.base/CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1231)
        at java.base/CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1174)
        at java.base/SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
        at java.base/SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
        at java.base/AccessController.doPrivileged(Native Method)
        at java.base/SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
        at SslConnection$DecryptedEndPoint.fill(SslConnection.java:639)
        at SslConnection$DecryptedEndPoint.flush(SslConnection.java:1028)
        at WriteFlusher.flush(WriteFlusher.java:422)
        at WriteFlusher.completeWrite(WriteFlusher.java:378)
        at SslConnection$DecryptedEndPoint.lambda$fill$1(SslConnection.java:813)
        at QueuedThreadPool.runJob(QueuedThreadPool.java:882)
        at QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
        at java.base/Thread.run(Thread.java:834)
Caused by: ValidatorException: PKIX path building failed: SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/Validator.validate(Validator.java:264)
        at java.base/X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
        at java.base/X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
        at java.base/CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1334)
        ... 16 more
Caused by: SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 22 more
```
Any idea?

**Comment by lukasz-walkiewicz** [comment]
Hi @ricosega,

It looks like you're trying to use a Keycloak server with a self-signed certificate.
In order to make this work you have to import the certificate to a truststore and configure the JWK client to use it:
`oauth2-jwk.http-client.trust-store-path=<path-to-the-truststore>`

**Comment by ricosega** [comment]
Hi @lukasz-walkiewicz , 
I am using the latest trino docker image in kubernetes, would it be possible to add the self-signed certificate somewhere inside the container and avoid this messages?

**Comment by lukasz-walkiewicz** [comment]
You can use docker volumes (https://docs.docker.com/storage/volumes/) for it. e.g.
```bash
docker run -p 8080:8080 -v /path/to/the-truststore:/tmp/truststore.jks --name trino trinodb/trino
```
