### ISSUE TITLE
Trino with Hive using SSL

### ISSUE THREAD

**Issue by l1x** [trinodb/trino#7836]
I am trying to connect to a Hive metastore with Thrift + SSL the following way:

```
connector.name=hive-hadoop2
hive.metastore.uri=thrift://server:port

hive.metastore.thrift.client.ssl.enabled=true
hive.metastore.thrift.client.ssl.trust-certificate=/opt/ssl_truststore
hive.metastore.thrift.client.ssl.trust-certificate-password=super-secret
```

Unfortunately it throws the following exception:

```
io.trino.spi.TrinoException: hive-meta.bigdata.e2de.pbrz.eu:9083: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getAllDatabases(ThriftHiveMetastore.java:265)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.getAllDatabases(BridgingHiveMetastore.java:90)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadAllDatabases(CachingHiveMetastore.java:298)
	at com.google.common.cache.CacheLoader$SupplierToCacheLoader.load(CacheLoader.java:227)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4952)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:259)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getAllDatabases(CachingHiveMetastore.java:293)
	at io.trino.plugin.hive.HiveMetastoreClosure.getAllDatabases(HiveMetastoreClosure.java:65)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.getAllDatabases(SemiTransactionalHiveMetastore.java:183)
	at io.trino.plugin.hive.HiveMetadata.listSchemaNames(HiveMetadata.java:374)
	at io.trino.spi.connector.ConnectorMetadata.schemaExists(ConnectorMetadata.java:56)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.schemaExists(ClassLoaderSafeConnectorMetadata.java:186)
	at io.trino.metadata.MetadataManager.lambda$schemaExists$0(MetadataManager.java:312)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at io.trino.metadata.MetadataManager.schemaExists(MetadataManager.java:312)
	at io.trino.execution.UseTask.execute(UseTask.java:68)
	at io.trino.execution.UseTask.execute(UseTask.java:35)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:170)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_355____20210503_181144_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.thrift.transport.TTransportException: hive-meta.bigdata.e2de.pbrz.eu:9083: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at io.trino.plugin.hive.metastore.thrift.Transport.rewriteException(Transport.java:96)
	at io.trino.plugin.hive.metastore.thrift.Transport$TTransportWrapper.flush(Transport.java:221)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.send_get_all_databases(ThriftHiveMetastore.java:1230)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_all_databases(ThriftHiveMetastore.java:1223)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.getAllDatabases(ThriftHiveMetastoreClient.java:116)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.runWithHandle(FailureAwareThriftMetastoreClient.java:447)
	at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.getAllDatabases(FailureAwareThriftMetastoreClient.java:76)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$getAllDatabases$0(ThriftHiveMetastore.java:260)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
	at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getAllDatabases(ThriftHiveMetastore.ja
```

Does anybody know what the issue might be?

**Comment by losipiuk** [comment]
It seems like the endpoint you are connecting to is not talking valid TLS protocol. But error messages can be misleading here. @electrum can you chime in here; you implemented the feature.

**Comment by l1x** [comment]
I think this is happening because of trying to connect to a non-SSL service.
