### ISSUE TITLE
SSL certificates/keys are not properly resolved

### ISSUE THREAD

**Issue by lukasz-walkiewicz** [trinodb/trino#7845]
Trino cannot resolve certificates and/or keys (which are correct, valid and have SAN extensions matching hostnames) when a keystore contains multiple entries, for example: when using the same keystore for all of the nodes but each node uses its own certificate. What's interesting cluster works perfectly fine for a short period of time after the start.

My initial diagnosis is that it's caused by the SSL context reloading which is run on a fixed schedule ([https://github.com/airlift/airlift/blob/master/http-server/src/main/java/io/airlift/http/server/ReloadableSslContextFactoryProvider.java](https://github.com/airlift/airlift/blob/master/http-server/src/main/java/io/airlift/http/server/ReloadableSslContextFactoryProvider.java)). 

I've created a PR [https://github.com/trinodb/trino/pull/7844](https://github.com/trinodb/trino/pull/7844) with a keystore using a dedicated certificate for each node in product tests. The PR contains also the workaround: refresh schedule which effectively disables the SSL context reloading.

Stacktrace of the error:
```
presto-master       | io.trino.server.remotetask.RequestErrorTracker	Error getting task status 20210506_140524_00060_zk2kw.1.1: https://presto-worker-1.docker.cluster:7778/v1/task/20210506_140524_00060_zk2kw.1.1
presto-master       | java.io.UncheckedIOException: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching presto-worker-1.docker.cluster found.
presto-master       | 	at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:21)
presto-master       | 	at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58)
presto-master       | 	at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:38)
presto-master       | 	at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:120)
presto-master       | 	at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:85)
presto-master       | 	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
presto-master       | 	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
presto-master       | 	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481)
presto-master       | 	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461)
presto-master       | 	at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:557)
presto-master       | 	at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
presto-master       | 	at org.eclipse.jetty.client.HttpSender.terminateRequest(HttpSender.java:397)
presto-master       | 	at org.eclipse.jetty.client.HttpSender.abort(HttpSender.java:574)
presto-master       | 	at org.eclipse.jetty.client.HttpSender.lambda$executeAbort$0(HttpSender.java:361)
presto-master       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
presto-master       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
presto-master       | 	at java.base/java.lang.Thread.run(Thread.java:834)
presto-master       | Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching presto-worker-1.docker.cluster found.
presto-master       | 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
presto-master       | 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
presto-master       | 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
presto-master       | 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
presto-master       | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1339)
presto-master       | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1214)
presto-master       | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1157)
presto-master       | 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
presto-master       | 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
presto-master       | 	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
presto-master       | 	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1048)
presto-master       | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
presto-master       | 	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:995)
presto-master       | 	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:639)
presto-master       | 	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1028)
presto-master       | 	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)
presto-master       | 	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:378)
presto-master       | 	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.lambda$fill$1(SslConnection.java:813)
presto-master       | 	... 3 more
presto-master       | Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching presto-worker-1.docker.cluster found.
presto-master       | 	at java.base/sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:207)
presto-master       | 	at java.base/sun.security.util.HostnameChecker.match(HostnameChecker.java:98)
presto-master       | 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
presto-master       | 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:415)
presto-master       | 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:283)
presto-master       | 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
presto-master       | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1317)
presto-master       | 	... 16 more
```

Content of the keystore:
```
Enter keystore password:
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 4 entries

Alias name: presto-master
Creation date: May 5, 2021
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=presto-master.docker.cluster, OU=, O=, L=, ST=, C=
Issuer: CN=presto-master.docker.cluster, OU=, O=, L=, ST=, C=
Serial number: 50e245a5
Valid from: Wed May 05 12:15:27 CEST 2021 until: Fri Apr 11 12:15:27 CEST 2121
Certificate fingerprints:
	 SHA1: 1A:24:43:9D:4B:08:8D:F1:04:BE:FD:05:A6:B7:3C:1F:1A:DD:81:55
	 SHA256: 97:EB:7F:ED:94:D4:CC:B8:FE:64:15:1C:ED:62:82:75:63:67:03:50:40:3D:3D:B5:C3:E8:C5:43:B6:D9:C1:C6
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions:

#1: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: presto-master.docker.cluster
]

#2: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: E5 D3 21 B4 B4 9B E7 A6   6B 48 E3 ED 93 00 DA FF  ..!.....kH......
0010: 56 3F C6 AE                                        V?..
]
]



*******************************************
*******************************************


Alias name: presto-worker
Creation date: May 6, 2021
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=presto-worker.docker.cluster, OU=, O=, L=, ST=, C=
Issuer: CN=presto-worker.docker.cluster, OU=, O=, L=, ST=, C=
Serial number: d7701a4
Valid from: Thu May 06 14:21:27 CEST 2021 until: Sat Apr 12 14:21:27 CEST 2121
Certificate fingerprints:
	 SHA1: 68:76:1E:7B:E1:12:24:B5:2C:7A:89:52:1A:CC:7A:CC:75:36:FA:FF
	 SHA256: EE:9D:38:A4:53:2B:47:11:0C:D3:07:50:98:FD:4C:6F:C2:5F:8E:AA:57:5E:BD:1F:12:BF:0E:E9:C1:1E:BF:D7
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions:

#1: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: presto-worker.docker.cluster
]

#2: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: BC D3 BE AD 5D 79 A4 19   C8 4D A8 C8 6B 6B CB 49  ....]y...M..kk.I
0010: 54 F3 9D 87                                        T...
]
]



*******************************************
*******************************************


Alias name: presto-worker-1
Creation date: May 5, 2021
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=presto-worker-1.docker.cluster, OU=, O=, L=, ST=, C=
Issuer: CN=presto-worker-1.docker.cluster, OU=, O=, L=, ST=, C=
Serial number: 30e0567
Valid from: Wed May 05 12:16:47 CEST 2021 until: Fri Apr 11 12:16:47 CEST 2121
Certificate fingerprints:
	 SHA1: 3D:B1:D8:25:93:CC:38:CF:17:D4:A8:35:5C:B2:97:C6:44:D5:7C:21
	 SHA256: B0:0F:DA:33:3A:18:72:55:8F:85:EB:48:87:F0:F4:E7:CA:9D:5C:6A:BB:05:B6:81:BD:D9:E5:CF:88:22:BE:73
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions:

#1: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: presto-worker-1.docker.cluster
]

#2: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 50 3F 7F B9 1E 85 6B E5   E7 8E C6 56 FD B8 A7 A1  P?....k....V....
0010: 6D 41 E8 06                                        mA..
]
]



*******************************************
*******************************************


Alias name: presto-worker-2
Creation date: May 5, 2021
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=presto-worker-2.docker.cluster, OU=, O=, L=, ST=, C=
Issuer: CN=presto-worker-2.docker.cluster, OU=, O=, L=, ST=, C=
Serial number: 7d4bd8a
Valid from: Wed May 05 12:16:59 CEST 2021 until: Fri Apr 11 12:16:59 CEST 2121
Certificate fingerprints:
	 SHA1: 19:10:BC:94:28:E7:56:BC:25:6F:B7:D8:40:F7:6D:5C:01:99:CC:4B
	 SHA256: ED:FF:CF:7D:19:97:36:8E:0B:EF:5A:52:E9:E5:AE:F5:88:6E:E5:4F:BD:C1:18:C4:CD:A1:F3:FD:9E:3E:3C:BE
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions:

#1: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: presto-worker-2.docker.cluster
]

#2: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 8E E6 4F 14 B5 AB EB B2   84 FA B9 79 55 CC 0D A6  ..O........yU...
0010: CC 56 8C 18                                        .V..
]
]



*******************************************
*******************************************
```

**Comment by hashhar** [comment]
since this was fixed upstream in https://github.com/airlift/airlift/pull/915 is it now time to revert this?
