### ISSUE TITLE
Unable to set `hive.s3.iam-role` with `hive.s3-file-system-type = EMRFS` 

### ISSUE THREAD

**Issue by npow** [trinodb/trino#7866]
I am trying to set `hive.s3.iam-role` according to the [docs](https://trino.io/docs/current/connector/hive-s3.html), but am getting a configuration error. I am using version `356` of trino-server. Are there some other configuration changes needed to make this work? I also tried setting `hive.s3.aws-access-key` and `hive.s3.aws-secret-key` and got the same "property was not used" error. 

```
2021-05-08T19:10:15.687Z        INFO    main    io.trino.metadata.StaticCatalogStore    -- Loading catalog etc/catalog/hive.properties --
2021-05-08T19:10:16.315Z        ERROR   main    io.trino.server.Server  Configuration errors:

1) Error: Configuration property 'hive.s3.iam-role' was not used

1 error
io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Configuration property 'hive.s3.iam-role' was not used

1 error
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:239)
        at io.trino.plugin.hive.InternalHiveConnectorFactory.createConnector(InternalHiveConnectorFactory.java:122)
        at io.trino.plugin.hive.InternalHiveConnectorFactory.createConnector(InternalHiveConnectorFactory.java:80)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.trino.plugin.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:63)
        at io.trino.connector.ConnectorManager.createConnector(ConnectorManager.java:361)
        at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:216)
        at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:208)
        at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:194)
        at io.trino.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
        at io.trino.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
        at io.trino.server.Server.doStart(Server.java:123)
        at io.trino.server.Server.lambda$start$0(Server.java:77)
        at io.trino.$gen.Trino_356____20210508_191008_1.run(Unknown Source)
        at io.trino.server.Server.start(Server.java:77)
        at io.trino.server.TrinoServer.main(TrinoServer.java:38)
```

**Comment by jkaufman5** [comment]
Is there a way to set (in the AWS console's node configuration) the `hive.s3.iam-role` with an EMR cluster for Trino?
