### ISSUE TITLE
Flaky TestSqlServerTypeMapping: "Transaction was deadlocked ... and has been chosen as the deadlock victim"

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#7872]
```
2021-05-09T11:29:42.9038391Z [ERROR] init(io.trino.plugin.sqlserver.TestSqlServerTypeMapping)  Time elapsed: 2.698 s  <<< FAILURE!
2021-05-09T11:29:42.9040757Z java.lang.RuntimeException: Failed to execute statement: ALTER DATABASE database_6dfc467e1fca49b3b1e222cf5b22d97b SET READ_COMMITTED_SNAPSHOT ON
2021-05-09T11:29:42.9043000Z 	at io.trino.plugin.sqlserver.TestingSqlServer.execute(TestingSqlServer.java:69)
2021-05-09T11:29:42.9045474Z 	at io.trino.plugin.sqlserver.TestingSqlServer.setUpDatabase(TestingSqlServer.java:106)
2021-05-09T11:29:42.9047892Z 	at io.trino.plugin.sqlserver.TestingSqlServer.start(TestingSqlServer.java:82)
2021-05-09T11:29:42.9050812Z 	at io.trino.plugin.sqlserver.TestSqlServerTypeMapping.createQueryRunner(TestSqlServerTypeMapping.java:33)
2021-05-09T11:29:42.9053925Z 	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:90)
2021-05-09T11:29:42.9056353Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-05-09T11:29:42.9061656Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-05-09T11:29:42.9064445Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-05-09T11:29:42.9066515Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-05-09T11:29:42.9068382Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-05-09T11:29:42.9070682Z 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
2021-05-09T11:29:42.9072613Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
2021-05-09T11:29:42.9074378Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
2021-05-09T11:29:42.9076873Z 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
2021-05-09T11:29:42.9079140Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
2021-05-09T11:29:42.9081080Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-05-09T11:29:42.9083107Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-05-09T11:29:42.9084525Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-09T11:29:42.9086391Z Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 51) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
2021-05-09T11:29:42.9089454Z 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
2021-05-09T11:29:42.9092519Z 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
2021-05-09T11:29:42.9095497Z 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:872)
2021-05-09T11:29:42.9098375Z 	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767)
2021-05-09T11:29:42.9100423Z 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
2021-05-09T11:29:42.9102785Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
2021-05-09T11:29:42.9105666Z 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
2021-05-09T11:29:42.9108576Z 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
2021-05-09T11:29:42.9111293Z 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:743)
2021-05-09T11:29:42.9113560Z 	at io.trino.plugin.sqlserver.TestingSqlServer.execute(TestingSqlServer.java:66)
2021-05-09T11:29:42.9114812Z 	... 17 more
2021-05-09T11:29:42.9115059Z 
2021-05-09T11:29:43.3184530
```

Similar issue: https://github.com/trinodb/trino/issues/6389

**Comment by kokosing** [comment]
Possibly fixed with #7889
