### ISSUE TITLE
Oauth 2.0 fails when using an Okta org as an authorization server

### ISSUE THREAD

**Issue by mapshen** [trinodb/trino#7879]
We run trino 355 behind an nginx server, which is responsible for terminating HTTPS/TLS.

We have confirmed that the password file authentication works with this setting:
```
http-server.authentication.type=PASSWORD
http-server.process-forwarded=true
```
Users hit `trino.example.com` will be able to connect to the trino server hosted on `server1.example.com`.

However, when we switch to OAUTH2 with Okta with this setup:
```
http-server.authentication.type=oauth2
http-server.authentication.oauth2.auth-url=https://example.okta.com/oauth2/v1/authorize
http-server.authentication.oauth2.token-url=https://example.okta.com/oauth2/v1/token
http-server.authentication.oauth2.jwks-url=https://example.okta.com/oauth2/v1/keys
http-server.authentication.oauth2.client-id=XXX
http-server.authentication.oauth2.client-secret=XXX
http-server.process-forwarded=true
```

after an authorization code request

```
https://example.okta.com/oauth2/v1/authorize?redirect_uri=https%3A%2F%2Ftrino.example.com%2Foauth2%2Fcallback&state=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ0cmlub19vYXV0aF91aSIsImV4cCI6MTYyMDY3MzgzN30.EqZ4xA1hh196V3wBXtJzs9iocj_fMbErBiFSnyajpAA&nonce=f855818e1dc6c1a0902188647ecb3fd6ec411130cb974e174b92d27ac4e614cf&response_type=code&client_id=0oaz316io5A8TfKvS0h7&scope=openid

```
is sent to `/authorize` by Trino, and a response is received from Okta, we get this error which we suspect has something to do with the cross site policy:
```
2021-05-10T19:28:55.970Z        DEBUG   http-worker-491 io.trino.server.security.oauth2.OAuth2CallbackResource  Authentication response could not be verified: state=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ0cmlub19vYXV0aF91aSIsImV4cCI6MTYyMDY3NTgzNX0.3_HeAeuXFlCHh4f4GyFUL0As80DYy7H49PmWvrtVUzM
io.jsonwebtoken.SignatureException: Unknown signing key ID
        at io.trino.server.security.jwt.JwkSigningKeyResolver.lambda$getKey$0(JwkSigningKeyResolver.java:57)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at io.trino.server.security.jwt.JwkSigningKeyResolver.getKey(JwkSigningKeyResolver.java:57)
        at io.trino.server.security.jwt.JwkSigningKeyResolver.resolveSigningKey(JwkSigningKeyResolver.java:41)
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:316)
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:481)
        at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:541)
        at io.trino.server.security.oauth2.OAuth2Service.finishChallenge(OAuth2Service.java:134)
        at io.trino.server.security.oauth2.OAuth2CallbackResource.callback(OAuth2CallbackResource.java:105)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
        at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:279)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lukasz-walkiewicz** [comment]
Hi @mapshen,

It doesn't look like it has anything to do with the proxy. The error message says that the key (`kid`) from the JWT signature cannot be found in the JWKS endpoint response, ie. the signature key is unknown to the server. You probably have missconfigurations in you Trino config. Try getting the access token yourself using the authorization code you got and check whether it has the correct signature.

**Comment by mapshen** [comment]
@lukasz-walkiewicz thanks for quick response - you're right! Totally misread the error message. 

I checked the signature manually and confirmed that the validation failed. After some research, I found [1] states 

> When using an Okta org as an authorization server to request an access token, the signature validation fails on that access token

which explains the error we are experiencing.

Further, as per [2],

>If you are just looking to add SSO for your OpenID Connect-based applications, you can use your Org Authorization Server. You should also use the Org Authorization Server if you want to use OAuth 2.0 bearer tokens with your Okta APIs. Only the Org Authorization Server can mint access tokens that contain Okta API scopes.

Our use case is simply to add SSO, so we wonder if this is possible to disable the validation via configuration?

[1] https://support.okta.com/help/s/article/Signature-Validation-Failed-on-Access-Token?language=en_US
[2] https://developer.okta.com/docs/concepts/auth-servers/#which-authorization-server-should-you-use

**Comment by lukasz-walkiewicz** [comment]
Sorry for the delay @mapshen. I'm not sure I understand the question but you could try using the default authorization server, ie. try the configuration from: `https://<example>.okta.com/oauth2/default/.well-known/oauth-authorization-server`.

**Comment by mapshen** [comment]
> Sorry for the delay @mapshen. I'm not sure I understand the question but you could try using the default authorization server, ie. try the configuration from: `https://<example>.okta.com/oauth2/default/.well-known/oauth-authorization-server`.

No worries! I got it working a couple of weeks ago using the default authorization server. Sarcastically, the default authorization server was not available to us by default. Had to have our Okta admin reach out to Okta to get it...

On a side note, do you think Oauth is suitable for programmatic access? Say when you run an app on a server where no browser is available, I am not sure how to get the Authorization Code flow to work.

**Comment by kokosing** [comment]
The problem is solved. Let me close the issue then.
