### ISSUE TITLE
Support DISTINCT in window functions

### ISSUE THREAD

**Issue by martint** [trinodb/trino#7885]
Currently, window functions involving DISTINCT fail with an error:

```sql
SELECT count(DISTINCT orderstatus) OVER (PARTITION BY custkey)
FROM orders
```

```
Query 20210511_032412_00008_qbt2s failed: line 1:1: DISTINCT in window function parameters not yet supported: count(DISTINCT orderstatus) OVER (PARTITION BY custkey)
io.trino.spi.TrinoException: line 1:1: DISTINCT in window function parameters not yet supported: count(DISTINCT orderstatus) OVER (PARTITION BY custkey)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeWindowFunctions(StatementAnalyzer.java:2639)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeWindowFunctions(StatementAnalyzer.java:2609)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2015)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:366)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:383)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:393)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1152)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:366)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:383)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:346)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:267)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:190)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:800)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:129)
	at io.trino.$gen.Trino_356____20210511_032157_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findinpath** [comment]
I'd like to work on this one.

Could you @martint  or anybody else give me a few pointers on how to approach this one ?

**Comment by kasiafi** [comment]
According to the spec, `DISTINCT` in function call only applies to certain aggregate functions, which are
- either `<general set function>`:  
```
    AVG
  | MAX
  | MIN
  | SUM
  | EVERY
  | ANY
  | SOME
  | COUNT
  | STDDEV_POP
  | STDDEV_SAMP
  | VAR_SAMP
  | VAR_POP
  | COLLECT
  | FUSION
  | INTERSECTION
```
except `STDDEV_POP, STDDEV_SAMP, VAR_SAMP, VAR_POP`
- or `<listagg set function>`

If the aggregate function is called over a window, there is further limitation:
- `DISTINCT` is not allowed if the window has ordering or frame.

This limits the usage of DISTINCT in window functions to cases like e.g.
`avg(DISTINCT x) OVER(PARTITION BY y)`
`avg(DISTINCT x) OVER()`

If the window ordering is not specified, all rows are peers.
If the frame is not specified, it defaults to `RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW`
Effectively, the frame for each row encloses the whole partition.

So, the result of such window call is the same value as the result of the aggregation, but repeated for every input row.

This could be accomplished by following the execution of `AggregationNode`. Ideally, the computation should be done once per partition, and the result propagated for every output row.
Because we're operating on the whole partition, it is also possible to use MarkDistinctNode as a preparatory step (see: `MultipleDistinctAggregationToMarkDistinct`), which could help transform the distinct aggregation into a masked aggregation.

**Comment by taylorbentz** [comment]
Was this resolved in the above mention? If not, I will +1.

**Comment by scottedwards2000** [comment]
looks like #5523 was closed in favor of this one - any plans to pick it up?  I think ISO SQL standard supports it, no?

**Comment by kasiafi** [comment]
It was addressed as part of https://github.com/trinodb/trino/pull/24366
@losipiuk is that correct? Shall we close this issue?

**Comment by losipiuk** [comment]
Yeah - thanks for cleaning up :)
