### ISSUE TITLE
com.google.common.util.concurrent.UncheckedExecutionException when access sql server 2017

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#7917]
trino version: prestosql 340
sqlserver version:Microsoft SQL Server 2017

When I trying to access sql server by prestosql 340 I got below exception:
Query 20210514_062321_00000_e2zi8 failed: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Driver returned null connection
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Driver returned null connection
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:460)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.getSchemaNames(CachingJdbcClient.java:93)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.schemaExists(CachingJdbcClient.java:87)
	at io.prestosql.plugin.jdbc.JdbcMetadata.schemaExists(JdbcMetadata.java:85)
	at io.prestosql.metadata.MetadataManager.lambda$schemaExists$0(MetadataManager.java:304)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at io.prestosql.metadata.MetadataManager.schemaExists(MetadataManager.java:304)
	at io.prestosql.execution.UseTask.execute(UseTask.java:60)
	at io.prestosql.execution.UseTask.execute(UseTask.java:34)
	at io.prestosql.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:167)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:245)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132)
	at io.prestosql.$gen.Presto_340____20210514_062311_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Driver returned null connection
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:460)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.getSchemaNames(CachingJdbcClient.java:93)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 30 more
Caused by: java.lang.IllegalStateException: Driver returned null connection
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at io.prestosql.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:74)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:42)
	at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:42)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.getSchemaNames(BaseJdbcClient.java:170)
	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.getSchemaNames(ForwardingJdbcClient.java:66)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getSchemaNames$1(StatisticsAwareJdbcClient.java:83)
	at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getSchemaNames(StatisticsAwareJdbcClient.java:83)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 41 more

**Comment by kokosing** [comment]
```
Caused by: java.lang.IllegalStateException: Driver returned null connection
at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
at io.prestosql.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:74)
```

This means that Trino was not able to open JDBC connection to SQL Server. Typically in such case an exception is thrown, here `null` was returned.

Can you please share your `sqlserver.properties` file? Also can you please to use same configuration with other JDBC tools like DBeaver to see if you are able to connect to SQL Server.

**Comment by njalan** [comment]
@kokosing  Below is my sqlserver.properties and I am able to access sql server by DBeaver with the same configuration.
connector.name=sqlserver
connection-url=jdbc:jdbc:sqlserver://xxxx:1433;database=xx
connection-user=xxxx
connection-password=xxxx

**Comment by hashhar** [comment]
> jdbc:jdbc:sqlserver://xxxx:1433;database=xx

That could be the issue. Should it be `jdbc:sqlserver://xxxx:1433;database=xx` instead?

**Comment by njalan** [comment]
@hashhar I am sorry for my mistake and thanks for your help. It is working now.

**Comment by hashhar** [comment]
No need to be sorry. It's easy to miss.

Also, you might want to join the [Trino slack](https://trino.io/slack.html) so that you can get more help on the #troubleshooting channel.

**Comment by njalan** [comment]
I will join it. Thanks again
