### ISSUE TITLE
Testing SQL Server is flaky

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#7919]
```
2021-05-13T19:20:51.7120936Z 2021-05-13T14:20:51.711-0500 INFO Container is started (JDBC URL: jdbc:sqlserver://localhost:49173)
2021-05-13T19:20:51.7129602Z 2021-05-13T14:20:51.712-0500 INFO Container microsoft/mssql-server-linux:2017-CU13 started in PT25.399234S
2021-05-13T19:28:29.3893532Z 2021-05-13T14:28:29.374-0500 WARNING No test started or completed in 8.00m. Running tests:
2021-05-13T19:28:29.3895209Z 	io.trino.plugin.sqlserver.TestSqlServerConnectorTest::init running for 8.07m
2021-05-13T19:28:29.3897338Z 	io.trino.plugin.sqlserver.TestSqlServerConnectorTest running for 8.07m.
2021-05-13T19:28:29.3898400Z 
2021-05-13T19:28:29.3898850Z Full Thread Dump:
2021-05-13T19:28:29.3900192Z "main" prio=5 Id=1 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@ebab000
2021-05-13T19:28:29.3901806Z 	at java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method)
2021-05-13T19:28:29.3903634Z 	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@ebab000
2021-05-13T19:28:29.3905592Z 	at java.base@11.0.11/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
2021-05-13T19:28:29.3907919Z 	at java.base@11.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
2021-05-13T19:28:29.3910534Z 	at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454)
2021-05-13T19:28:29.3912326Z 	at app//org.testng.TestRunner.privateRun(TestRunner.java:735)
2021-05-13T19:28:29.3913411Z 	at app//org.testng.TestRunner.run(TestRunner.java:610)
2021-05-13T19:28:29.3914894Z 	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
2021-05-13T19:28:29.3916703Z 	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
2021-05-13T19:28:29.3917483Z 	...
2021-05-13T19:28:29.3917684Z 
2021-05-13T19:28:29.3917881Z 
2021-05-13T19:28:29.3918322Z "Reference Handler" daemon prio=10 Id=2 RUNNABLE
2021-05-13T19:28:29.3919530Z 	at java.base@11.0.11/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
2021-05-13T19:28:29.3921271Z 	at java.base@11.0.11/java.lang.ref.Reference.processPendingReferences(Reference.java:241)
2021-05-13T19:28:29.3922702Z 	at java.base@11.0.11/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)
2021-05-13T19:28:29.3923344Z 
2021-05-13T19:28:29.3923542Z 
2021-05-13T19:28:29.3924197Z "Finalizer" daemon prio=8 Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@6256cf54
2021-05-13T19:28:29.3925343Z 	at java.base@11.0.11/java.lang.Object.wait(Native Method)
2021-05-13T19:28:29.3926354Z 	-  waiting on java.lang.ref.ReferenceQueue$Lock@6256cf54
2021-05-13T19:28:29.3927467Z 	at java.base@11.0.11/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
2021-05-13T19:28:29.3928788Z 	at java.base@11.0.11/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
2021-05-13T19:28:29.3930098Z 	at java.base@11.0.11/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)
2021-05-13T19:28:29.3930714Z 
2021-05-13T19:28:29.3930914Z 
2021-05-13T19:28:29.3931344Z "Signal Dispatcher" daemon prio=9 Id=4 RUNNABLE
2021-05-13T19:28:29.3931865Z 
2021-05-13T19:28:29.3932065Z 
2021-05-13T19:28:29.3932985Z "Common-Cleaner" daemon prio=8 Id=9 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@508fc130
2021-05-13T19:28:29.3933950Z 	at java.base@11.0.11/java.lang.Object.wait(Native Method)
2021-05-13T19:28:29.3934896Z 	-  waiting on java.lang.ref.ReferenceQueue$Lock@508fc130
2021-05-13T19:28:29.3936012Z 	at java.base@11.0.11/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
2021-05-13T19:28:29.3937252Z 	at java.base@11.0.11/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
2021-05-13T19:28:29.3979097Z 	at java.base@11.0.11/java.lang.Thread.run(Thread.java:829)
2021-05-13T19:28:29.3980158Z 	at java.base@11.0.11/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)
2021-05-13T19:28:29.3980905Z 
2021-05-13T19:28:29.3981103Z 
2021-05-13T19:28:29.3982078Z "surefire-forkedjvm-command-thread" daemon prio=5 Id=10 RUNNABLE (in native)
2021-05-13T19:28:29.3983180Z 	at java.base@11.0.11/java.io.FileInputStream.readBytes(Native Method)
2021-05-13T19:28:29.3984289Z 	at java.base@11.0.11/java.io.FileInputStream.read(FileInputStream.java:279)
2021-05-13T19:28:29.3985536Z 	at java.base@11.0.11/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
2021-05-13T19:28:29.3987366Z 	at java.base@11.0.11/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
2021-05-13T19:28:29.4020546Z 	-  locked java.io.BufferedInputStream@17243a53
2021-05-13T19:28:29.4021582Z 	at java.base@11.0.11/java.io.DataInputStream.readInt(DataInputStream.java:392)
2021-05-13T19:28:29.4023402Z 	at app//org.apache.maven.surefire.booter.MasterProcessCommand.decode(MasterProcessCommand.java:115)
2021-05-13T19:28:29.4025559Z 	at app//org.apache.maven.surefire.booter.CommandReader$CommandRunnable.run(CommandReader.java:391)
2021-05-13T19:28:29.4026853Z 	at java.base@11.0.11/java.lang.Thread.run(Thread.java:829)
2021-05-13T19:28:29.4027287Z 
2021-05-13T19:28:29.4027485Z 
2021-05-13T19:28:29.4029115Z "surefire-forkedjvm-ping-30s" daemon prio=5 Id=11 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@183df8b4
2021-05-13T19:28:29.4030843Z 	at java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method)
2021-05-13T19:28:29.4032478Z 	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@183df8b4
2021-05-13T19:28:29.4034306Z 	at java.base@11.0.11/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
2021-05-13T19:28:29.4036536Z 	at java.base@11.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
2021-05-13T19:28:29.4039124Z 	at java.base@11.0.11/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
2021-05-13T19:28:29.4041603Z 	at java.base@11.0.11/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
2021-05-13T19:28:29.4043773Z 	at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
2021-05-13T19:28:29.4045645Z 	at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
2021-05-13T19:28:29.4047443Z 	at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-05-13T19:28:29.4048382Z 	...
2021-05-13T19:28:29.4048747Z 
2021-05-13T19:28:29.4048944Z 
2021-05-13T19:28:29.4049846Z "process reaper" daemon prio=10 Id=12 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@36952cc2
2021-05-13T19:28:29.4051063Z 	at java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method)
2021-05-13T19:28:29.4052497Z 	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@36952cc2
2021-05-13T19:28:29.4054061Z 	at java.base@11.0.11/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
2021-05-13T19:28:29.4055840Z 	at java.base@11.0.11/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
2021-05-13T19:28:29.4057591Z 	at java.base@11.0.11/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
2021-05-13T19:28:29.4100218Z 	at java.base@11.0.11/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
2021-05-13T19:28:29.4102060Z 	at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
2021-05-13T19:28:29.4103965Z 	at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
2021-05-13T19:28:29.4105752Z 	at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-05-13T19:28:29.4106690Z 	...
2021-05-13T19:28:29.4106897Z 
2021-05-13T19:28:29.4107095Z 
2021-05-13T19:28:29.4107541Z "TestHangMonitor" daemon prio=5 Id=14 RUNNABLE
2021-05-13T19:28:29.4108558Z 	at java.management@11.0.11/sun.management.ThreadImpl.dumpThreads0(Native Method)
2021-05-13T19:28:29.4110000Z 	at java.management@11.0.11/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
2021-05-13T19:28:29.4111501Z 	at java.management@11.0.11/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
2021-05-13T19:28:29.4113613Z 	at app//io.trino.testng.services.LogTestDurationListener.dumpAllThreads(LogTestDurationListener.java:160)
2021-05-13T19:28:29.4116366Z 	at app//io.trino.testng.services.LogTestDurationListener.checkForTestHang(LogTestDurationListener.java:147)
2021-05-13T19:28:29.4118622Z 	at app//io.trino.testng.services.LogTestDurationListener$$Lambda$71/0x000000080014a040.run(Unknown Source)
2021-05-13T19:28:29.4120122Z 	at java.base@11.0.11/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2021-05-13T19:28:29.4121513Z 	at java.base@11.0.11/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
2021-05-13T19:28:29.4122403Z 	...
2021-05-13T19:28:29.4122612Z 
2021-05-13T19:28:29.4123007Z 	Number of locked synchronizers = 1
2021-05-13T19:28:29.4124161Z 	- java.util.concurrent.ThreadPoolExecutor$Worker@6b8ca3c8
2021-05-13T19:28:29.4124801Z 
2021-05-13T19:28:29.4124996Z 
2021-05-13T19:28:29.4125597Z "pool-3-thread-1" prio=5 Id=15 RUNNABLE (in native)
2021-05-13T19:28:29.4126546Z 	at java.base@11.0.11/java.net.SocketInputStream.socketRead0(Native Method)
2021-05-13T19:28:29.4166716Z 	at java.base@11.0.11/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
2021-05-13T19:28:29.4168123Z 	at java.base@11.0.11/java.net.SocketInputStream.read(SocketInputStream.java:168)
2021-05-13T19:28:29.4169380Z 	at java.base@11.0.11/java.net.SocketInputStream.read(SocketInputStream.java:140)
2021-05-13T19:28:29.4170734Z 	at app//com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2054)
2021-05-13T19:28:29.4172447Z 	at app//com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6596)
2021-05-13T19:28:29.4174137Z 	-  locked com.microsoft.sqlserver.jdbc.TDSReader@d56ee1
2021-05-13T19:28:29.4175625Z 	at app//com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7760)
2021-05-13T19:28:29.4177908Z 	at app//com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:870)
2021-05-13T19:28:29.4179417Z 	...
2021-05-13T19:28:29.4179608Z 
2021-05-13T19:28:29.4180015Z 	Number of locked synchronizers = 1
2021-05-13T19:28:29.4181049Z 	- java.util.concurrent.ThreadPoolExecutor$Worker@7af707e0
2021-05-13T19:28:29.4181918Z 
2021-05-13T19:28:29.4182118Z 
2021-05-13T19:28:29.4183222Z "pool-3-thread-2" prio=5 Id=16 BLOCKED on org.testng.TestClass@17b6c061 owned by "pool-3-thread-1" Id=15
2021-05-13T19:28:29.4184989Z 	at app//org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:158)
2021-05-13T19:28:29.4186677Z 	-  blocked on org.testng.TestClass@17b6c061
2021-05-13T19:28:29.4187742Z 	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
2021-05-13T19:28:29.4189521Z 	at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-05-13T19:28:29.4191310Z 	at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-05-13T19:28:29.4192479Z 	at java.base@11.0.11/java.lang.Thread.run(Thread.java:829)
2021-05-13T19:28:29.4192913Z 
2021-05-13T19:28:29.4193323Z 	Number of locked synchronizers = 1
2021-05-13T19:28:29.4194339Z 	- java.util.concurrent.ThreadPoolExecutor$Worker@737edcfa
2021-05-13T19:28:29.4194986Z 
2021-05-13T19:28:29.4195190Z 
2021-05-13T19:28:29.4195953Z "docker-java-stream-117563928" daemon prio=5 Id=20 RUNNABLE (in native)
2021-05-13T19:28:29.4197231Z 	at app//com.github.dockerjava.transport.DomainSocket.read(Native Method)
2021-05-13T19:28:29.4198879Z 	at app//com.github.dockerjava.transport.DomainSocket.read(DomainSocket.java:79)
2021-05-13T19:28:29.4200648Z 	at app//com.github.dockerjava.transport.DomainSocket.access$200(DomainSocket.java:35)
2021-05-13T19:28:29.4202546Z 	at app//com.github.dockerjava.transport.DomainSocket$DomainSocketInputStream.read(DomainSocket.java:162)
2021-05-13T19:28:29.4205215Z 	at app//org.testcontainers.shaded.okio.Okio$2.read(Okio.java:140)
2021-05-13T19:28:29.4206536Z 	at app//org.testcontainers.shaded.okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
2021-05-13T19:28:29.4208422Z 	at app//org.testcontainers.shaded.okio.RealBufferedSource.request(RealBufferedSource.java:72)
2021-05-13T19:28:29.4210673Z 	at app//org.testcontainers.shaded.okio.RealBufferedSource.require(RealBufferedSource.java:65)
2021-05-13T19:28:29.4212041Z 	...
2021-05-13T19:28:29.4212250Z 
2021-05-13T19:28:29.4212446Z 
2021-05-13T19:28:29.4213365Z "testcontainers-ryuk" daemon prio=5 Id=21 TIMED_WAITING on java.util.ArrayList@16ee1da6
2021-05-13T19:28:29.4214257Z 	at java.base@11.0.11/java.lang.Object.wait(Native Method)
2021-05-13T19:28:29.4215083Z 	-  waiting on java.util.ArrayList@16ee1da6
2021-05-13T19:28:29.4216297Z 	at app//org.testcontainers.utility.ResourceReaper.lambda$null$1(ResourceReaper.java:170)
2021-05-13T19:28:29.4217916Z 	at app//org.testcontainers.utility.ResourceReaper$$Lambda$289/0x0000000800408840.run(Unknown Source)
2021-05-13T19:28:29.4219607Z 	at app//org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
2021-05-13T19:28:29.4221480Z 	at app//org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:159)
2021-05-13T19:28:29.4223320Z 	at app//org.testcontainers.utility.ResourceReaper$$Lambda$288/0x0000000800408440.run(Unknown Source)
2021-05-13T19:28:29.4224400Z 	at java.base@11.0.11/java.lang.Thread.run(Thread.java:829)
2021-05-13T19:28:29.4224843Z 
2021-05-13T19:28:29.4225042Z 

````

**Comment by raunaqmorarka** [comment]
Encountered in https://github.com/trinodb/trino/pull/9389/checks?check_run_id=3721560355

**Comment by findepi** [comment]
Old. Obsolete?
