### ISSUE TITLE
EOFException while querying iceberg table of parquet format

### ISSUE THREAD

**Issue by dixingxing0** [trinodb/trino#7922]
I encountered an exception while querying a iceberg table of parqeut format.

Environment:
```
Trino 356
Iceberg 0.11
parquet 1.11.1
```

Stack trace:
```
io.trino.spi.TrinoException: Error reading tail from viewfs://MyCluster/mydb/table1/data/dt=2021-05-12/h=10/00107-111-7175b3c4-3ff0-48bd-92fa-ec7f85aaaa00-00001.parquet with length 16384
        at io.trino.plugin.hive.parquet.HdfsParquetDataSource.readTail(HdfsParquetDataSource.java:112)
        at io.trino.parquet.reader.MetadataReader.readFooter(MetadataReader.java:90)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.lambda$createParquetPageSource$10(IcebergPageSourceProvider.java:447)
        at io.trino.plugin.hive.authentication.UserGroupInformationUtils.lambda$executeActionInDoAs$0(UserGroupInformationUtils.java:29)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1710)
        at io.trino.plugin.hive.authentication.UserGroupInformationUtils.executeActionInDoAs(UserGroupInformationUtils.java:27)
        at io.trino.plugin.hive.authentication.ImpersonatingHdfsAuthentication.doAs(ImpersonatingHdfsAuthentication.java:39)
        at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:95)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.createParquetPageSource(IcebergPageSourceProvider.java:447)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.createDataPageSource(IcebergPageSourceProvider.java:226)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.createPageSource(IcebergPageSourceProvider.java:167)
        at io.trino.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:68)
        at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:66)
        at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
        at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:298)
        at io.trino.operator.Driver.processInternal(Driver.java:387)
        at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
        at io.trino.operator.Driver.tryWithLock(Driver.java:683)
        at io.trino.operator.Driver.processFor(Driver.java:284)
        at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
        at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.trino.$gen.Trino_356____20210511_112047_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: Cannot seek after EOF
        at org.apache.hadoop.hdfs.DFSInputStream.seek(DFSInputStream.java:1447)
        at org.apache.hadoop.fs.FSDataInputStream.seek(FSDataInputStream.java:65)
        at org.apache.hadoop.fs.FSDataInputStream.seek(FSDataInputStream.java:65)
        at org.apache.hadoop.fs.FSDataInputStream.seek(FSDataInputStream.java:65)
        at io.trino.plugin.hive.util.FSDataInputStreamTail.readTail(FSDataInputStreamTail.java:57)
        at io.trino.plugin.hive.parquet.HdfsParquetDataSource.readTail(HdfsParquetDataSource.java:108)
        ... 27 more

```

**Comment by phd3** [comment]
@dixingxing0 Do you know if any older Trino version executes the query successfully? One possible reason could be that the writer stored incorrect file size in Iceberg metadata. ( e.g. #6539 ) Can you try the query with session property `iceberg.USE_FILE_SIZE_FROM_METADATA=false` ?

**Comment by dixingxing0** [comment]
Thank you @phd3, `SET SESSION iceberg.use_file_size_from_metadata  = false;` works! and you are right, there is one parquet file's `fileSizeInBytes` was not incorrect.
