### ISSUE TITLE
NullPointerException In Iceberg when joining a partitioned table with nested fields

### ISSUE THREAD

**Issue by JoJoBizarreAdventure** [trinodb/trino#7999]
The error message is as follow
`at io.trino.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:80)
	at io.trino.cost.CostCalculatorUsingExchanges$CostEstimator.getStats(CostCalculatorUsingExchanges.java:358)
	at io.trino.cost.CostCalculatorUsingExchanges$CostEstimator.visitTableScan(CostCalculatorUsingExchanges.java:150)
	at io.trino.cost.CostCalculatorUsingExchanges$CostEstimator.visitTableScan(CostCalculatorUsingExchanges.java:83)
	at io.trino.sql.planner.plan.TableScanNode.accept(TableScanNode.java:167)
	at io.trino.cost.CostCalculatorUsingExchanges.calculateCost(CostCalculatorUsingExchanges.java:80)
	at io.trino.cost.CostCalculatorWithEstimatedExchanges.calculateCost(CostCalculatorWithEstimatedExchanges.java:64)
	at io.trino.cost.CachingCostProvider.calculateCost(CachingCostProvider.java:109)
	at io.trino.cost.CachingCostProvider.getGroupCost(CachingCostProvider.java:101)
	at io.trino.cost.CachingCostProvider.getCost(CachingCostProvider.java:70)
	at io.trino.sql.planner.iterative.rule.ReorderJoins$JoinEnumerator.createJoinEnumerationResult(ReorderJoins.java:471)
	at io.trino.sql.planner.iterative.rule.ReorderJoins$JoinEnumerator.getJoinSource(ReorderJoins.java:383)
	at io.trino.sql.planner.iterative.rule.ReorderJoins$JoinEnumerator.createJoin(ReorderJoins.java:291)
	at io.trino.sql.planner.iterative.rule.ReorderJoins$JoinEnumerator.createJoinAccordingToPartitioning(ReorderJoins.java:262)
	at io.trino.sql.planner.iterative.rule.ReorderJoins$JoinEnumerator.chooseJoinOrder(ReorderJoins.java:206)
	at io.trino.sql.planner.iterative.rule.ReorderJoins.chooseJoinOrder(ReorderJoins.java:160)
	at io.trino.sql.planner.iterative.rule.ReorderJoins.apply(ReorderJoins.java:133)
	at io.trino.sql.planner.iterative.rule.ReorderJoins.apply(ReorderJoins.java:94)
	at io.trino.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:168)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:143)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:108)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:110)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:110)
	at io.trino.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:99)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:208)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:197)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:192)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:482)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:462)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:405)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20210520_135923_3.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
`
This can be reproduce by the test method in https://github.com/trinodb/trino/issues/7502
It is at **plugin.trino-iceberg.src.main.java.io.trino.plugin.iceberg.TableStatisticsMaker.java**
![image](https://user-images.githubusercontent.com/64888038/118992894-9ed75d00-b9b7-11eb-8a93-379f727a4b89.png)
**dataFile.lowerBounds** contains two value 4 and 5 which is not in **idToTypeMapping**, as follow
![image](https://user-images.githubusercontent.com/64888038/118993247-ee1d8d80-b9b7-11eb-9c57-2943948571e3.png)
Same happens for upperBounds

**Comment by hashhar** [comment]
The cause is detailed in https://github.com/trinodb/trino/issues/7502#issuecomment-845210600.

FYI Piotr this is `PartitionTable#convert` striking again. 😞

**Comment by chenjian2664** [comment]
I think here is because while collecting Iceberg `Type.PrimitiveType` we missing the `Type.PrimitiveType` here.

I am interested in this can take this @JoJoBizarreAdventure @hashhar , also the same https://github.com/trinodb/trino/issues/7502
