### ISSUE TITLE
'Multiple entries with same key' error on duplicated grouping on literal value

### ISSUE THREAD

**Issue by takezoe** [trinodb/trino#8027]
The following queries fail with 'Multiple entries with same key' error on Trino 356.

```
trino> select null group by 1, 1;
Query 20210521_142930_00005_r3wn2 failed: line 1:26: Multiple entries with same key: @15593b5d: null=expr and @15593b5d: null=expr

trino> select '123' group by 1, 1;
Query 20210521_142933_00006_r3wn2 failed: Multiple entries with same key: @55e072a3: '123'=expr and @55e072a3: '123'=expr
```

Full stacktrace:
```
	
java.lang.IllegalArgumentException: Multiple entries with same key: @15593b5d: null=expr and @15593b5d: null=expr
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:210)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:204)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:146)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:109)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:389)
	at io.trino.sql.planner.QueryPlanner.coerce(QueryPlanner.java:1340)
	at io.trino.sql.planner.QueryPlanner.aggregate(QueryPlanner.java:657)
	at io.trino.sql.planner.QueryPlanner.plan(QueryPlanner.java:377)
	at io.trino.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:931)
	at io.trino.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:129)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:587)
	at io.trino.sql.planner.QueryPlanner.plan(QueryPlanner.java:185)
	at io.trino.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:924)
	at io.trino.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:129)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:692)
	at io.trino.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:266)
	at io.trino.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:237)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:202)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:197)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:192)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:482)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:462)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:405)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_356____20210521_141328_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

As far as I investigated, this error started to happen from this commit: https://github.com/trinodb/trino/commit/edb4b8b12a01d4b5ecad3395b87bc92daa829902, but I'm not yet sure what actually causes this issue.

**Comment by findepi** [comment]
cc @kasiafi

**Comment by takezoe** [comment]
I confirmed that https://github.com/trinodb/trino/pull/8023 solves this issue. Thank you @martint!
