### ISSUE TITLE
Flaky TestSqlServerWithoutSnapshotIsolation

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#8061]
```
Error:  init(io.trino.plugin.sqlserver.TestSqlServerWithoutSnapshotIsolation)  Time elapsed: 16.374 s  <<< FAILURE!
java.lang.RuntimeException: Failed to execute statement: CREATE DATABASE database_f71b1f65c51e4dbcacf2850bbb520f1e
	at io.trino.plugin.sqlserver.TestingSqlServer.execute(TestingSqlServer.java:94)
	at io.trino.plugin.sqlserver.TestingSqlServer.setUpDatabase(TestingSqlServer.java:127)
	at io.trino.plugin.sqlserver.TestingSqlServer.start(TestingSqlServer.java:107)
	at io.trino.plugin.sqlserver.BaseSqlServerTransactionIsolationTest.createQueryRunner(BaseSqlServerTransactionIsolationTest.java:37)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: An unexpected error occurred while checking the sector size for file '/var/opt/mssql/data/database_f71b1f65c51e4dbcacf2850bbb520f1e.mdf'. Move the file to a local NTFS volume, where the sector size can be retrieved. Check the SQL Server error log for more information.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:872)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3272)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:743)
	at io.trino.plugin.sqlserver.TestingSqlServer.execute(TestingSqlServer.java:91)
	... 17 more
```

from https://github.com/trinodb/trino/runs/2652292179

**Comment by chenjian2664** [comment]
@electrum Is it similar to https://github.com/microsoft/mssql-docker/issues/344 ?

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/8051
