### ISSUE TITLE
After enable Password file authentication, i encounter error "Error starting query at https://***/v1/statement returned an invalid response: JsonResponse{statusCode=403} "

### ISSUE THREAD

**Issue by simple-tec** [trinodb/trino#8344]
### Issue Brief Description: 
Before enable authentication, it works ok.
 After enable password file authentication, i encounter error : 
`java.lang.RuntimeException: Error starting query at https://trino-ds-e300.***.com.cn/v1/statement returned an invalid response: JsonResponse{statusCode=403, statusMessage=, headers={cache-control=[must-revalidate,no-cache,no-store], content-type=[text/html;charset=iso-8859-1], date=[Tue, 22 Jun 2021 03:51:19 GMT], server=[nginx/1.16.0], vary=[Accept-Encoding]}, hasValue=false} [Error: <html>

### my trino version
358

### my trino server configuration
config.properties:
`coordinator=true
http-server.authentication.type=PASSWORD
http-server.process-forwarded=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
query.max-memory=4GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
memory.heap-headroom-per-node=1GB
discovery-server.enabled=true
discovery.uri=http://localhost:8080
`
password-authenticator.properties:
`password-authenticator.name=file
file.refresh-period=5s
file.password-file=/etc/trino/password.db
`
password.db: (generated by : htpasswd -B -C 10 password.db test )
`test:$2y$10$T3Mc26qTCErXPBGN0TuHNOnPVZGJGCHmE9q4sYMnQGE6blkGIoNxS
`
### Cli connect command:
root@jinxin:/tftpboot# ./trino --server https://trino-ds-e300.axa.wise-paas.com.cn --user=test --password --debug
Password: 
trino> show catalogs;
Error running command: Error starting query at https://trino-ds-e300.axa.wise-paas.com.cn/v1/statement returned an invalid response: JsonResponse{statusCode=403, statusMessage=, headers={cache-control=[must-revalidate,no-cache,no-store], content-type=[text/html;charset=iso-8859-1], date=[Tue, 22 Jun 2021 03:51:19 GMT], server=[nginx/1.16.0], vary=[Accept-Encoding]}, hasValue=false} [Error: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 403 Forbidden</title>
</head>
<body><h2>HTTP ERROR 403 Forbidden</h2>
<table>
<tr><th>URI:</th><td>/v1/statement</td></tr>
<tr><th>STATUS:</th><td>403</td></tr>
<tr><th>MESSAGE:</th><td>Forbidden</td></tr>
<tr><th>SERVLET:</th><td>org.glassfish.jersey.servlet.ServletContainer-2d36add1</td></tr>
</table>

</body>
</html>
]
java.lang.RuntimeException: Error starting query at https://trino-ds-e300.axa.wise-paas.com.cn/v1/statement returned an invalid response: JsonResponse{statusCode=403, statusMessage=, headers={cache-control=[must-revalidate,no-cache,no-store], content-type=[text/html;charset=iso-8859-1], date=[Tue, 22 Jun 2021 03:51:19 GMT], server=[nginx/1.16.0], vary=[Accept-Encoding]}, hasValue=false} [Error: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 403 Forbidden</title>
</head>
<body><h2>HTTP ERROR 403 Forbidden</h2>
<table>
<tr><th>URI:</th><td>/v1/statement</td></tr>
<tr><th>STATUS:</th><td>403</td></tr>
<tr><th>MESSAGE:</th><td>Forbidden</td></tr>
<tr><th>SERVLET:</th><td>org.glassfish.jersey.servlet.ServletContainer-2d36add1</td></tr>
</table>

</body>
</html>
]
	at io.trino.client.StatementClientV1.requestFailedException(StatementClientV1.java:448)
	at io.trino.client.StatementClientV1.<init>(StatementClientV1.java:113)
	at io.trino.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24)
	at io.trino.cli.QueryRunner.startInternalQuery(QueryRunner.java:153)
	at io.trino.cli.QueryRunner.startQuery(QueryRunner.java:139)
	at io.trino.cli.Console.process(Console.java:362)
	at io.trino.cli.Console.runConsole(Console.java:293)
	at io.trino.cli.Console.run(Console.java:195)
	at io.trino.cli.Console.call(Console.java:105)
	at io.trino.cli.Console.call(Console.java:78)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.trino.cli.Trino.main(Trino.java:42)
trino>

**Comment by simple-tec** [comment]
could anyone help me ?

**Comment by simple-tec** [comment]
What puzzles me is that when the error occurs, the server does not print anything useful logs !

**Comment by nnandula** [comment]
Hi, 
I am facing the same issue. Just checking if you were able to resolve it.

**Comment by hashhar** [comment]
JsonResponse{statusCode=403

Suggests that your client isn't authenticating to Trino. Make sure you use the https url and pass the username and password. And that there are no system access controls configured preventing the user from executing the given query.

**Comment by nnandula** [comment]
Hello @hashhar, 

Yes it is present in the `config.properties`

We are using a proxy server and the Trino coordinator is running with HTTP configuration on the default port, 8080. 

Added `http-server.process-forwarded=true` to the `config.properties` file.

We are able to connect to trino using the proxy server https url and query data.

Now to configure LDAP authentication added `http-server.authentication.type=PASSWORD `to `config.properties` file. 
And password-authenticator.properties with below content:
```
password-authenticator.name=ldap
ldap.allow-insecure=true
ldap.url=ldap://ldap.example.com:389
ldap.user-bind-pattern=${USER}@example.com

```

When we try to connect to Trino CLI it fails with below error:
```
Caused by: java.lang.RuntimeException: Error starting query at https://trino-dev.example.com/v1/statement returned an invalid response: JsonResponse{statusCode=403, statusMessage=Forbidden, headers={cache-control=[must-revalidate,no-cache,no-store], content-length=[417], content-type=[text/html;charset=iso-8859-1]}, hasValue=false} [Error: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 403 Forbidden</title>
</head>
<body><h2>HTTP ERROR 403 Forbidden</h2>
```

Please advise.
