### ISSUE TITLE
Failure in TestOraclePoolRemarksReportingConnectorSmokeTest.init

### ISSUE THREAD

**Issue by raunaqmorarka** [trinodb/trino#8345]
```
2021-06-21T10:13:35.7684358Z [ERROR] Tests run: 249, Failures: 1, Errors: 0, Skipped: 109, Time elapsed: 677.97 s <<< FAILURE! - in TestSuite
2021-06-21T10:13:35.7687120Z [ERROR] init(io.trino.plugin.oracle.TestOraclePoolRemarksReportingConnectorSmokeTest)  Time elapsed: 246.648 s  <<< FAILURE!
2021-06-21T10:13:35.7690143Z java.lang.RuntimeException: java.sql.SQLRecoverableException: IO Error: Connection reset by peer, Authentication lapse 0 ms.
2021-06-21T10:13:35.7692863Z 	at io.trino.plugin.oracle.TestingOracleServer.<init>(TestingOracleServer.java:81)
2021-06-21T10:13:35.7700325Z 	at io.trino.plugin.oracle.TestOraclePoolRemarksReportingConnectorSmokeTest.createQueryRunner(TestOraclePoolRemarksReportingConnectorSmokeTest.java:38)
2021-06-21T10:13:35.7705646Z 	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:91)
2021-06-21T10:13:35.7707942Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-06-21T10:13:35.7710393Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-06-21T10:13:35.7714690Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-06-21T10:13:35.7717186Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-06-21T10:13:35.7720582Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-06-21T10:13:35.7723627Z 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
2021-06-21T10:13:35.7725788Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
2021-06-21T10:13:35.7727981Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
2021-06-21T10:13:35.7730608Z 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
2021-06-21T10:13:35.7734482Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
2021-06-21T10:13:35.7736519Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-06-21T10:13:35.7738960Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-06-21T10:13:35.7740718Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-06-21T10:13:35.7742202Z Caused by: java.sql.SQLRecoverableException: IO Error: Connection reset by peer, Authentication lapse 0 ms.
2021-06-21T10:13:35.7743644Z 	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:874)
2021-06-21T10:13:35.7745224Z 	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
2021-06-21T10:13:35.7747807Z 	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
2021-06-21T10:13:35.7749415Z 	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
2021-06-21T10:13:35.7751095Z 	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562)
2021-06-21T10:13:35.7753003Z 	at io.trino.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:65)
2021-06-21T10:13:35.7755427Z 	at io.trino.plugin.jdbc.RetryingConnectionFactory.lambda$openConnection$0(RetryingConnectionFactory.java:54)
2021-06-21T10:13:35.7757396Z 	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
2021-06-21T10:13:35.7758903Z 	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:62)
2021-06-21T10:13:35.7760676Z 	at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
2021-06-21T10:13:35.7762660Z 	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
2021-06-21T10:13:35.7764181Z 	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:67)
2021-06-21T10:13:35.7766480Z 	at io.trino.plugin.jdbc.RetryingConnectionFactory.openConnection(RetryingConnectionFactory.java:54)
2021-06-21T10:13:35.7768700Z 	at io.trino.plugin.oracle.TestingOracleServer.<init>(TestingOracleServer.java:73)
2021-06-21T10:13:35.7769741Z 	... 15 more
2021-06-21T10:13:35.7770432Z Caused by: java.io.IOException: Connection reset by peer, Authentication lapse 0 ms.
2021-06-21T10:13:35.7771750Z 	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:870)
2021-06-21T10:13:35.7772832Z 	... 28 more
2021-06-21T10:13:35.7773416Z Caused by: java.io.IOException: Connection reset by peer
2021-06-21T10:13:35.7777421Z 	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
2021-06-21T10:13:35.7783690Z 	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
2021-06-21T10:13:35.7789346Z 	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
2021-06-21T10:13:35.7794100Z 	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
2021-06-21T10:13:35.7800023Z 	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
2021-06-21T10:13:35.7806554Z 	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:353)
2021-06-21T10:13:35.7813356Z 	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:174)
2021-06-21T10:13:35.7819367Z 	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:555)
2021-06-21T10:13:35.7824545Z 	at oracle.net.ns.NIOPacket.readNIOPacket(NIOPacket.java:403)
2021-06-21T10:13:35.7831293Z 	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:127)
2021-06-21T10:13:35.7836821Z 	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:340)
2021-06-21T10:13:35.7843575Z 	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1596)
2021-06-21T10:13:35.7850671Z 	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:588)
2021-06-21T10:13:35.7852888Z 	... 28 more
2021-06-21T10:13:35.7853628Z 
2021-06-21T10:13:36.3340531Z [INFO] 
2021-06-21T10:13:36.3343552Z [INFO] Results:
2021-06-21T10:13:36.3345667Z [INFO] 
2021-06-21T10:13:36.3350162Z [ERROR] Failures: 
2021-06-21T10:13:36.3376098Z [ERROR]   TestOraclePoolRemarksReportingConnectorSmokeTest>AbstractTestQueryFramework.init:91->createQueryRunner:38 » Runtime
2021-06-21T10:13:36.3377754Z [INFO] 
2021-06-21T10:13:36.3379552Z [ERROR] Tests run: 245, Failures: 1, Errors: 0, Skipped: 105
```

**Comment by raunaqmorarka** [comment]
Encountered in https://github.com/trinodb/trino/pull/8327

**Comment by phd3** [comment]
Encountered in https://github.com/trinodb/trino/actions/runs/1020411622 on #8340

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/3179634070 cc @wendigo @hashhar

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/runs/3258682655 on #8810
