### ISSUE TITLE
can't create CREATE SCHEMA

### ISSUE THREAD

**Issue by longtran84** [trinodb/trino#8399]
trino> CREATE SCHEMA web;
Query 20210627_143241_00084_qfy3r failed: createDatabase

**Comment by ebyhr** [comment]
Could you share the full stacktrace? You can get `--debug` CLI option or webui.

**Comment by longtran84** [comment]
@ebyhr  i would like send to you logging

trino> CREATE SCHEMA hive.test;
Query 20210628_014206_00010_qfy3r failed: createDatabase
io.trino.spi.TrinoException: createDatabase
        at io.trino.plugin.hive.metastore.alluxio.AlluxioHiveMetastore.createDatabase(AlluxioHiveMetastore.java:259)
        at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.createDatabase(CachingHiveMetastore.java:453)
        at io.trino.plugin.hive.HiveMetastoreClosure.createDatabase(HiveMetastoreClosure.java:124)
        at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.lambda$createDatabase$2(SemiTransactionalHiveMetastore.java:359)
        at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1166)
        at io.trino.plugin.hive.HiveMetadata.commit(HiveMetadata.java:3010)
        at io.trino.plugin.hive.HiveConnector.commit(HiveConnector.java:225)
        at io.trino.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:594)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
        at io.trino.$gen.Trino_358____20210627_101935_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

trino>

**Comment by kokosing** [comment]
Alluxio metastore does not support many operation. It does not support `CREATE SCHEMA` or `DROP` or `RENAME`.... Same goes to `CREATE TABLE`. From what I understand it is read-only metastore.
