### ISSUE TITLE
Cannot overwrite partitioning with SINGLE (currently set to Optional[HASH]) [DB Errorcode=65536]

### ISSUE THREAD

**Issue by rsaw4** [trinodb/trino#8401]
Query:
```
select *
FROM
    (SELECT
  rates.*
, (CASE WHEN (rates.label LIKE '%#%') THEN concat(split_part(rates.label, '#', 1), '#') ELSE rates.label END) short_label
FROM
  (schema_a.table_a rates
INNER JOIN (
   SELECT a.*
   FROM
     (
      SELECT
        b.label
      , b.path
      , b.refdate
      , b.batch_id
      , ROW_NUMBER() OVER (PARTITION BY label, path, refdate ORDER BY batch_id DESC) row_no
      FROM
        schema_a.table_a b
      GROUP BY b.label, b.path, b.refdate, b.batch_id
   )  a
   WHERE (a.row_no = 1)
)  ld ON ((((rates.batch_id = ld.batch_id) AND (rates.label = ld.label)) AND (rates.path = ld.path)) AND (rates.refdate = ld.refdate)))) rates
        LEFT OUTER JOIN (SELECT
  rates.short_label label
, rates.path
, rates.payload
, rates.filename
, rates.refdate
, rates.load_date
, (CASE WHEN (substr(path, 1, 22) = 'HISTORIC.INTEREST_RATE') THEN split_part(path, '.', 3) ELSE null END) currency
, (CASE WHEN (substr(path, 1, 40) = 'HISTORIC.INTEREST_RATE.CHF.CHFSWAP_YIELD') THEN 'CHFSWAP_YIELD' WHEN (substr(path, 1, 22) = 'HISTORIC.INTEREST_RATE') THEN split_part(split_part(path, '.', 4), '_', 1) ELSE null END) index
, (CASE WHEN (substr(path, 1, 40) = 'HISTORIC.INTEREST_RATE.CHF.CHFSWAP_YIELD') THEN split_part(path, '_', -1) WHEN (substr(path, 1, 22) = 'HISTORIC.INTEREST_RATE') THEN split_part(split_part(path, '.', 4), '_', 2) ELSE null END) tenor
FROM
  ( SELECT
  rates.*
, (CASE WHEN (rates.label LIKE '%#%') THEN concat(split_part(rates.label, '#', 1), '#') ELSE rates.label END) short_label
FROM
  (schema_a.table_b rates
INNER JOIN (
   SELECT a.*
   FROM
     (
      SELECT
        b.label
      , b.path
      , b.refdate
      , b.batch_id
      , ROW_NUMBER() OVER (PARTITION BY label, path, refdate ORDER BY batch_id DESC) row_no
      FROM
        schema_a.table_b b
      GROUP BY b.label, b.path, b.refdate, b.batch_id
   )  a
   WHERE (a.row_no = 1)
)  ld ON ((((rates.batch_id = ld.batch_id) AND (rates.label = ld.label)) AND (rates.path = ld.path)) AND (rates.refdate = ld.refdate)))) rates
WHERE ((rates.short_label = 'ZZZ#') AND (substr(rates.path, 1, 23) = 'HISTORIC.INTEREST_RATE.'))) rates_base ON
            rates.label = rates_base.label
            AND rates.path = rates_base.path
            AND rates.refdate = rates_base.refdate
WHERE
    rates.short_label = 'ZZZ#'
    AND substr(rates.path,1,23) = 'HISTORIC.INTEREST_RATE.';
	
```

error:
```
java.lang.IllegalStateException: Cannot overwrite partitioning with SINGLE (currently set to Optional[HASH])
	at com.google.common.base.Preconditions.checkState(Preconditions.java:824)
	at io.prestosql.sql.planner.PlanFragmenter$FragmentProperties.setSingleNodeDistribution(PlanFragmenter.java:400)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.visitValues(PlanFragmenter.java:329)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.visitValues(PlanFragmenter.java:214)
	at io.prestosql.sql.planner.plan.ValuesNode.accept(ValuesNode.java:73)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Collections$2.tryAdvance(Unknown Source)
	at java.base/java.util.Collections$2.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at io.prestosql.sql.planner.plan.PlanVisitor.visitProject(PlanVisitor.java:39)
	at io.prestosql.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Collections$2.tryAdvance(Unknown Source)
	at java.base/java.util.Collections$2.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:337)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:214)
	at io.prestosql.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at io.prestosql.sql.planner.plan.PlanVisitor.visitJoin(PlanVisitor.java:94)
	at io.prestosql.sql.planner.plan.JoinNode.accept(JoinNode.java:320)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Collections$2.tryAdvance(Unknown Source)
	at java.base/java.util.Collections$2.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at io.prestosql.sql.planner.plan.PlanVisitor.visitProject(PlanVisitor.java:39)
	at io.prestosql.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Collections$2.tryAdvance(Unknown Source)
	at java.base/java.util.Collections$2.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at io.prestosql.sql.planner.plan.PlanVisitor.visitProject(PlanVisitor.java:39)
	at io.prestosql.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.buildSubPlan(PlanFragmenter.java:369)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:352)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:214)
	at io.prestosql.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Collections$2.tryAdvance(Unknown Source)
	at java.base/java.util.Collections$2.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:337)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:214)
	at io.prestosql.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at io.prestosql.sql.planner.plan.PlanVisitor.visitJoin(PlanVisitor.java:94)
	at io.prestosql.sql.planner.plan.JoinNode.accept(JoinNode.java:320)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.buildSubPlan(PlanFragmenter.java:369)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:352)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:214)
	at io.prestosql.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Collections$2.tryAdvance(Unknown Source)
	at java.base/java.util.Collections$2.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.visitOutput(PlanFragmenter.java:274)
	at io.prestosql.sql.planner.PlanFragmenter$Fragmenter.visitOutput(PlanFragmenter.java:214)
	at io.prestosql.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at io.prestosql.sql.planner.PlanFragmenter.createSubPlans(PlanFragmenter.java:114)
	at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:423)
	at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:401)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:356)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132)
	at io.prestosql.$gen.Presto_20f5dc9____20210625_031538_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

prestosql version 336, hive catalog on s3/parquet
note that schema_a.table_a table is empty but schema_a.table_b has some rows.

a workaround to make it work is ```set session  join_distribution_type='BROADCAST'```

but without changing session property or ```set session  join_distribution_type='AUTOMATIC'``` or ```set session  join_distribution_type='PARTITIONED' ``` it fails consistently. Also trying to run the query with EXPLAIN in front gives same error

jmx shows below difference from before/after query was run. nothing shows in failures column

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<body link="#0563C1" vlink="#954F72">

  | time.count | hits
-- | -- | --
presto.sql.planner.iterative:name=IterativeOptimizer,rule=ProjectExpressionRewrite | 322648 | 13
presto.sql.planner.iterative:name=IterativeOptimizer,rule=FilterExpressionRewrite | 485960 | 26
presto.sql.planner.iterative:name=IterativeOptimizer,rule=PruneProjectColumns | 485301 | 31
presto.sql.planner.iterative:name=IterativeOptimizer,rule=RemoveRedundantIdentityProjections | 4758970 | 208
presto.sql.planner.iterative:name=IterativeOptimizer,rule=RemoveTrivialFilters | 0 | 8
presto.sql.planner.iterative:name=IterativeOptimizer,rule=PruneFilterColumns | 484031 | 15
presto.sql.planner.iterative:name=IterativeOptimizer,rule=PushPredicateIntoTableScan | 323697 | 8
presto.sql.planner.iterative:name=IterativeOptimizer,rule=PushPartialAggregationThroughExchange | 967896 | 24
presto.sql.planner.iterative:name=IterativeOptimizer,rule=PruneTableScanColumns | 744222 | 23
presto.sql.planner.iterative:name=IterativeOptimizer,rule=AddIntermediateAggregations | 322617 | 8
presto.sql.planner.iterative:name=IterativeOptimizer,rule=PruneApplyColumns | 161307 | 4
presto.sql.planner.iterative:name=IterativeOptimizer,rule=InlineProjections | 6 | 1
presto.sql.planner.iterative:name=IterativeOptimizer,rule=TransformUncorrelatedInPredicateSubqueryToSemiJoin | 161307 | 4
presto.sql.planner.iterative:name=IterativeOptimizer,rule=DetermineSemiJoinDistributionType | 161307 | 4
presto.sql.planner.iterative:name=IterativeOptimizer,rule=PruneJoinChildrenColumns | 30 | 2
presto.sql.planner.iterative:name=IterativeOptimizer,rule=PruneJoinColumns | 30 | 3
presto.sql.planner.iterative:name=IterativeOptimizer,rule=PruneWindowColumns | 11 | 2
presto.sql.planner.iterative:name=IterativeOptimizer,rule=DetermineJoinDistributionType | 30 | 3

</body>

</html>

**Comment by tooptoop4** [comment]
cc: @kasiafi

**Comment by findepi** [comment]
@rsaw4 is this problem reproducible with Trino 359?

**Comment by tooptoop4** [comment]
no error in 359 😲

**Comment by findepi** [comment]
@rsaw4 can you please confirm whether this works in your environment as well, per @tooptoop4 's comment?

i am closing for now, but please reopen if you still experience this issue with 359.

**Comment by findepi** [comment]
Someone witnessed similar error in 366 -> https://github.com/trinodb/trino/issues/10887
