### ISSUE TITLE
TestAccumuloConnectorTest#testView is flaky

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#8410]
```
2021-06-28T16:23:31.5877098Z [ERROR] testView(io.trino.plugin.accumulo.TestAccumuloConnectorTest)  Time elapsed: 0.922 s  <<< FAILURE!
2021-06-28T16:23:31.5880046Z java.lang.RuntimeException: No value present
2021-06-28T16:23:31.5883467Z 	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:120)
2021-06-28T16:23:31.5886972Z 	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:476)
2021-06-28T16:23:31.5890305Z 	at io.trino.sql.query.QueryAssertions$QueryAssert.newQueryAssert(QueryAssertions.java:263)
2021-06-28T16:23:31.5893856Z 	at io.trino.sql.query.QueryAssertions.query(QueryAssertions.java:111)
2021-06-28T16:23:31.5897696Z 	at io.trino.testing.AbstractTestQueryFramework.query(AbstractTestQueryFramework.java:152)
2021-06-28T16:23:31.5901911Z 	at io.trino.testing.AbstractTestQueryFramework.query(AbstractTestQueryFramework.java:147)
2021-06-28T16:23:31.5906312Z 	at io.trino.testing.AbstractTestDistributedQueries.testView(AbstractTestDistributedQueries.java:761)
2021-06-28T16:23:31.5910942Z 	at io.trino.testing.BaseConnectorTest.testView(BaseConnectorTest.java:405)
2021-06-28T16:23:31.5915471Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-06-28T16:23:31.5920772Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-06-28T16:23:31.5934786Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-06-28T16:23:31.5936228Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-06-28T16:23:31.5937532Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-06-28T16:23:31.5938915Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-06-28T16:23:31.5939962Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-06-28T16:23:31.5941111Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-06-28T16:23:31.5942491Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-06-28T16:23:31.5943879Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-06-28T16:23:31.5945197Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-06-28T16:23:31.5946602Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-06-28T16:23:31.5947512Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-06-28T16:23:31.5948805Z 	Suppressed: java.lang.Exception: SQL: SELECT table_name, comment FROM system.metadata.table_comments WHERE catalog_name = 'accumulo' AND schema_name = 'tpch'
2021-06-28T16:23:31.5950155Z 		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:479)
2021-06-28T16:23:31.5951019Z 		... 19 more
2021-06-28T16:23:31.6098647Z Caused by: java.util.NoSuchElementException: No value present
2021-06-28T16:23:31.6100022Z 	at java.base/java.util.Optional.get(Optional.java:148)
2021-06-28T16:23:31.6105988Z 	at io.trino.connector.system.TableCommentSystemTable.getComment(TableCommentSystemTable.java:155)
2021-06-28T16:23:31.6109184Z 	at io.trino.connector.system.TableCommentSystemTable.cursor(TableCommentSystemTable.java:123)
2021-06-28T16:23:31.6112067Z 	at io.trino.connector.system.SystemPageSourceProvider$1.cursor(SystemPageSourceProvider.java:129)
2021-06-28T16:23:31.6114009Z 	at io.trino.split.MappedRecordSet.cursor(MappedRecordSet.java:53)
2021-06-28T16:23:31.6115583Z 	at io.trino.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
2021-06-28T16:23:31.6118108Z 	at io.trino.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:108)
2021-06-28T16:23:31.6120848Z 	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
2021-06-28T16:23:31.6123011Z 	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:257)
2021-06-28T16:23:31.6124847Z 	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:185)
2021-06-28T16:23:31.6126322Z 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
2021-06-28T16:23:31.6127601Z 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2021-06-28T16:23:31.6128859Z 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
2021-06-28T16:23:31.6130125Z 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2021-06-28T16:23:31.6131384Z 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
2021-06-28T16:23:31.6132655Z 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2021-06-28T16:23:31.6134166Z 	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
2021-06-28T16:23:31.6135852Z 	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
2021-06-28T16:23:31.6137304Z 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2021-06-28T16:23:31.6138737Z 	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
2021-06-28T16:23:31.6140135Z 	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
2021-06-28T16:23:31.6141509Z 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2021-06-28T16:23:31.6143440Z 	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:150)
2021-06-28T16:23:31.6145136Z 	at io.trino.operator.Driver.processInternal(Driver.java:387)
2021-06-28T16:23:31.6146011Z 	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
2021-06-28T16:23:31.6146845Z 	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
2021-06-28T16:23:31.6147675Z 	at io.trino.operator.Driver.processFor(Driver.java:284)
2021-06-28T16:23:31.6148992Z 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
2021-06-28T16:23:31.6150989Z 	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
2021-06-28T16:23:31.6152768Z 	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
2021-06-28T16:23:31.6153775Z 	at io.trino.$gen.Trino_testversion____20210628_161833_3.run(Unknown Source)
2021-06-28T16:23:31.6154975Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-06-28T16:23:31.6156599Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-06-28T16:23:31.6157654Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-06-28T16:23:31.6158920Z 
```
https://github.com/trinodb/trino/pull/8408/checks?check_run_id=2933585241

**Comment by ebyhr** [comment]
Going to close as it's probably fixed in #8443. Let's reopen if the same issue happened.
