### ISSUE TITLE
Access Denied when run  SQL command DROP TABLE or ALTER TABLE RENAME TO

### ISSUE THREAD

**Issue by hanson2021** [trinodb/trino#8428]
Refer to :https://trino.io/docs/358/security/file-system-access-control.html?highlight=drop%20table

when  run  SQL command : DROP TABLE or ALTER TABLE RENAME TO
trino> create table hive.bi_test.aa1(a int);                     
CREATE TABLE
trino> select * from  hive.bi_test.aa1;
 a 
(0 rows)
Query 20210630_083711_01084_iky9a, FINISHED, 2 nodes
Splits: 17 total, 17 done (100.00%)
0.23 [0 rows, 0B] [0 rows/s, 0B/s]
trino> drop table hive.bi_test.aa1;
Query 20210630_083632_01083_iky9a failed: Access Denied: Cannot drop table bi_test.aa1
trino> alter table hive.bi_test.aa1 rename to hive.bi_test.aa2;    
Query 20210630_083608_01082_iky9a failed: Access Denied: Cannot rename table from bi_test.aa1 to bi_test.aa2;**

**Comment by ssquan** [comment]
Enable debug in client if you want to get more informations. And you can ask this kind of question in trinodb slack for a quick response.

**Comment by hanson2021** [comment]
> Enable debug in client if you want to get more informations. And you can ask this kind of question in trinodb slack for a quick response.
The Debug Info as following :
trino> drop table hive.bi_test.aa1;
Query 20210703_023832_00263_iky9a failed: Access Denied: Cannot drop table bi_test.aa1
io.trino.spi.security.AccessDeniedException: Access Denied: Cannot drop table bi_test.aa1
        at io.trino.spi.security.AccessDeniedException.denyDropTable(AccessDeniedException.java:198)
        at io.trino.spi.security.AccessDeniedException.denyDropTable(AccessDeniedException.java:193)
        at io.trino.plugin.hive.security.LegacyAccessControl.checkCanDropTable(LegacyAccessControl.java:121)
        at io.trino.plugin.base.security.ForwardingConnectorAccessControl.checkCanDropTable(ForwardingConnectorAccessControl.java:106)
        at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorAccessControl.checkCanDropTable(ClassLoaderSafeConnectorAccessControl.java:122)
        at io.trino.security.AccessControlManager.lambda$checkCanDropTable$25(AccessControlManager.java:423)
        at io.trino.security.AccessControlManager.catalogAuthorizationCheck(AccessControlManager.java:1087)
        at io.trino.security.AccessControlManager.checkCanDropTable(AccessControlManager.java:423)
        at io.trino.security.ForwardingAccessControl.checkCanDropTable(ForwardingAccessControl.java:164)
        at io.trino.execution.DropTableTask.execute(DropTableTask.java:65)
        at io.trino.execution.DropTableTask.execute(DropTableTask.java:35)
        at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:170)
        at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
        at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
        at io.trino.$gen.Trino_358____20210609_042826_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by hanson2021** [comment]
> Enable debug in client if you want to get more informations. And you can ask this kind of question in trinodb slack for a quick response.

trino> alter table hive.bi_test.aa1 rename to hive.bi_test.aa2; 
Query 20210703_024107_00289_iky9a failed: Access Denied: Cannot rename table from bi_test.aa1 to bi_test.aa2
io.trino.spi.security.AccessDeniedException: Access Denied: Cannot rename table from bi_test.aa1 to bi_test.aa2
        at io.trino.spi.security.AccessDeniedException.denyRenameTable(AccessDeniedException.java:208)
        at io.trino.spi.security.AccessDeniedException.denyRenameTable(AccessDeniedException.java:203)
        at io.trino.plugin.hive.security.LegacyAccessControl.checkCanRenameTable(LegacyAccessControl.java:139)
        at io.trino.plugin.base.security.ForwardingConnectorAccessControl.checkCanRenameTable(ForwardingConnectorAccessControl.java:112)
        at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorAccessControl.checkCanRenameTable(ClassLoaderSafeConnectorAccessControl.java:130)
        at io.trino.security.AccessControlManager.lambda$checkCanRenameTable$27(AccessControlManager.java:437)
        at io.trino.security.AccessControlManager.catalogAuthorizationCheck(AccessControlManager.java:1087)
        at io.trino.security.AccessControlManager.checkCanRenameTable(AccessControlManager.java:437)
        at io.trino.security.ForwardingAccessControl.checkCanRenameTable(ForwardingAccessControl.java:170)
        at io.trino.execution.RenameTableTask.execute(RenameTableTask.java:77)
        at io.trino.execution.RenameTableTask.execute(RenameTableTask.java:38)
        at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:170)
        at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
        at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
        at io.trino.$gen.Trino_358____20210609_042826_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by haldes** [comment]
@hanson2021  try setting hive.allow-rename-table=true at the catalog level.

**Comment by hanson2021** [comment]
> @hanson2021 try setting hive.allow-rename-table=true at the catalog level.

**Comment by hashhar** [comment]
@hanson2021 Glad it worked for you. Here's some explanation to make sense of what's happenning.

The system access control (file-based that you are using) is allowed to limit permissions to what people can do on the entire cluster. It sits a level above the catalog specific permissions.

In case of Hive - take a look at https://trino.io/docs/current/connector/hive-security.html. That explains all you need to know.

For example, if you allow a user to SELECT from a table using file-based system access control but the underlying Postgres database doesn't allow the user to SELECT then the user won't be able to select. Trino can't bypass the underlying access control mechanisms of the data source.

Also for faster and better troubleshooting help, feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there.
We try to keep GitHub issues for the bugs and enhancements within Trino.

**Comment by hanson2021** [comment]
> @hanson2021 try setting hive.allow-rename-table=true at the catalog level.

@haldes ，you are right,thanks ,I forget it to set hive.xx true at  the  hive catalog level.

**Comment by JevonYang** [comment]
I tried this setting, buts shows below

```
2022-08-30T12:20:11.777Z	ERROR	main	io.trino.server.Server	Configuration errors:
1) Error: Configuration property 'hive.allow-rename-table' was not used
1 error
io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:
1) Error: Configuration property 'hive.allow-rename-table' was not used
1 error
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:234)
	at io.trino.plugin.iceberg.InternalIcebergConnectorFactory.createConnector(InternalIcebergConnectorFactory.java:110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.trino.plugin.iceberg.IcebergConnectorFactory.create(IcebergConnectorFactory.java:62)
	at io.trino.connector.DefaultCatalogFactory.createConnector(DefaultCatalogFactory.java:201)
	at io.trino.connector.DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:123)
	at io.trino.connector.LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:44)
	at io.trino.connector.StaticCatalogManager.loadInitialCatalogs(StaticCatalogManager.java:139)
	at io.trino.server.Server.doStart(Server.java:139)
	at io.trino.server.Server.lambda$start$0(Server.java:88)
	at io.trino.$gen.Trino_394____20220830_121949_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:88)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
```

**Comment by hashhar** [comment]
@JevonYang You seem to be using the Iceberg connector, not the Hive connector.
