### ISSUE TITLE
TestMySqlCaseInsensitiveMapping is flaky

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#8477]
```
Error:  Tests run: 256, Failures: 2, Errors: 0, Skipped: 10, Time elapsed: 433.45 s <<< FAILURE! - in TestSuite
Error:  testSchemaNameClashWithRuleMapping(io.trino.plugin.mysql.TestMySqlCaseInsensitiveMapping)  Time elapsed: 0.037 s  <<< FAILURE!
java.lang.RuntimeException: java.sql.SQLException: Can't create database 'casesensitivename'; database exists
	at io.trino.plugin.mysql.TestingMySqlServer.execute(TestingMySqlServer.java:79)
	at io.trino.plugin.mysql.TestingMySqlServer.execute(TestingMySqlServer.java:69)
	at io.trino.plugin.jdbc.BaseCaseInsensitiveMappingTest.withSchema(BaseCaseInsensitiveMappingTest.java:316)
	at io.trino.plugin.jdbc.BaseCaseInsensitiveMappingTest.testSchemaNameClashWithRuleMapping(BaseCaseInsensitiveMappingTest.java:213)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: Can't create database 'casesensitivename'; database exists
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at io.trino.plugin.mysql.TestingMySqlServer.execute(TestingMySqlServer.java:76)
	... 16 more

Error:  testTableNameClashWithRuleMapping(io.trino.plugin.mysql.TestMySqlCaseInsensitiveMapping)  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Table 'casesensitivename' already exists
	at io.trino.plugin.mysql.TestingMySqlServer.execute(TestingMySqlServer.java:79)
	at io.trino.plugin.mysql.TestingMySqlServer.execute(TestingMySqlServer.java:69)
	at io.trino.plugin.jdbc.BaseCaseInsensitiveMappingTest.withTable(BaseCaseInsensitiveMappingTest.java:323)
	at io.trino.plugin.jdbc.BaseCaseInsensitiveMappingTest.withTable(BaseCaseInsensitiveMappingTest.java:336)
	at io.trino.plugin.jdbc.BaseCaseInsensitiveMappingTest.testTableNameClashWithRuleMapping(BaseCaseInsensitiveMappingTest.java:273)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLSyntaxErrorException: Table 'casesensitivename' already exists
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at io.trino.plugin.mysql.TestingMySqlServer.execute(TestingMySqlServer.java:76)
	... 17 more
```

One of the possible causes could be that the schema names being used across the tests are the same. Verify if the `@Test(singleThreaded = true)` is being respected.

Another possibility is that the assertions are running before the rules have been reloaded.

**Comment by hashhar** [comment]
Noticed in https://github.com/trinodb/trino/runs/2998058600?check_suite_focus=true
