### ISSUE TITLE
Trino CLI prints exceptions to stdout when pressing Tab for completion

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#8481]
Since version 359:

```sql
# Press TAB after any input
trino> SHOW TAJul 06, 2021 11:35:35 PM org.jline.utils.Log logr
INFO: Error while parsing line
org.jline.reader.EOFError
	at io.trino.cli.InputParser.parse(InputParser.java:46)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4389)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4365)
	at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4304)
	at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3798)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:670)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:498)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:484)
	at io.trino.cli.InputReader.readLine(InputReader.java:59)
	at io.trino.cli.Console.runConsole(Console.java:239)
	at io.trino.cli.Console.run(Console.java:191)
	at io.trino.cli.Console.call(Console.java:102)
	at io.trino.cli.Console.call(Console.java:75)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.trino.cli.Trino.main(Trino.java:42)
```

This seems to be introduced in https://github.com/trinodb/trino/commit/dabd7fe45f. It's the first commit that can reproduce this issue.

cc: @electrum

**Comment by hashhar** [comment]
Notice that the exception is just printed and the  prompt is still active. So if you input `SHOW TABLES`, press TAB then the exception will be printed but you can then press ENTER and the query runs successfully.

**Comment by hashhar** [comment]
Seems like `Logging.initialize` has the side effect of redirecting stdout and stderr to the logger via https://github.com/airlift/airlift/blob/29e304b3f186da3d20507f3929a2a3f019de653a/log-manager/src/main/java/io/airlift/log/Logging.java#L95-L99

Maybe we need to add something similar here again?

**Comment by lucasdlemos** [comment]
@hashhar It seems the cli completion feature has been broken for a while. #8495 mentions that it just silently didn't work before and recently it started printing the exception to stdout.

If think I know the fix. If that's ok I can work on that.

**Comment by hashhar** [comment]
Sure, go ahead @lucasdlemos. Thanks a lot.
