### ISSUE TITLE
Can't created managed table against Hive v3

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#8564]
SQL:
```
create table somesch.zdummy5 as
select trade_id from somesch.sometbl  limit 0
```

error:
```
io.prestosql.spi.PrestoException: Insert of object "org.apache.hadoop.hive.metastore.model.MTableColumnStatistics@1fea18de" using statement "INSERT INTO `TAB_COL_STATS` (`CS_ID`,`AVG_COL_LEN`,`BIT_VECTOR`,`CAT_NAME`,`COLUMN_NAME`,`COLUMN_TYPE`,`DB_NAME`,`BIG_DECIMAL_HIGH_VALUE`,`BIG_DECIMAL_LOW_VALUE`,`DOUBLE_HIGH_VALUE`,`DOUBLE_LOW_VALUE`,`ENGINE`,`LAST_ANALYZED`,`LONG_HIGH_VALUE`,`LONG_LOW_VALUE`,`MAX_COL_LEN`,`NUM_DISTINCTS`,`NUM_FALSES`,`NUM_NULLS`,`NUM_TRUES`,`TBL_ID`,`TABLE_NAME`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)" failed : Column 'ENGINE' cannot be null
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.setTableColumnStatistics(ThriftHiveMetastore.java:554)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.updateTableStatistics(ThriftHiveMetastore.java:529)
	at io.prestosql.plugin.hive.metastore.thrift.BridgingHiveMetastore.updateTableStatistics(BridgingHiveMetastore.java:122)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.updateTableStatistics(CachingHiveMetastore.java:378)
	at io.prestosql.plugin.hive.HiveMetastoreClosure.updateTableStatistics(HiveMetastoreClosure.java:93)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore$UpdateStatisticsOperation.run(SemiTransactionalHiveMetastore.java:2784)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeUpdateStatisticsOperations(SemiTransactionalHiveMetastore.java:1612)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:1145)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:965)
	at io.prestosql.plugin.hive.HiveMetadata.commit(HiveMetadata.java:2614)
	at io.prestosql.plugin.hive.HiveConnector.commit(HiveConnector.java:212)
	at io.prestosql.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:594)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at io.prestosql.$gen.Presto_20f5dc9____20210714_120418_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: Insert of object "org.apache.hadoop.hive.metastore.model.MTableColumnStatistics@1fea18de" using statement "INSERT INTO `TAB_COL_STATS` (`CS_ID`,`AVG_COL_LEN`,`BIT_VECTOR`,`CAT_NAME`,`COLUMN_NAME`,`COLUMN_TYPE`,`DB_NAME`,`BIG_DECIMAL_HIGH_VALUE`,`BIG_DECIMAL_LOW_VALUE`,`DOUBLE_HIGH_VALUE`,`DOUBLE_LOW_VALUE`,`ENGINE`,`LAST_ANALYZED`,`LONG_HIGH_VALUE`,`LONG_LOW_VALUE`,`MAX_COL_LEN`,`NUM_DISTINCTS`,`NUM_FALSES`,`NUM_NULLS`,`NUM_TRUES`,`TBL_ID`,`TABLE_NAME`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)" failed : Column 'ENGINE' cannot be null
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$update_table_column_statistics_result$update_table_column_statistics_resultStandardScheme.read(ThriftHiveMetastore.java)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$update_table_column_statistics_result$update_table_column_statistics_resultStandardScheme.read(ThriftHiveMetastore.java)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$update_table_column_statistics_result.read(ThriftHiveMetastore.java)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_update_table_column_statistics(ThriftHiveMetastore.java:3839)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.update_table_column_statistics(ThriftHiveMetastore.java:3826)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.setTableColumnStatistics(ThriftHiveMetastoreClient.java:215)
	at io.prestosql.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.lambda$setTableColumnStatistics$14(FailureAwareThriftMetastoreClient.java:178)
	at io.prestosql.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.runWithHandle(FailureAwareThriftMetastoreClient.java:422)
	at io.prestosql.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.setTableColumnStatistics(FailureAwareThriftMetastoreClient.java:178)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$setTableColumnStatistics$21(ThriftHiveMetastore.java:546)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.setColumnStatistics(ThriftHiveMetastore.java:695)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$setTableColumnStatistics$22(ThriftHiveMetastore.java:542)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
	at io.prestosql.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.setTableColumnStatistics(ThriftHiveMetastore.java:541)
	... 20 more
```

my hive version is 3.1.3000.7.1.4.35-1
prestosql v336
related to https://github.com/trinodb/trino/issues/8548

**Comment by ans76** [comment]
Did you check the column `ENGINE` in `TAB_COL_STATS`?  [hive-metastore-schema](https://cwiki.apache.org/confluence/display/Hive/Column+Statistics+in+Hive#ColumnStatisticsinHive-MetastoreSchema) not describe it
