### ISSUE TITLE
How to access elasticsearch with authentication information?

### ISSUE THREAD

**Issue by mortalsWorld** [trinodb/trino#8593]
My configuration file is as follows:

```
connector.name=elasticsearch
elasticsearch.host=xxx
elasticsearch.port=9200
elasticsearch.default-schema-name=default
elasticsearch.scroll-size=5000
elasticsearch.scroll-timeout = 30s
elasticsearch.request-timeout = 60s
elasticsearch.connect-timeout = 60s
elasticsearch.max-retry-time = 30s
elasticsearch.node-refresh-interval = 1s
elasticsearch.max-http-connections=50
elasticsearch.http-thread-count=4
elasticsearch.auth.user=xxx
elasticsearch.auth.password=xxx
elasticsearch.security=PASSWORD
elasticsearch.tls.enabled=true
elasticsearch.tls.keystore-path=/opt/pem/http.pem
elasticsearch.tls.truststore-path=/opt/pem/elastic-certificates.pem
```

After using the certificate, it keeps saying that the connection is refused. When tls is not turned on and only uses password authentication, it keeps saying that the connection is closed. How do I set it up? A configuration file has been provided, can you tell me what the problem is?

**Comment by sumannewton** [comment]
Can you please share server & client (cli) logs?

**Comment by mortalsWorld** [comment]
The content of the error is as follows:
```
2021-07-19T17:45:17.541+0800    INFO    main    io.trino.metadata.StaticCatalogStore    -- Loading catalog etc/catalog/elasticsearch.properties --
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       PROPERTY                               DEFAULT     RUNTIME                            DESCRIPTION
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       jmx.base-name                          ----        ----
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.backoff-init-delay       500.00ms    500.00ms                           Initial delay to wait between backpressure retries
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.backoff-max-delay        20.00s      20.00s                             Maximum delay to wait between backpressure retries
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.connect-timeout          1.00s       60.00s                             Elasticsearch connect timeout
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.default-schema-name      default     default                            Default schema name to use
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.host                     ----        xxx.xxx.xxx.xxx
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.http-thread-count        4           4                                  Number of threads handling HTTP connections to Elasticsearch
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.ignore-publish-address   false       false
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.tls.keystore-password    [REDACTED]  [REDACTED]
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.tls.keystore-path        ----        /opt/pem/http.pem
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.max-http-connections     25          50                                 Maximum number of persistent HTTP connections to Elasticsearch
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.max-retry-time           30.00s      30.00s                             Maximum timeout in case of multiple retries
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.node-refresh-interval    1.00m       1.00s                              How often to refresh the list of available Elasticsearch nodes
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.port                     9200        9200
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.request-timeout          10.00s      60.00s                             Elasticsearch request timeout
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.scroll-size              1000        5000                               Scroll batch size
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.scroll-timeout           1.00m       30.00s                             Scroll timeout
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.security                 ----        PASSWORD
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.tls.enabled              false       true
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.tls.truststore-path      ----        /opt/pem/elastic-certificates.pem
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.tls.truststore-password  [REDACTED]  [REDACTED]
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.tls.verify-hostnames     true        true
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.auth.password            [REDACTED]  [REDACTED]
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.auth.user                ----        xxx
2021-07-19T17:45:19.969+0800    INFO    main    io.airlift.bootstrap.LifeCycleManager   Life cycle starting...
2021-07-19T17:45:19.970+0800    INFO    main    io.airlift.bootstrap.LifeCycleManager   Life cycle startup complete
2021-07-19T17:45:19.971+0800    INFO    main    io.trino.metadata.StaticCatalogStore    -- Added catalog elasticsearch using connector elasticsearch --
2021-07-19T17:45:19.974+0800    INFO    main    io.trino.security.AccessControlManager  Using system access control default
2021-07-19T17:45:20.019+0800    INFO    main    io.trino.server.Server  ======== SERVER STARTED ========
2021-07-19T17:45:20.944+0800    ERROR   NodeRefresher   io.trino.plugin.elasticsearch.client.ElasticsearchClient        Error refreshing nodes
io.trino.spi.TrinoException: 拒绝连接
        at io.trino.plugin.elasticsearch.client.ElasticsearchClient.doRequest(ElasticsearchClient.java:803)
        at io.trino.plugin.elasticsearch.client.ElasticsearchClient.fetchNodes(ElasticsearchClient.java:381)
        at io.trino.plugin.elasticsearch.client.ElasticsearchClient.refreshNodes(ElasticsearchClient.java:185)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mortalsWorld** [comment]
> Can you please share server & client (cli) logs?
The content of the error is as follows:
```
2021-07-19T17:45:17.541+0800    INFO    main    io.trino.metadata.StaticCatalogStore    -- Loading catalog etc/catalog/elasticsearch.properties --
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       PROPERTY                               DEFAULT     RUNTIME                            DESCRIPTION
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       jmx.base-name                          ----        ----
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.backoff-init-delay       500.00ms    500.00ms                           Initial delay to wait between backpressure retries
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.backoff-max-delay        20.00s      20.00s                             Maximum delay to wait between backpressure retries
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.connect-timeout          1.00s       60.00s                             Elasticsearch connect timeout
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.default-schema-name      default     default                            Default schema name to use
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.host                     ----        xxx.xxx.xxx.xxx
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.http-thread-count        4           4                                  Number of threads handling HTTP connections to Elasticsearch
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.ignore-publish-address   false       false
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.tls.keystore-password    [REDACTED]  [REDACTED]
2021-07-19T17:45:18.189+0800    INFO    main    Bootstrap       elasticsearch.tls.keystore-path        ----        /opt/pem/http.pem
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.max-http-connections     25          50                                 Maximum number of persistent HTTP connections to Elasticsearch
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.max-retry-time           30.00s      30.00s                             Maximum timeout in case of multiple retries
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.node-refresh-interval    1.00m       1.00s                              How often to refresh the list of available Elasticsearch nodes
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.port                     9200        9200
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.request-timeout          10.00s      60.00s                             Elasticsearch request timeout
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.scroll-size              1000        5000                               Scroll batch size
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.scroll-timeout           1.00m       30.00s                             Scroll timeout
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.security                 ----        PASSWORD
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.tls.enabled              false       true
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.tls.truststore-path      ----        /opt/pem/elastic-certificates.pem
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.tls.truststore-password  [REDACTED]  [REDACTED]
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.tls.verify-hostnames     true        true
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.auth.password            [REDACTED]  [REDACTED]
2021-07-19T17:45:18.190+0800    INFO    main    Bootstrap       elasticsearch.auth.user                ----        xxx
2021-07-19T17:45:19.969+0800    INFO    main    io.airlift.bootstrap.LifeCycleManager   Life cycle starting...
2021-07-19T17:45:19.970+0800    INFO    main    io.airlift.bootstrap.LifeCycleManager   Life cycle startup complete
2021-07-19T17:45:19.971+0800    INFO    main    io.trino.metadata.StaticCatalogStore    -- Added catalog elasticsearch using connector elasticsearch --
2021-07-19T17:45:19.974+0800    INFO    main    io.trino.security.AccessControlManager  Using system access control default
2021-07-19T17:45:20.019+0800    INFO    main    io.trino.server.Server  ======== SERVER STARTED ========
2021-07-19T17:45:20.944+0800    ERROR   NodeRefresher   io.trino.plugin.elasticsearch.client.ElasticsearchClient        Error refreshing nodes
io.trino.spi.TrinoException: 拒绝连接
        at io.trino.plugin.elasticsearch.client.ElasticsearchClient.doRequest(ElasticsearchClient.java:803)
        at io.trino.plugin.elasticsearch.client.ElasticsearchClient.fetchNodes(ElasticsearchClient.java:381)
        at io.trino.plugin.elasticsearch.client.ElasticsearchClient.refreshNodes(ElasticsearchClient.java:185)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mortalsWorld** [comment]
Need to add `elasticsearch.ignore-publish-address=true` in the elasticsearch.properties file.
