### ISSUE TITLE
Flaky test TestFullParquetReader.testMapSchemas: Overflow detected in ZSTD

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#8602]
https://github.com/trinodb/trino/runs/3103919905
```
Error:  Tests run: 83, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 629.926 s <<< FAILURE! - in io.trino.plugin.hive.parquet.TestFullParquetReader
Error:  testMapSchemas(io.trino.plugin.hive.parquet.TestFullParquetReader)  Time elapsed: 5.476 s  <<< FAILURE!
java.lang.IllegalStateException: Overflow detected
	at io.airlift.compress.zstd.Util.checkState(Util.java:59)
	at io.airlift.compress.zstd.BitOutputStream.close(BitOutputStream.java:85)
	at io.airlift.compress.zstd.HuffmanCompressor.compressSingleStream(HuffmanCompressor.java:130)
	at io.airlift.compress.zstd.HuffmanCompressor.compress4streams(HuffmanCompressor.java:75)
	at io.airlift.compress.zstd.ZstdFrameCompressor.encodeLiterals(ZstdFrameCompressor.java:333)
	at io.airlift.compress.zstd.ZstdFrameCompressor.compressBlock(ZstdFrameCompressor.java:224)
	at io.airlift.compress.zstd.ZstdFrameCompressor.compressFrame(ZstdFrameCompressor.java:172)
	at io.airlift.compress.zstd.ZstdFrameCompressor.compress(ZstdFrameCompressor.java:145)
	at io.airlift.compress.zstd.ZstdCompressor.compress(ZstdCompressor.java:45)
	at io.trino.parquet.writer.ParquetCompressor$AirLiftCompressor.compress(ParquetCompressor.java:93)
	at io.trino.parquet.writer.PrimitiveColumnWriter.flushCurrentPageToBuffer(PrimitiveColumnWriter.java:205)
	at io.trino.parquet.writer.PrimitiveColumnWriter.writeBlock(PrimitiveColumnWriter.java:148)
	at io.trino.parquet.writer.MapColumnWriter.writeBlock(MapColumnWriter.java:62)
	at io.trino.parquet.writer.ParquetWriter.writeChunk(ParquetWriter.java:157)
	at io.trino.parquet.writer.ParquetWriter.write(ParquetWriter.java:147)
	at io.trino.plugin.hive.parquet.ParquetTester.writeParquetColumnTrino(ParquetTester.java:747)
	at io.trino.plugin.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:366)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:304)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:281)
	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:254)
	at io.trino.plugin.hive.parquet.AbstractTestParquetReader.testMapSchemas(AbstractTestParquetReader.java:1415)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findepi** [comment]
I reproduced this locally with `@Test(invocationCount = 1000)`.
Failed in 17th iteration for me, was impatient to wait beyond 24th iteration.

@martint does this look like a bug in ZSTD implementation?

**Comment by electrum** [comment]
For debugging, it should be easy enough to wrapper the `ParquetCompressor.compress()` method to catch this exception and log the input data. Presumably, this is a bug in Zstd and compressing the same input would fail in a deterministic way. This would indicate that the Parquet data produced by the test is not deterministic, which is a bit surprising. Or it could be that Zstd fails non-deterministically on the same data, but that would be more surprising.
