### ISSUE TITLE
Iceberg connector failure when pushing down large domain: StackOverflowError

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#8644]
`testLargeInFailureOnPartitionedColumns` fails very often when run locally.

```
java.lang.AssertionError: 
Expecting message to be:
  <"java.lang.StackOverflowError">
but was:
  <"Failed while running parallel task">

Throwable that failed the check:

java.lang.RuntimeException: Failed while running parallel task
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:120)
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:85)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:464)
	at io.trino.plugin.iceberg.BaseIcebergConnectorTest.lambda$testLargeInFailureOnPartitionedColumns$8(BaseIcebergConnectorTest.java:681)
```

cc @phd3 @alexjo2144 @losipiuk

**Comment by findepi** [comment]
@phd3 would you be open to removing the test and creating an issue to track the problem instead?

**Comment by phd3** [comment]
sorry, I missed this one. IMO it's better to keep the test to easily know in future what we're fixing. (and since you've already sort of fixed it. ;) )

**Comment by findepi** [comment]
@phd3 would it be actually possible to avoid failure?
the code  seems to be attempting that: https://github.com/trinodb/trino/blob/47301fb28275cd405ee89113ba4f2a54a01250a8/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitManager.java#L65-L69
the `testLargeInFailureOnPartitionedColumns` suggests there is something more that would benefit from the change?
