### ISSUE TITLE
Could not transfer artifact io.airlift:airbase:pom:110 when running DevelopmentServer in IDEA

### ISSUE THREAD

**Issue by guimingyue** [trinodb/trino#8651]
I saw the following exception when running `DevelopmentServer` in IDEA with the args from the trino [readme](https://github.com/trinodb/trino#running-the-full-server). How can I solve this problem? Is there any configuration missing. Anyone can help me?
```java
2021-07-23T22:05:36.609+0800  ERROR main  io.trino.server.Server  Error loading pom: /Users/test/github/trino/testing/trino-server-dev/../../plugin/trino-resource-group-managers/pom.xml
java.lang.RuntimeException: Error loading pom: /Users/test/github/trino/testing/trino-server-dev/../../plugin/trino-resource-group-managers/pom.xml
  at io.airlift.resolver.ArtifactResolver.getMavenProject(ArtifactResolver.java:204)
  at io.airlift.resolver.ArtifactResolver.resolvePom(ArtifactResolver.java:143)
  at io.trino.server.DevelopmentPluginsProvider.buildClassLoaderFromPom(DevelopmentPluginsProvider.java:80)
  at io.trino.server.DevelopmentPluginsProvider.doBuildClassLoader(DevelopmentPluginsProvider.java:72)
  at io.trino.server.DevelopmentPluginsProvider.buildClassLoader(DevelopmentPluginsProvider.java:60)
  at io.trino.server.DevelopmentPluginsProvider.lambda$loadPlugins$0(DevelopmentPluginsProvider.java:53)
  at io.trino.server.PluginManager.loadPlugin(PluginManager.java:121)
  at io.trino.server.DevelopmentPluginsProvider.loadPlugins(DevelopmentPluginsProvider.java:53)
  at io.trino.server.PluginManager.loadPlugins(PluginManager.java:110)
  at io.trino.server.Server.doStart(Server.java:122)
  at io.trino.server.Server.lambda$start$0(Server.java:77)
  at io.trino.$gen.Trino_dev____20210723_140146_1.run(Unknown Source)
  at io.trino.server.Server.start(Server.java:77)
  at io.trino.server.DevelopmentServer.main(DevelopmentServer.java:41)
Caused by: org.apache.maven.project.ProjectBuildingException: 1 problem was encountered while building the effective model for io.trino:trino-resource-group-managers:360-SNAPSHOT
[FATAL] Non-resolvable parent POM for io.trino:trino-root:360-SNAPSHOT: Could not transfer artifact io.airlift:airbase:pom:110 from/to confluent (https://packages.confluent.io/maven/): null to https://packages.confluent.io/maven/io/airlift/airbase/110/airbase-110.pom and 'parent.relativePath' points at wrong local POM @ io.trino:trino-root:360-SNAPSHOT, /Users/test/github/trino/pom.xml, line 5, column 13
 for project io.trino:trino-resource-group-managers:360-SNAPSHOT at /Users/test/github/trino/testing/trino-server-dev/../../plugin/trino-resource-group-managers/pom.xml
  at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:149)
  at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:102)
  at io.airlift.resolver.ArtifactResolver.getMavenProject(ArtifactResolver.java:200)
  ... 13 more
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for io.trino:trino-resource-group-managers:360-SNAPSHOT
[FATAL] Non-resolvable parent POM for io.trino:trino-root:360-SNAPSHOT: Could not transfer artifact io.airlift:airbase:pom:110 from/to confluent (https://packages.confluent.io/maven/): null to https://packages.confluent.io/maven/io/airlift/airbase/110/airbase-110.pom and 'parent.relativePath' points at wrong local POM @ io.trino:trino-root:360-SNAPSHOT, /Users/test/github/trino/pom.xml, line 5, column 13

  at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:195)
  at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:841)
  at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:664)
  at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:310)
  at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
  at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:142)
  ... 15 more


```

**Comment by hashhar** [comment]
Did you set the working directory to `$MODULE_DIR$`? I've seen this error if the working directory is incorrect.

The run configuration should look like 
<img width="1047" alt="Screenshot 2021-07-23 at 8 01 42 PM" src="https://user-images.githubusercontent.com/10473142/126797376-3515b42b-1557-4fa2-8e07-b7e2caf8f79f.png">

Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there for faster replies and more people are online there so you might get help faster.

I'm closing, but feel free to re-open the issue (or continue on Slack) if setting the Working Directory to `$MODULE_DIR$` doesn't solve the issue.

**Comment by guimingyue** [comment]
hi @hashhar, thanks for your reply, I have set the working directory to `$MODULE_DIR$`, the following picture is the configuration of the application. Looking forward to your reply.
![image](https://user-images.githubusercontent.com/1716196/126870201-727fd6d8-fc10-44f6-bff6-703c32c6f250.png)

**Comment by hashhar** [comment]
Make sure you have also successfully run `./mvnw clean install -DskiptTests` from within the repository once to make sure all dependencies are resolved and available to IntelliJ.

**Comment by guimingyue** [comment]
@hashhar I have run `mvnw` command with the pl option `-pl -docs` successfully, and the full command is  `./mvnw clean install -DskipTests -pl -docs`, the docs module require the docker command to build completely, so I exclude this module.  

I saw the following WARNING log in the standard log, I think this is the reason for the failure.
```java
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.netty.util.internal.ByteBufferUtil (file:/Users/test/repo/io/netty/netty/3.6.2.Final/netty-3.6.2.Final.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.jboss.netty.util.internal.ByteBufferUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by guimingyue** [comment]
@hashhar 
I have solved this problem. The reason for this problem is that the default maven repository is `confluent` which is defined in the file of trino/pom.xml. And the file `io/airlift/airbase/110/airbase-110.pom` is not present in this repository. So I replaced this configuration with aliyun repository which is ok for me.
```
<repository>
    <id>aliyun</id>
    <url>https://maven.aliyun.com/repository/public</url>
    <releases>
        <enabled>true</enabled>
    </releases>
    <snapshots>
        <enabled>false</enabled>
    </snapshots>
</repository>
```

**Comment by hashhar** [comment]
> default maven repository is confluent which is defined in the file of trino/pom.xml

That doesn't define the default. That's in addition to the default repository which is Maven Central (configured by Maven itself). I think you are behind a proxy which doesn't allow connections to Maven Central hence are seeing this issue.

If that is the case you should configure aliyun repo as a mirror of maven central as below in your `~/.m2/settings.xml`.

```xml
<mirror>
  <id>aliyun</id>
  <mirrorOf>central</mirrorOf>
  <name>aliyun</name>
  <url>https://maven.aliyun.com/repository/public</url>
</mirror>
```
