### ISSUE TITLE
Flaky test TestHiveStorageFormats.testTimestampCreatedFromTrino

### ISSUE THREAD

**Issue by CodyLeeWhite** [trinodb/trino#8662]
Test fails intermittently with 

```
presto-master       | io.trino.spi.TrinoException: Failed to translate Hive view 'test_list_failing_views.failing_view': At line 0, column 0: Object 'table_dropped' not found within 'hive.test_list_failing_views'
presto-master       | 	at io.trino.plugin.hive.ViewReaderUtil$HiveViewReader.decodeViewData(ViewReaderUtil.java:184)
presto-master       | 	at io.trino.plugin.hive.HiveMetadata.lambda$getView$63(HiveMetadata.java:2055)
presto-master       | 	at java.base/java.util.Optional.map(Optional.java:265)
presto-master       | 	at io.trino.plugin.hive.HiveMetadata.getView(HiveMetadata.java:2049)
presto-master       | 	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getView(ClassLoaderSafeConnectorMetadata.java:544)
presto-master       | 	at io.trino.metadata.MetadataManager.getViews(MetadataManager.java:1080)
presto-master       | 	at io.trino.metadata.MetadataListing.getViews(MetadataListing.java:110)
presto-master       | 	at io.trino.connector.informationschema.InformationSchemaPageSource.addViewsRecords(InformationSchemaPageSource.java:301)
presto-master       | 	at io.trino.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:222)
presto-master       | 	at io.trino.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:183)
presto-master       | 	at io.trino.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:376)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
presto-master       | 	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
presto-master       | 	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
presto-master       | 	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
presto-master       | 	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
presto-master       | 	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
presto-master       | 	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
presto-master       | 	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
presto-master       | 	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
presto-master       | 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
presto-master       | 	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:149)
presto-master       | 	at io.trino.operator.Driver.processInternal(Driver.java:387)
presto-master       | 	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
presto-master       | 	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
presto-master       | 	at io.trino.operator.Driver.processFor(Driver.java:284)
presto-master       | 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
presto-master       | 	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
presto-master       | 	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
presto-master       | 	at io.trino.$gen.Trino_145c700____20210416_104650_2.run(Unknown Source)
presto-master       | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
presto-master       | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
presto-master       | 	at java.base/java.lang.Thread.run(Thread.java:834)
presto-master       | Caused by: org.apache.calcite.runtime.CalciteContextException: At line 0, column 0: Object 'table_dropped' not found within 'hive.test_list_failing_views'
presto-master       | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
presto-master       | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
presto-master       | 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
presto-master       | 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
presto-master       | 	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
presto-master       | 	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:834)
presto-master       | 	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:819)
presto-master       | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4867)
presto-master       | 	at org.apache.calcite.sql.validate.IdentifierNamespace.resolveImpl(IdentifierNamespace.java:127)
presto-master       | 	at org.apache.calcite.sql.validate.IdentifierNamespace.validateImpl(IdentifierNamespace.java:177)
presto-master       | 	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
presto-master       | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1005)
presto-master       | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:965)
presto-master       | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3125)
presto-master       | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3379)
presto-master       | 	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
presto-master       | 	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
presto-master       | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1005)
presto-master       | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:965)
presto-master       | 	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:216)
presto-master       | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:940)
presto-master       | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:647)
presto-master       | 	at com.linkedin.coral.hive.hive2rel.HiveSqlToRelConverter.convertQuery(HiveSqlToRelConverter.java:57)
presto-master       | 	at com.linkedin.coral.hive.hive2rel.HiveToRelConverter.toRel(HiveToRelConverter.java:126)
presto-master       | 	at com.linkedin.coral.hive.hive2rel.HiveToRelConverter.convertView(HiveToRelConverter.java:110)
presto-master       | 	at io.trino.plugin.hive.ViewReaderUtil$HiveViewReader.decodeViewData(ViewReaderUtil.java:165)
presto-master       | 	... 46 more
presto-master       | Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Object 'table_dropped' not found within 'hive.test_list_failing_views'
presto-master       | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
presto-master       | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
presto-master       | 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
presto-master       | 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
presto-master       | 	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
presto-master       | 	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:572)
presto-master       | 	... 67 more
```

**Comment by findepi** [comment]
@CodyLeeWhite which test line this fails at?

**Comment by hashhar** [comment]
The logs are no longer available for the run this was originally observed on but the test method is `TestHiveViews#testFailingHiveViewsForInformationSchema`.

It seems it fails on https://github.com/trinodb/trino/blob/7458520ccae2d18e3962e03f78d6d1bd737b3260/testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java#L75.

The fact that the error comes from Calcite is concerning.
