### ISSUE TITLE
Properly reject Iceberg tables in Hive connector

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#8693]
Currently 

```
SELECT * FROM hive.default.an_iceberg_table
```

fails with

```
Query 20211207_145628_00264_6i3st failed: Unable to create input format org.apache.hadoop.mapred.FileInputFormat
io.trino.spi.TrinoException: Unable to create input format org.apache.hadoop.mapred.FileInputFormat
	at io.trino.plugin.hive.util.HiveUtil.getInputFormat(HiveUtil.java:342)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:388)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:352)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:276)
	at io.trino.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
	at io.trino.$gen.Trino_dev____20211207_122558_2.run(Unknown Source)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: java.lang.InstantiationException
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:135)
	at io.trino.plugin.hive.util.HiveUtil.getInputFormat(HiveUtil.java:339)
	... 9 more
Caused by: java.lang.InstantiationException
	at java.base/jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133)
	... 10 more
```

and

```
SELECT * FROM hive.default."an_iceberg_table$properties"
```

does not fail at all.

**Comment by HiLany** [comment]
My understanding is that if it is an iceberg table, should both of the above SQLs fail and return a friendly prompt? Is that right?

**Comment by findepi** [comment]
correct

**Comment by findinpath** [comment]
### Reproduction steps for the issue

Spin up a Trino hadoop dockerized environment
```
testing/bin/ptl env up --environment 'singlenode'  --config 'config-default'
```

Create the tables via Trino CLI
```
create table hive.default.hivetable (id bigint);

create table iceberg.default.icebergtable (id bigint);
```

Select from an iceberg table within the hive connector:

```
select * from hive.default.icebergtable;
```
This operation fails with the above mentioned exception.


Select from a hive table within the iceberg connector
```
sel`ct * from iceberg.default.hivetable;
```


The operation fails with the exception (as expected):
```
2021-12-31 11:45:45] [84148224] Query failed (#20211231_104545_00014_c7yj6): Not an Iceberg table: default.hivetable
[2021-12-31 11:45:45] io.trino.plugin.iceberg.UnknownTableTypeException: Not an Iceberg table: default.hivetable
```

**Comment by shubhamg931** [comment]
Is there a thread to explain why iceberg tables can't be queries via hive connector? Thanks in advance!
