### ISSUE TITLE
Unable to query optimizer_rule_stats table

### ISSUE THREAD

**Issue by posulliv** [trinodb/trino#8700]
Attempting to query the `system.runtime.optimizer_rule_stats` table results in the following error:

```
trino:runtime> select * from optimizer_rule_stats;
Query 20210728_202457_00005_9rmqb failed: Rule stats system table can return results only on coordinator
java.lang.IllegalStateException: Rule stats system table can return results only on coordinator
	at com.google.common.base.Preconditions.checkState(Preconditions.java:510)
	at io.trino.connector.system.RuleStatsSystemTable.pageSource(RuleStatsSystemTable.java:86)
	at io.trino.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:105)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:306)
	at io.trino.operator.Driver.processInternal(Driver.java:387)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_359____20210728_202230_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

trino:runtime>
```

I have tried querying this table in multiple clusters I have access to and tried with `node-scheduler.include-coordinator` set to both `true` and `false` but no luck.

I've tested with 356 and 359 and have hit the same issue on both versions.

**Comment by findepi** [comment]
Caused by 9777b4676720954cece4532d9996826bf3f5c608 (cc @martint), which was fixing f3dda9c96289c38ac99024ac64393debdf2dab9d (cc @sopel39)

the test should go into `io.trino.connector.system.runtime.TestSystemConnector`.

**Comment by sopel39** [comment]
`optimizer_rule_stats` should now use `OptimizerStatsMBeanExporter` which should be extended to return `ruleStats`
