### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: 

### ISSUE THREAD

**Issue by suryans1** [trinodb/trino#8702]
Hii i am getting the below error while i am trying to insert the data in to a table from another table.

PFA error

[inserterror.txt](https://github.com/trinodb/trino/files/6898167/inserterror.txt)

create query for table test

CREATE TABLE sample.test (
   account_no bigint,
   msisdn varchar,
   product_name varchar,
   sub_segment varchar,
   rev_segment varchar,
   region varchar,
   free_usage double,
   actual_usage double,
   subscription_revenue integer,
   usage_revenue double,
   addon_revenue double,
   other_revenue double,
   int_ic_revenue double,
   sales_meet double,
   sales_recharge double,
   csd_call_center double,
   csd_training double,
   bill_printing double,
   collection_expenses double,
   mrkt_media double,
   mrkt_outdoor double,
   mrkt_retail double,
   mrkt_event double,
   mrkt_research double,
   it_si_rev_share double,
   it_connectivity double,
   it_call_center_infra double,
   it_nwsm double,
   it_portal double,
   hr_salary_onroll double,
   hr_salary_outsource double,
   hr_staff_welfare double,
   hr_recruitment double,
   hr_training double,
   hr_travel double,
   hr_staff_meetings double,
   facilities_rent double,
   facilities_energy double,
   facilities_amc double,
   facilities_printing double,
   facilities_rates_taxes double,
   facilities_maintenance double,
   legal_audit double,
   legal_regulatory double,
   legal_consultancy double,
   legal_insurance double,
   regulator_lincense double,
   regulator_spectrum double,
   int_outgoing_cost double,
   roaming_cost double,
   sales_commission double,
   net_bandwidth double,
   net_leasedline double,
   net_o_m double,
   net_ip_port double,
   net_vast double,
   net_r_m double,
   net_overseas_pop double,
   net_installation double,
   net_others double,
   total_revenue double,
   total_cost double,
   margin double,
   margin_ double,
   col1 varchar,
   col2 varchar,
   col3 varchar,
   col4 varchar,
   col5 varchar,
   col6 varchar,
   col7 varchar,
   col8 varchar,
   col9 varchar,
   col10 varchar,
   col11 double,
   col12 double,
   col13 double,
   col14 double,
   col15 double,
   col16 double,
   col17 double,
   col18 double,
   col19 double,
   col20 double,
   col21 double,
   col22 double,
   col23 double,
   col24 double,
   col25 double,
   col26 double,
   col27 double,
   col28 double,
   col29 double,
   col30 double,
   col31 double,
   col32 double,
   col33 double,
   col34 double,
   col35 double,
   col36 double,
   col37 double,
   col38 double,
   col39 double,
   col40 double,
   col41 double,
   col42 double,
   col43 double,
   col44 double,
   col45 double,
   col46 double,
   col47 double,
   col48 double,
   col49 double,
   col50 double,
   col51 varchar,
   col52 varchar,
   col53 varchar,
   col54 varchar,
   col55 varchar,
   col56 timestamp(3),
   col57 timestamp(3),
   col58 varchar,
   col59 varchar,
   col60 varchar,
   col61 varchar,
   col62 varchar,
   col63 varchar,
   col64 varchar,
   col65 varchar,
   col66 varchar,
   col67 varchar,
   col68 bigint,
   col69 bigint,
   col70 bigint,
   col71 bigint,
   col72 bigint,
   col73 bigint,
   col74 bigint,
   col75 bigint,
   col76 varchar,
   col77 varchar,
   col78 varchar,
   col79 varchar,
   col80 timestamp(3),
   new_freeusage varchar,
   month timestamp(3)
)
WITH (
   external_location = 's3a://dmstest/test_newdata2/default/test',
   format = 'PARQUET',
   partitioned_by = ARRAY['month']
)

create query for table test567

CREATE TABLE IF NOT EXISTS test567 as Select  other_revenue AS other_revenue, int_ic_revenue AS int_ic_revenue, sales_meet AS sales_meet, col63 AS col63, col64 AS col64, col65 AS col65, month AS month, account_no AS account_no, msisdn AS msisdn, product_name AS product_name, sub_segment AS sub_segment, rev_segment AS rev_segment, region AS region, free_usage AS free_usage, actual_usage AS actual_usage, subscription_revenue AS subscription_revenue, usage_revenue AS usage_revenue, addon_revenue AS addon_revenue, sales_recharge AS sales_recharge, csd_call_center AS csd_call_center, csd_training AS csd_training, bill_printing AS bill_printing, collection_expenses AS collection_expenses, mrkt_media AS mrkt_media, mrkt_outdoor AS mrkt_outdoor, mrkt_retail AS mrkt_retail, mrkt_event AS mrkt_event, mrkt_research AS mrkt_research, it_si_rev_share AS it_si_rev_share, it_connectivity AS it_connectivity, it_call_center_infra AS it_call_center_infra, it_nwsm AS it_nwsm, it_portal AS it_portal, hr_salary_onroll AS hr_salary_onroll, hr_salary_outsource AS hr_salary_outsource, hr_staff_welfare AS hr_staff_welfare, hr_recruitment AS hr_recruitment, hr_training AS hr_training, hr_travel AS hr_travel, hr_staff_meetings AS hr_staff_meetings, facilities_rent AS facilities_rent, facilities_energy AS facilities_energy, facilities_amc AS facilities_amc, facilities_printing AS facilities_printing, facilities_rates_taxes AS facilities_rates_taxes, facilities_maintenance AS facilities_maintenance, legal_audit AS legal_audit, legal_regulatory AS legal_regulatory, legal_consultancy AS legal_consultancy, legal_insurance AS legal_insurance, regulator_lincense AS regulator_lincense, regulator_spectrum AS regulator_spectrum, int_outgoing_cost AS int_outgoing_cost, roaming_cost AS roaming_cost, sales_commission AS sales_commission, net_bandwidth AS net_bandwidth, net_leasedline AS net_leasedline, net_o_m AS net_o_m, net_ip_port AS net_ip_port, net_vast AS net_vast, net_r_m AS net_r_m, net_overseas_pop AS net_overseas_pop, net_installation AS net_installation, net_others AS net_others, total_revenue AS total_revenue, total_cost AS total_cost, margin AS margin, margin_ AS margin_, col1 AS col1, col2 AS col2, col3 AS col3, col4 AS col4, col5 AS col5, col6 AS col6, col7 AS col7, col8 AS col8, col9 AS col9, col10 AS col10, col11 AS col11, col12 AS col12, col13 AS col13, col14 AS col14, col15 AS col15, col16 AS col16, col17 AS col17, col18 AS col18, col19 AS col19, col20 AS col20, col21 AS col21, col22 AS col22, col23 AS col23, col24 AS col24, col25 AS col25, col26 AS col26, col27 AS col27, col28 AS col28, col29 AS col29, col30 AS col30, col31 AS col31, col32 AS col32, col33 AS col33, col34 AS col34, col35 AS col35, col36 AS col36, col37 AS col37, col38 AS col38, col39 AS col39, col40 AS col40, col41 AS col41, col42 AS col42, col43 AS col43, col44 AS col44, col45 AS col45, col46 AS col46, col47 AS col47, col48 AS col48, col49 AS col49, col50 AS col50, col51 AS col51, col52 AS col52, col53 AS col53, col54 AS col54, col55 AS col55, col56 AS col56, col57 AS col57, col58 AS col58, col59 AS col59, col60 AS col60, col61 AS col61, col62 AS col62, col66 AS col66, col67 AS col67, col68 AS col68, col69 AS col69, col70 AS col70, col71 AS col71, col72 AS col72, col73 AS col73, col74 AS col74, col75 AS col75, col76 AS col76, col77 AS col77, col78 AS col78, col79 AS col79, col80 AS col80, new_freeusage AS new_freeusage,ROW_NUMBER() OVER() as rowid from test WITH NO DATA

INSERT QUERY

INSERT INTO test567
SELECT
  other_revenue other_revenue
, int_ic_revenue int_ic_revenue
, sales_meet sales_meet
, col63 col63
, col64 col64
, col65 col65
, month month
, account_no account_no
, msisdn msisdn
, product_name product_name
, sub_segment sub_segment
, rev_segment rev_segment
, region region
, free_usage free_usage
, actual_usage actual_usage
, subscription_revenue subscription_revenue
, usage_revenue usage_revenue
, addon_revenue addon_revenue
, sales_recharge sales_recharge
, csd_call_center csd_call_center
, csd_training csd_training
, bill_printing bill_printing
, collection_expenses collection_expenses
, mrkt_media mrkt_media
, mrkt_outdoor mrkt_outdoor
, mrkt_retail mrkt_retail
, mrkt_event mrkt_event
, mrkt_research mrkt_research
, it_si_rev_share it_si_rev_share
, it_connectivity it_connectivity
, it_call_center_infra it_call_center_infra
, it_nwsm it_nwsm
, it_portal it_portal
, hr_salary_onroll hr_salary_onroll
, hr_salary_outsource hr_salary_outsource
, hr_staff_welfare hr_staff_welfare
, hr_recruitment hr_recruitment
, hr_training hr_training
, hr_travel hr_travel
, hr_staff_meetings hr_staff_meetings
, facilities_rent facilities_rent
, facilities_energy facilities_energy
, facilities_amc facilities_amc
, facilities_printing facilities_printing
, facilities_rates_taxes facilities_rates_taxes
, facilities_maintenance facilities_maintenance
, legal_audit legal_audit
, legal_regulatory legal_regulatory
, legal_consultancy legal_consultancy
, legal_insurance legal_insurance
, regulator_lincense regulator_lincense
, regulator_spectrum regulator_spectrum
, int_outgoing_cost int_outgoing_cost
, roaming_cost roaming_cost
, sales_commission sales_commission
, net_bandwidth net_bandwidth
, net_leasedline net_leasedline
, net_o_m net_o_m
, net_ip_port net_ip_port
, net_vast net_vast
, net_r_m net_r_m
, net_overseas_pop net_overseas_pop
, net_installation net_installation
, net_others net_others
, total_revenue total_revenue
, total_cost total_cost
, margin margin
, margin_ margin_
, col1 col1
, col2 col2
, col3 col3
, col4 col4
, col5 col5
, col6 col6
, col7 col7
, col8 col8
, col9 col9
, col10 col10
, col11 col11
, col12 col12
, col13 col13
, col14 col14
, col15 col15
, col16 col16
, col17 col17
, col18 col18
, col19 col19
, col20 col20
, col21 col21
, col22 col22
, col23 col23
, col24 col24
, col25 col25
, col26 col26
, col27 col27
, col28 col28
, col29 col29
, col30 col30
, col31 col31
, col32 col32
, col33 col33
, col34 col34
, col35 col35
, col36 col36
, col37 col37
, col38 col38
, col39 col39
, col40 col40
, col41 col41
, col42 col42
, col43 col43
, col44 col44
, col45 col45
, col46 col46
, col47 col47
, col48 col48
, col49 col49
, col50 col50
, col51 col51
, col52 col52
, col53 col53
, col54 col54
, col55 col55
, col56 col56
, col57 col57
, col58 col58
, col59 col59
, col60 col60
, col61 col61
, col62 col62
, col66 col66
, col67 col67
, col68 col68
, col69 col69
, col70 col70
, col71 col71
, col72 col72
, col73 col73
, col74 col74
, col75 col75
, col76 col76
, col77 col77
, col78 col78
, col79 col79
, col80 col80
, new_freeusage new_freeusage
, ROW_NUMBER() OVER () rowid
FROM
  test
WHERE ((month >= TIMESTAMP '2021-01-01') AND (month <= TIMESTAMP '2021-01-07 23:59:59.000'))
OFFSET 0 ROWS
LIMIT 1000

**Comment by findepi** [comment]
@suryans1 thank you for your report.
i see that you encountered a problem when working with tables that have 80 columns.
Was the problem reproducible for tables with 40 columns?
What is the minimum number of columns required to reproduce the problem?

> PFA error
> 
> inserterror.txt

please inline the exception in the issue description (using ```` ``` ```` blocks), so it's easily searchable.

**Comment by suryans1** [comment]
Please fimd the exception
"com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Multiple entries with same key: col18=HiveColumnStatistics{integerStatistics=Optional.empty, doubleStatistics=Optional[DoubleStatistics{min=OptionalDouble.empty, max=OptionalDouble.empty}], decimalStatistics=Optional.empty, dateStatistics=Optional.empty, booleanStatistics=Optional.empty, maxValueSizeInBytes=OptionalLong.empty, totalSizeInBytes=OptionalLong.empty, nullsCount=OptionalLong[0], distinctValuesCount=OptionalLong[0]} and col18=HiveColumnStatistics{integerStatistics=Optional.empty, doubleStatistics=Optional[DoubleStatistics{min=OptionalDouble.empty, max=OptionalDouble.empty}], decimalStatistics=Optional.empty, dateStatistics=Optional.empty, booleanStatistics=Optional.empty, maxValueSizeInBytes=OptionalLong.empty, totalSizeInBytes=OptionalLong.empty, nullsCount=OptionalLong[0], distinctValuesCount=OptionalLong[0]}
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4952)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:259)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getTableStatistics(CachingHiveMetastore.java:328)
	at io.trino.plugin.hive.HiveMetastoreClosure.getTableStatistics(HiveMetastoreClosure.java:86)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.getTableStatistics(SemiTransactionalHiveMetastore.java:234)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.finishInsertIntoExistingTable(SemiTransactionalHiveMetastore.java:558)
	at io.trino.plugin.hive.HiveMetadata.finishInsert(HiveMetadata.java:1788)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishInsert(ClassLoaderSafeConnectorMetadata.java:471)
	at io.trino.metadata.MetadataManager.finishInsert(MetadataManager.java:941)
	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$3(LocalExecutionPlanner.java:3573)
	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:300)
	at io.trino.operator.Driver.processInternal(Driver.java:387)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_359____20210728_141431_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: col18=HiveColumnStatistics{integerStatistics=Optional.empty, doubleStatistics=Optional[Dou bleStatistics{min=OptionalDouble.empty, max=OptionalDouble.empty}], decimalStatistics=Optional.empty, dateStatistics=Optional.empty, booleanStatistics=Optional.empty, maxValueSizeInBytes=OptionalLong.empty, totalSizeInBytes=OptionalLong.empty, nullsCount=OptionalLong[0], distinctValuesCount=OptionalLong[0]} and col18=HiveColumnStatistics{integerStatistics=Optional.empty, doubleStatistics=Optional[DoubleStatistics{min=OptionalDouble.empty, max=OptionalDouble.empty}], decimalStatistics=Optional.empty, dateStatistics=Optional.empty, booleanStatistics=Optional.empty, maxValueSizeInBytes=OptionalLong.empty, totalSizeInBytes=OptionalLong.empty, nullsCount=OptionalLong[0], distinctValuesCount=OptionalLong[0]}
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:210)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:204)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:146)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:109)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:389)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:582)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.groupStatisticsByColumn(ThriftHiveMetastore.java:513)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$getTableColumnStatistics$8(ThriftHiveMetastore.java:400)
	at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
	at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getTableColumnStatistics(ThriftHiveMetastore.java:398)
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getTableStatistics(ThriftHiveMetastore.java:388)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.getTableStatistics(BridgingHiveMetastore.java:115)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadTableColumnStatistics(CachingHiveMetastore.java:335)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 25 more"

**Comment by suryans1** [comment]
@findepi  
Was the problem reproducible for tables with 40 columns?====> No it's not reproducible

Even with more columns also we are seeing this issue  intermittently and that to also only with partition table 

What is the minimum number of columns required to reproduce the problem?===> 80 columns and a partition column on time stamp field

**Comment by suryans1** [comment]
@findepi  this error we are able to see when there are multiple entries for the same table in the hive metastore.
