### ISSUE TITLE
Add support for DatabaseMetaData.getImportedKeys in Trino JDBC

### ISSUE THREAD

**Issue by walter-weinmann** [trinodb/trino#8708]
```
2021-07-29 14:10:36,559 [DatabaseSeeder.java] INFO  Start PostgreSQL via trino
java.sql.SQLFeatureNotSupportedException: imported keys not supported
        at io.trino.jdbc.TrinoDatabaseMetaData.getImportedKeys(TrinoDatabaseMetaData.java:1066)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.dropTableConstraints(AbstractJdbcSeeder.java:965)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:408)
        at ch.konnexions.db_seeder.DatabaseSeeder.main(DatabaseSeeder.java:250)
Processing of the script was aborted, error code=1
```

**Comment by findepi** [comment]
There are many unimplemented methods in Trino JDBC, you can them by searching for `throw new SQLFeatureNotSupportedException` in the code base
The `DatabaseMetaData.getImportedKeys` is one of them. @walter-weinmann Is this method of any particular interest?

The method docs is

> Retrieves a description of the primary key columns that are referenced by the given table's foreign key columns (the primary keys imported by a table)

Currently there is no concept of primary or foreign keys in Trino, so it seems legitimate for this method to return an empty result set.

**Comment by walter-weinmann** [comment]
Thanks @findepi for the explanation.

**Comment by findepi** [comment]
Fixed by https://github.com/trinodb/trino/pull/11472
