### ISSUE TITLE
CTAS into HIVE with column names having trailing spaces fails

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#8709]
Query:
```
CREATE TABLE
  hive.default.tcn__atrailingspace___hgh7f_dc15919f_c589_49ed_ae65_7528eff382a4 
  AS SELECT "key","atrailingspace " FROM hive.default.tcn__atrailingspace___hgh7f
```
Error
```
io.trino.spi.TrinoException: Table 'default.tcn__atrailingspace___hgh7f_dc15919f_c589_49ed_ae65_7528eff382a4' does not have columns [atrailingspace ]
	at io.trino.plugin.hive.HiveWriterFactory.validateSchema(HiveWriterFactory.java:610)
	at io.trino.plugin.hive.HiveWriterFactory.createWriter(HiveWriterFactory.java:440)
	at io.trino.plugin.hive.HivePageSink.getWriterIndexes(HivePageSink.java:350)
	at io.trino.plugin.hive.HivePageSink.writePage(HivePageSink.java:275)
	at io.trino.plugin.hive.HivePageSink.doAppend(HivePageSink.java:270)
	at io.trino.plugin.hive.HivePageSink.lambda$appendPage$2(HivePageSink.java:256)
	at io.trino.plugin.hive.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:26)
	at io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.plugin.hive.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:25)
	at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:103)
	at io.trino.plugin.hive.HivePageSink.appendPage(HivePageSink.java:256)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:69)
	at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:263)
```
cc @findepi

**Comment by hashhar** [comment]
Duplicate of https://github.com/trinodb/trino/issues/3461.

**Comment by sopel39** [comment]
Closing as duplicate
