### ISSUE TITLE
Flaky TestHiveStorageFormats tests

### ISSUE THREAD

**Issue by CodyLeeWhite** [trinodb/trino#8763]
testInsertIntoTable and testInsertIntoPartitionedTable can fail with Self-suppression not permitted

testInsertIntoTable stack trace
```
2021-03-10T07:29:41.8952588Z tests               | 2021-03-10 13:14:41 INFO: FAILURE     /    io.prestosql.tests.hive.TestHiveStorageFormats.testInsertIntoTable (Groups: storage_formats) took 0.5 seconds
2021-03-10T07:29:41.8955978Z tests               | 2021-03-10 13:14:41 SEVERE: Failure cause:
2021-03-10T07:29:41.8958144Z tests               | io.prestosql.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20210310_072941_00199_vqysk): Self-suppression not permitted
2021-03-10T07:29:41.8961058Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:114)
2021-03-10T07:29:41.8964338Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:82)
2021-03-10T07:29:41.8967572Z tests               | 	at io.prestosql.tempto.query.QueryExecutor.query(QueryExecutor.java:57)
2021-03-10T07:29:41.8971486Z tests               | 	at io.prestosql.tests.hive.TestHiveStorageFormats.testInsertIntoTable(TestHiveStorageFormats.java:141)
2021-03-10T07:29:41.8974921Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-03-10T07:29:41.8977134Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-03-10T07:29:41.8979647Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-03-10T07:29:41.8981551Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-03-10T07:29:41.8983339Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-03-10T07:29:41.8985690Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-03-10T07:29:41.8987956Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-03-10T07:29:41.8990387Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-03-10T07:29:41.8993445Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-03-10T07:29:41.8996465Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-03-10T07:29:41.9011669Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-03-10T07:29:41.9014975Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-03-10T07:29:41.9017468Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-03-10T07:29:41.9019931Z tests               | Caused by: java.sql.SQLException: Query failed (#20210310_072941_00199_vqysk): Self-suppression not permitted
2021-03-10T07:29:41.9023355Z tests               | 	at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1761)
2021-03-10T07:29:41.9027755Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:228)
2021-03-10T07:29:41.9031357Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:188)
2021-03-10T07:29:41.9033883Z tests               | 	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-03-10T07:29:41.9036387Z tests               | 	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-03-10T07:29:41.9038200Z tests               | 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
2021-03-10T07:29:41.9040284Z tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
2021-03-10T07:29:41.9042573Z tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
2021-03-10T07:29:41.9044995Z tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
2021-03-10T07:29:41.9047129Z tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
2021-03-10T07:29:41.9048751Z tests               | 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
2021-03-10T07:29:41.9050184Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$AsyncIterator.lambda$new$0(PrestoResultSet.java:134)
2021-03-10T07:29:41.9051861Z tests               | 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
2021-03-10T07:29:41.9052959Z tests               | 	... 3 more
2021-03-10T07:29:41.9054239Z tests               | Caused by: java.lang.IllegalArgumentException: Self-suppression not permitted
2021-03-10T07:29:41.9055696Z tests               | 	at java.base/java.lang.Throwable.addSuppressed(Throwable.java:1054)
2021-03-10T07:29:41.9057674Z tests               | 	at io.prestosql.plugin.hive.util.SequenceFileRecordWriter.close(SequenceFileRecordWriter.java:67)
2021-03-10T07:29:41.9060194Z tests               | 	at io.prestosql.plugin.hive.RecordFileWriter.commit(RecordFileWriter.java:186)
2021-03-10T07:29:41.9061899Z tests               | 	at io.prestosql.plugin.hive.HiveWriter.commit(HiveWriter.java:86)
2021-03-10T07:29:41.9063506Z tests               | 	at io.prestosql.plugin.hive.HivePageSink.doFinish(HivePageSink.java:190)
2021-03-10T07:29:41.9066000Z tests               | 	at io.prestosql.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
2021-03-10T07:29:41.9068323Z tests               | 	at io.prestosql.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:96)
2021-03-10T07:29:41.9069974Z tests               | 	at io.prestosql.plugin.hive.HivePageSink.finish(HivePageSink.java:181)
2021-03-10T07:29:41.9072715Z tests               | 	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:77)
2021-03-10T07:29:41.9075608Z tests               | 	at io.prestosql.operator.TableWriterOperator.finish(TableWriterOperator.java:208)
2021-03-10T07:29:41.9077349Z tests               | 	at io.prestosql.operator.Driver.processInternal(Driver.java:397)
2021-03-10T07:29:41.9078866Z tests               | 	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
2021-03-10T07:29:41.9080213Z tests               | 	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
2021-03-10T07:29:41.9081577Z tests               | 	at io.prestosql.operator.Driver.processFor(Driver.java:276)
2021-03-10T07:29:41.9083399Z tests               | 	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
2021-03-10T07:29:41.9085771Z tests               | 	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
2021-03-10T07:29:41.9088019Z tests               | 	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
2021-03-10T07:29:41.9089357Z tests               | 	at io.prestosql.$gen.Presto_06a5140____20210310_072659_2.run(Unknown Source)
2021-03-10T07:29:41.9090833Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-03-10T07:29:41.9092747Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-03-10T07:29:41.9094070Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-03-10T07:29:41.9096635Z tests               | Caused by: org.apache.hadoop.ipc.RemoteException: File /tmp/presto-hive/4abe0a1d-49fb-4ba6-9dfb-e774d386f880/20210310_072941_00199_vqysk_23d5d1e8-1aee-4592-9dcc-1899ae08b2fb could only be replicated to 0 nodes instead of minReplication (=1).  There are 1 datanode(s) running and no node(s) are excluded in this operation.
2021-03-10T07:29:41.9100104Z tests               | 	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:1719)
2021-03-10T07:29:41.9103540Z tests               | 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3508)
2021-03-10T07:29:41.9106873Z tests               | 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:694)
2021-03-10T07:29:41.9110953Z tests               | 	at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.addBlock(AuthorizationProviderProxyClientProtocol.java:219)
2021-03-10T07:29:41.9116172Z tests               | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:507)
2021-03-10T07:29:41.9120513Z tests               | 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
2021-03-10T07:29:41.9123328Z tests               | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
2021-03-10T07:29:41.9124816Z tests               | 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
2021-03-10T07:29:41.9125960Z tests               | 	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2281)
2021-03-10T07:29:41.9127081Z tests               | 	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2277)
2021-03-10T07:29:41.9128378Z tests               | 	at java.security.AccessController.doPrivileged(Native Method)
2021-03-10T07:29:41.9129692Z tests               | 	at javax.security.auth.Subject.doAs(Subject.java:422)
2021-03-10T07:29:41.9131359Z tests               | 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1924)
2021-03-10T07:29:41.9133023Z tests               | 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2275)
2021-03-10T07:29:41.9133806Z tests               | 
2021-03-10T07:29:41.9134781Z tests               | 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1511)
2021-03-10T07:29:41.9136089Z tests               | 	at org.apache.hadoop.ipc.Client.call(Client.java:1457)
2021-03-10T07:29:41.9137234Z tests               | 	at org.apache.hadoop.ipc.Client.call(Client.java:1367)
2021-03-10T07:29:41.9138772Z tests               | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
2021-03-10T07:29:41.9140619Z tests               | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
2021-03-10T07:29:41.9141912Z tests               | 	at com.sun.proxy.$Proxy266.addBlock(Unknown Source)
2021-03-10T07:29:41.9144342Z tests               | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:513)
2021-03-10T07:29:41.9147404Z tests               | 	at jdk.internal.reflect.GeneratedMethodAccessor384.invoke(Unknown Source)
2021-03-10T07:29:41.9149737Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-03-10T07:29:41.9151664Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-03-10T07:29:41.9153574Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
2021-03-10T07:29:41.9156118Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
2021-03-10T07:29:41.9158303Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
2021-03-10T07:29:41.9160509Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
2021-03-10T07:29:41.9162876Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
2021-03-10T07:29:41.9164588Z tests               | 	at com.sun.proxy.$Proxy267.addBlock(Unknown Source)
2021-03-10T07:29:41.9166066Z tests               | 	at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1081)
2021-03-10T07:29:41.9168059Z tests               | 	at org.apache.hadoop.hdfs.DataStreamer.locateFollowingBlock(DataStreamer.java:1865)
2021-03-10T07:29:41.9170234Z tests               | 	at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1668)
2021-03-10T07:29:41.9172049Z tests               | 	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:716)
2021-03-10T07:29:41.9172999Z tests               |
```

testInsertIntoPartitionedTable stack trace
```
2021-01-22T12:04:21.0622347Z tests               | 2021-01-22 17:49:21 INFO: FAILURE     /    io.prestosql.tests.hive.TestHiveStorageFormats.testInsertIntoPartitionedTable [StorageFormat{name=SEQUENCEFILE, properties={}, sessionProperties={}}] (Groups: storage_formats) took 0.5 seconds
2021-01-22T12:04:21.0624390Z tests               | 2021-01-22 17:49:21 SEVERE: Failure cause:
2021-01-22T12:04:21.0626143Z tests               | io.prestosql.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20210122_120420_00147_6hnmx): Self-suppression not permitted
2021-01-22T12:04:21.0627798Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
2021-01-22T12:04:21.0629376Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2021-01-22T12:04:21.0630866Z tests               | 	at io.prestosql.tempto.query.QueryExecutor.query(QueryExecutor.java:57)
2021-01-22T12:04:21.0632539Z tests               | 	at io.prestosql.tests.hive.TestHiveStorageFormats.testInsertIntoPartitionedTable(TestHiveStorageFormats.java:353)
2021-01-22T12:04:21.0634360Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-01-22T12:04:21.0635977Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-01-22T12:04:21.0637798Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-01-22T12:04:21.0639435Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-01-22T12:04:21.0640783Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-01-22T12:04:21.0642082Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-01-22T12:04:21.0643188Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-01-22T12:04:21.0644372Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-01-22T12:04:21.0645766Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-01-22T12:04:21.0647195Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-01-22T12:04:21.0648614Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-01-22T12:04:21.0650282Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-01-22T12:04:21.0651522Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-22T12:04:21.0653222Z tests               | Caused by: java.sql.SQLException: Query failed (#20210122_120420_00147_6hnmx): Self-suppression not permitted
2021-01-22T12:04:21.0654719Z tests               | 	at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1912)
2021-01-22T12:04:21.0656684Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:218)
2021-01-22T12:04:21.0658075Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:178)
2021-01-22T12:04:21.0659517Z tests               | 	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2021-01-22T12:04:21.0661067Z tests               | 	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2021-01-22T12:04:21.0662601Z tests               | 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
2021-01-22T12:04:21.0663783Z tests               | 	at java.base/java.util.stre
2021-01-22T12:04:21.0665055Z tests               | am.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
2021-01-22T12:04:21.0666750Z tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
2021-01-22T12:04:21.0668612Z tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
2021-01-22T12:04:21.0670259Z tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
2021-01-22T12:04:21.0671953Z tests               | 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
2021-01-22T12:04:21.0673193Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$AsyncIterator.lambda$new$0(PrestoResultSet.java:124)
2021-01-22T12:04:21.0674565Z tests               | 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
2021-01-22T12:04:21.0675688Z tests               | 	... 3 more
2021-01-22T12:04:21.0677440Z tests               | 	Suppressed: java.lang.Exception: Query: INSERT INTO storage_formats_test_insert_into_partitioned_sequencefile SELECT orderkey, partkey, suppkey, linenumber, quantity, extendedprice, discount, tax, linestatus, shipinstruct, shipmode, comment, returnflag FROM tpch.tiny.lineitem
2021-01-22T12:04:21.0679407Z tests               | 		at io.prestosql.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
2021-01-22T12:04:21.0681046Z tests               | 		at io.prestosql.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
2021-01-22T12:04:21.0682898Z tests               | 		at io.prestosql.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2021-01-22T12:04:21.0684357Z tests               | 		at io.prestosql.tempto.query.QueryExecutor.query(QueryExecutor.java:57)
2021-01-22T12:04:21.0686125Z tests               | 		at io.prestosql.tests.hive.TestHiveStorageFormats.testInsertIntoPartitionedTable(TestHiveStorageFormats.java:353)
2021-01-22T12:04:21.0687685Z tests               | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-01-22T12:04:21.0689103Z tests               | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-01-22T12:04:21.0690704Z tests               | 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-01-22T12:04:21.0691994Z tests               | 		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-01-22T12:04:21.0693279Z tests               | 		at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-01-22T12:04:21.0694623Z tests               | 		at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-01-22T12:04:21.0695751Z tests               | 		at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-01-22T12:04:21.0696933Z tests               | 		at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-01-22T12:04:21.0698392Z tests               | 		at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-01-22T12:04:21.0699930Z tests               | 		at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-01-22T12:04:21.0700871Z tests               | 		... 3 more
2021-01-22T12:04:21.0702378Z tests               | Caused by: java.lang.IllegalArgumentException: Self-suppression not permitted
2021-01-22T12:04:21.0703619Z tests               | 	at java.base/java.lang.Throwable.addSuppressed(Throwable.java:1054)
2021-01-22T12:04:21.0705088Z tests               | 	at io.prestosql.plugin.hive.util.SequenceFileRecordWriter.close(SequenceFileRecordWriter.java:67)
2021-01-22T12:04:21.0706660Z tests               | 	at io.prestosql.plugin.hive.RecordFileWriter.commit(RecordFileWriter.java:187)
2021-01-22T12:04:21.0708038Z tests               | 	at io.prestosql.plugin.hive.HiveWriter.commit(HiveWriter.java:86)
2021-01-22T12:04:21.0709392Z tests               | 	at io.prestosql.plugin.hive.HivePageSink.doFinish(HivePageSink.java:190)
2021-01-22T12:04:21.0711031Z tests               | 	at io.prestosql.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
2021-01-22T12:04:21.0712655Z tests               | 	at io.prestosql.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:96)
2021-01-22T12:04:21.0713909Z tests               | 	at io.prestosql.plugin.hive.HivePageSink.finish(HivePageSink.java:181)
2021-01-22T12:04:21.0715477Z tests               | 	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:77)
2021-01-22T12:04:21.0717336Z tests               | 	at io.prestosql.operator.TableWriterOperator.finish(TableWriterOperator.java:208)
2021-01-22T12:04:21.0718637Z tests               | 	at io.prestosql.operator.Driver.processInternal(Driver.java:397)
2021-01-22T12:04:21.0719834Z tests               | 	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
2021-01-22T12:04:21.0721120Z tests               | 	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
2021-01-22T12:04:21.0722428Z tests               | 	at io.prestosql.operator.Driver.processFor(Driver.java:276)
2021-01-22T12:04:21.0723794Z tests               | 	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
2021-01-22T12:04:21.0725447Z tests               | 	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
2021-01-22T12:04:21.0727497Z tests               | 	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
2021-01-22T12:04:21.0728869Z tests               | 	at io.prestosql.$gen.Presto_10e2ce6____20210122_120147_2.run(Unknown Source)
2021-01-22T12:04:21.0730041Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-01-22T12:04:21.0731616Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-01-22T12:04:21.0732774Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-22T12:04:21.0735401Z tests               | Caused by: org.apache.hadoop.ipc.RemoteException: File /tmp/presto-hive/3c65b5a6-1b9c-4dc2-9194-7f3d487dea36/returnflag=A/20210122_120420_00147_6hnmx_398e8acb-d02f-49b7-abb3-3124d1e432b9 could only be replicated to 0 nodes instead of minReplication (=1).  There are 1 datanode(s) running and no node(s) are excluded in this operation.
2021-01-22T12:04:21.0737928Z tests               | 	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:1719)
2021-01-22T12:04:21.0739965Z tests               | 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3508)
2021-01-22T12:04:21.0741875Z tests               | 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:694)
2021-01-22T12:04:21.0744436Z tests               | 	at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.addBlock(AuthorizationProviderProxyClientProtocol.java:219)
2021-01-22T12:04:21.0747404Z tests               | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:507)
2021-01-22T12:04:21.0749859Z tests               | 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
2021-01-22T12:04:21.0751792Z tests               | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
2021-01-22T12:04:21.0753085Z tests               | 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
2021-01-22T12:04:21.0754189Z tests               | 	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2281)
2021-01-22T12:04:21.0755321Z tests               | 	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2277)
2021-01-22T12:04:21.0756335Z tests               | 	at java.security.AccessController.doPrivileged(Native Method)
2021-01-22T12:04:21.0757476Z tests               | 	at javax.security.auth.Subject.doAs(Subject.java:422)
2021-01-22T12:04:21.0758776Z tests               | 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1924)
2021-01-22T12:04:21.0760127Z tests               | 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2275)
2021-01-22T12:04:21.0760970Z tests               | 
2021-01-22T12:04:21.0761895Z tests               | 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1511)
2021-01-22T12:04:21.0763064Z tests               | 	at org.apache.hadoop.ipc.Client.call(Client.java:1457)
2021-01-22T12:04:21.0764143Z tests               | 	at org.apache.hadoop.ipc.Client.call(Client.java:1367)
2021-01-22T12:04:21.0765429Z tests               | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
2021-01-22T12:04:21.0766904Z tests               | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
2021-01-22T12:04:21.0768149Z tests               | 	at com.sun.proxy.$Proxy264.addBlock(Unknown Source)
2021-01-22T12:04:21.0769769Z tests               | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:513)
2021-01-22T12:04:21.0771791Z tests               | 	at jdk.internal.reflect.GeneratedMethodAccessor518.invoke(Unknown Source)
2021-01-22T12:04:21.0773346Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-01-22T12:04:21.0774857Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-01-22T12:04:21.0776400Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
2021-01-22T12:04:21.0778426Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
2021-01-22T12:04:21.0780135Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
2021-01-22T12:04:21.0781844Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
2021-01-22T12:04:21.0783559Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
2021-01-22T12:04:21.0784850Z tests               | 	at com.sun.proxy.$Proxy265.addBlock(Unknown Source)
2021-01-22T12:04:21.0785777Z tests               | 	at org.apache.hadoop.hdfs.DFS
2021-01-22T12:04:21.0786765Z tests               | OutputStream.addBlock(DFSOutputStream.java:1081)
2021-01-22T12:04:21.0788093Z tests               | 	at org.apache.hadoop.hdfs.DataStreamer.locateFollowingBlock(DataStreamer.java:1865)
2021-01-22T12:04:21.0789716Z tests               | 	at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1668)
2021-01-22T12:04:21.0791366Z tests               | 	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:716)
2021-01-22T12:04:21.0792279Z tests               | 
```

**Comment by hashhar** [comment]
The root cause seems to be same as most of the Hive tests.

`Caused by: org.apache.hadoop.ipc.RemoteException: File /tmp/presto-hive/3c65b5a6-1b9c-4dc2-9194-7f3d487dea36/returnflag=A/20210122_120420_00147_6hnmx_398e8acb-d02f-49b7-abb3-3124d1e432b9 could only be replicated to 0 nodes instead of minReplication (=1).  There are 1 datanode(s) running and no node(s) are excluded in this operation.`

There is already a Flaky pattern created for this - see https://github.com/trinodb/trino/blob/cd2787b51dff02cdde4cba8427d99e97763478f2/testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/HiveProductTest.java#L35

**Comment by CodyLeeWhite** [comment]
but that only covers 
(could only be replicated to 0 nodes instead of minReplication|could only be written to 0 of the 1 minReplication)

I plan to add another or for "Self-suppression not permitted"

**Comment by hashhar** [comment]
@CodyLeeWhite Did these failures occur recently? Since the tests are already marked Flaky it should've passed. Can you verify if the retry did happen?

Also, it's helpful to paste a link to the workflow run in addition to the stack trace since the logs of the run might have more information.
