### ISSUE TITLE
No nodes available to run query

### ISSUE THREAD

**Issue by rockZjy** [trinodb/trino#8774]
Hi guys,
My trino version is 355, when running query sql on hive , it occurs below errors.The trino just have one node act as coordinator and worker.But the query sometimes works and sometimes occurs "No nodes available to run query" error. Do you have some ideas ?

`2021-08-04T08:43:50.333+0800    DEBUG   Query-20210804_004349_00002_5h7gv-157   io.trino.execution.scheduler.UniformNodeSelector        No nodes available to schedule Split{catalogName=hive, connectorSplit=HiveSplit{hdfs://host-172-28-216-14:8020/user/hive/warehouse/aa/part-m-00000, 0, 9, 9}, lifespan=TaskWide}. Available nodes []
2021-08-04T08:43:50.334+0800    DEBUG   query-execution-0       io.trino.execution.QueryStateMachine    Query 20210804_004349_00002_5h7gv failed
io.trino.spi.TrinoException: No nodes available to run query
        at io.trino.execution.scheduler.UniformNodeSelector.computeAssignments(UniformNodeSelector.java:170)
        at io.trino.execution.scheduler.DynamicSplitPlacementPolicy.computeAssignments(DynamicSplitPlacementPolicy.java:41)
        at io.trino.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:303)
        at io.trino.execution.scheduler.SourcePartitionedScheduler$1.schedule(SourcePartitionedScheduler.java:166)
        at io.trino.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:550)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by tooptoop4** [comment]
how u solve @rockZjy ?
