### ISSUE TITLE
Trino Hive connector not supporting Decimal column for bucketing

### ISSUE THREAD

**Issue by vinay-kl** [trinodb/trino#8812]
>Overview
Presto 347 was supporting the reading of hive tables which were bucketed on the Decimal column datatype, Trino 359 is failing with the following error 

```
io.trino.spi.TrinoException: Computation of Hive bucket hashCode is not supported for Hive primitive category: DECIMAL
	at io.trino.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:333)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:309)
	at io.trino.operator.Driver.processInternal(Driver.java:387)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_359____20210802_144456_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsupportedOperationException: Computation of Hive bucket hashCode is not supported for Hive primitive category: DECIMAL
	at io.trino.plugin.hive.util.HiveBucketingV2.hash(HiveBucketingV2.java:124)
	at io.trino.plugin.hive.util.HiveBucketingV2.getBucketHashCode(HiveBucketingV2.java:50)
	at io.trino.plugin.hive.util.HiveBucketing$BucketingVersion$2.getBucketHashCode(HiveBucketing.java:96)
	at io.trino.plugin.hive.util.HiveBucketing.getHiveBucket(HiveBucketing.java:133)
	at io.trino.plugin.hive.HivePageSource$BucketValidator.validate(HivePageSource.java:685)
	at io.trino.plugin.hive.HivePageSource.lambda$getNextPage$0(HivePageSource.java:322)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.trino.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:322)
	... 12 more
```

Table schema

```
trino> show create table bidb.fact_wh_inventory;
                 Create Table                 
----------------------------------------------
 CREATE TABLE hive.bidb.fact_wh_inventory (   
    id decimal(10, 0),                        
    warehouse_id bigint,                      
    warehouse_name varchar,                   
    store_id bigint,                          
    seller_id bigint,                         
    vendor_id bigint,                         
    platform_id bigint,                       
    store_partner_id bigint,                  
    seller_partner_id bigint,                 
    order_system varchar,                     
    created_on timestamp(3),                  
    last_modified_on timestamp(3),            
    last_synced_on timestamp(3),              
    pushed_order_count bigint,                
    version bigint,                           
    proc_sla bigint,                          
    supply_type varchar,                      
    sku_id bigint,                            
    sku_code varchar,                         
    inventory_count bigint,                   
    blocked_order_count bigint,               
    created_by varchar                        
 )                                            
 WITH (                                       
    bucket_count = 12,                        
    bucketed_by = ARRAY['id'],                
    bucketing_version = 2,                    
    format = 'ORC',                           
    orc_bloom_filter_columns = ARRAY['`id`'], 
    orc_bloom_filter_fpp = 5E-2,              
    sorted_by = ARRAY[],                      
    transactional = true                      
 )  
```

**Comment by hashhar** [comment]
I don't think we've ever supported bucketing on DECIMAL columns (and TIMESTAMPS for that matter). We do support on DOUBLE columns. Earlier we didn't validate this during read path which was fixed in https://github.com/trinodb/trino/commit/14e24360438db823d4ac18fbebdb092e6ba01211 which can cause correctness issues in case of incorrectly bucketed data.

From 348 release notes (https://trino.io/docs/current/release/release-348.html#hive-connector):

> Verify that data is in the correct bucket file when reading bucketed tables. This is enabled by default, as incorrect bucketing can cause incorrect query results, but can be disabled using the `hive.validate-bucketing` configuration property or the `validate_bucketing` session property. (#6012)

You can use the session property to toggle the behaviour but I'd recommend to instead fix the tables if possible.

cc: @electrum

**Comment by findepi** [comment]
@vinay-kl does Hive allow you to bucket on a decimal column?

**Comment by mgorbatenko** [comment]
Was there any progress made on this issue? (I see it is still open)

I'm running into a similar issue where I'd like to use a DECIMAL column for bucketing. I could see use cases for CHAR and TIMESTAMP as well
