### ISSUE TITLE
Show create schema for hive connector displays unsupported AUTHORIZATION ROLE property

### ISSUE THREAD

**Issue by ppalucha** [trinodb/trino#8817]
Query:
```
trino> create schema hive.my_test with (location = 's3://starburst-benchmark-data/my_test');
CREATE SCHEMA
trino> show create schema hive.my_test;
                     Create Schema
-------------------------------------------------------
 CREATE SCHEMA hive.my_test
 AUTHORIZATION ROLE public
 WITH (
    location = 's3://starburst-benchmark-data/my_test'
 )
(1 row)

Query 20210806_110755_00966_uhfzg, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.46 [0 rows, 0B] [0 rows/s, 0B/s]

trino> drop schema hive.my_test;
DROP SCHEMA
trino> CREATE SCHEMA hive.my_test
    ->  AUTHORIZATION ROLE public
    ->  WITH (
    ->     location = 's3://starburst-benchmark-data/my_test'
    ->  );
Query 20210806_110809_00968_uhfzg failed: This connector does not support roles
```

Expected behaviour: sql statement as produced by `show create schema` should work and allow to create schema.

**Comment by ppalucha** [comment]
Stack trace:
```
io.trino.spi.TrinoException: This connector does not support roles
	at io.trino.plugin.hive.security.AccessControlMetadata.listRoles(AccessControlMetadata.java:56)
	at io.trino.plugin.hive.HiveMetadata.listRoles(HiveMetadata.java:2737)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.listRoles(ClassLoaderSafeConnectorMetadata.java:677)
	at io.trino.metadata.MetadataManager.listRoles(MetadataManager.java:1754)
	at io.trino.execution.CreateSchemaTask.getCreatePrincipal(CreateSchemaTask.java:123)
	at io.trino.execution.CreateSchemaTask.internalExecute(CreateSchemaTask.java:103)
	at io.trino.execution.CreateSchemaTask.execute(CreateSchemaTask.java:72)
	at io.trino.execution.CreateSchemaTask.execute(CreateSchemaTask.java:47)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:170)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_359_e____20210806_082423_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ppalucha** [comment]
Version: 359

**Comment by findepi** [comment]
@ppalucha is this still applicable after https://github.com/trinodb/trino/pull/8598 ?

**Comment by ppalucha** [comment]
> @ppalucha is this still applicable after #8598 ?

Yes, I believe so - it behaves the same on version 360.

**Comment by findepi** [comment]
cc @dain @kokosing @lukasz-walkiewicz
