### ISSUE TITLE
UPDATE WHERE false fails

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#8855]
```
trino:tpch> update x SET i = 2 WHERE false;
Query 20210811_113325_00050_w7yqf failed: Invalid descendant for DeleteNode or UpdateNode: io.trino.sql.planner.plan.ExchangeNode
java.lang.IllegalArgumentException: Invalid descendant for DeleteNode or UpdateNode: io.trino.sql.planner.plan.ExchangeNode
        at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.findTableScanHandle(BeginTableWrite.java:274)
        at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.getWriterTarget(BeginTableWrite.java:203)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.getWriterTarget(BeginTableWrite.java:211)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.getWriterTarget(BeginTableWrite.java:211)
        at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:173)
        at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:93)
        at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
        at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
        at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
       at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
        at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
        at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
        at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
        at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
        at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
        at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:78)
        at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:227)
        at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:212)
        at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:207)
        at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:488)
        at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:468)
        at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:411)
        at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
        at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
        at io.trino.$gen.Trino_testversion____20210811_100431_3.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        Suppressed: java.lang.Exception: Current plan:
                Output[rows]
                │   Layout: [rows:bigint]
                └─ TableCommit[[]]
                   │   Layout: [rows:bigint]
                   └─ LocalExchange[SINGLE] ()
                      │   Layout: [partialrows:bigint, fragment:varbinary]
                      └─ RemoteExchange[GATHER]
                         │   Layout: [partialrows:bigint, fragment:varbinary]
                         └─ Update[[]]
                            │   Layout: [partialrows:bigint, fragment:varbinary]
                            │   i := expr
                            └─ LocalExchange[ROUND_ROBIN] ()
                               │   Layout: [field:row(originalTransaction bigint, bucket integer, rowId bigint), expr:integer]
                               └─ Values
                                      Layout: [field:row(originalTransaction bigint, bucket integer, rowId bigint), expr:integer]
                at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:84)
                ... 12 more
```

**Comment by kokosing** [comment]
We are missing a sibling for `RemoveEmptyDelete`, but for Update. However update is not that simple and it may evaluate to plans with different shape. So instead of matching an entire shape we should have empty values pull up rules for exchanges and projections.

**Comment by findepi** [comment]
> We are missing a sibling for RemoveEmptyDelete, but for Update. 

let's start with this.

cc @djsstarburst

**Comment by ebyhr** [comment]
Let's continue in #12422
