### ISSUE TITLE
Trino read Iceberg table error: java.lang.NullPointerException: undefined

### ISSUE THREAD

**Issue by sixtree92** [trinodb/trino#8873]
Trino version is 358 
my iceberg table with flinksql create,  Trino read error, but Iceberg create spark can read.

sql is:
```
CREATE TABLE `ods_users`(
    user_id bigint,
    user_name varchar,
    age int,
    sex varchar
    -- , PRIMARY KEY (user_id) NOT ENFORCED
) WITH(
    'format-version' = 2,
    'engine.hive.enabled' = 'true',
    'iceberg.mr.catalog' = 'hive'
);
```

Trino read table error:
```
java.lang.NullPointerException: undefined
	at io.trino.plugin.iceberg.HiveTableOperations.refreshFromMetadataLocation(HiveTableOperations.java:299)
	at io.trino.plugin.iceberg.HiveTableOperations.refresh(HiveTableOperations.java:145)
	at io.trino.plugin.iceberg.HiveTableOperations.current(HiveTableOperations.java:121)
	at io.trino.plugin.iceberg.IcebergMetadata.lambda$getIcebergTable$28(IcebergMetadata.java:860)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.trino.plugin.iceberg.IcebergMetadata.getIcebergTable(IcebergMetadata.java:858)
	at io.trino.plugin.iceberg.IcebergMetadata.getRawSystemTable(IcebergMetadata.java:277)
	at io.trino.plugin.iceberg.IcebergMetadata.getSystemTable(IcebergMetadata.java:264)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getSystemTable(ClassLoaderSafeConnectorMetadata.java:222)
	at io.trino.metadata.MetadataManager.getSystemTable(MetadataManager.java:435)
	at io.trino.connector.system.CoordinatorSystemTablesProvider.getSystemTable(CoordinatorSystemTablesProvider.java:72)
	at io.trino.connector.system.SystemTablesMetadata.getTableHandle(SystemTablesMetadata.java:68)
	at io.trino.metadata.CatalogMetadata.getConnectorId(CatalogMetadata.java:115)
	at io.trino.metadata.MetadataManager.getMaterializedView(MetadataManager.java:1269)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1286)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:367)
	at io.trino.sql.tree.Table.accept(Table.java:53)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:384)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3256)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2051)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:367)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:384)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:394)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1154)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:367)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:384)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:347)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:190)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:806)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
	at io.trino.$gen.Trino_358____20210720_030714_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lonelyGhostisdog** [comment]
This is what happens when you iceberg 0.12

**Comment by findepi** [comment]
@sixtree92 you should probably see the actual problem being logged before the NPE is thrown. 

https://github.com/trinodb/trino/pull/8951 fixes the code not to throw NPE and to propagate actual problem.

**Comment by haoweijia** [comment]
@findepi when i use version 367 ,  I have the following error.
`Query 20211223_080254_00004_24sr9 failed: Iceberg tables with delete files are not supported: default.person_cdc_addr`
my table is a iceberg v2 table and delete some row in this table.

**Comment by ayush-san** [comment]
@haoweijia I am also getting the same error in 369version. 
@findepi Is there any fix for this?

**Comment by atifiu** [comment]
Is there any fix or workaround ? I am using version 361 and getting the same error. Able to read the table using spark.

**Comment by findepi** [comment]
it's been quite a while since i wrote that:

> #8951 fixes the code not to throw NPE and to propagate actual problem.


i don't remember why i didn't close the issue, but it doesn't look actionable.
please reopen if the problems happens again on a recent Trino version
