### ISSUE TITLE
Integration with AWS ElasticSearch

### ISSUE THREAD

**Issue by dguymon** [trinodb/trino#8928]
Hello,

I was able to connect Trino on EC2 to an ElasticSearch cluster on EC2 instances via an AWS Network Load balancer with 2-way SSL that I stoop up myself without any issue.  Unfortunately, when attempting to connect that same Trino instance to an AWS ElasticSearch cluster managed by AWS, I see the below error during Trino server startup.  Before I deep-deive into troubleshooting, is Trino able to integrate with OpenDistro ElasticSearch that AWS uses for it's managed service?  My quick Google searches came up dry, unfortunately.  Many thanks for the confirmation!

2021-08-20T01:24:04.617Z        ERROR   main    io.trino.plugin.elasticsearch.client.ElasticsearchClient        Error refreshing nodes
io.trino.spi.TrinoException: ELASTICSEARCH_CONNECTION_ERROR
        at io.trino.plugin.elasticsearch.client.ElasticsearchClient.doRequest(ElasticsearchClient.java:818)
        at io.trino.plugin.elasticsearch.client.ElasticsearchClient.fetchNodes(ElasticsearchClient.java:396)
        at io.trino.plugin.elasticsearch.client.ElasticsearchClient.refreshNodes(ElasticsearchClient.java:187)
        at io.trino.plugin.elasticsearch.client.ElasticsearchClient.initialize(ElasticsearchClient.java:169)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.airlift.bootstrap.LifeCycleManager.startInstance(LifeCycleManager.java:241)
        at io.airlift.bootstrap.LifeCycleManager.addInstance(LifeCycleManager.java:212)
        at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:62)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1133)
        at org.weakref.jmx.guice.GuiceMBeanExporter.export(GuiceMBeanExporter.java:92)
        at org.weakref.jmx.guice.GuiceMBeanExporter.<init>(GuiceMBeanExporter.java:42)
        at org.weakref.jmx.guice.GuiceMBeanExporter$$FastClassByGuice$$2751632.GUICE$TRAMPOLINE(<generated>)
        at org.weakref.jmx.guice.GuiceMBeanExporter$$FastClassByGuice$$2751632.apply(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:275)
        at io.trino.plugin.elasticsearch.ElasticsearchConnectorFactory.create(ElasticsearchConnectorFactory.java:70)
        at io.trino.connector.ConnectorManager.createConnector(ConnectorManager.java:360)
        at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:215)
        at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:207)
        at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:193)
        at io.trino.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
        at io.trino.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
        at io.trino.server.Server.doStart(Server.java:124)
        at io.trino.server.Server.lambda$start$0(Server.java:77)
        at io.trino.$gen.Trino_360____20210820_012347_1.run(Unknown Source)
        at io.trino.server.Server.start(Server.java:77)
        at io.trino.server.TrinoServer.main(TrinoServer.java:38)
Caused by: java.net.ConnectException
        at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168)
        at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:561)
        at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:822)
        at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
        at java.base/java.lang.Thread.run(Thread.java:829)

Regards,

-Danny

**Comment by sumannewton** [comment]
Can you share the output of elasticsearch API `HOST:PORT/_nodes/http` from the host where trino is deployed?

**Comment by dguymon** [comment]
Hmm, I think I have network connectivity issues from my Trino EC2 instance to my AWS ElasticSearch cluster that I need to work through.  My bad, will post back with results once I've worked out by nACLs/route tables rules.

**Comment by sumannewton** [comment]
Then I will close this for now. Feel free to reopen if you still face any issues. 

Thanks.

**Comment by ebyhr** [comment]
@dguymon By the way, I would recommend joining the community Slack. There is a `#troubleshooting` channel. 
https://trino.io/community.html
