### ISSUE TITLE
KerberosConfigPath cannot be changed without reloading the JDBC driver

### ISSUE THREAD

**Issue by nineinchnick** [trinodb/trino#8952]
The JDBC driver accepts the `KerberosConfigPath` property and validates if it matches the `java.security.krb5.conf` system property, if the latter is set. But then it sets it to this value, which prevents using a different value for a subsequent connection.

I've noticed this when testing Kerberos auth in Tableau Desktop. After spotting a typo in the value, I couldn't correct it, without restarting Tableau. Furthermore, the error visible to the user is `Error setting up connection`, which is not very actionable:

Full stack-trace:
```
2021-08-24 12:00:19.650 +0000 (,,,,5,17) grpc-default-executor-3 : ERROR com.tableau.connect.grpc.GrpcProtocolService - Failed in constructProtocol. SQLState=null, ErrorCode=0.
com.tableausoftware.jdbc.SQLExceptionWithDriverInfo: Error setting up connection
	at com.tableausoftware.jdbc.JDBCDriverManager.getConnection(JDBCDriverManager.java:262) ~[jdbcserver.jar:20212.0.8]
	at com.tableausoftware.jdbc.JDBCProtocolImpl.getConnection(JDBCProtocolImpl.java:320) ~[jdbcserver.jar:20212.0.8]
	at com.tableausoftware.jdbc.JDBCProtocolImpl.createConnectionWithIntegratedAuth(JDBCProtocolImpl.java:264) ~[jdbcserver.jar:20212.0.8]
	at com.tableausoftware.jdbc.JDBCProtocolImpl.<init>(JDBCProtocolImpl.java:115) ~[jdbcserver.jar:20212.0.8]
	at com.tableau.connect.service.ProtocolPool.constructProtocol(ProtocolPool.java:46) ~[jdbcserver.jar:20212.0.8]
	at com.tableau.connect.service.ProtocolService.constructProtocol(ProtocolService.java:58) ~[jdbcserver.jar:20212.0.8]
	at com.tableau.connect.grpc.GrpcProtocolService.lambda$constructProtocol$0(GrpcProtocolService.java:66) ~[jdbcserver.jar:20212.0.8]
	at com.tableau.connect.grpc.GrpcProtocolService.wrap(GrpcProtocolService.java:292) ~[jdbcserver.jar:20212.0.8]
	at com.tableau.connect.grpc.GrpcProtocolService.constructProtocol(GrpcProtocolService.java:65) ~[jdbcserver.jar:20212.0.8]
	at com.tableau.connect.generated.ProtocolServiceGrpc$MethodHandlers.invoke(ProtocolServiceGrpc.java:1492) ~[jdbcserver.jar:20212.0.8]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180) ~[jdbcserver.jar:20212.0.8]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) ~[jdbcserver.jar:20212.0.8]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) ~[jdbcserver.jar:20212.0.8]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) ~[jdbcserver.jar:20212.0.8]
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) ~[jdbcserver.jar:20212.0.8]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) ~[jdbcserver.jar:20212.0.8]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) ~[jdbcserver.jar:20212.0.8]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[jdbcserver.jar:20212.0.8]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[jdbcserver.jar:20212.0.8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.sql.SQLException: Error setting up connection
	at io.trino.jdbc.TrinoDriverUri.setupClient(TrinoDriverUri.java:332) ~[?:?]
	at io.trino.jdbc.NonRegisteringTrinoDriver.connect(NonRegisteringTrinoDriver.java:56) ~[?:?]
	at com.tableausoftware.jdbc.JDBCDriverManager.getConnection(JDBCDriverManager.java:254) ~[jdbcserver.jar:20212.0.8]
	... 21 more
Caused by: java.lang.IllegalStateException: Refusing to set system property 'java.security.krb5.conf' to 'C:\Windows\krb5.ini', it is already set to 'C:\Windows'\krb5.ini'
	at io.trino.jdbc.$internal.guava.base.Preconditions.checkState(Preconditions.java:826) ~[?:?]
	at io.trino.jdbc.$internal.client.SpnegoHandler.lambda$new$0(SpnegoHandler.java:108) ~[?:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at io.trino.jdbc.$internal.client.SpnegoHandler.<init>(SpnegoHandler.java:105) ~[?:?]
	at io.trino.jdbc.$internal.client.OkHttpUtil.setupKerberos(OkHttpUtil.java:291) ~[?:?]
	at io.trino.jdbc.TrinoDriverUri.setupClient(TrinoDriverUri.java:289) ~[?:?]
	at io.trino.jdbc.NonRegisteringTrinoDriver.connect(NonRegisteringTrinoDriver.java:56) ~[?:?]
	at com.tableausoftware.jdbc.JDBCDriverManager.getConnection(JDBCDriverManager.java:254) ~[jdbcserver.jar:20212.0.8]
	... 21 more
```

Refs:
https://github.com/trinodb/trino/blob/fe608f2723842037ff620d612a706900e79c52c8/client/trino-client/src/main/java/io/trino/client/SpnegoHandler.java#L109

I suggest removing this check.

**Comment by kokosing** [comment]
> it is already set to 'C:\Windows'\krb5.ini'

It looks like an invalid path. `'` do not match.

**Comment by nineinchnick** [comment]
Yeah, that's the typo I mentioned in the description. This issue is about not being able to correct it, without restarting the app that's using the JDBC driver.

**Comment by nineinchnick** [comment]
This would also prevent using different configs when connecting to different Trino clusters, in a single instance of the client.

**Comment by kokosing** [comment]
The thing is that it is a system property that is used by internals of JVM and it cannot be set multiple times. If it is set in multiple connectors it has to be set to the same thing in all of them. I don't think we can do anything with this.

**Comment by nineinchnick** [comment]
Checking if the file exists would mitigate some issues, but not when a user points to a different file by mistake, which could even fail to parse. So it's simpler to pass an exception from GSSAPI, which actually uses this config, up to the user, and allowing the user to correct the mistake by trying to open another connection with different parameters.

I understand that this check was introduced to detect a situation where the system property is already initially set to a different value than the user is providing in connection parameters. This may cause surprising behavior that's hard to debug.

What we can do, is make sure that `System.getProperty("java.security.krb5.conf")` is only called once, saving it in some static var if it was initially set or not, and only comparing it if it was.

**Comment by nineinchnick** [comment]
WDYT about something like this? https://github.com/trinodb/trino/compare/master...nineinchnick:krb5-conf-check

**Comment by kokosing** [comment]
What's the difference?

I think checking file existence is good idea

**Comment by nineinchnick** [comment]
The difference is that we only compare the value of `KerberosConfigPath` connection param with the value of the `java.security.krb5.conf` system property at the time of starting the client program, and not with what has been used in the previous connection.

**Comment by nineinchnick** [comment]
We talked offline and now I understand that we shouldn't really change `java.security.krb5.conf` because it's not clear when and how it's being used and is it cached. I'll open up a PR to add a check if the file exists, if specified. That'll solve this particular problem.

**Comment by nineinchnick** [comment]
I overlooked that there's a `refreshKrb5Config` option that's always set to `true`. From https://docs.oracle.com/javase/8/docs/jre/api/security/jaas/spec/com/sun/security/auth/module/Krb5LoginModule.html:
> refreshKrb5Config:
>    Set this to true, if you want the configuration to be refreshed before the login method is called.
