### ISSUE TITLE
Error committing write to Hive

### ISSUE THREAD

**Issue by halicizade** [trinodb/trino#8983]
trino version: 360
hive version: 3.1.0
jdk: zulu jdk11_0_12
-DHADOOP_USER_NAME=hive

```
drop table if exists tmp;
create table tmp2 (id int) with (transactional=true);
insert into tmp2 (select 1 as id union select 2);
```

```
io.trino.spi.TrinoException: Error committing write to Hive
	at io.trino.plugin.hive.orc.OrcFileWriter.commit(OrcFileWriter.java:191)
	at io.trino.plugin.hive.HiveWriter.commit(HiveWriter.java:86)
	at io.trino.plugin.hive.HivePageSink.doFinish(HivePageSink.java:190)
	at io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:98)
	at io.trino.plugin.hive.HivePageSink.finish(HivePageSink.java:181)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:77)
	at io.trino.operator.TableWriterOperator.finish(TableWriterOperator.java:214)
	at io.trino.operator.Driver.processInternal(Driver.java:405)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_359____20210810_024148_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.FileNotFoundException: File does not exist: /warehouse/tablespace/managed/hive/my_db.db/tmp2/delta_0000004_0000004_0000/bucket_00000 (inode 7689792) Holder DFSClient_NONMAPREDUCE_1887014380_74 does not have any open files.
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2815)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.analyzeFileState(FSDirWriteFileOp.java:591)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.validateAddBlock(FSDirWriteFileOp.java:171)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2694)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:875)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:561)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:524)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:876)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:822)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2682)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
	at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1084)
	at org.apache.hadoop.hdfs.DataStreamer.locateFollowingBlock(DataStreamer.java:1865)
	at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1668)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:716)
Caused by: org.apache.hadoop.ipc.RemoteException: File does not exist: /warehouse/tablespace/managed/hive/my_db.db/tmp2/delta_0000004_0000004_0000/bucket_00000 (inode 7689792) Holder DFSClient_NONMAPREDUCE_1887014380_74 does not have any open files.
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2815)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.analyzeFileState(FSDirWriteFileOp.java:591)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.validateAddBlock(FSDirWriteFileOp.java:171)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2694)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:875)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:561)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:524)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:876)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:822)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2682)
	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1511)
	at org.apache.hadoop.ipc.Client.call(Client.java:1457)
	at org.apache.hadoop.ipc.Client.call(Client.java:1367)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
	at com.sun.proxy.$Proxy325.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:513)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy326.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1081)
	... 3 more```

**Comment by vaibhavvasa236** [comment]
Facing Similar issue:
io.trino.spi.TrinoException: Error committing write to Hive
	at io.trino.plugin.hive.SortingFileWriter.commit(SortingFileWriter.java:147)
	at io.trino.plugin.hive.HiveWriter.commit(HiveWriter.java:86)
	at io.trino.plugin.hive.HivePageSink.doFinish(HivePageSink.java:190)
	at io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:95)
	at io.trino.plugin.hive.HivePageSink.finish(HivePageSink.java:181)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:77)
	at io.trino.operator.TableWriterOperator.finish(TableWriterOperator.java:208)
	at io.trino.operator.Driver.processInternal(Driver.java:405)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_358____20210920_212926_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.UncheckedIOException: java.io.FileNotFoundException: File /tmp/presto-admin/.tmp-sort.hour=13.000059_0_20210920_213053_00001_5veb2.3 does not exist
	at io.trino.plugin.hive.SortingFileWriter.mergeFiles(SortingFileWriter.java:236)
	at io.trino.plugin.hive.SortingFileWriter.writeSorted(SortingFileWriter.java:192)
	at io.trino.plugin.hive.SortingFileWriter.commit(SortingFileWriter.java:143)
	... 18 more
Caused by: java.io.FileNotFoundException: File /tmp/presto-admin/.tmp-sort.hour=13.000059_0_20210920_213053_00001_5veb2.3 does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:666)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:987)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:656)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:454)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:454)
	at io.trino.plugin.hive.SortingFileWriter.mergeFiles(SortingFileWriter.java:217)
	... 20 more

**Comment by hashhar** [comment]
Can you try with a build that includes https://github.com/trinodb/trino/pull/8899? The first version that includes it is 361.

**Comment by vaibhavvasa236** [comment]
HI @hashhar ,

The issue still happens post upgrading trino to version 361. However the issue does not appear if we set hive.temporary-staging-directory-enabled=false
Can we reopen this?

**Comment by aakashnand** [comment]
@vaibhavvasa236 from your error message it seems that the staging directory is not getting created or getting deleted. I would recommend you to use "watch" command to check what is happening to staging directory as you execute the query. 

The second point is to check the directory permissions, So please check that user you are using in jvm.config for the property
-DHADOOP_USER_NAME is hive. In the documentation it is mentioned whenever you change HDFS_USER you need to delete the existing tmp/presto-* directories

https://trino.io/docs/current/connector/hive.html#hdfs-username-and-permissions

**Comment by gulivan** [comment]
Experiencing the same issue with `432` version

<img width="699" alt="image" src="https://github.com/trinodb/trino/assets/34831957/a39693f5-74b4-439a-a213-402b28a7eaab">

**Comment by Shoham-a** [comment]
I had this problem when I wanted to create a table using Trino + DBT. apparently it's about the syntax of the bucket I gave it. 

I wanted to create my table on location 's3://mybucket' when my bucket was actually 's3://MYBUCKET'. 

Hope that helps if someone has a similar case.
