### ISSUE TITLE
Not able to get column information from information_schema when struct field name contains a slash "/" character

### ISSUE THREAD

**Issue by fcomuniz** [trinodb/trino#9013]
I have an environment where i have trino (358) connected to a hive metastore (3.1.2), and trying to get the information schema for all the columns in the connector, i ran the following query

```
SELECT
            lower(col_name) AS col_name,
            c.column_comment AS col_description,
            lower(c.data_type) AS col_type,
            c.ordinal_position AS col_sort_order,
            c.table_catalog AS cluster,
            lower(c.table_schema) AS "schema",
            lower(c.table_name) AS name,
            t.table_comment AS description,
            case when lower(t.table_type) = 'view' then 'true' else 'false' end AS is_view
            FROM
            INFORMATION_SCHEMA.COLUMNS AS c
            LEFT JOIN
            INFORMATION_SCHEMA.TABLES t
                ON c.TABLE_NAME = t.TABLE_NAME
                AND c.TABLE_SCHEMA = t.TABLE_SCHEMA
            ORDER by cluster, "schema", name, col_sort_order 
```

This gave me an error when running the query

```
java.lang.IllegalArgumentException: Error: : expected at the position 9 of 'struct<24/7:string,gxr:string,lzone:string,ladies:string,livegx:string,pt:string,physiotherapist:string,yanga:string>' but '/' is found.
	at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.expect(TypeInfoUtils.java:413)
	at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.expect(TypeInfoUtils.java:384)
	at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.parseType(TypeInfoUtils.java:541)
	at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.parseTypeInfos(TypeInfoUtils.java:358)
	at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils.getTypeInfoFromTypeString(TypeInfoUtils.java:865)
	at io.trino.plugin.hive.HiveType.valueOf(HiveType.java:192)
```
I ommited the traceback for the rest to avoid too much output.

It looks like Trino uses hive to get the type info, but looks like it fails on a type with / on the type name, which is the case on the column that it fails "struct<24/7:string,gxr:string,lzone:string,ladies:string,livegx:string,pt:string,physiotherapist:string,yanga:string>"

Should trino pass field name information for the type for hive?

Thanks for any help

**Comment by hashhar** [comment]
cc: @alexjo2144 since you were looking into weirdly named columns behaviour in the Hive/Iceberg connectors.

**Comment by electrum** [comment]
The way to fix this is to wrap the call to `getTypeInfoFromTypeString` to return a proper exception:
```java
private static TypeInfo getHiveTypeInfo(String typeString)
{
    try {
        return getTypeInfoFromTypeString(typeString);
    }
    catch (IllegalArgumentException e) {
        throw new TrinoException(HIVE_INVALID_METADATA, "Invalid Hive type: " + typeString);
    }
}
```
We should do the same for the `getTypeInfosFromTypeString` call.

**Comment by electrum** [comment]
How did you create this table? None of the Hive code (likely including the metastore) can handle this due to being unable to parse the type name.

**Comment by fcomuniz** [comment]
i created the table using spark, connecting to the metastore through thrift, but the underlying table format is iceberg, so i used spark with IcebergCatalog.

**Comment by findepi** [comment]
Indeed, Hive doesn't seem to allow a struct field to contain `/`  (a table column name can contain the slash though).

@fcomuniz  Is this problem specific to Iceberg?

cc @losipiuk @phd3  @joshthoward

**Comment by fcomuniz** [comment]
I seems that way, is the only situation i encontered this issue

**Comment by meatheadmike** [comment]
I get this exact same error in my environment. I'm on the latest Trino, the latest Iceberg (1.11.0) and hive v3.x. My struct column has a colon in it instead of a slash. Is there a fix for this? Or is Trino just unable to query structs with special characters in the field names?
