### ISSUE TITLE
system.metadata.materialized_views fails when a materialized view removed during reading

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9041]
When  reading from `system.metadata.materialized_views` and a materialized view gets dropped concurrently, the query fails with 

```
Caused by: java.lang.NullPointerException
	at io.trino.plugin.iceberg.IcebergMetadata.getTableToken(IcebergMetadata.java:820)
	at io.trino.plugin.iceberg.IcebergMetadata.isTableCurrent(IcebergMetadata.java:828)
	at io.trino.plugin.iceberg.IcebergMetadata.getMaterializedViewFreshness(IcebergMetadata.java:856)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getMaterializedViewFreshness(ClassLoaderSafeConnectorMetadata.java:911)
	at io.trino.metadata.MetadataManager.getMaterializedViewFreshness(MetadataManager.java:1395)
	at io.trino.connector.system.MaterializedViewSystemTable.lambda$cursor$0(MaterializedViewSystemTable.java:105)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
	at io.trino.connector.system.MaterializedViewSystemTable.lambda$cursor$1(MaterializedViewSystemTable.java:103)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at com.google.common.collect.RegularImmutableSortedSet.forEach(RegularImmutableSortedSet.java:86)
	at io.trino.connector.system.MaterializedViewSystemTable.cursor(MaterializedViewSystemTable.java:100)
	at io.trino.connector.system.SystemPageSourceProvider$1.cursor(SystemPageSourceProvider.java:129)
	at io.trino.split.MappedRecordSet.cursor(MappedRecordSet.java:53)
	at io.trino.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
	at io.trino.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:108)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:267)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:195)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.trino.metadata.MetadataManager.getMaterializedView(MetadataManager.java:1380)
	at io.trino.execution.DropTableTask.execute(DropTableTask.java:59)
	at io.trino.execution.DropTableTask.execute(DropTableTask.java:37)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:170)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20210830_151149_2100.run(Unknown Source)
```

See https://github.com/trinodb/trino/issues/9040. That issue covers test flakiness and hopefully will be resolved soon, but the problem with production code remains. 

cc @sopel39 @raunaqmorarka @joshthoward

**Comment by raunaqmorarka** [comment]
Since MV freshness is not available as part of `getMaterializedView`, we have to make a separate `getMaterializedViewFreshness` metadata call for it. If the MV is dropped concurrently meanwhile, I think connector code should at least handle it gracefully and throw MaterializedViewNotFoundException. Then we could handle that exception in the MV listing code.
In this case, `IcebergMetada#getMaterializedViewFreshness` should definitely do a null check on the return of the getTableHandle call that it makes.

**Comment by Justin-Kwan** [comment]
Would it be helpful to unify the MV representation, where one could get a materialized view which contains its freshness status without making another call?

**Comment by Justin-Kwan** [comment]
We could also introduce `NoneIcebergTableHandle` and return that if the table is missing to avoid any sort of null checks as well.

**Comment by sopel39** [comment]
> Then we could handle that exception in the MV listing code.

Something similar as https://github.com/trinodb/trino/commit/d1417dc5f266942ad8d304e1639de47b2dba3033

**Comment by findepi** [comment]
> Since MV freshness is not available as part of `getMaterializedView`, we have to make a separate `getMaterializedViewFreshness` metadata call for it.

@raunaqmorarka @sopel39  can you share reasoning behind that?

**Comment by raunaqmorarka** [comment]
> > Since MV freshness is not available as part of `getMaterializedView`, we have to make a separate `getMaterializedViewFreshness` metadata call for it.
> 
> @raunaqmorarka @sopel39 can you share reasoning behind that?

Reasoning behind separate APIs ?
idk that was introduced before I got involved, maybe @martint would know

**Comment by findepi** [comment]
Unless `getMaterializedViewFreshness` is expensive to call, would we consider folding this into `getMaterializedView`?

**Comment by sopel39** [comment]
> Unless getMaterializedViewFreshness is expensive to call, would we consider folding this into getMaterializedView?

I think it might be expensive to call, but I wouldn't fold it into `getMaterializedView` just because it's harder to list MVs
