### ISSUE TITLE
TestHiveViews.testNestedGroupBy is flaky when executing query on Hive

### ISSUE THREAD

**Issue by Praveen2112** [trinodb/trino#9074]
Stress check on [cdh-5](https://github.com/trinodb/trino/pull/9069/checks) shows flakiness.

**Comment by findepi** [comment]
What is the stacktrace it is failing with?

**Comment by Praveen2112** [comment]
```
2021-09-01T10:36:03.4716978Z tests               | 2021-09-01 16:21:03 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveViewsLegacy.testNestedGroupBy (Groups: hive_views) took 3.0 seconds
2021-09-01T10:36:03.4732868Z tests               | 2021-09-01 16:21:03 SEVERE: Failure cause:
2021-09-01T10:36:03.4734951Z tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
2021-09-01T10:36:03.4737278Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
2021-09-01T10:36:03.4739098Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2021-09-01T10:36:03.4741401Z tests               | 	at io.trino.tests.product.hive.AbstractTestHiveViews.assertViewQuery(AbstractTestHiveViews.java:534)
2021-09-01T10:36:03.4744138Z tests               | 	at io.trino.tests.product.hive.AbstractTestHiveViews.testNestedGroupBy(AbstractTestHiveViews.java:451)
2021-09-01T10:36:03.4746424Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-09-01T10:36:03.4748483Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-09-01T10:36:03.4751322Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-01T10:36:03.4753512Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-01T10:36:03.4755605Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-09-01T10:36:03.4757756Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-09-01T10:36:03.4759408Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-09-01T10:36:03.4761409Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-09-01T10:36:03.4763770Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-09-01T10:36:03.4765840Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-09-01T10:36:03.4767514Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-09-01T10:36:03.4769279Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-09-01T10:36:03.4770447Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-09-01T10:36:03.4771844Z tests               | Caused by: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
2021-09-01T10:36:03.4773849Z tests               | 	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:275)
2021-09-01T10:36:03.4776007Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
2021-09-01T10:36:03.4778438Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
2021-09-01T10:36:03.4779610Z tests               | 	... 16 more
2021-09-01T10:36:03.4780362Z tests               | 	Suppressed: java.lang.Exception: Query: SELECT * FROM test_nested_group_by_view
2021-09-01T10:36:03.4782255Z tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
2021-09-01T10:36:03.4783796Z tests               | 		... 17 more
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/3531888652 `pt (cdh5, suite-1, false)`

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/3538243209

**Comment by findepi** [comment]
The test is now marked `@Flaky(issue = "https://github.com/trinodb/trino/issues/9074", match = "Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask")`, but this doesn't seem to help, as it may fail couple times in a row.

cc @losipiuk
