### ISSUE TITLE
Investigate Spark throwing exceptions during Iceberg product tests

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9078]
While running `TestIcebergSparkCompatibility` on `SinglenodeSparkIceberg` (which is what CI does) these get logged very repeatedly

```
spark               | org.apache.thrift.transport.TTransportException
spark               | 	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
spark               | 	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
spark               | 	at org.apache.thrift.transport.TSaslTransport.readLength(TSaslTransport.java:374)
spark               | 	at org.apache.thrift.transport.TSaslTransport.readFrame(TSaslTransport.java:451)
spark               | 	at org.apache.thrift.transport.TSaslTransport.read(TSaslTransport.java:433)
spark               | 	at org.apache.thrift.transport.TSaslServerTransport.read(TSaslServerTransport.java:43)
spark               | 	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
spark               | 	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:425)
spark               | 	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:321)
spark               | 	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:225)
spark               | 	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27)
spark               | 	at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:53)
spark               | 	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:310)
spark               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
spark               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
spark               | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

even though tests are passing.

(the above comes from running the test locally)

this should be investigated whether our test setup is configured correctly

cc @phd3 @joshthoward @losipiuk

**Comment by pajaks** [comment]
https://github.com/trinodb/trino/actions/runs/4111284237/jobs/7095536455
