### ISSUE TITLE
TestHiveTransactionalTable.testPartitionedInsertAndRowLevelDelete is flaky

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#9083]
TestHiveTransactionalTable.testPartitionedInsertAndRowLevelDelete fails with a stack trace as below. This is a concerning failure since the error occurs for Trino - Hive isn't involved at the point where the failure occurs.

```
tests               | 2021-09-01 20:35:46 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveTransactionalTable.testPartitionedInsertAndRowLevelDelete [TRINO, HIVE] (Groups: hive_transactional) took 3.8 seconds
tests               | 2021-09-01 20:35:46 SEVERE: Failure cause:
tests               | java.lang.AssertionError: [onTrino] Could not find rows:
tests               | [40]
tests               | 
tests               | actual rows:
tests               | [60]
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.verifySelect(TestHiveTransactionalTable.java:1930)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.verifySelectForTrinoAndHive(TestHiveTransactionalTable.java:1920)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.lambda$testPartitionedInsertAndRowLevelDelete$17(TestHiveTransactionalTable.java:779)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.withTemporaryTable(TestHiveTransactionalTable.java:1632)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.testPartitionedInsertAndRowLevelDelete(TestHiveTransactionalTable.java:767)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
tests               | 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

_Originally posted by @hashhar in https://github.com/trinodb/trino/issues/9076#issuecomment-910449840_

**Comment by findepi** [comment]
Merging this issue into https://github.com/trinodb/trino/issues/14519
