### ISSUE TITLE
TestHiveTableStatistics.testMixedHiveAndPrestoStatistics is flaky

### ISSUE THREAD

**Issue by Praveen2112** [trinodb/trino#9089]
It was seen during the stress checks on [cdh5](https://github.com/trinodb/trino/runs/3484927156). 

```
2021-09-01T14:10:35.0563954Z tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
2021-09-01T14:10:35.0566640Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
2021-09-01T14:10:35.0568568Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2021-09-01T14:10:35.0571714Z tests               | 	at io.trino.tests.product.hive.TestHiveTableStatistics.testMixedHiveAndPrestoStatistics(TestHiveTableStatistics.java:1504)
2021-09-01T14:10:35.0574952Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-09-01T14:10:35.0577087Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-09-01T14:10:35.0579552Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-01T14:10:35.0582939Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-01T14:10:35.0584564Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-09-01T14:10:35.0586298Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-09-01T14:10:35.0587607Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-09-01T14:10:35.0589184Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-09-01T14:10:35.0590932Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-09-01T14:10:35.0592643Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-09-01T14:10:35.0594456Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-09-01T14:10:35.0596189Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-09-01T14:10:35.0597369Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-09-01T14:10:35.0598759Z tests               | Caused by: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
2021-09-01T14:10:35.0600463Z tests               | 	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:275)
2021-09-01T14:10:35.0602331Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
2021-09-01T14:10:35.0604323Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
2021-09-01T14:10:35.0605350Z tests               | 	... 15 more
2021-09-01T14:10:35.0606213Z tests               | 	Suppressed: java.lang.Exception: Query: ANALYZE TABLE test_mixed_hive_and_presto_statistics PARTITION (p = "2") COMPUTE STATISTICS FOR COLUMNS
2021-09-01T14:10:35.0608009Z tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
2021-09-01T14:10:35.0609341Z tests               | 		... 16 more
```

**Comment by hashhar** [comment]
Other tests can fail with same cause. e.g. `testShowStatisticsForExternalTable`

```
tests               | 2021-09-03 15:03:47 INFO: FAILURE     /    io.trino.tests.product.hive.TestExternalHiveTable.testShowStatisticsForExternalTable (Groups: ) took 6.1 seconds
tests               | 2021-09-03 15:03:47 SEVERE: Failure cause:
tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.hive.TestExternalHiveTable.testShowStatisticsForExternalTable(TestExternalHiveTable.java:75)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:829)
tests               | Caused by: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
tests               | 	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:275)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 	... 15 more
tests               | 	Suppressed: java.lang.Exception: Query: ANALYZE TABLE target_table PARTITION (p_regionkey) COMPUTE STATISTICS FOR COLUMNS
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
tests               | 		... 16 more
```

**Comment by findepi** [comment]
Supposedly fixed by https://github.com/trinodb/trino/pull/9595. Please reopen this (or maybe https://github.com/trinodb/trino/issues/9472) if seen again.
cc @homar
