### ISSUE TITLE
Support LZ4 compression with native Parquet writer

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9142]
per https://trino.io/blog/2020/01/01/2019-summary.html

> Support for LZ4 and Zstd compression in Parquet and ORC. LZ4 is currently the recommended algorithm for fast, lightweight compression, and Zstd otherwise.

let's support LZ4 with the native Parquet writer

currently it fails:

```
Caused by: java.lang.RuntimeException: Unsupported codec: LZ4
	at io.trino.parquet.writer.ParquetCompressor.getCompressor(ParquetCompressor.java:56)
	at io.trino.parquet.writer.PrimitiveColumnWriter.<init>(PrimitiveColumnWriter.java:101)
	at io.trino.parquet.writer.ParquetWriters$WriteBuilder.primitive(ParquetWriters.java:147)
	at io.trino.parquet.writer.ParquetWriters$WriteBuilder.primitive(ParquetWriters.java:78)
	at io.trino.parquet.writer.ParquetTypeVisitor.visit(ParquetTypeVisitor.java:42)
	at io.trino.parquet.writer.ParquetTypeVisitor.visitField(ParquetTypeVisitor.java:118)
	at io.trino.parquet.writer.ParquetTypeVisitor.visitFields(ParquetTypeVisitor.java:129)
	at io.trino.parquet.writer.ParquetTypeVisitor.visit(ParquetTypeVisitor.java:39)
	at io.trino.parquet.writer.ParquetWriters.getColumnWriters(ParquetWriters.java:74)
	at io.trino.parquet.writer.ParquetWriter.<init>(ParquetWriter.java:96)
	at io.trino.plugin.hive.parquet.ParquetFileWriter.<init>(ParquetFileWriter.java:64)
	at io.trino.plugin.hive.parquet.ParquetFileWriterFactory.createFileWriter(ParquetFileWriterFactory.java:119)
	at io.trino.plugin.hive.HiveWriterFactory.createWriter(HiveWriterFactory.java:462)
	at io.trino.plugin.hive.HivePageSink.getWriterIndexes(HivePageSink.java:377)
	at io.trino.plugin.hive.HivePageSink.writePage(HivePageSink.java:277)
	at io.trino.plugin.hive.HivePageSink.doAppend(HivePageSink.java:272)
	at io.trino.plugin.hive.HivePageSink.lambda$appendPage$2(HivePageSink.java:258)
	at io.trino.plugin.hive.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:26)
	at io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.plugin.hive.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:25)
	at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:103)
	at io.trino.plugin.hive.HivePageSink.appendPage(HivePageSink.java:258)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:69)
	at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:263)
	at io.trino.operator.Driver.processInternal(Driver.java:392)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
```

**Comment by raunaqmorarka** [comment]
Parquet format has deprecated LZ4 https://github.com/apache/parquet-format/blob/master/Compression.md#lz4
We should support LZ4_RAW instead.

**Comment by Bukhtawar** [comment]
Any plans to support LZ4_RAW @findepi, @raunaqmorarka?
