### ISSUE TITLE
INSERT INTO TABLE ... TABLE fails at planning when source table has hidden columns

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9150]
```
trino:default> USE hive.default;
USE

trino:default> CREATE TABLE nation AS TABLE tpch.tiny.nation WITH NO DATA;
CREATE TABLE: 0 rows

trino:default> INSERT INTO nation TABLE tpch.tiny.nation;
Query 20210908_094500_00029_c89az failed: inserting non-character value to column of character type
java.lang.IllegalStateException: inserting non-character value to column of character type
	at com.google.common.base.Preconditions.checkState(Preconditions.java:510)
	at io.trino.sql.planner.LogicalPlanner.noTruncationCast(LogicalPlanner.java:632)
	at io.trino.sql.planner.LogicalPlanner.getInsertPlan(LogicalPlanner.java:423)
	at io.trino.sql.planner.LogicalPlanner.createInsertPlan(LogicalPlanner.java:480)
	at io.trino.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:267)
	at io.trino.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:251)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:208)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:203)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:198)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:488)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:468)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:411)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_361_132_ge8b8554____20210908_093156_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findepi** [comment]
Similar to https://github.com/trinodb/trino/issues/6835 but for INSERT. cc @martint @kasiafi
