### ISSUE TITLE
Trino worker fails to connect to hbase with phoenix connector

### ISSUE THREAD

**Issue by cyq89051127** [trinodb/trino#9151]
* Trino version

   358 and newer version

* Description:

  When you connect hbase through phoenix connector by trino, the worker fails but the coorinator works well.  
  
  1. The excpetion as follows :
  
     ```
     JDBC_ERROR: org.apache.phoenix.exception.PhoenixNonRetryableRuntimeException: Could not load/instantiate class org.apache.phoenix.query.DefaultGuidePostsCacheFactory
     io.trino.spi.TrinoException: org.apache.phoenix.exception.PhoenixNonRetryableRuntimeException: Could not load/instantiate class org.apache.phoenix.query.DefaultGuidePostsCacheFactory
     	at io.trino.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:299)
     	at io.trino.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:113)
     	at io.trino.plugin.jdbc.JdbcRecordSet.cursor(JdbcRecordSet.java:63)
     	at io.trino.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
     	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
     	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
     	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:298)
     	at io.trino.operator.Driver.processInternal(Driver.java:387)
     	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
     	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
     	at io.trino.operator.Driver.processFor(Driver.java:284)
     	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
     	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
     	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
     	at io.trino.$gen.Trino_358____20210906_062144_2.run(Unknown Source)
     	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
     	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
     	at java.base/java.lang.Thread.run(Thread.java:834)
     Caused by: org.apache.phoenix.thirdparty.com.google.common.util.concurrent.UncheckedExecutionException: org.apache.phoenix.exception.PhoenixNonRetryableRuntimeException: Could not load/instantiate class org.apache.phoenix.query.DefaultGuidePostsCacheFactory
     	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
     	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCahe.get(LocalCache.java:3849)
     	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4711)
     	at org.apache.phoenix.jdbc.PhoenixDriver.getConnectionQueryServices(PhoenixDriver.java:241)
     	at org.apache.phoenix.jdbc.PhoenixEmbeddedDriver.createConnection(PhoenixEmbeddedDriver.java:144)
     	at org.apache.phoenix.jdbc.PhoenixDriver.connect(PhoenixDriver.java:221)
     	at io.trino.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:65)
     	at io.trino.plugin.jdbc.ConfiguringConnectionFactory.openConnection(ConfiguringConnectionFactory.java:39)
     	at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:42)
     	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
     	at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:42)
     	at io.trino.plugin.jdbc.LazyConnectionFactory.lambda$openConnection$0(LazyConnectionFactory.java:45)
     	at io.trino.plugin.jdbc.LazyConnectionFactory$LazyConnection.getDelegate(LazyConnectionFactory.java:76)
     	at io.trino.plugin.jdbc.ForwardingConnection.setReadOnly(ForwardingConnection.java:124)
     	at io.trino.plugin.jdbc.BaseJdbcClient.getConnection(BaseJdbcClient.java:409)
     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     	at io.trino.plugin.base.util.LoggingInvocationHandler.handleInvocation(LoggingInvocationHandler.java:60)
     	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:86)
     	at com.sun.proxy.$Proxy165.getConnection(Unknown Source)
     	at io.trino.plugin.jdbc.ForwardingJdbcClient.getConnection(ForwardingJdbcClient.java:130)
     	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getConnection$10(StatisticsAwareJdbcClient.java:150)
     	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
     	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getConnection(StatisticsAwareJdbcClient.java:150)
     	at io.trino.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:79)
     	... 16 more
     Caused by: org.apache.phoenix.exception.PhoenixNonRetryableRuntimeException: Could not load/instantiate class org.apache.phoenix.query.DefaultGuidePostsCacheFactory
     	at org.apache.phoenix.query.GuidePostsCacheProvider.loadAndGetGuidePostsCacheFactory(GuidePostsCacheProvider.java:57)
     	at org.apache.phoenix.query.GuidePostsCacheProvider.getGuidePostsCache(GuidePostsCacheProvider.java:73)
     	at org.apache.phoenix.query.ConnectionQueryServicesImpl.<init>(ConnectionQueryServicesImpl.java:457)
     	at org.apache.phoenix.jdbc.PhoenixDriver$3.call(PhoenixDriver.java:248)
     	at org.apache.phoenix.jdbc.PhoenixDriver$3.call(PhoenixDriver.java:241)
     	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4716)
     	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3445)
     	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2194)
     	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2153)
     	at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2043)
     
     ```
  
     
  
  2. Well, the stack of trino coorinator(node-scheduler.include-coordinator=true) is like the following :  
  
     ```
     Query-20210907_080751_00000_fc9pw-165@18714" daemon prio=5 tid=0xa5 nid=NA runnable
       java.lang.Thread.State: RUNNABLE
     	  at java.util.ServiceLoader.load(ServiceLoader.java:1692)
     	  at org.apache.phoenix.util.InstanceResolver.get(InstanceResolver.java:72)
     	  at org.apache.phoenix.query.GuidePostsCacheProvider.loadAndGetGuidePostsCacheFactory(GuidePostsCacheProvider.java:45)
     	  at org.apache.phoenix.query.GuidePostsCacheProvider.getGuidePostsCache(GuidePostsCacheProvider.java:73)
     	  at org.apache.phoenix.query.ConnectionQueryServicesImpl.<init>(ConnectionQueryServicesImpl.java:457)
     	  at org.apache.phoenix.jdbc.PhoenixDriver$3.call(PhoenixDriver.java:248)
     	  at org.apache.phoenix.jdbc.PhoenixDriver$3.call(PhoenixDriver.java:241)
     	  at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4716)
     	  at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3445)
     	  at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2194)
     	  at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2153)
     	  - locked <0x4b49> (a org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$StrongAccessEntry)
     	  at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2043)
     	  at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache.get(LocalCache.java:3849)
     	  at org.apache.phoenix.thirdparty.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4711)
     	  at org.apache.phoenix.jdbc.PhoenixDriver.getConnectionQueryServices(PhoenixDriver.java:241)
     	  at org.apache.phoenix.jdbc.PhoenixEmbeddedDriver.createConnection(PhoenixEmbeddedDriver.java:144)
     	  at org.apache.phoenix.jdbc.PhoenixDriver.connect(PhoenixDriver.java:221)
     	  at io.trino.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:65)
     	  at io.trino.plugin.jdbc.ConfiguringConnectionFactory.openConnection(ConfiguringConnectionFactory.java:39)
     	  at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:42)
     	  at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory$$Lambda$2851.1205532496.call(Unknown Source:-1)
     	  at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
     	  at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:42)
     	  at io.trino.plugin.jdbc.LazyConnectionFactory.lambda$openConnection$0(LazyConnectionFactory.java:45)
     	  at io.trino.plugin.jdbc.LazyConnectionFactory$$Lambda$2849.234461411.get(Unknown Source:-1)
     	  at io.trino.plugin.jdbc.LazyConnectionFactory$LazyConnection.getDelegate(LazyConnectionFactory.java:76)
     	  - locked <0x4b4a> (a io.trino.plugin.jdbc.LazyConnectionFactory$LazyConnection)
     	  at io.trino.plugin.jdbc.ForwardingConnection.getMetaData(ForwardingConnection.java:117)
     	  at io.trino.plugin.jdbc.mapping.DefaultIdentifierMapping.storesUpperCaseIdentifiers(DefaultIdentifierMapping.java:82)
     	  at io.trino.plugin.jdbc.mapping.DefaultIdentifierMapping.toRemoteIdentifier(DefaultIdentifierMapping.java:70)
     	  at io.trino.plugin.jdbc.mapping.DefaultIdentifierMapping.toRemoteSchemaName(DefaultIdentifierMapping.java:53)
     	  at io.trino.plugin.jdbc.BaseJdbcClient.getTableHandle(BaseJdbcClient.java:234)
     	  at io.trino.plugin.phoenix5.PhoenixMetadata.getTableHandle(PhoenixMetadata.java:80)
     	  at io.trino.plugin.phoenix5.PhoenixMetadata.getTableHandle(PhoenixMetadata.java:59)
     	  at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableHandle(ClassLoaderSafeConnectorMetadata.java:206)
     	  at io.trino.metadata.MetadataManager.lambda$getTableHandle$5(MetadataManager.java:389)
     	  at io.trino.metadata.MetadataManager$$Lambda$2848.833372125.apply(Unknown Source:-1)
     	  at java.util.Optional.flatMap(Optional.java:294)
     	  at io.trino.metadata.MetadataManager.getTableHandle(MetadataManager.java:383)
     	  at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1350)
     	  at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1317)
     	  at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:367)
     	  at io.trino.sql.tree.Table.accept(Table.java:53)
     	  at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
     	  at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:384)
     	  at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3256)
     	  at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2051)
     	  at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:367)
     	  at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
     	  at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
     	  at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:384)
     	  at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:394)
     	  at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1154)
     	  at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:367)
     	  at io.trino.sql.tree.Query.accept(Query.java:107)
     	  at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
     	  at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:384)
     	  at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:347)
     	  at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
     	  at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
     	  at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)
     	  at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:190)
     	  at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:806)
     	  at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
     	  at io.trino.dispatcher.LocalDispatchQueryFactory$$Lambda$2811.634730624.call(Unknown Source:-1)
     	  at io.trino.$gen.Trino_358____20210907_080722_2.call(Unknown Source:-1)
     	  at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
     	  at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
     	  at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
     	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
     	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
     	  at java.lang.Thread.run(Thread.java:834)
     ```

* Reason

  1. Why does it work failed in the worker JVM

     ```
     List<GuidePostsCacheFactory> factoryList = InstanceResolver.get(GuidePostsCacheFactory.class, null);
     ## The get method in InstanceResolver
     public static <T> List get(Class<T> clazz, List<T> defaultInstances) {
             Iterator<T> iterator = ServiceLoader.load(clazz).iterator();
             ...
             return defaultInstances;
         }
     ## The load method in ServiceLoader
     public static <S> ServiceLoader<S> load(Class<S> service) {
             ClassLoader cl = Thread.currentThread().getContextClassLoader();
             return new ServiceLoader<>(Reflection.getCallerClass(), service, cl);
         }
     ```

     In the Worker stack, `Thread.currentThread().getContextClassLoader() is AppClassLoader`, It can't instant the phoenix class at `${TRINO_HOME}/plugin/phoenix5`.

  2. Why does it work well in coordinator JVM

     Checking the Coordinator JVM stack, we could find before calling phoenix, It set the ` Thread.currentThread().getContextClassLoader()` to `PluginClassLoader` in `ClassLoaderSafeConnectorMetadata.getTableHandle`

     ```
     public ConnectorTableHandle getTableHandle(ConnectorSession session, SchemaTableName tableName)
         {
             try (ThreadContextClassLoader ignored = new ThreadContextClassLoader(classLoader)) {
                 return delegate.getTableHandle(session, tableName);
             }
         }
     ```
*

**Comment by hashhar** [comment]
> 358 and newer version

Do you mean this cannot be reproduced on 357 and older? Or did you test only with 358 and newer?

Thanks a lot for doing the in-depth investigation - seems very helpful.

cc: @lhofhansl @wendigo

**Comment by cyq89051127** [comment]
I test this problem on 358 and 361 with phoenix5. But according to the phoenix code , This might be a  long-term problem.

**Comment by Praveen2112** [comment]
Can we check by applying this diff to `PhoenixClientModule`. This might fix for worker. 
```
     {
         binder.bind(ConnectorSplitManager.class).annotatedWith(ForClassLoaderSafe.class).to(PhoenixSplitManager.class).in(Scopes.SINGLETON);
         binder.bind(ConnectorSplitManager.class).to(ClassLoaderSafeConnectorSplitManager.class).in(Scopes.SINGLETON);
-        binder.bind(ConnectorRecordSetProvider.class).to(JdbcRecordSetProvider.class).in(Scopes.SINGLETON);
+        binder.bind(ConnectorRecordSetProvider.class).annotatedWith(ForClassLoaderSafe.class).to(JdbcRecordSetProvider.class).in(Scopes.SINGLETON);
+        binder.bind(ConnectorRecordSetProvider.class).to(ClassLoaderSafeConnectorRecordSetProvider.class).in(Scopes.SINGLETON);
         binder.bind(ConnectorPageSinkProvider.class).annotatedWith(ForClassLoaderSafe.class).to(JdbcPageSinkProvider.class).in(Scopes.SINGLETON);
         binder.bind(ConnectorPageSinkProvider.class).to(ClassLoaderSafeConnectorPageSinkProvider.class).in(Scopes.SINGLETON);
         newOptionalBinder(binder, Key.get(int.class, MaxDomainCompactionThreshold.class));

```

**Comment by cyq89051127** [comment]
@Praveen2112 You're right. It worked.

**Comment by cyq89051127** [comment]
@Praveen2112  @hashhar @joshk @electrum    Do you think It's a bug for trino?  Do you have a plan to fix this ?

**Comment by Praveen2112** [comment]
I'll raise a PR for it.
