### ISSUE TITLE
Incorrect results of COUNT(DISTINCT) queries in MemSQL connector

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#9166]
`TestMemSqlConnectorTest.testCountDistinctWithStringTypes` looks not working.

```bash
Error:  Tests run: 268, Failures: 1, Errors: 0, Skipped: 33, Time elapsed: 465.575 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.memsql.TestMemSqlConnectorTest.testCountDistinctWithStringTypes  Time elapsed: 1.651 s  <<< FAILURE!
java.lang.AssertionError: 
[Rows] 
Expecting:
  <(4)>
to contain exactly in any order:
  <[(7)]>
elements not found:
  <(7)>
and elements not expected:
  <(4)>

	at io.trino.sql.query.QueryAssertions$QueryAssert.lambda$matches$2(QueryAssertions.java:339)
	at io.trino.sql.query.QueryAssertions$QueryAssert.matches(QueryAssertions.java:326)
	at io.trino.sql.query.QueryAssertions$QueryAssert.matches(QueryAssertions.java:321)
	at io.trino.plugin.jdbc.BaseJdbcConnectorTest.testCountDistinctWithStringTypes(BaseJdbcConnectorTest.java:478)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Relates to #8562
cc: @findepi @losipiuk @alexjo2144

**Comment by hashhar** [comment]
Looks like a correctness issue? It's not isolated to tests?

**Comment by ebyhr** [comment]
MemSQL behavior might be different from other connector:
```
memsql> select * from tpch.test_agg;
+------+
| c1   |
+------+
| A    |
|  a   |
| b    |
|      |
| a    |
| a    |
| b    |
| B    |
|  b   |
+------+
9 rows in set (0.01 sec)

memsql>
memsql> select count(distinct c1) from tpch.test_agg;
+--------------------+
| count(distinct c1) |
+--------------------+
|                  5 |
+--------------------+
1 row in set (0.02 sec)
```

**Comment by hashhar** [comment]
A fix is implemented in https://github.com/trinodb/trino/pull/9220. PTAL.
