### ISSUE TITLE
"Expected Limit input to be sorted by ..." exception   from Trino 361

### ISSUE THREAD

**Issue by mozhou1991** [trinodb/trino#9171]
sql:
```
with dim_table as (SELECT t.s_id,t.s_num FROM (VALUES ('11',20),('12',22),('13',40),('14',80)) t(s_id,s_num))
, fact_table as (SELECT t.s_id,t.s_code,t.sales FROM (VALUES ('11','hotel_011',1220),('12','hotel_011',1222),('13','hotel_011',1440)) t(s_id,s_code,sales))
SELECT * FROM (
    SELECT NULL AS A3, K2 AS K2, 0 AS s_order 
      FROM(
        SELECT SUM(t1.sales) AS K2 FROM fact_table t1 
         INNER JOIN (SELECT SUM(s_num) AS s_num FROM dim_table ) t3 ON 1 = 1 
         WHERE 1 = 1 GROUP BY t3.s_num 
         LIMIT 10
    ) x 
    UNION ALL 
    SELECT A3 AS A3, NULL AS K2, 1 AS s_order
      FROM (
          SELECT t1.s_code AS A3, SUM(t1.sales) AS C3 FROM fact_table t1 
           INNER JOIN (SELECT  SUM(s_num) AS s_num, s_id AS s_id FROM dim_table t2 GROUP BY s_id)t3 
              ON t1.s_id = t3.s_id 
          GROUP BY  t1.s_code, t1.s_id, t3.s_num 
          LIMIT 10
     ) x
) MT 
ORDER BY s_order LIMIT 10
```

**run result**
![image](https://user-images.githubusercontent.com/62421826/132654378-0a9bc6bb-4879-4f0e-8707-b44e8da58622.png)

**remark**
1、Temporary tables are used to generate data,
2、There is an inner and outer limit statement and there is a union, where there is a JOIN statement in the union and the group field is inconsistent. Wrap the union layer and use order BY and limit conflicts

**Comment by hashhar** [comment]
cc: @raunaqmorarka @sopel39

**Comment by findepi** [comment]
@mozhou1991 many thanks for repro steps!

FWIW here is the full stacktrace from running the above query

```
Query 20210910_084108_00000_9ujk9 failed: Expected Limit input to be sorted by: [expr_6], but was [expr_7, expr_6]
com.google.common.base.VerifyException: Expected Limit input to be sorted by: [expr_6], but was [expr_7, expr_6]
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.visitLimit(ValidateLimitWithPresortedInput.java:107)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.visitLimit(ValidateLimitWithPresortedInput.java:57)
	at io.trino.sql.planner.plan.LimitNode.accept(LimitNode.java:124)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.lambda$visitPlan$0(ValidateLimitWithPresortedInput.java:82)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.visitPlan(ValidateLimitWithPresortedInput.java:82)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.visitPlan(ValidateLimitWithPresortedInput.java:57)
	at io.trino.sql.planner.plan.PlanVisitor.visitExchange(PlanVisitor.java:199)
	at io.trino.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.lambda$visitPlan$0(ValidateLimitWithPresortedInput.java:82)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.visitPlan(ValidateLimitWithPresortedInput.java:82)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.visitPlan(ValidateLimitWithPresortedInput.java:57)
	at io.trino.sql.planner.plan.PlanVisitor.visitExchange(PlanVisitor.java:199)
	at io.trino.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.lambda$visitPlan$0(ValidateLimitWithPresortedInput.java:82)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.visitPlan(ValidateLimitWithPresortedInput.java:82)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.visitPlan(ValidateLimitWithPresortedInput.java:57)
	at io.trino.sql.planner.plan.PlanVisitor.visitTopN(PlanVisitor.java:44)
	at io.trino.sql.planner.plan.TopNNode.accept(TopNNode.java:107)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.lambda$visitPlan$0(ValidateLimitWithPresortedInput.java:82)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.visitPlan(ValidateLimitWithPresortedInput.java:82)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput$Visitor.visitPlan(ValidateLimitWithPresortedInput.java:57)
	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.sanity.ValidateLimitWithPresortedInput.validate(ValidateLimitWithPresortedInput.java:54)
	at io.trino.sql.planner.sanity.PlanSanityChecker.lambda$validateFinalPlan$0(PlanSanityChecker.java:75)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at io.trino.sql.planner.sanity.PlanSanityChecker.validateFinalPlan(PlanSanityChecker.java:75)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:229)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:203)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:198)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:488)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:468)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:411)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_361____20210910_084053_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by martint** [comment]
Here's a smaller repro:

```sql
SELECT *
FROM (
    VALUES (0, 1)
    UNION ALL
    SELECT k, 1
    FROM (
        SELECT k
        FROM (VALUES 1) t(k)
        GROUP BY k
     )
) u(a, b)
ORDER BY b
LIMIT 10
```

**Comment by martint** [comment]
Here's a query that fails in current master:

```sql
SELECT a
FROM (
    SELECT 0, 1
    FROM (
        SELECT 1
        FROM (VALUES (1, 1, 1)) t(k, g, h) -- works if we remove column 'h'
            CROSS JOIN (VALUES 1)
        GROUP BY k
    )
    UNION ALL
    SELECT 0, 1
) u(a, b)
ORDER BY b
LIMIT 10
```

**Comment by martint** [comment]
The failure is because ValidateLimitWithPresortedInput is mischaracterizing whether the input is sorted on the expected columns. In particular, in:

```java
if (sortedColumns.size() < node.getPreSortedInputs().size() ||
    !sortedColumns.subList(0, node.getPreSortedInputs().size()).equals(node.getPreSortedInputs())) {
```

when columns are constant, they can be safely ignored from the prefix check. The code should use `LocalProperties.match` to determine whether the inputs are properly sorted.

**Comment by martint** [comment]
Repro with TPC-H connector:

```sql
SELECT orderkey, custkey 
FROM orders 
WHERE orderkey = 1 AND custkey = 370 
ORDER BY orderkey 
LIMIT 1
```
