### ISSUE TITLE
Flaky TestPinotIntegrationSmokeTest.testNullBehavior

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#9197]
Re-running the test 50 times (using `@Test(invocationCount = 50)`) is sufficient to make it fail after the 10th or so invocation.

```
java.lang.AssertionError: [Rows] 
Expecting:
  <>
to contain exactly in any order:
  <[(null)]>
but could not find the following elements:
  <(null)>

	at io.trino.sql.query.QueryAssertions$QueryAssert.lambda$matches$2(QueryAssertions.java:339)
	at io.trino.sql.query.QueryAssertions$QueryAssert.matches(QueryAssertions.java:326)
	at io.trino.sql.query.QueryAssertions$QueryAssert.matches(QueryAssertions.java:321)
	at io.trino.plugin.pinot.TestPinotIntegrationSmokeTest.testNullBehavior(TestPinotIntegrationSmokeTest.java:745)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

cc: @elonazoulay

**Comment by hashhar** [comment]
The interesting part is that after the first failure all subsequent invocations fail consistently.

**Comment by hashhar** [comment]
Is my assumption that it has to do with the fact that the null record has `updated_at` set to 0L and the realtime table spec has a retention time of 365 days make sense?

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/3564746564
