### ISSUE TITLE
Flaky phoenix5's TestPhoenixConnectorTest.testStddevAggregationPushdown test

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9199]
https://github.com/trinodb/trino/runs/3564747062

```
Error:  Tests run: 230, Failures: 1, Errors: 0, Skipped: 52, Time elapsed: 408.893 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.phoenix5.TestPhoenixConnectorTest.testStddevAggregationPushdown  Time elapsed: 1.112 s  <<< FAILURE!
java.lang.RuntimeException: 
org.apache.phoenix.exception.PhoenixIOException: Failed after attempts=4, exceptions:
2021-09-10T07:41:03.515Z, RpcRetryingCaller{globalStartTime=1631259663509, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.NotServingRegionException: org.apache.hadoop.hbase.NotServingRegionException: hbase:meta,,1.1588230740 is closing
	at org.apache.hadoop.hbase.regionserver.HRegion.startRegionOperation(HRegion.java:8455)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2972)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2967)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2961)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2642)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2569)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42274)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

```

**Comment by findepi** [comment]
failure doesn't look specific to `testStddevAggregationPushdown`. it might be service failure and `testStddevAggregationPushdown` happened to be the last test in the class?

**Comment by phd3** [comment]
a similar looking stacktrace on https://github.com/trinodb/trino/runs/4749356863?check_suite_focus=true

```
Error:  io.trino.plugin.phoenix5.TestPhoenixConnectorTest.testVarcharCharComparison  Time elapsed: 1.075 s  <<< FAILURE!
java.lang.RuntimeException: 
Failed after attempts=4, exceptions:
2022-01-08T18:52:38.309Z, RpcRetryingCaller{globalStartTime=1641667958306, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.NotServingRegionException: org.apache.hadoop.hbase.NotServingRegionException: hbase:meta,,1.1588230740 is closing
	at org.apache.hadoop.hbase.regionserver.HRegion.startRegionOperation(HRegion.java:8455)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2972)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2967)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2961)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2642)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2569)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42274)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

2022-01-08T18:52:38.448Z, RpcRetryingCaller{globalStartTime=1641667958306, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.NotServingRegionException: org.apache.hadoop.hbase.NotServingRegionException: hbase:meta,,1.1588230740 is closing
	at org.apache.hadoop.hbase.regionserver.HRegion.startRegionOperation(HRegion.java:8455)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2972)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2967)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2961)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2642)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2569)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42274)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)
```
