### ISSUE TITLE
Run DevelopmentServer failed with exception Unsupported class file major version 61

### ISSUE THREAD

**Issue by artiship** [trinodb/trino#9273]
Java version: 11.0.12 2021-07-20 LTS
Trino version: 359

```
2021-09-17T10:08:19.944+0800	ERROR	main	io.trino.server.Server	Unsupported class file major version 61
java.lang.IllegalArgumentException: Unsupported class file major version 61
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:158)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:146)
	at io.trino.server.PluginDiscovery.readClass(PluginDiscovery.java:126)
	at io.trino.server.PluginDiscovery.classInterfaces(PluginDiscovery.java:110)
	at io.trino.server.PluginDiscovery.classInterfaces(PluginDiscovery.java:115)
	at io.trino.server.PluginDiscovery.lambda$discoverPlugins$0(PluginDiscovery.java:72)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.server.PluginDiscovery.discoverPlugins(PluginDiscovery.java:73)
	at io.trino.server.DevelopmentPluginsProvider.buildClassLoaderFromPom(DevelopmentPluginsProvider.java:84)
	at io.trino.server.DevelopmentPluginsProvider.doBuildClassLoader(DevelopmentPluginsProvider.java:72)
	at io.trino.server.DevelopmentPluginsProvider.buildClassLoader(DevelopmentPluginsProvider.java:60)
	at io.trino.server.DevelopmentPluginsProvider.lambda$loadPlugins$0(DevelopmentPluginsProvider.java:53)
	at io.trino.server.PluginManager.loadPlugin(PluginManager.java:121)
	at io.trino.server.DevelopmentPluginsProvider.loadPlugins(DevelopmentPluginsProvider.java:53)
	at io.trino.server.PluginManager.loadPlugins(PluginManager.java:110)
	at io.trino.server.Server.doStart(Server.java:122)
	at io.trino.server.Server.lambda$start$0(Server.java:77)
	at io.trino.$gen.Trino_dev____20210917_020754_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:77)
	at io.trino.server.DevelopmentServer.main(DevelopmentServer.java:41)


2021-09-17T10:08:19.947+0800	INFO	Thread-76	io.airlift.bootstrap.LifeCycleManager	JVM is shutting down, cleaning up
```

**Comment by findepi** [comment]
If you compiled the project with Java 17, you also need to use Java 17 for run time.
