### ISSUE TITLE
io.airlift.discovery.client.Announcer   Cannot connect to discovery server for announce

### ISSUE THREAD

**Issue by yunfeng79** [trinodb/trino#9364]
coordinator

coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=30080
query.max-memory=30GB
query.max-memory-per-node=2GB
query.max-total-memory-per-node=4GB
discovery-server.enabled=true
discovery.uri=http://192.168.0.120:30080

worker node1
coordinator=false
http-server.http.port=30080
query.max-memory=30GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
discovery.uri=http://192.168.0.120:30080

worker node2 
coordinator=false
http-server.http.port=30080
query.max-memory=30GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
discovery.uri=http://192.168.0.120:30080

worker node2 start error log

2021-09-24T14:19:38.671+0800    INFO    main    io.trino.server.Server  ======== SERVER STARTED ========
2021-09-24T14:19:38.671+0800    ERROR   Announcer-0     io.airlift.discovery.client.Announcer   Cannot connect to discovery server for announce
io.airlift.discovery.client.DiscoveryException: Announcement failed with status code 404: 
        at io.airlift.discovery.client.HttpDiscoveryAnnouncementClient$1.handle(HttpDiscoveryAnnouncementClient.java:104)
        at io.airlift.discovery.client.HttpDiscoveryAnnouncementClient$1.handle(HttpDiscoveryAnnouncementClient.java:97)
        at io.airlift.http.client.jetty.JettyResponseFuture.processResponse(JettyResponseFuture.java:99)
        at io.airlift.http.client.jetty.JettyResponseFuture.completed(JettyResponseFuture.java:76)
        at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:90)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
        at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481)
        at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461)
        at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:424)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:365)
        at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:591)
        at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1662)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1545)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:204)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:144)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:79)
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:172)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
        at java.base/java.lang.Thread.run(Thread.java:834)

2021-09-24T14:19:38.672+0800    ERROR   Announcer-0     io.airlift.discovery.client.Announcer   Service announcement failed after 25.05ms. Next request will happen within 0.00s
2021-09-24T14:19:38.683+0800    ERROR   Announcer-1     io.airlift.discovery.client.Announcer   Service announcement failed after 7.82ms. Next request will happen within 1.00ms
2021-09-24T14:19:38.692+0800    ERROR   Announcer-2     io.airlift.discovery.client.Announcer   Service announcement failed after 6.85ms. Next request will happen within 2.00ms

**Comment by yunfeng79** [comment]
node2  ping  coordinator
