### ISSUE TITLE
Querying a Parquet backed table with real values in the WHERE clause throws an exception

### ISSUE THREAD

**Issue by lhofhansl** [trinodb/trino#9382]
Script:
```
CREATE TABLE hivems.default.test_parquet (pk1 integer,v1 real,v2 real,v3 real) WITH (format = 'PARQUET');
insert into hivems.default.test_parquet values (rand()*1000000000, rand(), rand(), rand());
-- Repeat 20x
insert into hivems.default.test_parquet select rand()*1000000000, rand(), rand(), rand() from hivems.default.test_parquet;

-- now this fails:
select count(*) from hivems.default.test_parquet where v2 < 0.00001;

Query 20210925_172448_00046_22m7k, FAILED, 1 node
Splits: 38 total, 18 done (47.37%)
0.23 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20210925_172448_00046_22m7k failed: Failed reading parquet data; source= hdfs://localhost:9000/hive/test_parquet/20210925_172144_00042_22m7k_e4ec253f-f3e4-4898-b451-a73d0772ca7f; can not read class org.apache.parquet.format.PageHeader: Socket is closed by peer.

-- strangely this works:
select count(*) from hivems.default.test_parquet where v2 < 0.001;
_col0
-------
1000
(1 row)

-- and this too:
select count(*) from hivems.default.test_parquet where v2 < 1.00001;
_col0
---------
1048576
(1 row)
```

**Comment by lhofhansl** [comment]
Full exception:
```
Query 20210925_172816_00053_22m7k failed: Failed reading parquet data; source= hdfs://localhost:9000/hive/test_parquet/20210925_172144_00042_22m7k_e4ec253f-f3e4-4898-b451-a73d0772ca7f; can not read class org.apache.parquet.format.PageHeader: Socket is closed by peer.
io.trino.spi.TrinoException: Failed reading parquet data; source= hdfs://localhost:9000/hive/test_parquet/20210925_172144_00042_22m7k_e4ec253f-f3e4-4898-b451-a73d0772ca7f; can not read class org.apache.parquet.format.PageHeader: Socket is closed by peer.
at io.trino.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:230)
at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:396)
at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:375)
at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:282)
at io.trino.operator.project.DictionaryAwarePageFilter.filter(DictionaryAwarePageFilter.java:59)
at io.trino.operator.project.PageProcessor.createWorkProcessor(PageProcessor.java:121)
at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.lambda$processPageSource$1(ScanFilterAndProjectOperator.java:293)
at io.trino.operator.WorkProcessorUtils.lambda$flatMap$4(WorkProcessorUtils.java:245)
at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:151)
at io.trino.operator.Driver.processInternal(Driver.java:387)
at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
at io.trino.operator.Driver.tryWithLock(Driver.java:683)
at io.trino.operator.Driver.processFor(Driver.java:284)
at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
at io.trino.$gen.Trino_351_2513_geb9b5ef____20210925_171753_2.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: can not read class org.apache.parquet.format.PageHeader: Socket is closed by peer.
at org.apache.parquet.format.Util.read(Util.java:365)
at org.apache.parquet.format.Util.readPageHeader(Util.java:132)
at org.apache.parquet.format.Util.readPageHeader(Util.java:127)
at io.trino.parquet.reader.ParquetColumnChunk.readPageHeader(ParquetColumnChunk.java:76)
at io.trino.parquet.reader.ParquetColumnChunk.readAllPages(ParquetColumnChunk.java:89)
at io.trino.parquet.reader.ParquetReader.createPageReader(ParquetReader.java:388)
at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:368)
at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:444)
at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:427)
at io.trino.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:224)
... 39 more
Caused by: io.trino.hive.$internal.parquet.org.apache.thrift.transport.TTransportException: Socket is closed by peer.
at io.trino.hive.$internal.parquet.org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:130)
at io.trino.hive.$internal.parquet.org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
at io.trino.hive.$internal.parquet.org.apache.thrift.protocol.TCompactProtocol.readByte(TCompactProtocol.java:635)
at io.trino.hive.$internal.parquet.org.apache.thrift.protocol.TCompactProtocol.readFieldBegin(TCompactProtocol.java:541)
at org.apache.parquet.format.InterningProtocol.readFieldBegin(InterningProtocol.java:155)
at org.apache.parquet.format.PageHeader$PageHeaderStandardScheme.read(PageHeader.java:1026)
at org.apache.parquet.format.PageHeader$PageHeaderStandardScheme.read(PageHeader.java:1019)
at org.apache.parquet.format.PageHeader.read(PageHeader.java:896)
at org.apache.parquet.format.Util.read(Util.java:362)
... 48 more
```

**Comment by lhofhansl** [comment]
I didn't have time to investigate further...

#9338 could be a suspect.

**Comment by hashhar** [comment]
cc: @findepi @alexjo2144

**Comment by martint** [comment]
@lhofhansl, can you try turning off use of column indexes? We’ve seen similar reports, and it might be related to that. Thanks for the repro. I’ll try to debug it.

**Comment by martint** [comment]
cc @JamesRTaylor

**Comment by findepi** [comment]
Let's close this in favor of https://github.com/trinodb/trino/issues/9097.

**Comment by martint** [comment]
We should copy the repro steps to the other issue so that we don’t lose track of it.

**Comment by lhofhansl** [comment]
I can confirm that with column indexes turned off the query works as expected.
