### ISSUE TITLE
Flaky test TestParquetReader.testSchemaWithRepeatedOptionalRequiredFields

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#9392]
```bash
2021-09-27T02:04:14.3093596Z [ERROR] Tests run: 2942, Failures: 1, Errors: 0, Skipped: 89, Time elapsed: 1,813.994 s <<< FAILURE! - in TestSuite
2021-09-27T02:04:14.3098746Z [ERROR] io.trino.plugin.hive.parquet.TestParquetReader.testSchemaWithRepeatedOptionalRequiredFields  Time elapsed: 0.931 s  <<< FAILURE!
2021-09-27T02:04:14.3101936Z org.apache.parquet.io.ParquetDecodingException: Dictionary is missing for Page
2021-09-27T02:04:14.3104557Z 	at io.trino.parquet.reader.PrimitiveColumnReader.initDataReader(PrimitiveColumnReader.java:409)
2021-09-27T02:04:14.3107734Z 	at io.trino.parquet.reader.PrimitiveColumnReader.readPageV2(PrimitiveColumnReader.java:393)
2021-09-27T02:04:14.3110422Z 	at io.trino.parquet.reader.PrimitiveColumnReader.readNextPage(PrimitiveColumnReader.java:356)
2021-09-27T02:04:14.3113041Z 	at io.trino.parquet.reader.PrimitiveColumnReader.readPrimitive(PrimitiveColumnReader.java:210)
2021-09-27T02:04:14.3115526Z 	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:370)
2021-09-27T02:04:14.3117839Z 	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:444)
2021-09-27T02:04:14.3120150Z 	at io.trino.parquet.reader.ParquetReader.readArray(ParquetReader.java:289)
2021-09-27T02:04:14.3122107Z 	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:441)
2021-09-27T02:04:14.3124082Z 	at io.trino.parquet.reader.ParquetReader.readStruct(ParquetReader.java:325)
2021-09-27T02:04:14.3126277Z 	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:435)
2021-09-27T02:04:14.3128296Z 	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:427)
2021-09-27T02:04:14.3130760Z 	at io.trino.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:224)
2021-09-27T02:04:14.3132648Z 	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:396)
2021-09-27T02:04:14.3133944Z 	at io.trino.spi.block.LazyBlock$LazyData.getTopLevelBlock(LazyBlock.java:365)
2021-09-27T02:04:14.3135294Z 	at io.trino.spi.block.LazyBlock.getBlock(LazyBlock.java:270)
2021-09-27T02:04:14.3136549Z 	at io.trino.spi.block.LazyBlock.isNull(LazyBlock.java:253)
2021-09-27T02:04:14.3138669Z 	at io.trino.plugin.hive.parquet.ParquetTester.decodeObject(ParquetTester.java:712)
2021-09-27T02:04:14.3141371Z 	at io.trino.plugin.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:492)
2021-09-27T02:04:14.3143877Z 	at io.trino.plugin.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:473)
2021-09-27T02:04:14.3146379Z 	at io.trino.plugin.hive.parquet.ParquetTester.assertFileContents(ParquetTester.java:465)
2021-09-27T02:04:14.3151760Z 	at io.trino.plugin.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:367)
2021-09-27T02:04:14.3155438Z 	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:301)
2021-09-27T02:04:14.3158720Z 	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:281)
2021-09-27T02:04:14.3160969Z 	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:254)
2021-09-27T02:04:14.3165132Z 	at io.trino.plugin.hive.parquet.AbstractTestParquetReader.testSchemaWithRepeatedOptionalRequiredFields(AbstractTestParquetReader.java:1026)
2021-09-27T02:04:14.3168896Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-09-27T02:04:14.3171280Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-09-27T02:04:14.3174280Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-27T02:04:14.3176499Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-27T02:04:14.3178191Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-09-27T02:04:14.3179985Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-09-27T02:04:14.3181336Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-09-27T02:04:14.3182991Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-09-27T02:04:14.3185089Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-09-27T02:04:14.3187379Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-09-27T02:04:14.3189136Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-09-27T02:04:14.3190946Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-09-27T02:04:14.3192156Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

https://github.com/trinodb/trino/runs/3715532329

**Comment by raunaqmorarka** [comment]
Probably same underlying issue as https://github.com/trinodb/trino/issues/10038
Not reported in a while, closing
