### ISSUE TITLE
Hive cannot read files written by the native Trino parquet writer

### ISSUE THREAD

**Issue by joshthoward** [trinodb/trino#9416]
Hives (HDP 2.6, HDP 3.1, and CDH 5.15) produce the following error when attempting to read VARCHAR data written by the native Trino Parquet writer. 

```
Caused by: java.sql.SQLException: java.io.IOException: org.apache.hadoop.hive.ql.metadata.HiveException:
java.lang.ClassCastException: org.apache.hadoop.io.BytesWritable cannot be cast to org.apache.hadoop.hive.serde2.io.HiveVarcharWritable
	at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:121)
	at org.apache.hive.jdbc.Utils.verifySuccessWithInfo(Utils.java:109)
	at org.apache.hive.jdbc.HiveQueryResultSet.next(HiveQueryResultSet.java:330)
	at io.trino.tempto.query.QueryResult$QueryResultBuilder.addRows(QueryResult.java:243)
	at io.trino.tempto.query.QueryResult.forResultSet(QueryResult.java:192)
	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:129)
	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
	... 16 more
	Suppressed: java.lang.Exception: Query: SELECT * FROM table_trino_parquet_snappy_native_writer
 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
		... 17 more
```

Further testing should be performed to verify readability from Hives for all data types.

**Comment by findepi** [comment]
Thanks for sharing the stacktrace. 

Logically this duplicates https://github.com/trinodb/trino/issues/6377. Let's continue the discussion there.
