### ISSUE TITLE
Flaky test TestCassandraConnectorTest

### ISSUE THREAD

**Issue by raunaqmorarka** [trinodb/trino#9433]
```
2021-09-29T17:56:26.8080671Z 2021-09-29T12:56:26.517-0500 INFO Container cassandra:2.2 started in PT14.301669S
2021-09-29T17:56:26.8081610Z 2021-09-29T12:56:26.518-0500 INFO Using native clock to generate timestamps.
2021-09-29T17:56:26.8083391Z 2021-09-29T12:56:26.687-0500 INFO Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
2021-09-29T17:56:26.8085028Z 2021-09-29T12:56:26.689-0500 INFO New Cassandra host localhost/127.0.0.1:49158 added
2021-09-29T17:56:26.8085857Z 2021-09-29T12:56:26.715-0500 INFO Cassandra version: 2.2.19
2021-09-29T17:56:32.2542063Z 2021-09-29T12:56:27.133-0500 SEVERE [Control connection] Cannot connect to any host, scheduling retry in 16000 milliseconds
2021-09-29T17:56:32.2545222Z 2021-09-29T12:56:27.631-0500 SEVERE [Control connection] Cannot connect to any host, scheduling retry in 10000 milliseconds
2021-09-29T17:56:32.2552512Z 2021-09-29T12:56:27.651-0500 SEVERE [Control connection] Cannot connect to any host, scheduling retry in 10000 milliseconds
2021-09-29T17:56:32.2554344Z 2021-09-29T12:56:27.653-0500 SEVERE [Control connection] Cannot connect to any host, scheduling retry in 10000 milliseconds
2021-09-29T17:56:32.2560351Z 2021-09-29T12:56:29.765-0500 SEVERE [Control connection] Cannot connect to any host, scheduling retry in 10000 milliseconds
2021-09-29T17:56:32.2563571Z 2021-09-29T12:56:29.976-0500 SEVERE [Control connection] Cannot connect to any host, scheduling retry in 16000 milliseconds
2021-09-29T17:56:32.2576822Z 2021-09-29T12:56:30.491-0500 SEVERE [Control connection] Cannot connect to any host, scheduling retry in 10000 milliseconds
2021-09-29T17:56:32.2578175Z 2021-09-29T12:56:30.491-0500 SEVERE [Control connection] Cannot connect to any host, scheduling retry in 10000 milliseconds
2021-09-29T17:56:32.2579712Z 2021-09-29T12:56:30.496-0500 SEVERE [Control connection] Cannot connect to any host, scheduling retry in 10000 milliseconds
2021-09-29T17:56:32.2581619Z 2021-09-29T12:56:32.076-0500 INFO Size estimates for the table test_cassandra_token_split_manager_keyspace.empty_table have been refreshed successfully: [SizeEstimate{partitionsCount=0}]
2021-09-29T17:56:33.6860814Z 2021-09-29T12:56:33.582-0500 INFO Size estimates for the table test_cassandra_token_split_manager_keyspace.non_empty_table have been refreshed successfully: [SizeEstimate{partitionsCount=1024}]
2021-09-29T17:56:33.6932385Z 2021-09-29T12:56:33.687-0500 INFO Using native clock to generate timestamps.
2021-09-29T17:56:33.6934123Z 2021-09-29T12:56:33.688-0500 INFO Using native clock to generate timestamps.
2021-09-29T17:56:35.0753414Z 2021-09-29T12:56:35.070-0500 INFO Size estimates for the table test_cassandra_token_split_manager_keyspace.partition_count_override_table have been refreshed successfully: [SizeEstimate{partitionsCount=0}]
2021-09-29T17:56:35.6093172Z 2021-09-29T12:56:35.114-0500 SEVERE [Control connection] Cannot connect to any host, scheduling retry in 1000 milliseconds
2021-09-29T17:56:36.1799399Z [ERROR] Tests run: 242, Failures: 2, Errors: 0, Skipped: 34, Time elapsed: 408.741 s <<< FAILURE! - in TestSuite
2021-09-29T17:56:36.1805079Z [ERROR] io.trino.plugin.cassandra.TestCassandraConnectorTest.testEmptyTimestampClusteringKey  Time elapsed: 0.718 s  <<< FAILURE!
2021-09-29T17:56:36.1808745Z com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on localhost/127.0.0.1:49154: java.lang.AssertionError: Unknown keyspace keyspace_5
2021-09-29T17:56:36.1811227Z 	at com.datastax.driver.core.exceptions.ServerError.copy(ServerError.java:63)
2021-09-29T17:56:36.1813393Z 	at com.datastax.driver.core.exceptions.ServerError.copy(ServerError.java:25)
2021-09-29T17:56:36.1815722Z 	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
2021-09-29T17:56:36.1819018Z 	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
2021-09-29T17:56:36.1822170Z 	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
2021-09-29T17:56:36.1825208Z 	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:43)
2021-09-29T17:56:36.1862353Z 	at io.trino.plugin.cassandra.CassandraSession.lambda$execute$11(CassandraSession.java:432)
2021-09-29T17:56:36.1864912Z 	at io.trino.plugin.cassandra.CassandraSession.executeWithSession(CassandraSession.java:538)
2021-09-29T17:56:36.1867870Z 	at io.trino.plugin.cassandra.CassandraSession.execute(CassandraSession.java:432)
2021-09-29T17:56:36.1872427Z 	at io.trino.plugin.cassandra.TestCassandraConnectorTest.testEmptyTimestampClusteringKey(TestCassandraConnectorTest.java:639)
2021-09-29T17:56:36.1877900Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-09-29T17:56:36.1880121Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-09-29T17:56:36.1884318Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-29T17:56:36.1886276Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-29T17:56:36.1888023Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-09-29T17:56:36.1890233Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-09-29T17:56:36.1891642Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-09-29T17:56:36.1893158Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-09-29T17:56:36.1895001Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-09-29T17:56:36.1896854Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-09-29T17:56:36.1898632Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-09-29T17:56:36.1900526Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-09-29T17:56:36.1901950Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-09-29T17:56:36.1903859Z Caused by: com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on localhost/127.0.0.1:49154: java.lang.AssertionError: Unknown keyspace keyspace_5
2021-09-29T17:56:36.1905861Z 	at com.datastax.driver.core.Responses$Error.asException(Responses.java:108)
2021-09-29T17:56:36.1908012Z 	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:506)
2021-09-29T17:56:36.1909781Z 	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1070)
2021-09-29T17:56:36.1911340Z 	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:993)
2021-09-29T17:56:36.1913398Z 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
2021-09-29T17:56:36.1916245Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-09-29T17:56:36.1919756Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-09-29T17:56:36.1922844Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
2021-09-29T17:56:36.1925392Z 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
2021-09-29T17:56:36.1927975Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-09-29T17:56:36.1931076Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-09-29T17:56:36.1934170Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
2021-09-29T17:56:36.1936939Z 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
2021-09-29T17:56:36.1941419Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-09-29T17:56:36.1947511Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-09-29T17:56:36.1950601Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
2021-09-29T17:56:36.1953368Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
2021-09-29T17:56:36.1955792Z 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
2021-09-29T17:56:36.1958480Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-09-29T17:56:36.1961579Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-09-29T17:56:36.1964610Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
2021-09-29T17:56:36.1967117Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1280)
2021-09-29T17:56:36.1969688Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-09-29T17:56:36.1972784Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-09-29T17:56:36.1975800Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:890)
2021-09-29T17:56:36.1978021Z 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
2021-09-29T17:56:36.1979997Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564)
2021-09-29T17:56:36.1982201Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505)
2021-09-29T17:56:36.1984634Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419)
2021-09-29T17:56:36.1986264Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
2021-09-29T17:56:36.1988156Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
2021-09-29T17:56:36.1990442Z 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
2021-09-29T17:56:36.1991781Z 	... 1 more
2021-09-29T17:56:36.1992027Z 
2021-09-29T17:56:36.1994314Z [ERROR] io.trino.plugin.cassandra.TestCassandraConnectorTest.testIdentifiers  Time elapsed: 0.723 s  <<< FAILURE!
2021-09-29T17:56:36.1996849Z com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:49154] Connection has been closed
2021-09-29T17:56:36.1999113Z 	at com.datastax.driver.core.exceptions.TransportException.copy(TransportException.java:38)
2021-09-29T17:56:36.2001531Z 	at com.datastax.driver.core.exceptions.TransportException.copy(TransportException.java:24)
2021-09-29T17:56:36.2003857Z 	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
2021-09-29T17:56:36.2006470Z 	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
2021-09-29T17:56:36.2008849Z 	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
2021-09-29T17:56:36.2010665Z 	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:43)
2021-09-29T17:56:36.2012534Z 	at io.trino.plugin.cassandra.CassandraSession.lambda$execute$11(CassandraSession.java:432)
2021-09-29T17:56:36.2014751Z 	at io.trino.plugin.cassandra.CassandraSession.executeWithSession(CassandraSession.java:538)
2021-09-29T17:56:36.2016953Z 	at io.trino.plugin.cassandra.CassandraSession.execute(CassandraSession.java:432)
2021-09-29T17:56:36.2019501Z 	at io.trino.plugin.cassandra.TestCassandraConnectorTest.testIdentifiers(TestCassandraConnectorTest.java:320)
2021-09-29T17:56:36.2039340Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-09-29T17:56:36.2041550Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-09-29T17:56:36.2044135Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-29T17:56:36.2046050Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-29T17:56:36.2047772Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-09-29T17:56:36.2049640Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-09-29T17:56:36.2051037Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-09-29T17:56:36.2052536Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-09-29T17:56:36.2054386Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-09-29T17:56:36.2056219Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-09-29T17:56:36.2058011Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-09-29T17:56:36.2059900Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-09-29T17:56:36.2061140Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-09-29T17:56:36.2062630Z Caused by: com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:49154] Connection has been closed
2021-09-29T17:56:36.2065007Z 	at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1210)
2021-09-29T17:56:36.2066687Z 	at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1195)
2021-09-29T17:56:36.2068260Z 	at com.datastax.driver.core.Connection.defunct(Connection.java:445)
2021-09-29T17:56:36.2089747Z 	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:579)
2021-09-29T17:56:36.2091635Z 	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1070)
2021-09-29T17:56:36.2093183Z 	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:993)
2021-09-29T17:56:36.2095492Z 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
2021-09-29T17:56:36.2103820Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-09-29T17:56:36.2107694Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-09-29T17:56:36.2111899Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
2021-09-29T17:56:36.2115915Z 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
2021-09-29T17:56:36.2118515Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-09-29T17:56:36.2124116Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-09-29T17:56:36.2134255Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
2021-09-29T17:56:36.2137059Z 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
2021-09-29T17:56:36.2139906Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-09-29T17:56:36.2142995Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-09-29T17:56:36.2146234Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
2021-09-29T17:56:36.2149002Z 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
2021-09-29T17:56:36.2151465Z 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
2021-09-29T17:56:36.2154194Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-09-29T17:56:36.2169209Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-09-29T17:56:36.2176413Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
2021-09-29T17:56:36.2178962Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1280)
2021-09-29T17:56:36.2181547Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
2021-09-29T17:56:36.2185009Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
2021-09-29T17:56:36.2187871Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:890)
2021-09-29T17:56:36.2190126Z 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
2021-09-29T17:56:36.2192143Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564)
2021-09-29T17:56:36.2194343Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505)
2021-09-29T17:56:36.2196577Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419)
2021-09-29T17:56:36.2198218Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
2021-09-29T17:56:36.2200333Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
2021-09-29T17:56:36.2202603Z 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
2021-09-29T17:56:36.2203923Z 	... 1 more
2021-09-29T17:56:36.2204172Z 
2021-09-29T17:56:36.2205753Z 2021-09-29T12:56:36.114-0500 SEVERE [Control connection] Cannot connect to any host, scheduling retry in 2000 milliseconds
2021-09-29T17:56:36.9804926Z [INFO] 
2021-09-29T17:56:36.9805686Z [INFO] Results:
2021-09-29T17:56:36.9806425Z [INFO] 
2021-09-29T17:56:36.9806888Z [ERROR] Failures: 
2021-09-29T17:56:36.9826515Z [ERROR]   TestCassandraConnectorTest.testEmptyTimestampClusteringKey:639 » Server An une...
2021-09-29T17:56:36.9829420Z [ERROR]   TestCassandraConnectorTest.testIdentifiers:320 » Transport [localhost/127.0.0....
```

https://github.com/trinodb/trino/runs/3747561131

**Comment by findinpath** [comment]
@ebyhr  with the upgrade to cassandra driver v4 we'll probably not bump anymore in such stacktraces (the namespace of the driver changed to `com.datastax.oss`). 
Moreover there was no additional report of flakiness in the last year for this test.

Can we close this ticket?

**Comment by ebyhr** [comment]
@findinpath Yes, feel free to close this ticket.
