### ISSUE TITLE
Flaky TestJdbcVendorCompatibility - unable to download postgres docker image

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#9444]
```2021-09-29T15:39:04.2058393Z [ERROR] io.trino.jdbc.TestJdbcVendorCompatibility.setupServer  Time elapsed: 61.01 s  <<< FAILURE!
2021-09-29T15:39:04.2060263Z org.testcontainers.containers.ContainerLaunchException: Container startup failed
2021-09-29T15:39:04.2062139Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
2021-09-29T15:39:04.2064028Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:315)
2021-09-29T15:39:04.2065983Z 	at io.trino.jdbc.TestJdbcVendorCompatibility$PostgresqlReferenceDriver.<init>(TestJdbcVendorCompatibility.java:549)
2021-09-29T15:39:04.2068061Z 	at io.trino.jdbc.TestJdbcVendorCompatibility.setupServer(TestJdbcVendorCompatibility.java:91)
2021-09-29T15:39:04.2070251Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-09-29T15:39:04.2072174Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-09-29T15:39:04.2074397Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-29T15:39:04.2076094Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-29T15:39:04.2078443Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-09-29T15:39:04.2080329Z 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
2021-09-29T15:39:04.2081999Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
2021-09-29T15:39:04.2083444Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
2021-09-29T15:39:04.2085485Z 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
2021-09-29T15:39:04.2087265Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
2021-09-29T15:39:04.2088820Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-09-29T15:39:04.2090427Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-09-29T15:39:04.2091532Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-09-29T15:39:04.2093544Z Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=postgres:12.4, imagePullPolicy=DefaultPullPolicy())
2021-09-29T15:39:04.2095977Z 	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1317)
2021-09-29T15:39:04.2098078Z 	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:641)
2021-09-29T15:39:04.2099925Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:324)
2021-09-29T15:39:04.2101123Z 	... 16 more
2021-09-29T15:39:04.2103616Z Caused by: org.testcontainers.containers.ContainerFetchException: Failed to pull image: postgres:12.4
2021-09-29T15:39:04.2105300Z 	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:108)
2021-09-29T15:39:04.2106961Z 	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:28)
2021-09-29T15:39:04.2108619Z 	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:17)
2021-09-29T15:39:04.2109990Z 	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:39)
2021-09-29T15:39:04.2111688Z 	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1315)
2021-09-29T15:39:04.2112954Z 	... 18 more
2021-09-29T15:39:04.2113445Z Caused by: java.lang.InterruptedException
2021-09-29T15:39:04.2115524Z 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)
2021-09-29T15:39:04.2118922Z 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
2021-09-29T15:39:04.2121185Z 	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
2021-09-29T15:39:04.2123120Z 	at com.github.dockerjava.api.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:91)
2021-09-29T15:39:04.2126493Z 	at org.testcontainers.images.TimeLimitedLoggedPullImageResultCallback.awaitCompletion(TimeLimitedLoggedPullImageResultCallback.java:52)
2021-09-29T15:39:04.2129311Z 	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:86)
2021-09-29T15:39:04.2130282Z 	... 22 more
2021-09-29T15:39:04.2132634Z 
2021-09-29T15:39:04.2135942Z [ERROR] io.trino.jdbc.TestJdbcVendorCompatibility.tearDown  Time elapsed: 0 s  <<< FAILURE!
2021-09-29T15:39:04.2137025Z java.lang.NullPointerException
2021-09-29T15:39:04.2138263Z 	at io.trino.jdbc.TestJdbcVendorCompatibility.tearDown(TestJdbcVendorCompatibility.java:119)
2021-09-29T15:39:04.2139977Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-09-29T15:39:04.2141901Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-09-29T15:39:04.2143945Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-29T15:39:04.2145475Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-29T15:39:04.2146883Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-09-29T15:39:04.2148596Z 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
2021-09-29T15:39:04.2150102Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
2021-09-29T15:39:04.2151305Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
2021-09-29T15:39:04.2152438Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-09-29T15:39:04.2153657Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-09-29T15:39:04.2155192Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-09-29T15:39:04.2156693Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-09-29T15:39:04.2158109Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-09-29T15:39:04.2159616Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-09-29T15:39:04.2160613Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by kokosing** [comment]
```
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=mongo:3.6.20, imagePullPolicy=DefaultPullPolicy())
```

**Comment by ebyhr** [comment]
Same issue in Pinot connector
```
2021-09-29T14:35:42.3436521Z 2021-09-29T09:33:34.759-0500 INFO Pulling docker image: zookeeper:3.5.6. Please be patient; this may take some time but only needs to be done once.
2021-09-29T14:35:42.3437507Z 2021-09-29T09:33:36.114-0500 INFO Starting to pull image
2021-09-29T14:35:42.3439781Z 2021-09-29T09:33:36.114-0500 INFO Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
2021-09-29T14:35:42.3441366Z 2021-09-29T09:33:36.820-0500 INFO Pulling image layers:  7 pending,  1 downloaded,  0 extracted, (211 bytes/? MB)
2021-09-29T14:35:42.3442681Z 2021-09-29T09:33:36.877-0500 INFO Pulling image layers:  6 pending,  2 downloaded,  0 extracted, (311 KB/? MB)
2021-09-29T14:35:42.3444030Z 2021-09-29T09:33:37.016-0500 INFO Pulling image layers:  5 pending,  3 downloaded,  0 extracted, (12 MB/? MB)
2021-09-29T14:35:42.3518044Z 2021-09-29T09:33:37.288-0500 INFO Pulling image layers:  4 pending,  4 downloaded,  0 extracted, (12 MB/? MB)
2021-09-29T14:35:42.3519153Z 2021-09-29T09:33:37.448-0500 INFO Pulling image layers:  3 pending,  5 downloaded,  0 extracted, (12 MB/? MB)
2021-09-29T14:35:42.3520185Z 2021-09-29T09:33:37.800-0500 INFO Pulling image layers:  2 pending,  6 downloaded,  0 extracted, (23 MB/? MB)
2021-09-29T14:35:42.3521234Z 2021-09-29T09:33:37.833-0500 INFO Pulling image layers:  1 pending,  7 downloaded,  0 extracted, (26 MB/? MB)
2021-09-29T14:35:42.3522251Z 2021-09-29T09:33:38.378-0500 INFO Pulling image layers:  1 pending,  7 downloaded,  1 extracted, (30 MB/? MB)
2021-09-29T14:35:42.3523289Z 2021-09-29T09:33:39.123-0500 INFO Pulling image layers:  1 pending,  7 downloaded,  2 extracted, (33 MB/? MB)
2021-09-29T14:35:42.3524327Z 2021-09-29T09:33:39.196-0500 INFO Pulling image layers:  1 pending,  7 downloaded,  3 extracted, (33 MB/? MB)
2021-09-29T14:35:42.3525658Z 2021-09-29T09:34:09.196-0500 SEVERE Docker image pull has not made progress in 30s - aborting pull
2021-09-29T14:35:42.3526627Z 2021-09-29T09:34:09.198-0500 WARNING Retrying pull for image: zookeeper:3.5.6 (85s remaining)
2021-09-29T14:35:42.3527427Z 2021-09-29T09:34:10.249-0500 INFO Starting to pull image
2021-09-29T14:35:42.3528331Z 2021-09-29T09:34:10.250-0500 INFO Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
2021-09-29T14:35:42.3529407Z 2021-09-29T09:34:10.262-0500 INFO Pulling image layers:  7 pending,  1 downloaded,  0 extracted, (0 bytes/? MB)
2021-09-29T14:35:42.3530450Z 2021-09-29T09:34:10.263-0500 INFO Pulling image layers:  6 pending,  2 downloaded,  0 extracted, (0 bytes/? MB)
2021-09-29T14:35:42.3531514Z 2021-09-29T09:34:10.263-0500 INFO Pulling image layers:  5 pending,  3 downloaded,  0 extracted, (0 bytes/? MB)
2021-09-29T14:35:42.3532570Z 2021-09-29T09:34:10.263-0500 INFO Pulling image layers:  4 pending,  4 downloaded,  0 extracted, (0 bytes/? MB)
2021-09-29T14:35:42.3533765Z 2021-09-29T09:34:40.264-0500 SEVERE Docker image pull has not made progress in 30s - aborting pull
2021-09-29T14:35:42.3534785Z 2021-09-29T09:34:40.265-0500 WARNING Retrying pull for image: zookeeper:3.5.6 (54s remaining)
2021-09-29T14:35:42.3535578Z 2021-09-29T09:34:41.253-0500 INFO Starting to pull image
2021-09-29T14:35:42.3536636Z 2021-09-29T09:34:41.254-0500 INFO Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
2021-09-29T14:35:42.3537711Z 2021-09-29T09:34:41.263-0500 INFO Pulling image layers:  7 pending,  1 downloaded,  0 extracted, (0 bytes/? MB)
2021-09-29T14:35:42.3538930Z 2021-09-29T09:34:41.263-0500 INFO Pulling image layers:  6 pending,  2 downloaded,  0 extracted, (0 bytes/? MB)
2021-09-29T14:35:42.3541877Z 2021-09-29T09:34:41.263-0500 INFO Pulling image layers:  5 pending,  3 downloaded,  0 extracted, (0 bytes/? MB)
2021-09-29T14:35:42.3543150Z 2021-09-29T09:34:41.264-0500 INFO Pulling image layers:  4 pending,  4 downloaded,  0 extracted, (0 bytes/? MB)
2021-09-29T14:35:42.3544340Z 2021-09-29T09:35:11.264-0500 SEVERE Docker image pull has not made progress in 30s - aborting pull
2021-09-29T14:35:42.3545473Z 2021-09-29T09:35:11.266-0500 WARNING Retrying pull for image: zookeeper:3.5.6 (23s remaining)
2021-09-29T14:35:42.3546407Z 2021-09-29T09:35:12.312-0500 INFO Starting to pull image
2021-09-29T14:35:42.3547906Z 2021-09-29T09:35:12.314-0500 INFO Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
2021-09-29T14:35:42.3548978Z 2021-09-29T09:35:12.322-0500 INFO Pulling image layers:  7 pending,  1 downloaded,  0 extracted, (0 bytes/? MB)
2021-09-29T14:35:42.3550012Z 2021-09-29T09:35:12.322-0500 INFO Pulling image layers:  6 pending,  2 downloaded,  0 extracted, (0 bytes/? MB)
2021-09-29T14:35:42.3551068Z 2021-09-29T09:35:12.323-0500 INFO Pulling image layers:  5 pending,  3 downloaded,  0 extracted, (0 bytes/? MB)
2021-09-29T14:35:42.3552125Z 2021-09-29T09:35:12.323-0500 INFO Pulling image layers:  4 pending,  4 downloaded,  0 extracted, (0 bytes/? MB)
2021-09-29T14:35:42.3553116Z 2021-09-29T09:35:42.323-0500 SEVERE Docker image pull has not made progress in 30s - aborting pull
2021-09-29T14:35:42.3554073Z 2021-09-29T09:35:42.325-0500 WARNING Retrying pull for image: zookeeper:3.5.6 (-8s remaining)
2021-09-29T14:35:42.3555136Z 2021-09-29T09:35:42.325-0500 SEVERE Failed to pull image: zookeeper:3.5.6. Please check output of `docker pull zookeeper:3.5.6`
2021-09-29T14:35:42.3555964Z java.lang.InterruptedException
2021-09-29T14:35:42.3558256Z 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)
2021-09-29T14:35:42.3562636Z 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
2021-09-29T14:35:42.3566572Z 	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
2021-09-29T14:35:42.3569667Z 	at com.github.dockerjava.api.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:91)
2021-09-29T14:35:42.3573302Z 	at org.testcontainers.images.TimeLimitedLoggedPullImageResultCallback.awaitCompletion(TimeLimitedLoggedPullImageResultCallback.java:52)
2021-09-29T14:35:42.3576468Z 	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:86)
2021-09-29T14:35:42.3578342Z 	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:28)
2021-09-29T14:35:42.3580179Z 	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:17)
2021-09-29T14:35:42.3581740Z 	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:39)
2021-09-29T14:35:42.3583632Z 	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1315)
2021-09-29T14:35:42.3585851Z 	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:641)
2021-09-29T14:35:42.3587788Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:324)
2021-09-29T14:35:42.3589853Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:315)
2021-09-29T14:35:42.3591673Z 	at io.trino.plugin.pinot.TestingPinotCluster.start(TestingPinotCluster.java:108)
2021-09-29T14:35:42.3594048Z 	at io.trino.plugin.pinot.TestPinotIntegrationSmokeTest.createQueryRunner(TestPinotIntegrationSmokeTest.java:92)
2021-09-29T14:35:42.3596668Z 	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:95)
2021-09-29T14:35:42.3598548Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-09-29T14:35:42.3600507Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-09-29T14:35:42.3602819Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-29T14:35:42.3605048Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-29T14:35:42.3606677Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-09-29T14:35:42.3608615Z 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
2021-09-29T14:35:42.3610190Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
2021-09-29T14:35:42.3611669Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
2021-09-29T14:35:42.3622355Z 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
2021-09-29T14:35:42.3624205Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
2021-09-29T14:35:42.3625823Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-09-29T14:35:42.3627507Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
```
https://github.com/trinodb/trino/runs/3745083553

**Comment by kokosing** [comment]
It looks like an issue with docker hub.

**Comment by ebyhr** [comment]
Sent a PR https://github.com/testcontainers/testcontainers-java/pull/4491 to testcontainers though I'm not sure whether it's acceptable or not.

**Comment by lukasz-walkiewicz** [comment]
hit: https://github.com/trinodb/trino/runs/3882745687
