### ISSUE TITLE
Flaky trino-hive tests: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9563]
https://github.com/trinodb/trino/runs/3836704455

```
2021-10-08T04:36:19.890-0500	INFO	pool-3-thread-1	io.trino.testing.QueryAssertions	FINISHED in Trino: 19.03s
2021-10-08T04:36:19.941-0500	INFO	dispatcher-query-135	io.trino.event.QueryMonitor	TIMELINE: Query 20211008_093600_04161_z8tzm :: Transaction:[3ef1bb95-32ea-40e1-82f2-d492d84a6330] :: elapsed 19026ms :: planning 104ms :: waiting 0ms :: scheduling 12ms :: running 9724ms :: finishing 9186ms :: begin 2021-10-08T04:36:00.863-05:00 :: end 2021-10-08T04:36:19.889-05:00
2021-10-08T04:36:21.375-0500	INFO	dispatcher-query-125	io.trino.event.QueryMonitor	TIMELINE: Query 20211008_093619_04162_z8tzm :: Transaction:[cceccf24-9f90-48c5-b425-10ccb3fb3727] :: elapsed 1468ms :: planning 93ms :: waiting 0ms :: scheduling 98ms :: running 1160ms :: finishing 117ms :: begin 2021-10-08T04:36:19.894-05:00 :: end 2021-10-08T04:36:21.362-05:00
2021-10-08T04:36:21.445-0500	INFO	dispatcher-query-298	io.trino.event.QueryMonitor	TIMELINE: Query 20211008_093621_04163_z8tzm :: Transaction:[0354e2ab-233d-4a33-bf76-83e7aca1576b] :: elapsed 57ms :: planning 0ms :: waiting 0ms :: scheduling 57ms :: running 0ms :: finishing 57ms :: begin 2021-10-08T04:36:21.387-05:00 :: end 2021-10-08T04:36:21.444-05:00
2021-10-08T04:36:21.445-0500	INFO	pool-3-thread-1	io.trino.testng.services.LogTestDurationListener	Test io.trino.plugin.hive.TestHiveConnectorTest::testTargetMaxFileSize took 47.52s
Error:  java.lang.OutOfMemoryError: Java heap space
Error:  Terminating due to java.lang.OutOfMemoryError: Java heap space
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
Warning:  Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/runner/work/trino/trino/plugin/trino-hive/target/surefire-reports/2021-10-08T09-06-15_622-jvmRun1.dumpstream
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for trino-orc 364-SNAPSHOT:
[INFO] 
[INFO] trino-orc .......................................... SUCCESS [04:15 min]
[INFO] trino-hive ......................................... FAILURE [26:45 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31:03 min
[INFO] Finished at: 2021-10-08T09:37:13Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project trino-hive: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/trino/trino/plugin/trino-hive/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd /home/runner/work/trino/trino/plugin/trino-hive && /opt/hostedtoolcache/Java_Zulu_jdk/11.0.12-7/x64/bin/java -Dfile.encoding=UTF-8 -Xmx3g -Xms3g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -jar /home/runner/work/trino/trino/plugin/trino-hive/target/surefire/surefirebooter6435039010443116078.jar /home/runner/work/trino/trino/plugin/trino-hive/target/surefire 2021-10-08T09-06-15_622-jvmRun1 surefire7826773693969939225tmp surefire_35987103246075577345tmp
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 3
Error:  Crashed tests:
Error:  io.trino.plugin.hive.TestHiveConnectorTest
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd /home/runner/work/trino/trino/plugin/trino-hive && /opt/hostedtoolcache/Java_Zulu_jdk/11.0.12-7/x64/bin/java -Dfile.encoding=UTF-8 -Xmx3g -Xms3g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -jar /home/runner/work/trino/trino/plugin/trino-hive/target/surefire/surefirebooter6435039010443116078.jar /home/runner/work/trino/trino/plugin/trino-hive/target/surefire 2021-10-08T09-06-15_622-jvmRun1 surefire7826773693969939225tmp surefire_35987103246075577345tmp
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 3
Error:  Crashed tests:
Error:  io.trino.plugin.hive.TestHiveConnectorTest
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
Error:  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
Error:  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
Error:  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
Error:  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
Error:  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Error:  	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
Error:  	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
Error:  	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :trino-hive
Error: Process completed with exit code 1.
```

**Comment by findepi** [comment]
cc @losipiuk @homar @alexjo2144

**Comment by findepi** [comment]
> ould that be a big deal we add logging out which test is being executed.

it is easy to do and It would be awesome to have it, unless it would inflate the CI logs too much.
i don't know how much is "too much" though.

cc @wendigo

**Comment by findepi** [comment]
> would that be a big deal we add logging out which test is being executed.

done in https://github.com/trinodb/trino/pull/9566

**Comment by hashhar** [comment]
Fixed by https://github.com/trinodb/trino/commit/a7e76646bab3202c02e12fe0925b0d5dd0cf60bc
