### ISSUE TITLE
java.lang.UnsupportedOperationException: io.trino.spi.block.LongArrayBlockBuilder on max_by call

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#9592]
```
❯ ./client/trino-cli/target/trino-cli-364-SNAPSHOT-executable.jar
trino> use tpch.tiny;
USE
trino:tiny> SELECT max_by(name, nationkey) FROM nation GROUP BY regionkey;

Query 20211011_165927_00002_scsjy, FAILED, 3 nodes
Splits: 76 total, 47 done (61.84%)
4.93 [25 rows, 0B] [5 rows/s, 0B/s]

Query 20211011_165927_00002_scsjy failed: io.trino.spi.block.LongArrayBlockBuilder
```

```
java.lang.UnsupportedOperationException: io.trino.spi.block.LongArrayBlockBuilder
	at io.trino.spi.block.BlockBuilder.writeByte(BlockBuilder.java:26)
	at io.trino.spi.block.SingleRowBlockWriter.writeByte(SingleRowBlockWriter.java:110)
	at io.trino.spi.block.ByteArrayBlock.writePositionTo(ByteArrayBlock.java:148)
	at io.trino.spi.block.RowBlockBuilder.appendStructureInternal(RowBlockBuilder.java:274)
	at io.trino.spi.block.AbstractRowBlock.writePositionTo(AbstractRowBlock.java:204)
	at io.trino.spi.type.RowType.appendTo(RowType.java:238)
	at io.trino.operator.project.MergePages$MergePagesTransformation.appendPage(MergePages.java:209)
	at io.trino.operator.project.MergePages$MergePagesTransformation.process(MergePages.java:193)
	at io.trino.operator.project.MergePages$MergePagesTransformation.process(MergePages.java:134)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorOperatorAdapter.getOutput(WorkProcessorOperatorAdapter.java:188)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_testversion____20211011_165858_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

This could be a regression introduced by https://github.com/trinodb/trino/pull/6042

**Comment by wendigo** [comment]
cc @dain @findepi

**Comment by dain** [comment]
I'm working on a fix
