### ISSUE TITLE
Flaky test TestMemoryConnectorTest.testJoinLargeBuildSideDynamicFiltering

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9658]
https://github.com/trinodb/trino/runs/3907796195 `test-other-modules`

```
Error:  Tests run: 245, Failures: 1, Errors: 0, Skipped: 31, Time elapsed: 372.731 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.memory.TestMemoryConnectorTest.testJoinLargeBuildSideDynamicFiltering[AUTOMATIC](6)  Time elapsed: 1.681 s  <<< FAILURE!
java.lang.AssertionError: Lists differ at element [1]: 15000 != 7500 expected [15000] but found [7500]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:568)
	at org.testng.Assert.assertEquals(Assert.java:533)
	at io.trino.plugin.memory.TestMemoryConnectorTest.assertDynamicFiltering(TestMemoryConnectorTest.java:438)
	at io.trino.plugin.memory.TestMemoryConnectorTest.testJoinLargeBuildSideDynamicFiltering(TestMemoryConnectorTest.java:216)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/4984192609?check_suite_focus=true 
```
2022-01-28T18:49:29.1430139Z [ERROR] io.trino.plugin.memory.TestMemoryConnectorTest.testJoinLargeBuildSideDynamicFiltering[BROADCAST](2)  Time elapsed: 0.358 s  <<< FAILURE!
2022-01-28T18:49:29.1431110Z java.lang.AssertionError: lists don't have the same size expected [2] but found [0]
2022-01-28T18:49:29.1431937Z 	at org.testng.Assert.fail(Assert.java:94)
2022-01-28T18:49:29.1432312Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2022-01-28T18:49:29.1432699Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2022-01-28T18:49:29.1433127Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2022-01-28T18:49:29.1433709Z 	at org.testng.Assert.assertEquals(Assert.java:389)
2022-01-28T18:49:29.1434065Z 	at org.testng.Assert.assertEquals(Assert.java:556)
2022-01-28T18:49:29.1434413Z 	at org.testng.Assert.assertEquals(Assert.java:533)
2022-01-28T18:49:29.1434934Z 	at io.trino.plugin.memory.TestMemoryConnectorTest.assertDynamicFiltering(TestMemoryConnectorTest.java:460)
2022-01-28T18:49:29.1435733Z 	at io.trino.plugin.memory.TestMemoryConnectorTest.testJoinLargeBuildSideDynamicFiltering(TestMemoryConnectorTest.java:233)
2022-01-28T18:49:29.1436420Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-01-28T18:49:29.1436990Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-01-28T18:49:29.1437613Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-01-28T18:49:29.1438126Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-01-28T18:49:29.1438624Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-01-28T18:49:29.1439182Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2022-01-28T18:49:29.1439673Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2022-01-28T18:49:29.1440158Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-01-28T18:49:29.1440602Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-01-28T18:49:29.1441323Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-01-28T18:49:29.1441851Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-01-28T18:49:29.1442266Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-01-28T18:49:29.1442450Z 
2022-01-28T18:49:29.1443089Z [ERROR] io.trino.plugin.memory.TestMemoryConnectorTest.testJoinLargeBuildSideDynamicFiltering[PARTITIONED](4)  Time elapsed: 0.648 s  <<< FAILURE!
2022-01-28T18:49:29.1444077Z java.lang.AssertionError: lists don't have the same size expected [2] but found [0]
2022-01-28T18:49:29.1444425Z 	at org.testng.Assert.fail(Assert.java:94)
2022-01-28T18:49:29.1444764Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2022-01-28T18:49:29.1445131Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2022-01-28T18:49:29.1445474Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2022-01-28T18:49:29.1445817Z 	at org.testng.Assert.assertEquals(Assert.java:389)
2022-01-28T18:49:29.1446158Z 	at org.testng.Assert.assertEquals(Assert.java:556)
2022-01-28T18:49:29.1446508Z 	at org.testng.Assert.assertEquals(Assert.java:533)
2022-01-28T18:49:29.1447022Z 	at io.trino.plugin.memory.TestMemoryConnectorTest.assertDynamicFiltering(TestMemoryConnectorTest.java:460)
2022-01-28T18:49:29.1447808Z 	at io.trino.plugin.memory.TestMemoryConnectorTest.testJoinLargeBuildSideDynamicFiltering(TestMemoryConnectorTest.java:233)
2022-01-28T18:49:29.1448499Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-01-28T18:49:29.1449073Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-01-28T18:49:29.1449695Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-01-28T18:49:29.1450204Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-01-28T18:49:29.1450703Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-01-28T18:49:29.1451245Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2022-01-28T18:49:29.1451754Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2022-01-28T18:49:29.1452238Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-01-28T18:49:29.1452698Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-01-28T18:49:29.1453267Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-01-28T18:49:29.1453807Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-01-28T18:49:29.1454220Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-01-28T18:49:29.1454404Z 
2022-01-28T18:49:29.1455028Z [ERROR] io.trino.plugin.memory.TestMemoryConnectorTest.testJoinLargeBuildSideDynamicFiltering[AUTOMATIC](6)  Time elapsed: 5.338 s  <<< FAILURE!
2022-01-28T18:49:29.1455755Z java.lang.AssertionError: lists don't have the same size expected [2] but found [0]
2022-01-28T18:49:29.1456111Z 	at org.testng.Assert.fail(Assert.java:94)
2022-01-28T18:49:29.1456448Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2022-01-28T18:49:29.1456804Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2022-01-28T18:49:29.1457170Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2022-01-28T18:49:29.1457523Z 	at org.testng.Assert.assertEquals(Assert.java:389)
2022-01-28T18:49:29.1457865Z 	at org.testng.Assert.assertEquals(Assert.java:556)
2022-01-28T18:49:29.1458198Z 	at org.testng.Assert.assertEquals(Assert.java:533)
2022-01-28T18:49:29.1458735Z 	at io.trino.plugin.memory.TestMemoryConnectorTest.assertDynamicFiltering(TestMemoryConnectorTest.java:460)
2022-01-28T18:49:29.1459527Z 	at io.trino.plugin.memory.TestMemoryConnectorTest.testJoinLargeBuildSideDynamicFiltering(TestMemoryConnectorTest.java:233)
2022-01-28T18:49:29.1460214Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-01-28T18:49:29.1460767Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-01-28T18:49:29.1461403Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-01-28T18:49:29.1461920Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-01-28T18:49:29.1462418Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-01-28T18:49:29.1463022Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2022-01-28T18:49:29.1463537Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2022-01-28T18:49:29.1464017Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-01-28T18:49:29.1464475Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-01-28T18:49:29.1464958Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-01-28T18:49:29.1465494Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-01-28T18:49:29.1465911Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```
