### ISSUE TITLE
Query failure when reading from `$partitions` when Iceberg table partitioned on timestamp with time zone

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9703]
Surely, this is far from common use-case, but still...

```
CREATE TABLE t2 (x timestamp(6) with time zone) WITH (partitioning = ARRAY['x']);
INSERT INTO t2 VALUES TIMESTAMP '2021-10-31 00:30:00 UTC',  TIMESTAMP '2021-10-31 01:30:00 UTC',  TIMESTAMP '2021-10-31 02:30:00 UTC', TIMESTAMP '2021-10-31 03:30:00 UTC';
SELECT * FROM "t2$partitions";
```

```
Query 20211020_093723_00058_7pzkj failed: Unknown type: class io.trino.spi.type.LongTimestampWithTimeZone
java.lang.IllegalArgumentException: Unknown type: class io.trino.spi.type.LongTimestampWithTimeZone
	at io.trino.spi.connector.InMemoryRecordSet.sizeOf(InMemoryRecordSet.java:311)
	at io.trino.spi.connector.InMemoryRecordSet$InMemoryRecordCursor.advanceNextPosition(InMemoryRecordSet.java:108)
	at io.trino.split.MappedRecordSet$MappedRecordCursor.advanceNextPosition(MappedRecordSet.java:89)
	at io.trino.spi.connector.RecordPageSource.getNextPage(RecordPageSource.java:88)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_testversion____20211020_092651_3.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findepi** [comment]
cc @losipiuk @alexjo2144
