### ISSUE TITLE
SHOW STATS fails if Iceberg metadata has no statistics for a file

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9707]
```
CREATE TABLE t AS SELECT localtimestamp(6) x;

SHOW STATS FOR t;
Query 20211020_114603_00028_94qhj failed: Internal error
java.lang.NullPointerException
	at io.trino.plugin.iceberg.TableStatisticsMaker.makeTableStatistics(TableStatisticsMaker.java:173)
	at io.trino.plugin.iceberg.TableStatisticsMaker.getTableStatistics(TableStatisticsMaker.java:72)
	at io.trino.plugin.iceberg.IcebergMetadata.getTableStatistics(IcebergMetadata.java:694)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableStatistics(ClassLoaderSafeConnectorMetadata.java:303)
	at io.trino.metadata.MetadataManager.getTableStatistics(MetadataManager.java:578)
	at io.trino.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:69)
	at io.trino.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:40)
	at io.trino.cost.SimpleStatsRule.calculate(SimpleStatsRule.java:39)
	at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:85)
	at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:73)
	at io.trino.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:80)
	at io.trino.cost.ExchangeStatsRule.doCalculate(ExchangeStatsRule.java:54)
	at io.trino.cost.ExchangeStatsRule.doCalculate(ExchangeStatsRule.java:32)
	at io.trino.cost.SimpleStatsRule.calculate(SimpleStatsRule.java:39)
	at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:85)
	at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:73)
	at io.trino.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:80)
	at io.trino.cost.OutputStatsRule.calculate(OutputStatsRule.java:41)
	at io.trino.cost.OutputStatsRule.calculate(OutputStatsRule.java:27)
	at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:85)
	at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:73)
	at io.trino.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:80)
	at io.trino.cost.StatsAndCosts.create(StatsAndCosts.java:87)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:237)
	at io.trino.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:214)
	at io.trino.sql.rewrite.ShowStatsRewrite$Visitor.visitShowStats(ShowStatsRewrite.java:128)
	at io.trino.sql.rewrite.ShowStatsRewrite$Visitor.visitShowStats(ShowStatsRewrite.java:104)
	at io.trino.sql.tree.ShowStats.accept(ShowStats.java:45)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.rewrite.ShowStatsRewrite.rewrite(ShowStatsRewrite.java:101)
	at io.trino.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:61)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:89)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:84)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:190)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:806)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
	at io.trino.$gen.Trino_testversion____20211020_114255_3.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findepi** [comment]
cc @losipiuk @alexjo2144
