### ISSUE TITLE
SHOW STATS for Iceberg Parquet data with timestamp with time zone column

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9709]
```
Unexpected type: timestamp(6) with time zone
	at io.trino.sql.rewrite.ShowStatsRewrite$Visitor.toStringLiteral(ShowStatsRewrite.java:231)
	at io.trino.sql.rewrite.ShowStatsRewrite$Visitor.rewriteShowStats(ShowStatsRewrite.java:163)
	at io.trino.sql.rewrite.ShowStatsRewrite$Visitor.visitShowStats(ShowStatsRewrite.java:131)
	at io.trino.sql.rewrite.ShowStatsRewrite$Visitor.visitShowStats(ShowStatsRewrite.java:104)
	at io.trino.sql.tree.ShowStats.accept(ShowStats.java:45)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.rewrite.ShowStatsRewrite.rewrite(ShowStatsRewrite.java:101)
```

**Comment by findepi** [comment]
cc @losipiuk @alexjo2144
