### ISSUE TITLE
Location field not acknowledged when creating iceberg tables

### ISSUE THREAD

**Issue by SamWheating** [trinodb/trino#9732]
I've just deployed a test cluster Trino 363 and I'm seeing some changes in behaviour from Trino 358.

I created an iceberg table like so:

```sql
CREATE TABLE iceberg_catalog.test_schema.test_table (
    c1 integer,
    c2 date,
    c3 double)
WITH (
    format = 'PARQUET',
    partitioning = ARRAY['c1', 'c2'],
    location = 'gs://valid-iceberg-data-location/test_table'
)
```

And got this error:
```
io.trino.spi.TrinoException: Failed checking path: gs://default-location/folder/test_schema.db
	at io.trino.plugin.hive.util.HiveWriteUtils.pathExists(HiveWriteUtils.java:474)
	at io.trino.plugin.hive.util.HiveWriteUtils.getTableDefaultLocation(HiveWriteUtils.java:457)
	at io.trino.plugin.iceberg.TrinoHiveCatalog.defaultTableLocation(TrinoHiveCatalog.java:347)
	at io.trino.plugin.iceberg.IcebergUtil.newCreateTableTransaction(IcebergUtil.java:380)
	at io.trino.plugin.iceberg.IcebergMetadata.beginCreateTable(IcebergMetadata.java:400)
	at io.trino.plugin.iceberg.IcebergMetadata.createTable(IcebergMetadata.java:388)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.createTable(ClassLoaderSafeConnectorMetadata.java:359)
	at io.trino.metadata.MetadataManager.createTable(MetadataManager.java:758)
	at io.trino.execution.CreateTableTask.internalExecute(CreateTableTask.java:249)
	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:106)
	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:81)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:170)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_870acc2____20211021_201015_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Error accessing gs://default-location/folder/test_schema.db
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getObject(GoogleCloudStorageImpl.java:1911)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfo(GoogleCloudStorageImpl.java:1813)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.getFileInfoInternal(GoogleCloudStorageFileSystem.java:1127)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.getFileInfo(GoogleCloudStorageFileSystem.java:1095)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getFileStatus(GoogleHadoopFileSystemBase.java:1038)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:454)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1683)
	at io.trino.plugin.hive.util.HiveWriteUtils.pathExists(HiveWriteUtils.java:471)
	... 17 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "<service account> does not have storage.objects.get access to the Google Cloud Storage object.",
    "reason" : "forbidden"
  } ],
  "message" : "<service account> does not have storage.objects.get access to the Google Cloud Storage object."
}
```

The default location doesn't exist as we only use external tables, but I don't think it should've been checked anyways. 

Based on the findings from https://github.com/trinodb/trino/issues/4069, I created a new schema with a valid default location

```sql
CREATE SCHEMA iceberg_catalog.test_schema_2
WITH (
   location = 'gs://<valid path>/testing/'
)
```

And I was able to create a table in this schema without errors:
```sql
CREATE TABLE iceberg_catalog.test_schema_2.test_table (
    c1 integer,
    c2 date,
    c3 double)
WITH (
    format = 'PARQUET',
    partitioning = ARRAY['c1', 'c2'],
    location = 'gs://iceberg-data-location/test_table'
)
```

But when I `SHOW CREATE` this table it doesn't show the location field.

```sql 
> SHOW CREATE TABLE iceberg_catalog.test_schema_2.test_table

CREATE TABLE pepto_do_not_use.lifeboat_testing_2.test_table (
   c1 integer,
   c2 date,
   c3 double
)
WITH (
   format = 'PARQUET',
   partitioning = ARRAY['c1','c2']
)
```

Based on these results I'm wondering if the location field isn't being correctly parsed or saved with the iceberg table definition, which then causes the default location to be checked on table creation.

**Comment by findepi** [comment]
Fixed by https://github.com/trinodb/trino/pull/9817
