### ISSUE TITLE
Iceberg failure when reading Parquet file written by Iceberg connector: Dictionary is missing for Page

### ISSUE THREAD

**Issue by mdesmet** [trinodb/trino#9749]
Doing a CTAS query on Trino v363 from iceberg parquet to iceberg orc and getting this error. Selecting from the iceberg parquet table works fine.

It seems in the codepath there is no dictionary created for a V2Page

https://github.com/trinodb/trino/blob/ffc34cbdfb4d8efb3afb2240176b8bf1aeeacf9d/lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetColumnChunk.java#L107-L111

Compared to 

https://github.com/trinodb/trino/blob/ffc34cbdfb4d8efb3afb2240176b8bf1aeeacf9d/lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetColumnChunk.java#L96-L101

```
org.apache.parquet.io.ParquetDecodingException: Dictionary is missing for Page
	at io.trino.parquet.reader.PrimitiveColumnReader.initDataReader(PrimitiveColumnReader.java:409)
	at io.trino.parquet.reader.PrimitiveColumnReader.readPageV2(PrimitiveColumnReader.java:393)
	at io.trino.parquet.reader.PrimitiveColumnReader.readNextPage(PrimitiveColumnReader.java:356)
	at io.trino.parquet.reader.PrimitiveColumnReader.readPrimitive(PrimitiveColumnReader.java:210)
	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:370)
	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:444)
	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:427)
	at io.trino.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:224)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:396)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:375)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:282)
	at io.trino.spi.Page.getLoadedPage(Page.java:293)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:314)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_363____20211022_122419_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findepi** [comment]
@mdesmet what are the steps i should follow to recreate this on my side?
also, are you able to reproduce this with current master, with freshly written data?
We fixed some bugs in Parquet writer, so maybe Parquet reader won't be failing anymore (on new files).

**Comment by mdesmet** [comment]
HI @findepi ,

I tried with master, however the same issue occurs, now (as expected by glancing the code changes) with the v1 page.

org.apache.parquet.io.ParquetDecodingException: Dictionary is missing for Page
	at io.trino.parquet.reader.PrimitiveColumnReader.initDataReader(PrimitiveColumnReader.java:406)
	at io.trino.parquet.reader.PrimitiveColumnReader.readPageV1(PrimitiveColumnReader.java:379)
	at io.trino.parquet.reader.PrimitiveColumnReader.readNextPage(PrimitiveColumnReader.java:350)
	at io.trino.parquet.reader.PrimitiveColumnReader.readPrimitive(PrimitiveColumnReader.java:217)
	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:370)
	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:444)
	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:427)
	at io.trino.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:224)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:396)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:375)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:282)
	at io.trino.spi.Page.getLoadedPage(Page.java:293)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:314)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1078)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_362_500_g54d8154____20211101_141755_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

I have also tried to find cheaper ways of reproducing this issue, but have not yet succeeded with that. I'll keep you posted.

**Comment by mdesmet** [comment]
What I have tried now:

Successful CTAS from hive (external table) to iceberg parquet of 60M recors with 1600 columns
Querying this iceberg parquet fails with above exception.

I was able to get the same exception by selecting only one column within a partition. What is remarkable that over the 2 big selects I did, the issue is not occuring in the same partition (given the same data), so it's probably not based on the actual values. The column type is varchar.

I tried writing from hive to iceberg parquet with just that one column (and partition columns) but that succeeded and reads gave no exceptions.

Anything else I could try?

**Comment by findepi** [comment]
> Successful CTAS from hive (external table) to iceberg parquet of 60M records with 1600 columns

Is there a smaller data set you can repro this with?
can you repro this using `tpch.sfNN.orders` table?


cc @raunaqmorarka @losipiuk @alexjo2144

**Comment by sshkvar** [comment]
We have faced the same issue. In our case we have table with 1 parquet file. Lets say that this table contains column `N`. In few first row groups this column has not null values, but in all other row groups contains only null values. 

In this case in FallbackValuesWriter we didn't switch `currentWriter` to Plain because of code changes from this [PR](https://github.com/trinodb/trino/pull/9245/files).

Long story:
Lets look on ParquetWriter code 
https://github.com/trinodb/trino/blob/aeb753aed2f04d6a6d520edb5645f03bb24e1721/lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java#L166-L167
During the `flush()` method we perform reset for primitive column writer, which uses FallbackValuesWriter under the hood.
https://github.com/trinodb/trino/blob/aeb753aed2f04d6a6d520edb5645f03bb24e1721/lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java#L247
Then we call `resetDictionary` method 
https://github.com/trinodb/trino/blob/aeb753aed2f04d6a6d520edb5645f03bb24e1721/lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java#L282
This is main point for issue understanding.  `resetDictionary` sets `firstPage` to `true`, it will allow us to perform value writer fallback in FallbackValuesWriter

https://github.com/apache/parquet-mr/blob/59e9f78b8b3a30073db202eb6432071ff71df0ec/parquet-column/src/main/java/org/apache/parquet/column/values/fallback/FallbackValuesWriter.java#L71-L73

As you can see we will be able to fallback valueWriter only if `firstPage==true`, but we added few additional resets in 
https://github.com/trinodb/trino/blob/aeb753aed2f04d6a6d520edb5645f03bb24e1721/lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java#L313-L316
so we reset firstPage to false right after it was set to true in `resetDictionary` method.
Because of it we didn't switch value writer and will continue use Dictionary value writer, but dictionary will be not written because page contains only null values.

So we need to find way how to reset both value writers to fix [this issue](https://github.com/trinodb/trino/issues/5518) and also don't change firstPage flag which was set to true in resetDictionary
 
@mdesmet you can remove this line 
https://github.com/trinodb/trino/blob/aeb753aed2f04d6a6d520edb5645f03bb24e1721/lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java#L315
and check will it help you with your issue, to be sure that this is the root cause for your issue too

**Comment by findinpath** [comment]
As @sshkvar  described, the issue can be reproduced when creating a parquet file containing multiple row groups and the last row groups contain columns containing only null values.

Here is the code to reproduce the issue:


Spin up a Trino product test environment with `hive` connector:
```sh
testing/bin/ptl env up --environment 'singlenode'  --config 'config-default'
```



```sql
SET SESSION hive.experimental_parquet_optimized_writer_enabled = true;
SET SESSION hive.parquet_writer_page_size = '1000001B';
SET SESSION hive.parquet_writer_block_size = '1000001B';


create table hive.default.customerbundle1parquet
    with (format='PARQUET')
as
select custkey,
       name,
       address,
       cast(
         case
             when custkey > 1 then null
             else nationkey
             end as int
           )as nationkey,
       cast(
           case
               when custkey > 1 then null
               else comment
               end as varchar
           )as comment
from tpch.sf100.customer
order by custkey asc;


create table hive.default.customerbundle1orc
    with (format='ORC')
as select * from hive.default.customerbundle1parquet;
```

Probably it would be enough to have only 1 non-null value for `nationkey` or `comment` in the SQL code above.

This problem seems to be related to `trino-parquet` project.

Due to the fact that with the SQL script above, the issue doesn't occur each time, I'll be attaching the problematic Parquet file.
