### ISSUE TITLE
Writing Hive bucketed table sometimes fails when ZSTD compression is selected

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9775]
```
java.lang.IllegalArgumentException: No enum constant org.apache.orc.CompressionKind.ZSTD
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at org.apache.orc.CompressionKind.valueOf(CompressionKind.java:25)
	at org.apache.orc.OrcFile$WriterOptions.<init>(OrcFile.java:424)
	at org.apache.hadoop.hive.ql.io.orc.OrcFile$WriterOptions.<init>(OrcFile.java:112)
	at org.apache.hadoop.hive.ql.io.orc.OrcFile.writerOptions(OrcFile.java:317)
	at org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat.getOptions(OrcOutputFormat.java:126)
	at org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat.getHiveRecordWriter(OrcOutputFormat.java:184)
	at org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat.getHiveRecordWriter(OrcOutputFormat.java:61)
	at io.trino.plugin.hive.util.HiveWriteUtils.createRecordWriter(HiveWriteUtils.java:196)
	at io.trino.plugin.hive.util.HiveWriteUtils.createRecordWriter(HiveWriteUtils.java:176)
	at io.trino.plugin.hive.HiveMetadata.writeEmptyFile(HiveMetadata.java:1554)
	at io.trino.plugin.hive.HiveMetadata.lambda$createEmptyFiles$44(HiveMetadata.java:1543)
	at io.trino.plugin.hive.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:26)
	at io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.plugin.hive.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:25)
	at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:102)
	at io.trino.plugin.hive.HiveMetadata.createEmptyFiles(HiveMetadata.java:1541)
	at io.trino.plugin.hive.HiveMetadata.finishInsert(HiveMetadata.java:1738)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishInsert(ClassLoaderSafeConnectorMetadata.java:513)
	at io.trino.metadata.MetadataManager.finishInsert(MetadataManager.java:1015)
```

**Comment by arhimondr** [comment]
Ideally it would be great to completely avoid creating these files. However this would break compatibility with other engines. Creating a zero length file would probably require additional research to make sure it doesn't break compatibility with Hive / Spark or other engines. Thus it feels like the easiest way to proceed would be to use native ORC writer. Do you know if ZSTD is supported by other formats? (Parquet, etc.?) Or do we only care about ORC (as it is the default)?

**Comment by findepi** [comment]
> Ideally it would be great to completely avoid creating these files

See https://github.com/trinodb/trino/pull/11677#discussion_r836173642 and David's answer there.

> However this would break compatibility with other engines.

Not really. Hive on Tez doesn't create empty bucket files.

> Creating a zero length file would probably require additional research to make sure it doesn't break compatibility with Hive / Spark or other engines

Hive already does create empty files (this caused some problem for us, that's how i learned).

> Do you know if ZSTD is supported by other formats? (Parquet, etc.?) 

Parquet does support ZSTD. Idk about other file formats.

> Or do we only care about ORC (as it is the default)?

If we switch ZSTD to be the default compression, it needs to work for all file formats.
@electrum suggested offline to use different default depending on the file type. This would mean we would want ZSTD for ORC and Parquet and GZIP as a safer default for other formats.
