### ISSUE TITLE
Elasticsearch connector getting 401 errors

### ISSUE THREAD

**Issue by Gordonei** [trinodb/trino#9796]
Firstly, thanks for the awesome project!

Trino error:
```
trino> show tables from "elasticsearch"."default";

Query 20211028_054913_00006_wbntp, FAILED, 5 nodes
Splits: 70 total, 0 done (0.00%)
0.61 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20211028_054913_00006_wbntp failed: method [GET], host [http://<ES IP>:<ES Port>], URI [/_cat/indices?h=index,docs.count,docs.deleted&format=json&s=index:asc], status line [HTTP/1.1 401 Unauthorized]
{"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate user [<Trino ES username>] for REST request [/_cat/indices?h=index,docs.count,docs.deleted&format=json&s=index:asc]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"unable to authenticate user [<Trino ES username>] for REST request [/_cat/indices?h=index,docs.count,docs.deleted&format=json&s=index:asc]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}
```

ES Connector config:
```
    connector.name=elasticsearch
    elasticsearch.host=<ES IP>
    elasticsearch.port=<ES Port>
    elasticsearch.ignore-publish-address=true
    elasticsearch.default-schema-name=default
    elasticsearch.security=PASSWORD
    elasticsearch.auth.user=<trino username e.g. bob>
    elasticsearch.auth.password=<trino password e.g. alice>
    elasticsearch.tls.enabled=false
```

On the ES server side, I'm seeing the following errors:
```json
{"type": "server", "timestamp": "2021-10-28T05:45:04,983Z", "level": "WARN", "component": "o.e.x.s.a.AuthenticationService", "cluster.name": "<cluster name>", "node.name": "<node name>", "message": "Authentication to realm default_native failed - Password authentication failed for <trino username>", "cluster.uuid": "<cluster UUID>", "node.id": "<node ID>"  }
```
Which apparently means [a bad password](https://discuss.elastic.co/t/authentication-to-realm-default-native-failed-password-authentication-failed/269272).

When I recreate the query that Trino is doing via cURL:
```
curl -u <Trino username>:<Trino password> -q http://<ES IP>:<ES Port>/_cat/indices?h=index,docs.count,docs.deleted&format=json&s=index:asc
```
It works fine, so makes me suspect the Trino password is somehow getting mangled?

**Comment by findinpath** [comment]
@Gordonei I tried out your usecase with the project

https://github.com/findinpath/trino-elasticsearch7-auth

and to me it seems that the password elasticsearch security works just fine.

I was able to reproduce your problem though when I used a false password to connect from Trino to Elasticsearch7.

Can you provide more info regarding the Trino version used in your test and also the Elasticsearch version ?

**Comment by hashhar** [comment]
Does your password include whitespace, :, = or \? If so you might need to escape them in the properties file. Also are there any non-ASCII characters present?

**Comment by Gordonei** [comment]
> @Gordonei I tried out your usecase with the project
> 
> https://github.com/findinpath/trino-elasticsearch7-auth
> 
> and to me it seems that the password elasticsearch security works just fine.
> 
> I was able to reproduce your problem though when I used a false password to connect from Trino to Elasticsearch7.
> 
> Can you provide more info regarding the Trino version used in your test and also the Elasticsearch version ?

Thanks, @findinpath , appreciate the careful reproduction

Versions:
* trino - `363`
* ES - `7.10.1`

I don't have docker compose properly setup, but would you see if changing the ES password to something using non-alphanumeric characters causes issues?

> Does your password include whitespace, :, = or ? If so you might need to escape them in the properties file. Also are there any non-ASCII characters present?

@hashhar , it's a good thought - I'm deploying to k8s, and the properties is getting created via a YAML, so it's quite possible some escaping needs to be happening. 

No whitespace, `:`, `=` or non-ASCII characters, but there is a `-`. I've tried a few obvious things, like wrapping in `"`, as well as `\` the character. Anything else I should try?

**Comment by Gordonei** [comment]
OK, so it looks like @hashhar is on to something, although I don't know if escaping will help: I tried a few different password combinations, and what seems to break things is the combination of multiple numbers concatenated with `-`s. So a password of `bob-alice-2021` is fine, but *not* `bob-alice-2021-11`.

Something that might or might not be related is that when I then talk to the ES cluster, I'm getting errors on any queries against indices that have the same pattern of `-<some number>-<some number>`. I'm surprised, as this is a fairly common pattern for index naming in ES (e.g. `<my-index>-<year>-<month>`). 

The stack trace for the error that results when running `SELECT COUNT(*) from "elasticsearch"."default"."<my-index>-<year>-<month>";`:
```
java.lang.NullPointerException: undefined
	at io.trino.plugin.elasticsearch.ElasticsearchMetadata.getColumnFields(ElasticsearchMetadata.java:223)
	at io.trino.plugin.elasticsearch.ElasticsearchMetadata.makeInternalTableMetadata(ElasticsearchMetadata.java:211)
	at io.trino.plugin.elasticsearch.ElasticsearchMetadata.getTableMetadata(ElasticsearchMetadata.java:198)
	at io.trino.plugin.elasticsearch.ElasticsearchMetadata.getTableMetadata(ElasticsearchMetadata.java:193)
	at io.trino.spi.connector.ConnectorMetadata.getTableSchema(ConnectorMetadata.java:180)
	at io.trino.metadata.MetadataManager.getTableSchema(MetadataManager.java:566)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1344)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:360)
	at io.trino.sql.tree.Table.accept(Table.java:53)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3185)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1955)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:360)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:387)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1169)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:360)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:340)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:190)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:806)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
	at io.trino.$gen.Trino_363____20211107_075911_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
This might be a separate issue thought.

**Comment by ebyhr** [comment]
@Gordonei Can we close this issue now?

**Comment by Gordonei** [comment]
sure, whatever wasn't working here, was fixed by changing my password to have less `-`s in it!

Thanks for input, everyone!
