### ISSUE TITLE
TestingScyllaServer failed to start on systems having many cpu cores

### ISSUE THREAD

**Issue by sangkeon** [trinodb/trino#9842]
Unittests failed on trino-cassandra in system have many cpu cores because of Scylla DB container failed to create.

Environment: Ubuntu 20.04 LTS, AMD 5950x (16core 32thread, 128GB memory)
Related Issue: https://github.com/scylladb/scylla/issues/5638
Solution: Increase fs.aio-max-nr from 65536 to 1048576

Error message are as follows.

Scylla version 3.3.4-0.20200616.ec12331f116 with build-id cbe795af793db6b94ed25c98e177c0ab324250ed starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.5 --rpc-address 172.17.0.5 --seed-provider-parameters seeds=172.17.0.5 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.5, rpc-address: 172.17.0.5, seed-provider-parameters: seeds=172.17.0.5, blocked-reactor-notify-ms: 999999999]
ERROR 2021-11-03 08:51:17,652 [shard 2] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
2021-11-03 08:51:17,753 INFO exited: scylla (exit status 1; not expected)
2021-11-03 08:51:19,756 INFO spawned: 'scylla' with pid 514
Scylla version 3.3.4-0.20200616.ec12331f116 with build-id cbe795af793db6b94ed25c98e177c0ab324250ed starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.5 --rpc-address 172.17.0.5 --seed-provider-parameters seeds=172.17.0.5 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.5, rpc-address: 172.17.0.5, seed-provider-parameters: seeds=172.17.0.5, blocked-reactor-notify-ms: 999999999]
_**ERROR 2021-11-03 08:51:20,200 [shard 13] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application**_
2021-11-03 08:51:20,286 INFO exited: scylla (exit status 1; not expected)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/scylladb/python3/lib64/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/opt/scylladb/python3/lib64/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/python3/lib64/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 64, in get_url
    return urllib.request.urlopen(path).read().decode('utf-8')
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 1347, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 197, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 123, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 82, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 74, in get_json_from_url
    retval = result.get(timeout=5)
  File "/opt/scylladb/python3/lib64/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
2021-11-03 08:51:23,946 INFO spawned: 'scylla' with pid 833

**Comment by ebyhr** [comment]
@sangkeon Can you try this PR on your machine? #9863

**Comment by sangkeon** [comment]
Reverted  fs.aio-max-nr to 65536 and apply #9863 on my machine.

It worked.

**Comment by ebyhr** [comment]
@sangkeon Do you mean only setting SMP is insufficient on your machine?

**Comment by lamdalabs** [comment]
It's sufficient.

If I didn't rollback my fs.aio-max-nr to initial setting, It will succeed whether setting SMP or not. 
So I reverted fs.aio-max-nr to check setting SMP is sufficient.
