### ISSUE TITLE
Insert query fails with "Corrupted statistics for column ..." exception

### ISSUE THREAD

**Issue by isharamet** [trinodb/trino#9890]
After upgrading from **360** to **364** some of the insert queries are started to fail with the following exception:

```
io.trino.spi.TrinoException: Corrupted statistics for column "<REDACTED>" in Parquet file "s3://<REDACTED>". Corrupted column index: [Boudary order: UNORDERED
                      null count  min                                       max                                     
page-0                     19973  2021-09-24                                2021-10-30                              
page-1                     19980  2021-10-11                                2021-10-31                              
page-2                     19968  2021-09-13                                2021-10-30                              
page-3                     19985  2021-10-13                                2021-10-31                              
page-4                       530  <none>                                    <none>                                  
]
	at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:278)
	at io.trino.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:164)
	at io.trino.plugin.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:286)
	at io.trino.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:175)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:49)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:68)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:268)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:196)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:151)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1078)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_364____20211105_120014_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Table is in Parquet format and disabling column index usage in session properties helps:

```SQL
SET SESSION hive.parquet_use_column_index = false
```

**Comment by findepi** [comment]
cc @JamesRTaylor @martint

**Comment by ryanrupp** [comment]
Is there a `caused by` that's missing from the exception stack here? Expecting to see a wrapped `ParquetCorruptionException` which itself would then potentially have another wrapped cause depending if it failed [here](https://github.com/trinodb/trino/blob/master/lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java#L417) (no additional caused by) or [here](https://github.com/trinodb/trino/blob/master/lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java#L446) (would have the original exception)

My guess would be this is related to the handling of null pages which is where the `<none>` is coming on page 4 in the column index stats that get printed out in the exception. I haven't tried to reproduce locally yet though.

Also wanted to confirm you can/can't reproduce this by just taking the `select` part of your `insert into select` statement - i.e. this isn't tied to inserts necessarily then but in general selects?

**Comment by raunaqmorarka** [comment]
@ryanrupp The problem is indeed related to handling of null pages while constructing Domain from ColumnIndex, PTAL at https://github.com/trinodb/trino/pull/9945
