### ISSUE TITLE
Hive connector insert overwrite does not work after compaction

### ISSUE THREAD

**Issue by aakashnand** [trinodb/trino#9894]
I have encountered a bug in the hive connector. I am achieving INSERT OVERWRITE behaviour by using
`set session hive.insert_existing_partitions_behavior='OVERWRITE'` property.  
The important point to note is that INSERT OVERWRITE works until compactions are triggered. 

Following are the details on how to reproduce this issue
I am using insert overwrite to insert data as a CSV file between two different hive catalogs.

1. CREATE AN EXTERNAL TABLE in destination hive catalog

```
CREATE TABLE hive.lab_aakash_ingest.cards_ext ( 
    ->     name varchar,
    ->     dt varchar
    ->  )
    -> WITH(
    -> FORMAT='csv',
    -> partitioned_by= ARRAY['dt'],
    -> external_location='hdfs://MY-HOST/warehouse/tablespace/external/hive/cards_ext'
    -> );
```

2. CREATE INTERNAL TABLE in source hive catalog

```
CREATE TABLE prd_cdp_hive.default.fruits ( 
    ->     name varchar,dt varchar)
    -> WITH(
    -> FORMAT='ORC',
    -> transactional=true
    -> );
```

3. Insert data into the source table 

```
INSERT INTO prd_cdp_hive.default.fruits values ('a','2021-11-08'), ('b','2021-11-08'); 
INSERT INTO prd_cdp_hive.default.fruits values ('c','2021-11-08'), ('d','2021-11-08'); 
```

4. Trigger compactions from beeline
```
0: jdbc:hive2://MY-HOST:10000/def> ALTER TABLE fruits COMPACT 'minor';
INFO  : Compiling command(queryId=hive_20211108143612_9df4f45c-0a07-4c06-b43b-f282c427a1a4): ALTER TABLE fruits COMPACT 'minor'
INFO  : Semantic Analysis Completed (retrial = false)
INFO  : Created Hive schema: Schema(fieldSchemas:null, properties:null)
INFO  : Completed compiling command(queryId=hive_20211108143612_9df4f45c-0a07-4c06-b43b-f282c427a1a4); Time taken: 0.006 seconds
INFO  : Executing command(queryId=hive_20211108143612_9df4f45c-0a07-4c06-b43b-f282c427a1a4): ALTER TABLE fruits COMPACT 'minor'
INFO  : Starting task [Stage-0:DDL] in serial mode
INFO  : Compaction enqueued with id 10
INFO  : Completed executing command(queryId=hive_20211108143612_9df4f45c-0a07-4c06-b43b-f282c427a1a4); Time taken: 0.011 seconds
INFO: OK
No rows affected (0.028 seconds)
```

5. Confirm that compaction is succeeded
```
0: jdbc:hive2://MY-SECRET-HOSTNAME:10000/def> show compactions;
INFO  : Compiling command(queryId=hive_20211108143922_93ee5393-fc56-4af7-8030-ee35526337b2): show compactions
INFO  : Semantic Analysis Completed (retrial = false)
INFO  : Created Hive schema: Schema(fieldSchemas:[FieldSchema(name:compactionid, type:string, comment:from deserializer), FieldSchema(name:dbname, type:string, comment:from deserializer), FieldSchema(name:tabname, type:string, comment:from deserializer), FieldSchema(name:partname, type:string, comment:from deserializer), FieldSchema(name:type, type:string, comment:from deserializer), FieldSchema(name:state, type:string, comment:from deserializer), FieldSchema(name:hostname, type:string, comment:from deserializer), FieldSchema(name:workerid, type:string, comment:from deserializer), FieldSchema(name:starttime, type:string, comment:from deserializer), FieldSchema(name:duration, type:string, comment:from deserializer), FieldSchema(name:hadoopjobid, type:string, comment:from deserializer), FieldSchema(name:errormessage, type:string, comment:from deserializer)], properties:null)
INFO  : Completed compiling command(queryId=hive_20211108143922_93ee5393-fc56-4af7-8030-ee35526337b2); Time taken: 0.004 seconds
INFO  : Executing command(queryId=hive_20211108143922_93ee5393-fc56-4af7-8030-ee35526337b2): show compactions
INFO  : Starting task [Stage-0:DDL] in serial mode
INFO  : Completed executing command(queryId=hive_20211108143922_93ee5393-fc56-4af7-8030-ee35526337b2); Time taken: 0.012 seconds
INFO  : OK
+---------------+-----------+----------+------------+--------+------------+-------------------------+----------------+---------------+-------------------------+----------------+---------------+
| compactionid  |  dbname   | tabname  |  partname  |  type  |   state    |        hostname         |    workerid    |   starttime   |        duration         |  hadoopjobid   | errormessage  |
+---------------+-----------+----------+------------+--------+------------+-------------------------+----------------+---------------+-------------------------+----------------+---------------+
| CompactionId  | Database  | Table    | Partition  | Type   | State      | Worker                  | Start Time     | Duration(ms)  | HadoopJobId             | Error message  | NULL          |
| 9             | default   | fruits   |  ---       | MINOR  | succeeded  | MY-SECRET-HOSTNAME      | 1636349744441  | 30            | None                    |  ---           | NULL          |
| 10            | default   | fruits   |  ---       | MINOR  | succeeded  |  ---                    | 1636349773769  | 22090         | job_1636007785812_0011  |  ---           | NULL          |
+---------------+-----------+----------+------------+--------+------------+-------------------------+----------------+---------------+-------------------------+----------------+---------------+
3 rows selected (0.041 seconds)
0: jdbc:hive2://MY-SECRET-HOSTNAME:10000/def>
```

6. Insert data into the external table using insert overwrite

```
trino> set session hive.insert_existing_partitions_behavior='OVERWRITE';
SET SESSION
trino> INSERT INTO hive.lab_aakash_ingest.cards_ext SELECT * from prd_cdp_hive.default.fruits;

Query 20211108_054419_00021_kbf8p, FAILED, 4 nodes
https://trino-stg.d4b.jp/ui/query.html?20211108_054419_00021_kbf8p
Splits: 68 total, 0 done (0.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 37% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
Peak Memory: 0B
0.53 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20211108_054419_00021_kbf8p failed: For input string: "v0000370"
io.trino.spi.TrinoException: For input string: "v0000370"
	at io.trino.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:279)
	at io.trino.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
	at io.trino.$gen.Trino_364____20211108_051210_2.run(Unknown Source)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NumberFormatException: For input string: "v0000370"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.apache.hadoop.hive.ql.io.AcidUtils.parsedDelta(AcidUtils.java:915)
	at org.apache.hadoop.hive.ql.io.AcidUtils.parseDelta(AcidUtils.java:892)
	at org.apache.hadoop.hive.ql.io.AcidUtils.getChildState(AcidUtils.java:1185)
	at org.apache.hadoop.hive.ql.io.AcidUtils.getAcidState(AcidUtils.java:1019)
	at org.apache.hadoop.hive.ql.io.AcidUtils.getAcidState(AcidUtils.java:978)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.lambda$loadPartition$5(BackgroundHiveSplitLoader.java:499)
	at io.trino.plugin.hive.authentication.UserGroupInformationUtils.lambda$executeActionInDoAs$0(UserGroupInformationUtils.java:29)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1710)
	at io.trino.plugin.hive.authentication.UserGroupInformationUtils.executeActionInDoAs(UserGroupInformationUtils.java:27)
	at io.trino.plugin.hive.authentication.DirectHdfsAuthentication.doAs(DirectHdfsAuthentication.java:39)
	at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:97)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:499)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:348)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:272)
	... 6 more

trino>

```

**Comment by aakashnand** [comment]
Just in case I confirmed the describe command output before and after Compaction/


### Before
```
trino> describe prd_cdp_hive.default.fruits;
 Column |  Type   | Extra | Comment 
--------+---------+-------+---------
 name   | varchar |       |         
 dt     | varchar |       |         
(2 rows)

Query 20211108_131416_00044_kbf8p, FINISHED, 4 nodes
https://MY-HOST/ui/query.html?20211108_131416_00044_kbf8p
Splits: 53 total, 53 done (100.00%)
CPU Time: 0.2s total,    11 rows/s,   693B/s, 18% active
Per Node: 0.1 parallelism,     1 rows/s,    64B/s
Parallelism: 0.4
Peak Memory: 0B
0.48 [2 rows, 124B] [4 rows/s, 257B/s]
```


### After
```
trino> describe prd_cdp_hive.default.fruits;
 Column |  Type   | Extra | Comment 
--------+---------+-------+---------
 name   | varchar |       |         
 dt     | varchar |       |         
(2 rows)

Query 20211108_131514_00045_kbf8p, FINISHED, 4 nodes
https://MY-HOST/ui/query.html?20211108_131514_00045_kbf8p
Splits: 53 total, 53 done (100.00%)
CPU Time: 0.1s total,    27 rows/s, 1.66KB/s, 14% active
Per Node: 0.0 parallelism,     1 rows/s,    77B/s
Parallelism: 0.2
Peak Memory: 0B
0.40 [2 rows, 124B] [4 rows/s, 308B/s]
```

**Comment by martint** [comment]
cc @findepi, any thoughts?

**Comment by aakashnand** [comment]
On further investigation, I have found following things

1. In hive4.0.0 the compactions are executed using transactions. Therefore new transaction_id is getting appended to base file 

- Base file after compaction in case of hive3.1.2 : `base_0000003`
- Base file after compaction in case of hive4.0.0 : `base_0000003_v0006076` 

because of this new file name of base file after compaction, hive connector from trino is throwing `java.lang.NumberFormatException: For input string: "v0000370"` for that appended string `v0000370`

Check this hive JIRA for more details: https://issues.apache.org/jira/browse/HIVE-20823

I know the cause of this problem, but I don't know how to solve this?

Of course the best option is to make trino compatible with hive4 and upgrade the dependency of trino hive from 3.1.2 to latest version. Any other thoughts? @findepi

**Comment by akshat0395** [comment]
As you mentioned @aakashnand, With hive compaction running in transactions, the naming conventions of the files has also changed. 
This required corresponding changes in the splitLoader files as well(BackgroundHiveSplitLoader), to be able to read the file and parse individual changes with transaction ids. 
It would be great if Trino can upgrade the plugin to support this.

**Comment by aakashnand** [comment]
@akshat0395 were you able to fix this? Or if you have PR that would be helpful. We have temporarily disabled the automatic compaction on hive side for this

**Comment by akshat0395** [comment]
@aakashnand Did you try performing compaction via beeline or Hive side?

**Comment by aakashnand** [comment]
@akshat0395 I tried compaction using the beeline command

`0: jdbc:hive2://MY-HOST:10000/def> ALTER TABLE fruits COMPACT 'minor';`

**Comment by akshat0395** [comment]
Did that run successfully ? @aakashnand Or did you face any issues?

**Comment by aakashnand** [comment]
@akshat0395 Compactions runs successfully it is a trino query that is failing. I have attached the logs in the description of this issue. 
Is it working for you? Can you share some more insights such as terminal logs or steps to reproduce?

**Comment by akshat0395** [comment]
@aakashnand As I mentioned in my previous comment this wont work without a code change to support the new naming convention on the trino side.
I'm trying to reach out to the the team via their community slack, waiting for a response and a fix for this issue.

@findepi can you please share any insights on this one?
