### ISSUE TITLE
Iceberg is getting NullPointerException when joining two sub selects

### ISSUE THREAD

**Issue by Sartan4455** [trinodb/trino#9937]
Version: 364 
hive/iceberg
orc file hdfs

doing 2 subqueries, then joining on them.  Both the sub queries complete just fine alone.  And we can retrieve data IF we don't join the two temp tables it's fine, but it we doing any sort of conditional we get an error.
q1:
`select session_id from sessions where appliance_id='bcmid6f0fd6d8f3d6a3' and import_id=13`
q2:
`select session_id from artifacts where  appliance_id='bcmid6f0fd6d8f3d6a3' and session_id >= 7768253748 and session_id <= 7768256094`
Full query:
```
with ses as 
( select session_id from sessions where appliance_id='bcmid6f0fd6d8f3d6a3' and import_id=13),
art as 
(select session_id from artifacts where  appliance_id='bcmid6f0fd6d8f3d6a3' and session_id >= 7768253748 and session_id <= 7768256094)
select art.session_id, ses.session_id  from ses, art where art.session_id = ses.session_id;
```
```
       java.lang.NullPointerException: undefined
	at io.trino.plugin.iceberg.IcebergSplitSource.fileMatchesPredicate(IcebergSplitSource.java:219)
	at io.trino.plugin.iceberg.IcebergSplitSource.getNextBatch(IcebergSplitSource.java:161)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorSplitSource.getNextBatch(ClassLoaderSafeConnectorSplitSource.java:45)
	at io.trino.split.ConnectorAwareSplitSource.getNextBatch(ConnectorAwareSplitSource.java:55)
	at io.trino.split.BufferingSplitSource$GetNextBatch.fetchSplits(BufferingSplitSource.java:113)
	at io.trino.split.BufferingSplitSource$GetNextBatch.fetchNextBatchAsync(BufferingSplitSource.java:94)
	at io.trino.split.BufferingSplitSource.getNextBatch(BufferingSplitSource.java:54)
	at io.trino.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:267)
	at io.trino.execution.scheduler.SourcePartitionedScheduler$1.schedule(SourcePartitionedScheduler.java:176)
	at io.trino.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:558)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I attempted a smaller test, which had no issues. See attached file.
config file looks like this:
coordinator=true                                                                              
node-scheduler.include-coordinator=true                                                       
node-scheduler.network-topology=flat                                                          
http-server.http.port=5578                                                                    
query.max-memory=256GB                                                                        
query.max-memory-per-node=128GB                                                               
query.max-total-memory-per-node=128GB                                                         
discovery-server.enabled=true                                                                 
discovery.uri=hxxp..... 

Rolling back to 363 fixed the issue.

Also noted in slack 
https://trinodb.slack.com/archives/CJ6UC075E/p1636584192040200

**Comment by Sartan4455** [comment]
[small_test.sql.txt](https://github.com/trinodb/trino/files/7516584/small_test.sql.txt)

**Comment by phd3** [comment]
cc @alexjo2144 @raunaqmorarka
