### ISSUE TITLE
Concat CHAR with more than 2 arguments throws exception

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#9988]
If we change to `||` operator, it works well because it's evaluated as `concat(concat(...))` internally.

```bash
trino> SELECT concat(CAST('a' AS char(1)), CAST('b' AS char(1)), CAST('cd' AS char(2)));
Query 20211118_050011_00030_sik2y failed: line 1:8: Unexpected parameters (char(1), char(1), char(2)) for function concat. Expected: concat(char(x), char(y)) , concat(array(E), E) E, concat(E, array(E)) E, concat(array(E)) E, concat(varchar) , concat(varbinary)
io.trino.spi.TrinoException: line 1:8: Unexpected parameters (char(1), char(1), char(2)) for function concat. Expected: concat(char(x), char(y)) , concat(array(E), E) E, concat(E, array(E)) E, concat(array(E)) E, concat(varchar) , concat(varbinary)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:1150)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:486)
	at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
	at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:509)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:405)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:2592)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:3485)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelectSingleColumn(StatementAnalyzer.java:3299)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:3121)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2113)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:375)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:392)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:400)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1324)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:375)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:392)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:355)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:92)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:84)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:274)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:193)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:817)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
	at io.trino.$gen.Trino_testversion____20211118_044953_3.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.trino.spi.TrinoException: Unexpected parameters (char(1), char(1), char(2)) for function concat. Expected: concat(char(x), char(y)) , concat(array(E), E) E, concat(E, array(E)) E, concat(array(E)) E, concat(varchar) , concat(varbinary)
	at io.trino.metadata.FunctionResolver.resolveFunction(FunctionResolver.java:152)
	at io.trino.metadata.MetadataManager.lambda$resolvedFunctionInternal$43(MetadataManager.java:2479)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at io.trino.metadata.MetadataManager.resolvedFunctionInternal(MetadataManager.java:2479)
	at io.trino.metadata.MetadataManager.resolveFunction(MetadataManager.java:2447)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:1138)
	... 34 more
SELECT concat(CAST('a' AS char(1)), CAST('b' AS char(1)), CAST('cd' AS char(2)))
```

Labeled `bug`, but it's kind of `enhancement`.

**Comment by findepi** [comment]
Let me copy my comment from a PR https://github.com/trinodb/trino/pull/10098#discussion_r759042882 since it's more suited here.

`'a'` is of type `varchar(1)`

`varchar(1) || varchar(1) -> varchar` -- this is OK and yes, we could do better, i.e. know the type is `varchar(2)`. We should be able to do this in some more reasonable manner than loading a ton of overloads of a function into the system. If we need better type resolution for function results, this is what we should do. 

`varchar || char(1) -> char(65537)` -- this fails (char limit overflow). Your PR doesn't fix that, does it?
This should produce `varchar` instead.

BTW it's not only about type resolution of the results. There is a problem what is the actual value when concatenating varchar and char. -- https://github.com/trinodb/trino/issues/10118

**Comment by findepi** [comment]
Solved by
- https://github.com/trinodb/trino/pull/29939
